# Bản dịch da — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code da --name "…" scripts/ban-dich/da.py
VALS = [
    'Arkiverede versioner…',
    'Dette dokument er aldrig blevet arkiveret — ingen historik',
    'Ingen tidligere arkiverede versioner',
    'Den version kan ikke læses',
    'Gendan den arkiverede version',
    'XML: valider mod DTD/XSD…',
    'Denne Mac har ikke libxml2, så XSD-validering er ikke tilgængelig.',
    'Vælg et XSD-skema at validere mod',
    'Gyldig efter',
    'Pluginet sluttede uden at ændre noget',
    'Der er ikke installeret nogen indbyggede plugins',
    'Fjern dette plugin',
    'Fjern dette plugin?',
    'Fjern',
    'Installer et indbygget plugin…',
    'Åbn pluginmappen',
    'Vælg pluginets .dylib-fil',
    'Installeret:',
    'Fjernet:',
    'Indbyggede plugins…',
    'Kun .dylib-arkiver accepteres.',
    'Et plugin med samme navn er allerede installeret:',
    'Pluginet kan ikke kopieres:',
    'Indbyggede plugins findes kun i den direkte hentning, ikke i App Store-versionen.',
    'Hjælpeprocessen til plugins blev ikke fundet.',
    'Hjælpeprocessen kan ikke startes:',
    'Pluginets proces stoppede halvvejs.',
    'Pluginet svarede ikke i tide — det blev stoppet.',
    'Pluginet svarede med en forkert udformet besked:',
    'Pluginet meldte en fejl:',
    'Om GEditor',
    'Indstillinger…',
    'Slut GEditor',
    'Arkiv',
    'Nyt faneblad',
    'Luk fanebladet',
    'Næste faneblad',
    'Forrige faneblad',
    'Nyt dokument',
    'Åbn…',
    'Åbn en mappe som arbejdsområde…',
    'Åbn seneste',
    'Arkiver',
    'Arkiver som…',
    'Fjern mellemrum i slutningen af linjen ved arkivering',
    'Følg arkivet (tail -f)',
    'Udskriv…',
    'Åbn det lukkede faneblad igen',
    'Ingen arkiver',
    'Ryd listen',
    'Rediger',
    'Fortryd',
    'Gentag',
    'Klip',
    'Kopier',
    'Sæt ind',
    'Historik for udklipsholderen…',
    'Kolonneediteringsværktøj…',
    'Vælg næste træf',
    'Vælg alt',
    'Dupliker linjen',
    'Slet linjen',
    'Udkommenter linjen',
    'Der er ikke kopieret noget i denne session',
    'Ryd historikken',
    'Søg',
    'Find…',
    'Find og erstat…',
    'Søg i en mappe…',
    'Erstat i en mappe…',
    'Næste resultat',
    'Forrige resultat',
    'Gå til linje…',
    'Gå til den tilsvarende parentes',
    'Marker alle matchende linjer…',
    'Vend markeringerne om',
    'Fjern alle markeringer',
    'Kopier de markerede linjer',
    'Slet de markerede linjer',
    'Behold kun de markerede linjer',
    'Linjer',
    'Sorter A→Å',
    'Sorter Å→A',
    'Naturlig sortering',
    'Fjern dubletter',
    'Vend linjernes rækkefølge',
    'Flyt linjen op',
    'Flyt linjen ned',
    'Sammenføj linjer',
    'Del linjer efter længde…',
    'Del linjer efter tegn…',
    'Slet tomme linjer',
    'Slå sammenhængende tomme linjer sammen',
    'Fjern mellemrum i slutningen af linjen',
    'Tabulator → mellemrum',
    'Mellemrum → tabulator',
    'STORE BOGSTAVER',
    'små bogstaver',
    'Stort Begyndelsesbogstav I Hvert Ord',
    'Stort begyndelsesbogstav i sætningen',
    'vEND sTORE/sMÅ',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: vælg ark…',
    'Skift mellem tabel- og tekstvisning',
    'Slet kolonne…',
    'Valider data (antal kolonner · typer)',
    'Arbejdsbord til datarensning…',
    'Kør en renseopskrift…',
    'Konverter…',
    'Skift adskiller…',
    'Eksporter til JSON…',
    'Format',
    'Tegnkodning…',
    'Linjeafslutninger…',
    'Normaliser Unicode…',
    'JSON: formater',
    'JSON: pres sammen til én linje',
    'JSON: sorter nøgler',
    'JSON: JSONPath-forespørgsel…',
    'CSV: SQL-forespørgsel…',
    'SQL-forespørgsel',
    'Kører…',
    'Eksporter til et nyt faneblad',
    'Tomt dokument — ingen tabel at forespørge',
    'Ikke en CSV-tabel — første linje har kun én kolonne',
    'Forespørgslen kan ikke læses',
    'Forespørgslen kan ikke kontrolleres',
    'Gul (standard)',
    'Blå',
    'Grøn',
    'Okker',
    'Lilla',
    'Lyserød',
    'Turkis',
    'Orange',
    'Skifer',
    'Tekst',
    'Talrække',
    'Datorække',
    'STORE BOGSTAVER (hexadecimalt)',
    'Begyndelse',
    'Trin',
    'Udfyld med nuller op til',
    'Grundtal',
    'Første dato',
    'Format',
    'Indsæt',
    'Annuller',
    'Konverter formatet',
    'Se de første 5 rækker',
    'Åbn i et nyt faneblad',
    'Arkiver i et arkiv…',
    'Resultatet åbnes i et nyt, ikke-arkiveret faneblad. Det oprindelige dokument røres ikke.',
    'Kør på dette dokument',
    'Kør på en mappe…',
    'Hele opskriften er ÉT fortryd-trin. Arkivet på disken røres ikke, før du arkiverer.',
    'fra',
    'kolonnen blev ikke fundet',
    'klar',
    'den optager fortsat en processorkerne, indtil appen sluttes.',
    'Scriptet returnerede ingenting',
    'JavaScript-motoren kan ikke oprettes',
    'Ukendt JavaScript-fejl',
    'Tabel',
    'Anvend sorteringen på arkivet',
    'Konverter ▾',
    'Eksporter de matchende rækker',
    'Skjul denne kolonne',
    'Omdøb overskriften…',
    'Indsæt en tom kolonne til venstre',
    'Indsæt en tom kolonne til højre',
    'Slet denne kolonne fra arkivet…',
    'Mindst én kolonne skal forblive synlig',
    'Sorterer…',
    'Tilbage til rækkefølgen i arkivet',
    'de første hundrede rækker',
    'vælge kolonner',
    'navngive en resultatkolonne',
    'filtrere på tekst',
    'tomme felter',
    'kombinere betingelser',
    'tælle rækker',
    'gruppere og opsummere',
    'minimum, maksimum',
    'sortere og begrænse',
    'kolonnenavn med mellemrum',
    'Forespørgslen blev afbrudt',
    'Ikke understøttet: JOIN · underforespørgsel · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · vinduesfunktioner',
    'XML: formater',
    'XML: pres sammen til én linje',
    'XML: kontroller syntaksen',
    'YAML: kontroller gentagne nøgler og indrykning',
    'Vis',
    'Vis/skjul sidepanelet (funktionslisten)',
    'Vis/skjul dokumentkortet',
    'Fold blokken ved markøren sammen / ud',
    'Fold alt sammen',
    'Fold alt ud',
    'Fold sammen efter niveau',
    'Niveau %d',
    '%1$d {one=blok foldet|other=blokke foldet} sammen på niveau %2$d',
    'Dette dokument er kun %d {one=niveau|other=niveauer} dybt',
    'mermaid: manifestet kan ikke læses',
    'Søg efter opdateringer…',
    'Søg efter opdateringer',
    'App Store-versioner opdateres via Mac App Store, ikke via GEditor.',
    'Denne udgave har ingen signeringsnøgle til opdateringer og kan derfor ikke søge efter dem.',
    'Forstør teksten',
    'Formindsk teksten',
    'Faktisk størrelse',
    'Del lodret',
    'Del vandret',
    'Luk delingen',
    'Åbn dette faneblad i den anden rude',
    'Gå til den anden rude',
    'Linjeombrydning (fra / vindue / kolonne)',
    'Ombryd ved kolonne…',
    'Marker denne linje',
    'Næste markering',
    'Forrige markering',
    'Markeringernes farve…',
    'Vis alle usynlige tegn',
    '  Mellemrum',
    '  Tabulatorer',
    '  Linjeafslutninger',
    '  NBSP · nulbredde · styretegn',
    'Binær visning',
    'CSV-tilstand (kolonner i farver)',
    'Makro',
    'Start / stop optagelsen',
    'Afspil',
    'Afspil flere gange…',
    'Afspil til dokumentets slutning',
    'Kør på alle faneblade',
    'Annuller den kørende makro',
    'Arkiver makroen…',
    'Arkiverede makroer…',
    'Hjælp',
    'GEditor-hjælp',
    'Funktionsoversigt',
    'Skift fra Notepad++',
    'Find',
    'Erstat med',
    'Næste',
    'Forrige',
    'Tæl',
    'Luk',
    'Valider mod et JSON-skema…',
    'Vælg et JSON-skemaarkiv',
    'Der blev ikke fundet problemer efter dette skema.',
    'JSON-skema',
    'Kontroller grafens syntaks',
    'Grafformatet blev ikke genkendt — der kræves endelsen .dot, .gv, .cypher, .ttl eller .graphml.',
    'Der blev ikke fundet %@-syntaksfejl (kontrollen er ikke udtømmende).',
    '%@-syntaks',
    'er ikke et JSON-objekt',
    'Tekstudvinding (n-gram, TF-IDF)',
    'Dokumentet er tomt.',
    'Der kunne ikke udtrækkes et eneste nøgleord.',
    'Nøgleord',
    '%d {one=nøgleord|other=nøgleord} · %d {one=token|other=tokens} · %d {one=dokument|other=dokumenter}',
    'Marker i dokumentet',
    'Marker entiteter fra en liste…',
    'Vælg en entitetsliste (CSV eller JSON)',
    'Entitetslisten kan ikke læses.',
    'Entitetslisten er tom.',
    'Der blev ikke fundet entiteter i dokumentet (%d indlæst).',
    '%d {one=forekomst|other=forekomster} · %@',
    'Konverter viden…',
    'Konvertering: %@ → %@',
    'Det kunne ikke konverteres.',
    'Forhåndsvisning af opdelingen…',
    'Fast størrelse 800 B, overlap 100 B',
    'Efter sætning (≤ 800 B)',
    'Efter Markdown-overskrift',
    'Tomt dokument — ingen stykker.',
    '%d {one=stykke|other=stykker} · i gennemsnit %d B · %@',
    'Eksporter JSONL',
    'Stykkernes JSONL',
    'Åbn tripler/kanter som tabel',
    'Tripeltabel',
    'Dette dokument har ingen tripellinje.',
    'Der kunne ikke læses en eneste tripel — linje %d: %@',
    '%1$d {one=tripel læst|other=tripler læst} · %2$d {one=fejlbehæftet linje|other=fejlbehæftede linjer} sprunget over (den første: linje %3$d)',
    'Uskarpe dubletter efter kolonne…',
    'Uskarpe dubletter — kolonnen «%1$@»: %2$d {one=kandidatgruppe|other=kandidatgrupper}',
    'Flet',
    'Match',
    'Værdier i gruppen',
    'Flet til',
    'Flet de valgte grupper',
    'Der er ikke valgt nogen gruppe — at trykke på «Flet» ændrer INTET. Appen fletter aldrig af sig selv.',
    '%d {one=gruppe valgt|other=grupper valgt} · %d {one=række ændres|other=rækker ændres} · ÉT fortryd-trin',
    'Denne kolonne kunne ikke gennemsøges.',
    'Kolonnen «%@» har ingen grupper med uskarpe dubletter.',
    'Ingen gruppe blev flettet — dokumentet er uændret.',
    'Uskarp dubletfjernelse · kolonnen %@',
    '%d {one=gruppe flettet|other=grupper flettet} · %d {one=felt ændret|other=felter ændret}',
    'Rapport om rensning',
    '# Rapport om rensning — %@\n\n',
    '## Anvendt (%d)\n\n',
    '_Der er ikke anvendt et eneste trin._\n',
    '\n## Dataprofil\n\n',
    '_%1$d {one=kolonne|other=kolonner} · %2$d {one=række|other=rækker} · gennemsøgt på %3$.1f s_\n\n',
    '| Kolonne | Type | Tomme | Unikke | Min | Maks | Middel |\n',
    '\n### Afvigende værdier\n\n',
    'række %d: %@',
    '- kolonnen «%1$@» — %2$d {one=felt|other=felter}: %3$@\n',
    '\n## Tilbage (%d)\n\n',
    '_Der er ikke flere observationer._\n',
    '- kolonnen «%@»: %@\n',
    None,
    'Fjern mellemrum ved arkivering',
    'Normaliser linjeafslutningerne',
    'forrige',
    'Mappen «%@» fra den forrige session kunne ikke åbnes igen',
    ' (og %d {one=arkiv|other=arkiver} mere)',
    '%d {one=faneblad kunne|other=faneblade kunne} ikke åbnes igen: %@%@ — arkiverne ligger ikke længere samme sted.',
    'Inddata fra røret kunne ikke læses',
    'Mellemrum i slutningen af linjen fjernes ved hver arkivering',
    'Mellemrum fjernes ikke længere ved arkivering',
    'Uden navn.txt',
    'At konvertere tegnkodningen får tegn til at gå tabt',
    'Arkiver alligevel',
    'Dokumentet har ikke-arkiverede ændringer',
    'At lukke uden at arkivere kasserer dem.',
    'Kasser ændringerne',
    'Gå til linje',
    'Dokumentet har %d {one=linje|other=linjer}.',
    'Linjenummer',
    'Gå',
    'Fortolk igen som…',
    'Konverter til…',
    'Det kunne ikke fortolkes igen',
    '%@ kan ikke gengive alle tegn',
    'Vælg alligevel',
    'Kolonne %d',
    'Kolonne %d: %@',
    'Skjulte kolonner: %@ (%d) — hent dem tilbage fra kontekstmenuen på overskriftsrækken',
    'Vis igen: %@',
    'Kolonnen %@ er skjult — den ligger urørt i arkivet',
    'Sorteret efter %@ %@ · kun visning',
    'Sorteret: %@ %@ (kun visning)',
    '%d+ rækker matcher — søger videre…',
    '%d / %d {one=række matcher|other=rækker matcher}',
    'Der blev ikke fundet problemer i %d {one=række|other=rækker}',
    '%d {one=række|other=rækker} med forkert antal kolonner',
    '%d {one=felt|other=felter} med forkert datatype',
    ' (stoppede ved de %d {one=første problem|other=første problemer})',
    '   —   genkendte typer: ',
    'Række %1$d, kolonnen %2$@: «%3$@» er ikke %4$@',
    'Kolonneediteringsværktøj — %d {one=linje|other=linjer}',
    'Observationer',
    'Dataprofil',
    'Dataprofil — gennemsøger…',
    'Arkiver opskriften…',
    'Eksporter rapporten',
    'Der er ikke anvendt nogen gruppe · hver gruppe er ét fortryd-trin',
    'for mange værdier',
    'hyppigst: ',
    'Værdi til at udfylde tomme felter med',
    'Anvend',
    'Der kunne ikke opbygges en forhåndsvisning',
    '· efterladt som det er, kan ikke tydes ·',
    'Konverter kolonnen til ISO 8601 (ÅÅÅÅ-MM-DD)',
    'Talkonvention for hele kolonnen',
    'Hvad der skal ske med tomme felter',
    'Normaliser til ISO 8601',
    'Læs tvetydige felter med DAGEN først (31/12)',
    'Læs tvetydige felter med MÅNEDEN først (12/31)',
    'Spring tvetydige felter over, ret kun de sikre',
    'Til vietnamesisk/europæisk (1.234,56)',
    'Til angloamerikansk (1,234.56)',
    'Til angloamerikansk, uden tusindtalsadskiller (1234.56)',
    'Udfyld med en standardværdi…',
    'Udfyld nedad — tag værdien ovenover',
    'Udfyld opad — tag værdien nedenunder',
    'Slet rækker med tomt felt i denne kolonne',
    'Fjern mellemrum i begge ender',
    'Fjern i begge ender og pres mellemrum indeni sammen',
    'Pivottabel…',
    'Kilder…',
    'Pivottabel — grupper efter kolonne',
    'Rækker (gruppering)',
    'Værdier',
    '+ Række',
    '+ Værdi',
    'Ryd alt',
    'Læg i forespørgselsfeltet',
    'Vælg kolonner for at opbygge forespørgslen.',
    'Kolonnenavnene i denne tabel kunne ikke læses.',
    'Forespørgslens datakilder',
    '«%@» — det åbne dokument',
    '  ⚠️ arkivet er ændret, siden det blev registreret',
    'Tilføj arkiv…',
    'Fjern alle',
    'Der kunne ikke udledes et tabelnavn af «%@» — omdøb arkivet.',
    'Sum',
    'Gennemsnit',
    'Min',
    'Maks',
    'Antal unikke',
    'Diagram',
    'Eksporter PNG',
    'Eksporter SVG',
    'Denne tabel har ingen numerisk kolonne at tegne.',
    'PNG-billedet kunne ikke opbygges.',
    'Forespørgselsresultat',
    '%@ arkiveret',
    '%1$@-diagram for «%2$@» — %3$d {one=punkt|other=punkter}, værdier fra %4$@ til %5$@',
    'Søjle',
    'Linje',
    'Histogram',
    'Punkt',
    'Boks',
    'CSV: datakvalitet…',
    'Datakvalitet',
    'Eksporter overtrædelserne til et nyt faneblad',
    'Niveau',
    'Regel',
    'Overtrædelser',
    'Andel',
    'bestået',
    'fejl',
    'advarsel',
    'ødelagt',
    '%d {one=overtrædende linje markeret|other=overtrædende linjer markeret}',
    'Udvikling',
    'Bedømt',
    'Rækker',
    'Forskel',
    'Ikke-beståede regler',
    'Kvalitetsscore',
    'Score over tid',
    'Der er endnu ingen historik — hver bedømmelse føjer ',
    'én linje til arkivet «.history.jsonl» ved siden af reglerne.',
    '%d {one=punkt|other=punkter} i historikken',
    ' · %d {one=linje KAN IKKE LÆSES|other=linjer KAN IKKE LÆSES}',
    ' · vælg to rækker at sammenligne',
    'score %+.1f',
    'ingen dimension faldt',
    'faldt: ',
    '%d {one=nyligt ikke-bestået regel|other=nyligt ikke-beståede regler}: %@',
    'rækker %+d',
    ' (og %d {one=advarsel|other=advarsler} mere på fanebladet Udvikling)',
    'Ingen automatisk rettelse: ',
    'Åbner det rette værktøj på rensearbejdsbordet og bedømmer så straks igen.',
    'Håndter manglende værdier…',
    'Normaliser datoer…',
    'Fjern dubletter…',
    'Erstat…',
    'Vis de forkerte rækker',
    'Kolonnen «%@» findes ikke i denne tabel.',
    'Dubletterne er fjernet — «%@» er nu unik. Score: %.0f/100',
    'Dubletterne er fjernet, men «%1$@» har stadig %2$d {one=gentaget række|other=gentagne rækker} (før: %3$d) — ',
    'de rækker deler NØGLE men ikke hele rækken, så du må se efter og vælge ',
    'hvilken du beholder.',
    'Der kunne ikke læses en eneste værdi, der overtræder denne regel.',
    '%1$d {one=forkert værdi|other=forkerte værdier} i kolonnen «%2$@» — udfyld Erstat og tryk på Forhåndsvis',
    'Bedømt igen: %.0f/100',
    'Forhåndsvisning af rapporten',
    'Parametre…',
    'Eksporter HTML…',
    'Udskriv / PDF…',
    '%d {one=blok kørt|other=blokke kørt} · %d {one=blok MISLYKKEDES|other=blokke MISLYKKEDES}',
    '%d {one=blok kørt|other=blokke kørt}',
    ' · FORÆLDEDE DATA — kildearkivet er ændret; byg igen',
    'Rapportforhåndsvisning kræver et .%@-dokument',
    'Der blev ikke fundet en datakilde — erklær «source: arkiv.csv» i frontmatter.',
    'Rapporten kunne ikke opbygges.',
    'Denne rapport erklærer ingen parametre i frontmatter.',
    'Rapportens parametre',
    'Byg igen',
    '%@ eksporteret',
    'Rapport: forhåndsvisning',
    'Rapport: batch-generering…',
    'er ikke et .greport.md-dokument',
    'rapporten kunne ikke tolkes',
    'kildedata kunne ikke findes',
    'parameterlisten kunne ikke læses',
    'Batch-generering kræver et .%@-dokument',
    'Vælg en parameterliste (CSV eller JSON)',
    'Vælg en mappe til %d {one=rapport|other=rapporter}',
    '[%d/%d] %@',
    'manglende parametre ',
    'peger på selve kildearkivet — nægter at overskrive',
    '%d {one=blok MISLYKKEDES|other=blokke MISLYKKEDES}',
    'Batchen er færdig: %d {one=arkiv|other=arkiver} · %d mislykkedes',
    '%d {one=parametersæt|other=parametersæt} kunne ikke opbygges — se opsummeringen',
    'Mermaid-diagram: forhåndsvisning',
    'Mermaid-diagram: indsæt skabelon…',
    'Mermaid-diagram: formater igen',
    'Gennemsigtig baggrund',
    'Denne Mac kan ikke omdanne diagrammet til PNG — macOS 13 kræves. SVG-eksport virker stadig.',
    'Arkiver PNG %@…',
    'Arkiver SVG…',
    'Kopier billedet til udklipsholderen',
    'Mærkefarver…',
    'Mærkefarver til diagrammer',
    'Hvert felt er en farve af typen #rrggbb. Arkiveres i «themes/mermaid-brand.json» — kan kopieres til en anden Mac.',
    'Hovedfarve',
    'Tekst på knuder',
    'Ramme',
    'Forbindelser',
    'Baggrund ved eksport',
    'Arkiver og indsæt %%{init}%% i dokumentet',
    'Mærkefarverne er arkiveret',
    'Diagrambilledet er kopieret til udklipsholderen',
    '%@ arkiveret — %@',
    'Dette diagram har allerede et %%{init}%%-direktiv — dit lades urørt.',
    '%%{init}%% indsat — diagrammet bærer nu sine egne farver',
    'Indsæt mærkefarverne i diagrammet',
    'Formater Mermaid-diagrammet igen',
    'Diagramkilden er allerede ryddelig — der er intet at ændre',
    'Diagrammet er formateret igen',
    '%d {one=diagram formateret|other=diagrammer formateret} igen',
    'Bibliotek med diagramskabeloner',
    'Fuldstændige diagramskabeloner',
    'Syntaksstumper',
    'Redigeres: %@',
    'Skabelonen «%@» er indsat',
    'Dette dokument er skrivebeskyttet.',
    'Mermaid-diagram',
    'Dette dokument har ingen mermaid-blok.',
    'Mærke',
    'Eksporter…',
    'Endnu ingen diagrammer',
    '%d {one=diagram|other=diagrammer} · %@',
    '%1$d/%2$d {one=diagram MISLYKKEDES|other=diagrammer MISLYKKEDES} — diagram %3$d%4$@',
    ', linje %d',
    'Dette dokument har ingen ```mermaid-blok og er heller ikke et .mmd-arkiv.',
    'Intet diagram er tegnet færdigt endnu.',
    '«%@» blev ikke fundet i diagramkilden',
    'netværksspærringen til WKWebView kunne ikke opbygges',
    'Associationsregler',
    'Én kurv pr. række',
    'To kolonner: id · vare',
    'Transaktionsdataenes form',
    'Kurvekolonne eller kolonne med transaktions-id',
    'Varekolonne',
    'Tegn der adskiller varer',
    'Mindste support, procent',
    'Mindste confidence, procent',
    'Adskilt af:',
    'Support ≥',
    '% · Confidence ≥',
    'Tabel over associationsregler',
    'Support',
    'Confidence',
    'Lift',
    'Leverage',
    'Bemærk',
    '%d {one=transaktion|other=transaktioner} · %d {one=vare|other=varer} · %d {one=regel|other=regler}',
    ' — ingen regel nåede tærsklerne; sænk support eller confidence',
    ' — STOPPEDE FOR TIDLIGT, tabellen er UFULDSTÆNDIG',
    '%d / %d {one=transaktion indeholder|other=transaktioner indeholder} begge sider',
    'Tokolonneformen kræver to FORSKELLIGE kolonner.',
    '%1$d {one=række markeret|other=rækker markeret} i %2$d {one=transaktion|other=transaktioner} der indeholder «%3$@»',
    'CSV: associationsregler…',
    'Gruppevis udvinding',
    'Grupperingskolonne',
    'Værdikolonne',
    'Anden kolonne til korrelationen',
    'Rangordningsmåde',
    'Grupper efter:',
    'Værdi:',
    'Rangordn efter:',
    'Tabel over gruppernes rangorden',
    'Gruppe',
    'Rækker',
    'Egen tærskel',
    'MAPE',
    'r',
    'r-forskel',
    'Note',
    'kan ikke måles',
    '%d {one=gruppe|other=grupper} · samlet referencekorrelation %@',
    ' · %d {one=GRUPPE FRAVALGT|other=GRUPPER FRAVALGT}',
    'Denne tabel har ingen tekstkolonne at gruppere efter.',
    'Denne tabel har ingen numerisk kolonne at udvinde af.',
    '%1$d {one=række|other=rækker} i gruppen «%2$@» markeret',
    'CSV: gruppevis udvinding…',
    '↔',
    'Prognose',
    'Værdikolonne over tid',
    'Prognosemodel',
    'Antal perioder der skal forudsiges',
    'Vurdering over for referencemodellerne',
    'Model:',
    'Perioder:',
    'Sæson:',
    'auto',
    'Sæsonperiode; lad stå tomt for automatisk registrering',
    'Tabel over forudsagte værdier',
    'Periode',
    '80 %-bånd',
    '95 %-bånd',
    'MAE %@ · MAPE %@',
    'kan ikke beregnes',
    'Denne tabel har ingen numerisk kolonne at forudsige.',
    'Der kunne ikke opbygges en prognose for denne kolonne.',
    'Kolonnen «%1$@» har kun %2$d {one=numerisk værdi|other=numeriske værdier} — der kræves mindst 4 til en prognose.',
    '# Rækken læses nøjagtigt i arkivets rækkefølge — uden omsortering og uden at udlede en tidskolonne.\n',
    'Træningsfejl',
    'CSV: tidsserieprognose…',
    'Holt-Winters additiv',
    'Holt-Winters multiplikativ',
    'seasonal-naive',
    'naive',
    'Kolonner der indgår i klyngedannelsen',
    'WCSS-kurve',
    'Klynge',
    'Skalering:',
    'k:',
    'eps:',
    'minPts:',
    'Vælg mindst én kolonne.',
    'Der er for lidt data til at opbygge kurven.',
    'Albuen antyder k = %d. WCSS falder ALTID, når k vokser, så det er en måde at læse diagrammet på og ikke et statistisk kriterium — se på kurven og vurder, om knækket er tydeligt.',
    'WCSS efter k',
    'k-afstanden antyder eps = %1$@ (minPts er som standard 2 × antallet af kolonner = %2$d). %3$@',
    "Afstand til den k'te nabo",
    'Klyngedannelse kræver mindst 2 numeriske kolonner.',
    'Klynger efter %@ og %@',
    ' — klyngerne blev fundet i %d {one=dimension|other=dimensioner}; diagrammet viser kun de 2 første',
    '# støj (cluster_id = -1): %d {one=række|other=rækker}\n',
    'CSV: klyngedannelse…',
    '# --- Klyngecentre (oprindelige enheder) ---\n',
    'k-means',
    'DBSCAN',
    'Korrelationsmatrix',
    'Korrelationsmetode',
    'Korrelation betyder ikke årsagssammenhæng.',
    'Stærkeste par: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klik på et felt for at se et punktdiagram.',
    'Intet par kan måles.',
    '%1$@ ↔ %2$@: %3$@ over %4$d {one=række|other=rækker}',
    'Korrelation kræver mindst 2 numeriske kolonner.',
    'Kolonnen «%@» kan ikke læses.',
    'CSV: korrelationsmatrix…',
    'Afvigelser',
    'Liste over afvigelser',
    'Kolonne:',
    'Numerisk kolonne der skal undersøges',
    'Metode:',
    'Registreringsmetode',
    'Anvendt metode',
    'Tærskel',
    'Marker',
    'Eksporter til et nyt faneblad',
    'Linje',
    'Score',
    'Hvorfor',
    'let',
    'middel',
    'alvorlig',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=række|other=rækker} (%.2f %%)',
    'Denne tabel har ingen numerisk kolonne at lede efter afvigelser i.',
    '%d {one=afvigende linje markeret|other=afvigende linjer markeret}',
    'CSV: find afvigelser…',
    '%1$d {one=regel, BESTÅET|other=regler, alle BESTÅET} · %2$d {one=række|other=rækker} · %3$.0f ms',
    '%1$d {one=fejl|other=fejl} · %2$d {one=advarsel|other=advarsler} på tværs af %3$d {one=regel|other=regler} · %4$d {one=række|other=rækker} · %5$.0f ms',
    'Arkiver dokumentet først — kvalitetsreglerne ligger ved siden af dataarkivet.',
    'Der er endnu intet regelsæt. Opret arkivet %@ og åbn igen.',
    'Historik',
    'Arkiverede forespørgsler',
    'Arkiver denne forespørgsel…',
    'Arkiver forespørgslen',
    'Giv den et navn, så du kan finde den senere. Samme navn overskriver.',
    'For eksempel: Omsætning pr. region',
    'Der blev ikke angivet en værdi til parameteren: %@',
    'Pluginet er ændret, siden du godkendte det — GEditor nægter at køre det',
    'Køre et ikke-godkendt plugin?',
    'Jeg stoler på dette arkiv — kør',
    'IKKE signeret',
    'Signatur: %@',
    'Sti: %@',
    'Erstat',
    'Erstat alle',
    'Almindelig tekst',
    'Udvidet (\\n \\t \\xNN)',
    'Regulært udtryk',
    'Skeln mellem store og små bogstaver',
    'Helt ord',
    'Ingen resultater',
    'Prøv et regulært udtryk…',
    'Logtilstand (farve efter niveau)',
    'Filtrer loggen efter niveau…',
    'Kør på hele mappen…',
    'Filtrer gennem en ekstern kommando…',
    'Scripts…',
    'Udvidelsespakker…',
    'Nyt vindue',
    'Løsn fanebladet til et nyt vindue',
    'Der er ikke åbnet nogen mappe',
    'Find et arkiv i mappen',
    'Filtrer på navn',
    'Nyt arkiv…',
    'Ny mappe…',
    'Omdøb…',
    'Flyt til papirkurven',
    'Vis i Finder',
    'Læser dokumentets struktur…',
    'dette arkiv har ingen funktioner',
    'Ingen træf',
    'Almindelig tekst',
    '🔒 Skrivebeskyttet',
    'Følges',
    'ombrydning ved kolonne',
    'Syntaks',
    'Klik for at indsætte i forespørgslen',
    'ugyldig forespørgsel',
    'nøglen «navn» i roden',
    'nøgle med mellemrum',
    'første element',
    'alle elementer',
    'udsnit',
    'forening af indeks',
    'alle nøgler «pris» på alle niveauer',
    'alle knuder',
    'filtrer på tal',
    'filtrer på tilstedeværelse',
    'Til første fejl',
    'Kolonnen omsætning er numerisk',
    'filtrer…',
    'Annuller',
    'Udfør erstatningen',
    'forhåndsvisning',
    'interaktivt',
    'Rediger',
    'Grænseflade',
    'Tastaturgenveje',
    'Tekststørrelse',
    'Tabulatorbredde',
    'Ryk ind med tabulatorer',
    'Ryk automatisk ind ved ny linje',
    'Fremhæv alle søgeresultater',
    'Normaliser til NFC ved arkivering',
    'Sprog',
    'Udseende',
    'Som systemet',
    'Lyst',
    'Mørkt',
    'Tema',
    'Brug Notepad++-opsætningen',
    'Tilbage til standardtasterne',
    'Åbn konfigurationsarkivet',
    'Eksporter det aktuelle tema',
    'Sprogskiftet slår helt igennem ved næste start.',
    'Standardtasterne vender tilbage ved næste start.',
    'Markdown-forhåndsvisning',
    'Forhåndsvisningen bruger systemets Markdown-motor: endnu ingen tabeller og ingen farvelægning af kodeblokke.',
    'Prøv et regulært udtryk',
    'Udtryk',
    'Prøvetekst',
    'Resultat',
    'Træf',
    'Hvad dette udtryk gør',
    'Forklar udtrykket',
    'Søgetilstand',
    'Søgeresultater',
    'Ingen træf',
    ' (afkortet)',
    'Dokumentkort',
    'Fanebladslinje',
    'Overskriftsrække for kolonnerne',
    'Ingen kolonner',
    'Arbejdsområdets træ',
    'Liste over funktioner og klasser',
    'Søgeresultater i mappen',
    'CSV-datatabel',
    'Arbejdsbord til datarensning',
    'JSONPath-forespørgsel',
    'Liste over datafejl',
    'Bedømmer til guldmængden…',
    'Sammenlign med eksterne scorer (JSONL)…',
    'Vælg et arkiv med eksterne scorer (JSONL: query, chunk_id, score)',
    'Omdøb den valgte knude',
    'Flet de valgte knuder',
    'Del den valgte knude',
    'Træk den valgte delgraf ud i et nyt faneblad',
    'Der er intet at ændre',
    '%1$@ — anvend %2$d {one=ændring|other=ændringer}?',
    '%1$@: %2$d {one=ændring|other=ændringer} · Cmd-Z fortryder hele omgangen',
    'Sæt markøren på NØJAGTIGT ÉN knude og prøv igen',
    'Omdøb «%@»',
    'Alle kanter og etiketter der henviser til denne knude, ændres med den.',
    'Omdøb knuden',
    'Vælg MINDST TO knuder og prøv igen',
    'Kanonisk form «%@» — hyppigst, længst, med diakritiske tegn',
    'Flet knuder',
    'Vælg de KANTLINJER der skal flyttes, og prøv igen',
    'Alle valgte linjer skal røre NØJAGTIGT ÉN knude — vælg flere kantlinjer',
    'Del «%1$@» — flyt %2$d {one=kant|other=kanter}',
    'Kanter til: %@',
    'Del knuden',
    'Dokumentet er ikke arkiveret — det udtrukne arkiv har brug for en plads ved siden af',
    'Vælg den del af grafen der skal trækkes ud, og prøv igen',
    'Saml entitetsvarianter → gennemsynstabel',
    'Anvend den rettede gennemsynstabel',
    'Dokumentet er ikke arkiveret — gennemsynstabellen skal ligge ved siden af grafarkivet',
    'Der blev ikke fundet varianter at samle',
    '%d {one=variantgruppe|other=variantgrupper} — ret kolonnen «canonical» og kør «Anvend gennemsynstabellen»',
    'Der er ingen gennemsynstabel «%@» — kør «Saml entitetsvarianter» først',
    'Gennemsynstabellen kan ikke læses: %@',
    'Gennemsynstabellen har ingen linje der skal ændres',
    'Intet sted i grafen svarer til gennemsynstabellen',
    'Saml entitetsvarianter',
    '%d {one=ændring anvendt|other=ændringer anvendt} · alias-tabellen og markørlisten er skrevet ved siden af arkivet',
    'Anvend %d {one=ændring|other=ændringer} på grafen?',
    '%d {one=alias|other=aliasser} → kanonisk form.',
    'FLET knuder (kan ikke fortrydes ved at skrive igen):',
    '%d {one=alias findes|other=aliasser findes} ikke i grafen og blev sprunget over.',
    'GraphRAG…',
    'Dækningsanalyse stykke ↔ entitet',
    'Eksporter kontekstpakken (JSONL)',
    'Dækning stykke ↔ entitet ↔ graf',
    '- %1$d {one=entitet|other=entiteter} · %2$d {one=stykke|other=stykker} · %3$.0f %% af entiteterne nævnt · %4$.0f %% af stykkerne med entitet',
    'Entiteter som intet stykke nævner',
    'Forældreløse stykker (uden en eneste entitet)',
    'Grafknuder uden tilsvarende entitet',
    'ingen',
    'Metode',
    'Sammenkoblingen stykke ↔ entitet kunne ikke opbygges',
    'Bedøm grafens sundhed',
    'grafens sundhed',
    'Sundhed %1$@/100 · %2$d {one=fejl|other=fejl} · %3$d {one=ombytning|other=ombytninger} · %4$d forældreløse',
    'Hybrid med grafen',
    'α = 1: grafens signal ignoreres helt, resultatet svarer til ren BM25',
    'α høj: grafen justerer kun BM25-rangordenen let',
    'α omkring standardværdien 0,7: BM25 fører an, grafen justerer',
    'α lav: grafen fører an, BM25 bryder kun uafgjort',
    'α = 0: kun grafens signal; stykker uden entiteter står lige',
    'Dokumentet er ikke arkiveret — hybriden har brug for et grafarkiv ved siden af korpusset',
    'Grafarkivet «%@» blev ikke fundet — hybriden har brug for det til sit signal',
    'hybrid %.1f ms · %@',
    'Algoritmer…',
    'PageRank (kantens tykkelse)',
    'Fællesskaber (baggrundsfarve)',
    'Sammenhængende komponenter',
    'Eksporter knudetabellen til et nyt faneblad',
    '%1$d {one=komponent|other=komponenter} · den største %2$d {one=knude|other=knuder} · %3$d forældreløse knuder',
    'Dette dokument er ikke en DOT-graf',
    'Knude-/kanttabellen kunne ikke opbygges: %@',
    '%d {one=række|other=rækker} · %@',
    'Sæt etiket',
    'Note (valgfri)',
    'Arkiver posten',
    'Eksporter CSV',
    'Dokumentet er ikke arkiveret — bedømmeren skal ligge ved siden af korpusarkivet',
    'Bedømmeren kunne ikke indlæses: %@',
    'Kunne ikke arkiveres: %@',
    'Bedømmeren har endnu ingen post',
    'Kunne ikke skrives: %@',
    'Dette dokument er hverken et .mmd-arkiv eller DOT og har ingen mermaid-blok.',
    '%d {one=knude|other=knuder} · %d {one=kant|other=kanter} · ⚠ %@',
    'Mermaid-diagram: tilføj element…',
    'Mermaid-diagram: forbind de to valgte elementer',
    'Mermaid-diagram: ret etiketten på det valgte element…',
    'Mermaid-diagram: slet det valgte element',
    'Mermaid-diagram: flyt beskeden op',
    'Mermaid-diagram: flyt beskeden ned',
    'Tilføj element',
    'Tilføj deltager',
    'Tilføj post',
    'Tilføj en post til diagrammet',
    'Ret en post i diagrammet',
    'Slet en post fra diagrammet',
    'Slet elementet',
    'Ret etiketten',
    'Skift beskedernes rækkefølge',
    'Postens navn',
    'Ny post',
    'Postens navn vises på diagrammet.',
    'Diagrammets egenskabstabel',
    'Dette dokument har ingen mermaid-blok',
    'Identifikator i diagramkilden — uden mellemrum. Etiketten rettes bagefter med dobbeltklik.',
    'Lades den tom, vises identifikatoren selv.',
    'Kun den synlige ETIKET ændres; elementets identifikator forbliver den samme.',
    'Det er uklart, hvilket element «%@» er',
    'Vælg NØJAGTIGT TO elementer og prøv igen',
    'Sæt markøren på NØJAGTIGT ÉT element og prøv igen',
    'Vælg ÉT element der skal slettes, eller to elementer som en kant forbinder',
    'Slet «%1$@» og den %2$d {one=kant der rører det|other=kanter der rører det}?',
    'Knuderne i den anden ende af de kanter bevares — de erklæres igen med deres etiket, hvis kantsætningen var deres eneste erklæring.',
    'Diagrammet «%1$@» redigeres kun som tekst — %2$@',
    '%@: træk mellem to elementer for at forbinde dem, dobbeltklik for at rette etiketten',
    '%@: træk mellem to deltagere for at tilføje en besked; rækkefølgen ændres via menuen Værktøjer',
    '%@: rediger i egenskabstabellen nedenfor',
    'Visuel redigering slået til',
    '%1$@ · %2$d {one=post|other=poster} — rediger direkte i tabellen, hvert felt er ét fortryd-trin',
    'Ved et cirkeldiagram er det et tal; ved et gantt det der følger efter kolon.',
    'Mermaid-diagram: træk blokken ud i et .mmd-arkiv…',
    'Mermaid-diagram: indlejr det henviste arkiv igen',
    'Træk diagramblokken ud',
    'Indlejr diagramblokken',
    'Træk diagramblokken ud i et selvstændigt arkiv',
    'Arkivet lægges VED SIDEN AF dokumentet; blokken beholder en henvisningslinje, så der kun redigeres ét sted.',
    'Dokumentet er ikke arkiveret — diagramarkivet har brug for en plads ved siden af',
    'Arkivet «%@» findes allerede — vælg et andet navn',
    'Trukket ud til «%@» — blokken beholdt en henvisningslinje',
    'Åbn arkivet',
    '«%@» er indlejret igen; arkivet ligger stadig på disken',
    'Denne blok indeholder et rigtigt diagram, ikke en henvisning',
    'Denne blok henviser til «%@» — åbn det arkiv for at redigere',
    'Diagramarkivet %@ kunne ikke læses',
    'Visuel redigering',
    'Træk fra en knude til en anden for at tilføje en kant; dobbeltklik for at rette etiketten. Hver handling er ét fortryd-trin.',
    'Visuel redigering: træk mellem to knuder for at tilføje en kant, dobbeltklik for at rette etiketten',
    'Visuel redigering slået fra',
    'Tilføj knude…',
    'Tilføj en kant mellem de to valgte knuder…',
    'Ret etiketten på den valgte knude…',
    'Slet den valgte knude/kant',
    'Tilføj knude',
    'Tilføj kant',
    'Ret knudens etiket',
    'Slet knuden',
    'Slet kanten',
    'Cmd-Z fortryder',
    'Dette dokument er skrivebeskyttet',
    'Etiketten for «%@»',
    'Kun den synlige ETIKET ændres; knudens identifikator forbliver den samme.',
    'Det er uklart, hvilken knude «%@» er',
    'Knudens identifikator i DOT-arkivet. Etiketten rettes bagefter med dobbeltklik på tegningen.',
    'Vælg NØJAGTIGT TO knuder og prøv igen',
    'Vælg ÉN knude der skal slettes, eller to knuder som en kant forbinder',
    'Slet knuden «%1$@» og de %2$d {one=kant der rører den|other=kanter der rører den}?',
    'Bliver der hængende kanter tilbage, genskaber DOT knuderne ud fra dem — den slettede knude dukker op igen ved næste tegning.',
    'BM25-søgelaboratorium',
    'Spørgsmål — Enter for at søge',
    'Bedøm…',
    'Opbygger indekset',
    'Intet stykke matcher',
    'bedste resultater',
    'k1 = 0: hvert ord tælles KUN én gang, uanset hvor mange gange det forekommer',
    'k1 lav: at gentage et ord giver næsten ingen ekstra score',
    'k1 omkring standardværdien 1,2: gentagelse giver score, men mindre og mindre',
    'k1 høj: et stykke der gentager et ord mange gange, belønnes kraftigt',
    'b = 0: længden ignoreres, lange stykker straffes ikke',
    'b lav: lange stykker straffes kun let',
    'b omkring standardværdien 0,75: lange stykker straffes moderat',
    'b = 1: største straf for længde, korte stykker foretrækkes',
    'JSONL: søgelaboratorium…',
    'Dokumentet er ikke arkiveret — BM25-indekset ligger ved siden af korpusarkivet og har derfor brug for en sti',
    'Dette arkiv er ikke JSONL — Retrieval Lab arbejder på et korpus af stykker',
    'Der kunne ikke opbygges et BM25-indeks til dette arkiv',
    'Dokumentet er ikke arkiveret — der kræves en korpussti for at lave rapporten',
    'Vælg et bedømmelsessæt (CSV eller JSONL: spørgsmål + forventet stykke-id)',
    'Bedømmelse af søgningen',
    'Ret k1, b eller k ovenfor og se igen for at sammenligne to opsætninger; tilføj en «compare»-blok for at køre to parametersæt sideløbende på det samme bedømmelsessæt.',
    'Fejl',
    '   (%d…%d, i gennemsnit %.0f)',
    'JSONL-tilstand',
    'Post',
    'Detaljer',
    'Posten på linjen',
    'er ikke gyldig JSON',
    'poster',
    'tomme linjer',
    'er ikke et objekt',
    'vist tabel',
    'AFBRUDT PÅ HALVVEJEN',
    'Intet filter',
    'poster der matcher filteret',
    'Sæt markøren på en linje for at se posten',
    'Ingen ødelagte poster',
    'Endnu ikke undersøgt. Kør «JSONL: undersøg stykker» igen efter kontrollen.',
    'tekstfelt',
    'SKEMA (gættet — ændres ved at vælge et andet felt)',
    'tekst',
    'identifikator',
    'indlejrede metadata',
    'FELT',
    'dækning',
    'flere typer',
    'LÆNGDE — tegn',
    'LÆNGDE — ord',
    'LÆNGDE — anslåede tokens',
    'TOMME OG DUBLETTER',
    'tomme stykker',
    'linjer',
    'grupper af nøjagtige dubletter',
    'linjer kan ikke læses, uden for statistikken',
    'METODE',
    '«tegn» tælles som Unicode-tegn (skalarer), ikke som synlige grupper',
    '«ord» adskilles ved ASCII-mellemrum',
    '«tokens» tælles med en stavelsesdeler — IKKE modellens',
    '«dublet» betyder NØJAGTIG dublet; næsten-dubletter står i blokken ```quality',
    'stykker',
    'JSONL: kontroller og undersøg stykker…',
    'Billede',
    'PDF',
    'Word-dokument',
    'Excel-regneark',
    'PowerPoint-præsentation',
    'Arkivfil',
    'Tilpas til vinduet',
    'Kopier billedet',
    'Roter',
    'Billedet «%@» kan ikke læses',
    'Billedet er kopieret til udklipsholderen',
    'Fremhæv med gult',
    'Understreg',
    'Note…',
    'Fjern noterne',
    'Træk teksten ud i et nyt faneblad',
    'Arkiver versionen med noter…',
    'Søg i PDF-filen',
    'Tilføj',
    'Side %d/%d',
    'Side %d',
    'Resultat %d/%d',
    '0 resultater',
    'PDF-filen «%@» kan ikke læses',
    'Denne PDF-fil er beskyttet med adgangskode — indholdet kan ikke tilgås',
    '«%@» blev ikke fundet i dokumentet',
    'Fremhævet',
    'Understreget',
    'Vælg først et stykke tekst',
    'Note tilføjet',
    'Denne side har ingen noter',
    '%d {one=note fjernet|other=noter fjernet} fra denne side',
    'Denne PDF-fil har intet tekstlag — det er sandsynligvis en indscanning',
    'Arkivet kunne ikke skrives',
    'Det skrevne arkiv åbnes IKKE korrekt igen — brug ikke denne version',
    '%@ arkiveret · %d {one=side|other=sider}',
    'Navn',
    'Størrelse',
    'Komprimeret',
    'Forhold',
    'Ændret',
    'Åbn det valgte emne',
    'Pak ud i en mappe…',
    'Pak ud her',
    '%d {one=emne|other=emner}',
    'pakket ud til %@',
    '— indersiden af et Office-arkiv er en arkivfil; dette er dens dele',
    '%d {one=emne pakket|other=emner pakket} ud',
    '%d {one=emne er ødelagt|other=emner er ødelagte}',
    '%d {one=emne blev AFVIST|other=emner blev AFVIST}, fordi deres stier går uden for målmappen',
    'Dette emne kan ikke åbnes',
    'Der kan endnu ikke skrives direkte til en %@ — brug «Arkiver som…»',
    'Intet er ændret',
    '%1$d {one=felt skrevet|other=felter skrevet} til %2$@',
    '%1$d {one=afsnit skrevet|other=afsnit skrevet} til %2$@',
    'Der kunne ikke skrives til arkivet — originalen er urørt',
    'forberede testtilfældet',
    'settings.json kan ikke skrives',
    'Rotér til venstre',
    'Rotér til højre',
    'Flyt side op',
    'Flyt side ned',
    'Slet sider…',
    'Slet sider',
    'Udtræk sider…',
    'Udtræk sider til ny fil',
    'Flet PDF-fil…',
    'Opdel fil…',
    'Opdel PDF-fil',
    'Eksportér billeder…',
    'Eksportér sider som PNG-billeder',
    'Fortryd sideændring',
    'Arkivér redigeret kopi…',
    'Afspil',
    'Pause',
    'Normal visning',
    'Vælg ark',
    'Åbn ark',
    'Kassér og skift ark',
    'Projektmappen har %d ark.',
    'Denne projektmappe har kun ét ark: »%@«',
    'Vil du kassere ikke-arkiverede ændringer i dette ark?',
    'Skift af ark erstatter hele fanen. Det, der ikke er arkiveret med ⌘S, går tabt.',
    'Vælg PDF-fil, der skal flettes ind',
    'Vælg mappe til billederne',
    'Vælg placering. Den anden fil arkiveres ved siden af denne.',
    'Dokumentet har %d sider. Angiv sider, der skal slettes, fx 2-4,7',
    'Dokumentet har %d sider. Angiv sider, der skal udtrækkes, fx 1-3,8',
    'Dokumentet har %d sider. Angiv sider, der skal eksporteres, fx 1-3',
    'Dokumentet har %d sider. Angiv den del, der skal skilles ud, fx 1-5; resten bliver en anden fil.',
    'Side %d roteret',
    'Siderne %@ slettet · %d sider tilbage',
    '%d sider flettet fra »%@«',
    'Opdelt i %@ (%d sider) og %@ (%d sider)',
    'Skrev %@ — %@ · %d sider',
    '%d billeder eksporteret til %@',
    'Kun %d af %d billeder blev eksporteret',
    'Én sidehandling blev fortrudt',
    'Ingen sidehandlinger tilbage at fortryde',
    'Kan ikke slette ALLE sider — en PDF skal have mindst én side',
    'Det interval er hele dokumentet — der er intet at skille ud',
    '»%@« er adgangskodebeskyttet — kan ikke flettes',
    '»%@« har ingen sider',
    'Allerede på første side',
    'Allerede på sidste side',
    '· redigeret, ikke arkiveret',
    'Animeret billede · %d billeder',
    'Ikke-arkiveret dokument — ingen fil på disken til binær visning',
    'Denne kommando virker kun med Excel-projektmapper',
    'Listen over ark kunne ikke læses',
    'Der findes intet ark ved navn »%@«',
    'Arket »%@« kunne ikke læses',
    'Arket »%@« · %d rækker',
    'resten',
    'Bemærk',
    'Forsigtig',
    'Se også',
    'Kopiér',
    'Kopieret',
    'Kopiér eksempelkoden',
    'Søg i hjælp',
    'Tilbage',
    'Kom i gang',
    'Vis ikke dette vindue ved start',
    'Hjælpen er endnu ikke oversat til dette sprog — viser den vietnamesiske tekst.',
    'Gå til offset (fx 1F400 eller 0x1F400)',
    'Kopiér valgte rækker',
    '%d rækker kopieret',
    '»%@« kunne ikke læses',
    'Tom fil',
    'Offset »%@« kunne ikke læses',
    'Offset 0x%@ ligger uden for filens størrelse',
    'Åbn med anden app…',
    '%d kanaler',
    '»%@« kan ikke afspilles',
    'Kan ikke afspilles — %@',
    'macOS har ingen indbygget dekoder til formatet %@ — det er en systembegrænsning, ikke en ødelagt fil.',
    'Du kan stadig se byte i binær visning eller åbne filen med en app, der har sin egen dekoder.',
    'Underskriv…',
    'Rediger tekst…',
    'Rediger tekst',
    'Tegn ovenpå',
    'Næste tomme felt',
    'Ryd udfyldte værdier',
    'Denne fil har ingen formularfelter',
    '%d formularfelter ryddet',
    'Alle formularfelter er allerede udfyldt',
    '%d felter er stadig tomme',
    'Formular, der kan udfyldes: %d felter. Skriv direkte, og vælg så »Arkivér redigeret kopi…«',
    'Vælg et underskriftsbillede (gennemsigtig baggrund ser bedst ud)',
    'Den underskrevne side kunne ikke oprettes',
    'Underskrift indsat på side %d',
    'Vælg først den tekst, du vil ændre',
    'Markeringen er for lille',
    'Den nye tekst TEGNES OVEN PÅ markeringen med systemskriften. Den gamle tekst dækkes, den fjernes ikke — den kan stadig udtrækkes, så dette er ikke sløring.',
    'Den redigerede side kunne ikke oprettes',
    'Ny tekst tegnet over side %d',
    'Skift Visning / Kode',
    'Endnu ingen trævisning for JSON · XML · YAML',
    'Endnu ingen diagramvisning i fanen',
    'Endnu ingen dispositionsvisning for PowerPoint',
    'Denne fil har kun én visningstilstand',
    '%d knuder',
    'Træet kunne ikke opbygges: %@',
    'Dokumentet er for stort til et træ — brug Kode-tilstand',
]
