# Bản dịch es — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code es --name "…" scripts/ban-dich/es.py
VALS = [
    'Versiones guardadas…',
    'Este documento nunca se ha guardado — no hay historial',
    'No hay versiones guardadas anteriores',
    'No se puede leer esa versión',
    'Restaurar la versión guardada',
    'XML: validar con DTD/XSD…',
    'Este Mac no tiene libxml2, así que la validación XSD no está disponible.',
    'Elegir un esquema XSD para validar',
    'Válido según',
    'El complemento terminó sin cambiar nada',
    'No hay complementos nativos instalados',
    'Quitar este complemento',
    '¿Quitar este complemento?',
    'Quitar',
    'Instalar un complemento nativo…',
    'Abrir la carpeta de complementos',
    'Elegir el archivo .dylib del complemento',
    'Instalado:',
    'Quitado:',
    'Complementos nativos…',
    'Solo se aceptan archivos .dylib.',
    'Ya hay un complemento con el mismo nombre:',
    'No se puede copiar el complemento:',
    'Los complementos nativos solo están en la descarga directa, no en la versión de la App Store.',
    'No se encuentra el proceso auxiliar de complementos.',
    'No se puede iniciar el proceso auxiliar:',
    'El proceso del complemento se detuvo a medias.',
    'El complemento no respondió a tiempo — se detuvo.',
    'El complemento respondió con un mensaje mal formado:',
    'El complemento informó de un error:',
    'Acerca de GEditor',
    'Ajustes…',
    'Salir de GEditor',
    'Archivo',
    'Pestaña nueva',
    'Cerrar pestaña',
    'Pestaña siguiente',
    'Pestaña anterior',
    'Documento nuevo',
    'Abrir…',
    'Abrir una carpeta como espacio de trabajo…',
    'Abrir reciente',
    'Guardar',
    'Guardar como…',
    'Quitar espacios al final de línea al guardar',
    'Seguir el archivo (tail -f)',
    'Imprimir…',
    'Reabrir la pestaña cerrada',
    'No hay archivos',
    'Vaciar la lista',
    'Edición',
    'Deshacer',
    'Rehacer',
    'Cortar',
    'Copiar',
    'Pegar',
    'Historial del portapapeles…',
    'Editor de columnas…',
    'Seleccionar la siguiente coincidencia',
    'Seleccionar todo',
    'Duplicar la línea',
    'Eliminar la línea',
    'Comentar la línea',
    'No se ha copiado nada en esta sesión',
    'Borrar el historial',
    'Buscar',
    'Buscar…',
    'Buscar y reemplazar…',
    'Buscar en una carpeta…',
    'Reemplazar en una carpeta…',
    'Resultado siguiente',
    'Resultado anterior',
    'Ir a la línea…',
    'Ir al paréntesis correspondiente',
    'Marcar todas las líneas coincidentes…',
    'Invertir las marcas',
    'Quitar todas las marcas',
    'Copiar las líneas marcadas',
    'Eliminar las líneas marcadas',
    'Conservar solo las líneas marcadas',
    'Líneas',
    'Ordenar A→Z',
    'Ordenar Z→A',
    'Orden natural',
    'Quitar duplicados',
    'Invertir el orden de las líneas',
    'Subir la línea',
    'Bajar la línea',
    'Unir líneas',
    'Dividir líneas por longitud…',
    'Dividir líneas por carácter…',
    'Eliminar líneas vacías',
    'Reducir líneas vacías consecutivas',
    'Quitar espacios al final de línea',
    'Tab → Espacio',
    'Espacio → Tab',
    'MAYÚSCULAS',
    'minúsculas',
    'Mayúscula En Cada Palabra',
    'Mayúscula al inicio de la frase',
    'iNVERTIR mAYÚSCULAS',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: elegir hoja…',
    'Alternar vista de tabla / texto',
    'Eliminar columna…',
    'Validar los datos (número de columnas · tipos)',
    'Mesa de limpieza de datos…',
    'Ejecutar una receta de limpieza…',
    'Convertir…',
    'Cambiar el separador…',
    'Exportar a JSON…',
    'Formato',
    'Codificación…',
    'Fin de línea…',
    'Normalizar Unicode…',
    'JSON: formatear',
    'JSON: compactar en una línea',
    'JSON: ordenar claves',
    'JSON: consulta JSONPath…',
    'CSV: consulta SQL…',
    'Consulta SQL',
    'Ejecutando…',
    'Exportar a una pestaña nueva',
    'Documento vacío — no hay tabla que consultar',
    'No es una tabla CSV — la primera fila solo tiene una columna',
    'No se puede leer la consulta',
    'No se puede comprobar la consulta',
    'Amarillo (por defecto)',
    'Azul',
    'Verde',
    'Ocre',
    'Morado',
    'Rosa',
    'Turquesa',
    'Naranja',
    'Pizarra',
    'Texto',
    'Serie numérica',
    'Serie de fechas',
    'MAYÚSCULAS (hexadecimal)',
    'Inicio',
    'Paso',
    'Rellenar con ceros hasta',
    'Base',
    'Primera fecha',
    'Formato',
    'Insertar',
    'Cancelar',
    'Convertir el formato',
    'Vista previa de las 5 primeras filas',
    'Abrir en una pestaña nueva',
    'Guardar en un archivo…',
    'El resultado se abre en una pestaña nueva sin guardar. El documento original queda intacto.',
    'Ejecutar en este documento',
    'Ejecutar en una carpeta…',
    'Toda la receta es UN solo paso de deshacer. El archivo del disco queda intacto hasta que guardes.',
    'desactivado',
    'columna no encontrada',
    'listo',
    'sigue ocupando un núcleo de CPU hasta que se cierre la aplicación.',
    'El script no devolvió nada',
    'No se pudo crear el motor de JavaScript',
    'Error de JavaScript desconocido',
    'Tabla',
    'Aplicar el orden al archivo',
    'Convertir ▾',
    'Exportar las filas coincidentes',
    'Ocultar esta columna',
    'Renombrar el encabezado…',
    'Insertar una columna vacía a la izquierda',
    'Insertar una columna vacía a la derecha',
    'Eliminar esta columna del archivo…',
    'Debe quedar al menos una columna visible',
    'Ordenando…',
    'Volver al orden del archivo',
    'primeras cien filas',
    'elegir columnas',
    'nombrar una columna del resultado',
    'filtrar por texto',
    'celdas vacías',
    'combinar condiciones',
    'contar filas',
    'agrupar y agregar',
    'mínimo, máximo',
    'ordenar y limitar',
    'nombre de columna con espacios',
    'La consulta se interrumpió',
    'No admitido: JOIN · subconsulta · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funciones de ventana',
    'XML: formatear',
    'XML: compactar en una línea',
    'XML: comprobar la sintaxis',
    'YAML: revisar claves duplicadas e indentación',
    'Ver',
    'Mostrar/ocultar la barra lateral (lista de funciones)',
    'Mostrar/ocultar el mapa del documento',
    'Plegar / desplegar el bloque del cursor',
    'Plegar todo',
    'Desplegar todo',
    'Plegar por nivel',
    'Nivel %d',
    '%d {one=bloque plegado|other=bloques plegados} en el nivel %d',
    'Este documento solo tiene %d {one=nivel|other=niveles} de profundidad',
    'mermaid: no se puede leer el manifiesto',
    'Buscar actualizaciones…',
    'Buscar actualizaciones',
    'Las versiones de la App Store se actualizan por la Mac App Store, no por GEditor.',
    'Esta versión no tiene clave de firma de actualizaciones, así que no puede buscarlas.',
    'Aumentar el texto',
    'Reducir el texto',
    'Tamaño real',
    'Dividir verticalmente',
    'Dividir horizontalmente',
    'Cerrar la división',
    'Abrir esta pestaña en el otro panel',
    'Ir al otro panel',
    'Ajuste de línea (desactivado / ventana / columna)',
    'Ajustar línea en la columna…',
    'Marcar esta línea',
    'Marca siguiente',
    'Marca anterior',
    'Color de las marcas…',
    'Mostrar todos los caracteres invisibles',
    '  Espacios',
    '  Tabulaciones',
    '  Fin de línea',
    '  NBSP · ancho cero · control',
    'Vista binaria',
    'Modo CSV (columnas en colores)',
    'Macro',
    'Iniciar / detener la grabación',
    'Reproducir',
    'Reproducir varias veces…',
    'Reproducir hasta el final del documento',
    'Ejecutar en todas las pestañas',
    'Cancelar la macro en curso',
    'Guardar la macro…',
    'Macros guardadas…',
    'Ayuda',
    'Ayuda de GEditor',
    'Descubre las funciones',
    'Migrar desde Notepad++',
    'Buscar',
    'Reemplazar por',
    'Siguiente',
    'Anterior',
    'Contar',
    'Cerrar',
    'Validar con un esquema JSON…',
    'Elegir un archivo de esquema JSON',
    'No se encontraron problemas según este esquema.',
    'Esquema JSON',
    'Comprobar la sintaxis del grafo',
    'Formato de grafo no reconocido — se necesita una extensión .dot, .gv, .cypher, .ttl o .graphml.',
    'No se encontraron errores de sintaxis %@ (la comprobación no es exhaustiva).',
    'Sintaxis %@',
    'no es un objeto JSON',
    'Minería de texto (n-gramas, TF-IDF)',
    'El documento está vacío.',
    'No se pudo extraer ninguna palabra clave.',
    'Palabras clave',
    '%d {one=palabra clave|other=palabras clave} · %d {one=token|other=tokens} · %d {one=documento|other=documentos}',
    'Marcar en el documento',
    'Marcar entidades desde una lista…',
    'Elegir una lista de entidades (CSV o JSON)',
    'No se puede leer la lista de entidades.',
    'La lista de entidades está vacía.',
    'No se encontraron entidades en el documento (%d cargadas).',
    '%d {one=aparición|other=apariciones} · %@',
    'Convertir conocimiento…',
    'Conversión: %@ → %@',
    'No se pudo convertir.',
    'Vista previa del troceado…',
    'Tamaño fijo 800 B, solape 100 B',
    'Por frase (≤ 800 B)',
    'Por encabezado Markdown',
    'Documento vacío — no hay fragmentos.',
    '%d {one=fragmento|other=fragmentos} · %d B de media · %@',
    'Exportar JSONL',
    'Fragmentos JSONL',
    'Abrir triples/aristas como tabla',
    'Tabla de triples',
    'Este documento no tiene ninguna línea de triple.',
    'No se pudo leer ningún triple — línea %d: %@',
    '%d {one=triple leído|other=triples leídos} · %d {one=línea mal formada omitida|other=líneas mal formadas omitidas} (la primera: línea %d)',
    'Duplicados aproximados por columna…',
    'Duplicados aproximados — columna «%@»: %d {one=grupo candidato|other=grupos candidatos}',
    'Fusionar',
    'Coincidencia',
    'Valores del grupo',
    'Fusionar en',
    'Fusionar los grupos seleccionados',
    'No hay ningún grupo seleccionado — pulsar Fusionar NO cambiará nada. La aplicación nunca fusiona por su cuenta.',
    '%d {one=grupo seleccionado|other=grupos seleccionados} · %d {one=fila cambiará|other=filas cambiarán} · UN solo paso de deshacer',
    'No se pudo analizar esta columna.',
    'La columna «%@» no tiene grupos de duplicados aproximados.',
    'No se fusionó ningún grupo — el documento queda igual.',
    'Deduplicación aproximada · columna %@',
    '%d {one=grupo fusionado|other=grupos fusionados} · %d {one=celda modificada|other=celdas modificadas}',
    'Informe de limpieza',
    '# Informe de limpieza — %@\n\n',
    '## Aplicado (%d)\n\n',
    '_No se aplicó ningún paso._\n',
    '\n## Perfil de los datos\n\n',
    '_%d {one=columna|other=columnas} · %d {one=fila|other=filas} · analizado en %.1f s_\n\n',
    '| Columna | Tipo | Nulos | Distintos | Mín | Máx | Media |\n',
    '\n### Valores atípicos\n\n',
    'fila %d: %@',
    '- columna «%@» — %d {one=celda|other=celdas}: %@\n',
    '\n## Restante (%d)\n\n',
    '_No quedan hallazgos._\n',
    '- columna «%@»: %@\n',
    None,
    'Quitar espacios al guardar',
    'Normalizar los fines de línea',
    'anterior',
    'No se pudo reabrir la carpeta «%@» de la sesión anterior',
    ' (y %d {one=archivo|other=archivos} más)',
    '%d {one=pestaña no se pudo reabrir|other=pestañas no se pudieron reabrir}: %@%@ — los archivos ya no están donde estaban.',
    'No se pudo leer la entrada desde la tubería',
    'Se quitarán los espacios al final de línea en cada guardado',
    'Ya no se quitan los espacios al guardar',
    'Sin título.txt',
    'Convertir la codificación perderá caracteres',
    'Guardar de todos modos',
    'El documento tiene cambios sin guardar',
    'Cerrar sin guardar los descartará.',
    'Descartar los cambios',
    'Ir a la línea',
    'El documento tiene %d {one=línea|other=líneas}.',
    'Número de línea',
    'Ir',
    'Reinterpretar como…',
    'Convertir a…',
    'No se pudo reinterpretar',
    '%@ no puede representar todos los caracteres',
    'Elegir de todos modos',
    'Columna %d',
    'Columna %d: %@',
    'Columnas ocultas: %@ (%d) — restáuralas desde el menú contextual de la fila de encabezado',
    'Mostrar de nuevo: %@',
    'Columna %@ oculta — sigue intacta en el archivo',
    'Ordenado por %@ %@ · solo visualización',
    'Ordenado: %@ %@ (solo visualización)',
    '%d+ filas coinciden — seguimos buscando…',
    '%d / %d {one=fila coincide|other=filas coinciden}',
    'No se encontraron problemas en %d {one=fila|other=filas}',
    '%d {one=fila|other=filas} con un número de columnas incorrecto',
    '%d {one=celda|other=celdas} con el tipo de dato incorrecto',
    ' (detenido en los primeros %d {one=problema|other=problemas})',
    '   —   tipos detectados: ',
    'Fila %d, columna %@: «%@» no es %@',
    'Editor de columnas — %d {one=línea|other=líneas}',
    'Hallazgos',
    'Perfil de los datos',
    'Perfil de los datos — analizando…',
    'Guardar la receta…',
    'Exportar el informe',
    'No se aplicó ningún grupo · cada grupo es un paso de deshacer',
    'demasiados valores',
    'más frecuentes: ',
    'Valor con el que rellenar las celdas vacías',
    'Aplicar',
    'No se pudo construir una vista previa',
    '· conservado tal cual, ilegible ·',
    'Convertir la columna a ISO 8601 (AAAA-MM-DD)',
    'Convención numérica para toda la columna',
    'Qué hacer con las celdas vacías',
    'Normalizar a ISO 8601',
    'Leer las celdas ambiguas con el DÍA primero (31/12)',
    'Leer las celdas ambiguas con el MES primero (12/31)',
    'Omitir las celdas ambiguas, corregir solo las seguras',
    'A vietnamita/europeo (1.234,56)',
    'A angloamericano (1,234.56)',
    'A angloamericano, sin separador de miles (1234.56)',
    'Rellenar con un valor por defecto…',
    'Rellenar hacia abajo — tomar el valor de arriba',
    'Rellenar hacia arriba — tomar el valor de abajo',
    'Eliminar las filas con celda vacía en esta columna',
    'Quitar espacios en ambos extremos',
    'Quitar en ambos extremos y reducir los espacios internos',
    'Tabla dinámica…',
    'Fuentes…',
    'Tabla dinámica — agrupar por columna',
    'Filas (agrupación)',
    'Valores',
    '+ Fila',
    '+ Valor',
    'Borrar todo',
    'Poner en la consulta',
    'Elige columnas para construir la consulta.',
    'No se pudieron leer los nombres de columna de esta tabla.',
    'Fuentes de datos de la consulta',
    '«%@» — el documento abierto',
    '  ⚠️ el archivo ha cambiado desde que se registró',
    'Añadir archivo…',
    'Quitar todo',
    'No se pudo deducir un nombre de tabla de «%@» — renombra el archivo.',
    'Suma',
    'Media',
    'Mín',
    'Máx',
    'Recuento distinto',
    'Gráfico',
    'Exportar PNG',
    'Exportar SVG',
    'Esta tabla no tiene ninguna columna numérica que representar.',
    'No se pudo construir la imagen PNG.',
    'Resultado de la consulta',
    '%@ guardado',
    'Gráfico %@ de «%@» — %d {one=punto|other=puntos}, valores de %@ a %@',
    'Barras',
    'Líneas',
    'Histograma',
    'Dispersión',
    'Caja',
    'CSV: calidad de los datos…',
    'Calidad de los datos',
    'Exportar las infracciones a una pestaña nueva',
    'Nivel',
    'Regla',
    'Infracciones',
    'Tasa',
    'correcto',
    'error',
    'aviso',
    'roto',
    '%d {one=línea infractora marcada|other=líneas infractoras marcadas}',
    'Tendencia',
    'Evaluado el',
    'Filas',
    'Diferencia',
    'Reglas fallidas',
    'Puntuación de calidad',
    'Puntuación en el tiempo',
    'Aún no hay historial — cada evaluación añade ',
    'una línea al archivo «.history.jsonl» junto a las reglas.',
    '%d {one=punto|other=puntos} en el historial',
    ' · %d {one=línea ILEGIBLE|other=líneas ILEGIBLES}',
    ' · selecciona dos filas para comparar',
    'puntuación %+.1f',
    'ninguna dimensión bajó',
    'bajaron: ',
    '%d {one=regla que ahora falla|other=reglas que ahora fallan}: %@',
    'filas %+d',
    ' (y %d {one=aviso|other=avisos} más en la pestaña Tendencia)',
    'Sin corrección automática: ',
    'Abre la herramienta correspondiente en la Mesa de limpieza y vuelve a evaluar enseguida.',
    'Tratar los valores faltantes…',
    'Normalizar las fechas…',
    'Quitar duplicados…',
    'Reemplazar…',
    'Mostrar las filas incorrectas',
    'La columna «%@» no está en esta tabla.',
    'Duplicados eliminados — «%@» ya es único. Puntuación: %.0f/100',
    'Duplicados eliminados, pero «%@» aún tiene %d {one=fila repetida|other=filas repetidas} (antes: %d) — ',
    'esas filas comparten la CLAVE pero no la línea entera, así que hay que mirarlas y elegir ',
    'cuál conservar.',
    'No se pudo leer ningún valor que infrinja esta regla.',
    '%d {one=valor incorrecto|other=valores incorrectos} en la columna «%@» — rellena Reemplazar y pulsa Vista previa',
    'Evaluado de nuevo: %.0f/100',
    'Vista previa del informe',
    'Parámetros…',
    'Exportar HTML…',
    'Imprimir / PDF…',
    '%d {one=bloque ejecutado|other=bloques ejecutados} · %d {one=bloque FALLIDO|other=bloques FALLIDOS}',
    '%d {one=bloque ejecutado|other=bloques ejecutados}',
    ' · DATOS OBSOLETOS — el archivo de origen cambió; reconstruye',
    'La vista previa del informe necesita un documento .%@',
    'No se encontró origen de datos — declara «source: archivo.csv» en el frontmatter.',
    'No se pudo construir el informe.',
    'Este informe no declara ningún parámetro en su frontmatter.',
    'Parámetros del informe',
    'Reconstruir',
    '%@ exportado',
    'Informe: vista previa',
    'Informe: generación por lotes…',
    'no es un documento .greport.md',
    'no se pudo analizar el informe',
    'no se encontró el origen de datos',
    'no se pudo leer la lista de parámetros',
    'La generación por lotes necesita un documento .%@',
    'Elegir una lista de parámetros (CSV o JSON)',
    'Elegir una carpeta para %d {one=informe|other=informes}',
    '[%d/%d] %@',
    'faltan parámetros ',
    'apunta al propio archivo de origen — se rechaza sobrescribir',
    '%d {one=bloque FALLIDO|other=bloques FALLIDOS}',
    'Lote terminado: %d {one=archivo|other=archivos} · %d fallidos',
    '%d {one=juego de parámetros no se pudo construir|other=juegos de parámetros no se pudieron construir} — mira el resumen',
    'Diagrama Mermaid: vista previa',
    'Diagrama Mermaid: insertar plantilla…',
    'Diagrama Mermaid: volver a formatear',
    'Fondo transparente',
    'Este Mac no puede rasterizar el diagrama a PNG — se necesita macOS 13. La exportación SVG sigue funcionando.',
    'Guardar PNG %@…',
    'Guardar SVG…',
    'Copiar la imagen al portapapeles',
    'Colores de marca…',
    'Colores de marca para los diagramas',
    'Cada campo es un color #rrggbb. Se guarda en «themes/mermaid-brand.json» — se puede copiar a otro Mac.',
    'Color principal',
    'Texto de los nodos',
    'Borde',
    'Enlaces',
    'Fondo al exportar',
    'Guardar e insertar %%{init}%% en el documento',
    'Colores de marca guardados',
    'Imagen del diagrama copiada al portapapeles',
    '%@ guardado — %@',
    'Este diagrama ya tiene una directiva %%{init}%% — la tuya se deja intacta.',
    '%%{init}%% insertado — el diagrama ya lleva sus propios colores',
    'Insertar los colores de marca en el diagrama',
    'Volver a formatear el diagrama Mermaid',
    'El código del diagrama ya está ordenado — no hay nada que cambiar',
    'Diagrama reformateado',
    '%d {one=diagrama reformateado|other=diagramas reformateados}',
    'Biblioteca de plantillas de diagramas',
    'Plantillas de diagrama completas',
    'Fragmentos de sintaxis',
    'Editando: %@',
    'Plantilla «%@» insertada',
    'Este documento es de solo lectura.',
    'Diagrama Mermaid',
    'Este documento no tiene ningún bloque mermaid.',
    'Marca',
    'Exportar…',
    'Todavía no hay diagramas',
    '%d {one=diagrama|other=diagramas} · %@',
    '%d/%d {one=diagrama FALLIDO|other=diagramas FALLIDOS} — diagrama %d%@',
    ', línea %d',
    'Este documento no tiene ningún bloque ```mermaid y tampoco es un archivo .mmd.',
    'Ningún diagrama ha terminado de dibujarse.',
    'No se encontró «%@» en el código del diagrama',
    'no se pudo construir el cortafuegos de red para WKWebView',
    'Reglas de asociación',
    'Una cesta por fila',
    'Dos columnas: id · artículo',
    'Forma de los datos transaccionales',
    'Columna de cesta o de id de transacción',
    'Columna de artículo',
    'Carácter separador de artículos',
    'Soporte mínimo, porcentaje',
    'Confianza mínima, porcentaje',
    'Separado por:',
    'Soporte ≥',
    '% · Confianza ≥',
    'Tabla de reglas de asociación',
    'Soporte',
    'Confianza',
    'Lift',
    'Leverage',
    'Atención',
    '%d {one=transacción|other=transacciones} · %d {one=artículo|other=artículos} · %d {one=regla|other=reglas}',
    ' — ninguna regla alcanzó los umbrales; baja el soporte o la confianza',
    ' — SE DETUVO ANTES, la tabla está INCOMPLETA',
    '%d / %d {one=transacción contiene|other=transacciones contienen} ambos lados',
    'La forma de dos columnas necesita dos columnas DISTINTAS.',
    '%d {one=fila marcada|other=filas marcadas} en %d {one=transacción que contiene|other=transacciones que contienen} «%@»',
    'CSV: reglas de asociación…',
    'Minería por grupos',
    'Columna de grupo',
    'Columna de valores',
    'Segunda columna para la correlación',
    'Criterio de clasificación',
    'Agrupar por:',
    'Valor:',
    'Clasificar por:',
    'Tabla de clasificación de grupos',
    'Grupo',
    'Filas',
    'Umbral propio',
    'MAPE',
    'r',
    'Diferencia r',
    'Nota',
    'no medible',
    '%d {one=grupo|other=grupos} · correlación global de referencia %@',
    ' · %d {one=GRUPO DESCARTADO|other=GRUPOS DESCARTADOS}',
    'Esta tabla no tiene ninguna columna de texto por la que agrupar.',
    'Esta tabla no tiene ninguna columna numérica que explorar.',
    '%d {one=fila del grupo|other=filas del grupo} «%@» {one=marcada|other=marcadas}',
    'CSV: minería por grupos…',
    '↔',
    'Pronóstico',
    'Columna de valores en el tiempo',
    'Modelo de pronóstico',
    'Número de periodos a pronosticar',
    'Veredicto frente a las líneas base',
    'Modelo:',
    'Periodos:',
    'Estación:',
    'auto',
    'Periodo estacional; déjalo vacío para detectarlo automáticamente',
    'Tabla de valores pronosticados',
    'Periodo',
    'Banda del 80 %',
    'Banda del 95 %',
    'MAE %@ · MAPE %@',
    'no calculable',
    'Esta tabla no tiene ninguna columna numérica que pronosticar.',
    'No se pudo construir un pronóstico para esta columna.',
    'La columna «%@» solo tiene %d {one=valor numérico|other=valores numéricos} — se necesitan al menos 4 para pronosticar.',
    '# La serie se lee en el orden de filas del archivo — sin reordenar, sin deducir columna temporal.\n',
    'Error de entrenamiento',
    'CSV: pronóstico de series temporales…',
    'Holt-Winters aditivo',
    'Holt-Winters multiplicativo',
    'seasonal-naive',
    'naive',
    'Columnas usadas para el agrupamiento',
    'Curva WCSS',
    'Clúster',
    'Escalado:',
    'k:',
    'eps:',
    'minPts:',
    'Selecciona al menos una columna.',
    'No hay datos suficientes para construir la curva.',
    'El codo sugiere k = %d. El WCSS SIEMPRE baja al crecer k, así que es un truco de lectura del gráfico y no un criterio estadístico — mira la curva y juzga si el quiebre es claro.',
    'WCSS según k',
    'La k-distancia sugiere eps = %@ (minPts vale por defecto 2 × número de columnas = %d). %@',
    'Distancia al k-ésimo vecino',
    'Se necesitan al menos 2 columnas numéricas para el agrupamiento.',
    'Clústeres según %@ y %@',
    ' — clústeres hallados en %d {one=dimensión|other=dimensiones}; el gráfico solo muestra las 2 primeras',
    '# ruido (cluster_id = -1): %d {one=fila|other=filas}\n',
    'CSV: agrupamiento…',
    '# --- Centros de los clústeres (unidades originales) ---\n',
    'k-means',
    'DBSCAN',
    'Matriz de correlación',
    'Método de correlación',
    'La correlación no implica causalidad.',
    'Par más fuerte: %@ ↔ %@ = %@ (n = %d). Pulsa una celda para ver el diagrama de dispersión.',
    'Ningún par es medible.',
    '%@ ↔ %@: %@ sobre %d {one=fila|other=filas}',
    'Se necesitan al menos 2 columnas numéricas para la correlación.',
    'No se pudo leer la columna «%@».',
    'CSV: matriz de correlación…',
    'Anomalías',
    'Lista de anomalías',
    'Columna:',
    'Columna numérica a examinar',
    'Método:',
    'Método de detección',
    'Método utilizado',
    'Umbral',
    'Marcar',
    'Exportar a una pestaña nueva',
    'Línea',
    'Puntuación',
    'Por qué',
    'leve',
    'moderada',
    'grave',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=fila|other=filas} (%.2f %%)',
    'Esta tabla no tiene ninguna columna numérica donde buscar anomalías.',
    '%d {one=línea anómala marcada|other=líneas anómalas marcadas}',
    'CSV: detectar anomalías…',
    '%d {one=regla, CORRECTA|other=reglas, todas CORRECTAS} · %d {one=fila|other=filas} · %.0f ms',
    '%d {one=error|other=errores} · %d {one=aviso|other=avisos} en %d {one=regla|other=reglas} · %d {one=fila|other=filas} · %.0f ms',
    'Guarda primero el documento — las reglas de calidad viven junto al archivo de datos.',
    'Aún no hay conjunto de reglas. Crea el archivo %@ y vuelve a abrir.',
    'Historial',
    'Consultas guardadas',
    'Guardar esta consulta…',
    'Guardar la consulta',
    'Ponle un nombre para encontrarla luego. Un nombre repetido sobrescribe.',
    'Por ejemplo: Ingresos por provincia',
    'No se ha introducido valor para el parámetro: %@',
    'El complemento cambió desde que lo aprobaste — GEditor se niega a ejecutarlo',
    '¿Ejecutar un complemento no aprobado?',
    'Confío en este archivo — ejecutar',
    'SIN firma',
    'Firma: %@',
    'Ruta: %@',
    'Reemplazar',
    'Reemplazar todo',
    'Texto plano',
    'Extendido (\\n \\t \\xNN)',
    'Expresión regular',
    'Distinguir mayúsculas',
    'Palabra completa',
    'Sin resultados',
    'Probar una expresión regular…',
    'Modo registro (color por nivel)',
    'Filtrar el registro por nivel…',
    'Ejecutar en toda la carpeta…',
    'Filtrar con un comando externo…',
    'Scripts…',
    'Paquetes de extensión…',
    'Ventana nueva',
    'Separar la pestaña en una ventana nueva',
    'No hay ninguna carpeta abierta',
    'Buscar un archivo en la carpeta',
    'Filtrar por nombre',
    'Archivo nuevo…',
    'Carpeta nueva…',
    'Renombrar…',
    'Mover a la papelera',
    'Mostrar en el Finder',
    'Leyendo la estructura del documento…',
    'este archivo no tiene funciones',
    'Sin coincidencias',
    'Texto plano',
    '🔒 Solo lectura',
    'Siguiendo',
    'ajuste en la columna',
    'Sintaxis',
    'Pulsa para insertar en la consulta',
    'consulta no válida',
    'clave «nombre» en la raíz',
    'clave con espacios',
    'primer elemento',
    'todos los elementos',
    'porción',
    'unión de índices',
    'todas las claves «precio» en todos los niveles',
    'todos los nodos',
    'filtrar por número',
    'filtrar por presencia',
    'Ir al primer error',
    'La columna ingresos es numérica',
    'filtrar…',
    'Cancelar',
    'Realizar el reemplazo',
    'vista previa',
    'interactivo',
    'Edición',
    'Interfaz',
    'Atajos de teclado',
    'Tamaño del texto',
    'Ancho de tabulación',
    'Indentar con tabulaciones',
    'Indentar automáticamente al saltar de línea',
    'Resaltar todos los resultados de la búsqueda',
    'Normalizar a NFC al guardar',
    'Idioma',
    'Apariencia',
    'Del sistema',
    'Claro',
    'Oscuro',
    'Tema',
    'Usar el preajuste de Notepad++',
    'Volver a las teclas por defecto',
    'Abrir el archivo de configuración',
    'Exportar el tema actual',
    'El cambio de idioma se aplica del todo en el próximo arranque.',
    'Las teclas por defecto vuelven en el próximo arranque.',
    'Vista previa de Markdown',
    'La vista previa usa el motor Markdown del sistema: todavía sin tablas ni coloreado de bloques de código.',
    'Probar una expresión regular',
    'Expresión',
    'Texto de prueba',
    'Resultado',
    'Coincidencias',
    'Qué hace esta expresión',
    'Explicar la expresión',
    'Modo de búsqueda',
    'Resultados de la búsqueda',
    'Sin coincidencias',
    ' (recortado)',
    'Mapa del documento',
    'Barra de pestañas',
    'Fila de encabezado de columnas',
    'No hay columnas',
    'Árbol del espacio de trabajo',
    'Lista de funciones y clases',
    'Resultados de la búsqueda en la carpeta',
    'Tabla de datos CSV',
    'Mesa de limpieza de datos',
    'Consulta JSONPath',
    'Lista de errores de datos',
    'Evaluador de golden set…',
    'Comparar con puntuaciones externas (JSONL)…',
    'Elegir un archivo de puntuaciones externas (JSONL: query, chunk_id, score)',
    'Renombrar el nodo seleccionado',
    'Fusionar los nodos seleccionados',
    'Dividir el nodo seleccionado',
    'Extraer el subgrafo seleccionado a una pestaña nueva',
    'No hay nada que cambiar',
    '%@ — ¿aplicar %d {one=cambio|other=cambios}?',
    '%@: %d {one=cambio|other=cambios} · Cmd-Z deshace todo el lote',
    'Pon el cursor sobre EXACTAMENTE UN nodo y vuelve a intentarlo',
    'Renombrar «%@»',
    'Todas las aristas y etiquetas que referencian este nodo cambiarán con él.',
    'Renombrar el nodo',
    'Selecciona AL MENOS DOS nodos y vuelve a intentarlo',
    'Forma canónica «%@» — la más frecuente, la más larga, con tildes',
    'Fusionar nodos',
    'Selecciona las LÍNEAS DE ARISTA que quieras mover y vuelve a intentarlo',
    'Todas las líneas seleccionadas deben tocar EXACTAMENTE UN nodo — selecciona más líneas de arista',
    'Dividir «%@» — mover %d {one=arista|other=aristas}',
    'Aristas hacia: %@',
    'Dividir el nodo',
    'Documento sin guardar — el archivo extraído necesita un sitio al lado',
    'Selecciona la parte del grafo que quieras extraer y vuelve a intentarlo',
    'Agrupar variantes de entidad → tabla de revisión',
    'Aplicar la tabla de revisión modificada',
    'Documento sin guardar — la tabla de revisión debe estar junto al archivo del grafo',
    'No se encontró ninguna variante que agrupar',
    '%d {one=grupo de variantes|other=grupos de variantes} — corrige la columna «canonical» y ejecuta «Aplicar la tabla de revisión»',
    'No hay tabla de revisión «%@» — ejecuta antes «Agrupar variantes de entidad»',
    'Tabla de revisión ilegible: %@',
    'La tabla de revisión no tiene ninguna fila que cambiar',
    'Ningún punto del grafo coincide con la tabla de revisión',
    'Agrupar variantes de entidad',
    '%d {one=cambio aplicado|other=cambios aplicados} · tabla de alias y lista de marcadores escritas junto al archivo',
    '¿Aplicar %d {one=cambio|other=cambios} al grafo?',
    '%d {one=alias|other=alias} → forma canónica.',
    'FUSIONAR nodos (no se deshace volviendo a escribir):',
    '%d {one=alias no está en el grafo y se omite|other=alias no están en el grafo y se omiten}.',
    'GraphRAG…',
    'Análisis de cobertura Fragmento ↔ Entidad',
    'Exportar el paquete de contexto (JSONL)',
    'Cobertura Fragmento ↔ Entidad ↔ Grafo',
    '- %d {one=entidad|other=entidades} · %d {one=fragmento|other=fragmentos} · %.0f %% de entidades mencionadas · %.0f %% de fragmentos con entidad',
    'Entidades que ningún fragmento menciona',
    'Fragmentos huérfanos (sin ninguna entidad)',
    'Nodos del grafo sin entidad correspondiente',
    'ninguno',
    'Método',
    'No se pudo construir la correspondencia Fragmento ↔ Entidad',
    'Evaluar la salud del grafo',
    'salud del grafo',
    'Salud %@/100 · %d {one=error|other=errores} · %d {one=inversión|other=inversiones} · %d huérfanos',
    'Híbrido con el grafo',
    'α = 1: se ignora del todo la señal del grafo, el resultado es igual a BM25 puro',
    'α alto: el grafo solo ajusta ligeramente el ranking de BM25',
    'α cerca del valor por defecto 0,7: manda BM25, el grafo ajusta',
    'α bajo: manda el grafo, BM25 solo desempata',
    'α = 0: solo la señal del grafo; los fragmentos sin entidad quedan empatados',
    'Documento sin guardar — el híbrido necesita un archivo de grafo junto al corpus',
    'No se encuentra el archivo de grafo «%@» — el híbrido lo necesita para su señal',
    'híbrido %.1f ms · %@',
    'Algoritmos…',
    'PageRank (grosor del borde)',
    'Comunidades (color de fondo)',
    'Componentes conexas',
    'Exportar la tabla de nodos a una pestaña nueva',
    '%d {one=componente|other=componentes} · la mayor con %d {one=nodo|other=nodos} · %d nodos huérfanos',
    'Este documento no es un grafo DOT',
    'No se pudo construir la tabla de nodos/aristas: %@',
    '%d {one=fila|other=filas} · %@',
    'Etiquetar',
    'Nota (opcional)',
    'Guardar el registro',
    'Exportar CSV',
    'Documento sin guardar — el evaluador debe estar junto al archivo de corpus',
    'No se pudo cargar el evaluador: %@',
    'No se pudo guardar: %@',
    'El evaluador aún no tiene ningún registro',
    'No se pudo escribir: %@',
    'Este documento no es un archivo .mmd, no es DOT y no tiene ningún bloque mermaid.',
    '%d {one=nodo|other=nodos} · %d {one=arista|other=aristas} · ⚠ %@',
    'Diagrama Mermaid: añadir un elemento…',
    'Diagrama Mermaid: conectar los dos elementos seleccionados',
    'Diagrama Mermaid: editar la etiqueta del elemento seleccionado…',
    'Diagrama Mermaid: eliminar el elemento seleccionado',
    'Diagrama Mermaid: subir el mensaje',
    'Diagrama Mermaid: bajar el mensaje',
    'Añadir un elemento',
    'Añadir un participante',
    'Añadir una entrada',
    'Añadir una entrada al diagrama',
    'Editar una entrada del diagrama',
    'Eliminar una entrada del diagrama',
    'Eliminar el elemento',
    'Editar la etiqueta',
    'Reordenar los mensajes',
    'Nombre de la entrada',
    'Entrada nueva',
    'El nombre de la entrada aparece en el diagrama.',
    'Tabla de propiedades del diagrama',
    'Este documento no tiene ningún bloque mermaid',
    'Identificador en el código del diagrama — sin espacios. La etiqueta se edita después con doble clic.',
    'Si se deja vacío, se muestra el propio identificador.',
    'Solo cambia la ETIQUETA visible; el identificador del elemento se mantiene.',
    'No está claro qué elemento es «%@»',
    'Selecciona EXACTAMENTE DOS elementos y vuelve a intentarlo',
    'Pon el cursor sobre EXACTAMENTE UN elemento y vuelve a intentarlo',
    'Elige UN elemento para eliminar, o dos elementos unidos por una arista',
    '¿Eliminar «%@» y las %d {one=arista que lo toca|other=aristas que lo tocan}?',
    'Los nodos del otro extremo de esas aristas se conservan — se vuelven a declarar con su etiqueta si la instrucción de arista era su única declaración.',
    'El diagrama «%@» solo se edita como texto — %@',
    '%@: arrastra entre dos elementos para conectarlos, doble clic para editar la etiqueta',
    '%@: arrastra entre dos participantes para añadir un mensaje; reordena desde el menú Herramientas',
    '%@: edita en la tabla de propiedades de abajo',
    'Edición visual activada',
    '%@ · %d {one=entrada|other=entradas} — edita directamente en la tabla, cada celda es un paso de deshacer',
    'Para un gráfico circular, un número; para un gantt, lo que sigue a los dos puntos.',
    'Diagrama Mermaid: extraer el bloque a un archivo .mmd…',
    'Diagrama Mermaid: reincorporar el archivo referenciado',
    'Extraer el bloque del diagrama',
    'Reincorporar el bloque del diagrama',
    'Extraer el bloque del diagrama a un archivo aparte',
    'El archivo se coloca JUNTO al documento; el bloque conserva una línea de referencia para editar en un solo sitio.',
    'Documento sin guardar — el archivo del diagrama necesita un sitio al lado',
    'Ya existe el archivo «%@» — elige otro nombre',
    'Extraído a «%@» — el bloque conserva una línea de referencia',
    'Abrir el archivo',
    '«%@» reincorporado; el archivo sigue en el disco',
    'Este bloque contiene un diagrama real, no una referencia',
    'Este bloque referencia «%@» — abre ese archivo para editarlo',
    'No se pudo leer el archivo de diagrama %@',
    'Edición visual',
    'Arrastra de un nodo a otro para añadir una arista; doble clic para editar la etiqueta. Cada acción es un paso de deshacer.',
    'Edición visual: arrastra entre dos nodos para añadir una arista, doble clic para editar la etiqueta',
    'Edición visual desactivada',
    'Añadir un nodo…',
    'Añadir una arista entre los dos nodos seleccionados…',
    'Editar la etiqueta del nodo seleccionado…',
    'Eliminar el nodo/arista seleccionado',
    'Añadir un nodo',
    'Añadir una arista',
    'Editar la etiqueta del nodo',
    'Eliminar el nodo',
    'Eliminar la arista',
    'Cmd-Z para deshacer',
    'Este documento es de solo lectura',
    'Etiqueta de «%@»',
    'Solo cambia la ETIQUETA visible; el identificador del nodo se mantiene.',
    'No está claro qué nodo es «%@»',
    'Identificador del nodo en el archivo DOT. La etiqueta se edita después con doble clic en el gráfico.',
    'Selecciona EXACTAMENTE DOS nodos y vuelve a intentarlo',
    'Elige UN nodo para eliminarlo, o dos nodos unidos por una arista',
    '¿Eliminar el nodo «%@» y las %d {one=arista que lo toca|other=aristas que lo tocan}?',
    'Si quedan aristas huérfanas, DOT recrea los nodos a partir de ellas — el nodo eliminado reaparecerá en el siguiente dibujo.',
    'Laboratorio de recuperación BM25',
    'Pregunta — Intro para buscar',
    'Evaluar…',
    'Construyendo el índice',
    'Ningún fragmento coincide',
    'mejores resultados',
    'k1 = 0: cada palabra cuenta SOLO una vez, sin importar cuántas veces aparezca',
    'k1 bajo: repetir una palabra casi no añade puntuación',
    'k1 cerca del valor por defecto 1,2: repetir añade puntuación, pero cada vez menos',
    'k1 alto: un fragmento que repite una palabra se premia con fuerza',
    'b = 0: se ignora la longitud, los fragmentos largos no se penalizan',
    'b bajo: los fragmentos largos se penalizan solo un poco',
    'b cerca del valor por defecto 0,75: los fragmentos largos se penalizan moderadamente',
    'b = 1: penalización máxima por longitud, se favorecen los fragmentos cortos',
    'JSONL: laboratorio de recuperación…',
    'Documento sin guardar — el índice BM25 vive junto al archivo de corpus y necesita una ruta',
    'Este archivo no es JSONL — el Retrieval Lab funciona sobre un corpus de fragmentos',
    'No se pudo construir un índice BM25 para este archivo',
    'Documento sin guardar — hace falta una ruta de corpus para generar el informe',
    'Elegir un conjunto de evaluación (CSV o JSONL: pregunta + id de fragmento esperado)',
    'Evaluación de la recuperación',
    'Cambia k1, b o k arriba y vuelve a revisar para comparar dos configuraciones; añade un bloque «compare» para ejecutar dos juegos de parámetros en paralelo sobre el mismo conjunto.',
    'Error',
    '   (%d…%d, media %.0f)',
    'Modo JSONL',
    'Registro',
    'Detalle',
    'Registro en la línea',
    'no es JSON válido',
    'registros',
    'líneas en blanco',
    'no es un objeto',
    'tabla mostrada',
    'CANCELADO a medias',
    'Sin filtro',
    'registros que coinciden con el filtro',
    'Pon el cursor en una línea para ver el registro',
    'No hay registros defectuosos',
    'Todavía sin inspeccionar. Vuelve a ejecutar «JSONL: inspeccionar fragmentos» tras la comprobación.',
    'campo de texto',
    'ESQUEMA (deducido — se cambia eligiendo otro campo)',
    'texto',
    'identificador',
    'metadatos anidados',
    'CAMPO',
    'cobertura',
    'varios tipos',
    'LONGITUD — caracteres',
    'LONGITUD — palabras',
    'LONGITUD — tokens estimados',
    'VACÍOS Y DUPLICADOS',
    'fragmentos vacíos',
    'líneas',
    'grupos de duplicados exactos',
    'líneas ilegibles, fuera de las estadísticas',
    'MÉTODO',
    '«caracteres» cuenta caracteres Unicode (escalares), no grupos visibles',
    '«palabras» separa por espacios ASCII',
    '«tokens» cuenta con un separador de sílabas — NO es el del modelo',
    '«duplicado» significa duplicado EXACTO; los casi duplicados están en el bloque ```quality',
    'fragmentos',
    'JSONL: comprobar e inspeccionar fragmentos…',
    'Imagen',
    'PDF',
    'Documento de Word',
    'Hoja de cálculo de Excel',
    'Presentación de PowerPoint',
    'Archivo comprimido',
    'Ajustar a la ventana',
    'Copiar la imagen',
    'Rotar',
    'No se puede leer la imagen «%@»',
    'Imagen copiada al portapapeles',
    'Resaltar en amarillo',
    'Subrayar',
    'Nota…',
    'Quitar las anotaciones',
    'Extraer el texto a una pestaña nueva',
    'Guardar la versión anotada…',
    'Buscar en el PDF',
    'Añadir',
    'Página %d/%d',
    'Página %d',
    'Resultado %d/%d',
    '0 resultados',
    'No se puede leer el PDF «%@»',
    'Este PDF tiene contraseña — no se puede acceder al contenido',
    'No se encuentra «%@» en el documento',
    'Resaltado',
    'Subrayado',
    'Selecciona antes un fragmento de texto',
    'Nota añadida',
    'Esta página no tiene ninguna anotación',
    '%d {one=anotación quitada|other=anotaciones quitadas} de esta página',
    'Este PDF no tiene capa de texto — probablemente sea un escaneo',
    'No se pudo escribir el archivo',
    'El archivo escrito NO se vuelve a abrir bien — no uses esta versión',
    '%@ guardado · %d {one=página|other=páginas}',
    'Nombre',
    'Tamaño',
    'Comprimido',
    'Proporción',
    'Modificado el',
    'Abrir el elemento seleccionado',
    'Extraer a una carpeta…',
    'Extraer aquí',
    '%d {one=elemento|other=elementos}',
    'extraído a %@',
    '— el interior de un archivo de Office es un comprimido; estas son sus partes',
    '%d {one=elemento extraído|other=elementos extraídos}',
    '%d {one=elemento defectuoso|other=elementos defectuosos}',
    '%d {one=elemento RECHAZADO|other=elementos RECHAZADOS} porque sus rutas salen de la carpeta de destino',
    'No se puede abrir este elemento',
    'Todavía no se puede escribir directamente en un %@ — usa «Guardar como…»',
    'No ha cambiado nada',
    '%d {one=celda escrita|other=celdas escritas} en %@',
    '%d {one=párrafo escrito|other=párrafos escritos} en %@',
    'No se pudo escribir en el archivo — el original queda intacto',
    'preparar el caso de prueba',
    'No se puede escribir settings.json',
    'Girar a la izquierda',
    'Girar a la derecha',
    'Subir página',
    'Bajar página',
    'Eliminar páginas…',
    'Eliminar páginas',
    'Extraer páginas…',
    'Extraer páginas a un archivo nuevo',
    'Combinar archivo PDF…',
    'Dividir archivo…',
    'Dividir archivo PDF',
    'Exportar imágenes…',
    'Exportar páginas como imágenes PNG',
    'Deshacer edición de página',
    'Guardar copia editada…',
    'Reproducir',
    'Pausa',
    'Vista normal',
    'Elegir hoja',
    'Abrir hoja',
    'Descartar y cambiar de hoja',
    'El libro tiene %d hojas.',
    'Este libro solo tiene una hoja: «%@»',
    '¿Descartar los cambios sin guardar de esta hoja?',
    'Cambiar de hoja reemplaza toda la pestaña. Lo editado sin guardar con ⌘S se perderá.',
    'Elige el PDF que se combinará',
    'Elige la carpeta para las imágenes',
    'Elige dónde guardar. El segundo archivo se escribe junto a este.',
    'El documento tiene %d páginas. Escribe las páginas a eliminar, p. ej. 2-4,7',
    'El documento tiene %d páginas. Escribe las páginas a extraer, p. ej. 1-3,8',
    'El documento tiene %d páginas. Escribe las páginas a exportar, p. ej. 1-3',
    'El documento tiene %d páginas. Escribe la parte a separar, p. ej. 1-5; el resto será un segundo archivo.',
    'Página %d girada',
    'Páginas %@ eliminadas · quedan %d páginas',
    '%d páginas combinadas de «%@»',
    'Dividido en %@ (%d páginas) y %@ (%d páginas)',
    'Se escribió %@ — %@ · %d páginas',
    '%d imágenes exportadas a %@',
    'Solo se exportaron %d de %d imágenes',
    'Se deshizo una operación de página',
    'No quedan operaciones de página que deshacer',
    'No se pueden eliminar TODAS las páginas: un PDF debe conservar al menos una',
    'Ese intervalo es todo el documento: no hay nada que separar',
    '«%@» está protegido con contraseña: no se puede combinar',
    '«%@» no tiene páginas',
    'Ya en la primera página',
    'Ya en la última página',
    '· editado, sin guardar',
    'Imagen animada · %d fotogramas',
    'Documento sin guardar: no hay archivo en el disco para ver en binario',
    'Este comando solo funciona con libros de Excel',
    'No se pudo leer la lista de hojas',
    'No hay ninguna hoja llamada «%@»',
    'No se pudo leer la hoja «%@»',
    'Hoja «%@» · %d filas',
    'el resto',
    'Nota',
    'Precaución',
    'Véase también',
    'Copiar',
    'Copiado',
    'Copiar el código de ejemplo',
    'Buscar en la ayuda',
    'Atrás',
    'Empezar',
    'No mostrar esta ventana al iniciar',
    'La ayuda aún no está traducida a este idioma; se muestra en vietnamita.',
    'Ir al desplazamiento (p. ej. 1F400 o 0x1F400)',
    'Copiar las filas seleccionadas',
    '%d filas copiadas',
    'No se pudo leer «%@»',
    'Archivo vacío',
    'No se pudo leer el desplazamiento «%@»',
    'El desplazamiento 0x%@ supera el tamaño del archivo',
    'Abrir con otra app…',
    '%d canales',
    'No se puede reproducir «%@»',
    'No se puede reproducir — %@',
    'macOS no incluye un decodificador para el formato %@: es un límite del sistema, no un archivo dañado.',
    'Aún puedes ver los bytes en modo binario o abrirlo con una app que tenga su propio decodificador.',
    'Firmar…',
    'Editar texto…',
    'Editar texto',
    'Dibujar encima',
    'Siguiente campo vacío',
    'Borrar lo rellenado',
    'Este archivo no tiene campos de formulario',
    'Se borraron %d campos de formulario',
    'Todos los campos de formulario ya tienen valor',
    'Quedan %d campos vacíos',
    'Formulario rellenable: %d campos. Escribe directamente y luego «Guardar copia editada…»',
    'Elige una imagen de firma (con fondo transparente queda mejor)',
    'No se pudo crear la página firmada',
    'Firma insertada en la página %d',
    'Primero selecciona el texto que quieres cambiar',
    'La selección es demasiado pequeña',
    'El texto nuevo se DIBUJA ENCIMA de la selección con la tipografía del sistema. El texto antiguo queda tapado, no eliminado: aún se puede extraer, así que esto no es una censura.',
    'No se pudo crear la página editada',
    'Se dibujó el texto nuevo en la página %d',
    'Cambiar Vista / Código',
    'Todavía no hay vista de árbol para JSON · XML · YAML',
    'Todavía no hay vista de diagrama en la pestaña',
    'Todavía no hay vista de esquema para PowerPoint',
    'Este archivo solo tiene un modo de visualización',
    '%d nodos',
    'No se pudo construir el árbol: %@',
    'El documento es demasiado grande para el árbol: usa el modo Código',
]
