# Bản dịch fi — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code fi --name "…" scripts/ban-dich/fi.py
VALS = [
    'Tallennetut versiot…',
    'Tätä dokumenttia ei ole koskaan tallennettu — ei historiaa',
    'Ei aiempia tallennettuja versioita',
    'Tuota versiota ei voi lukea',
    'Palauta tallennettu versio',
    'XML: tarkista DTD/XSD:tä vasten…',
    'Tässä Macissa ei ole libxml2:ta, joten XSD-tarkistus ei ole käytettävissä.',
    'Valitse XSD-skeema tarkistusta varten',
    'Kelpaa seuraavan mukaan:',
    'Liitännäinen päättyi muuttamatta mitään',
    'Natiiveja liitännäisiä ei ole asennettu',
    'Poista tämä liitännäinen',
    'Poistetaanko tämä liitännäinen?',
    'Poista',
    'Asenna natiivi liitännäinen…',
    'Avaa liitännäisten kansio',
    'Valitse liitännäisen .dylib-tiedosto',
    'Asennettu:',
    'Poistettu:',
    'Natiivit liitännäiset…',
    'Vain .dylib-tiedostot kelpaavat.',
    'Samanniminen liitännäinen on jo asennettu:',
    'Liitännäistä ei voi kopioida:',
    'Natiivit liitännäiset ovat vain suoraan ladattavassa versiossa, eivät App Store -versiossa.',
    'Liitännäisten apuprosessia ei löytynyt.',
    'Apuprosessia ei voi käynnistää:',
    'Liitännäisen prosessi pysähtyi kesken.',
    'Liitännäinen ei vastannut ajoissa — se pysäytettiin.',
    'Liitännäinen lähetti virheellisen viestin:',
    'Liitännäinen ilmoitti virheestä:',
    'Tietoja GEditorista',
    'Asetukset…',
    'Lopeta GEditor',
    'Arkisto',
    'Uusi välilehti',
    'Sulje välilehti',
    'Seuraava välilehti',
    'Edellinen välilehti',
    'Uusi dokumentti',
    'Avaa…',
    'Avaa kansio työtilaksi…',
    'Avaa viimeaikaiset',
    'Tallenna',
    'Tallenna nimellä…',
    'Poista rivin lopun välilyönnit tallennettaessa',
    'Seuraa tiedostoa (tail -f)',
    'Tulosta…',
    'Avaa suljettu välilehti uudelleen',
    'Ei tiedostoja',
    'Tyhjennä luettelo',
    'Muokkaa',
    'Kumoa',
    'Tee uudelleen',
    'Leikkaa',
    'Kopioi',
    'Sijoita',
    'Leikepöydän historia…',
    'Sarakemuokkain…',
    'Valitse seuraava osuma',
    'Valitse kaikki',
    'Kahdenna rivi',
    'Poista rivi',
    'Kommentoi rivi pois',
    'Tässä istunnossa ei ole kopioitu mitään',
    'Tyhjennä historia',
    'Etsi',
    'Etsi…',
    'Etsi ja korvaa…',
    'Etsi kansiosta…',
    'Korvaa kansiossa…',
    'Seuraava tulos',
    'Edellinen tulos',
    'Siirry riville…',
    'Siirry vastaavaan sulkuun',
    'Merkitse kaikki osuvat rivit…',
    'Käännä merkinnät',
    'Poista kaikki merkinnät',
    'Kopioi merkityt rivit',
    'Poista merkityt rivit',
    'Säilytä vain merkityt rivit',
    'Rivit',
    'Lajittele A→Ö',
    'Lajittele Ö→A',
    'Luonnollinen lajittelu',
    'Poista kaksoiskappaleet',
    'Käännä rivien järjestys',
    'Siirrä rivi ylös',
    'Siirrä rivi alas',
    'Yhdistä rivit',
    'Jaa rivit pituuden mukaan…',
    'Jaa rivit merkin mukaan…',
    'Poista tyhjät rivit',
    'Tiivistä peräkkäiset tyhjät rivit',
    'Poista rivin lopun välilyönnit',
    'Sarkain → välilyönti',
    'Välilyönti → sarkain',
    'SUURAAKKOSET',
    'pienaakkoset',
    'Iso Alkukirjain Joka Sanassa',
    'Iso alkukirjain virkkeessä',
    'kÄÄNNÄ kIRJAINKOKO',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: valitse taulukko…',
    'Vaihda taulukko- ja tekstinäkymän välillä',
    'Poista sarake…',
    'Tarkista data (sarakkeiden määrä · tyypit)',
    'Datan puhdistuspenkki…',
    'Suorita puhdistusresepti…',
    'Muunna…',
    'Vaihda erotinmerkki…',
    'Vie JSON-muotoon…',
    'Muoto',
    'Merkistö…',
    'Rivinvaihdot…',
    'Normalisoi Unicode…',
    'JSON: muotoile',
    'JSON: tiivistä yhdelle riville',
    'JSON: lajittele avaimet',
    'JSON: JSONPath-kysely…',
    'CSV: SQL-kysely…',
    'SQL-kysely',
    'Suoritetaan…',
    'Vie uuteen välilehteen',
    'Tyhjä dokumentti — ei taulukkoa kyseltäväksi',
    'Ei ole CSV-taulukko — ensimmäisellä rivillä on vain yksi sarake',
    'Kyselyä ei voi lukea',
    'Kyselyä ei voi tarkistaa',
    'Keltainen (oletus)',
    'Sininen',
    'Vihreä',
    'Okra',
    'Violetti',
    'Vaaleanpunainen',
    'Turkoosi',
    'Oranssi',
    'Liuske',
    'Teksti',
    'Lukusarja',
    'Päivämääräsarja',
    'SUURAAKKOSET (heksadesimaali)',
    'Alku',
    'Askel',
    'Täytä nollilla pituuteen',
    'Kantaluku',
    'Ensimmäinen päivämäärä',
    'Muoto',
    'Lisää',
    'Kumoa',
    'Muunna muoto',
    'Esikatsele 5 ensimmäistä riviä',
    'Avaa uuteen välilehteen',
    'Tallenna tiedostoon…',
    'Tulos avautuu uuteen, tallentamattomaan välilehteen. Alkuperäiseen dokumenttiin ei kosketa.',
    'Suorita tälle dokumentille',
    'Suorita kansiolle…',
    'Koko resepti on YKSI kumoamisaskel. Levyllä olevaan tiedostoon ei kosketa ennen kuin tallennat.',
    'pois',
    'saraketta ei löytynyt',
    'valmis',
    'se varaa yhä yhden suoritinytimen, kunnes ohjelma lopetetaan.',
    'Skripti ei palauttanut mitään',
    'JavaScript-moottoria ei voi luoda',
    'Tuntematon JavaScript-virhe',
    'Taulukko',
    'Käytä lajittelua tiedostoon',
    'Muunna ▾',
    'Vie osuvat rivit',
    'Kätke tämä sarake',
    'Nimeä otsikko uudelleen…',
    'Lisää tyhjä sarake vasemmalle',
    'Lisää tyhjä sarake oikealle',
    'Poista tämä sarake tiedostosta…',
    'Vähintään yhden sarakkeen on jäätävä näkyviin',
    'Lajitellaan…',
    'Takaisin tiedoston järjestykseen',
    'sata ensimmäistä riviä',
    'sarakkeiden valinta',
    'tulossarakkeen nimeäminen',
    'suodatus tekstin mukaan',
    'tyhjät solut',
    'ehtojen yhdistäminen',
    'rivien laskeminen',
    'ryhmittely ja koonti',
    'pienin, suurin',
    'lajittelu ja rajaus',
    'sarakkeen nimi välilyönnein',
    'Kysely keskeytettiin',
    'Ei tueta: JOIN · alikysely · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · ikkunafunktiot',
    'XML: muotoile',
    'XML: tiivistä yhdelle riville',
    'XML: tarkista syntaksi',
    'YAML: tarkista toistuvat avaimet ja sisennys',
    'Näytä',
    'Näytä/kätke sivupalkki (funktioluettelo)',
    'Näytä/kätke dokumenttikartta',
    'Laskosta / avaa lohko osoittimen kohdalla',
    'Laskosta kaikki',
    'Avaa kaikki',
    'Laskosta tason mukaan',
    'Taso %d',
    '%1$d {one=lohko|other=lohkoa} laskostettu tasolla %2$d',
    'Tämä dokumentti on vain %d {one=taso|other=tasoa} syvä',
    'mermaid: manifestia ei voi lukea',
    'Tarkista päivitykset…',
    'Tarkista päivitykset',
    'App Store -versiot päivittyvät Mac App Storen kautta, eivät GEditorin kautta.',
    'Tässä koosteessa ei ole päivitysten allekirjoitusavainta, joten se ei voi etsiä niitä.',
    'Suurenna tekstiä',
    'Pienennä tekstiä',
    'Todellinen koko',
    'Jaa pystysuunnassa',
    'Jaa vaakasuunnassa',
    'Sulje jako',
    'Avaa tämä välilehti toisessa ruudussa',
    'Siirry toiseen ruutuun',
    'Rivitys (pois / ikkuna / sarake)',
    'Rivitä sarakkeen kohdalla…',
    'Merkitse tämä rivi',
    'Seuraava merkintä',
    'Edellinen merkintä',
    'Merkintöjen väri…',
    'Näytä kaikki näkymättömät merkit',
    '  Välilyönnit',
    '  Sarkaimet',
    '  Rivinvaihdot',
    '  NBSP · nollalevyinen · ohjausmerkki',
    'Binäärinäkymä',
    'CSV-tila (sarakkeet väreillä)',
    'Makro',
    'Aloita / lopeta tallennus',
    'Toista',
    'Toista useita kertoja…',
    'Toista dokumentin loppuun',
    'Suorita kaikissa välilehdissä',
    'Peru suoritettava makro',
    'Tallenna makro…',
    'Tallennetut makrot…',
    'Ohje',
    'GEditorin ohje',
    'Ominaisuuksien esittely',
    'Siirtyminen Notepad++:sta',
    'Etsi',
    'Korvaa merkinnällä',
    'Seuraava',
    'Edellinen',
    'Laske',
    'Sulje',
    'Tarkista JSON-skeemaa vasten…',
    'Valitse JSON-skeematiedosto',
    'Tämän skeeman mukaan ei löytynyt ongelmia.',
    'JSON-skeema',
    'Tarkista graafin syntaksi',
    'Graafin muotoa ei tunnistettu — tarvitaan pääte .dot, .gv, .cypher, .ttl tai .graphml.',
    '%@-syntaksivirheitä ei löytynyt (tarkistus ei ole kattava).',
    '%@-syntaksi',
    'ei ole JSON-olio',
    'Tekstinlouhinta (n-grammit, TF-IDF)',
    'Dokumentti on tyhjä.',
    'Yhtään avainsanaa ei saatu poimittua.',
    'Avainsanat',
    '%d {one=avainsana|other=avainsanaa} · %d {one=merkkijakso|other=merkkijaksoa} · %d {one=dokumentti|other=dokumenttia}',
    'Merkitse dokumenttiin',
    'Merkitse entiteetit luettelosta…',
    'Valitse entiteettiluettelo (CSV tai JSON)',
    'Entiteettiluetteloa ei voi lukea.',
    'Entiteettiluettelo on tyhjä.',
    'Dokumentista ei löytynyt entiteettejä (%d ladattu).',
    '%d {one=esiintymä|other=esiintymää} · %@',
    'Muunna tietämystä…',
    'Muunnos: %@ → %@',
    'Muuntaminen ei onnistunut.',
    'Paloittelun esikatselu…',
    'Kiinteä koko 800 tavua, limitys 100 tavua',
    'Virkkeittäin (≤ 800 tavua)',
    'Markdown-otsikoittain',
    'Tyhjä dokumentti — ei paloja.',
    '%d {one=pala|other=palaa} · keskimäärin %d tavua · %@',
    'Vie JSONL',
    'Palojen JSONL',
    'Avaa kolmikot/kaaret taulukkona',
    'Kolmikkotaulukko',
    'Tässä dokumentissa ei ole yhtään kolmikkoriviä.',
    'Yhtään kolmikkoa ei saatu luettua — rivi %d: %@',
    '%1$d {one=kolmikko|other=kolmikkoa} luettu · %2$d {one=virheellinen rivi|other=virheellistä riviä} ohitettu (ensimmäinen: rivi %3$d)',
    'Sumeat kaksoiskappaleet sarakkeittain…',
    'Sumeat kaksoiskappaleet — sarake «%1$@»: %2$d {one=ehdokasryhmä|other=ehdokasryhmää}',
    'Yhdistä',
    'Osuma',
    'Ryhmän arvot',
    'Yhdistä arvoon',
    'Yhdistä valitut ryhmät',
    'Yhtään ryhmää ei ole valittu — «Yhdistä» ei muuta MITÄÄN. Ohjelma ei koskaan yhdistä omin päin.',
    '%d {one=ryhmä|other=ryhmää} valittu · %d {one=rivi|other=riviä} muuttuu · YKSI kumoamisaskel',
    'Tätä saraketta ei voitu käydä läpi.',
    'Sarakkeessa «%@» ei ole sumeiden kaksoiskappaleiden ryhmiä.',
    'Yhtään ryhmää ei yhdistetty — dokumentti on ennallaan.',
    'Sumeiden kaksoiskappaleiden poisto · sarake %@',
    '%d {one=ryhmä|other=ryhmää} yhdistetty · %d {one=solu|other=solua} muuttui',
    'Puhdistusraportti',
    '# Puhdistusraportti — %@\n\n',
    '## Käytetty (%d)\n\n',
    '_Yhtään askelta ei ole käytetty._\n',
    '\n## Datan profiili\n\n',
    '_%1$d {one=sarake|other=saraketta} · %2$d {one=rivi|other=riviä} · käyty läpi %3$.1f sekunnissa_\n\n',
    '| Sarake | Tyyppi | Tyhjät | Eri arvoja | Pienin | Suurin | Keskiarvo |\n',
    '\n### Poikkeavat arvot\n\n',
    'rivi %d: %@',
    '- sarake «%1$@» — %2$d {one=solu|other=solua}: %3$@\n',
    '\n## Jäljellä (%d)\n\n',
    '_Havaintoja ei ole enää jäljellä._\n',
    '- sarake «%@»: %@\n',
    None,
    'Poista välilyönnit tallennettaessa',
    'Normalisoi rivinvaihdot',
    'edellinen',
    'Edellisen istunnon kansiota «%@» ei voitu avata uudelleen',
    ' (ja %d {one=tiedosto|other=tiedostoa} lisää)',
    '%d {one=välilehteä|other=välilehteä} ei voitu avata uudelleen: %@%@ — tiedostot eivät ole enää entisellä paikallaan.',
    'Syötettä putkesta ei voitu lukea',
    'Rivin lopun välilyönnit poistetaan jokaisella tallennuksella',
    'Välilyöntejä ei enää poisteta tallennettaessa',
    'Nimetön.txt',
    'Merkistön muuntaminen hävittää merkkejä',
    'Tallenna silti',
    'Dokumentissa on tallentamattomia muutoksia',
    'Sulkeminen tallentamatta hylkää ne.',
    'Hylkää muutokset',
    'Siirry riville',
    'Dokumentissa on %d {one=rivi|other=riviä}.',
    'Rivinumero',
    'Siirry',
    'Tulkitse uudelleen muodossa…',
    'Muunna muotoon…',
    'Uudelleentulkinta ei onnistunut',
    '%@ ei pysty esittämään kaikkia merkkejä',
    'Valitse silti',
    'Sarake %d',
    'Sarake %d: %@',
    'Kätketyt sarakkeet: %@ (%d) — palauta ne otsikkorivin kontekstivalikosta',
    'Näytä uudelleen: %@',
    'Sarake %@ kätketty — se on tiedostossa koskemattomana',
    'Lajiteltu: %@ %@ · vain näyttö',
    'Lajiteltu: %@ %@ (vain näyttö)',
    '%d+ riviä osuu — etsintä jatkuu…',
    '%d / %d {one=rivi|other=riviä} osuu',
    '%d rivillä ei löytynyt ongelmia',
    '%d rivillä on väärä määrä sarakkeita',
    '%d solussa on väärä tietotyyppi',
    ' (pysähtyi %d ensimmäiseen ongelmaan)',
    '   —   tunnistetut tyypit: ',
    'Rivi %1$d, sarake %2$@: «%3$@» ei ole %4$@',
    'Sarakemuokkain — %d {one=rivi|other=riviä}',
    'Havainnot',
    'Datan profiili',
    'Datan profiili — käydään läpi…',
    'Tallenna resepti…',
    'Vie raportti',
    'Yhtään ryhmää ei ole käytetty · jokainen ryhmä on yksi kumoamisaskel',
    'liian monta arvoa',
    'yleisimmät: ',
    'Arvo, jolla tyhjät solut täytetään',
    'Käytä',
    'Esikatselua ei voitu rakentaa',
    '· jätetty ennalleen, ei tulkittavissa ·',
    'Muunna sarake muotoon ISO 8601 (VVVV-KK-PP)',
    'Lukujen esitystapa koko sarakkeelle',
    'Mitä tyhjille soluille tehdään',
    'Normalisoi muotoon ISO 8601',
    'Lue monitulkintaiset solut PÄIVÄ ensin (31/12)',
    'Lue monitulkintaiset solut KUUKAUSI ensin (12/31)',
    'Ohita monitulkintaiset solut, korjaa vain varmat',
    'Vietnamilaiseen/eurooppalaiseen (1.234,56)',
    'Angloamerikkalaiseen (1,234.56)',
    'Angloamerikkalaiseen ilman tuhaterotinta (1234.56)',
    'Täytä oletusarvolla…',
    'Täytä alaspäin — ota yläpuolinen arvo',
    'Täytä ylöspäin — ota alapuolinen arvo',
    'Poista rivit, joilla tämä sarake on tyhjä',
    'Poista välilyönnit molemmista päistä',
    'Poista molemmista päistä ja tiivistä sisäiset välilyönnit',
    'Pivot-taulukko…',
    'Lähteet…',
    'Pivot-taulukko — ryhmittele sarakkeen mukaan',
    'Rivit (ryhmittely)',
    'Arvot',
    '+ Rivi',
    '+ Arvo',
    'Tyhjennä kaikki',
    'Sijoita kyselykenttään',
    'Valitse sarakkeet, joista kysely rakennetaan.',
    'Tämän taulukon sarakkeiden nimiä ei voitu lukea.',
    'Kyselyn tietolähteet',
    '«%@» — avoinna oleva dokumentti',
    '  ⚠️ tiedosto on muuttunut rekisteröinnin jälkeen',
    'Lisää tiedosto…',
    'Poista kaikki',
    'Taulukon nimeä ei voitu päätellä nimestä «%@» — nimeä tiedosto uudelleen.',
    'Summa',
    'Keskiarvo',
    'Pienin',
    'Suurin',
    'Eri arvojen määrä',
    'Kaavio',
    'Vie PNG',
    'Vie SVG',
    'Tässä taulukossa ei ole numeerista saraketta piirrettäväksi.',
    'PNG-kuvaa ei voitu rakentaa.',
    'Kyselyn tulos',
    '%@ tallennettu',
    '%1$@-kaavio kohteesta «%2$@» — %3$d {one=piste|other=pistettä}, arvot väliltä %4$@–%5$@',
    'Pylväs',
    'Viiva',
    'Histogrammi',
    'Hajonta',
    'Laatikko',
    'CSV: datan laatu…',
    'Datan laatu',
    'Vie rikkomukset uuteen välilehteen',
    'Taso',
    'Sääntö',
    'Rikkomukset',
    'Osuus',
    'läpäisi',
    'virhe',
    'varoitus',
    'rikki',
    '%d {one=rikkova rivi|other=rikkovaa riviä} merkitty',
    'Kehitys',
    'Arvioitu',
    'Rivejä',
    'Erotus',
    'Hylätyt säännöt',
    'Laatupisteet',
    'Pisteet ajan mittaan',
    'Historiaa ei vielä ole — jokainen arviointi lisää ',
    'yhden rivin sääntöjen vieressä olevaan tiedostoon «.history.jsonl».',
    '%d {one=piste|other=pistettä} historiassa',
    ' · %d {one=riviä|other=riviä} EI VOI LUKEA',
    ' · valitse kaksi riviä vertailtavaksi',
    'pisteet %+.1f',
    'yksikään ulottuvuus ei laskenut',
    'laskivat: ',
    '%d {one=vasta hylätty sääntö|other=vasta hylättyä sääntöä}: %@',
    'rivejä %+d',
    ' (ja %d {one=varoitus|other=varoitusta} lisää Kehitys-välilehdellä)',
    'Ei automaattista korjausta: ',
    'Avaa oikean työkalun puhdistuspenkissä ja arvioi sitten heti uudelleen.',
    'Käsittele puuttuvat arvot…',
    'Normalisoi päivämäärät…',
    'Poista kaksoiskappaleet…',
    'Korvaa…',
    'Näytä virheelliset rivit',
    'Saraketta «%@» ei ole tässä taulukossa.',
    'Kaksoiskappaleet poistettu — «%@» on nyt yksikäsitteinen. Pisteet: %.0f/100',
    'Kaksoiskappaleet poistettu, mutta sarakkeessa «%1$@» on yhä %2$d {one=toistuva rivi|other=toistuvaa riviä} (aiemmin: %3$d) — ',
    'ne rivit jakavat AVAIMEN mutta eivät koko riviä, joten sinun on katsottava ja valittava ',
    'kumman säilytät.',
    'Yhtään tätä sääntöä rikkovaa arvoa ei voitu lukea.',
    '%1$d {one=virheellinen arvo|other=virheellistä arvoa} sarakkeessa «%2$@» — täytä Korvaa-kenttä ja paina Esikatsele',
    'Arvioitu uudelleen: %.0f/100',
    'Raportin esikatselu',
    'Parametrit…',
    'Vie HTML…',
    'Tulosta / PDF…',
    '%d {one=lohko|other=lohkoa} suoritettu · %d {one=lohko|other=lohkoa} EPÄONNISTUI',
    '%d {one=lohko|other=lohkoa} suoritettu',
    ' · VANHENTUNUT DATA — lähdetiedosto on muuttunut; rakenna uudelleen',
    'Raportin esikatselu vaatii .%@-dokumentin',
    'Tietolähdettä ei löytynyt — ilmoita «source: tiedosto.csv» frontmatterissa.',
    'Raporttia ei voitu rakentaa.',
    'Tämä raportti ei ilmoita yhtään parametria frontmatterissa.',
    'Raportin parametrit',
    'Rakenna uudelleen',
    '%@ viety',
    'Raportti: esikatselu',
    'Raportti: erätuotanto…',
    'ei ole .greport.md-dokumentti',
    'raporttia ei voitu jäsentää',
    'lähdedataa ei löytynyt',
    'parametriluetteloa ei voitu lukea',
    'Erätuotanto vaatii .%@-dokumentin',
    'Valitse parametriluettelo (CSV tai JSON)',
    'Valitse kansio %d {one=raportille|other=raportille}',
    '[%d/%d] %@',
    'puuttuvat parametrit ',
    'osoittaa itse lähdetiedostoon — päälle kirjoittaminen evättiin',
    '%d {one=lohko|other=lohkoa} EPÄONNISTUI',
    'Erä valmis: %d {one=tiedosto|other=tiedostoa} · %d epäonnistui',
    '%d {one=parametrijoukkoa|other=parametrijoukkoa} ei voitu rakentaa — katso yhteenveto',
    'Mermaid-kaavio: esikatselu',
    'Mermaid-kaavio: lisää malli…',
    'Mermaid-kaavio: muotoile uudelleen',
    'Läpinäkyvä tausta',
    'Tämä Mac ei osaa muuntaa kaaviota PNG-muotoon — tarvitaan macOS 13. SVG-vienti toimii yhä.',
    'Tallenna PNG %@…',
    'Tallenna SVG…',
    'Kopioi kuva leikepöydälle',
    'Brändin värit…',
    'Kaavioiden brändivärit',
    'Jokainen kenttä on väri muodossa #rrggbb. Tallennetaan tiedostoon «themes/mermaid-brand.json» — voi kopioida toiseen Maciin.',
    'Pääväri',
    'Solmujen teksti',
    'Reunus',
    'Yhteydet',
    'Tausta vietäessä',
    'Tallenna ja lisää %%{init}%% dokumenttiin',
    'Brändin värit tallennettu',
    'Kaavion kuva kopioitu leikepöydälle',
    '%@ tallennettu — %@',
    'Tässä kaaviossa on jo %%{init}%%-määre — omasi jätetään koskematta.',
    '%%{init}%% lisätty — kaavio kantaa nyt omat värinsä',
    'Lisää brändin värit kaavioon',
    'Muotoile Mermaid-kaavio uudelleen',
    'Kaavion lähde on jo siisti — mitään ei tarvitse muuttaa',
    'Kaavio muotoiltu uudelleen',
    '%d {one=kaavio|other=kaaviota} muotoiltu uudelleen',
    'Kaaviomallien kirjasto',
    'Täydelliset kaaviomallit',
    'Syntaksin palasia',
    'Muokataan: %@',
    'Malli «%@» lisätty',
    'Tämä dokumentti on vain luettavissa.',
    'Mermaid-kaavio',
    'Tässä dokumentissa ei ole yhtään mermaid-lohkoa.',
    'Brändi',
    'Vie…',
    'Ei vielä kaavioita',
    '%d {one=kaavio|other=kaaviota} · %@',
    '%1$d/%2$d {one=kaavio|other=kaaviota} EPÄONNISTUI — kaavio %3$d%4$@',
    ', rivi %d',
    'Tässä dokumentissa ei ole ```mermaid-lohkoa eikä se ole .mmd-tiedosto.',
    'Yhtään kaaviota ei ole vielä piirretty valmiiksi.',
    '«%@» ei löytynyt kaavion lähteestä',
    'verkkoestoa WKWebView:lle ei voitu rakentaa',
    'Assosiaatiosäännöt',
    'Yksi kori riviä kohden',
    'Kaksi saraketta: tunnus · nimike',
    'Tapahtumadatan muoto',
    'Korisarake tai tapahtumatunnuksen sarake',
    'Nimikesarake',
    'Nimikkeitä erottava merkki',
    'Pienin support, prosenttia',
    'Pienin confidence, prosenttia',
    'Erottimena:',
    'Support ≥',
    '% · Confidence ≥',
    'Assosiaatiosääntöjen taulukko',
    'Support',
    'Confidence',
    'Lift',
    'Leverage',
    'Huomio',
    '%d {one=tapahtuma|other=tapahtumaa} · %d {one=nimike|other=nimikettä} · %d {one=sääntö|other=sääntöä}',
    ' — yksikään sääntö ei yltänyt kynnyksiin; laske support- tai confidence-arvoa',
    ' — PYSÄHTYI ENNENAIKAISESTI, taulukko on VAJAA',
    '%d / %d {one=tapahtuma|other=tapahtumaa} sisältää molemmat puolet',
    'Kahden sarakkeen muoto vaatii kaksi ERI saraketta.',
    '%1$d {one=rivi|other=riviä} merkitty %2$d tapahtumassa, jotka sisältävät «%3$@»',
    'CSV: assosiaatiosäännöt…',
    'Ryhmittäinen louhinta',
    'Ryhmittelysarake',
    'Arvosarake',
    'Toinen sarake korrelaatiota varten',
    'Järjestystapa',
    'Ryhmittele:',
    'Arvo:',
    'Järjestä:',
    'Ryhmien järjestystaulukko',
    'Ryhmä',
    'Rivejä',
    'Oma kynnys',
    'MAPE',
    'r',
    'r-ero',
    'Muistiinpano',
    'ei mitattavissa',
    '%d {one=ryhmä|other=ryhmää} · kokonaisviitekorrelaatio %@',
    ' · %d {one=RYHMÄ|other=RYHMÄÄ} JÄTETTY POIS',
    'Tässä taulukossa ei ole tekstisaraketta ryhmittelyyn.',
    'Tässä taulukossa ei ole numeerista saraketta louhittavaksi.',
    '%1$d {one=rivi|other=riviä} ryhmästä «%2$@» merkitty',
    'CSV: ryhmittäinen louhinta…',
    '↔',
    'Ennuste',
    'Arvosarake ajan mittaan',
    'Ennustemalli',
    'Ennustettavien jaksojen määrä',
    'Tuomio vertailumalleihin nähden',
    'Malli:',
    'Jaksoja:',
    'Kausi:',
    'auto',
    'Kausivaihtelun jakso; jätä tyhjäksi automaattista tunnistusta varten',
    'Ennustettujen arvojen taulukko',
    'Jakso',
    '80 %:n väli',
    '95 %:n väli',
    'MAE %@ · MAPE %@',
    'ei laskettavissa',
    'Tässä taulukossa ei ole numeerista saraketta ennustettavaksi.',
    'Tälle sarakkeelle ei voitu rakentaa ennustetta.',
    'Sarakkeessa «%1$@» on vain %2$d {one=numeerinen arvo|other=numeerista arvoa} — ennusteeseen tarvitaan vähintään 4.',
    '# Sarja luetaan täsmälleen tiedoston riviväljestyksessä — ilman uudelleenlajittelua ja ilman aikasarakkeen päättelyä.\n',
    'Opetusvirhe',
    'CSV: aikasarjaennuste…',
    'Holt-Winters additiivinen',
    'Holt-Winters multiplikatiivinen',
    'seasonal-naive',
    'naive',
    'Klusterointiin menevät sarakkeet',
    'WCSS-käyrä',
    'Klusteri',
    'Skaalaus:',
    'k:',
    'eps:',
    'minPts:',
    'Valitse vähintään yksi sarake.',
    'Käyrän rakentamiseen ei ole tarpeeksi dataa.',
    'Kyynärpää ehdottaa k = %d. WCSS laskee AINA k:n kasvaessa, joten tämä on tapa lukea kuvaajaa eikä tilastollinen kriteeri — katso käyrää ja arvioi, onko taite selvä.',
    'WCSS k:n mukaan',
    'k-etäisyys ehdottaa eps = %1$@ (minPts on oletuksena 2 × sarakkeiden määrä = %2$d). %3$@',
    'Etäisyys k:nteen naapuriin',
    'Klusterointiin tarvitaan vähintään 2 numeerista saraketta.',
    'Klusterit sarakkeiden %@ ja %@ mukaan',
    ' — klusterit löytyivät %d {one=ulottuvuudesta|other=ulottuvuudesta}; kuvaaja näyttää vain 2 ensimmäistä',
    '# kohina (cluster_id = -1): %d {one=rivi|other=riviä}\n',
    'CSV: klusterointi…',
    '# --- Klustereiden keskipisteet (alkuperäiset yksiköt) ---\n',
    'k-means',
    'DBSCAN',
    'Korrelaatiomatriisi',
    'Korrelaatiomenetelmä',
    'Korrelaatio ei tarkoita syy-yhteyttä.',
    'Vahvin pari: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Napsauta solua nähdäksesi hajontakuvion.',
    'Yhtään paria ei voi mitata.',
    '%1$@ ↔ %2$@: %3$@ %4$d rivillä',
    'Korrelaatioon tarvitaan vähintään 2 numeerista saraketta.',
    'Saraketta «%@» ei voi lukea.',
    'CSV: korrelaatiomatriisi…',
    'Poikkeamat',
    'Poikkeamien luettelo',
    'Sarake:',
    'Tutkittava numeerinen sarake',
    'Menetelmä:',
    'Havaitsemismenetelmä',
    'Käytetty menetelmä',
    'Kynnys',
    'Merkitse',
    'Vie uuteen välilehteen',
    'Rivi',
    'Pisteet',
    'Miksi',
    'lievä',
    'kohtalainen',
    'vakava',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=rivi|other=riviä} (%.2f %%)',
    'Tässä taulukossa ei ole numeerista saraketta, josta etsiä poikkeamia.',
    '%d {one=poikkeava rivi|other=poikkeavaa riviä} merkitty',
    'CSV: etsi poikkeamia…',
    '%1$d {one=sääntö, LÄPÄISI|other=sääntöä, kaikki LÄPÄISIVÄT} · %2$d {one=rivi|other=riviä} · %3$.0f ms',
    '%1$d {one=virhe|other=virhettä} · %2$d {one=varoitus|other=varoitusta} %3$d {one=säännössä|other=säännössä} · %4$d {one=rivi|other=riviä} · %5$.0f ms',
    'Tallenna dokumentti ensin — laatusäännöt ovat datatiedoston vieressä.',
    'Sääntöjoukkoa ei vielä ole. Luo tiedosto %@ ja avaa uudelleen.',
    'Historia',
    'Tallennetut kyselyt',
    'Tallenna tämä kysely…',
    'Tallenna kysely',
    'Anna sille nimi, jotta löydät sen myöhemmin. Sama nimi korvaa aiemman.',
    'Esimerkiksi: Liikevaihto maakunnittain',
    'Parametrille ei annettu arvoa: %@',
    'Liitännäinen on muuttunut hyväksymisesi jälkeen — GEditor kieltäytyy suorittamasta sitä',
    'Suoritetaanko hyväksymätön liitännäinen?',
    'Luotan tähän tiedostoon — suorita',
    'EI allekirjoitettu',
    'Allekirjoitus: %@',
    'Polku: %@',
    'Korvaa',
    'Korvaa kaikki',
    'Pelkkä teksti',
    'Laajennettu (\\n \\t \\xNN)',
    'Säännöllinen lauseke',
    'Erota isot ja pienet kirjaimet',
    'Koko sana',
    'Ei tuloksia',
    'Kokeile säännöllistä lauseketta…',
    'Lokitila (väri tason mukaan)',
    'Suodata loki tason mukaan…',
    'Suorita koko kansiolle…',
    'Suodata ulkoisella komennolla…',
    'Skriptit…',
    'Laajennuspaketit…',
    'Uusi ikkuna',
    'Irrota välilehti uuteen ikkunaan',
    'Yhtään kansiota ei ole avattu',
    'Etsi tiedostoa kansiosta',
    'Suodata nimen mukaan',
    'Uusi tiedosto…',
    'Uusi kansio…',
    'Nimeä uudelleen…',
    'Siirrä roskakoriin',
    'Näytä Finderissa',
    'Luetaan dokumentin rakennetta…',
    'tässä tiedostossa ei ole funktioita',
    'Ei osumia',
    'Pelkkä teksti',
    '🔒 Vain luku',
    'Seurataan',
    'rivitys sarakkeen kohdalla',
    'Syntaksi',
    'Napsauta lisätäksesi kyselyyn',
    'kelvoton kysely',
    'avain «nimi» juuressa',
    'avain, jossa on välilyöntejä',
    'ensimmäinen alkio',
    'kaikki alkiot',
    'viipale',
    'indeksien unioni',
    'kaikki «hinta»-avaimet kaikilla tasoilla',
    'kaikki solmut',
    'suodata luvun mukaan',
    'suodata olemassaolon mukaan',
    'Ensimmäiseen virheeseen',
    'Sarake liikevaihto on numeerinen',
    'suodata…',
    'Kumoa',
    'Suorita korvaus',
    'esikatselu',
    'vuorovaikutteinen',
    'Muokkaus',
    'Käyttöliittymä',
    'Näppäinoikotiet',
    'Tekstin koko',
    'Sarkaimen leveys',
    'Sisennä sarkaimin',
    'Sisennä automaattisesti uudella rivillä',
    'Korosta kaikki hakutulokset',
    'Normalisoi NFC-muotoon tallennettaessa',
    'Kieli',
    'Ulkoasu',
    'Järjestelmän mukaan',
    'Vaalea',
    'Tumma',
    'Teema',
    'Käytä Notepad++-esiasetusta',
    'Takaisin oletusnäppäimiin',
    'Avaa asetustiedosto',
    'Vie nykyinen teema',
    'Kielen vaihto tulee kokonaan voimaan seuraavalla käynnistyksellä.',
    'Oletusnäppäimet palaavat seuraavalla käynnistyksellä.',
    'Markdown-esikatselu',
    'Esikatselu käyttää järjestelmän Markdown-moottoria: ei vielä taulukoita eikä koodilohkojen väritystä.',
    'Kokeile säännöllistä lauseketta',
    'Lauseke',
    'Koeteksti',
    'Tulos',
    'Osumat',
    'Mitä tämä lauseke tekee',
    'Selitä lauseke',
    'Hakutila',
    'Hakutulokset',
    'Ei osumia',
    ' (katkaistu)',
    'Dokumenttikartta',
    'Välilehtipalkki',
    'Sarakkeiden otsikkorivi',
    'Ei sarakkeita',
    'Työtilan puu',
    'Funktioiden ja luokkien luettelo',
    'Hakutulokset kansiosta',
    'CSV-datataulukko',
    'Datan puhdistuspenkki',
    'JSONPath-kysely',
    'Datavirheiden luettelo',
    'Kultajoukon arvioija…',
    'Vertaa ulkoisiin pisteisiin (JSONL)…',
    'Valitse ulkoisten pisteiden tiedosto (JSONL: query, chunk_id, score)',
    'Nimeä valittu solmu uudelleen',
    'Yhdistä valitut solmut',
    'Jaa valittu solmu',
    'Poimi valittu aligraafi uuteen välilehteen',
    'Ei mitään muutettavaa',
    '%1$@ — otetaanko %2$d {one=muutos|other=muutosta} käyttöön?',
    '%1$@: %2$d {one=muutos|other=muutosta} · Cmd-Z kumoaa koko erän',
    'Aseta osoitin TÄSMÄLLEEN YHDEN solmun päälle ja yritä uudelleen',
    'Nimeä «%@» uudelleen',
    'Kaikki tähän solmuun viittaavat kaaret ja nimiöt muuttuvat sen mukana.',
    'Nimeä solmu uudelleen',
    'Valitse VÄHINTÄÄN KAKSI solmua ja yritä uudelleen',
    'Kanoninen muoto «%@» — yleisin, pisin, tarkkeineen',
    'Yhdistä solmut',
    'Valitse siirrettävät KAARIRIVIT ja yritä uudelleen',
    'Kaikkien valittujen rivien on kosketettava TÄSMÄLLEEN YHTÄ solmua — valitse lisää kaaririvejä',
    'Jaa «%1$@» — siirrä %2$d {one=kaari|other=kaarta}',
    'Kaaret kohteeseen: %@',
    'Jaa solmu',
    'Dokumenttia ei ole tallennettu — poimitulle tiedostolle tarvitaan paikka viereen',
    'Valitse poimittava graafin osa ja yritä uudelleen',
    'Kokoa entiteettimuunnelmat → tarkistustaulukko',
    'Ota muokattu tarkistustaulukko käyttöön',
    'Dokumenttia ei ole tallennettu — tarkistustaulukon on oltava graafitiedoston vieressä',
    'Koottavia muunnelmia ei löytynyt',
    '%d {one=muunnelmaryhmä|other=muunnelmaryhmää} — korjaa sarake «canonical» ja suorita «Ota tarkistustaulukko käyttöön»',
    'Tarkistustaulukkoa «%@» ei ole — suorita ensin «Kokoa entiteettimuunnelmat»',
    'Tarkistustaulukkoa ei voi lukea: %@',
    'Tarkistustaulukossa ei ole yhtään muutettavaa riviä',
    'Yksikään graafin kohta ei vastaa tarkistustaulukkoa',
    'Kokoa entiteettimuunnelmat',
    '%d {one=muutos|other=muutosta} otettu käyttöön · aliastaulukko ja merkintäluettelo kirjoitettu tiedoston viereen',
    'Otetaanko graafiin %d {one=muutos|other=muutosta} käyttöön?',
    '%d {one=alias|other=aliasta} → kanoninen muoto.',
    'YHDISTÄ solmut (ei kumottavissa kirjoittamalla uudelleen):',
    '%d {one=aliasta|other=aliasta} ei ole graafissa ja ne ohitettiin.',
    'GraphRAG…',
    'Kattavuusanalyysi pala ↔ entiteetti',
    'Vie kontekstipaketti (JSONL)',
    'Kattavuus pala ↔ entiteetti ↔ graafi',
    '- %1$d {one=entiteetti|other=entiteettiä} · %2$d {one=pala|other=palaa} · %3$.0f %% entiteeteistä mainittu · %4$.0f %% paloista sisältää entiteetin',
    'Entiteetit, joita yksikään pala ei mainitse',
    'Orvot palat (ilman yhtään entiteettiä)',
    'Graafin solmut ilman vastaavaa entiteettiä',
    'ei mitään',
    'Menetelmä',
    'Vastaavuutta pala ↔ entiteetti ei voitu rakentaa',
    'Arvioi graafin kunto',
    'graafin kunto',
    'Kunto %1$@/100 · %2$d {one=virhe|other=virhettä} · %3$d {one=käännös|other=käännöstä} · %4$d orpoa',
    'Hybridi graafin kanssa',
    'α = 1: graafin signaali sivuutetaan kokonaan, tulos on sama kuin puhtaalla BM25:llä',
    'α korkea: graafi säätää BM25:n järjestystä vain hieman',
    'α oletusarvon 0,7 tienoilla: BM25 johtaa, graafi säätää',
    'α matala: graafi johtaa, BM25 ratkaisee vain tasatilanteet',
    'α = 0: pelkkä graafin signaali; palat ilman entiteettejä ovat tasoissa',
    'Dokumenttia ei ole tallennettu — hybridi tarvitsee graafitiedoston korpuksen viereen',
    'Graafitiedostoa «%@» ei löytynyt — hybridi tarvitsee sen signaaliaan varten',
    'hybridi %.1f ms · %@',
    'Algoritmit…',
    'PageRank (reunuksen paksuus)',
    'Yhteisöt (taustaväri)',
    'Yhtenäiset komponentit',
    'Vie solmutaulukko uuteen välilehteen',
    '%1$d {one=komponentti|other=komponenttia} · suurin %2$d {one=solmu|other=solmua} · %3$d orpoa solmua',
    'Tämä dokumentti ei ole DOT-graafi',
    'Solmu-/kaaritaulukkoa ei voitu rakentaa: %@',
    '%d {one=rivi|other=riviä} · %@',
    'Nimiöi',
    'Muistiinpano (valinnainen)',
    'Tallenna tietue',
    'Vie CSV',
    'Dokumenttia ei ole tallennettu — arvioijan on oltava korpustiedoston vieressä',
    'Arvioijaa ei voitu ladata: %@',
    'Tallennus ei onnistunut: %@',
    'Arvioijalla ei ole vielä yhtään tietuetta',
    'Kirjoittaminen ei onnistunut: %@',
    'Tämä dokumentti ei ole .mmd-tiedosto eikä DOT, eikä siinä ole mermaid-lohkoa.',
    '%d {one=solmu|other=solmua} · %d {one=kaari|other=kaarta} · ⚠ %@',
    'Mermaid-kaavio: lisää elementti…',
    'Mermaid-kaavio: yhdistä kaksi valittua elementtiä',
    'Mermaid-kaavio: muuta valitun elementin nimiötä…',
    'Mermaid-kaavio: poista valittu elementti',
    'Mermaid-kaavio: siirrä viesti ylös',
    'Mermaid-kaavio: siirrä viesti alas',
    'Lisää elementti',
    'Lisää osallistuja',
    'Lisää merkintä',
    'Lisää merkintä kaavioon',
    'Muuta kaavion merkintää',
    'Poista merkintä kaaviosta',
    'Poista elementti',
    'Muuta nimiötä',
    'Järjestä viestit uudelleen',
    'Merkinnän nimi',
    'Uusi merkintä',
    'Merkinnän nimi näkyy kaaviossa.',
    'Kaavion ominaisuustaulukko',
    'Tässä dokumentissa ei ole mermaid-lohkoa',
    'Tunniste kaavion lähteessä — ilman välilyöntejä. Nimiötä muutetaan jälkeenpäin kaksoisnapsautuksella.',
    'Jos jätät tyhjäksi, näytetään itse tunniste.',
    'Vain näkyvä NIMIÖ muuttuu; elementin tunniste pysyy samana.',
    'Ei ole selvää, mikä elementti «%@» on',
    'Valitse TÄSMÄLLEEN KAKSI elementtiä ja yritä uudelleen',
    'Aseta osoitin TÄSMÄLLEEN YHDEN elementin päälle ja yritä uudelleen',
    'Valitse YKSI poistettava elementti tai kaksi kaarella yhdistettyä elementtiä',
    'Poistetaanko «%1$@» ja sitä koskettavat %2$d {one=kaari|other=kaarta}?',
    'Näiden kaarien toisessa päässä olevat solmut säilytetään — ne esitellään uudelleen nimiöineen, jos kaarilause oli niiden ainoa esittely.',
    'Kaaviota «%1$@» muokataan vain tekstinä — %2$@',
    '%@: vedä kahden elementin välillä yhdistääksesi ne, kaksoisnapsauta muuttaaksesi nimiötä',
    '%@: vedä kahden osallistujan välillä lisätäksesi viestin; järjestystä muutetaan Työkalut-valikosta',
    '%@: muokkaa alla olevassa ominaisuustaulukossa',
    'Visuaalinen muokkaus käytössä',
    '%1$@ · %2$d {one=merkintä|other=merkintää} — muokkaa suoraan taulukossa, jokainen solu on yksi kumoamisaskel',
    'Ympyräkaaviossa se on luku; gantt-kaaviossa se, mikä tulee kaksoispisteen jälkeen.',
    'Mermaid-kaavio: poimi lohko .mmd-tiedostoon…',
    'Mermaid-kaavio: upota viitattu tiedosto takaisin',
    'Poimi kaaviolohko',
    'Upota kaaviolohko',
    'Poimi kaaviolohko omaksi tiedostokseen',
    'Tiedosto sijoitetaan dokumentin VIEREEN; lohkoon jää yksi viiterivi, jotta muokkaus tapahtuu vain yhdessä paikassa.',
    'Dokumenttia ei ole tallennettu — kaaviotiedostolle tarvitaan paikka viereen',
    'Tiedosto «%@» on jo olemassa — valitse toinen nimi',
    'Poimittu tiedostoon «%@» — lohkoon jäi viiterivi',
    'Avaa tiedosto',
    '«%@» upotettu takaisin; tiedosto on yhä levyllä',
    'Tässä lohkossa on oikea kaavio, ei viite',
    'Tämä lohko viittaa tiedostoon «%@» — avaa se muokataksesi',
    'Kaaviotiedostoa %@ ei voitu lukea',
    'Visuaalinen muokkaus',
    'Vedä solmusta toiseen lisätäksesi kaaren; kaksoisnapsauta muuttaaksesi nimiötä. Jokainen toimenpide on yksi kumoamisaskel.',
    'Visuaalinen muokkaus: vedä kahden solmun välillä lisätäksesi kaaren, kaksoisnapsauta muuttaaksesi nimiötä',
    'Visuaalinen muokkaus pois käytöstä',
    'Lisää solmu…',
    'Lisää kaari kahden valitun solmun välille…',
    'Muuta valitun solmun nimiötä…',
    'Poista valittu solmu/kaari',
    'Lisää solmu',
    'Lisää kaari',
    'Muuta solmun nimiötä',
    'Poista solmu',
    'Poista kaari',
    'Cmd-Z kumoaa',
    'Tämä dokumentti on vain luettavissa',
    'Kohteen «%@» nimiö',
    'Vain näkyvä NIMIÖ muuttuu; solmun tunniste pysyy samana.',
    'Ei ole selvää, mikä solmu «%@» on',
    'Solmun tunniste DOT-tiedostossa. Nimiötä muutetaan jälkeenpäin kaksoisnapsauttamalla kuvaa.',
    'Valitse TÄSMÄLLEEN KAKSI solmua ja yritä uudelleen',
    'Valitse YKSI poistettava solmu tai kaksi kaarella yhdistettyä solmua',
    'Poistetaanko solmu «%1$@» ja sitä koskettavat %2$d {one=kaari|other=kaarta}?',
    'Jos roikkuvia kaaria jää jäljelle, DOT luo solmut niistä uudelleen — poistettu solmu ilmestyy takaisin seuraavalla piirrolla.',
    'BM25-hakulaboratorio',
    'Kysymys — Enter hakee',
    'Arvioi…',
    'Rakennetaan hakemistoa',
    'Yksikään pala ei osu',
    'parasta tulosta',
    'k1 = 0: jokainen sana lasketaan VAIN kerran, esiintyi se kuinka monta kertaa tahansa',
    'k1 matala: sanan toistaminen ei juuri lisää pisteitä',
    'k1 oletusarvon 1,2 tienoilla: toisto lisää pisteitä, mutta yhä vähemmän',
    'k1 korkea: pala, joka toistaa sanaa monta kertaa, palkitaan voimakkaasti',
    'b = 0: pituus sivuutetaan, pitkiä paloja ei rangaista',
    'b matala: pitkiä paloja rangaistaan vain kevyesti',
    'b oletusarvon 0,75 tienoilla: pitkiä paloja rangaistaan kohtalaisesti',
    'b = 1: suurin rangaistus pituudesta, lyhyet palat ovat etusijalla',
    'JSONL: hakulaboratorio…',
    'Dokumenttia ei ole tallennettu — BM25-hakemisto on korpustiedoston vieressä ja tarvitsee siksi polun',
    'Tämä tiedosto ei ole JSONL — Retrieval Lab toimii palojen korpuksella',
    'Tälle tiedostolle ei voitu rakentaa BM25-hakemistoa',
    'Dokumenttia ei ole tallennettu — raportin luomiseen tarvitaan korpuspolku',
    'Valitse arviointijoukko (CSV tai JSONL: kysymys + odotettu palan tunnus)',
    'Haun arviointi',
    'Muuta yllä k1-, b- tai k-arvoa ja katso uudelleen vertaillaksesi kahta kokoonpanoa; lisää «compare»-lohko ajaaksesi kaksi parametrijoukkoa rinnakkain samalla arviointijoukolla.',
    'Virhe',
    '   (%d…%d, keskimäärin %.0f)',
    'JSONL-tila',
    'Tietue',
    'Yksityiskohdat',
    'Rivin tietue',
    'ei ole kelvollista JSONia',
    'tietuetta',
    'tyhjää riviä',
    'ei ole olio',
    'näytetty taulukko',
    'PERUTTU KESKEN',
    'Ei suodatusta',
    'suodattimeen osuvaa tietuetta',
    'Aseta osoitin riville nähdäksesi tietueen',
    'Ei rikkinäisiä tietueita',
    'Ei vielä tutkittu. Suorita «JSONL: tutki palat» uudelleen tarkistuksen jälkeen.',
    'tekstikenttä',
    'SKEEMA (arvattu — muuttuu valitsemalla toinen kenttä)',
    'teksti',
    'tunniste',
    'sisäkkäiset metatiedot',
    'KENTTÄ',
    'kattavuus',
    'useita tyyppejä',
    'PITUUS — merkkejä',
    'PITUUS — sanoja',
    'PITUUS — arvioituja merkkijaksoja',
    'TYHJÄT JA KAKSOISKAPPALEET',
    'tyhjää palaa',
    'riviä',
    'täsmällisten kaksoiskappaleiden ryhmää',
    'riviä ei voi lukea, tilastojen ulkopuolella',
    'MENETELMÄ',
    '«merkit» lasketaan Unicode-merkkeinä (skalaareina), ei näkyvinä ryhminä',
    '«sanat» erotellaan ASCII-välilyönnein',
    '«merkkijaksot» lasketaan tavutuserottimella — EI mallin erottimella',
    '«kaksoiskappale» tarkoittaa TÄSMÄLLISTÄ kaksoiskappaletta; lähes samat ovat lohkossa ```quality',
    'palaa',
    'JSONL: tarkista ja tutki palat…',
    'Kuva',
    'PDF',
    'Word-dokumentti',
    'Excel-taulukko',
    'PowerPoint-esitys',
    'Arkisto',
    'Sovita ikkunaan',
    'Kopioi kuva',
    'Käännä',
    'Kuvaa «%@» ei voi lukea',
    'Kuva kopioitu leikepöydälle',
    'Korosta keltaisella',
    'Alleviivaa',
    'Muistiinpano…',
    'Poista merkinnät',
    'Poimi teksti uuteen välilehteen',
    'Tallenna merkinnöillä varustettu versio…',
    'Etsi PDF:stä',
    'Lisää',
    'Sivu %d/%d',
    'Sivu %d',
    'Tulos %d/%d',
    '0 tulosta',
    'PDF-tiedostoa «%@» ei voi lukea',
    'Tämä PDF on suojattu salasanalla — sisältöön ei pääse käsiksi',
    '«%@» ei löytynyt dokumentista',
    'Korostettu',
    'Alleviivattu',
    'Valitse ensin tekstikohta',
    'Muistiinpano lisätty',
    'Tällä sivulla ei ole merkintöjä',
    '%d {one=merkintä|other=merkintää} poistettu tältä sivulta',
    'Tässä PDF:ssä ei ole tekstikerrosta — se on todennäköisesti skannaus',
    'Tiedostoa ei voitu kirjoittaa',
    'Kirjoitettu tiedosto EI avaudu oikein uudelleen — älä käytä tätä versiota',
    '%@ tallennettu · %d {one=sivu|other=sivua}',
    'Nimi',
    'Koko',
    'Pakattu',
    'Suhde',
    'Muutettu',
    'Avaa valittu kohde',
    'Pura kansioon…',
    'Pura tähän',
    '%d {one=kohde|other=kohdetta}',
    'purettu kohteeseen %@',
    '— Office-tiedoston sisus on arkisto; nämä ovat sen osat',
    '%d {one=kohde|other=kohdetta} purettu',
    '%d {one=kohde|other=kohdetta} rikki',
    '%d {one=kohde|other=kohdetta} HYLÄTTIIN, koska niiden polut menevät kohdekansion ulkopuolelle',
    'Tätä kohdetta ei voi avata',
    'Tiedostoon %@ ei voi vielä kirjoittaa suoraan — käytä «Tallenna nimellä…»',
    'Mikään ei muuttunut',
    '%1$d {one=solu|other=solua} kirjoitettu kohteeseen %2$@',
    '%1$d {one=kappale|other=kappaletta} kirjoitettu kohteeseen %2$@',
    'Tiedostoon ei voitu kirjoittaa — alkuperäinen on koskematon',
    'valmistella testitapaus',
    'Tiedostoa settings.json ei voi kirjoittaa',
    'Käännä vasemmalle',
    'Käännä oikealle',
    'Siirrä sivua ylös',
    'Siirrä sivua alas',
    'Poista sivuja…',
    'Poista sivuja',
    'Pura sivut…',
    'Pura sivut uuteen tiedostoon',
    'Yhdistä PDF-tiedosto…',
    'Jaa tiedosto…',
    'Jaa PDF-tiedosto',
    'Vie kuvat…',
    'Vie sivut PNG-kuvina',
    'Kumoa sivumuokkaus',
    'Tallenna muokattu kopio…',
    'Toista',
    'Keskeytä',
    'Tavallinen näkymä',
    'Valitse taulukko',
    'Avaa taulukko',
    'Hylkää ja vaihda taulukkoa',
    'Työkirjassa on %d taulukkoa.',
    'Tässä työkirjassa on vain yksi taulukko: ”%@”',
    'Hylätäänkö tämän taulukon tallentamattomat muutokset?',
    'Taulukon vaihto korvaa koko välilehden. ⌘S:llä tallentamaton työ menetetään.',
    'Valitse yhdistettävä PDF-tiedosto',
    'Valitse kansio kuville',
    'Valitse tallennuspaikka. Toinen tiedosto kirjoitetaan tämän viereen.',
    'Dokumentissa on %d sivua. Anna poistettavat sivut, esim. 2-4,7',
    'Dokumentissa on %d sivua. Anna purettavat sivut, esim. 1-3,8',
    'Dokumentissa on %d sivua. Anna vietävät sivut, esim. 1-3',
    'Dokumentissa on %d sivua. Anna erotettava osa, esim. 1-5; loput tulevat toiseen tiedostoon.',
    'Sivu %d käännetty',
    'Sivut %@ poistettu · %d sivua jäljellä',
    '%d sivua yhdistetty tiedostosta ”%@”',
    'Jaettu osiin %@ (%d sivua) ja %@ (%d sivua)',
    'Kirjoitettiin %@ — %@ · %d sivua',
    '%d kuvaa viety kansioon %@',
    'Vain %d/%d kuvaa vietiin',
    'Yksi sivutoiminto kumottiin',
    'Ei enää kumottavia sivutoimintoja',
    'KAIKKIA sivuja ei voi poistaa — PDF:ssä on oltava vähintään yksi sivu',
    'Tuo alue on koko dokumentti — ei mitään erotettavaa',
    '”%@” on salasanasuojattu — yhdistäminen ei onnistu',
    '”%@” ei sisällä sivuja',
    'Jo ensimmäisellä sivulla',
    'Jo viimeisellä sivulla',
    '· muokattu, ei tallennettu',
    'Animoitu kuva · %d ruutua',
    'Tallentamaton dokumentti — levyllä ei ole tiedostoa binäärinäkymään',
    'Tämä komento toimii vain Excel-työkirjoissa',
    'Taulukkoluetteloa ei voitu lukea',
    'Taulukkoa ”%@” ei ole',
    'Taulukkoa ”%@” ei voitu lukea',
    'Taulukko ”%@” · %d riviä',
    'loput',
    'Huomaa',
    'Varoitus',
    'Katso myös',
    'Kopioi',
    'Kopioitu',
    'Kopioi esimerkkikoodi',
    'Etsi ohjeesta',
    'Takaisin',
    'Aloita',
    'Älä näytä tätä ikkunaa käynnistyksessä',
    'Ohjetta ei ole vielä käännetty tälle kielelle — näytetään vietnaminkielinen teksti.',
    'Siirry siirtymään (esim. 1F400 tai 0x1F400)',
    'Kopioi valitut rivit',
    '%d riviä kopioitu',
    'Kohdetta ”%@” ei voitu lukea',
    'Tyhjä tiedosto',
    'Siirtymää ”%@” ei voitu lukea',
    'Siirtymä 0x%@ ylittää tiedoston koon',
    'Avaa toisessa apissa…',
    '%d kanavaa',
    'Kohdetta ”%@” ei voi toistaa',
    'Ei voi toistaa — %@',
    'macOS:ssä ei ole valmista dekooderia muodolle %@ — kyse on käyttöjärjestelmän rajoituksesta, ei rikkinäisestä tiedostosta.',
    'Voit silti katsoa tavut binäärinäkymässä tai avata tiedoston apissa, jolla on oma dekooderi.',
    'Allekirjoita…',
    'Muokkaa tekstiä…',
    'Muokkaa tekstiä',
    'Piirrä päälle',
    'Seuraava tyhjä kenttä',
    'Tyhjennä täytetyt arvot',
    'Tässä tiedostossa ei ole lomakekenttiä',
    '%d lomakekenttää tyhjennetty',
    'Kaikki lomakekentät on jo täytetty',
    '%d kenttää vielä tyhjänä',
    'Täytettävä lomake: %d kenttää. Kirjoita suoraan ja valitse sitten ”Tallenna muokattu kopio…”',
    'Valitse allekirjoituskuva (läpinäkyvä tausta näyttää parhaalta)',
    'Allekirjoitettua sivua ei voitu luoda',
    'Allekirjoitus lisätty sivulle %d',
    'Valitse ensin muutettava teksti',
    'Valinta on liian pieni',
    'Uusi teksti PIIRRETÄÄN valinnan päälle järjestelmäfontilla. Vanha teksti peittyy, ei poistu — sen voi yhä purkaa, joten tämä ei ole peittosensuuri.',
    'Muokattua sivua ei voitu luoda',
    'Uusi teksti piirrettiin sivun %d päälle',
    'Vaihda Näkymä / Koodi',
    'JSON-, XML- ja YAML-tiedostoille ei ole vielä puunäkymää',
    'Välilehdellä ei ole vielä kaavionäkymää',
    'PowerPointille ei ole vielä jäsennysnäkymää',
    'Tällä tiedostolla on vain yksi näyttötila',
    '%d solmua',
    'Puuta ei voitu rakentaa: %@',
    'Dokumentti on liian suuri puuksi — käytä Koodi-tilaa',
]
