# Bản dịch fr — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code fr --name "…" scripts/ban-dich/fr.py
VALS = [
    'Versions enregistrées…',
    'Ce document n’a jamais été enregistré — aucun historique',
    'Aucune version enregistrée antérieure',
    'Impossible de lire cette version',
    'Restaurer la version enregistrée',
    'XML : valider avec une DTD/XSD…',
    'Ce Mac n’a pas libxml2, la validation XSD est indisponible.',
    'Choisir un schéma XSD pour la validation',
    'Valide selon',
    'L’extension a terminé sans rien modifier',
    'Aucune extension native installée',
    'Supprimer cette extension',
    'Supprimer cette extension ?',
    'Supprimer',
    'Installer une extension native…',
    'Ouvrir le dossier des extensions',
    'Choisir le fichier .dylib de l’extension',
    'Installé :',
    'Supprimé :',
    'Extensions natives…',
    'Seuls les fichiers .dylib sont acceptés.',
    'Une extension du même nom est déjà installée :',
    'Impossible de copier l’extension :',
    'Les extensions natives ne sont disponibles que dans le téléchargement direct, pas dans la version App Store.',
    'Processus auxiliaire des extensions introuvable.',
    'Impossible de démarrer le processus auxiliaire :',
    'Le processus de l’extension s’est arrêté en cours de route.',
    'L’extension n’a pas répondu à temps — elle a été arrêtée.',
    'L’extension a répondu avec un message mal formé :',
    'L’extension a signalé une erreur :',
    'À propos de GEditor',
    'Réglages…',
    'Quitter GEditor',
    'Fichier',
    'Nouvel onglet',
    'Fermer l’onglet',
    'Onglet suivant',
    'Onglet précédent',
    'Nouveau document',
    'Ouvrir…',
    'Ouvrir un dossier comme espace de travail…',
    'Ouvrir un élément récent',
    'Enregistrer',
    'Enregistrer sous…',
    'Supprimer les espaces en fin de ligne à l’enregistrement',
    'Suivre le fichier (tail -f)',
    'Imprimer…',
    'Rouvrir l’onglet fermé',
    'Aucun fichier',
    'Vider la liste',
    'Édition',
    'Annuler',
    'Rétablir',
    'Couper',
    'Copier',
    'Coller',
    'Historique du presse-papiers…',
    'Éditeur de colonnes…',
    'Sélectionner l’occurrence suivante',
    'Tout sélectionner',
    'Dupliquer la ligne',
    'Supprimer la ligne',
    'Commenter la ligne',
    'Rien n’a été copié durant cette session',
    'Effacer l’historique',
    'Recherche',
    'Rechercher…',
    'Rechercher et remplacer…',
    'Rechercher dans un dossier…',
    'Remplacer dans un dossier…',
    'Résultat suivant',
    'Résultat précédent',
    'Aller à la ligne…',
    'Aller à la parenthèse correspondante',
    'Marquer toutes les lignes correspondantes…',
    'Inverser les marques',
    'Supprimer toutes les marques',
    'Copier les lignes marquées',
    'Supprimer les lignes marquées',
    'Ne garder que les lignes marquées',
    'Lignes',
    'Trier A→Z',
    'Trier Z→A',
    'Tri naturel',
    'Supprimer les doublons',
    'Inverser l’ordre des lignes',
    'Monter la ligne',
    'Descendre la ligne',
    'Joindre les lignes',
    'Couper les lignes selon la longueur…',
    'Couper les lignes selon un caractère…',
    'Supprimer les lignes vides',
    'Réduire les lignes vides consécutives',
    'Supprimer les espaces en fin de ligne',
    'Tab → Espace',
    'Espace → Tab',
    'MAJUSCULES',
    'minuscules',
    'Majuscule À Chaque Mot',
    'Majuscule en début de phrase',
    'iNVERSER lA cASSE',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV : choisir la feuille…',
    'Basculer vue tableau / texte',
    'Supprimer une colonne…',
    'Valider les données (nombre de colonnes · types)',
    'Atelier de nettoyage des données…',
    'Exécuter une recette de nettoyage…',
    'Convertir…',
    'Changer le séparateur…',
    'Exporter en JSON…',
    'Format',
    'Encodage…',
    'Fins de ligne…',
    'Normaliser l’Unicode…',
    'JSON : mettre en forme',
    'JSON : compacter sur une ligne',
    'JSON : trier les clés',
    'JSON : requête JSONPath…',
    'CSV : requête SQL…',
    'Requête SQL',
    'Exécution…',
    'Exporter dans un nouvel onglet',
    'Document vide — aucune table à interroger',
    'Ce n’est pas une table CSV — la première ligne n’a qu’une colonne',
    'Impossible de lire la requête',
    'Impossible de vérifier la requête',
    'Jaune (par défaut)',
    'Bleu',
    'Vert',
    'Ocre',
    'Violet',
    'Rose',
    'Turquoise',
    'Orange',
    'Ardoise',
    'Texte',
    'Suite numérique',
    'Suite de dates',
    'MAJUSCULES (hexadécimal)',
    'Début',
    'Pas',
    'Compléter par des zéros jusqu’à',
    'Base',
    'Première date',
    'Format',
    'Insérer',
    'Annuler',
    'Convertir le format',
    'Aperçu des 5 premières lignes',
    'Ouvrir dans un nouvel onglet',
    'Enregistrer dans un fichier…',
    'Le résultat s’ouvre dans un nouvel onglet non enregistré. Le document d’origine reste intact.',
    'Exécuter sur ce document',
    'Exécuter sur un dossier…',
    'Toute la recette est UNE seule annulation. Le fichier sur le disque reste intact jusqu’à l’enregistrement.',
    'désactivé',
    'colonne introuvable',
    'prêt',
    'il continue d’occuper un cœur du processeur jusqu’à la fermeture de l’application.',
    'Le script n’a rien renvoyé',
    'Impossible de créer le moteur JavaScript',
    'Erreur JavaScript inconnue',
    'Table',
    'Appliquer le tri au fichier',
    'Convertir ▾',
    'Exporter les lignes correspondantes',
    'Masquer cette colonne',
    'Renommer l’en-tête…',
    'Insérer une colonne vide à gauche',
    'Insérer une colonne vide à droite',
    'Supprimer cette colonne du fichier…',
    'Au moins une colonne doit rester visible',
    'Tri en cours…',
    'Revenir à l’ordre du fichier',
    'cent premières lignes',
    'choisir des colonnes',
    'nommer une colonne de résultat',
    'filtrer par texte',
    'cellules vides',
    'combiner des conditions',
    'compter les lignes',
    'regrouper et agréger',
    'minimum, maximum',
    'trier et limiter',
    'nom de colonne avec espaces',
    'La requête a été interrompue',
    'Non pris en charge : JOIN · sous-requête · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · fonctions de fenêtrage',
    'XML : mettre en forme',
    'XML : compacter sur une ligne',
    'XML : vérifier la syntaxe',
    'YAML : vérifier les clés en double et l’indentation',
    'Affichage',
    'Afficher/masquer la barre latérale (liste des fonctions)',
    'Afficher/masquer la carte du document',
    'Plier / déplier le bloc au curseur',
    'Tout plier',
    'Tout déplier',
    'Plier par niveau',
    'Niveau %d',
    '%d {one=bloc plié|other=blocs pliés} au niveau %d',
    'Ce document ne fait que %d {one=niveau|other=niveaux} de profondeur',
    'mermaid : manifeste illisible',
    'Rechercher les mises à jour…',
    'Rechercher les mises à jour',
    'Les versions App Store se mettent à jour via le Mac App Store, pas via GEditor.',
    'Cette version n’a pas de clé de signature de mise à jour, elle ne peut donc pas en rechercher.',
    'Agrandir le texte',
    'Réduire le texte',
    'Taille réelle',
    'Diviser verticalement',
    'Diviser horizontalement',
    'Fermer la division',
    'Ouvrir cet onglet dans l’autre volet',
    'Aller à l’autre volet',
    'Retour à la ligne (désactivé / fenêtre / colonne)',
    'Retour à la ligne à la colonne…',
    'Marquer cette ligne',
    'Marque suivante',
    'Marque précédente',
    'Couleur des marques…',
    'Afficher tous les caractères invisibles',
    '  Espaces',
    '  Tabulations',
    '  Fins de ligne',
    '  NBSP · largeur nulle · contrôle',
    'Vue binaire',
    'Mode CSV (colonnes en couleurs)',
    'Macro',
    'Démarrer / arrêter l’enregistrement',
    'Lire',
    'Lire plusieurs fois…',
    'Lire jusqu’à la fin du document',
    'Exécuter sur tous les onglets',
    'Annuler la macro en cours',
    'Enregistrer la macro…',
    'Macros enregistrées…',
    'Aide',
    'Aide de GEditor',
    'Découverte des fonctionnalités',
    'Migrer depuis Notepad++',
    'Rechercher',
    'Remplacer par',
    'Suivant',
    'Précédent',
    'Compter',
    'Fermer',
    'Valider avec un schéma JSON…',
    'Choisir un fichier de schéma JSON',
    'Aucun problème trouvé selon ce schéma.',
    'Schéma JSON',
    'Vérifier la syntaxe du graphe',
    'Format de graphe non reconnu — une extension .dot, .gv, .cypher, .ttl ou .graphml est requise.',
    'Aucune erreur de syntaxe %@ trouvée (la vérification n’est pas exhaustive).',
    'Syntaxe %@',
    'n’est pas un objet JSON',
    'Fouille de texte (n-grammes, TF-IDF)',
    'Le document est vide.',
    'Aucun mot-clé n’a pu être extrait.',
    'Mots-clés',
    '%d {one=mot-clé|other=mots-clés} · %d {one=jeton|other=jetons} · %d {one=document|other=documents}',
    'Marquer dans le document',
    'Marquer des entités depuis une liste…',
    'Choisir une liste d’entités (CSV ou JSON)',
    'Impossible de lire la liste d’entités.',
    'La liste d’entités est vide.',
    'Aucune entité trouvée dans le document (%d chargées).',
    '%d {one=occurrence|other=occurrences} · %@',
    'Convertir des connaissances…',
    'Conversion : %@ → %@',
    'Conversion impossible.',
    'Aperçu du découpage…',
    'Taille fixe 800 o, chevauchement 100 o',
    'Par phrase (≤ 800 o)',
    'Par titre Markdown',
    'Document vide — aucun segment.',
    '%d {one=segment|other=segments} · %d o en moyenne · %@',
    'Exporter en JSONL',
    'Segments JSONL',
    'Ouvrir les triplets/arêtes sous forme de table',
    'Table de triplets',
    'Ce document ne contient aucune ligne de triplet.',
    'Aucun triplet n’a pu être lu — ligne %d : %@',
    '%d {one=triplet lu|other=triplets lus} · %d {one=ligne mal formée ignorée|other=lignes mal formées ignorées} (première : ligne %d)',
    'Doublons approximatifs par colonne…',
    'Doublons approximatifs — colonne « %@ » : %d {one=groupe candidat|other=groupes candidats}',
    'Fusionner',
    'Correspondance',
    'Valeurs du groupe',
    'Fusionner vers',
    'Fusionner les groupes sélectionnés',
    'Aucun groupe sélectionné — Fusionner ne changera RIEN. L’application ne fusionne jamais d’elle-même.',
    '%d {one=groupe sélectionné|other=groupes sélectionnés} · %d {one=ligne changera|other=lignes changeront} · UNE seule annulation',
    'Impossible d’analyser cette colonne.',
    'La colonne « %@ » n’a aucun groupe de doublons approximatifs.',
    'Aucun groupe fusionné — le document est inchangé.',
    'Déduplication approximative · colonne %@',
    '%d {one=groupe fusionné|other=groupes fusionnés} · %d {one=cellule modifiée|other=cellules modifiées}',
    'Rapport de nettoyage',
    '# Rapport de nettoyage — %@\n\n',
    '## Appliqué (%d)\n\n',
    '_Aucune étape appliquée._\n',
    '\n## Profil des données\n\n',
    '_%d {one=colonne|other=colonnes} · %d {one=ligne|other=lignes} · analysé en %.1f s_\n\n',
    '| Colonne | Type | Null | Distinct | Min | Max | Moyenne |\n',
    '\n### Valeurs aberrantes\n\n',
    'ligne %d : %@',
    '- colonne « %@ » — %d {one=cellule|other=cellules} : %@\n',
    '\n## Restant (%d)\n\n',
    '_Aucune observation restante._\n',
    '- colonne « %@ » : %@\n',
    None,
    'Supprimer les espaces à l’enregistrement',
    'Normaliser les fins de ligne',
    'précédent',
    'Impossible de rouvrir le dossier « %@ » de la session précédente',
    ' (et %d {one=autre fichier|other=autres fichiers})',
    'Impossible de rouvrir %d {one=onglet|other=onglets} : %@%@ — les fichiers ne sont plus au même endroit.',
    'Impossible de lire l’entrée depuis le tube',
    'Les espaces en fin de ligne seront supprimés à chaque enregistrement',
    'Les espaces ne sont plus supprimés à l’enregistrement',
    'Sans titre.txt',
    'La conversion d’encodage perdra des caractères',
    'Enregistrer quand même',
    'Le document a des modifications non enregistrées',
    'Fermer sans enregistrer les abandonnera.',
    'Abandonner les modifications',
    'Aller à la ligne',
    'Le document a %d {one=ligne|other=lignes}.',
    'Numéro de ligne',
    'Aller',
    'Réinterpréter comme…',
    'Convertir vers…',
    'Réinterprétation impossible',
    '%@ ne peut pas représenter tous les caractères',
    'Choisir quand même',
    'Colonne %d',
    'Colonne %d : %@',
    'Colonnes masquées : %@ (%d) — restaurez-les depuis le menu contextuel de l’en-tête',
    'Réafficher : %@',
    'Colonne %@ masquée — elle reste intacte dans le fichier',
    'Trié par %@ %@ · affichage seulement',
    'Trié : %@ %@ (affichage seulement)',
    '%d+ lignes correspondent — recherche en cours…',
    '%d / %d {one=ligne correspond|other=lignes correspondent}',
    'Aucun problème trouvé dans %d {one=ligne|other=lignes}',
    '%d {one=ligne|other=lignes} avec un nombre de colonnes incorrect',
    '%d {one=cellule|other=cellules} du mauvais type',
    ' (arrêté aux %d {one=premier problème|other=premiers problèmes})',
    '   —   types détectés : ',
    'Ligne %d, colonne %@ : « %@ » n’est pas %@',
    'Éditeur de colonnes — %d {one=ligne|other=lignes}',
    'Observations',
    'Profil des données',
    'Profil des données — analyse…',
    'Enregistrer la recette…',
    'Exporter le rapport',
    'Aucun groupe appliqué · chaque groupe est une annulation',
    'trop de valeurs',
    'les plus fréquentes : ',
    'Valeur de remplissage des cellules vides',
    'Appliquer',
    'Impossible de construire un aperçu',
    '· conservé tel quel, illisible ·',
    'Convertir la colonne en ISO 8601 (AAAA-MM-JJ)',
    'Convention numérique pour toute la colonne',
    'Que faire des cellules vides',
    'Normaliser en ISO 8601',
    'Lire les cellules ambiguës JOUR d’abord (31/12)',
    'Lire les cellules ambiguës MOIS d’abord (12/31)',
    'Ignorer les cellules ambiguës, ne corriger que les certaines',
    'Vers le vietnamien/européen (1.234,56)',
    'Vers l’anglo-américain (1,234.56)',
    'Vers l’anglo-américain, sans séparateur (1234.56)',
    'Remplir avec une valeur par défaut…',
    'Remplir vers le bas — reprendre la valeur du dessus',
    'Remplir vers le haut — reprendre la valeur du dessous',
    'Supprimer les lignes vides dans cette colonne',
    'Supprimer les espaces aux deux extrémités',
    'Supprimer aux extrémités et réduire les espaces internes',
    'Tableau croisé…',
    'Sources…',
    'Tableau croisé — regrouper par colonne',
    'Lignes (regroupement)',
    'Valeurs',
    '+ Ligne',
    '+ Valeur',
    'Tout effacer',
    'Insérer dans la requête',
    'Choisissez des colonnes pour construire la requête.',
    'Impossible de lire les noms de colonnes de cette table.',
    'Sources de données de la requête',
    '« %@ » — le document ouvert',
    '  ⚠️ le fichier a changé depuis son enregistrement',
    'Ajouter un fichier…',
    'Tout retirer',
    'Impossible de déduire un nom de table depuis « %@ » — renommez le fichier.',
    'Somme',
    'Moyenne',
    'Min',
    'Max',
    'Nombre de valeurs distinctes',
    'Graphique',
    'Exporter en PNG',
    'Exporter en SVG',
    'Cette table n’a aucune colonne numérique à représenter.',
    'Impossible de construire l’image PNG.',
    'Résultat de la requête',
    '%@ enregistré',
    'Graphique %@ de « %@ » — %d {one=point|other=points}, valeurs de %@ à %@',
    'Barres',
    'Courbe',
    'Histogramme',
    'Nuage de points',
    'Boîte',
    'CSV : qualité des données…',
    'Qualité des données',
    'Exporter les violations dans un nouvel onglet',
    'Niveau',
    'Règle',
    'Violations',
    'Taux',
    'réussi',
    'erreur',
    'avertissement',
    'cassé',
    '%d {one=ligne en violation marquée|other=lignes en violation marquées}',
    'Tendance',
    'Évalué le',
    'Lignes',
    'Écart',
    'Règles en échec',
    'Score de qualité',
    'Score dans le temps',
    'Aucun historique — chaque évaluation ajoute ',
    'une ligne au fichier « .history.jsonl » à côté des règles.',
    '%d {one=point|other=points} dans l’historique',
    ' · %d {one=ligne ILLISIBLE|other=lignes ILLISIBLES}',
    ' · sélectionnez deux lignes pour comparer',
    'score %+.1f',
    'aucune dimension en baisse',
    'en baisse : ',
    '%d {one=nouvelle règle en échec|other=nouvelles règles en échec} : %@',
    'lignes %+d',
    ' (et %d {one=autre avertissement|other=autres avertissements} dans l’onglet Tendance)',
    'Pas de correction automatique : ',
    'Ouvre l’outil correspondant dans l’Atelier de nettoyage, puis réévalue aussitôt.',
    'Traiter les valeurs manquantes…',
    'Normaliser les dates…',
    'Supprimer les doublons…',
    'Remplacer…',
    'Afficher les lignes fautives',
    'La colonne « %@ » n’est pas dans cette table.',
    'Doublons supprimés — « %@ » est désormais unique. Score : %.0f/100',
    'Doublons supprimés, mais « %@ » a encore %d {one=ligne en double|other=lignes en double} (avant : %d) — ',
    'ces lignes partagent la CLÉ mais pas la ligne entière, il faut donc regarder et choisir ',
    'laquelle garder.',
    'Impossible de lire une valeur en violation de cette règle.',
    '%d {one=valeur incorrecte|other=valeurs incorrectes} dans la colonne « %@ » — remplissez Remplacer puis prévisualisez',
    'Réévalué : %.0f/100',
    'Aperçu du rapport',
    'Paramètres…',
    'Exporter en HTML…',
    'Imprimer / PDF…',
    '%d {one=bloc exécuté|other=blocs exécutés} · %d {one=bloc EN ÉCHEC|other=blocs EN ÉCHEC}',
    '%d {one=bloc exécuté|other=blocs exécutés}',
    ' · DONNÉES PÉRIMÉES — le fichier source a changé ; reconstruisez',
    'L’aperçu de rapport nécessite un document .%@',
    'Aucune source de données trouvée — déclarez « source: fichier.csv » dans le frontmatter.',
    'Impossible de construire le rapport.',
    'Ce rapport ne déclare aucun paramètre dans son frontmatter.',
    'Paramètres du rapport',
    'Reconstruire',
    '%@ exporté',
    'Rapport : aperçu',
    'Rapport : génération par lot…',
    'n’est pas un document .greport.md',
    'impossible d’analyser le rapport',
    'source de données introuvable',
    'impossible de lire la liste des paramètres',
    'La génération par lot nécessite un document .%@',
    'Choisir une liste de paramètres (CSV ou JSON)',
    'Choisir un dossier pour %d {one=rapport|other=rapports}',
    '[%d/%d] %@',
    'paramètres manquants ',
    'pointe vers le fichier source lui-même — écrasement refusé',
    '%d {one=bloc EN ÉCHEC|other=blocs EN ÉCHEC}',
    'Lot terminé : %d {one=fichier|other=fichiers} · %d en échec',
    '%d {one=jeu de paramètres n’a pas pu être construit|other=jeux de paramètres n’ont pas pu être construits} — voir le récapitulatif',
    'Diagramme Mermaid : aperçu',
    'Diagramme Mermaid : insérer un modèle…',
    'Diagramme Mermaid : remettre en forme',
    'Fond transparent',
    'Ce Mac ne peut pas convertir le diagramme en PNG — macOS 13 est requis. L’export SVG fonctionne toujours.',
    'Enregistrer le PNG %@…',
    'Enregistrer le SVG…',
    'Copier l’image dans le presse-papiers',
    'Couleurs de marque…',
    'Couleurs de marque pour les diagrammes',
    'Chaque champ est une couleur #rrggbb. Enregistré dans « themes/mermaid-brand.json » — copiable vers un autre Mac.',
    'Couleur principale',
    'Texte des nœuds',
    'Bordure',
    'Liens',
    'Fond à l’export',
    'Enregistrer et insérer %%{init}%% dans le document',
    'Couleurs de marque enregistrées',
    'Image du diagramme copiée dans le presse-papiers',
    '%@ enregistré — %@',
    'Ce diagramme a déjà une directive %%{init}%% — la vôtre est conservée telle quelle.',
    '%%{init}%% inséré — le diagramme porte désormais ses propres couleurs',
    'Insérer les couleurs de marque dans le diagramme',
    'Remettre en forme le diagramme Mermaid',
    'La source du diagramme est déjà propre — rien à changer',
    'Diagramme remis en forme',
    '%d {one=diagramme remis|other=diagrammes remis} en forme',
    'Bibliothèque de modèles de diagrammes',
    'Modèles de diagrammes complets',
    'Fragments de syntaxe',
    'Édition : %@',
    'Modèle « %@ » inséré',
    'Ce document est en lecture seule.',
    'Diagramme Mermaid',
    'Ce document n’a aucun bloc mermaid.',
    'Marque',
    'Exporter…',
    'Aucun diagramme',
    '%d {one=diagramme|other=diagrammes} · %@',
    '%d/%d {one=diagramme EN ÉCHEC|other=diagrammes EN ÉCHEC} — diagramme %d%@',
    ', ligne %d',
    'Ce document n’a aucun bloc ```mermaid et n’est pas un fichier .mmd.',
    'Aucun diagramme n’a fini d’être rendu.',
    'Impossible de trouver « %@ » dans la source du diagramme',
    'impossible de construire le pare-feu réseau pour WKWebView',
    'Règles d’association',
    'Un panier par ligne',
    'Deux colonnes : identifiant · article',
    'Forme des données transactionnelles',
    'Colonne panier ou identifiant de transaction',
    'Colonne article',
    'Caractère séparateur d’articles',
    'Support minimum, pourcentage',
    'Confiance minimum, pourcentage',
    'Séparé par :',
    'Support ≥',
    '% · Confiance ≥',
    'Table des règles d’association',
    'Support',
    'Confiance',
    'Lift',
    'Leverage',
    'Attention',
    '%d {one=transaction|other=transactions} · %d {one=article|other=articles} · %d {one=règle|other=règles}',
    ' — aucune règle n’a atteint les seuils ; baissez le support ou la confiance',
    ' — ARRÊTÉ TÔT, la table est INCOMPLÈTE',
    '%d / %d {one=transaction contient|other=transactions contiennent} les deux membres',
    'La forme à deux colonnes nécessite deux colonnes DIFFÉRENTES.',
    '%d {one=ligne marquée|other=lignes marquées} sur %d {one=transaction contenant|other=transactions contenant} « %@ »',
    'CSV : règles d’association…',
    'Fouille par groupe',
    'Colonne de groupe',
    'Colonne de valeurs',
    'Deuxième colonne pour la corrélation',
    'Classement',
    'Regrouper par :',
    'Valeur :',
    'Classer par :',
    'Table de classement des groupes',
    'Groupe',
    'Lignes',
    'Seuil propre',
    'MAPE',
    'r',
    'Écart r',
    'Note',
    'non mesurable',
    '%d {one=groupe|other=groupes} · corrélation globale de référence %@',
    ' · %d {one=GROUPE ÉCARTÉ|other=GROUPES ÉCARTÉS}',
    'Cette table n’a aucune colonne texte pour regrouper.',
    'Cette table n’a aucune colonne numérique à explorer.',
    '%d {one=ligne du groupe|other=lignes du groupe} « %@ » {one=marquée|other=marquées}',
    'CSV : fouille par groupe…',
    '↔',
    'Prévision',
    'Colonne de valeurs dans le temps',
    'Modèle de prévision',
    'Nombre de périodes à prévoir',
    'Verdict face aux modèles de référence',
    'Modèle :',
    'Périodes :',
    'Saison :',
    'auto',
    'Période saisonnière ; laisser vide pour détection automatique',
    'Table des valeurs prévues',
    'Période',
    'Bande 80 %',
    'Bande 95 %',
    'MAE %@ · MAPE %@',
    'non calculable',
    'Cette table n’a aucune colonne numérique à prévoir.',
    'Impossible de construire une prévision pour cette colonne.',
    'La colonne « %@ » n’a que %d {one=valeur numérique|other=valeurs numériques} — il en faut au moins 4 pour prévoir.',
    '# La série est lue dans l’ordre des lignes du fichier — sans retri, sans colonne temporelle déduite.\n',
    'Erreur d’apprentissage',
    'CSV : prévision de série temporelle…',
    'Holt-Winters additif',
    'Holt-Winters multiplicatif',
    'seasonal-naive',
    'naive',
    'Colonnes utilisées pour le clustering',
    'Courbe WCSS',
    'Cluster',
    'Mise à l’échelle :',
    'k :',
    'eps :',
    'minPts :',
    'Sélectionnez au moins une colonne.',
    'Pas assez de données pour construire la courbe.',
    'Le coude suggère k = %d. Le WCSS diminue TOUJOURS quand k augmente ; c’est donc une astuce de lecture graphique et non un critère statistique — regardez la courbe et jugez si la cassure est nette.',
    'WCSS selon k',
    'La k-distance suggère eps = %@ (minPts vaut par défaut 2 × nombre de colonnes = %d). %@',
    'Distance au k-ième voisin',
    'Au moins 2 colonnes numériques sont nécessaires pour le clustering.',
    'Clusters selon %@ et %@',
    ' — clusters trouvés en %d {one=dimension|other=dimensions} ; le graphique n’en montre que les 2 premières',
    '# bruit (cluster_id = -1) : %d {one=ligne|other=lignes}\n',
    'CSV : clustering…',
    '# --- Centres des clusters (unités d’origine) ---\n',
    'k-means',
    'DBSCAN',
    'Matrice de corrélation',
    'Méthode de corrélation',
    'Corrélation n’implique pas causalité.',
    'Paire la plus forte : %@ ↔ %@ = %@ (n = %d). Cliquez une cellule pour un nuage de points.',
    'Aucune paire mesurable.',
    '%@ ↔ %@ : %@ sur %d {one=ligne|other=lignes}',
    'Au moins 2 colonnes numériques sont nécessaires pour la corrélation.',
    'Impossible de lire la colonne « %@ ».',
    'CSV : matrice de corrélation…',
    'Anomalies',
    'Liste des anomalies',
    'Colonne :',
    'Colonne numérique à examiner',
    'Méthode :',
    'Méthode de détection',
    'Méthode utilisée',
    'Seuil',
    'Marquer',
    'Exporter dans un nouvel onglet',
    'Ligne',
    'Score',
    'Pourquoi',
    'léger',
    'modéré',
    'sévère',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=ligne|other=lignes} (%.2f %%)',
    'Cette table n’a aucune colonne numérique où chercher des anomalies.',
    '%d {one=ligne anormale marquée|other=lignes anormales marquées}',
    'CSV : détecter les anomalies…',
    '%d {one=règle, RÉUSSIE|other=règles, toutes RÉUSSIES} · %d {one=ligne|other=lignes} · %.0f ms',
    '%d {one=erreur|other=erreurs} · %d {one=avertissement|other=avertissements} sur %d {one=règle|other=règles} · %d {one=ligne|other=lignes} · %.0f ms',
    'Enregistrez d’abord le document — les règles de qualité vivent à côté du fichier de données.',
    'Aucun jeu de règles. Créez le fichier %@ puis rouvrez.',
    'Historique',
    'Requêtes enregistrées',
    'Enregistrer cette requête…',
    'Enregistrer la requête',
    'Donnez-lui un nom pour la retrouver plus tard. Un nom identique écrase.',
    'Par exemple : Chiffre d’affaires par province',
    'Aucune valeur saisie pour le paramètre : %@',
    'L’extension a changé depuis votre approbation — GEditor refuse de l’exécuter',
    'Exécuter une extension non approuvée ?',
    'Je fais confiance à ce fichier — exécuter',
    'NON signé',
    'Signature : %@',
    'Chemin : %@',
    'Remplacer',
    'Tout remplacer',
    'Texte brut',
    'Étendu (\\n \\t \\xNN)',
    'Expression régulière',
    'Respecter la casse',
    'Mot entier',
    'Aucun résultat',
    'Tester une expression régulière…',
    'Mode journal (couleur par niveau)',
    'Filtrer le journal par niveau…',
    'Exécuter sur tout le dossier…',
    'Filtrer par une commande externe…',
    'Scripts…',
    'Paquets d’extension…',
    'Nouvelle fenêtre',
    'Détacher l’onglet dans une nouvelle fenêtre',
    'Aucun dossier ouvert',
    'Rechercher un fichier dans le dossier',
    'Filtrer par nom',
    'Nouveau fichier…',
    'Nouveau dossier…',
    'Renommer…',
    'Placer dans la corbeille',
    'Afficher dans le Finder',
    'Lecture de la structure du document…',
    'ce fichier n’a aucune fonction',
    'Aucune correspondance',
    'Texte brut',
    '🔒 Lecture seule',
    'Suivi en cours',
    'retour à la colonne',
    'Syntaxe',
    'Cliquez pour insérer dans la requête',
    'requête invalide',
    'clé « nom » à la racine',
    'clé avec espaces',
    'premier élément',
    'tous les éléments',
    'tranche',
    'union d’indices',
    'toutes les clés « prix » à tous les niveaux',
    'tous les nœuds',
    'filtrer par nombre',
    'filtrer par présence',
    'Aller à la première erreur',
    'La colonne chiffre_affaires est numérique',
    'filtrer…',
    'Annuler',
    'Effectuer le remplacement',
    'aperçu',
    'interactif',
    'Édition',
    'Interface',
    'Raccourcis clavier',
    'Taille du texte',
    'Largeur de tabulation',
    'Indenter avec des tabulations',
    'Indenter automatiquement à la ligne suivante',
    'Surligner tous les résultats de recherche',
    'Normaliser en NFC à l’enregistrement',
    'Langue',
    'Apparence',
    'Système',
    'Clair',
    'Sombre',
    'Thème',
    'Utiliser le préréglage Notepad++',
    'Revenir aux touches par défaut',
    'Ouvrir le fichier de configuration',
    'Exporter le thème actuel',
    'Le changement de langue s’applique entièrement au prochain lancement.',
    'Les touches par défaut reviennent au prochain lancement.',
    'Aperçu Markdown',
    'L’aperçu utilise le moteur Markdown du système : pas encore de tableaux ni de coloration des blocs de code.',
    'Tester une expression régulière',
    'Expression',
    'Texte d’essai',
    'Résultat',
    'Correspondances',
    'Ce que fait cette expression',
    'Expliquer l’expression',
    'Mode de recherche',
    'Résultats de recherche',
    'Aucune correspondance',
    ' (tronqué)',
    'Carte du document',
    'Barre d’onglets',
    'Ligne d’en-tête des colonnes',
    'Aucune colonne',
    'Arborescence de l’espace de travail',
    'Liste des fonctions et classes',
    'Résultats de recherche dans le dossier',
    'Table de données CSV',
    'Atelier de nettoyage des données',
    'Requête JSONPath',
    'Liste des erreurs de données',
    'Évaluateur de golden set…',
    'Comparer à des scores externes (JSONL)…',
    'Choisir un fichier de scores externes (JSONL : query, chunk_id, score)',
    'Renommer le nœud sélectionné',
    'Fusionner les nœuds sélectionnés',
    'Scinder le nœud sélectionné',
    'Extraire le sous-graphe sélectionné dans un nouvel onglet',
    'Rien à changer',
    '%@ — appliquer %d {one=modification|other=modifications} ?',
    '%@ : %d {one=modification|other=modifications} · Cmd-Z annule tout le lot',
    'Placez le curseur sur EXACTEMENT UN nœud puis réessayez',
    'Renommer « %@ »',
    'Toutes les arêtes et étiquettes référençant ce nœud suivront.',
    'Renommer le nœud',
    'Sélectionnez AU MOINS DEUX nœuds puis réessayez',
    'Forme canonique « %@ » — la plus fréquente, la plus longue, accentuée',
    'Fusionner les nœuds',
    'Sélectionnez les LIGNES D’ARÊTES à déplacer puis réessayez',
    'Toutes les lignes sélectionnées doivent toucher EXACTEMENT UN nœud — sélectionnez d’autres lignes d’arêtes',
    'Scinder « %@ » — déplacer %d {one=arête|other=arêtes}',
    'Arêtes vers : %@',
    'Scinder le nœud',
    'Document non enregistré — le fichier extrait a besoin d’un emplacement voisin',
    'Sélectionnez la partie du graphe à extraire puis réessayez',
    'Regrouper les variantes d’entités → table de révision',
    'Appliquer la table de révision modifiée',
    'Document non enregistré — la table de révision doit être à côté du fichier de graphe',
    'Aucune variante à regrouper',
    '%d {one=groupe de variantes|other=groupes de variantes} — corrigez la colonne « canonical » puis lancez « Appliquer la table de révision »',
    'Pas de table de révision « %@ » — lancez d’abord « Regrouper les variantes d’entités »',
    'Table de révision illisible : %@',
    'La table de révision n’a aucune ligne à modifier',
    'Aucun endroit du graphe ne correspond à la table de révision',
    'Regrouper les variantes d’entités',
    '%d {one=modification appliquée|other=modifications appliquées} · table d’alias et liste de marqueurs écrites à côté du fichier',
    'Appliquer %d {one=modification|other=modifications} au graphe ?',
    '%d {one=alias|other=alias} → forme canonique.',
    'FUSIONNER des nœuds (impossible à défaire en retapant) :',
    '%d {one=alias absent du graphe, ignoré|other=alias absents du graphe, ignorés}.',
    'GraphRAG…',
    'Analyse de couverture Segment ↔ Entité',
    'Exporter le paquet de contexte (JSONL)',
    'Couverture Segment ↔ Entité ↔ Graphe',
    '- %d {one=entité|other=entités} · %d {one=segment|other=segments} · %.0f %% d’entités mentionnées · %.0f %% de segments avec entité',
    'Entités qu’aucun segment ne mentionne',
    'Segments orphelins (sans aucune entité)',
    'Nœuds du graphe sans entité correspondante',
    'aucun',
    'Méthode',
    'Impossible de construire la correspondance Segment ↔ Entité',
    'Évaluer la santé du graphe',
    'santé du graphe',
    'Santé %@/100 · %d {one=erreur|other=erreurs} · %d {one=inversion|other=inversions} · %d orphelins',
    'Hybride avec le graphe',
    'α = 1 : signal du graphe totalement ignoré, résultat identique à BM25 pur',
    'α élevé : le graphe n’ajuste que légèrement le classement BM25',
    'α autour de la valeur par défaut 0,7 : BM25 mène, le graphe ajuste',
    'α faible : le graphe mène, BM25 ne fait que départager',
    'α = 0 : signal du graphe seul ; les segments sans entité sont à égalité',
    'Document non enregistré — l’hybride a besoin d’un fichier de graphe à côté du corpus',
    'Fichier de graphe « %@ » introuvable — l’hybride en a besoin pour son signal',
    'hybride %.1f ms · %@',
    'Algorithmes…',
    'PageRank (épaisseur du contour)',
    'Communautés (couleur de fond)',
    'Composantes connexes',
    'Exporter la table des nœuds dans un nouvel onglet',
    '%d {one=composante|other=composantes} · la plus grande %d {one=nœud|other=nœuds} · %d nœuds orphelins',
    'Ce document n’est pas un graphe DOT',
    'Impossible de construire la table nœuds/arêtes : %@',
    '%d {one=ligne|other=lignes} · %@',
    'Étiqueter',
    'Note (facultatif)',
    'Enregistrer l’enregistrement',
    'Exporter en CSV',
    'Document non enregistré — l’évaluateur doit être à côté du fichier de corpus',
    'Impossible de charger l’évaluateur : %@',
    'Enregistrement impossible : %@',
    'L’évaluateur n’a encore aucun enregistrement',
    'Écriture impossible : %@',
    'Ce document n’est ni un fichier .mmd, ni du DOT, et n’a aucun bloc mermaid.',
    '%d {one=nœud|other=nœuds} · %d {one=arête|other=arêtes} · ⚠ %@',
    'Diagramme Mermaid : ajouter un élément…',
    'Diagramme Mermaid : relier les deux éléments sélectionnés',
    'Diagramme Mermaid : modifier l’étiquette de l’élément sélectionné…',
    'Diagramme Mermaid : supprimer l’élément sélectionné',
    'Diagramme Mermaid : remonter le message',
    'Diagramme Mermaid : descendre le message',
    'Ajouter un élément',
    'Ajouter un participant',
    'Ajouter une entrée',
    'Ajouter une entrée au diagramme',
    'Modifier une entrée du diagramme',
    'Supprimer une entrée du diagramme',
    'Supprimer l’élément',
    'Modifier l’étiquette',
    'Réordonner les messages',
    'Nom de l’entrée',
    'Nouvelle entrée',
    'Le nom de l’entrée apparaît sur le diagramme.',
    'Table des propriétés du diagramme',
    'Ce document n’a aucun bloc mermaid',
    'Identifiant dans la source du diagramme — sans espaces. L’étiquette se modifie ensuite par double-clic.',
    'Si vide, l’identifiant lui-même est affiché.',
    'Seule l’ÉTIQUETTE affichée change ; l’identifiant de l’élément reste le même.',
    'Impossible de savoir quel élément est « %@ »',
    'Sélectionnez EXACTEMENT DEUX éléments puis réessayez',
    'Placez le curseur sur EXACTEMENT UN élément puis réessayez',
    'Choisissez UN élément à supprimer, ou deux éléments reliés par une arête',
    'Supprimer « %@ » et les %d {one=arête qui le touche|other=arêtes qui le touchent} ?',
    'Les nœuds à l’autre bout de ces arêtes sont conservés — ils sont redéclarés avec leur étiquette si l’instruction d’arête était leur seule déclaration.',
    'Le diagramme « %@ » se modifie uniquement en texte — %@',
    '%@ : glissez entre deux éléments pour relier, double-cliquez pour modifier l’étiquette',
    '%@ : glissez entre deux participants pour ajouter un message ; réordonnez via le menu Outils',
    '%@ : modifiez dans la table des propriétés ci-dessous',
    'Édition visuelle activée',
    '%@ · %d {one=entrée|other=entrées} — modifiez directement dans la table, chaque cellule est une annulation',
    'Pour un camembert, un nombre ; pour un gantt, ce qui suit les deux-points.',
    'Diagramme Mermaid : extraire le bloc dans un fichier .mmd…',
    'Diagramme Mermaid : réintégrer le fichier référencé',
    'Extraire le bloc du diagramme',
    'Réintégrer le bloc du diagramme',
    'Extraire le bloc du diagramme dans un fichier séparé',
    'Le fichier est placé À CÔTÉ du document ; le bloc conserve une ligne de référence pour n’éditer qu’à un seul endroit.',
    'Document non enregistré — le fichier du diagramme a besoin d’un emplacement voisin',
    'Le fichier « %@ » existe déjà — choisissez un autre nom',
    'Extrait dans « %@ » — le bloc conserve une ligne de référence',
    'Ouvrir le fichier',
    '« %@ » réintégré ; le fichier reste sur le disque',
    'Ce bloc contient un vrai diagramme, pas une référence',
    'Ce bloc référence « %@ » — ouvrez ce fichier pour le modifier',
    'Impossible de lire le fichier de diagramme %@',
    'Édition visuelle',
    'Glissez d’un nœud à un autre pour ajouter une arête ; double-cliquez pour modifier l’étiquette. Chaque action est une annulation.',
    'Édition visuelle : glissez entre deux nœuds pour ajouter une arête, double-cliquez pour modifier l’étiquette',
    'Édition visuelle désactivée',
    'Ajouter un nœud…',
    'Ajouter une arête entre les deux nœuds sélectionnés…',
    'Modifier l’étiquette du nœud sélectionné…',
    'Supprimer le nœud/l’arête sélectionné',
    'Ajouter un nœud',
    'Ajouter une arête',
    'Modifier l’étiquette du nœud',
    'Supprimer le nœud',
    'Supprimer l’arête',
    'Cmd-Z pour annuler',
    'Ce document est en lecture seule',
    'Étiquette de « %@ »',
    'Seule l’ÉTIQUETTE affichée change ; l’identifiant du nœud reste le même.',
    'Impossible de savoir quel nœud est « %@ »',
    'Identifiant du nœud dans le fichier DOT. L’étiquette se modifie ensuite par double-clic sur le graphique.',
    'Sélectionnez EXACTEMENT DEUX nœuds puis réessayez',
    'Choisissez UN nœud à supprimer, ou deux nœuds reliés par une arête',
    'Supprimer le nœud « %@ » et les %d {one=arête qui le touche|other=arêtes qui le touchent} ?',
    'Si les arêtes orphelines restent, DOT recrée les nœuds à partir d’elles — le nœud supprimé réapparaîtra au tracé suivant.',
    'Laboratoire de recherche BM25',
    'Question — Entrée pour rechercher',
    'Évaluer…',
    'Construction de l’index',
    'Aucun segment ne correspond',
    'meilleurs résultats',
    'k1 = 0 : chaque mot ne compte QU’UNE fois, quel que soit le nombre d’occurrences',
    'k1 faible : répéter un mot n’ajoute presque rien au score',
    'k1 autour de la valeur par défaut 1,2 : la répétition ajoute du score, de façon décroissante',
    'k1 élevé : un segment répétant un mot est fortement récompensé',
    'b = 0 : la longueur est ignorée, les segments longs ne sont pas pénalisés',
    'b faible : les segments longs ne sont que légèrement pénalisés',
    'b autour de la valeur par défaut 0,75 : les segments longs sont modérément pénalisés',
    'b = 1 : pénalité maximale selon la longueur, les segments courts sont favorisés',
    'JSONL : laboratoire de recherche…',
    'Document non enregistré — l’index BM25 vit à côté du fichier de corpus et a donc besoin d’un chemin',
    'Ce fichier n’est pas du JSONL — le Retrieval Lab fonctionne sur un corpus de segments',
    'Impossible de construire un index BM25 pour ce fichier',
    'Document non enregistré — un chemin de corpus est nécessaire pour générer le rapport',
    'Choisir un jeu d’évaluation (CSV ou JSONL : question + identifiant de segment attendu)',
    'Évaluation de la recherche',
    'Modifiez k1, b ou k ci-dessus puis réexaminez pour comparer deux configurations ; ajoutez un bloc « compare » pour exécuter deux jeux de paramètres en parallèle sur le même jeu d’évaluation.',
    'Erreur',
    '   (%d…%d, moyenne %.0f)',
    'Mode JSONL',
    'Enregistrement',
    'Détail',
    'Enregistrement à la ligne',
    'n’est pas du JSON valide',
    'enregistrements',
    'lignes vides',
    'n’est pas un objet',
    'table affichée',
    'ANNULÉ en cours de route',
    'Aucun filtre',
    'enregistrements correspondant au filtre',
    'Placez le curseur sur une ligne pour voir l’enregistrement',
    'Aucun enregistrement défectueux',
    'Pas encore inspecté. Relancez « JSONL : inspecter les segments » après la vérification.',
    'champ texte',
    'SCHÉMA (deviné — modifiable en choisissant un autre champ)',
    'texte',
    'identifiant',
    'métadonnées imbriquées',
    'CHAMP',
    'couverture',
    'types multiples',
    'LONGUEUR — caractères',
    'LONGUEUR — mots',
    'LONGUEUR — jetons estimés',
    'VIDES ET DOUBLONS',
    'segments vides',
    'lignes',
    'groupes de doublons exacts',
    'lignes illisibles, hors statistiques',
    'MÉTHODE',
    '« caractères » compte les caractères Unicode (scalaires), pas les groupes affichés',
    '« mots » découpe sur les espaces ASCII',
    '« jetons » compte avec un découpeur de syllabes — CE N’EST PAS celui du modèle',
    '« doublon » signifie doublon EXACT ; les quasi-doublons sont dans le bloc ```quality',
    'segments',
    'JSONL : vérifier et inspecter les segments…',
    'Image',
    'PDF',
    'Document Word',
    'Feuille de calcul Excel',
    'Présentation PowerPoint',
    'Archive',
    'Ajuster à la fenêtre',
    'Copier l’image',
    'Pivoter',
    'Impossible de lire l’image « %@ »',
    'Image copiée dans le presse-papiers',
    'Surligner en jaune',
    'Souligner',
    'Note…',
    'Retirer les annotations',
    'Extraire le texte dans un nouvel onglet',
    'Enregistrer la version annotée…',
    'Rechercher dans le PDF',
    'Ajouter',
    'Page %d/%d',
    'Page %d',
    'Résultat %d/%d',
    '0 résultat',
    'Impossible de lire le PDF « %@ »',
    'Ce PDF est protégé par mot de passe — contenu inaccessible',
    '« %@ » introuvable dans le document',
    'Surligné',
    'Souligné',
    'Sélectionnez d’abord un passage de texte',
    'Note ajoutée',
    'Cette page n’a aucune annotation',
    '%d {one=annotation retirée|other=annotations retirées} de cette page',
    'Ce PDF n’a pas de couche de texte — il s’agit probablement d’un scan',
    'Impossible d’écrire le fichier',
    'Le fichier écrit ne se rouvre PAS correctement — n’utilisez pas cette version',
    '%@ enregistré · %d {one=page|other=pages}',
    'Nom',
    'Taille',
    'Compressé',
    'Ratio',
    'Modifié le',
    'Ouvrir l’élément sélectionné',
    'Extraire vers un dossier…',
    'Extraire ici',
    '%d {one=élément|other=éléments}',
    'extrait vers %@',
    '— l’intérieur d’un fichier Office est une archive ; voici ses composants',
    '%d {one=élément extrait|other=éléments extraits}',
    '%d {one=élément défectueux|other=éléments défectueux}',
    '%d {one=élément REFUSÉ|other=éléments REFUSÉS} — leurs chemins sortent du dossier de destination',
    'Impossible d’ouvrir cet élément',
    'Impossible d’écrire directement dans un %@ pour l’instant — utilisez « Enregistrer sous… »',
    'Rien n’a changé',
    '%d {one=cellule écrite|other=cellules écrites} dans %@',
    '%d {one=paragraphe écrit|other=paragraphes écrits} dans %@',
    'Impossible d’écrire dans le fichier — l’original est intact',
    'préparer le cas de test',
    'Impossible d’écrire settings.json',
    'Pivoter à gauche',
    'Pivoter à droite',
    'Monter la page',
    'Descendre la page',
    'Supprimer des pages…',
    'Supprimer des pages',
    'Extraire des pages…',
    'Extraire les pages vers un nouveau fichier',
    'Fusionner un PDF…',
    'Diviser le fichier…',
    'Diviser le fichier PDF',
    'Exporter en images…',
    'Exporter les pages en images PNG',
    "Annuler l'action sur la page",
    'Enregistrer la copie modifiée…',
    'Lire',
    'Pause',
    'Vue normale',
    'Choisir la feuille',
    'Ouvrir la feuille',
    'Abandonner et changer de feuille',
    'Le classeur contient %d feuilles.',
    "Ce classeur ne contient qu'une feuille : « %@ »",
    'Abandonner les modifications non enregistrées de cette feuille ?',
    "Changer de feuille remplace tout l'onglet. Ce qui n'a pas été enregistré avec ⌘S sera perdu.",
    'Choisir le PDF à fusionner',
    'Choisir le dossier des images',
    "Choisissez l'emplacement. Le second fichier sera écrit à côté de celui-ci.",
    'Le document a %d pages. Saisissez les pages à supprimer, ex. 2-4,7',
    'Le document a %d pages. Saisissez les pages à extraire, ex. 1-3,8',
    'Le document a %d pages. Saisissez les pages à exporter, ex. 1-3',
    'Le document a %d pages. Saisissez la partie à détacher, ex. 1-5 ; le reste devient un second fichier.',
    'Page %d pivotée',
    'Pages %@ supprimées · %d pages restantes',
    '%d pages fusionnées depuis « %@ »',
    'Divisé en %@ (%d pages) et %@ (%d pages)',
    '%@ écrit — %@ · %d pages',
    '%d images exportées vers %@',
    'Seules %d images sur %d ont été exportées',
    'Une action sur la page a été annulée',
    'Plus aucune action sur la page à annuler',
    'Impossible de supprimer TOUTES les pages — un PDF doit en garder au moins une',
    'Cette plage correspond à tout le document — rien à détacher',
    '« %@ » est protégé par mot de passe — fusion impossible',
    '« %@ » ne contient aucune page',
    'Déjà à la première page',
    'Déjà à la dernière page',
    '· modifié, non enregistré',
    'Image animée · %d images',
    'Document non enregistré — aucun fichier sur le disque à afficher en binaire',
    "Cette commande ne fonctionne qu'avec les classeurs Excel",
    'Impossible de lire la liste des feuilles',
    'Aucune feuille nommée « %@ »',
    'Impossible de lire la feuille « %@ »',
    'Feuille « %@ » · %d lignes',
    'le reste',
    'Remarque',
    'Attention',
    'Voir aussi',
    'Copier',
    'Copié',
    "Copier l'exemple de code",
    "Rechercher dans l'aide",
    'Retour',
    'Commencer',
    'Ne plus afficher cette fenêtre au démarrage',
    "L'aide n'est pas encore traduite dans cette langue — affichage en vietnamien.",
    "Aller à l'offset (ex. 1F400 ou 0x1F400)",
    'Copier les lignes sélectionnées',
    '%d lignes copiées',
    'Impossible de lire « %@ »',
    'Fichier vide',
    'Offset « %@ » illisible',
    "L'offset 0x%@ dépasse la taille du fichier",
    'Ouvrir avec une autre app…',
    '%d canaux',
    'Impossible de lire « %@ »',
    'Lecture impossible — %@',
    "macOS n'a pas de décodeur intégré pour le format %@ — c'est une limite du système, pas un fichier corrompu.",
    "Vous pouvez toujours voir les octets en mode binaire, ou l'ouvrir avec une app disposant de son propre décodeur.",
    'Signer…',
    'Modifier le texte…',
    'Modifier le texte',
    'Dessiner par-dessus',
    'Champ vide suivant',
    'Effacer les champs remplis',
    "Ce fichier n'a aucun champ de formulaire",
    '%d champs de formulaire effacés',
    'Tous les champs de formulaire sont remplis',
    '%d champs encore vides',
    'Formulaire à remplir : %d champs. Saisissez directement, puis « Enregistrer la copie modifiée… »',
    'Choisir une image de signature (fond transparent de préférence)',
    'Impossible de créer la page signée',
    'Signature insérée à la page %d',
    "Sélectionnez d'abord le texte à modifier",
    'La sélection est trop petite',
    "Le nouveau texte est DESSINÉ PAR-DESSUS la sélection avec la police système. L'ancien texte est masqué, pas supprimé — il reste extractible, ce n'est donc pas un caviardage.",
    'Impossible de créer la page modifiée',
    'Nouveau texte dessiné sur la page %d',
    'Basculer Vue / Code',
    'Pas encore de vue arborescente pour JSON · XML · YAML',
    "Pas encore de vue schéma dans l'onglet",
    'Pas encore de vue plan pour PowerPoint',
    "Ce fichier n'a qu'un seul mode d'affichage",
    '%d nœuds',
    "Impossible de construire l'arbre : %@",
    'Le document est trop grand pour un arbre — utilisez le mode Code',
]
