# Bản dịch id — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code id --name "…" scripts/ban-dich/id.py
VALS = [
    'Versi tersimpan…',
    'Dokumen ini belum pernah disimpan — belum ada riwayat',
    'Tidak ada versi tersimpan sebelumnya',
    'Versi itu tidak dapat dibaca',
    'Pulihkan versi tersimpan',
    'XML: validasi terhadap DTD/XSD…',
    'Mac ini tidak punya libxml2, jadi validasi XSD tidak tersedia.',
    'Pilih skema XSD untuk validasi',
    'Valid terhadap',
    'Pengaya selesai tanpa mengubah apa pun',
    'Belum ada pengaya native yang terpasang',
    'Hapus pengaya ini',
    'Hapus pengaya ini?',
    'Hapus',
    'Pasang pengaya native…',
    'Buka folder pengaya',
    'Pilih berkas .dylib pengaya',
    'Terpasang:',
    'Dihapus:',
    'Pengaya native…',
    'Hanya berkas .dylib yang diterima.',
    'Pengaya dengan nama yang sama sudah terpasang:',
    'Pengaya tidak dapat disalin:',
    'Pengaya native hanya tersedia pada unduhan langsung, bukan pada versi App Store.',
    'Proses pembantu pengaya tidak ditemukan.',
    'Proses pembantu pengaya tidak dapat dijalankan:',
    'Proses pengaya berhenti tanpa diduga.',
    'Pengaya tidak menjawab tepat waktu — proses dihentikan.',
    'Pengaya membalas dengan pesan yang rusak:',
    'Pengaya melaporkan galat:',
    'Tentang GEditor',
    'Pengaturan…',
    'Keluar dari GEditor',
    'Berkas',
    'Tab Baru',
    'Tutup Tab',
    'Tab Berikutnya',
    'Tab Sebelumnya',
    'Dokumen Baru',
    'Buka…',
    'Buka Folder sebagai Ruang Kerja…',
    'Baru Saja Dibuka',
    'Simpan',
    'Simpan Sebagai…',
    'Pangkas Spasi Akhir Baris saat Menyimpan',
    'Ikuti Berkas (tail -f)',
    'Cetak…',
    'Buka Kembali Tab yang Terakhir Ditutup',
    'Tidak ada berkas terkini',
    'Kosongkan Menu',
    'Sunting',
    'Urungkan',
    'Ulangi',
    'Potong',
    'Salin',
    'Tempel',
    'Riwayat Papan Klip…',
    'Penyunting Kolom…',
    'Pilih Kemunculan Berikutnya',
    'Pilih Semua',
    'Gandakan Baris',
    'Hapus Baris',
    'Jadikan Komentar / Batalkan',
    'Belum ada yang disalin',
    'Kosongkan Riwayat',
    'Cari',
    'Cari…',
    'Cari dan Ganti…',
    'Cari di Folder…',
    'Ganti di Folder…',
    'Hasil Berikutnya',
    'Hasil Sebelumnya',
    'Ke Baris…',
    'Lompat ke Kurung Pasangan',
    'Tandai Semua Baris yang Cocok…',
    'Balik Tanda',
    'Hapus Semua Tanda',
    'Salin Baris Bertanda',
    'Hapus Baris Bertanda',
    'Sisakan Hanya Baris Bertanda',
    'Baris',
    'Urutkan A→Z',
    'Urutkan Z→A',
    'Urutan Alami',
    'Hapus Duplikat',
    'Balik Urutan Baris',
    'Naikkan Baris',
    'Turunkan Baris',
    'Gabungkan Baris',
    'Potong Baris Menurut Panjang…',
    'Potong Baris Menurut Karakter…',
    'Hapus Baris Kosong',
    'Rapatkan Baris Kosong',
    'Pangkas Spasi Akhir Baris',
    'Tab → Spasi',
    'Spasi → Tab',
    'HURUF BESAR',
    'huruf kecil',
    'Huruf Besar Tiap Kata',
    'Huruf besar di awal kalimat',
    'bALIK bESAR kECIL',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: pilih lembar…',
    'Alihkan Tampilan Tabel / Teks',
    'Hapus Kolom…',
    'Periksa Data (kolom · tipe)',
    'Meja Pembersihan Data…',
    'Jalankan Resep Pembersihan…',
    'Konversi…',
    'Ubah Pemisah…',
    'Ekspor ke JSON…',
    'Format',
    'Pengodean…',
    'Akhir Baris…',
    'Normalkan Unicode…',
    'JSON: Rapikan',
    'JSON: Padatkan',
    'JSON: Urutkan Kunci',
    'JSON: Kueri JSONPath…',
    'CSV: Kueri SQL…',
    'Kueri SQL',
    'Sedang berjalan…',
    'Ekspor ke Tab Baru',
    'Dokumen kosong — tidak ada tabel untuk dikueri',
    'Bukan tabel CSV — baris pertama hanya punya satu kolom',
    'Kueri tidak dapat dibaca',
    'Kueri tidak dapat diperiksa',
    'Kuning (bawaan)',
    'Biru',
    'Hijau',
    'Oker',
    'Ungu',
    'Merah muda',
    'Tosca',
    'Jingga',
    'Kelabu batu',
    'Teks',
    'Deret angka',
    'Deret tanggal',
    'Huruf besar (heksa)',
    'Mulai',
    'Langkah',
    'Isi nol sampai',
    'Basis',
    'Tanggal pertama',
    'Format',
    'Sisipkan',
    'Batal',
    'Konversi format',
    'Pratinjau 5 baris pertama',
    'Buka di tab baru',
    'Simpan ke berkas…',
    'Hasilnya terbuka di tab baru yang belum disimpan. Dokumen asli tidak tersentuh.',
    'Jalankan pada dokumen ini',
    'Jalankan pada satu folder…',
    'Seluruh resep adalah SATU langkah urung. Berkas di cakram tidak tersentuh sampai Anda menyimpan.',
    'mati',
    'kolom tidak ditemukan',
    'siap',
    'ia terus memakai satu inti prosesor sampai aplikasi ditutup.',
    'Skrip tidak mengembalikan apa pun',
    'Mesin JavaScript tidak dapat dibuat',
    'Galat JavaScript yang tidak dikenal',
    'Tabel',
    'Terapkan pengurutan ke berkas',
    'Konversi ▾',
    'Ekspor baris yang cocok',
    'Sembunyikan kolom ini',
    'Ganti nama tajuk…',
    'Sisipkan kolom kosong di kiri',
    'Sisipkan kolom kosong di kanan',
    'Hapus kolom ini dari berkas…',
    'Setidaknya satu kolom harus tetap terlihat',
    'Sedang mengurutkan…',
    'Kembali ke urutan berkas',
    'seratus baris pertama',
    'memilih kolom',
    'menamai kolom hasil',
    'menyaring menurut teks',
    'sel kosong',
    'menggabungkan syarat',
    'menghitung baris',
    'mengelompokkan dan meringkas',
    'minimum, maksimum',
    'mengurutkan dan membatasi',
    'nama kolom berspasi',
    'Kueri dihentikan di tengah jalan',
    'Tidak didukung: JOIN · subkueri · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · fungsi jendela',
    'XML: Rapikan',
    'XML: Padatkan',
    'XML: Periksa Sintaks',
    'YAML: Periksa Kunci dan Indentasi',
    'Tampilan',
    'Alihkan Bilah Samping (Daftar Fungsi)',
    'Alihkan Peta Dokumen',
    'Lipat / Buka di Kursor',
    'Lipat Semua',
    'Buka Semua Lipatan',
    'Lipat sampai Tingkat',
    'Tingkat %d',
    'Melipat %1$d blok pada tingkat %2$d',
    'Dokumen ini hanya sedalam %d tingkat',
    'mermaid: manifes tidak terbaca',
    'Periksa Pembaruan…',
    'Periksa Pembaruan',
    'Versi App Store diperbarui lewat Mac App Store, bukan lewat GEditor.',
    'Versi ini tidak punya kunci tanda tangan pembaruan, jadi ia tidak bisa memeriksa pembaruan.',
    'Perbesar',
    'Perkecil',
    'Ukuran Asli',
    'Belah Tegak',
    'Belah Mendatar',
    'Tutup Belahan',
    'Buka Tab di Panel Sebelah',
    'Pindah ke Panel Sebelah',
    'Bungkus Baris (mati / ke jendela / ke kolom)',
    'Bungkus pada Kolom…',
    'Alihkan Penanda',
    'Penanda Berikutnya',
    'Penanda Sebelumnya',
    'Warna Penanda…',
    'Tampilkan Semua Karakter Tak Terlihat',
    '  Spasi',
    '  Tab',
    '  Akhir baris',
    '  NBSP · lebar nol · kendali',
    'Tampilan biner',
    'Mode CSV (kolom pelangi)',
    'Makro',
    'Mulai / Hentikan Perekaman',
    'Mainkan',
    'Mainkan Beberapa Kali…',
    'Mainkan sampai Akhir Dokumen',
    'Jalankan pada Semua Tab',
    'Hentikan Makro yang Berjalan',
    'Simpan Makro…',
    'Makro Tersimpan…',
    'Bantuan',
    'Bantuan GEditor',
    'Pengenalan Fitur',
    'Pindah dari Notepad++',
    'Cari',
    'Ganti dengan',
    'Berikutnya',
    'Sebelumnya',
    'Hitung',
    'Tutup',
    'Validasi terhadap Skema JSON…',
    'Pilih berkas Skema JSON',
    'Tidak ada masalah terhadap skema ini.',
    'Skema JSON',
    'Periksa sintaks graf',
    'Format graf tidak dikenali — perlu ekstensi .dot, .gv, .cypher, .ttl atau .graphml.',
    'Tidak ditemukan galat sintaks %@ (pemeriksaan ini tidak menyeluruh).',
    'sintaks %@',
    'bukan objek JSON',
    'Penambangan teks (n-gram, TF-IDF)',
    'Dokumen kosong.',
    'Tidak ada kata kunci yang bisa diambil.',
    'Kata kunci',
    '%d kata kunci · %d token · %d dokumen',
    'Tandai di dokumen',
    'Tandai entitas dari sebuah daftar…',
    'Pilih daftar entitas (CSV atau JSON)',
    'Daftar entitas tidak dapat dibaca.',
    'Daftar entitas kosong.',
    'Tidak ada entitas yang ditemukan di dokumen (%d dimuat).',
    '%d kemunculan · %@',
    'Konversi pengetahuan…',
    'Konversi: %@ → %@',
    'Konversi gagal.',
    'Pratinjau pemenggalan…',
    'Tetap 800 B, tumpang tindih 100 B',
    'Per kalimat (≤ 800 B)',
    'Per judul Markdown',
    'Dokumen kosong — tidak ada penggalan.',
    '%d penggalan · rata-rata %d B · %@',
    'Ekspor JSONL',
    'JSONL penggalan',
    'Buka triple/sisi sebagai tabel',
    'Tabel triple',
    'Dokumen ini tidak punya baris triple.',
    'Tidak ada triple yang terbaca — baris %d: %@',
    'Terbaca %1$d triple · dilewati %2$d baris rusak (pertama: baris %3$d)',
    'Duplikat mirip menurut kolom…',
    'Duplikat mirip — kolom «%1$@»: %2$d kelompok calon',
    'Gabungkan',
    'Kemiripan',
    'Nilai dalam kelompok',
    'Gabungkan menjadi',
    'Gabungkan kelompok terpilih',
    'Tidak ada kelompok terpilih — Gabungkan tidak akan mengubah apa pun. Aplikasi tidak pernah menggabungkan sendiri.',
    '%1$d kelompok terpilih · %2$d baris akan berubah · SATU langkah urung',
    'Kolom ini tidak dapat dipindai.',
    'Kolom «%@» tidak punya kelompok duplikat mirip.',
    'Tidak ada kelompok yang digabungkan — dokumen tidak berubah.',
    'Dedup mirip · kolom %@',
    'Digabungkan %1$d kelompok · %2$d sel berubah',
    'Laporan pembersihan',
    '# Laporan pembersihan — %@\n\n',
    '## Diterapkan (%d)\n\n',
    '_Belum ada langkah yang diterapkan._\n',
    '\n## Profil data\n\n',
    '_%1$d kolom · %2$d baris · dipindai dalam %3$.1f d_\n\n',
    '| Kolom | Tipe | Kosong | Berbeda | Min | Maks | Rerata |\n',
    '\n### Pencilan\n\n',
    'baris %d: %@',
    '- kolom «%1$@» — %2$d sel: %3$@\n',
    '\n## Tersisa (%d)\n\n',
    '_Tidak ada temuan yang tersisa._\n',
    '- kolom «%1$@»: %2$@\n',
    None,
    'Pangkas spasi saat menyimpan',
    'Seragamkan akhir baris',
    'sebelumnya',
    'Folder «%@» dari sesi sebelumnya tidak dapat dibuka kembali',
    ' (dan %d berkas lagi)',
    '%1$d tab tidak dapat dibuka kembali: %2$@%3$@ — berkasnya sudah tidak ada di tempatnya.',
    'Masukan dari pipa tidak dapat dibaca',
    'Spasi di akhir baris akan dipangkas setiap kali menyimpan',
    'Spasi tidak lagi dipangkas saat menyimpan',
    'TanpaJudul.txt',
    'Konversi pengodean akan menghilangkan sebagian karakter',
    'Simpan saja',
    'Dokumen punya perubahan yang belum disimpan',
    'Menutup tanpa menyimpan akan membuangnya.',
    'Buang perubahan',
    'Ke baris',
    'Dokumen punya %d baris.',
    'Nomor baris',
    'Pergi',
    'Tafsirkan ulang sebagai…',
    'Konversi ke…',
    'Penafsiran ulang gagal',
    '%@ tidak dapat mewakili semua karakter',
    'Tetap pilih',
    'Kolom %d',
    'Kolom %1$d: %2$@',
    'Kolom tersembunyi: %1$@ (%2$d) — kembalikan dari menu konteks baris tajuk',
    'Tampilkan lagi: %@',
    'Kolom %@ disembunyikan — kolomnya masih utuh di dalam berkas',
    'Diurutkan menurut %@ %@ · hanya tampilan',
    'Terurut: %@ %@ (hanya tampilan)',
    '%d+ baris cocok — pencarian masih berjalan…',
    '%1$d / %2$d baris cocok',
    'Tidak ada masalah pada %d baris',
    '%d baris dengan jumlah kolom yang salah',
    '%d sel dengan tipe data yang salah',
    ' (berhenti pada %d masalah pertama)',
    '   —   tipe yang terdeteksi: ',
    'Baris %1$d, kolom %2$@: «%3$@» bukan %4$@',
    'Penyunting Kolom — %d baris',
    'Temuan',
    'Profil data',
    'Profil data — sedang memindai…',
    'Simpan resep…',
    'Ekspor laporan',
    'Belum ada kelompok yang diterapkan · setiap kelompok adalah satu langkah urung',
    'terlalu banyak nilai',
    'paling sering: ',
    'Nilai pengisi untuk sel kosong',
    'Terapkan',
    'Pratinjau tidak dapat dibuat',
    '· dibiarkan apa adanya, tak terbaca ·',
    'Konversi kolom ke ISO 8601 (TTTT-BB-HH)',
    'Kelaziman angka untuk seluruh kolom',
    'Apa yang dilakukan pada sel kosong',
    'Seragamkan ke ISO 8601',
    'Baca sel ambigu dengan HARI di depan (31/12)',
    'Baca sel ambigu dengan BULAN di depan (12/31)',
    'Lewati sel ambigu, perbaiki yang pasti saja',
    'Ke gaya Vietnam/Eropa (1.234,56)',
    'Ke gaya Anglo-Amerika (1,234.56)',
    'Ke gaya Anglo-Amerika, tanpa pemisah ribuan (1234.56)',
    'Isi dengan nilai bawaan…',
    'Isi ke bawah — ambil nilai di atasnya',
    'Isi ke atas — ambil nilai di bawahnya',
    'Hapus baris yang kosong pada kolom ini',
    'Pangkas spasi di kedua ujung',
    'Pangkas kedua ujung dan rapatkan spasi di dalam',
    'Tabel pivot…',
    'Sumber…',
    'Pivot — kelompokkan menurut kolom',
    'Baris (kelompokkan menurut)',
    'Nilai',
    '+ Baris',
    '+ Nilai',
    'Kosongkan semua',
    'Masukkan ke kotak kueri',
    'Pilih kolom untuk menyusun kueri.',
    'Nama kolom tabel ini tidak dapat dibaca.',
    'Sumber data kueri',
    '“%@” — dokumen yang terbuka',
    '  ⚠️ berkas berubah sejak didaftarkan',
    'Tambah berkas…',
    'Hapus semua',
    'Nama tabel tidak dapat diturunkan dari “%@” — ganti nama berkasnya.',
    'Jumlah',
    'Rerata',
    'Min',
    'Maks',
    'Cacah nilai berbeda',
    'Grafik',
    'Ekspor PNG',
    'Ekspor SVG',
    'Tabel ini tidak punya kolom angka untuk digambar.',
    'Gambar PNG tidak dapat dibuat.',
    'Hasil kueri',
    'Tersimpan %@',
    'Grafik %1$@ dari “%2$@” — %3$d titik, nilai dari %4$@ sampai %5$@',
    'Batang',
    'Garis',
    'Histogram',
    'Sebar',
    'Kotak',
    'CSV: Mutu data…',
    'Mutu data',
    'Ekspor pelanggaran ke tab baru',
    'Tingkat',
    'Aturan',
    'Pelanggaran',
    'Rasio',
    'lolos',
    'galat',
    'peringatan',
    'rusak',
    'Ditandai %d baris yang melanggar',
    'Tren',
    'Dinilai pada',
    'Baris',
    'Selisih',
    'Aturan yang gagal',
    'Nilai mutu',
    'Nilai sepanjang waktu',
    'Belum ada riwayat — setiap penilaian menambahkan ',
    'satu baris ke berkas “.history.jsonl” di sebelah berkas aturan.',
    '%d titik dalam riwayat',
    ' · %d baris tak terbaca',
    ' · pilih dua baris untuk dibandingkan',
    'nilai %+.1f',
    'tidak ada dimensi yang turun',
    'turun: ',
    '%1$d aturan yang baru gagal: %2$@',
    'baris %+d',
    ' (dan %d peringatan lagi di tab Tren)',
    'Tidak ada perbaikan otomatis: ',
    'Membuka alat Meja Pembersihan yang sesuai, lalu langsung menilai ulang.',
    'Tangani nilai yang hilang…',
    'Seragamkan tanggal…',
    'Hapus duplikat…',
    'Ganti…',
    'Tampilkan baris yang bermasalah',
    'Kolom “%@” tidak ada di tabel ini.',
    'Duplikat sudah dihapus — “%1$@” kini unik. Nilai: %2$.0f/100',
    'Duplikat sudah dihapus, tetapi “%1$@” masih punya %2$d baris kembar (tadinya %3$d) — ',
    'baris-baris itu sama pada KUNCI-nya, tetapi tidak pada seluruh barisnya, jadi Anda harus melihat dan memilih ',
    'mana yang dipertahankan.',
    'Tidak ada nilai pelanggar aturan ini yang dapat dibaca.',
    '%1$d nilai keliru di kolom “%2$@” — isi kolom Ganti, lalu lihat pratinjau',
    'Dinilai ulang: %.0f/100',
    'Pratinjau laporan',
    'Parameter…',
    'Ekspor HTML…',
    'Cetak / PDF…',
    '%1$d blok berjalan · %2$d blok GAGAL',
    '%d blok berjalan',
    ' · DATA USANG — berkas sumber berubah; bangun ulang',
    'Pratinjau laporan memerlukan dokumen .%@',
    'Sumber data tidak ditemukan — nyatakan “source: file.csv” di frontmatter.',
    'Laporan tidak dapat dibangun.',
    'Laporan ini tidak menyatakan parameter apa pun di frontmatter-nya.',
    'Parameter laporan',
    'Bangun ulang',
    'Diekspor %@',
    'Laporan: Pratinjau',
    'Laporan: Buat sekaligus…',
    'bukan dokumen .greport.md',
    'laporan tidak dapat diurai',
    'data sumber tidak ditemukan',
    'daftar parameter tidak dapat dibaca',
    'Pembuatan sekaligus memerlukan dokumen .%@',
    'Pilih daftar parameter (CSV atau JSON)',
    'Pilih folder untuk %d laporan',
    '[%1$d/%2$d] %3$@',
    'parameter yang hilang ',
    'menunjuk ke berkas sumber itu sendiri — menolak menimpanya',
    '%d blok GAGAL',
    'Selesai sekaligus: %1$d berkas · %2$d gagal',
    '%d set parameter tidak dapat disusun — lihat ringkasannya',
    'Diagram Mermaid: Pratinjau',
    'Diagram Mermaid: Sisipkan templat…',
    'Diagram Mermaid: Rapikan ulang',
    'Latar tembus pandang',
    'Mac ini tidak dapat meraster diagram menjadi PNG — perlu macOS 13. Ekspor SVG tetap berjalan.',
    'Simpan PNG %@…',
    'Simpan SVG…',
    'Salin gambar ke papan klip',
    'Warna merek…',
    'Warna merek untuk diagram',
    'Setiap ruas adalah warna #rrggbb. Disimpan ke “themes/mermaid-brand.json” — salin berkas itu ke Mac lain.',
    'Warna utama',
    'Teks pada simpul',
    'Bingkai',
    'Tautan',
    'Latar saat mengekspor',
    'Simpan dan sisipkan %%{init}%% ke dokumen',
    'Warna merek tersimpan',
    'Gambar diagram disalin ke papan klip',
    'Tersimpan %1$@ — %2$@',
    'Diagram ini sudah punya arahan %%{init}%% — milik Anda dibiarkan apa adanya.',
    '%%{init}%% disisipkan — diagram kini membawa warnanya sendiri',
    'Sisipkan warna merek ke dalam diagram',
    'Rapikan ulang diagram Mermaid',
    'Sumber diagram sudah rapi — tidak ada yang perlu diubah',
    'Diagram sudah dirapikan ulang',
    'Dirapikan ulang %d diagram',
    'Pustaka templat diagram',
    'Templat diagram utuh',
    'Potongan sintaks',
    'Sedang menyunting: %@',
    'Templat “%@” disisipkan',
    'Dokumen ini hanya-baca.',
    'Diagram Mermaid',
    'Dokumen ini tidak punya blok mermaid.',
    'Merek',
    'Ekspor…',
    'Belum ada diagram',
    '%d diagram · %@',
    '%1$d/%2$d diagram GAGAL — diagram %3$d%4$@',
    ', baris %d',
    'Dokumen ini tidak punya blok ```mermaid dan bukan berkas .mmd.',
    'Belum ada diagram yang selesai digambar.',
    '“%@” tidak ditemukan di sumber diagram',
    'pemblokir jaringan untuk WKWebView tidak dapat dibuat',
    'Aturan asosiasi',
    'Satu keranjang per baris',
    'Dua kolom: id · barang',
    'Bentuk data transaksi',
    'Kolom keranjang atau kolom id transaksi',
    'Kolom barang',
    'Karakter pemisah barang',
    'Dukungan minimum, persen',
    'Keyakinan minimum, persen',
    'Pisahkan dengan:',
    'Dukungan ≥',
    '% · Keyakinan ≥',
    'Tabel aturan asosiasi',
    'Dukungan',
    'Keyakinan',
    'Angkat',
    'Ungkitan',
    'Awas',
    '%d transaksi · %d barang · %d aturan',
    ' — tidak ada aturan yang mencapai ambang; turunkan dukungan atau keyakinan',
    ' — BERHENTI LEBIH AWAL, tabel ini BELUM LENGKAP',
    '%1$d / %2$d transaksi memuat kedua sisinya',
    'Bentuk dua kolom memerlukan dua kolom yang BERBEDA.',
    'Ditandai %1$d baris di %2$d transaksi yang memuat “%3$@”',
    'CSV: Aturan Asosiasi…',
    'Penambangan kelompok',
    'Kolom pengelompokan',
    'Kolom nilai',
    'Kolom kedua untuk korelasi',
    'Peringkat',
    'Kelompokkan menurut:',
    'Nilai:',
    'Peringkatkan menurut:',
    'Tabel peringkat kelompok',
    'Kelompok',
    'Baris',
    'Ambang sendiri',
    'MAPE',
    'r',
    'beda r',
    'Catatan',
    'tak terukur',
    '%d kelompok · korelasi gabungan %@',
    ' · %d KELOMPOK DIBUANG',
    'Tabel ini tidak punya kolom teks untuk dikelompokkan.',
    'Tabel ini tidak punya kolom angka untuk ditambang.',
    'Ditandai %1$d baris kelompok “%2$@”',
    'CSV: Penambangan Kelompok…',
    '↔',
    'Ramalan',
    'Kolom nilai sepanjang waktu',
    'Model ramalan',
    'Banyaknya periode yang diramalkan',
    'Putusan terhadap model acuan',
    'Model:',
    'Periode:',
    'Musim:',
    'otomatis',
    'Panjang musim; biarkan kosong agar dideteksi otomatis',
    'Tabel nilai ramalan',
    'Periode',
    'Pita 80 persen',
    'Pita 95 persen',
    'MAE %@ · MAPE %@',
    'tak terhitung',
    'Tabel ini tidak punya kolom angka untuk diramalkan.',
    'Ramalan untuk kolom ini tidak dapat dibangun.',
    'Kolom “%1$@” hanya punya %2$d nilai angka — meramalkan perlu setidaknya 4.',
    '# Deret dibaca menurut urutan baris di berkas — tanpa diurutkan ulang dan tanpa menebak kolom waktu.\n',
    'Galat pelatihan',
    'CSV: Ramalkan Deret Waktu…',
    'Holt-Winters aditif',
    'Holt-Winters multiplikatif',
    'naif musiman',
    'naif',
    'Kolom yang masuk ke pengelompokan',
    'Kurva WCSS',
    'Gugus',
    'Penskalaan:',
    'k:',
    'eps:',
    'minPts:',
    'Pilih setidaknya satu kolom.',
    'Data tidak cukup untuk membangun kurva.',
    'Sikunya menyarankan k = %d. WCSS SELALU turun saat k membesar, jadi ini cara membaca grafik, bukan kriteria statistik — lihat kurvanya dan nilai sendiri apakah tekukannya jelas.',
    'WCSS menurut k',
    'Jarak-k menyarankan eps = %1$@ (minPts bawaannya 2 × jumlah kolom = %2$d). %3$@',
    'Jarak ke tetangga ke-k',
    'Pengelompokan memerlukan setidaknya 2 kolom angka.',
    'Gugus menurut %@ dan %@',
    ' — gugus ditemukan dalam %d dimensi; grafik hanya menampilkan 2 yang pertama',
    '# derau (cluster_id = -1): %d baris\n',
    'CSV: Gugus…',
    '# --- Pusat gugus (satuan asli) ---\n',
    'k-means',
    'DBSCAN',
    'Matriks korelasi',
    'Metode korelasi',
    'Korelasi bukan berarti sebab-akibat.',
    'Pasangan terkuat: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klik satu sel untuk grafik sebar.',
    'Tidak ada pasangan yang dapat diukur.',
    '%1$@ ↔ %2$@: %3$@ pada %4$d baris',
    'Korelasi memerlukan setidaknya 2 kolom angka.',
    'Kolom “%@” tidak dapat dibaca.',
    'CSV: Matriks Korelasi…',
    'Keanehan',
    'Daftar keanehan',
    'Kolom:',
    'Kolom angka yang diperiksa',
    'Metode:',
    'Metode pendeteksian',
    'Metode yang dipakai',
    'Ambang',
    'Tandai',
    'Ekspor ke tab baru',
    'Baris',
    'Skor',
    'Alasan',
    'ringan',
    'sedang',
    'berat',
    'skor-z',
    'IQR',
    'MAD',
    '%1$d / %2$d baris (%3$.2f%%)',
    'Tabel ini tidak punya kolom angka untuk dipindai keanehannya.',
    'Ditandai %d baris yang aneh',
    'CSV: Cari Keanehan…',
    '%1$d aturan, semua LOLOS · %2$d baris · %3$.0f md',
    '%1$d galat · %2$d peringatan pada %3$d aturan · %4$d baris · %5$.0f md',
    'Simpan dokumennya dulu — aturan mutu tinggal di sebelah berkas data.',
    'Belum ada berkas aturan. Buat %@ lalu buka kembali.',
    'Riwayat',
    'Kueri tersimpan',
    'Simpan kueri ini…',
    'Simpan kueri',
    'Beri nama agar mudah ditemukan nanti. Nama yang sama akan menimpa.',
    'Misalnya: Pendapatan per provinsi',
    'Belum ada nilai untuk parameter: %@',
    'Pengaya berubah sejak Anda menyetujuinya — GEditor menolak menjalankannya',
    'Jalankan pengaya yang belum disetujui?',
    'Saya percaya berkas ini — jalankan',
    'TANPA tanda tangan',
    'Tanda tangan: %@',
    'Jalur: %@',
    'Ganti',
    'Ganti Semua',
    'Teks biasa',
    'Diperluas (\\n \\t \\xNN)',
    'Ekspresi reguler',
    'Bedakan huruf besar-kecil',
    'Kata utuh',
    'Tidak ada hasil',
    'Uji Ekspresi Reguler…',
    'Mode Log (warna menurut tingkat)',
    'Saring Log menurut Tingkat…',
    'Jalankan pada Seluruh Folder…',
    'Saring lewat Perintah…',
    'Skrip…',
    'Paket Perluasan…',
    'Jendela Baru',
    'Pindahkan Tab ke Jendela Baru',
    'Tidak ada folder yang terbuka',
    'Cari berkas di folder',
    'Saring menurut nama',
    'Berkas Baru…',
    'Folder Baru…',
    'Ganti Nama…',
    'Pindahkan ke Tong Sampah',
    'Tampilkan di Finder',
    'Membaca struktur dokumen…',
    'tidak ada fungsi di berkas ini',
    'Tidak ada yang cocok',
    'Teks biasa',
    '🔒 Hanya-baca',
    'Sedang diikuti',
    'bungkus pada kolom',
    'Sintaks',
    'Klik untuk menyisipkan ke kotak kueri',
    'kueri tidak sah',
    'kunci `ten` di akar',
    'kunci yang mengandung spasi',
    'elemen pertama',
    'semua elemen',
    'irisan',
    'gabungan indeks',
    'semua kunci `gia` pada kedalaman mana pun',
    'semua simpul',
    'saring menurut angka',
    'saring menurut keberadaan',
    'Ke masalah pertama',
    'Kolom doanh_thu berupa angka',
    'saring…',
    'Batal',
    'Ganti',
    'pratinjau',
    'interaktif',
    'Penyuntingan',
    'Tampilan',
    'Pintasan Papan Ketik',
    'Ukuran huruf',
    'Lebar tab',
    'Indentasi dengan tab',
    'Indentasi otomatis di baris baru',
    'Sorot semua hasil pencarian',
    'Normalkan ke NFC saat menyimpan',
    'Bahasa',
    'Latar',
    'Ikut sistem',
    'Terang',
    'Gelap',
    'Tema',
    'Pakai prasetel Notepad++',
    'Kembalikan tombol bawaan',
    'Buka berkas konfigurasi',
    'Ekspor tema saat ini',
    'Pergantian bahasa berlaku sepenuhnya saat aplikasi dibuka berikutnya.',
    'Tombol bawaan kembali saat aplikasi dibuka berikutnya.',
    'Pratinjau Markdown',
    'Digambar dengan mesin Markdown bawaan sistem: tabel dan pewarnaan blok kode belum didukung.',
    'Penguji Ekspresi Reguler',
    'Ekspresi',
    'Teks contoh',
    'Hasil',
    'Hasil kecocokan',
    'Apa yang dilakukan ekspresi ini',
    'Penjelasan ekspresi',
    'Mode pencarian',
    'Hasil pencarian',
    'Tidak ada yang cocok',
    ' (dipotong)',
    'Peta dokumen',
    'Bilah tab',
    'Baris tajuk kolom',
    'Tidak ada kolom',
    'Pohon berkas ruang kerja',
    'Daftar fungsi dan kelas',
    'Hasil pencarian di folder',
    'Tabel data CSV',
    'Meja pembersihan data',
    'Kueri JSONPath',
    'Daftar masalah data',
    'Set emas…',
    'Bandingkan dengan skor dari luar (JSONL)…',
    'Pilih berkas skor dari luar (JSONL: query, chunk_id, score)',
    'Ganti nama simpul terpilih',
    'Gabungkan simpul terpilih',
    'Pecah simpul terpilih',
    'Keluarkan subgraf terpilih ke tab baru',
    'Tidak ada yang perlu diubah',
    '%1$@ — terapkan %2$d perubahan?',
    '%1$@: %2$d perubahan · Cmd-Z mengurungkan seluruh rangkaian',
    'Letakkan kursor tepat pada SATU simpul, lalu jalankan lagi',
    'Ganti nama “%@”',
    'Semua sisi dan label yang menunjuk simpul ini ikut berubah.',
    'Ganti nama simpul',
    'Pilih DUA simpul atau lebih, lalu jalankan lagi',
    'Bentuk baku “%@” — paling sering, paling panjang, memakai tanda diakritik',
    'Gabungkan simpul',
    'Pilih BARIS-BARIS SISI yang dipindahkan, lalu jalankan lagi',
    'Setiap baris terpilih harus menyentuh tepat SATU simpul yang sama — pilih lebih banyak baris sisi',
    'Pecah “%1$@” — pindahkan %2$d sisi',
    'Sisi ke: %@',
    'Pecah simpul',
    'Dokumen belum disimpan — berkas hasil perlu tempat untuk berdampingan',
    'Pilih bagian graf yang dikeluarkan, lalu jalankan lagi',
    'Kelompokkan ragam entitas → tabel tinjauan',
    'Terapkan tabel tinjauan yang sudah disunting',
    'Dokumen belum disimpan — tabel tinjauan harus berada di sebelah berkas graf',
    'Tidak ada ragam yang bisa dikelompokkan',
    '%d kelompok ragam — sunting kolom “canonical”, lalu jalankan “Terapkan”',
    'Belum ada tabel tinjauan “%@” — jalankan “Kelompokkan ragam entitas” dulu',
    'Tabel tinjauan tidak dapat dibaca: %@',
    'Tabel tinjauan tidak punya baris yang perlu diubah',
    'Tidak ada bagian graf yang cocok dengan tabel tinjauan',
    'Kelompokkan ragam entitas',
    'Diterapkan %d perubahan · tabel alias dan daftar penanda ditulis di sebelah berkas',
    'Terapkan %d perubahan pada graf?',
    '%d alias → bentuk baku.',
    'MENGGABUNGKAN simpul (tidak bisa dibatalkan dengan mengetik ulang):',
    '%d alias tidak ada di graf dan dilewati.',
    'GraphRAG…',
    'Cakupan penggalan ↔ entitas',
    'Ekspor paket konteks (JSONL)',
    'Cakupan penggalan ↔ entitas ↔ graf',
    '- %1$d entitas · %2$d penggalan · %3$.0f%% entitas disebut · %4$.0f%% penggalan memuat entitas',
    'Entitas yang tidak disebut penggalan mana pun',
    'Penggalan yatim (tanpa entitas di dalamnya)',
    'Simpul graf tanpa entitas yang cocok',
    'tidak ada',
    'Metode',
    'Pemetaan penggalan ↔ entitas tidak dapat dibangun',
    'Nilai kesehatan graf',
    'kesehatan graf',
    'Kesehatan %1$@/100 · %2$d masalah · %3$d pulau · %4$d menyendiri',
    'Hibrida dengan graf',
    'α = 1: sinyal graf mati sama sekali, hasilnya sama dengan BM25 polos',
    'α tinggi: graf hanya menggeser sedikit peringkat BM25',
    'α di sekitar bawaan 0,7: BM25 memimpin, graf menyesuaikan',
    'α rendah: graf memimpin, BM25 hanya memutus seri',
    'α = 0: hanya sinyal graf; penggalan tanpa entitas semuanya seri',
    'Dokumen belum disimpan — hibrida perlu berkas graf di sebelah korpus',
    'Tidak ada berkas graf “%@” — hibrida memerlukannya agar punya sinyal',
    'hibrida %.1f md · %@',
    'Algoritme…',
    'PageRank (tebal garis tepi)',
    'Komunitas (warna isi)',
    'Komponen terhubung',
    'Ekspor tabel simpul ke tab baru',
    '%1$d komponen · terbesar %2$d simpul · %3$d menyendiri',
    'Dokumen ini bukan graf DOT',
    'Tabel simpul/sisi tidak dapat dibangun: %@',
    '%d baris · %@',
    'Label',
    'Catatan (boleh dikosongkan)',
    'Simpan catatan',
    'Ekspor CSV',
    'Dokumen belum disimpan — set penilaian harus berada di sebelah berkas korpus',
    'Set penilaian tidak dapat dimuat: %@',
    'Tidak dapat disimpan: %@',
    'Set penilaian belum punya satu pun catatan',
    'Tidak dapat ditulis: %@',
    'Dokumen ini bukan berkas .mmd, bukan DOT, dan tidak punya blok mermaid.',
    '%d simpul · %d sisi · ⚠ %@',
    'Diagram Mermaid: tambah elemen…',
    'Diagram Mermaid: hubungkan dua elemen terpilih',
    'Diagram Mermaid: ubah label elemen terpilih…',
    'Diagram Mermaid: hapus elemen terpilih',
    'Diagram Mermaid: naikkan pesan',
    'Diagram Mermaid: turunkan pesan',
    'Tambah elemen',
    'Tambah peserta',
    'Tambah butir',
    'Tambah butir diagram',
    'Ubah butir diagram',
    'Hapus butir diagram',
    'Hapus elemen',
    'Ubah label',
    'Susun ulang pesan',
    'Nama butir',
    'Butir baru',
    'Nama butir yang tampil pada diagram.',
    'Tabel properti diagram',
    'Dokumen ini tidak punya blok mermaid',
    'Pengenal di sumber diagram — tanpa spasi. Labelnya diubah nanti dengan klik ganda.',
    'Kosongkan agar pengenalnya sendiri yang tampil.',
    'Yang berubah hanya LABEL yang tampil; pengenal elemen tetap sama.',
    'Tidak jelas elemen yang mana “%@” itu',
    'Pilih tepat DUA elemen, lalu jalankan lagi',
    'Letakkan kursor tepat pada SATU elemen, lalu jalankan lagi',
    'Pilih SATU elemen untuk dihapus, atau dua elemen yang terhubung sisi',
    'Hapus “%1$@” dan %2$d sisi yang menyentuhnya?',
    'Simpul di ujung seberang sisi-sisi itu dipertahankan — ia dinyatakan ulang beserta labelnya jika perintah sisi tadi satu-satunya tempat ia dinyatakan.',
    'Diagram “%1$@” hanya bisa disunting sebagai teks — %2$@',
    '%@: seret di antara dua elemen untuk menghubungkannya, klik ganda untuk mengubah label',
    '%@: seret di antara dua peserta untuk menambah pesan; urutannya diubah dari menu Alat',
    '%@: sunting di tabel properti di bawah',
    'Penyuntingan visual menyala',
    '%1$@ · %2$d butir — sunting langsung di tempat; setiap sel satu langkah urung',
    'Untuk pie berupa angka; untuk gantt, semua yang mengikuti titik dua.',
    'Diagram Mermaid: keluarkan blok ke berkas .mmd…',
    'Diagram Mermaid: benamkan kembali berkas yang dirujuk',
    'Keluarkan blok diagram',
    'Benamkan blok diagram',
    'Keluarkan blok diagram ke berkasnya sendiri',
    'Berkasnya berdampingan DENGAN dokumen; bloknya menyisakan satu baris rujukan agar penyuntingan terjadi di satu tempat saja.',
    'Dokumen belum disimpan — berkas diagram perlu tempat untuk berdampingan',
    'Berkas “%@” sudah ada — pilih nama lain',
    'Dikeluarkan ke “%@” — bloknya menyisakan satu baris rujukan',
    'Buka berkas',
    '“%@” sudah dibenamkan kembali; berkasnya masih ada di cakram',
    'Blok ini memuat diagram sungguhan, bukan rujukan',
    'Blok ini merujuk ke “%@” — buka berkas itu untuk menyuntingnya',
    'Berkas diagram tidak dapat dibaca: %@',
    'Penyuntingan visual',
    'Seret dari satu simpul ke simpul lain untuk menambah sisi; klik ganda untuk mengubah label. Setiap tindakan adalah satu langkah urung.',
    'Penyuntingan visual: seret di antara dua simpul untuk menambah sisi, klik ganda untuk mengubah label',
    'Penyuntingan visual mati',
    'Tambah simpul…',
    'Tambah sisi di antara dua simpul terpilih…',
    'Ubah label simpul terpilih…',
    'Hapus simpul atau sisi terpilih',
    'Tambah simpul',
    'Tambah sisi',
    'Ubah label simpul',
    'Hapus simpul',
    'Hapus sisi',
    'Cmd-Z untuk mengurungkan',
    'Dokumen ini hanya-baca',
    'Label “%@”',
    'Yang berubah hanya LABEL yang tampil; pengenal simpul tetap sama.',
    'Tidak jelas simpul yang mana “%@” itu',
    'Pengenal simpul di berkas DOT. Labelnya diubah nanti dengan klik ganda pada diagram.',
    'Pilih tepat DUA simpul, lalu jalankan lagi',
    'Pilih SATU simpul untuk menghapus simpul, atau dua simpul yang terhubung sisi',
    'Hapus simpul “%1$@” dan %2$d sisi yang menyentuhnya?',
    'Kalau sisinya dibiarkan menggantung, DOT membuat ulang simpulnya justru dari sisi-sisi itu — simpul yang baru dihapus akan muncul lagi pada penggambaran berikutnya.',
    'Lab pencarian BM25',
    'Pertanyaan — tekan Return untuk mencari',
    'Nilai…',
    'Sedang membangun indeks',
    'Tidak ada penggalan yang cocok',
    'hasil dari',
    'k1 = 0: setiap kata dihitung SEKALI saja, sesering apa pun ia muncul',
    'k1 rendah: mengulang satu kata hampir tidak menambah apa-apa',
    'k1 di sekitar bawaan 1,2: pengulangan menambah skor, tetapi makin lama makin sedikit',
    'k1 tinggi: penggalan yang mengulang satu kata diganjar besar',
    'b = 0: panjang diabaikan, penggalan panjang tidak dihukum',
    'b rendah: penggalan panjang hanya dihukum sedikit',
    'b di sekitar bawaan 0,75: penggalan panjang dihukum sedang-sedang',
    'b = 1: hukuman panjang paling besar, penggalan pendek diuntungkan',
    'JSONL: lab pencarian…',
    'Dokumen belum disimpan — indeks BM25 tinggal di sebelah berkas korpus, jadi ia perlu jalur',
    'Berkas ini bukan JSONL — Lab Pencarian bekerja pada korpus penggalan',
    'Indeks BM25 untuk berkas ini tidak dapat dibangun',
    'Dokumen belum disimpan — perlu jalur korpus untuk membuat laporannya',
    'Pilih set penilaian (CSV atau JSONL: pertanyaan + id penggalan yang diharapkan)',
    'Penilaian pencarian',
    'Ubah k1, b atau k di atas lalu gambar ulang untuk membandingkan dua konfigurasi; tambahkan blok “compare” agar dua set parameter berjalan berdampingan pada set penilaian yang sama.',
    'Galat',
    '   (%1$d…%2$d, rerata %3$.0f)',
    'Mode JSONL',
    'Catatan',
    'Rincian',
    'Catatan di baris',
    'bukan JSON yang sah',
    'catatan',
    'baris kosong',
    'bukan objek',
    'tabel menampilkan',
    'DIBATALKAN DI TENGAH JALAN',
    'Tanpa saringan',
    'catatan cocok dengan saringan',
    'Pindahkan kursor ke satu baris untuk melihat catatannya',
    'Tidak ada catatan yang rusak',
    'Belum diperiksa. Jalankan “JSONL: periksa penggalan” setelah pemeriksaan selesai.',
    'ruas teks',
    'SKEMA (tebakan — pilih ruas lain untuk mengubahnya)',
    'teks',
    'pengenal',
    'metadata bersarang',
    'RUAS',
    'ada pada',
    'tipe campur',
    'PANJANG — karakter',
    'PANJANG — kata',
    'PANJANG — perkiraan token',
    'KOSONG DAN KEMBAR',
    'penggalan kosong',
    'baris',
    'kelompok kembar persis',
    'baris tak terbaca, tidak dihitung dalam statistik',
    'METODE',
    '“karakter” menghitung skalar Unicode, bukan kelompok tampilan',
    '“kata” dipisah pada spasi ASCII',
    '“token” memakai pemenggal suku kata — BUKAN milik modelnya',
    '“kembar” berarti PERSIS sama; yang HAMPIR sama ada di blok ```quality',
    'penggalan',
    'JSONL: periksa dan telaah penggalan…',
    'Gambar',
    'PDF',
    'Dokumen Word',
    'Lembar kerja Excel',
    'Presentasi PowerPoint',
    'Arsip',
    'Paskan',
    'Salin gambar',
    'Putar',
    'Gambar “%@” tidak dapat dibaca',
    'Gambar disalin ke papan klip',
    'Sorot',
    'Garis bawah',
    'Catatan…',
    'Hapus anotasi',
    'Keluarkan teksnya ke tab baru',
    'Simpan salinan beranotasi…',
    'Cari di PDF',
    'Tambah',
    'Halaman %d dari %d',
    'Halaman %d',
    'Kecocokan %d dari %d',
    'Tidak ada yang cocok',
    'PDF “%@” tidak dapat dibaca',
    'PDF ini dilindungi kata sandi — isinya tidak dapat dibuka',
    '“%@” tidak ada di dokumen ini',
    'Sudah disorot',
    'Sudah digarisbawahi',
    'Pilih sepotong teks dulu',
    'Catatan ditambahkan',
    'Halaman ini tidak punya anotasi',
    'Dihapus %d anotasi dari halaman ini',
    'PDF ini tidak punya lapisan teks — kemungkinan besar hasil pindaian',
    'Berkasnya tidak dapat ditulis',
    'Berkas yang baru ditulis TIDAK terbuka dengan benar — jangan pakai salinan ini',
    'Tersimpan %1$@ · %2$d halaman',
    'Nama',
    'Ukuran',
    'Termampat',
    'Nisbah',
    'Diubah',
    'Buka butir terpilih',
    'Bongkar ke folder…',
    'Bongkar di sini',
    '%d butir',
    'membesar menjadi %@',
    '— isi sebuah berkas Office adalah arsip; inilah bagian-bagian di dalamnya',
    'Dibongkar %d butir',
    '%d butir gagal',
    '%d butir DITOLAK — jalurnya keluar dari folder tujuan',
    'Butir ini tidak dapat dibuka',
    'Belum bisa menulis balik ke %@ — pakai “Simpan Sebagai…”',
    'Tidak ada yang berubah',
    'Ditulis %1$d sel ke %2$@',
    'Ditulis %1$d paragraf ke %2$@',
    'Tidak dapat menulis ke berkas — yang asli tidak tersentuh',
    'menyiapkan kasus uji',
    'settings.json tidak dapat ditulis',
    'Putar kiri',
    'Putar kanan',
    'Pindahkan halaman ke atas',
    'Pindahkan halaman ke bawah',
    'Hapus halaman…',
    'Hapus halaman',
    'Ekstrak halaman…',
    'Ekstrak halaman ke berkas baru',
    'Gabungkan berkas PDF…',
    'Pisahkan berkas…',
    'Pisahkan berkas PDF',
    'Ekspor gambar…',
    'Ekspor halaman sebagai gambar PNG',
    'Urungkan penyuntingan halaman',
    'Simpan salinan hasil edit…',
    'Putar',
    'Jeda',
    'Tampilan normal',
    'Pilih lembar',
    'Buka lembar',
    'Buang dan ganti lembar',
    'Buku kerja memiliki %d lembar.',
    'Buku kerja ini hanya memiliki satu lembar: «%@»',
    'Buang perubahan yang belum disimpan di lembar ini?',
    'Berganti lembar mengganti seluruh tab. Yang belum disimpan dengan ⌘S akan hilang.',
    'Pilih berkas PDF untuk digabungkan',
    'Pilih folder untuk gambar',
    'Pilih lokasi simpan. Berkas kedua ditulis di sebelahnya.',
    'Dokumen memiliki %d halaman. Masukkan halaman yang dihapus, mis. 2-4,7',
    'Dokumen memiliki %d halaman. Masukkan halaman yang diekstrak, mis. 1-3,8',
    'Dokumen memiliki %d halaman. Masukkan halaman yang diekspor, mis. 1-3',
    'Dokumen memiliki %d halaman. Masukkan bagian yang dipisah, mis. 1-5; sisanya jadi berkas kedua.',
    'Halaman %d diputar',
    'Halaman %@ dihapus · sisa %d halaman',
    '%d halaman digabungkan dari «%@»',
    'Dipisahkan menjadi %@ (%d halaman) dan %@ (%d halaman)',
    'Menulis %@ — %@ · %d halaman',
    '%d gambar diekspor ke %@',
    'Hanya %d/%d gambar yang diekspor',
    'Satu operasi halaman diurungkan',
    'Tidak ada operasi halaman untuk diurungkan',
    'Tidak bisa menghapus SEMUA halaman — PDF harus punya minimal satu halaman',
    'Rentang itu adalah seluruh dokumen — tidak ada yang dipisah',
    '«%@» dilindungi kata sandi — tidak bisa digabungkan',
    '«%@» tidak memiliki halaman',
    'Sudah di halaman pertama',
    'Sudah di halaman terakhir',
    '· disunting, belum disimpan',
    'Gambar animasi · %d bingkai',
    'Dokumen belum disimpan — tidak ada berkas di disk untuk tampilan biner',
    'Perintah ini hanya untuk buku kerja Excel',
    'Tidak dapat membaca daftar lembar',
    'Tidak ada lembar bernama «%@»',
    'Tidak dapat membaca lembar «%@»',
    'Lembar «%@» · %d baris',
    'sisanya',
    'Catatan',
    'Perhatian',
    'Lihat juga',
    'Salin',
    'Tersalin',
    'Salin kode contoh',
    'Cari di bantuan',
    'Kembali',
    'Mulai',
    'Jangan tampilkan jendela ini saat memulai',
    'Bantuan belum diterjemahkan ke bahasa ini — menampilkan teks bahasa Vietnam.',
    'Ke offset (mis. 1F400 atau 0x1F400)',
    'Salin baris terpilih',
    '%d baris disalin',
    'Tidak dapat membaca «%@»',
    'Berkas kosong',
    'Tidak dapat membaca offset «%@»',
    'Offset 0x%@ melewati ukuran berkas',
    'Buka dengan aplikasi lain…',
    '%d kanal',
    'Tidak bisa memutar «%@»',
    'Tidak bisa diputar — %@',
    'macOS tidak punya dekoder bawaan untuk format %@ — ini batas sistem, bukan berkas rusak.',
    'Anda tetap bisa melihat byte dalam mode biner, atau membukanya dengan aplikasi yang punya dekoder sendiri.',
    'Tanda tangan…',
    'Sunting teks…',
    'Sunting teks',
    'Gambar di atasnya',
    'Bidang kosong berikutnya',
    'Hapus isian',
    'Berkas ini tidak punya bidang formulir',
    '%d bidang formulir dikosongkan',
    'Semua bidang formulir sudah terisi',
    'Masih %d bidang kosong',
    'Formulir isian: %d bidang. Ketik langsung, lalu «Simpan salinan hasil edit…»',
    'Pilih gambar tanda tangan (latar transparan paling bagus)',
    'Tidak bisa membuat halaman bertanda tangan',
    'Tanda tangan disisipkan di halaman %d',
    'Pilih dulu teks yang ingin diubah',
    'Pilihan terlalu kecil',
    'Teks baru DIGAMBAR DI ATAS pilihan dengan fon sistem. Teks lama tertutup, bukan terhapus — masih bisa diekstrak, jadi ini bukan penyensoran.',
    'Tidak bisa membuat halaman hasil edit',
    'Teks baru digambar di halaman %d',
    'Alihkan Tampilan / Kode',
    'Belum ada tampilan pohon untuk JSON · XML · YAML',
    'Belum ada tampilan diagram di dalam tab',
    'Belum ada tampilan kerangka untuk PowerPoint',
    'Berkas ini hanya punya satu mode tampilan',
    '%d simpul',
    'Tidak bisa membangun pohon: %@',
    'Dokumen terlalu besar untuk pohon — gunakan mode Kode',
]
