# Bản dịch it — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code it --name "…" scripts/ban-dich/it.py
VALS = [
    'Versioni salvate…',
    'Questo documento non è mai stato salvato — nessuna cronologia',
    'Non ci sono versioni salvate precedenti',
    'Impossibile leggere quella versione',
    'Ripristina la versione salvata',
    'XML: valida con DTD/XSD…',
    'Questo Mac non ha libxml2, quindi la validazione XSD non è disponibile.',
    'Scegli uno schema XSD per la validazione',
    'Valido secondo',
    'L’estensione ha terminato senza modificare nulla',
    'Nessuna estensione nativa installata',
    'Rimuovi questa estensione',
    'Rimuovere questa estensione?',
    'Rimuovi',
    'Installa un’estensione nativa…',
    'Apri la cartella delle estensioni',
    'Scegli il file .dylib dell’estensione',
    'Installato:',
    'Rimosso:',
    'Estensioni native…',
    'Sono accettati solo file .dylib.',
    'Esiste già un’estensione con lo stesso nome:',
    'Impossibile copiare l’estensione:',
    'Le estensioni native ci sono solo nel download diretto, non nella versione App Store.',
    'Processo ausiliario delle estensioni non trovato.',
    'Impossibile avviare il processo ausiliario:',
    'Il processo dell’estensione si è interrotto a metà.',
    'L’estensione non ha risposto in tempo — è stata fermata.',
    'L’estensione ha risposto con un messaggio malformato:',
    'L’estensione ha segnalato un errore:',
    'Informazioni su GEditor',
    'Impostazioni…',
    'Esci da GEditor',
    'File',
    'Nuova scheda',
    'Chiudi scheda',
    'Scheda successiva',
    'Scheda precedente',
    'Nuovo documento',
    'Apri…',
    'Apri una cartella come area di lavoro…',
    'Apri recenti',
    'Salva',
    'Salva come…',
    'Rimuovi gli spazi a fine riga al salvataggio',
    'Segui il file (tail -f)',
    'Stampa…',
    'Riapri la scheda chiusa',
    'Nessun file',
    'Svuota l’elenco',
    'Modifica',
    'Annulla',
    'Ripristina',
    'Taglia',
    'Copia',
    'Incolla',
    'Cronologia degli appunti…',
    'Editor di colonne…',
    'Seleziona l’occorrenza successiva',
    'Seleziona tutto',
    'Duplica la riga',
    'Elimina la riga',
    'Commenta la riga',
    'Non è stato copiato nulla in questa sessione',
    'Cancella la cronologia',
    'Cerca',
    'Trova…',
    'Trova e sostituisci…',
    'Cerca in una cartella…',
    'Sostituisci in una cartella…',
    'Risultato successivo',
    'Risultato precedente',
    'Vai alla riga…',
    'Vai alla parentesi corrispondente',
    'Segna tutte le righe corrispondenti…',
    'Inverti i segnalibri',
    'Rimuovi tutti i segnalibri',
    'Copia le righe segnate',
    'Elimina le righe segnate',
    'Tieni solo le righe segnate',
    'Righe',
    'Ordina A→Z',
    'Ordina Z→A',
    'Ordinamento naturale',
    'Rimuovi i duplicati',
    'Inverti l’ordine delle righe',
    'Sposta la riga in su',
    'Sposta la riga in giù',
    'Unisci le righe',
    'Dividi le righe per lunghezza…',
    'Dividi le righe per carattere…',
    'Elimina le righe vuote',
    'Comprimi le righe vuote consecutive',
    'Rimuovi gli spazi a fine riga',
    'Tab → Spazio',
    'Spazio → Tab',
    'MAIUSCOLO',
    'minuscolo',
    'Maiuscola A Ogni Parola',
    'Maiuscola a inizio frase',
    'iNVERTI mAIUSCOLE',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: scegli foglio…',
    'Alterna vista tabella / testo',
    'Elimina colonna…',
    'Valida i dati (numero di colonne · tipi)',
    'Banco di pulizia dei dati…',
    'Esegui una ricetta di pulizia…',
    'Converti…',
    'Cambia il separatore…',
    'Esporta in JSON…',
    'Formato',
    'Codifica…',
    'Fine riga…',
    'Normalizza Unicode…',
    'JSON: formatta',
    'JSON: compatta su una riga',
    'JSON: ordina le chiavi',
    'JSON: query JSONPath…',
    'CSV: query SQL…',
    'Query SQL',
    'In esecuzione…',
    'Esporta in una nuova scheda',
    'Documento vuoto — nessuna tabella da interrogare',
    'Non è una tabella CSV — la prima riga ha una sola colonna',
    'Impossibile leggere la query',
    'Impossibile verificare la query',
    'Giallo (predefinito)',
    'Blu',
    'Verde',
    'Ocra',
    'Viola',
    'Rosa',
    'Turchese',
    'Arancione',
    'Ardesia',
    'Testo',
    'Serie numerica',
    'Serie di date',
    'MAIUSCOLO (esadecimale)',
    'Inizio',
    'Passo',
    'Riempi di zeri fino a',
    'Base',
    'Prima data',
    'Formato',
    'Inserisci',
    'Annulla',
    'Converti il formato',
    'Anteprima delle prime 5 righe',
    'Apri in una nuova scheda',
    'Salva su file…',
    'Il risultato si apre in una nuova scheda non salvata. Il documento originale resta intatto.',
    'Esegui su questo documento',
    'Esegui su una cartella…',
    'L’intera ricetta è UN solo passo di annullamento. Il file su disco resta intatto finché non salvi.',
    'disattivato',
    'colonna non trovata',
    'pronto',
    'continua a occupare un core della CPU finché l’app non viene chiusa.',
    'Lo script non ha restituito nulla',
    'Impossibile creare il motore JavaScript',
    'Errore JavaScript sconosciuto',
    'Tabella',
    'Applica l’ordinamento al file',
    'Converti ▾',
    'Esporta le righe corrispondenti',
    'Nascondi questa colonna',
    'Rinomina l’intestazione…',
    'Inserisci una colonna vuota a sinistra',
    'Inserisci una colonna vuota a destra',
    'Elimina questa colonna dal file…',
    'Deve restare visibile almeno una colonna',
    'Ordinamento in corso…',
    'Torna all’ordine del file',
    'prime cento righe',
    'scegliere le colonne',
    'dare un nome a una colonna del risultato',
    'filtrare per testo',
    'celle vuote',
    'combinare condizioni',
    'contare le righe',
    'raggruppare e aggregare',
    'minimo, massimo',
    'ordinare e limitare',
    'nome di colonna con spazi',
    'La query è stata interrotta',
    'Non supportato: JOIN · sottoquery · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funzioni finestra',
    'XML: formatta',
    'XML: compatta su una riga',
    'XML: verifica la sintassi',
    'YAML: verifica chiavi duplicate e indentazione',
    'Vista',
    'Mostra/nascondi la barra laterale (elenco funzioni)',
    'Mostra/nascondi la mappa del documento',
    'Comprimi / espandi il blocco al cursore',
    'Comprimi tutto',
    'Espandi tutto',
    'Comprimi per livello',
    'Livello %d',
    '%d {one=blocco compresso|other=blocchi compressi} al livello %d',
    'Questo documento è profondo solo %d {one=livello|other=livelli}',
    'mermaid: manifest illeggibile',
    'Cerca aggiornamenti…',
    'Cerca aggiornamenti',
    'Le versioni App Store si aggiornano tramite il Mac App Store, non tramite GEditor.',
    'Questa build non ha una chiave di firma per gli aggiornamenti, quindi non può cercarli.',
    'Ingrandisci il testo',
    'Riduci il testo',
    'Dimensione reale',
    'Dividi verticalmente',
    'Dividi orizzontalmente',
    'Chiudi la divisione',
    'Apri questa scheda nell’altro riquadro',
    'Vai all’altro riquadro',
    'A capo automatico (disattivato / finestra / colonna)',
    'A capo alla colonna…',
    'Segna questa riga',
    'Segnalibro successivo',
    'Segnalibro precedente',
    'Colore dei segnalibri…',
    'Mostra tutti i caratteri invisibili',
    '  Spazi',
    '  Tabulazioni',
    '  Fine riga',
    '  NBSP · larghezza zero · controllo',
    'Vista binaria',
    'Modalità CSV (colonne colorate)',
    'Macro',
    'Avvia / ferma la registrazione',
    'Riproduci',
    'Riproduci più volte…',
    'Riproduci fino alla fine del documento',
    'Esegui su tutte le schede',
    'Annulla la macro in corso',
    'Salva la macro…',
    'Macro salvate…',
    'Aiuto',
    'Aiuto di GEditor',
    'Panoramica delle funzioni',
    'Migrare da Notepad++',
    'Trova',
    'Sostituisci con',
    'Successivo',
    'Precedente',
    'Conta',
    'Chiudi',
    'Valida con uno schema JSON…',
    'Scegli un file di schema JSON',
    'Nessun problema trovato secondo questo schema.',
    'Schema JSON',
    'Verifica la sintassi del grafo',
    'Formato del grafo non riconosciuto — serve un’estensione .dot, .gv, .cypher, .ttl o .graphml.',
    'Nessun errore di sintassi %@ trovato (la verifica non è esaustiva).',
    'Sintassi %@',
    'non è un oggetto JSON',
    'Text mining (n-grammi, TF-IDF)',
    'Il documento è vuoto.',
    'Non è stato possibile estrarre alcuna parola chiave.',
    'Parole chiave',
    '%d {one=parola chiave|other=parole chiave} · %d token · %d {one=documento|other=documenti}',
    'Segna nel documento',
    'Segna entità da un elenco…',
    'Scegli un elenco di entità (CSV o JSON)',
    'Impossibile leggere l’elenco di entità.',
    'L’elenco di entità è vuoto.',
    'Nessuna entità trovata nel documento (%d caricate).',
    '%d {one=occorrenza|other=occorrenze} · %@',
    'Converti conoscenza…',
    'Conversione: %@ → %@',
    'Conversione non riuscita.',
    'Anteprima della suddivisione…',
    'Dimensione fissa 800 B, sovrapposizione 100 B',
    'Per frase (≤ 800 B)',
    'Per titolo Markdown',
    'Documento vuoto — nessun frammento.',
    '%d {one=frammento|other=frammenti} · %d B in media · %@',
    'Esporta JSONL',
    'Frammenti JSONL',
    'Apri triple/archi come tabella',
    'Tabella di triple',
    'Questo documento non ha alcuna riga di tripla.',
    'Non è stato possibile leggere alcuna tripla — riga %d: %@',
    '%d {one=tripla letta|other=triple lette} · %d {one=riga malformata saltata|other=righe malformate saltate} (la prima: riga %d)',
    'Duplicati approssimati per colonna…',
    'Duplicati approssimati — colonna «%@»: %d {one=gruppo candidato|other=gruppi candidati}',
    'Unisci',
    'Corrispondenza',
    'Valori del gruppo',
    'Unisci in',
    'Unisci i gruppi selezionati',
    'Nessun gruppo selezionato — premere Unisci NON cambierà nulla. L’app non unisce mai da sola.',
    '%d {one=gruppo selezionato|other=gruppi selezionati} · %d {one=riga cambierà|other=righe cambieranno} · UN solo passo di annullamento',
    'Impossibile analizzare questa colonna.',
    'La colonna «%@» non ha gruppi di duplicati approssimati.',
    'Nessun gruppo unito — il documento resta invariato.',
    'Deduplicazione approssimata · colonna %@',
    '%d {one=gruppo unito|other=gruppi uniti} · %d {one=cella modificata|other=celle modificate}',
    'Rapporto di pulizia',
    '# Rapporto di pulizia — %@\n\n',
    '## Applicato (%d)\n\n',
    '_Nessun passo applicato._\n',
    '\n## Profilo dei dati\n\n',
    '_%d {one=colonna|other=colonne} · %d {one=riga|other=righe} · analizzato in %.1f s_\n\n',
    '| Colonna | Tipo | Null | Distinti | Min | Max | Media |\n',
    '\n### Valori anomali\n\n',
    'riga %d: %@',
    '- colonna «%@» — %d {one=cella|other=celle}: %@\n',
    '\n## Rimanente (%d)\n\n',
    '_Non restano rilevazioni._\n',
    '- colonna «%@»: %@\n',
    None,
    'Rimuovi gli spazi al salvataggio',
    'Normalizza i fine riga',
    'precedente',
    'Impossibile riaprire la cartella «%@» della sessione precedente',
    ' (e %d {one=altro file|other=altri file})',
    'Impossibile riaprire %d {one=scheda|other=schede}: %@%@ — i file non sono più dov’erano.',
    'Impossibile leggere l’input dalla pipe',
    'Gli spazi a fine riga verranno rimossi a ogni salvataggio',
    'Gli spazi non vengono più rimossi al salvataggio',
    'Senza titolo.txt',
    'Convertire la codifica farà perdere caratteri',
    'Salva comunque',
    'Il documento ha modifiche non salvate',
    'Chiudere senza salvare le scarterà.',
    'Scarta le modifiche',
    'Vai alla riga',
    'Il documento ha %d {one=riga|other=righe}.',
    'Numero di riga',
    'Vai',
    'Reinterpreta come…',
    'Converti in…',
    'Reinterpretazione non riuscita',
    '%@ non può rappresentare tutti i caratteri',
    'Scegli comunque',
    'Colonna %d',
    'Colonna %d: %@',
    'Colonne nascoste: %@ (%d) — ripristinale dal menu contestuale della riga di intestazione',
    'Mostra di nuovo: %@',
    'Colonna %@ nascosta — resta intatta nel file',
    'Ordinato per %@ %@ · solo visualizzazione',
    'Ordinato: %@ %@ (solo visualizzazione)',
    '%d+ righe corrispondono — ricerca in corso…',
    '%d / %d {one=riga corrisponde|other=righe corrispondono}',
    'Nessun problema trovato in %d {one=riga|other=righe}',
    '%d {one=riga|other=righe} con un numero di colonne errato',
    '%d {one=cella|other=celle} con il tipo di dato errato',
    ' (fermato ai primi %d {one=problema|other=problemi})',
    '   —   tipi rilevati: ',
    'Riga %d, colonna %@: «%@» non è %@',
    'Editor di colonne — %d {one=riga|other=righe}',
    'Rilevazioni',
    'Profilo dei dati',
    'Profilo dei dati — analisi in corso…',
    'Salva la ricetta…',
    'Esporta il rapporto',
    'Nessun gruppo applicato · ogni gruppo è un passo di annullamento',
    'troppi valori',
    'più frequenti: ',
    'Valore con cui riempire le celle vuote',
    'Applica',
    'Impossibile costruire un’anteprima',
    '· lasciato com’è, illeggibile ·',
    'Converti la colonna in ISO 8601 (AAAA-MM-GG)',
    'Convenzione numerica per tutta la colonna',
    'Cosa fare con le celle vuote',
    'Normalizza in ISO 8601',
    'Leggi le celle ambigue con il GIORNO prima (31/12)',
    'Leggi le celle ambigue con il MESE prima (12/31)',
    'Salta le celle ambigue, correggi solo quelle certe',
    'In vietnamita/europeo (1.234,56)',
    'In angloamericano (1,234.56)',
    'In angloamericano, senza separatore delle migliaia (1234.56)',
    'Riempi con un valore predefinito…',
    'Riempi verso il basso — prendi il valore sopra',
    'Riempi verso l’alto — prendi il valore sotto',
    'Elimina le righe con cella vuota in questa colonna',
    'Rimuovi gli spazi a entrambe le estremità',
    'Rimuovi alle estremità e comprimi gli spazi interni',
    'Tabella pivot…',
    'Sorgenti…',
    'Tabella pivot — raggruppa per colonna',
    'Righe (raggruppamento)',
    'Valori',
    '+ Riga',
    '+ Valore',
    'Cancella tutto',
    'Metti nella query',
    'Scegli le colonne per costruire la query.',
    'Impossibile leggere i nomi di colonna di questa tabella.',
    'Sorgenti dati della query',
    '«%@» — il documento aperto',
    '  ⚠️ il file è cambiato da quando è stato registrato',
    'Aggiungi file…',
    'Rimuovi tutto',
    'Impossibile dedurre un nome di tabella da «%@» — rinomina il file.',
    'Somma',
    'Media',
    'Min',
    'Max',
    'Conteggio distinto',
    'Grafico',
    'Esporta PNG',
    'Esporta SVG',
    'Questa tabella non ha alcuna colonna numerica da rappresentare.',
    'Impossibile costruire l’immagine PNG.',
    'Risultato della query',
    '%@ salvato',
    'Grafico %@ di «%@» — %d {one=punto|other=punti}, valori da %@ a %@',
    'Barre',
    'Linea',
    'Istogramma',
    'Dispersione',
    'Box',
    'CSV: qualità dei dati…',
    'Qualità dei dati',
    'Esporta le violazioni in una nuova scheda',
    'Livello',
    'Regola',
    'Violazioni',
    'Tasso',
    'superato',
    'errore',
    'avviso',
    'rotto',
    '%d {one=riga in violazione segnata|other=righe in violazione segnate}',
    'Andamento',
    'Valutato il',
    'Righe',
    'Scarto',
    'Regole fallite',
    'Punteggio di qualità',
    'Punteggio nel tempo',
    'Ancora nessuna cronologia — ogni valutazione aggiunge ',
    'una riga al file «.history.jsonl» accanto alle regole.',
    '%d {one=punto|other=punti} nella cronologia',
    ' · %d {one=riga ILLEGGIBILE|other=righe ILLEGGIBILI}',
    ' · seleziona due righe per confrontare',
    'punteggio %+.1f',
    'nessuna dimensione è scesa',
    'scese: ',
    '%d {one=regola che ora fallisce|other=regole che ora falliscono}: %@',
    'righe %+d',
    ' (e %d {one=altro avviso|other=altri avvisi} nella scheda Andamento)',
    'Nessuna correzione automatica: ',
    'Apre lo strumento corrispondente nel Banco di pulizia, poi rivaluta subito.',
    'Gestisci i valori mancanti…',
    'Normalizza le date…',
    'Rimuovi i duplicati…',
    'Sostituisci…',
    'Mostra le righe errate',
    'La colonna «%@» non è in questa tabella.',
    'Duplicati rimossi — «%@» ora è univoca. Punteggio: %.0f/100',
    'Duplicati rimossi, ma «%@» ha ancora %d {one=riga ripetuta|other=righe ripetute} (prima: %d) — ',
    'quelle righe condividono la CHIAVE ma non l’intera riga, quindi devi guardarle e scegliere ',
    'quale tenere.',
    'Impossibile leggere un valore che violi questa regola.',
    '%d {one=valore errato|other=valori errati} nella colonna «%@» — compila Sostituisci e premi Anteprima',
    'Rivalutato: %.0f/100',
    'Anteprima del rapporto',
    'Parametri…',
    'Esporta HTML…',
    'Stampa / PDF…',
    '%d {one=blocco eseguito|other=blocchi eseguiti} · %d {one=blocco FALLITO|other=blocchi FALLITI}',
    '%d {one=blocco eseguito|other=blocchi eseguiti}',
    ' · DATI OBSOLETI — il file sorgente è cambiato; ricostruisci',
    'L’anteprima del rapporto richiede un documento .%@',
    'Nessuna sorgente dati trovata — dichiara «source: file.csv» nel frontmatter.',
    'Impossibile costruire il rapporto.',
    'Questo rapporto non dichiara alcun parametro nel frontmatter.',
    'Parametri del rapporto',
    'Ricostruisci',
    '%@ esportato',
    'Rapporto: anteprima',
    'Rapporto: generazione in blocco…',
    'non è un documento .greport.md',
    'impossibile analizzare il rapporto',
    'impossibile trovare i dati sorgente',
    'impossibile leggere l’elenco dei parametri',
    'La generazione in blocco richiede un documento .%@',
    'Scegli un elenco di parametri (CSV o JSON)',
    'Scegli una cartella per %d {one=rapporto|other=rapporti}',
    '[%d/%d] %@',
    'parametri mancanti ',
    'punta al file sorgente stesso — sovrascrittura rifiutata',
    '%d {one=blocco FALLITO|other=blocchi FALLITI}',
    'Blocco completato: %d {one=file|other=file} · %d falliti',
    '%d {one=set di parametri non è stato costruito|other=set di parametri non sono stati costruiti} — vedi il riepilogo',
    'Diagramma Mermaid: anteprima',
    'Diagramma Mermaid: inserisci un modello…',
    'Diagramma Mermaid: riformatta',
    'Sfondo trasparente',
    'Questo Mac non può convertire il diagramma in PNG — serve macOS 13. L’esportazione SVG funziona comunque.',
    'Salva PNG %@…',
    'Salva SVG…',
    'Copia l’immagine negli appunti',
    'Colori del marchio…',
    'Colori del marchio per i diagrammi',
    'Ogni campo è un colore #rrggbb. Salvato in «themes/mermaid-brand.json» — copiabile su un altro Mac.',
    'Colore principale',
    'Testo sui nodi',
    'Bordo',
    'Collegamenti',
    'Sfondo all’esportazione',
    'Salva e inserisci %%{init}%% nel documento',
    'Colori del marchio salvati',
    'Immagine del diagramma copiata negli appunti',
    '%@ salvato — %@',
    'Questo diagramma ha già una direttiva %%{init}%% — la tua resta intatta.',
    '%%{init}%% inserito — il diagramma porta ora i propri colori',
    'Inserisci i colori del marchio nel diagramma',
    'Riformatta il diagramma Mermaid',
    'Il codice del diagramma è già in ordine — nulla da cambiare',
    'Diagramma riformattato',
    '%d {one=diagramma riformattato|other=diagrammi riformattati}',
    'Libreria di modelli di diagramma',
    'Modelli di diagramma completi',
    'Frammenti di sintassi',
    'In modifica: %@',
    'Modello «%@» inserito',
    'Questo documento è di sola lettura.',
    'Diagramma Mermaid',
    'Questo documento non ha alcun blocco mermaid.',
    'Marchio',
    'Esporta…',
    'Ancora nessun diagramma',
    '%d {one=diagramma|other=diagrammi} · %@',
    '%d/%d {one=diagramma FALLITO|other=diagrammi FALLITI} — diagramma %d%@',
    ', riga %d',
    'Questo documento non ha alcun blocco ```mermaid e non è nemmeno un file .mmd.',
    'Nessun diagramma ha finito di essere disegnato.',
    '«%@» non è stato trovato nel codice del diagramma',
    'impossibile costruire la barriera di rete per WKWebView',
    'Regole di associazione',
    'Un carrello per riga',
    'Due colonne: id · articolo',
    'Forma dei dati transazionali',
    'Colonna carrello o id transazione',
    'Colonna articolo',
    'Carattere separatore degli articoli',
    'Supporto minimo, percentuale',
    'Confidenza minima, percentuale',
    'Separato da:',
    'Supporto ≥',
    '% · Confidenza ≥',
    'Tabella delle regole di associazione',
    'Supporto',
    'Confidenza',
    'Lift',
    'Leverage',
    'Attenzione',
    '%d {one=transazione|other=transazioni} · %d {one=articolo|other=articoli} · %d {one=regola|other=regole}',
    ' — nessuna regola ha raggiunto le soglie; abbassa supporto o confidenza',
    ' — FERMATO IN ANTICIPO, la tabella è INCOMPLETA',
    '%d / %d {one=transazione contiene|other=transazioni contengono} entrambi i lati',
    'La forma a due colonne richiede due colonne DIVERSE.',
    '%d {one=riga segnata|other=righe segnate} in %d {one=transazione che contiene|other=transazioni che contengono} «%@»',
    'CSV: regole di associazione…',
    'Mining per gruppi',
    'Colonna di gruppo',
    'Colonna dei valori',
    'Seconda colonna per la correlazione',
    'Criterio di classifica',
    'Raggruppa per:',
    'Valore:',
    'Ordina per:',
    'Tabella di classifica dei gruppi',
    'Gruppo',
    'Righe',
    'Soglia propria',
    'MAPE',
    'r',
    'Scarto r',
    'Nota',
    'non misurabile',
    '%d {one=gruppo|other=gruppi} · correlazione globale di riferimento %@',
    ' · %d {one=GRUPPO SCARTATO|other=GRUPPI SCARTATI}',
    'Questa tabella non ha alcuna colonna di testo per raggruppare.',
    'Questa tabella non ha alcuna colonna numerica da esplorare.',
    '%d {one=riga del gruppo|other=righe del gruppo} «%@» {one=segnata|other=segnate}',
    'CSV: mining per gruppi…',
    '↔',
    'Previsione',
    'Colonna dei valori nel tempo',
    'Modello di previsione',
    'Numero di periodi da prevedere',
    'Verdetto rispetto ai modelli di riferimento',
    'Modello:',
    'Periodi:',
    'Stagione:',
    'auto',
    'Periodo stagionale; lascia vuoto per il rilevamento automatico',
    'Tabella dei valori previsti',
    'Periodo',
    'Banda all’80 %',
    'Banda al 95 %',
    'MAE %@ · MAPE %@',
    'non calcolabile',
    'Questa tabella non ha alcuna colonna numerica da prevedere.',
    'Impossibile costruire una previsione per questa colonna.',
    'La colonna «%@» ha solo %d {one=valore numerico|other=valori numerici} — ne servono almeno 4 per prevedere.',
    '# La serie viene letta nell’ordine delle righe del file — senza riordinare, senza dedurre una colonna temporale.\n',
    'Errore di addestramento',
    'CSV: previsione di serie temporali…',
    'Holt-Winters additivo',
    'Holt-Winters moltiplicativo',
    'seasonal-naive',
    'naive',
    'Colonne usate per il clustering',
    'Curva WCSS',
    'Cluster',
    'Scalatura:',
    'k:',
    'eps:',
    'minPts:',
    'Seleziona almeno una colonna.',
    'Dati insufficienti per costruire la curva.',
    'Il gomito suggerisce k = %d. Il WCSS scende SEMPRE al crescere di k, quindi è un accorgimento di lettura del grafico e non un criterio statistico — guarda la curva e giudica se la piega è netta.',
    'WCSS per k',
    'La k-distanza suggerisce eps = %@ (minPts vale per default 2 × numero di colonne = %d). %@',
    'Distanza dal k-esimo vicino',
    'Per il clustering servono almeno 2 colonne numeriche.',
    'Cluster per %@ e %@',
    ' — cluster trovati in %d {one=dimensione|other=dimensioni}; il grafico mostra solo le prime 2',
    '# rumore (cluster_id = -1): %d {one=riga|other=righe}\n',
    'CSV: clustering…',
    '# --- Centri dei cluster (unità originali) ---\n',
    'k-means',
    'DBSCAN',
    'Matrice di correlazione',
    'Metodo di correlazione',
    'Correlazione non implica causalità.',
    'Coppia più forte: %@ ↔ %@ = %@ (n = %d). Fai clic su una cella per il grafico a dispersione.',
    'Nessuna coppia è misurabile.',
    '%@ ↔ %@: %@ su %d {one=riga|other=righe}',
    'Per la correlazione servono almeno 2 colonne numeriche.',
    'Impossibile leggere la colonna «%@».',
    'CSV: matrice di correlazione…',
    'Anomalie',
    'Elenco delle anomalie',
    'Colonna:',
    'Colonna numerica da esaminare',
    'Metodo:',
    'Metodo di rilevamento',
    'Metodo usato',
    'Soglia',
    'Segna',
    'Esporta in una nuova scheda',
    'Riga',
    'Punteggio',
    'Perché',
    'lieve',
    'moderata',
    'grave',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=riga|other=righe} (%.2f %%)',
    'Questa tabella non ha alcuna colonna numerica in cui cercare anomalie.',
    '%d {one=riga anomala segnata|other=righe anomale segnate}',
    'CSV: trova anomalie…',
    '%d {one=regola, SUPERATA|other=regole, tutte SUPERATE} · %d {one=riga|other=righe} · %.0f ms',
    '%d {one=errore|other=errori} · %d {one=avviso|other=avvisi} su %d {one=regola|other=regole} · %d {one=riga|other=righe} · %.0f ms',
    'Salva prima il documento — le regole di qualità stanno accanto al file di dati.',
    'Nessun set di regole. Crea il file %@ e riapri.',
    'Cronologia',
    'Query salvate',
    'Salva questa query…',
    'Salva la query',
    'Dalle un nome per ritrovarla dopo. Lo stesso nome sovrascrive.',
    'Per esempio: Ricavi per provincia',
    'Nessun valore inserito per il parametro: %@',
    'L’estensione è cambiata da quando l’hai approvata — GEditor si rifiuta di eseguirla',
    'Eseguire un’estensione non approvata?',
    'Mi fido di questo file — esegui',
    'NON firmata',
    'Firma: %@',
    'Percorso: %@',
    'Sostituisci',
    'Sostituisci tutto',
    'Testo semplice',
    'Esteso (\\n \\t \\xNN)',
    'Espressione regolare',
    'Distingui maiuscole',
    'Parola intera',
    'Nessun risultato',
    'Prova un’espressione regolare…',
    'Modalità log (colore per livello)',
    'Filtra il log per livello…',
    'Esegui sull’intera cartella…',
    'Filtra con un comando esterno…',
    'Script…',
    'Pacchetti di estensione…',
    'Nuova finestra',
    'Stacca la scheda in una nuova finestra',
    'Nessuna cartella aperta',
    'Cerca un file nella cartella',
    'Filtra per nome',
    'Nuovo file…',
    'Nuova cartella…',
    'Rinomina…',
    'Sposta nel Cestino',
    'Mostra nel Finder',
    'Lettura della struttura del documento…',
    'questo file non ha funzioni',
    'Nessuna corrispondenza',
    'Testo semplice',
    '🔒 Sola lettura',
    'In ascolto',
    'a capo alla colonna',
    'Sintassi',
    'Fai clic per inserire nella query',
    'query non valida',
    'chiave «nome» alla radice',
    'chiave con spazi',
    'primo elemento',
    'tutti gli elementi',
    'porzione',
    'unione di indici',
    'tutte le chiavi «prezzo» a ogni livello',
    'tutti i nodi',
    'filtra per numero',
    'filtra per presenza',
    'Vai al primo errore',
    'La colonna ricavi è numerica',
    'filtra…',
    'Annulla',
    'Esegui la sostituzione',
    'anteprima',
    'interattivo',
    'Modifica',
    'Interfaccia',
    'Scorciatoie da tastiera',
    'Dimensione del testo',
    'Larghezza della tabulazione',
    'Indenta con tabulazioni',
    'Indenta automaticamente andando a capo',
    'Evidenzia tutti i risultati della ricerca',
    'Normalizza in NFC al salvataggio',
    'Lingua',
    'Aspetto',
    'Di sistema',
    'Chiaro',
    'Scuro',
    'Tema',
    'Usa il preset di Notepad++',
    'Torna ai tasti predefiniti',
    'Apri il file di configurazione',
    'Esporta il tema attuale',
    'Il cambio di lingua si applica del tutto al prossimo avvio.',
    'I tasti predefiniti tornano al prossimo avvio.',
    'Anteprima Markdown',
    'L’anteprima usa il motore Markdown di sistema: ancora senza tabelle né colorazione dei blocchi di codice.',
    'Prova un’espressione regolare',
    'Espressione',
    'Testo di prova',
    'Risultato',
    'Corrispondenze',
    'Cosa fa questa espressione',
    'Spiega l’espressione',
    'Modalità di ricerca',
    'Risultati della ricerca',
    'Nessuna corrispondenza',
    ' (troncato)',
    'Mappa del documento',
    'Barra delle schede',
    'Riga di intestazione delle colonne',
    'Nessuna colonna',
    'Albero dell’area di lavoro',
    'Elenco di funzioni e classi',
    'Risultati della ricerca nella cartella',
    'Tabella dati CSV',
    'Banco di pulizia dei dati',
    'Query JSONPath',
    'Elenco degli errori nei dati',
    'Valutatore del golden set…',
    'Confronta con punteggi esterni (JSONL)…',
    'Scegli un file di punteggi esterni (JSONL: query, chunk_id, score)',
    'Rinomina il nodo selezionato',
    'Unisci i nodi selezionati',
    'Dividi il nodo selezionato',
    'Estrai il sottografo selezionato in una nuova scheda',
    'Nulla da cambiare',
    '%@ — applicare %d {one=modifica|other=modifiche}?',
    '%@: %d {one=modifica|other=modifiche} · Cmd-Z annulla l’intero blocco',
    'Metti il cursore su ESATTAMENTE UN nodo e riprova',
    'Rinomina «%@»',
    'Tutti gli archi e le etichette che fanno riferimento a questo nodo cambieranno con esso.',
    'Rinomina il nodo',
    'Seleziona ALMENO DUE nodi e riprova',
    'Forma canonica «%@» — la più frequente, la più lunga, accentata',
    'Unisci i nodi',
    'Seleziona le RIGHE DI ARCO da spostare e riprova',
    'Tutte le righe selezionate devono toccare ESATTAMENTE UN nodo — seleziona altre righe di arco',
    'Dividi «%@» — sposta %d {one=arco|other=archi}',
    'Archi verso: %@',
    'Dividi il nodo',
    'Documento non salvato — il file estratto ha bisogno di un posto accanto',
    'Seleziona la parte del grafo da estrarre e riprova',
    'Raggruppa le varianti di entità → tabella di revisione',
    'Applica la tabella di revisione modificata',
    'Documento non salvato — la tabella di revisione deve stare accanto al file del grafo',
    'Nessuna variante da raggruppare',
    '%d {one=gruppo di varianti|other=gruppi di varianti} — correggi la colonna «canonical» ed esegui «Applica la tabella di revisione»',
    'Nessuna tabella di revisione «%@» — esegui prima «Raggruppa le varianti di entità»',
    'Tabella di revisione illeggibile: %@',
    'La tabella di revisione non ha righe da cambiare',
    'Nessun punto del grafo corrisponde alla tabella di revisione',
    'Raggruppa le varianti di entità',
    '%d {one=modifica applicata|other=modifiche applicate} · tabella di alias ed elenco di marcatori scritti accanto al file',
    'Applicare %d {one=modifica|other=modifiche} al grafo?',
    '%d {one=alias|other=alias} → forma canonica.',
    'UNIRE i nodi (non si annulla riscrivendo):',
    '%d {one=alias non è nel grafo e viene saltato|other=alias non sono nel grafo e vengono saltati}.',
    'GraphRAG…',
    'Analisi di copertura Frammento ↔ Entità',
    'Esporta il pacchetto di contesto (JSONL)',
    'Copertura Frammento ↔ Entità ↔ Grafo',
    '- %d {one=entità|other=entità} · %d {one=frammento|other=frammenti} · %.0f %% di entità citate · %.0f %% di frammenti con entità',
    'Entità che nessun frammento cita',
    'Frammenti orfani (senza alcuna entità)',
    'Nodi del grafo senza entità corrispondente',
    'nessuno',
    'Metodo',
    'Impossibile costruire la corrispondenza Frammento ↔ Entità',
    'Valuta la salute del grafo',
    'salute del grafo',
    'Salute %@/100 · %d {one=errore|other=errori} · %d {one=inversione|other=inversioni} · %d orfani',
    'Ibrido con il grafo',
    'α = 1: il segnale del grafo è del tutto ignorato, il risultato coincide con BM25 puro',
    'α alto: il grafo regola solo leggermente la classifica di BM25',
    'α intorno al valore predefinito 0,7: comanda BM25, il grafo regola',
    'α basso: comanda il grafo, BM25 rompe solo la parità',
    'α = 0: solo il segnale del grafo; i frammenti senza entità restano a pari merito',
    'Documento non salvato — l’ibrido ha bisogno di un file di grafo accanto al corpus',
    'File di grafo «%@» non trovato — l’ibrido ne ha bisogno per il suo segnale',
    'ibrido %.1f ms · %@',
    'Algoritmi…',
    'PageRank (spessore del bordo)',
    'Comunità (colore di sfondo)',
    'Componenti connesse',
    'Esporta la tabella dei nodi in una nuova scheda',
    '%d {one=componente|other=componenti} · la più grande %d {one=nodo|other=nodi} · %d nodi orfani',
    'Questo documento non è un grafo DOT',
    'Impossibile costruire la tabella di nodi/archi: %@',
    '%d {one=riga|other=righe} · %@',
    'Etichetta',
    'Nota (facoltativa)',
    'Salva il record',
    'Esporta CSV',
    'Documento non salvato — il valutatore deve stare accanto al file di corpus',
    'Impossibile caricare il valutatore: %@',
    'Impossibile salvare: %@',
    'Il valutatore non ha ancora alcun record',
    'Impossibile scrivere: %@',
    'Questo documento non è un file .mmd, non è DOT e non ha alcun blocco mermaid.',
    '%d {one=nodo|other=nodi} · %d {one=arco|other=archi} · ⚠ %@',
    'Diagramma Mermaid: aggiungi un elemento…',
    'Diagramma Mermaid: collega i due elementi selezionati',
    'Diagramma Mermaid: modifica l’etichetta dell’elemento selezionato…',
    'Diagramma Mermaid: elimina l’elemento selezionato',
    'Diagramma Mermaid: sposta il messaggio in su',
    'Diagramma Mermaid: sposta il messaggio in giù',
    'Aggiungi un elemento',
    'Aggiungi un partecipante',
    'Aggiungi una voce',
    'Aggiungi una voce al diagramma',
    'Modifica una voce del diagramma',
    'Elimina una voce del diagramma',
    'Elimina l’elemento',
    'Modifica l’etichetta',
    'Riordina i messaggi',
    'Nome della voce',
    'Nuova voce',
    'Il nome della voce appare sul diagramma.',
    'Tabella delle proprietà del diagramma',
    'Questo documento non ha alcun blocco mermaid',
    'Identificatore nel codice del diagramma — senza spazi. L’etichetta si modifica poi con un doppio clic.',
    'Se lasciato vuoto, viene mostrato l’identificatore stesso.',
    'Cambia solo l’ETICHETTA visibile; l’identificatore dell’elemento resta lo stesso.',
    'Non è chiaro quale elemento sia «%@»',
    'Seleziona ESATTAMENTE DUE elementi e riprova',
    'Metti il cursore su ESATTAMENTE UN elemento e riprova',
    'Scegli UN elemento da eliminare, o due elementi collegati da un arco',
    'Eliminare «%@» e %d {one=arco che lo tocca|other=archi che lo toccano}?',
    'I nodi all’altro capo di quegli archi vengono conservati — sono ridichiarati con la loro etichetta se l’istruzione di arco era la loro unica dichiarazione.',
    'Il diagramma «%@» si modifica solo come testo — %@',
    '%@: trascina tra due elementi per collegarli, doppio clic per modificare l’etichetta',
    '%@: trascina tra due partecipanti per aggiungere un messaggio; riordina dal menu Strumenti',
    '%@: modifica nella tabella delle proprietà qui sotto',
    'Modifica visuale attivata',
    '%@ · %d {one=voce|other=voci} — modifica direttamente nella tabella, ogni cella è un passo di annullamento',
    'Per un grafico a torta un numero; per un gantt, ciò che segue i due punti.',
    'Diagramma Mermaid: estrai il blocco in un file .mmd…',
    'Diagramma Mermaid: reincorpora il file referenziato',
    'Estrai il blocco del diagramma',
    'Reincorpora il blocco del diagramma',
    'Estrai il blocco del diagramma in un file separato',
    'Il file viene messo ACCANTO al documento; il blocco conserva una riga di riferimento per modificare in un solo posto.',
    'Documento non salvato — il file del diagramma ha bisogno di un posto accanto',
    'Il file «%@» esiste già — scegli un altro nome',
    'Estratto in «%@» — il blocco conserva una riga di riferimento',
    'Apri il file',
    '«%@» reincorporato; il file resta sul disco',
    'Questo blocco contiene un diagramma vero, non un riferimento',
    'Questo blocco fa riferimento a «%@» — apri quel file per modificarlo',
    'Impossibile leggere il file di diagramma %@',
    'Modifica visuale',
    'Trascina da un nodo all’altro per aggiungere un arco; doppio clic per modificare l’etichetta. Ogni azione è un passo di annullamento.',
    'Modifica visuale: trascina tra due nodi per aggiungere un arco, doppio clic per modificare l’etichetta',
    'Modifica visuale disattivata',
    'Aggiungi un nodo…',
    'Aggiungi un arco tra i due nodi selezionati…',
    'Modifica l’etichetta del nodo selezionato…',
    'Elimina il nodo/arco selezionato',
    'Aggiungi un nodo',
    'Aggiungi un arco',
    'Modifica l’etichetta del nodo',
    'Elimina il nodo',
    'Elimina l’arco',
    'Cmd-Z annulla',
    'Questo documento è di sola lettura',
    'Etichetta di «%@»',
    'Cambia solo l’ETICHETTA visibile; l’identificatore del nodo resta lo stesso.',
    'Non è chiaro quale nodo sia «%@»',
    'Identificatore del nodo nel file DOT. L’etichetta si modifica poi con un doppio clic sul grafico.',
    'Seleziona ESATTAMENTE DUE nodi e riprova',
    'Scegli UN nodo da eliminare, o due nodi collegati da un arco',
    'Eliminare il nodo «%@» e %d {one=arco che lo tocca|other=archi che lo toccano}?',
    'Se restano archi orfani, DOT ricrea i nodi da essi — il nodo eliminato ricomparirà al disegno successivo.',
    'Laboratorio di retrieval BM25',
    'Domanda — Invio per cercare',
    'Valuta…',
    'Costruzione dell’indice',
    'Nessun frammento corrisponde',
    'risultati migliori',
    'k1 = 0: ogni parola conta SOLO una volta, per quante volte compaia',
    'k1 basso: ripetere una parola non aggiunge quasi punteggio',
    'k1 intorno al valore predefinito 1,2: ripetere aggiunge punteggio, ma sempre meno',
    'k1 alto: un frammento che ripete una parola viene premiato molto',
    'b = 0: la lunghezza è ignorata, i frammenti lunghi non sono penalizzati',
    'b basso: i frammenti lunghi sono penalizzati solo un poco',
    'b intorno al valore predefinito 0,75: i frammenti lunghi sono penalizzati moderatamente',
    'b = 1: penalità massima per la lunghezza, i frammenti corti sono favoriti',
    'JSONL: laboratorio di retrieval…',
    'Documento non salvato — l’indice BM25 sta accanto al file di corpus e ha quindi bisogno di un percorso',
    'Questo file non è JSONL — il Retrieval Lab lavora su un corpus di frammenti',
    'Impossibile costruire un indice BM25 per questo file',
    'Documento non salvato — serve un percorso di corpus per generare il rapporto',
    'Scegli un set di valutazione (CSV o JSONL: domanda + id del frammento atteso)',
    'Valutazione del retrieval',
    'Cambia k1, b o k qui sopra e riesamina per confrontare due configurazioni; aggiungi un blocco «compare» per eseguire due set di parametri in parallelo sullo stesso set di valutazione.',
    'Errore',
    '   (%d…%d, media %.0f)',
    'Modalità JSONL',
    'Record',
    'Dettaglio',
    'Record alla riga',
    'non è JSON valido',
    'record',
    'righe vuote',
    'non è un oggetto',
    'tabella mostrata',
    'ANNULLATO a metà',
    'Nessun filtro',
    'record che corrispondono al filtro',
    'Metti il cursore su una riga per vedere il record',
    'Nessun record difettoso',
    'Non ancora ispezionato. Riesegui «JSONL: ispeziona i frammenti» dopo la verifica.',
    'campo di testo',
    'SCHEMA (indovinato — si cambia scegliendo un altro campo)',
    'testo',
    'identificatore',
    'metadati annidati',
    'CAMPO',
    'copertura',
    'più tipi',
    'LUNGHEZZA — caratteri',
    'LUNGHEZZA — parole',
    'LUNGHEZZA — token stimati',
    'VUOTI E DUPLICATI',
    'frammenti vuoti',
    'righe',
    'gruppi di duplicati esatti',
    'righe illeggibili, fuori dalle statistiche',
    'METODO',
    '«caratteri» conta i caratteri Unicode (scalari), non i gruppi visibili',
    '«parole» divide sugli spazi ASCII',
    '«token» conta con un divisore di sillabe — NON è quello del modello',
    '«duplicato» significa duplicato ESATTO; i quasi-duplicati stanno nel blocco ```quality',
    'frammenti',
    'JSONL: verifica e ispeziona i frammenti…',
    'Immagine',
    'PDF',
    'Documento Word',
    'Foglio di calcolo Excel',
    'Presentazione PowerPoint',
    'Archivio',
    'Adatta alla finestra',
    'Copia l’immagine',
    'Ruota',
    'Impossibile leggere l’immagine «%@»',
    'Immagine copiata negli appunti',
    'Evidenzia in giallo',
    'Sottolinea',
    'Nota…',
    'Rimuovi le annotazioni',
    'Estrai il testo in una nuova scheda',
    'Salva la versione annotata…',
    'Cerca nel PDF',
    'Aggiungi',
    'Pagina %d/%d',
    'Pagina %d',
    'Risultato %d/%d',
    '0 risultati',
    'Impossibile leggere il PDF «%@»',
    'Questo PDF è protetto da password — il contenuto non è accessibile',
    '«%@» non è stato trovato nel documento',
    'Evidenziato',
    'Sottolineato',
    'Seleziona prima un brano di testo',
    'Nota aggiunta',
    'Questa pagina non ha annotazioni',
    '%d {one=annotazione rimossa|other=annotazioni rimosse} da questa pagina',
    'Questo PDF non ha un livello di testo — è probabilmente una scansione',
    'Impossibile scrivere il file',
    'Il file scritto NON si riapre correttamente — non usare questa versione',
    '%@ salvato · %d {one=pagina|other=pagine}',
    'Nome',
    'Dimensione',
    'Compresso',
    'Rapporto',
    'Modificato il',
    'Apri l’elemento selezionato',
    'Estrai in una cartella…',
    'Estrai qui',
    '%d {one=elemento|other=elementi}',
    'estratto in %@',
    '— l’interno di un file Office è un archivio; queste sono le sue parti',
    '%d {one=elemento estratto|other=elementi estratti}',
    '%d {one=elemento difettoso|other=elementi difettosi}',
    '%d {one=elemento RIFIUTATO|other=elementi RIFIUTATI} perché i loro percorsi escono dalla cartella di destinazione',
    'Impossibile aprire questo elemento',
    'Non è ancora possibile scrivere direttamente in un %@ — usa «Salva come…»',
    'Non è cambiato nulla',
    '%d {one=cella scritta|other=celle scritte} in %@',
    '%d {one=paragrafo scritto|other=paragrafi scritti} in %@',
    'Impossibile scrivere nel file — l’originale resta intatto',
    'preparare il caso di prova',
    'Impossibile scrivere settings.json',
    'Ruota a sinistra',
    'Ruota a destra',
    'Sposta pagina su',
    'Sposta pagina giù',
    'Elimina pagine…',
    'Elimina pagine',
    'Estrai pagine…',
    'Estrai pagine in un nuovo file',
    'Unisci file PDF…',
    'Dividi file…',
    'Dividi file PDF',
    'Esporta immagini…',
    'Esporta pagine come immagini PNG',
    'Annulla modifica pagina',
    'Salva copia modificata…',
    'Riproduci',
    'Pausa',
    'Vista normale',
    'Scegli foglio',
    'Apri foglio',
    'Scarta e cambia foglio',
    'La cartella ha %d fogli.',
    'Questa cartella ha un solo foglio: «%@»',
    'Scartare le modifiche non salvate di questo foglio?',
    "Cambiare foglio sostituisce l'intera scheda. Le modifiche non salvate con ⌘S vanno perse.",
    'Scegli il PDF da unire',
    'Scegli la cartella per le immagini',
    'Scegli dove salvare. Il secondo file viene scritto accanto a questo.',
    'Il documento ha %d pagine. Inserisci le pagine da eliminare, es. 2-4,7',
    'Il documento ha %d pagine. Inserisci le pagine da estrarre, es. 1-3,8',
    'Il documento ha %d pagine. Inserisci le pagine da esportare, es. 1-3',
    'Il documento ha %d pagine. Inserisci la parte da separare, es. 1-5; il resto diventa un secondo file.',
    'Pagina %d ruotata',
    'Pagine %@ eliminate · restano %d pagine',
    '%d pagine unite da «%@»',
    'Diviso in %@ (%d pagine) e %@ (%d pagine)',
    'Scritto %@ — %@ · %d pagine',
    '%d immagini esportate in %@',
    'Sono state esportate solo %d immagini su %d',
    "Annullata un'operazione sulla pagina",
    'Nessuna operazione sulla pagina da annullare',
    'Impossibile eliminare TUTTE le pagine: un PDF deve averne almeno una',
    "Quell'intervallo è l'intero documento: non c'è nulla da separare",
    '«%@» è protetto da password: impossibile unirlo',
    '«%@» non ha pagine',
    'Già alla prima pagina',
    "Già all'ultima pagina",
    '· modificato, non salvato',
    'Immagine animata · %d fotogrammi',
    'Documento non salvato: nessun file su disco da vedere in binario',
    'Questo comando vale solo per le cartelle di lavoro Excel',
    "Impossibile leggere l'elenco dei fogli",
    'Non esiste alcun foglio «%@»',
    'Impossibile leggere il foglio «%@»',
    'Foglio «%@» · %d righe',
    'il resto',
    'Nota',
    'Attenzione',
    'Vedi anche',
    'Copia',
    'Copiato',
    'Copia il codice di esempio',
    "Cerca nell'aiuto",
    'Indietro',
    'Inizia',
    "Non mostrare questa finestra all'avvio",
    "L'aiuto non è ancora tradotto in questa lingua: viene mostrato in vietnamita.",
    "Vai all'offset (es. 1F400 o 0x1F400)",
    'Copia le righe selezionate',
    '%d righe copiate',
    'Impossibile leggere «%@»',
    'File vuoto',
    "Impossibile leggere l'offset «%@»",
    "L'offset 0x%@ supera la dimensione del file",
    "Apri con un'altra app…",
    '%d canali',
    'Impossibile riprodurre «%@»',
    'Riproduzione impossibile — %@',
    'macOS non ha un decoder integrato per il formato %@: è un limite del sistema, non un file danneggiato.',
    "Puoi comunque vedere i byte in modalità binaria o aprirlo con un'app dotata di decoder proprio.",
    'Firma…',
    'Modifica testo…',
    'Modifica testo',
    'Disegna sopra',
    'Prossimo campo vuoto',
    'Cancella i valori inseriti',
    'Questo file non ha campi modulo',
    'Svuotati %d campi modulo',
    'Tutti i campi modulo sono già compilati',
    'Restano %d campi vuoti',
    'Modulo compilabile: %d campi. Scrivi direttamente, poi «Salva copia modificata…»',
    "Scegli un'immagine di firma (sfondo trasparente è meglio)",
    'Impossibile creare la pagina firmata',
    'Firma inserita a pagina %d',
    'Seleziona prima il testo da modificare',
    'La selezione è troppo piccola',
    'Il nuovo testo viene DISEGNATO SOPRA la selezione con il font di sistema. Il testo vecchio è coperto, non rimosso: può ancora essere estratto, quindi non è un oscuramento.',
    'Impossibile creare la pagina modificata',
    'Nuovo testo disegnato sulla pagina %d',
    'Alterna Vista / Codice',
    "Non c'è ancora una vista ad albero per JSON · XML · YAML",
    "Non c'è ancora una vista diagramma nella scheda",
    "Non c'è ancora una vista struttura per PowerPoint",
    'Questo file ha una sola modalità di visualizzazione',
    '%d nodi',
    "Impossibile costruire l'albero: %@",
    "Il documento è troppo grande per l'albero: usa la modalità Codice",
]
