# Bản dịch nb — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code nb --name "…" scripts/ban-dich/nb.py
VALS = [
    'Lagrede versjoner…',
    'Dette dokumentet er aldri blitt lagret — ingen historikk',
    'Ingen tidligere lagrede versjoner',
    'Den versjonen kan ikke leses',
    'Gjenopprett den lagrede versjonen',
    'XML: valider mot DTD/XSD…',
    'Denne Macen har ikke libxml2, så XSD-validering er ikke tilgjengelig.',
    'Velg et XSD-skjema å validere mot',
    'Gyldig etter',
    'Tillegget avsluttet uten å endre noe',
    'Ingen innebygde tillegg er installert',
    'Fjern dette tillegget',
    'Fjerne dette tillegget?',
    'Fjern',
    'Installer et innebygd tillegg…',
    'Åpne tilleggsmappen',
    'Velg .dylib-filen til tillegget',
    'Installert:',
    'Fjernet:',
    'Innebygde tillegg…',
    'Bare .dylib-filer godtas.',
    'Et tillegg med samme navn er allerede installert:',
    'Tillegget kan ikke kopieres:',
    'Innebygde tillegg finnes bare i den direkte nedlastingen, ikke i App Store-versjonen.',
    'Hjelpeprosessen for tillegg ble ikke funnet.',
    'Hjelpeprosessen kan ikke startes:',
    'Prosessen til tillegget stoppet halvveis.',
    'Tillegget svarte ikke i tide — det ble stoppet.',
    'Tillegget svarte med en feilformet melding:',
    'Tillegget meldte om en feil:',
    'Om GEditor',
    'Innstillinger…',
    'Avslutt GEditor',
    'Arkiv',
    'Ny fane',
    'Lukk fanen',
    'Neste fane',
    'Forrige fane',
    'Nytt dokument',
    'Åpne…',
    'Åpne en mappe som arbeidsområde…',
    'Åpne nylige',
    'Lagre',
    'Lagre som…',
    'Fjern mellomrom sist på linjen ved lagring',
    'Følg filen (tail -f)',
    'Skriv ut…',
    'Åpne den lukkede fanen igjen',
    'Ingen filer',
    'Tøm listen',
    'Rediger',
    'Angre',
    'Gjør om',
    'Klipp ut',
    'Kopier',
    'Lim inn',
    'Utklippshistorikk…',
    'Kolonneredigering…',
    'Merk neste treff',
    'Merk alt',
    'Dupliser linjen',
    'Slett linjen',
    'Kommenter ut linjen',
    'Ingenting er kopiert i denne økten',
    'Tøm historikken',
    'Søk',
    'Finn…',
    'Finn og erstatt…',
    'Søk i en mappe…',
    'Erstatt i en mappe…',
    'Neste treff',
    'Forrige treff',
    'Gå til linje…',
    'Gå til den samsvarende parentesen',
    'Merk alle linjer som samsvarer…',
    'Snu merkingene',
    'Fjern alle merkinger',
    'Kopier de merkede linjene',
    'Slett de merkede linjene',
    'Behold bare de merkede linjene',
    'Linjer',
    'Sorter A→Å',
    'Sorter Å→A',
    'Naturlig sortering',
    'Fjern duplikater',
    'Snu rekkefølgen på linjene',
    'Flytt linjen opp',
    'Flytt linjen ned',
    'Slå sammen linjer',
    'Del linjer etter lengde…',
    'Del linjer etter tegn…',
    'Slett tomme linjer',
    'Slå sammen påfølgende tomme linjer',
    'Fjern mellomrom sist på linjen',
    'Tabulator → mellomrom',
    'Mellomrom → tabulator',
    'STORE BOKSTAVER',
    'små bokstaver',
    'Stor Forbokstav I Hvert Ord',
    'Stor forbokstav i setningen',
    'sNU sTORE/sMÅ',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: velg ark…',
    'Veksle mellom tabell- og tekstvisning',
    'Slett kolonne…',
    'Valider data (antall kolonner · typer)',
    'Arbeidsbenk for datarensing…',
    'Kjør en renseoppskrift…',
    'Konverter…',
    'Bytt skilletegn…',
    'Eksporter til JSON…',
    'Format',
    'Tegnkoding…',
    'Linjeslutt…',
    'Normaliser Unicode…',
    'JSON: formater',
    'JSON: press sammen til én linje',
    'JSON: sorter nøkler',
    'JSON: JSONPath-spørring…',
    'CSV: SQL-spørring…',
    'SQL-spørring',
    'Kjører…',
    'Eksporter til en ny fane',
    'Tomt dokument — ingen tabell å spørre mot',
    'Ikke en CSV-tabell — første linje har bare én kolonne',
    'Spørringen kan ikke leses',
    'Spørringen kan ikke kontrolleres',
    'Gul (standard)',
    'Blå',
    'Grønn',
    'Oker',
    'Lilla',
    'Rosa',
    'Turkis',
    'Oransje',
    'Skifer',
    'Tekst',
    'Tallrekke',
    'Datorekke',
    'STORE BOKSTAVER (heksadesimalt)',
    'Start',
    'Steg',
    'Fyll ut med nuller til',
    'Grunntall',
    'Første dato',
    'Format',
    'Sett inn',
    'Avbryt',
    'Konverter formatet',
    'Forhåndsvis de 5 første radene',
    'Åpne i en ny fane',
    'Lagre til en fil…',
    'Resultatet åpnes i en ny, ulagret fane. Det opprinnelige dokumentet røres ikke.',
    'Kjør på dette dokumentet',
    'Kjør på en mappe…',
    'Hele oppskriften er ETT angre-trinn. Filen på disken røres ikke før du lagrer.',
    'av',
    'kolonnen ble ikke funnet',
    'klar',
    'den fortsetter å oppta en prosessorkjerne til appen avsluttes.',
    'Skriptet returnerte ingenting',
    'JavaScript-motoren kan ikke opprettes',
    'Ukjent JavaScript-feil',
    'Tabell',
    'Bruk sorteringen på filen',
    'Konverter ▾',
    'Eksporter radene som samsvarer',
    'Skjul denne kolonnen',
    'Gi overskriften nytt navn…',
    'Sett inn en tom kolonne til venstre',
    'Sett inn en tom kolonne til høyre',
    'Slett denne kolonnen fra filen…',
    'Minst én kolonne må forbli synlig',
    'Sorterer…',
    'Tilbake til rekkefølgen i filen',
    'de første hundre radene',
    'velge kolonner',
    'gi navn til en resultatkolonne',
    'filtrere på tekst',
    'tomme celler',
    'kombinere vilkår',
    'telle rader',
    'gruppere og oppsummere',
    'minimum, maksimum',
    'sortere og begrense',
    'kolonnenavn med mellomrom',
    'Spørringen ble avbrutt',
    'Ikke støttet: JOIN · underspørring · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · vindusfunksjoner',
    'XML: formater',
    'XML: press sammen til én linje',
    'XML: kontroller syntaksen',
    'YAML: kontroller gjentatte nøkler og innrykk',
    'Vis',
    'Vis/skjul sidepanelet (funksjonslisten)',
    'Vis/skjul dokumentkartet',
    'Fold sammen / fold ut blokken ved markøren',
    'Fold sammen alt',
    'Fold ut alt',
    'Fold sammen etter nivå',
    'Nivå %d',
    '%1$d {one=blokk foldet|other=blokker foldet} sammen på nivå %2$d',
    'Dette dokumentet er bare %d {one=nivå|other=nivåer} dypt',
    'mermaid: manifestet kan ikke leses',
    'Se etter oppdateringer…',
    'Se etter oppdateringer',
    'App Store-versjoner oppdateres via Mac App Store, ikke via GEditor.',
    'Denne utgaven har ingen signeringsnøkkel for oppdateringer og kan derfor ikke se etter dem.',
    'Forstørr teksten',
    'Forminsk teksten',
    'Virkelig størrelse',
    'Del loddrett',
    'Del vannrett',
    'Lukk delingen',
    'Åpne denne fanen i den andre ruten',
    'Gå til den andre ruten',
    'Linjebryting (av / vindu / kolonne)',
    'Bryt ved kolonne…',
    'Merk denne linjen',
    'Neste merke',
    'Forrige merke',
    'Farge på merkene…',
    'Vis alle usynlige tegn',
    '  Mellomrom',
    '  Tabulatorer',
    '  Linjeslutt',
    '  NBSP · nullbredde · styretegn',
    'Binærvisning',
    'CSV-modus (kolonner i farger)',
    'Makro',
    'Start / stopp opptaket',
    'Spill av',
    'Spill av flere ganger…',
    'Spill av til slutten av dokumentet',
    'Kjør på alle faner',
    'Avbryt makroen som kjører',
    'Lagre makroen…',
    'Lagrede makroer…',
    'Hjelp',
    'GEditor-hjelp',
    'Funksjonsoversikt',
    'Bytte fra Notepad++',
    'Finn',
    'Erstatt med',
    'Neste',
    'Forrige',
    'Tell',
    'Lukk',
    'Valider mot et JSON-skjema…',
    'Velg en JSON-skjemafil',
    'Ingen problemer ble funnet etter dette skjemaet.',
    'JSON-skjema',
    'Kontroller syntaksen til grafen',
    'Grafformatet ble ikke gjenkjent — det trengs endelsen .dot, .gv, .cypher, .ttl eller .graphml.',
    'Ingen %@-syntaksfeil ble funnet (kontrollen er ikke uttømmende).',
    '%@-syntaks',
    'er ikke et JSON-objekt',
    'Tekstutvinning (n-gram, TF-IDF)',
    'Dokumentet er tomt.',
    'Ingen nøkkelord kunne hentes ut.',
    'Nøkkelord',
    '%d {one=nøkkelord|other=nøkkelord} · %d {one=token|other=tokener} · %d {one=dokument|other=dokumenter}',
    'Merk i dokumentet',
    'Merk entiteter fra en liste…',
    'Velg en entitetsliste (CSV eller JSON)',
    'Entitetslisten kan ikke leses.',
    'Entitetslisten er tom.',
    'Ingen entiteter ble funnet i dokumentet (%d lest inn).',
    '%d {one=forekomst|other=forekomster} · %@',
    'Konverter kunnskap…',
    'Konvertering: %@ → %@',
    'Det kunne ikke konverteres.',
    'Forhåndsvisning av oppdelingen…',
    'Fast størrelse 800 B, overlapp 100 B',
    'Etter setning (≤ 800 B)',
    'Etter Markdown-overskrift',
    'Tomt dokument — ingen biter.',
    '%d {one=bit|other=biter} · i snitt %d B · %@',
    'Eksporter JSONL',
    'JSONL for bitene',
    'Åpne tripler/kanter som tabell',
    'Tripeltabell',
    'Dette dokumentet har ingen tripellinje.',
    'Ingen tripel kunne leses — linje %d: %@',
    '%1$d {one=trippel lest|other=tripler lest} · %2$d {one=feilaktig linje|other=feilaktige linjer} hoppet over (den første: linje %3$d)',
    'Uskarpe duplikater per kolonne…',
    'Uskarpe duplikater — kolonnen «%1$@»: %2$d {one=kandidatgruppe|other=kandidatgrupper}',
    'Slå sammen',
    'Treff',
    'Verdier i gruppen',
    'Slå sammen til',
    'Slå sammen de valgte gruppene',
    'Ingen gruppe er valgt — å trykke «Slå sammen» endrer INGENTING. Appen slår aldri sammen av seg selv.',
    '%d {one=gruppe valgt|other=grupper valgt} · %d {one=rad vil|other=rader vil} bli endret · ETT angre-trinn',
    'Denne kolonnen kunne ikke gjennomsøkes.',
    'Kolonnen «%@» har ingen grupper med uskarpe duplikater.',
    'Ingen gruppe ble slått sammen — dokumentet er uendret.',
    'Uskarp duplikatrensing · kolonnen %@',
    '%d {one=gruppe slått|other=grupper slått} sammen · %d {one=celle endret|other=celler endret}',
    'Rapport om rensing',
    '# Rapport om rensing — %@\n\n',
    '## Brukt (%d)\n\n',
    '_Ingen trinn er brukt._\n',
    '\n## Dataprofil\n\n',
    '_%1$d {one=kolonne|other=kolonner} · %2$d {one=rad|other=rader} · gjennomsøkt på %3$.1f s_\n\n',
    '| Kolonne | Type | Tomme | Unike | Min | Maks | Snitt |\n',
    '\n### Avvikende verdier\n\n',
    'rad %d: %@',
    '- kolonnen «%1$@» — %2$d {one=celle|other=celler}: %3$@\n',
    '\n## Igjen (%d)\n\n',
    '_Ingen observasjoner igjen._\n',
    '- kolonnen «%@»: %@\n',
    None,
    'Fjern mellomrom ved lagring',
    'Normaliser linjesluttene',
    'forrige',
    'Mappen «%@» fra forrige økt kunne ikke åpnes igjen',
    ' (og %d {one=fil|other=filer} til)',
    '%d {one=fane kunne|other=faner kunne} ikke åpnes igjen: %@%@ — filene ligger ikke lenger på samme sted.',
    'Inndata fra røret kunne ikke leses',
    'Mellomrom sist på linjen fjernes ved hver lagring',
    'Mellomrom fjernes ikke lenger ved lagring',
    'Uten navn.txt',
    'Å konvertere tegnkodingen gjør at tegn går tapt',
    'Lagre likevel',
    'Dokumentet har ulagrede endringer',
    'Å lukke uten å lagre forkaster dem.',
    'Forkast endringene',
    'Gå til linje',
    'Dokumentet har %d {one=linje|other=linjer}.',
    'Linjenummer',
    'Gå',
    'Tolk om som…',
    'Konverter til…',
    'Det kunne ikke tolkes om',
    '%@ kan ikke gjengi alle tegn',
    'Velg likevel',
    'Kolonne %d',
    'Kolonne %d: %@',
    'Skjulte kolonner: %@ (%d) — hent dem tilbake fra kontekstmenyen på overskriftsraden',
    'Vis igjen: %@',
    'Kolonnen %@ er skjult — den ligger urørt i filen',
    'Sortert etter %@ %@ · bare visning',
    'Sortert: %@ %@ (bare visning)',
    '%d+ rader samsvarer — søker videre…',
    '%d / %d {one=rad samsvarer|other=rader samsvarer}',
    'Ingen problemer ble funnet i %d {one=rad|other=rader}',
    '%d {one=rad|other=rader} med feil antall kolonner',
    '%d {one=celle|other=celler} med feil datatype',
    ' (stoppet ved de %d {one=første problemet|other=første problemene})',
    '   —   gjenkjente typer: ',
    'Rad %1$d, kolonnen %2$@: «%3$@» er ikke %4$@',
    'Kolonneredigering — %d {one=linje|other=linjer}',
    'Observasjoner',
    'Dataprofil',
    'Dataprofil — gjennomsøker…',
    'Lagre oppskriften…',
    'Eksporter rapporten',
    'Ingen gruppe er brukt · hver gruppe er ett angre-trinn',
    'for mange verdier',
    'vanligst: ',
    'Verdi å fylle tomme celler med',
    'Bruk',
    'Det gikk ikke å bygge en forhåndsvisning',
    '· latt stå som det er, kan ikke tydes ·',
    'Konverter kolonnen til ISO 8601 (ÅÅÅÅ-MM-DD)',
    'Tallkonvensjon for hele kolonnen',
    'Hva som skal gjøres med tomme celler',
    'Normaliser til ISO 8601',
    'Les tvetydige celler med DAGEN først (31/12)',
    'Les tvetydige celler med MÅNEDEN først (12/31)',
    'Hopp over tvetydige celler, rett bare de sikre',
    'Til vietnamesisk/europeisk (1.234,56)',
    'Til angloamerikansk (1,234.56)',
    'Til angloamerikansk, uten tusenskilletegn (1234.56)',
    'Fyll med en standardverdi…',
    'Fyll nedover — ta verdien over',
    'Fyll oppover — ta verdien under',
    'Slett rader med tom celle i denne kolonnen',
    'Fjern mellomrom i begge ender',
    'Fjern i begge ender og press sammen mellomrom inni',
    'Pivottabell…',
    'Kilder…',
    'Pivottabell — grupper etter kolonne',
    'Rader (gruppering)',
    'Verdier',
    '+ Rad',
    '+ Verdi',
    'Tøm alt',
    'Legg i spørringsfeltet',
    'Velg kolonner for å bygge spørringen.',
    'Kolonnenavnene i denne tabellen kunne ikke leses.',
    'Datakildene til spørringen',
    '«%@» — det åpne dokumentet',
    '  ⚠️ filen er endret siden den ble registrert',
    'Legg til fil…',
    'Fjern alle',
    'Det gikk ikke å utlede et tabellnavn av «%@» — gi filen nytt navn.',
    'Sum',
    'Gjennomsnitt',
    'Min',
    'Maks',
    'Antall unike',
    'Diagram',
    'Eksporter PNG',
    'Eksporter SVG',
    'Denne tabellen har ingen numerisk kolonne å tegne.',
    'PNG-bildet kunne ikke bygges.',
    'Spørringsresultat',
    '%@ lagret',
    '%1$@-diagram for «%2$@» — %3$d {one=punkt|other=punkter}, verdier fra %4$@ til %5$@',
    'Søyle',
    'Linje',
    'Histogram',
    'Punkt',
    'Boks',
    'CSV: datakvalitet…',
    'Datakvalitet',
    'Eksporter bruddene til en ny fane',
    'Nivå',
    'Regel',
    'Brudd',
    'Andel',
    'bestått',
    'feil',
    'advarsel',
    'ødelagt',
    '%d {one=linje med brudd er merket|other=linjer med brudd er merket}',
    'Utvikling',
    'Vurdert',
    'Rader',
    'Differanse',
    'Regler som ikke er bestått',
    'Kvalitetsskår',
    'Skår over tid',
    'Ingen historikk ennå — hver vurdering legger til ',
    'én linje i filen «.history.jsonl» ved siden av reglene.',
    '%d {one=punkt|other=punkter} i historikken',
    ' · %d {one=linje KAN IKKE LESES|other=linjer KAN IKKE LESES}',
    ' · velg to rader å sammenligne',
    'skår %+.1f',
    'ingen dimensjon falt',
    'falt: ',
    '%d {one=regel som nylig ikke er bestått|other=regler som nylig ikke er bestått}: %@',
    'rader %+d',
    ' (og %d {one=advarsel|other=advarsler} til i fanen Utvikling)',
    'Ingen automatisk retting: ',
    'Åpner det rette verktøyet på rensebenken og vurderer så på nytt med én gang.',
    'Håndter manglende verdier…',
    'Normaliser datoer…',
    'Fjern duplikater…',
    'Erstatt…',
    'Vis de feilaktige radene',
    'Kolonnen «%@» finnes ikke i denne tabellen.',
    'Duplikatene er fjernet — «%@» er nå unik. Skår: %.0f/100',
    'Duplikatene er fjernet, men «%1$@» har fortsatt %2$d {one=gjentatt rad|other=gjentatte rader} (før: %3$d) — ',
    'de radene deler NØKKEL, men ikke hele raden, så du må se etter og velge ',
    'hvilken du beholder.',
    'Det gikk ikke å lese en eneste verdi som bryter denne regelen.',
    '%1$d {one=feilaktig verdi|other=feilaktige verdier} i kolonnen «%2$@» — fyll ut Erstatt og trykk Forhåndsvis',
    'Vurdert på nytt: %.0f/100',
    'Forhåndsvisning av rapporten',
    'Parametere…',
    'Eksporter HTML…',
    'Skriv ut / PDF…',
    '%d {one=blokk kjørte|other=blokker kjørte} · %d {one=blokk MISLYKTES|other=blokker MISLYKTES}',
    '%d {one=blokk kjørte|other=blokker kjørte}',
    ' · UTDATERTE DATA — kildefilen er endret; bygg på nytt',
    'Rapportforhåndsvisning krever et .%@-dokument',
    'Ingen datakilde ble funnet — oppgi «source: fil.csv» i frontmatter.',
    'Rapporten kunne ikke bygges.',
    'Denne rapporten oppgir ingen parametere i frontmatter.',
    'Parametere for rapporten',
    'Bygg på nytt',
    '%@ eksportert',
    'Rapport: forhåndsvisning',
    'Rapport: masseproduksjon…',
    'er ikke et .greport.md-dokument',
    'rapporten kunne ikke tolkes',
    'kildedataene ble ikke funnet',
    'parameterlisten kunne ikke leses',
    'Masseproduksjon krever et .%@-dokument',
    'Velg en parameterliste (CSV eller JSON)',
    'Velg en mappe for %d {one=rapport|other=rapporter}',
    '[%d/%d] %@',
    'manglende parametere ',
    'peker på selve kildefilen — nekter å skrive over',
    '%d {one=blokk MISLYKTES|other=blokker MISLYKTES}',
    'Kjøringen er ferdig: %d {one=fil|other=filer} · %d mislyktes',
    '%d {one=parametersett|other=parametersett} kunne ikke bygges — se oppsummeringen',
    'Mermaid-diagram: forhåndsvisning',
    'Mermaid-diagram: sett inn mal…',
    'Mermaid-diagram: formater på nytt',
    'Gjennomsiktig bakgrunn',
    'Denne Macen kan ikke gjøre diagrammet om til PNG — macOS 13 kreves. SVG-eksport virker fortsatt.',
    'Lagre PNG %@…',
    'Lagre SVG…',
    'Kopier bildet til utklippstavlen',
    'Merkefarger…',
    'Merkefarger for diagrammer',
    'Hvert felt er en farge av typen #rrggbb. Lagres i «themes/mermaid-brand.json» — kan kopieres til en annen Mac.',
    'Hovedfarge',
    'Tekst på noder',
    'Ramme',
    'Forbindelser',
    'Bakgrunn ved eksport',
    'Lagre og sett inn %%{init}%% i dokumentet',
    'Merkefargene er lagret',
    'Diagrambildet er kopiert til utklippstavlen',
    '%@ lagret — %@',
    'Dette diagrammet har allerede et %%{init}%%-direktiv — ditt lates urørt.',
    '%%{init}%% satt inn — diagrammet bærer nå sine egne farger',
    'Sett inn merkefargene i diagrammet',
    'Formater Mermaid-diagrammet på nytt',
    'Diagramkilden er allerede ryddig — det er ingenting å endre',
    'Diagrammet er formatert på nytt',
    '%d {one=diagram formatert|other=diagrammer formatert} på nytt',
    'Bibliotek med diagrammaler',
    'Fullstendige diagrammaler',
    'Syntaksbiter',
    'Redigeres: %@',
    'Malen «%@» er satt inn',
    'Dette dokumentet er skrivebeskyttet.',
    'Mermaid-diagram',
    'Dette dokumentet har ingen mermaid-blokk.',
    'Merke',
    'Eksporter…',
    'Ingen diagrammer ennå',
    '%d {one=diagram|other=diagrammer} · %@',
    '%1$d/%2$d {one=diagram MISLYKTES|other=diagrammer MISLYKTES} — diagram %3$d%4$@',
    ', linje %d',
    'Dette dokumentet har ingen ```mermaid-blokk og er heller ikke en .mmd-fil.',
    'Ingen diagram er ferdig tegnet ennå.',
    '«%@» ble ikke funnet i diagramkilden',
    'nettverkssperren for WKWebView kunne ikke bygges',
    'Assosiasjonsregler',
    'Én kurv per rad',
    'To kolonner: id · vare',
    'Formen på transaksjonsdataene',
    'Kurvkolonne eller kolonne med transaksjons-id',
    'Varekolonne',
    'Tegn som skiller varer',
    'Minste support, prosent',
    'Minste confidence, prosent',
    'Skilt av:',
    'Support ≥',
    '% · Confidence ≥',
    'Tabell over assosiasjonsregler',
    'Support',
    'Confidence',
    'Lift',
    'Leverage',
    'Merk',
    '%d {one=transaksjon|other=transaksjoner} · %d {one=vare|other=varer} · %d {one=regel|other=regler}',
    ' — ingen regel nådde tersklene; senk support eller confidence',
    ' — STOPPET FOR TIDLIG, tabellen er UFULLSTENDIG',
    '%d / %d {one=transaksjon inneholder|other=transaksjoner inneholder} begge sider',
    'Tokolonneformen krever to FORSKJELLIGE kolonner.',
    '%1$d {one=rad merket|other=rader merket} i %2$d {one=transaksjon|other=transaksjoner} som inneholder «%3$@»',
    'CSV: assosiasjonsregler…',
    'Gruppevis utvinning',
    'Grupperingskolonne',
    'Verdikolonne',
    'Andre kolonne for korrelasjonen',
    'Rangeringsmåte',
    'Grupper etter:',
    'Verdi:',
    'Ranger etter:',
    'Tabell over gruppenes rangering',
    'Gruppe',
    'Rader',
    'Egen terskel',
    'MAPE',
    'r',
    'r-differanse',
    'Notat',
    'kan ikke måles',
    '%d {one=gruppe|other=grupper} · samlet referansekorrelasjon %@',
    ' · %d {one=GRUPPE UTELATT|other=GRUPPER UTELATT}',
    'Denne tabellen har ingen tekstkolonne å gruppere etter.',
    'Denne tabellen har ingen numerisk kolonne å utvinne av.',
    '%1$d {one=rad|other=rader} i gruppen «%2$@» er merket',
    'CSV: gruppevis utvinning…',
    '↔',
    'Prognose',
    'Verdikolonne over tid',
    'Prognosemodell',
    'Antall perioder som skal forutsies',
    'Vurdering mot referansemodellene',
    'Modell:',
    'Perioder:',
    'Sesong:',
    'auto',
    'Sesongperiode; la stå tom for automatisk gjenkjenning',
    'Tabell over forutsagte verdier',
    'Periode',
    '80 %-bånd',
    '95 %-bånd',
    'MAE %@ · MAPE %@',
    'kan ikke beregnes',
    'Denne tabellen har ingen numerisk kolonne å forutsi.',
    'Det gikk ikke å bygge en prognose for denne kolonnen.',
    'Kolonnen «%1$@» har bare %2$d {one=numerisk verdi|other=numeriske verdier} — det kreves minst 4 til en prognose.',
    '# Rekken leses nøyaktig i radrekkefølgen i filen — uten omsortering og uten å utlede en tidskolonne.\n',
    'Treningsfeil',
    'CSV: tidsserieprognose…',
    'Holt-Winters additiv',
    'Holt-Winters multiplikativ',
    'seasonal-naive',
    'naive',
    'Kolonner som inngår i klyngingen',
    'WCSS-kurve',
    'Klynge',
    'Skalering:',
    'k:',
    'eps:',
    'minPts:',
    'Velg minst én kolonne.',
    'Det er for lite data til å bygge kurven.',
    'Albuen antyder k = %d. WCSS synker ALLTID når k vokser, så dette er en måte å lese diagrammet på og ikke et statistisk kriterium — se på kurven og vurder om knekken er tydelig.',
    'WCSS etter k',
    'k-avstanden antyder eps = %1$@ (minPts er som standard 2 × antallet kolonner = %2$d). %3$@',
    'Avstand til den k-te naboen',
    'Klynging krever minst 2 numeriske kolonner.',
    'Klynger etter %@ og %@',
    ' — klyngene ble funnet i %d {one=dimensjon|other=dimensjoner}; diagrammet viser bare de 2 første',
    '# støy (cluster_id = -1): %d {one=rad|other=rader}\n',
    'CSV: klynging…',
    '# --- Klyngesentre (opprinnelige enheter) ---\n',
    'k-means',
    'DBSCAN',
    'Korrelasjonsmatrise',
    'Korrelasjonsmetode',
    'Korrelasjon betyr ikke årsakssammenheng.',
    'Sterkeste par: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klikk på en celle for å se et punktdiagram.',
    'Ingen par kan måles.',
    '%1$@ ↔ %2$@: %3$@ over %4$d {one=rad|other=rader}',
    'Korrelasjon krever minst 2 numeriske kolonner.',
    'Kolonnen «%@» kan ikke leses.',
    'CSV: korrelasjonsmatrise…',
    'Avvik',
    'Liste over avvik',
    'Kolonne:',
    'Numerisk kolonne som skal undersøkes',
    'Metode:',
    'Gjenkjenningsmetode',
    'Brukt metode',
    'Terskel',
    'Merk',
    'Eksporter til en ny fane',
    'Linje',
    'Skår',
    'Hvorfor',
    'lett',
    'moderat',
    'alvorlig',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=rad|other=rader} (%.2f %%)',
    'Denne tabellen har ingen numerisk kolonne å lete etter avvik i.',
    '%d {one=avvikende linje er merket|other=avvikende linjer er merket}',
    'CSV: finn avvik…',
    '%1$d {one=regel, BESTÅTT|other=regler, alle BESTÅTT} · %2$d {one=rad|other=rader} · %3$.0f ms',
    '%1$d {one=feil|other=feil} · %2$d {one=advarsel|other=advarsler} på tvers av %3$d {one=regel|other=regler} · %4$d {one=rad|other=rader} · %5$.0f ms',
    'Lagre dokumentet først — kvalitetsreglene ligger ved siden av datafilen.',
    'Det finnes ennå ikke noe regelsett. Opprett filen %@ og åpne på nytt.',
    'Historikk',
    'Lagrede spørringer',
    'Lagre denne spørringen…',
    'Lagre spørringen',
    'Gi den et navn så du finner den senere. Samme navn skriver over.',
    'For eksempel: Inntekt per fylke',
    'Det ble ikke oppgitt en verdi for parameteren: %@',
    'Tillegget er endret siden du godkjente det — GEditor nekter å kjøre det',
    'Kjøre et ikke godkjent tillegg?',
    'Jeg stoler på denne filen — kjør',
    'IKKE signert',
    'Signatur: %@',
    'Bane: %@',
    'Erstatt',
    'Erstatt alle',
    'Ren tekst',
    'Utvidet (\\n \\t \\xNN)',
    'Regulært uttrykk',
    'Skill mellom store og små bokstaver',
    'Helt ord',
    'Ingen resultater',
    'Prøv et regulært uttrykk…',
    'Loggmodus (farge etter nivå)',
    'Filtrer loggen etter nivå…',
    'Kjør på hele mappen…',
    'Filtrer gjennom en ekstern kommando…',
    'Skript…',
    'Utvidelsespakker…',
    'Nytt vindu',
    'Løsne fanen til et nytt vindu',
    'Ingen mappe er åpnet',
    'Finn en fil i mappen',
    'Filtrer på navn',
    'Ny fil…',
    'Ny mappe…',
    'Gi nytt navn…',
    'Flytt til papirkurven',
    'Vis i Finder',
    'Leser strukturen i dokumentet…',
    'denne filen har ingen funksjoner',
    'Ingen treff',
    'Ren tekst',
    '🔒 Skrivebeskyttet',
    'Følges',
    'bryting ved kolonne',
    'Syntaks',
    'Klikk for å sette inn i spørringen',
    'ugyldig spørring',
    'nøkkelen «navn» i roten',
    'nøkkel med mellomrom',
    'første element',
    'alle elementer',
    'utsnitt',
    'union av indekser',
    'alle nøkler «pris» på alle nivåer',
    'alle noder',
    'filtrer på tall',
    'filtrer på tilstedeværelse',
    'Til første feil',
    'Kolonnen inntekt er numerisk',
    'filtrer…',
    'Avbryt',
    'Utfør erstatningen',
    'forhåndsvisning',
    'interaktivt',
    'Rediger',
    'Grensesnitt',
    'Tastatursnarveier',
    'Tekststørrelse',
    'Tabulatorbredde',
    'Rykk inn med tabulatorer',
    'Rykk inn automatisk ved ny linje',
    'Fremhev alle søketreff',
    'Normaliser til NFC ved lagring',
    'Språk',
    'Utseende',
    'Som systemet',
    'Lyst',
    'Mørkt',
    'Tema',
    'Bruk Notepad++-oppsettet',
    'Tilbake til standardtastene',
    'Åpne konfigurasjonsfilen',
    'Eksporter det gjeldende temaet',
    'Språkbyttet slår helt inn ved neste oppstart.',
    'Standardtastene kommer tilbake ved neste oppstart.',
    'Markdown-forhåndsvisning',
    'Forhåndsvisningen bruker systemets Markdown-motor: ennå ingen tabeller og ingen fargelegging av kodeblokker.',
    'Prøv et regulært uttrykk',
    'Uttrykk',
    'Prøvetekst',
    'Resultat',
    'Treff',
    'Hva dette uttrykket gjør',
    'Forklar uttrykket',
    'Søkemodus',
    'Søkeresultater',
    'Ingen treff',
    ' (forkortet)',
    'Dokumentkart',
    'Fanelinje',
    'Overskriftsrad for kolonnene',
    'Ingen kolonner',
    'Treet for arbeidsområdet',
    'Liste over funksjoner og klasser',
    'Søkeresultater i mappen',
    'CSV-datatabell',
    'Arbeidsbenk for datarensing',
    'JSONPath-spørring',
    'Liste over datafeil',
    'Vurderer for gullmengden…',
    'Sammenlign med eksterne skårer (JSONL)…',
    'Velg en fil med eksterne skårer (JSONL: query, chunk_id, score)',
    'Gi den valgte noden nytt navn',
    'Slå sammen de valgte nodene',
    'Del den valgte noden',
    'Trekk den valgte delgrafen ut i en ny fane',
    'Det er ingenting å endre',
    '%1$@ — bruke %2$d {one=endring|other=endringer}?',
    '%1$@: %2$d {one=endring|other=endringer} · Cmd-Z angrer hele omgangen',
    'Sett markøren på NØYAKTIG ÉN node og prøv igjen',
    'Gi «%@» nytt navn',
    'Alle kanter og etiketter som viser til denne noden, endres med den.',
    'Gi noden nytt navn',
    'Velg MINST TO noder og prøv igjen',
    'Kanonisk form «%@» — vanligst, lengst, med diakritiske tegn',
    'Slå sammen noder',
    'Velg de KANTLINJENE som skal flyttes, og prøv igjen',
    'Alle valgte linjer må berøre NØYAKTIG ÉN node — velg flere kantlinjer',
    'Del «%1$@» — flytt %2$d {one=kant|other=kanter}',
    'Kanter til: %@',
    'Del noden',
    'Dokumentet er ulagret — den uttrukne filen trenger en plass ved siden av',
    'Velg den delen av grafen som skal trekkes ut, og prøv igjen',
    'Samle entitetsvarianter → gjennomgangstabell',
    'Bruk den endrede gjennomgangstabellen',
    'Dokumentet er ulagret — gjennomgangstabellen må ligge ved siden av graffilen',
    'Det ble ikke funnet varianter å samle',
    '%d {one=variantgruppe|other=variantgrupper} — rett kolonnen «canonical» og kjør «Bruk gjennomgangstabellen»',
    'Det finnes ingen gjennomgangstabell «%@» — kjør «Samle entitetsvarianter» først',
    'Gjennomgangstabellen kan ikke leses: %@',
    'Gjennomgangstabellen har ingen linje som må endres',
    'Ingen steder i grafen samsvarer med gjennomgangstabellen',
    'Samle entitetsvarianter',
    '%d {one=endring brukt|other=endringer brukt} · alias-tabellen og markørlisten er skrevet ved siden av filen',
    'Bruke %d {one=endring|other=endringer} på grafen?',
    '%d {one=alias|other=aliaser} → kanonisk form.',
    'SLÅ SAMMEN noder (kan ikke angres ved å skrive om):',
    '%d {one=alias finnes|other=aliaser finnes} ikke i grafen og ble hoppet over.',
    'GraphRAG…',
    'Dekningsanalyse bit ↔ entitet',
    'Eksporter kontekstpakken (JSONL)',
    'Dekning bit ↔ entitet ↔ graf',
    '- %1$d {one=entitet|other=entiteter} · %2$d {one=bit|other=biter} · %3$.0f %% av entitetene nevnt · %4$.0f %% av bitene med entitet',
    'Entiteter som ingen bit nevner',
    'Foreldreløse biter (uten en eneste entitet)',
    'Grafnoder uten tilsvarende entitet',
    'ingen',
    'Metode',
    'Koblingen bit ↔ entitet kunne ikke bygges',
    'Vurder helsen til grafen',
    'helsen til grafen',
    'Helse %1$@/100 · %2$d {one=feil|other=feil} · %3$d {one=omvending|other=omvendinger} · %4$d foreldreløse',
    'Hybrid med grafen',
    'α = 1: signalet fra grafen ignoreres helt, resultatet blir det samme som ren BM25',
    'α høy: grafen justerer bare BM25-rangeringen lett',
    'α rundt standardverdien 0,7: BM25 leder, grafen justerer',
    'α lav: grafen leder, BM25 bryter bare uavgjort',
    'α = 0: bare signalet fra grafen; biter uten entiteter står likt',
    'Dokumentet er ulagret — hybriden trenger en graffil ved siden av korpuset',
    'Graffilen «%@» ble ikke funnet — hybriden trenger den til signalet sitt',
    'hybrid %.1f ms · %@',
    'Algoritmer…',
    'PageRank (tykkelsen på kanten)',
    'Fellesskap (bakgrunnsfarge)',
    'Sammenhengende komponenter',
    'Eksporter nodetabellen til en ny fane',
    '%1$d {one=komponent|other=komponenter} · den største %2$d {one=node|other=noder} · %3$d foreldreløse noder',
    'Dette dokumentet er ikke en DOT-graf',
    'Node-/kanttabellen kunne ikke bygges: %@',
    '%d {one=rad|other=rader} · %@',
    'Sett etikett',
    'Notat (valgfritt)',
    'Lagre posten',
    'Eksporter CSV',
    'Dokumentet er ulagret — vurdereren må ligge ved siden av korpusfilen',
    'Vurdereren kunne ikke lastes inn: %@',
    'Kunne ikke lagres: %@',
    'Vurdereren har ennå ingen post',
    'Kunne ikke skrives: %@',
    'Dette dokumentet er verken en .mmd-fil eller DOT, og har ingen mermaid-blokk.',
    '%d {one=node|other=noder} · %d {one=kant|other=kanter} · ⚠ %@',
    'Mermaid-diagram: legg til element…',
    'Mermaid-diagram: koble sammen de to valgte elementene',
    'Mermaid-diagram: endre etiketten på det valgte elementet…',
    'Mermaid-diagram: slett det valgte elementet',
    'Mermaid-diagram: flytt meldingen opp',
    'Mermaid-diagram: flytt meldingen ned',
    'Legg til element',
    'Legg til deltaker',
    'Legg til post',
    'Legg til en post i diagrammet',
    'Endre en post i diagrammet',
    'Slett en post fra diagrammet',
    'Slett elementet',
    'Endre etiketten',
    'Endre rekkefølgen på meldingene',
    'Navnet på posten',
    'Ny post',
    'Navnet på posten vises på diagrammet.',
    'Egenskapstabellen til diagrammet',
    'Dette dokumentet har ingen mermaid-blokk',
    'Identifikator i diagramkilden — uten mellomrom. Etiketten endres etterpå med dobbeltklikk.',
    'Lates den tom, vises identifikatoren selv.',
    'Bare den synlige ETIKETTEN endres; identifikatoren til elementet forblir den samme.',
    'Det er uklart hvilket element «%@» er',
    'Velg NØYAKTIG TO elementer og prøv igjen',
    'Sett markøren på NØYAKTIG ETT element og prøv igjen',
    'Velg ETT element som skal slettes, eller to elementer som en kant forbinder',
    'Slette «%1$@» og den %2$d {one=kanten som berører det|other=kantene som berører det}?',
    'Nodene i den andre enden av de kantene beholdes — de erklæres på nytt med etiketten sin hvis kantsetningen var den eneste erklæringen deres.',
    'Diagrammet «%1$@» redigeres bare som tekst — %2$@',
    '%@: dra mellom to elementer for å koble dem sammen, dobbeltklikk for å endre etiketten',
    '%@: dra mellom to deltakere for å legge til en melding; rekkefølgen endres via menyen Verktøy',
    '%@: rediger i egenskapstabellen nedenfor',
    'Visuell redigering er slått på',
    '%1$@ · %2$d {one=post|other=poster} — rediger direkte i tabellen, hver celle er ett angre-trinn',
    'For et kakediagram er det et tall; for et gantt det som følger etter kolon.',
    'Mermaid-diagram: trekk blokken ut i en .mmd-fil…',
    'Mermaid-diagram: bygg den refererte filen inn igjen',
    'Trekk ut diagramblokken',
    'Bygg inn diagramblokken',
    'Trekk diagramblokken ut i en egen fil',
    'Filen legges VED SIDEN AV dokumentet; blokken beholder en referanselinje, slik at det bare redigeres ett sted.',
    'Dokumentet er ulagret — diagramfilen trenger en plass ved siden av',
    'Filen «%@» finnes allerede — velg et annet navn',
    'Trukket ut til «%@» — blokken beholdt en referanselinje',
    'Åpne filen',
    '«%@» er bygd inn igjen; filen ligger fortsatt på disken',
    'Denne blokken inneholder et ekte diagram, ikke en referanse',
    'Denne blokken viser til «%@» — åpne den filen for å redigere',
    'Diagramfilen %@ kunne ikke leses',
    'Visuell redigering',
    'Dra fra en node til en annen for å legge til en kant; dobbeltklikk for å endre etiketten. Hver handling er ett angre-trinn.',
    'Visuell redigering: dra mellom to noder for å legge til en kant, dobbeltklikk for å endre etiketten',
    'Visuell redigering er slått av',
    'Legg til node…',
    'Legg til en kant mellom de to valgte nodene…',
    'Endre etiketten på den valgte noden…',
    'Slett den valgte noden/kanten',
    'Legg til node',
    'Legg til kant',
    'Endre etiketten til noden',
    'Slett noden',
    'Slett kanten',
    'Cmd-Z angrer',
    'Dette dokumentet er skrivebeskyttet',
    'Etiketten til «%@»',
    'Bare den synlige ETIKETTEN endres; identifikatoren til noden forblir den samme.',
    'Det er uklart hvilken node «%@» er',
    'Identifikatoren til noden i DOT-filen. Etiketten endres etterpå med dobbeltklikk på tegningen.',
    'Velg NØYAKTIG TO noder og prøv igjen',
    'Velg ÉN node som skal slettes, eller to noder som en kant forbinder',
    'Slette noden «%1$@» og de %2$d {one=kanten som berører den|other=kantene som berører den}?',
    'Blir det liggende igjen løse kanter, gjenskaper DOT nodene ut fra dem — den slettede noden dukker opp igjen ved neste tegning.',
    'BM25-søkelaboratorium',
    'Spørsmål — Enter for å søke',
    'Vurder…',
    'Bygger indeksen',
    'Ingen bit samsvarer',
    'beste treff',
    'k1 = 0: hvert ord telles BARE én gang, uansett hvor mange ganger det forekommer',
    'k1 lav: å gjenta et ord gir nesten ingen ekstra skår',
    'k1 rundt standardverdien 1,2: gjentakelse gir skår, men mindre og mindre',
    'k1 høy: en bit som gjentar et ord mange ganger, belønnes kraftig',
    'b = 0: lengden ignoreres, lange biter straffes ikke',
    'b lav: lange biter straffes bare litt',
    'b rundt standardverdien 0,75: lange biter straffes moderat',
    'b = 1: største straff for lengde, korte biter foretrekkes',
    'JSONL: søkelaboratorium…',
    'Dokumentet er ulagret — BM25-indeksen ligger ved siden av korpusfilen og trenger derfor en bane',
    'Denne filen er ikke JSONL — Retrieval Lab arbeider på et korpus av biter',
    'Det gikk ikke å bygge en BM25-indeks for denne filen',
    'Dokumentet er ulagret — det kreves en korpusbane for å lage rapporten',
    'Velg et vurderingssett (CSV eller JSONL: spørsmål + forventet bit-id)',
    'Vurdering av søket',
    'Endre k1, b eller k ovenfor og se igjen for å sammenligne to oppsett; legg til en «compare»-blokk for å kjøre to parametersett parallelt på det samme vurderingssettet.',
    'Feil',
    '   (%d…%d, i snitt %.0f)',
    'JSONL-modus',
    'Post',
    'Detaljer',
    'Posten på linjen',
    'er ikke gyldig JSON',
    'poster',
    'tomme linjer',
    'er ikke et objekt',
    'vist tabell',
    'AVBRUTT PÅ HALVVEIEN',
    'Ingen filtrering',
    'poster som samsvarer med filteret',
    'Sett markøren på en linje for å se posten',
    'Ingen ødelagte poster',
    'Ennå ikke undersøkt. Kjør «JSONL: undersøk biter» på nytt etter kontrollen.',
    'tekstfelt',
    'SKJEMA (gjettet — endres ved å velge et annet felt)',
    'tekst',
    'identifikator',
    'nøstede metadata',
    'FELT',
    'dekning',
    'flere typer',
    'LENGDE — tegn',
    'LENGDE — ord',
    'LENGDE — anslåtte tokener',
    'TOMME OG DUPLIKATER',
    'tomme biter',
    'linjer',
    'grupper med nøyaktige duplikater',
    'linjer kan ikke leses, utenfor statistikken',
    'METODE',
    '«tegn» telles som Unicode-tegn (skalarer), ikke som synlige grupper',
    '«ord» deles ved ASCII-mellomrom',
    '«tokener» telles med en stavelsesdeler — IKKE modellens',
    '«duplikat» betyr NØYAKTIG duplikat; nesten-duplikater står i blokken ```quality',
    'biter',
    'JSONL: kontroller og undersøk biter…',
    'Bilde',
    'PDF',
    'Word-dokument',
    'Excel-regneark',
    'PowerPoint-presentasjon',
    'Arkiv',
    'Tilpass til vinduet',
    'Kopier bildet',
    'Roter',
    'Bildet «%@» kan ikke leses',
    'Bildet er kopiert til utklippstavlen',
    'Fremhev med gult',
    'Understrek',
    'Notat…',
    'Fjern merknadene',
    'Trekk teksten ut i en ny fane',
    'Lagre versjonen med merknader…',
    'Søk i PDF-filen',
    'Legg til',
    'Side %d/%d',
    'Side %d',
    'Treff %d/%d',
    '0 treff',
    'PDF-filen «%@» kan ikke leses',
    'Denne PDF-filen er passordbeskyttet — innholdet er ikke tilgjengelig',
    '«%@» ble ikke funnet i dokumentet',
    'Fremhevet',
    'Understreket',
    'Merk et tekststykke først',
    'Notat lagt til',
    'Denne siden har ingen merknader',
    '%d {one=merknad fjernet|other=merknader fjernet} fra denne siden',
    'Denne PDF-filen har ingen tekstlag — det er sannsynligvis en skanning',
    'Filen kunne ikke skrives',
    'Den skrevne filen åpnes IKKE riktig igjen — ikke bruk denne versjonen',
    '%@ lagret · %d {one=side|other=sider}',
    'Navn',
    'Størrelse',
    'Komprimert',
    'Forhold',
    'Endret',
    'Åpne det valgte objektet',
    'Pakk ut til en mappe…',
    'Pakk ut her',
    '%d {one=objekt|other=objekter}',
    'pakket ut til %@',
    '— innsiden av en Office-fil er et arkiv; dette er delene i det',
    '%d {one=objekt pakket|other=objekter pakket} ut',
    '%d {one=objekt er ødelagt|other=objekter er ødelagt}',
    '%d {one=objekt ble AVVIST|other=objekter ble AVVIST} fordi banene deres går utenfor målmappen',
    'Dette objektet kan ikke åpnes',
    'Det går ennå ikke å skrive direkte til en %@ — bruk «Lagre som…»',
    'Ingenting er endret',
    '%1$d {one=celle skrevet|other=celler skrevet} til %2$@',
    '%1$d {one=avsnitt skrevet|other=avsnitt skrevet} til %2$@',
    'Det gikk ikke å skrive til filen — originalen er urørt',
    'forberede testtilfellet',
    'Kan ikke skrive til settings.json',
    'Roter til venstre',
    'Roter til høyre',
    'Flytt siden opp',
    'Flytt siden ned',
    'Slett sider…',
    'Slett sider',
    'Trekk ut sider…',
    'Trekk ut sider til ny fil',
    'Slå sammen PDF-fil…',
    'Del opp fil…',
    'Del opp PDF-fil',
    'Eksporter bilder…',
    'Eksporter sider som PNG-bilder',
    'Angre sideendring',
    'Lagre redigert kopi…',
    'Spill av',
    'Pause',
    'Normal visning',
    'Velg ark',
    'Åpne ark',
    'Forkast og bytt ark',
    'Arbeidsboken har %d ark.',
    'Denne arbeidsboken har bare ett ark: «%@»',
    'Forkaste ulagrede endringer i dette arket?',
    'Å bytte ark erstatter hele fanen. Det som ikke er lagret med ⌘S, går tapt.',
    'Velg PDF-fil som skal slås sammen',
    'Velg mappe for bildene',
    'Velg lagringssted. Den andre filen skrives ved siden av denne.',
    'Dokumentet har %d sider. Angi sidene som skal slettes, f.eks. 2-4,7',
    'Dokumentet har %d sider. Angi sidene som skal trekkes ut, f.eks. 1-3,8',
    'Dokumentet har %d sider. Angi sidene som skal eksporteres, f.eks. 1-3',
    'Dokumentet har %d sider. Angi delen som skal skilles ut, f.eks. 1-5; resten blir en andre fil.',
    'Side %d rotert',
    'Sidene %@ slettet · %d sider igjen',
    '%d sider slått sammen fra «%@»',
    'Delt i %@ (%d sider) og %@ (%d sider)',
    'Skrev %@ — %@ · %d sider',
    '%d bilder eksportert til %@',
    'Bare %d av %d bilder ble eksportert',
    'Én sidehandling ble angret',
    'Ingen sidehandlinger igjen å angre',
    'Kan ikke slette ALLE sider — en PDF må ha minst én side',
    'Det området er hele dokumentet — ingenting å skille ut',
    '«%@» er passordbeskyttet — kan ikke slås sammen',
    '«%@» har ingen sider',
    'Allerede på første side',
    'Allerede på siste side',
    '· redigert, ikke lagret',
    'Animert bilde · %d bilder',
    'Ulagret dokument — ingen fil på disken for binærvisning',
    'Denne kommandoen virker bare med Excel-arbeidsbøker',
    'Kunne ikke lese listen over ark',
    'Det finnes ikke noe ark som heter «%@»',
    'Kunne ikke lese arket «%@»',
    'Arket «%@» · %d rader',
    'resten',
    'Merk',
    'Forsiktig',
    'Se også',
    'Kopier',
    'Kopiert',
    'Kopier eksempelkoden',
    'Søk i hjelp',
    'Tilbake',
    'Kom i gang',
    'Ikke vis dette vinduet ved oppstart',
    'Hjelpen er ennå ikke oversatt til dette språket — viser den vietnamesiske teksten.',
    'Gå til offset (f.eks. 1F400 eller 0x1F400)',
    'Kopier valgte rader',
    '%d rader kopiert',
    'Kunne ikke lese «%@»',
    'Tom fil',
    'Kunne ikke lese offset «%@»',
    'Offset 0x%@ er utenfor filens størrelse',
    'Åpne med et annet program…',
    '%d kanaler',
    'Kan ikke spille av «%@»',
    'Kan ikke spilles av — %@',
    'macOS har ingen innebygd dekoder for formatet %@ — det er en systembegrensning, ikke en ødelagt fil.',
    'Du kan fortsatt se bytene i binærvisning, eller åpne filen i et program med egen dekoder.',
    'Signer…',
    'Rediger tekst…',
    'Rediger tekst',
    'Tegn over',
    'Neste tomme felt',
    'Tøm utfylte verdier',
    'Denne filen har ingen skjemafelt',
    '%d skjemafelt tømt',
    'Alle skjemafelt er allerede fylt ut',
    '%d felt er fortsatt tomme',
    'Utfyllbart skjema: %d felt. Skriv rett inn, og velg så «Lagre redigert kopi…»',
    'Velg et signaturbilde (gjennomsiktig bakgrunn ser best ut)',
    'Kunne ikke lage den signerte siden',
    'Signatur satt inn på side %d',
    'Merk først teksten du vil endre',
    'Merkingen er for liten',
    'Den nye teksten TEGNES OVER merkingen med systemskriften. Den gamle teksten dekkes, ikke fjernes — den kan fortsatt trekkes ut, så dette er ikke sladding.',
    'Kunne ikke lage den redigerte siden',
    'Ny tekst tegnet over side %d',
    'Bytt Visning / Kode',
    'Ingen trevisning ennå for JSON · XML · YAML',
    'Ingen diagramvisning i fanen ennå',
    'Ingen disposisjonsvisning ennå for PowerPoint',
    'Denne filen har bare én visningsmodus',
    '%d noder',
    'Kunne ikke bygge treet: %@',
    'Dokumentet er for stort for et tre — bruk Kode-modus',
]
