# Bản dịch nl — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code nl --name "…" scripts/ban-dich/nl.py
VALS = [
    'Bewaarde versies…',
    'Dit document is nooit bewaard — geen geschiedenis',
    'Geen eerdere bewaarde versies',
    'Kan die versie niet lezen',
    'Bewaarde versie terugzetten',
    'XML: valideren met DTD/XSD…',
    'Deze Mac heeft geen libxml2, dus XSD-validatie is niet beschikbaar.',
    'Kies een XSD-schema om mee te valideren',
    'Geldig volgens',
    'De plug-in is geëindigd zonder iets te wijzigen',
    'Geen native plug-ins geïnstalleerd',
    'Deze plug-in verwijderen',
    'Deze plug-in verwijderen?',
    'Verwijderen',
    'Native plug-in installeren…',
    'Plug-inmap openen',
    'Kies het .dylib-bestand van de plug-in',
    'Geïnstalleerd:',
    'Verwijderd:',
    'Native plug-ins…',
    'Alleen .dylib-bestanden worden geaccepteerd.',
    'Er is al een plug-in met dezelfde naam geïnstalleerd:',
    'Kan de plug-in niet kopiëren:',
    'Native plug-ins bestaan alleen in de directe download, niet in de App Store-versie.',
    'Het hulpproces voor plug-ins is niet gevonden.',
    'Kan het hulpproces niet starten:',
    'Het plug-inproces is halverwege gestopt.',
    'De plug-in reageerde niet op tijd — hij is gestopt.',
    'De plug-in stuurde een onjuist opgemaakt bericht:',
    'De plug-in meldde een fout:',
    'Over GEditor',
    'Instellingen…',
    'GEditor stoppen',
    'Archief',
    'Nieuw tabblad',
    'Tabblad sluiten',
    'Volgend tabblad',
    'Vorig tabblad',
    'Nieuw document',
    'Openen…',
    'Map als werkruimte openen…',
    'Recent geopend',
    'Bewaren',
    'Bewaar als…',
    'Spaties aan het regeleinde verwijderen bij het bewaren',
    'Bestand volgen (tail -f)',
    'Print…',
    'Gesloten tabblad opnieuw openen',
    'Geen bestanden',
    'Lijst wissen',
    'Wijzig',
    'Herstel',
    'Opnieuw',
    'Knippen',
    'Kopiëren',
    'Plakken',
    'Klembordgeschiedenis…',
    'Kolomeditor…',
    'Volgende overeenkomst selecteren',
    'Alles selecteren',
    'Regel dupliceren',
    'Regel verwijderen',
    'Regel uitcommentariëren',
    'In deze sessie is er niets gekopieerd',
    'Geschiedenis wissen',
    'Zoek',
    'Zoeken…',
    'Zoeken en vervangen…',
    'Zoeken in een map…',
    'Vervangen in een map…',
    'Volgend resultaat',
    'Vorig resultaat',
    'Ga naar regel…',
    'Naar het bijbehorende haakje',
    'Alle overeenkomende regels markeren…',
    'Markeringen omkeren',
    'Alle markeringen wissen',
    'Gemarkeerde regels kopiëren',
    'Gemarkeerde regels verwijderen',
    'Alleen gemarkeerde regels behouden',
    'Regels',
    'Sorteren A→Z',
    'Sorteren Z→A',
    'Natuurlijk sorteren',
    'Dubbele regels verwijderen',
    'Regelvolgorde omkeren',
    'Regel omhoog',
    'Regel omlaag',
    'Regels samenvoegen',
    'Regels splitsen op lengte…',
    'Regels splitsen op teken…',
    'Lege regels verwijderen',
    'Opeenvolgende lege regels samenvoegen',
    'Spaties aan het regeleinde verwijderen',
    'Tab → spatie',
    'Spatie → Tab',
    'HOOFDLETTERS',
    'kleine letters',
    'Elk Woord Met Hoofdletter',
    'Hoofdletter aan het begin van de zin',
    'hOOFDLETTERS oMKEREN',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: blad kiezen…',
    'Tabel- / tekstweergave wisselen',
    'Kolom verwijderen…',
    'Gegevens valideren (aantal kolommen · typen)',
    'Werkbank voor gegevensopschoning…',
    'Opschoonrecept uitvoeren…',
    'Converteren…',
    'Scheidingsteken wijzigen…',
    'Exporteren naar JSON…',
    'Opmaak',
    'Codering…',
    'Regeleinden…',
    'Unicode normaliseren…',
    'JSON: opmaken',
    'JSON: comprimeren tot één regel',
    'JSON: sleutels sorteren',
    'JSON: JSONPath-zoekopdracht…',
    'CSV: SQL-zoekopdracht…',
    'SQL-zoekopdracht',
    'Bezig…',
    'Exporteren naar een nieuw tabblad',
    'Leeg document — geen tabel om te bevragen',
    'Geen CSV-tabel — de eerste regel heeft maar één kolom',
    'Kan de zoekopdracht niet lezen',
    'Kan de zoekopdracht niet controleren',
    'Geel (standaard)',
    'Blauw',
    'Groen',
    'Oker',
    'Paars',
    'Roze',
    'Turkoois',
    'Oranje',
    'Leisteen',
    'Tekst',
    'Getallenreeks',
    'Datumreeks',
    'HOOFDLETTERS (hexadecimaal)',
    'Begin',
    'Stap',
    'Aanvullen met nullen tot',
    'Grondtal',
    'Eerste datum',
    'Opmaak',
    'Invoegen',
    'Annuleer',
    'Opmaak converteren',
    'Voorvertoning van de eerste 5 rijen',
    'Openen in een nieuw tabblad',
    'Bewaren in een bestand…',
    'Het resultaat opent in een nieuw, niet-bewaard tabblad. Het oorspronkelijke document blijft ongemoeid.',
    'Uitvoeren op dit document',
    'Uitvoeren op een map…',
    'Het hele recept is ÉÉN herstelstap. Het bestand op schijf blijft ongemoeid tot je bewaart.',
    'uit',
    'kolom niet gevonden',
    'gereed',
    'hij blijft een processorkern bezetten tot de app wordt gestopt.',
    'Het script gaf niets terug',
    'Kan de JavaScript-engine niet aanmaken',
    'Onbekende JavaScript-fout',
    'Tabel',
    'Sortering op het bestand toepassen',
    'Converteren ▾',
    'Overeenkomende rijen exporteren',
    'Deze kolom verbergen',
    'Kop hernoemen…',
    'Lege kolom links invoegen',
    'Lege kolom rechts invoegen',
    'Deze kolom uit het bestand verwijderen…',
    'Er moet ten minste één kolom zichtbaar blijven',
    'Bezig met sorteren…',
    'Terug naar de volgorde in het bestand',
    'eerste honderd rijen',
    'kolommen kiezen',
    'een resultaatkolom benoemen',
    'filteren op tekst',
    'lege cellen',
    'voorwaarden combineren',
    'rijen tellen',
    'groeperen en samenvatten',
    'minimum, maximum',
    'sorteren en beperken',
    'kolomnaam met spaties',
    'De zoekopdracht is onderbroken',
    'Niet ondersteund: JOIN · subquery · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · vensterfuncties',
    'XML: opmaken',
    'XML: comprimeren tot één regel',
    'XML: syntaxis controleren',
    'YAML: dubbele sleutels en inspringing controleren',
    'Weergave',
    'Navigatiekolom (functielijst) tonen/verbergen',
    'Documentkaart tonen/verbergen',
    'Blok bij de cursor invouwen / uitvouwen',
    'Alles invouwen',
    'Alles uitvouwen',
    'Invouwen per niveau',
    'Niveau %d',
    '%d {one=blok ingevouwen|other=blokken ingevouwen} op niveau %d',
    'Dit document is maar %d {one=niveau|other=niveaus} diep',
    'mermaid: manifest onleesbaar',
    'Controleer op updates…',
    'Controleer op updates',
    'App Store-versies werken bij via de Mac App Store, niet via GEditor.',
    'Deze build heeft geen ondertekeningssleutel voor updates en kan er dus niet naar zoeken.',
    'Tekst vergroten',
    'Tekst verkleinen',
    'Werkelijke grootte',
    'Verticaal splitsen',
    'Horizontaal splitsen',
    'Splitsing sluiten',
    'Dit tabblad in het andere deelvenster openen',
    'Naar het andere deelvenster',
    'Regelterugloop (uit / venster / kolom)',
    'Terugloop bij kolom…',
    'Deze regel markeren',
    'Volgende markering',
    'Vorige markering',
    'Kleur van markeringen…',
    'Alle onzichtbare tekens tonen',
    '  Spaties',
    '  Tabs',
    '  Regeleinden',
    '  NBSP · nulbreedte · stuurtekens',
    'Binaire weergave',
    'CSV-modus (kolommen in kleur)',
    'Macro',
    'Opname starten / stoppen',
    'Afspelen',
    'Meerdere keren afspelen…',
    'Afspelen tot het einde van het document',
    'Uitvoeren op alle tabbladen',
    'Lopende macro annuleren',
    'Macro bewaren…',
    "Bewaarde macro's…",
    'Help',
    'GEditor Help',
    'Functieoverzicht',
    'Overstappen vanaf Notepad++',
    'Zoeken',
    'Vervangen door',
    'Volgende',
    'Vorige',
    'Tellen',
    'Sluiten',
    'Valideren met een JSON-schema…',
    'Kies een JSON-schemabestand',
    'Geen problemen gevonden volgens dit schema.',
    'JSON-schema',
    'Grafieksyntaxis controleren',
    'Grafiekindeling niet herkend — er is een extensie .dot, .gv, .cypher, .ttl of .graphml nodig.',
    'Geen %@-syntaxisfouten gevonden (deze controle is niet uitputtend).',
    '%@-syntaxis',
    'is geen JSON-object',
    'Tekstmining (n-grammen, TF-IDF)',
    'Het document is leeg.',
    'Er kon geen enkel trefwoord worden gehaald.',
    'Trefwoorden',
    '%d {one=trefwoord|other=trefwoorden} · %d {one=token|other=tokens} · %d {one=document|other=documenten}',
    'Markeren in het document',
    'Entiteiten uit een lijst markeren…',
    'Kies een entiteitenlijst (CSV of JSON)',
    'Kan de entiteitenlijst niet lezen.',
    'De entiteitenlijst is leeg.',
    'Geen entiteiten in het document gevonden (%d geladen).',
    '%d {one=keer|other=keer} gevonden · %@',
    'Kennis converteren…',
    'Conversie: %@ → %@',
    'Kan niet converteren.',
    'Voorvertoning van het opdelen…',
    'Vaste grootte 800 B, overlap 100 B',
    'Per zin (≤ 800 B)',
    'Per Markdown-kop',
    'Leeg document — geen fragmenten.',
    '%d {one=fragment|other=fragmenten} · gemiddeld %d B · %@',
    'JSONL exporteren',
    'Fragment-JSONL',
    'Triples/randen als tabel openen',
    'Tripletabel',
    'Dit document bevat geen enkele tripleregel.',
    'Er kon geen enkele triple worden gelezen — regel %d: %@',
    '%1$d {one=triple|other=triples} gelezen · %2$d {one=onjuiste regel|other=onjuiste regels} overgeslagen (de eerste: regel %3$d)',
    'Vage duplicaten per kolom…',
    'Vage duplicaten — kolom «%1$@»: %2$d {one=kandidaatgroep|other=kandidaatgroepen}',
    'Samenvoegen',
    'Overeenkomst',
    'Waarden in de groep',
    'Samenvoegen tot',
    'Geselecteerde groepen samenvoegen',
    'Geen enkele groep geselecteerd — op Samenvoegen drukken verandert NIETS. De app voegt nooit uit zichzelf samen.',
    '%d {one=groep|other=groepen} geselecteerd · %d {one=rij verandert|other=rijen veranderen} · ÉÉN herstelstap',
    'Kan deze kolom niet doorzoeken.',
    'Kolom «%@» heeft geen groepen met vage duplicaten.',
    'Geen enkele groep samengevoegd — het document is onveranderd.',
    'Vage ontdubbeling · kolom %@',
    '%d {one=groep|other=groepen} samengevoegd · %d {one=cel|other=cellen} gewijzigd',
    'Opschoonrapport',
    '# Opschoonrapport — %@\n\n',
    '## Toegepast (%d)\n\n',
    '_Er is geen enkele stap toegepast._\n',
    '\n## Gegevensprofiel\n\n',
    '_%1$d {one=kolom|other=kolommen} · %2$d {one=rij|other=rijen} · in %3$.1f s doorzocht_\n\n',
    '| Kolom | Type | Null | Uniek | Min | Max | Gemiddelde |\n',
    '\n### Uitschieters\n\n',
    'rij %d: %@',
    '- kolom «%1$@» — %2$d {one=cel|other=cellen}: %3$@\n',
    '\n## Resterend (%d)\n\n',
    '_Er zijn geen bevindingen meer._\n',
    '- kolom «%@»: %@\n',
    None,
    'Spaties verwijderen bij het bewaren',
    'Regeleinden normaliseren',
    'vorige',
    'Kan de map «%@» van de vorige sessie niet opnieuw openen',
    ' (en nog %d {one=bestand|other=bestanden})',
    'Kan %d {one=tabblad|other=tabbladen} niet opnieuw openen: %@%@ — de bestanden staan niet meer op hun plek.',
    'Kan de invoer uit de pipe niet lezen',
    'Spaties aan het regeleinde worden bij elke keer bewaren verwijderd',
    'Spaties worden niet meer verwijderd bij het bewaren',
    'Naamloos.txt',
    'Bij het converteren van de codering gaan tekens verloren',
    'Toch bewaren',
    'Het document heeft niet-bewaarde wijzigingen',
    'Sluiten zonder bewaren gooit ze weg.',
    'Wijzigingen weggooien',
    'Ga naar regel',
    'Het document heeft %d {one=regel|other=regels}.',
    'Regelnummer',
    'Ga',
    'Opnieuw interpreteren als…',
    'Converteren naar…',
    'Kan niet opnieuw interpreteren',
    '%@ kan niet alle tekens weergeven',
    'Toch kiezen',
    'Kolom %d',
    'Kolom %d: %@',
    'Verborgen kolommen: %@ (%d) — herstel ze via het contextmenu op de koprij',
    'Weer tonen: %@',
    'Kolom %@ verborgen — hij staat nog ongeschonden in het bestand',
    'Gesorteerd op %@ %@ · alleen weergave',
    'Gesorteerd: %@ %@ (alleen weergave)',
    '%d+ rijen komen overeen — nog aan het zoeken…',
    '%d / %d {one=rij komt|other=rijen komen} overeen',
    'Geen problemen gevonden in %d {one=rij|other=rijen}',
    '%d {one=rij|other=rijen} met een onjuist aantal kolommen',
    '%d {one=cel|other=cellen} met een onjuist gegevenstype',
    ' (gestopt bij de eerste %d {one=probleem|other=problemen})',
    '   —   herkende typen: ',
    'Rij %1$d, kolom %2$@: «%3$@» is geen %4$@',
    'Kolomeditor — %d {one=regel|other=regels}',
    'Bevindingen',
    'Gegevensprofiel',
    'Gegevensprofiel — bezig met doorzoeken…',
    'Recept bewaren…',
    'Rapport exporteren',
    'Geen enkele groep toegepast · elke groep is één herstelstap',
    'te veel waarden',
    'meest voorkomend: ',
    'Waarde om lege cellen mee te vullen',
    'Toepassen',
    'Kan geen voorvertoning opbouwen',
    '· ongewijzigd gelaten, onleesbaar ·',
    'Kolom omzetten naar ISO 8601 (JJJJ-MM-DD)',
    'Getalnotatie voor de hele kolom',
    'Wat te doen met lege cellen',
    'Normaliseren naar ISO 8601',
    'Dubbelzinnige cellen als DAG eerst lezen (31/12)',
    'Dubbelzinnige cellen als MAAND eerst lezen (12/31)',
    'Dubbelzinnige cellen overslaan, alleen de zekere corrigeren',
    'Naar Vietnamees/Europees (1.234,56)',
    'Naar Angelsaksisch (1,234.56)',
    'Naar Angelsaksisch, zonder duizendtalscheiding (1234.56)',
    'Vullen met een standaardwaarde…',
    'Naar beneden vullen — de waarde erboven overnemen',
    'Naar boven vullen — de waarde eronder overnemen',
    'Rijen met een lege cel in deze kolom verwijderen',
    'Spaties aan beide uiteinden verwijderen',
    'Aan beide uiteinden verwijderen en spaties binnenin samenvoegen',
    'Draaitabel…',
    'Bronnen…',
    'Draaitabel — groeperen op kolom',
    'Rijen (groepering)',
    'Waarden',
    '+ Rij',
    '+ Waarde',
    'Alles wissen',
    'In het zoekvak zetten',
    'Kies kolommen om de zoekopdracht op te bouwen.',
    'Kan de kolomnamen van deze tabel niet lezen.',
    'Gegevensbronnen van de zoekopdracht',
    '«%@» — het geopende document',
    '  ⚠️ het bestand is gewijzigd sinds het werd geregistreerd',
    'Bestand toevoegen…',
    'Alles verwijderen',
    'Kan geen tabelnaam afleiden uit «%@» — hernoem het bestand.',
    'Som',
    'Gemiddelde',
    'Min',
    'Max',
    'Aantal unieke waarden',
    'Grafiek',
    'PNG exporteren',
    'SVG exporteren',
    'Deze tabel heeft geen numerieke kolom om weer te geven.',
    'Kan de PNG-afbeelding niet opbouwen.',
    'Resultaat van de zoekopdracht',
    '%@ bewaard',
    '%1$@-grafiek van «%2$@» — %3$d {one=punt|other=punten}, waarden van %4$@ tot %5$@',
    'Staaf',
    'Lijn',
    'Histogram',
    'Spreiding',
    'Boxplot',
    'CSV: gegevenskwaliteit…',
    'Gegevenskwaliteit',
    'Overtredingen naar een nieuw tabblad exporteren',
    'Niveau',
    'Regel',
    'Overtredingen',
    'Percentage',
    'geslaagd',
    'fout',
    'waarschuwing',
    'kapot',
    '%d {one=overtredende regel|other=overtredende regels} gemarkeerd',
    'Verloop',
    'Beoordeeld op',
    'Rijen',
    'Verschil',
    'Niet-geslaagde regels',
    'Kwaliteitsscore',
    'Score in de tijd',
    'Nog geen geschiedenis — elke beoordeling voegt ',
    'één regel toe aan het bestand «.history.jsonl» naast de regels.',
    '%d {one=punt|other=punten} in de geschiedenis',
    ' · %d {one=regel ONLEESBAAR|other=regels ONLEESBAAR}',
    ' · selecteer twee rijen om te vergelijken',
    'score %+.1f',
    'geen enkele dimensie is gedaald',
    'gedaald: ',
    '%d {one=regel die nu niet meer slaagt|other=regels die nu niet meer slagen}: %@',
    'rijen %+d',
    ' (en nog %d {one=waarschuwing|other=waarschuwingen} op het tabblad Verloop)',
    'Geen automatische correctie: ',
    'Opent het bijbehorende gereedschap in de opschoonwerkbank en beoordeelt daarna meteen opnieuw.',
    'Ontbrekende waarden afhandelen…',
    'Datums normaliseren…',
    'Duplicaten verwijderen…',
    'Vervangen…',
    'De foutieve rijen tonen',
    'Kolom «%@» staat niet in deze tabel.',
    'Duplicaten verwijderd — «%@» is nu uniek. Score: %.0f/100',
    'Duplicaten verwijderd, maar «%1$@» heeft nog %2$d {one=dubbele rij|other=dubbele rijen} (eerder: %3$d) — ',
    'die rijen delen de SLEUTEL maar niet de hele regel, dus je moet kijken en kiezen ',
    'welke je houdt.',
    'Kan geen enkele waarde lezen die deze regel overtreedt.',
    '%1$d {one=onjuiste waarde|other=onjuiste waarden} in kolom «%2$@» — vul Vervangen in en klik op Voorvertoning',
    'Opnieuw beoordeeld: %.0f/100',
    'Voorvertoning van het rapport',
    'Parameters…',
    'HTML exporteren…',
    'Print / PDF…',
    '%d {one=blok|other=blokken} uitgevoerd · %d {one=blok|other=blokken} MISLUKT',
    '%d {one=blok|other=blokken} uitgevoerd',
    ' · VEROUDERDE GEGEVENS — het bronbestand is gewijzigd; bouw opnieuw op',
    'De rapportvoorvertoning heeft een .%@-document nodig',
    'Geen gegevensbron gevonden — declareer «source: bestand.csv» in de frontmatter.',
    'Kan het rapport niet opbouwen.',
    'Dit rapport declareert geen enkele parameter in de frontmatter.',
    'Rapportparameters',
    'Opnieuw opbouwen',
    '%@ geëxporteerd',
    'Rapport: voorvertoning',
    'Rapport: in batch genereren…',
    'is geen .greport.md-document',
    'kan het rapport niet ontleden',
    'kan de brongegevens niet vinden',
    'kan de parameterlijst niet lezen',
    'Batchgeneratie heeft een .%@-document nodig',
    'Kies een parameterlijst (CSV of JSON)',
    'Kies een map voor %d {one=rapport|other=rapporten}',
    '[%d/%d] %@',
    'ontbrekende parameters ',
    'wijst naar het bronbestand zelf — overschrijven geweigerd',
    '%d {one=blok|other=blokken} MISLUKT',
    'Batch klaar: %d {one=bestand|other=bestanden} · %d mislukt',
    '%d {one=parameterset kon|other=parametersets konden} niet worden opgebouwd — zie de samenvatting',
    'Mermaid-diagram: voorvertoning',
    'Mermaid-diagram: sjabloon invoegen…',
    'Mermaid-diagram: opnieuw opmaken',
    'Doorzichtige achtergrond',
    'Deze Mac kan het diagram niet omzetten naar PNG — macOS 13 is vereist. SVG exporteren werkt nog wel.',
    'PNG %@ bewaren…',
    'SVG bewaren…',
    'Afbeelding naar het klembord kopiëren',
    'Merkkleuren…',
    'Merkkleuren voor diagrammen',
    'Elk veld is een kleur als #rrggbb. Bewaard in «themes/mermaid-brand.json» — te kopiëren naar een andere Mac.',
    'Hoofdkleur',
    'Tekst op knooppunten',
    'Rand',
    'Verbindingen',
    'Achtergrond bij het exporteren',
    'Bewaren en %%{init}%% in het document invoegen',
    'Merkkleuren bewaard',
    'Diagramafbeelding naar het klembord gekopieerd',
    '%@ bewaard — %@',
    'Dit diagram heeft al een %%{init}%%-instructie — die van jou blijft ongemoeid.',
    '%%{init}%% ingevoegd — het diagram draagt nu zijn eigen kleuren',
    'Merkkleuren in het diagram invoegen',
    'Mermaid-diagram opnieuw opmaken',
    'De diagrambron is al netjes — er valt niets te wijzigen',
    'Diagram opnieuw opgemaakt',
    '%d {one=diagram|other=diagrammen} opnieuw opgemaakt',
    'Bibliotheek met diagramsjablonen',
    'Volledige diagramsjablonen',
    'Syntaxisfragmenten',
    'Bezig met wijzigen: %@',
    'Sjabloon «%@» ingevoegd',
    'Dit document is alleen-lezen.',
    'Mermaid-diagram',
    'Dit document heeft geen enkel mermaid-blok.',
    'Merk',
    'Exporteren…',
    'Nog geen diagrammen',
    '%d {one=diagram|other=diagrammen} · %@',
    '%1$d/%2$d {one=diagram|other=diagrammen} MISLUKT — diagram %3$d%4$@',
    ', regel %d',
    'Dit document heeft geen ```mermaid-blok en is ook geen .mmd-bestand.',
    'Nog geen enkel diagram is klaar met tekenen.',
    '«%@» niet gevonden in de diagrambron',
    'kan de netwerkblokkade voor WKWebView niet opbouwen',
    'Associatieregels',
    'Eén mandje per rij',
    'Twee kolommen: id · item',
    'Vorm van de transactiegegevens',
    'Mandjekolom of transactie-id-kolom',
    'Itemkolom',
    'Scheidingsteken voor items',
    'Minimale support, percentage',
    'Minimale confidence, percentage',
    'Gescheiden door:',
    'Support ≥',
    '% · Confidence ≥',
    'Tabel met associatieregels',
    'Support',
    'Confidence',
    'Lift',
    'Leverage',
    'Let op',
    '%d {one=transactie|other=transacties} · %d {one=item|other=items} · %d {one=regel|other=regels}',
    ' — geen enkele regel haalde de drempels; verlaag support of confidence',
    ' — VROEGTIJDIG GESTOPT, de tabel is ONVOLLEDIG',
    '%d / %d {one=transactie bevat|other=transacties bevatten} beide kanten',
    'De tweekolomsvorm heeft twee VERSCHILLENDE kolommen nodig.',
    '%1$d {one=rij|other=rijen} gemarkeerd in %2$d {one=transactie die|other=transacties die} «%3$@» {one=bevat|other=bevatten}',
    'CSV: associatieregels…',
    'Groepsmining',
    'Groepskolom',
    'Waardekolom',
    'Tweede kolom voor de correlatie',
    'Manier van rangschikken',
    'Groeperen op:',
    'Waarde:',
    'Rangschikken op:',
    'Tabel met groepsrangschikking',
    'Groep',
    'Rijen',
    'Eigen drempel',
    'MAPE',
    'r',
    'r-verschil',
    'Notitie',
    'niet meetbaar',
    '%d {one=groep|other=groepen} · algemene referentiecorrelatie %@',
    ' · %d {one=GROEP|other=GROEPEN} WEGGELATEN',
    'Deze tabel heeft geen tekstkolom om op te groeperen.',
    'Deze tabel heeft geen numerieke kolom om te doorzoeken.',
    '%1$d {one=rij|other=rijen} van groep «%2$@» gemarkeerd',
    'CSV: groepsmining…',
    '↔',
    'Voorspelling',
    'Waardekolom in de tijd',
    'Voorspellingsmodel',
    'Aantal te voorspellen perioden',
    'Oordeel ten opzichte van de referentiemodellen',
    'Model:',
    'Perioden:',
    'Seizoen:',
    'auto',
    'Seizoensperiode; laat leeg om automatisch te detecteren',
    'Tabel met voorspelde waarden',
    'Periode',
    '80%-band',
    '95%-band',
    'MAE %@ · MAPE %@',
    'niet berekenbaar',
    'Deze tabel heeft geen numerieke kolom om te voorspellen.',
    'Kan geen voorspelling opbouwen voor deze kolom.',
    'Kolom «%1$@» heeft maar %2$d {one=numerieke waarde|other=numerieke waarden} — er zijn er minstens 4 nodig om te voorspellen.',
    '# De reeks wordt in de rijvolgorde van het bestand gelezen — niet opnieuw gesorteerd, geen tijdkolom afgeleid.\n',
    'Trainingsfout',
    'CSV: tijdreeksvoorspelling…',
    'Holt-Winters additief',
    'Holt-Winters multiplicatief',
    'seasonal-naive',
    'naive',
    'Kolommen die in de clustering gaan',
    'WCSS-curve',
    'Cluster',
    'Schaling:',
    'k:',
    'eps:',
    'minPts:',
    'Selecteer ten minste één kolom.',
    'Niet genoeg gegevens om de curve op te bouwen.',
    'De elleboog suggereert k = %d. WCSS daalt ALTIJD als k groeit, dus dit is een leestruc voor de grafiek en geen statistisch criterium — kijk naar de curve en beoordeel of de knik duidelijk is.',
    'WCSS naar k',
    'De k-afstand suggereert eps = %1$@ (minPts is standaard 2 × aantal kolommen = %2$d). %3$@',
    'Afstand tot de k-de buur',
    'Voor clustering zijn ten minste 2 numerieke kolommen nodig.',
    'Clusters op %@ en %@',
    ' — clusters gevonden in %d {one=dimensie|other=dimensies}; de grafiek toont alleen de eerste 2',
    '# ruis (cluster_id = -1): %d {one=rij|other=rijen}\n',
    'CSV: clustering…',
    '# --- Clustercentra (oorspronkelijke eenheden) ---\n',
    'k-means',
    'DBSCAN',
    'Correlatiematrix',
    'Correlatiemethode',
    'Correlatie betekent geen oorzakelijk verband.',
    'Sterkste paar: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klik op een cel voor een spreidingsdiagram.',
    'Geen enkel paar is meetbaar.',
    '%1$@ ↔ %2$@: %3$@ over %4$d {one=rij|other=rijen}',
    'Voor correlatie zijn ten minste 2 numerieke kolommen nodig.',
    'Kan kolom «%@» niet lezen.',
    'CSV: correlatiematrix…',
    'Afwijkingen',
    'Lijst met afwijkingen',
    'Kolom:',
    'Te onderzoeken numerieke kolom',
    'Methode:',
    'Detectiemethode',
    'Gebruikte methode',
    'Drempel',
    'Markeren',
    'Exporteren naar een nieuw tabblad',
    'Regel',
    'Score',
    'Waarom',
    'licht',
    'matig',
    'ernstig',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=rij|other=rijen} (%.2f %%)',
    'Deze tabel heeft geen numerieke kolom om afwijkingen in te zoeken.',
    '%d {one=afwijkende regel|other=afwijkende regels} gemarkeerd',
    'CSV: afwijkingen zoeken…',
    '%1$d {one=regel|other=regels}, alle GESLAAGD · %2$d {one=rij|other=rijen} · %3$.0f ms',
    '%1$d {one=fout|other=fouten} · %2$d {one=waarschuwing|other=waarschuwingen} over %3$d {one=regel|other=regels} · %4$d {one=rij|other=rijen} · %5$.0f ms',
    'Bewaar eerst het document — de kwaliteitsregels staan naast het gegevensbestand.',
    'Nog geen regelset. Maak het bestand %@ aan en open opnieuw.',
    'Geschiedenis',
    'Bewaarde zoekopdrachten',
    'Deze zoekopdracht bewaren…',
    'Zoekopdracht bewaren',
    'Geef hem een naam om hem later terug te vinden. Dezelfde naam overschrijft.',
    'Bijvoorbeeld: Omzet per provincie',
    'Geen waarde ingevoerd voor parameter: %@',
    'De plug-in is gewijzigd sinds je hem goedkeurde — GEditor weigert hem uit te voeren',
    'Een niet-goedgekeurde plug-in uitvoeren?',
    'Ik vertrouw dit bestand — uitvoeren',
    'NIET ondertekend',
    'Handtekening: %@',
    'Pad: %@',
    'Vervangen',
    'Alles vervangen',
    'Platte tekst',
    'Uitgebreid (\\n \\t \\xNN)',
    'Reguliere expressie',
    'Hoofdlettergevoelig',
    'Heel woord',
    'Geen resultaten',
    'Een reguliere expressie testen…',
    'Logmodus (kleur per niveau)',
    'Log filteren op niveau…',
    'Uitvoeren op de hele map…',
    'Filteren via een externe opdracht…',
    'Scripts…',
    'Uitbreidingspakketten…',
    'Nieuw venster',
    'Tabblad losmaken in een nieuw venster',
    'Geen map geopend',
    'Een bestand in de map zoeken',
    'Filteren op naam',
    'Nieuw bestand…',
    'Nieuwe map…',
    'Hernoemen…',
    'Verplaats naar prullenmand',
    'Toon in Finder',
    'Bezig met het lezen van de documentstructuur…',
    'dit bestand heeft geen functies',
    'Geen overeenkomsten',
    'Platte tekst',
    '🔒 Alleen-lezen',
    'Wordt gevolgd',
    'terugloop bij kolom',
    'Syntaxis',
    'Klik om in de zoekopdracht in te voegen',
    'ongeldige zoekopdracht',
    'sleutel «naam» in de wortel',
    'sleutel met spaties',
    'eerste element',
    'alle elementen',
    'segment',
    'vereniging van indexen',
    'alle sleutels «prijs» op alle niveaus',
    'alle knooppunten',
    'filteren op getal',
    'filteren op aanwezigheid',
    'Naar de eerste fout',
    'De kolom omzet is numeriek',
    'filteren…',
    'Annuleer',
    'Vervanging uitvoeren',
    'voorvertoning',
    'interactief',
    'Wijzigen',
    'Interface',
    'Toetscombinaties',
    'Tekstgrootte',
    'Tabbreedte',
    'Inspringen met tabs',
    'Automatisch inspringen bij een nieuwe regel',
    'Alle zoekresultaten markeren',
    'Normaliseren naar NFC bij het bewaren',
    'Taal',
    'Weergave',
    'Systeem volgen',
    'Licht',
    'Donker',
    'Thema',
    'De Notepad++-voorinstelling gebruiken',
    'Terug naar de standaardtoetsen',
    'Configuratiebestand openen',
    'Het huidige thema exporteren',
    'De taalwijziging wordt volledig toegepast bij de volgende start.',
    'De standaardtoetsen komen terug bij de volgende start.',
    'Markdown-voorvertoning',
    'De voorvertoning gebruikt de Markdown-engine van het systeem: nog geen tabellen en geen kleuren in codeblokken.',
    'Een reguliere expressie testen',
    'Expressie',
    'Testtekst',
    'Resultaat',
    'Overeenkomsten',
    'Wat deze expressie doet',
    'De expressie uitleggen',
    'Zoekmodus',
    'Zoekresultaten',
    'Geen overeenkomsten',
    ' (ingekort)',
    'Documentkaart',
    'Tabbladbalk',
    'Koprij van de kolommen',
    'Geen kolommen',
    'Boomstructuur van de werkruimte',
    'Lijst met functies en klassen',
    'Zoekresultaten in de map',
    'CSV-gegevenstabel',
    'Werkbank voor gegevensopschoning',
    'JSONPath-zoekopdracht',
    'Lijst met gegevensfouten',
    'Beoordelaar voor de golden set…',
    'Vergelijken met externe scores (JSONL)…',
    'Kies een bestand met externe scores (JSONL: query, chunk_id, score)',
    'Het geselecteerde knooppunt hernoemen',
    'De geselecteerde knooppunten samenvoegen',
    'Het geselecteerde knooppunt splitsen',
    'De geselecteerde subgrafiek naar een nieuw tabblad halen',
    'Er valt niets te wijzigen',
    '%1$@ — %2$d {one=wijziging|other=wijzigingen} toepassen?',
    '%1$@: %2$d {one=wijziging|other=wijzigingen} · Cmd-Z herstelt de hele reeks',
    'Zet de cursor op PRECIES ÉÉN knooppunt en probeer opnieuw',
    '«%@» hernoemen',
    'Alle randen en labels die naar dit knooppunt verwijzen, veranderen mee.',
    'Knooppunt hernoemen',
    'Selecteer MINSTENS TWEE knooppunten en probeer opnieuw',
    'Canonieke vorm «%@» — meest voorkomend, langst, met accenten',
    'Knooppunten samenvoegen',
    'Selecteer de RANDREGELS die je wilt verplaatsen en probeer opnieuw',
    'Alle geselecteerde regels moeten PRECIES ÉÉN knooppunt raken — selecteer meer randregels',
    '«%1$@» splitsen — %2$d {one=rand|other=randen} verplaatsen',
    'Randen naar: %@',
    'Knooppunt splitsen',
    'Document niet bewaard — het uitgehaalde bestand heeft een plek ernaast nodig',
    'Selecteer het deel van de grafiek dat je eruit wilt halen en probeer opnieuw',
    'Entiteitsvarianten samenbrengen → controletabel',
    'De gewijzigde controletabel toepassen',
    'Document niet bewaard — de controletabel moet naast het grafiekbestand staan',
    'Geen varianten gevonden om samen te brengen',
    '%d {one=groep varianten|other=groepen varianten} — corrigeer de kolom «canonical» en voer «Controletabel toepassen» uit',
    'Geen controletabel «%@» — voer eerst «Entiteitsvarianten samenbrengen» uit',
    'Controletabel onleesbaar: %@',
    'De controletabel heeft geen enkele regel die gewijzigd moet worden',
    'Geen enkele plek in de grafiek komt overeen met de controletabel',
    'Entiteitsvarianten samenbrengen',
    '%d {one=wijziging|other=wijzigingen} toegepast · aliastabel en markeringslijst naast het bestand geschreven',
    '%d {one=wijziging|other=wijzigingen} op de grafiek toepassen?',
    '%d {one=alias|other=aliassen} → canonieke vorm.',
    'Knooppunten SAMENVOEGEN (niet ongedaan te maken door opnieuw te typen):',
    '%d {one=alias staat|other=aliassen staan} niet in de grafiek en {one=is|other=zijn} overgeslagen.',
    'GraphRAG…',
    'Dekkingsanalyse fragment ↔ entiteit',
    'Contextpakket exporteren (JSONL)',
    'Dekking fragment ↔ entiteit ↔ grafiek',
    '- %1$d {one=entiteit|other=entiteiten} · %2$d {one=fragment|other=fragmenten} · %3$.0f %% van de entiteiten genoemd · %4$.0f %% van de fragmenten met entiteit',
    'Entiteiten die door geen enkel fragment genoemd worden',
    'Verweesde fragmenten (zonder enige entiteit)',
    'Grafiekknooppunten zonder bijbehorende entiteit',
    'geen',
    'Methode',
    'Kan de koppeling fragment ↔ entiteit niet opbouwen',
    'De gezondheid van de grafiek beoordelen',
    'gezondheid van de grafiek',
    'Gezondheid %1$@/100 · %2$d {one=fout|other=fouten} · %3$d {one=omkering|other=omkeringen} · %4$d verweesd',
    'Hybride met de grafiek',
    'α = 1: het grafieksignaal wordt volledig genegeerd, het resultaat is gelijk aan puur BM25',
    'α hoog: de grafiek past de BM25-rangschikking maar licht aan',
    'α rond de standaardwaarde 0,7: BM25 leidt, de grafiek past aan',
    'α laag: de grafiek leidt, BM25 breekt alleen gelijke standen',
    'α = 0: alleen het grafieksignaal; fragmenten zonder entiteit staan gelijk',
    'Document niet bewaard — de hybride heeft een grafiekbestand naast het corpus nodig',
    'Grafiekbestand «%@» niet gevonden — de hybride heeft het nodig voor zijn signaal',
    'hybride %.1f ms · %@',
    'Algoritmen…',
    'PageRank (dikte van de rand)',
    'Gemeenschappen (achtergrondkleur)',
    'Samenhangende componenten',
    'De knooppunttabel naar een nieuw tabblad exporteren',
    '%1$d {one=component|other=componenten} · de grootste %2$d {one=knooppunt|other=knooppunten} · %3$d verweesde knooppunten',
    'Dit document is geen DOT-grafiek',
    'Kan de knooppunt-/randtabel niet opbouwen: %@',
    '%d {one=rij|other=rijen} · %@',
    'Labelen',
    'Notitie (optioneel)',
    'Record bewaren',
    'CSV exporteren',
    'Document niet bewaard — de beoordelaar moet naast het corpusbestand staan',
    'Kan de beoordelaar niet laden: %@',
    'Kan niet bewaren: %@',
    'De beoordelaar heeft nog geen enkel record',
    'Kan niet schrijven: %@',
    'Dit document is geen .mmd-bestand, geen DOT en heeft geen mermaid-blok.',
    '%d {one=knooppunt|other=knooppunten} · %d {one=rand|other=randen} · ⚠ %@',
    'Mermaid-diagram: element toevoegen…',
    'Mermaid-diagram: de twee geselecteerde elementen verbinden',
    'Mermaid-diagram: het label van het geselecteerde element wijzigen…',
    'Mermaid-diagram: het geselecteerde element verwijderen',
    'Mermaid-diagram: bericht omhoog',
    'Mermaid-diagram: bericht omlaag',
    'Element toevoegen',
    'Deelnemer toevoegen',
    'Item toevoegen',
    'Een item aan het diagram toevoegen',
    'Een item van het diagram wijzigen',
    'Een item van het diagram verwijderen',
    'Element verwijderen',
    'Label wijzigen',
    'Berichten opnieuw ordenen',
    'Naam van het item',
    'Nieuw item',
    'De naam van het item verschijnt op het diagram.',
    'Eigenschappentabel van het diagram',
    'Dit document heeft geen mermaid-blok',
    'Aanduiding in de diagrambron — zonder spaties. Het label wijzig je daarna met een dubbelklik.',
    'Laat je het leeg, dan wordt de aanduiding zelf getoond.',
    'Alleen het zichtbare LABEL verandert; de aanduiding van het element blijft gelijk.',
    'Onduidelijk welk element «%@» is',
    'Selecteer PRECIES TWEE elementen en probeer opnieuw',
    'Zet de cursor op PRECIES ÉÉN element en probeer opnieuw',
    'Kies ÉÉN element om te verwijderen, of twee elementen die door een rand verbonden zijn',
    '«%1$@» en de %2$d {one=rand die het raakt|other=randen die het raken} verwijderen?',
    'De knooppunten aan de andere kant van die randen blijven behouden — ze worden opnieuw gedeclareerd met hun label als de randinstructie hun enige declaratie was.',
    'Diagram «%1$@» is alleen als tekst te wijzigen — %2$@',
    '%@: sleep tussen twee elementen om ze te verbinden, dubbelklik om het label te wijzigen',
    '%@: sleep tussen twee deelnemers om een bericht toe te voegen; herordenen via het menu Gereedschap',
    '%@: wijzig in de eigenschappentabel hieronder',
    'Visueel wijzigen is ingeschakeld',
    '%1$@ · %2$d {one=item|other=items} — wijzig rechtstreeks in de tabel, elke cel is één herstelstap',
    'Bij een taartdiagram een getal; bij een gantt wat na de dubbele punt staat.',
    'Mermaid-diagram: blok naar een .mmd-bestand halen…',
    'Mermaid-diagram: het gerefereerde bestand terugplaatsen',
    'Diagramblok eruit halen',
    'Diagramblok terugplaatsen',
    'Het diagramblok naar een apart bestand halen',
    'Het bestand komt NAAST het document; het blok houdt één verwijzingsregel, zodat je maar op één plek wijzigt.',
    'Document niet bewaard — het diagrambestand heeft een plek ernaast nodig',
    'Bestand «%@» bestaat al — kies een andere naam',
    'Naar «%@» gehaald — het blok houdt één verwijzingsregel',
    'Bestand openen',
    '«%@» teruggeplaatst; het bestand staat nog op schijf',
    'Dit blok bevat een echt diagram, geen verwijzing',
    'Dit blok verwijst naar «%@» — open dat bestand om het te wijzigen',
    'Kan het diagrambestand %@ niet lezen',
    'Visueel wijzigen',
    'Sleep van het ene knooppunt naar het andere om een rand toe te voegen; dubbelklik om het label te wijzigen. Elke handeling is één herstelstap.',
    'Visueel wijzigen: sleep tussen twee knooppunten om een rand toe te voegen, dubbelklik om het label te wijzigen',
    'Visueel wijzigen is uitgeschakeld',
    'Knooppunt toevoegen…',
    'Een rand tussen de twee geselecteerde knooppunten toevoegen…',
    'Het label van het geselecteerde knooppunt wijzigen…',
    'Het geselecteerde knooppunt/de rand verwijderen',
    'Knooppunt toevoegen',
    'Rand toevoegen',
    'Knooppuntlabel wijzigen',
    'Knooppunt verwijderen',
    'Rand verwijderen',
    'Cmd-Z herstelt',
    'Dit document is alleen-lezen',
    'Label van «%@»',
    'Alleen het zichtbare LABEL verandert; de aanduiding van het knooppunt blijft gelijk.',
    'Onduidelijk welk knooppunt «%@» is',
    'Aanduiding van het knooppunt in het DOT-bestand. Het label wijzig je daarna met een dubbelklik op de tekening.',
    'Selecteer PRECIES TWEE knooppunten en probeer opnieuw',
    'Kies ÉÉN knooppunt om te verwijderen, of twee knooppunten die door een rand verbonden zijn',
    'Knooppunt «%1$@» en de %2$d {one=rand die het raakt|other=randen die het raken} verwijderen?',
    'Blijven er losse randen staan, dan maakt DOT de knooppunten daaruit opnieuw aan — het verwijderde knooppunt duikt bij de volgende tekening weer op.',
    'BM25-zoeklab',
    'Vraag — Enter om te zoeken',
    'Beoordelen…',
    'Bezig met het opbouwen van de index',
    'Geen enkel fragment komt overeen',
    'beste resultaten',
    'k1 = 0: elk woord telt SLECHTS één keer, hoe vaak het ook voorkomt',
    'k1 laag: een woord herhalen levert nauwelijks extra score op',
    'k1 rond de standaardwaarde 1,2: herhalen levert score op, maar steeds minder',
    'k1 hoog: een fragment dat een woord vaak herhaalt wordt sterk beloond',
    'b = 0: de lengte wordt genegeerd, lange fragmenten worden niet bestraft',
    'b laag: lange fragmenten worden maar licht bestraft',
    'b rond de standaardwaarde 0,75: lange fragmenten worden matig bestraft',
    'b = 1: maximale straf voor lengte, korte fragmenten krijgen de voorkeur',
    'JSONL: zoeklab…',
    'Document niet bewaard — de BM25-index staat naast het corpusbestand en heeft dus een pad nodig',
    'Dit bestand is geen JSONL — het Retrieval Lab werkt op een corpus van fragmenten',
    'Kan geen BM25-index opbouwen voor dit bestand',
    'Document niet bewaard — er is een corpuspad nodig om het rapport te genereren',
    'Kies een beoordelingsset (CSV of JSONL: vraag + verwacht fragment-id)',
    'Beoordeling van het zoeken',
    'Wijzig k1, b of k hierboven en kijk opnieuw om twee configuraties te vergelijken; voeg een «compare»-blok toe om twee parametersets parallel op dezelfde beoordelingsset te draaien.',
    'Fout',
    '   (%d…%d, gemiddeld %.0f)',
    'JSONL-modus',
    'Record',
    'Details',
    'Record op regel',
    'is geen geldige JSON',
    'records',
    'lege regels',
    'is geen object',
    'getoonde tabel',
    'HALVERWEGE GEANNULEERD',
    'Geen filter',
    'records die aan het filter voldoen',
    'Zet de cursor op een regel om het record te zien',
    'Geen kapotte records',
    'Nog niet onderzocht. Voer «JSONL: fragmenten onderzoeken» opnieuw uit na de controle.',
    'tekstveld',
    'SCHEMA (geraden — te wijzigen door een ander veld te kiezen)',
    'tekst',
    'aanduiding',
    'geneste metagegevens',
    'VELD',
    'dekking',
    'meerdere typen',
    'LENGTE — tekens',
    'LENGTE — woorden',
    'LENGTE — geschatte tokens',
    'LEEG EN DUBBEL',
    'lege fragmenten',
    'regels',
    'groepen exacte duplicaten',
    'onleesbare regels, buiten de statistiek',
    'METHODE',
    '«tekens» telt Unicode-tekens (scalairen), niet zichtbare groepen',
    '«woorden» splitst op ASCII-spaties',
    '«tokens» telt met een lettergreepsplitser — NIET die van het model',
    '«duplicaat» betekent een EXACT duplicaat; bijna-duplicaten staan in het blok ```quality',
    'fragmenten',
    'JSONL: fragmenten controleren en onderzoeken…',
    'Afbeelding',
    'PDF',
    'Word-document',
    'Excel-werkblad',
    'PowerPoint-presentatie',
    'Archief',
    'Passend in het venster',
    'Afbeelding kopiëren',
    'Draaien',
    'Kan de afbeelding «%@» niet lezen',
    'Afbeelding naar het klembord gekopieerd',
    'Geel markeren',
    'Onderstrepen',
    'Notitie…',
    'Aantekeningen verwijderen',
    'De tekst naar een nieuw tabblad halen',
    'De versie met aantekeningen bewaren…',
    'Zoeken in de PDF',
    'Toevoegen',
    'Pagina %d/%d',
    'Pagina %d',
    'Resultaat %d/%d',
    '0 resultaten',
    'Kan de PDF «%@» niet lezen',
    'Deze PDF is met een wachtwoord beveiligd — de inhoud is niet toegankelijk',
    '«%@» niet gevonden in het document',
    'Gemarkeerd',
    'Onderstreept',
    'Selecteer eerst een stuk tekst',
    'Notitie toegevoegd',
    'Deze pagina heeft geen aantekeningen',
    '%d {one=aantekening|other=aantekeningen} van deze pagina verwijderd',
    'Deze PDF heeft geen tekstlaag — het is waarschijnlijk een scan',
    'Kan het bestand niet schrijven',
    'Het geschreven bestand gaat NIET goed weer open — gebruik deze versie niet',
    "%@ bewaard · %d {one=pagina|other=pagina's}",
    'Naam',
    'Grootte',
    'Gecomprimeerd',
    'Verhouding',
    'Gewijzigd op',
    'Het geselecteerde onderdeel openen',
    'Uitpakken naar een map…',
    'Hier uitpakken',
    '%d {one=onderdeel|other=onderdelen}',
    'uitgepakt naar %@',
    '— de binnenkant van een Office-bestand is een archief; dit zijn de onderdelen',
    '%d {one=onderdeel|other=onderdelen} uitgepakt',
    '%d {one=onderdeel kapot|other=onderdelen kapot}',
    '%d {one=onderdeel|other=onderdelen} GEWEIGERD omdat hun paden buiten de doelmap vallen',
    'Kan dit onderdeel niet openen',
    'Er kan nog niet rechtstreeks in een %@ worden teruggeschreven — gebruik «Bewaar als…»',
    'Er is niets veranderd',
    '%1$d {one=cel|other=cellen} naar %2$@ geschreven',
    "%1$d {one=alinea|other=alinea's} naar %2$@ geschreven",
    'Kan niet naar het bestand schrijven — het origineel is ongeschonden',
    'de testcase klaarzetten',
    'Kan settings.json niet schrijven',
    'Links draaien',
    'Rechts draaien',
    'Pagina omhoog',
    'Pagina omlaag',
    "Pagina's verwijderen…",
    "Pagina's verwijderen",
    "Pagina's extraheren…",
    "Pagina's naar nieuw bestand extraheren",
    'PDF-bestand samenvoegen…',
    'Bestand splitsen…',
    'PDF-bestand splitsen',
    'Afbeeldingen exporteren…',
    "Pagina's als PNG-afbeeldingen exporteren",
    'Paginabewerking ongedaan maken',
    'Bewerkte kopie bewaren…',
    'Afspelen',
    'Pauze',
    'Normale weergave',
    'Blad kiezen',
    'Blad openen',
    'Verwerpen en blad wisselen',
    'De werkmap heeft %d bladen.',
    'Deze werkmap heeft maar één blad: ‘%@’',
    'Niet-bewaarde wijzigingen in dit blad verwerpen?',
    'Van blad wisselen vervangt het hele tabblad. Niet met ⌘S bewaard werk gaat verloren.',
    'Kies het PDF-bestand om samen te voegen',
    'Kies een map voor de afbeeldingen',
    'Kies waar te bewaren. Het tweede bestand komt hiernaast.',
    "Het document heeft %d pagina's. Geef de te verwijderen pagina's op, bv. 2-4,7",
    "Het document heeft %d pagina's. Geef de te extraheren pagina's op, bv. 1-3,8",
    "Het document heeft %d pagina's. Geef de te exporteren pagina's op, bv. 1-3",
    "Het document heeft %d pagina's. Geef het af te splitsen deel op, bv. 1-5; de rest wordt een tweede bestand.",
    'Pagina %d gedraaid',
    "Pagina's %@ verwijderd · %d pagina's over",
    "%d pagina's samengevoegd uit ‘%@’",
    "Gesplitst in %@ (%d pagina's) en %@ (%d pagina's)",
    "%@ geschreven — %@ · %d pagina's",
    '%d afbeeldingen geëxporteerd naar %@',
    'Slechts %d van %d afbeeldingen geëxporteerd',
    'Eén paginabewerking ongedaan gemaakt',
    'Geen paginabewerkingen meer om ongedaan te maken',
    "ALLE pagina's verwijderen kan niet — een PDF moet minstens één pagina houden",
    'Dat bereik is het hele document — niets om af te splitsen',
    '‘%@’ is met een wachtwoord beveiligd — samenvoegen lukt niet',
    "‘%@’ bevat geen pagina's",
    'Al op de eerste pagina',
    'Al op de laatste pagina',
    '· bewerkt, niet bewaard',
    'Bewegende afbeelding · %d frames',
    'Niet-bewaard document — geen bestand op schijf voor binaire weergave',
    'Deze opdracht werkt alleen met Excel-werkmappen',
    'Kan de lijst met bladen niet lezen',
    'Er is geen blad met de naam ‘%@’',
    'Kan blad ‘%@’ niet lezen',
    'Blad ‘%@’ · %d rijen',
    'de rest',
    'Let op',
    'Voorzichtig',
    'Zie ook',
    'Kopieer',
    'Gekopieerd',
    'Voorbeeldcode kopiëren',
    'Zoek in help',
    'Terug',
    'Aan de slag',
    'Dit venster niet meer tonen bij het starten',
    'De help is nog niet vertaald in deze taal — de Vietnamese tekst wordt getoond.',
    'Ga naar offset (bv. 1F400 of 0x1F400)',
    'Geselecteerde rijen kopiëren',
    '%d rijen gekopieerd',
    'Kan ‘%@’ niet lezen',
    'Leeg bestand',
    'Kan offset ‘%@’ niet lezen',
    'Offset 0x%@ ligt voorbij het einde van het bestand',
    'Openen met andere app…',
    '%d kanalen',
    'Kan ‘%@’ niet afspelen',
    'Afspelen lukt niet — %@',
    'macOS heeft geen ingebouwde decoder voor het %@-formaat — dat is een systeemgrens, geen kapot bestand.',
    'Je kunt de bytes nog steeds binair bekijken, of het openen met een app met een eigen decoder.',
    'Ondertekenen…',
    'Tekst bewerken…',
    'Tekst bewerken',
    'Overheen tekenen',
    'Volgend leeg veld',
    'Ingevulde waarden wissen',
    'Dit bestand heeft geen formuliervelden',
    '%d formuliervelden gewist',
    'Alle formuliervelden zijn al ingevuld',
    'Nog %d velden leeg',
    'Invulbaar formulier: %d velden. Typ er direct in en kies dan ‘Bewerkte kopie bewaren…’',
    'Kies een handtekeningafbeelding (transparante achtergrond oogt het best)',
    'Kan de ondertekende pagina niet maken',
    'Handtekening ingevoegd op pagina %d',
    'Selecteer eerst de tekst die je wilt wijzigen',
    'De selectie is te klein',
    'De nieuwe tekst wordt met het systeemlettertype OVER de selectie getekend. De oude tekst is bedekt, niet verwijderd — die is nog steeds te extraheren, dus dit is geen redactie.',
    'Kan de bewerkte pagina niet maken',
    'Nieuwe tekst over pagina %d getekend',
    'Wissel Weergave / Code',
    'Nog geen boomweergave voor JSON · XML · YAML',
    'Nog geen diagramweergave in het tabblad',
    'Nog geen overzichtsweergave voor PowerPoint',
    'Dit bestand heeft maar één weergavemodus',
    '%d knopen',
    'Kan de boom niet opbouwen: %@',
    'Het document is te groot voor een boom — gebruik de Code-modus',
]
