# Bản dịch pl — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code pl --name "…" scripts/ban-dich/pl.py
VALS = [
    'Zapisane wersje…',
    'Ten dokument nigdy nie był zapisany — brak historii',
    'Brak wcześniejszych zapisanych wersji',
    'Nie można odczytać tej wersji',
    'Przywróć zapisaną wersję',
    'XML: sprawdź według DTD/XSD…',
    'Ten Mac nie ma libxml2, więc sprawdzanie XSD jest niedostępne.',
    'Wybierz schemat XSD do sprawdzenia',
    'Zgodny z',
    'Wtyczka zakończyła działanie, niczego nie zmieniając',
    'Nie zainstalowano żadnych wtyczek natywnych',
    'Usuń tę wtyczkę',
    'Usunąć tę wtyczkę?',
    'Usuń',
    'Zainstaluj wtyczkę natywną…',
    'Otwórz katalog wtyczek',
    'Wybierz plik .dylib wtyczki',
    'Zainstalowano:',
    'Usunięto:',
    'Wtyczki natywne…',
    'Przyjmowane są wyłącznie pliki .dylib.',
    'Wtyczka o tej samej nazwie jest już zainstalowana:',
    'Nie można skopiować wtyczki:',
    'Wtyczki natywne są tylko w wersji pobieranej bezpośrednio, nie w wersji z App Store.',
    'Nie znaleziono procesu pomocniczego wtyczek.',
    'Nie można uruchomić procesu pomocniczego:',
    'Proces wtyczki zatrzymał się w połowie.',
    'Wtyczka nie odpowiedziała na czas — została zatrzymana.',
    'Wtyczka odesłała źle sformułowany komunikat:',
    'Wtyczka zgłosiła błąd:',
    'O programie GEditor',
    'Ustawienia…',
    'Zakończ GEditor',
    'Plik',
    'Nowa karta',
    'Zamknij kartę',
    'Następna karta',
    'Poprzednia karta',
    'Nowy dokument',
    'Otwórz…',
    'Otwórz katalog jako obszar roboczy…',
    'Otwórz ostatnie',
    'Zapisz',
    'Zapisz jako…',
    'Usuwaj spacje na końcu wiersza przy zapisie',
    'Śledź plik (tail -f)',
    'Drukuj…',
    'Otwórz ponownie zamkniętą kartę',
    'Brak plików',
    'Wyczyść listę',
    'Edycja',
    'Cofnij',
    'Ponów',
    'Wytnij',
    'Kopiuj',
    'Wklej',
    'Historia schowka…',
    'Edytor kolumn…',
    'Zaznacz następne dopasowanie',
    'Zaznacz wszystko',
    'Powiel wiersz',
    'Usuń wiersz',
    'Zakomentuj wiersz',
    'W tej sesji nic nie skopiowano',
    'Wyczyść historię',
    'Szukaj',
    'Znajdź…',
    'Znajdź i zamień…',
    'Szukaj w katalogu…',
    'Zamień w katalogu…',
    'Następny wynik',
    'Poprzedni wynik',
    'Przejdź do wiersza…',
    'Przejdź do pasującego nawiasu',
    'Zaznacz wszystkie pasujące wiersze…',
    'Odwróć zaznaczenia',
    'Usuń wszystkie zaznaczenia',
    'Kopiuj zaznaczone wiersze',
    'Usuń zaznaczone wiersze',
    'Zostaw tylko zaznaczone wiersze',
    'Wiersze',
    'Sortuj A→Z',
    'Sortuj Z→A',
    'Sortowanie naturalne',
    'Usuń duplikaty',
    'Odwróć kolejność wierszy',
    'Przesuń wiersz w górę',
    'Przesuń wiersz w dół',
    'Połącz wiersze',
    'Podziel wiersze według długości…',
    'Podziel wiersze według znaku…',
    'Usuń puste wiersze',
    'Zredukuj kolejne puste wiersze',
    'Usuń spacje na końcu wiersza',
    'Tab → spacja',
    'Spacja → Tab',
    'WIELKIE LITERY',
    'małe litery',
    'Pierwsza Litera Każdego Słowa',
    'Pierwsza litera zdania',
    'oDWRÓĆ wIELKOŚĆ lITER',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: wybierz arkusz…',
    'Przełącz widok tabeli / tekstu',
    'Usuń kolumnę…',
    'Sprawdź dane (liczba kolumn · typy)',
    'Warsztat czyszczenia danych…',
    'Uruchom przepis czyszczenia…',
    'Konwertuj…',
    'Zmień separator…',
    'Wyeksportuj do JSON…',
    'Format',
    'Kodowanie…',
    'Końce wierszy…',
    'Normalizuj Unicode…',
    'JSON: sformatuj',
    'JSON: skompresuj do jednego wiersza',
    'JSON: posortuj klucze',
    'JSON: zapytanie JSONPath…',
    'CSV: zapytanie SQL…',
    'Zapytanie SQL',
    'Trwa…',
    'Wyeksportuj do nowej karty',
    'Pusty dokument — nie ma tabeli do odpytania',
    'To nie jest tabela CSV — pierwszy wiersz ma tylko jedną kolumnę',
    'Nie można odczytać zapytania',
    'Nie można sprawdzić zapytania',
    'Żółty (domyślny)',
    'Niebieski',
    'Zielony',
    'Ochra',
    'Fioletowy',
    'Różowy',
    'Turkusowy',
    'Pomarańczowy',
    'Łupkowy',
    'Tekst',
    'Ciąg liczb',
    'Ciąg dat',
    'WIELKIE LITERY (szesnastkowo)',
    'Początek',
    'Krok',
    'Uzupełnij zerami do',
    'Podstawa',
    'Pierwsza data',
    'Format',
    'Wstaw',
    'Anuluj',
    'Konwertuj format',
    'Podgląd pierwszych 5 wierszy',
    'Otwórz w nowej karcie',
    'Zapisz do pliku…',
    'Wynik otworzy się w nowej, niezapisanej karcie. Pierwotny dokument pozostaje nietknięty.',
    'Uruchom na tym dokumencie',
    'Uruchom na katalogu…',
    'Cały przepis to JEDEN krok cofania. Plik na dysku pozostaje nietknięty, dopóki nie zapiszesz.',
    'wyłączone',
    'nie znaleziono kolumny',
    'gotowe',
    'zajmuje rdzeń procesora aż do zamknięcia programu.',
    'Skrypt niczego nie zwrócił',
    'Nie można utworzyć silnika JavaScript',
    'Nieznany błąd JavaScript',
    'Tabela',
    'Zastosuj sortowanie do pliku',
    'Konwertuj ▾',
    'Wyeksportuj pasujące wiersze',
    'Ukryj tę kolumnę',
    'Zmień nazwę nagłówka…',
    'Wstaw pustą kolumnę po lewej',
    'Wstaw pustą kolumnę po prawej',
    'Usuń tę kolumnę z pliku…',
    'Co najmniej jedna kolumna musi pozostać widoczna',
    'Trwa sortowanie…',
    'Wróć do kolejności z pliku',
    'pierwsze sto wierszy',
    'wybór kolumn',
    'nazwanie kolumny wyniku',
    'filtrowanie po tekście',
    'puste komórki',
    'łączenie warunków',
    'liczenie wierszy',
    'grupowanie i agregacja',
    'minimum, maksimum',
    'sortowanie i ograniczanie',
    'nazwa kolumny ze spacjami',
    'Zapytanie zostało przerwane',
    'Nieobsługiwane: JOIN · podzapytanie · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funkcje okna',
    'XML: sformatuj',
    'XML: skompresuj do jednego wiersza',
    'XML: sprawdź składnię',
    'YAML: sprawdź powtórzone klucze i wcięcia',
    'Widok',
    'Pokaż/ukryj panel boczny (lista funkcji)',
    'Pokaż/ukryj mapę dokumentu',
    'Zwiń / rozwiń blok przy kursorze',
    'Zwiń wszystko',
    'Rozwiń wszystko',
    'Zwiń według poziomu',
    'Poziom %d',
    'Zwinięto %1$d {one=blok|few=bloki|many=bloków} na poziomie %2$d',
    'Ten dokument ma tylko %d {one=poziom|few=poziomy|many=poziomów} głębokości',
    'mermaid: nie można odczytać manifestu',
    'Sprawdź uaktualnienia…',
    'Sprawdź uaktualnienia',
    'Wersje z App Store aktualizują się przez Mac App Store, a nie przez GEditor.',
    'Ta kompilacja nie ma klucza podpisu uaktualnień, więc nie może ich sprawdzać.',
    'Powiększ tekst',
    'Pomniejsz tekst',
    'Rzeczywisty rozmiar',
    'Podziel pionowo',
    'Podziel poziomo',
    'Zamknij podział',
    'Otwórz tę kartę w drugim panelu',
    'Przejdź do drugiego panelu',
    'Zawijanie wierszy (wyłączone / okno / kolumna)',
    'Zawijaj na kolumnie…',
    'Zaznacz ten wiersz',
    'Następne zaznaczenie',
    'Poprzednie zaznaczenie',
    'Kolor zaznaczeń…',
    'Pokaż wszystkie niewidoczne znaki',
    '  Spacje',
    '  Tabulatory',
    '  Końce wierszy',
    '  NBSP · zerowa szerokość · sterujące',
    'Widok binarny',
    'Tryb CSV (kolumny w kolorach)',
    'Makro',
    'Rozpocznij / zatrzymaj nagrywanie',
    'Odtwórz',
    'Odtwórz wielokrotnie…',
    'Odtwarzaj do końca dokumentu',
    'Uruchom na wszystkich kartach',
    'Anuluj działające makro',
    'Zapisz makro…',
    'Zapisane makra…',
    'Pomoc',
    'Pomoc GEditor',
    'Przegląd funkcji',
    'Przejście z Notepad++',
    'Znajdź',
    'Zamień na',
    'Następny',
    'Poprzedni',
    'Policz',
    'Zamknij',
    'Sprawdź według schematu JSON…',
    'Wybierz plik schematu JSON',
    'Nie znaleziono problemów według tego schematu.',
    'Schemat JSON',
    'Sprawdź składnię grafu',
    'Nie rozpoznano formatu grafu — potrzebne rozszerzenie .dot, .gv, .cypher, .ttl lub .graphml.',
    'Nie znaleziono błędów składni %@ (sprawdzenie nie jest wyczerpujące).',
    'Składnia %@',
    'nie jest obiektem JSON',
    'Eksploracja tekstu (n-gramy, TF-IDF)',
    'Dokument jest pusty.',
    'Nie udało się wydobyć żadnego słowa kluczowego.',
    'Słowa kluczowe',
    '%d {one=słowo kluczowe|few=słowa kluczowe|many=słów kluczowych} · %d {one=token|few=tokeny|many=tokenów} · %d {one=dokument|few=dokumenty|many=dokumentów}',
    'Zaznacz w dokumencie',
    'Zaznacz encje z listy…',
    'Wybierz listę encji (CSV lub JSON)',
    'Nie można odczytać listy encji.',
    'Lista encji jest pusta.',
    'Nie znaleziono encji w dokumencie (wczytano %d).',
    '%d {one=wystąpienie|few=wystąpienia|many=wystąpień} · %@',
    'Konwertuj wiedzę…',
    'Konwersja: %@ → %@',
    'Nie udało się przekonwertować.',
    'Podgląd podziału na fragmenty…',
    'Stały rozmiar 800 B, zachodzenie 100 B',
    'Według zdania (≤ 800 B)',
    'Według nagłówka Markdown',
    'Pusty dokument — brak fragmentów.',
    '%d {one=fragment|few=fragmenty|many=fragmentów} · średnio %d B · %@',
    'Wyeksportuj JSONL',
    'JSONL fragmentów',
    'Otwórz trójki/krawędzie jako tabelę',
    'Tabela trójek',
    'Ten dokument nie ma żadnego wiersza z trójką.',
    'Nie udało się odczytać żadnej trójki — wiersz %d: %@',
    'Odczytano %1$d {one=trójkę|few=trójki|many=trójek} · pominięto %2$d {one=błędny wiersz|few=błędne wiersze|many=błędnych wierszy} (pierwszy: wiersz %3$d)',
    'Rozmyte duplikaty według kolumny…',
    'Rozmyte duplikaty — kolumna «%1$@»: %2$d {one=grupa kandydatów|few=grupy kandydatów|many=grup kandydatów}',
    'Scal',
    'Dopasowanie',
    'Wartości w grupie',
    'Scal w',
    'Scal wybrane grupy',
    'Nie wybrano żadnej grupy — naciśnięcie «Scal» NICZEGO nie zmieni. Program nigdy nie scala sam z siebie.',
    'Wybrano %d {one=grupę|few=grupy|many=grup} · zmieni się %d {one=wiersz|few=wiersze|many=wierszy} · JEDEN krok cofania',
    'Nie udało się przeskanować tej kolumny.',
    'Kolumna «%@» nie ma grup rozmytych duplikatów.',
    'Nie scalono żadnej grupy — dokument pozostaje bez zmian.',
    'Usuwanie rozmytych duplikatów · kolumna %@',
    'Scalono %d {one=grupę|few=grupy|many=grup} · zmieniono %d {one=komórkę|few=komórki|many=komórek}',
    'Raport czyszczenia',
    '# Raport czyszczenia — %@\n\n',
    '## Zastosowano (%d)\n\n',
    '_Nie zastosowano żadnego kroku._\n',
    '\n## Profil danych\n\n',
    '_%1$d {one=kolumna|few=kolumny|many=kolumn} · %2$d {one=wiersz|few=wiersze|many=wierszy} · przeskanowano w %3$.1f s_\n\n',
    '| Kolumna | Typ | Puste | Unikalne | Min | Maks | Średnia |\n',
    '\n### Wartości odstające\n\n',
    'wiersz %d: %@',
    '- kolumna «%1$@» — %2$d {one=komórka|few=komórki|many=komórek}: %3$@\n',
    '\n## Pozostało (%d)\n\n',
    '_Nie ma już żadnych spostrzeżeń._\n',
    '- kolumna «%@»: %@\n',
    None,
    'Usuwaj spacje przy zapisie',
    'Normalizuj końce wierszy',
    'poprzedni',
    'Nie udało się ponownie otworzyć katalogu «%@» z poprzedniej sesji',
    ' (oraz %d {one=inny plik|few=inne pliki|many=innych plików})',
    'Nie udało się ponownie otworzyć %d {one=karty|few=kart|many=kart}: %@%@ — plików nie ma już w dawnym miejscu.',
    'Nie udało się odczytać danych wejściowych z potoku',
    'Spacje na końcu wiersza będą usuwane przy każdym zapisie',
    'Spacje nie są już usuwane przy zapisie',
    'Bez tytułu.txt',
    'Konwersja kodowania spowoduje utratę znaków',
    'Zapisz mimo to',
    'Dokument ma niezapisane zmiany',
    'Zamknięcie bez zapisania je odrzuci.',
    'Odrzuć zmiany',
    'Przejdź do wiersza',
    'Dokument ma %d {one=wiersz|few=wiersze|many=wierszy}.',
    'Numer wiersza',
    'Przejdź',
    'Zinterpretuj ponownie jako…',
    'Konwertuj na…',
    'Nie udało się zinterpretować ponownie',
    '%@ nie potrafi przedstawić wszystkich znaków',
    'Wybierz mimo to',
    'Kolumna %d',
    'Kolumna %d: %@',
    'Ukryte kolumny: %@ (%d) — przywróć je z menu kontekstowego wiersza nagłówków',
    'Pokaż ponownie: %@',
    'Ukryto kolumnę %@ — w pliku pozostaje nietknięta',
    'Posortowano według %@ %@ · tylko wyświetlanie',
    'Posortowano: %@ %@ (tylko wyświetlanie)',
    '%d+ wierszy pasuje — trwa dalsze szukanie…',
    '%d / %d {one=wiersz pasuje|few=wiersze pasują|many=wierszy pasuje}',
    'Nie znaleziono problemów w %d {one=wierszu|few=wierszach|many=wierszach}',
    '%d {one=wiersz|few=wiersze|many=wierszy} z niewłaściwą liczbą kolumn',
    '%d {one=komórka|few=komórki|many=komórek} z niewłaściwym typem danych',
    ' (zatrzymano na pierwszych %d {one=problemie|few=problemach|many=problemach})',
    '   —   rozpoznane typy: ',
    'Wiersz %1$d, kolumna %2$@: «%3$@» nie jest %4$@',
    'Edytor kolumn — %d {one=wiersz|few=wiersze|many=wierszy}',
    'Spostrzeżenia',
    'Profil danych',
    'Profil danych — trwa skanowanie…',
    'Zapisz przepis…',
    'Wyeksportuj raport',
    'Nie zastosowano żadnej grupy · każda grupa to jeden krok cofania',
    'zbyt wiele wartości',
    'najczęstsze: ',
    'Wartość do wypełnienia pustych komórek',
    'Zastosuj',
    'Nie udało się zbudować podglądu',
    '· zostawiono bez zmian, nie da się odczytać ·',
    'Przekształć kolumnę na ISO 8601 (RRRR-MM-DD)',
    'Konwencja liczbowa dla całej kolumny',
    'Co zrobić z pustymi komórkami',
    'Znormalizuj do ISO 8601',
    'Czytaj niejednoznaczne komórki z DNIEM na początku (31/12)',
    'Czytaj niejednoznaczne komórki z MIESIĄCEM na początku (12/31)',
    'Pomiń niejednoznaczne komórki, popraw tylko pewne',
    'Na wietnamski/europejski (1.234,56)',
    'Na angloamerykański (1,234.56)',
    'Na angloamerykański, bez separatora tysięcy (1234.56)',
    'Wypełnij wartością domyślną…',
    'Wypełnij w dół — weź wartość z góry',
    'Wypełnij w górę — weź wartość z dołu',
    'Usuń wiersze z pustą komórką w tej kolumnie',
    'Usuń spacje z obu końców',
    'Usuń z obu końców i zredukuj spacje wewnątrz',
    'Tabela przestawna…',
    'Źródła…',
    'Tabela przestawna — grupuj według kolumny',
    'Wiersze (grupowanie)',
    'Wartości',
    '+ Wiersz',
    '+ Wartość',
    'Wyczyść wszystko',
    'Wstaw do pola zapytania',
    'Wybierz kolumny, aby zbudować zapytanie.',
    'Nie udało się odczytać nazw kolumn tej tabeli.',
    'Źródła danych zapytania',
    '«%@» — otwarty dokument',
    '  ⚠️ plik zmienił się od czasu zarejestrowania',
    'Dodaj plik…',
    'Usuń wszystkie',
    'Nie udało się wywnioskować nazwy tabeli z «%@» — zmień nazwę pliku.',
    'Suma',
    'Średnia',
    'Min',
    'Maks',
    'Liczba unikalnych',
    'Wykres',
    'Wyeksportuj PNG',
    'Wyeksportuj SVG',
    'Ta tabela nie ma kolumny liczbowej do przedstawienia.',
    'Nie udało się zbudować obrazu PNG.',
    'Wynik zapytania',
    'Zapisano %@',
    'Wykres %1$@ dla «%2$@» — %3$d {one=punkt|few=punkty|many=punktów}, wartości od %4$@ do %5$@',
    'Słupkowy',
    'Liniowy',
    'Histogram',
    'Punktowy',
    'Pudełkowy',
    'CSV: jakość danych…',
    'Jakość danych',
    'Wyeksportuj naruszenia do nowej karty',
    'Poziom',
    'Reguła',
    'Naruszenia',
    'Udział',
    'zaliczone',
    'błąd',
    'ostrzeżenie',
    'uszkodzone',
    'Zaznaczono %d {one=naruszający wiersz|few=naruszające wiersze|many=naruszających wierszy}',
    'Trend',
    'Oceniono',
    'Wierszy',
    'Różnica',
    'Niezaliczone reguły',
    'Ocena jakości',
    'Ocena w czasie',
    'Nie ma jeszcze historii — każda ocena dopisuje ',
    'jeden wiersz do pliku «.history.jsonl» obok reguł.',
    '%d {one=punkt|few=punkty|many=punktów} w historii',
    ' · %d {one=wiersz NIE DO ODCZYTANIA|few=wiersze NIE DO ODCZYTANIA|many=wierszy NIE DO ODCZYTANIA}',
    ' · wybierz dwa wiersze do porównania',
    'ocena %+.1f',
    'żaden wymiar nie spadł',
    'spadły: ',
    '%d {one=nowo niezaliczona reguła|few=nowo niezaliczone reguły|many=nowo niezaliczonych reguł}: %@',
    'wierszy %+d',
    ' (oraz %d {one=dalsze ostrzeżenie|few=dalsze ostrzeżenia|many=dalszych ostrzeżeń} na karcie Trend)',
    'Brak automatycznej poprawki: ',
    'Otwiera odpowiednie narzędzie w warsztacie czyszczenia, a potem od razu ocenia ponownie.',
    'Obsłuż brakujące wartości…',
    'Znormalizuj daty…',
    'Usuń duplikaty…',
    'Zamień…',
    'Pokaż błędne wiersze',
    'Kolumny «%@» nie ma w tej tabeli.',
    'Duplikaty usunięte — «%@» jest teraz unikalna. Ocena: %.0f/100',
    'Duplikaty usunięte, ale «%1$@» ma nadal %2$d {one=powtórzony wiersz|few=powtórzone wiersze|many=powtórzonych wierszy} (wcześniej: %3$d) — ',
    'te wiersze mają wspólny KLUCZ, ale nie cały wiersz, więc trzeba je obejrzeć i wybrać ',
    'który zostawić.',
    'Nie udało się odczytać żadnej wartości naruszającej tę regułę.',
    '%1$d {one=błędna wartość|few=błędne wartości|many=błędnych wartości} w kolumnie «%2$@» — wypełnij pole Zamień i naciśnij Podgląd',
    'Oceniono ponownie: %.0f/100',
    'Podgląd raportu',
    'Parametry…',
    'Wyeksportuj HTML…',
    'Drukuj / PDF…',
    'Wykonano %d {one=blok|few=bloki|many=bloków} · %d {one=blok|few=bloki|many=bloków} NIE POWIODŁO SIĘ',
    'Wykonano %d {one=blok|few=bloki|many=bloków}',
    ' · NIEAKTUALNE DANE — plik źródłowy się zmienił; zbuduj ponownie',
    'Podgląd raportu wymaga dokumentu .%@',
    'Nie znaleziono źródła danych — zadeklaruj «source: plik.csv» we frontmatterze.',
    'Nie udało się zbudować raportu.',
    'Ten raport nie deklaruje żadnego parametru we frontmatterze.',
    'Parametry raportu',
    'Zbuduj ponownie',
    'Wyeksportowano %@',
    'Raport: podgląd',
    'Raport: generowanie wsadowe…',
    'to nie jest dokument .greport.md',
    'nie udało się przeanalizować raportu',
    'nie znaleziono danych źródłowych',
    'nie udało się odczytać listy parametrów',
    'Generowanie wsadowe wymaga dokumentu .%@',
    'Wybierz listę parametrów (CSV lub JSON)',
    'Wybierz katalog dla %d {one=raportu|few=raportów|many=raportów}',
    '[%d/%d] %@',
    'brakujące parametry ',
    'wskazuje na sam plik źródłowy — odmówiono nadpisania',
    '%d {one=blok|few=bloki|many=bloków} NIE POWIODŁO SIĘ',
    'Wsad zakończony: %d {one=plik|few=pliki|many=plików} · %d nieudanych',
    'Nie udało się zbudować %d {one=zestawu parametrów|few=zestawów parametrów|many=zestawów parametrów} — zobacz podsumowanie',
    'Diagram Mermaid: podgląd',
    'Diagram Mermaid: wstaw szablon…',
    'Diagram Mermaid: sformatuj ponownie',
    'Przezroczyste tło',
    'Ten Mac nie potrafi przekształcić diagramu w PNG — wymagany jest macOS 13. Eksport SVG nadal działa.',
    'Zapisz PNG %@…',
    'Zapisz SVG…',
    'Skopiuj obraz do schowka',
    'Kolory marki…',
    'Kolory marki dla diagramów',
    'Każde pole to kolor w postaci #rrggbb. Zapisywane w «themes/mermaid-brand.json» — można skopiować na innego Maca.',
    'Kolor główny',
    'Tekst na węzłach',
    'Obramowanie',
    'Połączenia',
    'Tło przy eksporcie',
    'Zapisz i wstaw %%{init}%% do dokumentu',
    'Zapisano kolory marki',
    'Skopiowano obraz diagramu do schowka',
    'Zapisano %@ — %@',
    'Ten diagram ma już dyrektywę %%{init}%% — twoja pozostaje nietknięta.',
    'Wstawiono %%{init}%% — diagram niesie teraz własne kolory',
    'Wstaw kolory marki do diagramu',
    'Sformatuj ponownie diagram Mermaid',
    'Źródło diagramu jest już uporządkowane — nie ma czego zmieniać',
    'Diagram sformatowany ponownie',
    'Sformatowano ponownie %d {one=diagram|few=diagramy|many=diagramów}',
    'Biblioteka szablonów diagramów',
    'Pełne szablony diagramów',
    'Fragmenty składni',
    'Edytowany: %@',
    'Wstawiono szablon «%@»',
    'Ten dokument jest tylko do odczytu.',
    'Diagram Mermaid',
    'Ten dokument nie ma żadnego bloku mermaid.',
    'Marka',
    'Wyeksportuj…',
    'Nie ma jeszcze diagramów',
    '%d {one=diagram|few=diagramy|many=diagramów} · %@',
    '%1$d/%2$d {one=diagram|few=diagramy|many=diagramów} NIE POWIODŁO SIĘ — diagram %3$d%4$@',
    ', wiersz %d',
    'Ten dokument nie ma bloku ```mermaid i nie jest też plikiem .mmd.',
    'Żaden diagram nie skończył się jeszcze rysować.',
    'Nie znaleziono «%@» w źródle diagramu',
    'nie udało się zbudować blokady sieciowej dla WKWebView',
    'Reguły asocjacyjne',
    'Jeden koszyk na wiersz',
    'Dwie kolumny: identyfikator · pozycja',
    'Postać danych transakcyjnych',
    'Kolumna koszyka lub identyfikatora transakcji',
    'Kolumna pozycji',
    'Znak rozdzielający pozycje',
    'Minimalne support, procent',
    'Minimalne confidence, procent',
    'Rozdzielone przez:',
    'Support ≥',
    '% · Confidence ≥',
    'Tabela reguł asocjacyjnych',
    'Support',
    'Confidence',
    'Lift',
    'Leverage',
    'Uwaga',
    '%d {one=transakcja|few=transakcje|many=transakcji} · %d {one=pozycja|few=pozycje|many=pozycji} · %d {one=reguła|few=reguły|many=reguł}',
    ' — żadna reguła nie osiągnęła progów; obniż support lub confidence',
    ' — ZATRZYMANO WCZEŚNIEJ, tabela jest NIEPEŁNA',
    '%d / %d {one=transakcja zawiera|few=transakcje zawierają|many=transakcji zawiera} obie strony',
    'Postać dwukolumnowa wymaga dwóch RÓŻNYCH kolumn.',
    'Zaznaczono %1$d {one=wiersz|few=wiersze|many=wierszy} w %2$d {one=transakcji|few=transakcjach|many=transakcjach} zawierających «%3$@»',
    'CSV: reguły asocjacyjne…',
    'Eksploracja grupowa',
    'Kolumna grupująca',
    'Kolumna wartości',
    'Druga kolumna do korelacji',
    'Sposób uszeregowania',
    'Grupuj według:',
    'Wartość:',
    'Uszereguj według:',
    'Tabela rankingu grup',
    'Grupa',
    'Wierszy',
    'Własny próg',
    'MAPE',
    'r',
    'Różnica r',
    'Notatka',
    'nie da się zmierzyć',
    '%d {one=grupa|few=grupy|many=grup} · ogólna korelacja odniesienia %@',
    ' · ODRZUCONO %d {one=GRUPĘ|few=GRUPY|many=GRUP}',
    'Ta tabela nie ma kolumny tekstowej do grupowania.',
    'Ta tabela nie ma kolumny liczbowej do eksploracji.',
    'Zaznaczono %1$d {one=wiersz|few=wiersze|many=wierszy} grupy «%2$@»',
    'CSV: eksploracja grupowa…',
    '↔',
    'Prognoza',
    'Kolumna wartości w czasie',
    'Model prognozy',
    'Liczba prognozowanych okresów',
    'Werdykt wobec modeli odniesienia',
    'Model:',
    'Okresy:',
    'Sezon:',
    'auto',
    'Okres sezonowy; zostaw puste, aby wykryć automatycznie',
    'Tabela wartości prognozowanych',
    'Okres',
    'Przedział 80%',
    'Przedział 95%',
    'MAE %@ · MAPE %@',
    'nie da się obliczyć',
    'Ta tabela nie ma kolumny liczbowej do prognozowania.',
    'Nie udało się zbudować prognozy dla tej kolumny.',
    'Kolumna «%1$@» ma tylko %2$d {one=wartość liczbową|few=wartości liczbowe|many=wartości liczbowych} — do prognozy potrzeba co najmniej 4.',
    '# Szereg jest czytany dokładnie w kolejności wierszy pliku — bez sortowania i bez wnioskowania kolumny czasu.\n',
    'Błąd uczenia',
    'CSV: prognoza szeregu czasowego…',
    'Holt-Winters addytywny',
    'Holt-Winters multiplikatywny',
    'seasonal-naive',
    'naive',
    'Kolumny wchodzące do grupowania',
    'Krzywa WCSS',
    'Skupienie',
    'Skalowanie:',
    'k:',
    'eps:',
    'minPts:',
    'Wybierz co najmniej jedną kolumnę.',
    'Za mało danych, aby zbudować krzywą.',
    'Łokieć sugeruje k = %d. WCSS ZAWSZE maleje wraz ze wzrostem k, więc to sposób czytania wykresu, a nie kryterium statystyczne — spójrz na krzywą i oceń, czy załamanie jest wyraźne.',
    'WCSS według k',
    'k-odległość sugeruje eps = %1$@ (minPts domyślnie 2 × liczba kolumn = %2$d). %3$@',
    'Odległość do k-tego sąsiada',
    'Do grupowania potrzeba co najmniej 2 kolumn liczbowych.',
    'Skupienia według %@ i %@',
    ' — skupienia znaleziono w %d {one=wymiarze|few=wymiarach|many=wymiarach}; wykres pokazuje tylko 2 pierwsze',
    '# szum (cluster_id = -1): %d {one=wiersz|few=wiersze|many=wierszy}\n',
    'CSV: grupowanie…',
    '# --- Środki skupień (jednostki pierwotne) ---\n',
    'k-means',
    'DBSCAN',
    'Macierz korelacji',
    'Metoda korelacji',
    'Korelacja nie oznacza przyczynowości.',
    'Najsilniejsza para: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Kliknij komórkę, aby zobaczyć wykres punktowy.',
    'Żadnej pary nie da się zmierzyć.',
    '%1$@ ↔ %2$@: %3$@ na %4$d {one=wierszu|few=wierszach|many=wierszach}',
    'Do korelacji potrzeba co najmniej 2 kolumn liczbowych.',
    'Nie udało się odczytać kolumny «%@».',
    'CSV: macierz korelacji…',
    'Anomalie',
    'Lista anomalii',
    'Kolumna:',
    'Kolumna liczbowa do zbadania',
    'Metoda:',
    'Metoda wykrywania',
    'Użyta metoda',
    'Próg',
    'Zaznacz',
    'Wyeksportuj do nowej karty',
    'Wiersz',
    'Ocena',
    'Dlaczego',
    'łagodna',
    'umiarkowana',
    'poważna',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=wiersz|few=wiersze|many=wierszy} (%.2f%%)',
    'Ta tabela nie ma kolumny liczbowej, w której można szukać anomalii.',
    'Zaznaczono %d {one=anomalny wiersz|few=anomalne wiersze|many=anomalnych wierszy}',
    'CSV: znajdź anomalie…',
    '%1$d {one=reguła|few=reguły|many=reguł}, wszystkie ZALICZONE · %2$d {one=wiersz|few=wiersze|many=wierszy} · %3$.0f ms',
    '%1$d {one=błąd|few=błędy|many=błędów} · %2$d {one=ostrzeżenie|few=ostrzeżenia|many=ostrzeżeń} w %3$d {one=regule|few=regułach|many=regułach} · %4$d {one=wiersz|few=wiersze|many=wierszy} · %5$.0f ms',
    'Najpierw zapisz dokument — reguły jakości leżą obok pliku danych.',
    'Nie ma jeszcze zestawu reguł. Utwórz plik %@ i otwórz ponownie.',
    'Historia',
    'Zapisane zapytania',
    'Zapisz to zapytanie…',
    'Zapisz zapytanie',
    'Nadaj mu nazwę, aby odnaleźć je później. Ta sama nazwa nadpisuje.',
    'Na przykład: Przychód według województwa',
    'Nie podano wartości parametru: %@',
    'Wtyczka zmieniła się od czasu zatwierdzenia — GEditor odmawia jej uruchomienia',
    'Uruchomić niezatwierdzoną wtyczkę?',
    'Ufam temu plikowi — uruchom',
    'NIEPODPISANA',
    'Podpis: %@',
    'Ścieżka: %@',
    'Zamień',
    'Zamień wszystko',
    'Zwykły tekst',
    'Rozszerzony (\\n \\t \\xNN)',
    'Wyrażenie regularne',
    'Uwzględniaj wielkość liter',
    'Całe słowo',
    'Brak wyników',
    'Wypróbuj wyrażenie regularne…',
    'Tryb dziennika (kolor według poziomu)',
    'Filtruj dziennik według poziomu…',
    'Uruchom na całym katalogu…',
    'Filtruj przez polecenie zewnętrzne…',
    'Skrypty…',
    'Pakiety rozszerzeń…',
    'Nowe okno',
    'Odłącz kartę do nowego okna',
    'Nie otwarto żadnego katalogu',
    'Znajdź plik w katalogu',
    'Filtruj według nazwy',
    'Nowy plik…',
    'Nowy katalog…',
    'Zmień nazwę…',
    'Przenieś do Kosza',
    'Pokaż w Finderze',
    'Trwa odczyt struktury dokumentu…',
    'ten plik nie ma funkcji',
    'Brak dopasowań',
    'Zwykły tekst',
    '🔒 Tylko do odczytu',
    'Śledzony',
    'zawijanie na kolumnie',
    'Składnia',
    'Kliknij, aby wstawić do zapytania',
    'nieprawidłowe zapytanie',
    'klucz «nazwa» w korzeniu',
    'klucz ze spacjami',
    'pierwszy element',
    'wszystkie elementy',
    'wycinek',
    'suma indeksów',
    'wszystkie klucze «cena» na wszystkich poziomach',
    'wszystkie węzły',
    'filtruj według liczby',
    'filtruj według obecności',
    'Przejdź do pierwszego błędu',
    'Kolumna przychód jest liczbowa',
    'filtruj…',
    'Anuluj',
    'Wykonaj zamianę',
    'podgląd',
    'interaktywnie',
    'Edycja',
    'Interfejs',
    'Skróty klawiszowe',
    'Rozmiar tekstu',
    'Szerokość tabulatora',
    'Wcinaj tabulatorami',
    'Wcinaj automatycznie przy przejściu do nowego wiersza',
    'Podświetlaj wszystkie wyniki wyszukiwania',
    'Normalizuj do NFC przy zapisie',
    'Język',
    'Wygląd',
    'Zgodnie z systemem',
    'Jasny',
    'Ciemny',
    'Motyw',
    'Użyj zestawu Notepad++',
    'Wróć do klawiszy domyślnych',
    'Otwórz plik konfiguracji',
    'Wyeksportuj bieżący motyw',
    'Zmiana języka zadziała w pełni przy następnym uruchomieniu.',
    'Klawisze domyślne wrócą przy następnym uruchomieniu.',
    'Podgląd Markdown',
    'Podgląd korzysta z systemowego silnika Markdown: na razie bez tabel i bez kolorowania bloków kodu.',
    'Wypróbuj wyrażenie regularne',
    'Wyrażenie',
    'Tekst próbny',
    'Wynik',
    'Dopasowania',
    'Co robi to wyrażenie',
    'Wyjaśnij wyrażenie',
    'Tryb wyszukiwania',
    'Wyniki wyszukiwania',
    'Brak dopasowań',
    ' (skrócono)',
    'Mapa dokumentu',
    'Pasek kart',
    'Wiersz nagłówków kolumn',
    'Brak kolumn',
    'Drzewo obszaru roboczego',
    'Lista funkcji i klas',
    'Wyniki wyszukiwania w katalogu',
    'Tabela danych CSV',
    'Warsztat czyszczenia danych',
    'Zapytanie JSONPath',
    'Lista błędów w danych',
    'Ewaluator zbioru złotego…',
    'Porównaj z ocenami zewnętrznymi (JSONL)…',
    'Wybierz plik ocen zewnętrznych (JSONL: query, chunk_id, score)',
    'Zmień nazwę zaznaczonego węzła',
    'Scal zaznaczone węzły',
    'Podziel zaznaczony węzeł',
    'Wyodrębnij zaznaczony podgraf do nowej karty',
    'Nie ma czego zmieniać',
    '%1$@ — zastosować %2$d {one=zmianę|few=zmiany|many=zmian}?',
    '%1$@: %2$d {one=zmiana|few=zmiany|many=zmian} · Cmd-Z cofa całą partię',
    'Ustaw kursor DOKŁADNIE na jednym węźle i spróbuj ponownie',
    'Zmień nazwę «%@»',
    'Wszystkie krawędzie i etykiety wskazujące ten węzeł zmienią się razem z nim.',
    'Zmień nazwę węzła',
    'Zaznacz CO NAJMNIEJ DWA węzły i spróbuj ponownie',
    'Postać kanoniczna «%@» — najczęstsza, najdłuższa, ze znakami diakrytycznymi',
    'Scal węzły',
    'Zaznacz WIERSZE KRAWĘDZI do przeniesienia i spróbuj ponownie',
    'Wszystkie zaznaczone wiersze muszą dotykać DOKŁADNIE jednego węzła — zaznacz więcej wierszy krawędzi',
    'Podział «%1$@» — przeniesienie %2$d {one=krawędzi|few=krawędzi|many=krawędzi}',
    'Krawędzie do: %@',
    'Podziel węzeł',
    'Dokument niezapisany — wyodrębniony plik potrzebuje miejsca obok',
    'Zaznacz część grafu do wyodrębnienia i spróbuj ponownie',
    'Zbierz warianty encji → tabela przeglądu',
    'Zastosuj poprawioną tabelę przeglądu',
    'Dokument niezapisany — tabela przeglądu musi leżeć obok pliku grafu',
    'Nie znaleziono wariantów do zebrania',
    '%d {one=grupa wariantów|few=grupy wariantów|many=grup wariantów} — popraw kolumnę «canonical» i uruchom «Zastosuj tabelę przeglądu»',
    'Nie ma tabeli przeglądu «%@» — najpierw uruchom «Zbierz warianty encji»',
    'Nie można odczytać tabeli przeglądu: %@',
    'Tabela przeglądu nie ma żadnego wiersza do zmiany',
    'Żadne miejsce w grafie nie pasuje do tabeli przeglądu',
    'Zbierz warianty encji',
    'Zastosowano %d {one=zmianę|few=zmiany|many=zmian} · tabelę aliasów i listę znaczników zapisano obok pliku',
    'Zastosować %d {one=zmianę|few=zmiany|many=zmian} do grafu?',
    '%d {one=alias|few=aliasy|many=aliasów} → postać kanoniczna.',
    'SCAL węzły (nie da się cofnąć przez ponowne wpisanie):',
    '%d {one=aliasu nie ma|few=aliasów nie ma|many=aliasów nie ma} w grafie i został pominięty.',
    'GraphRAG…',
    'Analiza pokrycia fragment ↔ encja',
    'Wyeksportuj pakiet kontekstu (JSONL)',
    'Pokrycie fragment ↔ encja ↔ graf',
    '- %1$d {one=encja|few=encje|many=encji} · %2$d {one=fragment|few=fragmenty|many=fragmentów} · %3$.0f%% encji wspomnianych · %4$.0f%% fragmentów z encją',
    'Encje, których nie wspomina żaden fragment',
    'Osierocone fragmenty (bez żadnej encji)',
    'Węzły grafu bez odpowiadającej encji',
    'brak',
    'Metoda',
    'Nie udało się zbudować odwzorowania fragment ↔ encja',
    'Oceń kondycję grafu',
    'kondycja grafu',
    'Kondycja %1$@/100 · %2$d {one=błąd|few=błędy|many=błędów} · %3$d {one=odwrócenie|few=odwrócenia|many=odwróceń} · %4$d osieroconych',
    'Hybryda z grafem',
    'α = 1: sygnał grafu jest całkowicie pomijany, wynik jest taki sam jak czysty BM25',
    'α wysokie: graf tylko lekko koryguje ranking BM25',
    'α w okolicy domyślnej 0,7: prowadzi BM25, graf koryguje',
    'α niskie: prowadzi graf, BM25 tylko rozstrzyga remisy',
    'α = 0: tylko sygnał grafu; fragmenty bez encji są sobie równe',
    'Dokument niezapisany — hybryda potrzebuje pliku grafu obok korpusu',
    'Nie znaleziono pliku grafu «%@» — hybryda potrzebuje go, aby uzyskać sygnał',
    'hybryda %.1f ms · %@',
    'Algorytmy…',
    'PageRank (grubość obramowania)',
    'Społeczności (kolor tła)',
    'Składowe spójne',
    'Wyeksportuj tabelę węzłów do nowej karty',
    '%1$d {one=składowa|few=składowe|many=składowych} · największa %2$d {one=węzeł|few=węzły|many=węzłów} · %3$d osieroconych węzłów',
    'Ten dokument nie jest grafem DOT',
    'Nie udało się zbudować tabeli węzłów/krawędzi: %@',
    '%d {one=wiersz|few=wiersze|many=wierszy} · %@',
    'Oznacz',
    'Notatka (opcjonalnie)',
    'Zapisz rekord',
    'Wyeksportuj CSV',
    'Dokument niezapisany — ewaluator musi leżeć obok pliku korpusu',
    'Nie udało się wczytać ewaluatora: %@',
    'Nie udało się zapisać: %@',
    'Ewaluator nie ma jeszcze żadnego rekordu',
    'Nie udało się zapisać: %@',
    'Ten dokument nie jest plikiem .mmd, nie jest DOT i nie ma bloku mermaid.',
    '%d {one=węzeł|few=węzły|many=węzłów} · %d {one=krawędź|few=krawędzie|many=krawędzi} · ⚠ %@',
    'Diagram Mermaid: dodaj element…',
    'Diagram Mermaid: połącz dwa zaznaczone elementy',
    'Diagram Mermaid: zmień etykietę zaznaczonego elementu…',
    'Diagram Mermaid: usuń zaznaczony element',
    'Diagram Mermaid: przesuń komunikat w górę',
    'Diagram Mermaid: przesuń komunikat w dół',
    'Dodaj element',
    'Dodaj uczestnika',
    'Dodaj pozycję',
    'Dodaj pozycję do diagramu',
    'Zmień pozycję diagramu',
    'Usuń pozycję z diagramu',
    'Usuń element',
    'Zmień etykietę',
    'Zmień kolejność komunikatów',
    'Nazwa pozycji',
    'Nowa pozycja',
    'Nazwa pozycji pojawia się na diagramie.',
    'Tabela właściwości diagramu',
    'Ten dokument nie ma bloku mermaid',
    'Identyfikator w źródle diagramu — bez spacji. Etykietę zmienia się potem dwukrotnym kliknięciem.',
    'Jeśli zostawisz puste, wyświetli się sam identyfikator.',
    'Zmienia się tylko widoczna ETYKIETA; identyfikator elementu pozostaje ten sam.',
    'Nie wiadomo, którym elementem jest «%@»',
    'Zaznacz DOKŁADNIE DWA elementy i spróbuj ponownie',
    'Ustaw kursor DOKŁADNIE na jednym elemencie i spróbuj ponownie',
    'Wybierz JEDEN element do usunięcia albo dwa elementy połączone krawędzią',
    'Usunąć «%1$@» oraz %2$d {one=krawędź, która go dotyka|few=krawędzie, które go dotykają|many=krawędzi, które go dotykają}?',
    'Węzły na drugim końcu tych krawędzi zostają zachowane — są deklarowane ponownie wraz z etykietą, jeśli instrukcja krawędzi była ich jedyną deklaracją.',
    'Diagram «%1$@» edytuje się wyłącznie jako tekst — %2$@',
    '%@: przeciągnij między dwoma elementami, aby je połączyć, kliknij dwukrotnie, aby zmienić etykietę',
    '%@: przeciągnij między dwoma uczestnikami, aby dodać komunikat; kolejność zmienisz w menu Narzędzia',
    '%@: edytuj w tabeli właściwości poniżej',
    'Włączono edycję wizualną',
    '%1$@ · %2$d {one=pozycja|few=pozycje|many=pozycji} — edytuj bezpośrednio w tabeli, każda komórka to jeden krok cofania',
    'Dla wykresu kołowego to liczba; dla Gantta to, co następuje po dwukropku.',
    'Diagram Mermaid: wyodrębnij blok do pliku .mmd…',
    'Diagram Mermaid: wstaw z powrotem wskazywany plik',
    'Wyodrębnij blok diagramu',
    'Wstaw blok diagramu',
    'Wyodrębnij blok diagramu do osobnego pliku',
    'Plik trafia OBOK dokumentu; w bloku zostaje jeden wiersz odwołania, więc edytujesz tylko w jednym miejscu.',
    'Dokument niezapisany — plik diagramu potrzebuje miejsca obok',
    'Plik «%@» już istnieje — wybierz inną nazwę',
    'Wyodrębniono do «%@» — w bloku został wiersz odwołania',
    'Otwórz plik',
    '«%@» wstawiono z powrotem; plik nadal jest na dysku',
    'Ten blok zawiera prawdziwy diagram, a nie odwołanie',
    'Ten blok odwołuje się do «%@» — otwórz tamten plik, aby go edytować',
    'Nie udało się odczytać pliku diagramu %@',
    'Edycja wizualna',
    'Przeciągnij z jednego węzła do drugiego, aby dodać krawędź; kliknij dwukrotnie, aby zmienić etykietę. Każda czynność to jeden krok cofania.',
    'Edycja wizualna: przeciągnij między dwoma węzłami, aby dodać krawędź, kliknij dwukrotnie, aby zmienić etykietę',
    'Wyłączono edycję wizualną',
    'Dodaj węzeł…',
    'Dodaj krawędź między dwoma zaznaczonymi węzłami…',
    'Zmień etykietę zaznaczonego węzła…',
    'Usuń zaznaczony węzeł/krawędź',
    'Dodaj węzeł',
    'Dodaj krawędź',
    'Zmień etykietę węzła',
    'Usuń węzeł',
    'Usuń krawędź',
    'Cmd-Z cofa',
    'Ten dokument jest tylko do odczytu',
    'Etykieta «%@»',
    'Zmienia się tylko widoczna ETYKIETA; identyfikator węzła pozostaje ten sam.',
    'Nie wiadomo, którym węzłem jest «%@»',
    'Identyfikator węzła w pliku DOT. Etykietę zmienia się potem dwukrotnym kliknięciem na rysunku.',
    'Zaznacz DOKŁADNIE DWA węzły i spróbuj ponownie',
    'Wybierz JEDEN węzeł do usunięcia albo dwa węzły połączone krawędzią',
    'Usunąć węzeł «%1$@» oraz %2$d {one=krawędź, która go dotyka|few=krawędzie, które go dotykają|many=krawędzi, które go dotykają}?',
    'Jeśli zostaną wiszące krawędzie, DOT odtworzy z nich węzły — usunięty węzeł pojawi się ponownie przy następnym rysowaniu.',
    'Laboratorium wyszukiwania BM25',
    'Pytanie — Enter, aby wyszukać',
    'Oceń…',
    'Trwa budowanie indeksu',
    'Żaden fragment nie pasuje',
    'najlepszych wyników',
    'k1 = 0: każde słowo liczy się TYLKO raz, niezależnie od liczby wystąpień',
    'k1 niskie: powtórzenie słowa prawie nie zwiększa oceny',
    'k1 w okolicy domyślnej 1,2: powtórzenie zwiększa ocenę, ale coraz mniej',
    'k1 wysokie: fragment powtarzający słowo wiele razy jest mocno nagradzany',
    'b = 0: długość jest pomijana, długie fragmenty nie są karane',
    'b niskie: długie fragmenty są karane tylko nieznacznie',
    'b w okolicy domyślnej 0,75: długie fragmenty są karane umiarkowanie',
    'b = 1: największa kara za długość, krótkie fragmenty są uprzywilejowane',
    'JSONL: laboratorium wyszukiwania…',
    'Dokument niezapisany — indeks BM25 leży obok pliku korpusu, więc potrzebna jest ścieżka',
    'Ten plik nie jest JSONL — Retrieval Lab działa na korpusie fragmentów',
    'Nie udało się zbudować indeksu BM25 dla tego pliku',
    'Dokument niezapisany — do wygenerowania raportu potrzebna jest ścieżka korpusu',
    'Wybierz zestaw ewaluacyjny (CSV lub JSONL: pytanie + oczekiwany identyfikator fragmentu)',
    'Ewaluacja wyszukiwania',
    'Zmień k1, b lub k powyżej i spójrz ponownie, aby porównać dwie konfiguracje; dodaj blok «compare», aby uruchomić dwa zestawy parametrów równolegle na tym samym zestawie ewaluacyjnym.',
    'Błąd',
    '   (%d…%d, średnio %.0f)',
    'Tryb JSONL',
    'Rekord',
    'Szczegóły',
    'Rekord w wierszu',
    'nie jest prawidłowym JSON-em',
    'rekordów',
    'pustych wierszy',
    'nie jest obiektem',
    'wyświetlana tabela',
    'ANULOWANO W POŁOWIE',
    'Bez filtra',
    'rekordów pasujących do filtra',
    'Ustaw kursor na wierszu, aby zobaczyć rekord',
    'Brak uszkodzonych rekordów',
    'Jeszcze nie zbadano. Uruchom ponownie «JSONL: zbadaj fragmenty» po sprawdzeniu.',
    'pole tekstowe',
    'SCHEMAT (zgadnięty — zmienia się po wybraniu innego pola)',
    'tekst',
    'identyfikator',
    'zagnieżdżone metadane',
    'POLE',
    'pokrycie',
    'wiele typów',
    'DŁUGOŚĆ — znaki',
    'DŁUGOŚĆ — słowa',
    'DŁUGOŚĆ — szacowane tokeny',
    'PUSTE I POWTÓRZONE',
    'pustych fragmentów',
    'wierszy',
    'grup dokładnych duplikatów',
    'wierszy nie do odczytania, poza statystyką',
    'METODA',
    '«znaki» liczone są jako znaki Unicode (skalary), a nie widoczne grupy',
    '«słowa» rozdzielane są spacjami ASCII',
    '«tokeny» liczone są dzielnikiem sylab — NIE tym z modelu',
    '«duplikat» oznacza duplikat DOKŁADNY; niemal-duplikaty są w bloku ```quality',
    'fragmentów',
    'JSONL: sprawdź i zbadaj fragmenty…',
    'Obraz',
    'PDF',
    'Dokument Word',
    'Arkusz Excel',
    'Prezentacja PowerPoint',
    'Archiwum',
    'Dopasuj do okna',
    'Skopiuj obraz',
    'Obróć',
    'Nie można odczytać obrazu «%@»',
    'Skopiowano obraz do schowka',
    'Podświetl na żółto',
    'Podkreśl',
    'Notatka…',
    'Usuń adnotacje',
    'Wyodrębnij tekst do nowej karty',
    'Zapisz wersję z adnotacjami…',
    'Szukaj w PDF',
    'Dodaj',
    'Strona %d/%d',
    'Strona %d',
    'Wynik %d/%d',
    '0 wyników',
    'Nie można odczytać pliku PDF «%@»',
    'Ten PDF jest chroniony hasłem — treść jest niedostępna',
    'Nie znaleziono «%@» w dokumencie',
    'Podświetlono',
    'Podkreślono',
    'Najpierw zaznacz fragment tekstu',
    'Dodano notatkę',
    'Ta strona nie ma żadnych adnotacji',
    'Usunięto %d {one=adnotację|few=adnotacje|many=adnotacji} z tej strony',
    'Ten PDF nie ma warstwy tekstowej — najpewniej jest to skan',
    'Nie udało się zapisać pliku',
    'Zapisany plik NIE otwiera się poprawnie — nie używaj tej wersji',
    'Zapisano %@ · %d {one=strona|few=strony|many=stron}',
    'Nazwa',
    'Rozmiar',
    'Skompresowany',
    'Stosunek',
    'Zmieniono',
    'Otwórz zaznaczoną pozycję',
    'Rozpakuj do katalogu…',
    'Rozpakuj tutaj',
    '%d {one=pozycja|few=pozycje|many=pozycji}',
    'rozpakowano do %@',
    '— wnętrze pliku Office to archiwum; oto jego części',
    'Rozpakowano %d {one=pozycję|few=pozycje|many=pozycji}',
    '%d {one=pozycja uszkodzona|few=pozycje uszkodzone|many=pozycji uszkodzonych}',
    '%d {one=pozycję ODRZUCONO|few=pozycje ODRZUCONO|many=pozycji ODRZUCONO}, bo ich ścieżki wychodzą poza katalog docelowy',
    'Nie można otworzyć tej pozycji',
    'Nie da się jeszcze zapisywać bezpośrednio do %@ — użyj «Zapisz jako…»',
    'Nic się nie zmieniło',
    'Zapisano %1$d {one=komórkę|few=komórki|many=komórek} do %2$@',
    'Zapisano %1$d {one=akapit|few=akapity|many=akapitów} do %2$@',
    'Nie udało się zapisać do pliku — oryginał pozostaje nietknięty',
    'przygotowanie przypadku testowego',
    'Nie można zapisać settings.json',
    'Obróć w lewo',
    'Obróć w prawo',
    'Przenieś stronę w górę',
    'Przenieś stronę w dół',
    'Usuń strony…',
    'Usuń strony',
    'Wyodrębnij strony…',
    'Wyodrębnij strony do nowego pliku',
    'Scal plik PDF…',
    'Podziel plik…',
    'Podziel plik PDF',
    'Eksportuj obrazy…',
    'Eksportuj strony jako obrazy PNG',
    'Cofnij edycję strony',
    'Zapisz zmienioną kopię…',
    'Odtwórz',
    'Wstrzymaj',
    'Widok normalny',
    'Wybierz arkusz',
    'Otwórz arkusz',
    'Odrzuć i zmień arkusz',
    'Skoroszyt ma %d arkuszy.',
    'Ten skoroszyt ma tylko jeden arkusz: „%@”',
    'Odrzucić niezapisane zmiany w tym arkuszu?',
    'Zmiana arkusza zastępuje całą kartę. To, co nie zostało zapisane przez ⌘S, przepadnie.',
    'Wybierz plik PDF do scalenia',
    'Wybierz folder na obrazy',
    'Wybierz miejsce zapisu. Drugi plik zostanie zapisany obok tego.',
    'Dokument ma %d stron. Podaj strony do usunięcia, np. 2-4,7',
    'Dokument ma %d stron. Podaj strony do wyodrębnienia, np. 1-3,8',
    'Dokument ma %d stron. Podaj strony do eksportu, np. 1-3',
    'Dokument ma %d stron. Podaj część do oddzielenia, np. 1-5; reszta trafi do drugiego pliku.',
    'Obrócono stronę %d',
    'Usunięto strony %@ · pozostało %d stron',
    'Scalono %d stron z „%@”',
    'Podzielono na %@ (%d stron) i %@ (%d stron)',
    'Zapisano %@ — %@ · %d stron',
    'Wyeksportowano %d obrazów do %@',
    'Wyeksportowano tylko %d z %d obrazów',
    'Cofnięto jedną operację na stronie',
    'Brak operacji na stronie do cofnięcia',
    'Nie można usunąć WSZYSTKICH stron — PDF musi mieć co najmniej jedną',
    'Ten zakres to cały dokument — nie ma czego oddzielać',
    '„%@” jest chroniony hasłem — nie można scalić',
    '„%@” nie ma stron',
    'To już pierwsza strona',
    'To już ostatnia strona',
    '· zmieniono, niezapisane',
    'Obraz animowany · %d klatek',
    'Niezapisany dokument — brak pliku na dysku do podglądu binarnego',
    'To polecenie działa tylko ze skoroszytami Excela',
    'Nie udało się odczytać listy arkuszy',
    'Nie ma arkusza „%@”',
    'Nie udało się odczytać arkusza „%@”',
    'Arkusz „%@” · %d wierszy',
    'reszta',
    'Uwaga',
    'Uwaga!',
    'Zobacz też',
    'Kopiuj',
    'Skopiowano',
    'Skopiuj przykładowy kod',
    'Szukaj w pomocy',
    'Wstecz',
    'Zaczynamy',
    'Nie pokazuj tego okna przy uruchamianiu',
    'Pomoc nie jest jeszcze przetłumaczona na ten język — pokazywana jest wersja wietnamska.',
    'Przejdź do offsetu (np. 1F400 lub 0x1F400)',
    'Kopiuj zaznaczone wiersze',
    'Skopiowano %d wierszy',
    'Nie udało się odczytać „%@”',
    'Pusty plik',
    'Nie udało się odczytać offsetu „%@”',
    'Offset 0x%@ wykracza poza rozmiar pliku',
    'Otwórz w innej aplikacji…',
    '%d kanałów',
    'Nie można odtworzyć „%@”',
    'Nie można odtworzyć — %@',
    'macOS nie ma wbudowanego dekodera formatu %@ — to ograniczenie systemu, a nie uszkodzony plik.',
    'Nadal możesz obejrzeć bajty w trybie binarnym lub otworzyć plik aplikacją z własnym dekoderem.',
    'Podpisz…',
    'Edytuj tekst…',
    'Edytuj tekst',
    'Narysuj na wierzchu',
    'Następne puste pole',
    'Wyczyść wypełnione pola',
    'Ten plik nie ma pól formularza',
    'Wyczyszczono %d pól formularza',
    'Wszystkie pola formularza są już wypełnione',
    'Pozostało %d pustych pól',
    'Formularz do wypełnienia: %d pól. Wpisuj bezpośrednio, potem „Zapisz zmienioną kopię…”',
    'Wybierz obraz podpisu (najlepiej z przezroczystym tłem)',
    'Nie udało się utworzyć podpisanej strony',
    'Wstawiono podpis na stronie %d',
    'Najpierw zaznacz tekst do zmiany',
    'Zaznaczenie jest za małe',
    'Nowy tekst jest RYSOWANY NA WIERZCHU zaznaczenia czcionką systemową. Stary tekst jest zakryty, a nie usunięty — nadal da się go wydobyć, więc to nie jest redakcja.',
    'Nie udało się utworzyć zmienionej strony',
    'Narysowano nowy tekst na stronie %d',
    'Przełącz Widok / Kod',
    'Brak jeszcze widoku drzewa dla JSON · XML · YAML',
    'Brak jeszcze widoku diagramu w karcie',
    'Brak jeszcze widoku konspektu dla PowerPointa',
    'Ten plik ma tylko jeden tryb wyświetlania',
    '%d węzłów',
    'Nie udało się zbudować drzewa: %@',
    'Dokument jest za duży na drzewo — użyj trybu Kod',
]
