# Bản dịch ro — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code ro --name "…" scripts/ban-dich/ro.py
VALS = [
    'Versiuni salvate…',
    'Acest document nu a fost salvat niciodată — nu există încă istoric',
    'Nu există versiuni salvate anterioare',
    'Versiunea aceasta nu poate fi citită',
    'Restaurează versiunea salvată',
    'XML: validare după DTD/XSD…',
    'Acest Mac nu are libxml2, așa că validarea XSD nu este disponibilă.',
    'Alegeți o schemă XSD pentru validare',
    'Valid față de',
    'Modulul s-a încheiat fără să schimbe nimic',
    'Niciun modul nativ instalat',
    'Elimină acest modul',
    'Eliminați acest modul?',
    'Elimină',
    'Instalează un modul nativ…',
    'Deschide dosarul modulelor',
    'Alegeți fișierul .dylib al modulului',
    'Instalat:',
    'Eliminat:',
    'Module native…',
    'Se acceptă doar fișiere .dylib.',
    'Un modul cu același nume este deja instalat:',
    'Modulul nu poate fi copiat:',
    'Modulele native sunt disponibile doar în descărcarea directă, nu în versiunea din App Store.',
    'Procesul ajutător al modulelor nu poate fi găsit.',
    'Procesul ajutător al modulelor nu poate fi pornit:',
    'Procesul modulului s-a oprit pe neașteptate.',
    'Modulul nu a răspuns la timp — a fost oprit.',
    'Modulul a răspuns cu un mesaj deformat:',
    'Modulul a raportat o eroare:',
    'Despre GEditor',
    'Configurări…',
    'Ieșire din GEditor',
    'Fișier',
    'Filă nouă',
    'Închide fila',
    'Fila următoare',
    'Fila anterioară',
    'Document nou',
    'Deschide…',
    'Deschide dosarul ca spațiu de lucru…',
    'Deschise recent',
    'Salvează',
    'Salvează ca…',
    'Taie spațiile de la capăt la salvare',
    'Urmărește fișierul (tail -f)',
    'Tipărește…',
    'Redeschide ultima filă închisă',
    'Niciun fișier recent',
    'Golește meniul',
    'Editare',
    'Anulează',
    'Refă',
    'Taie',
    'Copiază',
    'Lipește',
    'Istoricul clipboardului…',
    'Editor de coloane…',
    'Selectează apariția următoare',
    'Selectează tot',
    'Dublează linia',
    'Șterge linia',
    'Comentează / decomentează',
    'Nu ați copiat încă nimic',
    'Golește istoricul',
    'Căutare',
    'Caută…',
    'Caută și înlocuiește…',
    'Caută în dosar…',
    'Înlocuiește în dosar…',
    'Rezultatul următor',
    'Rezultatul anterior',
    'Mergi la linia…',
    'Sari la paranteza pereche',
    'Marchează toate liniile care se potrivesc…',
    'Inversează marcajele',
    'Șterge toate marcajele',
    'Copiază liniile marcate',
    'Șterge liniile marcate',
    'Păstrează doar liniile marcate',
    'Linii',
    'Sortează A→Z',
    'Sortează Z→A',
    'Sortare naturală',
    'Elimină duplicatele',
    'Inversează liniile',
    'Mută liniile în sus',
    'Mută liniile în jos',
    'Unește liniile',
    'Taie liniile după lungime…',
    'Taie liniile după caracter…',
    'Elimină liniile goale',
    'Comprimă liniile goale',
    'Taie spațiile de la capătul liniei',
    'Tab → spațiu',
    'Spațiu → tab',
    'MAJUSCULE',
    'minuscule',
    'Fiecare Cuvânt Cu Majusculă',
    'Prima literă majusculă',
    'iNVERSEAZĂ mAJUSCULELE',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: alege foaia…',
    'Comută între tabel și text',
    'Șterge coloana…',
    'Verifică datele (coloane · tipuri)',
    'Banc de curățare a datelor…',
    'Rulează o rețetă de curățare…',
    'Convertește…',
    'Schimbă separatorul…',
    'Exportă în JSON…',
    'Format',
    'Codificare…',
    'Sfârșituri de linie…',
    'Normalizează Unicode…',
    'JSON: formatează',
    'JSON: comprimă',
    'JSON: sortează cheile',
    'JSON: interogare JSONPath…',
    'CSV: interogare SQL…',
    'Interogare SQL',
    'Se execută…',
    'Exportă într-o filă nouă',
    'Document gol — nu există tabel de interogat',
    'Nu este un tabel CSV — primul rând are o singură coloană',
    'Interogarea nu a putut fi citită',
    'Interogarea nu a putut fi verificată',
    'Galben (implicit)',
    'Albastru',
    'Verde',
    'Ocru',
    'Violet',
    'Roz',
    'Turcoaz',
    'Portocaliu',
    'Ardezie',
    'Text',
    'Serie de numere',
    'Serie de date',
    'Majuscule (hexa)',
    'Început',
    'Pas',
    'Completează cu zerouri până la',
    'Bază',
    'Prima dată',
    'Format',
    'Inserează',
    'Renunță',
    'Convertește formatul',
    'Previzualizează primele 5 rânduri',
    'Deschide într-o filă nouă',
    'Salvează în fișier…',
    'Rezultatul se deschide într-o filă nouă, nesalvată. Documentul original rămâne neatins.',
    'Rulează pe acest document',
    'Rulează pe un dosar…',
    'Toată rețeta este UN singur pas de anulare. Fișierul de pe disc rămâne neatins până la salvare.',
    'oprit',
    'coloana nu a fost găsită',
    'gata',
    'ține ocupat un nucleu de procesor până la închiderea aplicației.',
    'Scriptul nu a returnat nimic',
    'Motorul JavaScript nu a putut fi creat',
    'Eroare JavaScript necunoscută',
    'Tabel',
    'Aplică sortarea asupra fișierului',
    'Convertește ▾',
    'Exportă rândurile care se potrivesc',
    'Ascunde această coloană',
    'Redenumește antetul…',
    'Inserează o coloană goală la stânga',
    'Inserează o coloană goală la dreapta',
    'Șterge această coloană din fișier…',
    'Cel puțin o coloană trebuie să rămână vizibilă',
    'Se sortează…',
    'Înapoi la ordinea din fișier',
    'primele o sută de rânduri',
    'alegerea coloanelor',
    'denumirea unei coloane de rezultat',
    'filtrare după text',
    'celule goale',
    'combinarea condițiilor',
    'numărarea rândurilor',
    'grupare și agregare',
    'minim, maxim',
    'sortare și limitare',
    'nume de coloană cu spații',
    'Interogarea a fost întreruptă',
    'Nu sunt acceptate: JOIN · subinterogare · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funcții de fereastră',
    'XML: formatează',
    'XML: comprimă',
    'XML: verifică sintaxa',
    'YAML: verifică cheile și indentarea',
    'Vizualizare',
    'Comută bara laterală (lista de funcții)',
    'Comută harta documentului',
    'Pliază / depliază la cursor',
    'Pliază tot',
    'Depliază tot',
    'Pliază până la nivelul',
    'Nivelul %d',
    'S-au pliat %1$d {one=bloc|few=blocuri|other=de blocuri} la nivelul %2$d',
    'Acest document are doar %d {one=nivel|few=niveluri|other=de niveluri}',
    'mermaid: manifestul nu poate fi citit',
    'Caută actualizări…',
    'Caută actualizări',
    'Versiunile din App Store se actualizează prin Mac App Store, nu prin GEditor.',
    'Această versiune nu are cheie de semnare a actualizărilor, deci nu poate căuta actualizări.',
    'Mărește',
    'Micșorează',
    'Mărime reală',
    'Împarte pe verticală',
    'Împarte pe orizontală',
    'Închide împărțirea',
    'Deschide fila în celălalt panou',
    'Treci în celălalt panou',
    'Încadrarea rândurilor (oprită / la fereastră / la coloană)',
    'Încadrează la coloana…',
    'Comută semnul de carte',
    'Semnul de carte următor',
    'Semnul de carte anterior',
    'Culoarea semnului de carte…',
    'Arată toate caracterele invizibile',
    '  Spații',
    '  Taburi',
    '  Sfârșituri de linie',
    '  NBSP · lățime zero · control',
    'Vizualizare binară',
    'Mod CSV (coloane curcubeu)',
    'Macro',
    'Pornește / oprește înregistrarea',
    'Redă',
    'Redă de mai multe ori…',
    'Redă până la sfârșitul documentului',
    'Rulează pe toate filele',
    'Oprește macroul în curs',
    'Salvează macroul…',
    'Macrouri salvate…',
    'Ajutor',
    'Ajutor GEditor',
    'Prezentarea funcțiilor',
    'Trecerea de la Notepad++',
    'Caută',
    'Înlocuiește cu',
    'Următorul',
    'Anteriorul',
    'Numără',
    'Închide',
    'Validează după o schemă JSON…',
    'Alegeți un fișier de schemă JSON',
    'Nicio problemă față de această schemă.',
    'Schemă JSON',
    'Verifică sintaxa grafului',
    'Format de graf nerecunoscut — este nevoie de extensia .dot, .gv, .cypher, .ttl sau .graphml.',
    'Nu am găsit erori de sintaxă %@ (verificarea nu este exhaustivă).',
    'sintaxă %@',
    'nu este un obiect JSON',
    'Minerit de text (n-grame, TF-IDF)',
    'Documentul este gol.',
    'Nu s-au putut extrage cuvinte-cheie.',
    'Cuvinte-cheie',
    '%d {one=cuvânt-cheie|few=cuvinte-cheie|other=de cuvinte-cheie} · %d {one=jeton|few=jetoane|other=de jetoane} · %d {one=document|few=documente|other=de documente}',
    'Marchează în document',
    'Marchează entități dintr-o listă…',
    'Alegeți o listă de entități (CSV sau JSON)',
    'Lista de entități nu a putut fi citită.',
    'Lista de entități este goală.',
    'Nicio entitate găsită în document (%d încărcate).',
    '%d {one=apariție|few=apariții|other=de apariții} · %@',
    'Convertește cunoștințe…',
    'Conversie: %@ → %@',
    'Conversia nu a reușit.',
    'Previzualizează fragmentarea…',
    'Fix 800 B, suprapunere 100 B',
    'După propoziție (≤ 800 B)',
    'După titlurile Markdown',
    'Document gol — niciun fragment.',
    '%d {one=fragment|few=fragmente|other=de fragmente} · %d B în medie · %@',
    'Exportă JSONL',
    'JSONL de fragmente',
    'Deschide tripletele/muchiile ca tabel',
    'Tabel de triplete',
    'Acest document nu are linii de triplete.',
    'Nu s-au putut citi triplete — linia %d: %@',
    'S-au citit %1$d {one=triplet|few=triplete|other=de triplete} · s-au sărit %2$d {one=linie deformată|few=linii deformate|other=de linii deformate} (prima: linia %3$d)',
    'Duplicate aproximative după coloană…',
    'Duplicate aproximative — coloana „%1$@”: %2$d {one=grup candidat|few=grupuri candidate|other=de grupuri candidate}',
    'Contopește',
    'Potrivire',
    'Valorile din grup',
    'Contopește în',
    'Contopește grupurile selectate',
    'Niciun grup selectat — Contopirea nu va schimba nimic. Aplicația nu contopește niciodată singură.',
    '%1$d {one=grup selectat|few=grupuri selectate|other=de grupuri selectate} · %2$d {one=rând se va schimba|few=rânduri se vor schimba|other=de rânduri se vor schimba} · UN singur pas de anulare',
    'Această coloană nu a putut fi scanată.',
    'Coloana „%@” nu are grupuri de duplicate aproximative.',
    'Niciun grup contopit — documentul este neschimbat.',
    'Deduplicare aproximativă · coloana %@',
    'S-au contopit %1$d {one=grup|few=grupuri|other=de grupuri} · %2$d {one=celulă modificată|few=celule modificate|other=de celule modificate}',
    'Raport de curățare',
    '# Raport de curățare — %@\n\n',
    '## Aplicate (%d)\n\n',
    '_Niciun pas aplicat încă._\n',
    '\n## Profilul datelor\n\n',
    '_%1$d {one=coloană|few=coloane|other=de coloane} · %2$d {one=rând|few=rânduri|other=de rânduri} · scanate în %3$.1f s_\n\n',
    '| Coloană | Tip | Goale | Distincte | Minim | Maxim | Medie |\n',
    '\n### Valori aberante\n\n',
    'rândul %d: %@',
    '- coloana „%1$@” — %2$d {one=celulă|few=celule|other=de celule}: %3$@\n',
    '\n## Rămase (%d)\n\n',
    '_Nu a mai rămas nicio constatare._\n',
    '- coloana „%1$@”: %2$@\n',
    None,
    'Taie spațiile la salvare',
    'Normalizează sfârșiturile de linie',
    'anterior',
    'Dosarul „%@” din sesiunea anterioară nu a putut fi redeschis',
    ' (și încă %d {one=fișier|few=fișiere|other=de fișiere})',
    '%1$d {one=filă nu a putut fi redeschisă|few=file nu au putut fi redeschise|other=de file nu au putut fi redeschise}: %2$@%3$@ — fișierele nu mai sunt unde erau.',
    'Nu s-a putut citi intrarea din conductă',
    'Spațiile de la capătul liniei vor fi tăiate la fiecare salvare',
    'Nu mai tăiem spațiile la salvare',
    'Fără titlu.txt',
    'Conversia codificării va pierde caractere',
    'Salvează oricum',
    'Documentul are modificări nesalvate',
    'Închiderea fără salvare le va pierde.',
    'Renunță la modificări',
    'Mergi la linia',
    'Documentul are %d {one=linie|few=linii|other=de linii}.',
    'Numărul liniei',
    'Mergi',
    'Reinterpretează ca…',
    'Convertește în…',
    'Reinterpretarea nu a reușit',
    '%@ nu poate reprezenta fiecare caracter',
    'Aleg oricum',
    'Coloana %d',
    'Coloana %1$d: %2$@',
    'Coloane ascunse: %1$@ (%2$d) — se restaurează din meniul contextual al antetului',
    'Arată din nou: %@',
    'Coloana %@ a fost ascunsă — coloana este intactă în fișier',
    'Sortat după %@ %@ · doar la afișare',
    'Sortat: %@ %@ (doar la afișare)',
    '%d+ rânduri se potrivesc — căutarea continuă…',
    '%1$d / %2$d {one=rând se potrivește|few=rânduri se potrivesc|other=de rânduri se potrivesc}',
    'Nicio problemă în %d {one=rând|few=rânduri|other=de rânduri}',
    '%d {one=rând|few=rânduri|other=de rânduri} cu număr greșit de coloane',
    '%d {one=celulă|few=celule|other=de celule} cu tip de date greșit',
    ' (ne-am oprit la primele %d {one=problemă|few=probleme|other=de probleme})',
    '   —   tipuri detectate: ',
    'Rândul %1$d, coloana %2$@: „%3$@” nu este %4$@',
    'Editor de coloane — %d {one=linie|few=linii|other=de linii}',
    'Constatări',
    'Profilul datelor',
    'Profilul datelor — se scanează…',
    'Salvează rețeta…',
    'Exportă raportul',
    'Niciun grup aplicat încă · fiecare grup este un pas de anulare',
    'prea multe valori',
    'cele mai frecvente: ',
    'Valoarea cu care se umplu golurile',
    'Aplică',
    'Nu s-a putut construi o previzualizare',
    '· păstrat ca atare, neinterpretabil ·',
    'Convertește coloana în ISO 8601 (AAAA-LL-ZZ)',
    'Convenția numerică pentru toată coloana',
    'Ce se face cu golurile',
    'Normalizează la ISO 8601',
    'Citește celulele ambigue cu ZIUA prima (31/12)',
    'Citește celulele ambigue cu LUNA prima (12/31)',
    'Sari peste celulele ambigue, repară doar pe cele sigure',
    'Spre stilul vietnamez/european (1.234,56)',
    'Spre stilul anglo-american (1,234.56)',
    'Spre stilul anglo-american, fără grupare (1234.56)',
    'Umple cu o valoare implicită…',
    'Umple în jos — ia valoarea de deasupra',
    'Umple în sus — ia valoarea de dedesubt',
    'Șterge rândurile cu gol în această coloană',
    'Taie spațiile de la ambele capete',
    'Taie la ambele capete și comprimă spațiile interioare',
    'Tabel pivot…',
    'Surse…',
    'Pivot — grupare după coloană',
    'Rânduri (grupare după)',
    'Valori',
    '+ Rând',
    '+ Valoare',
    'Șterge tot',
    'Pune în caseta de interogare',
    'Alegeți coloanele pentru a construi interogarea.',
    'Numele coloanelor acestui tabel nu au putut fi citite.',
    'Sursele de date ale interogării',
    '„%@” — documentul deschis',
    '  ⚠️ fișierul s-a schimbat de la înregistrare',
    'Adaugă fișier…',
    'Elimină tot',
    'Nu s-a putut deriva un nume de tabel din „%@” — redenumiți fișierul.',
    'Sumă',
    'Medie',
    'Minim',
    'Maxim',
    'Număr de valori distincte',
    'Grafic',
    'Exportă PNG',
    'Exportă SVG',
    'Acest tabel nu are nicio coloană numerică de reprezentat grafic.',
    'Imaginea PNG nu a putut fi construită.',
    'Rezultatul interogării',
    'S-a salvat %@',
    'Grafic %1$@ pentru „%2$@” — %3$d {one=punct|few=puncte|other=de puncte}, valori de la %4$@ la %5$@',
    'Bare',
    'Linie',
    'Histogramă',
    'Dispersie',
    'Cutie',
    'CSV: calitatea datelor…',
    'Calitatea datelor',
    'Exportă încălcările într-o filă nouă',
    'Nivel',
    'Regulă',
    'Încălcări',
    'Rată',
    'trecut',
    'eroare',
    'avertisment',
    'defect',
    'S-au marcat %d {one=linie care încalcă regulile|few=linii care încalcă regulile|other=de linii care încalcă regulile}',
    'Evoluție',
    'Punctat la',
    'Rânduri',
    'Diferență',
    'Reguli căzute',
    'Punctajul calității',
    'Punctajul în timp',
    'Nu există încă istoric — fiecare punctare adaugă ',
    'câte o linie în fișierul „.history.jsonl” de lângă reguli.',
    '%d {one=punct|few=puncte|other=de puncte} în istoric',
    ' · %d {one=linie ilizibilă|few=linii ilizibile|other=de linii ilizibile}',
    ' · selectați două rânduri pentru comparație',
    'punctaj %+.1f',
    'nicio dimensiune nu a scăzut',
    'au scăzut: ',
    '%1$d {one=regulă căzută nou|few=reguli căzute nou|other=de reguli căzute nou}: %2$@',
    'rânduri %+d',
    ' (și încă %d {one=avertisment|few=avertismente|other=de avertismente} în fila Evoluție)',
    'Nicio reparare automată: ',
    'Deschide unealta de curățare potrivită, apoi punctează din nou imediat.',
    'Tratează valorile lipsă…',
    'Normalizează datele calendaristice…',
    'Elimină duplicatele…',
    'Înlocuiește…',
    'Arată rândurile vinovate',
    'Coloana „%@” nu se află în acest tabel.',
    'Duplicatele au fost eliminate — „%1$@” este acum unică. Punctaj: %2$.0f/100',
    'Duplicatele au fost eliminate, dar „%1$@” mai are %2$d {one=rând duplicat|few=rânduri duplicate|other=de rânduri duplicate} (erau %3$d) — ',
    'acele rânduri au aceeași CHEIE, dar nu și restul liniei, așa că trebuie să vă uitați și să alegeți ',
    'pe care îl păstrați.',
    'Nu s-a putut citi nicio valoare care încalcă această regulă.',
    '%1$d {one=valoare greșită|few=valori greșite|other=de valori greșite} în coloana „%2$@” — completați la Înlocuiește, apoi previzualizați',
    'Punctat din nou: %.0f/100',
    'Previzualizarea raportului',
    'Parametri…',
    'Exportă HTML…',
    'Tipărește / PDF…',
    '%1$d {one=bloc a rulat|few=blocuri au rulat|other=de blocuri au rulat} · %2$d {one=bloc A CĂZUT|few=blocuri AU CĂZUT|other=de blocuri AU CĂZUT}',
    '%d {one=bloc a rulat|few=blocuri au rulat|other=de blocuri au rulat}',
    ' · DATE ÎNVECHITE — fișierul sursă s-a schimbat; reconstruiți',
    'Previzualizarea raportului are nevoie de un document .%@',
    'Nicio sursă de date găsită — declarați „source: file.csv” în frontmatter.',
    'Raportul nu a putut fi construit.',
    'Acest raport nu declară niciun parametru în frontmatter.',
    'Parametrii raportului',
    'Reconstruiește',
    'S-a exportat %@',
    'Raport: previzualizare',
    'Raport: generare în lot…',
    'nu este un document .greport.md',
    'raportul nu a putut fi analizat',
    'datele sursă nu au putut fi găsite',
    'lista de parametri nu a putut fi citită',
    'Generarea în lot are nevoie de un document .%@',
    'Alegeți o listă de parametri (CSV sau JSON)',
    'Alegeți un dosar pentru %d {one=raport|few=rapoarte|other=de rapoarte}',
    '[%1$d/%2$d] %3$@',
    'parametri lipsă ',
    'indică chiar fișierul sursă — refuzăm să îl suprascriem',
    '%d {one=bloc A CĂZUT|few=blocuri AU CĂZUT|other=de blocuri AU CĂZUT}',
    'Lot terminat: %1$d {one=fișier|few=fișiere|other=de fișiere} · %2$d căzute',
    '%d {one=set de parametri nu a putut fi construit|few=seturi de parametri nu au putut fi construite|other=de seturi de parametri nu au putut fi construite} — vedeți rezumatul',
    'Diagramă Mermaid: previzualizare',
    'Diagramă Mermaid: inserează un șablon…',
    'Diagramă Mermaid: reformatează',
    'Fundal transparent',
    'Acest Mac nu poate rasteriza diagrama în PNG — este nevoie de macOS 13. Exportul SVG funcționează în continuare.',
    'Salvează PNG %@…',
    'Salvează SVG…',
    'Copiază imaginea în clipboard',
    'Culorile mărcii…',
    'Culorile mărcii pentru diagrame',
    'Fiecare câmp este o culoare #rrggbb. Se salvează în „themes/mermaid-brand.json” — copiați-l pe alt Mac.',
    'Culoarea principală',
    'Textul de pe noduri',
    'Chenar',
    'Legături',
    'Fundalul la export',
    'Salvează și inserează %%{init}%% în document',
    'Culorile mărcii au fost salvate',
    'Imaginea diagramei a fost copiată în clipboard',
    'S-a salvat %1$@ — %2$@',
    'Această diagramă are deja o directivă %%{init}%% — a dumneavoastră a rămas neatinsă.',
    'S-a inserat %%{init}%% — diagrama își poartă acum propriile culori',
    'Inserează culorile mărcii în diagramă',
    'Reformatează diagrama Mermaid',
    'Sursa diagramei este deja ordonată — nu e nimic de schimbat',
    'Diagrama a fost reformatată',
    'S-au reformatat %d {one=diagramă|few=diagrame|other=de diagrame}',
    'Biblioteca de șabloane de diagrame',
    'Șabloane complete de diagrame',
    'Fragmente de sintaxă',
    'Se editează: %@',
    'S-a inserat șablonul „%@”',
    'Acest document este doar pentru citire.',
    'Diagramă Mermaid',
    'Acest document nu are niciun bloc mermaid.',
    'Marcă',
    'Exportă…',
    'Nicio diagramă încă',
    '%d {one=diagramă|few=diagrame|other=de diagrame} · %@',
    '%1$d/%2$d {one=diagramă A CĂZUT|few=diagrame AU CĂZUT|other=de diagrame AU CĂZUT} — diagrama %3$d%4$@',
    ', linia %d',
    'Acest document nu are niciun bloc ```mermaid și nu este un fișier .mmd.',
    'Nicio diagramă nu a terminat încă de randat.',
    'Nu am găsit „%@” în sursa diagramei',
    'nu s-a putut construi blocarea rețelei pentru WKWebView',
    'Reguli de asociere',
    'Un coș pe rând',
    'Două coloane: id · articol',
    'Forma datelor de tranzacție',
    'Coloana coșului sau coloana id-ului de tranzacție',
    'Coloana articolului',
    'Caracterul separator al articolelor',
    'Suport minim, procente',
    'Încredere minimă, procente',
    'Împarte după:',
    'Suport ≥',
    '% · Încredere ≥',
    'Tabelul regulilor de asociere',
    'Suport',
    'Încredere',
    'Lift',
    'Pârghie',
    'Atenție',
    '%d {one=tranzacție|few=tranzacții|other=de tranzacții} · %d {one=articol|few=articole|other=de articole} · %d {one=regulă|few=reguli|other=de reguli}',
    ' — nicio regulă nu a atins pragurile; coborâți suportul sau încrederea',
    ' — S-A OPRIT DEVREME, tabelul este INCOMPLET',
    '%1$d / %2$d {one=tranzacție conține|few=tranzacții conțin|other=de tranzacții conțin} ambele părți',
    'Forma cu două coloane are nevoie de două coloane DIFERITE.',
    'S-au marcat %1$d {one=rând|few=rânduri|other=de rânduri} din %2$d {one=tranzacție|few=tranzacții|other=de tranzacții} care conțin „%3$@”',
    'CSV: reguli de asociere…',
    'Minerit pe grupuri',
    'Coloana de grupare',
    'Coloana de valori',
    'A doua coloană pentru corelație',
    'Clasament',
    'Grupează după:',
    'Valoare:',
    'Clasează după:',
    'Tabelul clasamentului grupurilor',
    'Grup',
    'Rânduri',
    'Prag propriu',
    'MAPE',
    'r',
    'diferență r',
    'Notă',
    'nemăsurabil',
    '%d {one=grup|few=grupuri|other=de grupuri} · corelație comună %@',
    ' · %d {one=GRUP ELIMINAT|few=GRUPURI ELIMINATE|other=DE GRUPURI ELIMINATE}',
    'Acest tabel nu are nicio coloană de text după care să grupeze.',
    'Acest tabel nu are nicio coloană numerică de exploatat.',
    'S-au marcat %1$d {one=rând|few=rânduri|other=de rânduri} ale grupului „%2$@”',
    'CSV: minerit pe grupuri…',
    '↔',
    'Prognoză',
    'Coloana de valori în timp',
    'Modelul de prognoză',
    'Numărul de perioade de prognozat',
    'Verdictul față de modelele de referință',
    'Model:',
    'Perioade:',
    'Sezon:',
    'automat',
    'Perioada sezonieră; lăsați gol pentru detectare automată',
    'Tabelul valorilor prognozate',
    'Perioadă',
    'Banda de 80%',
    'Banda de 95%',
    'MAE %@ · MAPE %@',
    'nu se poate calcula',
    'Acest tabel nu are nicio coloană numerică de prognozat.',
    'Nu s-a putut construi o prognoză pentru această coloană.',
    'Coloana „%1$@” are doar %2$d {one=valoare numerică|few=valori numerice|other=de valori numerice} — pentru prognoză sunt necesare cel puțin 4.',
    '# Seria se citește în ordinea rândurilor din fișier — fără resortare și fără a deduce o coloană de timp.\n',
    'Eroare de antrenare',
    'CSV: prognoză de serie temporală…',
    'Holt-Winters aditiv',
    'Holt-Winters multiplicativ',
    'naiv sezonier',
    'naiv',
    'Coloanele introduse în grupare',
    'Curba WCSS',
    'Grupă',
    'Scalare:',
    'k:',
    'eps:',
    'minPts:',
    'Selectați cel puțin o coloană.',
    'Nu sunt destule date pentru a construi curba.',
    'Cotul sugerează k = %d. WCSS scade ÎNTOTDEAUNA pe măsură ce k crește, deci aceasta este o regulă de citire a graficului, nu un criteriu statistic — uitați-vă la curbă și judecați dacă îndoitura este clară.',
    'WCSS în funcție de k',
    'Distanța-k sugerează eps = %1$@ (minPts este implicit 2 × numărul de coloane = %2$d). %3$@',
    'Distanța până la al k-lea vecin',
    'Pentru grupare sunt necesare cel puțin 2 coloane numerice.',
    'Grupe după %@ și %@',
    ' — grupele au fost găsite în %d {one=dimensiune|few=dimensiuni|other=de dimensiuni}; graficul arată doar primele 2',
    '# zgomot (cluster_id = -1): %d {one=rând|few=rânduri|other=de rânduri}\n',
    'CSV: grupare…',
    '# --- Centrele grupelor (unități originale) ---\n',
    'k-medii',
    'DBSCAN',
    'Matricea de corelație',
    'Metoda de corelație',
    'Corelația nu înseamnă cauzalitate.',
    'Cea mai puternică pereche: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Apăsați pe o celulă pentru un grafic de dispersie.',
    'Nicio pereche nu a putut fi măsurată.',
    '%1$@ ↔ %2$@: %3$@ pe %4$d {one=rând|few=rânduri|other=de rânduri}',
    'Pentru corelație sunt necesare cel puțin 2 coloane numerice.',
    'Coloana „%@” nu a putut fi citită.',
    'CSV: matricea de corelație…',
    'Anomalii',
    'Lista anomaliilor',
    'Coloană:',
    'Coloana numerică de examinat',
    'Metodă:',
    'Metoda de detectare',
    'Metoda folosită',
    'Prag',
    'Marchează',
    'Exportă într-o filă nouă',
    'Linie',
    'Scor',
    'De ce',
    'ușoară',
    'moderată',
    'severă',
    'scor z',
    'IQR',
    'MAD',
    '%1$d / %2$d {one=rând|few=rânduri|other=de rânduri} (%3$.2f%%)',
    'Acest tabel nu are nicio coloană numerică de scanat pentru anomalii.',
    'S-au marcat %d {one=linie anormală|few=linii anormale|other=de linii anormale}',
    'CSV: caută anomalii…',
    '%1$d {one=regulă, TRECUTĂ|few=reguli, toate TRECUTE|other=de reguli, toate TRECUTE} · %2$d {one=rând|few=rânduri|other=de rânduri} · %3$.0f ms',
    '%1$d {one=eroare|few=erori|other=de erori} · %2$d {one=avertisment|few=avertismente|other=de avertismente} în %3$d {one=regulă|few=reguli|other=de reguli} · %4$d {one=rând|few=rânduri|other=de rânduri} · %5$.0f ms',
    'Salvați mai întâi documentul — regulile de calitate stau lângă fișierul de date.',
    'Niciun set de reguli încă. Creați %@ și redeschideți.',
    'Istoric',
    'Interogări salvate',
    'Salvează această interogare…',
    'Salvează interogarea',
    'Dați-i un nume ca să o găsiți mai târziu. Același nume suprascrie.',
    'De exemplu: Venituri pe județe',
    'Nu ați introdus nicio valoare pentru parametrul: %@',
    'Modulul s-a schimbat de când l-ați aprobat — GEditor refuză să îl ruleze',
    'Rulați un modul neaprobat?',
    'Am încredere în acest fișier — rulează-l',
    'NESEMNAT',
    'Semnătură: %@',
    'Cale: %@',
    'Înlocuiește',
    'Înlocuiește tot',
    'Text simplu',
    'Extins (\\n \\t \\xNN)',
    'Expresie regulată',
    'Ține cont de majuscule',
    'Cuvânt întreg',
    'Niciun rezultat',
    'Testează expresia regulată…',
    'Mod jurnal (culoare după nivel)',
    'Filtrează jurnalul după nivel…',
    'Rulează pe tot dosarul…',
    'Filtrează printr-o comandă…',
    'Scripturi…',
    'Pachete de extensii…',
    'Fereastră nouă',
    'Mută fila într-o fereastră nouă',
    'Niciun dosar deschis',
    'Caută un fișier în dosar',
    'Filtrează după nume',
    'Fișier nou…',
    'Dosar nou…',
    'Redenumește…',
    'Mută la Coș',
    'Arată în Finder',
    'Se citește structura documentului…',
    'nicio funcție în acest fișier',
    'Nimic nu se potrivește',
    'Text simplu',
    '🔒 Doar citire',
    'Se urmărește',
    'încadrare la coloana',
    'Sintaxă',
    'Apăsați pentru a insera în câmpul de interogare',
    'interogare nevalidă',
    'cheia `ten` de la rădăcină',
    'cheie care conține un spațiu',
    'primul element',
    'fiecare element',
    'felie',
    'reuniune de indici',
    'fiecare cheie `gia` la orice adâncime',
    'fiecare nod',
    'filtrare după număr',
    'filtrare după prezență',
    'Mergi la prima problemă',
    'Coloana doanh_thu este numerică',
    'filtrează…',
    'Renunță',
    'Înlocuiește',
    'previzualizare',
    'interactiv',
    'Editare',
    'Aspect',
    'Scurtături de tastatură',
    'Mărimea fontului',
    'Lățimea tabului',
    'Indentare cu taburi',
    'Indentare automată pe linie nouă',
    'Evidențiază toate rezultatele căutării',
    'Normalizează la NFC la salvare',
    'Limbă',
    'Fundal',
    'Ca sistemul',
    'Luminos',
    'Întunecat',
    'Temă',
    'Folosește presetarea Notepad++',
    'Revino la tastele implicite',
    'Deschide fișierul de configurare',
    'Exportă tema curentă',
    'Schimbarea limbii se aplică pe deplin la următoarea pornire a aplicației.',
    'Tastele implicite revin la următoarea pornire a aplicației.',
    'Previzualizare Markdown',
    'Randat cu motorul Markdown al sistemului: tabelele și colorarea blocurilor de cod nu sunt încă acceptate.',
    'Testarea expresiilor regulate',
    'Expresie',
    'Text de probă',
    'Rezultate',
    'Rezultatele potrivirii',
    'Ce face această expresie',
    'Explicația expresiei',
    'Mod de căutare',
    'Rezultatele căutării',
    'Nicio potrivire',
    ' (trunchiat)',
    'Harta documentului',
    'Bara de file',
    'Rândul de antet al coloanelor',
    'Nicio coloană',
    'Arborele de fișiere al spațiului de lucru',
    'Lista de funcții și clase',
    'Rezultatele căutării în dosar',
    'Tabel de date CSV',
    'Banc de curățare a datelor',
    'Interogare JSONPath',
    'Lista problemelor de date',
    'Set de aur…',
    'Compară cu scoruri externe (JSONL)…',
    'Alegeți fișierul de scoruri externe (JSONL: query, chunk_id, score)',
    'Redenumește nodul selectat',
    'Contopește nodurile selectate',
    'Împarte nodul selectat',
    'Extrage subgraful selectat într-o filă nouă',
    'Nimic de schimbat',
    '%1$@ — aplicați %2$d {one=modificare|few=modificări|other=de modificări}?',
    '%1$@: %2$d {one=modificare|few=modificări|other=de modificări} · Cmd-Z anulează întreg setul',
    'Puneți cursorul pe EXACT UN nod, apoi rulați din nou',
    'Redenumește „%@”',
    'Fiecare muchie și etichetă care trimite la acest nod se schimbă odată cu el.',
    'Redenumește nodul',
    'Selectați DOUĂ sau mai multe noduri, apoi rulați din nou',
    'Forma canonică „%@” — cea mai frecventă, cea mai lungă, cu diacritice',
    'Contopește nodurile',
    'Selectați LINIILE DE MUCHII de mutat, apoi rulați din nou',
    'Fiecare linie selectată trebuie să atingă EXACT UN nod comun — selectați mai multe linii de muchii',
    'Împarte „%1$@” — mută %2$d {one=muchie|few=muchii|other=de muchii}',
    'Muchii spre: %@',
    'Împarte nodul',
    'Document nesalvat — fișierul extras are nevoie de un loc lângă care să stea',
    'Selectați partea de graf de extras, apoi rulați din nou',
    'Grupează variantele de entități → tabel de verificare',
    'Aplică tabelul de verificare editat',
    'Document nesalvat — tabelul de verificare trebuie să stea lângă fișierul grafului',
    'Nicio variantă de grupat',
    '%d {one=grup de variante|few=grupuri de variante|other=de grupuri de variante} — editați coloana „canonical”, apoi rulați „Aplică”',
    'Nu există încă tabelul de verificare „%@” — rulați mai întâi „Grupează variantele de entități”',
    'Tabelul de verificare nu a putut fi citit: %@',
    'Tabelul de verificare nu are niciun rând de schimbat',
    'Nimic din graf nu se potrivește cu tabelul de verificare',
    'Grupează variantele de entități',
    'S-au aplicat %d {one=modificare|few=modificări|other=de modificări} · tabelul de alias-uri și lista de marcaje au fost scrise lângă fișier',
    'Aplicați %d {one=modificare|few=modificări|other=de modificări} asupra grafului?',
    '%d {one=alias|few=alias-uri|other=de alias-uri} → formă canonică.',
    'CONTOPEȘTE noduri (nu se poate anula prin retastare):',
    '%d {one=alias nu se află|few=alias-uri nu se află|other=de alias-uri nu se află} în graf și au fost sărite.',
    'GraphRAG…',
    'Acoperire fragment ↔ entitate',
    'Exportă pachetul de context (JSONL)',
    'Acoperire fragment ↔ entitate ↔ graf',
    '- %1$d {one=entitate|few=entități|other=de entități} · %2$d {one=fragment|few=fragmente|other=de fragmente} · %3$.0f%% dintre entități sunt menționate · %4$.0f%% dintre fragmente conțin o entitate',
    'Entități pe care niciun fragment nu le menționează',
    'Fragmente orfane (fără nicio entitate înăuntru)',
    'Noduri de graf fără entitate corespunzătoare',
    'niciuna',
    'Metodă',
    'Nu s-a putut construi corespondența fragment ↔ entitate',
    'Punctează sănătatea grafului',
    'sănătatea grafului',
    'Sănătate %1$@/100 · %2$d {one=problemă|few=probleme|other=de probleme} · %3$d {one=insulă|few=insule|other=de insule} · %4$d izolate',
    'Hibrid cu graful',
    'α = 1: semnalul grafului este complet oprit, rezultatele coincid cu BM25 simplu',
    'α mare: graful doar ajustează ușor clasamentul BM25',
    'α aproape de valoarea implicită 0,7: BM25 conduce, graful ajustează',
    'α mic: graful conduce, BM25 doar departajează',
    'α = 0: doar semnalul grafului; fragmentele fără entități sunt toate la egalitate',
    'Document nesalvat — hibridul are nevoie de un fișier de graf lângă corpus',
    'Niciun fișier de graf „%@” — hibridul are nevoie de el ca să aibă vreun semnal',
    'hibrid %.1f ms · %@',
    'Algoritm…',
    'PageRank (grosimea conturului)',
    'Comunități (culoarea de umplere)',
    'Componente conexe',
    'Exportă tabelul de noduri într-o filă nouă',
    '%1$d {one=componentă|few=componente|other=de componente} · cea mai mare %2$d {one=nod|few=noduri|other=de noduri} · %3$d izolate',
    'Acest document nu este un graf DOT',
    'Tabelele de noduri/muchii nu au putut fi construite: %@',
    '%d {one=rând|few=rânduri|other=de rânduri} · %@',
    'Etichetă',
    'Notă (opțional)',
    'Salvează înregistrarea',
    'Exportă CSV',
    'Document nesalvat — setul de evaluare trebuie să stea lângă fișierul corpusului',
    'Setul de evaluare nu a putut fi încărcat: %@',
    'Nu s-a putut salva: %@',
    'Setul de evaluare nu are încă nicio înregistrare',
    'Nu s-a putut scrie: %@',
    'Acest document nu este un fișier .mmd, nu este DOT și nu are niciun bloc mermaid.',
    '%d {one=nod|few=noduri|other=de noduri} · %d {one=muchie|few=muchii|other=de muchii} · ⚠ %@',
    'Diagramă Mermaid: adaugă un element…',
    'Diagramă Mermaid: leagă cele două elemente selectate',
    'Diagramă Mermaid: modifică eticheta elementului selectat…',
    'Diagramă Mermaid: șterge elementul selectat',
    'Diagramă Mermaid: mută mesajul în sus',
    'Diagramă Mermaid: mută mesajul în jos',
    'Adaugă un element',
    'Adaugă un participant',
    'Adaugă o intrare',
    'Adaugă o intrare în diagramă',
    'Modifică o intrare din diagramă',
    'Șterge o intrare din diagramă',
    'Șterge elementul',
    'Modifică eticheta',
    'Reordonează mesajul',
    'Numele intrării',
    'Intrare nouă',
    'Numele intrării afișat pe diagramă.',
    'Tabelul de proprietăți al diagramei',
    'Acest document nu are niciun bloc mermaid',
    'Identificatorul din sursa diagramei — fără spații. Eticheta se modifică mai târziu cu dublu clic.',
    'Lăsați gol pentru a afișa chiar identificatorul.',
    'Se schimbă doar ETICHETA afișată; identificatorul elementului rămâne același.',
    'Nu se poate spune care element este „%@”',
    'Selectați EXACT DOUĂ elemente, apoi rulați din nou',
    'Puneți cursorul pe EXACT UN element, apoi rulați din nou',
    'Selectați UN element de șters sau două elemente unite printr-o muchie',
    'Ștergeți „%1$@” și cele %2$d {one=muchie care îl atinge|few=muchii care îl ating|other=de muchii care îl ating}?',
    'Nodurile de la celălalt capăt al acelor muchii se păstrează — sunt redeclarate cu etichetele lor dacă instrucțiunea de muchie era singurul loc care le declara.',
    'Diagrama „%1$@” se editează doar ca text — %2$@',
    '%@: trageți între două elemente pentru a le lega, dublu clic pentru a modifica o etichetă',
    '%@: trageți între doi participanți pentru a adăuga un mesaj; ordinea se schimbă din meniul Unelte',
    '%@: editați în tabelul de proprietăți de mai jos',
    'Editarea vizuală este pornită',
    '%1$@ · %2$d {one=intrare|few=intrări|other=de intrări} — editați pe loc; fiecare celulă este un pas de anulare',
    'Pentru pie, un număr; pentru gantt, tot ce urmează după două puncte.',
    'Diagramă Mermaid: scoate blocul într-un fișier .mmd…',
    'Diagramă Mermaid: încorporează înapoi fișierul referit',
    'Scoate blocul diagramei',
    'Încorporează blocul diagramei',
    'Scoate blocul diagramei în fișierul lui propriu',
    'Fișierul stă LÂNGĂ document; blocul păstrează o referință de o linie, ca editarea să se facă într-un singur loc.',
    'Document nesalvat — fișierul diagramei are nevoie de un loc lângă care să stea',
    'Fișierul „%@” există deja — alegeți alt nume',
    'S-a scos în „%@” — blocul a păstrat o referință de o linie',
    'Deschide fișierul',
    '„%@” a fost încorporat înapoi; fișierul rămâne pe disc',
    'Acest bloc conține o diagramă adevărată, nu o referință',
    'Acest bloc trimite la „%@” — deschideți acel fișier ca să îl editați',
    'Fișierul diagramei nu a putut fi citit: %@',
    'Editare vizuală',
    'Trageți de la un nod la altul pentru a adăuga o muchie; dublu clic pentru a modifica o etichetă. Fiecare acțiune este un pas de anulare.',
    'Editare vizuală: trageți între două noduri pentru a adăuga o muchie, dublu clic pentru a modifica o etichetă',
    'Editarea vizuală este oprită',
    'Adaugă un nod…',
    'Adaugă o muchie între cele două noduri selectate…',
    'Modifică eticheta nodului selectat…',
    'Șterge nodul sau muchia selectată',
    'Adaugă un nod',
    'Adaugă o muchie',
    'Modifică eticheta nodului',
    'Șterge nodul',
    'Șterge muchia',
    'Cmd-Z anulează',
    'Documentul este doar pentru citire',
    'Eticheta lui „%@”',
    'Se schimbă doar ETICHETA afișată; identificatorul nodului rămâne același.',
    'Nu se poate spune care nod este „%@”',
    'Identificatorul nodului din fișierul DOT. Eticheta se modifică mai târziu cu dublu clic pe diagramă.',
    'Selectați EXACT DOUĂ noduri, apoi rulați din nou',
    'Selectați UN nod ca să ștergeți un nod sau două noduri unite printr-o muchie',
    'Ștergeți nodul „%1$@” și cele %2$d {one=muchie care îl atinge|few=muchii care îl ating|other=de muchii care îl ating}?',
    'Dacă rămân muchii suspendate, DOT recreează nodul chiar din ele — nodul tocmai șters ar reapărea la următoarea randare.',
    'Laborator de regăsire BM25',
    'Întrebare — apăsați Return pentru a căuta',
    'Evaluează…',
    'Se construiește indexul',
    'Niciun fragment nu se potrivește',
    'rezultate din',
    'k1 = 0: fiecare termen contează O SINGURĂ dată, oricât de des ar apărea',
    'k1 mic: repetarea unui termen aproape că nu adaugă nimic',
    'k1 aproape de valoarea implicită 1,2: repetările adaugă punctaj, dar tot mai puțin',
    'k1 mare: fragmentele care repetă un termen sunt răsplătite puternic',
    'b = 0: lungimea este ignorată, fragmentele lungi nu sunt penalizate',
    'b mic: fragmentele lungi sunt penalizate doar ușor',
    'b aproape de valoarea implicită 0,75: fragmentele lungi sunt penalizate moderat',
    'b = 1: penalizare maximă pentru lungime, fragmentele scurte sunt favorizate',
    'JSONL: laborator de regăsire…',
    'Document nesalvat — indexul BM25 stă lângă fișierul corpusului, deci are nevoie de o cale',
    'Acest fișier nu este JSONL — Laboratorul de regăsire lucrează pe corpusuri de fragmente',
    'Nu s-a putut construi un index BM25 pentru acest fișier',
    'Document nesalvat — este nevoie de o cale de corpus pentru a genera raportul',
    'Alegeți un set de evaluare (CSV sau JSONL: întrebare + id-urile fragmentelor așteptate)',
    'Evaluarea regăsirii',
    'Schimbați k1, b sau k mai sus și randați din nou pentru a compara două configurații; adăugați un bloc „compare” ca să rulați două seturi de parametri alături pe același set de evaluare.',
    'Erori',
    '   (%1$d…%2$d, medie %3$.0f)',
    'Mod JSONL',
    'Înregistrare',
    'Detaliu',
    'Înregistrarea de la linia',
    'nu este JSON valid',
    'înregistrări',
    'linii goale',
    'nu sunt obiecte',
    'tabelul arată',
    'ANULAT PE PARCURS',
    'Fără filtru',
    'înregistrări se potrivesc cu filtrul',
    'Mutați cursorul pe o linie ca să îi vedeți înregistrarea',
    'Nicio înregistrare deformată',
    'Neinspectat încă. Rulați „JSONL: inspectează fragmentele” după ce se termină verificarea.',
    'câmp de text',
    'SCHEMĂ (o presupunere — alegeți alt câmp ca să o schimbați)',
    'text',
    'identificator',
    'metadate imbricate',
    'CÂMPURI',
    'prezent în',
    'tipuri amestecate',
    'LUNGIME — caractere',
    'LUNGIME — cuvinte',
    'LUNGIME — jetoane estimate',
    'GOALE ȘI DUPLICATE',
    'fragmente goale',
    'linii',
    'grupuri de duplicate exacte',
    'linii ilizibile, lăsate în afara statisticilor',
    'METODĂ',
    '„caracterele” numără scalari Unicode, nu grupuri de afișare',
    '„cuvintele” se despart la spațiile ASCII',
    '„jetoanele” folosesc segmentatorul de silabe — NU pe cel al modelului',
    '„duplicat” înseamnă EXACT; cele APROAPE identice stau în blocul ```quality',
    'fragmente',
    'JSONL: verifică și inspectează fragmentele…',
    'Imagine',
    'PDF',
    'Document Word',
    'Foaie de calcul Excel',
    'Prezentare PowerPoint',
    'Arhivă',
    'Încadrează',
    'Copiază imaginea',
    'Rotește',
    'Imaginea „%@” nu poate fi citită',
    'Imaginea a fost copiată în clipboard',
    'Evidențiază',
    'Subliniază',
    'Notă…',
    'Șterge adnotările',
    'Extrage textul într-o filă nouă',
    'Salvează copia adnotată…',
    'Caută în PDF',
    'Adaugă',
    'Pagina %d din %d',
    'Pagina %d',
    'Potrivirea %d din %d',
    'Nicio potrivire',
    'PDF-ul „%@” nu poate fi citit',
    'Acest PDF este protejat cu parolă — conținutul lui nu poate fi deschis',
    '„%@” nu se află în acest document',
    'Evidențiat',
    'Subliniat',
    'Selectați mai întâi un text',
    'Nota a fost adăugată',
    'Această pagină nu are adnotări',
    'S-au eliminat %d {one=adnotare|few=adnotări|other=de adnotări} de pe această pagină',
    'Acest PDF nu are strat de text — cel mai probabil este o scanare',
    'Fișierul nu poate fi scris',
    'Fișierul tocmai scris NU se redeschide corect — nu folosiți această copie',
    'S-a salvat %1$@ · %2$d {one=pagină|few=pagini|other=de pagini}',
    'Nume',
    'Mărime',
    'Comprimat',
    'Raport',
    'Modificat',
    'Deschide intrarea selectată',
    'Extrage într-un dosar…',
    'Extrage aici',
    '%d {one=intrare|few=intrări|other=de intrări}',
    'se extinde la %@',
    '— un fișier Office este o arhivă; acestea sunt părțile din interiorul lui',
    'S-au extras %d {one=intrare|few=intrări|other=de intrări}',
    '%d {one=intrare a eșuat|few=intrări au eșuat|other=de intrări au eșuat}',
    '%d {one=intrare a fost REFUZATĂ|few=intrări au fost REFUZATE|other=de intrări au fost REFUZATE} — căile lor ies din dosarul de destinație',
    'Această intrare nu poate fi deschisă',
    'Încă nu se poate scrie înapoi într-un %@ — folosiți „Salvează ca…”',
    'Nu s-a schimbat nimic',
    'S-au scris %1$d {one=celulă|few=celule|other=de celule} în %2$@',
    'S-au scris %1$d {one=paragraf|few=paragrafe|other=de paragrafe} în %2$@',
    'Nu s-a putut scrie în fișier — originalul este neatins',
    'pregătirea cazului de test',
    'settings.json nu poate fi scris',
    'Rotește la stânga',
    'Rotește la dreapta',
    'Mută pagina în sus',
    'Mută pagina în jos',
    'Șterge pagini…',
    'Șterge pagini',
    'Extrage pagini…',
    'Extrage paginile într-un fișier nou',
    'Îmbină fișier PDF…',
    'Împarte fișierul…',
    'Împarte fișierul PDF',
    'Exportă imagini…',
    'Exportă paginile ca imagini PNG',
    'Anulează modificarea paginii',
    'Salvează copia modificată…',
    'Redă',
    'Pauză',
    'Vizualizare normală',
    'Alege foaia',
    'Deschide foaia',
    'Renunță și schimbă foaia',
    'Registrul are %d foi.',
    'Acest registru are o singură foaie: „%@”',
    'Renunțați la modificările nesalvate din această foaie?',
    'Schimbarea foii înlocuiește toată fila. Ce nu a fost salvat cu ⌘S se pierde.',
    'Alege fișierul PDF de îmbinat',
    'Alege dosarul pentru imagini',
    'Alege unde se salvează. Al doilea fișier se scrie lângă acesta.',
    'Documentul are %d pagini. Introdu paginile de șters, ex. 2-4,7',
    'Documentul are %d pagini. Introdu paginile de extras, ex. 1-3,8',
    'Documentul are %d pagini. Introdu paginile de exportat, ex. 1-3',
    'Documentul are %d pagini. Introdu partea de separat, ex. 1-5; restul devine al doilea fișier.',
    'Pagina %d a fost rotită',
    'Paginile %@ au fost șterse · au rămas %d pagini',
    '%d pagini îmbinate din „%@”',
    'Împărțit în %@ (%d pagini) și %@ (%d pagini)',
    'S-a scris %@ — %@ · %d pagini',
    '%d imagini exportate în %@',
    'Doar %d din %d imagini au fost exportate',
    'S-a anulat o operație de pagină',
    'Nu mai există operații de pagină de anulat',
    'Nu se pot șterge TOATE paginile — un PDF trebuie să aibă cel puțin una',
    'Acel interval este tot documentul — nu e nimic de separat',
    '„%@” este protejat cu parolă — nu se poate îmbina',
    '„%@” nu are pagini',
    'Deja la prima pagină',
    'Deja la ultima pagină',
    '· modificat, nesalvat',
    'Imagine animată · %d cadre',
    'Document nesalvat — nu există fișier pe disc pentru vizualizare binară',
    'Această comandă funcționează doar cu registre Excel',
    'Lista de foi nu a putut fi citită',
    'Nu există foaia „%@”',
    'Foaia „%@” nu a putut fi citită',
    'Foaia „%@” · %d rânduri',
    'restul',
    'Notă',
    'Atenție',
    'Vezi și',
    'Copiază',
    'Copiat',
    'Copiază codul exemplu',
    'Caută în ajutor',
    'Înapoi',
    'Începe',
    'Nu afișa această fereastră la pornire',
    'Ajutorul nu este încă tradus în această limbă — se afișează textul vietnamez.',
    'Mergi la offset (ex. 1F400 sau 0x1F400)',
    'Copiază rândurile selectate',
    '%d rânduri copiate',
    '„%@” nu a putut fi citit',
    'Fișier gol',
    'Offsetul „%@” nu a putut fi citit',
    'Offsetul 0x%@ depășește dimensiunea fișierului',
    'Deschide cu altă aplicație…',
    '%d canale',
    '„%@” nu poate fi redat',
    'Nu poate fi redat — %@',
    'macOS nu are decodor integrat pentru formatul %@ — este o limită a sistemului, nu un fișier corupt.',
    'Poți vedea în continuare octeții în mod binar sau îl poți deschide cu o aplicație cu decodor propriu.',
    'Semnează…',
    'Editează textul…',
    'Editează textul',
    'Desenează deasupra',
    'Următorul câmp gol',
    'Șterge valorile completate',
    'Acest fișier nu are câmpuri de formular',
    '%d câmpuri de formular șterse',
    'Toate câmpurile de formular sunt deja completate',
    'Au rămas %d câmpuri goale',
    'Formular completabil: %d câmpuri. Scrie direct, apoi „Salvează copia modificată…”',
    'Alege o imagine cu semnătura (fundal transparent arată cel mai bine)',
    'Pagina semnată nu a putut fi creată',
    'Semnătura a fost inserată la pagina %d',
    'Selectează mai întâi textul de modificat',
    'Selecția este prea mică',
    'Textul nou este DESENAT PESTE selecție cu fontul sistemului. Textul vechi este acoperit, nu șters — poate fi extras în continuare, deci nu este redactare.',
    'Pagina modificată nu a putut fi creată',
    'Textul nou a fost desenat peste pagina %d',
    'Comută Vizualizare / Cod',
    'Încă nu există vizualizare arbore pentru JSON · XML · YAML',
    'Încă nu există vizualizare diagramă în filă',
    'Încă nu există vizualizare schiță pentru PowerPoint',
    'Acest fișier are un singur mod de afișare',
    '%d noduri',
    'Arborele nu a putut fi construit: %@',
    'Documentul este prea mare pentru arbore — folosește modul Cod',
]
