# Bản dịch sv — một phần tử cho mỗi khoá, đúng thứ tự bảng tiếng Anh.
# Sinh tệp Swift: python3 scripts/gen-language.py --code sv --name "…" scripts/ban-dich/sv.py
VALS = [
    'Sparade versioner…',
    'Det här dokumentet har aldrig sparats — ingen historik',
    'Inga tidigare sparade versioner',
    'Det går inte att läsa den versionen',
    'Återställ den sparade versionen',
    'XML: validera mot DTD/XSD…',
    'Den här Mac-datorn saknar libxml2, så XSD-validering är inte tillgänglig.',
    'Välj ett XSD-schema att validera mot',
    'Giltig enligt',
    'Tillägget avslutades utan att ändra något',
    'Inga inbyggda tillägg är installerade',
    'Ta bort det här tillägget',
    'Ta bort det här tillägget?',
    'Ta bort',
    'Installera ett inbyggt tillägg…',
    'Öppna tilläggsmappen',
    'Välj tilläggets .dylib-fil',
    'Installerat:',
    'Borttaget:',
    'Inbyggda tillägg…',
    'Endast .dylib-filer godtas.',
    'Ett tillägg med samma namn är redan installerat:',
    'Det går inte att kopiera tillägget:',
    'Inbyggda tillägg finns bara i den direkta hämtningen, inte i App Store-versionen.',
    'Hjälpprocessen för tillägg hittades inte.',
    'Det går inte att starta hjälpprocessen:',
    'Tilläggets process stannade halvvägs.',
    'Tillägget svarade inte i tid — det stoppades.',
    'Tillägget svarade med ett felformat meddelande:',
    'Tillägget rapporterade ett fel:',
    'Om GEditor',
    'Inställningar…',
    'Avsluta GEditor',
    'Arkiv',
    'Ny flik',
    'Stäng fliken',
    'Nästa flik',
    'Föregående flik',
    'Nytt dokument',
    'Öppna…',
    'Öppna en mapp som arbetsyta…',
    'Öppna senaste',
    'Spara',
    'Spara som…',
    'Ta bort blanksteg i radslut vid sparande',
    'Följ filen (tail -f)',
    'Skriv ut…',
    'Öppna den stängda fliken igen',
    'Inga filer',
    'Töm listan',
    'Redigera',
    'Ångra',
    'Gör om',
    'Klipp ut',
    'Kopiera',
    'Klistra in',
    'Urklippshistorik…',
    'Kolumnredigerare…',
    'Markera nästa träff',
    'Markera allt',
    'Duplicera raden',
    'Radera raden',
    'Kommentera bort raden',
    'Inget har kopierats i den här sessionen',
    'Rensa historiken',
    'Sök',
    'Sök…',
    'Sök och ersätt…',
    'Sök i en mapp…',
    'Ersätt i en mapp…',
    'Nästa träff',
    'Föregående träff',
    'Gå till rad…',
    'Gå till matchande parentes',
    'Markera alla matchande rader…',
    'Invertera markeringarna',
    'Ta bort alla markeringar',
    'Kopiera markerade rader',
    'Radera markerade rader',
    'Behåll bara markerade rader',
    'Rader',
    'Sortera A→Ö',
    'Sortera Ö→A',
    'Naturlig sortering',
    'Ta bort dubbletter',
    'Vänd radordningen',
    'Flytta raden uppåt',
    'Flytta raden nedåt',
    'Slå ihop rader',
    'Dela rader efter längd…',
    'Dela rader efter tecken…',
    'Radera tomma rader',
    'Slå ihop rader av tomma rader',
    'Ta bort blanksteg i radslut',
    'Tabb → mellanslag',
    'Mellanslag → tabb',
    'VERSALER',
    'gemener',
    'Stor Bokstav I Varje Ord',
    'Stor bokstav i meningens början',
    'vÄND gEMENER/vERSALER',
    'camelCase',
    'snake_case',
    'kebab-case',
    'CSV',
    'CSV: välj blad…',
    'Växla mellan tabell- och textvy',
    'Radera kolumn…',
    'Validera data (antal kolumner · typer)',
    'Arbetsbänk för datarensning…',
    'Kör ett rensningsrecept…',
    'Konvertera…',
    'Byt avgränsare…',
    'Exportera till JSON…',
    'Format',
    'Teckenkodning…',
    'Radslut…',
    'Normalisera Unicode…',
    'JSON: formatera',
    'JSON: pressa ihop till en rad',
    'JSON: sortera nycklar',
    'JSON: JSONPath-fråga…',
    'CSV: SQL-fråga…',
    'SQL-fråga',
    'Kör…',
    'Exportera till en ny flik',
    'Tomt dokument — ingen tabell att fråga',
    'Ingen CSV-tabell — första raden har bara en kolumn',
    'Det går inte att läsa frågan',
    'Det går inte att kontrollera frågan',
    'Gul (standard)',
    'Blå',
    'Grön',
    'Ockra',
    'Lila',
    'Rosa',
    'Turkos',
    'Orange',
    'Skiffer',
    'Text',
    'Talserie',
    'Datumserie',
    'VERSALER (hexadecimalt)',
    'Början',
    'Steg',
    'Fyll ut med nollor till',
    'Bas',
    'Första datum',
    'Format',
    'Infoga',
    'Avbryt',
    'Konvertera formatet',
    'Förhandsvisa de 5 första raderna',
    'Öppna i en ny flik',
    'Spara till en fil…',
    'Resultatet öppnas i en ny, osparad flik. Ursprungsdokumentet lämnas orört.',
    'Kör på det här dokumentet',
    'Kör på en mapp…',
    'Hela receptet är ETT ångra-steg. Filen på hårddisken lämnas orörd tills du sparar.',
    'av',
    'kolumnen hittades inte',
    'klar',
    'den fortsätter att uppta en processorkärna tills appen avslutas.',
    'Skriptet returnerade ingenting',
    'Det går inte att skapa JavaScript-motorn',
    'Okänt JavaScript-fel',
    'Tabell',
    'Tillämpa sorteringen på filen',
    'Konvertera ▾',
    'Exportera matchande rader',
    'Dölj den här kolumnen',
    'Byt namn på rubriken…',
    'Infoga en tom kolumn till vänster',
    'Infoga en tom kolumn till höger',
    'Radera den här kolumnen ur filen…',
    'Minst en kolumn måste förbli synlig',
    'Sorterar…',
    'Tillbaka till ordningen i filen',
    'de första hundra raderna',
    'välja kolumner',
    'namnge en resultatkolumn',
    'filtrera på text',
    'tomma celler',
    'kombinera villkor',
    'räkna rader',
    'gruppera och sammanfatta',
    'minimum, maximum',
    'sortera och begränsa',
    'kolumnnamn med mellanslag',
    'Frågan avbröts',
    'Stöds inte: JOIN · underfråga · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · fönsterfunktioner',
    'XML: formatera',
    'XML: pressa ihop till en rad',
    'XML: kontrollera syntaxen',
    'YAML: kontrollera dubblerade nycklar och indrag',
    'Visa',
    'Visa/dölj sidofältet (funktionslistan)',
    'Visa/dölj dokumentkartan',
    'Fäll ihop / fäll ut blocket vid markören',
    'Fäll ihop allt',
    'Fäll ut allt',
    'Fäll ihop efter nivå',
    'Nivå %d',
    '%1$d {one=block ihopfällt|other=block ihopfällda} på nivå %2$d',
    'Det här dokumentet är bara %d {one=nivå|other=nivåer} djupt',
    'mermaid: manifestet går inte att läsa',
    'Sök efter uppdateringar…',
    'Sök efter uppdateringar',
    'App Store-versioner uppdateras via Mac App Store, inte via GEditor.',
    'Det här bygget saknar signeringsnyckel för uppdateringar och kan därför inte söka efter dem.',
    'Förstora texten',
    'Förminska texten',
    'Verklig storlek',
    'Dela lodrätt',
    'Dela vågrätt',
    'Stäng delningen',
    'Öppna den här fliken i den andra rutan',
    'Gå till den andra rutan',
    'Radbrytning (av / fönster / kolumn)',
    'Bryt vid kolumn…',
    'Markera den här raden',
    'Nästa markering',
    'Föregående markering',
    'Färg på markeringar…',
    'Visa alla osynliga tecken',
    '  Mellanslag',
    '  Tabbar',
    '  Radslut',
    '  NBSP · nollbredd · styrtecken',
    'Binärvy',
    'CSV-läge (kolumner i färg)',
    'Makro',
    'Starta / stoppa inspelningen',
    'Spela upp',
    'Spela upp flera gånger…',
    'Spela upp till dokumentets slut',
    'Kör på alla flikar',
    'Avbryt makrot som körs',
    'Spara makrot…',
    'Sparade makron…',
    'Hjälp',
    'GEditor Hjälp',
    'Funktionsöversikt',
    'Byta från Notepad++',
    'Sök',
    'Ersätt med',
    'Nästa',
    'Föregående',
    'Räkna',
    'Stäng',
    'Validera mot ett JSON-schema…',
    'Välj en JSON-schemafil',
    'Inga problem hittades enligt det här schemat.',
    'JSON-schema',
    'Kontrollera grafens syntax',
    'Grafformatet kändes inte igen — det krävs ändelsen .dot, .gv, .cypher, .ttl eller .graphml.',
    'Inga %@-syntaxfel hittades (kontrollen är inte uttömmande).',
    '%@-syntax',
    'är inte ett JSON-objekt',
    'Textutvinning (n-gram, TF-IDF)',
    'Dokumentet är tomt.',
    'Inget nyckelord kunde utvinnas.',
    'Nyckelord',
    '%d {one=nyckelord|other=nyckelord} · %d {one=token|other=tokens} · %d {one=dokument|other=dokument}',
    'Markera i dokumentet',
    'Markera entiteter från en lista…',
    'Välj en entitetslista (CSV eller JSON)',
    'Det går inte att läsa entitetslistan.',
    'Entitetslistan är tom.',
    'Inga entiteter hittades i dokumentet (%d inlästa).',
    '%d {one=förekomst|other=förekomster} · %@',
    'Konvertera kunskap…',
    'Konvertering: %@ → %@',
    'Det gick inte att konvertera.',
    'Förhandsvisning av styckningen…',
    'Fast storlek 800 B, överlapp 100 B',
    'Per mening (≤ 800 B)',
    'Per Markdown-rubrik',
    'Tomt dokument — inga stycken.',
    '%d {one=stycke|other=stycken} · i snitt %d B · %@',
    'Exportera JSONL',
    'Styckenas JSONL',
    'Öppna tripplar/kanter som tabell',
    'Trippeltabell',
    'Det här dokumentet har ingen trippelrad.',
    'Ingen trippel kunde läsas — rad %d: %@',
    '%1$d {one=trippel lästes|other=tripplar lästes} · %2$d {one=felaktig rad|other=felaktiga rader} hoppades över (den första: rad %3$d)',
    'Luddiga dubbletter per kolumn…',
    'Luddiga dubbletter — kolumnen «%1$@»: %2$d {one=kandidatgrupp|other=kandidatgrupper}',
    'Slå samman',
    'Träff',
    'Värden i gruppen',
    'Slå samman till',
    'Slå samman de valda grupperna',
    'Ingen grupp är vald — att trycka på «Slå samman» ändrar INGENTING. Appen slår aldrig samman av sig själv.',
    '%d {one=grupp vald|other=grupper valda} · %d {one=rad kommer|other=rader kommer} att ändras · ETT ångra-steg',
    'Det gick inte att söka igenom den här kolumnen.',
    'Kolumnen «%@» har inga grupper med luddiga dubbletter.',
    'Ingen grupp slogs samman — dokumentet är oförändrat.',
    'Luddig dubblettrensning · kolumnen %@',
    '%d {one=grupp sammanslagen|other=grupper sammanslagna} · %d {one=cell ändrad|other=celler ändrade}',
    'Rensningsrapport',
    '# Rensningsrapport — %@\n\n',
    '## Tillämpat (%d)\n\n',
    '_Inget steg har tillämpats._\n',
    '\n## Dataprofil\n\n',
    '_%1$d {one=kolumn|other=kolumner} · %2$d {one=rad|other=rader} · genomsökt på %3$.1f s_\n\n',
    '| Kolumn | Typ | Tomma | Unika | Min | Max | Medel |\n',
    '\n### Avvikande värden\n\n',
    'rad %d: %@',
    '- kolumnen «%1$@» — %2$d {one=cell|other=celler}: %3$@\n',
    '\n## Återstår (%d)\n\n',
    '_Inga observationer kvar._\n',
    '- kolumnen «%@»: %@\n',
    None,
    'Ta bort blanksteg vid sparande',
    'Normalisera radsluten',
    'föregående',
    'Det gick inte att öppna mappen «%@» från den förra sessionen igen',
    ' (och %d {one=fil|other=filer} till)',
    'Det gick inte att öppna %d {one=flik|other=flikar} igen: %@%@ — filerna finns inte kvar på sin gamla plats.',
    'Det gick inte att läsa indata från röret',
    'Blanksteg i radslut tas bort vid varje sparande',
    'Blanksteg tas inte längre bort vid sparande',
    'Namnlös.txt',
    'Att konvertera teckenkodningen gör att tecken går förlorade',
    'Spara ändå',
    'Dokumentet har osparade ändringar',
    'Att stänga utan att spara kastar bort dem.',
    'Kasta ändringarna',
    'Gå till rad',
    'Dokumentet har %d {one=rad|other=rader}.',
    'Radnummer',
    'Gå',
    'Tolka om som…',
    'Konvertera till…',
    'Det gick inte att tolka om',
    '%@ kan inte återge alla tecken',
    'Välj ändå',
    'Kolumn %d',
    'Kolumn %d: %@',
    'Dolda kolumner: %@ (%d) — återställ dem från kontextmenyn på rubrikraden',
    'Visa igen: %@',
    'Kolumnen %@ dolde — den ligger kvar orörd i filen',
    'Sorterad efter %@ %@ · endast visning',
    'Sorterad: %@ %@ (endast visning)',
    '%d+ rader matchar — söker vidare…',
    '%d / %d {one=rad matchar|other=rader matchar}',
    'Inga problem hittades i %d {one=rad|other=rader}',
    '%d {one=rad|other=rader} med fel antal kolumner',
    '%d {one=cell|other=celler} med fel datatyp',
    ' (stannade vid de %d {one=första problemet|other=första problemen})',
    '   —   igenkända typer: ',
    'Rad %1$d, kolumnen %2$@: «%3$@» är inte %4$@',
    'Kolumnredigerare — %d {one=rad|other=rader}',
    'Observationer',
    'Dataprofil',
    'Dataprofil — söker igenom…',
    'Spara receptet…',
    'Exportera rapporten',
    'Ingen grupp har tillämpats · varje grupp är ett ångra-steg',
    'för många värden',
    'vanligast: ',
    'Värde att fylla tomma celler med',
    'Tillämpa',
    'Det gick inte att bygga en förhandsvisning',
    '· lämnat som det är, går inte att tyda ·',
    'Konvertera kolumnen till ISO 8601 (ÅÅÅÅ-MM-DD)',
    'Talkonvention för hela kolumnen',
    'Vad som ska göras med tomma celler',
    'Normalisera till ISO 8601',
    'Läs tvetydiga celler med DAGEN först (31/12)',
    'Läs tvetydiga celler med MÅNADEN först (12/31)',
    'Hoppa över tvetydiga celler, rätta bara de säkra',
    'Till vietnamesiskt/europeiskt (1.234,56)',
    'Till angloamerikanskt (1,234.56)',
    'Till angloamerikanskt, utan tusentalsavgränsare (1234.56)',
    'Fyll med ett standardvärde…',
    'Fyll nedåt — ta värdet ovanför',
    'Fyll uppåt — ta värdet nedanför',
    'Radera rader med tom cell i den här kolumnen',
    'Ta bort blanksteg i båda ändarna',
    'Ta bort i båda ändarna och pressa ihop blanksteg inuti',
    'Pivottabell…',
    'Källor…',
    'Pivottabell — gruppera efter kolumn',
    'Rader (gruppering)',
    'Värden',
    '+ Rad',
    '+ Värde',
    'Rensa allt',
    'Lägg i frågefältet',
    'Välj kolumner för att bygga frågan.',
    'Det gick inte att läsa kolumnnamnen i den här tabellen.',
    'Frågans datakällor',
    '«%@» — det öppna dokumentet',
    '  ⚠️ filen har ändrats sedan den registrerades',
    'Lägg till fil…',
    'Ta bort alla',
    'Det gick inte att härleda ett tabellnamn ur «%@» — byt namn på filen.',
    'Summa',
    'Medelvärde',
    'Min',
    'Max',
    'Antal unika',
    'Diagram',
    'Exportera PNG',
    'Exportera SVG',
    'Den här tabellen har ingen numerisk kolumn att rita.',
    'Det gick inte att bygga PNG-bilden.',
    'Frågeresultat',
    '%@ sparad',
    '%1$@-diagram för «%2$@» — %3$d {one=punkt|other=punkter}, värden från %4$@ till %5$@',
    'Stapel',
    'Linje',
    'Histogram',
    'Punkt',
    'Låda',
    'CSV: datakvalitet…',
    'Datakvalitet',
    'Exportera överträdelserna till en ny flik',
    'Nivå',
    'Regel',
    'Överträdelser',
    'Andel',
    'godkänd',
    'fel',
    'varning',
    'trasig',
    '%d {one=överträdande rad markerad|other=överträdande rader markerade}',
    'Utveckling',
    'Bedömd',
    'Rader',
    'Skillnad',
    'Underkända regler',
    'Kvalitetspoäng',
    'Poäng över tid',
    'Ingen historik ännu — varje bedömning lägger till ',
    'en rad i filen «.history.jsonl» bredvid reglerna.',
    '%d {one=punkt|other=punkter} i historiken',
    ' · %d {one=rad GÅR INTE ATT LÄSA|other=rader GÅR INTE ATT LÄSA}',
    ' · välj två rader att jämföra',
    'poäng %+.1f',
    'ingen dimension sjönk',
    'sjönk: ',
    '%d {one=nyligen underkänd regel|other=nyligen underkända regler}: %@',
    'rader %+d',
    ' (och %d {one=varning|other=varningar} till på fliken Utveckling)',
    'Ingen automatisk rättning: ',
    'Öppnar rätt verktyg i rensningsbänken och bedömer sedan om direkt.',
    'Hantera saknade värden…',
    'Normalisera datum…',
    'Ta bort dubbletter…',
    'Ersätt…',
    'Visa de felaktiga raderna',
    'Kolumnen «%@» finns inte i den här tabellen.',
    'Dubbletterna borttagna — «%@» är nu unik. Poäng: %.0f/100',
    'Dubbletterna borttagna, men «%1$@» har fortfarande %2$d {one=upprepad rad|other=upprepade rader} (tidigare: %3$d) — ',
    'de raderna delar NYCKEL men inte hela raden, så du måste titta och välja ',
    'vilken du behåller.',
    'Det gick inte att läsa något värde som bryter mot den här regeln.',
    '%1$d {one=felaktigt värde|other=felaktiga värden} i kolumnen «%2$@» — fyll i Ersätt och tryck på Förhandsvisa',
    'Bedömd på nytt: %.0f/100',
    'Förhandsvisning av rapporten',
    'Parametrar…',
    'Exportera HTML…',
    'Skriv ut / PDF…',
    '%d {one=block kördes|other=block kördes} · %d {one=block MISSLYCKADES|other=block MISSLYCKADES}',
    '%d block kördes',
    ' · FÖRÅLDRADE DATA — källfilen har ändrats; bygg om',
    'Rapportförhandsvisning kräver ett .%@-dokument',
    'Ingen datakälla hittades — deklarera «source: fil.csv» i frontmattern.',
    'Det gick inte att bygga rapporten.',
    'Den här rapporten deklarerar ingen parameter i frontmattern.',
    'Rapportparametrar',
    'Bygg om',
    '%@ exporterad',
    'Rapport: förhandsvisning',
    'Rapport: satsvis generering…',
    'är inget .greport.md-dokument',
    'det gick inte att tolka rapporten',
    'det gick inte att hitta källdata',
    'det gick inte att läsa parameterlistan',
    'Satsvis generering kräver ett .%@-dokument',
    'Välj en parameterlista (CSV eller JSON)',
    'Välj en mapp för %d {one=rapport|other=rapporter}',
    '[%d/%d] %@',
    'saknade parametrar ',
    'pekar på själva källfilen — vägrar skriva över',
    '%d block MISSLYCKADES',
    'Satsen klar: %d {one=fil|other=filer} · %d misslyckade',
    '%d {one=parameteruppsättning kunde|other=parameteruppsättningar kunde} inte byggas — se sammanfattningen',
    'Mermaid-diagram: förhandsvisning',
    'Mermaid-diagram: infoga mall…',
    'Mermaid-diagram: formatera om',
    'Genomskinlig bakgrund',
    'Den här Mac-datorn kan inte omvandla diagrammet till PNG — macOS 13 krävs. SVG-export fungerar fortfarande.',
    'Spara PNG %@…',
    'Spara SVG…',
    'Kopiera bilden till urklipp',
    'Varumärkesfärger…',
    'Varumärkesfärger för diagram',
    'Varje fält är en färg av typen #rrggbb. Sparas i «themes/mermaid-brand.json» — går att kopiera till en annan Mac.',
    'Huvudfärg',
    'Text på noder',
    'Ram',
    'Länkar',
    'Bakgrund vid export',
    'Spara och infoga %%{init}%% i dokumentet',
    'Varumärkesfärgerna sparade',
    'Diagrambilden kopierad till urklipp',
    '%@ sparad — %@',
    'Det här diagrammet har redan ett %%{init}%%-direktiv — ditt lämnas orört.',
    '%%{init}%% infogat — diagrammet bär nu sina egna färger',
    'Infoga varumärkesfärgerna i diagrammet',
    'Formatera om Mermaid-diagrammet',
    'Diagramkällan är redan städad — inget att ändra',
    'Diagrammet omformaterat',
    '%d {one=diagram omformaterat|other=diagram omformaterade}',
    'Bibliotek med diagrammallar',
    'Fullständiga diagrammallar',
    'Syntaxfragment',
    'Redigeras: %@',
    'Mallen «%@» infogad',
    'Det här dokumentet är skrivskyddat.',
    'Mermaid-diagram',
    'Det här dokumentet har inget mermaid-block.',
    'Varumärke',
    'Exportera…',
    'Inga diagram ännu',
    '%d diagram · %@',
    '%1$d/%2$d diagram MISSLYCKADES — diagram %3$d%4$@',
    ', rad %d',
    'Det här dokumentet har inget ```mermaid-block och är inte heller en .mmd-fil.',
    'Inget diagram har ritats färdigt ännu.',
    '«%@» hittades inte i diagramkällan',
    'det gick inte att bygga nätverksspärren för WKWebView',
    'Associationsregler',
    'En korg per rad',
    'Två kolumner: id · artikel',
    'Transaktionsdatats form',
    'Korgkolumn eller kolumn med transaktions-id',
    'Artikelkolumn',
    'Avgränsartecken för artiklar',
    'Minsta support, procent',
    'Minsta confidence, procent',
    'Avgränsat av:',
    'Support ≥',
    '% · Confidence ≥',
    'Tabell över associationsregler',
    'Support',
    'Confidence',
    'Lift',
    'Leverage',
    'Obs',
    '%d {one=transaktion|other=transaktioner} · %d {one=artikel|other=artiklar} · %d {one=regel|other=regler}',
    ' — ingen regel nådde trösklarna; sänk support eller confidence',
    ' — STOPPADES I FÖRTID, tabellen är OFULLSTÄNDIG',
    '%d / %d {one=transaktion innehåller|other=transaktioner innehåller} båda sidorna',
    'Tvåkolumnsformen kräver två OLIKA kolumner.',
    '%1$d {one=rad markerad|other=rader markerade} i %2$d {one=transaktion|other=transaktioner} som innehåller «%3$@»',
    'CSV: associationsregler…',
    'Gruppvis utvinning',
    'Grupperingskolumn',
    'Värdekolumn',
    'Andra kolumnen för korrelationen',
    'Rangordningssätt',
    'Gruppera efter:',
    'Värde:',
    'Rangordna efter:',
    'Tabell över gruppernas rangordning',
    'Grupp',
    'Rader',
    'Egen tröskel',
    'MAPE',
    'r',
    'r-skillnad',
    'Anteckning',
    'går inte att mäta',
    '%d {one=grupp|other=grupper} · samlad referenskorrelation %@',
    ' · %d {one=GRUPP BORTVALD|other=GRUPPER BORTVALDA}',
    'Den här tabellen har ingen textkolumn att gruppera efter.',
    'Den här tabellen har ingen numerisk kolumn att utvinna ur.',
    '%1$d {one=rad|other=rader} i gruppen «%2$@» {one=markerad|other=markerade}',
    'CSV: gruppvis utvinning…',
    '↔',
    'Prognos',
    'Värdekolumn över tid',
    'Prognosmodell',
    'Antal perioder att prognosticera',
    'Utlåtande mot referensmodellerna',
    'Modell:',
    'Perioder:',
    'Säsong:',
    'auto',
    'Säsongsperiod; lämna tomt för att upptäcka automatiskt',
    'Tabell över prognosticerade värden',
    'Period',
    '80 %-band',
    '95 %-band',
    'MAE %@ · MAPE %@',
    'går inte att beräkna',
    'Den här tabellen har ingen numerisk kolumn att prognosticera.',
    'Det gick inte att bygga en prognos för den här kolumnen.',
    'Kolumnen «%1$@» har bara %2$d {one=numeriskt värde|other=numeriska värden} — minst 4 krävs för en prognos.',
    '# Serien läses i filens radordning — utan omsortering och utan att härleda någon tidskolumn.\n',
    'Träningsfel',
    'CSV: tidsserieprognos…',
    'Holt-Winters additiv',
    'Holt-Winters multiplikativ',
    'seasonal-naive',
    'naive',
    'Kolumner som går in i klustringen',
    'WCSS-kurva',
    'Kluster',
    'Skalning:',
    'k:',
    'eps:',
    'minPts:',
    'Välj minst en kolumn.',
    'För lite data för att bygga kurvan.',
    'Armbågen antyder k = %d. WCSS sjunker ALLTID när k växer, så det här är ett sätt att läsa diagrammet och inte ett statistiskt kriterium — titta på kurvan och bedöm om knäcken är tydlig.',
    'WCSS efter k',
    'k-avståndet antyder eps = %1$@ (minPts är som standard 2 × antalet kolumner = %2$d). %3$@',
    'Avstånd till den k:te grannen',
    'Klustring kräver minst 2 numeriska kolumner.',
    'Kluster efter %@ och %@',
    ' — klustren hittades i %d {one=dimension|other=dimensioner}; diagrammet visar bara de 2 första',
    '# brus (cluster_id = -1): %d {one=rad|other=rader}\n',
    'CSV: klustring…',
    '# --- Klustercentra (ursprungliga enheter) ---\n',
    'k-means',
    'DBSCAN',
    'Korrelationsmatris',
    'Korrelationsmetod',
    'Korrelation innebär inte orsakssamband.',
    'Starkaste paret: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klicka på en cell för att se ett punktdiagram.',
    'Inget par går att mäta.',
    '%1$@ ↔ %2$@: %3$@ över %4$d {one=rad|other=rader}',
    'Korrelation kräver minst 2 numeriska kolumner.',
    'Det går inte att läsa kolumnen «%@».',
    'CSV: korrelationsmatris…',
    'Avvikelser',
    'Lista över avvikelser',
    'Kolumn:',
    'Numerisk kolumn att undersöka',
    'Metod:',
    'Upptäcktsmetod',
    'Använd metod',
    'Tröskel',
    'Markera',
    'Exportera till en ny flik',
    'Rad',
    'Poäng',
    'Varför',
    'lindrig',
    'måttlig',
    'allvarlig',
    'z-score',
    'IQR',
    'MAD',
    '%d / %d {one=rad|other=rader} (%.2f %%)',
    'Den här tabellen har ingen numerisk kolumn att leta avvikelser i.',
    '%d {one=avvikande rad markerad|other=avvikande rader markerade}',
    'CSV: leta avvikelser…',
    '%1$d {one=regel, GODKÄND|other=regler, alla GODKÄNDA} · %2$d {one=rad|other=rader} · %3$.0f ms',
    '%1$d {one=fel|other=fel} · %2$d {one=varning|other=varningar} över %3$d {one=regel|other=regler} · %4$d {one=rad|other=rader} · %5$.0f ms',
    'Spara dokumentet först — kvalitetsreglerna ligger bredvid datafilen.',
    'Ingen regeluppsättning ännu. Skapa filen %@ och öppna igen.',
    'Historik',
    'Sparade frågor',
    'Spara den här frågan…',
    'Spara frågan',
    'Ge den ett namn så du hittar den senare. Samma namn skriver över.',
    'Till exempel: Intäkter per län',
    'Inget värde angavs för parametern: %@',
    'Tillägget har ändrats sedan du godkände det — GEditor vägrar köra det',
    'Köra ett icke godkänt tillägg?',
    'Jag litar på den här filen — kör',
    'OSIGNERAT',
    'Signatur: %@',
    'Sökväg: %@',
    'Ersätt',
    'Ersätt alla',
    'Ren text',
    'Utökad (\\n \\t \\xNN)',
    'Reguljärt uttryck',
    'Skilj på versaler och gemener',
    'Helt ord',
    'Inga resultat',
    'Pröva ett reguljärt uttryck…',
    'Loggläge (färg efter nivå)',
    'Filtrera loggen efter nivå…',
    'Kör på hela mappen…',
    'Filtrera genom ett externt kommando…',
    'Skript…',
    'Tilläggspaket…',
    'Nytt fönster',
    'Lossa fliken till ett nytt fönster',
    'Ingen mapp är öppnad',
    'Sök efter en fil i mappen',
    'Filtrera på namn',
    'Ny fil…',
    'Ny mapp…',
    'Byt namn…',
    'Flytta till papperskorgen',
    'Visa i Finder',
    'Läser dokumentets struktur…',
    'den här filen har inga funktioner',
    'Inga träffar',
    'Ren text',
    '🔒 Skrivskyddad',
    'Följs',
    'brytning vid kolumn',
    'Syntax',
    'Klicka för att infoga i frågan',
    'ogiltig fråga',
    'nyckeln «namn» i roten',
    'nyckel med mellanslag',
    'första elementet',
    'alla element',
    'utsnitt',
    'union av index',
    'alla nycklar «pris» på alla nivåer',
    'alla noder',
    'filtrera på tal',
    'filtrera på förekomst',
    'Till första felet',
    'Kolumnen intäkt är numerisk',
    'filtrera…',
    'Avbryt',
    'Utför ersättningen',
    'förhandsvisning',
    'interaktivt',
    'Redigera',
    'Gränssnitt',
    'Tangentbordsgenvägar',
    'Textstorlek',
    'Tabbredd',
    'Indrag med tabbar',
    'Dra in automatiskt vid ny rad',
    'Framhäv alla sökträffar',
    'Normalisera till NFC vid sparande',
    'Språk',
    'Utseende',
    'Som systemet',
    'Ljust',
    'Mörkt',
    'Tema',
    'Använd Notepad++-uppsättningen',
    'Tillbaka till standardtangenterna',
    'Öppna konfigurationsfilen',
    'Exportera det aktuella temat',
    'Språkbytet slår igenom helt vid nästa start.',
    'Standardtangenterna kommer tillbaka vid nästa start.',
    'Markdown-förhandsvisning',
    'Förhandsvisningen använder systemets Markdown-motor: ännu inga tabeller och ingen färgläggning av kodblock.',
    'Pröva ett reguljärt uttryck',
    'Uttryck',
    'Testtext',
    'Resultat',
    'Träffar',
    'Vad det här uttrycket gör',
    'Förklara uttrycket',
    'Sökläge',
    'Sökresultat',
    'Inga träffar',
    ' (avkortat)',
    'Dokumentkarta',
    'Flikfält',
    'Rubrikrad för kolumnerna',
    'Inga kolumner',
    'Arbetsytans träd',
    'Lista över funktioner och klasser',
    'Sökresultat i mappen',
    'CSV-datatabell',
    'Arbetsbänk för datarensning',
    'JSONPath-fråga',
    'Lista över datafel',
    'Bedömare för guldmängden…',
    'Jämför med externa poäng (JSONL)…',
    'Välj en fil med externa poäng (JSONL: query, chunk_id, score)',
    'Byt namn på den valda noden',
    'Slå samman de valda noderna',
    'Dela den valda noden',
    'Plocka ut den valda delgrafen till en ny flik',
    'Inget att ändra',
    '%1$@ — tillämpa %2$d {one=ändring|other=ändringar}?',
    '%1$@: %2$d {one=ändring|other=ändringar} · Cmd-Z ångrar hela omgången',
    'Sätt markören på EXAKT EN nod och försök igen',
    'Byt namn på «%@»',
    'Alla kanter och etiketter som pekar på den här noden ändras med den.',
    'Byt namn på noden',
    'Välj MINST TVÅ noder och försök igen',
    'Kanonisk form «%@» — vanligast, längst, med diakritiska tecken',
    'Slå samman noder',
    'Välj de KANTRADER som ska flyttas och försök igen',
    'Alla valda rader måste röra EXAKT EN nod — välj fler kantrader',
    'Dela «%1$@» — flytta %2$d {one=kant|other=kanter}',
    'Kanter till: %@',
    'Dela noden',
    'Dokumentet är osparat — den uttagna filen behöver en plats bredvid',
    'Välj den del av grafen som ska plockas ut och försök igen',
    'Samla entitetsvarianter → granskningstabell',
    'Tillämpa den ändrade granskningstabellen',
    'Dokumentet är osparat — granskningstabellen måste ligga bredvid graffilen',
    'Inga varianter att samla hittades',
    '%d {one=variantgrupp|other=variantgrupper} — rätta kolumnen «canonical» och kör «Tillämpa granskningstabellen»',
    'Ingen granskningstabell «%@» — kör «Samla entitetsvarianter» först',
    'Granskningstabellen går inte att läsa: %@',
    'Granskningstabellen har ingen rad som behöver ändras',
    'Ingen plats i grafen stämmer med granskningstabellen',
    'Samla entitetsvarianter',
    '%d {one=ändring tillämpad|other=ändringar tillämpade} · alias-tabellen och markörlistan skrevs bredvid filen',
    'Tillämpa %d {one=ändring|other=ändringar} på grafen?',
    '%d alias → kanonisk form.',
    'SLÅ SAMMAN noder (går inte att ångra genom att skriva om):',
    '%d {one=alias finns|other=alias finns} inte i grafen och hoppades över.',
    'GraphRAG…',
    'Täckningsanalys stycke ↔ entitet',
    'Exportera kontextpaketet (JSONL)',
    'Täckning stycke ↔ entitet ↔ graf',
    '- %1$d {one=entitet|other=entiteter} · %2$d {one=stycke|other=stycken} · %3$.0f %% av entiteterna nämnda · %4$.0f %% av styckena med entitet',
    'Entiteter som inget stycke nämner',
    'Föräldralösa stycken (utan någon entitet)',
    'Grafnoder utan motsvarande entitet',
    'inga',
    'Metod',
    'Det gick inte att bygga kopplingen stycke ↔ entitet',
    'Bedöm grafens hälsa',
    'grafens hälsa',
    'Hälsa %1$@/100 · %2$d {one=fel|other=fel} · %3$d {one=omkastning|other=omkastningar} · %4$d föräldralösa',
    'Hybrid med grafen',
    'α = 1: grafens signal ignoreras helt, resultatet blir samma som ren BM25',
    'α högt: grafen justerar bara BM25-rangordningen lätt',
    'α kring standardvärdet 0,7: BM25 leder, grafen justerar',
    'α lågt: grafen leder, BM25 bryter bara lika',
    'α = 0: bara grafens signal; stycken utan entiteter hamnar på samma nivå',
    'Dokumentet är osparat — hybriden behöver en graffil bredvid korpusen',
    'Graffilen «%@» hittades inte — hybriden behöver den för sin signal',
    'hybrid %.1f ms · %@',
    'Algoritmer…',
    'PageRank (kantens tjocklek)',
    'Gemenskaper (bakgrundsfärg)',
    'Sammanhängande komponenter',
    'Exportera nodtabellen till en ny flik',
    '%1$d {one=komponent|other=komponenter} · den största %2$d {one=nod|other=noder} · %3$d föräldralösa noder',
    'Det här dokumentet är ingen DOT-graf',
    'Det gick inte att bygga nod-/kanttabellen: %@',
    '%d {one=rad|other=rader} · %@',
    'Etikettera',
    'Anteckning (frivillig)',
    'Spara posten',
    'Exportera CSV',
    'Dokumentet är osparat — bedömaren måste ligga bredvid korpusfilen',
    'Det gick inte att läsa in bedömaren: %@',
    'Det gick inte att spara: %@',
    'Bedömaren har ännu ingen post',
    'Det gick inte att skriva: %@',
    'Det här dokumentet är varken en .mmd-fil eller DOT och har inget mermaid-block.',
    '%d {one=nod|other=noder} · %d {one=kant|other=kanter} · ⚠ %@',
    'Mermaid-diagram: lägg till element…',
    'Mermaid-diagram: koppla ihop de två valda elementen',
    'Mermaid-diagram: ändra etiketten på det valda elementet…',
    'Mermaid-diagram: radera det valda elementet',
    'Mermaid-diagram: flytta meddelandet uppåt',
    'Mermaid-diagram: flytta meddelandet nedåt',
    'Lägg till element',
    'Lägg till deltagare',
    'Lägg till post',
    'Lägg till en post i diagrammet',
    'Ändra en post i diagrammet',
    'Radera en post ur diagrammet',
    'Radera elementet',
    'Ändra etiketten',
    'Ändra ordningen på meddelandena',
    'Postens namn',
    'Ny post',
    'Postens namn visas på diagrammet.',
    'Diagrammets egenskapstabell',
    'Det här dokumentet har inget mermaid-block',
    'Identifierare i diagramkällan — utan mellanslag. Etiketten ändras sedan med dubbelklick.',
    'Lämnas det tomt visas identifieraren själv.',
    'Bara den synliga ETIKETTEN ändras; elementets identifierare förblir densamma.',
    'Oklart vilket element «%@» är',
    'Välj EXAKT TVÅ element och försök igen',
    'Sätt markören på EXAKT ETT element och försök igen',
    'Välj ETT element att radera, eller två element som en kant förbinder',
    'Radera «%1$@» och den %2$d {one=kant som rör det|other=kanter som rör det}?',
    'Noderna i andra änden av de kanterna behålls — de deklareras om med sin etikett om kantsatsen var deras enda deklaration.',
    'Diagrammet «%1$@» redigeras bara som text — %2$@',
    '%@: dra mellan två element för att koppla ihop dem, dubbelklicka för att ändra etiketten',
    '%@: dra mellan två deltagare för att lägga till ett meddelande; ordningen ändras via menyn Verktyg',
    '%@: redigera i egenskapstabellen nedanför',
    'Visuell redigering påslagen',
    '%1$@ · %2$d {one=post|other=poster} — redigera direkt i tabellen, varje cell är ett ångra-steg',
    'För ett cirkeldiagram är det ett tal; för ett gantt det som följer efter kolon.',
    'Mermaid-diagram: plocka ut blocket till en .mmd-fil…',
    'Mermaid-diagram: bädda in den refererade filen igen',
    'Plocka ut diagramblocket',
    'Bädda in diagramblocket',
    'Plocka ut diagramblocket till en egen fil',
    'Filen läggs BREDVID dokumentet; blocket behåller en referensrad så att redigering sker på ett enda ställe.',
    'Dokumentet är osparat — diagramfilen behöver en plats bredvid',
    'Filen «%@» finns redan — välj ett annat namn',
    'Utplockat till «%@» — blocket behöll en referensrad',
    'Öppna filen',
    '«%@» inbäddat igen; filen ligger kvar på hårddisken',
    'Det här blocket innehåller ett riktigt diagram, inte en referens',
    'Det här blocket refererar till «%@» — öppna den filen för att redigera',
    'Det gick inte att läsa diagramfilen %@',
    'Visuell redigering',
    'Dra från en nod till en annan för att lägga till en kant; dubbelklicka för att ändra etiketten. Varje handling är ett ångra-steg.',
    'Visuell redigering: dra mellan två noder för att lägga till en kant, dubbelklicka för att ändra etiketten',
    'Visuell redigering avstängd',
    'Lägg till nod…',
    'Lägg till en kant mellan de två valda noderna…',
    'Ändra etiketten på den valda noden…',
    'Radera den valda noden/kanten',
    'Lägg till nod',
    'Lägg till kant',
    'Ändra nodens etikett',
    'Radera noden',
    'Radera kanten',
    'Cmd-Z ångrar',
    'Det här dokumentet är skrivskyddat',
    'Etiketten för «%@»',
    'Bara den synliga ETIKETTEN ändras; nodens identifierare förblir densamma.',
    'Oklart vilken nod «%@» är',
    'Nodens identifierare i DOT-filen. Etiketten ändras sedan med dubbelklick på bilden.',
    'Välj EXAKT TVÅ noder och försök igen',
    'Välj EN nod att radera, eller två noder som en kant förbinder',
    'Radera noden «%1$@» och de %2$d {one=kant som rör den|other=kanter som rör den}?',
    'Om hängande kanter blir kvar återskapar DOT noderna ur dem — den raderade noden dyker upp igen vid nästa ritning.',
    'BM25-sökningslabb',
    'Fråga — Enter för att söka',
    'Bedöm…',
    'Bygger indexet',
    'Inget stycke matchar',
    'bästa träffarna',
    'k1 = 0: varje ord räknas BARA en gång, hur många gånger det än förekommer',
    'k1 lågt: att upprepa ett ord ger nästan ingen extra poäng',
    'k1 kring standardvärdet 1,2: upprepning ger poäng, men allt mindre',
    'k1 högt: ett stycke som upprepar ett ord många gånger belönas kraftigt',
    'b = 0: längden ignoreras, långa stycken straffas inte',
    'b lågt: långa stycken straffas bara lätt',
    'b kring standardvärdet 0,75: långa stycken straffas måttligt',
    'b = 1: största straffet för längd, korta stycken gynnas',
    'JSONL: sökningslabb…',
    'Dokumentet är osparat — BM25-indexet ligger bredvid korpusfilen och behöver därför en sökväg',
    'Den här filen är inte JSONL — Retrieval Lab arbetar på en korpus av stycken',
    'Det gick inte att bygga ett BM25-index för den här filen',
    'Dokumentet är osparat — en korpussökväg krävs för att skapa rapporten',
    'Välj en bedömningsmängd (CSV eller JSONL: fråga + väntat stycke-id)',
    'Bedömning av sökningen',
    'Ändra k1, b eller k ovanför och titta igen för att jämföra två inställningar; lägg till ett «compare»-block för att köra två parameteruppsättningar parallellt på samma bedömningsmängd.',
    'Fel',
    '   (%d…%d, i snitt %.0f)',
    'JSONL-läge',
    'Post',
    'Detaljer',
    'Posten på raden',
    'är inte giltig JSON',
    'poster',
    'tomma rader',
    'är inget objekt',
    'visad tabell',
    'AVBRUTET PÅ HALVA VÄGEN',
    'Inget filter',
    'poster som matchar filtret',
    'Sätt markören på en rad för att se posten',
    'Inga trasiga poster',
    'Ännu inte undersökt. Kör «JSONL: undersök stycken» igen efter kontrollen.',
    'textfält',
    'SCHEMA (gissat — ändras genom att välja ett annat fält)',
    'text',
    'identifierare',
    'nästlade metadata',
    'FÄLT',
    'täckning',
    'flera typer',
    'LÄNGD — tecken',
    'LÄNGD — ord',
    'LÄNGD — uppskattade tokens',
    'TOMMA OCH DUBBLETTER',
    'tomma stycken',
    'rader',
    'grupper av exakta dubbletter',
    'rader går inte att läsa, utanför statistiken',
    'METOD',
    '«tecken» räknas som Unicode-tecken (skalärer), inte som synliga grupper',
    '«ord» delas på ASCII-mellanslag',
    '«tokens» räknas med en stavelsedelare — INTE modellens',
    '«dubblett» betyder EXAKT dubblett; nästan-dubbletter finns i blocket ```quality',
    'stycken',
    'JSONL: kontrollera och undersök stycken…',
    'Bild',
    'PDF',
    'Word-dokument',
    'Excel-kalkylblad',
    'PowerPoint-presentation',
    'Arkiv',
    'Anpassa till fönstret',
    'Kopiera bilden',
    'Rotera',
    'Det går inte att läsa bilden «%@»',
    'Bilden kopierad till urklipp',
    'Framhäv i gult',
    'Stryk under',
    'Anteckning…',
    'Ta bort anteckningarna',
    'Plocka ut texten till en ny flik',
    'Spara versionen med anteckningar…',
    'Sök i PDF-filen',
    'Lägg till',
    'Sida %d/%d',
    'Sida %d',
    'Träff %d/%d',
    '0 träffar',
    'Det går inte att läsa PDF-filen «%@»',
    'Den här PDF-filen är lösenordsskyddad — innehållet går inte att komma åt',
    '«%@» hittades inte i dokumentet',
    'Framhävt',
    'Understruket',
    'Markera ett textstycke först',
    'Anteckning tillagd',
    'Den här sidan har inga anteckningar',
    '%d {one=anteckning borttagen|other=anteckningar borttagna} från den här sidan',
    'Den här PDF-filen har inget textlager — troligen är det en inskanning',
    'Det gick inte att skriva filen',
    'Den skrivna filen öppnas INTE korrekt igen — använd inte den här versionen',
    '%@ sparad · %d {one=sida|other=sidor}',
    'Namn',
    'Storlek',
    'Komprimerad',
    'Förhållande',
    'Ändrad',
    'Öppna det valda objektet',
    'Packa upp till en mapp…',
    'Packa upp här',
    '%d {one=objekt|other=objekt}',
    'uppackat till %@',
    '— insidan av en Office-fil är ett arkiv; det här är dess delar',
    '%d {one=objekt uppackat|other=objekt uppackade}',
    '%d {one=objekt trasigt|other=objekt trasiga}',
    '%d {one=objekt NEKADES|other=objekt NEKADES} eftersom deras sökvägar går utanför målmappen',
    'Det går inte att öppna det här objektet',
    'Det går ännu inte att skriva direkt till en %@ — använd «Spara som…»',
    'Ingenting har ändrats',
    '%1$d {one=cell skriven|other=celler skrivna} till %2$@',
    '%1$d {one=stycke skrivet|other=stycken skrivna} till %2$@',
    'Det gick inte att skriva till filen — originalet är orört',
    'förbereda testfallet',
    'Det går inte att skriva settings.json',
    'Rotera vänster',
    'Rotera höger',
    'Flytta sidan upp',
    'Flytta sidan ned',
    'Radera sidor…',
    'Radera sidor',
    'Extrahera sidor…',
    'Extrahera sidor till ny fil',
    'Slå ihop PDF-fil…',
    'Dela fil…',
    'Dela PDF-fil',
    'Exportera bilder…',
    'Exportera sidor som PNG-bilder',
    'Ångra sidändring',
    'Spara ändrad kopia…',
    'Spela',
    'Paus',
    'Normal vy',
    'Välj blad',
    'Öppna blad',
    'Kasta och byt blad',
    'Arbetsboken har %d blad.',
    'Arbetsboken har bara ett blad: ”%@”',
    'Kasta osparade ändringar i det här bladet?',
    'Att byta blad ersätter hela fliken. Det som inte sparats med ⌘S går förlorat.',
    'Välj PDF-fil att slå ihop',
    'Välj mapp för bilderna',
    'Välj var filen ska sparas. Den andra filen skrivs bredvid.',
    'Dokumentet har %d sidor. Ange sidorna som ska raderas, t.ex. 2-4,7',
    'Dokumentet har %d sidor. Ange sidorna som ska extraheras, t.ex. 1-3,8',
    'Dokumentet har %d sidor. Ange sidorna som ska exporteras, t.ex. 1-3',
    'Dokumentet har %d sidor. Ange delen som ska skiljas ut, t.ex. 1-5; resten blir en andra fil.',
    'Sida %d roterad',
    'Sidorna %@ raderade · %d sidor kvar',
    '%d sidor sammanslagna från ”%@”',
    'Delad i %@ (%d sidor) och %@ (%d sidor)',
    'Skrev %@ — %@ · %d sidor',
    '%d bilder exporterade till %@',
    'Endast %d av %d bilder exporterades',
    'En sidåtgärd ångrades',
    'Inga sidåtgärder kvar att ångra',
    'Kan inte radera ALLA sidor — en PDF måste ha minst en sida',
    'Det intervallet är hela dokumentet — inget att dela av',
    '”%@” är lösenordsskyddad — går inte att slå ihop',
    '”%@” har inga sidor',
    'Redan på första sidan',
    'Redan på sista sidan',
    '· ändrad, ej sparad',
    'Animerad bild · %d bildrutor',
    'Osparat dokument — ingen fil på disken att visa binärt',
    'Det här kommandot fungerar bara med Excel-arbetsböcker',
    'Det gick inte att läsa listan över blad',
    'Det finns inget blad som heter ”%@”',
    'Det gick inte att läsa bladet ”%@”',
    'Bladet ”%@” · %d rader',
    'resten',
    'Obs',
    'Varning',
    'Se även',
    'Kopiera',
    'Kopierat',
    'Kopiera exempelkoden',
    'Sök i hjälpen',
    'Tillbaka',
    'Kom igång',
    'Visa inte det här fönstret vid start',
    'Hjälpen är ännu inte översatt till det här språket — visar den vietnamesiska texten.',
    'Gå till offset (t.ex. 1F400 eller 0x1F400)',
    'Kopiera markerade rader',
    '%d rader kopierade',
    'Det gick inte att läsa ”%@”',
    'Tom fil',
    'Det gick inte att läsa offseten ”%@”',
    'Offseten 0x%@ ligger bortom filens slut',
    'Öppna med annat program…',
    '%d kanaler',
    'Kan inte spela ”%@”',
    'Kan inte spela — %@',
    'macOS saknar inbyggd avkodare för formatet %@ — det är en systembegränsning, inte en trasig fil.',
    'Du kan ändå se byten i binärläge, eller öppna filen i ett program med egen avkodare.',
    'Signera…',
    'Redigera text…',
    'Redigera text',
    'Rita över',
    'Nästa tomma fält',
    'Rensa ifyllda värden',
    'Den här filen har inga formulärfält',
    '%d formulärfält rensade',
    'Alla formulärfält är redan ifyllda',
    '%d fält är fortfarande tomma',
    'Ifyllbart formulär: %d fält. Skriv direkt i dem och välj sedan ”Spara ändrad kopia…”',
    'Välj en signaturbild (transparent bakgrund ser bäst ut)',
    'Det gick inte att skapa den signerade sidan',
    'Signaturen infogad på sida %d',
    'Markera först texten du vill ändra',
    'Markeringen är för liten',
    'Den nya texten RITAS ÖVER markeringen med systemtypsnittet. Den gamla texten täcks, den tas inte bort — den går fortfarande att extrahera, så detta är ingen maskering.',
    'Det gick inte att skapa den ändrade sidan',
    'Ny text ritades över sida %d',
    'Växla Vy / Kod',
    'Ingen trädvy ännu för JSON · XML · YAML',
    'Ingen diagramvy i fliken ännu',
    'Ingen dispositionsvy ännu för PowerPoint',
    'Den här filen har bara ett visningsläge',
    '%d noder',
    'Det gick inte att bygga trädet: %@',
    'Dokumentet är för stort för ett träd — använd Kod-läget',
]
