# -*- coding: utf-8 -*-
"""Use case bổ sung v1.2: nhóm I (kỹ nghệ), J (tri thức & dò tìm), K (tự tạo công cụ)."""
from uc_data import uc, UCS, FLOWS, ALTS
G_I, G_J, G_K = "I. Kỹ nghệ (v1.2)", "J. Tri thức & dò tìm (v1.2)", "K. Tự tạo công cụ (v1.2)"

uc("UC-I01", "Phân tích yêu cầu từ lệnh/tài liệu và sinh ReqSet", G_I, "Tác tử (architect)", "Kỹ sư",
   "ReqSet có mã, loại, câu đo được, ưu tiên, tiêu chí chấp nhận, khả thi theo hộ chiếu", "Lệnh 'phân tích yêu cầu…'; dự án mới có README; P7.1", "Dự án mở; có hộ chiếu chip (hoặc sẽ hỏi)",
   "Bảng requirement status generated; issue mơ hồ đã hỏi hoặc mặc định; trace tới module rỗng", "Hội thoại (câu hỏi gộp)", "K10 ReqSet", "M", "M1", "FR-REQ-01…07", "UR-KN-01", "Yêu cầu & kiến trúc",
   [("N", "Ra lệnh: 'phân tích yêu cầu cho robot từ README' (hoặc tự chạy sau nhập zip)", "câu lệnh", "", "Lệnh"),
    ("T", "req.elicit: gom câu yêu cầu từ README/tài liệu/ảnh/chat; nêu gaps", "nguồn", "raw[]", "req.elicit"),
    ("T", "req.classify: FR/NFR/HW/SAFETY/RT, câu đo được, mã UR/FR", "raw", "ReqSet", "req.classify"),
    ("K", "req.ground_hw: so ngưỡng với fact (tần số, RAM, ADC, bus); thiếu fact → kg.request", "ReqSet, hộ chiếu", "FeasibilityReport", "req.ground_hw"),
    ("T", "req.detect_conflict + req.prioritize; mâu thuẫn không tự giải → một câu hỏi gộp", "ReqSet", "Issue[], ReqSet'", "T1*"),
    ("N", "Trả lời câu hỏi gộp (hoặc mặc định sau timeout)", "Question", "answer", "D3"),
    ("T", "req.acceptance sinh Given–When–Then; ghi bảng requirement; chat.report_back", "ReqSet", "AC[]", "req.acceptance")],
   [("A1", "Không có README/tài liệu", "Chỉ từ lệnh + mẫu tham chiếu K5′; ghi nguồn 'template'"), ("A2", "Yêu cầu không khả thi", "Đề xuất thay thế (chip khác trong registry hoặc giảm ngưỡng) — ASK")])
uc("UC-I02", "Thiết kế kiến trúc firmware, HwMap, ngân sách, ADR", G_I, "Tác tử (architect)", "Kỹ sư",
   "ModuleGraph, HwMap không xung đột, ngân sách RAM/thời gian, ADR có phương án bị loại", "Sau UC-I01; lệnh 'thiết kế kiến trúc'", "ReqSet accepted; hộ chiếu chip+board",
   "Bảng module/hw_map/adr; FEATURES.json từ arch.to_plan", "G1 (đổi kiến trúc dự án đã có)", "K10 ModuleGraph, ADR; K6 HwMap", "M", "M2", "FR-ARCH-01…11", "UR-KN-02", "Yêu cầu & kiến trúc",
   [("T", "arch.style_select theo NFR/RT và fact tài nguyên (quy tắc tiền kiểm + lý do)", "ReqSet, hộ chiếu", "ArchDecision", "T1*"),
    ("T", "arch.decompose → module theo lớp; mỗi FR có module", "ReqSet", "ModuleGraph", "arch.decompose"),
    ("K", "arch.map_hw + board.check_pins; xung đột → board.propose_fix", "ModuleGraph, hộ chiếu", "HwMap", "arch.map_hw"),
    ("T", "arch.memory_budget + arch.timing_budget (RMS)", "ModuleGraph", "budgets", "arch.memory_budget"),
    ("T", "arch.interface_spec + arch.state_machine cho module có FSM", "ModuleGraph", "interfaces, FSM", ""),
    ("T", "arch.adr ghi quyết định có trích dẫn; arch.review theo checklist", "decision", "ADR, findings", "arch.adr"),
    ("N", "Duyệt nếu đổi kiến trúc dự án đã có (G1) hoặc chọn phương án cuối khi arch.compare", "ADR", "approved", "G1 tự động ≥ A2"),
    ("T", "arch.to_plan → Feature; diagram.architecture/pinmap; chat.report_back", "ModuleGraph", "FEATURES.json", "arch.to_plan")],
   [("A1", "Xung đột chân không tự giải", "board.propose_fix → ASK phương án chạm mã passing"), ("A2", "Không schedulable", "Đề xuất giảm tần số/tách task; ASK")])
uc("UC-I03", "Vẽ lược đồ từ mô hình và đồng bộ với mã", G_I, "Tác tử (writer)", "Kỹ sư",
   "Lược đồ ở ngôn ngữ GEditor hỗ trợ, lint 0 lỗi, render, đồng bộ hai chiều", "Lệnh 'vẽ sơ đồ …'; doc.generate; FSM/mã đổi", "Mô hình nguồn tồn tại (BOM, HwMap, ModuleGraph, FSM, Plan, fact timing)",
   "Diagram trong .eide/diagrams, DocArtifact liên kết nếu chèn", "T1* khi sync lệch lớn", "K10 Diagram", "M", "M1–M2", "FR-DIAGRAM-01…14", "UR-KN-03, UR-KN-04", "Lược đồ",
   [("N", "Ra lệnh 'vẽ sơ đồ trạng thái module motor' (hoặc tự chạy trong P7)", "câu lệnh", "", "Lệnh"),
    ("T", "Chọn generator theo kind; sinh mã lược đồ với node_ids = định danh mô hình", "mô hình", "Diagram.src", "diagram.state"),
    ("K", "diagram.lint (cú pháp, mồ côi, tên khớp mô hình)", "src", "issues", "diagram.lint"),
    ("H", "diagram.render trong sandbox (mmdc/plantuml/dot/d2/wavedrom) hoặc GEditor render", "src", "svg", "diagram.render"),
    ("N", "Xem/sửa mã lược đồ trong DiagramView; sửa → lint/render lại", "src'", "", ""),
    ("T", "diagram.sync check ↔ mã/kiến trúc; lệch nhỏ tự cập nhật, lệch lớn hỏi", "src, code", "diff", "T1*")],
   [("A1", "Thiếu renderer", "env.install từ danh sách tin cậy; GEditor render trực tiếp nếu có"), ("A2", "Ảnh sơ đồ vẽ tay", "diagram.from_image → mã; confidence thấp → chờ duyệt")])
uc("UC-I04", "Sinh tài liệu chuẩn EAA/EIDE và kiểm style", G_I, "Tác tử (writer)", "Kỹ sư",
   "Tài liệu docx/md theo mẫu có thuộc tính, lịch sử, hình đánh số, mục Nguồn; style_check 0 lỗi", "Lệnh 'viết SRS'; P7.7; mốc dự án", "ReqSet/ModuleGraph/fact có sẵn theo loại tài liệu",
   "DocArtifact trong .eide/docs; commit", "—", "K10 DocArtifact", "M", "M2", "FR-DOC-01…12", "UR-KN-05", "Tài liệu",
   [("N", "Ra lệnh 'viết SRS cho dự án'", "câu lệnh", "", "Lệnh"),
    ("T", "doc.generate: mục lục chuẩn theo loại; mỗi mục lấy tri thức nguồn; writer viết có citations", "type, scope", "sections", "doc.generate"),
    ("T", "doc.embed_diagram cho hình chuẩn (kiến trúc, chân, trạng thái)", "diagram ids", "figures", "doc.embed_diagram"),
    ("K", "doc.style_check: tiếng Việt, thuật ngữ, khẳng định có nguồn, định dạng", "doc", "issues", "doc.style_check"),
    ("T", "Sửa mục có issue (≤ 2 vòng); dựng docx; lưu DocArtifact; báo cáo", "doc", "docx", "")],
   [("A1", "Thiếu tri thức cho một mục", "Mục ghi 'chưa xác định' + kg.request; không bịa"), ("A2", "Yêu cầu bản tiếng Anh", "doc.translate giữ số hình/bảng")])
uc("UC-I05", "Đổi yêu cầu → tác động → cập nhật tài liệu/lược đồ", G_I, "Tác tử", "Kỹ sư",
   "Mọi hiện vật liên quan (module, mã, test, tài liệu, lược đồ) được đánh dấu stale và cập nhật theo chính sách", "Người đổi yêu cầu; fact thay đổi (supersede)", "ReqSet có trace",
   "stale được xử lý hoặc nằm trong hàng đợi", "T1* thay đổi lớn", "K10", "S", "M3", "FR-REQ-08, FR-DOC-12, FR-DIAGRAM-14", "UR-KN-06", "Yêu cầu & kiến trúc",
   [("N", "Sửa yêu cầu (hoặc fact đổi qua UC-B13)", "delta", "", "Lệnh"),
    ("K", "req.change_impact + kg.impact → danh sách hiện vật", "delta", "ImpactReport", "req.change_impact"),
    ("T", "doc.sync/diagram.sync: mục nhỏ tự cập nhật, lớn hỏi", "stale[]", "updated[]", "T1*"),
    ("K", "Feature liên quan → failing; view.impact_map; báo cáo", "impact", "", "")],
   [("A1", "Tác động ≥ 3 module", "ASK toàn bộ; đề xuất kế hoạch cập nhật")])
uc("UC-J01", "Xem bản đồ tri thức, nguồn gốc, độ phủ, tác động", G_J, "Kỹ sư", "Knowledge Plane",
   "Hiểu tri thức dự án có gì, từ đâu, thiếu gì, đổi gì ảnh hưởng gì — không cần đọc PDF", "Mở màn hình; lệnh 'cho anh xem bản đồ'", "Có hộ chiếu",
   "—", "—", "—", "M", "M1", "FR-VIEW-01…06, 11–13", "UR-TQ-01, UR-TQ-03", "Bản đồ tri thức & hỏi đáp",
   [("N", "Mở bản đồ / ra lệnh", "", "", "Lệnh"),
    ("K", "view.kg_map: dựng, tô màu tier/status/lớp, gom cụm > 5.000 nút", "project", "GraphView", "view.kg_map"),
    ("N", "Nhấp nút → view.kg_focus; nhấp fact → view.provenance mở PDF trang/bbox", "node", "", ""),
    ("K", "view.coverage_map / view.impact_map theo yêu cầu", "passport|delta", "heatmap|graph", ""),
    ("N", "Xuất Mermaid/DOT để chèn tài liệu", "view", "file", "view.export_map")],
   [("A1", "KG > 50.000 nút", "Gom cụm theo ngoại vi; lọc mặc định lân cận dự án")])
uc("UC-J02", "Hỏi–đáp RAG có trích dẫn và trace", G_J, "Kỹ sư", "Tác tử (writer)",
   "Câu trả lời từ kho tài liệu dự án, mọi câu có trích dẫn mở được nguồn, có giải thích vì sao", "Câu hỏi trong màn hình hoặc chat", "Chỉ mục RAG đã xây (view.rag_index sau nhập tài liệu)",
   "Answer + citations + trace lưu M3", "—", "K7 (câu hỏi/trả lời)", "M", "M1", "FR-VIEW-07…10", "UR-TQ-02, UR-TQ-04", "Bản đồ tri thức & hỏi đáp",
   [("N", "Hỏi 'địa chỉ I2C BME280 và điều kiện chọn?'", "question", "", "Lệnh"),
    ("K", "RagIndex.retrieve lai (FTS5 + vector + lan tỏa KG)", "question", "hits[]", "memory.retrieve"),
    ("T", "writer trả lời chỉ từ chunk, mỗi câu [n]; không đủ điểm → chat.decline", "hits", "answer", "view.rag_ask"),
    ("N", "Nhấp [n] → mở nguồn; 'Vì sao' → view.rag_trace; 'So sánh nguồn' → view.rag_compare", "", "", "")],
   [("A1", "Câu hỏi ngoài kho", "'Không tìm thấy trong tài liệu dự án' + đề xuất search.web/kg.request"), ("A2", "Nguồn mâu thuẫn", "rag_compare chỉ khác biệt; không tự chọn")])
uc("UC-J03", "Dò board/probe/ID chip và tự cấu hình target", G_J, "Tác tử (Discovery)", "Kỹ sư",
   "Cắm board → target.yaml đúng adapter/cổng/tốc độ, ID khớp hộ chiếu, sẵn sàng nạp", "Cắm USB; lệnh 'board nào đang cắm?'; trước target.flash", "Driver/quyền cổng ok (discover.env_hw)",
   "Discovery lưu; target.yaml; thanh trạng thái cập nhật", "Leo thang khi ID lệch", "K7 Discovery", "M", "M2", "FR-DISCOVER-01…03, 08, 09, 11, 12", "UR-DT-01, UR-DT-04", "Dò board",
   [("H", "event.discover.changed khi cắm/rút (hotplug)", "USB", "", ""),
    ("K", "discover.ports + discover.probe (VID/PID, probe-rs list)", "", "ports, probes", "discover.ports"),
    ("H", "discover.chip_id qua probe theo họ; đối chiếu hộ chiếu", "probe", "identity", "discover.chip_id"),
    ("K", "discover.firmware_probe (banner) + discover.power (VDD)", "port", "fw, power", ""),
    ("K", "discover.auto_setup ghi target.yaml (sao lưu cũ); board lab từ autonomy.yaml", "discovery", "target.yaml", "discover.auto_setup"),
    ("T", "Thông báo ngắn trong chat/thanh trạng thái", "", "", "")],
   [("A1", "ID không khớp hộ chiếu", "E4003; không nạp; đề xuất project.set_target đúng part hoặc kiểm board"), ("A2", "Không có probe, chỉ serial", "Chế độ bootloader (DFU/arduino/esptool) nếu firmware hỗ trợ"), ("A3", "VDD ngoài dải", "Chặn nạp; cảnh báo")])
uc("UC-J04", "Dò tốc độ kết nối tối ưu", G_J, "Tác tử (Discovery)", "Kỹ sư",
   "Baud/clock cao nhất với 0 lỗi trong giới hạn có nguồn", "Sau UC-J03; serial baud=auto; lệnh 'dò tốc độ'", "Board cắm; firmware kiểm định hoặc banner",
   "target.yaml speeds; Discovery.link_speed", "ASK khi nấc vượt fact", "K7", "M", "M2", "FR-DISCOVER-06", "UR-DT-02", "Dò board",
   [("T", "Chọn thang nấc theo kind; limit từ fact (swd_max_khz, uart_max_baud) hoặc mặc định ISA", "kind", "ladder, limit", "discover.link_speed"),
    ("H", "Thử từng nấc 1.000 khung (echo/IDCODE/ID ngoại vi); đo lỗi", "nấc", "err", ""),
    ("T", "Chọn nấc cao nhất lỗi 0; nấc vượt limit → ASK", "tried", "chosen", "T1"),
    ("K", "Ghi target.yaml; báo cáo", "", "", "")],
   [("A1", "Mọi nấc đều lỗi", "Giữ mặc định; cảnh báo dây/nguồn; đề xuất discover.clock_measure")])
uc("UC-J05", "Nhận diện board từ ID + quét bus + ảnh", G_J, "Tác tử (Discovery)", "Kỹ sư",
   "Xác định board đang cắm là board nào trong registry/dự án khi không khai báo", "Board lạ cắm; Z-04 ảnh board", "UC-J03 có chip_id",
   "BoardPassport ghim hoặc ứng viên chờ chọn", "Hỏi khi nhiều ứng viên", "K3 đề xuất", "S", "M2", "FR-DISCOVER-04, 05", "UR-DT-03", "Dò board",
   [("K", "discover.bus_scan i2c/spi trên board lab (firmware kiểm định)", "bus", "devices", "discover.bus_scan"),
    ("T", "extract.image_board nếu có ảnh", "image", "parts", ""),
    ("T", "discover.board_match tính điểm với registry/templates/BOM", "evidence", "candidates", "discover.board_match"),
    ("N", "Chọn nếu ứng viên điểm gần nhau (một câu hỏi gộp)", "candidates", "board", "T1*")],
   [("A1", "Không ứng viên", "Tạo BoardPassport tạm từ chip + bus scan (bạc) và hỏi schematic")])
uc("UC-K01", "Tác tử tự viết công cụ khi thiếu năng lực", G_K, "Tác tử (Orchestrator, coder)", "Kỹ sư, Pack owner",
   "Một công cụ Python mới, có test, hiệu ứng khai báo, chạy trong sandbox theo chính sách, đăng ký thành năng lực tạm; sau khi chứng minh được thăng cấp", "Chuỗi không tìm được năng lực khớp; năng lực trả lỗi lặp; kỹ sư ra lệnh 'viết cho anh công cụ …'", "Dự án mở; coder khả dụng",
   "tool_id trong .eide/tools; Capability user.* trong registry; ledger; (tùy) đề xuất thăng cấp", "G-TOOL (POL-17 TOOL-*); tool.promote T2", "K5 thủ tục (công cụ), K7 (CapabilityRun)", "M", "M1", "FR-TOOL-01…10", "UR-NL-06", "Công cụ tự tạo",
   [("T", "tool.need: nhận diện nhu cầu, viết ToolSpec (vào/ra/effects/deps/acceptance); tool.search tái dùng nếu có", "gap", "ToolSpec", "tool.need"),
    ("T", "tool.write: coder sinh tool.py + test; kiểm tĩnh import theo effects", "ToolSpec", "code, tests", "tool.write"),
    ("K", "tool.test trong sandbox: pytest + giám sát hiệu ứng thực tế ⊆ khai báo", "tool", "ToolReport, effects_ok", "tool.test"),
    ("T", "Thất bại → tool.repair ≤ 3 vòng", "report", "code'", "tool.repair"),
    ("K", "tool.register: khai báo Capability user.<name> (risk từ effects, tier, undo); nạp nóng registry", "tool", "USER-nn", "tool.register"),
    ("K", "tool.run trong chuỗi: policy G-TOOL (TOOL-01…05) → sandbox theo effects → kết quả → ledger", "args", "result", "G-TOOL"),
    ("N", "Chỉ khi hiệu ứng hệ thống/phần cứng ngoài lab hoặc chưa đủ lịch sử: duyệt/từ chối; xem mã và test trong ToolForge", "ASK", "decision", "TOOL-05/TOOL-99"),
    ("T", "Sau ≥ 3 lần ok: tool.promote đề xuất gói kind=tool → Pack owner duyệt → năng lực chính thức; hoặc tool.deprecate", "tool", "proposal", "T2")],
   [("A1", "Hiệu ứng thực tế vượt khai báo", "TOOL-03 REJECT; tool.deprecate tạm; error_ledger; leo thang"), ("A2", "Công cụ cần thư viện ngoài danh sách deps cho phép", "ASK cài (env.install) — gói lạ → người"), ("A3", "Đã có năng lực khớp ≥ 0,8", "Không viết mới; dùng năng lực có sẵn và báo lý do")])
