import Foundation

/// Bảng dịch tiếng Hàn. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let ko: [String: String] = [
        "Bản đã lưu…": "저장된 버전…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "이 문서는 한 번도 저장된 적이 없습니다 — 기록이 없습니다",
        "Chưa có bản đã lưu nào trước đó": "이전에 저장된 버전이 없습니다",
        "Không đọc được bản ấy": "그 버전을 읽을 수 없습니다",
        "Khôi phục bản đã lưu": "저장된 버전 복원",
        "XML: kiểm theo DTD/XSD…": "XML: DTD/XSD로 검증…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "이 Mac에는 libxml2가 없어 XSD 검증을 할 수 없습니다.",
        "Chọn lược đồ XSD để kiểm": "검증에 사용할 XSD 스키마 선택",
        "Hợp lệ theo": "적합:",
        "Plugin chạy xong, không đổi gì": "플러그인이 아무것도 바꾸지 않고 끝났습니다",
        "Chưa cài plugin native nào": "설치된 네이티브 플러그인이 없습니다",
        "Gỡ plugin này": "이 플러그인 제거",
        "Gỡ plugin này?": "이 플러그인을 제거할까요?",
        "Gỡ": "제거",
        "Cài plugin native…": "네이티브 플러그인 설치…",
        "Mở thư mục plugin": "플러그인 폴더 열기",
        "Chọn file .dylib của plugin native": "플러그인의 .dylib 파일 선택",
        "Đã cài:": "설치됨:",
        "Đã gỡ:": "제거됨:",
        "Plugin native…": "네이티브 플러그인…",
        "Chỉ nhận file .dylib.": ".dylib 파일만 받습니다.",
        "Đã có một plugin trùng tên:": "같은 이름의 플러그인이 이미 설치되어 있습니다:",
        "Không chép được plugin:": "플러그인을 복사할 수 없습니다:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "네이티브 플러그인은 직접 내려받은 버전에만 있고 App Store 버전에는 없습니다.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "플러그인 보조 프로세스를 찾을 수 없습니다.",
        "Không khởi động được tiến trình phụ:": "보조 프로세스를 시작할 수 없습니다:",
        "Tiến trình plugin đã dừng giữa chừng.": "플러그인 프로세스가 도중에 멈췄습니다.",
        "Plugin không trả lời kịp — đã dừng nó.": "플러그인이 제때 응답하지 않아 중단했습니다.",
        "Plugin trả lời sai giao thức:": "플러그인이 형식에 맞지 않는 메시지를 보냈습니다:",
        "Plugin báo lỗi:": "플러그인이 오류를 알렸습니다:",
        "Về GEditor": "GEditor 정보",
        "Cài đặt…": "설정…",
        "Thoát GEditor": "GEditor 종료",
        "File": "파일",
        "Tab mới": "새 탭",
        "Đóng tab": "탭 닫기",
        "Tab kế": "다음 탭",
        "Tab trước": "이전 탭",
        "Tài liệu mới": "새 문서",
        "Mở…": "열기…",
        "Mở thư mục làm Workspace…": "폴더를 작업 공간으로 열기…",
        "Mở gần đây": "최근 항목 열기",
        "Lưu": "저장",
        "Lưu thành…": "다른 이름으로 저장…",
        "Cắt khoảng trắng cuối dòng khi lưu": "저장할 때 줄 끝 공백 제거",
        "Theo dõi file (tail -f)": "파일 추적(tail -f)",
        "In…": "프린트…",
        "Mở lại tab vừa đóng": "닫은 탭 다시 열기",
        "Chưa có file nào": "파일이 없습니다",
        "Xoá danh sách": "목록 비우기",
        "Edit": "편집",
        "Hoàn tác": "실행 취소",
        "Làm lại": "다시 실행",
        "Cắt": "오려두기",
        "Sao chép": "복사하기",
        "Dán": "붙여넣기",
        "Lịch sử clipboard…": "클립보드 기록…",
        "Column Editor…": "열 편집기…",
        "Chọn lần kế tiếp": "다음 일치 항목 선택",
        "Chọn tất cả": "전체 선택",
        "Nhân đôi dòng": "줄 복제",
        "Xóa dòng": "줄 삭제",
        "Comment dòng": "줄 주석 처리",
        "Chưa chép gì trong phiên này": "이번 세션에서 복사한 것이 없습니다",
        "Xoá lịch sử": "기록 지우기",
        "Search": "검색",
        "Tìm…": "찾기…",
        "Tìm và thay…": "찾아 바꾸기…",
        "Tìm trong thư mục…": "폴더에서 찾기…",
        "Thay trong thư mục…": "폴더에서 바꾸기…",
        "Kết quả kế": "다음 결과",
        "Kết quả trước": "이전 결과",
        "Đi tới dòng…": "줄로 이동…",
        "Nhảy tới ngoặc khớp": "짝이 되는 괄호로 이동",
        "Đánh dấu mọi dòng khớp…": "일치하는 모든 줄에 표시…",
        "Đảo dấu": "표시 반전",
        "Bỏ mọi dấu": "모든 표시 지우기",
        "Chép dòng đã đánh dấu": "표시한 줄 복사",
        "Xóa dòng đã đánh dấu": "표시한 줄 삭제",
        "Chỉ giữ dòng đã đánh dấu": "표시한 줄만 남기기",
        "Lines": "줄",
        "Sắp xếp A→Z": "가나다순 정렬",
        "Sắp xếp Z→A": "역순 정렬",
        "Sắp xếp tự nhiên": "자연 정렬",
        "Khử trùng lặp": "중복 제거",
        "Đảo thứ tự dòng": "줄 순서 뒤집기",
        "Dời dòng lên": "줄 위로 이동",
        "Dời dòng xuống": "줄 아래로 이동",
        "Ghép dòng": "줄 합치기",
        "Tách dòng theo độ dài…": "길이로 줄 나누기…",
        "Tách dòng theo ký tự…": "문자로 줄 나누기…",
        "Xóa dòng rỗng": "빈 줄 삭제",
        "Nén dòng trống liên tiếp": "연속된 빈 줄 줄이기",
        "Cắt khoảng trắng cuối dòng": "줄 끝 공백 제거",
        "Tab → Space": "Tab → 공백",
        "Space → Tab": "공백 → Tab",
        "HOA": "대문자",
        "thường": "소문자",
        "Chữ Hoa Đầu Từ": "각 단어 첫 글자 대문자",
        "Chữ hoa đầu câu": "문장 첫 글자 대문자",
        "Đảo hoa/thường": "대소문자 뒤집기",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: 시트 선택…",
        "Xem dạng bảng / văn bản": "표 / 텍스트 보기 전환",
        "Xóa cột…": "열 삭제…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "데이터 검증(열 수 · 자료형)",
        "Bàn làm sạch dữ liệu…": "데이터 정리 작업대…",
        "Chạy công thức làm sạch…": "정리 레시피 실행…",
        "Chuyển đổi…": "변환…",
        "Đổi dấu phân tách…": "구분자 바꾸기…",
        "Xuất sang JSON…": "JSON으로 내보내기…",
        "Format": "포맷",
        "Bảng mã…": "인코딩…",
        "Xuống dòng…": "줄바꿈…",
        "Chuẩn hóa Unicode…": "유니코드 정규화…",
        "JSON: định dạng lại": "JSON: 정렬해 보기 좋게",
        "JSON: thu gọn một dòng": "JSON: 한 줄로 압축",
        "JSON: sắp xếp khóa": "JSON: 키 정렬",
        "JSON: truy vấn JSONPath…": "JSON: JSONPath 질의…",
        "CSV: truy vấn SQL…": "CSV: SQL 질의…",
        "Truy vấn SQL": "SQL 질의",
        "Đang chạy…": "실행 중…",
        "Xuất ra tab mới": "새 탭으로 내보내기",
        "Tài liệu rỗng — không có bảng để truy vấn": "문서가 비어 있습니다 — 질의할 표가 없습니다",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "CSV 표가 아닙니다 — 첫 줄에 열이 하나뿐입니다",
        "Không đọc được câu truy vấn": "질의를 읽을 수 없습니다",
        "Không kiểm được câu truy vấn": "질의를 검사할 수 없습니다",
        "Vàng (mặc định)": "노랑(기본값)",
        "Xanh dương": "파랑",
        "Xanh lá": "초록",
        "Vàng đất": "황토색",
        "Tím": "보라",
        "Hồng": "분홍",
        "Xanh ngọc": "청록",
        "Cam": "주황",
        "Xám lam": "슬레이트",
        "Văn bản": "텍스트",
        "Dãy số": "숫자 연속값",
        "Dãy ngày": "날짜 연속값",
        "Chữ HOA (hex)": "대문자(16진수)",
        "Bắt đầu": "시작",
        "Bước": "증가폭",
        "Đệm 0 tới": "0으로 채울 자릿수",
        "Hệ": "진법",
        "Ngày đầu": "첫 날짜",
        "Định dạng": "형식",
        "Chèn": "삽입",
        "Huỷ": "취소",
        "Chuyển đổi định dạng": "형식 변환",
        "Xem trước 5 hàng đầu": "첫 5행 미리보기",
        "Tạo tab mới": "새 탭에서 열기",
        "Lưu ra file…": "파일로 저장…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "결과는 저장되지 않은 새 탭에서 열립니다. 원본 문서는 그대로입니다.",
        "Chạy trên tài liệu này": "이 문서에 실행",
        "Chạy trên thư mục…": "폴더에 실행…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "레시피 전체가 실행 취소 한 단계입니다. 저장하기 전까지 디스크의 파일은 그대로입니다.",
        "tắt": "끔",
        "không thấy cột": "열을 찾을 수 없음",
        "sẵn sàng": "준비됨",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "앱을 끝낼 때까지 CPU 코어 하나를 계속 차지합니다.",
        "Script không trả về gì": "스크립트가 아무것도 반환하지 않았습니다",
        "Không dựng được máy JavaScript": "JavaScript 엔진을 만들 수 없습니다",
        "Lỗi JavaScript không rõ": "알 수 없는 JavaScript 오류",
        "Bảng": "표",
        "Áp sắp xếp vào file": "정렬을 파일에 적용",
        "Chuyển đổi ▾": "변환 ▾",
        "Xuất dòng khớp": "일치하는 행 내보내기",
        "Ẩn cột này": "이 열 숨기기",
        "Đổi tên tiêu đề…": "머리글 이름 바꾸기…",
        "Chèn cột trống bên trái": "왼쪽에 빈 열 삽입",
        "Chèn cột trống bên phải": "오른쪽에 빈 열 삽입",
        "Xóa cột này khỏi file…": "이 열을 파일에서 삭제…",
        "Phải còn ít nhất một cột đang hiện": "적어도 한 열은 보이도록 남겨야 합니다",
        "Đang sắp xếp…": "정렬 중…",
        "Trở về thứ tự trong file": "파일의 순서로 되돌리기",
        "trăm hàng đầu": "첫 100행",
        "chọn cột": "열 고르기",
        "đặt tên cột kết quả": "결과 열 이름 짓기",
        "lọc theo chữ": "텍스트로 거르기",
        "ô rỗng": "빈 셀",
        "ghép điều kiện": "조건 결합하기",
        "đếm hàng": "행 세기",
        "gộp nhóm": "묶어서 집계하기",
        "nhỏ nhất, lớn nhất": "최솟값, 최댓값",
        "sắp xếp và cắt": "정렬하고 개수 자르기",
        "tên cột có dấu cách": "공백이 있는 열 이름",
        "Truy vấn bị dừng giữa chừng": "질의가 중단되었습니다",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "지원하지 않음: JOIN · 하위 질의 · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · 윈도우 함수",
        "XML: định dạng lại": "XML: 정렬해 보기 좋게",
        "XML: thu gọn một dòng": "XML: 한 줄로 압축",
        "XML: kiểm cú pháp": "XML: 문법 검사",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: 중복 키와 들여쓰기 검사",
        "View": "보기",
        "Ẩn/hiện sidebar (Function List)": "사이드바(함수 목록) 보기/숨기기",
        "Ẩn/hiện bản đồ tài liệu": "문서 지도 보기/숨기기",
        "Gấp / mở khối tại con nháy": "커서 위치의 블록 접기 / 펼치기",
        "Gấp tất cả": "모두 접기",
        "Bỏ gấp tất cả": "모두 펼치기",
        "Gấp theo cấp": "단계별로 접기",
        "Cấp %d": "%d단계",
        "Đã gấp %d khối ở cấp %d": "%2$d단계에서 블록 %1$d개를 접었습니다",
        "Tài liệu này chỉ sâu %d cấp": "이 문서는 %d단계 깊이밖에 되지 않습니다",
        "mermaid: không đọc được bản kê": "mermaid: 매니페스트를 읽을 수 없습니다",
        "Kiểm tra bản cập nhật…": "업데이트 확인…",
        "Kiểm tra bản cập nhật": "업데이트 확인",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store 버전은 GEditor가 아니라 Mac App Store를 통해 업데이트됩니다.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "이 빌드에는 업데이트 서명 키가 없어 확인할 수 없습니다.",
        "Phóng to chữ": "글자 크게",
        "Thu nhỏ chữ": "글자 작게",
        "Cỡ chữ gốc": "실제 크기",
        "Chia đôi theo chiều dọc": "세로로 나누기",
        "Chia đôi theo chiều ngang": "가로로 나누기",
        "Bỏ chia đôi": "나누기 닫기",
        "Mở tab này ở nửa kia": "이 탭을 다른 쪽에서 열기",
        "Nhảy sang nửa kia": "다른 쪽으로 이동",
        "Ngắt dòng (tắt / cửa sổ / cột)": "줄바꿈(끔 / 창 / 열)",
        "Ngắt dòng tại cột…": "지정한 열에서 줄바꿈…",
        "Đánh dấu dòng này": "이 줄에 표시",
        "Dấu kế tiếp": "다음 표시",
        "Dấu trước đó": "이전 표시",
        "Màu đánh dấu…": "표시 색상…",
        "Hiện tất cả ký tự ẩn": "보이지 않는 문자 모두 표시",
        "  Khoảng trắng": "  공백",
        "  Tab": "  탭",
        "  Xuống dòng": "  줄바꿈",
        "  NBSP · zero-width · điều khiển": "  NBSP · 너비 0 · 제어 문자",
        "Xem nhị phân": "바이너리 보기",
        "Chế độ CSV (tô màu theo cột)": "CSV 모드(열별 색상)",
        "Macro": "매크로",
        "Bắt đầu / dừng ghi": "기록 시작 / 중지",
        "Phát lại": "재생",
        "Phát nhiều lần…": "여러 번 재생…",
        "Phát đến cuối tài liệu": "문서 끝까지 재생",
        "Chạy trên mọi tab": "모든 탭에서 실행",
        "Hủy macro đang chạy": "실행 중인 매크로 취소",
        "Lưu macro…": "매크로 저장…",
        "Macro đã lưu…": "저장된 매크로…",
        "Help": "도움말",
        "Trợ giúp GEditor": "GEditor 도움말",
        "Giới thiệu tính năng": "기능 소개",
        "Di cư từ Notepad++": "Notepad++에서 옮겨오기",
        "Tìm": "찾기",
        "Thay bằng": "바꿀 내용",
        "Kế": "다음",
        "Trước": "이전",
        "Đếm": "개수",
        "Đóng": "닫기",
        "Kiểm theo JSON Schema…": "JSON 스키마로 검증…",
        "Chọn tệp JSON Schema": "JSON 스키마 파일 선택",
        "Không thấy lỗi nào theo schema này.": "이 스키마에 비추어 문제를 찾지 못했습니다.",
        "JSON Schema": "JSON 스키마",
        "Kiểm cú pháp đồ thị": "그래프 문법 검사",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "그래프 형식을 알아볼 수 없습니다 — .dot, .gv, .cypher, .ttl 또는 .graphml 확장자가 필요합니다.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "%@ 문법 오류를 찾지 못했습니다(이 검사는 완전하지 않습니다).",
        "Cú pháp %@": "%@ 문법",
        "không phải một đối tượng JSON": "JSON 객체가 아닙니다",
        "Khai phá văn bản (n-gram, TF-IDF)": "텍스트 마이닝(n-그램, TF-IDF)",
        "Tài liệu rỗng.": "문서가 비어 있습니다.",
        "Không rút được từ khoá nào.": "키워드를 하나도 뽑아내지 못했습니다.",
        "Từ khoá": "키워드",
        "%d từ khoá · %d token · %d tài liệu": "키워드 %d개 · 토큰 %d개 · 문서 %d건",
        "Tô lên tài liệu": "문서에 표시하기",
        "Đánh dấu entity từ danh sách…": "목록에서 개체 표시…",
        "Chọn danh sách entity (CSV hoặc JSON)": "개체 목록 선택(CSV 또는 JSON)",
        "Không đọc được danh sách entity.": "개체 목록을 읽을 수 없습니다.",
        "Danh sách entity rỗng.": "개체 목록이 비어 있습니다.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "문서에서 개체를 찾지 못했습니다(%d개 불러옴).",
        "%d lần xuất hiện · %@": "%d번 나타남 · %@",
        "Chuyển đổi tri thức…": "지식 변환…",
        "Chuyển đổi: %@ → %@": "변환: %@ → %@",
        "Không chuyển đổi được.": "변환할 수 없습니다.",
        "Xem trước cắt chunk…": "청크 나누기 미리보기…",
        "Cỡ cố định 800B, chồng 100B": "고정 크기 800B, 겹침 100B",
        "Theo câu (≤ 800B)": "문장 단위(≤ 800B)",
        "Theo heading Markdown": "Markdown 제목 단위",
        "Tài liệu rỗng — không có chunk nào.": "문서가 비어 있습니다 — 청크가 없습니다.",
        "%d chunk · trung bình %d B · %@": "청크 %d개 · 평균 %dB · %@",
        "Xuất JSONL": "JSONL 내보내기",
        "Chunk JSONL": "청크 JSONL",
        "Mở triple/edge dạng bảng": "트리플/간선을 표로 열기",
        "Bảng triple": "트리플 표",
        "Tài liệu này không có dòng triple nào.": "이 문서에는 트리플 줄이 없습니다.",
        "Không đọc được triple nào — dòng %d: %@": "트리플을 하나도 읽지 못했습니다 — %d번째 줄: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "트리플 %1$d개를 읽음 · 잘못된 줄 %2$d개 건너뜀(첫 번째: %3$d번째 줄)",
        "Trùng lặp mờ theo cột…": "열별 유사 중복…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "유사 중복 — 열 「%1$@」: 후보 그룹 %2$d개",
        "Gộp": "병합",
        "Giống": "일치",
        "Các giá trị trong cụm": "그룹 안의 값",
        "Gộp về": "병합 대상",
        "Gộp các cụm đã chọn": "선택한 그룹 병합",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "선택한 그룹이 없습니다 — 「병합」을 눌러도 아무것도 바뀌지 않습니다. 앱이 스스로 병합하는 일은 없습니다.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "그룹 %d개 선택 · %d행이 바뀝니다 · 실행 취소 한 단계",
        "Không quét được cột này.": "이 열을 훑을 수 없습니다.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "열 「%@」에는 유사 중복 그룹이 없습니다.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "병합된 그룹이 없습니다 — 문서는 그대로입니다.",
        "Khử trùng lặp mờ · cột %@": "유사 중복 제거 · 열 %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "그룹 %d개 병합 · 셀 %d개 변경",
        "Báo cáo làm sạch": "정리 보고서",
        "# Báo cáo làm sạch — %@\n\n": "# 정리 보고서 — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## 적용됨(%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_적용된 단계가 없습니다._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## 데이터 프로파일\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_열 %1$d개 · 행 %2$d개 · %3$.1f초 동안 훑음_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| 열 | 자료형 | NULL | 고유값 | 최소 | 최대 | 평균 |\n",
        "\n### Giá trị bất thường\n\n": "\n### 이상값\n\n",
        "hàng %d: %@": "%d번째 행: %@",
        "- cột «%@» — %d ô: %@\n": "- 열 「%1$@」— 셀 %2$d개: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## 남음(%d)\n\n",
        "_Không còn phát hiện nào._\n": "_남은 지적 사항이 없습니다._\n",
        "- cột «%@»: %@\n": "- 열 「%@」: %@\n",
        "Cắt khoảng trắng khi lưu": "저장할 때 공백 제거",
        "Chuẩn hóa xuống dòng": "줄바꿈 정규화",
        "trước đó": "이전",
        "Không mở lại được thư mục «%@» của phiên trước": "지난 세션의 폴더 「%@」를 다시 열 수 없습니다",
        " (và %d file khác)": "(그리고 파일 %d개 더)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "탭 %d개를 다시 열 수 없습니다: %@%@ — 파일이 원래 자리에 없습니다.",
        "Không đọc được nội dung từ ống dẫn": "파이프에서 입력을 읽을 수 없습니다",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "저장할 때마다 줄 끝 공백을 제거합니다",
        "Không cắt khoảng trắng khi lưu nữa": "저장할 때 더 이상 공백을 제거하지 않습니다",
        "Chưa đặt tên.txt": "제목 없음.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "인코딩을 바꾸면 문자가 사라집니다",
        "Vẫn lưu": "그래도 저장",
        "Tài liệu có thay đổi chưa lưu": "문서에 저장하지 않은 변경 사항이 있습니다",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "저장하지 않고 닫으면 변경 사항이 사라집니다.",
        "Bỏ thay đổi": "변경 사항 버리기",
        "Đi tới dòng": "줄로 이동",
        "Tài liệu có %d dòng.": "이 문서는 %d줄입니다.",
        "Số dòng": "줄 번호",
        "Đi tới": "이동",
        "Diễn giải lại theo…": "다른 인코딩으로 다시 해석…",
        "Chuyển đổi sang…": "다음으로 변환…",
        "Không diễn giải lại được": "다시 해석할 수 없습니다",
        "Bảng mã %@ không chứa hết ký tự": "%@ 로는 모든 문자를 나타낼 수 없습니다",
        "Vẫn chọn": "그래도 선택",
        "Cột %d": "%d번째 열",
        "Cột %d: %@": "%d번째 열: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "숨긴 열: %@(%d) — 머리글 행의 컨텍스트 메뉴에서 되돌릴 수 있습니다",
        "Hiện lại: %@": "다시 보이기: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "열 %@ 를 숨겼습니다 — 파일 안에는 그대로 있습니다",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "%@ %@ 기준 정렬 · 표시만",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "정렬됨: %@ %@(표시만)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d행 이상 일치 — 계속 찾는 중…",
        "%d / %d dòng khớp": "%d / %d행 일치",
        "Không tìm thấy lỗi trong %d hàng": "%d행에서 문제를 찾지 못했습니다",
        "%d hàng lệch số cột": "열 개수가 맞지 않는 행 %d개",
        "%d ô sai kiểu dữ liệu": "자료형이 맞지 않는 셀 %d개",
        " (đã dừng ở %d lỗi đầu)": "(처음 %d개 문제에서 멈췄습니다)",
        "   —   kiểu nhận ra: ": "   —   알아낸 자료형: ",
        "Hàng %d, cột %@: «%@» không phải %@": "%1$d번째 행, 열 %2$@: 「%3$@」는 %4$@ 가 아닙니다",
        "Column Editor — %d dòng": "열 편집기 — %d줄",
        "Phát hiện": "지적 사항",
        "Hồ sơ dữ liệu": "데이터 프로파일",
        "Hồ sơ dữ liệu — đang quét…": "데이터 프로파일 — 훑는 중…",
        "Lưu công thức…": "레시피 저장…",
        "Xuất báo cáo": "보고서 내보내기",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "적용한 그룹이 없습니다 · 각 그룹이 실행 취소 한 단계입니다",
        "quá nhiều giá trị": "값이 너무 많습니다",
        "hay gặp: ": "자주 나옴: ",
        "Giá trị điền vào ô thiếu": "빈 셀을 채울 값",
        "Áp dụng": "적용",
        "Không dựng được bản xem trước": "미리보기를 만들 수 없습니다",
        "· giữ nguyên, không đọc được ·": "· 읽을 수 없어 그대로 둠 ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "열을 ISO 8601(YYYY-MM-DD)로 변환",
        "Quy ước số cho cả cột": "열 전체의 숫자 표기 규칙",
        "Làm gì với ô thiếu": "빈 셀을 어떻게 할지",
        "Chuẩn hóa về ISO 8601": "ISO 8601로 정규화",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "모호한 셀은 일(日)을 먼저 읽기(31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "모호한 셀은 월(月)을 먼저 읽기(12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "모호한 셀은 건너뛰고 확실한 것만 고치기",
        "Về Việt/Âu (1.234,56)": "베트남/유럽식으로(1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "영미식으로(1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "영미식으로, 천 단위 구분 없이(1234.56)",
        "Điền một giá trị mặc định…": "기본값으로 채우기…",
        "Điền xuôi — lấy giá trị phía trên": "아래로 채우기 — 위의 값 가져오기",
        "Điền ngược — lấy giá trị phía dưới": "위로 채우기 — 아래의 값 가져오기",
        "Xóa hàng có ô thiếu ở cột này": "이 열이 빈 행 삭제",
        "Cắt khoảng trắng hai đầu": "양끝 공백 제거",
        "Cắt hai đầu và nén khoảng trắng bên trong": "양끝을 제거하고 안쪽 공백 줄이기",
        "Pivot…": "피벗…",
        "Nguồn…": "원본…",
        "Pivot — gộp theo cột": "피벗 — 열로 묶기",
        "Hàng (gộp nhóm)": "행(묶기)",
        "Giá trị": "값",
        "+ Hàng": "+ 행",
        "+ Giá trị": "+ 값",
        "Xoá hết": "모두 지우기",
        "Đưa vào ô truy vấn": "질의 칸에 넣기",
        "Chọn cột để dựng câu truy vấn.": "질의를 만들 열을 고르세요.",
        "Không đọc được tên cột của bảng này.": "이 표의 열 이름을 읽을 수 없습니다.",
        "Nguồn dữ liệu của truy vấn": "질의의 데이터 원본",
        "«%@» — tài liệu đang mở": "「%@」— 열려 있는 문서",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ 등록한 뒤 파일이 바뀌었습니다",
        "Thêm file…": "파일 추가…",
        "Bỏ hết": "모두 빼기",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "「%@」에서 표 이름을 끌어낼 수 없습니다 — 파일 이름을 바꾸세요.",
        "Tổng": "합계",
        "Trung bình": "평균",
        "Nhỏ nhất": "최소",
        "Lớn nhất": "최대",
        "Đếm khác nhau": "고유값 개수",
        "Biểu đồ": "차트",
        "Xuất PNG": "PNG 내보내기",
        "Xuất SVG": "SVG 내보내기",
        "Bảng này không có cột số nào để vẽ.": "이 표에는 그릴 수 있는 숫자 열이 없습니다.",
        "Không dựng được ảnh PNG.": "PNG 이미지를 만들 수 없습니다.",
        "Kết quả truy vấn": "질의 결과",
        "Đã lưu %@": "%@ 저장됨",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "「%2$@」의 %1$@ 차트 — 점 %3$d개, 값은 %4$@ 부터 %5$@ 까지",
        "Cột": "막대",
        "Đường": "선",
        "Phân bố": "히스토그램",
        "Phân tán": "산점도",
        "Hộp": "상자",
        "CSV: chất lượng dữ liệu…": "CSV: 데이터 품질…",
        "Chất lượng dữ liệu": "데이터 품질",
        "Xuất vi phạm ra tab mới": "위반 항목을 새 탭으로 내보내기",
        "Mức": "수준",
        "Luật": "규칙",
        "Vi phạm": "위반",
        "Tỷ lệ": "비율",
        "đạt": "통과",
        "lỗi": "오류",
        "cảnh báo": "경고",
        "hỏng": "손상",
        "Đã đánh dấu %d dòng vi phạm": "위반한 줄 %d개에 표시했습니다",
        "Xu hướng": "추이",
        "Lúc chấm": "채점 시각",
        "Số hàng": "행 수",
        "Lệch": "차이",
        "Luật trượt": "통과하지 못한 규칙",
        "Điểm chất lượng": "품질 점수",
        "Điểm theo thời gian": "시간에 따른 점수",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "아직 기록이 없습니다 — 채점할 때마다 ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "규칙 옆의 「.history.jsonl」 파일에 한 줄씩 덧붙입니다.",
        "%d mốc trong lịch sử": "기록에 %d개 지점",
        " · %d dòng KHÔNG đọc được": " · %d줄을 읽을 수 없음",
        " · chọn hai dòng để so": " · 비교할 두 행을 선택하세요",
        "điểm %+.1f": "점수 %+.1f",
        "không chiều nào tụt": "떨어진 항목이 없습니다",
        "tụt: ": "떨어짐: ",
        "%d luật mới trượt: %@": "새로 통과하지 못한 규칙 %d개: %@",
        "số hàng %+d": "행 수 %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": "(「추이」 탭에 경고가 %d개 더 있습니다)",
        "Không sửa tự động được: ": "자동으로 고칠 수 없습니다: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "정리 작업대의 해당 도구를 열고, 끝나면 바로 다시 채점합니다.",
        "Xử lý giá trị thiếu…": "빠진 값 처리…",
        "Chuẩn hóa ngày…": "날짜 정규화…",
        "Khử trùng lặp…": "중복 제거…",
        "Thay thế…": "바꾸기…",
        "Xem các dòng sai": "잘못된 행 보기",
        "Không tìm thấy cột «%@» trong bảng này.": "이 표에는 열 「%@」가 없습니다.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "중복을 제거했습니다 — 「%@」는 이제 고유합니다. 점수: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "중복을 제거했지만 「%1$@」에는 아직 중복 행이 %2$d개 있습니다(이전: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "그 행들은 키는 같지만 줄 전체가 같지는 않으므로, 직접 보고 골라야 합니다 ",
        "giữ hàng nào.": "어느 것을 남길지.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "이 규칙을 어기는 값을 하나도 읽지 못했습니다.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "열 「%2$@」에 잘못된 값이 %1$d개 — 「바꾸기」를 채우고 미리보기를 누르세요",
        "Đã chấm lại: %.0f/100": "다시 채점했습니다: %.0f/100",
        "Xem trước báo cáo": "보고서 미리보기",
        "Tham số…": "매개변수…",
        "Xuất HTML…": "HTML로 내보내기…",
        "In / PDF…": "프린트 / PDF…",
        "%d khối chạy được · %d khối HỎNG": "블록 %d개 실행 · 블록 %d개 실패",
        "%d khối chạy được": "블록 %d개 실행",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · 데이터가 오래됨 — 원본 파일이 바뀌었습니다. 다시 만드세요",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "보고서 미리보기에는 .%@ 문서가 필요합니다",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "데이터 원본을 찾지 못했습니다 — frontmatter에 「source: 파일.csv」를 적으세요.",
        "Không dựng được báo cáo.": "보고서를 만들 수 없습니다.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "이 보고서의 frontmatter에는 매개변수가 하나도 없습니다.",
        "Tham số báo cáo": "보고서 매개변수",
        "Dựng lại": "다시 만들기",
        "Đã xuất %@": "%@ 내보냄",
        "Báo cáo: xem trước": "보고서: 미리보기",
        "Báo cáo: sinh loạt…": "보고서: 일괄 생성…",
        "không phải tài liệu .greport.md": ".greport.md 문서가 아닙니다",
        "không phân tích được báo cáo": "보고서를 해석할 수 없습니다",
        "không tìm được dữ liệu nguồn": "원본 데이터를 찾을 수 없습니다",
        "không đọc được danh sách tham số": "매개변수 목록을 읽을 수 없습니다",
        "Sinh loạt cần tài liệu đuôi .%@": "일괄 생성에는 .%@ 문서가 필요합니다",
        "Chọn danh sách tham số (CSV hoặc JSON)": "매개변수 목록 선택(CSV 또는 JSON)",
        "Chọn thư mục để ghi %d báo cáo": "보고서 %d개를 넣을 폴더 선택",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "빠진 매개변수 ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "원본 파일 자신을 가리킵니다 — 덮어쓰기를 거부했습니다",
        "%d khối HỎNG": "블록 %d개 실패",
        "Sinh loạt xong: %d tệp · %d hỏng": "일괄 처리 완료: 파일 %d개 · 실패 %d개",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "매개변수 묶음 %d개를 만들지 못했습니다 — 요약을 보세요",
        "Sơ đồ Mermaid: xem trước": "Mermaid 다이어그램: 미리보기",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid 다이어그램: 템플릿 삽입…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid 다이어그램: 다시 정렬",
        "Nền trong suốt": "투명한 배경",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "이 Mac에서는 다이어그램을 PNG로 변환할 수 없습니다 — macOS 13이 필요합니다. SVG 내보내기는 됩니다.",
        "Lưu PNG %@…": "PNG %@ 저장…",
        "Lưu SVG…": "SVG 저장…",
        "Chép ảnh vào clipboard": "이미지를 클립보드로 복사",
        "Màu thương hiệu…": "브랜드 색상…",
        "Màu thương hiệu cho sơ đồ": "다이어그램의 브랜드 색상",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "각 칸은 #rrggbb 형식의 색입니다. 「themes/mermaid-brand.json」에 저장되며 다른 Mac으로 복사할 수 있습니다.",
        "Màu chính": "주 색상",
        "Chữ trên nút": "노드 위의 글자",
        "Viền": "테두리",
        "Đường nối": "연결선",
        "Nền khi xuất ảnh": "내보낼 때의 배경",
        "Lưu và chèn %%{init}%% vào tài liệu": "저장하고 %%{init}%% 를 문서에 삽입",
        "Đã lưu màu thương hiệu": "브랜드 색상을 저장했습니다",
        "Đã chép ảnh sơ đồ vào clipboard": "다이어그램 이미지를 클립보드로 복사했습니다",
        "Đã lưu %@ — %@": "%@ 저장됨 — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "이 다이어그램에는 이미 %%{init}%% 지시자가 있습니다 — 당신의 것은 그대로 둡니다.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% 를 삽입했습니다 — 이제 다이어그램이 자체 색상을 갖습니다",
        "Chèn màu thương hiệu vào sơ đồ": "다이어그램에 브랜드 색상 삽입",
        "Định dạng sơ đồ Mermaid": "Mermaid 다이어그램 다시 정렬",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "다이어그램 소스가 이미 깔끔합니다 — 바꿀 것이 없습니다",
        "Đã định dạng lại sơ đồ": "다이어그램을 다시 정렬했습니다",
        "Đã định dạng lại %d sơ đồ": "다이어그램 %d개를 다시 정렬했습니다",
        "Thư viện mẫu sơ đồ": "다이어그램 템플릿 라이브러리",
        "Mẫu sơ đồ đầy đủ": "완전한 다이어그램 템플릿",
        "Mẩu cú pháp": "문법 조각",
        "Đang soạn: %@": "편집 중: %@",
        "Đã chèn mẫu «%@»": "템플릿 「%@」를 삽입했습니다",
        "Tài liệu đang ở chế độ chỉ đọc.": "이 문서는 읽기 전용입니다.",
        "Sơ đồ Mermaid": "Mermaid 다이어그램",
        "Tài liệu chưa có khối mermaid nào.": "이 문서에는 mermaid 블록이 없습니다.",
        "Thương hiệu": "브랜드",
        "Xuất…": "내보내기…",
        "Chưa có sơ đồ nào": "아직 다이어그램이 없습니다",
        "%d sơ đồ · %@": "다이어그램 %d개 · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "다이어그램 %1$d/%2$d개 실패 — %3$d번째 다이어그램%4$@",
        ", dòng %d": ", %d번째 줄",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "이 문서에는 ```mermaid 블록이 없고 .mmd 파일도 아닙니다.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "아직 그리기를 마친 다이어그램이 없습니다.",
        "Không tìm thấy «%@» trong mã sơ đồ": "다이어그램 소스에서 「%@」를 찾을 수 없습니다",
        "không dựng được hàng rào chặn mạng cho WKWebView": "WKWebView용 네트워크 차단을 만들 수 없습니다",
        "Luật kết hợp": "연관 규칙",
        "Mỗi dòng một giỏ": "한 행에 장바구니 하나",
        "Hai cột: mã · item": "두 열: 식별자 · 항목",
        "Dạng dữ liệu giao dịch": "거래 데이터의 형태",
        "Cột giỏ hàng hoặc mã giao dịch": "장바구니 열 또는 거래 식별자 열",
        "Cột item": "항목 열",
        "Ký tự phân tách item": "항목 구분 문자",
        "Support tối thiểu, phần trăm": "최소 support, 퍼센트",
        "Confidence tối thiểu, phần trăm": "최소 confidence, 퍼센트",
        "Tách bởi:": "구분:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "연관 규칙 표",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "주의",
        "%d giao dịch · %d item · %d luật": "거래 %d건 · 항목 %d개 · 규칙 %d개",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — 기준을 넘은 규칙이 없습니다. support나 confidence를 낮추세요",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — 일찍 멈췄습니다. 표가 완전하지 않습니다",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d건의 거래가 양쪽을 모두 담고 있습니다",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "두 열 형태에서는 서로 다른 두 열을 골라야 합니다.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "「%3$@」를 담은 거래 %2$d건에서 %1$d행에 표시했습니다",
        "CSV: luật kết hợp…": "CSV: 연관 규칙…",
        "Khai phá theo nhóm": "그룹 마이닝",
        "Cột nhóm": "묶기 열",
        "Cột giá trị": "값 열",
        "Cột thứ hai cho tương quan": "상관에 쓸 두 번째 열",
        "Cách xếp hạng": "순위 매기는 방법",
        "Nhóm theo:": "묶기 기준:",
        "Giá trị:": "값:",
        "Xếp theo:": "정렬 기준:",
        "Bảng xếp hạng nhóm": "그룹 순위 표",
        "Nhóm": "그룹",
        "Hàng": "행 수",
        "Hàng rào riêng": "자체 기준선",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r 차이",
        "Ghi chú": "메모",
        "không đo được": "잴 수 없음",
        "%d nhóm · mốc tương quan toàn bộ %@": "그룹 %d개 · 전체 기준 상관 %@",
        " · ĐÃ CẮT %d nhóm": " · 그룹 %d개 제외",
        "Bảng này không có cột chữ nào để gom nhóm.": "이 표에는 묶기에 쓸 텍스트 열이 없습니다.",
        "Bảng này không có cột số nào để khai phá.": "이 표에는 살펴볼 숫자 열이 없습니다.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "그룹 「%2$@」의 %1$d행에 표시했습니다",
        "CSV: khai phá theo nhóm…": "CSV: 그룹 마이닝…",
        "\u{2194}": "↔",
        "Dự báo": "예측",
        "Cột giá trị theo thời gian": "시간에 따른 값 열",
        "Mô hình dự báo": "예측 모형",
        "Số kỳ dự báo": "예측할 기간 수",
        "Kết luận so với baseline": "기준 모형과 비교한 판단",
        "Mô hình:": "모형:",
        "Số kỳ:": "기간:",
        "Chu kỳ:": "계절:",
        "tự": "자동",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "계절 주기. 비워 두면 자동으로 찾습니다",
        "Bảng giá trị dự báo": "예측값 표",
        "Kỳ": "기",
        "Dải 80%": "80% 구간",
        "Dải 95%": "95% 구간",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "계산할 수 없음",
        "Bảng này không có cột số nào để dự báo.": "이 표에는 예측할 숫자 열이 없습니다.",
        "Không dựng được dự báo cho cột này.": "이 열의 예측을 만들 수 없습니다.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "열 「%1$@」에는 숫자 값이 %2$d개뿐입니다 — 예측하려면 적어도 4개가 필요합니다.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# 계열은 파일의 행 순서 그대로 읽습니다 — 다시 정렬하지 않고, 시간 열을 추정하지도 않습니다.\n",
        "Sai số huấn luyện": "학습 오차",
        "CSV: dự báo chuỗi thời gian…": "CSV: 시계열 예측…",
        "Holt-Winters cộng": "Holt-Winters 가법",
        "Holt-Winters nhân": "Holt-Winters 승법",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "군집에 넣을 열",
        "Đường cong WCSS": "WCSS 곡선",
        "Phân cụm": "군집",
        "Chuẩn hoá:": "스케일링:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "적어도 한 열을 고르세요.",
        "Không đủ dữ liệu để dựng đường cong.": "곡선을 그릴 데이터가 부족합니다.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "엘보는 k = %d를 시사합니다. WCSS는 k가 커지면 언제나 줄어들므로, 이는 통계적 기준이 아니라 그래프를 읽는 요령입니다 — 곡선을 보고 꺾임이 뚜렷한지 판단하세요.",
        "WCSS theo k": "k에 따른 WCSS",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k-거리는 eps = %1$@ 를 시사합니다(minPts 기본값은 2 × 열 수 = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "k번째 이웃까지의 거리",
        "Cần ít nhất 2 cột số để phân cụm.": "군집에는 숫자 열이 적어도 2개 필요합니다.",
        "Cụm theo %@ và %@": "%@ 와 %@ 기준 군집",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — 군집은 %d차원에서 찾았고, 그림은 처음 2차원만 보여 줍니다",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# 잡음(cluster_id = -1): %d행\n",
        "CSV: phân cụm…": "CSV: 군집…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- 군집 중심(원래 단위) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "상관 행렬",
        "Phương pháp tương quan": "상관 계산 방법",
        "Tương quan không hàm ý nhân quả.": "상관은 인과를 뜻하지 않습니다.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "가장 강한 짝: %1$@ ↔ %2$@ = %3$@(n = %4$d). 셀을 누르면 산점도를 볼 수 있습니다.",
        "Không cặp nào đo được.": "잴 수 있는 짝이 없습니다.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ (%4$d행 기준)",
        "Cần ít nhất 2 cột số để tính tương quan.": "상관을 구하려면 숫자 열이 적어도 2개 필요합니다.",
        "Không đọc được cột «%@».": "열 「%@」를 읽을 수 없습니다.",
        "CSV: ma trận tương quan…": "CSV: 상관 행렬…",
        "Bất thường": "이상값",
        "Danh sách bất thường": "이상값 목록",
        "Cột:": "열:",
        "Cột số cần xét": "살펴볼 숫자 열",
        "Cách:": "방법:",
        "Phương pháp phát hiện": "탐지 방법",
        "Phương pháp đã dùng": "사용한 방법",
        "Ngưỡng": "기준값",
        "Đánh dấu": "표시",
        "Xuất tab mới": "새 탭으로 내보내기",
        "Dòng": "줄",
        "Điểm": "점수",
        "Vì sao": "이유",
        "nhẹ": "가벼움",
        "vừa": "보통",
        "nặng": "심함",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d행(%.2f%%)",
        "Bảng này không có cột số nào để tìm bất thường.": "이 표에는 이상값을 찾을 숫자 열이 없습니다.",
        "Đã đánh dấu %d dòng bất thường": "이상한 줄 %d개에 표시했습니다",
        "CSV: tìm bất thường…": "CSV: 이상값 찾기…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "규칙 %1$d개, 모두 통과 · %2$d행 · %3$.0f밀리초",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "오류 %1$d개 · 경고 %2$d개, 규칙 %3$d개에 걸쳐 · %4$d행 · %5$.0f밀리초",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "먼저 문서를 저장하세요 — 품질 규칙은 데이터 파일 옆에 있습니다.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "규칙 모음이 아직 없습니다. 파일 %@ 를 만든 뒤 다시 여세요.",
        "Lịch sử": "기록",
        "Câu đã lưu": "저장한 질의",
        "Lưu câu này…": "이 질의 저장…",
        "Lưu câu truy vấn": "질의 저장",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "나중에 찾을 수 있도록 이름을 지으세요. 같은 이름은 덮어씁니다.",
        "Ví dụ: Doanh thu theo tỉnh": "예: 지역별 매출",
        "Chưa nhập giá trị cho tham số: %@": "매개변수에 값을 넣지 않았습니다: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "승인한 뒤 플러그인이 바뀌었습니다 — GEditor는 실행을 거부합니다",
        "Chạy plugin chưa duyệt?": "승인하지 않은 플러그인을 실행할까요?",
        "Tôi tin file này — chạy": "이 파일을 믿습니다 — 실행",
        "KHÔNG có chữ ký": "서명 없음",
        "Chữ ký: %@": "서명: %@",
        "Đường dẫn: %@": "경로: %@",
        "Thay": "바꾸기",
        "Thay tất cả": "모두 바꾸기",
        "Chuỗi thuần": "일반 텍스트",
        "Extended (\\n \\t \\xNN)": "확장(\\n \\t \\xNN)",
        "Biểu thức chính quy": "정규 표현식",
        "Phân biệt hoa thường": "대소문자 구분",
        "Cả từ": "단어 단위",
        "Không có kết quả": "결과가 없습니다",
        "Thử biểu thức chính quy…": "정규 표현식 시험…",
        "Chế độ Log (tô theo mức)": "로그 모드(수준별 색상)",
        "Lọc log theo mức…": "수준으로 로그 거르기…",
        "Chạy trên cả thư mục…": "폴더 전체에 실행…",
        "Lọc qua lệnh ngoài…": "외부 명령으로 거르기…",
        "Script…": "스크립트…",
        "Gói mở rộng…": "확장 패키지…",
        "Cửa sổ mới": "새 창",
        "Tách tab ra cửa sổ mới": "탭을 새 창으로 떼어내기",
        "Chưa mở thư mục nào": "열린 폴더가 없습니다",
        "Tìm file trong thư mục": "폴더에서 파일 찾기",
        "Lọc theo tên": "이름으로 거르기",
        "File mới…": "새 파일…",
        "Thư mục mới…": "새 폴더…",
        "Đổi tên…": "이름 바꾸기…",
        "Chuyển vào Thùng rác": "휴지통으로 이동",
        "Hiện trong Finder": "Finder에서 보기",
        "Đang đọc cấu trúc tài liệu…": "문서 구조를 읽는 중…",
        "file này không có hàm nào": "이 파일에는 함수가 없습니다",
        "Không có gì khớp": "일치하는 것이 없습니다",
        "Văn bản thuần": "일반 텍스트",
        "🔒 Chỉ đọc": "🔒 읽기 전용",
        "Đang theo dõi": "추적 중",
        "ngắt tại cột": "줄바꿈 열",
        "Cú pháp": "문법",
        "Bấm để chèn vào ô truy vấn": "누르면 질의에 삽입됩니다",
        "truy vấn không hợp lệ": "잘못된 질의",
        "khóa `ten` ở gốc": "루트의 「이름」 키",
        "khóa có dấu cách": "공백이 있는 키",
        "phần tử đầu": "첫 번째 요소",
        "mọi phần tử": "모든 요소",
        "lát cắt": "구간",
        "hợp nhiều chỉ số": "인덱스 합집합",
        "mọi khóa `gia` ở mọi tầng": "모든 층의 「가격」 키",
        "mọi nút": "모든 노드",
        "lọc theo số": "숫자로 거르기",
        "lọc theo có mặt": "있는지로 거르기",
        "Tới lỗi đầu tiên": "첫 오류로 이동",
        "Cột doanh_thu là số": "「매출」 열은 숫자입니다",
        "lọc…": "거르기…",
        "Hủy": "취소",
        "Thực hiện thay": "바꾸기 실행",
        "xem trước": "미리보기",
        "tương tác": "대화형",
        "Soạn thảo": "편집",
        "Giao diện": "인터페이스",
        "Phím tắt": "단축키",
        "Cỡ chữ": "글자 크기",
        "Bề rộng TAB": "탭 너비",
        "Thụt lề bằng TAB": "탭으로 들여쓰기",
        "Tự động thụt lề khi xuống dòng": "줄을 바꿀 때 자동으로 들여쓰기",
        "Tô mọi kết quả tìm kiếm": "검색 결과를 모두 강조",
        "Chuẩn hóa về NFC khi lưu": "저장할 때 NFC로 정규화",
        "Ngôn ngữ": "언어",
        "Nền": "모양",
        "Theo hệ thống": "시스템에 맞춤",
        "Sáng": "밝게",
        "Tối": "어둡게",
        "Theme": "테마",
        "Dùng preset Notepad++": "Notepad++ 프리셋 사용",
        "Về phím mặc định": "기본 키로 되돌리기",
        "Mở file cấu hình": "설정 파일 열기",
        "Xuất theme hiện tại": "현재 테마 내보내기",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "언어 변경은 다음에 실행할 때 완전히 적용됩니다.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "기본 키는 다음에 실행할 때 돌아옵니다.",
        "Xem trước Markdown": "Markdown 미리보기",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "미리보기는 시스템의 Markdown 엔진을 씁니다: 아직 표를 그리지 못하고 코드 블록에 색을 입히지도 않습니다.",
        "Thử biểu thức chính quy": "정규 표현식 시험",
        "Biểu thức": "식",
        "Văn bản thử": "시험용 텍스트",
        "Kết quả": "결과",
        "Kết quả khớp": "일치 항목",
        "Biểu thức này làm gì": "이 식이 하는 일",
        "Giải thích biểu thức": "식 설명",
        "Chế độ tìm kiếm": "검색 방식",
        "Kết quả tìm kiếm": "검색 결과",
        "Không khớp chỗ nào": "일치하는 것이 없습니다",
        " (đã cắt bớt)": "(잘림)",
        "Bản đồ tài liệu": "문서 지도",
        "Thanh tab": "탭 막대",
        "Hàng tiêu đề cột": "열 머리글 행",
        "Không có cột nào": "열이 없습니다",
        "Cây thư mục workspace": "작업 공간 트리",
        "Danh sách hàm và lớp": "함수와 클래스 목록",
        "Kết quả tìm trong thư mục": "폴더 검색 결과",
        "Bảng dữ liệu CSV": "CSV 데이터 표",
        "Bàn làm sạch dữ liệu": "데이터 정리 작업대",
        "Truy vấn JSONPath": "JSONPath 질의",
        "Danh sách lỗi dữ liệu": "데이터 오류 목록",
        "Bộ đánh giá golden set…": "골든셋 평가기…",
        "So với điểm ngoài (JSONL)…": "외부 점수와 비교(JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "외부 점수 파일 선택(JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "선택한 노드 이름 바꾸기",
        "Gộp các node đang chọn": "선택한 노드 병합",
        "Tách node đang chọn": "선택한 노드 나누기",
        "Trích subgraph đang chọn ra tab mới": "선택한 부분 그래프를 새 탭으로 뽑아내기",
        "Không có gì để đổi": "바꿀 것이 없습니다",
        "%@ — áp %d thay đổi?": "%1$@ — 변경 %2$d건을 적용할까요?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: 변경 %2$d건 · Cmd-Z로 한 묶음을 되돌립니다",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "커서를 정확히 노드 하나에 두고 다시 하세요",
        "Đổi tên «%@»": "「%@」 이름 바꾸기",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "이 노드를 가리키는 모든 간선과 레이블도 함께 바뀝니다.",
        "Đổi tên node": "노드 이름 바꾸기",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "노드를 둘 이상 선택하고 다시 하세요",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "표준형 「%@」— 가장 흔하고, 가장 길고, 부호가 붙은 것",
        "Gộp node": "노드 병합",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "옮길 간선 줄을 선택하고 다시 하세요",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "선택한 모든 줄이 정확히 노드 하나에 닿아야 합니다 — 간선 줄을 더 선택하세요",
        "Tách «%@» — chuyển %d cạnh": "「%1$@」 나누기 — 간선 %2$d개 옮김",
        "Cạnh tới: %@": "%@ 로 가는 간선",
        "Tách node": "노드 나누기",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "문서를 저장하지 않았습니다 — 뽑아낸 파일을 옆에 둘 자리가 필요합니다",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "뽑아낼 그래프 부분을 선택하고 다시 하세요",
        "Gom biến thể entity → bảng duyệt": "개체 표기 변형 모으기 → 검토 표",
        "Áp bảng duyệt đã sửa": "고친 검토 표 적용",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "문서를 저장하지 않았습니다 — 검토 표는 그래프 파일 옆에 있어야 합니다",
        "Không tìm thấy biến thể nào để gom": "모을 표기 변형을 찾지 못했습니다",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "변형 묶음 %d개 — 「canonical」 열을 고친 뒤 「검토 표 적용」을 실행하세요",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "검토 표 「%@」가 없습니다 — 먼저 「개체 표기 변형 모으기」를 실행하세요",
        "Bảng duyệt không đọc được: %@": "검토 표를 읽을 수 없습니다: %@",
        "Bảng duyệt không có dòng nào cần đổi": "검토 표에 바꿔야 할 줄이 없습니다",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "그래프에서 검토 표와 맞는 곳이 없습니다",
        "Gom biến thể entity": "개체 표기 변형 모으기",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "변경 %d건 적용 · 별칭 표와 표식 목록을 파일 옆에 적었습니다",
        "Áp %d thay đổi lên đồ thị?": "그래프에 변경 %d건을 적용할까요?",
        "%d alias → dạng chuẩn.": "별칭 %d개 → 표준형.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "노드를 병합합니다(다시 입력해도 되돌릴 수 없습니다):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "별칭 %d개는 그래프에 없어 건너뛰었습니다.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "청크 ↔ 개체 적용 범위 분석",
        "Xuất gói ngữ cảnh (JSONL)": "맥락 묶음 내보내기(JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "청크 ↔ 개체 ↔ 그래프 적용 범위",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- 개체 %1$d개 · 청크 %2$d개 · 개체의 %3$.0f%% 가 언급됨 · 청크의 %4$.0f%% 가 개체를 담음",
        "Entity không chunk nào nhắc tới": "어떤 청크도 언급하지 않는 개체",
        "Chunk mồ côi (không chứa entity nào)": "외톨이 청크(개체가 하나도 없음)",
        "Node đồ thị không có entity đối ứng": "대응하는 개체가 없는 그래프 노드",
        "không có": "없음",
        "Phương pháp": "방법",
        "Không dựng được ánh xạ Chunk ↔ Entity": "청크 ↔ 개체 대응을 만들 수 없습니다",
        "Chấm sức khoẻ đồ thị": "그래프 건강도 채점",
        "sức khoẻ đồ thị": "그래프 건강도",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "건강도 %1$@/100 · 오류 %2$d · 뒤집힘 %3$d · 외톨이 %4$d",
        "Lai với đồ thị": "그래프와 혼합",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: 그래프 신호를 완전히 무시하며, 결과는 순수 BM25와 같습니다",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α 가 큼: 그래프는 BM25 순위를 살짝만 다듬습니다",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α 가 기본값 0.7 부근: BM25가 이끌고 그래프가 다듬습니다",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α 가 작음: 그래프가 이끌고 BM25는 동점만 가릅니다",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: 그래프 신호만 씁니다. 개체가 없는 청크는 서로 같은 점수가 됩니다",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "문서를 저장하지 않았습니다 — 혼합에는 말뭉치 옆에 그래프 파일이 필요합니다",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "그래프 파일 「%@」를 찾을 수 없습니다 — 혼합은 신호를 얻기 위해 이 파일이 필요합니다",
        "lai %.1f ms · %@": "혼합 %.1f밀리초 · %@",
        "Thuật toán…": "알고리즘…",
        "PageRank (độ dày viền)": "PageRank(테두리 굵기)",
        "Cộng đồng (màu nền)": "커뮤니티(배경색)",
        "Thành phần liên thông": "연결 요소",
        "Xuất bảng node ra tab mới": "노드 표를 새 탭으로 내보내기",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "요소 %1$d개 · 가장 큰 것은 노드 %2$d개 · 외톨이 노드 %3$d개",
        "Tài liệu này không phải đồ thị DOT": "이 문서는 DOT 그래프가 아닙니다",
        "Không dựng được bảng node/cạnh: %@": "노드/간선 표를 만들 수 없습니다: %@",
        "%d hàng · %@": "%d행 · %@",
        "Gán nhãn": "라벨 붙이기",
        "Ghi chú (tuỳ chọn)": "메모(선택)",
        "Lưu record": "레코드 저장",
        "Xuất CSV": "CSV 내보내기",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "문서를 저장하지 않았습니다 — 평가기는 말뭉치 파일 옆에 있어야 합니다",
        "Không nạp được bộ đánh giá: %@": "평가기를 불러올 수 없습니다: %@",
        "Không lưu được: %@": "저장할 수 없습니다: %@",
        "Bộ đánh giá chưa có record nào": "평가기에 아직 레코드가 없습니다",
        "Không ghi được: %@": "쓸 수 없습니다: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "이 문서는 .mmd 파일도, DOT도 아니며 mermaid 블록도 없습니다.",
        "%d node · %d cạnh · ⚠ %@": "노드 %d개 · 간선 %d개 · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid 다이어그램: 요소 추가…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid 다이어그램: 선택한 두 요소 잇기",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid 다이어그램: 선택한 요소의 레이블 고치기…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid 다이어그램: 선택한 요소 삭제",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid 다이어그램: 메시지를 위로",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid 다이어그램: 메시지를 아래로",
        "Thêm phần tử": "요소 추가",
        "Thêm participant": "참여자 추가",
        "Thêm mục": "항목 추가",
        "Thêm mục sơ đồ": "다이어그램에 항목 추가",
        "Sửa mục sơ đồ": "다이어그램의 항목 고치기",
        "Xoá mục sơ đồ": "다이어그램의 항목 삭제",
        "Xoá phần tử": "요소 삭제",
        "Sửa nhãn": "레이블 고치기",
        "Đổi thứ tự message": "메시지 순서 바꾸기",
        "Tên mục": "항목 이름",
        "Mục mới": "새 항목",
        "Tên mục hiện trên sơ đồ.": "항목 이름은 다이어그램에 나타납니다.",
        "Bảng thuộc tính sơ đồ": "다이어그램 속성 표",
        "Tài liệu này không có khối mermaid nào": "이 문서에는 mermaid 블록이 없습니다",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "다이어그램 소스에서의 식별자 — 공백은 쓸 수 없습니다. 레이블은 나중에 두 번 눌러 고칩니다.",
        "Để trống thì hiện chính định danh.": "비워 두면 식별자 자체가 나타납니다.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "보이는 레이블만 바뀌고, 요소의 식별자는 그대로입니다.",
        "Không rõ «%@» là phần tử nào": "「%@」가 어느 요소인지 알 수 없습니다",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "요소를 정확히 둘 선택하고 다시 하세요",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "커서를 정확히 요소 하나에 두고 다시 하세요",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "삭제할 요소 하나, 또는 간선으로 이어진 요소 둘을 고르세요",
        "Xoá «%@» và %d cạnh chạm nó?": "「%1$@」와 거기에 닿은 간선 %2$d개를 삭제할까요?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "그 간선 반대쪽의 노드는 남습니다 — 간선 문장이 유일한 선언이었다면 레이블과 함께 다시 선언됩니다.",
        "Sơ đồ «%@» chỉ soạn text — %@": "다이어그램 「%1$@」는 텍스트로만 고칠 수 있습니다 — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: 두 요소 사이를 끌면 이어지고, 두 번 누르면 레이블을 고칩니다",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: 두 참여자 사이를 끌면 메시지가 추가됩니다. 순서는 「도구」 메뉴에서 바꿉니다",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: 아래 속성 표에서 고치세요",
        "Soạn trực quan đã bật": "시각 편집을 켰습니다",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · 항목 %2$d개 — 표에서 바로 고칠 수 있고, 각 셀이 실행 취소 한 단계입니다",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "원 그래프는 숫자, 간트는 쌍점 뒤의 내용입니다.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid 다이어그램: 블록을 .mmd 파일로 빼내기…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid 다이어그램: 참조한 파일을 도로 끼워 넣기",
        "Tách khối sơ đồ": "다이어그램 블록 빼내기",
        "Nhúng khối sơ đồ": "다이어그램 블록 끼워 넣기",
        "Tách khối sơ đồ ra tệp riêng": "다이어그램 블록을 별도 파일로 빼내기",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "파일은 문서 옆에 놓입니다. 블록에는 참조 한 줄이 남아 한 곳에서만 고치면 됩니다.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "문서를 저장하지 않았습니다 — 다이어그램 파일을 옆에 둘 자리가 필요합니다",
        "Đã có tệp «%@» — chọn tên khác": "파일 「%@」가 이미 있습니다 — 다른 이름을 고르세요",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "「%@」로 빼냈습니다 — 블록에는 참조 한 줄이 남았습니다",
        "Mở tệp": "파일 열기",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "「%@」를 도로 끼워 넣었습니다. 파일은 디스크에 그대로 있습니다",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "이 블록에는 참조가 아니라 진짜 다이어그램이 들어 있습니다",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "이 블록은 「%@」를 가리킵니다 — 고치려면 그 파일을 여세요",
        "Không đọc được tệp sơ đồ %@": "다이어그램 파일 %@ 를 읽을 수 없습니다",
        "Soạn trực quan": "시각 편집",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "한 노드에서 다른 노드로 끌면 간선이 추가됩니다. 두 번 누르면 레이블을 고칩니다. 동작 하나가 실행 취소 한 단계입니다.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "시각 편집: 두 노드 사이를 끌면 간선 추가, 두 번 누르면 레이블 고치기",
        "Soạn trực quan đã tắt": "시각 편집을 껐습니다",
        "Thêm node…": "노드 추가…",
        "Thêm cạnh giữa hai node đang chọn…": "선택한 두 노드 사이에 간선 추가…",
        "Sửa nhãn node đang chọn…": "선택한 노드의 레이블 고치기…",
        "Xoá node/cạnh đang chọn": "선택한 노드/간선 삭제",
        "Thêm node": "노드 추가",
        "Thêm cạnh": "간선 추가",
        "Sửa nhãn node": "노드 레이블 고치기",
        "Xoá node": "노드 삭제",
        "Xoá cạnh": "간선 삭제",
        "Cmd-Z hoàn tác": "Cmd-Z로 되돌리기",
        "Tài liệu đang ở chế độ chỉ đọc": "이 문서는 읽기 전용입니다",
        "Nhãn của «%@»": "「%@」의 레이블",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "보이는 레이블만 바뀌고, 노드의 식별자는 그대로입니다.",
        "Không rõ «%@» là node nào": "「%@」가 어느 노드인지 알 수 없습니다",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "DOT 파일 안의 노드 식별자. 레이블은 나중에 그림 위에서 두 번 눌러 고칩니다.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "노드를 정확히 둘 선택하고 다시 하세요",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "삭제할 노드 하나, 또는 간선으로 이어진 노드 둘을 고르세요",
        "Xoá node «%@» và %d cạnh chạm nó?": "노드 「%1$@」와 거기에 닿은 간선 %2$d개를 삭제할까요?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "매달린 간선을 남기면 DOT가 그것으로 노드를 다시 만듭니다 — 삭제한 노드가 다음 그리기에서 되살아납니다.",
        "Phòng thí nghiệm truy hồi BM25": "BM25 검색 실험실",
        "Câu hỏi — Enter để tìm": "질문 — Enter로 검색",
        "Đánh giá…": "평가…",
        "Đang dựng chỉ mục": "색인을 만드는 중",
        "Không chunk nào khớp": "맞는 청크가 없습니다",
        "kết quả trên": "개의 상위 결과",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: 각 낱말은 몇 번 나오든 한 번만 셉니다",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 이 작음: 낱말을 되풀이해도 점수가 거의 늘지 않습니다",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 이 기본값 1.2 부근: 되풀이하면 점수가 늘지만 늘어나는 폭이 점점 줄어듭니다",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 이 큼: 같은 낱말을 많이 되풀이한 청크가 크게 우대됩니다",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: 길이를 무시하며 긴 청크에 벌점이 없습니다",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b 가 작음: 긴 청크에 벌점이 조금만 붙습니다",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b 가 기본값 0.75 부근: 긴 청크에 알맞은 벌점이 붙습니다",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: 길이에 따른 벌점이 가장 크고 짧은 청크가 유리해집니다",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: 검색 실험실…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "문서를 저장하지 않았습니다 — BM25 색인은 말뭉치 파일 옆에 놓이므로 경로가 필요합니다",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "이 파일은 JSONL이 아닙니다 — Retrieval Lab은 청크 말뭉치에서 동작합니다",
        "Không dựng được chỉ mục BM25 cho tệp này": "이 파일의 BM25 색인을 만들 수 없습니다",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "문서를 저장하지 않았습니다 — 보고서를 만들려면 말뭉치 경로가 필요합니다",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "평가 모음 선택(CSV 또는 JSONL: 질문 + 기대하는 청크 식별자)",
        "Đánh giá truy hồi": "검색 평가",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "위의 k1, b, k를 바꾸고 다시 보면 두 설정을 견줄 수 있습니다. 「compare」 블록을 넣으면 같은 평가 모음에서 두 매개변수 묶음을 나란히 돌립니다.",
        "Lỗi": "오류",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, 평균 %.0f)",
        "Chế độ JSONL": "JSONL 모드",
        "Bản ghi": "레코드",
        "Chi tiết": "자세히",
        "Bản ghi ở dòng": "줄의 레코드",
        "không phải JSON hợp lệ": "올바른 JSON이 아닙니다",
        "bản ghi": "개 레코드",
        "dòng trắng": "빈 줄",
        "không phải đối tượng": "객체가 아닙니다",
        "bảng hiện": "보이는 표",
        "ĐÃ HUỶ giữa chừng": "도중에 취소됨",
        "Không lọc": "거르지 않음",
        "bản ghi khớp bộ lọc": "개 레코드가 조건에 맞음",
        "Đưa con nháy tới một dòng để xem bản ghi": "줄에 커서를 두면 레코드를 볼 수 있습니다",
        "Không có bản ghi nào hỏng": "망가진 레코드가 없습니다",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "아직 살펴보지 않았습니다. 검증을 마친 뒤 「JSONL: 청크 살펴보기」를 다시 실행하세요.",
        "trường văn bản": "텍스트 필드",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "스키마(추측 — 다른 필드를 고르면 바뀝니다)",
        "văn bản": "텍스트",
        "định danh": "식별자",
        "metadata lồng": "중첩된 메타데이터",
        "TRƯỜNG": "필드",
        "phủ": "적용 범위",
        "nhiều kiểu": "여러 자료형",
        "ĐỘ DÀI — ký tự": "길이 — 문자",
        "ĐỘ DÀI — từ": "길이 — 낱말",
        "ĐỘ DÀI — token ước lượng": "길이 — 추정 토큰",
        "RỖNG VÀ TRÙNG": "빈 값과 중복",
        "chunk rỗng": "개의 빈 청크",
        "dòng": "줄",
        "nhóm trùng chính xác": "개의 완전 중복 묶음",
        "dòng không đọc được, không vào thống kê": "줄은 읽을 수 없어 통계에서 뺐습니다",
        "PHƯƠNG PHÁP": "방법",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "「문자」는 유니코드 문자(스칼라)로 세며, 보이는 묶음 단위가 아닙니다",
        "«từ» tách theo khoảng trắng ASCII": "「낱말」은 ASCII 공백으로 나눕니다",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "「토큰」은 음절 분리기로 셉니다 — 모형의 분리기가 아닙니다",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "「중복」은 완전히 같은 것을 뜻하며, 거의 같은 것은 ```quality 블록에 있습니다",
        "chunk": "개 청크",
        "JSONL: kiểm và soi chunk…": "JSONL: 청크 검증하고 살펴보기…",
        "Ảnh": "이미지",
        "PDF": "PDF",
        "Tài liệu Word": "Word 문서",
        "Bảng tính Excel": "Excel 스프레드시트",
        "Bản trình chiếu PowerPoint": "PowerPoint 프레젠테이션",
        "File nén": "압축 파일",
        "Vừa khung": "창에 맞추기",
        "Chép ảnh": "이미지 복사",
        "Xoay": "회전",
        "Không đọc được ảnh «%@»": "이미지 「%@」를 읽을 수 없습니다",
        "Đã chép ảnh vào clipboard": "이미지를 클립보드로 복사했습니다",
        "Bôi vàng": "노랑으로 강조",
        "Gạch chân": "밑줄",
        "Ghi chú…": "메모…",
        "Bỏ chú thích": "주석 지우기",
        "Lấy chữ ra tab mới": "텍스트를 새 탭으로 빼내기",
        "Lưu bản có chú thích…": "주석이 달린 버전 저장…",
        "Tìm trong PDF": "PDF에서 찾기",
        "Thêm": "추가",
        "Trang %d/%d": "%d/%d쪽",
        "Trang %d": "%d쪽",
        "Kết quả %d/%d": "%d/%d번째 결과",
        "0 kết quả": "결과 0개",
        "Không đọc được PDF «%@»": "PDF 「%@」를 읽을 수 없습니다",
        "PDF này có mật khẩu — chưa mở được nội dung": "이 PDF는 암호로 보호되어 있어 내용을 볼 수 없습니다",
        "Không thấy «%@» trong tài liệu": "문서에서 「%@」를 찾을 수 없습니다",
        "Đã bôi vàng": "강조했습니다",
        "Đã gạch chân": "밑줄을 그었습니다",
        "Hãy bôi đen một đoạn chữ trước": "먼저 텍스트를 선택하세요",
        "Đã thêm ghi chú": "메모를 추가했습니다",
        "Trang này chưa có chú thích nào": "이 쪽에는 주석이 없습니다",
        "Đã bỏ %d chú thích trên trang này": "이 쪽에서 주석 %d개를 지웠습니다",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "이 PDF에는 텍스트 층이 없습니다 — 아마 스캔한 것입니다",
        "Không ghi được tệp": "파일에 쓸 수 없습니다",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "쓴 파일이 제대로 다시 열리지 않습니다 — 이 버전은 쓰지 마세요",
        "Đã lưu %@ · %d trang": "%@ 저장됨 · %d쪽",
        "Tên": "이름",
        "Kích thước": "크기",
        "Đã nén": "압축됨",
        "Tỉ lệ": "비율",
        "Sửa lúc": "수정 시각",
        "Mở mục đang chọn": "선택한 항목 열기",
        "Bung ra thư mục…": "폴더로 풀기…",
        "Bung vào đây": "여기에 풀기",
        "%d mục": "항목 %d개",
        "giải nén ra %@": "%@ 로 풀었습니다",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— Office 파일의 속은 압축 파일이며, 이것이 그 구성 요소입니다",
        "Đã bung %d mục": "항목 %d개를 풀었습니다",
        "%d mục hỏng": "항목 %d개가 망가졌습니다",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "항목 %d개는 경로가 대상 폴더 밖으로 나가 거부했습니다",
        "Không mở được mục này": "이 항목을 열 수 없습니다",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "%@ 에는 아직 바로 되쓸 수 없습니다 — 「다른 이름으로 저장…」을 쓰세요",
        "Không có gì đổi": "바뀐 것이 없습니다",
        "Đã ghi %d ô vào %@": "%2$@ 에 셀 %1$d개를 썼습니다",
        "Đã ghi %d đoạn vào %@": "%2$@ 에 문단 %1$d개를 썼습니다",
        "Không ghi được vào tệp — bản gốc còn nguyên": "파일에 쓸 수 없습니다 — 원본은 그대로입니다",
        "dựng bài": "시험 사례 준비",
        "Không ghi được settings.json": "settings.json에 쓸 수 없습니다",
        "Xoay trái": "왼쪽으로 회전",
        "Xoay phải": "오른쪽으로 회전",
        "Trang lên": "페이지 위로",
        "Trang xuống": "페이지 아래로",
        "Xoá trang…": "페이지 삭제…",
        "Xoá trang": "페이지 삭제",
        "Trích trang…": "페이지 추출…",
        "Trích trang ra tệp mới": "페이지를 새 파일로 추출",
        "Gộp tệp PDF…": "PDF 파일 병합…",
        "Tách tệp…": "파일 분할…",
        "Tách tệp PDF": "PDF 파일 분할",
        "Xuất ảnh…": "이미지 내보내기…",
        "Xuất trang ra ảnh PNG": "페이지를 PNG 이미지로 내보내기",
        "Hoàn tác trang": "페이지 편집 실행 취소",
        "Lưu bản đã sửa…": "편집한 사본 저장…",
        "Phát": "재생",
        "Tạm dừng": "일시정지",
        "Xem bình thường": "일반 보기",
        "Chọn sheet": "시트 선택",
        "Mở sheet": "시트 열기",
        "Bỏ và đổi sheet": "무시하고 시트 전환",
        "Bảng tính có %d sheet.": "통합 문서에 시트가 %d개 있습니다.",
        "Bảng tính này chỉ có một sheet: «%@»": "이 통합 문서에는 시트가 하나뿐입니다: “%@”",
        "Bỏ phần chưa lưu của sheet này?": "이 시트의 저장되지 않은 변경사항을 무시하시겠습니까?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "시트를 전환하면 탭 전체가 바뀝니다. ⌘S로 저장하지 않은 내용은 사라집니다.",
        "Chọn tệp PDF cần gộp vào": "병합할 PDF 파일 선택",
        "Chọn thư mục ghi ảnh": "이미지를 저장할 폴더 선택",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "저장할 위치를 선택하세요. 두 번째 파일은 그 옆에 기록됩니다.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "문서가 %d페이지입니다. 삭제할 페이지를 입력하세요. 예: 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "문서가 %d페이지입니다. 추출할 페이지를 입력하세요. 예: 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "문서가 %d페이지입니다. 내보낼 페이지를 입력하세요. 예: 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "문서가 %d페이지입니다. 분리할 부분을 입력하세요. 예: 1-5. 나머지는 두 번째 파일이 됩니다.",
        "Đã xoay trang %d": "%d페이지를 회전했습니다",
        "Đã xoá trang %@ · còn %d trang": "%@페이지를 삭제했습니다 · %d페이지 남음",
        "Đã gộp %d trang từ «%@»": "“%2$@”에서 %1$d페이지를 병합했습니다",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "%@(%d페이지)와 %@(%d페이지)로 분할했습니다",
        "Đã ghi %@ — %@ · %d trang": "%@ 기록함 — %@ · %d페이지",
        "Đã xuất %d ảnh vào %@": "이미지 %d개를 %@에 내보냈습니다",
        "Chỉ xuất được %d/%d ảnh": "이미지 %d/%d개만 내보냈습니다",
        "Đã hoàn tác một thao tác trang": "페이지 작업 하나를 실행 취소했습니다",
        "Không còn thao tác trang nào để hoàn tác": "실행 취소할 페이지 작업이 없습니다",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "모든 페이지를 삭제할 수 없습니다 — PDF에는 최소 한 페이지가 있어야 합니다",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "그 범위는 문서 전체입니다 — 분리할 것이 없습니다",
        "«%@» có mật khẩu — chưa gộp được": "“%@”은(는) 암호로 보호되어 있어 병합할 수 없습니다",
        "«%@» không có trang nào": "“%@”에 페이지가 없습니다",
        "Đã ở trang đầu": "이미 첫 페이지입니다",
        "Đã ở trang cuối": "이미 마지막 페이지입니다",
        "· đã sửa, chưa lưu": "· 편집됨, 저장 안 됨",
        "Ảnh động · %d khung": "움직이는 이미지 · %d프레임",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "저장되지 않은 문서입니다 — 바이너리로 볼 파일이 디스크에 없습니다",
        "Lệnh này chỉ dùng cho bảng tính Excel": "이 명령은 Excel 통합 문서에서만 동작합니다",
        "Không đọc được danh sách sheet": "시트 목록을 읽을 수 없습니다",
        "Không có sheet «%@»": "“%@” 시트가 없습니다",
        "Không đọc được sheet «%@»": "“%@” 시트를 읽을 수 없습니다",
        "Sheet «%@» · %d hàng": "시트 “%@” · %d행",
        "phần còn lại": "나머지",
        "Lưu ý": "참고",
        "Cẩn thận": "주의",
        "Xem thêm": "함께 보기",
        "Chép": "복사",
        "Đã chép": "복사됨",
        "Chép đoạn mã mẫu": "예제 코드 복사",
        "Tìm trong trợ giúp": "도움말 검색",
        "Lùi": "뒤로",
        "Bắt đầu dùng": "시작하기",
        "Không mở cửa sổ này khi khởi động nữa": "시작할 때 이 윈도우를 표시하지 않기",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "도움말이 아직 이 언어로 번역되지 않았습니다 — 베트남어로 표시합니다.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "오프셋으로 이동 (예: 1F400 또는 0x1F400)",
        "Chép dòng đã chọn": "선택한 행 복사",
        "Đã chép %d dòng": "%d행을 복사했습니다",
        "Không đọc được «%@»": "“%@”을(를) 읽을 수 없습니다",
        "Tệp rỗng": "빈 파일",
        "Không đọc được offset «%@»": "오프셋 “%@”을(를) 읽을 수 없습니다",
        "Offset 0x%@ vượt quá cỡ tệp": "오프셋 0x%@이(가) 파일 크기를 넘습니다",
        "Mở bằng ứng dụng khác…": "다른 앱으로 열기…",
        "%d kênh": "%d채널",
        "Không phát được «%@»": "“%@”을(를) 재생할 수 없습니다",
        "Không phát được — %@": "재생할 수 없음 — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS에는 %@ 형식용 디코더가 없습니다 — 파일 손상이 아니라 운영체제의 한계입니다.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "바이너리 보기로 바이트를 확인하거나, 자체 디코더가 있는 앱으로 열 수 있습니다.",
        "Ký…": "서명…",
        "Sửa chữ…": "텍스트 편집…",
        "Sửa chữ": "텍스트 편집",
        "Vẽ đè": "위에 그리기",
        "Ô chưa điền": "다음 빈 필드",
        "Xoá nội dung đã điền": "입력 내용 지우기",
        "Tệp này không có ô biểu mẫu nào": "이 파일에는 양식 필드가 없습니다",
        "Đã xoá nội dung của %d ô biểu mẫu": "양식 필드 %d개를 지웠습니다",
        "Mọi ô biểu mẫu đều đã có nội dung": "모든 양식 필드가 이미 채워졌습니다",
        "Còn %d ô chưa điền": "빈 필드가 %d개 남았습니다",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "작성 가능한 양식: 필드 %d개. 바로 입력한 뒤 “편집한 사본 저장…”",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "서명 이미지 선택 (배경이 투명하면 가장 좋습니다)",
        "Không dựng được trang có chữ ký": "서명된 페이지를 만들 수 없습니다",
        "Đã chèn chữ ký vào trang %d": "%d페이지에 서명을 삽입했습니다",
        "Hãy bôi chọn phần chữ cần sửa trước": "먼저 변경할 텍스트를 선택하세요",
        "Vùng chọn quá nhỏ": "선택 영역이 너무 작습니다",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "새 텍스트는 시스템 서체로 선택 영역 위에 그려집니다. 기존 텍스트는 가려질 뿐 삭제되지 않아 여전히 추출할 수 있으므로, 이것은 마스킹이 아닙니다.",
        "Không dựng được trang đã sửa": "편집된 페이지를 만들 수 없습니다",
        "Đã vẽ đè chữ mới lên trang %d": "%d페이지에 새 텍스트를 그렸습니다",
        "Đổi chế độ View / Code": "보기 / 코드 전환",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "JSON · XML · YAML용 트리 보기는 아직 없습니다",
        "Chưa có chế độ View dạng sơ đồ trong tab": "탭 내 다이어그램 보기는 아직 없습니다",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "PowerPoint용 개요 보기는 아직 없습니다",
        "Tệp này chỉ có một chế độ hiển thị": "이 파일에는 표시 모드가 하나뿐입니다",
        "%d nút": "노드 %d개",
        "Không dựng được cây: %@": "트리를 만들 수 없습니다: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "문서가 너무 커서 트리를 만들 수 없습니다 — 코드 모드를 사용하세요",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "이 파일의 페이지를 만들지 못했습니다 \u{2014} 코드 모드를 사용하세요.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "슬라이드는 글자로 만들었습니다. 원본 이미지와 배치는 아직 그리지 않았습니다.",
        "Vừa ngang": "너비 맞춤",
        "Thu nhỏ trang": "페이지 축소",
        "Phóng to trang": "페이지 확대",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "이 문서에서 «%@»을(를) 찾지 못했습니다",
        "Chỗ khớp %d/%d": "%d / %d번째 일치",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "페이지에서 선택한 글자가 없습니다.",
        "%d ký tự": "%d자",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có": "View가 있는 파일은 바로 View 모드로 열기",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· 도중에 취소됨 — 표가 완전하지 않습니다",
        "Chế độ hiển thị": "표시 모드",
        "Đổi giữa View và Code (⌥⌘V)": "View와 Code 전환(⌥⌘V)",
        "Trang tài liệu": "문서 페이지",
        "Chữ đã dựng": "조판된 텍스트",
        "Trang bảng tính": "스프레드시트 페이지",
        "Sơ đồ": "다이어그램",
        "Cây khoá–giá trị": "키–값 트리",
        "Bộ phát": "재생기",
        "Danh sách mục": "항목 목록",
        "Báo cáo đã dựng": "완성된 보고서",
        "Tô theo mức": "수준별 색상",
        "Trang slide": "슬라이드 페이지",
        "Dàn ý": "개요",
        "Lưu rồi dựng lại": "저장하고 다시 구성",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "디스크에 있는 사본을 표시 중 — 저장하지 않은 변경 사항은 없습니다.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "시스템이 문서 뷰어를 만들지 못했습니다 — Code 모드를 사용하세요.",
        "Lưu tệp trước khi xem trang.": "페이지를 보기 전에 파일을 저장하세요.",
        "Đang ở chế độ Code": "현재 Code 모드",
        "Đang ở chế độ View": "현재 View 모드",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "소스를 보는 중 — 클릭하면 View 모드로(⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "View 모드 — 클릭하면 소스로 돌아갑니다(⌥⌘V)",
        "Tín hiệu: %@": "시그널: %@",
        "Lý do: %@": "이유: %@",
        "Chi tiết: %@": "세부: %@",
        "Mở báo cáo": "보고서 열기",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor가 %@에 갑자기 종료되었습니다 — 보고서를 열어 읽어 보세요. 아무것도 전송되지 않습니다.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "합자 — 끄면 각 문자가 한 칸을 차지합니다",
        "Chế độ CSV": "CSV 모드",
        "Dấu phân tách": "구분자",
        "Tự nhận diện": "자동으로 인식",
        "Dấu phân tách: %@": "구분자: %@",
        "Theo đuôi tệp": "파일 확장자에 따라",
        "%d dấu cách": "공백 %d개",
        "Tài liệu đang sửa được": "이 문서는 편집할 수 있습니다",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "파일을 추적 중이라 읽기 전용입니다 — 편집하려면 추적을 멈추세요",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "디스크의 파일에 쓸 수 없어 읽기 전용입니다",
        "Đã mở khoá — tài liệu sửa được": "잠금 해제 — 문서를 다시 편집할 수 있습니다",
        "Nhân bản tệp": "파일 복제",
        "Đổi tên tệp…": "파일 이름 변경…",
        "Chuyển tệp tới…": "파일 옮기기…",
        "XML: đánh giá XPath…": "XML: XPath 평가…",
        "Đánh giá XPath": "XPath 평가",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "예: //order/item[2]/@code · //*[@kind='A'] · count(//item)",
        "Đánh giá": "평가",
        "XPath không đọc được: %@": "이 XPath를 읽을 수 없습니다: %@",
        "XPath «%@» không khớp node nào": "XPath 「%@」와 일치하는 노드가 없습니다",
        "XPath «%@» — %d node": "XPath 「%@」 — 노드 %d개",
        "XPath «%@»: %d node": "XPath 「%@」: 노드 %d개",
        "Lưu tệp trước khi nhân bản.": "복제하기 전에 파일을 저장하세요.",
        "Không nhân bản được": "복제할 수 없습니다",
        "Đã nhân bản thành %@": "%@(으)로 복제했습니다",
        "Lưu tệp trước khi đổi tên.": "이름을 바꾸기 전에 파일을 저장하세요.",
        "Đổi tên tệp": "파일 이름 변경",
        "Tên hiện tại: %@": "현재 이름: %@",
        "Đổi tên": "이름 변경",
        "Tên tệp không hợp lệ": "그 파일 이름은 사용할 수 없습니다",
        "Đã có tệp tên %@ ở đó": "거기에 이미 %@(이)라는 파일이 있습니다",
        "Lưu tệp trước khi chuyển.": "옮기기 전에 파일을 저장하세요.",
        "Chuyển tới": "여기로 옮기기",
        "Thư mục đích đã có tệp tên %@": "대상 폴더에 이미 %@(이)라는 파일이 있습니다",
        "Không chuyển được tệp": "파일을 옮길 수 없습니다",
        "Đã chuyển tới %@": "%@(으)로 옮겼습니다",
        "Bảng mã:": "인코딩:",
        "Xuống dòng:": "줄 바꿈:",
        "Riêng cho %@": "%@ 전용",
        "    %d — dùng TAB": "    %d — 탭 사용",
        "    %d — dùng dấu cách": "    %d — 공백 사용",
        "    Bỏ khai riêng, dùng cài đặt chung": "    개별 설정을 지우고 전체 설정 사용",
        "%@: thụt lề %d %@": "%@: 들여쓰기 %d %@",
        "TAB": "탭",
        "dấu cách": "공백",
        "Xuất": "내보내기",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "결과를 텍스트 탭으로 열기 — ⌘S로 저장",
        "Lượt tìm trước đó": "이전 검색",
        "«%@» — %d kết quả": "「%@」 — 결과 %d개",
        "Kết quả tìm «%@»": "「%@」 검색 결과",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "파일 이름 필터 — 예: *.csv;*.log(비우면 모든 텍스트 파일)",
        "Thư mục %@ không có file văn bản nào": "폴더 %@에 텍스트 파일이 없습니다",
        "Không tệp nào trong %@ khớp «%@»": "%@ 안에 「%@」와 맞는 파일이 없습니다",
        "%d byte · %d dòng": "%d바이트 · %d줄",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d바이트 · %d줄 — 너무 커서 글자와 단어를 셀 수 없습니다",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d바이트 · %d자 · %d단어 · %d줄",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "이 문서는 %d줄, %d바이트입니다. 줄 번호, 「줄,열」 또는 「@바이트」를 입력하세요.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "「%@」를 읽을 수 없습니다 — 줄 번호, 「줄,열」 또는 「@바이트」를 입력하세요",
    ]
}
