import Foundation

/// Bảng dịch tiếng Ba Lan. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let pl: [String: String] = [
        "Bản đã lưu…": "Zapisane wersje…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Ten dokument nigdy nie był zapisany — brak historii",
        "Chưa có bản đã lưu nào trước đó": "Brak wcześniejszych zapisanych wersji",
        "Không đọc được bản ấy": "Nie można odczytać tej wersji",
        "Khôi phục bản đã lưu": "Przywróć zapisaną wersję",
        "XML: kiểm theo DTD/XSD…": "XML: sprawdź według DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Ten Mac nie ma libxml2, więc sprawdzanie XSD jest niedostępne.",
        "Chọn lược đồ XSD để kiểm": "Wybierz schemat XSD do sprawdzenia",
        "Hợp lệ theo": "Zgodny z",
        "Plugin chạy xong, không đổi gì": "Wtyczka zakończyła działanie, niczego nie zmieniając",
        "Chưa cài plugin native nào": "Nie zainstalowano żadnych wtyczek natywnych",
        "Gỡ plugin này": "Usuń tę wtyczkę",
        "Gỡ plugin này?": "Usunąć tę wtyczkę?",
        "Gỡ": "Usuń",
        "Cài plugin native…": "Zainstaluj wtyczkę natywną…",
        "Mở thư mục plugin": "Otwórz katalog wtyczek",
        "Chọn file .dylib của plugin native": "Wybierz plik .dylib wtyczki",
        "Đã cài:": "Zainstalowano:",
        "Đã gỡ:": "Usunięto:",
        "Plugin native…": "Wtyczki natywne…",
        "Chỉ nhận file .dylib.": "Przyjmowane są wyłącznie pliki .dylib.",
        "Đã có một plugin trùng tên:": "Wtyczka o tej samej nazwie jest już zainstalowana:",
        "Không chép được plugin:": "Nie można skopiować wtyczki:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Wtyczki natywne są tylko w wersji pobieranej bezpośrednio, nie w wersji z App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Nie znaleziono procesu pomocniczego wtyczek.",
        "Không khởi động được tiến trình phụ:": "Nie można uruchomić procesu pomocniczego:",
        "Tiến trình plugin đã dừng giữa chừng.": "Proces wtyczki zatrzymał się w połowie.",
        "Plugin không trả lời kịp — đã dừng nó.": "Wtyczka nie odpowiedziała na czas — została zatrzymana.",
        "Plugin trả lời sai giao thức:": "Wtyczka odesłała źle sformułowany komunikat:",
        "Plugin báo lỗi:": "Wtyczka zgłosiła błąd:",
        "Về GEditor": "O programie GEditor",
        "Cài đặt…": "Ustawienia…",
        "Thoát GEditor": "Zakończ GEditor",
        "File": "Plik",
        "Tab mới": "Nowa karta",
        "Đóng tab": "Zamknij kartę",
        "Tab kế": "Następna karta",
        "Tab trước": "Poprzednia karta",
        "Tài liệu mới": "Nowy dokument",
        "Mở…": "Otwórz…",
        "Mở thư mục làm Workspace…": "Otwórz katalog jako obszar roboczy…",
        "Mở gần đây": "Otwórz ostatnie",
        "Lưu": "Zapisz",
        "Lưu thành…": "Zapisz jako…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Usuwaj spacje na końcu wiersza przy zapisie",
        "Theo dõi file (tail -f)": "Śledź plik (tail -f)",
        "In…": "Drukuj…",
        "Mở lại tab vừa đóng": "Otwórz ponownie zamkniętą kartę",
        "Chưa có file nào": "Brak plików",
        "Xoá danh sách": "Wyczyść listę",
        "Edit": "Edycja",
        "Hoàn tác": "Cofnij",
        "Làm lại": "Ponów",
        "Cắt": "Wytnij",
        "Sao chép": "Kopiuj",
        "Dán": "Wklej",
        "Lịch sử clipboard…": "Historia schowka…",
        "Column Editor…": "Edytor kolumn…",
        "Chọn lần kế tiếp": "Zaznacz następne dopasowanie",
        "Chọn tất cả": "Zaznacz wszystko",
        "Nhân đôi dòng": "Powiel wiersz",
        "Xóa dòng": "Usuń wiersz",
        "Comment dòng": "Zakomentuj wiersz",
        "Chưa chép gì trong phiên này": "W tej sesji nic nie skopiowano",
        "Xoá lịch sử": "Wyczyść historię",
        "Search": "Szukaj",
        "Tìm…": "Znajdź…",
        "Tìm và thay…": "Znajdź i zamień…",
        "Tìm trong thư mục…": "Szukaj w katalogu…",
        "Thay trong thư mục…": "Zamień w katalogu…",
        "Kết quả kế": "Następny wynik",
        "Kết quả trước": "Poprzedni wynik",
        "Đi tới dòng…": "Przejdź do wiersza…",
        "Nhảy tới ngoặc khớp": "Przejdź do pasującego nawiasu",
        "Đánh dấu mọi dòng khớp…": "Zaznacz wszystkie pasujące wiersze…",
        "Đảo dấu": "Odwróć zaznaczenia",
        "Bỏ mọi dấu": "Usuń wszystkie zaznaczenia",
        "Chép dòng đã đánh dấu": "Kopiuj zaznaczone wiersze",
        "Xóa dòng đã đánh dấu": "Usuń zaznaczone wiersze",
        "Chỉ giữ dòng đã đánh dấu": "Zostaw tylko zaznaczone wiersze",
        "Lines": "Wiersze",
        "Sắp xếp A→Z": "Sortuj A→Z",
        "Sắp xếp Z→A": "Sortuj Z→A",
        "Sắp xếp tự nhiên": "Sortowanie naturalne",
        "Khử trùng lặp": "Usuń duplikaty",
        "Đảo thứ tự dòng": "Odwróć kolejność wierszy",
        "Dời dòng lên": "Przesuń wiersz w górę",
        "Dời dòng xuống": "Przesuń wiersz w dół",
        "Ghép dòng": "Połącz wiersze",
        "Tách dòng theo độ dài…": "Podziel wiersze według długości…",
        "Tách dòng theo ký tự…": "Podziel wiersze według znaku…",
        "Xóa dòng rỗng": "Usuń puste wiersze",
        "Nén dòng trống liên tiếp": "Zredukuj kolejne puste wiersze",
        "Cắt khoảng trắng cuối dòng": "Usuń spacje na końcu wiersza",
        "Tab → Space": "Tab → spacja",
        "Space → Tab": "Spacja → Tab",
        "HOA": "WIELKIE LITERY",
        "thường": "małe litery",
        "Chữ Hoa Đầu Từ": "Pierwsza Litera Każdego Słowa",
        "Chữ hoa đầu câu": "Pierwsza litera zdania",
        "Đảo hoa/thường": "oDWRÓĆ wIELKOŚĆ lITER",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: wybierz arkusz…",
        "Xem dạng bảng / văn bản": "Przełącz widok tabeli / tekstu",
        "Xóa cột…": "Usuń kolumnę…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Sprawdź dane (liczba kolumn · typy)",
        "Bàn làm sạch dữ liệu…": "Warsztat czyszczenia danych…",
        "Chạy công thức làm sạch…": "Uruchom przepis czyszczenia…",
        "Chuyển đổi…": "Konwertuj…",
        "Đổi dấu phân tách…": "Zmień separator…",
        "Xuất sang JSON…": "Wyeksportuj do JSON…",
        "Format": "Format",
        "Bảng mã…": "Kodowanie…",
        "Xuống dòng…": "Końce wierszy…",
        "Chuẩn hóa Unicode…": "Normalizuj Unicode…",
        "JSON: định dạng lại": "JSON: sformatuj",
        "JSON: thu gọn một dòng": "JSON: skompresuj do jednego wiersza",
        "JSON: sắp xếp khóa": "JSON: posortuj klucze",
        "JSON: truy vấn JSONPath…": "JSON: zapytanie JSONPath…",
        "CSV: truy vấn SQL…": "CSV: zapytanie SQL…",
        "Truy vấn SQL": "Zapytanie SQL",
        "Đang chạy…": "Trwa…",
        "Xuất ra tab mới": "Wyeksportuj do nowej karty",
        "Tài liệu rỗng — không có bảng để truy vấn": "Pusty dokument — nie ma tabeli do odpytania",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "To nie jest tabela CSV — pierwszy wiersz ma tylko jedną kolumnę",
        "Không đọc được câu truy vấn": "Nie można odczytać zapytania",
        "Không kiểm được câu truy vấn": "Nie można sprawdzić zapytania",
        "Vàng (mặc định)": "Żółty (domyślny)",
        "Xanh dương": "Niebieski",
        "Xanh lá": "Zielony",
        "Vàng đất": "Ochra",
        "Tím": "Fioletowy",
        "Hồng": "Różowy",
        "Xanh ngọc": "Turkusowy",
        "Cam": "Pomarańczowy",
        "Xám lam": "Łupkowy",
        "Văn bản": "Tekst",
        "Dãy số": "Ciąg liczb",
        "Dãy ngày": "Ciąg dat",
        "Chữ HOA (hex)": "WIELKIE LITERY (szesnastkowo)",
        "Bắt đầu": "Początek",
        "Bước": "Krok",
        "Đệm 0 tới": "Uzupełnij zerami do",
        "Hệ": "Podstawa",
        "Ngày đầu": "Pierwsza data",
        "Định dạng": "Format",
        "Chèn": "Wstaw",
        "Huỷ": "Anuluj",
        "Chuyển đổi định dạng": "Konwertuj format",
        "Xem trước 5 hàng đầu": "Podgląd pierwszych 5 wierszy",
        "Tạo tab mới": "Otwórz w nowej karcie",
        "Lưu ra file…": "Zapisz do pliku…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Wynik otworzy się w nowej, niezapisanej karcie. Pierwotny dokument pozostaje nietknięty.",
        "Chạy trên tài liệu này": "Uruchom na tym dokumencie",
        "Chạy trên thư mục…": "Uruchom na katalogu…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Cały przepis to JEDEN krok cofania. Plik na dysku pozostaje nietknięty, dopóki nie zapiszesz.",
        "tắt": "wyłączone",
        "không thấy cột": "nie znaleziono kolumny",
        "sẵn sàng": "gotowe",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "zajmuje rdzeń procesora aż do zamknięcia programu.",
        "Script không trả về gì": "Skrypt niczego nie zwrócił",
        "Không dựng được máy JavaScript": "Nie można utworzyć silnika JavaScript",
        "Lỗi JavaScript không rõ": "Nieznany błąd JavaScript",
        "Bảng": "Tabela",
        "Áp sắp xếp vào file": "Zastosuj sortowanie do pliku",
        "Chuyển đổi ▾": "Konwertuj ▾",
        "Xuất dòng khớp": "Wyeksportuj pasujące wiersze",
        "Ẩn cột này": "Ukryj tę kolumnę",
        "Đổi tên tiêu đề…": "Zmień nazwę nagłówka…",
        "Chèn cột trống bên trái": "Wstaw pustą kolumnę po lewej",
        "Chèn cột trống bên phải": "Wstaw pustą kolumnę po prawej",
        "Xóa cột này khỏi file…": "Usuń tę kolumnę z pliku…",
        "Phải còn ít nhất một cột đang hiện": "Co najmniej jedna kolumna musi pozostać widoczna",
        "Đang sắp xếp…": "Trwa sortowanie…",
        "Trở về thứ tự trong file": "Wróć do kolejności z pliku",
        "trăm hàng đầu": "pierwsze sto wierszy",
        "chọn cột": "wybór kolumn",
        "đặt tên cột kết quả": "nazwanie kolumny wyniku",
        "lọc theo chữ": "filtrowanie po tekście",
        "ô rỗng": "puste komórki",
        "ghép điều kiện": "łączenie warunków",
        "đếm hàng": "liczenie wierszy",
        "gộp nhóm": "grupowanie i agregacja",
        "nhỏ nhất, lớn nhất": "minimum, maksimum",
        "sắp xếp và cắt": "sortowanie i ograniczanie",
        "tên cột có dấu cách": "nazwa kolumny ze spacjami",
        "Truy vấn bị dừng giữa chừng": "Zapytanie zostało przerwane",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Nieobsługiwane: JOIN · podzapytanie · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funkcje okna",
        "XML: định dạng lại": "XML: sformatuj",
        "XML: thu gọn một dòng": "XML: skompresuj do jednego wiersza",
        "XML: kiểm cú pháp": "XML: sprawdź składnię",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: sprawdź powtórzone klucze i wcięcia",
        "View": "Widok",
        "Ẩn/hiện sidebar (Function List)": "Pokaż/ukryj panel boczny (lista funkcji)",
        "Ẩn/hiện bản đồ tài liệu": "Pokaż/ukryj mapę dokumentu",
        "Gấp / mở khối tại con nháy": "Zwiń / rozwiń blok przy kursorze",
        "Gấp tất cả": "Zwiń wszystko",
        "Bỏ gấp tất cả": "Rozwiń wszystko",
        "Gấp theo cấp": "Zwiń według poziomu",
        "Cấp %d": "Poziom %d",
        "Đã gấp %d khối ở cấp %d": "Zwinięto %1$d {one=blok|few=bloki|many=bloków} na poziomie %2$d",
        "Tài liệu này chỉ sâu %d cấp": "Ten dokument ma tylko %d {one=poziom|few=poziomy|many=poziomów} głębokości",
        "mermaid: không đọc được bản kê": "mermaid: nie można odczytać manifestu",
        "Kiểm tra bản cập nhật…": "Sprawdź uaktualnienia…",
        "Kiểm tra bản cập nhật": "Sprawdź uaktualnienia",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Wersje z App Store aktualizują się przez Mac App Store, a nie przez GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Ta kompilacja nie ma klucza podpisu uaktualnień, więc nie może ich sprawdzać.",
        "Phóng to chữ": "Powiększ tekst",
        "Thu nhỏ chữ": "Pomniejsz tekst",
        "Cỡ chữ gốc": "Rzeczywisty rozmiar",
        "Chia đôi theo chiều dọc": "Podziel pionowo",
        "Chia đôi theo chiều ngang": "Podziel poziomo",
        "Bỏ chia đôi": "Zamknij podział",
        "Mở tab này ở nửa kia": "Otwórz tę kartę w drugim panelu",
        "Nhảy sang nửa kia": "Przejdź do drugiego panelu",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Zawijanie wierszy (wyłączone / okno / kolumna)",
        "Ngắt dòng tại cột…": "Zawijaj na kolumnie…",
        "Đánh dấu dòng này": "Zaznacz ten wiersz",
        "Dấu kế tiếp": "Następne zaznaczenie",
        "Dấu trước đó": "Poprzednie zaznaczenie",
        "Màu đánh dấu…": "Kolor zaznaczeń…",
        "Hiện tất cả ký tự ẩn": "Pokaż wszystkie niewidoczne znaki",
        "  Khoảng trắng": "  Spacje",
        "  Tab": "  Tabulatory",
        "  Xuống dòng": "  Końce wierszy",
        "  NBSP · zero-width · điều khiển": "  NBSP · zerowa szerokość · sterujące",
        "Xem nhị phân": "Widok binarny",
        "Chế độ CSV (tô màu theo cột)": "Tryb CSV (kolumny w kolorach)",
        "Macro": "Makro",
        "Bắt đầu / dừng ghi": "Rozpocznij / zatrzymaj nagrywanie",
        "Phát lại": "Odtwórz",
        "Phát nhiều lần…": "Odtwórz wielokrotnie…",
        "Phát đến cuối tài liệu": "Odtwarzaj do końca dokumentu",
        "Chạy trên mọi tab": "Uruchom na wszystkich kartach",
        "Hủy macro đang chạy": "Anuluj działające makro",
        "Lưu macro…": "Zapisz makro…",
        "Macro đã lưu…": "Zapisane makra…",
        "Help": "Pomoc",
        "Trợ giúp GEditor": "Pomoc GEditor",
        "Giới thiệu tính năng": "Przegląd funkcji",
        "Di cư từ Notepad++": "Przejście z Notepad++",
        "Tìm": "Znajdź",
        "Thay bằng": "Zamień na",
        "Kế": "Następny",
        "Trước": "Poprzedni",
        "Đếm": "Policz",
        "Đóng": "Zamknij",
        "Kiểm theo JSON Schema…": "Sprawdź według schematu JSON…",
        "Chọn tệp JSON Schema": "Wybierz plik schematu JSON",
        "Không thấy lỗi nào theo schema này.": "Nie znaleziono problemów według tego schematu.",
        "JSON Schema": "Schemat JSON",
        "Kiểm cú pháp đồ thị": "Sprawdź składnię grafu",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Nie rozpoznano formatu grafu — potrzebne rozszerzenie .dot, .gv, .cypher, .ttl lub .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Nie znaleziono błędów składni %@ (sprawdzenie nie jest wyczerpujące).",
        "Cú pháp %@": "Składnia %@",
        "không phải một đối tượng JSON": "nie jest obiektem JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Eksploracja tekstu (n-gramy, TF-IDF)",
        "Tài liệu rỗng.": "Dokument jest pusty.",
        "Không rút được từ khoá nào.": "Nie udało się wydobyć żadnego słowa kluczowego.",
        "Từ khoá": "Słowa kluczowe",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=słowo kluczowe|few=słowa kluczowe|many=słów kluczowych} · %d {one=token|few=tokeny|many=tokenów} · %d {one=dokument|few=dokumenty|many=dokumentów}",
        "Tô lên tài liệu": "Zaznacz w dokumencie",
        "Đánh dấu entity từ danh sách…": "Zaznacz encje z listy…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Wybierz listę encji (CSV lub JSON)",
        "Không đọc được danh sách entity.": "Nie można odczytać listy encji.",
        "Danh sách entity rỗng.": "Lista encji jest pusta.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Nie znaleziono encji w dokumencie (wczytano %d).",
        "%d lần xuất hiện · %@": "%d {one=wystąpienie|few=wystąpienia|many=wystąpień} · %@",
        "Chuyển đổi tri thức…": "Konwertuj wiedzę…",
        "Chuyển đổi: %@ → %@": "Konwersja: %@ → %@",
        "Không chuyển đổi được.": "Nie udało się przekonwertować.",
        "Xem trước cắt chunk…": "Podgląd podziału na fragmenty…",
        "Cỡ cố định 800B, chồng 100B": "Stały rozmiar 800 B, zachodzenie 100 B",
        "Theo câu (≤ 800B)": "Według zdania (≤ 800 B)",
        "Theo heading Markdown": "Według nagłówka Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Pusty dokument — brak fragmentów.",
        "%d chunk · trung bình %d B · %@": "%d {one=fragment|few=fragmenty|many=fragmentów} · średnio %d B · %@",
        "Xuất JSONL": "Wyeksportuj JSONL",
        "Chunk JSONL": "JSONL fragmentów",
        "Mở triple/edge dạng bảng": "Otwórz trójki/krawędzie jako tabelę",
        "Bảng triple": "Tabela trójek",
        "Tài liệu này không có dòng triple nào.": "Ten dokument nie ma żadnego wiersza z trójką.",
        "Không đọc được triple nào — dòng %d: %@": "Nie udało się odczytać żadnej trójki — wiersz %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "Odczytano %1$d {one=trójkę|few=trójki|many=trójek} · pominięto %2$d {one=błędny wiersz|few=błędne wiersze|many=błędnych wierszy} (pierwszy: wiersz %3$d)",
        "Trùng lặp mờ theo cột…": "Rozmyte duplikaty według kolumny…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Rozmyte duplikaty — kolumna «%1$@»: %2$d {one=grupa kandydatów|few=grupy kandydatów|many=grup kandydatów}",
        "Gộp": "Scal",
        "Giống": "Dopasowanie",
        "Các giá trị trong cụm": "Wartości w grupie",
        "Gộp về": "Scal w",
        "Gộp các cụm đã chọn": "Scal wybrane grupy",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Nie wybrano żadnej grupy — naciśnięcie «Scal» NICZEGO nie zmieni. Program nigdy nie scala sam z siebie.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "Wybrano %d {one=grupę|few=grupy|many=grup} · zmieni się %d {one=wiersz|few=wiersze|many=wierszy} · JEDEN krok cofania",
        "Không quét được cột này.": "Nie udało się przeskanować tej kolumny.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Kolumna «%@» nie ma grup rozmytych duplikatów.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Nie scalono żadnej grupy — dokument pozostaje bez zmian.",
        "Khử trùng lặp mờ · cột %@": "Usuwanie rozmytych duplikatów · kolumna %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "Scalono %d {one=grupę|few=grupy|many=grup} · zmieniono %d {one=komórkę|few=komórki|many=komórek}",
        "Báo cáo làm sạch": "Raport czyszczenia",
        "# Báo cáo làm sạch — %@\n\n": "# Raport czyszczenia — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Zastosowano (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Nie zastosowano żadnego kroku._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Profil danych\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d {one=kolumna|few=kolumny|many=kolumn} · %2$d {one=wiersz|few=wiersze|many=wierszy} · przeskanowano w %3$.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Kolumna | Typ | Puste | Unikalne | Min | Maks | Średnia |\n",
        "\n### Giá trị bất thường\n\n": "\n### Wartości odstające\n\n",
        "hàng %d: %@": "wiersz %d: %@",
        "- cột «%@» — %d ô: %@\n": "- kolumna «%1$@» — %2$d {one=komórka|few=komórki|many=komórek}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Pozostało (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Nie ma już żadnych spostrzeżeń._\n",
        "- cột «%@»: %@\n": "- kolumna «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Usuwaj spacje przy zapisie",
        "Chuẩn hóa xuống dòng": "Normalizuj końce wierszy",
        "trước đó": "poprzedni",
        "Không mở lại được thư mục «%@» của phiên trước": "Nie udało się ponownie otworzyć katalogu «%@» z poprzedniej sesji",
        " (và %d file khác)": " (oraz %d {one=inny plik|few=inne pliki|many=innych plików})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "Nie udało się ponownie otworzyć %d {one=karty|few=kart|many=kart}: %@%@ — plików nie ma już w dawnym miejscu.",
        "Không đọc được nội dung từ ống dẫn": "Nie udało się odczytać danych wejściowych z potoku",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Spacje na końcu wiersza będą usuwane przy każdym zapisie",
        "Không cắt khoảng trắng khi lưu nữa": "Spacje nie są już usuwane przy zapisie",
        "Chưa đặt tên.txt": "Bez tytułu.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Konwersja kodowania spowoduje utratę znaków",
        "Vẫn lưu": "Zapisz mimo to",
        "Tài liệu có thay đổi chưa lưu": "Dokument ma niezapisane zmiany",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Zamknięcie bez zapisania je odrzuci.",
        "Bỏ thay đổi": "Odrzuć zmiany",
        "Đi tới dòng": "Przejdź do wiersza",
        "Tài liệu có %d dòng.": "Dokument ma %d {one=wiersz|few=wiersze|many=wierszy}.",
        "Số dòng": "Numer wiersza",
        "Đi tới": "Przejdź",
        "Diễn giải lại theo…": "Zinterpretuj ponownie jako…",
        "Chuyển đổi sang…": "Konwertuj na…",
        "Không diễn giải lại được": "Nie udało się zinterpretować ponownie",
        "Bảng mã %@ không chứa hết ký tự": "%@ nie potrafi przedstawić wszystkich znaków",
        "Vẫn chọn": "Wybierz mimo to",
        "Cột %d": "Kolumna %d",
        "Cột %d: %@": "Kolumna %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Ukryte kolumny: %@ (%d) — przywróć je z menu kontekstowego wiersza nagłówków",
        "Hiện lại: %@": "Pokaż ponownie: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Ukryto kolumnę %@ — w pliku pozostaje nietknięta",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Posortowano według %@ %@ · tylko wyświetlanie",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Posortowano: %@ %@ (tylko wyświetlanie)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ wierszy pasuje — trwa dalsze szukanie…",
        "%d / %d dòng khớp": "%d / %d {one=wiersz pasuje|few=wiersze pasują|many=wierszy pasuje}",
        "Không tìm thấy lỗi trong %d hàng": "Nie znaleziono problemów w %d {one=wierszu|few=wierszach|many=wierszach}",
        "%d hàng lệch số cột": "%d {one=wiersz|few=wiersze|many=wierszy} z niewłaściwą liczbą kolumn",
        "%d ô sai kiểu dữ liệu": "%d {one=komórka|few=komórki|many=komórek} z niewłaściwym typem danych",
        " (đã dừng ở %d lỗi đầu)": " (zatrzymano na pierwszych %d {one=problemie|few=problemach|many=problemach})",
        "   —   kiểu nhận ra: ": "   —   rozpoznane typy: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Wiersz %1$d, kolumna %2$@: «%3$@» nie jest %4$@",
        "Column Editor — %d dòng": "Edytor kolumn — %d {one=wiersz|few=wiersze|many=wierszy}",
        "Phát hiện": "Spostrzeżenia",
        "Hồ sơ dữ liệu": "Profil danych",
        "Hồ sơ dữ liệu — đang quét…": "Profil danych — trwa skanowanie…",
        "Lưu công thức…": "Zapisz przepis…",
        "Xuất báo cáo": "Wyeksportuj raport",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Nie zastosowano żadnej grupy · każda grupa to jeden krok cofania",
        "quá nhiều giá trị": "zbyt wiele wartości",
        "hay gặp: ": "najczęstsze: ",
        "Giá trị điền vào ô thiếu": "Wartość do wypełnienia pustych komórek",
        "Áp dụng": "Zastosuj",
        "Không dựng được bản xem trước": "Nie udało się zbudować podglądu",
        "· giữ nguyên, không đọc được ·": "· zostawiono bez zmian, nie da się odczytać ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Przekształć kolumnę na ISO 8601 (RRRR-MM-DD)",
        "Quy ước số cho cả cột": "Konwencja liczbowa dla całej kolumny",
        "Làm gì với ô thiếu": "Co zrobić z pustymi komórkami",
        "Chuẩn hóa về ISO 8601": "Znormalizuj do ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Czytaj niejednoznaczne komórki z DNIEM na początku (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Czytaj niejednoznaczne komórki z MIESIĄCEM na początku (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Pomiń niejednoznaczne komórki, popraw tylko pewne",
        "Về Việt/Âu (1.234,56)": "Na wietnamski/europejski (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Na angloamerykański (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Na angloamerykański, bez separatora tysięcy (1234.56)",
        "Điền một giá trị mặc định…": "Wypełnij wartością domyślną…",
        "Điền xuôi — lấy giá trị phía trên": "Wypełnij w dół — weź wartość z góry",
        "Điền ngược — lấy giá trị phía dưới": "Wypełnij w górę — weź wartość z dołu",
        "Xóa hàng có ô thiếu ở cột này": "Usuń wiersze z pustą komórką w tej kolumnie",
        "Cắt khoảng trắng hai đầu": "Usuń spacje z obu końców",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Usuń z obu końców i zredukuj spacje wewnątrz",
        "Pivot…": "Tabela przestawna…",
        "Nguồn…": "Źródła…",
        "Pivot — gộp theo cột": "Tabela przestawna — grupuj według kolumny",
        "Hàng (gộp nhóm)": "Wiersze (grupowanie)",
        "Giá trị": "Wartości",
        "+ Hàng": "+ Wiersz",
        "+ Giá trị": "+ Wartość",
        "Xoá hết": "Wyczyść wszystko",
        "Đưa vào ô truy vấn": "Wstaw do pola zapytania",
        "Chọn cột để dựng câu truy vấn.": "Wybierz kolumny, aby zbudować zapytanie.",
        "Không đọc được tên cột của bảng này.": "Nie udało się odczytać nazw kolumn tej tabeli.",
        "Nguồn dữ liệu của truy vấn": "Źródła danych zapytania",
        "«%@» — tài liệu đang mở": "«%@» — otwarty dokument",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ plik zmienił się od czasu zarejestrowania",
        "Thêm file…": "Dodaj plik…",
        "Bỏ hết": "Usuń wszystkie",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Nie udało się wywnioskować nazwy tabeli z «%@» — zmień nazwę pliku.",
        "Tổng": "Suma",
        "Trung bình": "Średnia",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Maks",
        "Đếm khác nhau": "Liczba unikalnych",
        "Biểu đồ": "Wykres",
        "Xuất PNG": "Wyeksportuj PNG",
        "Xuất SVG": "Wyeksportuj SVG",
        "Bảng này không có cột số nào để vẽ.": "Ta tabela nie ma kolumny liczbowej do przedstawienia.",
        "Không dựng được ảnh PNG.": "Nie udało się zbudować obrazu PNG.",
        "Kết quả truy vấn": "Wynik zapytania",
        "Đã lưu %@": "Zapisano %@",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Wykres %1$@ dla «%2$@» — %3$d {one=punkt|few=punkty|many=punktów}, wartości od %4$@ do %5$@",
        "Cột": "Słupkowy",
        "Đường": "Liniowy",
        "Phân bố": "Histogram",
        "Phân tán": "Punktowy",
        "Hộp": "Pudełkowy",
        "CSV: chất lượng dữ liệu…": "CSV: jakość danych…",
        "Chất lượng dữ liệu": "Jakość danych",
        "Xuất vi phạm ra tab mới": "Wyeksportuj naruszenia do nowej karty",
        "Mức": "Poziom",
        "Luật": "Reguła",
        "Vi phạm": "Naruszenia",
        "Tỷ lệ": "Udział",
        "đạt": "zaliczone",
        "lỗi": "błąd",
        "cảnh báo": "ostrzeżenie",
        "hỏng": "uszkodzone",
        "Đã đánh dấu %d dòng vi phạm": "Zaznaczono %d {one=naruszający wiersz|few=naruszające wiersze|many=naruszających wierszy}",
        "Xu hướng": "Trend",
        "Lúc chấm": "Oceniono",
        "Số hàng": "Wierszy",
        "Lệch": "Różnica",
        "Luật trượt": "Niezaliczone reguły",
        "Điểm chất lượng": "Ocena jakości",
        "Điểm theo thời gian": "Ocena w czasie",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Nie ma jeszcze historii — każda ocena dopisuje ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "jeden wiersz do pliku «.history.jsonl» obok reguł.",
        "%d mốc trong lịch sử": "%d {one=punkt|few=punkty|many=punktów} w historii",
        " · %d dòng KHÔNG đọc được": " · %d {one=wiersz NIE DO ODCZYTANIA|few=wiersze NIE DO ODCZYTANIA|many=wierszy NIE DO ODCZYTANIA}",
        " · chọn hai dòng để so": " · wybierz dwa wiersze do porównania",
        "điểm %+.1f": "ocena %+.1f",
        "không chiều nào tụt": "żaden wymiar nie spadł",
        "tụt: ": "spadły: ",
        "%d luật mới trượt: %@": "%d {one=nowo niezaliczona reguła|few=nowo niezaliczone reguły|many=nowo niezaliczonych reguł}: %@",
        "số hàng %+d": "wierszy %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (oraz %d {one=dalsze ostrzeżenie|few=dalsze ostrzeżenia|many=dalszych ostrzeżeń} na karcie Trend)",
        "Không sửa tự động được: ": "Brak automatycznej poprawki: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Otwiera odpowiednie narzędzie w warsztacie czyszczenia, a potem od razu ocenia ponownie.",
        "Xử lý giá trị thiếu…": "Obsłuż brakujące wartości…",
        "Chuẩn hóa ngày…": "Znormalizuj daty…",
        "Khử trùng lặp…": "Usuń duplikaty…",
        "Thay thế…": "Zamień…",
        "Xem các dòng sai": "Pokaż błędne wiersze",
        "Không tìm thấy cột «%@» trong bảng này.": "Kolumny «%@» nie ma w tej tabeli.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplikaty usunięte — «%@» jest teraz unikalna. Ocena: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplikaty usunięte, ale «%1$@» ma nadal %2$d {one=powtórzony wiersz|few=powtórzone wiersze|many=powtórzonych wierszy} (wcześniej: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "te wiersze mają wspólny KLUCZ, ale nie cały wiersz, więc trzeba je obejrzeć i wybrać ",
        "giữ hàng nào.": "który zostawić.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Nie udało się odczytać żadnej wartości naruszającej tę regułę.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {one=błędna wartość|few=błędne wartości|many=błędnych wartości} w kolumnie «%2$@» — wypełnij pole Zamień i naciśnij Podgląd",
        "Đã chấm lại: %.0f/100": "Oceniono ponownie: %.0f/100",
        "Xem trước báo cáo": "Podgląd raportu",
        "Tham số…": "Parametry…",
        "Xuất HTML…": "Wyeksportuj HTML…",
        "In / PDF…": "Drukuj / PDF…",
        "%d khối chạy được · %d khối HỎNG": "Wykonano %d {one=blok|few=bloki|many=bloków} · %d {one=blok|few=bloki|many=bloków} NIE POWIODŁO SIĘ",
        "%d khối chạy được": "Wykonano %d {one=blok|few=bloki|many=bloków}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · NIEAKTUALNE DANE — plik źródłowy się zmienił; zbuduj ponownie",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Podgląd raportu wymaga dokumentu .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Nie znaleziono źródła danych — zadeklaruj «source: plik.csv» we frontmatterze.",
        "Không dựng được báo cáo.": "Nie udało się zbudować raportu.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Ten raport nie deklaruje żadnego parametru we frontmatterze.",
        "Tham số báo cáo": "Parametry raportu",
        "Dựng lại": "Zbuduj ponownie",
        "Đã xuất %@": "Wyeksportowano %@",
        "Báo cáo: xem trước": "Raport: podgląd",
        "Báo cáo: sinh loạt…": "Raport: generowanie wsadowe…",
        "không phải tài liệu .greport.md": "to nie jest dokument .greport.md",
        "không phân tích được báo cáo": "nie udało się przeanalizować raportu",
        "không tìm được dữ liệu nguồn": "nie znaleziono danych źródłowych",
        "không đọc được danh sách tham số": "nie udało się odczytać listy parametrów",
        "Sinh loạt cần tài liệu đuôi .%@": "Generowanie wsadowe wymaga dokumentu .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Wybierz listę parametrów (CSV lub JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Wybierz katalog dla %d {one=raportu|few=raportów|many=raportów}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "brakujące parametry ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "wskazuje na sam plik źródłowy — odmówiono nadpisania",
        "%d khối HỎNG": "%d {one=blok|few=bloki|many=bloków} NIE POWIODŁO SIĘ",
        "Sinh loạt xong: %d tệp · %d hỏng": "Wsad zakończony: %d {one=plik|few=pliki|many=plików} · %d nieudanych",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "Nie udało się zbudować %d {one=zestawu parametrów|few=zestawów parametrów|many=zestawów parametrów} — zobacz podsumowanie",
        "Sơ đồ Mermaid: xem trước": "Diagram Mermaid: podgląd",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagram Mermaid: wstaw szablon…",
        "Sơ đồ Mermaid: định dạng lại": "Diagram Mermaid: sformatuj ponownie",
        "Nền trong suốt": "Przezroczyste tło",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Ten Mac nie potrafi przekształcić diagramu w PNG — wymagany jest macOS 13. Eksport SVG nadal działa.",
        "Lưu PNG %@…": "Zapisz PNG %@…",
        "Lưu SVG…": "Zapisz SVG…",
        "Chép ảnh vào clipboard": "Skopiuj obraz do schowka",
        "Màu thương hiệu…": "Kolory marki…",
        "Màu thương hiệu cho sơ đồ": "Kolory marki dla diagramów",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Każde pole to kolor w postaci #rrggbb. Zapisywane w «themes/mermaid-brand.json» — można skopiować na innego Maca.",
        "Màu chính": "Kolor główny",
        "Chữ trên nút": "Tekst na węzłach",
        "Viền": "Obramowanie",
        "Đường nối": "Połączenia",
        "Nền khi xuất ảnh": "Tło przy eksporcie",
        "Lưu và chèn %%{init}%% vào tài liệu": "Zapisz i wstaw %%{init}%% do dokumentu",
        "Đã lưu màu thương hiệu": "Zapisano kolory marki",
        "Đã chép ảnh sơ đồ vào clipboard": "Skopiowano obraz diagramu do schowka",
        "Đã lưu %@ — %@": "Zapisano %@ — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Ten diagram ma już dyrektywę %%{init}%% — twoja pozostaje nietknięta.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "Wstawiono %%{init}%% — diagram niesie teraz własne kolory",
        "Chèn màu thương hiệu vào sơ đồ": "Wstaw kolory marki do diagramu",
        "Định dạng sơ đồ Mermaid": "Sformatuj ponownie diagram Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Źródło diagramu jest już uporządkowane — nie ma czego zmieniać",
        "Đã định dạng lại sơ đồ": "Diagram sformatowany ponownie",
        "Đã định dạng lại %d sơ đồ": "Sformatowano ponownie %d {one=diagram|few=diagramy|many=diagramów}",
        "Thư viện mẫu sơ đồ": "Biblioteka szablonów diagramów",
        "Mẫu sơ đồ đầy đủ": "Pełne szablony diagramów",
        "Mẩu cú pháp": "Fragmenty składni",
        "Đang soạn: %@": "Edytowany: %@",
        "Đã chèn mẫu «%@»": "Wstawiono szablon «%@»",
        "Tài liệu đang ở chế độ chỉ đọc.": "Ten dokument jest tylko do odczytu.",
        "Sơ đồ Mermaid": "Diagram Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Ten dokument nie ma żadnego bloku mermaid.",
        "Thương hiệu": "Marka",
        "Xuất…": "Wyeksportuj…",
        "Chưa có sơ đồ nào": "Nie ma jeszcze diagramów",
        "%d sơ đồ · %@": "%d {one=diagram|few=diagramy|many=diagramów} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d {one=diagram|few=diagramy|many=diagramów} NIE POWIODŁO SIĘ — diagram %3$d%4$@",
        ", dòng %d": ", wiersz %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Ten dokument nie ma bloku ```mermaid i nie jest też plikiem .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Żaden diagram nie skończył się jeszcze rysować.",
        "Không tìm thấy «%@» trong mã sơ đồ": "Nie znaleziono «%@» w źródle diagramu",
        "không dựng được hàng rào chặn mạng cho WKWebView": "nie udało się zbudować blokady sieciowej dla WKWebView",
        "Luật kết hợp": "Reguły asocjacyjne",
        "Mỗi dòng một giỏ": "Jeden koszyk na wiersz",
        "Hai cột: mã · item": "Dwie kolumny: identyfikator · pozycja",
        "Dạng dữ liệu giao dịch": "Postać danych transakcyjnych",
        "Cột giỏ hàng hoặc mã giao dịch": "Kolumna koszyka lub identyfikatora transakcji",
        "Cột item": "Kolumna pozycji",
        "Ký tự phân tách item": "Znak rozdzielający pozycje",
        "Support tối thiểu, phần trăm": "Minimalne support, procent",
        "Confidence tối thiểu, phần trăm": "Minimalne confidence, procent",
        "Tách bởi:": "Rozdzielone przez:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "Tabela reguł asocjacyjnych",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Uwaga",
        "%d giao dịch · %d item · %d luật": "%d {one=transakcja|few=transakcje|many=transakcji} · %d {one=pozycja|few=pozycje|many=pozycji} · %d {one=reguła|few=reguły|many=reguł}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — żadna reguła nie osiągnęła progów; obniż support lub confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — ZATRZYMANO WCZEŚNIEJ, tabela jest NIEPEŁNA",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transakcja zawiera|few=transakcje zawierają|many=transakcji zawiera} obie strony",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Postać dwukolumnowa wymaga dwóch RÓŻNYCH kolumn.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "Zaznaczono %1$d {one=wiersz|few=wiersze|many=wierszy} w %2$d {one=transakcji|few=transakcjach|many=transakcjach} zawierających «%3$@»",
        "CSV: luật kết hợp…": "CSV: reguły asocjacyjne…",
        "Khai phá theo nhóm": "Eksploracja grupowa",
        "Cột nhóm": "Kolumna grupująca",
        "Cột giá trị": "Kolumna wartości",
        "Cột thứ hai cho tương quan": "Druga kolumna do korelacji",
        "Cách xếp hạng": "Sposób uszeregowania",
        "Nhóm theo:": "Grupuj według:",
        "Giá trị:": "Wartość:",
        "Xếp theo:": "Uszereguj według:",
        "Bảng xếp hạng nhóm": "Tabela rankingu grup",
        "Nhóm": "Grupa",
        "Hàng": "Wierszy",
        "Hàng rào riêng": "Własny próg",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "Różnica r",
        "Ghi chú": "Notatka",
        "không đo được": "nie da się zmierzyć",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=grupa|few=grupy|many=grup} · ogólna korelacja odniesienia %@",
        " · ĐÃ CẮT %d nhóm": " · ODRZUCONO %d {one=GRUPĘ|few=GRUPY|many=GRUP}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Ta tabela nie ma kolumny tekstowej do grupowania.",
        "Bảng này không có cột số nào để khai phá.": "Ta tabela nie ma kolumny liczbowej do eksploracji.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "Zaznaczono %1$d {one=wiersz|few=wiersze|many=wierszy} grupy «%2$@»",
        "CSV: khai phá theo nhóm…": "CSV: eksploracja grupowa…",
        "\u{2194}": "↔",
        "Dự báo": "Prognoza",
        "Cột giá trị theo thời gian": "Kolumna wartości w czasie",
        "Mô hình dự báo": "Model prognozy",
        "Số kỳ dự báo": "Liczba prognozowanych okresów",
        "Kết luận so với baseline": "Werdykt wobec modeli odniesienia",
        "Mô hình:": "Model:",
        "Số kỳ:": "Okresy:",
        "Chu kỳ:": "Sezon:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Okres sezonowy; zostaw puste, aby wykryć automatycznie",
        "Bảng giá trị dự báo": "Tabela wartości prognozowanych",
        "Kỳ": "Okres",
        "Dải 80%": "Przedział 80%",
        "Dải 95%": "Przedział 95%",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "nie da się obliczyć",
        "Bảng này không có cột số nào để dự báo.": "Ta tabela nie ma kolumny liczbowej do prognozowania.",
        "Không dựng được dự báo cho cột này.": "Nie udało się zbudować prognozy dla tej kolumny.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Kolumna «%1$@» ma tylko %2$d {one=wartość liczbową|few=wartości liczbowe|many=wartości liczbowych} — do prognozy potrzeba co najmniej 4.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Szereg jest czytany dokładnie w kolejności wierszy pliku — bez sortowania i bez wnioskowania kolumny czasu.\n",
        "Sai số huấn luyện": "Błąd uczenia",
        "CSV: dự báo chuỗi thời gian…": "CSV: prognoza szeregu czasowego…",
        "Holt-Winters cộng": "Holt-Winters addytywny",
        "Holt-Winters nhân": "Holt-Winters multiplikatywny",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Kolumny wchodzące do grupowania",
        "Đường cong WCSS": "Krzywa WCSS",
        "Phân cụm": "Skupienie",
        "Chuẩn hoá:": "Skalowanie:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Wybierz co najmniej jedną kolumnę.",
        "Không đủ dữ liệu để dựng đường cong.": "Za mało danych, aby zbudować krzywą.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Łokieć sugeruje k = %d. WCSS ZAWSZE maleje wraz ze wzrostem k, więc to sposób czytania wykresu, a nie kryterium statystyczne — spójrz na krzywą i oceń, czy załamanie jest wyraźne.",
        "WCSS theo k": "WCSS według k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k-odległość sugeruje eps = %1$@ (minPts domyślnie 2 × liczba kolumn = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Odległość do k-tego sąsiada",
        "Cần ít nhất 2 cột số để phân cụm.": "Do grupowania potrzeba co najmniej 2 kolumn liczbowych.",
        "Cụm theo %@ và %@": "Skupienia według %@ i %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — skupienia znaleziono w %d {one=wymiarze|few=wymiarach|many=wymiarach}; wykres pokazuje tylko 2 pierwsze",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# szum (cluster_id = -1): %d {one=wiersz|few=wiersze|many=wierszy}\n",
        "CSV: phân cụm…": "CSV: grupowanie…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Środki skupień (jednostki pierwotne) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Macierz korelacji",
        "Phương pháp tương quan": "Metoda korelacji",
        "Tương quan không hàm ý nhân quả.": "Korelacja nie oznacza przyczynowości.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Najsilniejsza para: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Kliknij komórkę, aby zobaczyć wykres punktowy.",
        "Không cặp nào đo được.": "Żadnej pary nie da się zmierzyć.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ na %4$d {one=wierszu|few=wierszach|many=wierszach}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Do korelacji potrzeba co najmniej 2 kolumn liczbowych.",
        "Không đọc được cột «%@».": "Nie udało się odczytać kolumny «%@».",
        "CSV: ma trận tương quan…": "CSV: macierz korelacji…",
        "Bất thường": "Anomalie",
        "Danh sách bất thường": "Lista anomalii",
        "Cột:": "Kolumna:",
        "Cột số cần xét": "Kolumna liczbowa do zbadania",
        "Cách:": "Metoda:",
        "Phương pháp phát hiện": "Metoda wykrywania",
        "Phương pháp đã dùng": "Użyta metoda",
        "Ngưỡng": "Próg",
        "Đánh dấu": "Zaznacz",
        "Xuất tab mới": "Wyeksportuj do nowej karty",
        "Dòng": "Wiersz",
        "Điểm": "Ocena",
        "Vì sao": "Dlaczego",
        "nhẹ": "łagodna",
        "vừa": "umiarkowana",
        "nặng": "poważna",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=wiersz|few=wiersze|many=wierszy} (%.2f%%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Ta tabela nie ma kolumny liczbowej, w której można szukać anomalii.",
        "Đã đánh dấu %d dòng bất thường": "Zaznaczono %d {one=anomalny wiersz|few=anomalne wiersze|many=anomalnych wierszy}",
        "CSV: tìm bất thường…": "CSV: znajdź anomalie…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d {one=reguła|few=reguły|many=reguł}, wszystkie ZALICZONE · %2$d {one=wiersz|few=wiersze|many=wierszy} · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d {one=błąd|few=błędy|many=błędów} · %2$d {one=ostrzeżenie|few=ostrzeżenia|many=ostrzeżeń} w %3$d {one=regule|few=regułach|many=regułach} · %4$d {one=wiersz|few=wiersze|many=wierszy} · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Najpierw zapisz dokument — reguły jakości leżą obok pliku danych.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Nie ma jeszcze zestawu reguł. Utwórz plik %@ i otwórz ponownie.",
        "Lịch sử": "Historia",
        "Câu đã lưu": "Zapisane zapytania",
        "Lưu câu này…": "Zapisz to zapytanie…",
        "Lưu câu truy vấn": "Zapisz zapytanie",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Nadaj mu nazwę, aby odnaleźć je później. Ta sama nazwa nadpisuje.",
        "Ví dụ: Doanh thu theo tỉnh": "Na przykład: Przychód według województwa",
        "Chưa nhập giá trị cho tham số: %@": "Nie podano wartości parametru: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Wtyczka zmieniła się od czasu zatwierdzenia — GEditor odmawia jej uruchomienia",
        "Chạy plugin chưa duyệt?": "Uruchomić niezatwierdzoną wtyczkę?",
        "Tôi tin file này — chạy": "Ufam temu plikowi — uruchom",
        "KHÔNG có chữ ký": "NIEPODPISANA",
        "Chữ ký: %@": "Podpis: %@",
        "Đường dẫn: %@": "Ścieżka: %@",
        "Thay": "Zamień",
        "Thay tất cả": "Zamień wszystko",
        "Chuỗi thuần": "Zwykły tekst",
        "Extended (\\n \\t \\xNN)": "Rozszerzony (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Wyrażenie regularne",
        "Phân biệt hoa thường": "Uwzględniaj wielkość liter",
        "Cả từ": "Całe słowo",
        "Không có kết quả": "Brak wyników",
        "Thử biểu thức chính quy…": "Wypróbuj wyrażenie regularne…",
        "Chế độ Log (tô theo mức)": "Tryb dziennika (kolor według poziomu)",
        "Lọc log theo mức…": "Filtruj dziennik według poziomu…",
        "Chạy trên cả thư mục…": "Uruchom na całym katalogu…",
        "Lọc qua lệnh ngoài…": "Filtruj przez polecenie zewnętrzne…",
        "Script…": "Skrypty…",
        "Gói mở rộng…": "Pakiety rozszerzeń…",
        "Cửa sổ mới": "Nowe okno",
        "Tách tab ra cửa sổ mới": "Odłącz kartę do nowego okna",
        "Chưa mở thư mục nào": "Nie otwarto żadnego katalogu",
        "Tìm file trong thư mục": "Znajdź plik w katalogu",
        "Lọc theo tên": "Filtruj według nazwy",
        "File mới…": "Nowy plik…",
        "Thư mục mới…": "Nowy katalog…",
        "Đổi tên…": "Zmień nazwę…",
        "Chuyển vào Thùng rác": "Przenieś do Kosza",
        "Hiện trong Finder": "Pokaż w Finderze",
        "Đang đọc cấu trúc tài liệu…": "Trwa odczyt struktury dokumentu…",
        "file này không có hàm nào": "ten plik nie ma funkcji",
        "Không có gì khớp": "Brak dopasowań",
        "Văn bản thuần": "Zwykły tekst",
        "🔒 Chỉ đọc": "🔒 Tylko do odczytu",
        "Đang theo dõi": "Śledzony",
        "ngắt tại cột": "zawijanie na kolumnie",
        "Cú pháp": "Składnia",
        "Bấm để chèn vào ô truy vấn": "Kliknij, aby wstawić do zapytania",
        "truy vấn không hợp lệ": "nieprawidłowe zapytanie",
        "khóa `ten` ở gốc": "klucz «nazwa» w korzeniu",
        "khóa có dấu cách": "klucz ze spacjami",
        "phần tử đầu": "pierwszy element",
        "mọi phần tử": "wszystkie elementy",
        "lát cắt": "wycinek",
        "hợp nhiều chỉ số": "suma indeksów",
        "mọi khóa `gia` ở mọi tầng": "wszystkie klucze «cena» na wszystkich poziomach",
        "mọi nút": "wszystkie węzły",
        "lọc theo số": "filtruj według liczby",
        "lọc theo có mặt": "filtruj według obecności",
        "Tới lỗi đầu tiên": "Przejdź do pierwszego błędu",
        "Cột doanh_thu là số": "Kolumna przychód jest liczbowa",
        "lọc…": "filtruj…",
        "Hủy": "Anuluj",
        "Thực hiện thay": "Wykonaj zamianę",
        "xem trước": "podgląd",
        "tương tác": "interaktywnie",
        "Soạn thảo": "Edycja",
        "Giao diện": "Interfejs",
        "Phím tắt": "Skróty klawiszowe",
        "Cỡ chữ": "Rozmiar tekstu",
        "Bề rộng TAB": "Szerokość tabulatora",
        "Thụt lề bằng TAB": "Wcinaj tabulatorami",
        "Tự động thụt lề khi xuống dòng": "Wcinaj automatycznie przy przejściu do nowego wiersza",
        "Tô mọi kết quả tìm kiếm": "Podświetlaj wszystkie wyniki wyszukiwania",
        "Chuẩn hóa về NFC khi lưu": "Normalizuj do NFC przy zapisie",
        "Ngôn ngữ": "Język",
        "Nền": "Wygląd",
        "Theo hệ thống": "Zgodnie z systemem",
        "Sáng": "Jasny",
        "Tối": "Ciemny",
        "Theme": "Motyw",
        "Dùng preset Notepad++": "Użyj zestawu Notepad++",
        "Về phím mặc định": "Wróć do klawiszy domyślnych",
        "Mở file cấu hình": "Otwórz plik konfiguracji",
        "Xuất theme hiện tại": "Wyeksportuj bieżący motyw",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Zmiana języka zadziała w pełni przy następnym uruchomieniu.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Klawisze domyślne wrócą przy następnym uruchomieniu.",
        "Xem trước Markdown": "Podgląd Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Podgląd korzysta z systemowego silnika Markdown: na razie bez tabel i bez kolorowania bloków kodu.",
        "Thử biểu thức chính quy": "Wypróbuj wyrażenie regularne",
        "Biểu thức": "Wyrażenie",
        "Văn bản thử": "Tekst próbny",
        "Kết quả": "Wynik",
        "Kết quả khớp": "Dopasowania",
        "Biểu thức này làm gì": "Co robi to wyrażenie",
        "Giải thích biểu thức": "Wyjaśnij wyrażenie",
        "Chế độ tìm kiếm": "Tryb wyszukiwania",
        "Kết quả tìm kiếm": "Wyniki wyszukiwania",
        "Không khớp chỗ nào": "Brak dopasowań",
        " (đã cắt bớt)": " (skrócono)",
        "Bản đồ tài liệu": "Mapa dokumentu",
        "Thanh tab": "Pasek kart",
        "Hàng tiêu đề cột": "Wiersz nagłówków kolumn",
        "Không có cột nào": "Brak kolumn",
        "Cây thư mục workspace": "Drzewo obszaru roboczego",
        "Danh sách hàm và lớp": "Lista funkcji i klas",
        "Kết quả tìm trong thư mục": "Wyniki wyszukiwania w katalogu",
        "Bảng dữ liệu CSV": "Tabela danych CSV",
        "Bàn làm sạch dữ liệu": "Warsztat czyszczenia danych",
        "Truy vấn JSONPath": "Zapytanie JSONPath",
        "Danh sách lỗi dữ liệu": "Lista błędów w danych",
        "Bộ đánh giá golden set…": "Ewaluator zbioru złotego…",
        "So với điểm ngoài (JSONL)…": "Porównaj z ocenami zewnętrznymi (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Wybierz plik ocen zewnętrznych (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Zmień nazwę zaznaczonego węzła",
        "Gộp các node đang chọn": "Scal zaznaczone węzły",
        "Tách node đang chọn": "Podziel zaznaczony węzeł",
        "Trích subgraph đang chọn ra tab mới": "Wyodrębnij zaznaczony podgraf do nowej karty",
        "Không có gì để đổi": "Nie ma czego zmieniać",
        "%@ — áp %d thay đổi?": "%1$@ — zastosować %2$d {one=zmianę|few=zmiany|many=zmian}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d {one=zmiana|few=zmiany|many=zmian} · Cmd-Z cofa całą partię",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Ustaw kursor DOKŁADNIE na jednym węźle i spróbuj ponownie",
        "Đổi tên «%@»": "Zmień nazwę «%@»",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Wszystkie krawędzie i etykiety wskazujące ten węzeł zmienią się razem z nim.",
        "Đổi tên node": "Zmień nazwę węzła",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Zaznacz CO NAJMNIEJ DWA węzły i spróbuj ponownie",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Postać kanoniczna «%@» — najczęstsza, najdłuższa, ze znakami diakrytycznymi",
        "Gộp node": "Scal węzły",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Zaznacz WIERSZE KRAWĘDZI do przeniesienia i spróbuj ponownie",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Wszystkie zaznaczone wiersze muszą dotykać DOKŁADNIE jednego węzła — zaznacz więcej wierszy krawędzi",
        "Tách «%@» — chuyển %d cạnh": "Podział «%1$@» — przeniesienie %2$d {one=krawędzi|few=krawędzi|many=krawędzi}",
        "Cạnh tới: %@": "Krawędzie do: %@",
        "Tách node": "Podziel węzeł",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Dokument niezapisany — wyodrębniony plik potrzebuje miejsca obok",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Zaznacz część grafu do wyodrębnienia i spróbuj ponownie",
        "Gom biến thể entity → bảng duyệt": "Zbierz warianty encji → tabela przeglądu",
        "Áp bảng duyệt đã sửa": "Zastosuj poprawioną tabelę przeglądu",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Dokument niezapisany — tabela przeglądu musi leżeć obok pliku grafu",
        "Không tìm thấy biến thể nào để gom": "Nie znaleziono wariantów do zebrania",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=grupa wariantów|few=grupy wariantów|many=grup wariantów} — popraw kolumnę «canonical» i uruchom «Zastosuj tabelę przeglądu»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Nie ma tabeli przeglądu «%@» — najpierw uruchom «Zbierz warianty encji»",
        "Bảng duyệt không đọc được: %@": "Nie można odczytać tabeli przeglądu: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Tabela przeglądu nie ma żadnego wiersza do zmiany",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Żadne miejsce w grafie nie pasuje do tabeli przeglądu",
        "Gom biến thể entity": "Zbierz warianty encji",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "Zastosowano %d {one=zmianę|few=zmiany|many=zmian} · tabelę aliasów i listę znaczników zapisano obok pliku",
        "Áp %d thay đổi lên đồ thị?": "Zastosować %d {one=zmianę|few=zmiany|many=zmian} do grafu?",
        "%d alias → dạng chuẩn.": "%d {one=alias|few=aliasy|many=aliasów} → postać kanoniczna.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "SCAL węzły (nie da się cofnąć przez ponowne wpisanie):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=aliasu nie ma|few=aliasów nie ma|many=aliasów nie ma} w grafie i został pominięty.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Analiza pokrycia fragment ↔ encja",
        "Xuất gói ngữ cảnh (JSONL)": "Wyeksportuj pakiet kontekstu (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Pokrycie fragment ↔ encja ↔ graf",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=encja|few=encje|many=encji} · %2$d {one=fragment|few=fragmenty|many=fragmentów} · %3$.0f%% encji wspomnianych · %4$.0f%% fragmentów z encją",
        "Entity không chunk nào nhắc tới": "Encje, których nie wspomina żaden fragment",
        "Chunk mồ côi (không chứa entity nào)": "Osierocone fragmenty (bez żadnej encji)",
        "Node đồ thị không có entity đối ứng": "Węzły grafu bez odpowiadającej encji",
        "không có": "brak",
        "Phương pháp": "Metoda",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Nie udało się zbudować odwzorowania fragment ↔ encja",
        "Chấm sức khoẻ đồ thị": "Oceń kondycję grafu",
        "sức khoẻ đồ thị": "kondycja grafu",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Kondycja %1$@/100 · %2$d {one=błąd|few=błędy|many=błędów} · %3$d {one=odwrócenie|few=odwrócenia|many=odwróceń} · %4$d osieroconych",
        "Lai với đồ thị": "Hybryda z grafem",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: sygnał grafu jest całkowicie pomijany, wynik jest taki sam jak czysty BM25",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α wysokie: graf tylko lekko koryguje ranking BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α w okolicy domyślnej 0,7: prowadzi BM25, graf koryguje",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α niskie: prowadzi graf, BM25 tylko rozstrzyga remisy",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: tylko sygnał grafu; fragmenty bez encji są sobie równe",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Dokument niezapisany — hybryda potrzebuje pliku grafu obok korpusu",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Nie znaleziono pliku grafu «%@» — hybryda potrzebuje go, aby uzyskać sygnał",
        "lai %.1f ms · %@": "hybryda %.1f ms · %@",
        "Thuật toán…": "Algorytmy…",
        "PageRank (độ dày viền)": "PageRank (grubość obramowania)",
        "Cộng đồng (màu nền)": "Społeczności (kolor tła)",
        "Thành phần liên thông": "Składowe spójne",
        "Xuất bảng node ra tab mới": "Wyeksportuj tabelę węzłów do nowej karty",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d {one=składowa|few=składowe|many=składowych} · największa %2$d {one=węzeł|few=węzły|many=węzłów} · %3$d osieroconych węzłów",
        "Tài liệu này không phải đồ thị DOT": "Ten dokument nie jest grafem DOT",
        "Không dựng được bảng node/cạnh: %@": "Nie udało się zbudować tabeli węzłów/krawędzi: %@",
        "%d hàng · %@": "%d {one=wiersz|few=wiersze|many=wierszy} · %@",
        "Gán nhãn": "Oznacz",
        "Ghi chú (tuỳ chọn)": "Notatka (opcjonalnie)",
        "Lưu record": "Zapisz rekord",
        "Xuất CSV": "Wyeksportuj CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Dokument niezapisany — ewaluator musi leżeć obok pliku korpusu",
        "Không nạp được bộ đánh giá: %@": "Nie udało się wczytać ewaluatora: %@",
        "Không lưu được: %@": "Nie udało się zapisać: %@",
        "Bộ đánh giá chưa có record nào": "Ewaluator nie ma jeszcze żadnego rekordu",
        "Không ghi được: %@": "Nie udało się zapisać: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Ten dokument nie jest plikiem .mmd, nie jest DOT i nie ma bloku mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=węzeł|few=węzły|many=węzłów} · %d {one=krawędź|few=krawędzie|many=krawędzi} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagram Mermaid: dodaj element…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagram Mermaid: połącz dwa zaznaczone elementy",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagram Mermaid: zmień etykietę zaznaczonego elementu…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagram Mermaid: usuń zaznaczony element",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagram Mermaid: przesuń komunikat w górę",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagram Mermaid: przesuń komunikat w dół",
        "Thêm phần tử": "Dodaj element",
        "Thêm participant": "Dodaj uczestnika",
        "Thêm mục": "Dodaj pozycję",
        "Thêm mục sơ đồ": "Dodaj pozycję do diagramu",
        "Sửa mục sơ đồ": "Zmień pozycję diagramu",
        "Xoá mục sơ đồ": "Usuń pozycję z diagramu",
        "Xoá phần tử": "Usuń element",
        "Sửa nhãn": "Zmień etykietę",
        "Đổi thứ tự message": "Zmień kolejność komunikatów",
        "Tên mục": "Nazwa pozycji",
        "Mục mới": "Nowa pozycja",
        "Tên mục hiện trên sơ đồ.": "Nazwa pozycji pojawia się na diagramie.",
        "Bảng thuộc tính sơ đồ": "Tabela właściwości diagramu",
        "Tài liệu này không có khối mermaid nào": "Ten dokument nie ma bloku mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identyfikator w źródle diagramu — bez spacji. Etykietę zmienia się potem dwukrotnym kliknięciem.",
        "Để trống thì hiện chính định danh.": "Jeśli zostawisz puste, wyświetli się sam identyfikator.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Zmienia się tylko widoczna ETYKIETA; identyfikator elementu pozostaje ten sam.",
        "Không rõ «%@» là phần tử nào": "Nie wiadomo, którym elementem jest «%@»",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Zaznacz DOKŁADNIE DWA elementy i spróbuj ponownie",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Ustaw kursor DOKŁADNIE na jednym elemencie i spróbuj ponownie",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Wybierz JEDEN element do usunięcia albo dwa elementy połączone krawędzią",
        "Xoá «%@» và %d cạnh chạm nó?": "Usunąć «%1$@» oraz %2$d {one=krawędź, która go dotyka|few=krawędzie, które go dotykają|many=krawędzi, które go dotykają}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Węzły na drugim końcu tych krawędzi zostają zachowane — są deklarowane ponownie wraz z etykietą, jeśli instrukcja krawędzi była ich jedyną deklaracją.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Diagram «%1$@» edytuje się wyłącznie jako tekst — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: przeciągnij między dwoma elementami, aby je połączyć, kliknij dwukrotnie, aby zmienić etykietę",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: przeciągnij między dwoma uczestnikami, aby dodać komunikat; kolejność zmienisz w menu Narzędzia",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: edytuj w tabeli właściwości poniżej",
        "Soạn trực quan đã bật": "Włączono edycję wizualną",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d {one=pozycja|few=pozycje|many=pozycji} — edytuj bezpośrednio w tabeli, każda komórka to jeden krok cofania",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Dla wykresu kołowego to liczba; dla Gantta to, co następuje po dwukropku.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagram Mermaid: wyodrębnij blok do pliku .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagram Mermaid: wstaw z powrotem wskazywany plik",
        "Tách khối sơ đồ": "Wyodrębnij blok diagramu",
        "Nhúng khối sơ đồ": "Wstaw blok diagramu",
        "Tách khối sơ đồ ra tệp riêng": "Wyodrębnij blok diagramu do osobnego pliku",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Plik trafia OBOK dokumentu; w bloku zostaje jeden wiersz odwołania, więc edytujesz tylko w jednym miejscu.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Dokument niezapisany — plik diagramu potrzebuje miejsca obok",
        "Đã có tệp «%@» — chọn tên khác": "Plik «%@» już istnieje — wybierz inną nazwę",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Wyodrębniono do «%@» — w bloku został wiersz odwołania",
        "Mở tệp": "Otwórz plik",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» wstawiono z powrotem; plik nadal jest na dysku",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Ten blok zawiera prawdziwy diagram, a nie odwołanie",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Ten blok odwołuje się do «%@» — otwórz tamten plik, aby go edytować",
        "Không đọc được tệp sơ đồ %@": "Nie udało się odczytać pliku diagramu %@",
        "Soạn trực quan": "Edycja wizualna",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Przeciągnij z jednego węzła do drugiego, aby dodać krawędź; kliknij dwukrotnie, aby zmienić etykietę. Każda czynność to jeden krok cofania.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Edycja wizualna: przeciągnij między dwoma węzłami, aby dodać krawędź, kliknij dwukrotnie, aby zmienić etykietę",
        "Soạn trực quan đã tắt": "Wyłączono edycję wizualną",
        "Thêm node…": "Dodaj węzeł…",
        "Thêm cạnh giữa hai node đang chọn…": "Dodaj krawędź między dwoma zaznaczonymi węzłami…",
        "Sửa nhãn node đang chọn…": "Zmień etykietę zaznaczonego węzła…",
        "Xoá node/cạnh đang chọn": "Usuń zaznaczony węzeł/krawędź",
        "Thêm node": "Dodaj węzeł",
        "Thêm cạnh": "Dodaj krawędź",
        "Sửa nhãn node": "Zmień etykietę węzła",
        "Xoá node": "Usuń węzeł",
        "Xoá cạnh": "Usuń krawędź",
        "Cmd-Z hoàn tác": "Cmd-Z cofa",
        "Tài liệu đang ở chế độ chỉ đọc": "Ten dokument jest tylko do odczytu",
        "Nhãn của «%@»": "Etykieta «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Zmienia się tylko widoczna ETYKIETA; identyfikator węzła pozostaje ten sam.",
        "Không rõ «%@» là node nào": "Nie wiadomo, którym węzłem jest «%@»",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identyfikator węzła w pliku DOT. Etykietę zmienia się potem dwukrotnym kliknięciem na rysunku.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Zaznacz DOKŁADNIE DWA węzły i spróbuj ponownie",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Wybierz JEDEN węzeł do usunięcia albo dwa węzły połączone krawędzią",
        "Xoá node «%@» và %d cạnh chạm nó?": "Usunąć węzeł «%1$@» oraz %2$d {one=krawędź, która go dotyka|few=krawędzie, które go dotykają|many=krawędzi, które go dotykają}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Jeśli zostaną wiszące krawędzie, DOT odtworzy z nich węzły — usunięty węzeł pojawi się ponownie przy następnym rysowaniu.",
        "Phòng thí nghiệm truy hồi BM25": "Laboratorium wyszukiwania BM25",
        "Câu hỏi — Enter để tìm": "Pytanie — Enter, aby wyszukać",
        "Đánh giá…": "Oceń…",
        "Đang dựng chỉ mục": "Trwa budowanie indeksu",
        "Không chunk nào khớp": "Żaden fragment nie pasuje",
        "kết quả trên": "najlepszych wyników",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: każde słowo liczy się TYLKO raz, niezależnie od liczby wystąpień",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 niskie: powtórzenie słowa prawie nie zwiększa oceny",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 w okolicy domyślnej 1,2: powtórzenie zwiększa ocenę, ale coraz mniej",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 wysokie: fragment powtarzający słowo wiele razy jest mocno nagradzany",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: długość jest pomijana, długie fragmenty nie są karane",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b niskie: długie fragmenty są karane tylko nieznacznie",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b w okolicy domyślnej 0,75: długie fragmenty są karane umiarkowanie",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: największa kara za długość, krótkie fragmenty są uprzywilejowane",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: laboratorium wyszukiwania…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Dokument niezapisany — indeks BM25 leży obok pliku korpusu, więc potrzebna jest ścieżka",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Ten plik nie jest JSONL — Retrieval Lab działa na korpusie fragmentów",
        "Không dựng được chỉ mục BM25 cho tệp này": "Nie udało się zbudować indeksu BM25 dla tego pliku",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Dokument niezapisany — do wygenerowania raportu potrzebna jest ścieżka korpusu",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Wybierz zestaw ewaluacyjny (CSV lub JSONL: pytanie + oczekiwany identyfikator fragmentu)",
        "Đánh giá truy hồi": "Ewaluacja wyszukiwania",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Zmień k1, b lub k powyżej i spójrz ponownie, aby porównać dwie konfiguracje; dodaj blok «compare», aby uruchomić dwa zestawy parametrów równolegle na tym samym zestawie ewaluacyjnym.",
        "Lỗi": "Błąd",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, średnio %.0f)",
        "Chế độ JSONL": "Tryb JSONL",
        "Bản ghi": "Rekord",
        "Chi tiết": "Szczegóły",
        "Bản ghi ở dòng": "Rekord w wierszu",
        "không phải JSON hợp lệ": "nie jest prawidłowym JSON-em",
        "bản ghi": "rekordów",
        "dòng trắng": "pustych wierszy",
        "không phải đối tượng": "nie jest obiektem",
        "bảng hiện": "wyświetlana tabela",
        "ĐÃ HUỶ giữa chừng": "ANULOWANO W POŁOWIE",
        "Không lọc": "Bez filtra",
        "bản ghi khớp bộ lọc": "rekordów pasujących do filtra",
        "Đưa con nháy tới một dòng để xem bản ghi": "Ustaw kursor na wierszu, aby zobaczyć rekord",
        "Không có bản ghi nào hỏng": "Brak uszkodzonych rekordów",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Jeszcze nie zbadano. Uruchom ponownie «JSONL: zbadaj fragmenty» po sprawdzeniu.",
        "trường văn bản": "pole tekstowe",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHEMAT (zgadnięty — zmienia się po wybraniu innego pola)",
        "văn bản": "tekst",
        "định danh": "identyfikator",
        "metadata lồng": "zagnieżdżone metadane",
        "TRƯỜNG": "POLE",
        "phủ": "pokrycie",
        "nhiều kiểu": "wiele typów",
        "ĐỘ DÀI — ký tự": "DŁUGOŚĆ — znaki",
        "ĐỘ DÀI — từ": "DŁUGOŚĆ — słowa",
        "ĐỘ DÀI — token ước lượng": "DŁUGOŚĆ — szacowane tokeny",
        "RỖNG VÀ TRÙNG": "PUSTE I POWTÓRZONE",
        "chunk rỗng": "pustych fragmentów",
        "dòng": "wierszy",
        "nhóm trùng chính xác": "grup dokładnych duplikatów",
        "dòng không đọc được, không vào thống kê": "wierszy nie do odczytania, poza statystyką",
        "PHƯƠNG PHÁP": "METODA",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«znaki» liczone są jako znaki Unicode (skalary), a nie widoczne grupy",
        "«từ» tách theo khoảng trắng ASCII": "«słowa» rozdzielane są spacjami ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«tokeny» liczone są dzielnikiem sylab — NIE tym z modelu",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«duplikat» oznacza duplikat DOKŁADNY; niemal-duplikaty są w bloku ```quality",
        "chunk": "fragmentów",
        "JSONL: kiểm và soi chunk…": "JSONL: sprawdź i zbadaj fragmenty…",
        "Ảnh": "Obraz",
        "PDF": "PDF",
        "Tài liệu Word": "Dokument Word",
        "Bảng tính Excel": "Arkusz Excel",
        "Bản trình chiếu PowerPoint": "Prezentacja PowerPoint",
        "File nén": "Archiwum",
        "Vừa khung": "Dopasuj do okna",
        "Chép ảnh": "Skopiuj obraz",
        "Xoay": "Obróć",
        "Không đọc được ảnh «%@»": "Nie można odczytać obrazu «%@»",
        "Đã chép ảnh vào clipboard": "Skopiowano obraz do schowka",
        "Bôi vàng": "Podświetl na żółto",
        "Gạch chân": "Podkreśl",
        "Ghi chú…": "Notatka…",
        "Bỏ chú thích": "Usuń adnotacje",
        "Lấy chữ ra tab mới": "Wyodrębnij tekst do nowej karty",
        "Lưu bản có chú thích…": "Zapisz wersję z adnotacjami…",
        "Tìm trong PDF": "Szukaj w PDF",
        "Thêm": "Dodaj",
        "Trang %d/%d": "Strona %d/%d",
        "Trang %d": "Strona %d",
        "Kết quả %d/%d": "Wynik %d/%d",
        "0 kết quả": "0 wyników",
        "Không đọc được PDF «%@»": "Nie można odczytać pliku PDF «%@»",
        "PDF này có mật khẩu — chưa mở được nội dung": "Ten PDF jest chroniony hasłem — treść jest niedostępna",
        "Không thấy «%@» trong tài liệu": "Nie znaleziono «%@» w dokumencie",
        "Đã bôi vàng": "Podświetlono",
        "Đã gạch chân": "Podkreślono",
        "Hãy bôi đen một đoạn chữ trước": "Najpierw zaznacz fragment tekstu",
        "Đã thêm ghi chú": "Dodano notatkę",
        "Trang này chưa có chú thích nào": "Ta strona nie ma żadnych adnotacji",
        "Đã bỏ %d chú thích trên trang này": "Usunięto %d {one=adnotację|few=adnotacje|many=adnotacji} z tej strony",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Ten PDF nie ma warstwy tekstowej — najpewniej jest to skan",
        "Không ghi được tệp": "Nie udało się zapisać pliku",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Zapisany plik NIE otwiera się poprawnie — nie używaj tej wersji",
        "Đã lưu %@ · %d trang": "Zapisano %@ · %d {one=strona|few=strony|many=stron}",
        "Tên": "Nazwa",
        "Kích thước": "Rozmiar",
        "Đã nén": "Skompresowany",
        "Tỉ lệ": "Stosunek",
        "Sửa lúc": "Zmieniono",
        "Mở mục đang chọn": "Otwórz zaznaczoną pozycję",
        "Bung ra thư mục…": "Rozpakuj do katalogu…",
        "Bung vào đây": "Rozpakuj tutaj",
        "%d mục": "%d {one=pozycja|few=pozycje|many=pozycji}",
        "giải nén ra %@": "rozpakowano do %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— wnętrze pliku Office to archiwum; oto jego części",
        "Đã bung %d mục": "Rozpakowano %d {one=pozycję|few=pozycje|many=pozycji}",
        "%d mục hỏng": "%d {one=pozycja uszkodzona|few=pozycje uszkodzone|many=pozycji uszkodzonych}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=pozycję ODRZUCONO|few=pozycje ODRZUCONO|many=pozycji ODRZUCONO}, bo ich ścieżki wychodzą poza katalog docelowy",
        "Không mở được mục này": "Nie można otworzyć tej pozycji",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Nie da się jeszcze zapisywać bezpośrednio do %@ — użyj «Zapisz jako…»",
        "Không có gì đổi": "Nic się nie zmieniło",
        "Đã ghi %d ô vào %@": "Zapisano %1$d {one=komórkę|few=komórki|many=komórek} do %2$@",
        "Đã ghi %d đoạn vào %@": "Zapisano %1$d {one=akapit|few=akapity|many=akapitów} do %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Nie udało się zapisać do pliku — oryginał pozostaje nietknięty",
        "dựng bài": "przygotowanie przypadku testowego",
        "Không ghi được settings.json": "Nie można zapisać settings.json",
        "Xoay trái": "Obróć w lewo",
        "Xoay phải": "Obróć w prawo",
        "Trang lên": "Przenieś stronę w górę",
        "Trang xuống": "Przenieś stronę w dół",
        "Xoá trang…": "Usuń strony…",
        "Xoá trang": "Usuń strony",
        "Trích trang…": "Wyodrębnij strony…",
        "Trích trang ra tệp mới": "Wyodrębnij strony do nowego pliku",
        "Gộp tệp PDF…": "Scal plik PDF…",
        "Tách tệp…": "Podziel plik…",
        "Tách tệp PDF": "Podziel plik PDF",
        "Xuất ảnh…": "Eksportuj obrazy…",
        "Xuất trang ra ảnh PNG": "Eksportuj strony jako obrazy PNG",
        "Hoàn tác trang": "Cofnij edycję strony",
        "Lưu bản đã sửa…": "Zapisz zmienioną kopię…",
        "Phát": "Odtwórz",
        "Tạm dừng": "Wstrzymaj",
        "Xem bình thường": "Widok normalny",
        "Chọn sheet": "Wybierz arkusz",
        "Mở sheet": "Otwórz arkusz",
        "Bỏ và đổi sheet": "Odrzuć i zmień arkusz",
        "Bảng tính có %d sheet.": "Skoroszyt ma %d arkuszy.",
        "Bảng tính này chỉ có một sheet: «%@»": "Ten skoroszyt ma tylko jeden arkusz: „%@”",
        "Bỏ phần chưa lưu của sheet này?": "Odrzucić niezapisane zmiany w tym arkuszu?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Zmiana arkusza zastępuje całą kartę. To, co nie zostało zapisane przez ⌘S, przepadnie.",
        "Chọn tệp PDF cần gộp vào": "Wybierz plik PDF do scalenia",
        "Chọn thư mục ghi ảnh": "Wybierz folder na obrazy",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Wybierz miejsce zapisu. Drugi plik zostanie zapisany obok tego.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Dokument ma %d stron. Podaj strony do usunięcia, np. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Dokument ma %d stron. Podaj strony do wyodrębnienia, np. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Dokument ma %d stron. Podaj strony do eksportu, np. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Dokument ma %d stron. Podaj część do oddzielenia, np. 1-5; reszta trafi do drugiego pliku.",
        "Đã xoay trang %d": "Obrócono stronę %d",
        "Đã xoá trang %@ · còn %d trang": "Usunięto strony %@ · pozostało %d stron",
        "Đã gộp %d trang từ «%@»": "Scalono %d stron z „%@”",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Podzielono na %@ (%d stron) i %@ (%d stron)",
        "Đã ghi %@ — %@ · %d trang": "Zapisano %@ — %@ · %d stron",
        "Đã xuất %d ảnh vào %@": "Wyeksportowano %d obrazów do %@",
        "Chỉ xuất được %d/%d ảnh": "Wyeksportowano tylko %d z %d obrazów",
        "Đã hoàn tác một thao tác trang": "Cofnięto jedną operację na stronie",
        "Không còn thao tác trang nào để hoàn tác": "Brak operacji na stronie do cofnięcia",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Nie można usunąć WSZYSTKICH stron — PDF musi mieć co najmniej jedną",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Ten zakres to cały dokument — nie ma czego oddzielać",
        "«%@» có mật khẩu — chưa gộp được": "„%@” jest chroniony hasłem — nie można scalić",
        "«%@» không có trang nào": "„%@” nie ma stron",
        "Đã ở trang đầu": "To już pierwsza strona",
        "Đã ở trang cuối": "To już ostatnia strona",
        "· đã sửa, chưa lưu": "· zmieniono, niezapisane",
        "Ảnh động · %d khung": "Obraz animowany · %d klatek",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Niezapisany dokument — brak pliku na dysku do podglądu binarnego",
        "Lệnh này chỉ dùng cho bảng tính Excel": "To polecenie działa tylko ze skoroszytami Excela",
        "Không đọc được danh sách sheet": "Nie udało się odczytać listy arkuszy",
        "Không có sheet «%@»": "Nie ma arkusza „%@”",
        "Không đọc được sheet «%@»": "Nie udało się odczytać arkusza „%@”",
        "Sheet «%@» · %d hàng": "Arkusz „%@” · %d wierszy",
        "phần còn lại": "reszta",
        "Lưu ý": "Uwaga",
        "Cẩn thận": "Uwaga!",
        "Xem thêm": "Zobacz też",
        "Chép": "Kopiuj",
        "Đã chép": "Skopiowano",
        "Chép đoạn mã mẫu": "Skopiuj przykładowy kod",
        "Tìm trong trợ giúp": "Szukaj w pomocy",
        "Lùi": "Wstecz",
        "Bắt đầu dùng": "Zaczynamy",
        "Không mở cửa sổ này khi khởi động nữa": "Nie pokazuj tego okna przy uruchamianiu",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Pomoc nie jest jeszcze przetłumaczona na ten język — pokazywana jest wersja wietnamska.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Przejdź do offsetu (np. 1F400 lub 0x1F400)",
        "Chép dòng đã chọn": "Kopiuj zaznaczone wiersze",
        "Đã chép %d dòng": "Skopiowano %d wierszy",
        "Không đọc được «%@»": "Nie udało się odczytać „%@”",
        "Tệp rỗng": "Pusty plik",
        "Không đọc được offset «%@»": "Nie udało się odczytać offsetu „%@”",
        "Offset 0x%@ vượt quá cỡ tệp": "Offset 0x%@ wykracza poza rozmiar pliku",
        "Mở bằng ứng dụng khác…": "Otwórz w innej aplikacji…",
        "%d kênh": "%d kanałów",
        "Không phát được «%@»": "Nie można odtworzyć „%@”",
        "Không phát được — %@": "Nie można odtworzyć — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS nie ma wbudowanego dekodera formatu %@ — to ograniczenie systemu, a nie uszkodzony plik.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Nadal możesz obejrzeć bajty w trybie binarnym lub otworzyć plik aplikacją z własnym dekoderem.",
        "Ký…": "Podpisz…",
        "Sửa chữ…": "Edytuj tekst…",
        "Sửa chữ": "Edytuj tekst",
        "Vẽ đè": "Narysuj na wierzchu",
        "Ô chưa điền": "Następne puste pole",
        "Xoá nội dung đã điền": "Wyczyść wypełnione pola",
        "Tệp này không có ô biểu mẫu nào": "Ten plik nie ma pól formularza",
        "Đã xoá nội dung của %d ô biểu mẫu": "Wyczyszczono %d pól formularza",
        "Mọi ô biểu mẫu đều đã có nội dung": "Wszystkie pola formularza są już wypełnione",
        "Còn %d ô chưa điền": "Pozostało %d pustych pól",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Formularz do wypełnienia: %d pól. Wpisuj bezpośrednio, potem „Zapisz zmienioną kopię…”",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Wybierz obraz podpisu (najlepiej z przezroczystym tłem)",
        "Không dựng được trang có chữ ký": "Nie udało się utworzyć podpisanej strony",
        "Đã chèn chữ ký vào trang %d": "Wstawiono podpis na stronie %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Najpierw zaznacz tekst do zmiany",
        "Vùng chọn quá nhỏ": "Zaznaczenie jest za małe",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Nowy tekst jest RYSOWANY NA WIERZCHU zaznaczenia czcionką systemową. Stary tekst jest zakryty, a nie usunięty — nadal da się go wydobyć, więc to nie jest redakcja.",
        "Không dựng được trang đã sửa": "Nie udało się utworzyć zmienionej strony",
        "Đã vẽ đè chữ mới lên trang %d": "Narysowano nowy tekst na stronie %d",
        "Đổi chế độ View / Code": "Przełącz Widok / Kod",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Brak jeszcze widoku drzewa dla JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Brak jeszcze widoku diagramu w karcie",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Brak jeszcze widoku konspektu dla PowerPointa",
        "Tệp này chỉ có một chế độ hiển thị": "Ten plik ma tylko jeden tryb wyświetlania",
        "%d nút": "%d węzłów",
        "Không dựng được cây: %@": "Nie udało się zbudować drzewa: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Dokument jest za duży na drzewo — użyj trybu Kod",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Nie udało się zbudować stron tego pliku \u{2014} użyj trybu Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Slajdy budowane są z tekstu; oryginalne obrazy i układ nie są jeszcze rysowane.",
        "Vừa ngang": "Dopasuj do szerokości",
        "Thu nhỏ trang": "Pomniejsz stronę",
        "Phóng to trang": "Powiększ stronę",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "Nie znaleziono „%@” w dokumencie",
        "Chỗ khớp %d/%d": "Dopasowanie %d z %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Na stronie nie zaznaczono tekstu.",
        "%d ký tự": "%d {one=znak|few=znaki|other=znaków}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Otwieraj pliki od razu w trybie View, jeśli go mają",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· ANULOWANO w połowie — tabela jest niepełna",
        "Chế độ hiển thị": "Tryb wyświetlania",
        "Đổi giữa View và Code (⌥⌘V)": "Przełącz między View a Code (⌥⌘V)",
        "Trang tài liệu": "Strony dokumentu",
        "Chữ đã dựng": "Złożony tekst",
        "Trang bảng tính": "Strony arkusza",
        "Sơ đồ": "Diagram",
        "Cây khoá–giá trị": "Drzewo klucz–wartość",
        "Bộ phát": "Odtwarzacz",
        "Danh sách mục": "Lista wpisów",
        "Báo cáo đã dựng": "Gotowy raport",
        "Tô theo mức": "Kolorowanie według poziomu",
        "Trang slide": "Strony slajdów",
        "Dàn ý": "Konspekt",
        "Lưu rồi dựng lại": "Zapisz i zbuduj ponownie",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Pokazuje kopię NA DYSKU — niezapisanych zmian tu nie ma.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "System nie zdołał zbudować podglądu dokumentu — użyj trybu Code.",
        "Lưu tệp trước khi xem trang.": "Zapisz plik, zanim obejrzysz jego strony.",
        "Đang ở chế độ Code": "Teraz w trybie Code",
        "Đang ở chế độ View": "Teraz w trybie View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Widzisz źródło — kliknij, aby przejść do trybu View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "Tryb View — kliknij, aby wrócić do źródła (⌥⌘V)",
        "Tín hiệu: %@": "Sygnał: %@",
        "Lý do: %@": "Powód: %@",
        "Chi tiết: %@": "Szczegół: %@",
        "Mở báo cáo": "Otwórz raport",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor zakończył się nagle o %@ — otwórz raport, aby go przeczytać; nic nie jest wysyłane.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligatury — wyłączone, każdy znak zostaje w swojej komórce",
        "Chế độ CSV": "Tryb CSV",
        "Dấu phân tách": "Separator",
        "Tự nhận diện": "Rozpoznaj automatycznie",
        "Dấu phân tách: %@": "Separator: %@",
        "Theo đuôi tệp": "Według rozszerzenia pliku",
        "%d dấu cách": "%d {one=spacja|few=spacje|other=spacji}",
        "Tài liệu đang sửa được": "Ten dokument można edytować",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Tylko do odczytu: plik jest śledzony — zatrzymaj śledzenie, aby edytować",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Tylko do odczytu: pliku na dysku nie można zapisać",
        "Đã mở khoá — tài liệu sửa được": "Odblokowano — dokument znów można edytować",
        "Nhân bản tệp": "Duplikuj plik",
        "Đổi tên tệp…": "Zmień nazwę pliku…",
        "Chuyển tệp tới…": "Przenieś plik do…",
        "XML: đánh giá XPath…": "XML: oblicz XPath…",
        "Đánh giá XPath": "Oblicz XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Na przykład: //zamowienie/pozycja[2]/@kod · //*[@rodzaj='A'] · count(//pozycja)",
        "Đánh giá": "Oblicz",
        "XPath không đọc được: %@": "Nie można odczytać tego XPath: %@",
        "XPath «%@» không khớp node nào": "XPath „%@” nie trafił w żaden węzeł",
        "XPath «%@» — %d node": "XPath „%@” — %d {one=węzeł|few=węzły|other=węzłów}",
        "XPath «%@»: %d node": "XPath „%@”: %d {one=węzeł|few=węzły|other=węzłów}",
        "Lưu tệp trước khi nhân bản.": "Zapisz plik, zanim go zduplikujesz.",
        "Không nhân bản được": "Nie udało się zduplikować",
        "Đã nhân bản thành %@": "Zduplikowano jako %@",
        "Lưu tệp trước khi đổi tên.": "Zapisz plik, zanim zmienisz jego nazwę.",
        "Đổi tên tệp": "Zmień nazwę pliku",
        "Tên hiện tại: %@": "Obecna nazwa: %@",
        "Đổi tên": "Zmień nazwę",
        "Tên tệp không hợp lệ": "Ta nazwa pliku jest nieprawidłowa",
        "Đã có tệp tên %@ ở đó": "Jest tam już plik o nazwie %@",
        "Lưu tệp trước khi chuyển.": "Zapisz plik, zanim go przeniesiesz.",
        "Chuyển tới": "Przenieś tutaj",
        "Thư mục đích đã có tệp tên %@": "Folder docelowy ma już plik o nazwie %@",
        "Không chuyển được tệp": "Nie udało się przenieść pliku",
        "Đã chuyển tới %@": "Przeniesiono do %@",
        "Bảng mã:": "Kodowanie:",
        "Xuống dòng:": "Końce wierszy:",
        "Riêng cho %@": "Tylko dla %@",
        "    %d — dùng TAB": "    %d — tabulatory",
        "    %d — dùng dấu cách": "    %d — spacje",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Usuń własną regułę, użyj ustawienia ogólnego",
        "%@: thụt lề %d %@": "%@: wcięcie %d %@",
        "TAB": "tabulatory",
        "dấu cách": "spacje",
        "Xuất": "Eksportuj",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Otwórz wyniki jako kartę tekstową — zapisz przez ⌘S",
        "Lượt tìm trước đó": "Wcześniejsze wyszukiwania",
        "«%@» — %d kết quả": "„%@” — %d {one=wynik|few=wyniki|other=wyników}",
        "Kết quả tìm «%@»": "Wyniki wyszukiwania „%@”",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtruj nazwy — np. *.csv;*.log (puste: każdy plik tekstowy)",
        "Thư mục %@ không có file văn bản nào": "Folder %@ nie ma plików tekstowych",
        "Không tệp nào trong %@ khớp «%@»": "Żaden plik w %@ nie pasuje do „%@”",
        "%d byte · %d dòng": "%d bajtów · %d {one=wiersz|few=wiersze|other=wierszy}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d bajtów · %d {one=wiersz|few=wiersze|other=wierszy} — za duży, aby liczyć znaki i słowa",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d bajtów · %d {one=znak|few=znaki|other=znaków} · %d {one=słowo|few=słowa|other=słów} · %d {one=wiersz|few=wiersze|other=wierszy}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Ten dokument ma %d {one=wiersz|few=wiersze|other=wierszy}, %d bajtów. Wpisz numer wiersza, „wiersz,kolumna” lub „@bajt”.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "Nie można odczytać „%@” — wpisz numer wiersza, „wiersz,kolumna” lub „@bajt”",
    ]
}
