import Foundation

/// Bảng dịch tiếng Hà Lan. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let nl: [String: String] = [
        "Bản đã lưu…": "Bewaarde versies…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Dit document is nooit bewaard — geen geschiedenis",
        "Chưa có bản đã lưu nào trước đó": "Geen eerdere bewaarde versies",
        "Không đọc được bản ấy": "Kan die versie niet lezen",
        "Khôi phục bản đã lưu": "Bewaarde versie terugzetten",
        "XML: kiểm theo DTD/XSD…": "XML: valideren met DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Deze Mac heeft geen libxml2, dus XSD-validatie is niet beschikbaar.",
        "Chọn lược đồ XSD để kiểm": "Kies een XSD-schema om mee te valideren",
        "Hợp lệ theo": "Geldig volgens",
        "Plugin chạy xong, không đổi gì": "De plug-in is geëindigd zonder iets te wijzigen",
        "Chưa cài plugin native nào": "Geen native plug-ins geïnstalleerd",
        "Gỡ plugin này": "Deze plug-in verwijderen",
        "Gỡ plugin này?": "Deze plug-in verwijderen?",
        "Gỡ": "Verwijderen",
        "Cài plugin native…": "Native plug-in installeren…",
        "Mở thư mục plugin": "Plug-inmap openen",
        "Chọn file .dylib của plugin native": "Kies het .dylib-bestand van de plug-in",
        "Đã cài:": "Geïnstalleerd:",
        "Đã gỡ:": "Verwijderd:",
        "Plugin native…": "Native plug-ins…",
        "Chỉ nhận file .dylib.": "Alleen .dylib-bestanden worden geaccepteerd.",
        "Đã có một plugin trùng tên:": "Er is al een plug-in met dezelfde naam geïnstalleerd:",
        "Không chép được plugin:": "Kan de plug-in niet kopiëren:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Native plug-ins bestaan alleen in de directe download, niet in de App Store-versie.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Het hulpproces voor plug-ins is niet gevonden.",
        "Không khởi động được tiến trình phụ:": "Kan het hulpproces niet starten:",
        "Tiến trình plugin đã dừng giữa chừng.": "Het plug-inproces is halverwege gestopt.",
        "Plugin không trả lời kịp — đã dừng nó.": "De plug-in reageerde niet op tijd — hij is gestopt.",
        "Plugin trả lời sai giao thức:": "De plug-in stuurde een onjuist opgemaakt bericht:",
        "Plugin báo lỗi:": "De plug-in meldde een fout:",
        "Về GEditor": "Over GEditor",
        "Cài đặt…": "Instellingen…",
        "Thoát GEditor": "GEditor stoppen",
        "File": "Archief",
        "Tab mới": "Nieuw tabblad",
        "Đóng tab": "Tabblad sluiten",
        "Tab kế": "Volgend tabblad",
        "Tab trước": "Vorig tabblad",
        "Tài liệu mới": "Nieuw document",
        "Mở…": "Openen…",
        "Mở thư mục làm Workspace…": "Map als werkruimte openen…",
        "Mở gần đây": "Recent geopend",
        "Lưu": "Bewaren",
        "Lưu thành…": "Bewaar als…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Spaties aan het regeleinde verwijderen bij het bewaren",
        "Theo dõi file (tail -f)": "Bestand volgen (tail -f)",
        "In…": "Print…",
        "Mở lại tab vừa đóng": "Gesloten tabblad opnieuw openen",
        "Chưa có file nào": "Geen bestanden",
        "Xoá danh sách": "Lijst wissen",
        "Edit": "Wijzig",
        "Hoàn tác": "Herstel",
        "Làm lại": "Opnieuw",
        "Cắt": "Knippen",
        "Sao chép": "Kopiëren",
        "Dán": "Plakken",
        "Lịch sử clipboard…": "Klembordgeschiedenis…",
        "Column Editor…": "Kolomeditor…",
        "Chọn lần kế tiếp": "Volgende overeenkomst selecteren",
        "Chọn tất cả": "Alles selecteren",
        "Nhân đôi dòng": "Regel dupliceren",
        "Xóa dòng": "Regel verwijderen",
        "Comment dòng": "Regel uitcommentariëren",
        "Chưa chép gì trong phiên này": "In deze sessie is er niets gekopieerd",
        "Xoá lịch sử": "Geschiedenis wissen",
        "Search": "Zoek",
        "Tìm…": "Zoeken…",
        "Tìm và thay…": "Zoeken en vervangen…",
        "Tìm trong thư mục…": "Zoeken in een map…",
        "Thay trong thư mục…": "Vervangen in een map…",
        "Kết quả kế": "Volgend resultaat",
        "Kết quả trước": "Vorig resultaat",
        "Đi tới dòng…": "Ga naar regel…",
        "Nhảy tới ngoặc khớp": "Naar het bijbehorende haakje",
        "Đánh dấu mọi dòng khớp…": "Alle overeenkomende regels markeren…",
        "Đảo dấu": "Markeringen omkeren",
        "Bỏ mọi dấu": "Alle markeringen wissen",
        "Chép dòng đã đánh dấu": "Gemarkeerde regels kopiëren",
        "Xóa dòng đã đánh dấu": "Gemarkeerde regels verwijderen",
        "Chỉ giữ dòng đã đánh dấu": "Alleen gemarkeerde regels behouden",
        "Lines": "Regels",
        "Sắp xếp A→Z": "Sorteren A→Z",
        "Sắp xếp Z→A": "Sorteren Z→A",
        "Sắp xếp tự nhiên": "Natuurlijk sorteren",
        "Khử trùng lặp": "Dubbele regels verwijderen",
        "Đảo thứ tự dòng": "Regelvolgorde omkeren",
        "Dời dòng lên": "Regel omhoog",
        "Dời dòng xuống": "Regel omlaag",
        "Ghép dòng": "Regels samenvoegen",
        "Tách dòng theo độ dài…": "Regels splitsen op lengte…",
        "Tách dòng theo ký tự…": "Regels splitsen op teken…",
        "Xóa dòng rỗng": "Lege regels verwijderen",
        "Nén dòng trống liên tiếp": "Opeenvolgende lege regels samenvoegen",
        "Cắt khoảng trắng cuối dòng": "Spaties aan het regeleinde verwijderen",
        "Tab → Space": "Tab → spatie",
        "Space → Tab": "Spatie → Tab",
        "HOA": "HOOFDLETTERS",
        "thường": "kleine letters",
        "Chữ Hoa Đầu Từ": "Elk Woord Met Hoofdletter",
        "Chữ hoa đầu câu": "Hoofdletter aan het begin van de zin",
        "Đảo hoa/thường": "hOOFDLETTERS oMKEREN",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: blad kiezen…",
        "Xem dạng bảng / văn bản": "Tabel- / tekstweergave wisselen",
        "Xóa cột…": "Kolom verwijderen…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Gegevens valideren (aantal kolommen · typen)",
        "Bàn làm sạch dữ liệu…": "Werkbank voor gegevensopschoning…",
        "Chạy công thức làm sạch…": "Opschoonrecept uitvoeren…",
        "Chuyển đổi…": "Converteren…",
        "Đổi dấu phân tách…": "Scheidingsteken wijzigen…",
        "Xuất sang JSON…": "Exporteren naar JSON…",
        "Format": "Opmaak",
        "Bảng mã…": "Codering…",
        "Xuống dòng…": "Regeleinden…",
        "Chuẩn hóa Unicode…": "Unicode normaliseren…",
        "JSON: định dạng lại": "JSON: opmaken",
        "JSON: thu gọn một dòng": "JSON: comprimeren tot één regel",
        "JSON: sắp xếp khóa": "JSON: sleutels sorteren",
        "JSON: truy vấn JSONPath…": "JSON: JSONPath-zoekopdracht…",
        "CSV: truy vấn SQL…": "CSV: SQL-zoekopdracht…",
        "Truy vấn SQL": "SQL-zoekopdracht",
        "Đang chạy…": "Bezig…",
        "Xuất ra tab mới": "Exporteren naar een nieuw tabblad",
        "Tài liệu rỗng — không có bảng để truy vấn": "Leeg document — geen tabel om te bevragen",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Geen CSV-tabel — de eerste regel heeft maar één kolom",
        "Không đọc được câu truy vấn": "Kan de zoekopdracht niet lezen",
        "Không kiểm được câu truy vấn": "Kan de zoekopdracht niet controleren",
        "Vàng (mặc định)": "Geel (standaard)",
        "Xanh dương": "Blauw",
        "Xanh lá": "Groen",
        "Vàng đất": "Oker",
        "Tím": "Paars",
        "Hồng": "Roze",
        "Xanh ngọc": "Turkoois",
        "Cam": "Oranje",
        "Xám lam": "Leisteen",
        "Văn bản": "Tekst",
        "Dãy số": "Getallenreeks",
        "Dãy ngày": "Datumreeks",
        "Chữ HOA (hex)": "HOOFDLETTERS (hexadecimaal)",
        "Bắt đầu": "Begin",
        "Bước": "Stap",
        "Đệm 0 tới": "Aanvullen met nullen tot",
        "Hệ": "Grondtal",
        "Ngày đầu": "Eerste datum",
        "Định dạng": "Opmaak",
        "Chèn": "Invoegen",
        "Huỷ": "Annuleer",
        "Chuyển đổi định dạng": "Opmaak converteren",
        "Xem trước 5 hàng đầu": "Voorvertoning van de eerste 5 rijen",
        "Tạo tab mới": "Openen in een nieuw tabblad",
        "Lưu ra file…": "Bewaren in een bestand…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Het resultaat opent in een nieuw, niet-bewaard tabblad. Het oorspronkelijke document blijft ongemoeid.",
        "Chạy trên tài liệu này": "Uitvoeren op dit document",
        "Chạy trên thư mục…": "Uitvoeren op een map…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Het hele recept is ÉÉN herstelstap. Het bestand op schijf blijft ongemoeid tot je bewaart.",
        "tắt": "uit",
        "không thấy cột": "kolom niet gevonden",
        "sẵn sàng": "gereed",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "hij blijft een processorkern bezetten tot de app wordt gestopt.",
        "Script không trả về gì": "Het script gaf niets terug",
        "Không dựng được máy JavaScript": "Kan de JavaScript-engine niet aanmaken",
        "Lỗi JavaScript không rõ": "Onbekende JavaScript-fout",
        "Bảng": "Tabel",
        "Áp sắp xếp vào file": "Sortering op het bestand toepassen",
        "Chuyển đổi ▾": "Converteren ▾",
        "Xuất dòng khớp": "Overeenkomende rijen exporteren",
        "Ẩn cột này": "Deze kolom verbergen",
        "Đổi tên tiêu đề…": "Kop hernoemen…",
        "Chèn cột trống bên trái": "Lege kolom links invoegen",
        "Chèn cột trống bên phải": "Lege kolom rechts invoegen",
        "Xóa cột này khỏi file…": "Deze kolom uit het bestand verwijderen…",
        "Phải còn ít nhất một cột đang hiện": "Er moet ten minste één kolom zichtbaar blijven",
        "Đang sắp xếp…": "Bezig met sorteren…",
        "Trở về thứ tự trong file": "Terug naar de volgorde in het bestand",
        "trăm hàng đầu": "eerste honderd rijen",
        "chọn cột": "kolommen kiezen",
        "đặt tên cột kết quả": "een resultaatkolom benoemen",
        "lọc theo chữ": "filteren op tekst",
        "ô rỗng": "lege cellen",
        "ghép điều kiện": "voorwaarden combineren",
        "đếm hàng": "rijen tellen",
        "gộp nhóm": "groeperen en samenvatten",
        "nhỏ nhất, lớn nhất": "minimum, maximum",
        "sắp xếp và cắt": "sorteren en beperken",
        "tên cột có dấu cách": "kolomnaam met spaties",
        "Truy vấn bị dừng giữa chừng": "De zoekopdracht is onderbroken",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Niet ondersteund: JOIN · subquery · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · vensterfuncties",
        "XML: định dạng lại": "XML: opmaken",
        "XML: thu gọn một dòng": "XML: comprimeren tot één regel",
        "XML: kiểm cú pháp": "XML: syntaxis controleren",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: dubbele sleutels en inspringing controleren",
        "View": "Weergave",
        "Ẩn/hiện sidebar (Function List)": "Navigatiekolom (functielijst) tonen/verbergen",
        "Ẩn/hiện bản đồ tài liệu": "Documentkaart tonen/verbergen",
        "Gấp / mở khối tại con nháy": "Blok bij de cursor invouwen / uitvouwen",
        "Gấp tất cả": "Alles invouwen",
        "Bỏ gấp tất cả": "Alles uitvouwen",
        "Gấp theo cấp": "Invouwen per niveau",
        "Cấp %d": "Niveau %d",
        "Đã gấp %d khối ở cấp %d": "%d {one=blok ingevouwen|other=blokken ingevouwen} op niveau %d",
        "Tài liệu này chỉ sâu %d cấp": "Dit document is maar %d {one=niveau|other=niveaus} diep",
        "mermaid: không đọc được bản kê": "mermaid: manifest onleesbaar",
        "Kiểm tra bản cập nhật…": "Controleer op updates…",
        "Kiểm tra bản cập nhật": "Controleer op updates",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store-versies werken bij via de Mac App Store, niet via GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Deze build heeft geen ondertekeningssleutel voor updates en kan er dus niet naar zoeken.",
        "Phóng to chữ": "Tekst vergroten",
        "Thu nhỏ chữ": "Tekst verkleinen",
        "Cỡ chữ gốc": "Werkelijke grootte",
        "Chia đôi theo chiều dọc": "Verticaal splitsen",
        "Chia đôi theo chiều ngang": "Horizontaal splitsen",
        "Bỏ chia đôi": "Splitsing sluiten",
        "Mở tab này ở nửa kia": "Dit tabblad in het andere deelvenster openen",
        "Nhảy sang nửa kia": "Naar het andere deelvenster",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Regelterugloop (uit / venster / kolom)",
        "Ngắt dòng tại cột…": "Terugloop bij kolom…",
        "Đánh dấu dòng này": "Deze regel markeren",
        "Dấu kế tiếp": "Volgende markering",
        "Dấu trước đó": "Vorige markering",
        "Màu đánh dấu…": "Kleur van markeringen…",
        "Hiện tất cả ký tự ẩn": "Alle onzichtbare tekens tonen",
        "  Khoảng trắng": "  Spaties",
        "  Tab": "  Tabs",
        "  Xuống dòng": "  Regeleinden",
        "  NBSP · zero-width · điều khiển": "  NBSP · nulbreedte · stuurtekens",
        "Xem nhị phân": "Binaire weergave",
        "Chế độ CSV (tô màu theo cột)": "CSV-modus (kolommen in kleur)",
        "Macro": "Macro",
        "Bắt đầu / dừng ghi": "Opname starten / stoppen",
        "Phát lại": "Afspelen",
        "Phát nhiều lần…": "Meerdere keren afspelen…",
        "Phát đến cuối tài liệu": "Afspelen tot het einde van het document",
        "Chạy trên mọi tab": "Uitvoeren op alle tabbladen",
        "Hủy macro đang chạy": "Lopende macro annuleren",
        "Lưu macro…": "Macro bewaren…",
        "Macro đã lưu…": "Bewaarde macro's…",
        "Help": "Help",
        "Trợ giúp GEditor": "GEditor Help",
        "Giới thiệu tính năng": "Functieoverzicht",
        "Di cư từ Notepad++": "Overstappen vanaf Notepad++",
        "Tìm": "Zoeken",
        "Thay bằng": "Vervangen door",
        "Kế": "Volgende",
        "Trước": "Vorige",
        "Đếm": "Tellen",
        "Đóng": "Sluiten",
        "Kiểm theo JSON Schema…": "Valideren met een JSON-schema…",
        "Chọn tệp JSON Schema": "Kies een JSON-schemabestand",
        "Không thấy lỗi nào theo schema này.": "Geen problemen gevonden volgens dit schema.",
        "JSON Schema": "JSON-schema",
        "Kiểm cú pháp đồ thị": "Grafieksyntaxis controleren",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Grafiekindeling niet herkend — er is een extensie .dot, .gv, .cypher, .ttl of .graphml nodig.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Geen %@-syntaxisfouten gevonden (deze controle is niet uitputtend).",
        "Cú pháp %@": "%@-syntaxis",
        "không phải một đối tượng JSON": "is geen JSON-object",
        "Khai phá văn bản (n-gram, TF-IDF)": "Tekstmining (n-grammen, TF-IDF)",
        "Tài liệu rỗng.": "Het document is leeg.",
        "Không rút được từ khoá nào.": "Er kon geen enkel trefwoord worden gehaald.",
        "Từ khoá": "Trefwoorden",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=trefwoord|other=trefwoorden} · %d {one=token|other=tokens} · %d {one=document|other=documenten}",
        "Tô lên tài liệu": "Markeren in het document",
        "Đánh dấu entity từ danh sách…": "Entiteiten uit een lijst markeren…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Kies een entiteitenlijst (CSV of JSON)",
        "Không đọc được danh sách entity.": "Kan de entiteitenlijst niet lezen.",
        "Danh sách entity rỗng.": "De entiteitenlijst is leeg.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Geen entiteiten in het document gevonden (%d geladen).",
        "%d lần xuất hiện · %@": "%d {one=keer|other=keer} gevonden · %@",
        "Chuyển đổi tri thức…": "Kennis converteren…",
        "Chuyển đổi: %@ → %@": "Conversie: %@ → %@",
        "Không chuyển đổi được.": "Kan niet converteren.",
        "Xem trước cắt chunk…": "Voorvertoning van het opdelen…",
        "Cỡ cố định 800B, chồng 100B": "Vaste grootte 800 B, overlap 100 B",
        "Theo câu (≤ 800B)": "Per zin (≤ 800 B)",
        "Theo heading Markdown": "Per Markdown-kop",
        "Tài liệu rỗng — không có chunk nào.": "Leeg document — geen fragmenten.",
        "%d chunk · trung bình %d B · %@": "%d {one=fragment|other=fragmenten} · gemiddeld %d B · %@",
        "Xuất JSONL": "JSONL exporteren",
        "Chunk JSONL": "Fragment-JSONL",
        "Mở triple/edge dạng bảng": "Triples/randen als tabel openen",
        "Bảng triple": "Tripletabel",
        "Tài liệu này không có dòng triple nào.": "Dit document bevat geen enkele tripleregel.",
        "Không đọc được triple nào — dòng %d: %@": "Er kon geen enkele triple worden gelezen — regel %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%1$d {one=triple|other=triples} gelezen · %2$d {one=onjuiste regel|other=onjuiste regels} overgeslagen (de eerste: regel %3$d)",
        "Trùng lặp mờ theo cột…": "Vage duplicaten per kolom…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Vage duplicaten — kolom «%1$@»: %2$d {one=kandidaatgroep|other=kandidaatgroepen}",
        "Gộp": "Samenvoegen",
        "Giống": "Overeenkomst",
        "Các giá trị trong cụm": "Waarden in de groep",
        "Gộp về": "Samenvoegen tot",
        "Gộp các cụm đã chọn": "Geselecteerde groepen samenvoegen",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Geen enkele groep geselecteerd — op Samenvoegen drukken verandert NIETS. De app voegt nooit uit zichzelf samen.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=groep|other=groepen} geselecteerd · %d {one=rij verandert|other=rijen veranderen} · ÉÉN herstelstap",
        "Không quét được cột này.": "Kan deze kolom niet doorzoeken.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Kolom «%@» heeft geen groepen met vage duplicaten.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Geen enkele groep samengevoegd — het document is onveranderd.",
        "Khử trùng lặp mờ · cột %@": "Vage ontdubbeling · kolom %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=groep|other=groepen} samengevoegd · %d {one=cel|other=cellen} gewijzigd",
        "Báo cáo làm sạch": "Opschoonrapport",
        "# Báo cáo làm sạch — %@\n\n": "# Opschoonrapport — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Toegepast (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Er is geen enkele stap toegepast._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Gegevensprofiel\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d {one=kolom|other=kolommen} · %2$d {one=rij|other=rijen} · in %3$.1f s doorzocht_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Kolom | Type | Null | Uniek | Min | Max | Gemiddelde |\n",
        "\n### Giá trị bất thường\n\n": "\n### Uitschieters\n\n",
        "hàng %d: %@": "rij %d: %@",
        "- cột «%@» — %d ô: %@\n": "- kolom «%1$@» — %2$d {one=cel|other=cellen}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Resterend (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Er zijn geen bevindingen meer._\n",
        "- cột «%@»: %@\n": "- kolom «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Spaties verwijderen bij het bewaren",
        "Chuẩn hóa xuống dòng": "Regeleinden normaliseren",
        "trước đó": "vorige",
        "Không mở lại được thư mục «%@» của phiên trước": "Kan de map «%@» van de vorige sessie niet opnieuw openen",
        " (và %d file khác)": " (en nog %d {one=bestand|other=bestanden})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "Kan %d {one=tabblad|other=tabbladen} niet opnieuw openen: %@%@ — de bestanden staan niet meer op hun plek.",
        "Không đọc được nội dung từ ống dẫn": "Kan de invoer uit de pipe niet lezen",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Spaties aan het regeleinde worden bij elke keer bewaren verwijderd",
        "Không cắt khoảng trắng khi lưu nữa": "Spaties worden niet meer verwijderd bij het bewaren",
        "Chưa đặt tên.txt": "Naamloos.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Bij het converteren van de codering gaan tekens verloren",
        "Vẫn lưu": "Toch bewaren",
        "Tài liệu có thay đổi chưa lưu": "Het document heeft niet-bewaarde wijzigingen",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Sluiten zonder bewaren gooit ze weg.",
        "Bỏ thay đổi": "Wijzigingen weggooien",
        "Đi tới dòng": "Ga naar regel",
        "Tài liệu có %d dòng.": "Het document heeft %d {one=regel|other=regels}.",
        "Số dòng": "Regelnummer",
        "Đi tới": "Ga",
        "Diễn giải lại theo…": "Opnieuw interpreteren als…",
        "Chuyển đổi sang…": "Converteren naar…",
        "Không diễn giải lại được": "Kan niet opnieuw interpreteren",
        "Bảng mã %@ không chứa hết ký tự": "%@ kan niet alle tekens weergeven",
        "Vẫn chọn": "Toch kiezen",
        "Cột %d": "Kolom %d",
        "Cột %d: %@": "Kolom %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Verborgen kolommen: %@ (%d) — herstel ze via het contextmenu op de koprij",
        "Hiện lại: %@": "Weer tonen: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Kolom %@ verborgen — hij staat nog ongeschonden in het bestand",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Gesorteerd op %@ %@ · alleen weergave",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Gesorteerd: %@ %@ (alleen weergave)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ rijen komen overeen — nog aan het zoeken…",
        "%d / %d dòng khớp": "%d / %d {one=rij komt|other=rijen komen} overeen",
        "Không tìm thấy lỗi trong %d hàng": "Geen problemen gevonden in %d {one=rij|other=rijen}",
        "%d hàng lệch số cột": "%d {one=rij|other=rijen} met een onjuist aantal kolommen",
        "%d ô sai kiểu dữ liệu": "%d {one=cel|other=cellen} met een onjuist gegevenstype",
        " (đã dừng ở %d lỗi đầu)": " (gestopt bij de eerste %d {one=probleem|other=problemen})",
        "   —   kiểu nhận ra: ": "   —   herkende typen: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Rij %1$d, kolom %2$@: «%3$@» is geen %4$@",
        "Column Editor — %d dòng": "Kolomeditor — %d {one=regel|other=regels}",
        "Phát hiện": "Bevindingen",
        "Hồ sơ dữ liệu": "Gegevensprofiel",
        "Hồ sơ dữ liệu — đang quét…": "Gegevensprofiel — bezig met doorzoeken…",
        "Lưu công thức…": "Recept bewaren…",
        "Xuất báo cáo": "Rapport exporteren",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Geen enkele groep toegepast · elke groep is één herstelstap",
        "quá nhiều giá trị": "te veel waarden",
        "hay gặp: ": "meest voorkomend: ",
        "Giá trị điền vào ô thiếu": "Waarde om lege cellen mee te vullen",
        "Áp dụng": "Toepassen",
        "Không dựng được bản xem trước": "Kan geen voorvertoning opbouwen",
        "· giữ nguyên, không đọc được ·": "· ongewijzigd gelaten, onleesbaar ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Kolom omzetten naar ISO 8601 (JJJJ-MM-DD)",
        "Quy ước số cho cả cột": "Getalnotatie voor de hele kolom",
        "Làm gì với ô thiếu": "Wat te doen met lege cellen",
        "Chuẩn hóa về ISO 8601": "Normaliseren naar ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Dubbelzinnige cellen als DAG eerst lezen (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Dubbelzinnige cellen als MAAND eerst lezen (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Dubbelzinnige cellen overslaan, alleen de zekere corrigeren",
        "Về Việt/Âu (1.234,56)": "Naar Vietnamees/Europees (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Naar Angelsaksisch (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Naar Angelsaksisch, zonder duizendtalscheiding (1234.56)",
        "Điền một giá trị mặc định…": "Vullen met een standaardwaarde…",
        "Điền xuôi — lấy giá trị phía trên": "Naar beneden vullen — de waarde erboven overnemen",
        "Điền ngược — lấy giá trị phía dưới": "Naar boven vullen — de waarde eronder overnemen",
        "Xóa hàng có ô thiếu ở cột này": "Rijen met een lege cel in deze kolom verwijderen",
        "Cắt khoảng trắng hai đầu": "Spaties aan beide uiteinden verwijderen",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Aan beide uiteinden verwijderen en spaties binnenin samenvoegen",
        "Pivot…": "Draaitabel…",
        "Nguồn…": "Bronnen…",
        "Pivot — gộp theo cột": "Draaitabel — groeperen op kolom",
        "Hàng (gộp nhóm)": "Rijen (groepering)",
        "Giá trị": "Waarden",
        "+ Hàng": "+ Rij",
        "+ Giá trị": "+ Waarde",
        "Xoá hết": "Alles wissen",
        "Đưa vào ô truy vấn": "In het zoekvak zetten",
        "Chọn cột để dựng câu truy vấn.": "Kies kolommen om de zoekopdracht op te bouwen.",
        "Không đọc được tên cột của bảng này.": "Kan de kolomnamen van deze tabel niet lezen.",
        "Nguồn dữ liệu của truy vấn": "Gegevensbronnen van de zoekopdracht",
        "«%@» — tài liệu đang mở": "«%@» — het geopende document",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ het bestand is gewijzigd sinds het werd geregistreerd",
        "Thêm file…": "Bestand toevoegen…",
        "Bỏ hết": "Alles verwijderen",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Kan geen tabelnaam afleiden uit «%@» — hernoem het bestand.",
        "Tổng": "Som",
        "Trung bình": "Gemiddelde",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Max",
        "Đếm khác nhau": "Aantal unieke waarden",
        "Biểu đồ": "Grafiek",
        "Xuất PNG": "PNG exporteren",
        "Xuất SVG": "SVG exporteren",
        "Bảng này không có cột số nào để vẽ.": "Deze tabel heeft geen numerieke kolom om weer te geven.",
        "Không dựng được ảnh PNG.": "Kan de PNG-afbeelding niet opbouwen.",
        "Kết quả truy vấn": "Resultaat van de zoekopdracht",
        "Đã lưu %@": "%@ bewaard",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "%1$@-grafiek van «%2$@» — %3$d {one=punt|other=punten}, waarden van %4$@ tot %5$@",
        "Cột": "Staaf",
        "Đường": "Lijn",
        "Phân bố": "Histogram",
        "Phân tán": "Spreiding",
        "Hộp": "Boxplot",
        "CSV: chất lượng dữ liệu…": "CSV: gegevenskwaliteit…",
        "Chất lượng dữ liệu": "Gegevenskwaliteit",
        "Xuất vi phạm ra tab mới": "Overtredingen naar een nieuw tabblad exporteren",
        "Mức": "Niveau",
        "Luật": "Regel",
        "Vi phạm": "Overtredingen",
        "Tỷ lệ": "Percentage",
        "đạt": "geslaagd",
        "lỗi": "fout",
        "cảnh báo": "waarschuwing",
        "hỏng": "kapot",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=overtredende regel|other=overtredende regels} gemarkeerd",
        "Xu hướng": "Verloop",
        "Lúc chấm": "Beoordeeld op",
        "Số hàng": "Rijen",
        "Lệch": "Verschil",
        "Luật trượt": "Niet-geslaagde regels",
        "Điểm chất lượng": "Kwaliteitsscore",
        "Điểm theo thời gian": "Score in de tijd",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Nog geen geschiedenis — elke beoordeling voegt ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "één regel toe aan het bestand «.history.jsonl» naast de regels.",
        "%d mốc trong lịch sử": "%d {one=punt|other=punten} in de geschiedenis",
        " · %d dòng KHÔNG đọc được": " · %d {one=regel ONLEESBAAR|other=regels ONLEESBAAR}",
        " · chọn hai dòng để so": " · selecteer twee rijen om te vergelijken",
        "điểm %+.1f": "score %+.1f",
        "không chiều nào tụt": "geen enkele dimensie is gedaald",
        "tụt: ": "gedaald: ",
        "%d luật mới trượt: %@": "%d {one=regel die nu niet meer slaagt|other=regels die nu niet meer slagen}: %@",
        "số hàng %+d": "rijen %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (en nog %d {one=waarschuwing|other=waarschuwingen} op het tabblad Verloop)",
        "Không sửa tự động được: ": "Geen automatische correctie: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Opent het bijbehorende gereedschap in de opschoonwerkbank en beoordeelt daarna meteen opnieuw.",
        "Xử lý giá trị thiếu…": "Ontbrekende waarden afhandelen…",
        "Chuẩn hóa ngày…": "Datums normaliseren…",
        "Khử trùng lặp…": "Duplicaten verwijderen…",
        "Thay thế…": "Vervangen…",
        "Xem các dòng sai": "De foutieve rijen tonen",
        "Không tìm thấy cột «%@» trong bảng này.": "Kolom «%@» staat niet in deze tabel.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplicaten verwijderd — «%@» is nu uniek. Score: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplicaten verwijderd, maar «%1$@» heeft nog %2$d {one=dubbele rij|other=dubbele rijen} (eerder: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "die rijen delen de SLEUTEL maar niet de hele regel, dus je moet kijken en kiezen ",
        "giữ hàng nào.": "welke je houdt.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Kan geen enkele waarde lezen die deze regel overtreedt.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {one=onjuiste waarde|other=onjuiste waarden} in kolom «%2$@» — vul Vervangen in en klik op Voorvertoning",
        "Đã chấm lại: %.0f/100": "Opnieuw beoordeeld: %.0f/100",
        "Xem trước báo cáo": "Voorvertoning van het rapport",
        "Tham số…": "Parameters…",
        "Xuất HTML…": "HTML exporteren…",
        "In / PDF…": "Print / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=blok|other=blokken} uitgevoerd · %d {one=blok|other=blokken} MISLUKT",
        "%d khối chạy được": "%d {one=blok|other=blokken} uitgevoerd",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · VEROUDERDE GEGEVENS — het bronbestand is gewijzigd; bouw opnieuw op",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "De rapportvoorvertoning heeft een .%@-document nodig",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Geen gegevensbron gevonden — declareer «source: bestand.csv» in de frontmatter.",
        "Không dựng được báo cáo.": "Kan het rapport niet opbouwen.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Dit rapport declareert geen enkele parameter in de frontmatter.",
        "Tham số báo cáo": "Rapportparameters",
        "Dựng lại": "Opnieuw opbouwen",
        "Đã xuất %@": "%@ geëxporteerd",
        "Báo cáo: xem trước": "Rapport: voorvertoning",
        "Báo cáo: sinh loạt…": "Rapport: in batch genereren…",
        "không phải tài liệu .greport.md": "is geen .greport.md-document",
        "không phân tích được báo cáo": "kan het rapport niet ontleden",
        "không tìm được dữ liệu nguồn": "kan de brongegevens niet vinden",
        "không đọc được danh sách tham số": "kan de parameterlijst niet lezen",
        "Sinh loạt cần tài liệu đuôi .%@": "Batchgeneratie heeft een .%@-document nodig",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Kies een parameterlijst (CSV of JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Kies een map voor %d {one=rapport|other=rapporten}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "ontbrekende parameters ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "wijst naar het bronbestand zelf — overschrijven geweigerd",
        "%d khối HỎNG": "%d {one=blok|other=blokken} MISLUKT",
        "Sinh loạt xong: %d tệp · %d hỏng": "Batch klaar: %d {one=bestand|other=bestanden} · %d mislukt",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=parameterset kon|other=parametersets konden} niet worden opgebouwd — zie de samenvatting",
        "Sơ đồ Mermaid: xem trước": "Mermaid-diagram: voorvertoning",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid-diagram: sjabloon invoegen…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid-diagram: opnieuw opmaken",
        "Nền trong suốt": "Doorzichtige achtergrond",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Deze Mac kan het diagram niet omzetten naar PNG — macOS 13 is vereist. SVG exporteren werkt nog wel.",
        "Lưu PNG %@…": "PNG %@ bewaren…",
        "Lưu SVG…": "SVG bewaren…",
        "Chép ảnh vào clipboard": "Afbeelding naar het klembord kopiëren",
        "Màu thương hiệu…": "Merkkleuren…",
        "Màu thương hiệu cho sơ đồ": "Merkkleuren voor diagrammen",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Elk veld is een kleur als #rrggbb. Bewaard in «themes/mermaid-brand.json» — te kopiëren naar een andere Mac.",
        "Màu chính": "Hoofdkleur",
        "Chữ trên nút": "Tekst op knooppunten",
        "Viền": "Rand",
        "Đường nối": "Verbindingen",
        "Nền khi xuất ảnh": "Achtergrond bij het exporteren",
        "Lưu và chèn %%{init}%% vào tài liệu": "Bewaren en %%{init}%% in het document invoegen",
        "Đã lưu màu thương hiệu": "Merkkleuren bewaard",
        "Đã chép ảnh sơ đồ vào clipboard": "Diagramafbeelding naar het klembord gekopieerd",
        "Đã lưu %@ — %@": "%@ bewaard — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Dit diagram heeft al een %%{init}%%-instructie — die van jou blijft ongemoeid.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% ingevoegd — het diagram draagt nu zijn eigen kleuren",
        "Chèn màu thương hiệu vào sơ đồ": "Merkkleuren in het diagram invoegen",
        "Định dạng sơ đồ Mermaid": "Mermaid-diagram opnieuw opmaken",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "De diagrambron is al netjes — er valt niets te wijzigen",
        "Đã định dạng lại sơ đồ": "Diagram opnieuw opgemaakt",
        "Đã định dạng lại %d sơ đồ": "%d {one=diagram|other=diagrammen} opnieuw opgemaakt",
        "Thư viện mẫu sơ đồ": "Bibliotheek met diagramsjablonen",
        "Mẫu sơ đồ đầy đủ": "Volledige diagramsjablonen",
        "Mẩu cú pháp": "Syntaxisfragmenten",
        "Đang soạn: %@": "Bezig met wijzigen: %@",
        "Đã chèn mẫu «%@»": "Sjabloon «%@» ingevoegd",
        "Tài liệu đang ở chế độ chỉ đọc.": "Dit document is alleen-lezen.",
        "Sơ đồ Mermaid": "Mermaid-diagram",
        "Tài liệu chưa có khối mermaid nào.": "Dit document heeft geen enkel mermaid-blok.",
        "Thương hiệu": "Merk",
        "Xuất…": "Exporteren…",
        "Chưa có sơ đồ nào": "Nog geen diagrammen",
        "%d sơ đồ · %@": "%d {one=diagram|other=diagrammen} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d {one=diagram|other=diagrammen} MISLUKT — diagram %3$d%4$@",
        ", dòng %d": ", regel %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Dit document heeft geen ```mermaid-blok en is ook geen .mmd-bestand.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Nog geen enkel diagram is klaar met tekenen.",
        "Không tìm thấy «%@» trong mã sơ đồ": "«%@» niet gevonden in de diagrambron",
        "không dựng được hàng rào chặn mạng cho WKWebView": "kan de netwerkblokkade voor WKWebView niet opbouwen",
        "Luật kết hợp": "Associatieregels",
        "Mỗi dòng một giỏ": "Eén mandje per rij",
        "Hai cột: mã · item": "Twee kolommen: id · item",
        "Dạng dữ liệu giao dịch": "Vorm van de transactiegegevens",
        "Cột giỏ hàng hoặc mã giao dịch": "Mandjekolom of transactie-id-kolom",
        "Cột item": "Itemkolom",
        "Ký tự phân tách item": "Scheidingsteken voor items",
        "Support tối thiểu, phần trăm": "Minimale support, percentage",
        "Confidence tối thiểu, phần trăm": "Minimale confidence, percentage",
        "Tách bởi:": "Gescheiden door:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "Tabel met associatieregels",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Let op",
        "%d giao dịch · %d item · %d luật": "%d {one=transactie|other=transacties} · %d {one=item|other=items} · %d {one=regel|other=regels}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — geen enkele regel haalde de drempels; verlaag support of confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — VROEGTIJDIG GESTOPT, de tabel is ONVOLLEDIG",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transactie bevat|other=transacties bevatten} beide kanten",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "De tweekolomsvorm heeft twee VERSCHILLENDE kolommen nodig.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%1$d {one=rij|other=rijen} gemarkeerd in %2$d {one=transactie die|other=transacties die} «%3$@» {one=bevat|other=bevatten}",
        "CSV: luật kết hợp…": "CSV: associatieregels…",
        "Khai phá theo nhóm": "Groepsmining",
        "Cột nhóm": "Groepskolom",
        "Cột giá trị": "Waardekolom",
        "Cột thứ hai cho tương quan": "Tweede kolom voor de correlatie",
        "Cách xếp hạng": "Manier van rangschikken",
        "Nhóm theo:": "Groeperen op:",
        "Giá trị:": "Waarde:",
        "Xếp theo:": "Rangschikken op:",
        "Bảng xếp hạng nhóm": "Tabel met groepsrangschikking",
        "Nhóm": "Groep",
        "Hàng": "Rijen",
        "Hàng rào riêng": "Eigen drempel",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r-verschil",
        "Ghi chú": "Notitie",
        "không đo được": "niet meetbaar",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=groep|other=groepen} · algemene referentiecorrelatie %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GROEP|other=GROEPEN} WEGGELATEN",
        "Bảng này không có cột chữ nào để gom nhóm.": "Deze tabel heeft geen tekstkolom om op te groeperen.",
        "Bảng này không có cột số nào để khai phá.": "Deze tabel heeft geen numerieke kolom om te doorzoeken.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%1$d {one=rij|other=rijen} van groep «%2$@» gemarkeerd",
        "CSV: khai phá theo nhóm…": "CSV: groepsmining…",
        "\u{2194}": "↔",
        "Dự báo": "Voorspelling",
        "Cột giá trị theo thời gian": "Waardekolom in de tijd",
        "Mô hình dự báo": "Voorspellingsmodel",
        "Số kỳ dự báo": "Aantal te voorspellen perioden",
        "Kết luận so với baseline": "Oordeel ten opzichte van de referentiemodellen",
        "Mô hình:": "Model:",
        "Số kỳ:": "Perioden:",
        "Chu kỳ:": "Seizoen:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Seizoensperiode; laat leeg om automatisch te detecteren",
        "Bảng giá trị dự báo": "Tabel met voorspelde waarden",
        "Kỳ": "Periode",
        "Dải 80%": "80%-band",
        "Dải 95%": "95%-band",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "niet berekenbaar",
        "Bảng này không có cột số nào để dự báo.": "Deze tabel heeft geen numerieke kolom om te voorspellen.",
        "Không dựng được dự báo cho cột này.": "Kan geen voorspelling opbouwen voor deze kolom.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Kolom «%1$@» heeft maar %2$d {one=numerieke waarde|other=numerieke waarden} — er zijn er minstens 4 nodig om te voorspellen.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# De reeks wordt in de rijvolgorde van het bestand gelezen — niet opnieuw gesorteerd, geen tijdkolom afgeleid.\n",
        "Sai số huấn luyện": "Trainingsfout",
        "CSV: dự báo chuỗi thời gian…": "CSV: tijdreeksvoorspelling…",
        "Holt-Winters cộng": "Holt-Winters additief",
        "Holt-Winters nhân": "Holt-Winters multiplicatief",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Kolommen die in de clustering gaan",
        "Đường cong WCSS": "WCSS-curve",
        "Phân cụm": "Cluster",
        "Chuẩn hoá:": "Schaling:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Selecteer ten minste één kolom.",
        "Không đủ dữ liệu để dựng đường cong.": "Niet genoeg gegevens om de curve op te bouwen.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "De elleboog suggereert k = %d. WCSS daalt ALTIJD als k groeit, dus dit is een leestruc voor de grafiek en geen statistisch criterium — kijk naar de curve en beoordeel of de knik duidelijk is.",
        "WCSS theo k": "WCSS naar k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "De k-afstand suggereert eps = %1$@ (minPts is standaard 2 × aantal kolommen = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Afstand tot de k-de buur",
        "Cần ít nhất 2 cột số để phân cụm.": "Voor clustering zijn ten minste 2 numerieke kolommen nodig.",
        "Cụm theo %@ và %@": "Clusters op %@ en %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — clusters gevonden in %d {one=dimensie|other=dimensies}; de grafiek toont alleen de eerste 2",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# ruis (cluster_id = -1): %d {one=rij|other=rijen}\n",
        "CSV: phân cụm…": "CSV: clustering…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Clustercentra (oorspronkelijke eenheden) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Correlatiematrix",
        "Phương pháp tương quan": "Correlatiemethode",
        "Tương quan không hàm ý nhân quả.": "Correlatie betekent geen oorzakelijk verband.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Sterkste paar: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klik op een cel voor een spreidingsdiagram.",
        "Không cặp nào đo được.": "Geen enkel paar is meetbaar.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ over %4$d {one=rij|other=rijen}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Voor correlatie zijn ten minste 2 numerieke kolommen nodig.",
        "Không đọc được cột «%@».": "Kan kolom «%@» niet lezen.",
        "CSV: ma trận tương quan…": "CSV: correlatiematrix…",
        "Bất thường": "Afwijkingen",
        "Danh sách bất thường": "Lijst met afwijkingen",
        "Cột:": "Kolom:",
        "Cột số cần xét": "Te onderzoeken numerieke kolom",
        "Cách:": "Methode:",
        "Phương pháp phát hiện": "Detectiemethode",
        "Phương pháp đã dùng": "Gebruikte methode",
        "Ngưỡng": "Drempel",
        "Đánh dấu": "Markeren",
        "Xuất tab mới": "Exporteren naar een nieuw tabblad",
        "Dòng": "Regel",
        "Điểm": "Score",
        "Vì sao": "Waarom",
        "nhẹ": "licht",
        "vừa": "matig",
        "nặng": "ernstig",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=rij|other=rijen} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Deze tabel heeft geen numerieke kolom om afwijkingen in te zoeken.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=afwijkende regel|other=afwijkende regels} gemarkeerd",
        "CSV: tìm bất thường…": "CSV: afwijkingen zoeken…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d {one=regel|other=regels}, alle GESLAAGD · %2$d {one=rij|other=rijen} · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d {one=fout|other=fouten} · %2$d {one=waarschuwing|other=waarschuwingen} over %3$d {one=regel|other=regels} · %4$d {one=rij|other=rijen} · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Bewaar eerst het document — de kwaliteitsregels staan naast het gegevensbestand.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Nog geen regelset. Maak het bestand %@ aan en open opnieuw.",
        "Lịch sử": "Geschiedenis",
        "Câu đã lưu": "Bewaarde zoekopdrachten",
        "Lưu câu này…": "Deze zoekopdracht bewaren…",
        "Lưu câu truy vấn": "Zoekopdracht bewaren",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Geef hem een naam om hem later terug te vinden. Dezelfde naam overschrijft.",
        "Ví dụ: Doanh thu theo tỉnh": "Bijvoorbeeld: Omzet per provincie",
        "Chưa nhập giá trị cho tham số: %@": "Geen waarde ingevoerd voor parameter: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "De plug-in is gewijzigd sinds je hem goedkeurde — GEditor weigert hem uit te voeren",
        "Chạy plugin chưa duyệt?": "Een niet-goedgekeurde plug-in uitvoeren?",
        "Tôi tin file này — chạy": "Ik vertrouw dit bestand — uitvoeren",
        "KHÔNG có chữ ký": "NIET ondertekend",
        "Chữ ký: %@": "Handtekening: %@",
        "Đường dẫn: %@": "Pad: %@",
        "Thay": "Vervangen",
        "Thay tất cả": "Alles vervangen",
        "Chuỗi thuần": "Platte tekst",
        "Extended (\\n \\t \\xNN)": "Uitgebreid (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Reguliere expressie",
        "Phân biệt hoa thường": "Hoofdlettergevoelig",
        "Cả từ": "Heel woord",
        "Không có kết quả": "Geen resultaten",
        "Thử biểu thức chính quy…": "Een reguliere expressie testen…",
        "Chế độ Log (tô theo mức)": "Logmodus (kleur per niveau)",
        "Lọc log theo mức…": "Log filteren op niveau…",
        "Chạy trên cả thư mục…": "Uitvoeren op de hele map…",
        "Lọc qua lệnh ngoài…": "Filteren via een externe opdracht…",
        "Script…": "Scripts…",
        "Gói mở rộng…": "Uitbreidingspakketten…",
        "Cửa sổ mới": "Nieuw venster",
        "Tách tab ra cửa sổ mới": "Tabblad losmaken in een nieuw venster",
        "Chưa mở thư mục nào": "Geen map geopend",
        "Tìm file trong thư mục": "Een bestand in de map zoeken",
        "Lọc theo tên": "Filteren op naam",
        "File mới…": "Nieuw bestand…",
        "Thư mục mới…": "Nieuwe map…",
        "Đổi tên…": "Hernoemen…",
        "Chuyển vào Thùng rác": "Verplaats naar prullenmand",
        "Hiện trong Finder": "Toon in Finder",
        "Đang đọc cấu trúc tài liệu…": "Bezig met het lezen van de documentstructuur…",
        "file này không có hàm nào": "dit bestand heeft geen functies",
        "Không có gì khớp": "Geen overeenkomsten",
        "Văn bản thuần": "Platte tekst",
        "🔒 Chỉ đọc": "🔒 Alleen-lezen",
        "Đang theo dõi": "Wordt gevolgd",
        "ngắt tại cột": "terugloop bij kolom",
        "Cú pháp": "Syntaxis",
        "Bấm để chèn vào ô truy vấn": "Klik om in de zoekopdracht in te voegen",
        "truy vấn không hợp lệ": "ongeldige zoekopdracht",
        "khóa `ten` ở gốc": "sleutel «naam» in de wortel",
        "khóa có dấu cách": "sleutel met spaties",
        "phần tử đầu": "eerste element",
        "mọi phần tử": "alle elementen",
        "lát cắt": "segment",
        "hợp nhiều chỉ số": "vereniging van indexen",
        "mọi khóa `gia` ở mọi tầng": "alle sleutels «prijs» op alle niveaus",
        "mọi nút": "alle knooppunten",
        "lọc theo số": "filteren op getal",
        "lọc theo có mặt": "filteren op aanwezigheid",
        "Tới lỗi đầu tiên": "Naar de eerste fout",
        "Cột doanh_thu là số": "De kolom omzet is numeriek",
        "lọc…": "filteren…",
        "Hủy": "Annuleer",
        "Thực hiện thay": "Vervanging uitvoeren",
        "xem trước": "voorvertoning",
        "tương tác": "interactief",
        "Soạn thảo": "Wijzigen",
        "Giao diện": "Interface",
        "Phím tắt": "Toetscombinaties",
        "Cỡ chữ": "Tekstgrootte",
        "Bề rộng TAB": "Tabbreedte",
        "Thụt lề bằng TAB": "Inspringen met tabs",
        "Tự động thụt lề khi xuống dòng": "Automatisch inspringen bij een nieuwe regel",
        "Tô mọi kết quả tìm kiếm": "Alle zoekresultaten markeren",
        "Chuẩn hóa về NFC khi lưu": "Normaliseren naar NFC bij het bewaren",
        "Ngôn ngữ": "Taal",
        "Nền": "Weergave",
        "Theo hệ thống": "Systeem volgen",
        "Sáng": "Licht",
        "Tối": "Donker",
        "Theme": "Thema",
        "Dùng preset Notepad++": "De Notepad++-voorinstelling gebruiken",
        "Về phím mặc định": "Terug naar de standaardtoetsen",
        "Mở file cấu hình": "Configuratiebestand openen",
        "Xuất theme hiện tại": "Het huidige thema exporteren",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "De taalwijziging wordt volledig toegepast bij de volgende start.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "De standaardtoetsen komen terug bij de volgende start.",
        "Xem trước Markdown": "Markdown-voorvertoning",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "De voorvertoning gebruikt de Markdown-engine van het systeem: nog geen tabellen en geen kleuren in codeblokken.",
        "Thử biểu thức chính quy": "Een reguliere expressie testen",
        "Biểu thức": "Expressie",
        "Văn bản thử": "Testtekst",
        "Kết quả": "Resultaat",
        "Kết quả khớp": "Overeenkomsten",
        "Biểu thức này làm gì": "Wat deze expressie doet",
        "Giải thích biểu thức": "De expressie uitleggen",
        "Chế độ tìm kiếm": "Zoekmodus",
        "Kết quả tìm kiếm": "Zoekresultaten",
        "Không khớp chỗ nào": "Geen overeenkomsten",
        " (đã cắt bớt)": " (ingekort)",
        "Bản đồ tài liệu": "Documentkaart",
        "Thanh tab": "Tabbladbalk",
        "Hàng tiêu đề cột": "Koprij van de kolommen",
        "Không có cột nào": "Geen kolommen",
        "Cây thư mục workspace": "Boomstructuur van de werkruimte",
        "Danh sách hàm và lớp": "Lijst met functies en klassen",
        "Kết quả tìm trong thư mục": "Zoekresultaten in de map",
        "Bảng dữ liệu CSV": "CSV-gegevenstabel",
        "Bàn làm sạch dữ liệu": "Werkbank voor gegevensopschoning",
        "Truy vấn JSONPath": "JSONPath-zoekopdracht",
        "Danh sách lỗi dữ liệu": "Lijst met gegevensfouten",
        "Bộ đánh giá golden set…": "Beoordelaar voor de golden set…",
        "So với điểm ngoài (JSONL)…": "Vergelijken met externe scores (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Kies een bestand met externe scores (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Het geselecteerde knooppunt hernoemen",
        "Gộp các node đang chọn": "De geselecteerde knooppunten samenvoegen",
        "Tách node đang chọn": "Het geselecteerde knooppunt splitsen",
        "Trích subgraph đang chọn ra tab mới": "De geselecteerde subgrafiek naar een nieuw tabblad halen",
        "Không có gì để đổi": "Er valt niets te wijzigen",
        "%@ — áp %d thay đổi?": "%1$@ — %2$d {one=wijziging|other=wijzigingen} toepassen?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d {one=wijziging|other=wijzigingen} · Cmd-Z herstelt de hele reeks",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Zet de cursor op PRECIES ÉÉN knooppunt en probeer opnieuw",
        "Đổi tên «%@»": "«%@» hernoemen",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Alle randen en labels die naar dit knooppunt verwijzen, veranderen mee.",
        "Đổi tên node": "Knooppunt hernoemen",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Selecteer MINSTENS TWEE knooppunten en probeer opnieuw",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Canonieke vorm «%@» — meest voorkomend, langst, met accenten",
        "Gộp node": "Knooppunten samenvoegen",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Selecteer de RANDREGELS die je wilt verplaatsen en probeer opnieuw",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Alle geselecteerde regels moeten PRECIES ÉÉN knooppunt raken — selecteer meer randregels",
        "Tách «%@» — chuyển %d cạnh": "«%1$@» splitsen — %2$d {one=rand|other=randen} verplaatsen",
        "Cạnh tới: %@": "Randen naar: %@",
        "Tách node": "Knooppunt splitsen",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Document niet bewaard — het uitgehaalde bestand heeft een plek ernaast nodig",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Selecteer het deel van de grafiek dat je eruit wilt halen en probeer opnieuw",
        "Gom biến thể entity → bảng duyệt": "Entiteitsvarianten samenbrengen → controletabel",
        "Áp bảng duyệt đã sửa": "De gewijzigde controletabel toepassen",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Document niet bewaard — de controletabel moet naast het grafiekbestand staan",
        "Không tìm thấy biến thể nào để gom": "Geen varianten gevonden om samen te brengen",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=groep varianten|other=groepen varianten} — corrigeer de kolom «canonical» en voer «Controletabel toepassen» uit",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Geen controletabel «%@» — voer eerst «Entiteitsvarianten samenbrengen» uit",
        "Bảng duyệt không đọc được: %@": "Controletabel onleesbaar: %@",
        "Bảng duyệt không có dòng nào cần đổi": "De controletabel heeft geen enkele regel die gewijzigd moet worden",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Geen enkele plek in de grafiek komt overeen met de controletabel",
        "Gom biến thể entity": "Entiteitsvarianten samenbrengen",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=wijziging|other=wijzigingen} toegepast · aliastabel en markeringslijst naast het bestand geschreven",
        "Áp %d thay đổi lên đồ thị?": "%d {one=wijziging|other=wijzigingen} op de grafiek toepassen?",
        "%d alias → dạng chuẩn.": "%d {one=alias|other=aliassen} → canonieke vorm.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "Knooppunten SAMENVOEGEN (niet ongedaan te maken door opnieuw te typen):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias staat|other=aliassen staan} niet in de grafiek en {one=is|other=zijn} overgeslagen.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Dekkingsanalyse fragment ↔ entiteit",
        "Xuất gói ngữ cảnh (JSONL)": "Contextpakket exporteren (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Dekking fragment ↔ entiteit ↔ grafiek",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=entiteit|other=entiteiten} · %2$d {one=fragment|other=fragmenten} · %3$.0f %% van de entiteiten genoemd · %4$.0f %% van de fragmenten met entiteit",
        "Entity không chunk nào nhắc tới": "Entiteiten die door geen enkel fragment genoemd worden",
        "Chunk mồ côi (không chứa entity nào)": "Verweesde fragmenten (zonder enige entiteit)",
        "Node đồ thị không có entity đối ứng": "Grafiekknooppunten zonder bijbehorende entiteit",
        "không có": "geen",
        "Phương pháp": "Methode",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Kan de koppeling fragment ↔ entiteit niet opbouwen",
        "Chấm sức khoẻ đồ thị": "De gezondheid van de grafiek beoordelen",
        "sức khoẻ đồ thị": "gezondheid van de grafiek",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Gezondheid %1$@/100 · %2$d {one=fout|other=fouten} · %3$d {one=omkering|other=omkeringen} · %4$d verweesd",
        "Lai với đồ thị": "Hybride met de grafiek",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: het grafieksignaal wordt volledig genegeerd, het resultaat is gelijk aan puur BM25",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α hoog: de grafiek past de BM25-rangschikking maar licht aan",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α rond de standaardwaarde 0,7: BM25 leidt, de grafiek past aan",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α laag: de grafiek leidt, BM25 breekt alleen gelijke standen",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: alleen het grafieksignaal; fragmenten zonder entiteit staan gelijk",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Document niet bewaard — de hybride heeft een grafiekbestand naast het corpus nodig",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Grafiekbestand «%@» niet gevonden — de hybride heeft het nodig voor zijn signaal",
        "lai %.1f ms · %@": "hybride %.1f ms · %@",
        "Thuật toán…": "Algoritmen…",
        "PageRank (độ dày viền)": "PageRank (dikte van de rand)",
        "Cộng đồng (màu nền)": "Gemeenschappen (achtergrondkleur)",
        "Thành phần liên thông": "Samenhangende componenten",
        "Xuất bảng node ra tab mới": "De knooppunttabel naar een nieuw tabblad exporteren",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d {one=component|other=componenten} · de grootste %2$d {one=knooppunt|other=knooppunten} · %3$d verweesde knooppunten",
        "Tài liệu này không phải đồ thị DOT": "Dit document is geen DOT-grafiek",
        "Không dựng được bảng node/cạnh: %@": "Kan de knooppunt-/randtabel niet opbouwen: %@",
        "%d hàng · %@": "%d {one=rij|other=rijen} · %@",
        "Gán nhãn": "Labelen",
        "Ghi chú (tuỳ chọn)": "Notitie (optioneel)",
        "Lưu record": "Record bewaren",
        "Xuất CSV": "CSV exporteren",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Document niet bewaard — de beoordelaar moet naast het corpusbestand staan",
        "Không nạp được bộ đánh giá: %@": "Kan de beoordelaar niet laden: %@",
        "Không lưu được: %@": "Kan niet bewaren: %@",
        "Bộ đánh giá chưa có record nào": "De beoordelaar heeft nog geen enkel record",
        "Không ghi được: %@": "Kan niet schrijven: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Dit document is geen .mmd-bestand, geen DOT en heeft geen mermaid-blok.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=knooppunt|other=knooppunten} · %d {one=rand|other=randen} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid-diagram: element toevoegen…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid-diagram: de twee geselecteerde elementen verbinden",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid-diagram: het label van het geselecteerde element wijzigen…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid-diagram: het geselecteerde element verwijderen",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid-diagram: bericht omhoog",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid-diagram: bericht omlaag",
        "Thêm phần tử": "Element toevoegen",
        "Thêm participant": "Deelnemer toevoegen",
        "Thêm mục": "Item toevoegen",
        "Thêm mục sơ đồ": "Een item aan het diagram toevoegen",
        "Sửa mục sơ đồ": "Een item van het diagram wijzigen",
        "Xoá mục sơ đồ": "Een item van het diagram verwijderen",
        "Xoá phần tử": "Element verwijderen",
        "Sửa nhãn": "Label wijzigen",
        "Đổi thứ tự message": "Berichten opnieuw ordenen",
        "Tên mục": "Naam van het item",
        "Mục mới": "Nieuw item",
        "Tên mục hiện trên sơ đồ.": "De naam van het item verschijnt op het diagram.",
        "Bảng thuộc tính sơ đồ": "Eigenschappentabel van het diagram",
        "Tài liệu này không có khối mermaid nào": "Dit document heeft geen mermaid-blok",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Aanduiding in de diagrambron — zonder spaties. Het label wijzig je daarna met een dubbelklik.",
        "Để trống thì hiện chính định danh.": "Laat je het leeg, dan wordt de aanduiding zelf getoond.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Alleen het zichtbare LABEL verandert; de aanduiding van het element blijft gelijk.",
        "Không rõ «%@» là phần tử nào": "Onduidelijk welk element «%@» is",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Selecteer PRECIES TWEE elementen en probeer opnieuw",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Zet de cursor op PRECIES ÉÉN element en probeer opnieuw",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Kies ÉÉN element om te verwijderen, of twee elementen die door een rand verbonden zijn",
        "Xoá «%@» và %d cạnh chạm nó?": "«%1$@» en de %2$d {one=rand die het raakt|other=randen die het raken} verwijderen?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "De knooppunten aan de andere kant van die randen blijven behouden — ze worden opnieuw gedeclareerd met hun label als de randinstructie hun enige declaratie was.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Diagram «%1$@» is alleen als tekst te wijzigen — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: sleep tussen twee elementen om ze te verbinden, dubbelklik om het label te wijzigen",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: sleep tussen twee deelnemers om een bericht toe te voegen; herordenen via het menu Gereedschap",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: wijzig in de eigenschappentabel hieronder",
        "Soạn trực quan đã bật": "Visueel wijzigen is ingeschakeld",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d {one=item|other=items} — wijzig rechtstreeks in de tabel, elke cel is één herstelstap",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Bij een taartdiagram een getal; bij een gantt wat na de dubbele punt staat.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid-diagram: blok naar een .mmd-bestand halen…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid-diagram: het gerefereerde bestand terugplaatsen",
        "Tách khối sơ đồ": "Diagramblok eruit halen",
        "Nhúng khối sơ đồ": "Diagramblok terugplaatsen",
        "Tách khối sơ đồ ra tệp riêng": "Het diagramblok naar een apart bestand halen",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Het bestand komt NAAST het document; het blok houdt één verwijzingsregel, zodat je maar op één plek wijzigt.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Document niet bewaard — het diagrambestand heeft een plek ernaast nodig",
        "Đã có tệp «%@» — chọn tên khác": "Bestand «%@» bestaat al — kies een andere naam",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Naar «%@» gehaald — het blok houdt één verwijzingsregel",
        "Mở tệp": "Bestand openen",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» teruggeplaatst; het bestand staat nog op schijf",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Dit blok bevat een echt diagram, geen verwijzing",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Dit blok verwijst naar «%@» — open dat bestand om het te wijzigen",
        "Không đọc được tệp sơ đồ %@": "Kan het diagrambestand %@ niet lezen",
        "Soạn trực quan": "Visueel wijzigen",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Sleep van het ene knooppunt naar het andere om een rand toe te voegen; dubbelklik om het label te wijzigen. Elke handeling is één herstelstap.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Visueel wijzigen: sleep tussen twee knooppunten om een rand toe te voegen, dubbelklik om het label te wijzigen",
        "Soạn trực quan đã tắt": "Visueel wijzigen is uitgeschakeld",
        "Thêm node…": "Knooppunt toevoegen…",
        "Thêm cạnh giữa hai node đang chọn…": "Een rand tussen de twee geselecteerde knooppunten toevoegen…",
        "Sửa nhãn node đang chọn…": "Het label van het geselecteerde knooppunt wijzigen…",
        "Xoá node/cạnh đang chọn": "Het geselecteerde knooppunt/de rand verwijderen",
        "Thêm node": "Knooppunt toevoegen",
        "Thêm cạnh": "Rand toevoegen",
        "Sửa nhãn node": "Knooppuntlabel wijzigen",
        "Xoá node": "Knooppunt verwijderen",
        "Xoá cạnh": "Rand verwijderen",
        "Cmd-Z hoàn tác": "Cmd-Z herstelt",
        "Tài liệu đang ở chế độ chỉ đọc": "Dit document is alleen-lezen",
        "Nhãn của «%@»": "Label van «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Alleen het zichtbare LABEL verandert; de aanduiding van het knooppunt blijft gelijk.",
        "Không rõ «%@» là node nào": "Onduidelijk welk knooppunt «%@» is",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Aanduiding van het knooppunt in het DOT-bestand. Het label wijzig je daarna met een dubbelklik op de tekening.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Selecteer PRECIES TWEE knooppunten en probeer opnieuw",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Kies ÉÉN knooppunt om te verwijderen, of twee knooppunten die door een rand verbonden zijn",
        "Xoá node «%@» và %d cạnh chạm nó?": "Knooppunt «%1$@» en de %2$d {one=rand die het raakt|other=randen die het raken} verwijderen?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Blijven er losse randen staan, dan maakt DOT de knooppunten daaruit opnieuw aan — het verwijderde knooppunt duikt bij de volgende tekening weer op.",
        "Phòng thí nghiệm truy hồi BM25": "BM25-zoeklab",
        "Câu hỏi — Enter để tìm": "Vraag — Enter om te zoeken",
        "Đánh giá…": "Beoordelen…",
        "Đang dựng chỉ mục": "Bezig met het opbouwen van de index",
        "Không chunk nào khớp": "Geen enkel fragment komt overeen",
        "kết quả trên": "beste resultaten",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: elk woord telt SLECHTS één keer, hoe vaak het ook voorkomt",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 laag: een woord herhalen levert nauwelijks extra score op",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 rond de standaardwaarde 1,2: herhalen levert score op, maar steeds minder",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 hoog: een fragment dat een woord vaak herhaalt wordt sterk beloond",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: de lengte wordt genegeerd, lange fragmenten worden niet bestraft",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b laag: lange fragmenten worden maar licht bestraft",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b rond de standaardwaarde 0,75: lange fragmenten worden matig bestraft",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: maximale straf voor lengte, korte fragmenten krijgen de voorkeur",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: zoeklab…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Document niet bewaard — de BM25-index staat naast het corpusbestand en heeft dus een pad nodig",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Dit bestand is geen JSONL — het Retrieval Lab werkt op een corpus van fragmenten",
        "Không dựng được chỉ mục BM25 cho tệp này": "Kan geen BM25-index opbouwen voor dit bestand",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Document niet bewaard — er is een corpuspad nodig om het rapport te genereren",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Kies een beoordelingsset (CSV of JSONL: vraag + verwacht fragment-id)",
        "Đánh giá truy hồi": "Beoordeling van het zoeken",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Wijzig k1, b of k hierboven en kijk opnieuw om twee configuraties te vergelijken; voeg een «compare»-blok toe om twee parametersets parallel op dezelfde beoordelingsset te draaien.",
        "Lỗi": "Fout",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, gemiddeld %.0f)",
        "Chế độ JSONL": "JSONL-modus",
        "Bản ghi": "Record",
        "Chi tiết": "Details",
        "Bản ghi ở dòng": "Record op regel",
        "không phải JSON hợp lệ": "is geen geldige JSON",
        "bản ghi": "records",
        "dòng trắng": "lege regels",
        "không phải đối tượng": "is geen object",
        "bảng hiện": "getoonde tabel",
        "ĐÃ HUỶ giữa chừng": "HALVERWEGE GEANNULEERD",
        "Không lọc": "Geen filter",
        "bản ghi khớp bộ lọc": "records die aan het filter voldoen",
        "Đưa con nháy tới một dòng để xem bản ghi": "Zet de cursor op een regel om het record te zien",
        "Không có bản ghi nào hỏng": "Geen kapotte records",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Nog niet onderzocht. Voer «JSONL: fragmenten onderzoeken» opnieuw uit na de controle.",
        "trường văn bản": "tekstveld",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHEMA (geraden — te wijzigen door een ander veld te kiezen)",
        "văn bản": "tekst",
        "định danh": "aanduiding",
        "metadata lồng": "geneste metagegevens",
        "TRƯỜNG": "VELD",
        "phủ": "dekking",
        "nhiều kiểu": "meerdere typen",
        "ĐỘ DÀI — ký tự": "LENGTE — tekens",
        "ĐỘ DÀI — từ": "LENGTE — woorden",
        "ĐỘ DÀI — token ước lượng": "LENGTE — geschatte tokens",
        "RỖNG VÀ TRÙNG": "LEEG EN DUBBEL",
        "chunk rỗng": "lege fragmenten",
        "dòng": "regels",
        "nhóm trùng chính xác": "groepen exacte duplicaten",
        "dòng không đọc được, không vào thống kê": "onleesbare regels, buiten de statistiek",
        "PHƯƠNG PHÁP": "METHODE",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«tekens» telt Unicode-tekens (scalairen), niet zichtbare groepen",
        "«từ» tách theo khoảng trắng ASCII": "«woorden» splitst op ASCII-spaties",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«tokens» telt met een lettergreepsplitser — NIET die van het model",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«duplicaat» betekent een EXACT duplicaat; bijna-duplicaten staan in het blok ```quality",
        "chunk": "fragmenten",
        "JSONL: kiểm và soi chunk…": "JSONL: fragmenten controleren en onderzoeken…",
        "Ảnh": "Afbeelding",
        "PDF": "PDF",
        "Tài liệu Word": "Word-document",
        "Bảng tính Excel": "Excel-werkblad",
        "Bản trình chiếu PowerPoint": "PowerPoint-presentatie",
        "File nén": "Archief",
        "Vừa khung": "Passend in het venster",
        "Chép ảnh": "Afbeelding kopiëren",
        "Xoay": "Draaien",
        "Không đọc được ảnh «%@»": "Kan de afbeelding «%@» niet lezen",
        "Đã chép ảnh vào clipboard": "Afbeelding naar het klembord gekopieerd",
        "Bôi vàng": "Geel markeren",
        "Gạch chân": "Onderstrepen",
        "Ghi chú…": "Notitie…",
        "Bỏ chú thích": "Aantekeningen verwijderen",
        "Lấy chữ ra tab mới": "De tekst naar een nieuw tabblad halen",
        "Lưu bản có chú thích…": "De versie met aantekeningen bewaren…",
        "Tìm trong PDF": "Zoeken in de PDF",
        "Thêm": "Toevoegen",
        "Trang %d/%d": "Pagina %d/%d",
        "Trang %d": "Pagina %d",
        "Kết quả %d/%d": "Resultaat %d/%d",
        "0 kết quả": "0 resultaten",
        "Không đọc được PDF «%@»": "Kan de PDF «%@» niet lezen",
        "PDF này có mật khẩu — chưa mở được nội dung": "Deze PDF is met een wachtwoord beveiligd — de inhoud is niet toegankelijk",
        "Không thấy «%@» trong tài liệu": "«%@» niet gevonden in het document",
        "Đã bôi vàng": "Gemarkeerd",
        "Đã gạch chân": "Onderstreept",
        "Hãy bôi đen một đoạn chữ trước": "Selecteer eerst een stuk tekst",
        "Đã thêm ghi chú": "Notitie toegevoegd",
        "Trang này chưa có chú thích nào": "Deze pagina heeft geen aantekeningen",
        "Đã bỏ %d chú thích trên trang này": "%d {one=aantekening|other=aantekeningen} van deze pagina verwijderd",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Deze PDF heeft geen tekstlaag — het is waarschijnlijk een scan",
        "Không ghi được tệp": "Kan het bestand niet schrijven",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Het geschreven bestand gaat NIET goed weer open — gebruik deze versie niet",
        "Đã lưu %@ · %d trang": "%@ bewaard · %d {one=pagina|other=pagina's}",
        "Tên": "Naam",
        "Kích thước": "Grootte",
        "Đã nén": "Gecomprimeerd",
        "Tỉ lệ": "Verhouding",
        "Sửa lúc": "Gewijzigd op",
        "Mở mục đang chọn": "Het geselecteerde onderdeel openen",
        "Bung ra thư mục…": "Uitpakken naar een map…",
        "Bung vào đây": "Hier uitpakken",
        "%d mục": "%d {one=onderdeel|other=onderdelen}",
        "giải nén ra %@": "uitgepakt naar %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— de binnenkant van een Office-bestand is een archief; dit zijn de onderdelen",
        "Đã bung %d mục": "%d {one=onderdeel|other=onderdelen} uitgepakt",
        "%d mục hỏng": "%d {one=onderdeel kapot|other=onderdelen kapot}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=onderdeel|other=onderdelen} GEWEIGERD omdat hun paden buiten de doelmap vallen",
        "Không mở được mục này": "Kan dit onderdeel niet openen",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Er kan nog niet rechtstreeks in een %@ worden teruggeschreven — gebruik «Bewaar als…»",
        "Không có gì đổi": "Er is niets veranderd",
        "Đã ghi %d ô vào %@": "%1$d {one=cel|other=cellen} naar %2$@ geschreven",
        "Đã ghi %d đoạn vào %@": "%1$d {one=alinea|other=alinea's} naar %2$@ geschreven",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Kan niet naar het bestand schrijven — het origineel is ongeschonden",
        "dựng bài": "de testcase klaarzetten",
        "Không ghi được settings.json": "Kan settings.json niet schrijven",
        "Xoay trái": "Links draaien",
        "Xoay phải": "Rechts draaien",
        "Trang lên": "Pagina omhoog",
        "Trang xuống": "Pagina omlaag",
        "Xoá trang…": "Pagina's verwijderen…",
        "Xoá trang": "Pagina's verwijderen",
        "Trích trang…": "Pagina's extraheren…",
        "Trích trang ra tệp mới": "Pagina's naar nieuw bestand extraheren",
        "Gộp tệp PDF…": "PDF-bestand samenvoegen…",
        "Tách tệp…": "Bestand splitsen…",
        "Tách tệp PDF": "PDF-bestand splitsen",
        "Xuất ảnh…": "Afbeeldingen exporteren…",
        "Xuất trang ra ảnh PNG": "Pagina's als PNG-afbeeldingen exporteren",
        "Hoàn tác trang": "Paginabewerking ongedaan maken",
        "Lưu bản đã sửa…": "Bewerkte kopie bewaren…",
        "Phát": "Afspelen",
        "Tạm dừng": "Pauze",
        "Xem bình thường": "Normale weergave",
        "Chọn sheet": "Blad kiezen",
        "Mở sheet": "Blad openen",
        "Bỏ và đổi sheet": "Verwerpen en blad wisselen",
        "Bảng tính có %d sheet.": "De werkmap heeft %d bladen.",
        "Bảng tính này chỉ có một sheet: «%@»": "Deze werkmap heeft maar één blad: ‘%@’",
        "Bỏ phần chưa lưu của sheet này?": "Niet-bewaarde wijzigingen in dit blad verwerpen?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Van blad wisselen vervangt het hele tabblad. Niet met ⌘S bewaard werk gaat verloren.",
        "Chọn tệp PDF cần gộp vào": "Kies het PDF-bestand om samen te voegen",
        "Chọn thư mục ghi ảnh": "Kies een map voor de afbeeldingen",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Kies waar te bewaren. Het tweede bestand komt hiernaast.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Het document heeft %d pagina's. Geef de te verwijderen pagina's op, bv. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Het document heeft %d pagina's. Geef de te extraheren pagina's op, bv. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Het document heeft %d pagina's. Geef de te exporteren pagina's op, bv. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Het document heeft %d pagina's. Geef het af te splitsen deel op, bv. 1-5; de rest wordt een tweede bestand.",
        "Đã xoay trang %d": "Pagina %d gedraaid",
        "Đã xoá trang %@ · còn %d trang": "Pagina's %@ verwijderd · %d pagina's over",
        "Đã gộp %d trang từ «%@»": "%d pagina's samengevoegd uit ‘%@’",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Gesplitst in %@ (%d pagina's) en %@ (%d pagina's)",
        "Đã ghi %@ — %@ · %d trang": "%@ geschreven — %@ · %d pagina's",
        "Đã xuất %d ảnh vào %@": "%d afbeeldingen geëxporteerd naar %@",
        "Chỉ xuất được %d/%d ảnh": "Slechts %d van %d afbeeldingen geëxporteerd",
        "Đã hoàn tác một thao tác trang": "Eén paginabewerking ongedaan gemaakt",
        "Không còn thao tác trang nào để hoàn tác": "Geen paginabewerkingen meer om ongedaan te maken",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "ALLE pagina's verwijderen kan niet — een PDF moet minstens één pagina houden",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Dat bereik is het hele document — niets om af te splitsen",
        "«%@» có mật khẩu — chưa gộp được": "‘%@’ is met een wachtwoord beveiligd — samenvoegen lukt niet",
        "«%@» không có trang nào": "‘%@’ bevat geen pagina's",
        "Đã ở trang đầu": "Al op de eerste pagina",
        "Đã ở trang cuối": "Al op de laatste pagina",
        "· đã sửa, chưa lưu": "· bewerkt, niet bewaard",
        "Ảnh động · %d khung": "Bewegende afbeelding · %d frames",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Niet-bewaard document — geen bestand op schijf voor binaire weergave",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Deze opdracht werkt alleen met Excel-werkmappen",
        "Không đọc được danh sách sheet": "Kan de lijst met bladen niet lezen",
        "Không có sheet «%@»": "Er is geen blad met de naam ‘%@’",
        "Không đọc được sheet «%@»": "Kan blad ‘%@’ niet lezen",
        "Sheet «%@» · %d hàng": "Blad ‘%@’ · %d rijen",
        "phần còn lại": "de rest",
        "Lưu ý": "Let op",
        "Cẩn thận": "Voorzichtig",
        "Xem thêm": "Zie ook",
        "Chép": "Kopieer",
        "Đã chép": "Gekopieerd",
        "Chép đoạn mã mẫu": "Voorbeeldcode kopiëren",
        "Tìm trong trợ giúp": "Zoek in help",
        "Lùi": "Terug",
        "Bắt đầu dùng": "Aan de slag",
        "Không mở cửa sổ này khi khởi động nữa": "Dit venster niet meer tonen bij het starten",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "De help is nog niet vertaald in deze taal — de Vietnamese tekst wordt getoond.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Ga naar offset (bv. 1F400 of 0x1F400)",
        "Chép dòng đã chọn": "Geselecteerde rijen kopiëren",
        "Đã chép %d dòng": "%d rijen gekopieerd",
        "Không đọc được «%@»": "Kan ‘%@’ niet lezen",
        "Tệp rỗng": "Leeg bestand",
        "Không đọc được offset «%@»": "Kan offset ‘%@’ niet lezen",
        "Offset 0x%@ vượt quá cỡ tệp": "Offset 0x%@ ligt voorbij het einde van het bestand",
        "Mở bằng ứng dụng khác…": "Openen met andere app…",
        "%d kênh": "%d kanalen",
        "Không phát được «%@»": "Kan ‘%@’ niet afspelen",
        "Không phát được — %@": "Afspelen lukt niet — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS heeft geen ingebouwde decoder voor het %@-formaat — dat is een systeemgrens, geen kapot bestand.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Je kunt de bytes nog steeds binair bekijken, of het openen met een app met een eigen decoder.",
        "Ký…": "Ondertekenen…",
        "Sửa chữ…": "Tekst bewerken…",
        "Sửa chữ": "Tekst bewerken",
        "Vẽ đè": "Overheen tekenen",
        "Ô chưa điền": "Volgend leeg veld",
        "Xoá nội dung đã điền": "Ingevulde waarden wissen",
        "Tệp này không có ô biểu mẫu nào": "Dit bestand heeft geen formuliervelden",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d formuliervelden gewist",
        "Mọi ô biểu mẫu đều đã có nội dung": "Alle formuliervelden zijn al ingevuld",
        "Còn %d ô chưa điền": "Nog %d velden leeg",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Invulbaar formulier: %d velden. Typ er direct in en kies dan ‘Bewerkte kopie bewaren…’",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Kies een handtekeningafbeelding (transparante achtergrond oogt het best)",
        "Không dựng được trang có chữ ký": "Kan de ondertekende pagina niet maken",
        "Đã chèn chữ ký vào trang %d": "Handtekening ingevoegd op pagina %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Selecteer eerst de tekst die je wilt wijzigen",
        "Vùng chọn quá nhỏ": "De selectie is te klein",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "De nieuwe tekst wordt met het systeemlettertype OVER de selectie getekend. De oude tekst is bedekt, niet verwijderd — die is nog steeds te extraheren, dus dit is geen redactie.",
        "Không dựng được trang đã sửa": "Kan de bewerkte pagina niet maken",
        "Đã vẽ đè chữ mới lên trang %d": "Nieuwe tekst over pagina %d getekend",
        "Đổi chế độ View / Code": "Wissel Weergave / Code",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Nog geen boomweergave voor JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Nog geen diagramweergave in het tabblad",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Nog geen overzichtsweergave voor PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Dit bestand heeft maar één weergavemodus",
        "%d nút": "%d knopen",
        "Không dựng được cây: %@": "Kan de boom niet opbouwen: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Het document is te groot voor een boom — gebruik de Code-modus",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Kon geen pagina's voor dit bestand opbouwen \u{2014} gebruik de Code-modus.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Dia's worden uit tekst opgebouwd; originele afbeeldingen en opmaak worden nog niet getekend.",
        "Vừa ngang": "Passend in breedte",
        "Thu nhỏ trang": "Pagina uitzoomen",
        "Phóng to trang": "Pagina inzoomen",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu":
            "\u{201C}%@\u{201D} niet gevonden in dit document",
        "Chỗ khớp %d/%d": "Overeenkomst %d van %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Er is geen tekst geselecteerd op de pagina.",
        "%d ký tự": "%d {one=teken|other=tekens}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Bestanden meteen in de View-modus openen als die er is",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· HALVERWEGE GEANNULEERD — tabel is onvolledig",
        "Chế độ hiển thị": "Weergavemodus",
        "Đổi giữa View và Code (⌥⌘V)": "Wisselen tussen View en Code (⌥⌘V)",
        "Trang tài liệu": "Documentpagina's",
        "Chữ đã dựng": "Opgemaakte tekst",
        "Trang bảng tính": "Werkbladpagina's",
        "Sơ đồ": "Diagram",
        "Cây khoá–giá trị": "Sleutel-waardeboom",
        "Bộ phát": "Speler",
        "Danh sách mục": "Lijst met items",
        "Báo cáo đã dựng": "Opgemaakt rapport",
        "Tô theo mức": "Gekleurd op niveau",
        "Trang slide": "Diapagina's",
        "Dàn ý": "Overzicht",
        "Lưu rồi dựng lại": "Bewaren en opnieuw opbouwen",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Toont de versie OP SCHIJF — niet-bewaarde wijzigingen staan hier niet in.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Het systeem kon de documentweergave niet opbouwen — gebruik de Code-modus.",
        "Lưu tệp trước khi xem trang.": "Bewaar het bestand voordat je de pagina's bekijkt.",
        "Đang ở chế độ Code": "Nu in Code-modus",
        "Đang ở chế độ View": "Nu in View-modus",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Je ziet de bron — klik voor de View-modus (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "In View-modus — klik om terug te gaan naar de bron (⌥⌘V)",
        "Tín hiệu: %@": "Signaal: %@",
        "Lý do: %@": "Reden: %@",
        "Chi tiết: %@": "Detail: %@",
        "Mở báo cáo": "Rapport openen",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor stopte onverwacht om %@ — open het rapport om het te lezen; er wordt niets verstuurd.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligaturen — uit houdt elk teken in een eigen cel",
        "Chế độ CSV": "CSV-modus",
        "Dấu phân tách": "Scheidingsteken",
        "Tự nhận diện": "Automatisch herkennen",
        "Dấu phân tách: %@": "Scheidingsteken: %@",
        "Theo đuôi tệp": "Volgens bestandsextensie",
        "%d dấu cách": "%d {one=spatie|other=spaties}",
        "Tài liệu đang sửa được": "Dit document is bewerkbaar",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Alleen-lezen omdat het bestand wordt gevolgd — stop het volgen om te bewerken",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Alleen-lezen omdat het bestand op schijf niet beschrijfbaar is",
        "Đã mở khoá — tài liệu sửa được": "Ontgrendeld — het document is weer bewerkbaar",
        "Nhân bản tệp": "Bestand dupliceren",
        "Đổi tên tệp…": "Bestand hernoemen…",
        "Chuyển tệp tới…": "Bestand verplaatsen naar…",
        "XML: đánh giá XPath…": "XML: XPath evalueren…",
        "Đánh giá XPath": "XPath evalueren",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Bijvoorbeeld: //bestelling/regel[2]/@code · //*[@soort='A'] · count(//regel)",
        "Đánh giá": "Evalueren",
        "XPath không đọc được: %@": "Deze XPath is niet leesbaar: %@",
        "XPath «%@» không khớp node nào": "XPath ‘%@’ vond geen enkele node",
        "XPath «%@» — %d node": "XPath ‘%@’ — %d {one=node|other=nodes}",
        "XPath «%@»: %d node": "XPath ‘%@’: %d {one=node|other=nodes}",
        "Lưu tệp trước khi nhân bản.": "Bewaar het bestand voordat je het dupliceert.",
        "Không nhân bản được": "Dupliceren lukte niet",
        "Đã nhân bản thành %@": "Gedupliceerd als %@",
        "Lưu tệp trước khi đổi tên.": "Bewaar het bestand voordat je het hernoemt.",
        "Đổi tên tệp": "Bestand hernoemen",
        "Tên hiện tại: %@": "Huidige naam: %@",
        "Đổi tên": "Hernoemen",
        "Tên tệp không hợp lệ": "Die bestandsnaam is niet geldig",
        "Đã có tệp tên %@ ở đó": "Daar staat al een bestand met de naam %@",
        "Lưu tệp trước khi chuyển.": "Bewaar het bestand voordat je het verplaatst.",
        "Chuyển tới": "Hierheen verplaatsen",
        "Thư mục đích đã có tệp tên %@": "De doelmap heeft al een bestand met de naam %@",
        "Không chuyển được tệp": "Het bestand kon niet worden verplaatst",
        "Đã chuyển tới %@": "Verplaatst naar %@",
        "Bảng mã:": "Tekencodering:",
        "Xuống dòng:": "Regeleinden:",
        "Riêng cho %@": "Alleen voor %@",
        "    %d — dùng TAB": "    %d — tabs",
        "    %d — dùng dấu cách": "    %d — spaties",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Eigen regel verwijderen, globale instelling gebruiken",
        "%@: thụt lề %d %@": "%@: inspringing %d %@",
        "TAB": "tabs",
        "dấu cách": "spaties",
        "Xuất": "Exporteren",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Open de resultaten als tekstpaneel — bewaar met ⌘S",
        "Lượt tìm trước đó": "Eerdere zoekopdrachten",
        "«%@» — %d kết quả": "‘%@’ — %d {one=resultaat|other=resultaten}",
        "Kết quả tìm «%@»": "Zoekresultaten voor ‘%@’",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Bestandsnamen filteren — bv. *.csv;*.log (leeg: elk tekstbestand)",
        "Thư mục %@ không có file văn bản nào": "De map %@ bevat geen tekstbestanden",
        "Không tệp nào trong %@ khớp «%@»": "Geen bestand in %@ komt overeen met ‘%@’",
        "%d byte · %d dòng": "%d bytes · %d {one=regel|other=regels}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d bytes · %d {one=regel|other=regels} — te groot om tekens en woorden te tellen",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d bytes · %d {one=teken|other=tekens} · %d {one=woord|other=woorden} · %d {one=regel|other=regels}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Dit document heeft %d {one=regel|other=regels}, %d bytes. Typ een regelnummer, ‘regel,kolom’ of ‘@byte’.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "‘%@’ is niet leesbaar — typ een regelnummer, ‘regel,kolom’ of ‘@byte’",
    ]
}
