import Foundation

/// Bảng dịch tiếng Rumani. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let ro: [String: String] = [
        "Bản đã lưu…": "Versiuni salvate…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Acest document nu a fost salvat niciodată — nu există încă istoric",
        "Chưa có bản đã lưu nào trước đó": "Nu există versiuni salvate anterioare",
        "Không đọc được bản ấy": "Versiunea aceasta nu poate fi citită",
        "Khôi phục bản đã lưu": "Restaurează versiunea salvată",
        "XML: kiểm theo DTD/XSD…": "XML: validare după DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Acest Mac nu are libxml2, așa că validarea XSD nu este disponibilă.",
        "Chọn lược đồ XSD để kiểm": "Alegeți o schemă XSD pentru validare",
        "Hợp lệ theo": "Valid față de",
        "Plugin chạy xong, không đổi gì": "Modulul s-a încheiat fără să schimbe nimic",
        "Chưa cài plugin native nào": "Niciun modul nativ instalat",
        "Gỡ plugin này": "Elimină acest modul",
        "Gỡ plugin này?": "Eliminați acest modul?",
        "Gỡ": "Elimină",
        "Cài plugin native…": "Instalează un modul nativ…",
        "Mở thư mục plugin": "Deschide dosarul modulelor",
        "Chọn file .dylib của plugin native": "Alegeți fișierul .dylib al modulului",
        "Đã cài:": "Instalat:",
        "Đã gỡ:": "Eliminat:",
        "Plugin native…": "Module native…",
        "Chỉ nhận file .dylib.": "Se acceptă doar fișiere .dylib.",
        "Đã có một plugin trùng tên:": "Un modul cu același nume este deja instalat:",
        "Không chép được plugin:": "Modulul nu poate fi copiat:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Modulele native sunt disponibile doar în descărcarea directă, nu în versiunea din App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Procesul ajutător al modulelor nu poate fi găsit.",
        "Không khởi động được tiến trình phụ:": "Procesul ajutător al modulelor nu poate fi pornit:",
        "Tiến trình plugin đã dừng giữa chừng.": "Procesul modulului s-a oprit pe neașteptate.",
        "Plugin không trả lời kịp — đã dừng nó.": "Modulul nu a răspuns la timp — a fost oprit.",
        "Plugin trả lời sai giao thức:": "Modulul a răspuns cu un mesaj deformat:",
        "Plugin báo lỗi:": "Modulul a raportat o eroare:",
        "Về GEditor": "Despre GEditor",
        "Cài đặt…": "Configurări…",
        "Thoát GEditor": "Ieșire din GEditor",
        "File": "Fișier",
        "Tab mới": "Filă nouă",
        "Đóng tab": "Închide fila",
        "Tab kế": "Fila următoare",
        "Tab trước": "Fila anterioară",
        "Tài liệu mới": "Document nou",
        "Mở…": "Deschide…",
        "Mở thư mục làm Workspace…": "Deschide dosarul ca spațiu de lucru…",
        "Mở gần đây": "Deschise recent",
        "Lưu": "Salvează",
        "Lưu thành…": "Salvează ca…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Taie spațiile de la capăt la salvare",
        "Theo dõi file (tail -f)": "Urmărește fișierul (tail -f)",
        "In…": "Tipărește…",
        "Mở lại tab vừa đóng": "Redeschide ultima filă închisă",
        "Chưa có file nào": "Niciun fișier recent",
        "Xoá danh sách": "Golește meniul",
        "Edit": "Editare",
        "Hoàn tác": "Anulează",
        "Làm lại": "Refă",
        "Cắt": "Taie",
        "Sao chép": "Copiază",
        "Dán": "Lipește",
        "Lịch sử clipboard…": "Istoricul clipboardului…",
        "Column Editor…": "Editor de coloane…",
        "Chọn lần kế tiếp": "Selectează apariția următoare",
        "Chọn tất cả": "Selectează tot",
        "Nhân đôi dòng": "Dublează linia",
        "Xóa dòng": "Șterge linia",
        "Comment dòng": "Comentează / decomentează",
        "Chưa chép gì trong phiên này": "Nu ați copiat încă nimic",
        "Xoá lịch sử": "Golește istoricul",
        "Search": "Căutare",
        "Tìm…": "Caută…",
        "Tìm và thay…": "Caută și înlocuiește…",
        "Tìm trong thư mục…": "Caută în dosar…",
        "Thay trong thư mục…": "Înlocuiește în dosar…",
        "Kết quả kế": "Rezultatul următor",
        "Kết quả trước": "Rezultatul anterior",
        "Đi tới dòng…": "Mergi la linia…",
        "Nhảy tới ngoặc khớp": "Sari la paranteza pereche",
        "Đánh dấu mọi dòng khớp…": "Marchează toate liniile care se potrivesc…",
        "Đảo dấu": "Inversează marcajele",
        "Bỏ mọi dấu": "Șterge toate marcajele",
        "Chép dòng đã đánh dấu": "Copiază liniile marcate",
        "Xóa dòng đã đánh dấu": "Șterge liniile marcate",
        "Chỉ giữ dòng đã đánh dấu": "Păstrează doar liniile marcate",
        "Lines": "Linii",
        "Sắp xếp A→Z": "Sortează A→Z",
        "Sắp xếp Z→A": "Sortează Z→A",
        "Sắp xếp tự nhiên": "Sortare naturală",
        "Khử trùng lặp": "Elimină duplicatele",
        "Đảo thứ tự dòng": "Inversează liniile",
        "Dời dòng lên": "Mută liniile în sus",
        "Dời dòng xuống": "Mută liniile în jos",
        "Ghép dòng": "Unește liniile",
        "Tách dòng theo độ dài…": "Taie liniile după lungime…",
        "Tách dòng theo ký tự…": "Taie liniile după caracter…",
        "Xóa dòng rỗng": "Elimină liniile goale",
        "Nén dòng trống liên tiếp": "Comprimă liniile goale",
        "Cắt khoảng trắng cuối dòng": "Taie spațiile de la capătul liniei",
        "Tab → Space": "Tab → spațiu",
        "Space → Tab": "Spațiu → tab",
        "HOA": "MAJUSCULE",
        "thường": "minuscule",
        "Chữ Hoa Đầu Từ": "Fiecare Cuvânt Cu Majusculă",
        "Chữ hoa đầu câu": "Prima literă majusculă",
        "Đảo hoa/thường": "iNVERSEAZĂ mAJUSCULELE",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: alege foaia…",
        "Xem dạng bảng / văn bản": "Comută între tabel și text",
        "Xóa cột…": "Șterge coloana…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Verifică datele (coloane · tipuri)",
        "Bàn làm sạch dữ liệu…": "Banc de curățare a datelor…",
        "Chạy công thức làm sạch…": "Rulează o rețetă de curățare…",
        "Chuyển đổi…": "Convertește…",
        "Đổi dấu phân tách…": "Schimbă separatorul…",
        "Xuất sang JSON…": "Exportă în JSON…",
        "Format": "Format",
        "Bảng mã…": "Codificare…",
        "Xuống dòng…": "Sfârșituri de linie…",
        "Chuẩn hóa Unicode…": "Normalizează Unicode…",
        "JSON: định dạng lại": "JSON: formatează",
        "JSON: thu gọn một dòng": "JSON: comprimă",
        "JSON: sắp xếp khóa": "JSON: sortează cheile",
        "JSON: truy vấn JSONPath…": "JSON: interogare JSONPath…",
        "CSV: truy vấn SQL…": "CSV: interogare SQL…",
        "Truy vấn SQL": "Interogare SQL",
        "Đang chạy…": "Se execută…",
        "Xuất ra tab mới": "Exportă într-o filă nouă",
        "Tài liệu rỗng — không có bảng để truy vấn": "Document gol — nu există tabel de interogat",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Nu este un tabel CSV — primul rând are o singură coloană",
        "Không đọc được câu truy vấn": "Interogarea nu a putut fi citită",
        "Không kiểm được câu truy vấn": "Interogarea nu a putut fi verificată",
        "Vàng (mặc định)": "Galben (implicit)",
        "Xanh dương": "Albastru",
        "Xanh lá": "Verde",
        "Vàng đất": "Ocru",
        "Tím": "Violet",
        "Hồng": "Roz",
        "Xanh ngọc": "Turcoaz",
        "Cam": "Portocaliu",
        "Xám lam": "Ardezie",
        "Văn bản": "Text",
        "Dãy số": "Serie de numere",
        "Dãy ngày": "Serie de date",
        "Chữ HOA (hex)": "Majuscule (hexa)",
        "Bắt đầu": "Început",
        "Bước": "Pas",
        "Đệm 0 tới": "Completează cu zerouri până la",
        "Hệ": "Bază",
        "Ngày đầu": "Prima dată",
        "Định dạng": "Format",
        "Chèn": "Inserează",
        "Huỷ": "Renunță",
        "Chuyển đổi định dạng": "Convertește formatul",
        "Xem trước 5 hàng đầu": "Previzualizează primele 5 rânduri",
        "Tạo tab mới": "Deschide într-o filă nouă",
        "Lưu ra file…": "Salvează în fișier…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Rezultatul se deschide într-o filă nouă, nesalvată. Documentul original rămâne neatins.",
        "Chạy trên tài liệu này": "Rulează pe acest document",
        "Chạy trên thư mục…": "Rulează pe un dosar…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Toată rețeta este UN singur pas de anulare. Fișierul de pe disc rămâne neatins până la salvare.",
        "tắt": "oprit",
        "không thấy cột": "coloana nu a fost găsită",
        "sẵn sàng": "gata",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "ține ocupat un nucleu de procesor până la închiderea aplicației.",
        "Script không trả về gì": "Scriptul nu a returnat nimic",
        "Không dựng được máy JavaScript": "Motorul JavaScript nu a putut fi creat",
        "Lỗi JavaScript không rõ": "Eroare JavaScript necunoscută",
        "Bảng": "Tabel",
        "Áp sắp xếp vào file": "Aplică sortarea asupra fișierului",
        "Chuyển đổi ▾": "Convertește ▾",
        "Xuất dòng khớp": "Exportă rândurile care se potrivesc",
        "Ẩn cột này": "Ascunde această coloană",
        "Đổi tên tiêu đề…": "Redenumește antetul…",
        "Chèn cột trống bên trái": "Inserează o coloană goală la stânga",
        "Chèn cột trống bên phải": "Inserează o coloană goală la dreapta",
        "Xóa cột này khỏi file…": "Șterge această coloană din fișier…",
        "Phải còn ít nhất một cột đang hiện": "Cel puțin o coloană trebuie să rămână vizibilă",
        "Đang sắp xếp…": "Se sortează…",
        "Trở về thứ tự trong file": "Înapoi la ordinea din fișier",
        "trăm hàng đầu": "primele o sută de rânduri",
        "chọn cột": "alegerea coloanelor",
        "đặt tên cột kết quả": "denumirea unei coloane de rezultat",
        "lọc theo chữ": "filtrare după text",
        "ô rỗng": "celule goale",
        "ghép điều kiện": "combinarea condițiilor",
        "đếm hàng": "numărarea rândurilor",
        "gộp nhóm": "grupare și agregare",
        "nhỏ nhất, lớn nhất": "minim, maxim",
        "sắp xếp và cắt": "sortare și limitare",
        "tên cột có dấu cách": "nume de coloană cu spații",
        "Truy vấn bị dừng giữa chừng": "Interogarea a fost întreruptă",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Nu sunt acceptate: JOIN · subinterogare · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funcții de fereastră",
        "XML: định dạng lại": "XML: formatează",
        "XML: thu gọn một dòng": "XML: comprimă",
        "XML: kiểm cú pháp": "XML: verifică sintaxa",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: verifică cheile și indentarea",
        "View": "Vizualizare",
        "Ẩn/hiện sidebar (Function List)": "Comută bara laterală (lista de funcții)",
        "Ẩn/hiện bản đồ tài liệu": "Comută harta documentului",
        "Gấp / mở khối tại con nháy": "Pliază / depliază la cursor",
        "Gấp tất cả": "Pliază tot",
        "Bỏ gấp tất cả": "Depliază tot",
        "Gấp theo cấp": "Pliază până la nivelul",
        "Cấp %d": "Nivelul %d",
        "Đã gấp %d khối ở cấp %d": "S-au pliat %1$d {one=bloc|few=blocuri|other=de blocuri} la nivelul %2$d",
        "Tài liệu này chỉ sâu %d cấp": "Acest document are doar %d {one=nivel|few=niveluri|other=de niveluri}",
        "mermaid: không đọc được bản kê": "mermaid: manifestul nu poate fi citit",
        "Kiểm tra bản cập nhật…": "Caută actualizări…",
        "Kiểm tra bản cập nhật": "Caută actualizări",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Versiunile din App Store se actualizează prin Mac App Store, nu prin GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Această versiune nu are cheie de semnare a actualizărilor, deci nu poate căuta actualizări.",
        "Phóng to chữ": "Mărește",
        "Thu nhỏ chữ": "Micșorează",
        "Cỡ chữ gốc": "Mărime reală",
        "Chia đôi theo chiều dọc": "Împarte pe verticală",
        "Chia đôi theo chiều ngang": "Împarte pe orizontală",
        "Bỏ chia đôi": "Închide împărțirea",
        "Mở tab này ở nửa kia": "Deschide fila în celălalt panou",
        "Nhảy sang nửa kia": "Treci în celălalt panou",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Încadrarea rândurilor (oprită / la fereastră / la coloană)",
        "Ngắt dòng tại cột…": "Încadrează la coloana…",
        "Đánh dấu dòng này": "Comută semnul de carte",
        "Dấu kế tiếp": "Semnul de carte următor",
        "Dấu trước đó": "Semnul de carte anterior",
        "Màu đánh dấu…": "Culoarea semnului de carte…",
        "Hiện tất cả ký tự ẩn": "Arată toate caracterele invizibile",
        "  Khoảng trắng": "  Spații",
        "  Tab": "  Taburi",
        "  Xuống dòng": "  Sfârșituri de linie",
        "  NBSP · zero-width · điều khiển": "  NBSP · lățime zero · control",
        "Xem nhị phân": "Vizualizare binară",
        "Chế độ CSV (tô màu theo cột)": "Mod CSV (coloane curcubeu)",
        "Macro": "Macro",
        "Bắt đầu / dừng ghi": "Pornește / oprește înregistrarea",
        "Phát lại": "Redă",
        "Phát nhiều lần…": "Redă de mai multe ori…",
        "Phát đến cuối tài liệu": "Redă până la sfârșitul documentului",
        "Chạy trên mọi tab": "Rulează pe toate filele",
        "Hủy macro đang chạy": "Oprește macroul în curs",
        "Lưu macro…": "Salvează macroul…",
        "Macro đã lưu…": "Macrouri salvate…",
        "Help": "Ajutor",
        "Trợ giúp GEditor": "Ajutor GEditor",
        "Giới thiệu tính năng": "Prezentarea funcțiilor",
        "Di cư từ Notepad++": "Trecerea de la Notepad++",
        "Tìm": "Caută",
        "Thay bằng": "Înlocuiește cu",
        "Kế": "Următorul",
        "Trước": "Anteriorul",
        "Đếm": "Numără",
        "Đóng": "Închide",
        "Kiểm theo JSON Schema…": "Validează după o schemă JSON…",
        "Chọn tệp JSON Schema": "Alegeți un fișier de schemă JSON",
        "Không thấy lỗi nào theo schema này.": "Nicio problemă față de această schemă.",
        "JSON Schema": "Schemă JSON",
        "Kiểm cú pháp đồ thị": "Verifică sintaxa grafului",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Format de graf nerecunoscut — este nevoie de extensia .dot, .gv, .cypher, .ttl sau .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Nu am găsit erori de sintaxă %@ (verificarea nu este exhaustivă).",
        "Cú pháp %@": "sintaxă %@",
        "không phải một đối tượng JSON": "nu este un obiect JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Minerit de text (n-grame, TF-IDF)",
        "Tài liệu rỗng.": "Documentul este gol.",
        "Không rút được từ khoá nào.": "Nu s-au putut extrage cuvinte-cheie.",
        "Từ khoá": "Cuvinte-cheie",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=cuvânt-cheie|few=cuvinte-cheie|other=de cuvinte-cheie} · %d {one=jeton|few=jetoane|other=de jetoane} · %d {one=document|few=documente|other=de documente}",
        "Tô lên tài liệu": "Marchează în document",
        "Đánh dấu entity từ danh sách…": "Marchează entități dintr-o listă…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Alegeți o listă de entități (CSV sau JSON)",
        "Không đọc được danh sách entity.": "Lista de entități nu a putut fi citită.",
        "Danh sách entity rỗng.": "Lista de entități este goală.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Nicio entitate găsită în document (%d încărcate).",
        "%d lần xuất hiện · %@": "%d {one=apariție|few=apariții|other=de apariții} · %@",
        "Chuyển đổi tri thức…": "Convertește cunoștințe…",
        "Chuyển đổi: %@ → %@": "Conversie: %@ → %@",
        "Không chuyển đổi được.": "Conversia nu a reușit.",
        "Xem trước cắt chunk…": "Previzualizează fragmentarea…",
        "Cỡ cố định 800B, chồng 100B": "Fix 800 B, suprapunere 100 B",
        "Theo câu (≤ 800B)": "După propoziție (≤ 800 B)",
        "Theo heading Markdown": "După titlurile Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Document gol — niciun fragment.",
        "%d chunk · trung bình %d B · %@": "%d {one=fragment|few=fragmente|other=de fragmente} · %d B în medie · %@",
        "Xuất JSONL": "Exportă JSONL",
        "Chunk JSONL": "JSONL de fragmente",
        "Mở triple/edge dạng bảng": "Deschide tripletele/muchiile ca tabel",
        "Bảng triple": "Tabel de triplete",
        "Tài liệu này không có dòng triple nào.": "Acest document nu are linii de triplete.",
        "Không đọc được triple nào — dòng %d: %@": "Nu s-au putut citi triplete — linia %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "S-au citit %1$d {one=triplet|few=triplete|other=de triplete} · s-au sărit %2$d {one=linie deformată|few=linii deformate|other=de linii deformate} (prima: linia %3$d)",
        "Trùng lặp mờ theo cột…": "Duplicate aproximative după coloană…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Duplicate aproximative — coloana „%1$@”: %2$d {one=grup candidat|few=grupuri candidate|other=de grupuri candidate}",
        "Gộp": "Contopește",
        "Giống": "Potrivire",
        "Các giá trị trong cụm": "Valorile din grup",
        "Gộp về": "Contopește în",
        "Gộp các cụm đã chọn": "Contopește grupurile selectate",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Niciun grup selectat — Contopirea nu va schimba nimic. Aplicația nu contopește niciodată singură.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%1$d {one=grup selectat|few=grupuri selectate|other=de grupuri selectate} · %2$d {one=rând se va schimba|few=rânduri se vor schimba|other=de rânduri se vor schimba} · UN singur pas de anulare",
        "Không quét được cột này.": "Această coloană nu a putut fi scanată.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Coloana „%@” nu are grupuri de duplicate aproximative.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Niciun grup contopit — documentul este neschimbat.",
        "Khử trùng lặp mờ · cột %@": "Deduplicare aproximativă · coloana %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "S-au contopit %1$d {one=grup|few=grupuri|other=de grupuri} · %2$d {one=celulă modificată|few=celule modificate|other=de celule modificate}",
        "Báo cáo làm sạch": "Raport de curățare",
        "# Báo cáo làm sạch — %@\n\n": "# Raport de curățare — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Aplicate (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Niciun pas aplicat încă._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Profilul datelor\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d {one=coloană|few=coloane|other=de coloane} · %2$d {one=rând|few=rânduri|other=de rânduri} · scanate în %3$.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Coloană | Tip | Goale | Distincte | Minim | Maxim | Medie |\n",
        "\n### Giá trị bất thường\n\n": "\n### Valori aberante\n\n",
        "hàng %d: %@": "rândul %d: %@",
        "- cột «%@» — %d ô: %@\n": "- coloana „%1$@” — %2$d {one=celulă|few=celule|other=de celule}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Rămase (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Nu a mai rămas nicio constatare._\n",
        "- cột «%@»: %@\n": "- coloana „%1$@”: %2$@\n",
        "Cắt khoảng trắng khi lưu": "Taie spațiile la salvare",
        "Chuẩn hóa xuống dòng": "Normalizează sfârșiturile de linie",
        "trước đó": "anterior",
        "Không mở lại được thư mục «%@» của phiên trước": "Dosarul „%@” din sesiunea anterioară nu a putut fi redeschis",
        " (và %d file khác)": " (și încă %d {one=fișier|few=fișiere|other=de fișiere})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%1$d {one=filă nu a putut fi redeschisă|few=file nu au putut fi redeschise|other=de file nu au putut fi redeschise}: %2$@%3$@ — fișierele nu mai sunt unde erau.",
        "Không đọc được nội dung từ ống dẫn": "Nu s-a putut citi intrarea din conductă",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Spațiile de la capătul liniei vor fi tăiate la fiecare salvare",
        "Không cắt khoảng trắng khi lưu nữa": "Nu mai tăiem spațiile la salvare",
        "Chưa đặt tên.txt": "Fără titlu.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Conversia codificării va pierde caractere",
        "Vẫn lưu": "Salvează oricum",
        "Tài liệu có thay đổi chưa lưu": "Documentul are modificări nesalvate",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Închiderea fără salvare le va pierde.",
        "Bỏ thay đổi": "Renunță la modificări",
        "Đi tới dòng": "Mergi la linia",
        "Tài liệu có %d dòng.": "Documentul are %d {one=linie|few=linii|other=de linii}.",
        "Số dòng": "Numărul liniei",
        "Đi tới": "Mergi",
        "Diễn giải lại theo…": "Reinterpretează ca…",
        "Chuyển đổi sang…": "Convertește în…",
        "Không diễn giải lại được": "Reinterpretarea nu a reușit",
        "Bảng mã %@ không chứa hết ký tự": "%@ nu poate reprezenta fiecare caracter",
        "Vẫn chọn": "Aleg oricum",
        "Cột %d": "Coloana %d",
        "Cột %d: %@": "Coloana %1$d: %2$@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Coloane ascunse: %1$@ (%2$d) — se restaurează din meniul contextual al antetului",
        "Hiện lại: %@": "Arată din nou: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Coloana %@ a fost ascunsă — coloana este intactă în fișier",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Sortat după %@ %@ · doar la afișare",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Sortat: %@ %@ (doar la afișare)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ rânduri se potrivesc — căutarea continuă…",
        "%d / %d dòng khớp": "%1$d / %2$d {one=rând se potrivește|few=rânduri se potrivesc|other=de rânduri se potrivesc}",
        "Không tìm thấy lỗi trong %d hàng": "Nicio problemă în %d {one=rând|few=rânduri|other=de rânduri}",
        "%d hàng lệch số cột": "%d {one=rând|few=rânduri|other=de rânduri} cu număr greșit de coloane",
        "%d ô sai kiểu dữ liệu": "%d {one=celulă|few=celule|other=de celule} cu tip de date greșit",
        " (đã dừng ở %d lỗi đầu)": " (ne-am oprit la primele %d {one=problemă|few=probleme|other=de probleme})",
        "   —   kiểu nhận ra: ": "   —   tipuri detectate: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Rândul %1$d, coloana %2$@: „%3$@” nu este %4$@",
        "Column Editor — %d dòng": "Editor de coloane — %d {one=linie|few=linii|other=de linii}",
        "Phát hiện": "Constatări",
        "Hồ sơ dữ liệu": "Profilul datelor",
        "Hồ sơ dữ liệu — đang quét…": "Profilul datelor — se scanează…",
        "Lưu công thức…": "Salvează rețeta…",
        "Xuất báo cáo": "Exportă raportul",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Niciun grup aplicat încă · fiecare grup este un pas de anulare",
        "quá nhiều giá trị": "prea multe valori",
        "hay gặp: ": "cele mai frecvente: ",
        "Giá trị điền vào ô thiếu": "Valoarea cu care se umplu golurile",
        "Áp dụng": "Aplică",
        "Không dựng được bản xem trước": "Nu s-a putut construi o previzualizare",
        "· giữ nguyên, không đọc được ·": "· păstrat ca atare, neinterpretabil ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Convertește coloana în ISO 8601 (AAAA-LL-ZZ)",
        "Quy ước số cho cả cột": "Convenția numerică pentru toată coloana",
        "Làm gì với ô thiếu": "Ce se face cu golurile",
        "Chuẩn hóa về ISO 8601": "Normalizează la ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Citește celulele ambigue cu ZIUA prima (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Citește celulele ambigue cu LUNA prima (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Sari peste celulele ambigue, repară doar pe cele sigure",
        "Về Việt/Âu (1.234,56)": "Spre stilul vietnamez/european (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Spre stilul anglo-american (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Spre stilul anglo-american, fără grupare (1234.56)",
        "Điền một giá trị mặc định…": "Umple cu o valoare implicită…",
        "Điền xuôi — lấy giá trị phía trên": "Umple în jos — ia valoarea de deasupra",
        "Điền ngược — lấy giá trị phía dưới": "Umple în sus — ia valoarea de dedesubt",
        "Xóa hàng có ô thiếu ở cột này": "Șterge rândurile cu gol în această coloană",
        "Cắt khoảng trắng hai đầu": "Taie spațiile de la ambele capete",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Taie la ambele capete și comprimă spațiile interioare",
        "Pivot…": "Tabel pivot…",
        "Nguồn…": "Surse…",
        "Pivot — gộp theo cột": "Pivot — grupare după coloană",
        "Hàng (gộp nhóm)": "Rânduri (grupare după)",
        "Giá trị": "Valori",
        "+ Hàng": "+ Rând",
        "+ Giá trị": "+ Valoare",
        "Xoá hết": "Șterge tot",
        "Đưa vào ô truy vấn": "Pune în caseta de interogare",
        "Chọn cột để dựng câu truy vấn.": "Alegeți coloanele pentru a construi interogarea.",
        "Không đọc được tên cột của bảng này.": "Numele coloanelor acestui tabel nu au putut fi citite.",
        "Nguồn dữ liệu của truy vấn": "Sursele de date ale interogării",
        "«%@» — tài liệu đang mở": "„%@” — documentul deschis",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ fișierul s-a schimbat de la înregistrare",
        "Thêm file…": "Adaugă fișier…",
        "Bỏ hết": "Elimină tot",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Nu s-a putut deriva un nume de tabel din „%@” — redenumiți fișierul.",
        "Tổng": "Sumă",
        "Trung bình": "Medie",
        "Nhỏ nhất": "Minim",
        "Lớn nhất": "Maxim",
        "Đếm khác nhau": "Număr de valori distincte",
        "Biểu đồ": "Grafic",
        "Xuất PNG": "Exportă PNG",
        "Xuất SVG": "Exportă SVG",
        "Bảng này không có cột số nào để vẽ.": "Acest tabel nu are nicio coloană numerică de reprezentat grafic.",
        "Không dựng được ảnh PNG.": "Imaginea PNG nu a putut fi construită.",
        "Kết quả truy vấn": "Rezultatul interogării",
        "Đã lưu %@": "S-a salvat %@",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Grafic %1$@ pentru „%2$@” — %3$d {one=punct|few=puncte|other=de puncte}, valori de la %4$@ la %5$@",
        "Cột": "Bare",
        "Đường": "Linie",
        "Phân bố": "Histogramă",
        "Phân tán": "Dispersie",
        "Hộp": "Cutie",
        "CSV: chất lượng dữ liệu…": "CSV: calitatea datelor…",
        "Chất lượng dữ liệu": "Calitatea datelor",
        "Xuất vi phạm ra tab mới": "Exportă încălcările într-o filă nouă",
        "Mức": "Nivel",
        "Luật": "Regulă",
        "Vi phạm": "Încălcări",
        "Tỷ lệ": "Rată",
        "đạt": "trecut",
        "lỗi": "eroare",
        "cảnh báo": "avertisment",
        "hỏng": "defect",
        "Đã đánh dấu %d dòng vi phạm": "S-au marcat %d {one=linie care încalcă regulile|few=linii care încalcă regulile|other=de linii care încalcă regulile}",
        "Xu hướng": "Evoluție",
        "Lúc chấm": "Punctat la",
        "Số hàng": "Rânduri",
        "Lệch": "Diferență",
        "Luật trượt": "Reguli căzute",
        "Điểm chất lượng": "Punctajul calității",
        "Điểm theo thời gian": "Punctajul în timp",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Nu există încă istoric — fiecare punctare adaugă ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "câte o linie în fișierul „.history.jsonl” de lângă reguli.",
        "%d mốc trong lịch sử": "%d {one=punct|few=puncte|other=de puncte} în istoric",
        " · %d dòng KHÔNG đọc được": " · %d {one=linie ilizibilă|few=linii ilizibile|other=de linii ilizibile}",
        " · chọn hai dòng để so": " · selectați două rânduri pentru comparație",
        "điểm %+.1f": "punctaj %+.1f",
        "không chiều nào tụt": "nicio dimensiune nu a scăzut",
        "tụt: ": "au scăzut: ",
        "%d luật mới trượt: %@": "%1$d {one=regulă căzută nou|few=reguli căzute nou|other=de reguli căzute nou}: %2$@",
        "số hàng %+d": "rânduri %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (și încă %d {one=avertisment|few=avertismente|other=de avertismente} în fila Evoluție)",
        "Không sửa tự động được: ": "Nicio reparare automată: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Deschide unealta de curățare potrivită, apoi punctează din nou imediat.",
        "Xử lý giá trị thiếu…": "Tratează valorile lipsă…",
        "Chuẩn hóa ngày…": "Normalizează datele calendaristice…",
        "Khử trùng lặp…": "Elimină duplicatele…",
        "Thay thế…": "Înlocuiește…",
        "Xem các dòng sai": "Arată rândurile vinovate",
        "Không tìm thấy cột «%@» trong bảng này.": "Coloana „%@” nu se află în acest tabel.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplicatele au fost eliminate — „%1$@” este acum unică. Punctaj: %2$.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplicatele au fost eliminate, dar „%1$@” mai are %2$d {one=rând duplicat|few=rânduri duplicate|other=de rânduri duplicate} (erau %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "acele rânduri au aceeași CHEIE, dar nu și restul liniei, așa că trebuie să vă uitați și să alegeți ",
        "giữ hàng nào.": "pe care îl păstrați.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Nu s-a putut citi nicio valoare care încalcă această regulă.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {one=valoare greșită|few=valori greșite|other=de valori greșite} în coloana „%2$@” — completați la Înlocuiește, apoi previzualizați",
        "Đã chấm lại: %.0f/100": "Punctat din nou: %.0f/100",
        "Xem trước báo cáo": "Previzualizarea raportului",
        "Tham số…": "Parametri…",
        "Xuất HTML…": "Exportă HTML…",
        "In / PDF…": "Tipărește / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%1$d {one=bloc a rulat|few=blocuri au rulat|other=de blocuri au rulat} · %2$d {one=bloc A CĂZUT|few=blocuri AU CĂZUT|other=de blocuri AU CĂZUT}",
        "%d khối chạy được": "%d {one=bloc a rulat|few=blocuri au rulat|other=de blocuri au rulat}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · DATE ÎNVECHITE — fișierul sursă s-a schimbat; reconstruiți",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Previzualizarea raportului are nevoie de un document .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Nicio sursă de date găsită — declarați „source: file.csv” în frontmatter.",
        "Không dựng được báo cáo.": "Raportul nu a putut fi construit.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Acest raport nu declară niciun parametru în frontmatter.",
        "Tham số báo cáo": "Parametrii raportului",
        "Dựng lại": "Reconstruiește",
        "Đã xuất %@": "S-a exportat %@",
        "Báo cáo: xem trước": "Raport: previzualizare",
        "Báo cáo: sinh loạt…": "Raport: generare în lot…",
        "không phải tài liệu .greport.md": "nu este un document .greport.md",
        "không phân tích được báo cáo": "raportul nu a putut fi analizat",
        "không tìm được dữ liệu nguồn": "datele sursă nu au putut fi găsite",
        "không đọc được danh sách tham số": "lista de parametri nu a putut fi citită",
        "Sinh loạt cần tài liệu đuôi .%@": "Generarea în lot are nevoie de un document .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Alegeți o listă de parametri (CSV sau JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Alegeți un dosar pentru %d {one=raport|few=rapoarte|other=de rapoarte}",
        "[%d/%d] %@": "[%1$d/%2$d] %3$@",
        "thiếu tham số ": "parametri lipsă ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "indică chiar fișierul sursă — refuzăm să îl suprascriem",
        "%d khối HỎNG": "%d {one=bloc A CĂZUT|few=blocuri AU CĂZUT|other=de blocuri AU CĂZUT}",
        "Sinh loạt xong: %d tệp · %d hỏng": "Lot terminat: %1$d {one=fișier|few=fișiere|other=de fișiere} · %2$d căzute",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=set de parametri nu a putut fi construit|few=seturi de parametri nu au putut fi construite|other=de seturi de parametri nu au putut fi construite} — vedeți rezumatul",
        "Sơ đồ Mermaid: xem trước": "Diagramă Mermaid: previzualizare",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagramă Mermaid: inserează un șablon…",
        "Sơ đồ Mermaid: định dạng lại": "Diagramă Mermaid: reformatează",
        "Nền trong suốt": "Fundal transparent",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Acest Mac nu poate rasteriza diagrama în PNG — este nevoie de macOS 13. Exportul SVG funcționează în continuare.",
        "Lưu PNG %@…": "Salvează PNG %@…",
        "Lưu SVG…": "Salvează SVG…",
        "Chép ảnh vào clipboard": "Copiază imaginea în clipboard",
        "Màu thương hiệu…": "Culorile mărcii…",
        "Màu thương hiệu cho sơ đồ": "Culorile mărcii pentru diagrame",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Fiecare câmp este o culoare #rrggbb. Se salvează în „themes/mermaid-brand.json” — copiați-l pe alt Mac.",
        "Màu chính": "Culoarea principală",
        "Chữ trên nút": "Textul de pe noduri",
        "Viền": "Chenar",
        "Đường nối": "Legături",
        "Nền khi xuất ảnh": "Fundalul la export",
        "Lưu và chèn %%{init}%% vào tài liệu": "Salvează și inserează %%{init}%% în document",
        "Đã lưu màu thương hiệu": "Culorile mărcii au fost salvate",
        "Đã chép ảnh sơ đồ vào clipboard": "Imaginea diagramei a fost copiată în clipboard",
        "Đã lưu %@ — %@": "S-a salvat %1$@ — %2$@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Această diagramă are deja o directivă %%{init}%% — a dumneavoastră a rămas neatinsă.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "S-a inserat %%{init}%% — diagrama își poartă acum propriile culori",
        "Chèn màu thương hiệu vào sơ đồ": "Inserează culorile mărcii în diagramă",
        "Định dạng sơ đồ Mermaid": "Reformatează diagrama Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Sursa diagramei este deja ordonată — nu e nimic de schimbat",
        "Đã định dạng lại sơ đồ": "Diagrama a fost reformatată",
        "Đã định dạng lại %d sơ đồ": "S-au reformatat %d {one=diagramă|few=diagrame|other=de diagrame}",
        "Thư viện mẫu sơ đồ": "Biblioteca de șabloane de diagrame",
        "Mẫu sơ đồ đầy đủ": "Șabloane complete de diagrame",
        "Mẩu cú pháp": "Fragmente de sintaxă",
        "Đang soạn: %@": "Se editează: %@",
        "Đã chèn mẫu «%@»": "S-a inserat șablonul „%@”",
        "Tài liệu đang ở chế độ chỉ đọc.": "Acest document este doar pentru citire.",
        "Sơ đồ Mermaid": "Diagramă Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Acest document nu are niciun bloc mermaid.",
        "Thương hiệu": "Marcă",
        "Xuất…": "Exportă…",
        "Chưa có sơ đồ nào": "Nicio diagramă încă",
        "%d sơ đồ · %@": "%d {one=diagramă|few=diagrame|other=de diagrame} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d {one=diagramă A CĂZUT|few=diagrame AU CĂZUT|other=de diagrame AU CĂZUT} — diagrama %3$d%4$@",
        ", dòng %d": ", linia %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Acest document nu are niciun bloc ```mermaid și nu este un fișier .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Nicio diagramă nu a terminat încă de randat.",
        "Không tìm thấy «%@» trong mã sơ đồ": "Nu am găsit „%@” în sursa diagramei",
        "không dựng được hàng rào chặn mạng cho WKWebView": "nu s-a putut construi blocarea rețelei pentru WKWebView",
        "Luật kết hợp": "Reguli de asociere",
        "Mỗi dòng một giỏ": "Un coș pe rând",
        "Hai cột: mã · item": "Două coloane: id · articol",
        "Dạng dữ liệu giao dịch": "Forma datelor de tranzacție",
        "Cột giỏ hàng hoặc mã giao dịch": "Coloana coșului sau coloana id-ului de tranzacție",
        "Cột item": "Coloana articolului",
        "Ký tự phân tách item": "Caracterul separator al articolelor",
        "Support tối thiểu, phần trăm": "Suport minim, procente",
        "Confidence tối thiểu, phần trăm": "Încredere minimă, procente",
        "Tách bởi:": "Împarte după:",
        "Support \u{2265}": "Suport ≥",
        "% · Confidence \u{2265}": "% · Încredere ≥",
        "Bảng luật kết hợp": "Tabelul regulilor de asociere",
        "Support": "Suport",
        "Confidence": "Încredere",
        "Lift": "Lift",
        "Leverage": "Pârghie",
        "Cảnh báo": "Atenție",
        "%d giao dịch · %d item · %d luật": "%d {one=tranzacție|few=tranzacții|other=de tranzacții} · %d {one=articol|few=articole|other=de articole} · %d {one=regulă|few=reguli|other=de reguli}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — nicio regulă nu a atins pragurile; coborâți suportul sau încrederea",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — S-A OPRIT DEVREME, tabelul este INCOMPLET",
        "%d / %d giao dịch chứa cả hai vế": "%1$d / %2$d {one=tranzacție conține|few=tranzacții conțin|other=de tranzacții conțin} ambele părți",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Forma cu două coloane are nevoie de două coloane DIFERITE.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "S-au marcat %1$d {one=rând|few=rânduri|other=de rânduri} din %2$d {one=tranzacție|few=tranzacții|other=de tranzacții} care conțin „%3$@”",
        "CSV: luật kết hợp…": "CSV: reguli de asociere…",
        "Khai phá theo nhóm": "Minerit pe grupuri",
        "Cột nhóm": "Coloana de grupare",
        "Cột giá trị": "Coloana de valori",
        "Cột thứ hai cho tương quan": "A doua coloană pentru corelație",
        "Cách xếp hạng": "Clasament",
        "Nhóm theo:": "Grupează după:",
        "Giá trị:": "Valoare:",
        "Xếp theo:": "Clasează după:",
        "Bảng xếp hạng nhóm": "Tabelul clasamentului grupurilor",
        "Nhóm": "Grup",
        "Hàng": "Rânduri",
        "Hàng rào riêng": "Prag propriu",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "diferență r",
        "Ghi chú": "Notă",
        "không đo được": "nemăsurabil",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=grup|few=grupuri|other=de grupuri} · corelație comună %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GRUP ELIMINAT|few=GRUPURI ELIMINATE|other=DE GRUPURI ELIMINATE}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Acest tabel nu are nicio coloană de text după care să grupeze.",
        "Bảng này không có cột số nào để khai phá.": "Acest tabel nu are nicio coloană numerică de exploatat.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "S-au marcat %1$d {one=rând|few=rânduri|other=de rânduri} ale grupului „%2$@”",
        "CSV: khai phá theo nhóm…": "CSV: minerit pe grupuri…",
        "\u{2194}": "↔",
        "Dự báo": "Prognoză",
        "Cột giá trị theo thời gian": "Coloana de valori în timp",
        "Mô hình dự báo": "Modelul de prognoză",
        "Số kỳ dự báo": "Numărul de perioade de prognozat",
        "Kết luận so với baseline": "Verdictul față de modelele de referință",
        "Mô hình:": "Model:",
        "Số kỳ:": "Perioade:",
        "Chu kỳ:": "Sezon:",
        "tự": "automat",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Perioada sezonieră; lăsați gol pentru detectare automată",
        "Bảng giá trị dự báo": "Tabelul valorilor prognozate",
        "Kỳ": "Perioadă",
        "Dải 80%": "Banda de 80%",
        "Dải 95%": "Banda de 95%",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "nu se poate calcula",
        "Bảng này không có cột số nào để dự báo.": "Acest tabel nu are nicio coloană numerică de prognozat.",
        "Không dựng được dự báo cho cột này.": "Nu s-a putut construi o prognoză pentru această coloană.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Coloana „%1$@” are doar %2$d {one=valoare numerică|few=valori numerice|other=de valori numerice} — pentru prognoză sunt necesare cel puțin 4.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Seria se citește în ordinea rândurilor din fișier — fără resortare și fără a deduce o coloană de timp.\n",
        "Sai số huấn luyện": "Eroare de antrenare",
        "CSV: dự báo chuỗi thời gian…": "CSV: prognoză de serie temporală…",
        "Holt-Winters cộng": "Holt-Winters aditiv",
        "Holt-Winters nhân": "Holt-Winters multiplicativ",
        "seasonal-naive": "naiv sezonier",
        "naive": "naiv",
        "Cột đưa vào phân cụm": "Coloanele introduse în grupare",
        "Đường cong WCSS": "Curba WCSS",
        "Phân cụm": "Grupă",
        "Chuẩn hoá:": "Scalare:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Selectați cel puțin o coloană.",
        "Không đủ dữ liệu để dựng đường cong.": "Nu sunt destule date pentru a construi curba.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Cotul sugerează k = %d. WCSS scade ÎNTOTDEAUNA pe măsură ce k crește, deci aceasta este o regulă de citire a graficului, nu un criteriu statistic — uitați-vă la curbă și judecați dacă îndoitura este clară.",
        "WCSS theo k": "WCSS în funcție de k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "Distanța-k sugerează eps = %1$@ (minPts este implicit 2 × numărul de coloane = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Distanța până la al k-lea vecin",
        "Cần ít nhất 2 cột số để phân cụm.": "Pentru grupare sunt necesare cel puțin 2 coloane numerice.",
        "Cụm theo %@ và %@": "Grupe după %@ și %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — grupele au fost găsite în %d {one=dimensiune|few=dimensiuni|other=de dimensiuni}; graficul arată doar primele 2",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# zgomot (cluster_id = -1): %d {one=rând|few=rânduri|other=de rânduri}\n",
        "CSV: phân cụm…": "CSV: grupare…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Centrele grupelor (unități originale) ---\n",
        "k-means": "k-medii",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Matricea de corelație",
        "Phương pháp tương quan": "Metoda de corelație",
        "Tương quan không hàm ý nhân quả.": "Corelația nu înseamnă cauzalitate.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Cea mai puternică pereche: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Apăsați pe o celulă pentru un grafic de dispersie.",
        "Không cặp nào đo được.": "Nicio pereche nu a putut fi măsurată.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ pe %4$d {one=rând|few=rânduri|other=de rânduri}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Pentru corelație sunt necesare cel puțin 2 coloane numerice.",
        "Không đọc được cột «%@».": "Coloana „%@” nu a putut fi citită.",
        "CSV: ma trận tương quan…": "CSV: matricea de corelație…",
        "Bất thường": "Anomalii",
        "Danh sách bất thường": "Lista anomaliilor",
        "Cột:": "Coloană:",
        "Cột số cần xét": "Coloana numerică de examinat",
        "Cách:": "Metodă:",
        "Phương pháp phát hiện": "Metoda de detectare",
        "Phương pháp đã dùng": "Metoda folosită",
        "Ngưỡng": "Prag",
        "Đánh dấu": "Marchează",
        "Xuất tab mới": "Exportă într-o filă nouă",
        "Dòng": "Linie",
        "Điểm": "Scor",
        "Vì sao": "De ce",
        "nhẹ": "ușoară",
        "vừa": "moderată",
        "nặng": "severă",
        "z-score": "scor z",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%1$d / %2$d {one=rând|few=rânduri|other=de rânduri} (%3$.2f%%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Acest tabel nu are nicio coloană numerică de scanat pentru anomalii.",
        "Đã đánh dấu %d dòng bất thường": "S-au marcat %d {one=linie anormală|few=linii anormale|other=de linii anormale}",
        "CSV: tìm bất thường…": "CSV: caută anomalii…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d {one=regulă, TRECUTĂ|few=reguli, toate TRECUTE|other=de reguli, toate TRECUTE} · %2$d {one=rând|few=rânduri|other=de rânduri} · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d {one=eroare|few=erori|other=de erori} · %2$d {one=avertisment|few=avertismente|other=de avertismente} în %3$d {one=regulă|few=reguli|other=de reguli} · %4$d {one=rând|few=rânduri|other=de rânduri} · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Salvați mai întâi documentul — regulile de calitate stau lângă fișierul de date.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Niciun set de reguli încă. Creați %@ și redeschideți.",
        "Lịch sử": "Istoric",
        "Câu đã lưu": "Interogări salvate",
        "Lưu câu này…": "Salvează această interogare…",
        "Lưu câu truy vấn": "Salvează interogarea",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Dați-i un nume ca să o găsiți mai târziu. Același nume suprascrie.",
        "Ví dụ: Doanh thu theo tỉnh": "De exemplu: Venituri pe județe",
        "Chưa nhập giá trị cho tham số: %@": "Nu ați introdus nicio valoare pentru parametrul: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Modulul s-a schimbat de când l-ați aprobat — GEditor refuză să îl ruleze",
        "Chạy plugin chưa duyệt?": "Rulați un modul neaprobat?",
        "Tôi tin file này — chạy": "Am încredere în acest fișier — rulează-l",
        "KHÔNG có chữ ký": "NESEMNAT",
        "Chữ ký: %@": "Semnătură: %@",
        "Đường dẫn: %@": "Cale: %@",
        "Thay": "Înlocuiește",
        "Thay tất cả": "Înlocuiește tot",
        "Chuỗi thuần": "Text simplu",
        "Extended (\\n \\t \\xNN)": "Extins (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Expresie regulată",
        "Phân biệt hoa thường": "Ține cont de majuscule",
        "Cả từ": "Cuvânt întreg",
        "Không có kết quả": "Niciun rezultat",
        "Thử biểu thức chính quy…": "Testează expresia regulată…",
        "Chế độ Log (tô theo mức)": "Mod jurnal (culoare după nivel)",
        "Lọc log theo mức…": "Filtrează jurnalul după nivel…",
        "Chạy trên cả thư mục…": "Rulează pe tot dosarul…",
        "Lọc qua lệnh ngoài…": "Filtrează printr-o comandă…",
        "Script…": "Scripturi…",
        "Gói mở rộng…": "Pachete de extensii…",
        "Cửa sổ mới": "Fereastră nouă",
        "Tách tab ra cửa sổ mới": "Mută fila într-o fereastră nouă",
        "Chưa mở thư mục nào": "Niciun dosar deschis",
        "Tìm file trong thư mục": "Caută un fișier în dosar",
        "Lọc theo tên": "Filtrează după nume",
        "File mới…": "Fișier nou…",
        "Thư mục mới…": "Dosar nou…",
        "Đổi tên…": "Redenumește…",
        "Chuyển vào Thùng rác": "Mută la Coș",
        "Hiện trong Finder": "Arată în Finder",
        "Đang đọc cấu trúc tài liệu…": "Se citește structura documentului…",
        "file này không có hàm nào": "nicio funcție în acest fișier",
        "Không có gì khớp": "Nimic nu se potrivește",
        "Văn bản thuần": "Text simplu",
        "🔒 Chỉ đọc": "🔒 Doar citire",
        "Đang theo dõi": "Se urmărește",
        "ngắt tại cột": "încadrare la coloana",
        "Cú pháp": "Sintaxă",
        "Bấm để chèn vào ô truy vấn": "Apăsați pentru a insera în câmpul de interogare",
        "truy vấn không hợp lệ": "interogare nevalidă",
        "khóa `ten` ở gốc": "cheia `ten` de la rădăcină",
        "khóa có dấu cách": "cheie care conține un spațiu",
        "phần tử đầu": "primul element",
        "mọi phần tử": "fiecare element",
        "lát cắt": "felie",
        "hợp nhiều chỉ số": "reuniune de indici",
        "mọi khóa `gia` ở mọi tầng": "fiecare cheie `gia` la orice adâncime",
        "mọi nút": "fiecare nod",
        "lọc theo số": "filtrare după număr",
        "lọc theo có mặt": "filtrare după prezență",
        "Tới lỗi đầu tiên": "Mergi la prima problemă",
        "Cột doanh_thu là số": "Coloana doanh_thu este numerică",
        "lọc…": "filtrează…",
        "Hủy": "Renunță",
        "Thực hiện thay": "Înlocuiește",
        "xem trước": "previzualizare",
        "tương tác": "interactiv",
        "Soạn thảo": "Editare",
        "Giao diện": "Aspect",
        "Phím tắt": "Scurtături de tastatură",
        "Cỡ chữ": "Mărimea fontului",
        "Bề rộng TAB": "Lățimea tabului",
        "Thụt lề bằng TAB": "Indentare cu taburi",
        "Tự động thụt lề khi xuống dòng": "Indentare automată pe linie nouă",
        "Tô mọi kết quả tìm kiếm": "Evidențiază toate rezultatele căutării",
        "Chuẩn hóa về NFC khi lưu": "Normalizează la NFC la salvare",
        "Ngôn ngữ": "Limbă",
        "Nền": "Fundal",
        "Theo hệ thống": "Ca sistemul",
        "Sáng": "Luminos",
        "Tối": "Întunecat",
        "Theme": "Temă",
        "Dùng preset Notepad++": "Folosește presetarea Notepad++",
        "Về phím mặc định": "Revino la tastele implicite",
        "Mở file cấu hình": "Deschide fișierul de configurare",
        "Xuất theme hiện tại": "Exportă tema curentă",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Schimbarea limbii se aplică pe deplin la următoarea pornire a aplicației.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Tastele implicite revin la următoarea pornire a aplicației.",
        "Xem trước Markdown": "Previzualizare Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Randat cu motorul Markdown al sistemului: tabelele și colorarea blocurilor de cod nu sunt încă acceptate.",
        "Thử biểu thức chính quy": "Testarea expresiilor regulate",
        "Biểu thức": "Expresie",
        "Văn bản thử": "Text de probă",
        "Kết quả": "Rezultate",
        "Kết quả khớp": "Rezultatele potrivirii",
        "Biểu thức này làm gì": "Ce face această expresie",
        "Giải thích biểu thức": "Explicația expresiei",
        "Chế độ tìm kiếm": "Mod de căutare",
        "Kết quả tìm kiếm": "Rezultatele căutării",
        "Không khớp chỗ nào": "Nicio potrivire",
        " (đã cắt bớt)": " (trunchiat)",
        "Bản đồ tài liệu": "Harta documentului",
        "Thanh tab": "Bara de file",
        "Hàng tiêu đề cột": "Rândul de antet al coloanelor",
        "Không có cột nào": "Nicio coloană",
        "Cây thư mục workspace": "Arborele de fișiere al spațiului de lucru",
        "Danh sách hàm và lớp": "Lista de funcții și clase",
        "Kết quả tìm trong thư mục": "Rezultatele căutării în dosar",
        "Bảng dữ liệu CSV": "Tabel de date CSV",
        "Bàn làm sạch dữ liệu": "Banc de curățare a datelor",
        "Truy vấn JSONPath": "Interogare JSONPath",
        "Danh sách lỗi dữ liệu": "Lista problemelor de date",
        "Bộ đánh giá golden set…": "Set de aur…",
        "So với điểm ngoài (JSONL)…": "Compară cu scoruri externe (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Alegeți fișierul de scoruri externe (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Redenumește nodul selectat",
        "Gộp các node đang chọn": "Contopește nodurile selectate",
        "Tách node đang chọn": "Împarte nodul selectat",
        "Trích subgraph đang chọn ra tab mới": "Extrage subgraful selectat într-o filă nouă",
        "Không có gì để đổi": "Nimic de schimbat",
        "%@ — áp %d thay đổi?": "%1$@ — aplicați %2$d {one=modificare|few=modificări|other=de modificări}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d {one=modificare|few=modificări|other=de modificări} · Cmd-Z anulează întreg setul",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Puneți cursorul pe EXACT UN nod, apoi rulați din nou",
        "Đổi tên «%@»": "Redenumește „%@”",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Fiecare muchie și etichetă care trimite la acest nod se schimbă odată cu el.",
        "Đổi tên node": "Redenumește nodul",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Selectați DOUĂ sau mai multe noduri, apoi rulați din nou",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Forma canonică „%@” — cea mai frecventă, cea mai lungă, cu diacritice",
        "Gộp node": "Contopește nodurile",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Selectați LINIILE DE MUCHII de mutat, apoi rulați din nou",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Fiecare linie selectată trebuie să atingă EXACT UN nod comun — selectați mai multe linii de muchii",
        "Tách «%@» — chuyển %d cạnh": "Împarte „%1$@” — mută %2$d {one=muchie|few=muchii|other=de muchii}",
        "Cạnh tới: %@": "Muchii spre: %@",
        "Tách node": "Împarte nodul",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Document nesalvat — fișierul extras are nevoie de un loc lângă care să stea",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Selectați partea de graf de extras, apoi rulați din nou",
        "Gom biến thể entity → bảng duyệt": "Grupează variantele de entități → tabel de verificare",
        "Áp bảng duyệt đã sửa": "Aplică tabelul de verificare editat",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Document nesalvat — tabelul de verificare trebuie să stea lângă fișierul grafului",
        "Không tìm thấy biến thể nào để gom": "Nicio variantă de grupat",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=grup de variante|few=grupuri de variante|other=de grupuri de variante} — editați coloana „canonical”, apoi rulați „Aplică”",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Nu există încă tabelul de verificare „%@” — rulați mai întâi „Grupează variantele de entități”",
        "Bảng duyệt không đọc được: %@": "Tabelul de verificare nu a putut fi citit: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Tabelul de verificare nu are niciun rând de schimbat",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Nimic din graf nu se potrivește cu tabelul de verificare",
        "Gom biến thể entity": "Grupează variantele de entități",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "S-au aplicat %d {one=modificare|few=modificări|other=de modificări} · tabelul de alias-uri și lista de marcaje au fost scrise lângă fișier",
        "Áp %d thay đổi lên đồ thị?": "Aplicați %d {one=modificare|few=modificări|other=de modificări} asupra grafului?",
        "%d alias → dạng chuẩn.": "%d {one=alias|few=alias-uri|other=de alias-uri} → formă canonică.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "CONTOPEȘTE noduri (nu se poate anula prin retastare):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias nu se află|few=alias-uri nu se află|other=de alias-uri nu se află} în graf și au fost sărite.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Acoperire fragment ↔ entitate",
        "Xuất gói ngữ cảnh (JSONL)": "Exportă pachetul de context (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Acoperire fragment ↔ entitate ↔ graf",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=entitate|few=entități|other=de entități} · %2$d {one=fragment|few=fragmente|other=de fragmente} · %3$.0f%% dintre entități sunt menționate · %4$.0f%% dintre fragmente conțin o entitate",
        "Entity không chunk nào nhắc tới": "Entități pe care niciun fragment nu le menționează",
        "Chunk mồ côi (không chứa entity nào)": "Fragmente orfane (fără nicio entitate înăuntru)",
        "Node đồ thị không có entity đối ứng": "Noduri de graf fără entitate corespunzătoare",
        "không có": "niciuna",
        "Phương pháp": "Metodă",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Nu s-a putut construi corespondența fragment ↔ entitate",
        "Chấm sức khoẻ đồ thị": "Punctează sănătatea grafului",
        "sức khoẻ đồ thị": "sănătatea grafului",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Sănătate %1$@/100 · %2$d {one=problemă|few=probleme|other=de probleme} · %3$d {one=insulă|few=insule|other=de insule} · %4$d izolate",
        "Lai với đồ thị": "Hibrid cu graful",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: semnalul grafului este complet oprit, rezultatele coincid cu BM25 simplu",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α mare: graful doar ajustează ușor clasamentul BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α aproape de valoarea implicită 0,7: BM25 conduce, graful ajustează",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α mic: graful conduce, BM25 doar departajează",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: doar semnalul grafului; fragmentele fără entități sunt toate la egalitate",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Document nesalvat — hibridul are nevoie de un fișier de graf lângă corpus",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Niciun fișier de graf „%@” — hibridul are nevoie de el ca să aibă vreun semnal",
        "lai %.1f ms · %@": "hibrid %.1f ms · %@",
        "Thuật toán…": "Algoritm…",
        "PageRank (độ dày viền)": "PageRank (grosimea conturului)",
        "Cộng đồng (màu nền)": "Comunități (culoarea de umplere)",
        "Thành phần liên thông": "Componente conexe",
        "Xuất bảng node ra tab mới": "Exportă tabelul de noduri într-o filă nouă",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d {one=componentă|few=componente|other=de componente} · cea mai mare %2$d {one=nod|few=noduri|other=de noduri} · %3$d izolate",
        "Tài liệu này không phải đồ thị DOT": "Acest document nu este un graf DOT",
        "Không dựng được bảng node/cạnh: %@": "Tabelele de noduri/muchii nu au putut fi construite: %@",
        "%d hàng · %@": "%d {one=rând|few=rânduri|other=de rânduri} · %@",
        "Gán nhãn": "Etichetă",
        "Ghi chú (tuỳ chọn)": "Notă (opțional)",
        "Lưu record": "Salvează înregistrarea",
        "Xuất CSV": "Exportă CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Document nesalvat — setul de evaluare trebuie să stea lângă fișierul corpusului",
        "Không nạp được bộ đánh giá: %@": "Setul de evaluare nu a putut fi încărcat: %@",
        "Không lưu được: %@": "Nu s-a putut salva: %@",
        "Bộ đánh giá chưa có record nào": "Setul de evaluare nu are încă nicio înregistrare",
        "Không ghi được: %@": "Nu s-a putut scrie: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Acest document nu este un fișier .mmd, nu este DOT și nu are niciun bloc mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=nod|few=noduri|other=de noduri} · %d {one=muchie|few=muchii|other=de muchii} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagramă Mermaid: adaugă un element…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagramă Mermaid: leagă cele două elemente selectate",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagramă Mermaid: modifică eticheta elementului selectat…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagramă Mermaid: șterge elementul selectat",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagramă Mermaid: mută mesajul în sus",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagramă Mermaid: mută mesajul în jos",
        "Thêm phần tử": "Adaugă un element",
        "Thêm participant": "Adaugă un participant",
        "Thêm mục": "Adaugă o intrare",
        "Thêm mục sơ đồ": "Adaugă o intrare în diagramă",
        "Sửa mục sơ đồ": "Modifică o intrare din diagramă",
        "Xoá mục sơ đồ": "Șterge o intrare din diagramă",
        "Xoá phần tử": "Șterge elementul",
        "Sửa nhãn": "Modifică eticheta",
        "Đổi thứ tự message": "Reordonează mesajul",
        "Tên mục": "Numele intrării",
        "Mục mới": "Intrare nouă",
        "Tên mục hiện trên sơ đồ.": "Numele intrării afișat pe diagramă.",
        "Bảng thuộc tính sơ đồ": "Tabelul de proprietăți al diagramei",
        "Tài liệu này không có khối mermaid nào": "Acest document nu are niciun bloc mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identificatorul din sursa diagramei — fără spații. Eticheta se modifică mai târziu cu dublu clic.",
        "Để trống thì hiện chính định danh.": "Lăsați gol pentru a afișa chiar identificatorul.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Se schimbă doar ETICHETA afișată; identificatorul elementului rămâne același.",
        "Không rõ «%@» là phần tử nào": "Nu se poate spune care element este „%@”",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Selectați EXACT DOUĂ elemente, apoi rulați din nou",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Puneți cursorul pe EXACT UN element, apoi rulați din nou",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Selectați UN element de șters sau două elemente unite printr-o muchie",
        "Xoá «%@» và %d cạnh chạm nó?": "Ștergeți „%1$@” și cele %2$d {one=muchie care îl atinge|few=muchii care îl ating|other=de muchii care îl ating}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Nodurile de la celălalt capăt al acelor muchii se păstrează — sunt redeclarate cu etichetele lor dacă instrucțiunea de muchie era singurul loc care le declara.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Diagrama „%1$@” se editează doar ca text — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: trageți între două elemente pentru a le lega, dublu clic pentru a modifica o etichetă",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: trageți între doi participanți pentru a adăuga un mesaj; ordinea se schimbă din meniul Unelte",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: editați în tabelul de proprietăți de mai jos",
        "Soạn trực quan đã bật": "Editarea vizuală este pornită",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d {one=intrare|few=intrări|other=de intrări} — editați pe loc; fiecare celulă este un pas de anulare",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Pentru pie, un număr; pentru gantt, tot ce urmează după două puncte.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagramă Mermaid: scoate blocul într-un fișier .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagramă Mermaid: încorporează înapoi fișierul referit",
        "Tách khối sơ đồ": "Scoate blocul diagramei",
        "Nhúng khối sơ đồ": "Încorporează blocul diagramei",
        "Tách khối sơ đồ ra tệp riêng": "Scoate blocul diagramei în fișierul lui propriu",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Fișierul stă LÂNGĂ document; blocul păstrează o referință de o linie, ca editarea să se facă într-un singur loc.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Document nesalvat — fișierul diagramei are nevoie de un loc lângă care să stea",
        "Đã có tệp «%@» — chọn tên khác": "Fișierul „%@” există deja — alegeți alt nume",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "S-a scos în „%@” — blocul a păstrat o referință de o linie",
        "Mở tệp": "Deschide fișierul",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "„%@” a fost încorporat înapoi; fișierul rămâne pe disc",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Acest bloc conține o diagramă adevărată, nu o referință",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Acest bloc trimite la „%@” — deschideți acel fișier ca să îl editați",
        "Không đọc được tệp sơ đồ %@": "Fișierul diagramei nu a putut fi citit: %@",
        "Soạn trực quan": "Editare vizuală",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Trageți de la un nod la altul pentru a adăuga o muchie; dublu clic pentru a modifica o etichetă. Fiecare acțiune este un pas de anulare.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Editare vizuală: trageți între două noduri pentru a adăuga o muchie, dublu clic pentru a modifica o etichetă",
        "Soạn trực quan đã tắt": "Editarea vizuală este oprită",
        "Thêm node…": "Adaugă un nod…",
        "Thêm cạnh giữa hai node đang chọn…": "Adaugă o muchie între cele două noduri selectate…",
        "Sửa nhãn node đang chọn…": "Modifică eticheta nodului selectat…",
        "Xoá node/cạnh đang chọn": "Șterge nodul sau muchia selectată",
        "Thêm node": "Adaugă un nod",
        "Thêm cạnh": "Adaugă o muchie",
        "Sửa nhãn node": "Modifică eticheta nodului",
        "Xoá node": "Șterge nodul",
        "Xoá cạnh": "Șterge muchia",
        "Cmd-Z hoàn tác": "Cmd-Z anulează",
        "Tài liệu đang ở chế độ chỉ đọc": "Documentul este doar pentru citire",
        "Nhãn của «%@»": "Eticheta lui „%@”",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Se schimbă doar ETICHETA afișată; identificatorul nodului rămâne același.",
        "Không rõ «%@» là node nào": "Nu se poate spune care nod este „%@”",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identificatorul nodului din fișierul DOT. Eticheta se modifică mai târziu cu dublu clic pe diagramă.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Selectați EXACT DOUĂ noduri, apoi rulați din nou",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Selectați UN nod ca să ștergeți un nod sau două noduri unite printr-o muchie",
        "Xoá node «%@» và %d cạnh chạm nó?": "Ștergeți nodul „%1$@” și cele %2$d {one=muchie care îl atinge|few=muchii care îl ating|other=de muchii care îl ating}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Dacă rămân muchii suspendate, DOT recreează nodul chiar din ele — nodul tocmai șters ar reapărea la următoarea randare.",
        "Phòng thí nghiệm truy hồi BM25": "Laborator de regăsire BM25",
        "Câu hỏi — Enter để tìm": "Întrebare — apăsați Return pentru a căuta",
        "Đánh giá…": "Evaluează…",
        "Đang dựng chỉ mục": "Se construiește indexul",
        "Không chunk nào khớp": "Niciun fragment nu se potrivește",
        "kết quả trên": "rezultate din",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: fiecare termen contează O SINGURĂ dată, oricât de des ar apărea",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 mic: repetarea unui termen aproape că nu adaugă nimic",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 aproape de valoarea implicită 1,2: repetările adaugă punctaj, dar tot mai puțin",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 mare: fragmentele care repetă un termen sunt răsplătite puternic",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: lungimea este ignorată, fragmentele lungi nu sunt penalizate",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b mic: fragmentele lungi sunt penalizate doar ușor",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b aproape de valoarea implicită 0,75: fragmentele lungi sunt penalizate moderat",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: penalizare maximă pentru lungime, fragmentele scurte sunt favorizate",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: laborator de regăsire…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Document nesalvat — indexul BM25 stă lângă fișierul corpusului, deci are nevoie de o cale",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Acest fișier nu este JSONL — Laboratorul de regăsire lucrează pe corpusuri de fragmente",
        "Không dựng được chỉ mục BM25 cho tệp này": "Nu s-a putut construi un index BM25 pentru acest fișier",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Document nesalvat — este nevoie de o cale de corpus pentru a genera raportul",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Alegeți un set de evaluare (CSV sau JSONL: întrebare + id-urile fragmentelor așteptate)",
        "Đánh giá truy hồi": "Evaluarea regăsirii",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Schimbați k1, b sau k mai sus și randați din nou pentru a compara două configurații; adăugați un bloc „compare” ca să rulați două seturi de parametri alături pe același set de evaluare.",
        "Lỗi": "Erori",
        "   (%d…%d, trung bình %.0f)": "   (%1$d…%2$d, medie %3$.0f)",
        "Chế độ JSONL": "Mod JSONL",
        "Bản ghi": "Înregistrare",
        "Chi tiết": "Detaliu",
        "Bản ghi ở dòng": "Înregistrarea de la linia",
        "không phải JSON hợp lệ": "nu este JSON valid",
        "bản ghi": "înregistrări",
        "dòng trắng": "linii goale",
        "không phải đối tượng": "nu sunt obiecte",
        "bảng hiện": "tabelul arată",
        "ĐÃ HUỶ giữa chừng": "ANULAT PE PARCURS",
        "Không lọc": "Fără filtru",
        "bản ghi khớp bộ lọc": "înregistrări se potrivesc cu filtrul",
        "Đưa con nháy tới một dòng để xem bản ghi": "Mutați cursorul pe o linie ca să îi vedeți înregistrarea",
        "Không có bản ghi nào hỏng": "Nicio înregistrare deformată",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Neinspectat încă. Rulați „JSONL: inspectează fragmentele” după ce se termină verificarea.",
        "trường văn bản": "câmp de text",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHEMĂ (o presupunere — alegeți alt câmp ca să o schimbați)",
        "văn bản": "text",
        "định danh": "identificator",
        "metadata lồng": "metadate imbricate",
        "TRƯỜNG": "CÂMPURI",
        "phủ": "prezent în",
        "nhiều kiểu": "tipuri amestecate",
        "ĐỘ DÀI — ký tự": "LUNGIME — caractere",
        "ĐỘ DÀI — từ": "LUNGIME — cuvinte",
        "ĐỘ DÀI — token ước lượng": "LUNGIME — jetoane estimate",
        "RỖNG VÀ TRÙNG": "GOALE ȘI DUPLICATE",
        "chunk rỗng": "fragmente goale",
        "dòng": "linii",
        "nhóm trùng chính xác": "grupuri de duplicate exacte",
        "dòng không đọc được, không vào thống kê": "linii ilizibile, lăsate în afara statisticilor",
        "PHƯƠNG PHÁP": "METODĂ",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "„caracterele” numără scalari Unicode, nu grupuri de afișare",
        "«từ» tách theo khoảng trắng ASCII": "„cuvintele” se despart la spațiile ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "„jetoanele” folosesc segmentatorul de silabe — NU pe cel al modelului",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "„duplicat” înseamnă EXACT; cele APROAPE identice stau în blocul ```quality",
        "chunk": "fragmente",
        "JSONL: kiểm và soi chunk…": "JSONL: verifică și inspectează fragmentele…",
        "Ảnh": "Imagine",
        "PDF": "PDF",
        "Tài liệu Word": "Document Word",
        "Bảng tính Excel": "Foaie de calcul Excel",
        "Bản trình chiếu PowerPoint": "Prezentare PowerPoint",
        "File nén": "Arhivă",
        "Vừa khung": "Încadrează",
        "Chép ảnh": "Copiază imaginea",
        "Xoay": "Rotește",
        "Không đọc được ảnh «%@»": "Imaginea „%@” nu poate fi citită",
        "Đã chép ảnh vào clipboard": "Imaginea a fost copiată în clipboard",
        "Bôi vàng": "Evidențiază",
        "Gạch chân": "Subliniază",
        "Ghi chú…": "Notă…",
        "Bỏ chú thích": "Șterge adnotările",
        "Lấy chữ ra tab mới": "Extrage textul într-o filă nouă",
        "Lưu bản có chú thích…": "Salvează copia adnotată…",
        "Tìm trong PDF": "Caută în PDF",
        "Thêm": "Adaugă",
        "Trang %d/%d": "Pagina %d din %d",
        "Trang %d": "Pagina %d",
        "Kết quả %d/%d": "Potrivirea %d din %d",
        "0 kết quả": "Nicio potrivire",
        "Không đọc được PDF «%@»": "PDF-ul „%@” nu poate fi citit",
        "PDF này có mật khẩu — chưa mở được nội dung": "Acest PDF este protejat cu parolă — conținutul lui nu poate fi deschis",
        "Không thấy «%@» trong tài liệu": "„%@” nu se află în acest document",
        "Đã bôi vàng": "Evidențiat",
        "Đã gạch chân": "Subliniat",
        "Hãy bôi đen một đoạn chữ trước": "Selectați mai întâi un text",
        "Đã thêm ghi chú": "Nota a fost adăugată",
        "Trang này chưa có chú thích nào": "Această pagină nu are adnotări",
        "Đã bỏ %d chú thích trên trang này": "S-au eliminat %d {one=adnotare|few=adnotări|other=de adnotări} de pe această pagină",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Acest PDF nu are strat de text — cel mai probabil este o scanare",
        "Không ghi được tệp": "Fișierul nu poate fi scris",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Fișierul tocmai scris NU se redeschide corect — nu folosiți această copie",
        "Đã lưu %@ · %d trang": "S-a salvat %1$@ · %2$d {one=pagină|few=pagini|other=de pagini}",
        "Tên": "Nume",
        "Kích thước": "Mărime",
        "Đã nén": "Comprimat",
        "Tỉ lệ": "Raport",
        "Sửa lúc": "Modificat",
        "Mở mục đang chọn": "Deschide intrarea selectată",
        "Bung ra thư mục…": "Extrage într-un dosar…",
        "Bung vào đây": "Extrage aici",
        "%d mục": "%d {one=intrare|few=intrări|other=de intrări}",
        "giải nén ra %@": "se extinde la %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— un fișier Office este o arhivă; acestea sunt părțile din interiorul lui",
        "Đã bung %d mục": "S-au extras %d {one=intrare|few=intrări|other=de intrări}",
        "%d mục hỏng": "%d {one=intrare a eșuat|few=intrări au eșuat|other=de intrări au eșuat}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=intrare a fost REFUZATĂ|few=intrări au fost REFUZATE|other=de intrări au fost REFUZATE} — căile lor ies din dosarul de destinație",
        "Không mở được mục này": "Această intrare nu poate fi deschisă",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Încă nu se poate scrie înapoi într-un %@ — folosiți „Salvează ca…”",
        "Không có gì đổi": "Nu s-a schimbat nimic",
        "Đã ghi %d ô vào %@": "S-au scris %1$d {one=celulă|few=celule|other=de celule} în %2$@",
        "Đã ghi %d đoạn vào %@": "S-au scris %1$d {one=paragraf|few=paragrafe|other=de paragrafe} în %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Nu s-a putut scrie în fișier — originalul este neatins",
        "dựng bài": "pregătirea cazului de test",
        "Không ghi được settings.json": "settings.json nu poate fi scris",
        "Xoay trái": "Rotește la stânga",
        "Xoay phải": "Rotește la dreapta",
        "Trang lên": "Mută pagina în sus",
        "Trang xuống": "Mută pagina în jos",
        "Xoá trang…": "Șterge pagini…",
        "Xoá trang": "Șterge pagini",
        "Trích trang…": "Extrage pagini…",
        "Trích trang ra tệp mới": "Extrage paginile într-un fișier nou",
        "Gộp tệp PDF…": "Îmbină fișier PDF…",
        "Tách tệp…": "Împarte fișierul…",
        "Tách tệp PDF": "Împarte fișierul PDF",
        "Xuất ảnh…": "Exportă imagini…",
        "Xuất trang ra ảnh PNG": "Exportă paginile ca imagini PNG",
        "Hoàn tác trang": "Anulează modificarea paginii",
        "Lưu bản đã sửa…": "Salvează copia modificată…",
        "Phát": "Redă",
        "Tạm dừng": "Pauză",
        "Xem bình thường": "Vizualizare normală",
        "Chọn sheet": "Alege foaia",
        "Mở sheet": "Deschide foaia",
        "Bỏ và đổi sheet": "Renunță și schimbă foaia",
        "Bảng tính có %d sheet.": "Registrul are %d foi.",
        "Bảng tính này chỉ có một sheet: «%@»": "Acest registru are o singură foaie: „%@”",
        "Bỏ phần chưa lưu của sheet này?": "Renunțați la modificările nesalvate din această foaie?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Schimbarea foii înlocuiește toată fila. Ce nu a fost salvat cu ⌘S se pierde.",
        "Chọn tệp PDF cần gộp vào": "Alege fișierul PDF de îmbinat",
        "Chọn thư mục ghi ảnh": "Alege dosarul pentru imagini",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Alege unde se salvează. Al doilea fișier se scrie lângă acesta.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Documentul are %d pagini. Introdu paginile de șters, ex. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Documentul are %d pagini. Introdu paginile de extras, ex. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Documentul are %d pagini. Introdu paginile de exportat, ex. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Documentul are %d pagini. Introdu partea de separat, ex. 1-5; restul devine al doilea fișier.",
        "Đã xoay trang %d": "Pagina %d a fost rotită",
        "Đã xoá trang %@ · còn %d trang": "Paginile %@ au fost șterse · au rămas %d pagini",
        "Đã gộp %d trang từ «%@»": "%d pagini îmbinate din „%@”",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Împărțit în %@ (%d pagini) și %@ (%d pagini)",
        "Đã ghi %@ — %@ · %d trang": "S-a scris %@ — %@ · %d pagini",
        "Đã xuất %d ảnh vào %@": "%d imagini exportate în %@",
        "Chỉ xuất được %d/%d ảnh": "Doar %d din %d imagini au fost exportate",
        "Đã hoàn tác một thao tác trang": "S-a anulat o operație de pagină",
        "Không còn thao tác trang nào để hoàn tác": "Nu mai există operații de pagină de anulat",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Nu se pot șterge TOATE paginile — un PDF trebuie să aibă cel puțin una",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Acel interval este tot documentul — nu e nimic de separat",
        "«%@» có mật khẩu — chưa gộp được": "„%@” este protejat cu parolă — nu se poate îmbina",
        "«%@» không có trang nào": "„%@” nu are pagini",
        "Đã ở trang đầu": "Deja la prima pagină",
        "Đã ở trang cuối": "Deja la ultima pagină",
        "· đã sửa, chưa lưu": "· modificat, nesalvat",
        "Ảnh động · %d khung": "Imagine animată · %d cadre",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Document nesalvat — nu există fișier pe disc pentru vizualizare binară",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Această comandă funcționează doar cu registre Excel",
        "Không đọc được danh sách sheet": "Lista de foi nu a putut fi citită",
        "Không có sheet «%@»": "Nu există foaia „%@”",
        "Không đọc được sheet «%@»": "Foaia „%@” nu a putut fi citită",
        "Sheet «%@» · %d hàng": "Foaia „%@” · %d rânduri",
        "phần còn lại": "restul",
        "Lưu ý": "Notă",
        "Cẩn thận": "Atenție",
        "Xem thêm": "Vezi și",
        "Chép": "Copiază",
        "Đã chép": "Copiat",
        "Chép đoạn mã mẫu": "Copiază codul exemplu",
        "Tìm trong trợ giúp": "Caută în ajutor",
        "Lùi": "Înapoi",
        "Bắt đầu dùng": "Începe",
        "Không mở cửa sổ này khi khởi động nữa": "Nu afișa această fereastră la pornire",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Ajutorul nu este încă tradus în această limbă — se afișează textul vietnamez.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Mergi la offset (ex. 1F400 sau 0x1F400)",
        "Chép dòng đã chọn": "Copiază rândurile selectate",
        "Đã chép %d dòng": "%d rânduri copiate",
        "Không đọc được «%@»": "„%@” nu a putut fi citit",
        "Tệp rỗng": "Fișier gol",
        "Không đọc được offset «%@»": "Offsetul „%@” nu a putut fi citit",
        "Offset 0x%@ vượt quá cỡ tệp": "Offsetul 0x%@ depășește dimensiunea fișierului",
        "Mở bằng ứng dụng khác…": "Deschide cu altă aplicație…",
        "%d kênh": "%d canale",
        "Không phát được «%@»": "„%@” nu poate fi redat",
        "Không phát được — %@": "Nu poate fi redat — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS nu are decodor integrat pentru formatul %@ — este o limită a sistemului, nu un fișier corupt.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Poți vedea în continuare octeții în mod binar sau îl poți deschide cu o aplicație cu decodor propriu.",
        "Ký…": "Semnează…",
        "Sửa chữ…": "Editează textul…",
        "Sửa chữ": "Editează textul",
        "Vẽ đè": "Desenează deasupra",
        "Ô chưa điền": "Următorul câmp gol",
        "Xoá nội dung đã điền": "Șterge valorile completate",
        "Tệp này không có ô biểu mẫu nào": "Acest fișier nu are câmpuri de formular",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d câmpuri de formular șterse",
        "Mọi ô biểu mẫu đều đã có nội dung": "Toate câmpurile de formular sunt deja completate",
        "Còn %d ô chưa điền": "Au rămas %d câmpuri goale",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Formular completabil: %d câmpuri. Scrie direct, apoi „Salvează copia modificată…”",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Alege o imagine cu semnătura (fundal transparent arată cel mai bine)",
        "Không dựng được trang có chữ ký": "Pagina semnată nu a putut fi creată",
        "Đã chèn chữ ký vào trang %d": "Semnătura a fost inserată la pagina %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Selectează mai întâi textul de modificat",
        "Vùng chọn quá nhỏ": "Selecția este prea mică",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Textul nou este DESENAT PESTE selecție cu fontul sistemului. Textul vechi este acoperit, nu șters — poate fi extras în continuare, deci nu este redactare.",
        "Không dựng được trang đã sửa": "Pagina modificată nu a putut fi creată",
        "Đã vẽ đè chữ mới lên trang %d": "Textul nou a fost desenat peste pagina %d",
        "Đổi chế độ View / Code": "Comută Vizualizare / Cod",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Încă nu există vizualizare arbore pentru JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Încă nu există vizualizare diagramă în filă",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Încă nu există vizualizare schiță pentru PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Acest fișier are un singur mod de afișare",
        "%d nút": "%d noduri",
        "Không dựng được cây: %@": "Arborele nu a putut fi construit: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Documentul este prea mare pentru arbore — folosește modul Cod",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Nu s-au putut construi paginile acestui fișier \u{2014} folosește modul Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Diapozitivele sunt construite din text; imaginile și aranjarea originale nu sunt încă desenate.",
        "Vừa ngang": "Potrivire pe lățime",
        "Thu nhỏ trang": "Micșorează pagina",
        "Phóng to trang": "Mărește pagina",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "Nu s-a găsit \u{201E}%@\u{201D} în document",
        "Chỗ khớp %d/%d": "Potrivirea %d din %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Niciun text selectat pe pagină.",
        "%d ký tự": "%d {one=caracter|other=caractere}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Deschide fișierele direct în modul View când există",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· ANULAT la jumătate — tabelul este incomplet",
        "Chế độ hiển thị": "Mod de afișare",
        "Đổi giữa View và Code (⌥⌘V)": "Comută între View și Code (⌥⌘V)",
        "Trang tài liệu": "Paginile documentului",
        "Chữ đã dựng": "Text paginat",
        "Trang bảng tính": "Paginile foii de calcul",
        "Sơ đồ": "Diagramă",
        "Cây khoá–giá trị": "Arbore cheie–valoare",
        "Bộ phát": "Player",
        "Danh sách mục": "Listă de intrări",
        "Báo cáo đã dựng": "Raport generat",
        "Tô theo mức": "Colorat după nivel",
        "Trang slide": "Paginile diapozitivelor",
        "Dàn ý": "Schiță",
        "Lưu rồi dựng lại": "Salvează și reconstruiește",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Arată copia DE PE DISC — modificările nesalvate nu sunt aici.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Sistemul nu a putut construi vizualizatorul — folosiți modul Code.",
        "Lưu tệp trước khi xem trang.": "Salvați fișierul înainte de a-i vedea paginile.",
        "Đang ở chế độ Code": "Acum în modul Code",
        "Đang ở chế độ View": "Acum în modul View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Vedeți sursa — apăsați pentru modul View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "În modul View — apăsați pentru a reveni la sursă (⌥⌘V)",
        "Tín hiệu: %@": "Semnal: %@",
        "Lý do: %@": "Motiv: %@",
        "Chi tiết: %@": "Detaliu: %@",
        "Mở báo cáo": "Deschide raportul",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor s-a închis brusc la %@ — deschideți raportul pentru a-l citi; nu se trimite nimic.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligaturi — dezactivate, fiecare caracter rămâne în celula lui",
        "Chế độ CSV": "Mod CSV",
        "Dấu phân tách": "Separator",
        "Tự nhận diện": "Detectează automat",
        "Dấu phân tách: %@": "Separator: %@",
        "Theo đuôi tệp": "După extensia fișierului",
        "%d dấu cách": "%d {one=spațiu|few=spații|other=de spații}",
        "Tài liệu đang sửa được": "Acest document poate fi editat",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Doar citire: fișierul este urmărit — opriți urmărirea pentru a edita",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Doar citire: fișierul de pe disc nu poate fi scris",
        "Đã mở khoá — tài liệu sửa được": "Deblocat — documentul poate fi editat din nou",
        "Nhân bản tệp": "Duplică fișierul",
        "Đổi tên tệp…": "Redenumește fișierul…",
        "Chuyển tệp tới…": "Mută fișierul în…",
        "XML: đánh giá XPath…": "XML: evaluează XPath…",
        "Đánh giá XPath": "Evaluează XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "De exemplu: //comanda/rand[2]/@cod · //*[@tip='A'] · count(//rand)",
        "Đánh giá": "Evaluează",
        "XPath không đọc được: %@": "Acest XPath nu poate fi citit: %@",
        "XPath «%@» không khớp node nào": "XPath „%@” nu a găsit niciun nod",
        "XPath «%@» — %d node": "XPath „%@” — %d {one=nod|few=noduri|other=de noduri}",
        "XPath «%@»: %d node": "XPath „%@”: %d {one=nod|few=noduri|other=de noduri}",
        "Lưu tệp trước khi nhân bản.": "Salvați fișierul înainte de a-l duplica.",
        "Không nhân bản được": "Duplicarea nu a reușit",
        "Đã nhân bản thành %@": "Duplicat ca %@",
        "Lưu tệp trước khi đổi tên.": "Salvați fișierul înainte de a-l redenumi.",
        "Đổi tên tệp": "Redenumește fișierul",
        "Tên hiện tại: %@": "Nume actual: %@",
        "Đổi tên": "Redenumește",
        "Tên tệp không hợp lệ": "Acest nume de fișier nu este valid",
        "Đã có tệp tên %@ ở đó": "Există deja un fișier numit %@ acolo",
        "Lưu tệp trước khi chuyển.": "Salvați fișierul înainte de a-l muta.",
        "Chuyển tới": "Mută aici",
        "Thư mục đích đã có tệp tên %@": "Dosarul de destinație are deja un fișier numit %@",
        "Không chuyển được tệp": "Fișierul nu a putut fi mutat",
        "Đã chuyển tới %@": "Mutat în %@",
        "Bảng mã:": "Codificare:",
        "Xuống dòng:": "Sfârșit de linie:",
        "Riêng cho %@": "Doar pentru %@",
        "    %d — dùng TAB": "    %d — tabulatori",
        "    %d — dùng dấu cách": "    %d — spații",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Elimină regula proprie, folosește setarea generală",
        "%@: thụt lề %d %@": "%@: indentare %d %@",
        "TAB": "tabulatori",
        "dấu cách": "spații",
        "Xuất": "Exportă",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Deschide rezultatele ca filă de text — salvați cu ⌘S",
        "Lượt tìm trước đó": "Căutări anterioare",
        "«%@» — %d kết quả": "„%@” — %d {one=rezultat|few=rezultate|other=de rezultate}",
        "Kết quả tìm «%@»": "Rezultatele căutării „%@”",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtrează numele — de ex. *.csv;*.log (gol: orice fișier text)",
        "Thư mục %@ không có file văn bản nào": "Dosarul %@ nu are fișiere text",
        "Không tệp nào trong %@ khớp «%@»": "Niciun fișier din %@ nu se potrivește cu „%@”",
        "%d byte · %d dòng": "%d octeți · %d {one=linie|few=linii|other=de linii}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d octeți · %d {one=linie|few=linii|other=de linii} — prea mare pentru a număra caractere și cuvinte",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d octeți · %d {one=caracter|few=caractere|other=de caractere} · %d {one=cuvânt|few=cuvinte|other=de cuvinte} · %d {one=linie|few=linii|other=de linii}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Acest document are %d {one=linie|few=linii|other=de linii}, %d octeți. Scrieți un număr de linie, „linie,coloană” sau „@octet”.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "„%@” nu poate fi citit — scrieți un număr de linie, „linie,coloană” sau „@octet”",
    ]
}
