import Foundation

/// Bảng dịch tiếng Na Uy (bokmål). Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let nb: [String: String] = [
        "Bản đã lưu…": "Lagrede versjoner…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Dette dokumentet er aldri blitt lagret — ingen historikk",
        "Chưa có bản đã lưu nào trước đó": "Ingen tidligere lagrede versjoner",
        "Không đọc được bản ấy": "Den versjonen kan ikke leses",
        "Khôi phục bản đã lưu": "Gjenopprett den lagrede versjonen",
        "XML: kiểm theo DTD/XSD…": "XML: valider mot DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Denne Macen har ikke libxml2, så XSD-validering er ikke tilgjengelig.",
        "Chọn lược đồ XSD để kiểm": "Velg et XSD-skjema å validere mot",
        "Hợp lệ theo": "Gyldig etter",
        "Plugin chạy xong, không đổi gì": "Tillegget avsluttet uten å endre noe",
        "Chưa cài plugin native nào": "Ingen innebygde tillegg er installert",
        "Gỡ plugin này": "Fjern dette tillegget",
        "Gỡ plugin này?": "Fjerne dette tillegget?",
        "Gỡ": "Fjern",
        "Cài plugin native…": "Installer et innebygd tillegg…",
        "Mở thư mục plugin": "Åpne tilleggsmappen",
        "Chọn file .dylib của plugin native": "Velg .dylib-filen til tillegget",
        "Đã cài:": "Installert:",
        "Đã gỡ:": "Fjernet:",
        "Plugin native…": "Innebygde tillegg…",
        "Chỉ nhận file .dylib.": "Bare .dylib-filer godtas.",
        "Đã có một plugin trùng tên:": "Et tillegg med samme navn er allerede installert:",
        "Không chép được plugin:": "Tillegget kan ikke kopieres:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Innebygde tillegg finnes bare i den direkte nedlastingen, ikke i App Store-versjonen.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Hjelpeprosessen for tillegg ble ikke funnet.",
        "Không khởi động được tiến trình phụ:": "Hjelpeprosessen kan ikke startes:",
        "Tiến trình plugin đã dừng giữa chừng.": "Prosessen til tillegget stoppet halvveis.",
        "Plugin không trả lời kịp — đã dừng nó.": "Tillegget svarte ikke i tide — det ble stoppet.",
        "Plugin trả lời sai giao thức:": "Tillegget svarte med en feilformet melding:",
        "Plugin báo lỗi:": "Tillegget meldte om en feil:",
        "Về GEditor": "Om GEditor",
        "Cài đặt…": "Innstillinger…",
        "Thoát GEditor": "Avslutt GEditor",
        "File": "Arkiv",
        "Tab mới": "Ny fane",
        "Đóng tab": "Lukk fanen",
        "Tab kế": "Neste fane",
        "Tab trước": "Forrige fane",
        "Tài liệu mới": "Nytt dokument",
        "Mở…": "Åpne…",
        "Mở thư mục làm Workspace…": "Åpne en mappe som arbeidsområde…",
        "Mở gần đây": "Åpne nylige",
        "Lưu": "Lagre",
        "Lưu thành…": "Lagre som…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Fjern mellomrom sist på linjen ved lagring",
        "Theo dõi file (tail -f)": "Følg filen (tail -f)",
        "In…": "Skriv ut…",
        "Mở lại tab vừa đóng": "Åpne den lukkede fanen igjen",
        "Chưa có file nào": "Ingen filer",
        "Xoá danh sách": "Tøm listen",
        "Edit": "Rediger",
        "Hoàn tác": "Angre",
        "Làm lại": "Gjør om",
        "Cắt": "Klipp ut",
        "Sao chép": "Kopier",
        "Dán": "Lim inn",
        "Lịch sử clipboard…": "Utklippshistorikk…",
        "Column Editor…": "Kolonneredigering…",
        "Chọn lần kế tiếp": "Merk neste treff",
        "Chọn tất cả": "Merk alt",
        "Nhân đôi dòng": "Dupliser linjen",
        "Xóa dòng": "Slett linjen",
        "Comment dòng": "Kommenter ut linjen",
        "Chưa chép gì trong phiên này": "Ingenting er kopiert i denne økten",
        "Xoá lịch sử": "Tøm historikken",
        "Search": "Søk",
        "Tìm…": "Finn…",
        "Tìm và thay…": "Finn og erstatt…",
        "Tìm trong thư mục…": "Søk i en mappe…",
        "Thay trong thư mục…": "Erstatt i en mappe…",
        "Kết quả kế": "Neste treff",
        "Kết quả trước": "Forrige treff",
        "Đi tới dòng…": "Gå til linje…",
        "Nhảy tới ngoặc khớp": "Gå til den samsvarende parentesen",
        "Đánh dấu mọi dòng khớp…": "Merk alle linjer som samsvarer…",
        "Đảo dấu": "Snu merkingene",
        "Bỏ mọi dấu": "Fjern alle merkinger",
        "Chép dòng đã đánh dấu": "Kopier de merkede linjene",
        "Xóa dòng đã đánh dấu": "Slett de merkede linjene",
        "Chỉ giữ dòng đã đánh dấu": "Behold bare de merkede linjene",
        "Lines": "Linjer",
        "Sắp xếp A→Z": "Sorter A→Å",
        "Sắp xếp Z→A": "Sorter Å→A",
        "Sắp xếp tự nhiên": "Naturlig sortering",
        "Khử trùng lặp": "Fjern duplikater",
        "Đảo thứ tự dòng": "Snu rekkefølgen på linjene",
        "Dời dòng lên": "Flytt linjen opp",
        "Dời dòng xuống": "Flytt linjen ned",
        "Ghép dòng": "Slå sammen linjer",
        "Tách dòng theo độ dài…": "Del linjer etter lengde…",
        "Tách dòng theo ký tự…": "Del linjer etter tegn…",
        "Xóa dòng rỗng": "Slett tomme linjer",
        "Nén dòng trống liên tiếp": "Slå sammen påfølgende tomme linjer",
        "Cắt khoảng trắng cuối dòng": "Fjern mellomrom sist på linjen",
        "Tab → Space": "Tabulator → mellomrom",
        "Space → Tab": "Mellomrom → tabulator",
        "HOA": "STORE BOKSTAVER",
        "thường": "små bokstaver",
        "Chữ Hoa Đầu Từ": "Stor Forbokstav I Hvert Ord",
        "Chữ hoa đầu câu": "Stor forbokstav i setningen",
        "Đảo hoa/thường": "sNU sTORE/sMÅ",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: velg ark…",
        "Xem dạng bảng / văn bản": "Veksle mellom tabell- og tekstvisning",
        "Xóa cột…": "Slett kolonne…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Valider data (antall kolonner · typer)",
        "Bàn làm sạch dữ liệu…": "Arbeidsbenk for datarensing…",
        "Chạy công thức làm sạch…": "Kjør en renseoppskrift…",
        "Chuyển đổi…": "Konverter…",
        "Đổi dấu phân tách…": "Bytt skilletegn…",
        "Xuất sang JSON…": "Eksporter til JSON…",
        "Format": "Format",
        "Bảng mã…": "Tegnkoding…",
        "Xuống dòng…": "Linjeslutt…",
        "Chuẩn hóa Unicode…": "Normaliser Unicode…",
        "JSON: định dạng lại": "JSON: formater",
        "JSON: thu gọn một dòng": "JSON: press sammen til én linje",
        "JSON: sắp xếp khóa": "JSON: sorter nøkler",
        "JSON: truy vấn JSONPath…": "JSON: JSONPath-spørring…",
        "CSV: truy vấn SQL…": "CSV: SQL-spørring…",
        "Truy vấn SQL": "SQL-spørring",
        "Đang chạy…": "Kjører…",
        "Xuất ra tab mới": "Eksporter til en ny fane",
        "Tài liệu rỗng — không có bảng để truy vấn": "Tomt dokument — ingen tabell å spørre mot",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Ikke en CSV-tabell — første linje har bare én kolonne",
        "Không đọc được câu truy vấn": "Spørringen kan ikke leses",
        "Không kiểm được câu truy vấn": "Spørringen kan ikke kontrolleres",
        "Vàng (mặc định)": "Gul (standard)",
        "Xanh dương": "Blå",
        "Xanh lá": "Grønn",
        "Vàng đất": "Oker",
        "Tím": "Lilla",
        "Hồng": "Rosa",
        "Xanh ngọc": "Turkis",
        "Cam": "Oransje",
        "Xám lam": "Skifer",
        "Văn bản": "Tekst",
        "Dãy số": "Tallrekke",
        "Dãy ngày": "Datorekke",
        "Chữ HOA (hex)": "STORE BOKSTAVER (heksadesimalt)",
        "Bắt đầu": "Start",
        "Bước": "Steg",
        "Đệm 0 tới": "Fyll ut med nuller til",
        "Hệ": "Grunntall",
        "Ngày đầu": "Første dato",
        "Định dạng": "Format",
        "Chèn": "Sett inn",
        "Huỷ": "Avbryt",
        "Chuyển đổi định dạng": "Konverter formatet",
        "Xem trước 5 hàng đầu": "Forhåndsvis de 5 første radene",
        "Tạo tab mới": "Åpne i en ny fane",
        "Lưu ra file…": "Lagre til en fil…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Resultatet åpnes i en ny, ulagret fane. Det opprinnelige dokumentet røres ikke.",
        "Chạy trên tài liệu này": "Kjør på dette dokumentet",
        "Chạy trên thư mục…": "Kjør på en mappe…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Hele oppskriften er ETT angre-trinn. Filen på disken røres ikke før du lagrer.",
        "tắt": "av",
        "không thấy cột": "kolonnen ble ikke funnet",
        "sẵn sàng": "klar",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "den fortsetter å oppta en prosessorkjerne til appen avsluttes.",
        "Script không trả về gì": "Skriptet returnerte ingenting",
        "Không dựng được máy JavaScript": "JavaScript-motoren kan ikke opprettes",
        "Lỗi JavaScript không rõ": "Ukjent JavaScript-feil",
        "Bảng": "Tabell",
        "Áp sắp xếp vào file": "Bruk sorteringen på filen",
        "Chuyển đổi ▾": "Konverter ▾",
        "Xuất dòng khớp": "Eksporter radene som samsvarer",
        "Ẩn cột này": "Skjul denne kolonnen",
        "Đổi tên tiêu đề…": "Gi overskriften nytt navn…",
        "Chèn cột trống bên trái": "Sett inn en tom kolonne til venstre",
        "Chèn cột trống bên phải": "Sett inn en tom kolonne til høyre",
        "Xóa cột này khỏi file…": "Slett denne kolonnen fra filen…",
        "Phải còn ít nhất một cột đang hiện": "Minst én kolonne må forbli synlig",
        "Đang sắp xếp…": "Sorterer…",
        "Trở về thứ tự trong file": "Tilbake til rekkefølgen i filen",
        "trăm hàng đầu": "de første hundre radene",
        "chọn cột": "velge kolonner",
        "đặt tên cột kết quả": "gi navn til en resultatkolonne",
        "lọc theo chữ": "filtrere på tekst",
        "ô rỗng": "tomme celler",
        "ghép điều kiện": "kombinere vilkår",
        "đếm hàng": "telle rader",
        "gộp nhóm": "gruppere og oppsummere",
        "nhỏ nhất, lớn nhất": "minimum, maksimum",
        "sắp xếp và cắt": "sortere og begrense",
        "tên cột có dấu cách": "kolonnenavn med mellomrom",
        "Truy vấn bị dừng giữa chừng": "Spørringen ble avbrutt",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Ikke støttet: JOIN · underspørring · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · vindusfunksjoner",
        "XML: định dạng lại": "XML: formater",
        "XML: thu gọn một dòng": "XML: press sammen til én linje",
        "XML: kiểm cú pháp": "XML: kontroller syntaksen",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: kontroller gjentatte nøkler og innrykk",
        "View": "Vis",
        "Ẩn/hiện sidebar (Function List)": "Vis/skjul sidepanelet (funksjonslisten)",
        "Ẩn/hiện bản đồ tài liệu": "Vis/skjul dokumentkartet",
        "Gấp / mở khối tại con nháy": "Fold sammen / fold ut blokken ved markøren",
        "Gấp tất cả": "Fold sammen alt",
        "Bỏ gấp tất cả": "Fold ut alt",
        "Gấp theo cấp": "Fold sammen etter nivå",
        "Cấp %d": "Nivå %d",
        "Đã gấp %d khối ở cấp %d": "%1$d {one=blokk foldet|other=blokker foldet} sammen på nivå %2$d",
        "Tài liệu này chỉ sâu %d cấp": "Dette dokumentet er bare %d {one=nivå|other=nivåer} dypt",
        "mermaid: không đọc được bản kê": "mermaid: manifestet kan ikke leses",
        "Kiểm tra bản cập nhật…": "Se etter oppdateringer…",
        "Kiểm tra bản cập nhật": "Se etter oppdateringer",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store-versjoner oppdateres via Mac App Store, ikke via GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Denne utgaven har ingen signeringsnøkkel for oppdateringer og kan derfor ikke se etter dem.",
        "Phóng to chữ": "Forstørr teksten",
        "Thu nhỏ chữ": "Forminsk teksten",
        "Cỡ chữ gốc": "Virkelig størrelse",
        "Chia đôi theo chiều dọc": "Del loddrett",
        "Chia đôi theo chiều ngang": "Del vannrett",
        "Bỏ chia đôi": "Lukk delingen",
        "Mở tab này ở nửa kia": "Åpne denne fanen i den andre ruten",
        "Nhảy sang nửa kia": "Gå til den andre ruten",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Linjebryting (av / vindu / kolonne)",
        "Ngắt dòng tại cột…": "Bryt ved kolonne…",
        "Đánh dấu dòng này": "Merk denne linjen",
        "Dấu kế tiếp": "Neste merke",
        "Dấu trước đó": "Forrige merke",
        "Màu đánh dấu…": "Farge på merkene…",
        "Hiện tất cả ký tự ẩn": "Vis alle usynlige tegn",
        "  Khoảng trắng": "  Mellomrom",
        "  Tab": "  Tabulatorer",
        "  Xuống dòng": "  Linjeslutt",
        "  NBSP · zero-width · điều khiển": "  NBSP · nullbredde · styretegn",
        "Xem nhị phân": "Binærvisning",
        "Chế độ CSV (tô màu theo cột)": "CSV-modus (kolonner i farger)",
        "Macro": "Makro",
        "Bắt đầu / dừng ghi": "Start / stopp opptaket",
        "Phát lại": "Spill av",
        "Phát nhiều lần…": "Spill av flere ganger…",
        "Phát đến cuối tài liệu": "Spill av til slutten av dokumentet",
        "Chạy trên mọi tab": "Kjør på alle faner",
        "Hủy macro đang chạy": "Avbryt makroen som kjører",
        "Lưu macro…": "Lagre makroen…",
        "Macro đã lưu…": "Lagrede makroer…",
        "Help": "Hjelp",
        "Trợ giúp GEditor": "GEditor-hjelp",
        "Giới thiệu tính năng": "Funksjonsoversikt",
        "Di cư từ Notepad++": "Bytte fra Notepad++",
        "Tìm": "Finn",
        "Thay bằng": "Erstatt med",
        "Kế": "Neste",
        "Trước": "Forrige",
        "Đếm": "Tell",
        "Đóng": "Lukk",
        "Kiểm theo JSON Schema…": "Valider mot et JSON-skjema…",
        "Chọn tệp JSON Schema": "Velg en JSON-skjemafil",
        "Không thấy lỗi nào theo schema này.": "Ingen problemer ble funnet etter dette skjemaet.",
        "JSON Schema": "JSON-skjema",
        "Kiểm cú pháp đồ thị": "Kontroller syntaksen til grafen",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Grafformatet ble ikke gjenkjent — det trengs endelsen .dot, .gv, .cypher, .ttl eller .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Ingen %@-syntaksfeil ble funnet (kontrollen er ikke uttømmende).",
        "Cú pháp %@": "%@-syntaks",
        "không phải một đối tượng JSON": "er ikke et JSON-objekt",
        "Khai phá văn bản (n-gram, TF-IDF)": "Tekstutvinning (n-gram, TF-IDF)",
        "Tài liệu rỗng.": "Dokumentet er tomt.",
        "Không rút được từ khoá nào.": "Ingen nøkkelord kunne hentes ut.",
        "Từ khoá": "Nøkkelord",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=nøkkelord|other=nøkkelord} · %d {one=token|other=tokener} · %d {one=dokument|other=dokumenter}",
        "Tô lên tài liệu": "Merk i dokumentet",
        "Đánh dấu entity từ danh sách…": "Merk entiteter fra en liste…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Velg en entitetsliste (CSV eller JSON)",
        "Không đọc được danh sách entity.": "Entitetslisten kan ikke leses.",
        "Danh sách entity rỗng.": "Entitetslisten er tom.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Ingen entiteter ble funnet i dokumentet (%d lest inn).",
        "%d lần xuất hiện · %@": "%d {one=forekomst|other=forekomster} · %@",
        "Chuyển đổi tri thức…": "Konverter kunnskap…",
        "Chuyển đổi: %@ → %@": "Konvertering: %@ → %@",
        "Không chuyển đổi được.": "Det kunne ikke konverteres.",
        "Xem trước cắt chunk…": "Forhåndsvisning av oppdelingen…",
        "Cỡ cố định 800B, chồng 100B": "Fast størrelse 800 B, overlapp 100 B",
        "Theo câu (≤ 800B)": "Etter setning (≤ 800 B)",
        "Theo heading Markdown": "Etter Markdown-overskrift",
        "Tài liệu rỗng — không có chunk nào.": "Tomt dokument — ingen biter.",
        "%d chunk · trung bình %d B · %@": "%d {one=bit|other=biter} · i snitt %d B · %@",
        "Xuất JSONL": "Eksporter JSONL",
        "Chunk JSONL": "JSONL for bitene",
        "Mở triple/edge dạng bảng": "Åpne tripler/kanter som tabell",
        "Bảng triple": "Tripeltabell",
        "Tài liệu này không có dòng triple nào.": "Dette dokumentet har ingen tripellinje.",
        "Không đọc được triple nào — dòng %d: %@": "Ingen tripel kunne leses — linje %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%1$d {one=trippel lest|other=tripler lest} · %2$d {one=feilaktig linje|other=feilaktige linjer} hoppet over (den første: linje %3$d)",
        "Trùng lặp mờ theo cột…": "Uskarpe duplikater per kolonne…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Uskarpe duplikater — kolonnen «%1$@»: %2$d {one=kandidatgruppe|other=kandidatgrupper}",
        "Gộp": "Slå sammen",
        "Giống": "Treff",
        "Các giá trị trong cụm": "Verdier i gruppen",
        "Gộp về": "Slå sammen til",
        "Gộp các cụm đã chọn": "Slå sammen de valgte gruppene",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Ingen gruppe er valgt — å trykke «Slå sammen» endrer INGENTING. Appen slår aldri sammen av seg selv.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=gruppe valgt|other=grupper valgt} · %d {one=rad vil|other=rader vil} bli endret · ETT angre-trinn",
        "Không quét được cột này.": "Denne kolonnen kunne ikke gjennomsøkes.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Kolonnen «%@» har ingen grupper med uskarpe duplikater.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Ingen gruppe ble slått sammen — dokumentet er uendret.",
        "Khử trùng lặp mờ · cột %@": "Uskarp duplikatrensing · kolonnen %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=gruppe slått|other=grupper slått} sammen · %d {one=celle endret|other=celler endret}",
        "Báo cáo làm sạch": "Rapport om rensing",
        "# Báo cáo làm sạch — %@\n\n": "# Rapport om rensing — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Brukt (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Ingen trinn er brukt._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Dataprofil\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d {one=kolonne|other=kolonner} · %2$d {one=rad|other=rader} · gjennomsøkt på %3$.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Kolonne | Type | Tomme | Unike | Min | Maks | Snitt |\n",
        "\n### Giá trị bất thường\n\n": "\n### Avvikende verdier\n\n",
        "hàng %d: %@": "rad %d: %@",
        "- cột «%@» — %d ô: %@\n": "- kolonnen «%1$@» — %2$d {one=celle|other=celler}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Igjen (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Ingen observasjoner igjen._\n",
        "- cột «%@»: %@\n": "- kolonnen «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Fjern mellomrom ved lagring",
        "Chuẩn hóa xuống dòng": "Normaliser linjesluttene",
        "trước đó": "forrige",
        "Không mở lại được thư mục «%@» của phiên trước": "Mappen «%@» fra forrige økt kunne ikke åpnes igjen",
        " (và %d file khác)": " (og %d {one=fil|other=filer} til)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%d {one=fane kunne|other=faner kunne} ikke åpnes igjen: %@%@ — filene ligger ikke lenger på samme sted.",
        "Không đọc được nội dung từ ống dẫn": "Inndata fra røret kunne ikke leses",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Mellomrom sist på linjen fjernes ved hver lagring",
        "Không cắt khoảng trắng khi lưu nữa": "Mellomrom fjernes ikke lenger ved lagring",
        "Chưa đặt tên.txt": "Uten navn.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Å konvertere tegnkodingen gjør at tegn går tapt",
        "Vẫn lưu": "Lagre likevel",
        "Tài liệu có thay đổi chưa lưu": "Dokumentet har ulagrede endringer",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Å lukke uten å lagre forkaster dem.",
        "Bỏ thay đổi": "Forkast endringene",
        "Đi tới dòng": "Gå til linje",
        "Tài liệu có %d dòng.": "Dokumentet har %d {one=linje|other=linjer}.",
        "Số dòng": "Linjenummer",
        "Đi tới": "Gå",
        "Diễn giải lại theo…": "Tolk om som…",
        "Chuyển đổi sang…": "Konverter til…",
        "Không diễn giải lại được": "Det kunne ikke tolkes om",
        "Bảng mã %@ không chứa hết ký tự": "%@ kan ikke gjengi alle tegn",
        "Vẫn chọn": "Velg likevel",
        "Cột %d": "Kolonne %d",
        "Cột %d: %@": "Kolonne %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Skjulte kolonner: %@ (%d) — hent dem tilbake fra kontekstmenyen på overskriftsraden",
        "Hiện lại: %@": "Vis igjen: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Kolonnen %@ er skjult — den ligger urørt i filen",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Sortert etter %@ %@ · bare visning",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Sortert: %@ %@ (bare visning)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ rader samsvarer — søker videre…",
        "%d / %d dòng khớp": "%d / %d {one=rad samsvarer|other=rader samsvarer}",
        "Không tìm thấy lỗi trong %d hàng": "Ingen problemer ble funnet i %d {one=rad|other=rader}",
        "%d hàng lệch số cột": "%d {one=rad|other=rader} med feil antall kolonner",
        "%d ô sai kiểu dữ liệu": "%d {one=celle|other=celler} med feil datatype",
        " (đã dừng ở %d lỗi đầu)": " (stoppet ved de %d {one=første problemet|other=første problemene})",
        "   —   kiểu nhận ra: ": "   —   gjenkjente typer: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Rad %1$d, kolonnen %2$@: «%3$@» er ikke %4$@",
        "Column Editor — %d dòng": "Kolonneredigering — %d {one=linje|other=linjer}",
        "Phát hiện": "Observasjoner",
        "Hồ sơ dữ liệu": "Dataprofil",
        "Hồ sơ dữ liệu — đang quét…": "Dataprofil — gjennomsøker…",
        "Lưu công thức…": "Lagre oppskriften…",
        "Xuất báo cáo": "Eksporter rapporten",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Ingen gruppe er brukt · hver gruppe er ett angre-trinn",
        "quá nhiều giá trị": "for mange verdier",
        "hay gặp: ": "vanligst: ",
        "Giá trị điền vào ô thiếu": "Verdi å fylle tomme celler med",
        "Áp dụng": "Bruk",
        "Không dựng được bản xem trước": "Det gikk ikke å bygge en forhåndsvisning",
        "· giữ nguyên, không đọc được ·": "· latt stå som det er, kan ikke tydes ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Konverter kolonnen til ISO 8601 (ÅÅÅÅ-MM-DD)",
        "Quy ước số cho cả cột": "Tallkonvensjon for hele kolonnen",
        "Làm gì với ô thiếu": "Hva som skal gjøres med tomme celler",
        "Chuẩn hóa về ISO 8601": "Normaliser til ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Les tvetydige celler med DAGEN først (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Les tvetydige celler med MÅNEDEN først (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Hopp over tvetydige celler, rett bare de sikre",
        "Về Việt/Âu (1.234,56)": "Til vietnamesisk/europeisk (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Til angloamerikansk (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Til angloamerikansk, uten tusenskilletegn (1234.56)",
        "Điền một giá trị mặc định…": "Fyll med en standardverdi…",
        "Điền xuôi — lấy giá trị phía trên": "Fyll nedover — ta verdien over",
        "Điền ngược — lấy giá trị phía dưới": "Fyll oppover — ta verdien under",
        "Xóa hàng có ô thiếu ở cột này": "Slett rader med tom celle i denne kolonnen",
        "Cắt khoảng trắng hai đầu": "Fjern mellomrom i begge ender",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Fjern i begge ender og press sammen mellomrom inni",
        "Pivot…": "Pivottabell…",
        "Nguồn…": "Kilder…",
        "Pivot — gộp theo cột": "Pivottabell — grupper etter kolonne",
        "Hàng (gộp nhóm)": "Rader (gruppering)",
        "Giá trị": "Verdier",
        "+ Hàng": "+ Rad",
        "+ Giá trị": "+ Verdi",
        "Xoá hết": "Tøm alt",
        "Đưa vào ô truy vấn": "Legg i spørringsfeltet",
        "Chọn cột để dựng câu truy vấn.": "Velg kolonner for å bygge spørringen.",
        "Không đọc được tên cột của bảng này.": "Kolonnenavnene i denne tabellen kunne ikke leses.",
        "Nguồn dữ liệu của truy vấn": "Datakildene til spørringen",
        "«%@» — tài liệu đang mở": "«%@» — det åpne dokumentet",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ filen er endret siden den ble registrert",
        "Thêm file…": "Legg til fil…",
        "Bỏ hết": "Fjern alle",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Det gikk ikke å utlede et tabellnavn av «%@» — gi filen nytt navn.",
        "Tổng": "Sum",
        "Trung bình": "Gjennomsnitt",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Maks",
        "Đếm khác nhau": "Antall unike",
        "Biểu đồ": "Diagram",
        "Xuất PNG": "Eksporter PNG",
        "Xuất SVG": "Eksporter SVG",
        "Bảng này không có cột số nào để vẽ.": "Denne tabellen har ingen numerisk kolonne å tegne.",
        "Không dựng được ảnh PNG.": "PNG-bildet kunne ikke bygges.",
        "Kết quả truy vấn": "Spørringsresultat",
        "Đã lưu %@": "%@ lagret",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "%1$@-diagram for «%2$@» — %3$d {one=punkt|other=punkter}, verdier fra %4$@ til %5$@",
        "Cột": "Søyle",
        "Đường": "Linje",
        "Phân bố": "Histogram",
        "Phân tán": "Punkt",
        "Hộp": "Boks",
        "CSV: chất lượng dữ liệu…": "CSV: datakvalitet…",
        "Chất lượng dữ liệu": "Datakvalitet",
        "Xuất vi phạm ra tab mới": "Eksporter bruddene til en ny fane",
        "Mức": "Nivå",
        "Luật": "Regel",
        "Vi phạm": "Brudd",
        "Tỷ lệ": "Andel",
        "đạt": "bestått",
        "lỗi": "feil",
        "cảnh báo": "advarsel",
        "hỏng": "ødelagt",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=linje med brudd er merket|other=linjer med brudd er merket}",
        "Xu hướng": "Utvikling",
        "Lúc chấm": "Vurdert",
        "Số hàng": "Rader",
        "Lệch": "Differanse",
        "Luật trượt": "Regler som ikke er bestått",
        "Điểm chất lượng": "Kvalitetsskår",
        "Điểm theo thời gian": "Skår over tid",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Ingen historikk ennå — hver vurdering legger til ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "én linje i filen «.history.jsonl» ved siden av reglene.",
        "%d mốc trong lịch sử": "%d {one=punkt|other=punkter} i historikken",
        " · %d dòng KHÔNG đọc được": " · %d {one=linje KAN IKKE LESES|other=linjer KAN IKKE LESES}",
        " · chọn hai dòng để so": " · velg to rader å sammenligne",
        "điểm %+.1f": "skår %+.1f",
        "không chiều nào tụt": "ingen dimensjon falt",
        "tụt: ": "falt: ",
        "%d luật mới trượt: %@": "%d {one=regel som nylig ikke er bestått|other=regler som nylig ikke er bestått}: %@",
        "số hàng %+d": "rader %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (og %d {one=advarsel|other=advarsler} til i fanen Utvikling)",
        "Không sửa tự động được: ": "Ingen automatisk retting: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Åpner det rette verktøyet på rensebenken og vurderer så på nytt med én gang.",
        "Xử lý giá trị thiếu…": "Håndter manglende verdier…",
        "Chuẩn hóa ngày…": "Normaliser datoer…",
        "Khử trùng lặp…": "Fjern duplikater…",
        "Thay thế…": "Erstatt…",
        "Xem các dòng sai": "Vis de feilaktige radene",
        "Không tìm thấy cột «%@» trong bảng này.": "Kolonnen «%@» finnes ikke i denne tabellen.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplikatene er fjernet — «%@» er nå unik. Skår: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplikatene er fjernet, men «%1$@» har fortsatt %2$d {one=gjentatt rad|other=gjentatte rader} (før: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "de radene deler NØKKEL, men ikke hele raden, så du må se etter og velge ",
        "giữ hàng nào.": "hvilken du beholder.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Det gikk ikke å lese en eneste verdi som bryter denne regelen.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {one=feilaktig verdi|other=feilaktige verdier} i kolonnen «%2$@» — fyll ut Erstatt og trykk Forhåndsvis",
        "Đã chấm lại: %.0f/100": "Vurdert på nytt: %.0f/100",
        "Xem trước báo cáo": "Forhåndsvisning av rapporten",
        "Tham số…": "Parametere…",
        "Xuất HTML…": "Eksporter HTML…",
        "In / PDF…": "Skriv ut / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=blokk kjørte|other=blokker kjørte} · %d {one=blokk MISLYKTES|other=blokker MISLYKTES}",
        "%d khối chạy được": "%d {one=blokk kjørte|other=blokker kjørte}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · UTDATERTE DATA — kildefilen er endret; bygg på nytt",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Rapportforhåndsvisning krever et .%@-dokument",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Ingen datakilde ble funnet — oppgi «source: fil.csv» i frontmatter.",
        "Không dựng được báo cáo.": "Rapporten kunne ikke bygges.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Denne rapporten oppgir ingen parametere i frontmatter.",
        "Tham số báo cáo": "Parametere for rapporten",
        "Dựng lại": "Bygg på nytt",
        "Đã xuất %@": "%@ eksportert",
        "Báo cáo: xem trước": "Rapport: forhåndsvisning",
        "Báo cáo: sinh loạt…": "Rapport: masseproduksjon…",
        "không phải tài liệu .greport.md": "er ikke et .greport.md-dokument",
        "không phân tích được báo cáo": "rapporten kunne ikke tolkes",
        "không tìm được dữ liệu nguồn": "kildedataene ble ikke funnet",
        "không đọc được danh sách tham số": "parameterlisten kunne ikke leses",
        "Sinh loạt cần tài liệu đuôi .%@": "Masseproduksjon krever et .%@-dokument",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Velg en parameterliste (CSV eller JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Velg en mappe for %d {one=rapport|other=rapporter}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "manglende parametere ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "peker på selve kildefilen — nekter å skrive over",
        "%d khối HỎNG": "%d {one=blokk MISLYKTES|other=blokker MISLYKTES}",
        "Sinh loạt xong: %d tệp · %d hỏng": "Kjøringen er ferdig: %d {one=fil|other=filer} · %d mislyktes",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=parametersett|other=parametersett} kunne ikke bygges — se oppsummeringen",
        "Sơ đồ Mermaid: xem trước": "Mermaid-diagram: forhåndsvisning",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid-diagram: sett inn mal…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid-diagram: formater på nytt",
        "Nền trong suốt": "Gjennomsiktig bakgrunn",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Denne Macen kan ikke gjøre diagrammet om til PNG — macOS 13 kreves. SVG-eksport virker fortsatt.",
        "Lưu PNG %@…": "Lagre PNG %@…",
        "Lưu SVG…": "Lagre SVG…",
        "Chép ảnh vào clipboard": "Kopier bildet til utklippstavlen",
        "Màu thương hiệu…": "Merkefarger…",
        "Màu thương hiệu cho sơ đồ": "Merkefarger for diagrammer",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Hvert felt er en farge av typen #rrggbb. Lagres i «themes/mermaid-brand.json» — kan kopieres til en annen Mac.",
        "Màu chính": "Hovedfarge",
        "Chữ trên nút": "Tekst på noder",
        "Viền": "Ramme",
        "Đường nối": "Forbindelser",
        "Nền khi xuất ảnh": "Bakgrunn ved eksport",
        "Lưu và chèn %%{init}%% vào tài liệu": "Lagre og sett inn %%{init}%% i dokumentet",
        "Đã lưu màu thương hiệu": "Merkefargene er lagret",
        "Đã chép ảnh sơ đồ vào clipboard": "Diagrambildet er kopiert til utklippstavlen",
        "Đã lưu %@ — %@": "%@ lagret — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Dette diagrammet har allerede et %%{init}%%-direktiv — ditt lates urørt.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% satt inn — diagrammet bærer nå sine egne farger",
        "Chèn màu thương hiệu vào sơ đồ": "Sett inn merkefargene i diagrammet",
        "Định dạng sơ đồ Mermaid": "Formater Mermaid-diagrammet på nytt",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Diagramkilden er allerede ryddig — det er ingenting å endre",
        "Đã định dạng lại sơ đồ": "Diagrammet er formatert på nytt",
        "Đã định dạng lại %d sơ đồ": "%d {one=diagram formatert|other=diagrammer formatert} på nytt",
        "Thư viện mẫu sơ đồ": "Bibliotek med diagrammaler",
        "Mẫu sơ đồ đầy đủ": "Fullstendige diagrammaler",
        "Mẩu cú pháp": "Syntaksbiter",
        "Đang soạn: %@": "Redigeres: %@",
        "Đã chèn mẫu «%@»": "Malen «%@» er satt inn",
        "Tài liệu đang ở chế độ chỉ đọc.": "Dette dokumentet er skrivebeskyttet.",
        "Sơ đồ Mermaid": "Mermaid-diagram",
        "Tài liệu chưa có khối mermaid nào.": "Dette dokumentet har ingen mermaid-blokk.",
        "Thương hiệu": "Merke",
        "Xuất…": "Eksporter…",
        "Chưa có sơ đồ nào": "Ingen diagrammer ennå",
        "%d sơ đồ · %@": "%d {one=diagram|other=diagrammer} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d {one=diagram MISLYKTES|other=diagrammer MISLYKTES} — diagram %3$d%4$@",
        ", dòng %d": ", linje %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Dette dokumentet har ingen ```mermaid-blokk og er heller ikke en .mmd-fil.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Ingen diagram er ferdig tegnet ennå.",
        "Không tìm thấy «%@» trong mã sơ đồ": "«%@» ble ikke funnet i diagramkilden",
        "không dựng được hàng rào chặn mạng cho WKWebView": "nettverkssperren for WKWebView kunne ikke bygges",
        "Luật kết hợp": "Assosiasjonsregler",
        "Mỗi dòng một giỏ": "Én kurv per rad",
        "Hai cột: mã · item": "To kolonner: id · vare",
        "Dạng dữ liệu giao dịch": "Formen på transaksjonsdataene",
        "Cột giỏ hàng hoặc mã giao dịch": "Kurvkolonne eller kolonne med transaksjons-id",
        "Cột item": "Varekolonne",
        "Ký tự phân tách item": "Tegn som skiller varer",
        "Support tối thiểu, phần trăm": "Minste support, prosent",
        "Confidence tối thiểu, phần trăm": "Minste confidence, prosent",
        "Tách bởi:": "Skilt av:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "Tabell over assosiasjonsregler",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Merk",
        "%d giao dịch · %d item · %d luật": "%d {one=transaksjon|other=transaksjoner} · %d {one=vare|other=varer} · %d {one=regel|other=regler}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — ingen regel nådde tersklene; senk support eller confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — STOPPET FOR TIDLIG, tabellen er UFULLSTENDIG",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transaksjon inneholder|other=transaksjoner inneholder} begge sider",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Tokolonneformen krever to FORSKJELLIGE kolonner.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%1$d {one=rad merket|other=rader merket} i %2$d {one=transaksjon|other=transaksjoner} som inneholder «%3$@»",
        "CSV: luật kết hợp…": "CSV: assosiasjonsregler…",
        "Khai phá theo nhóm": "Gruppevis utvinning",
        "Cột nhóm": "Grupperingskolonne",
        "Cột giá trị": "Verdikolonne",
        "Cột thứ hai cho tương quan": "Andre kolonne for korrelasjonen",
        "Cách xếp hạng": "Rangeringsmåte",
        "Nhóm theo:": "Grupper etter:",
        "Giá trị:": "Verdi:",
        "Xếp theo:": "Ranger etter:",
        "Bảng xếp hạng nhóm": "Tabell over gruppenes rangering",
        "Nhóm": "Gruppe",
        "Hàng": "Rader",
        "Hàng rào riêng": "Egen terskel",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r-differanse",
        "Ghi chú": "Notat",
        "không đo được": "kan ikke måles",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=gruppe|other=grupper} · samlet referansekorrelasjon %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GRUPPE UTELATT|other=GRUPPER UTELATT}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Denne tabellen har ingen tekstkolonne å gruppere etter.",
        "Bảng này không có cột số nào để khai phá.": "Denne tabellen har ingen numerisk kolonne å utvinne av.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%1$d {one=rad|other=rader} i gruppen «%2$@» er merket",
        "CSV: khai phá theo nhóm…": "CSV: gruppevis utvinning…",
        "\u{2194}": "↔",
        "Dự báo": "Prognose",
        "Cột giá trị theo thời gian": "Verdikolonne over tid",
        "Mô hình dự báo": "Prognosemodell",
        "Số kỳ dự báo": "Antall perioder som skal forutsies",
        "Kết luận so với baseline": "Vurdering mot referansemodellene",
        "Mô hình:": "Modell:",
        "Số kỳ:": "Perioder:",
        "Chu kỳ:": "Sesong:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Sesongperiode; la stå tom for automatisk gjenkjenning",
        "Bảng giá trị dự báo": "Tabell over forutsagte verdier",
        "Kỳ": "Periode",
        "Dải 80%": "80 %-bånd",
        "Dải 95%": "95 %-bånd",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "kan ikke beregnes",
        "Bảng này không có cột số nào để dự báo.": "Denne tabellen har ingen numerisk kolonne å forutsi.",
        "Không dựng được dự báo cho cột này.": "Det gikk ikke å bygge en prognose for denne kolonnen.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Kolonnen «%1$@» har bare %2$d {one=numerisk verdi|other=numeriske verdier} — det kreves minst 4 til en prognose.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Rekken leses nøyaktig i radrekkefølgen i filen — uten omsortering og uten å utlede en tidskolonne.\n",
        "Sai số huấn luyện": "Treningsfeil",
        "CSV: dự báo chuỗi thời gian…": "CSV: tidsserieprognose…",
        "Holt-Winters cộng": "Holt-Winters additiv",
        "Holt-Winters nhân": "Holt-Winters multiplikativ",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Kolonner som inngår i klyngingen",
        "Đường cong WCSS": "WCSS-kurve",
        "Phân cụm": "Klynge",
        "Chuẩn hoá:": "Skalering:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Velg minst én kolonne.",
        "Không đủ dữ liệu để dựng đường cong.": "Det er for lite data til å bygge kurven.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Albuen antyder k = %d. WCSS synker ALLTID når k vokser, så dette er en måte å lese diagrammet på og ikke et statistisk kriterium — se på kurven og vurder om knekken er tydelig.",
        "WCSS theo k": "WCSS etter k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k-avstanden antyder eps = %1$@ (minPts er som standard 2 × antallet kolonner = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Avstand til den k-te naboen",
        "Cần ít nhất 2 cột số để phân cụm.": "Klynging krever minst 2 numeriske kolonner.",
        "Cụm theo %@ và %@": "Klynger etter %@ og %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — klyngene ble funnet i %d {one=dimensjon|other=dimensjoner}; diagrammet viser bare de 2 første",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# støy (cluster_id = -1): %d {one=rad|other=rader}\n",
        "CSV: phân cụm…": "CSV: klynging…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Klyngesentre (opprinnelige enheter) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Korrelasjonsmatrise",
        "Phương pháp tương quan": "Korrelasjonsmetode",
        "Tương quan không hàm ý nhân quả.": "Korrelasjon betyr ikke årsakssammenheng.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Sterkeste par: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klikk på en celle for å se et punktdiagram.",
        "Không cặp nào đo được.": "Ingen par kan måles.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ over %4$d {one=rad|other=rader}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Korrelasjon krever minst 2 numeriske kolonner.",
        "Không đọc được cột «%@».": "Kolonnen «%@» kan ikke leses.",
        "CSV: ma trận tương quan…": "CSV: korrelasjonsmatrise…",
        "Bất thường": "Avvik",
        "Danh sách bất thường": "Liste over avvik",
        "Cột:": "Kolonne:",
        "Cột số cần xét": "Numerisk kolonne som skal undersøkes",
        "Cách:": "Metode:",
        "Phương pháp phát hiện": "Gjenkjenningsmetode",
        "Phương pháp đã dùng": "Brukt metode",
        "Ngưỡng": "Terskel",
        "Đánh dấu": "Merk",
        "Xuất tab mới": "Eksporter til en ny fane",
        "Dòng": "Linje",
        "Điểm": "Skår",
        "Vì sao": "Hvorfor",
        "nhẹ": "lett",
        "vừa": "moderat",
        "nặng": "alvorlig",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=rad|other=rader} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Denne tabellen har ingen numerisk kolonne å lete etter avvik i.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=avvikende linje er merket|other=avvikende linjer er merket}",
        "CSV: tìm bất thường…": "CSV: finn avvik…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d {one=regel, BESTÅTT|other=regler, alle BESTÅTT} · %2$d {one=rad|other=rader} · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d {one=feil|other=feil} · %2$d {one=advarsel|other=advarsler} på tvers av %3$d {one=regel|other=regler} · %4$d {one=rad|other=rader} · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Lagre dokumentet først — kvalitetsreglene ligger ved siden av datafilen.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Det finnes ennå ikke noe regelsett. Opprett filen %@ og åpne på nytt.",
        "Lịch sử": "Historikk",
        "Câu đã lưu": "Lagrede spørringer",
        "Lưu câu này…": "Lagre denne spørringen…",
        "Lưu câu truy vấn": "Lagre spørringen",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Gi den et navn så du finner den senere. Samme navn skriver over.",
        "Ví dụ: Doanh thu theo tỉnh": "For eksempel: Inntekt per fylke",
        "Chưa nhập giá trị cho tham số: %@": "Det ble ikke oppgitt en verdi for parameteren: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Tillegget er endret siden du godkjente det — GEditor nekter å kjøre det",
        "Chạy plugin chưa duyệt?": "Kjøre et ikke godkjent tillegg?",
        "Tôi tin file này — chạy": "Jeg stoler på denne filen — kjør",
        "KHÔNG có chữ ký": "IKKE signert",
        "Chữ ký: %@": "Signatur: %@",
        "Đường dẫn: %@": "Bane: %@",
        "Thay": "Erstatt",
        "Thay tất cả": "Erstatt alle",
        "Chuỗi thuần": "Ren tekst",
        "Extended (\\n \\t \\xNN)": "Utvidet (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Regulært uttrykk",
        "Phân biệt hoa thường": "Skill mellom store og små bokstaver",
        "Cả từ": "Helt ord",
        "Không có kết quả": "Ingen resultater",
        "Thử biểu thức chính quy…": "Prøv et regulært uttrykk…",
        "Chế độ Log (tô theo mức)": "Loggmodus (farge etter nivå)",
        "Lọc log theo mức…": "Filtrer loggen etter nivå…",
        "Chạy trên cả thư mục…": "Kjør på hele mappen…",
        "Lọc qua lệnh ngoài…": "Filtrer gjennom en ekstern kommando…",
        "Script…": "Skript…",
        "Gói mở rộng…": "Utvidelsespakker…",
        "Cửa sổ mới": "Nytt vindu",
        "Tách tab ra cửa sổ mới": "Løsne fanen til et nytt vindu",
        "Chưa mở thư mục nào": "Ingen mappe er åpnet",
        "Tìm file trong thư mục": "Finn en fil i mappen",
        "Lọc theo tên": "Filtrer på navn",
        "File mới…": "Ny fil…",
        "Thư mục mới…": "Ny mappe…",
        "Đổi tên…": "Gi nytt navn…",
        "Chuyển vào Thùng rác": "Flytt til papirkurven",
        "Hiện trong Finder": "Vis i Finder",
        "Đang đọc cấu trúc tài liệu…": "Leser strukturen i dokumentet…",
        "file này không có hàm nào": "denne filen har ingen funksjoner",
        "Không có gì khớp": "Ingen treff",
        "Văn bản thuần": "Ren tekst",
        "🔒 Chỉ đọc": "🔒 Skrivebeskyttet",
        "Đang theo dõi": "Følges",
        "ngắt tại cột": "bryting ved kolonne",
        "Cú pháp": "Syntaks",
        "Bấm để chèn vào ô truy vấn": "Klikk for å sette inn i spørringen",
        "truy vấn không hợp lệ": "ugyldig spørring",
        "khóa `ten` ở gốc": "nøkkelen «navn» i roten",
        "khóa có dấu cách": "nøkkel med mellomrom",
        "phần tử đầu": "første element",
        "mọi phần tử": "alle elementer",
        "lát cắt": "utsnitt",
        "hợp nhiều chỉ số": "union av indekser",
        "mọi khóa `gia` ở mọi tầng": "alle nøkler «pris» på alle nivåer",
        "mọi nút": "alle noder",
        "lọc theo số": "filtrer på tall",
        "lọc theo có mặt": "filtrer på tilstedeværelse",
        "Tới lỗi đầu tiên": "Til første feil",
        "Cột doanh_thu là số": "Kolonnen inntekt er numerisk",
        "lọc…": "filtrer…",
        "Hủy": "Avbryt",
        "Thực hiện thay": "Utfør erstatningen",
        "xem trước": "forhåndsvisning",
        "tương tác": "interaktivt",
        "Soạn thảo": "Rediger",
        "Giao diện": "Grensesnitt",
        "Phím tắt": "Tastatursnarveier",
        "Cỡ chữ": "Tekststørrelse",
        "Bề rộng TAB": "Tabulatorbredde",
        "Thụt lề bằng TAB": "Rykk inn med tabulatorer",
        "Tự động thụt lề khi xuống dòng": "Rykk inn automatisk ved ny linje",
        "Tô mọi kết quả tìm kiếm": "Fremhev alle søketreff",
        "Chuẩn hóa về NFC khi lưu": "Normaliser til NFC ved lagring",
        "Ngôn ngữ": "Språk",
        "Nền": "Utseende",
        "Theo hệ thống": "Som systemet",
        "Sáng": "Lyst",
        "Tối": "Mørkt",
        "Theme": "Tema",
        "Dùng preset Notepad++": "Bruk Notepad++-oppsettet",
        "Về phím mặc định": "Tilbake til standardtastene",
        "Mở file cấu hình": "Åpne konfigurasjonsfilen",
        "Xuất theme hiện tại": "Eksporter det gjeldende temaet",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Språkbyttet slår helt inn ved neste oppstart.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Standardtastene kommer tilbake ved neste oppstart.",
        "Xem trước Markdown": "Markdown-forhåndsvisning",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Forhåndsvisningen bruker systemets Markdown-motor: ennå ingen tabeller og ingen fargelegging av kodeblokker.",
        "Thử biểu thức chính quy": "Prøv et regulært uttrykk",
        "Biểu thức": "Uttrykk",
        "Văn bản thử": "Prøvetekst",
        "Kết quả": "Resultat",
        "Kết quả khớp": "Treff",
        "Biểu thức này làm gì": "Hva dette uttrykket gjør",
        "Giải thích biểu thức": "Forklar uttrykket",
        "Chế độ tìm kiếm": "Søkemodus",
        "Kết quả tìm kiếm": "Søkeresultater",
        "Không khớp chỗ nào": "Ingen treff",
        " (đã cắt bớt)": " (forkortet)",
        "Bản đồ tài liệu": "Dokumentkart",
        "Thanh tab": "Fanelinje",
        "Hàng tiêu đề cột": "Overskriftsrad for kolonnene",
        "Không có cột nào": "Ingen kolonner",
        "Cây thư mục workspace": "Treet for arbeidsområdet",
        "Danh sách hàm và lớp": "Liste over funksjoner og klasser",
        "Kết quả tìm trong thư mục": "Søkeresultater i mappen",
        "Bảng dữ liệu CSV": "CSV-datatabell",
        "Bàn làm sạch dữ liệu": "Arbeidsbenk for datarensing",
        "Truy vấn JSONPath": "JSONPath-spørring",
        "Danh sách lỗi dữ liệu": "Liste over datafeil",
        "Bộ đánh giá golden set…": "Vurderer for gullmengden…",
        "So với điểm ngoài (JSONL)…": "Sammenlign med eksterne skårer (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Velg en fil med eksterne skårer (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Gi den valgte noden nytt navn",
        "Gộp các node đang chọn": "Slå sammen de valgte nodene",
        "Tách node đang chọn": "Del den valgte noden",
        "Trích subgraph đang chọn ra tab mới": "Trekk den valgte delgrafen ut i en ny fane",
        "Không có gì để đổi": "Det er ingenting å endre",
        "%@ — áp %d thay đổi?": "%1$@ — bruke %2$d {one=endring|other=endringer}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d {one=endring|other=endringer} · Cmd-Z angrer hele omgangen",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Sett markøren på NØYAKTIG ÉN node og prøv igjen",
        "Đổi tên «%@»": "Gi «%@» nytt navn",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Alle kanter og etiketter som viser til denne noden, endres med den.",
        "Đổi tên node": "Gi noden nytt navn",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Velg MINST TO noder og prøv igjen",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Kanonisk form «%@» — vanligst, lengst, med diakritiske tegn",
        "Gộp node": "Slå sammen noder",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Velg de KANTLINJENE som skal flyttes, og prøv igjen",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Alle valgte linjer må berøre NØYAKTIG ÉN node — velg flere kantlinjer",
        "Tách «%@» — chuyển %d cạnh": "Del «%1$@» — flytt %2$d {one=kant|other=kanter}",
        "Cạnh tới: %@": "Kanter til: %@",
        "Tách node": "Del noden",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Dokumentet er ulagret — den uttrukne filen trenger en plass ved siden av",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Velg den delen av grafen som skal trekkes ut, og prøv igjen",
        "Gom biến thể entity → bảng duyệt": "Samle entitetsvarianter → gjennomgangstabell",
        "Áp bảng duyệt đã sửa": "Bruk den endrede gjennomgangstabellen",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Dokumentet er ulagret — gjennomgangstabellen må ligge ved siden av graffilen",
        "Không tìm thấy biến thể nào để gom": "Det ble ikke funnet varianter å samle",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=variantgruppe|other=variantgrupper} — rett kolonnen «canonical» og kjør «Bruk gjennomgangstabellen»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Det finnes ingen gjennomgangstabell «%@» — kjør «Samle entitetsvarianter» først",
        "Bảng duyệt không đọc được: %@": "Gjennomgangstabellen kan ikke leses: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Gjennomgangstabellen har ingen linje som må endres",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Ingen steder i grafen samsvarer med gjennomgangstabellen",
        "Gom biến thể entity": "Samle entitetsvarianter",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=endring brukt|other=endringer brukt} · alias-tabellen og markørlisten er skrevet ved siden av filen",
        "Áp %d thay đổi lên đồ thị?": "Bruke %d {one=endring|other=endringer} på grafen?",
        "%d alias → dạng chuẩn.": "%d {one=alias|other=aliaser} → kanonisk form.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "SLÅ SAMMEN noder (kan ikke angres ved å skrive om):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias finnes|other=aliaser finnes} ikke i grafen og ble hoppet over.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Dekningsanalyse bit ↔ entitet",
        "Xuất gói ngữ cảnh (JSONL)": "Eksporter kontekstpakken (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Dekning bit ↔ entitet ↔ graf",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=entitet|other=entiteter} · %2$d {one=bit|other=biter} · %3$.0f %% av entitetene nevnt · %4$.0f %% av bitene med entitet",
        "Entity không chunk nào nhắc tới": "Entiteter som ingen bit nevner",
        "Chunk mồ côi (không chứa entity nào)": "Foreldreløse biter (uten en eneste entitet)",
        "Node đồ thị không có entity đối ứng": "Grafnoder uten tilsvarende entitet",
        "không có": "ingen",
        "Phương pháp": "Metode",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Koblingen bit ↔ entitet kunne ikke bygges",
        "Chấm sức khoẻ đồ thị": "Vurder helsen til grafen",
        "sức khoẻ đồ thị": "helsen til grafen",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Helse %1$@/100 · %2$d {one=feil|other=feil} · %3$d {one=omvending|other=omvendinger} · %4$d foreldreløse",
        "Lai với đồ thị": "Hybrid med grafen",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: signalet fra grafen ignoreres helt, resultatet blir det samme som ren BM25",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α høy: grafen justerer bare BM25-rangeringen lett",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α rundt standardverdien 0,7: BM25 leder, grafen justerer",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α lav: grafen leder, BM25 bryter bare uavgjort",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: bare signalet fra grafen; biter uten entiteter står likt",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Dokumentet er ulagret — hybriden trenger en graffil ved siden av korpuset",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Graffilen «%@» ble ikke funnet — hybriden trenger den til signalet sitt",
        "lai %.1f ms · %@": "hybrid %.1f ms · %@",
        "Thuật toán…": "Algoritmer…",
        "PageRank (độ dày viền)": "PageRank (tykkelsen på kanten)",
        "Cộng đồng (màu nền)": "Fellesskap (bakgrunnsfarge)",
        "Thành phần liên thông": "Sammenhengende komponenter",
        "Xuất bảng node ra tab mới": "Eksporter nodetabellen til en ny fane",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d {one=komponent|other=komponenter} · den største %2$d {one=node|other=noder} · %3$d foreldreløse noder",
        "Tài liệu này không phải đồ thị DOT": "Dette dokumentet er ikke en DOT-graf",
        "Không dựng được bảng node/cạnh: %@": "Node-/kanttabellen kunne ikke bygges: %@",
        "%d hàng · %@": "%d {one=rad|other=rader} · %@",
        "Gán nhãn": "Sett etikett",
        "Ghi chú (tuỳ chọn)": "Notat (valgfritt)",
        "Lưu record": "Lagre posten",
        "Xuất CSV": "Eksporter CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Dokumentet er ulagret — vurdereren må ligge ved siden av korpusfilen",
        "Không nạp được bộ đánh giá: %@": "Vurdereren kunne ikke lastes inn: %@",
        "Không lưu được: %@": "Kunne ikke lagres: %@",
        "Bộ đánh giá chưa có record nào": "Vurdereren har ennå ingen post",
        "Không ghi được: %@": "Kunne ikke skrives: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Dette dokumentet er verken en .mmd-fil eller DOT, og har ingen mermaid-blokk.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=node|other=noder} · %d {one=kant|other=kanter} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid-diagram: legg til element…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid-diagram: koble sammen de to valgte elementene",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid-diagram: endre etiketten på det valgte elementet…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid-diagram: slett det valgte elementet",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid-diagram: flytt meldingen opp",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid-diagram: flytt meldingen ned",
        "Thêm phần tử": "Legg til element",
        "Thêm participant": "Legg til deltaker",
        "Thêm mục": "Legg til post",
        "Thêm mục sơ đồ": "Legg til en post i diagrammet",
        "Sửa mục sơ đồ": "Endre en post i diagrammet",
        "Xoá mục sơ đồ": "Slett en post fra diagrammet",
        "Xoá phần tử": "Slett elementet",
        "Sửa nhãn": "Endre etiketten",
        "Đổi thứ tự message": "Endre rekkefølgen på meldingene",
        "Tên mục": "Navnet på posten",
        "Mục mới": "Ny post",
        "Tên mục hiện trên sơ đồ.": "Navnet på posten vises på diagrammet.",
        "Bảng thuộc tính sơ đồ": "Egenskapstabellen til diagrammet",
        "Tài liệu này không có khối mermaid nào": "Dette dokumentet har ingen mermaid-blokk",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identifikator i diagramkilden — uten mellomrom. Etiketten endres etterpå med dobbeltklikk.",
        "Để trống thì hiện chính định danh.": "Lates den tom, vises identifikatoren selv.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Bare den synlige ETIKETTEN endres; identifikatoren til elementet forblir den samme.",
        "Không rõ «%@» là phần tử nào": "Det er uklart hvilket element «%@» er",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Velg NØYAKTIG TO elementer og prøv igjen",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Sett markøren på NØYAKTIG ETT element og prøv igjen",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Velg ETT element som skal slettes, eller to elementer som en kant forbinder",
        "Xoá «%@» và %d cạnh chạm nó?": "Slette «%1$@» og den %2$d {one=kanten som berører det|other=kantene som berører det}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Nodene i den andre enden av de kantene beholdes — de erklæres på nytt med etiketten sin hvis kantsetningen var den eneste erklæringen deres.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Diagrammet «%1$@» redigeres bare som tekst — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: dra mellom to elementer for å koble dem sammen, dobbeltklikk for å endre etiketten",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: dra mellom to deltakere for å legge til en melding; rekkefølgen endres via menyen Verktøy",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: rediger i egenskapstabellen nedenfor",
        "Soạn trực quan đã bật": "Visuell redigering er slått på",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d {one=post|other=poster} — rediger direkte i tabellen, hver celle er ett angre-trinn",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "For et kakediagram er det et tall; for et gantt det som følger etter kolon.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid-diagram: trekk blokken ut i en .mmd-fil…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid-diagram: bygg den refererte filen inn igjen",
        "Tách khối sơ đồ": "Trekk ut diagramblokken",
        "Nhúng khối sơ đồ": "Bygg inn diagramblokken",
        "Tách khối sơ đồ ra tệp riêng": "Trekk diagramblokken ut i en egen fil",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Filen legges VED SIDEN AV dokumentet; blokken beholder en referanselinje, slik at det bare redigeres ett sted.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Dokumentet er ulagret — diagramfilen trenger en plass ved siden av",
        "Đã có tệp «%@» — chọn tên khác": "Filen «%@» finnes allerede — velg et annet navn",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Trukket ut til «%@» — blokken beholdt en referanselinje",
        "Mở tệp": "Åpne filen",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» er bygd inn igjen; filen ligger fortsatt på disken",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Denne blokken inneholder et ekte diagram, ikke en referanse",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Denne blokken viser til «%@» — åpne den filen for å redigere",
        "Không đọc được tệp sơ đồ %@": "Diagramfilen %@ kunne ikke leses",
        "Soạn trực quan": "Visuell redigering",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Dra fra en node til en annen for å legge til en kant; dobbeltklikk for å endre etiketten. Hver handling er ett angre-trinn.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Visuell redigering: dra mellom to noder for å legge til en kant, dobbeltklikk for å endre etiketten",
        "Soạn trực quan đã tắt": "Visuell redigering er slått av",
        "Thêm node…": "Legg til node…",
        "Thêm cạnh giữa hai node đang chọn…": "Legg til en kant mellom de to valgte nodene…",
        "Sửa nhãn node đang chọn…": "Endre etiketten på den valgte noden…",
        "Xoá node/cạnh đang chọn": "Slett den valgte noden/kanten",
        "Thêm node": "Legg til node",
        "Thêm cạnh": "Legg til kant",
        "Sửa nhãn node": "Endre etiketten til noden",
        "Xoá node": "Slett noden",
        "Xoá cạnh": "Slett kanten",
        "Cmd-Z hoàn tác": "Cmd-Z angrer",
        "Tài liệu đang ở chế độ chỉ đọc": "Dette dokumentet er skrivebeskyttet",
        "Nhãn của «%@»": "Etiketten til «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Bare den synlige ETIKETTEN endres; identifikatoren til noden forblir den samme.",
        "Không rõ «%@» là node nào": "Det er uklart hvilken node «%@» er",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identifikatoren til noden i DOT-filen. Etiketten endres etterpå med dobbeltklikk på tegningen.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Velg NØYAKTIG TO noder og prøv igjen",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Velg ÉN node som skal slettes, eller to noder som en kant forbinder",
        "Xoá node «%@» và %d cạnh chạm nó?": "Slette noden «%1$@» og de %2$d {one=kanten som berører den|other=kantene som berører den}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Blir det liggende igjen løse kanter, gjenskaper DOT nodene ut fra dem — den slettede noden dukker opp igjen ved neste tegning.",
        "Phòng thí nghiệm truy hồi BM25": "BM25-søkelaboratorium",
        "Câu hỏi — Enter để tìm": "Spørsmål — Enter for å søke",
        "Đánh giá…": "Vurder…",
        "Đang dựng chỉ mục": "Bygger indeksen",
        "Không chunk nào khớp": "Ingen bit samsvarer",
        "kết quả trên": "beste treff",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: hvert ord telles BARE én gang, uansett hvor mange ganger det forekommer",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 lav: å gjenta et ord gir nesten ingen ekstra skår",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 rundt standardverdien 1,2: gjentakelse gir skår, men mindre og mindre",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 høy: en bit som gjentar et ord mange ganger, belønnes kraftig",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: lengden ignoreres, lange biter straffes ikke",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b lav: lange biter straffes bare litt",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b rundt standardverdien 0,75: lange biter straffes moderat",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: største straff for lengde, korte biter foretrekkes",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: søkelaboratorium…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Dokumentet er ulagret — BM25-indeksen ligger ved siden av korpusfilen og trenger derfor en bane",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Denne filen er ikke JSONL — Retrieval Lab arbeider på et korpus av biter",
        "Không dựng được chỉ mục BM25 cho tệp này": "Det gikk ikke å bygge en BM25-indeks for denne filen",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Dokumentet er ulagret — det kreves en korpusbane for å lage rapporten",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Velg et vurderingssett (CSV eller JSONL: spørsmål + forventet bit-id)",
        "Đánh giá truy hồi": "Vurdering av søket",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Endre k1, b eller k ovenfor og se igjen for å sammenligne to oppsett; legg til en «compare»-blokk for å kjøre to parametersett parallelt på det samme vurderingssettet.",
        "Lỗi": "Feil",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, i snitt %.0f)",
        "Chế độ JSONL": "JSONL-modus",
        "Bản ghi": "Post",
        "Chi tiết": "Detaljer",
        "Bản ghi ở dòng": "Posten på linjen",
        "không phải JSON hợp lệ": "er ikke gyldig JSON",
        "bản ghi": "poster",
        "dòng trắng": "tomme linjer",
        "không phải đối tượng": "er ikke et objekt",
        "bảng hiện": "vist tabell",
        "ĐÃ HUỶ giữa chừng": "AVBRUTT PÅ HALVVEIEN",
        "Không lọc": "Ingen filtrering",
        "bản ghi khớp bộ lọc": "poster som samsvarer med filteret",
        "Đưa con nháy tới một dòng để xem bản ghi": "Sett markøren på en linje for å se posten",
        "Không có bản ghi nào hỏng": "Ingen ødelagte poster",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Ennå ikke undersøkt. Kjør «JSONL: undersøk biter» på nytt etter kontrollen.",
        "trường văn bản": "tekstfelt",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SKJEMA (gjettet — endres ved å velge et annet felt)",
        "văn bản": "tekst",
        "định danh": "identifikator",
        "metadata lồng": "nøstede metadata",
        "TRƯỜNG": "FELT",
        "phủ": "dekning",
        "nhiều kiểu": "flere typer",
        "ĐỘ DÀI — ký tự": "LENGDE — tegn",
        "ĐỘ DÀI — từ": "LENGDE — ord",
        "ĐỘ DÀI — token ước lượng": "LENGDE — anslåtte tokener",
        "RỖNG VÀ TRÙNG": "TOMME OG DUPLIKATER",
        "chunk rỗng": "tomme biter",
        "dòng": "linjer",
        "nhóm trùng chính xác": "grupper med nøyaktige duplikater",
        "dòng không đọc được, không vào thống kê": "linjer kan ikke leses, utenfor statistikken",
        "PHƯƠNG PHÁP": "METODE",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«tegn» telles som Unicode-tegn (skalarer), ikke som synlige grupper",
        "«từ» tách theo khoảng trắng ASCII": "«ord» deles ved ASCII-mellomrom",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«tokener» telles med en stavelsesdeler — IKKE modellens",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«duplikat» betyr NØYAKTIG duplikat; nesten-duplikater står i blokken ```quality",
        "chunk": "biter",
        "JSONL: kiểm và soi chunk…": "JSONL: kontroller og undersøk biter…",
        "Ảnh": "Bilde",
        "PDF": "PDF",
        "Tài liệu Word": "Word-dokument",
        "Bảng tính Excel": "Excel-regneark",
        "Bản trình chiếu PowerPoint": "PowerPoint-presentasjon",
        "File nén": "Arkiv",
        "Vừa khung": "Tilpass til vinduet",
        "Chép ảnh": "Kopier bildet",
        "Xoay": "Roter",
        "Không đọc được ảnh «%@»": "Bildet «%@» kan ikke leses",
        "Đã chép ảnh vào clipboard": "Bildet er kopiert til utklippstavlen",
        "Bôi vàng": "Fremhev med gult",
        "Gạch chân": "Understrek",
        "Ghi chú…": "Notat…",
        "Bỏ chú thích": "Fjern merknadene",
        "Lấy chữ ra tab mới": "Trekk teksten ut i en ny fane",
        "Lưu bản có chú thích…": "Lagre versjonen med merknader…",
        "Tìm trong PDF": "Søk i PDF-filen",
        "Thêm": "Legg til",
        "Trang %d/%d": "Side %d/%d",
        "Trang %d": "Side %d",
        "Kết quả %d/%d": "Treff %d/%d",
        "0 kết quả": "0 treff",
        "Không đọc được PDF «%@»": "PDF-filen «%@» kan ikke leses",
        "PDF này có mật khẩu — chưa mở được nội dung": "Denne PDF-filen er passordbeskyttet — innholdet er ikke tilgjengelig",
        "Không thấy «%@» trong tài liệu": "«%@» ble ikke funnet i dokumentet",
        "Đã bôi vàng": "Fremhevet",
        "Đã gạch chân": "Understreket",
        "Hãy bôi đen một đoạn chữ trước": "Merk et tekststykke først",
        "Đã thêm ghi chú": "Notat lagt til",
        "Trang này chưa có chú thích nào": "Denne siden har ingen merknader",
        "Đã bỏ %d chú thích trên trang này": "%d {one=merknad fjernet|other=merknader fjernet} fra denne siden",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Denne PDF-filen har ingen tekstlag — det er sannsynligvis en skanning",
        "Không ghi được tệp": "Filen kunne ikke skrives",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Den skrevne filen åpnes IKKE riktig igjen — ikke bruk denne versjonen",
        "Đã lưu %@ · %d trang": "%@ lagret · %d {one=side|other=sider}",
        "Tên": "Navn",
        "Kích thước": "Størrelse",
        "Đã nén": "Komprimert",
        "Tỉ lệ": "Forhold",
        "Sửa lúc": "Endret",
        "Mở mục đang chọn": "Åpne det valgte objektet",
        "Bung ra thư mục…": "Pakk ut til en mappe…",
        "Bung vào đây": "Pakk ut her",
        "%d mục": "%d {one=objekt|other=objekter}",
        "giải nén ra %@": "pakket ut til %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— innsiden av en Office-fil er et arkiv; dette er delene i det",
        "Đã bung %d mục": "%d {one=objekt pakket|other=objekter pakket} ut",
        "%d mục hỏng": "%d {one=objekt er ødelagt|other=objekter er ødelagt}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=objekt ble AVVIST|other=objekter ble AVVIST} fordi banene deres går utenfor målmappen",
        "Không mở được mục này": "Dette objektet kan ikke åpnes",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Det går ennå ikke å skrive direkte til en %@ — bruk «Lagre som…»",
        "Không có gì đổi": "Ingenting er endret",
        "Đã ghi %d ô vào %@": "%1$d {one=celle skrevet|other=celler skrevet} til %2$@",
        "Đã ghi %d đoạn vào %@": "%1$d {one=avsnitt skrevet|other=avsnitt skrevet} til %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Det gikk ikke å skrive til filen — originalen er urørt",
        "dựng bài": "forberede testtilfellet",
        "Không ghi được settings.json": "Kan ikke skrive til settings.json",
        "Xoay trái": "Roter til venstre",
        "Xoay phải": "Roter til høyre",
        "Trang lên": "Flytt siden opp",
        "Trang xuống": "Flytt siden ned",
        "Xoá trang…": "Slett sider…",
        "Xoá trang": "Slett sider",
        "Trích trang…": "Trekk ut sider…",
        "Trích trang ra tệp mới": "Trekk ut sider til ny fil",
        "Gộp tệp PDF…": "Slå sammen PDF-fil…",
        "Tách tệp…": "Del opp fil…",
        "Tách tệp PDF": "Del opp PDF-fil",
        "Xuất ảnh…": "Eksporter bilder…",
        "Xuất trang ra ảnh PNG": "Eksporter sider som PNG-bilder",
        "Hoàn tác trang": "Angre sideendring",
        "Lưu bản đã sửa…": "Lagre redigert kopi…",
        "Phát": "Spill av",
        "Tạm dừng": "Pause",
        "Xem bình thường": "Normal visning",
        "Chọn sheet": "Velg ark",
        "Mở sheet": "Åpne ark",
        "Bỏ và đổi sheet": "Forkast og bytt ark",
        "Bảng tính có %d sheet.": "Arbeidsboken har %d ark.",
        "Bảng tính này chỉ có một sheet: «%@»": "Denne arbeidsboken har bare ett ark: «%@»",
        "Bỏ phần chưa lưu của sheet này?": "Forkaste ulagrede endringer i dette arket?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Å bytte ark erstatter hele fanen. Det som ikke er lagret med ⌘S, går tapt.",
        "Chọn tệp PDF cần gộp vào": "Velg PDF-fil som skal slås sammen",
        "Chọn thư mục ghi ảnh": "Velg mappe for bildene",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Velg lagringssted. Den andre filen skrives ved siden av denne.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Dokumentet har %d sider. Angi sidene som skal slettes, f.eks. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Dokumentet har %d sider. Angi sidene som skal trekkes ut, f.eks. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Dokumentet har %d sider. Angi sidene som skal eksporteres, f.eks. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Dokumentet har %d sider. Angi delen som skal skilles ut, f.eks. 1-5; resten blir en andre fil.",
        "Đã xoay trang %d": "Side %d rotert",
        "Đã xoá trang %@ · còn %d trang": "Sidene %@ slettet · %d sider igjen",
        "Đã gộp %d trang từ «%@»": "%d sider slått sammen fra «%@»",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Delt i %@ (%d sider) og %@ (%d sider)",
        "Đã ghi %@ — %@ · %d trang": "Skrev %@ — %@ · %d sider",
        "Đã xuất %d ảnh vào %@": "%d bilder eksportert til %@",
        "Chỉ xuất được %d/%d ảnh": "Bare %d av %d bilder ble eksportert",
        "Đã hoàn tác một thao tác trang": "Én sidehandling ble angret",
        "Không còn thao tác trang nào để hoàn tác": "Ingen sidehandlinger igjen å angre",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Kan ikke slette ALLE sider — en PDF må ha minst én side",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Det området er hele dokumentet — ingenting å skille ut",
        "«%@» có mật khẩu — chưa gộp được": "«%@» er passordbeskyttet — kan ikke slås sammen",
        "«%@» không có trang nào": "«%@» har ingen sider",
        "Đã ở trang đầu": "Allerede på første side",
        "Đã ở trang cuối": "Allerede på siste side",
        "· đã sửa, chưa lưu": "· redigert, ikke lagret",
        "Ảnh động · %d khung": "Animert bilde · %d bilder",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Ulagret dokument — ingen fil på disken for binærvisning",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Denne kommandoen virker bare med Excel-arbeidsbøker",
        "Không đọc được danh sách sheet": "Kunne ikke lese listen over ark",
        "Không có sheet «%@»": "Det finnes ikke noe ark som heter «%@»",
        "Không đọc được sheet «%@»": "Kunne ikke lese arket «%@»",
        "Sheet «%@» · %d hàng": "Arket «%@» · %d rader",
        "phần còn lại": "resten",
        "Lưu ý": "Merk",
        "Cẩn thận": "Forsiktig",
        "Xem thêm": "Se også",
        "Chép": "Kopier",
        "Đã chép": "Kopiert",
        "Chép đoạn mã mẫu": "Kopier eksempelkoden",
        "Tìm trong trợ giúp": "Søk i hjelp",
        "Lùi": "Tilbake",
        "Bắt đầu dùng": "Kom i gang",
        "Không mở cửa sổ này khi khởi động nữa": "Ikke vis dette vinduet ved oppstart",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Hjelpen er ennå ikke oversatt til dette språket — viser den vietnamesiske teksten.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Gå til offset (f.eks. 1F400 eller 0x1F400)",
        "Chép dòng đã chọn": "Kopier valgte rader",
        "Đã chép %d dòng": "%d rader kopiert",
        "Không đọc được «%@»": "Kunne ikke lese «%@»",
        "Tệp rỗng": "Tom fil",
        "Không đọc được offset «%@»": "Kunne ikke lese offset «%@»",
        "Offset 0x%@ vượt quá cỡ tệp": "Offset 0x%@ er utenfor filens størrelse",
        "Mở bằng ứng dụng khác…": "Åpne med et annet program…",
        "%d kênh": "%d kanaler",
        "Không phát được «%@»": "Kan ikke spille av «%@»",
        "Không phát được — %@": "Kan ikke spilles av — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS har ingen innebygd dekoder for formatet %@ — det er en systembegrensning, ikke en ødelagt fil.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Du kan fortsatt se bytene i binærvisning, eller åpne filen i et program med egen dekoder.",
        "Ký…": "Signer…",
        "Sửa chữ…": "Rediger tekst…",
        "Sửa chữ": "Rediger tekst",
        "Vẽ đè": "Tegn over",
        "Ô chưa điền": "Neste tomme felt",
        "Xoá nội dung đã điền": "Tøm utfylte verdier",
        "Tệp này không có ô biểu mẫu nào": "Denne filen har ingen skjemafelt",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d skjemafelt tømt",
        "Mọi ô biểu mẫu đều đã có nội dung": "Alle skjemafelt er allerede fylt ut",
        "Còn %d ô chưa điền": "%d felt er fortsatt tomme",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Utfyllbart skjema: %d felt. Skriv rett inn, og velg så «Lagre redigert kopi…»",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Velg et signaturbilde (gjennomsiktig bakgrunn ser best ut)",
        "Không dựng được trang có chữ ký": "Kunne ikke lage den signerte siden",
        "Đã chèn chữ ký vào trang %d": "Signatur satt inn på side %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Merk først teksten du vil endre",
        "Vùng chọn quá nhỏ": "Merkingen er for liten",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Den nye teksten TEGNES OVER merkingen med systemskriften. Den gamle teksten dekkes, ikke fjernes — den kan fortsatt trekkes ut, så dette er ikke sladding.",
        "Không dựng được trang đã sửa": "Kunne ikke lage den redigerte siden",
        "Đã vẽ đè chữ mới lên trang %d": "Ny tekst tegnet over side %d",
        "Đổi chế độ View / Code": "Bytt Visning / Kode",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Ingen trevisning ennå for JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Ingen diagramvisning i fanen ennå",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Ingen disposisjonsvisning ennå for PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Denne filen har bare én visningsmodus",
        "%d nút": "%d noder",
        "Không dựng được cây: %@": "Kunne ikke bygge treet: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Dokumentet er for stort for et tre — bruk Kode-modus",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Kunne ikke bygge sider for denne filen \u{2014} bruk Code-modus.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Lysbilder bygges fra tekst; originale bilder og oppsett tegnes ikke ennå.",
        "Vừa ngang": "Tilpass bredde",
        "Thu nhỏ trang": "Forminsk side",
        "Phóng to trang": "Forstørr side",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "Fant ikke «%@» i dokumentet",
        "Chỗ khớp %d/%d": "Treff %d av %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Ingen tekst er valgt på siden.",
        "%d ký tự": "%d {one=tegn|other=tegn}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Åpne filer rett i View-modus når de har en",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· AVBRUTT underveis — tabellen er ufullstendig",
        "Chế độ hiển thị": "Visningsmodus",
        "Đổi giữa View và Code (⌥⌘V)": "Bytt mellom View og Code (⌥⌘V)",
        "Trang tài liệu": "Dokumentsider",
        "Chữ đã dựng": "Satt tekst",
        "Trang bảng tính": "Regnearksider",
        "Sơ đồ": "Diagram",
        "Cây khoá–giá trị": "Nøkkel–verdi-tre",
        "Bộ phát": "Spiller",
        "Danh sách mục": "Liste over oppføringer",
        "Báo cáo đã dựng": "Ferdig rapport",
        "Tô theo mức": "Farget etter nivå",
        "Trang slide": "Lysbildesider",
        "Dàn ý": "Disposisjon",
        "Lưu rồi dựng lại": "Lagre og bygg på nytt",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Viser kopien PÅ DISKEN — ulagrede endringer er ikke med her.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Systemet klarte ikke å bygge dokumentvisningen — bruk Code-modus.",
        "Lưu tệp trước khi xem trang.": "Lagre filen før du ser sidene.",
        "Đang ở chế độ Code": "Nå i Code-modus",
        "Đang ở chế độ View": "Nå i View-modus",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Du ser kildeteksten — klikk for View-modus (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "I View-modus — klikk for å gå tilbake til kildeteksten (⌥⌘V)",
        "Tín hiệu: %@": "Signal: %@",
        "Lý do: %@": "Årsak: %@",
        "Chi tiết: %@": "Detalj: %@",
        "Mở báo cáo": "Åpne rapporten",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor avsluttet uventet kl. %@ — åpne rapporten for å lese den; ingenting sendes.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligaturer — av holder hvert tegn i sin egen rute",
        "Chế độ CSV": "CSV-modus",
        "Dấu phân tách": "Skilletegn",
        "Tự nhận diện": "Kjenn igjen automatisk",
        "Dấu phân tách: %@": "Skilletegn: %@",
        "Theo đuôi tệp": "Etter filendelse",
        "%d dấu cách": "%d {one=mellomrom|other=mellomrom}",
        "Tài liệu đang sửa được": "Dette dokumentet kan redigeres",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Skrivebeskyttet fordi filen følges — stopp følgingen for å redigere",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Skrivebeskyttet fordi filen på disken ikke kan skrives til",
        "Đã mở khoá — tài liệu sửa được": "Låst opp — dokumentet kan redigeres igjen",
        "Nhân bản tệp": "Dupliser fil",
        "Đổi tên tệp…": "Gi filen nytt navn…",
        "Chuyển tệp tới…": "Flytt filen til…",
        "XML: đánh giá XPath…": "XML: evaluer XPath…",
        "Đánh giá XPath": "Evaluer XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "For eksempel: //ordre/linje[2]/@kode · //*[@type='A'] · count(//linje)",
        "Đánh giá": "Evaluer",
        "XPath không đọc được: %@": "Klarer ikke lese den XPath-en: %@",
        "XPath «%@» không khớp node nào": "XPath «%@» traff ingen node",
        "XPath «%@» — %d node": "XPath «%@» — %d {one=node|other=noder}",
        "XPath «%@»: %d node": "XPath «%@»: %d {one=node|other=noder}",
        "Lưu tệp trước khi nhân bản.": "Lagre filen før du dupliserer den.",
        "Không nhân bản được": "Klarte ikke å duplisere",
        "Đã nhân bản thành %@": "Duplisert som %@",
        "Lưu tệp trước khi đổi tên.": "Lagre filen før du gir den nytt navn.",
        "Đổi tên tệp": "Gi filen nytt navn",
        "Tên hiện tại: %@": "Nåværende navn: %@",
        "Đổi tên": "Gi nytt navn",
        "Tên tệp không hợp lệ": "Det filnavnet er ikke gyldig",
        "Đã có tệp tên %@ ở đó": "Det finnes allerede en fil som heter %@ der",
        "Lưu tệp trước khi chuyển.": "Lagre filen før du flytter den.",
        "Chuyển tới": "Flytt hit",
        "Thư mục đích đã có tệp tên %@": "Målmappen har allerede en fil som heter %@",
        "Không chuyển được tệp": "Klarte ikke å flytte filen",
        "Đã chuyển tới %@": "Flyttet til %@",
        "Bảng mã:": "Tegnkoding:",
        "Xuống dòng:": "Linjeslutt:",
        "Riêng cho %@": "Bare for %@",
        "    %d — dùng TAB": "    %d — tabulatorer",
        "    %d — dùng dấu cách": "    %d — mellomrom",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Fjern egen regel, bruk den globale innstillingen",
        "%@: thụt lề %d %@": "%@: innrykk %d %@",
        "TAB": "tabulatorer",
        "dấu cách": "mellomrom",
        "Xuất": "Eksporter",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Åpne resultatene som en tekstfane — lagre med ⌘S",
        "Lượt tìm trước đó": "Tidligere søk",
        "«%@» — %d kết quả": "«%@» — %d {one=treff|other=treff}",
        "Kết quả tìm «%@»": "Søkeresultater for «%@»",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtrer filnavn — f.eks. *.csv;*.log (tomt: hver tekstfil)",
        "Thư mục %@ không có file văn bản nào": "Mappen %@ har ingen tekstfiler",
        "Không tệp nào trong %@ khớp «%@»": "Ingen fil i %@ passer med «%@»",
        "%d byte · %d dòng": "%d byte · %d {one=linje|other=linjer}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d byte · %d {one=linje|other=linjer} — for stor til å telle tegn og ord",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d byte · %d {one=tegn|other=tegn} · %d {one=ord|other=ord} · %d {one=linje|other=linjer}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Dette dokumentet har %d {one=linje|other=linjer}, %d byte. Skriv et linjenummer, «linje,kolonne» eller «@byte».",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "«%@» kan ikke leses — skriv et linjenummer, «linje,kolonne» eller «@byte»",
    ]
}
