import Foundation

/// Bảng dịch tiếng Urdu. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let ur: [String: String] = [
        "Bản đã lưu…": "محفوظ نسخے…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "یہ دستاویز کبھی محفوظ نہیں ہوئی — کوئی تاریخ نہیں",
        "Chưa có bản đã lưu nào trước đó": "اس سے پہلے کا کوئی محفوظ نسخہ نہیں",
        "Không đọc được bản ấy": "وہ نسخہ پڑھا نہیں جا سکتا",
        "Khôi phục bản đã lưu": "محفوظ نسخہ بحال کریں",
        "XML: kiểm theo DTD/XSD…": "XML: ‏DTD/XSD کے مطابق جانچیں…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "اس میک میں libxml2 نہیں ہے، اس لیے XSD جانچ دستیاب نہیں۔",
        "Chọn lược đồ XSD để kiểm": "جانچ کے لیے ایک XSD خاکہ منتخب کریں",
        "Hợp lệ theo": "اس کے مطابق درست:",
        "Plugin chạy xong, không đổi gì": "توسیع کچھ بدلے بغیر ختم ہو گئی",
        "Chưa cài plugin native nào": "کوئی مقامی توسیع نصب نہیں",
        "Gỡ plugin này": "یہ توسیع ہٹائیں",
        "Gỡ plugin này?": "کیا یہ توسیع ہٹا دی جائے؟",
        "Gỡ": "ہٹائیں",
        "Cài plugin native…": "مقامی توسیع نصب کریں…",
        "Mở thư mục plugin": "توسیعات کا فولڈر کھولیں",
        "Chọn file .dylib của plugin native": "توسیع کی ‎.dylib فائل منتخب کریں",
        "Đã cài:": "نصب ہوئی:",
        "Đã gỡ:": "ہٹا دی گئی:",
        "Plugin native…": "مقامی توسیعات…",
        "Chỉ nhận file .dylib.": "صرف ‎.dylib فائلیں قبول کی جاتی ہیں۔",
        "Đã có một plugin trùng tên:": "اسی نام کی ایک توسیع پہلے سے نصب ہے:",
        "Không chép được plugin:": "توسیع کی نقل نہیں بنائی جا سکی:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "مقامی توسیعات صرف براہِ راست ڈاؤن لوڈ میں ہیں، App Store نسخے میں نہیں۔",
        "Không tìm thấy tiến trình phụ chạy plugin.": "توسیعات کا معاون عمل نہیں ملا۔",
        "Không khởi động được tiến trình phụ:": "معاون عمل شروع نہیں کیا جا سکا:",
        "Tiến trình plugin đã dừng giữa chừng.": "توسیع کا عمل درمیان میں رک گیا۔",
        "Plugin không trả lời kịp — đã dừng nó.": "توسیع نے وقت پر جواب نہ دیا — اسے روک دیا گیا۔",
        "Plugin trả lời sai giao thức:": "توسیع نے غلط ساخت کا پیغام بھیجا:",
        "Plugin báo lỗi:": "توسیع نے ایک خامی بتائی:",
        "Về GEditor": "GEditor کے بارے میں",
        "Cài đặt…": "ترتیبات…",
        "Thoát GEditor": "GEditor سے باہر نکلیں",
        "File": "فائل",
        "Tab mới": "نیا ٹیب",
        "Đóng tab": "ٹیب بند کریں",
        "Tab kế": "اگلا ٹیب",
        "Tab trước": "پچھلا ٹیب",
        "Tài liệu mới": "نئی دستاویز",
        "Mở…": "کھولیں…",
        "Mở thư mục làm Workspace…": "ایک فولڈر کو کام کی جگہ کے طور پر کھولیں…",
        "Mở gần đây": "حالیہ کھولیں",
        "Lưu": "محفوظ کریں",
        "Lưu thành…": "بطور محفوظ کریں…",
        "Cắt khoảng trắng cuối dòng khi lưu": "محفوظ کرتے وقت سطر کے آخر کی خالی جگہیں ہٹائیں",
        "Theo dõi file (tail -f)": "فائل کی نگرانی کریں (tail -f)",
        "In…": "چھاپیں…",
        "Mở lại tab vừa đóng": "بند کیا ہوا ٹیب دوبارہ کھولیں",
        "Chưa có file nào": "کوئی فائل نہیں",
        "Xoá danh sách": "فہرست خالی کریں",
        "Edit": "ترمیم",
        "Hoàn tác": "کالعدم کریں",
        "Làm lại": "دوبارہ کریں",
        "Cắt": "کاٹیں",
        "Sao chép": "نقل کریں",
        "Dán": "چسپاں کریں",
        "Lịch sử clipboard…": "تختۂ تراشہ کی تاریخ…",
        "Column Editor…": "ستون مدوّن…",
        "Chọn lần kế tiếp": "اگلا مماثل منتخب کریں",
        "Chọn tất cả": "سب منتخب کریں",
        "Nhân đôi dòng": "سطر کی نقل بنائیں",
        "Xóa dòng": "سطر حذف کریں",
        "Comment dòng": "سطر کو تبصرہ بنائیں",
        "Chưa chép gì trong phiên này": "اس نشست میں کچھ نقل نہیں کیا گیا",
        "Xoá lịch sử": "تاریخ صاف کریں",
        "Search": "تلاش",
        "Tìm…": "ڈھونڈیں…",
        "Tìm và thay…": "ڈھونڈیں اور بدلیں…",
        "Tìm trong thư mục…": "ایک فولڈر میں ڈھونڈیں…",
        "Thay trong thư mục…": "ایک فولڈر میں بدلیں…",
        "Kết quả kế": "اگلا نتیجہ",
        "Kết quả trước": "پچھلا نتیجہ",
        "Đi tới dòng…": "سطر پر جائیں…",
        "Nhảy tới ngoặc khớp": "مماثل قوسین پر جائیں",
        "Đánh dấu mọi dòng khớp…": "تمام مماثل سطروں پر نشان لگائیں…",
        "Đảo dấu": "نشانات الٹ دیں",
        "Bỏ mọi dấu": "تمام نشانات ہٹائیں",
        "Chép dòng đã đánh dấu": "نشان زدہ سطروں کی نقل بنائیں",
        "Xóa dòng đã đánh dấu": "نشان زدہ سطریں حذف کریں",
        "Chỉ giữ dòng đã đánh dấu": "صرف نشان زدہ سطریں رکھیں",
        "Lines": "سطریں",
        "Sắp xếp A→Z": "الف→ی ترتیب دیں",
        "Sắp xếp Z→A": "ی→الف ترتیب دیں",
        "Sắp xếp tự nhiên": "قدرتی ترتیب",
        "Khử trùng lặp": "دہرائے ہوئے ہٹائیں",
        "Đảo thứ tự dòng": "سطروں کی ترتیب الٹ دیں",
        "Dời dòng lên": "سطر اوپر لے جائیں",
        "Dời dòng xuống": "سطر نیچے لے جائیں",
        "Ghép dòng": "سطریں جوڑیں",
        "Tách dòng theo độ dài…": "لمبائی کے حساب سے سطریں توڑیں…",
        "Tách dòng theo ký tự…": "حرف کے حساب سے سطریں توڑیں…",
        "Xóa dòng rỗng": "خالی سطریں حذف کریں",
        "Nén dòng trống liên tiếp": "لگاتار خالی سطریں سکیڑیں",
        "Cắt khoảng trắng cuối dòng": "سطر کے آخر کی خالی جگہیں ہٹائیں",
        "Tab → Space": "Tab ← خالی جگہ",
        "Space → Tab": "خالی جگہ ← Tab",
        "HOA": "بڑے حروف",
        "thường": "چھوٹے حروف",
        "Chữ Hoa Đầu Từ": "ہر لفظ کا پہلا حرف بڑا",
        "Chữ hoa đầu câu": "جملے کا پہلا حرف بڑا",
        "Đảo hoa/thường": "بڑے چھوٹے حروف الٹ دیں",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: شیٹ منتخب کریں…",
        "Xem dạng bảng / văn bản": "جدول / متن کے منظر میں تبدیلی",
        "Xóa cột…": "ستون حذف کریں…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "مواد جانچیں (ستونوں کی تعداد · اقسام)",
        "Bàn làm sạch dữ liệu…": "مواد صفائی کی میز…",
        "Chạy công thức làm sạch…": "صفائی کا نسخہ چلائیں…",
        "Chuyển đổi…": "تبدیل کریں…",
        "Đổi dấu phân tách…": "جدا کرنے والا نشان بدلیں…",
        "Xuất sang JSON…": "JSON میں برآمد کریں…",
        "Format": "ساخت",
        "Bảng mã…": "رمز کاری…",
        "Xuống dòng…": "سطر کے اختتام…",
        "Chuẩn hóa Unicode…": "یونی کوڈ معیاری بنائیں…",
        "JSON: định dạng lại": "JSON: خوش ساخت بنائیں",
        "JSON: thu gọn một dòng": "JSON: ایک سطر میں سکیڑیں",
        "JSON: sắp xếp khóa": "JSON: کلیدیں ترتیب دیں",
        "JSON: truy vấn JSONPath…": "JSON: ‏JSONPath استفسار…",
        "CSV: truy vấn SQL…": "CSV: ‏SQL استفسار…",
        "Truy vấn SQL": "SQL استفسار",
        "Đang chạy…": "چل رہا ہے…",
        "Xuất ra tab mới": "نئے ٹیب میں برآمد کریں",
        "Tài liệu rỗng — không có bảng để truy vấn": "دستاویز خالی ہے — استفسار کے لیے کوئی جدول نہیں",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "یہ CSV جدول نہیں — پہلی سطر میں صرف ایک ستون ہے",
        "Không đọc được câu truy vấn": "استفسار پڑھا نہیں جا سکتا",
        "Không kiểm được câu truy vấn": "استفسار جانچا نہیں جا سکتا",
        "Vàng (mặc định)": "پیلا (طے شدہ)",
        "Xanh dương": "نیلا",
        "Xanh lá": "سبز",
        "Vàng đất": "خاکی",
        "Tím": "جامنی",
        "Hồng": "گلابی",
        "Xanh ngọc": "فیروزی",
        "Cam": "نارنجی",
        "Xám lam": "سلیٹی",
        "Văn bản": "متن",
        "Dãy số": "عددی سلسلہ",
        "Dãy ngày": "تاریخوں کا سلسلہ",
        "Chữ HOA (hex)": "بڑے حروف (سولہ عددی)",
        "Bắt đầu": "آغاز",
        "Bước": "قدم",
        "Đệm 0 tới": "صفروں سے بھریں تاآنکہ",
        "Hệ": "بنیاد",
        "Ngày đầu": "پہلی تاریخ",
        "Định dạng": "ساخت",
        "Chèn": "داخل کریں",
        "Huỷ": "منسوخ کریں",
        "Chuyển đổi định dạng": "ساخت بدلیں",
        "Xem trước 5 hàng đầu": "پہلی ۵ سطروں کا پیش منظر",
        "Tạo tab mới": "نئے ٹیب میں کھولیں",
        "Lưu ra file…": "ایک فائل میں محفوظ کریں…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "نتیجہ ایک نئے، غیر محفوظ ٹیب میں کھلتا ہے۔ اصل دستاویز جوں کی توں رہتی ہے۔",
        "Chạy trên tài liệu này": "اس دستاویز پر چلائیں",
        "Chạy trên thư mục…": "ایک فولڈر پر چلائیں…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "پورا نسخہ ایک ہی کالعدم قدم ہے۔ ڈسک پر موجود فائل آپ کے محفوظ کرنے تک جوں کی توں رہتی ہے۔",
        "tắt": "بند",
        "không thấy cột": "ستون نہیں ملا",
        "sẵn sàng": "تیار",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "یہ ایپ بند ہونے تک پروسیسر کا ایک مرکز گھیرے رکھتا ہے۔",
        "Script không trả về gì": "اسکرپٹ نے کچھ واپس نہیں کیا",
        "Không dựng được máy JavaScript": "JavaScript انجن نہیں بنایا جا سکا",
        "Lỗi JavaScript không rõ": "نامعلوم JavaScript خامی",
        "Bảng": "جدول",
        "Áp sắp xếp vào file": "ترتیب فائل پر لاگو کریں",
        "Chuyển đổi ▾": "تبدیل کریں ▾",
        "Xuất dòng khớp": "مماثل سطریں برآمد کریں",
        "Ẩn cột này": "یہ ستون چھپائیں",
        "Đổi tên tiêu đề…": "سرخی کا نام بدلیں…",
        "Chèn cột trống bên trái": "بائیں جانب خالی ستون داخل کریں",
        "Chèn cột trống bên phải": "دائیں جانب خالی ستون داخل کریں",
        "Xóa cột này khỏi file…": "یہ ستون فائل سے حذف کریں…",
        "Phải còn ít nhất một cột đang hiện": "کم از کم ایک ستون نظر آتا رہنا چاہیے",
        "Đang sắp xếp…": "ترتیب دی جا رہی ہے…",
        "Trở về thứ tự trong file": "فائل کی ترتیب پر واپس جائیں",
        "trăm hàng đầu": "پہلی سو سطریں",
        "chọn cột": "ستون چننا",
        "đặt tên cột kết quả": "نتیجے کے ستون کو نام دینا",
        "lọc theo chữ": "متن کے حساب سے چھاننا",
        "ô rỗng": "خالی خانے",
        "ghép điều kiện": "شرائط جوڑنا",
        "đếm hàng": "سطریں گننا",
        "gộp nhóm": "گروہ بندی اور خلاصہ",
        "nhỏ nhất, lớn nhất": "کم سے کم، زیادہ سے زیادہ",
        "sắp xếp và cắt": "ترتیب دینا اور محدود کرنا",
        "tên cột có dấu cách": "خالی جگہ والا ستون کا نام",
        "Truy vấn bị dừng giữa chừng": "استفسار درمیان میں روک دیا گیا",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "معاونت نہیں: JOIN · ذیلی استفسار · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · دریچہ افعال",
        "XML: định dạng lại": "XML: خوش ساخت بنائیں",
        "XML: thu gọn một dòng": "XML: ایک سطر میں سکیڑیں",
        "XML: kiểm cú pháp": "XML: نحو جانچیں",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: دہرائی گئی کلیدیں اور حاشیہ جانچیں",
        "View": "منظر",
        "Ẩn/hiện sidebar (Function List)": "پہلو پٹی (افعال کی فہرست) دکھائیں/چھپائیں",
        "Ẩn/hiện bản đồ tài liệu": "دستاویز کا نقشہ دکھائیں/چھپائیں",
        "Gấp / mở khối tại con nháy": "نشان زد جگہ کا بلاک تہہ کریں / کھولیں",
        "Gấp tất cả": "سب تہہ کریں",
        "Bỏ gấp tất cả": "سب کھولیں",
        "Gấp theo cấp": "درجے کے حساب سے تہہ کریں",
        "Cấp %d": "درجہ %d",
        "Đã gấp %d khối ở cấp %d": "‏%2$d درجے پر %1$d {one=بلاک تہہ ہو گیا|other=بلاک تہہ ہو گئے}",
        "Tài liệu này chỉ sâu %d cấp": "اس دستاویز کی گہرائی صرف %d {one=درجہ|other=درجے} ہے",
        "mermaid: không đọc được bản kê": "mermaid: فہرستِ اجزا پڑھی نہیں جا سکی",
        "Kiểm tra bản cập nhật…": "تازہ کاری جانچیں…",
        "Kiểm tra bản cập nhật": "تازہ کاری جانچیں",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store نسخے Mac App Store کے ذریعے تازہ ہوتے ہیں، GEditor کے ذریعے نہیں۔",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "اس تعمیر میں تازہ کاری کی دستخطی کنجی نہیں، اس لیے وہ تازہ کاری نہیں ڈھونڈ سکتی۔",
        "Phóng to chữ": "متن بڑا کریں",
        "Thu nhỏ chữ": "متن چھوٹا کریں",
        "Cỡ chữ gốc": "اصل جسامت",
        "Chia đôi theo chiều dọc": "عمودی تقسیم",
        "Chia đôi theo chiều ngang": "افقی تقسیم",
        "Bỏ chia đôi": "تقسیم بند کریں",
        "Mở tab này ở nửa kia": "یہ ٹیب دوسرے حصے میں کھولیں",
        "Nhảy sang nửa kia": "دوسرے حصے میں جائیں",
        "Ngắt dòng (tắt / cửa sổ / cột)": "سطر لپیٹنا (بند / دریچہ / ستون)",
        "Ngắt dòng tại cột…": "اس ستون پر لپیٹیں…",
        "Đánh dấu dòng này": "اس سطر پر نشان لگائیں",
        "Dấu kế tiếp": "اگلا نشان",
        "Dấu trước đó": "پچھلا نشان",
        "Màu đánh dấu…": "نشانات کا رنگ…",
        "Hiện tất cả ký tự ẩn": "تمام غیر مرئی حروف دکھائیں",
        "  Khoảng trắng": "  خالی جگہیں",
        "  Tab": "  ٹیبیں",
        "  Xuống dòng": "  سطر کے اختتام",
        "  NBSP · zero-width · điều khiển": "  NBSP · صفر چوڑائی · ضابطی",
        "Xem nhị phân": "بائنری منظر",
        "Chế độ CSV (tô màu theo cột)": "CSV وضع (ستون رنگین)",
        "Macro": "میکرو",
        "Bắt đầu / dừng ghi": "ریکارڈنگ شروع / بند کریں",
        "Phát lại": "چلائیں",
        "Phát nhiều lần…": "کئی بار چلائیں…",
        "Phát đến cuối tài liệu": "دستاویز کے آخر تک چلائیں",
        "Chạy trên mọi tab": "تمام ٹیبوں پر چلائیں",
        "Hủy macro đang chạy": "چلتا میکرو منسوخ کریں",
        "Lưu macro…": "میکرو محفوظ کریں…",
        "Macro đã lưu…": "محفوظ میکرو…",
        "Help": "مدد",
        "Trợ giúp GEditor": "GEditor مدد",
        "Giới thiệu tính năng": "خصوصیات کا تعارف",
        "Di cư từ Notepad++": "Notepad++ سے منتقلی",
        "Tìm": "ڈھونڈیں",
        "Thay bằng": "اس سے بدلیں",
        "Kế": "اگلا",
        "Trước": "پچھلا",
        "Đếm": "گنتی",
        "Đóng": "بند کریں",
        "Kiểm theo JSON Schema…": "ایک JSON خاکے کے مطابق جانچیں…",
        "Chọn tệp JSON Schema": "ایک JSON خاکہ فائل منتخب کریں",
        "Không thấy lỗi nào theo schema này.": "اس خاکے کے مطابق کوئی مسئلہ نہیں ملا۔",
        "JSON Schema": "JSON خاکہ",
        "Kiểm cú pháp đồ thị": "گراف کا نحو جانچیں",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "گراف کی ساخت پہچانی نہیں گئی — ‎.dot، ‎.gv، ‎.cypher، ‎.ttl یا ‎.graphml لاحقہ درکار ہے۔",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "کوئی %@ نحوی خامی نہیں ملی (یہ جانچ مکمل نہیں ہے)۔",
        "Cú pháp %@": "%@ نحو",
        "không phải một đối tượng JSON": "یہ JSON شے نہیں",
        "Khai phá văn bản (n-gram, TF-IDF)": "متن کاوی (n-gram، TF-IDF)",
        "Tài liệu rỗng.": "دستاویز خالی ہے۔",
        "Không rút được từ khoá nào.": "کوئی کلیدی لفظ نہیں نکالا جا سکا۔",
        "Từ khoá": "کلیدی الفاظ",
        "%d từ khoá · %d token · %d tài liệu": "‏%d {one=کلیدی لفظ|other=کلیدی الفاظ} · %d نشان · %d {one=دستاویز|other=دستاویزیں}",
        "Tô lên tài liệu": "دستاویز میں نشان لگائیں",
        "Đánh dấu entity từ danh sách…": "فہرست سے اکائیوں پر نشان لگائیں…",
        "Chọn danh sách entity (CSV hoặc JSON)": "اکائیوں کی فہرست منتخب کریں (CSV یا JSON)",
        "Không đọc được danh sách entity.": "اکائیوں کی فہرست پڑھی نہیں جا سکتی۔",
        "Danh sách entity rỗng.": "اکائیوں کی فہرست خالی ہے۔",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "دستاویز میں کوئی اکائی نہیں ملی (%d لادی گئیں)۔",
        "%d lần xuất hiện · %@": "‏%d بار آئی · %@",
        "Chuyển đổi tri thức…": "علم تبدیل کریں…",
        "Chuyển đổi: %@ → %@": "تبدیلی: %@ ← %@",
        "Không chuyển đổi được.": "تبدیل نہیں کیا جا سکا۔",
        "Xem trước cắt chunk…": "ٹکڑوں کا پیش منظر…",
        "Cỡ cố định 800B, chồng 100B": "مقررہ جسامت ۸۰۰ بائٹ، تداخل ۱۰۰ بائٹ",
        "Theo câu (≤ 800B)": "جملے کے حساب سے (≤ ۸۰۰ بائٹ)",
        "Theo heading Markdown": "Markdown سرخی کے حساب سے",
        "Tài liệu rỗng — không có chunk nào.": "دستاویز خالی ہے — کوئی ٹکڑا نہیں۔",
        "%d chunk · trung bình %d B · %@": "‏%d {one=ٹکڑا|other=ٹکڑے} · اوسطاً %d بائٹ · %@",
        "Xuất JSONL": "JSONL برآمد کریں",
        "Chunk JSONL": "ٹکڑوں کا JSONL",
        "Mở triple/edge dạng bảng": "تہرے/کنارے بطور جدول کھولیں",
        "Bảng triple": "تہروں کا جدول",
        "Tài liệu này không có dòng triple nào.": "اس دستاویز میں تہرے کی کوئی سطر نہیں۔",
        "Không đọc được triple nào — dòng %d: %@": "کوئی تہرا نہیں پڑھا جا سکا — سطر %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "‏%1$d {one=تہرا پڑھا گیا|other=تہرے پڑھے گئے} · %2$d {one=خراب سطر چھوڑ دی گئی|other=خراب سطریں چھوڑ دی گئیں} (پہلی: سطر %3$d)",
        "Trùng lặp mờ theo cột…": "ستون کے حساب سے دھندلے دہرائے…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "دھندلے دہرائے — ستون «%1$@»: %2$d {one=امیدوار گروہ|other=امیدوار گروہ}",
        "Gộp": "ضم کریں",
        "Giống": "مماثلت",
        "Các giá trị trong cụm": "گروہ کی قدریں",
        "Gộp về": "اس میں ضم کریں",
        "Gộp các cụm đã chọn": "منتخب گروہ ضم کریں",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "کوئی گروہ منتخب نہیں — «ضم کریں» دبانے سے کچھ نہیں بدلے گا۔ ایپ کبھی خود سے ضم نہیں کرتی۔",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "‏%d {one=گروہ منتخب|other=گروہ منتخب} · %d {one=سطر بدلے گی|other=سطریں بدلیں گی} · ایک کالعدم قدم",
        "Không quét được cột này.": "اس ستون کی جانچ نہیں کی جا سکی۔",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "ستون «%@» میں دھندلے دہرائے کا کوئی گروہ نہیں۔",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "کوئی گروہ ضم نہیں ہوا — دستاویز جوں کی توں ہے۔",
        "Khử trùng lặp mờ · cột %@": "دھندلے دہرائے کی صفائی · ستون %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "‏%d {one=گروہ ضم ہوا|other=گروہ ضم ہوئے} · %d {one=خانہ بدلا|other=خانے بدلے}",
        "Báo cáo làm sạch": "صفائی کی رپورٹ",
        "# Báo cáo làm sạch — %@\n\n": "# صفائی کی رپورٹ — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## لاگو (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_کوئی قدم لاگو نہیں کیا گیا۔_\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## مواد کا خاکہ\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d ستون · %2$d {one=سطر|other=سطریں} · %3$.1f سیکنڈ میں جانچا گیا_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| ستون | قسم | خالی | منفرد | کم سے کم | زیادہ سے زیادہ | اوسط |\n",
        "\n### Giá trị bất thường\n\n": "\n### غیر معمولی قدریں\n\n",
        "hàng %d: %@": "سطر %d: %@",
        "- cột «%@» — %d ô: %@\n": "- ستون «%1$@» — %2$d {one=خانہ|other=خانے}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## باقی (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_کوئی اور مشاہدہ باقی نہیں۔_\n",
        "- cột «%@»: %@\n": "- ستون «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "محفوظ کرتے وقت خالی جگہیں ہٹائیں",
        "Chuẩn hóa xuống dòng": "سطر کے اختتام معیاری بنائیں",
        "trước đó": "پچھلا",
        "Không mở lại được thư mục «%@» của phiên trước": "پچھلی نشست کا فولڈر «%@» دوبارہ نہیں کھولا جا سکا",
        " (và %d file khác)": " (اور %d مزید {one=فائل|other=فائلیں})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "‏%d {one=ٹیب دوبارہ نہیں کھولا جا سکا|other=ٹیب دوبارہ نہیں کھولے جا سکے}: %@%@ — فائلیں اب اپنی پرانی جگہ پر نہیں۔",
        "Không đọc được nội dung từ ống dẫn": "نالی سے مواد پڑھا نہیں جا سکا",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "ہر بار محفوظ کرنے پر سطر کے آخر کی خالی جگہیں ہٹائی جائیں گی",
        "Không cắt khoảng trắng khi lưu nữa": "اب محفوظ کرتے وقت خالی جگہیں نہیں ہٹائی جاتیں",
        "Chưa đặt tên.txt": "بلا عنوان.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "رمز کاری بدلنے سے کچھ حروف ضائع ہوں گے",
        "Vẫn lưu": "پھر بھی محفوظ کریں",
        "Tài liệu có thay đổi chưa lưu": "دستاویز میں غیر محفوظ تبدیلیاں ہیں",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "محفوظ کیے بغیر بند کرنے سے وہ ضائع ہو جائیں گی۔",
        "Bỏ thay đổi": "تبدیلیاں چھوڑ دیں",
        "Đi tới dòng": "سطر پر جائیں",
        "Tài liệu có %d dòng.": "اس دستاویز میں %d {one=سطر ہے|other=سطریں ہیں}۔",
        "Số dòng": "سطر کا نمبر",
        "Đi tới": "جائیں",
        "Diễn giải lại theo…": "اس طور پر دوبارہ پڑھیں…",
        "Chuyển đổi sang…": "اس میں بدلیں…",
        "Không diễn giải lại được": "دوبارہ نہیں پڑھا جا سکا",
        "Bảng mã %@ không chứa hết ký tự": "‏%@ تمام حروف نہیں دکھا سکتا",
        "Vẫn chọn": "پھر بھی منتخب کریں",
        "Cột %d": "ستون %d",
        "Cột %d: %@": "ستون %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "چھپے ہوئے ستون: %@ (%d) — سرخی کی سطر کے سیاق مینو سے واپس لائیں",
        "Hiện lại: %@": "دوبارہ دکھائیں: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "ستون %@ چھپا دیا گیا — فائل میں وہ جوں کا توں ہے",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "‏%@ %@ کے حساب سے ترتیب · صرف نمائش",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "ترتیب: %@ %@ (صرف نمائش)",
        "%d+ dòng khớp — đang tìm tiếp…": "‏%d+ سطریں مماثل — ابھی تلاش جاری ہے…",
        "%d / %d dòng khớp": "‏%d / %d {one=سطر مماثل|other=سطریں مماثل}",
        "Không tìm thấy lỗi trong %d hàng": "‏%d {one=سطر|other=سطروں} میں کوئی مسئلہ نہیں ملا",
        "%d hàng lệch số cột": "‏%d {one=سطر|other=سطروں} میں ستونوں کی تعداد غلط",
        "%d ô sai kiểu dữ liệu": "‏%d {one=خانے|other=خانوں} میں مواد کی قسم غلط",
        " (đã dừng ở %d lỗi đầu)": " (پہلے %d {one=مسئلے|other=مسائل} پر رک گیا)",
        "   —   kiểu nhận ra: ": "   —   پہچانی گئی اقسام: ",
        "Hàng %d, cột %@: «%@» không phải %@": "سطر %1$d، ستون %2$@: «%3$@» ‏%4$@ نہیں ہے",
        "Column Editor — %d dòng": "ستون مدوّن — %d {one=سطر|other=سطریں}",
        "Phát hiện": "مشاہدات",
        "Hồ sơ dữ liệu": "مواد کا خاکہ",
        "Hồ sơ dữ liệu — đang quét…": "مواد کا خاکہ — جانچ جاری…",
        "Lưu công thức…": "نسخہ محفوظ کریں…",
        "Xuất báo cáo": "رپورٹ برآمد کریں",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "کوئی گروہ لاگو نہیں · ہر گروہ ایک کالعدم قدم ہے",
        "quá nhiều giá trị": "بہت زیادہ قدریں",
        "hay gặp: ": "سب سے عام: ",
        "Giá trị điền vào ô thiếu": "خالی خانوں کو بھرنے کی قدر",
        "Áp dụng": "لاگو کریں",
        "Không dựng được bản xem trước": "پیش منظر نہیں بنایا جا سکا",
        "· giữ nguyên, không đọc được ·": "· جوں کا توں رکھا، پڑھا نہیں جا سکتا ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "ستون کو ISO 8601 میں بدلیں (YYYY-MM-DD)",
        "Quy ước số cho cả cột": "پورے ستون کے لیے عددی روایت",
        "Làm gì với ô thiếu": "خالی خانوں کا کیا کیا جائے",
        "Chuẩn hóa về ISO 8601": "ISO 8601 میں معیاری بنائیں",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "مبہم خانوں کو دن پہلے پڑھیں (۳۱/۱۲)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "مبہم خانوں کو مہینہ پہلے پڑھیں (۱۲/۳۱)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "مبہم خانے چھوڑ دیں، صرف یقینی درست کریں",
        "Về Việt/Âu (1.234,56)": "ویتنامی/یورپی میں (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "انگریزی‑امریکی میں (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "انگریزی‑امریکی میں، ہزار کے نشان کے بغیر (1234.56)",
        "Điền một giá trị mặc định…": "ایک طے شدہ قدر سے بھریں…",
        "Điền xuôi — lấy giá trị phía trên": "نیچے کی طرف بھریں — اوپر کی قدر لیں",
        "Điền ngược — lấy giá trị phía dưới": "اوپر کی طرف بھریں — نیچے کی قدر لیں",
        "Xóa hàng có ô thiếu ở cột này": "اس ستون میں خالی خانے والی سطریں حذف کریں",
        "Cắt khoảng trắng hai đầu": "دونوں سروں کی خالی جگہیں ہٹائیں",
        "Cắt hai đầu và nén khoảng trắng bên trong": "دونوں سروں سے ہٹائیں اور اندر کی خالی جگہیں سکیڑیں",
        "Pivot…": "محوری جدول…",
        "Nguồn…": "مآخذ…",
        "Pivot — gộp theo cột": "محوری جدول — ستون کے حساب سے گروہ بندی",
        "Hàng (gộp nhóm)": "سطریں (گروہ بندی)",
        "Giá trị": "قدریں",
        "+ Hàng": "+ سطر",
        "+ Giá trị": "+ قدر",
        "Xoá hết": "سب صاف کریں",
        "Đưa vào ô truy vấn": "استفسار کے خانے میں ڈالیں",
        "Chọn cột để dựng câu truy vấn.": "استفسار بنانے کے لیے ستون چنیں۔",
        "Không đọc được tên cột của bảng này.": "اس جدول کے ستونوں کے نام پڑھے نہیں جا سکے۔",
        "Nguồn dữ liệu của truy vấn": "استفسار کے مآخذ",
        "«%@» — tài liệu đang mở": "«%@» — کھلی ہوئی دستاویز",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ اندراج کے بعد فائل بدل چکی ہے",
        "Thêm file…": "فائل شامل کریں…",
        "Bỏ hết": "سب ہٹائیں",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "«%@» سے جدول کا نام اخذ نہیں کیا جا سکا — فائل کا نام بدلیں۔",
        "Tổng": "مجموعہ",
        "Trung bình": "اوسط",
        "Nhỏ nhất": "کم سے کم",
        "Lớn nhất": "زیادہ سے زیادہ",
        "Đếm khác nhau": "منفرد کی گنتی",
        "Biểu đồ": "خاکہ",
        "Xuất PNG": "PNG برآمد کریں",
        "Xuất SVG": "SVG برآمد کریں",
        "Bảng này không có cột số nào để vẽ.": "اس جدول میں خاکہ بنانے کے لیے کوئی عددی ستون نہیں۔",
        "Không dựng được ảnh PNG.": "PNG تصویر نہیں بنائی جا سکی۔",
        "Kết quả truy vấn": "استفسار کا نتیجہ",
        "Đã lưu %@": "‏%@ محفوظ ہوا",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "«%2$@» کا %1$@ خاکہ — %3$d {one=نقطہ|other=نقطے}، قدریں %4$@ سے %5$@ تک",
        "Cột": "ستونی",
        "Đường": "خطی",
        "Phân bố": "تعدد نما",
        "Phân tán": "بکھراؤ",
        "Hộp": "صندوقی",
        "CSV: chất lượng dữ liệu…": "CSV: مواد کا معیار…",
        "Chất lượng dữ liệu": "مواد کا معیار",
        "Xuất vi phạm ra tab mới": "خلاف ورزیاں نئے ٹیب میں برآمد کریں",
        "Mức": "درجہ",
        "Luật": "قاعدہ",
        "Vi phạm": "خلاف ورزیاں",
        "Tỷ lệ": "شرح",
        "đạt": "کامیاب",
        "lỗi": "خامی",
        "cảnh báo": "تنبیہ",
        "hỏng": "خراب",
        "Đã đánh dấu %d dòng vi phạm": "‏%d {one=خلاف ورزی کرنے والی سطر پر نشان لگا|other=خلاف ورزی کرنے والی سطروں پر نشان لگا}",
        "Xu hướng": "رجحان",
        "Lúc chấm": "جانچ کا وقت",
        "Số hàng": "سطروں کی تعداد",
        "Lệch": "فرق",
        "Luật trượt": "ناکام قواعد",
        "Điểm chất lượng": "معیار کا نمبر",
        "Điểm theo thời gian": "وقت کے ساتھ نمبر",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "ابھی کوئی تاریخ نہیں — ہر جانچ ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "قواعد کے ساتھ رکھی «‎.history.jsonl» فائل میں ایک سطر بڑھاتی ہے۔",
        "%d mốc trong lịch sử": "تاریخ میں %d {one=نقطہ|other=نقطے}",
        " · %d dòng KHÔNG đọc được": " · %d {one=سطر پڑھی نہیں جا سکتی|other=سطریں پڑھی نہیں جا سکتیں}",
        " · chọn hai dòng để so": " · موازنے کے لیے دو سطریں منتخب کریں",
        "điểm %+.1f": "نمبر %+.1f",
        "không chiều nào tụt": "کوئی پہلو نیچے نہیں گیا",
        "tụt: ": "نیچے گئے: ",
        "%d luật mới trượt: %@": "‏%d {one=قاعدہ نئے سرے سے ناکام|other=قواعد نئے سرے سے ناکام}: %@",
        "số hàng %+d": "سطریں %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (اور «رجحان» ٹیب میں %d مزید {one=تنبیہ|other=تنبیہات})",
        "Không sửa tự động được: ": "خودکار درستی ممکن نہیں: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "صفائی کی میز میں متعلقہ اوزار کھولتا ہے، پھر فوراً دوبارہ جانچتا ہے۔",
        "Xử lý giá trị thiếu…": "غائب قدروں سے نمٹیں…",
        "Chuẩn hóa ngày…": "تاریخیں معیاری بنائیں…",
        "Khử trùng lặp…": "دہرائے ہٹائیں…",
        "Thay thế…": "بدلیں…",
        "Xem các dòng sai": "غلط سطریں دکھائیں",
        "Không tìm thấy cột «%@» trong bảng này.": "ستون «%@» اس جدول میں نہیں۔",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "دہرائے ہٹا دیے گئے — «%@» اب منفرد ہے۔ نمبر: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "دہرائے ہٹا دیے گئے، مگر «%1$@» میں اب بھی %2$d {one=دہرائی گئی سطر ہے|other=دہرائی گئی سطریں ہیں} (پہلے: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "وہ سطریں کلید میں شریک ہیں مگر پوری سطر میں نہیں، اس لیے دیکھ کر چننا ہو گا ",
        "giữ hàng nào.": "کون سی رکھنی ہے۔",
        "Không đọc được giá trị nào đang vi phạm luật này.": "اس قاعدے کی خلاف ورزی کرنے والی کوئی قدر نہیں پڑھی جا سکی۔",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "ستون «%2$@» میں %1$d {one=غلط قدر|other=غلط قدریں} — «بدلیں» بھریں اور پیش منظر دبائیں",
        "Đã chấm lại: %.0f/100": "دوبارہ جانچا گیا: %.0f/100",
        "Xem trước báo cáo": "رپورٹ کا پیش منظر",
        "Tham số…": "متغیرات…",
        "Xuất HTML…": "HTML برآمد کریں…",
        "In / PDF…": "چھاپیں / PDF…",
        "%d khối chạy được · %d khối HỎNG": "‏%d {one=بلاک چلا|other=بلاک چلے} · %d بلاک ناکام",
        "%d khối chạy được": "‏%d {one=بلاک چلا|other=بلاک چلے}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · پرانا مواد — ماخذ فائل بدل چکی ہے؛ دوبارہ بنائیں",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "رپورٹ کے پیش منظر کے لیے ‎.%@ دستاویز درکار ہے",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "کوئی ماخذ نہیں ملا — frontmatter میں «source: فائل.csv» لکھیں۔",
        "Không dựng được báo cáo.": "رپورٹ نہیں بنائی جا سکی۔",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "اس رپورٹ کے frontmatter میں کوئی متغیر درج نہیں۔",
        "Tham số báo cáo": "رپورٹ کے متغیرات",
        "Dựng lại": "دوبارہ بنائیں",
        "Đã xuất %@": "‏%@ برآمد ہوا",
        "Báo cáo: xem trước": "رپورٹ: پیش منظر",
        "Báo cáo: sinh loạt…": "رپورٹ: گروہی تیاری…",
        "không phải tài liệu .greport.md": "یہ ‎.greport.md دستاویز نہیں",
        "không phân tích được báo cáo": "رپورٹ کا تجزیہ نہیں ہو سکا",
        "không tìm được dữ liệu nguồn": "ماخذ مواد نہیں ملا",
        "không đọc được danh sách tham số": "متغیرات کی فہرست پڑھی نہیں جا سکی",
        "Sinh loạt cần tài liệu đuôi .%@": "گروہی تیاری کے لیے ‎.%@ دستاویز درکار ہے",
        "Chọn danh sách tham số (CSV hoặc JSON)": "متغیرات کی فہرست منتخب کریں (CSV یا JSON)",
        "Chọn thư mục để ghi %d báo cáo": "‏%d {one=رپورٹ|other=رپورٹوں} کے لیے ایک فولڈر منتخب کریں",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "غائب متغیرات ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "یہ خود ماخذ فائل کی طرف اشارہ کرتا ہے — اوپر لکھنے سے انکار",
        "%d khối HỎNG": "‏%d بلاک ناکام",
        "Sinh loạt xong: %d tệp · %d hỏng": "گروہ مکمل: %d {one=فائل|other=فائلیں} · %d ناکام",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "‏%d {one=متغیر مجموعہ نہیں بنایا جا سکا|other=متغیر مجموعے نہیں بنائے جا سکے} — خلاصہ دیکھیں",
        "Sơ đồ Mermaid: xem trước": "Mermaid خاکہ: پیش منظر",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid خاکہ: سانچہ داخل کریں…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid خاکہ: دوبارہ خوش ساخت بنائیں",
        "Nền trong suốt": "شفاف پس منظر",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "یہ میک خاکے کو PNG میں نہیں بدل سکتا — macOS 13 درکار ہے۔ SVG برآمدگی اب بھی چلتی ہے۔",
        "Lưu PNG %@…": "PNG ‏%@ محفوظ کریں…",
        "Lưu SVG…": "SVG محفوظ کریں…",
        "Chép ảnh vào clipboard": "تصویر تختۂ تراشہ میں نقل کریں",
        "Màu thương hiệu…": "برانڈ کے رنگ…",
        "Màu thương hiệu cho sơ đồ": "خاکوں کے لیے برانڈ کے رنگ",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "ہر خانہ ‎#rrggbb ساخت کا رنگ ہے۔ «themes/mermaid-brand.json» میں محفوظ ہوتا ہے — کسی اور میک پر نقل کیا جا سکتا ہے۔",
        "Màu chính": "بنیادی رنگ",
        "Chữ trên nút": "گرہوں پر متن",
        "Viền": "کنارہ",
        "Đường nối": "روابط",
        "Nền khi xuất ảnh": "برآمد کے وقت پس منظر",
        "Lưu và chèn %%{init}%% vào tài liệu": "محفوظ کریں اور %%{init}%% دستاویز میں داخل کریں",
        "Đã lưu màu thương hiệu": "برانڈ کے رنگ محفوظ ہو گئے",
        "Đã chép ảnh sơ đồ vào clipboard": "خاکے کی تصویر تختۂ تراشہ میں نقل ہو گئی",
        "Đã lưu %@ — %@": "‏%@ محفوظ ہوا — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "اس خاکے میں پہلے ہی %%{init}%% ہدایت موجود ہے — آپ کی جوں کی توں رہی۔",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "‏%%{init}%% داخل ہو گیا — خاکہ اب اپنے رنگ خود رکھتا ہے",
        "Chèn màu thương hiệu vào sơ đồ": "خاکے میں برانڈ کے رنگ داخل کریں",
        "Định dạng sơ đồ Mermaid": "Mermaid خاکہ دوبارہ خوش ساخت بنائیں",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "خاکے کا ماخذ پہلے ہی ستھرا ہے — بدلنے کو کچھ نہیں",
        "Đã định dạng lại sơ đồ": "خاکہ دوبارہ خوش ساخت ہو گیا",
        "Đã định dạng lại %d sơ đồ": "‏%d {one=خاکہ دوبارہ خوش ساخت ہوا|other=خاکے دوبارہ خوش ساخت ہوئے}",
        "Thư viện mẫu sơ đồ": "خاکوں کے سانچوں کی لائبریری",
        "Mẫu sơ đồ đầy đủ": "مکمل خاکہ سانچے",
        "Mẩu cú pháp": "نحوی ٹکڑے",
        "Đang soạn: %@": "زیرِ ترمیم: %@",
        "Đã chèn mẫu «%@»": "سانچہ «%@» داخل ہو گیا",
        "Tài liệu đang ở chế độ chỉ đọc.": "یہ دستاویز صرف پڑھنے کے لیے ہے۔",
        "Sơ đồ Mermaid": "Mermaid خاکہ",
        "Tài liệu chưa có khối mermaid nào.": "اس دستاویز میں کوئی mermaid بلاک نہیں۔",
        "Thương hiệu": "برانڈ",
        "Xuất…": "برآمد کریں…",
        "Chưa có sơ đồ nào": "ابھی کوئی خاکہ نہیں",
        "%d sơ đồ · %@": "‏%d {one=خاکہ|other=خاکے} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "‏%1$d/%2$d {one=خاکہ ناکام|other=خاکے ناکام} — %3$d واں خاکہ%4$@",
        ", dòng %d": "‏، سطر %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "اس دستاویز میں ‎```mermaid بلاک نہیں اور یہ ‎.mmd فائل بھی نہیں۔",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "ابھی کوئی خاکہ بن کر مکمل نہیں ہوا۔",
        "Không tìm thấy «%@» trong mã sơ đồ": "خاکے کے ماخذ میں «%@» نہیں ملا",
        "không dựng được hàng rào chặn mạng cho WKWebView": "WKWebView کے لیے جال بندش نہیں بنائی جا سکی",
        "Luật kết hợp": "ربطی قواعد",
        "Mỗi dòng một giỏ": "ہر سطر پر ایک ٹوکری",
        "Hai cột: mã · item": "دو ستون: شناخت · شے",
        "Dạng dữ liệu giao dịch": "لین دین کے مواد کی ساخت",
        "Cột giỏ hàng hoặc mã giao dịch": "ٹوکری کا ستون یا لین دین کی شناخت کا ستون",
        "Cột item": "شے کا ستون",
        "Ký tự phân tách item": "اشیا کو جدا کرنے والا حرف",
        "Support tối thiểu, phần trăm": "کم سے کم support، فیصد",
        "Confidence tối thiểu, phần trăm": "کم سے کم confidence، فیصد",
        "Tách bởi:": "جدا کرنے والا:",
        "Support \u{2265}": "‏Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "ربطی قواعد کا جدول",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "خبردار",
        "%d giao dịch · %d item · %d luật": "‏%d لین دین · %d {one=شے|other=اشیا} · %d {one=قاعدہ|other=قواعد}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — کوئی قاعدہ حدوں تک نہ پہنچا؛ support یا confidence کم کریں",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — جلد رک گیا، جدول نامکمل ہے",
        "%d / %d giao dịch chứa cả hai vế": "‏%d / %d لین دین دونوں طرف رکھتے ہیں",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "دو ستونی ساخت کے لیے دو مختلف ستون درکار ہیں۔",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "«%3$@» رکھنے والے %2$d لین دین میں %1$d {one=سطر پر نشان لگا|other=سطروں پر نشان لگا}",
        "CSV: luật kết hợp…": "CSV: ربطی قواعد…",
        "Khai phá theo nhóm": "گروہی کاوی",
        "Cột nhóm": "گروہ کا ستون",
        "Cột giá trị": "قدر کا ستون",
        "Cột thứ hai cho tương quan": "باہمی تعلق کے لیے دوسرا ستون",
        "Cách xếp hạng": "درجہ بندی کا طریقہ",
        "Nhóm theo:": "اس کے حساب سے گروہ:",
        "Giá trị:": "قدر:",
        "Xếp theo:": "اس کے حساب سے درجہ:",
        "Bảng xếp hạng nhóm": "گروہوں کی درجہ بندی کا جدول",
        "Nhóm": "گروہ",
        "Hàng": "سطریں",
        "Hàng rào riêng": "اپنی حد",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "‏r کا فرق",
        "Ghi chú": "نوٹ",
        "không đo được": "ناپا نہیں جا سکتا",
        "%d nhóm · mốc tương quan toàn bộ %@": "‏%d گروہ · مجموعی حوالہ تعلق %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=گروہ چھوڑ دیا گیا|other=گروہ چھوڑ دیے گئے}",
        "Bảng này không có cột chữ nào để gom nhóm.": "اس جدول میں گروہ بندی کے لیے کوئی متنی ستون نہیں۔",
        "Bảng này không có cột số nào để khai phá.": "اس جدول میں کاوی کے لیے کوئی عددی ستون نہیں۔",
        "Đã đánh dấu %d dòng của nhóm «%@»": "گروہ «%2$@» کی %1$d {one=سطر پر نشان لگا|other=سطروں پر نشان لگا}",
        "CSV: khai phá theo nhóm…": "CSV: گروہی کاوی…",
        "\u{2194}": "↔",
        "Dự báo": "پیش گوئی",
        "Cột giá trị theo thời gian": "وقت کے ساتھ قدر کا ستون",
        "Mô hình dự báo": "پیش گوئی کا نمونہ",
        "Số kỳ dự báo": "پیش گوئی کے ادوار کی تعداد",
        "Kết luận so với baseline": "بنیادی نمونوں کے مقابلے میں فیصلہ",
        "Mô hình:": "نمونہ:",
        "Số kỳ:": "ادوار:",
        "Chu kỳ:": "موسم:",
        "tự": "خودکار",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "موسمی دورانیہ؛ خودکار پہچان کے لیے خالی چھوڑیں",
        "Bảng giá trị dự báo": "پیش گوئی شدہ قدروں کا جدول",
        "Kỳ": "دور",
        "Dải 80%": "۸۰٪ کی حد",
        "Dải 95%": "۹۵٪ کی حد",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "شمار نہیں کیا جا سکتا",
        "Bảng này không có cột số nào để dự báo.": "اس جدول میں پیش گوئی کے لیے کوئی عددی ستون نہیں۔",
        "Không dựng được dự báo cho cột này.": "اس ستون کے لیے پیش گوئی نہیں بنائی جا سکی۔",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "ستون «%1$@» میں صرف %2$d {one=عددی قدر ہے|other=عددی قدریں ہیں} — پیش گوئی کے لیے کم از کم ۴ درکار ہیں۔",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# سلسلہ بالکل فائل کی سطروں کی ترتیب سے پڑھا جاتا ہے — نہ دوبارہ ترتیب، نہ وقت کے ستون کا اندازہ۔\n",
        "Sai số huấn luyện": "تربیت کی خامی",
        "CSV: dự báo chuỗi thời gian…": "CSV: وقتی سلسلے کی پیش گوئی…",
        "Holt-Winters cộng": "Holt-Winters جمعی",
        "Holt-Winters nhân": "Holt-Winters ضربی",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "خوشہ بندی میں شامل ستون",
        "Đường cong WCSS": "WCSS منحنی",
        "Phân cụm": "خوشہ",
        "Chuẩn hoá:": "پیمائش:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "کم از کم ایک ستون منتخب کریں۔",
        "Không đủ dữ liệu để dựng đường cong.": "منحنی بنانے کے لیے مواد کافی نہیں۔",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "کہنی k = %d تجویز کرتی ہے۔ WCSS ہمیشہ k بڑھنے پر گھٹتا ہے، اس لیے یہ خاکہ پڑھنے کا گر ہے، شماریاتی معیار نہیں — منحنی دیکھیں اور فیصلہ کریں کہ موڑ واضح ہے یا نہیں۔",
        "WCSS theo k": "‏k کے حساب سے WCSS",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "‏k فاصلہ eps = %1$@ تجویز کرتا ہے (minPts طے شدہ طور پر ۲ × ستونوں کی تعداد = %2$d)۔ %3$@",
        "Khoảng cách tới hàng xóm thứ k": "‏k ویں پڑوسی تک فاصلہ",
        "Cần ít nhất 2 cột số để phân cụm.": "خوشہ بندی کے لیے کم از کم ۲ عددی ستون درکار ہیں۔",
        "Cụm theo %@ và %@": "‏%@ اور %@ کے حساب سے خوشے",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — خوشے %d {one=بُعد|other=ابعاد} میں ملے؛ خاکہ صرف پہلے ۲ ابعاد دکھاتا ہے",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# شور (cluster_id = -1): %d {one=سطر|other=سطریں}\n",
        "CSV: phân cụm…": "CSV: خوشہ بندی…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- خوشوں کے مراکز (اصل اکائیاں) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "باہمی تعلق کا جدول",
        "Phương pháp tương quan": "باہمی تعلق کا طریقہ",
        "Tương quan không hàm ý nhân quả.": "باہمی تعلق کا مطلب سببیت نہیں۔",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "سب سے مضبوط جوڑا: %1$@ ↔ %2$@ = %3$@ ‏(n = %4$d)۔ بکھراؤ کا خاکہ دیکھنے کے لیے کسی خانے پر دبائیں۔",
        "Không cặp nào đo được.": "کوئی جوڑا ناپا نہیں جا سکتا۔",
        "%@ ↔ %@: %@ trên %d hàng": "‏%1$@ ↔ %2$@: %3$@، %4$d {one=سطر|other=سطروں} پر",
        "Cần ít nhất 2 cột số để tính tương quan.": "باہمی تعلق کے لیے کم از کم ۲ عددی ستون درکار ہیں۔",
        "Không đọc được cột «%@».": "ستون «%@» پڑھا نہیں جا سکا۔",
        "CSV: ma trận tương quan…": "CSV: باہمی تعلق کا جدول…",
        "Bất thường": "غیر معمولی",
        "Danh sách bất thường": "غیر معمولی کی فہرست",
        "Cột:": "ستون:",
        "Cột số cần xét": "جانچنے کے لیے عددی ستون",
        "Cách:": "طریقہ:",
        "Phương pháp phát hiện": "پہچان کا طریقہ",
        "Phương pháp đã dùng": "استعمال شدہ طریقہ",
        "Ngưỡng": "حد",
        "Đánh dấu": "نشان لگائیں",
        "Xuất tab mới": "نئے ٹیب میں برآمد کریں",
        "Dòng": "سطر",
        "Điểm": "نمبر",
        "Vì sao": "کیوں",
        "nhẹ": "ہلکا",
        "vừa": "درمیانہ",
        "nặng": "شدید",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "‏%d / %d {one=سطر|other=سطریں} (%.2f٪)",
        "Bảng này không có cột số nào để tìm bất thường.": "اس جدول میں غیر معمولی ڈھونڈنے کے لیے کوئی عددی ستون نہیں۔",
        "Đã đánh dấu %d dòng bất thường": "‏%d {one=غیر معمولی سطر پر نشان لگا|other=غیر معمولی سطروں پر نشان لگا}",
        "CSV: tìm bất thường…": "CSV: غیر معمولی ڈھونڈیں…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "‏%1$d {one=قاعدہ، کامیاب|other=قواعد، سب کامیاب} · %2$d {one=سطر|other=سطریں} · %3$.0f ملی سیکنڈ",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "‏%1$d {one=خامی|other=خامیاں} · %3$d {one=قاعدے|other=قواعد} میں %2$d {one=تنبیہ|other=تنبیہات} · %4$d {one=سطر|other=سطریں} · %5$.0f ملی سیکنڈ",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "پہلے دستاویز محفوظ کریں — معیار کے قواعد مواد کی فائل کے ساتھ رہتے ہیں۔",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "ابھی قواعد کا مجموعہ نہیں۔ فائل %@ بنائیں اور دوبارہ کھولیں۔",
        "Lịch sử": "تاریخ",
        "Câu đã lưu": "محفوظ استفسارات",
        "Lưu câu này…": "یہ استفسار محفوظ کریں…",
        "Lưu câu truy vấn": "استفسار محفوظ کریں",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "بعد میں ڈھونڈنے کے لیے اسے نام دیں۔ وہی نام اوپر لکھ دیتا ہے۔",
        "Ví dụ: Doanh thu theo tỉnh": "مثلاً: صوبے کے حساب سے آمدنی",
        "Chưa nhập giá trị cho tham số: %@": "متغیر کے لیے کوئی قدر درج نہیں: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "منظوری کے بعد توسیع بدل چکی ہے — GEditor اسے چلانے سے انکار کرتا ہے",
        "Chạy plugin chưa duyệt?": "کیا غیر منظور شدہ توسیع چلائی جائے؟",
        "Tôi tin file này — chạy": "مجھے اس فائل پر بھروسا ہے — چلائیں",
        "KHÔNG có chữ ký": "بغیر دستخط",
        "Chữ ký: %@": "دستخط: %@",
        "Đường dẫn: %@": "راستہ: %@",
        "Thay": "بدلیں",
        "Thay tất cả": "سب بدلیں",
        "Chuỗi thuần": "سادہ متن",
        "Extended (\\n \\t \\xNN)": "توسیعی (\\n \\t \\xNN)",
        "Biểu thức chính quy": "قاعدہ اظہار",
        "Phân biệt hoa thường": "بڑے چھوٹے حروف کا لحاظ",
        "Cả từ": "پورا لفظ",
        "Không có kết quả": "کوئی نتیجہ نہیں",
        "Thử biểu thức chính quy…": "قاعدہ اظہار آزمائیں…",
        "Chế độ Log (tô theo mức)": "لاگ وضع (درجے کے حساب سے رنگ)",
        "Lọc log theo mức…": "لاگ کو درجے کے حساب سے چھانیں…",
        "Chạy trên cả thư mục…": "پورے فولڈر پر چلائیں…",
        "Lọc qua lệnh ngoài…": "بیرونی حکم سے چھانیں…",
        "Script…": "اسکرپٹ…",
        "Gói mở rộng…": "توسیعی بستے…",
        "Cửa sổ mới": "نیا دریچہ",
        "Tách tab ra cửa sổ mới": "ٹیب کو نئے دریچے میں الگ کریں",
        "Chưa mở thư mục nào": "کوئی فولڈر کھلا نہیں",
        "Tìm file trong thư mục": "فولڈر میں فائل ڈھونڈیں",
        "Lọc theo tên": "نام کے حساب سے چھانیں",
        "File mới…": "نئی فائل…",
        "Thư mục mới…": "نیا فولڈر…",
        "Đổi tên…": "نام بدلیں…",
        "Chuyển vào Thùng rác": "ردی میں ڈالیں",
        "Hiện trong Finder": "Finder میں دکھائیں",
        "Đang đọc cấu trúc tài liệu…": "دستاویز کی ساخت پڑھی جا رہی ہے…",
        "file này không có hàm nào": "اس فائل میں کوئی فعل نہیں",
        "Không có gì khớp": "کوئی مماثل نہیں",
        "Văn bản thuần": "سادہ متن",
        "🔒 Chỉ đọc": "🔒 صرف پڑھنے کے لیے",
        "Đang theo dõi": "زیرِ نگرانی",
        "ngắt tại cột": "اس ستون پر لپیٹنا",
        "Cú pháp": "نحو",
        "Bấm để chèn vào ô truy vấn": "استفسار میں داخل کرنے کے لیے دبائیں",
        "truy vấn không hợp lệ": "غلط استفسار",
        "khóa `ten` ở gốc": "جڑ میں «نام» کلید",
        "khóa có dấu cách": "خالی جگہ والی کلید",
        "phần tử đầu": "پہلا عنصر",
        "mọi phần tử": "تمام عناصر",
        "lát cắt": "قطعہ",
        "hợp nhiều chỉ số": "اشاریوں کا اجتماع",
        "mọi khóa `gia` ở mọi tầng": "ہر درجے میں تمام «قیمت» کلیدیں",
        "mọi nút": "تمام گرہیں",
        "lọc theo số": "عدد کے حساب سے چھانیں",
        "lọc theo có mặt": "موجودگی کے حساب سے چھانیں",
        "Tới lỗi đầu tiên": "پہلی خامی پر جائیں",
        "Cột doanh_thu là số": "«آمدنی» ستون عددی ہے",
        "lọc…": "چھانیں…",
        "Hủy": "منسوخ کریں",
        "Thực hiện thay": "بدلنا انجام دیں",
        "xem trước": "پیش منظر",
        "tương tác": "متعامل",
        "Soạn thảo": "ترمیم",
        "Giao diện": "منظرِ عام",
        "Phím tắt": "کلیدی مختصرات",
        "Cỡ chữ": "متن کی جسامت",
        "Bề rộng TAB": "ٹیب کی چوڑائی",
        "Thụt lề bằng TAB": "ٹیب سے حاشیہ",
        "Tự động thụt lề khi xuống dòng": "نئی سطر پر خودکار حاشیہ",
        "Tô mọi kết quả tìm kiếm": "تلاش کے تمام نتائج نمایاں کریں",
        "Chuẩn hóa về NFC khi lưu": "محفوظ کرتے وقت NFC میں معیاری بنائیں",
        "Ngôn ngữ": "زبان",
        "Nền": "وضع قطع",
        "Theo hệ thống": "نظام کے مطابق",
        "Sáng": "روشن",
        "Tối": "تاریک",
        "Theme": "خیال",
        "Dùng preset Notepad++": "Notepad++ کا تیار مجموعہ استعمال کریں",
        "Về phím mặc định": "طے شدہ کلیدوں پر واپس جائیں",
        "Mở file cấu hình": "ترتیب کی فائل کھولیں",
        "Xuất theme hiện tại": "موجودہ خیال برآمد کریں",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "زبان کی تبدیلی اگلی بار چلانے پر پوری طرح لاگو ہوگی۔",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "طے شدہ کلیدیں اگلی بار چلانے پر واپس آئیں گی۔",
        "Xem trước Markdown": "Markdown پیش منظر",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "پیش منظر نظام کا Markdown انجن استعمال کرتا ہے: ابھی جدول نہیں اور کوڈ بلاک رنگین نہیں ہوتے۔",
        "Thử biểu thức chính quy": "قاعدہ اظہار آزمائیں",
        "Biểu thức": "اظہار",
        "Văn bản thử": "آزمائشی متن",
        "Kết quả": "نتیجہ",
        "Kết quả khớp": "مماثلتیں",
        "Biểu thức này làm gì": "یہ اظہار کیا کرتا ہے",
        "Giải thích biểu thức": "اظہار کی وضاحت",
        "Chế độ tìm kiếm": "تلاش کی وضع",
        "Kết quả tìm kiếm": "تلاش کے نتائج",
        "Không khớp chỗ nào": "کوئی مماثل نہیں",
        " (đã cắt bớt)": " (کاٹ دیا گیا)",
        "Bản đồ tài liệu": "دستاویز کا نقشہ",
        "Thanh tab": "ٹیب پٹی",
        "Hàng tiêu đề cột": "ستونوں کی سرخی کی سطر",
        "Không có cột nào": "کوئی ستون نہیں",
        "Cây thư mục workspace": "کام کی جگہ کا شجرہ",
        "Danh sách hàm và lớp": "افعال اور اصناف کی فہرست",
        "Kết quả tìm trong thư mục": "فولڈر میں تلاش کے نتائج",
        "Bảng dữ liệu CSV": "CSV مواد کا جدول",
        "Bàn làm sạch dữ liệu": "مواد صفائی کی میز",
        "Truy vấn JSONPath": "JSONPath استفسار",
        "Danh sách lỗi dữ liệu": "مواد کی خامیوں کی فہرست",
        "Bộ đánh giá golden set…": "سنہری مجموعے کا جانچ کار…",
        "So với điểm ngoài (JSONL)…": "بیرونی نمبروں سے موازنہ (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "بیرونی نمبروں کی فائل منتخب کریں (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "منتخب گرہ کا نام بدلیں",
        "Gộp các node đang chọn": "منتخب گرہیں ضم کریں",
        "Tách node đang chọn": "منتخب گرہ تقسیم کریں",
        "Trích subgraph đang chọn ra tab mới": "منتخب ذیلی گراف نئے ٹیب میں نکالیں",
        "Không có gì để đổi": "بدلنے کو کچھ نہیں",
        "%@ — áp %d thay đổi?": "‏%1$@ — کیا %2$d {one=تبدیلی|other=تبدیلیاں} لاگو کی جائیں؟",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "‏%1$@: %2$d {one=تبدیلی|other=تبدیلیاں} · Cmd-Z پورا مجموعہ کالعدم کرتا ہے",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "نشان کو ٹھیک ایک گرہ پر رکھیں اور دوبارہ کوشش کریں",
        "Đổi tên «%@»": "«%@» کا نام بدلیں",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "اس گرہ کا حوالہ دینے والے تمام کنارے اور عنوان بھی بدل جائیں گے۔",
        "Đổi tên node": "گرہ کا نام بدلیں",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "کم از کم دو گرہیں منتخب کریں اور دوبارہ کوشش کریں",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "معیاری صورت «%@» — سب سے عام، سب سے لمبی، اعراب سمیت",
        "Gộp node": "گرہیں ضم کریں",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "منتقل کرنے والی کناروں کی سطریں منتخب کریں اور دوبارہ کوشش کریں",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "تمام منتخب سطریں ٹھیک ایک گرہ کو چھونی چاہییں — مزید کناروں کی سطریں منتخب کریں",
        "Tách «%@» — chuyển %d cạnh": "«%1$@» تقسیم — %2$d {one=کنارہ|other=کنارے} منتقل",
        "Cạnh tới: %@": "اس کی طرف کنارے: %@",
        "Tách node": "گرہ تقسیم کریں",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "دستاویز محفوظ نہیں — نکالی گئی فائل کو ساتھ جگہ چاہیے",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "گراف کا وہ حصہ منتخب کریں جو نکالنا ہے اور دوبارہ کوشش کریں",
        "Gom biến thể entity → bảng duyệt": "اکائیوں کی صورتیں جمع کریں ← جانچ کا جدول",
        "Áp bảng duyệt đã sửa": "ترمیم شدہ جانچ کا جدول لاگو کریں",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "دستاویز محفوظ نہیں — جانچ کا جدول گراف فائل کے ساتھ ہونا چاہیے",
        "Không tìm thấy biến thể nào để gom": "جمع کرنے کے لیے کوئی صورت نہیں ملی",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "‏%d {one=صورت کا گروہ|other=صورتوں کے گروہ} — «canonical» ستون درست کریں اور «جانچ کا جدول لاگو کریں» چلائیں",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "«%@» جانچ کا جدول نہیں — پہلے «اکائیوں کی صورتیں جمع کریں» چلائیں",
        "Bảng duyệt không đọc được: %@": "جانچ کا جدول پڑھا نہیں جا سکتا: %@",
        "Bảng duyệt không có dòng nào cần đổi": "جانچ کے جدول میں بدلنے کے لیے کوئی سطر نہیں",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "گراف میں جانچ کے جدول سے کوئی جگہ مماثل نہیں",
        "Gom biến thể entity": "اکائیوں کی صورتیں جمع کریں",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "‏%d {one=تبدیلی لاگو|other=تبدیلیاں لاگو} · فرضی ناموں کا جدول اور نشانات کی فہرست فائل کے ساتھ لکھی گئی",
        "Áp %d thay đổi lên đồ thị?": "کیا گراف پر %d {one=تبدیلی|other=تبدیلیاں} لاگو کی جائیں؟",
        "%d alias → dạng chuẩn.": "‏%d {one=فرضی نام|other=فرضی نام} ← معیاری صورت۔",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "گرہیں ضم کریں (دوبارہ لکھنے سے کالعدم نہیں ہوتیں):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "‏%d {one=فرضی نام گراف میں نہیں، چھوڑ دیا گیا|other=فرضی نام گراف میں نہیں، چھوڑ دیے گئے}۔",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "ٹکڑا ↔ اکائی احاطے کا تجزیہ",
        "Xuất gói ngữ cảnh (JSONL)": "سیاق کا بستہ برآمد کریں (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "ٹکڑا ↔ اکائی ↔ گراف کا احاطہ",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=اکائی|other=اکائیاں} · %2$d {one=ٹکڑا|other=ٹکڑے} · %3$.0f٪ اکائیوں کا ذکر · %4$.0f٪ ٹکڑوں میں اکائی",
        "Entity không chunk nào nhắc tới": "وہ اکائیاں جن کا کوئی ٹکڑا ذکر نہیں کرتا",
        "Chunk mồ côi (không chứa entity nào)": "بے سہارا ٹکڑے (کسی اکائی کے بغیر)",
        "Node đồ thị không có entity đối ứng": "بغیر متعلقہ اکائی کے گراف گرہیں",
        "không có": "کوئی نہیں",
        "Phương pháp": "طریقہ",
        "Không dựng được ánh xạ Chunk ↔ Entity": "ٹکڑا ↔ اکائی کی مطابقت نہیں بنائی جا سکی",
        "Chấm sức khoẻ đồ thị": "گراف کی صحت جانچیں",
        "sức khoẻ đồ thị": "گراف کی صحت",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "صحت %1$@/100 · %2$d {one=خامی|other=خامیاں} · %3$d الٹ · %4$d بے سہارا",
        "Lai với đồ thị": "گراف کے ساتھ مخلوط",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "‏α = ۱: گراف کا اشارہ بالکل نظر انداز، نتیجہ خالص BM25 جیسا",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "‏α زیادہ: گراف BM25 کی درجہ بندی میں ہلکی سی درستی کرتا ہے",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "‏α طے شدہ ۰٫۷ کے قریب: BM25 راہ دکھاتا ہے، گراف درستی کرتا ہے",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "‏α کم: گراف راہ دکھاتا ہے، BM25 صرف برابری توڑتا ہے",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "‏α = ۰: صرف گراف کا اشارہ؛ بغیر اکائی والے ٹکڑے برابر رہتے ہیں",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "دستاویز محفوظ نہیں — مخلوط کو مجموعے کے ساتھ ایک گراف فائل چاہیے",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "گراف فائل «%@» نہیں ملی — مخلوط کو اپنے اشارے کے لیے یہ درکار ہے",
        "lai %.1f ms · %@": "مخلوط %.1f ملی سیکنڈ · %@",
        "Thuật toán…": "الگورتھم…",
        "PageRank (độ dày viền)": "PageRank ‏(کنارے کی موٹائی)",
        "Cộng đồng (màu nền)": "برادریاں (پس منظر کا رنگ)",
        "Thành phần liên thông": "جڑے ہوئے اجزا",
        "Xuất bảng node ra tab mới": "گرہوں کا جدول نئے ٹیب میں برآمد کریں",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "‏%1$d {one=جز|other=اجزا} · سب سے بڑا %2$d {one=گرہ|other=گرہیں} · %3$d بے سہارا گرہیں",
        "Tài liệu này không phải đồ thị DOT": "یہ دستاویز DOT گراف نہیں",
        "Không dựng được bảng node/cạnh: %@": "گرہ/کنارے کا جدول نہیں بنایا جا سکا: %@",
        "%d hàng · %@": "‏%d {one=سطر|other=سطریں} · %@",
        "Gán nhãn": "عنوان لگائیں",
        "Ghi chú (tuỳ chọn)": "نوٹ (اختیاری)",
        "Lưu record": "اندراج محفوظ کریں",
        "Xuất CSV": "CSV برآمد کریں",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "دستاویز محفوظ نہیں — جانچ کار کو مجموعے کی فائل کے ساتھ ہونا چاہیے",
        "Không nạp được bộ đánh giá: %@": "جانچ کار لادا نہیں جا سکا: %@",
        "Không lưu được: %@": "محفوظ نہیں کیا جا سکا: %@",
        "Bộ đánh giá chưa có record nào": "جانچ کار کے پاس ابھی کوئی اندراج نہیں",
        "Không ghi được: %@": "لکھا نہیں جا سکا: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "یہ دستاویز نہ ‎.mmd فائل ہے، نہ DOT، اور اس میں mermaid بلاک بھی نہیں۔",
        "%d node · %d cạnh · ⚠ %@": "‏%d {one=گرہ|other=گرہیں} · %d {one=کنارہ|other=کنارے} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid خاکہ: عنصر شامل کریں…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid خاکہ: منتخب دو عناصر جوڑیں",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid خاکہ: منتخب عنصر کا عنوان بدلیں…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid خاکہ: منتخب عنصر حذف کریں",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid خاکہ: پیغام اوپر لے جائیں",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid خاکہ: پیغام نیچے لے جائیں",
        "Thêm phần tử": "عنصر شامل کریں",
        "Thêm participant": "شریک شامل کریں",
        "Thêm mục": "اندراج شامل کریں",
        "Thêm mục sơ đồ": "خاکے میں اندراج شامل کریں",
        "Sửa mục sơ đồ": "خاکے کا اندراج بدلیں",
        "Xoá mục sơ đồ": "خاکے کا اندراج حذف کریں",
        "Xoá phần tử": "عنصر حذف کریں",
        "Sửa nhãn": "عنوان بدلیں",
        "Đổi thứ tự message": "پیغامات کی ترتیب بدلیں",
        "Tên mục": "اندراج کا نام",
        "Mục mới": "نیا اندراج",
        "Tên mục hiện trên sơ đồ.": "اندراج کا نام خاکے پر نظر آتا ہے۔",
        "Bảng thuộc tính sơ đồ": "خاکے کی خصوصیات کا جدول",
        "Tài liệu này không có khối mermaid nào": "اس دستاویز میں mermaid بلاک نہیں",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "خاکے کے ماخذ میں شناخت — خالی جگہ کے بغیر۔ عنوان بعد میں دوہری کلک سے بدلا جاتا ہے۔",
        "Để trống thì hiện chính định danh.": "خالی چھوڑیں تو خود شناخت دکھائی جاتی ہے۔",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "صرف نظر آنے والا عنوان بدلتا ہے؛ عنصر کی شناخت وہی رہتی ہے۔",
        "Không rõ «%@» là phần tử nào": "واضح نہیں کہ «%@» کون سا عنصر ہے",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "ٹھیک دو عناصر منتخب کریں اور دوبارہ کوشش کریں",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "نشان کو ٹھیک ایک عنصر پر رکھیں اور دوبارہ کوشش کریں",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "حذف کرنے کے لیے ایک عنصر چنیں، یا کنارے سے جڑے دو عناصر",
        "Xoá «%@» và %d cạnh chạm nó?": "کیا «%1$@» اور اسے چھونے والے %2$d {one=کنارے کو حذف کیا جائے|other=کنارے حذف کیے جائیں}؟",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "ان کناروں کے دوسرے سرے کی گرہیں رہ جاتی ہیں — اگر کنارے کا بیان ان کا واحد اعلان تھا تو وہ عنوان سمیت دوبارہ بیان کی جاتی ہیں۔",
        "Sơ đồ «%@» chỉ soạn text — %@": "خاکہ «%1$@» صرف متن کے طور پر بدلا جاتا ہے — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "‏%@: جوڑنے کے لیے دو عناصر کے درمیان کھینچیں، عنوان بدلنے کے لیے دوہری کلک کریں",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "‏%@: پیغام شامل کرنے کے لیے دو شرکا کے درمیان کھینچیں؛ ترتیب «اوزار» مینو سے بدلیں",
        "%@: sửa trong bảng thuộc tính bên dưới": "‏%@: نیچے خصوصیات کے جدول میں ترمیم کریں",
        "Soạn trực quan đã bật": "بصری ترمیم چالو",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "‏%1$@ · %2$d {one=اندراج|other=اندراج} — سیدھا جدول میں ترمیم کریں، ہر خانہ ایک کالعدم قدم ہے",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "دائرہ خاکے کے لیے ایک عدد؛ گانٹ کے لیے وقفے کے بعد کا حصہ۔",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid خاکہ: بلاک ‎.mmd فائل میں نکالیں…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid خاکہ: حوالہ دی گئی فائل دوبارہ شامل کریں",
        "Tách khối sơ đồ": "خاکے کا بلاک نکالیں",
        "Nhúng khối sơ đồ": "خاکے کا بلاک شامل کریں",
        "Tách khối sơ đồ ra tệp riêng": "خاکے کا بلاک الگ فائل میں نکالیں",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "فائل دستاویز کے ساتھ رکھی جاتی ہے؛ بلاک میں حوالے کی ایک سطر رہتی ہے تاکہ ترمیم ایک ہی جگہ ہو۔",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "دستاویز محفوظ نہیں — خاکے کی فائل کو ساتھ جگہ چاہیے",
        "Đã có tệp «%@» — chọn tên khác": "فائل «%@» پہلے سے موجود ہے — کوئی اور نام چنیں",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "«%@» میں نکال دیا گیا — بلاک میں حوالے کی ایک سطر رہ گئی",
        "Mở tệp": "فائل کھولیں",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» دوبارہ شامل ہو گئی؛ فائل اب بھی ڈسک پر ہے",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "اس بلاک میں حوالہ نہیں بلکہ اصل خاکہ ہے",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "یہ بلاک «%@» کا حوالہ دیتا ہے — ترمیم کے لیے وہ فائل کھولیں",
        "Không đọc được tệp sơ đồ %@": "خاکے کی فائل %@ پڑھی نہیں جا سکی",
        "Soạn trực quan": "بصری ترمیم",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "کنارہ شامل کرنے کے لیے ایک گرہ سے دوسری تک کھینچیں؛ عنوان بدلنے کے لیے دوہری کلک کریں۔ ہر عمل ایک کالعدم قدم ہے۔",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "بصری ترمیم: کنارہ شامل کرنے کے لیے دو گرہوں کے درمیان کھینچیں، عنوان بدلنے کے لیے دوہری کلک کریں",
        "Soạn trực quan đã tắt": "بصری ترمیم بند",
        "Thêm node…": "گرہ شامل کریں…",
        "Thêm cạnh giữa hai node đang chọn…": "منتخب دو گرہوں کے درمیان کنارہ شامل کریں…",
        "Sửa nhãn node đang chọn…": "منتخب گرہ کا عنوان بدلیں…",
        "Xoá node/cạnh đang chọn": "منتخب گرہ/کنارہ حذف کریں",
        "Thêm node": "گرہ شامل کریں",
        "Thêm cạnh": "کنارہ شامل کریں",
        "Sửa nhãn node": "گرہ کا عنوان بدلیں",
        "Xoá node": "گرہ حذف کریں",
        "Xoá cạnh": "کنارہ حذف کریں",
        "Cmd-Z hoàn tác": "‏Cmd-Z کالعدم کرتا ہے",
        "Tài liệu đang ở chế độ chỉ đọc": "یہ دستاویز صرف پڑھنے کے لیے ہے",
        "Nhãn của «%@»": "«%@» کا عنوان",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "صرف نظر آنے والا عنوان بدلتا ہے؛ گرہ کی شناخت وہی رہتی ہے۔",
        "Không rõ «%@» là node nào": "واضح نہیں کہ «%@» کون سی گرہ ہے",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "DOT فائل میں گرہ کی شناخت۔ عنوان بعد میں خاکے پر دوہری کلک سے بدلا جاتا ہے۔",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "ٹھیک دو گرہیں منتخب کریں اور دوبارہ کوشش کریں",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "حذف کرنے کے لیے ایک گرہ چنیں، یا کنارے سے جڑی دو گرہیں",
        "Xoá node «%@» và %d cạnh chạm nó?": "کیا گرہ «%1$@» اور اسے چھونے والے %2$d {one=کنارے کو حذف کیا جائے|other=کنارے حذف کیے جائیں}؟",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "اگر لٹکتے کنارے رہ جائیں تو DOT انہی سے گرہیں دوبارہ بنا دیتا ہے — حذف کی گئی گرہ اگلی بار بناتے وقت پھر نمودار ہو گی۔",
        "Phòng thí nghiệm truy hồi BM25": "BM25 بازیافت کی تجربہ گاہ",
        "Câu hỏi — Enter để tìm": "سوال — تلاش کے لیے Enter",
        "Đánh giá…": "جانچیں…",
        "Đang dựng chỉ mục": "اشاریہ بنایا جا رہا ہے",
        "Không chunk nào khớp": "کوئی ٹکڑا مماثل نہیں",
        "kết quả trên": "بہترین نتائج",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "‏k1 = ۰: ہر لفظ صرف ایک بار گنا جاتا ہے، چاہے کتنی بار آئے",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "‏k1 کم: لفظ دہرانے سے نمبر تقریباً نہیں بڑھتے",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "‏k1 طے شدہ ۱٫۲ کے قریب: دہرانے سے نمبر بڑھتے ہیں، مگر گھٹتے ہوئے",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "‏k1 زیادہ: کسی لفظ کو بہت دہرانے والے ٹکڑے کو بھاری انعام ملتا ہے",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "‏b = ۰: لمبائی نظر انداز، لمبے ٹکڑوں پر جرمانہ نہیں",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "‏b کم: لمبے ٹکڑوں پر ہلکا سا جرمانہ",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "‏b طے شدہ ۰٫۷۵ کے قریب: لمبے ٹکڑوں پر معتدل جرمانہ",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "‏b = ۱: لمبائی پر سب سے زیادہ جرمانہ، چھوٹے ٹکڑوں کو ترجیح",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: بازیافت کی تجربہ گاہ…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "دستاویز محفوظ نہیں — BM25 اشاریہ مجموعے کی فائل کے ساتھ رہتا ہے، اس لیے راستہ درکار ہے",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "یہ فائل JSONL نہیں — Retrieval Lab ٹکڑوں کے مجموعے پر چلتا ہے",
        "Không dựng được chỉ mục BM25 cho tệp này": "اس فائل کے لیے BM25 اشاریہ نہیں بنایا جا سکا",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "دستاویز محفوظ نہیں — رپورٹ بنانے کے لیے مجموعے کا راستہ درکار ہے",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "جانچ کا مجموعہ منتخب کریں (CSV یا JSONL: سوال + متوقع ٹکڑے کی شناخت)",
        "Đánh giá truy hồi": "بازیافت کی جانچ",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "اوپر k1، b یا k بدلیں اور دوبارہ دیکھیں تاکہ دو ترتیبوں کا موازنہ ہو؛ ایک «compare» بلاک شامل کریں تاکہ ایک ہی جانچ مجموعے پر دو متغیر مجموعے ساتھ ساتھ چلیں۔",
        "Lỗi": "خامی",
        "   (%d…%d, trung bình %.0f)": "   ‏(%d…%d، اوسط %.0f)",
        "Chế độ JSONL": "JSONL وضع",
        "Bản ghi": "اندراج",
        "Chi tiết": "تفصیل",
        "Bản ghi ở dòng": "سطر میں اندراج",
        "không phải JSON hợp lệ": "درست JSON نہیں",
        "bản ghi": "اندراج",
        "dòng trắng": "خالی سطریں",
        "không phải đối tượng": "شے نہیں",
        "bảng hiện": "دکھایا گیا جدول",
        "ĐÃ HUỶ giữa chừng": "درمیان میں منسوخ",
        "Không lọc": "بغیر چھانٹ",
        "bản ghi khớp bộ lọc": "چھانٹ سے مماثل اندراج",
        "Đưa con nháy tới một dòng để xem bản ghi": "اندراج دیکھنے کے لیے نشان کسی سطر پر رکھیں",
        "Không có bản ghi nào hỏng": "کوئی خراب اندراج نہیں",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "ابھی جانچا نہیں گیا۔ تصدیق کے بعد «JSONL: ٹکڑے جانچیں» دوبارہ چلائیں۔",
        "trường văn bản": "متنی خانہ",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "خاکہ (اندازہ — کوئی اور خانہ چن کر بدلا جا سکتا ہے)",
        "văn bản": "متن",
        "định danh": "شناخت",
        "metadata lồng": "نتھی فوق مواد",
        "TRƯỜNG": "خانہ",
        "phủ": "احاطہ",
        "nhiều kiểu": "کئی اقسام",
        "ĐỘ DÀI — ký tự": "لمبائی — حروف",
        "ĐỘ DÀI — từ": "لمبائی — الفاظ",
        "ĐỘ DÀI — token ước lượng": "لمبائی — تخمینی نشان",
        "RỖNG VÀ TRÙNG": "خالی اور دہرائے",
        "chunk rỗng": "خالی ٹکڑے",
        "dòng": "سطریں",
        "nhóm trùng chính xác": "بالکل یکساں دہرائے کے گروہ",
        "dòng không đọc được, không vào thống kê": "سطریں پڑھی نہیں جا سکتیں، شماریات سے باہر",
        "PHƯƠNG PHÁP": "طریقہ",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«حروف» یونی کوڈ حروف (اسکیلر) گنے جاتے ہیں، نظر آنے والے مجموعے نہیں",
        "«từ» tách theo khoảng trắng ASCII": "«الفاظ» ASCII خالی جگہوں پر جدا کیے جاتے ہیں",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«نشان» ایک ہجائی جدا کار سے گنے جاتے ہیں — نمونے کا جدا کار نہیں",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«دہرا» کا مطلب بالکل یکساں دہرا ہے؛ تقریباً یکساں ‎```quality بلاک میں ہیں",
        "chunk": "ٹکڑے",
        "JSONL: kiểm và soi chunk…": "JSONL: ٹکڑوں کی تصدیق اور جانچ…",
        "Ảnh": "تصویر",
        "PDF": "PDF",
        "Tài liệu Word": "Word دستاویز",
        "Bảng tính Excel": "Excel ورق",
        "Bản trình chiếu PowerPoint": "PowerPoint پیشکش",
        "File nén": "محفوظہ",
        "Vừa khung": "دریچے میں سمائیں",
        "Chép ảnh": "تصویر نقل کریں",
        "Xoay": "گھمائیں",
        "Không đọc được ảnh «%@»": "تصویر «%@» پڑھی نہیں جا سکتی",
        "Đã chép ảnh vào clipboard": "تصویر تختۂ تراشہ میں نقل ہو گئی",
        "Bôi vàng": "پیلے سے نمایاں کریں",
        "Gạch chân": "خط کشیدہ",
        "Ghi chú…": "نوٹ…",
        "Bỏ chú thích": "حواشی ہٹائیں",
        "Lấy chữ ra tab mới": "متن نئے ٹیب میں نکالیں",
        "Lưu bản có chú thích…": "حواشی والا نسخہ محفوظ کریں…",
        "Tìm trong PDF": "PDF میں تلاش کریں",
        "Thêm": "شامل کریں",
        "Trang %d/%d": "صفحہ %d/%d",
        "Trang %d": "صفحہ %d",
        "Kết quả %d/%d": "نتیجہ %d/%d",
        "0 kết quả": "۰ نتائج",
        "Không đọc được PDF «%@»": "PDF «%@» پڑھی نہیں جا سکتی",
        "PDF này có mật khẩu — chưa mở được nội dung": "یہ PDF کلمۂ شناخت سے محفوظ ہے — مواد تک رسائی نہیں",
        "Không thấy «%@» trong tài liệu": "دستاویز میں «%@» نہیں ملا",
        "Đã bôi vàng": "نمایاں ہو گیا",
        "Đã gạch chân": "خط کشیدہ ہو گیا",
        "Hãy bôi đen một đoạn chữ trước": "پہلے متن کا کوئی حصہ منتخب کریں",
        "Đã thêm ghi chú": "نوٹ شامل ہو گیا",
        "Trang này chưa có chú thích nào": "اس صفحے پر کوئی حاشیہ نہیں",
        "Đã bỏ %d chú thích trên trang này": "اس صفحے سے %d {one=حاشیہ ہٹا دیا گیا|other=حواشی ہٹا دیے گئے}",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "اس PDF میں متن کی تہہ نہیں — غالباً یہ عکس ہے",
        "Không ghi được tệp": "فائل لکھی نہیں جا سکی",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "لکھی گئی فائل ٹھیک سے دوبارہ نہیں کھلتی — یہ نسخہ استعمال نہ کریں",
        "Đã lưu %@ · %d trang": "‏%@ محفوظ ہوا · %d {one=صفحہ|other=صفحات}",
        "Tên": "نام",
        "Kích thước": "جسامت",
        "Đã nén": "سکیڑا ہوا",
        "Tỉ lệ": "تناسب",
        "Sửa lúc": "بدلا گیا",
        "Mở mục đang chọn": "منتخب شے کھولیں",
        "Bung ra thư mục…": "ایک فولڈر میں کھولیں…",
        "Bung vào đây": "یہیں کھولیں",
        "%d mục": "‏%d {one=شے|other=اشیا}",
        "giải nén ra %@": "‏%@ میں کھول دیا گیا",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— Office فائل کے اندر ایک محفوظہ ہوتا ہے؛ یہ اس کے اجزا ہیں",
        "Đã bung %d mục": "‏%d {one=شے کھل گئی|other=اشیا کھل گئیں}",
        "%d mục hỏng": "‏%d {one=شے خراب|other=اشیا خراب}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "‏%d {one=شے مسترد|other=اشیا مسترد}، کیونکہ ان کے راستے منزل فولڈر سے باہر جاتے ہیں",
        "Không mở được mục này": "یہ شے کھولی نہیں جا سکتی",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "‏%@ میں ابھی براہِ راست واپس نہیں لکھا جا سکتا — «بطور محفوظ کریں…» استعمال کریں",
        "Không có gì đổi": "کچھ نہیں بدلا",
        "Đã ghi %d ô vào %@": "‏%2$@ میں %1$d {one=خانہ لکھا گیا|other=خانے لکھے گئے}",
        "Đã ghi %d đoạn vào %@": "‏%2$@ میں %1$d {one=پیرا لکھا گیا|other=پیرا لکھے گئے}",
        "Không ghi được vào tệp — bản gốc còn nguyên": "فائل میں لکھا نہیں جا سکا — اصل جوں کی توں ہے",
        "dựng bài": "آزمائشی صورت تیار کریں",
        "Không ghi được settings.json": "settings.json میں لکھا نہیں جا سکا",
        "Xoay trái": "بائیں گھمائیں",
        "Xoay phải": "دائیں گھمائیں",
        "Trang lên": "صفحہ اوپر لے جائیں",
        "Trang xuống": "صفحہ نیچے لے جائیں",
        "Xoá trang…": "صفحات حذف کریں…",
        "Xoá trang": "صفحات حذف کریں",
        "Trích trang…": "صفحات نکالیں…",
        "Trích trang ra tệp mới": "صفحات نئی فائل میں نکالیں",
        "Gộp tệp PDF…": "PDF فائل ضم کریں…",
        "Tách tệp…": "فائل تقسیم کریں…",
        "Tách tệp PDF": "PDF فائل تقسیم کریں",
        "Xuất ảnh…": "تصاویر برآمد کریں…",
        "Xuất trang ra ảnh PNG": "صفحات کو PNG تصاویر کے طور پر برآمد کریں",
        "Hoàn tác trang": "صفحہ ترمیم واپس لیں",
        "Lưu bản đã sửa…": "ترمیم شدہ نقل محفوظ کریں…",
        "Phát": "چلائیں",
        "Tạm dừng": "وقفہ",
        "Xem bình thường": "عام منظر",
        "Chọn sheet": "شیٹ منتخب کریں",
        "Mở sheet": "شیٹ کھولیں",
        "Bỏ và đổi sheet": "ترک کریں اور شیٹ بدلیں",
        "Bảng tính có %d sheet.": "ورک بک میں %d شیٹس ہیں۔",
        "Bảng tính này chỉ có một sheet: «%@»": "اس ورک بک میں صرف ایک شیٹ ہے: «%@»",
        "Bỏ phần chưa lưu của sheet này?": "اس شیٹ کی غیر محفوظ تبدیلیاں ترک کریں؟",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "شیٹ بدلنے سے پورا ٹیب بدل جاتا ہے۔ جو ⌘S سے محفوظ نہیں ہوا وہ ضائع ہو جائے گا۔",
        "Chọn tệp PDF cần gộp vào": "ضم کرنے کے لیے PDF فائل منتخب کریں",
        "Chọn thư mục ghi ảnh": "تصاویر کے لیے فولڈر منتخب کریں",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "محفوظ کرنے کی جگہ منتخب کریں۔ دوسری فائل اسی کے ساتھ لکھی جائے گی۔",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "دستاویز میں %d صفحات ہیں۔ حذف کرنے والے صفحات لکھیں، مثلاً 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "دستاویز میں %d صفحات ہیں۔ نکالنے والے صفحات لکھیں، مثلاً 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "دستاویز میں %d صفحات ہیں۔ برآمد کرنے والے صفحات لکھیں، مثلاً 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "دستاویز میں %d صفحات ہیں۔ الگ کرنے والا حصہ لکھیں، مثلاً 1-5؛ باقی دوسری فائل بن جائے گا۔",
        "Đã xoay trang %d": "صفحہ %d گھمایا گیا",
        "Đã xoá trang %@ · còn %d trang": "صفحات %@ حذف ہوئے · %d صفحات باقی",
        "Đã gộp %d trang từ «%@»": "«%2$@» سے %1$d صفحات ضم ہوئے",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "%@ (%d صفحات) اور %@ (%d صفحات) میں تقسیم ہوا",
        "Đã ghi %@ — %@ · %d trang": "%@ لکھا گیا — %@ · %d صفحات",
        "Đã xuất %d ảnh vào %@": "%d تصاویر %@ میں برآمد ہوئیں",
        "Chỉ xuất được %d/%d ảnh": "صرف %d از %d تصاویر برآمد ہوئیں",
        "Đã hoàn tác một thao tác trang": "ایک صفحہ عمل واپس لیا گیا",
        "Không còn thao tác trang nào để hoàn tác": "واپس لینے کے لیے کوئی صفحہ عمل باقی نہیں",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "تمام صفحات حذف نہیں ہو سکتے — PDF میں کم از کم ایک صفحہ ہونا چاہیے",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "یہ حد پوری دستاویز ہے — الگ کرنے کو کچھ نہیں",
        "«%@» có mật khẩu — chưa gộp được": "«%@» پاس ورڈ سے محفوظ ہے — ضم نہیں ہو سکا",
        "«%@» không có trang nào": "«%@» میں کوئی صفحہ نہیں",
        "Đã ở trang đầu": "پہلے ہی پہلے صفحے پر",
        "Đã ở trang cuối": "پہلے ہی آخری صفحے پر",
        "· đã sửa, chưa lưu": "· ترمیم شدہ، غیر محفوظ",
        "Ảnh động · %d khung": "متحرک تصویر · %d فریم",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "غیر محفوظ دستاویز — بائنری منظر کے لیے ڈسک پر کوئی فائل نہیں",
        "Lệnh này chỉ dùng cho bảng tính Excel": "یہ کمانڈ صرف Excel ورک بکس کے ساتھ کام کرتی ہے",
        "Không đọc được danh sách sheet": "شیٹس کی فہرست نہیں پڑھی جا سکی",
        "Không có sheet «%@»": "«%@» نام کی کوئی شیٹ نہیں",
        "Không đọc được sheet «%@»": "شیٹ «%@» نہیں پڑھی جا سکی",
        "Sheet «%@» · %d hàng": "شیٹ «%@» · %d قطاریں",
        "phần còn lại": "باقی",
        "Lưu ý": "نوٹ",
        "Cẩn thận": "احتیاط",
        "Xem thêm": "مزید دیکھیں",
        "Chép": "نقل کریں",
        "Đã chép": "نقل ہو گیا",
        "Chép đoạn mã mẫu": "نمونہ کوڈ نقل کریں",
        "Tìm trong trợ giúp": "مدد میں تلاش کریں",
        "Lùi": "واپس",
        "Bắt đầu dùng": "شروع کریں",
        "Không mở cửa sổ này khi khởi động nữa": "اسٹارٹ اپ پر یہ ونڈو نہ دکھائیں",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "مدد ابھی اس زبان میں ترجمہ نہیں ہوئی — ویتنامی متن دکھایا جا رہا ہے۔",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "آفسیٹ پر جائیں (مثلاً 1F400 یا 0x1F400)",
        "Chép dòng đã chọn": "منتخب قطاریں نقل کریں",
        "Đã chép %d dòng": "%d قطاریں نقل ہوئیں",
        "Không đọc được «%@»": "«%@» نہیں پڑھا جا سکا",
        "Tệp rỗng": "خالی فائل",
        "Không đọc được offset «%@»": "آفسیٹ «%@» نہیں پڑھا جا سکا",
        "Offset 0x%@ vượt quá cỡ tệp": "آفسیٹ 0x%@ فائل کے حجم سے باہر ہے",
        "Mở bằng ứng dụng khác…": "دوسری ایپ سے کھولیں…",
        "%d kênh": "%d چینلز",
        "Không phát được «%@»": "«%@» نہیں چل سکا",
        "Không phát được — %@": "چل نہیں سکا — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS میں %@ فارمیٹ کے لیے ڈی کوڈر نہیں ہے — یہ نظام کی حد ہے، خراب فائل نہیں۔",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "آپ اب بھی بائٹس کو بائنری منظر میں دیکھ سکتے ہیں، یا اسے اپنے ڈی کوڈر والی ایپ سے کھول سکتے ہیں۔",
        "Ký…": "دستخط…",
        "Sửa chữ…": "متن میں ترمیم…",
        "Sửa chữ": "متن میں ترمیم",
        "Vẽ đè": "اوپر بنائیں",
        "Ô chưa điền": "اگلا خالی خانہ",
        "Xoá nội dung đã điền": "بھرے گئے مواد صاف کریں",
        "Tệp này không có ô biểu mẫu nào": "اس فائل میں کوئی فارم خانہ نہیں",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d فارم خانے صاف ہوئے",
        "Mọi ô biểu mẫu đều đã có nội dung": "تمام فارم خانے پہلے ہی بھرے ہوئے ہیں",
        "Còn %d ô chưa điền": "%d خانے ابھی خالی ہیں",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "پُر کرنے کے قابل فارم: %d خانے۔ براہِ راست لکھیں، پھر «ترمیم شدہ نقل محفوظ کریں…»",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "دستخط کی تصویر منتخب کریں (شفاف پس منظر بہترین لگتا ہے)",
        "Không dựng được trang có chữ ký": "دستخط شدہ صفحہ نہیں بن سکا",
        "Đã chèn chữ ký vào trang %d": "صفحہ %d پر دستخط داخل ہوا",
        "Hãy bôi chọn phần chữ cần sửa trước": "پہلے وہ متن منتخب کریں جسے بدلنا ہے",
        "Vùng chọn quá nhỏ": "منتخب حصہ بہت چھوٹا ہے",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "نیا متن سسٹم فونٹ سے منتخب حصے کے اوپر بنایا جاتا ہے۔ پرانا متن ڈھک جاتا ہے، مٹتا نہیں — وہ اب بھی نکالا جا سکتا ہے، اس لیے یہ سیاہ کرنے کا طریقہ نہیں۔",
        "Không dựng được trang đã sửa": "ترمیم شدہ صفحہ نہیں بن سکا",
        "Đã vẽ đè chữ mới lên trang %d": "نیا متن صفحہ %d پر بنایا گیا",
        "Đổi chế độ View / Code": "منظر / کوڈ تبدیل کریں",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "JSON · XML · YAML کے لیے ابھی درختی منظر نہیں",
        "Chưa có chế độ View dạng sơ đồ trong tab": "ٹیب میں خاکہ منظر ابھی نہیں",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "PowerPoint کے لیے خاکہ منظر ابھی نہیں",
        "Tệp này chỉ có một chế độ hiển thị": "اس فائل کا صرف ایک ڈسپلے موڈ ہے",
        "%d nút": "%d نوڈز",
        "Không dựng được cây: %@": "درخت نہیں بن سکا: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "دستاویز درخت بنانے کے لیے بہت بڑی ہے — کوڈ موڈ استعمال کریں",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "اس فائل کے صفحات نہیں بنائے جا سکے \u{2014} Code موڈ استعمال کریں۔",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "سلائیڈیں متن سے بنائی گئی ہیں؛ اصل تصاویر اور ترتیب ابھی نہیں بنائی گئیں۔",
        "Vừa ngang": "چوڑائی کے مطابق",
        "Thu nhỏ trang": "صفحہ چھوٹا کریں",
        "Phóng to trang": "صفحہ بڑا کریں",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "اس دستاویز میں «%@» نہیں ملا",
        "Chỗ khớp %d/%d": "مماثلت %d از %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "صفحے پر کوئی متن منتخب نہیں ہے۔",
        "%d ký tự": "%d حروف",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "جن فائلوں میں View ہو انہیں براہِ راست View موڈ میں کھولیں",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· بیچ میں منسوخ — جدول نامکمل ہے",
        "Chế độ hiển thị": "نمائش موڈ",
        "Đổi giữa View và Code (⌥⌘V)": "View اور Code کے درمیان تبدیل کریں (⌥⌘V)",
        "Trang tài liệu": "دستاویز کے صفحات",
        "Chữ đã dựng": "ترتیب شدہ متن",
        "Trang bảng tính": "اسپریڈ شیٹ کے صفحات",
        "Sơ đồ": "خاکہ",
        "Cây khoá–giá trị": "کلید–قدر شجرہ",
        "Bộ phát": "پلیئر",
        "Danh sách mục": "اندراجات کی فہرست",
        "Báo cáo đã dựng": "تیار رپورٹ",
        "Tô theo mức": "سطح کے مطابق رنگ",
        "Trang slide": "سلائیڈ کے صفحات",
        "Dàn ý": "خاکہ بندی",
        "Lưu rồi dựng lại": "محفوظ کر کے دوبارہ بنائیں",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "ڈسک پر موجود نقل دکھا رہا ہے — غیر محفوظ تبدیلیاں اس میں نہیں ہیں۔",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "نظام دستاویز کا منظر نہ بنا سکا — Code موڈ استعمال کریں۔",
        "Lưu tệp trước khi xem trang.": "صفحات دیکھنے سے پہلے فائل محفوظ کریں۔",
        "Đang ở chế độ Code": "اس وقت Code موڈ میں",
        "Đang ở chế độ View": "اس وقت View موڈ میں",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "آپ ماخذ دیکھ رہے ہیں — View موڈ کے لیے کلک کریں (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "View موڈ میں — ماخذ پر واپس جانے کے لیے کلک کریں (⌥⌘V)",
        "Tín hiệu: %@": "سگنل: %@",
        "Lý do: %@": "وجہ: %@",
        "Chi tiết: %@": "تفصیل: %@",
        "Mở báo cáo": "رپورٹ کھولیں",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor %@ پر اچانک بند ہو گیا — پڑھنے کے لیے رپورٹ کھولیں؛ کچھ بھی نہیں بھیجا جاتا۔",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "لگیچر — بند ہوں تو ہر حرف اپنے خانے میں رہتا ہے",
        "Chế độ CSV": "CSV موڈ",
        "Dấu phân tách": "جدا کنندہ",
        "Tự nhận diện": "خودکار شناخت",
        "Dấu phân tách: %@": "جدا کنندہ: %@",
        "Theo đuôi tệp": "فائل کی توسیع کے مطابق",
        "%d dấu cách": "%d خالی جگہ",
        "Tài liệu đang sửa được": "یہ دستاویز قابلِ ترمیم ہے",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "صرف پڑھنے کے لیے کیونکہ فائل کی نگرانی ہو رہی ہے — ترمیم کے لیے نگرانی روکیں",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "صرف پڑھنے کے لیے کیونکہ ڈسک کی فائل میں لکھا نہیں جا سکتا",
        "Đã mở khoá — tài liệu sửa được": "کھل گیا — دستاویز دوبارہ قابلِ ترمیم ہے",
        "Nhân bản tệp": "فائل کی نقل",
        "Đổi tên tệp…": "فائل کا نام بدلیں…",
        "Chuyển tệp tới…": "فائل یہاں منتقل کریں…",
        "XML: đánh giá XPath…": "XML: XPath جانچیں…",
        "Đánh giá XPath": "XPath جانچیں",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "مثال: //order/item[2]/@code · //*[@kind='A'] · count(//item)",
        "Đánh giá": "جانچیں",
        "XPath không đọc được: %@": "یہ XPath پڑھا نہیں جا سکا: %@",
        "XPath «%@» không khớp node nào": "XPath «%@» کسی نوڈ سے نہیں ملا",
        "XPath «%@» — %d node": "XPath «%@» — %d نوڈ",
        "XPath «%@»: %d node": "XPath «%@»: %d نوڈ",
        "Lưu tệp trước khi nhân bản.": "نقل بنانے سے پہلے فائل محفوظ کریں۔",
        "Không nhân bản được": "نقل نہ بن سکی",
        "Đã nhân bản thành %@": "%@ کے نام سے نقل بن گئی",
        "Lưu tệp trước khi đổi tên.": "نام بدلنے سے پہلے فائل محفوظ کریں۔",
        "Đổi tên tệp": "فائل کا نام بدلیں",
        "Tên hiện tại: %@": "موجودہ نام: %@",
        "Đổi tên": "نام بدلیں",
        "Tên tệp không hợp lệ": "یہ فائل کا نام درست نہیں",
        "Đã có tệp tên %@ ở đó": "وہاں پہلے سے %@ نام کی فائل موجود ہے",
        "Lưu tệp trước khi chuyển.": "منتقل کرنے سے پہلے فائل محفوظ کریں۔",
        "Chuyển tới": "یہاں منتقل کریں",
        "Thư mục đích đã có tệp tên %@": "ہدف فولڈر میں پہلے سے %@ نام کی فائل ہے",
        "Không chuyển được tệp": "فائل منتقل نہ ہو سکی",
        "Đã chuyển tới %@": "%@ پر منتقل ہو گئی",
        "Bảng mã:": "انکوڈنگ:",
        "Xuống dòng:": "سطر کے اختتام:",
        "Riêng cho %@": "صرف %@ کے لیے",
        "    %d — dùng TAB": "    %d — ٹیب استعمال کریں",
        "    %d — dùng dấu cách": "    %d — خالی جگہ استعمال کریں",
        "    Bỏ khai riêng, dùng cài đặt chung": "    الگ اصول ہٹا کر عمومی ترتیب استعمال کریں",
        "%@: thụt lề %d %@": "%@: حاشیہ %d %@",
        "TAB": "ٹیب",
        "dấu cách": "خالی جگہ",
        "Xuất": "برآمد",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "نتائج متن کے ٹیب کے طور پر کھولیں — ⌘S سے محفوظ کریں",
        "Lượt tìm trước đó": "پچھلی تلاشیں",
        "«%@» — %d kết quả": "«%@» — %d نتائج",
        "Kết quả tìm «%@»": "«%@» کے تلاش کے نتائج",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "فائل کے نام چھانیں — مثلاً *.csv;*.log (خالی: ہر متن فائل)",
        "Thư mục %@ không có file văn bản nào": "فولڈر %@ میں کوئی متن فائل نہیں",
        "Không tệp nào trong %@ khớp «%@»": "%@ میں کوئی فائل «%@» سے نہیں ملتی",
        "%d byte · %d dòng": "%d بائٹ · %d سطریں",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d بائٹ · %d سطریں — حروف اور الفاظ گننے کے لیے بہت بڑی",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d بائٹ · %d حروف · %d الفاظ · %d سطریں",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "اس دستاویز میں %d سطریں، %d بائٹ ہیں۔ سطر نمبر، «سطر,کالم» یا «@بائٹ» لکھیں۔",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "«%@» پڑھا نہیں جا سکا — سطر نمبر، «سطر,کالم» یا «@بائٹ» لکھیں",
    ]
}
