import Foundation

/// Bảng dịch tiếng Trung phồn thể. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let zhHant: [String: String] = [
        "Bản đã lưu…": "已儲存的版本…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "此文件從未儲存過 — 沒有歷史記錄",
        "Chưa có bản đã lưu nào trước đó": "沒有更早的已儲存版本",
        "Không đọc được bản ấy": "無法讀取該版本",
        "Khôi phục bản đã lưu": "回復已儲存的版本",
        "XML: kiểm theo DTD/XSD…": "XML：依 DTD/XSD 驗證…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "這台 Mac 沒有 libxml2，因此無法進行 XSD 驗證。",
        "Chọn lược đồ XSD để kiểm": "選擇用於驗證的 XSD 綱要",
        "Hợp lệ theo": "符合",
        "Plugin chạy xong, không đổi gì": "外掛已結束，未做任何更動",
        "Chưa cài plugin native nào": "尚未安裝任何原生外掛",
        "Gỡ plugin này": "移除此外掛",
        "Gỡ plugin này?": "要移除此外掛嗎？",
        "Gỡ": "移除",
        "Cài plugin native…": "安裝原生外掛…",
        "Mở thư mục plugin": "打開外掛檔案夾",
        "Chọn file .dylib của plugin native": "選擇外掛的 .dylib 檔案",
        "Đã cài:": "已安裝：",
        "Đã gỡ:": "已移除：",
        "Plugin native…": "原生外掛…",
        "Chỉ nhận file .dylib.": "只接受 .dylib 檔案。",
        "Đã có một plugin trùng tên:": "已安裝同名的外掛：",
        "Không chép được plugin:": "無法拷貝外掛：",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "原生外掛只在直接下載版中提供，App Store 版沒有。",
        "Không tìm thấy tiến trình phụ chạy plugin.": "找不到外掛的輔助程序。",
        "Không khởi động được tiến trình phụ:": "無法啟動輔助程序：",
        "Tiến trình plugin đã dừng giữa chừng.": "外掛的程序中途停止了。",
        "Plugin không trả lời kịp — đã dừng nó.": "外掛未及時回應 — 已將其停止。",
        "Plugin trả lời sai giao thức:": "外掛回傳了格式錯誤的訊息：",
        "Plugin báo lỗi:": "外掛回報了一個錯誤：",
        "Về GEditor": "關於 GEditor",
        "Cài đặt…": "設定…",
        "Thoát GEditor": "結束 GEditor",
        "File": "檔案",
        "Tab mới": "新增標籤頁",
        "Đóng tab": "關閉標籤頁",
        "Tab kế": "下一個標籤頁",
        "Tab trước": "上一個標籤頁",
        "Tài liệu mới": "新增文件",
        "Mở…": "打開…",
        "Mở thư mục làm Workspace…": "把檔案夾作為工作區打開…",
        "Mở gần đây": "打開最近使用",
        "Lưu": "儲存",
        "Lưu thành…": "另存為…",
        "Cắt khoảng trắng cuối dòng khi lưu": "儲存時移除行尾空白",
        "Theo dõi file (tail -f)": "追蹤檔案（tail -f）",
        "In…": "列印…",
        "Mở lại tab vừa đóng": "重新打開已關閉的標籤頁",
        "Chưa có file nào": "沒有檔案",
        "Xoá danh sách": "清空列表",
        "Edit": "編輯",
        "Hoàn tác": "還原",
        "Làm lại": "重做",
        "Cắt": "剪下",
        "Sao chép": "拷貝",
        "Dán": "貼上",
        "Lịch sử clipboard…": "剪貼板記錄…",
        "Column Editor…": "欄位編輯器…",
        "Chọn lần kế tiếp": "選擇下一個相符處",
        "Chọn tất cả": "全選",
        "Nhân đôi dòng": "重複此行",
        "Xóa dòng": "刪除此行",
        "Comment dòng": "註解此行",
        "Chưa chép gì trong phiên này": "本次工作階段中沒有拷貝過任何內容",
        "Xoá lịch sử": "清除記錄",
        "Search": "搜尋",
        "Tìm…": "尋找…",
        "Tìm và thay…": "尋找並取代…",
        "Tìm trong thư mục…": "在檔案夾中尋找…",
        "Thay trong thư mục…": "在檔案夾中取代…",
        "Kết quả kế": "下一個結果",
        "Kết quả trước": "上一個結果",
        "Đi tới dòng…": "跳至指定行…",
        "Nhảy tới ngoặc khớp": "跳至相對應的括號",
        "Đánh dấu mọi dòng khớp…": "標記所有相符的行…",
        "Đảo dấu": "反轉標記",
        "Bỏ mọi dấu": "清除所有標記",
        "Chép dòng đã đánh dấu": "拷貝已標記的行",
        "Xóa dòng đã đánh dấu": "刪除已標記的行",
        "Chỉ giữ dòng đã đánh dấu": "只保留已標記的行",
        "Lines": "行",
        "Sắp xếp A→Z": "遞增排序",
        "Sắp xếp Z→A": "遞減排序",
        "Sắp xếp tự nhiên": "自然排序",
        "Khử trùng lặp": "移除重複項目",
        "Đảo thứ tự dòng": "反轉行的順序",
        "Dời dòng lên": "上移此行",
        "Dời dòng xuống": "下移此行",
        "Ghép dòng": "合併行",
        "Tách dòng theo độ dài…": "依長度分割行…",
        "Tách dòng theo ký tự…": "依字元分割行…",
        "Xóa dòng rỗng": "刪除空行",
        "Nén dòng trống liên tiếp": "壓縮連續的空行",
        "Cắt khoảng trắng cuối dòng": "移除行尾空白",
        "Tab → Space": "Tab → 空格",
        "Space → Tab": "空格 → Tab",
        "HOA": "大寫",
        "thường": "小寫",
        "Chữ Hoa Đầu Từ": "每個單字首字母大寫",
        "Chữ hoa đầu câu": "句首字母大寫",
        "Đảo hoa/thường": "反轉大小寫",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV：選擇工作表…",
        "Xem dạng bảng / văn bản": "切換表格 / 文字顯示",
        "Xóa cột…": "刪除欄位…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "驗證資料（欄數 · 型別）",
        "Bàn làm sạch dữ liệu…": "資料清理工作檯…",
        "Chạy công thức làm sạch…": "執行清理配方…",
        "Chuyển đổi…": "轉換…",
        "Đổi dấu phân tách…": "更改分隔符號…",
        "Xuất sang JSON…": "輸出為 JSON…",
        "Format": "格式",
        "Bảng mã…": "編碼…",
        "Xuống dòng…": "換行符號…",
        "Chuẩn hóa Unicode…": "正規化 Unicode…",
        "JSON: định dạng lại": "JSON：格式化",
        "JSON: thu gọn một dòng": "JSON：壓縮成一行",
        "JSON: sắp xếp khóa": "JSON：排序索引鍵",
        "JSON: truy vấn JSONPath…": "JSON：JSONPath 查詢…",
        "CSV: truy vấn SQL…": "CSV：SQL 查詢…",
        "Truy vấn SQL": "SQL 查詢",
        "Đang chạy…": "執行中…",
        "Xuất ra tab mới": "輸出到新的標籤頁",
        "Tài liệu rỗng — không có bảng để truy vấn": "文件是空的 — 沒有可查詢的表格",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "不是 CSV 表格 — 第一行只有一個欄位",
        "Không đọc được câu truy vấn": "無法讀取查詢語句",
        "Không kiểm được câu truy vấn": "無法檢查查詢語句",
        "Vàng (mặc định)": "黃色（預設）",
        "Xanh dương": "藍色",
        "Xanh lá": "綠色",
        "Vàng đất": "赭色",
        "Tím": "紫色",
        "Hồng": "粉紅色",
        "Xanh ngọc": "青綠色",
        "Cam": "橘色",
        "Xám lam": "石板灰",
        "Văn bản": "文字",
        "Dãy số": "數字序列",
        "Dãy ngày": "日期序列",
        "Chữ HOA (hex)": "大寫（十六進位）",
        "Bắt đầu": "起始",
        "Bước": "間隔",
        "Đệm 0 tới": "補零至",
        "Hệ": "進位制",
        "Ngày đầu": "第一個日期",
        "Định dạng": "格式",
        "Chèn": "插入",
        "Huỷ": "取消",
        "Chuyển đổi định dạng": "轉換格式",
        "Xem trước 5 hàng đầu": "預覽前 5 列",
        "Tạo tab mới": "在新的標籤頁中打開",
        "Lưu ra file…": "儲存到檔案…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "結果會在一個未儲存的新標籤頁中打開。原本的文件不會更動。",
        "Chạy trên tài liệu này": "在此文件上執行",
        "Chạy trên thư mục…": "在檔案夾上執行…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "整個配方算一次還原。在你儲存之前，磁碟上的檔案不會更動。",
        "tắt": "關閉",
        "không thấy cột": "找不到該欄位",
        "sẵn sàng": "就緒",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "在 App 結束前，它會一直佔用一個 CPU 核心。",
        "Script không trả về gì": "腳本沒有回傳任何內容",
        "Không dựng được máy JavaScript": "無法建立 JavaScript 引擎",
        "Lỗi JavaScript không rõ": "不明的 JavaScript 錯誤",
        "Bảng": "表格",
        "Áp sắp xếp vào file": "把排序套用到檔案",
        "Chuyển đổi ▾": "轉換 ▾",
        "Xuất dòng khớp": "輸出相符的列",
        "Ẩn cột này": "隱藏此欄位",
        "Đổi tên tiêu đề…": "重新命名標題…",
        "Chèn cột trống bên trái": "在左側插入空白欄位",
        "Chèn cột trống bên phải": "在右側插入空白欄位",
        "Xóa cột này khỏi file…": "從檔案中刪除此欄位…",
        "Phải còn ít nhất một cột đang hiện": "至少要保留一個欄位顯示",
        "Đang sắp xếp…": "排序中…",
        "Trở về thứ tự trong file": "回到檔案中的順序",
        "trăm hàng đầu": "前一百列",
        "chọn cột": "選擇欄位",
        "đặt tên cột kết quả": "為結果欄位命名",
        "lọc theo chữ": "依文字篩選",
        "ô rỗng": "空白儲存格",
        "ghép điều kiện": "組合條件",
        "đếm hàng": "計算列數",
        "gộp nhóm": "分組並彙總",
        "nhỏ nhất, lớn nhất": "最小值、最大值",
        "sắp xếp và cắt": "排序並限制筆數",
        "tên cột có dấu cách": "含空格的欄位名稱",
        "Truy vấn bị dừng giữa chừng": "查詢被中斷",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "不支援：JOIN · 子查詢 · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · 視窗函數",
        "XML: định dạng lại": "XML：格式化",
        "XML: thu gọn một dòng": "XML：壓縮成一行",
        "XML: kiểm cú pháp": "XML：檢查語法",
        "YAML: kiểm khóa trùng và thụt lề": "YAML：檢查重複索引鍵與縮排",
        "View": "顯示",
        "Ẩn/hiện sidebar (Function List)": "顯示/隱藏側邊欄（函數列表）",
        "Ẩn/hiện bản đồ tài liệu": "顯示/隱藏文件地圖",
        "Gấp / mở khối tại con nháy": "收合 / 展開游標處的區塊",
        "Gấp tất cả": "全部收合",
        "Bỏ gấp tất cả": "全部展開",
        "Gấp theo cấp": "依層級收合",
        "Cấp %d": "第 %d 層",
        "Đã gấp %d khối ở cấp %d": "已在第 %2$d 層收合 %1$d 個區塊",
        "Tài liệu này chỉ sâu %d cấp": "此文件只有 %d 層深",
        "mermaid: không đọc được bản kê": "mermaid：無法讀取清單",
        "Kiểm tra bản cập nhật…": "檢查更新…",
        "Kiểm tra bản cập nhật": "檢查更新",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store 版透過 Mac App Store 更新，而不是透過 GEditor。",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "此版本沒有更新簽章金鑰，因此無法檢查更新。",
        "Phóng to chữ": "放大文字",
        "Thu nhỏ chữ": "縮小文字",
        "Cỡ chữ gốc": "實際大小",
        "Chia đôi theo chiều dọc": "垂直分割",
        "Chia đôi theo chiều ngang": "水平分割",
        "Bỏ chia đôi": "關閉分割",
        "Mở tab này ở nửa kia": "在另一側打開此標籤頁",
        "Nhảy sang nửa kia": "跳到另一側",
        "Ngắt dòng (tắt / cửa sổ / cột)": "自動換行（關閉 / 視窗 / 欄）",
        "Ngắt dòng tại cột…": "在指定欄換行…",
        "Đánh dấu dòng này": "標記此行",
        "Dấu kế tiếp": "下一個書籤",
        "Dấu trước đó": "上一個書籤",
        "Màu đánh dấu…": "書籤顏色…",
        "Hiện tất cả ký tự ẩn": "顯示所有不可見字元",
        "  Khoảng trắng": "  空格",
        "  Tab": "  Tab",
        "  Xuống dòng": "  換行符號",
        "  NBSP · zero-width · điều khiển": "  NBSP · 零寬 · 控制字元",
        "Xem nhị phân": "二進位檢視",
        "Chế độ CSV (tô màu theo cột)": "CSV 模式（依欄位上色）",
        "Macro": "巨集",
        "Bắt đầu / dừng ghi": "開始 / 停止錄製",
        "Phát lại": "播放",
        "Phát nhiều lần…": "播放多次…",
        "Phát đến cuối tài liệu": "播放到文件結尾",
        "Chạy trên mọi tab": "在所有標籤頁上執行",
        "Hủy macro đang chạy": "取消執行中的巨集",
        "Lưu macro…": "儲存巨集…",
        "Macro đã lưu…": "已儲存的巨集…",
        "Help": "輔助說明",
        "Trợ giúp GEditor": "GEditor 輔助說明",
        "Giới thiệu tính năng": "功能介紹",
        "Di cư từ Notepad++": "從 Notepad++ 轉移",
        "Tìm": "尋找",
        "Thay bằng": "取代為",
        "Kế": "下一個",
        "Trước": "上一個",
        "Đếm": "計數",
        "Đóng": "關閉",
        "Kiểm theo JSON Schema…": "依 JSON Schema 驗證…",
        "Chọn tệp JSON Schema": "選擇 JSON Schema 檔案",
        "Không thấy lỗi nào theo schema này.": "依此綱要未發現問題。",
        "JSON Schema": "JSON Schema",
        "Kiểm cú pháp đồ thị": "檢查圖形的語法",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "無法辨識圖形的格式 — 需要 .dot、.gv、.cypher、.ttl 或 .graphml 副檔名。",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "未發現 %@ 語法錯誤（此檢查並不完整）。",
        "Cú pháp %@": "%@ 語法",
        "không phải một đối tượng JSON": "不是 JSON 物件",
        "Khai phá văn bản (n-gram, TF-IDF)": "文字探勘（n-gram、TF-IDF）",
        "Tài liệu rỗng.": "文件是空的。",
        "Không rút được từ khoá nào.": "無法擷取任何關鍵字。",
        "Từ khoá": "關鍵字",
        "%d từ khoá · %d token · %d tài liệu": "%d 個關鍵字 · %d 個詞元 · %d 份文件",
        "Tô lên tài liệu": "在文件中標記",
        "Đánh dấu entity từ danh sách…": "從列表標記實體…",
        "Chọn danh sách entity (CSV hoặc JSON)": "選擇實體列表（CSV 或 JSON）",
        "Không đọc được danh sách entity.": "無法讀取實體列表。",
        "Danh sách entity rỗng.": "實體列表是空的。",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "文件中找不到實體（已載入 %d 個）。",
        "%d lần xuất hiện · %@": "出現 %d 次 · %@",
        "Chuyển đổi tri thức…": "轉換知識…",
        "Chuyển đổi: %@ → %@": "轉換：%@ → %@",
        "Không chuyển đổi được.": "無法轉換。",
        "Xem trước cắt chunk…": "分塊預覽…",
        "Cỡ cố định 800B, chồng 100B": "固定大小 800 B，重疊 100 B",
        "Theo câu (≤ 800B)": "依句子（≤ 800 B）",
        "Theo heading Markdown": "依 Markdown 標題",
        "Tài liệu rỗng — không có chunk nào.": "文件是空的 — 沒有分塊。",
        "%d chunk · trung bình %d B · %@": "%d 個分塊 · 平均 %d B · %@",
        "Xuất JSONL": "輸出 JSONL",
        "Chunk JSONL": "分塊 JSONL",
        "Mở triple/edge dạng bảng": "以表格打開三元組/邊",
        "Bảng triple": "三元組表格",
        "Tài liệu này không có dòng triple nào.": "此文件沒有任何三元組的行。",
        "Không đọc được triple nào — dòng %d: %@": "無法讀取任何三元組 — 第 %d 行：%@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "已讀取 %1$d 個三元組 · 略過 %2$d 個格式錯誤的行（第一個：第 %3$d 行）",
        "Trùng lặp mờ theo cột…": "依欄位尋找模糊重複…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "模糊重複 — 欄位「%1$@」：%2$d 個候選群組",
        "Gộp": "合併",
        "Giống": "相符",
        "Các giá trị trong cụm": "群組內的值",
        "Gộp về": "合併為",
        "Gộp các cụm đã chọn": "合併選取的群組",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "沒有選取任何群組 — 按「合併」不會更動任何內容。App 絕不會自行合併。",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "已選取 %d 個群組 · %d 列將會更動 · 一次還原",
        "Không quét được cột này.": "無法掃描此欄位。",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "欄位「%@」沒有模糊重複的群組。",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "沒有合併任何群組 — 文件維持原狀。",
        "Khử trùng lặp mờ · cột %@": "模糊去重 · 欄位 %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "已合併 %d 個群組 · %d 個儲存格有更動",
        "Báo cáo làm sạch": "清理報告",
        "# Báo cáo làm sạch — %@\n\n": "# 清理報告 — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## 已套用（%d）\n\n",
        "_Chưa áp dụng bước nào._\n": "_尚未套用任何步驟。_\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## 資料概況\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d 欄 · %2$d 列 · 掃描耗時 %3$.1f 秒_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| 欄位 | 型別 | 空值 | 相異值 | 最小 | 最大 | 平均 |\n",
        "\n### Giá trị bất thường\n\n": "\n### 異常值\n\n",
        "hàng %d: %@": "第 %d 列：%@",
        "- cột «%@» — %d ô: %@\n": "- 欄位「%1$@」— %2$d 個儲存格：%3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## 剩餘（%d）\n\n",
        "_Không còn phát hiện nào._\n": "_沒有剩下的發現。_\n",
        "- cột «%@»: %@\n": "- 欄位「%@」：%@\n",
        "Cắt khoảng trắng khi lưu": "儲存時移除空白",
        "Chuẩn hóa xuống dòng": "正規化換行符號",
        "trước đó": "先前",
        "Không mở lại được thư mục «%@» của phiên trước": "無法重新打開上次工作階段的檔案夾「%@」",
        " (và %d file khác)": "（以及另外 %d 個檔案）",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "無法重新打開 %d 個標籤頁：%@%@ — 檔案已不在原來的位置。",
        "Không đọc được nội dung từ ống dẫn": "無法從管線讀取輸入",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "每次儲存時都會移除行尾空白",
        "Không cắt khoảng trắng khi lưu nữa": "儲存時不再移除空白",
        "Chưa đặt tên.txt": "未命名.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "轉換編碼會遺失字元",
        "Vẫn lưu": "仍要儲存",
        "Tài liệu có thay đổi chưa lưu": "文件有尚未儲存的更動",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "不儲存就關閉會捨棄這些更動。",
        "Bỏ thay đổi": "捨棄更動",
        "Đi tới dòng": "跳至指定行",
        "Tài liệu có %d dòng.": "文件共有 %d 行。",
        "Số dòng": "行號",
        "Đi tới": "前往",
        "Diễn giải lại theo…": "重新解讀為…",
        "Chuyển đổi sang…": "轉換為…",
        "Không diễn giải lại được": "無法重新解讀",
        "Bảng mã %@ không chứa hết ký tự": "%@ 無法表示所有字元",
        "Vẫn chọn": "仍要選擇",
        "Cột %d": "第 %d 欄",
        "Cột %d: %@": "第 %d 欄：%@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "已隱藏的欄位：%@（%d）— 可從標題列的快捷選單復原",
        "Hiện lại: %@": "重新顯示：%@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "已隱藏欄位 %@ — 它在檔案中依然完整",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "依 %@ %@ 排序 · 僅影響顯示",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "已排序：%@ %@（僅影響顯示）",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ 列相符 — 仍在尋找…",
        "%d / %d dòng khớp": "%d / %d 列相符",
        "Không tìm thấy lỗi trong %d hàng": "在 %d 列中未發現問題",
        "%d hàng lệch số cột": "%d 列的欄數不正確",
        "%d ô sai kiểu dữ liệu": "%d 個儲存格的資料型別不正確",
        " (đã dừng ở %d lỗi đầu)": "（已在前 %d 個問題處停止）",
        "   —   kiểu nhận ra: ": "   —   辨識出的型別：",
        "Hàng %d, cột %@: «%@» không phải %@": "第 %1$d 列，欄位 %2$@：「%3$@」不是 %4$@",
        "Column Editor — %d dòng": "欄位編輯器 — %d 行",
        "Phát hiện": "發現",
        "Hồ sơ dữ liệu": "資料概況",
        "Hồ sơ dữ liệu — đang quét…": "資料概況 — 掃描中…",
        "Lưu công thức…": "儲存配方…",
        "Xuất báo cáo": "輸出報告",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "尚未套用任何群組 · 每個群組算一次還原",
        "quá nhiều giá trị": "值太多",
        "hay gặp: ": "最常見：",
        "Giá trị điền vào ô thiếu": "用來填補空白儲存格的值",
        "Áp dụng": "套用",
        "Không dựng được bản xem trước": "無法建立預覽",
        "· giữ nguyên, không đọc được ·": "· 原樣保留，無法解讀 ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "把欄位轉換為 ISO 8601（YYYY-MM-DD）",
        "Quy ước số cho cả cột": "整個欄位的數字慣例",
        "Làm gì với ô thiếu": "如何處理空白儲存格",
        "Chuẩn hóa về ISO 8601": "正規化為 ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "把有歧義的儲存格以「日在前」讀取（31/12）",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "把有歧義的儲存格以「月在前」讀取（12/31）",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "略過有歧義的儲存格，只修正確定的",
        "Về Việt/Âu (1.234,56)": "改為越南/歐洲式（1.234,56）",
        "Về Anh-Mỹ (1,234.56)": "改為英美式（1,234.56）",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "改為英美式，不含千位分隔（1234.56）",
        "Điền một giá trị mặc định…": "以預設值填補…",
        "Điền xuôi — lấy giá trị phía trên": "向下填補 — 取上方的值",
        "Điền ngược — lấy giá trị phía dưới": "向上填補 — 取下方的值",
        "Xóa hàng có ô thiếu ở cột này": "刪除此欄位為空白的列",
        "Cắt khoảng trắng hai đầu": "移除兩端的空白",
        "Cắt hai đầu và nén khoảng trắng bên trong": "移除兩端並壓縮內部空白",
        "Pivot…": "樞紐分析…",
        "Nguồn…": "資料來源…",
        "Pivot — gộp theo cột": "樞紐分析 — 依欄位分組",
        "Hàng (gộp nhóm)": "列（分組）",
        "Giá trị": "值",
        "+ Hàng": "+ 列",
        "+ Giá trị": "+ 值",
        "Xoá hết": "全部清除",
        "Đưa vào ô truy vấn": "放入查詢欄",
        "Chọn cột để dựng câu truy vấn.": "請選擇欄位以建立查詢。",
        "Không đọc được tên cột của bảng này.": "無法讀取此表格的欄位名稱。",
        "Nguồn dữ liệu của truy vấn": "查詢的資料來源",
        "«%@» — tài liệu đang mở": "「%@」— 目前打開的文件",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ 檔案自登錄以來已更動",
        "Thêm file…": "加入檔案…",
        "Bỏ hết": "全部移除",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "無法從「%@」推斷出表格名稱 — 請重新命名該檔案。",
        "Tổng": "總和",
        "Trung bình": "平均值",
        "Nhỏ nhất": "最小值",
        "Lớn nhất": "最大值",
        "Đếm khác nhau": "相異值計數",
        "Biểu đồ": "圖表",
        "Xuất PNG": "輸出 PNG",
        "Xuất SVG": "輸出 SVG",
        "Bảng này không có cột số nào để vẽ.": "此表格沒有可用來繪圖的數值欄位。",
        "Không dựng được ảnh PNG.": "無法建立 PNG 影像。",
        "Kết quả truy vấn": "查詢結果",
        "Đã lưu %@": "已儲存 %@",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "「%2$@」的 %1$@ 圖 — %3$d 個點，數值從 %4$@ 到 %5$@",
        "Cột": "長條",
        "Đường": "折線",
        "Phân bố": "直方圖",
        "Phân tán": "散佈",
        "Hộp": "盒鬚",
        "CSV: chất lượng dữ liệu…": "CSV：資料品質…",
        "Chất lượng dữ liệu": "資料品質",
        "Xuất vi phạm ra tab mới": "把違規項輸出到新的標籤頁",
        "Mức": "層級",
        "Luật": "規則",
        "Vi phạm": "違規",
        "Tỷ lệ": "比例",
        "đạt": "通過",
        "lỗi": "錯誤",
        "cảnh báo": "警告",
        "hỏng": "損毀",
        "Đã đánh dấu %d dòng vi phạm": "已標記 %d 個違規的行",
        "Xu hướng": "趨勢",
        "Lúc chấm": "評分於",
        "Số hàng": "列數",
        "Lệch": "差異",
        "Luật trượt": "未通過的規則",
        "Điểm chất lượng": "品質分數",
        "Điểm theo thời gian": "分數隨時間變化",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "還沒有記錄 — 每次評分都會附加",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "一行到規則旁的「.history.jsonl」檔案中。",
        "%d mốc trong lịch sử": "記錄中有 %d 個資料點",
        " · %d dòng KHÔNG đọc được": " · %d 行無法讀取",
        " · chọn hai dòng để so": " · 請選擇兩列來比較",
        "điểm %+.1f": "分數 %+.1f",
        "không chiều nào tụt": "沒有面向下降",
        "tụt: ": "下降：",
        "%d luật mới trượt: %@": "%d 條規則新近未通過：%@",
        "số hàng %+d": "列數 %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": "（趨勢標籤頁中還有 %d 條警告）",
        "Không sửa tự động được: ": "無法自動修正：",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "打開清理工作檯中對應的工具，完成後立即重新評分。",
        "Xử lý giá trị thiếu…": "處理缺失值…",
        "Chuẩn hóa ngày…": "正規化日期…",
        "Khử trùng lặp…": "移除重複項目…",
        "Thay thế…": "取代…",
        "Xem các dòng sai": "顯示有問題的列",
        "Không tìm thấy cột «%@» trong bảng này.": "此表格中沒有欄位「%@」。",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "重複項目已移除 —「%@」現在是唯一的。分數：%.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "重複項目已移除，但「%1$@」仍有 %2$d 個重複的列（先前：%3$d）— ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "那些列共用索引鍵，但整列並不相同，所以需要你查看並選擇",
        "giữ hàng nào.": "要保留哪一列。",
        "Không đọc được giá trị nào đang vi phạm luật này.": "無法讀取任何違反此規則的值。",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "欄位「%2$@」中有 %1$d 個錯誤的值 — 填寫「取代」後按「預覽」",
        "Đã chấm lại: %.0f/100": "已重新評分：%.0f/100",
        "Xem trước báo cáo": "報告預覽",
        "Tham số…": "參數…",
        "Xuất HTML…": "輸出 HTML…",
        "In / PDF…": "列印 / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d 個區塊已執行 · %d 個區塊失敗",
        "%d khối chạy được": "%d 個區塊已執行",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · 資料已過時 — 來源檔案已更動；請重新建立",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "報告預覽需要 .%@ 文件",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "找不到資料來源 — 請在 frontmatter 中宣告「source: 檔案.csv」。",
        "Không dựng được báo cáo.": "無法建立報告。",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "此報告的 frontmatter 中沒有宣告任何參數。",
        "Tham số báo cáo": "報告參數",
        "Dựng lại": "重新建立",
        "Đã xuất %@": "已輸出 %@",
        "Báo cáo: xem trước": "報告：預覽",
        "Báo cáo: sinh loạt…": "報告：批次產生…",
        "không phải tài liệu .greport.md": "不是 .greport.md 文件",
        "không phân tích được báo cáo": "無法解析報告",
        "không tìm được dữ liệu nguồn": "找不到來源資料",
        "không đọc được danh sách tham số": "無法讀取參數列表",
        "Sinh loạt cần tài liệu đuôi .%@": "批次產生需要 .%@ 文件",
        "Chọn danh sách tham số (CSV hoặc JSON)": "選擇參數列表（CSV 或 JSON）",
        "Chọn thư mục để ghi %d báo cáo": "為 %d 份報告選擇一個檔案夾",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "缺少參數 ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "指向來源檔案本身 — 已拒絕覆寫",
        "%d khối HỎNG": "%d 個區塊失敗",
        "Sinh loạt xong: %d tệp · %d hỏng": "批次處理完成：%d 個檔案 · %d 個失敗",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d 組參數無法建立 — 請查看摘要",
        "Sơ đồ Mermaid: xem trước": "Mermaid 圖：預覽",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid 圖：插入範本…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid 圖：重新格式化",
        "Nền trong suốt": "透明背景",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "這台 Mac 無法把圖點陣化為 PNG — 需要 macOS 13。SVG 輸出仍然可用。",
        "Lưu PNG %@…": "儲存 PNG %@…",
        "Lưu SVG…": "儲存 SVG…",
        "Chép ảnh vào clipboard": "把影像拷貝到剪貼板",
        "Màu thương hiệu…": "品牌配色…",
        "Màu thương hiệu cho sơ đồ": "圖表的品牌配色",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "每個欄位都是 #rrggbb 顏色。儲存在「themes/mermaid-brand.json」中 — 可拷貝到另一台 Mac。",
        "Màu chính": "主色",
        "Chữ trên nút": "節點上的文字",
        "Viền": "邊框",
        "Đường nối": "連線",
        "Nền khi xuất ảnh": "輸出時的背景",
        "Lưu và chèn %%{init}%% vào tài liệu": "儲存並把 %%{init}%% 插入文件",
        "Đã lưu màu thương hiệu": "品牌配色已儲存",
        "Đã chép ảnh sơ đồ vào clipboard": "已把圖的影像拷貝到剪貼板",
        "Đã lưu %@ — %@": "已儲存 %@ — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "此圖已有 %%{init}%% 指令 — 你的那份維持原狀。",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "已插入 %%{init}%% — 此圖現在自帶配色",
        "Chèn màu thương hiệu vào sơ đồ": "把品牌配色插入圖中",
        "Định dạng sơ đồ Mermaid": "重新格式化 Mermaid 圖",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "圖的原始碼已經很整齊 — 沒有需要更動的地方",
        "Đã định dạng lại sơ đồ": "圖已重新格式化",
        "Đã định dạng lại %d sơ đồ": "已重新格式化 %d 個圖",
        "Thư viện mẫu sơ đồ": "圖範本庫",
        "Mẫu sơ đồ đầy đủ": "完整的圖範本",
        "Mẩu cú pháp": "語法片段",
        "Đang soạn: %@": "正在編輯：%@",
        "Đã chèn mẫu «%@»": "已插入範本「%@」",
        "Tài liệu đang ở chế độ chỉ đọc.": "此文件為唯讀。",
        "Sơ đồ Mermaid": "Mermaid 圖",
        "Tài liệu chưa có khối mermaid nào.": "此文件沒有任何 mermaid 區塊。",
        "Thương hiệu": "品牌",
        "Xuất…": "輸出…",
        "Chưa có sơ đồ nào": "還沒有圖",
        "%d sơ đồ · %@": "%d 個圖 · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d 個圖失敗 — 第 %3$d 個圖%4$@",
        ", dòng %d": "，第 %d 行",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "此文件沒有 ```mermaid 區塊，也不是 .mmd 檔案。",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "還沒有圖繪製完成。",
        "Không tìm thấy «%@» trong mã sơ đồ": "在圖的原始碼中找不到「%@」",
        "không dựng được hàng rào chặn mạng cho WKWebView": "無法為 WKWebView 建立網路屏障",
        "Luật kết hợp": "關聯規則",
        "Mỗi dòng một giỏ": "每列一個購物籃",
        "Hai cột: mã · item": "兩個欄位：編號 · 品項",
        "Dạng dữ liệu giao dịch": "交易資料的形態",
        "Cột giỏ hàng hoặc mã giao dịch": "購物籃欄位或交易編號欄位",
        "Cột item": "品項欄位",
        "Ký tự phân tách item": "品項分隔字元",
        "Support tối thiểu, phần trăm": "最小 support，百分比",
        "Confidence tối thiểu, phần trăm": "最小 confidence，百分比",
        "Tách bởi:": "分隔符號：",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "關聯規則表格",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "注意",
        "%d giao dịch · %d item · %d luật": "%d 筆交易 · %d 個品項 · %d 條規則",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — 沒有規則達到門檻；請降低 support 或 confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — 已提早停止，表格並不完整",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d 筆交易同時包含兩側",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "兩欄形態需要選擇兩個不同的欄位。",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "已在包含「%3$@」的 %2$d 筆交易中標記了 %1$d 列",
        "CSV: luật kết hợp…": "CSV：關聯規則…",
        "Khai phá theo nhóm": "分組探勘",
        "Cột nhóm": "分組欄位",
        "Cột giá trị": "數值欄位",
        "Cột thứ hai cho tương quan": "用於相關性的第二個欄位",
        "Cách xếp hạng": "排名方式",
        "Nhóm theo:": "分組依據：",
        "Giá trị:": "數值：",
        "Xếp theo:": "排序依據：",
        "Bảng xếp hạng nhóm": "分組排名表",
        "Nhóm": "分組",
        "Hàng": "列數",
        "Hàng rào riêng": "各自的門檻",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r 差值",
        "Ghi chú": "備註",
        "không đo được": "無法測量",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d 個分組 · 整體參照相關性 %@",
        " · ĐÃ CẮT %d nhóm": " · 已捨棄 %d 個分組",
        "Bảng này không có cột chữ nào để gom nhóm.": "此表格沒有可用來分組的文字欄位。",
        "Bảng này không có cột số nào để khai phá.": "此表格沒有可用來探勘的數值欄位。",
        "Đã đánh dấu %d dòng của nhóm «%@»": "已標記分組「%2$@」的 %1$d 列",
        "CSV: khai phá theo nhóm…": "CSV：分組探勘…",
        "\u{2194}": "↔",
        "Dự báo": "預測",
        "Cột giá trị theo thời gian": "隨時間變化的數值欄位",
        "Mô hình dự báo": "預測模型",
        "Số kỳ dự báo": "要預測的期數",
        "Kết luận so với baseline": "與基準模型的比較結論",
        "Mô hình:": "模型：",
        "Số kỳ:": "期數：",
        "Chu kỳ:": "季節：",
        "tự": "自動",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "季節週期；留空則自動偵測",
        "Bảng giá trị dự báo": "預測值表格",
        "Kỳ": "期",
        "Dải 80%": "80% 區間",
        "Dải 95%": "95% 區間",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "無法計算",
        "Bảng này không có cột số nào để dự báo.": "此表格沒有可用來預測的數值欄位。",
        "Không dựng được dự báo cho cột này.": "無法為此欄位建立預測。",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "欄位「%1$@」只有 %2$d 個數值 — 預測至少需要 4 個。",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# 序列嚴格依照檔案中的列順序讀取 — 不重新排序，也不推斷時間欄位。\n",
        "Sai số huấn luyện": "訓練誤差",
        "CSV: dự báo chuỗi thời gian…": "CSV：時間序列預測…",
        "Holt-Winters cộng": "Holt-Winters 加法",
        "Holt-Winters nhân": "Holt-Winters 乘法",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "參與分群的欄位",
        "Đường cong WCSS": "WCSS 曲線",
        "Phân cụm": "分群",
        "Chuẩn hoá:": "縮放：",
        "k:": "k：",
        "eps:": "eps：",
        "minPts:": "minPts：",
        "Chọn ít nhất một cột.": "請至少選擇一個欄位。",
        "Không đủ dữ liệu để dựng đường cong.": "資料不足，無法建立曲線。",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "手肘法建議 k = %d。WCSS 總是隨著 k 增大而下降，所以這是一種讀圖技巧而非統計判準 — 請看曲線，判斷轉折是否清楚。",
        "WCSS theo k": "WCSS 隨 k 變化",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k 距離建議 eps = %1$@（minPts 預設為 2 × 欄位數 = %2$d）。%3$@",
        "Khoảng cách tới hàng xóm thứ k": "到第 k 個鄰居的距離",
        "Cần ít nhất 2 cột số để phân cụm.": "分群至少需要 2 個數值欄位。",
        "Cụm theo %@ và %@": "依 %@ 與 %@ 分群",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — 分群在 %d 個維度中完成；圖中只顯示前 2 個維度",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# 雜訊（cluster_id = -1）：%d 列\n",
        "CSV: phân cụm…": "CSV：分群…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- 分群中心（原始單位）---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "相關矩陣",
        "Phương pháp tương quan": "相關性方法",
        "Tương quan không hàm ý nhân quả.": "相關不代表因果。",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "最強的一組：%1$@ ↔ %2$@ = %3$@（n = %4$d）。點一下儲存格可查看散佈圖。",
        "Không cặp nào đo được.": "沒有可測量的組合。",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@：%3$@，依據 %4$d 列",
        "Cần ít nhất 2 cột số để tính tương quan.": "計算相關性至少需要 2 個數值欄位。",
        "Không đọc được cột «%@».": "無法讀取欄位「%@」。",
        "CSV: ma trận tương quan…": "CSV：相關矩陣…",
        "Bất thường": "異常",
        "Danh sách bất thường": "異常列表",
        "Cột:": "欄位：",
        "Cột số cần xét": "要檢查的數值欄位",
        "Cách:": "方法：",
        "Phương pháp phát hiện": "偵測方法",
        "Phương pháp đã dùng": "已使用的方法",
        "Ngưỡng": "門檻",
        "Đánh dấu": "標記",
        "Xuất tab mới": "輸出到新的標籤頁",
        "Dòng": "行",
        "Điểm": "分數",
        "Vì sao": "原因",
        "nhẹ": "輕微",
        "vừa": "中等",
        "nặng": "嚴重",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d 列（%.2f%%）",
        "Bảng này không có cột số nào để tìm bất thường.": "此表格沒有可用來尋找異常的數值欄位。",
        "Đã đánh dấu %d dòng bất thường": "已標記 %d 個異常的行",
        "CSV: tìm bất thường…": "CSV：尋找異常…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d 條規則，全部通過 · %2$d 列 · %3$.0f 毫秒",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d 個錯誤 · %2$d 個警告，涉及 %3$d 條規則 · %4$d 列 · %5$.0f 毫秒",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "請先儲存文件 — 品質規則位於資料檔案旁邊。",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "還沒有規則集。請建立檔案 %@ 後重新打開。",
        "Lịch sử": "記錄",
        "Câu đã lưu": "已儲存的查詢",
        "Lưu câu này…": "儲存此查詢…",
        "Lưu câu truy vấn": "儲存查詢",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "取個名稱以便日後尋找。同名會覆寫。",
        "Ví dụ: Doanh thu theo tỉnh": "例如：依縣市統計營收",
        "Chưa nhập giá trị cho tham số: %@": "參數未輸入值：%@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "外掛自你核准後已更動 — GEditor 拒絕執行它",
        "Chạy plugin chưa duyệt?": "要執行未核准的外掛嗎？",
        "Tôi tin file này — chạy": "我信任此檔案 — 執行",
        "KHÔNG có chữ ký": "未簽章",
        "Chữ ký: %@": "簽章：%@",
        "Đường dẫn: %@": "路徑：%@",
        "Thay": "取代",
        "Thay tất cả": "全部取代",
        "Chuỗi thuần": "純文字",
        "Extended (\\n \\t \\xNN)": "延伸（\\n \\t \\xNN）",
        "Biểu thức chính quy": "正規表示式",
        "Phân biệt hoa thường": "區分大小寫",
        "Cả từ": "全字相符",
        "Không có kết quả": "沒有結果",
        "Thử biểu thức chính quy…": "測試正規表示式…",
        "Chế độ Log (tô theo mức)": "記錄檔模式（依層級上色）",
        "Lọc log theo mức…": "依層級篩選記錄檔…",
        "Chạy trên cả thư mục…": "在整個檔案夾上執行…",
        "Lọc qua lệnh ngoài…": "透過外部指令篩選…",
        "Script…": "腳本…",
        "Gói mở rộng…": "延伸套件…",
        "Cửa sổ mới": "新增視窗",
        "Tách tab ra cửa sổ mới": "把標籤頁分離到新視窗",
        "Chưa mở thư mục nào": "沒有打開任何檔案夾",
        "Tìm file trong thư mục": "在檔案夾中尋找檔案",
        "Lọc theo tên": "依名稱篩選",
        "File mới…": "新增檔案…",
        "Thư mục mới…": "新增檔案夾…",
        "Đổi tên…": "重新命名…",
        "Chuyển vào Thùng rác": "移到垃圾桶",
        "Hiện trong Finder": "在 Finder 中顯示",
        "Đang đọc cấu trúc tài liệu…": "正在讀取文件結構…",
        "file này không có hàm nào": "此檔案沒有函數",
        "Không có gì khớp": "沒有相符項目",
        "Văn bản thuần": "純文字",
        "🔒 Chỉ đọc": "🔒 唯讀",
        "Đang theo dõi": "追蹤中",
        "ngắt tại cột": "在指定欄換行",
        "Cú pháp": "語法",
        "Bấm để chèn vào ô truy vấn": "點一下以插入查詢中",
        "truy vấn không hợp lệ": "查詢無效",
        "khóa `ten` ở gốc": "根部的「名稱」索引鍵",
        "khóa có dấu cách": "含空格的索引鍵",
        "phần tử đầu": "第一個元素",
        "mọi phần tử": "所有元素",
        "lát cắt": "切片",
        "hợp nhiều chỉ số": "索引聯集",
        "mọi khóa `gia` ở mọi tầng": "所有層級中的所有「價格」索引鍵",
        "mọi nút": "所有節點",
        "lọc theo số": "依數字篩選",
        "lọc theo có mặt": "依是否存在篩選",
        "Tới lỗi đầu tiên": "跳到第一個錯誤",
        "Cột doanh_thu là số": "「營收」欄位是數值欄位",
        "lọc…": "篩選…",
        "Hủy": "取消",
        "Thực hiện thay": "執行取代",
        "xem trước": "預覽",
        "tương tác": "互動式",
        "Soạn thảo": "編輯",
        "Giao diện": "介面",
        "Phím tắt": "鍵盤快速鍵",
        "Cỡ chữ": "文字大小",
        "Bề rộng TAB": "Tab 寬度",
        "Thụt lề bằng TAB": "以 Tab 縮排",
        "Tự động thụt lề khi xuống dòng": "換行時自動縮排",
        "Tô mọi kết quả tìm kiếm": "標示所有搜尋結果",
        "Chuẩn hóa về NFC khi lưu": "儲存時正規化為 NFC",
        "Ngôn ngữ": "語言",
        "Nền": "外觀",
        "Theo hệ thống": "跟隨系統",
        "Sáng": "淺色",
        "Tối": "深色",
        "Theme": "佈景主題",
        "Dùng preset Notepad++": "使用 Notepad++ 預設組合",
        "Về phím mặc định": "回復預設按鍵",
        "Mở file cấu hình": "打開設定檔",
        "Xuất theme hiện tại": "輸出目前的佈景主題",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "語言更動會在下次啟動時完全生效。",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "預設按鍵會在下次啟動時回復。",
        "Xem trước Markdown": "Markdown 預覽",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "預覽使用系統的 Markdown 引擎：尚未支援表格，程式碼區塊也沒有上色。",
        "Thử biểu thức chính quy": "測試正規表示式",
        "Biểu thức": "表示式",
        "Văn bản thử": "測試文字",
        "Kết quả": "結果",
        "Kết quả khớp": "相符項目",
        "Biểu thức này làm gì": "這個表示式的作用",
        "Giải thích biểu thức": "解說表示式",
        "Chế độ tìm kiếm": "搜尋模式",
        "Kết quả tìm kiếm": "搜尋結果",
        "Không khớp chỗ nào": "沒有相符項目",
        " (đã cắt bớt)": "（已截斷）",
        "Bản đồ tài liệu": "文件地圖",
        "Thanh tab": "標籤列",
        "Hàng tiêu đề cột": "欄位標題列",
        "Không có cột nào": "沒有欄位",
        "Cây thư mục workspace": "工作區目錄樹",
        "Danh sách hàm và lớp": "函數與類別列表",
        "Kết quả tìm trong thư mục": "檔案夾搜尋結果",
        "Bảng dữ liệu CSV": "CSV 資料表格",
        "Bàn làm sạch dữ liệu": "資料清理工作檯",
        "Truy vấn JSONPath": "JSONPath 查詢",
        "Danh sách lỗi dữ liệu": "資料錯誤列表",
        "Bộ đánh giá golden set…": "黃金集評估器…",
        "So với điểm ngoài (JSONL)…": "與外部分數比較（JSONL）…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "選擇外部分數檔案（JSONL：query, chunk_id, score）",
        "Đổi tên node đang chọn": "重新命名選取的節點",
        "Gộp các node đang chọn": "合併選取的節點",
        "Tách node đang chọn": "分割選取的節點",
        "Trích subgraph đang chọn ra tab mới": "把選取的子圖擷取到新的標籤頁",
        "Không có gì để đổi": "沒有需要更動的內容",
        "%@ — áp %d thay đổi?": "%1$@ — 要套用 %2$d 項更動嗎？",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@：%2$d 項更動 · Cmd-Z 可還原整批",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "請把游標放在恰好一個節點上，然後再試一次",
        "Đổi tên «%@»": "重新命名「%@」",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "所有參照此節點的邊與標籤都會跟著更動。",
        "Đổi tên node": "重新命名節點",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "請至少選取兩個節點，然後再試一次",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "標準形式「%@」— 最常見、最長、帶符號",
        "Gộp node": "合併節點",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "請選取要移動的邊所在的行，然後再試一次",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "選取的所有行必須恰好接觸一個節點 — 請再多選一些邊的行",
        "Tách «%@» — chuyển %d cạnh": "分割「%1$@」— 移動 %2$d 條邊",
        "Cạnh tới: %@": "指向：%@ 的邊",
        "Tách node": "分割節點",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "文件尚未儲存 — 擷取出的檔案需要一個相鄰的位置",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "請選取要擷取的圖形部分，然後再試一次",
        "Gom biến thể entity → bảng duyệt": "歸併實體變體 → 審閱表",
        "Áp bảng duyệt đã sửa": "套用修改後的審閱表",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "文件尚未儲存 — 審閱表必須位於圖形檔案旁邊",
        "Không tìm thấy biến thể nào để gom": "找不到可歸併的變體",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d 組變體 — 請修正「canonical」欄位，然後執行「套用審閱表」",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "沒有審閱表「%@」— 請先執行「歸併實體變體」",
        "Bảng duyệt không đọc được: %@": "審閱表無法讀取：%@",
        "Bảng duyệt không có dòng nào cần đổi": "審閱表中沒有需要更動的列",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "圖形中沒有任何位置與審閱表相符",
        "Gom biến thể entity": "歸併實體變體",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "已套用 %d 項更動 · 別名表與標記列表已寫入檔案旁邊",
        "Áp %d thay đổi lên đồ thị?": "要對圖形套用 %d 項更動嗎？",
        "%d alias → dạng chuẩn.": "%d 個別名 → 標準形式。",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "合併節點（重新輸入無法還原）：",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d 個別名不在圖形中，已略過。",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "分塊 ↔ 實體涵蓋率分析",
        "Xuất gói ngữ cảnh (JSONL)": "輸出脈絡包（JSONL）",
        "Phủ Chunk ↔ Entity ↔ Graph": "分塊 ↔ 實體 ↔ 圖形 的涵蓋率",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d 個實體 · %2$d 個分塊 · %3$.0f%% 的實體被提及 · %4$.0f%% 的分塊含實體",
        "Entity không chunk nào nhắc tới": "沒有任何分塊提及的實體",
        "Chunk mồ côi (không chứa entity nào)": "孤立的分塊（不含任何實體）",
        "Node đồ thị không có entity đối ứng": "沒有對應實體的圖形節點",
        "không có": "無",
        "Phương pháp": "方法",
        "Không dựng được ánh xạ Chunk ↔ Entity": "無法建立 分塊 ↔ 實體 的對應",
        "Chấm sức khoẻ đồ thị": "評估圖形的健康度",
        "sức khoẻ đồ thị": "圖形健康度",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "健康度 %1$@/100 · %2$d 個錯誤 · %3$d 處反轉 · %4$d 個孤立項",
        "Lai với đồ thị": "與圖形混合",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1：完全忽略圖形的訊號，結果與純 BM25 相同",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α 較高：圖形只對 BM25 的排名做輕微調整",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α 在預設值 0.7 附近：BM25 主導，圖形做調整",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α 較低：圖形主導，BM25 只用來打破平手",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0：只用圖形的訊號；不含實體的分塊彼此相同",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "文件尚未儲存 — 混合檢索需要語料庫旁邊有一個圖形檔案",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "找不到圖形檔案「%@」— 混合檢索需要它來取得訊號",
        "lai %.1f ms · %@": "混合 %.1f 毫秒 · %@",
        "Thuật toán…": "演算法…",
        "PageRank (độ dày viền)": "PageRank（邊框粗細）",
        "Cộng đồng (màu nền)": "社群（背景色）",
        "Thành phần liên thông": "連通元件",
        "Xuất bảng node ra tab mới": "把節點表輸出到新的標籤頁",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d 個元件 · 最大的有 %2$d 個節點 · %3$d 個孤立節點",
        "Tài liệu này không phải đồ thị DOT": "此文件不是 DOT 圖形",
        "Không dựng được bảng node/cạnh: %@": "無法建立節點/邊表格：%@",
        "%d hàng · %@": "%d 列 · %@",
        "Gán nhãn": "標註",
        "Ghi chú (tuỳ chọn)": "備註（選填）",
        "Lưu record": "儲存記錄",
        "Xuất CSV": "輸出 CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "文件尚未儲存 — 評估器必須位於語料庫檔案旁邊",
        "Không nạp được bộ đánh giá: %@": "無法載入評估器：%@",
        "Không lưu được: %@": "無法儲存：%@",
        "Bộ đánh giá chưa có record nào": "評估器還沒有任何記錄",
        "Không ghi được: %@": "無法寫入：%@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "此文件不是 .mmd 檔案，不是 DOT，也沒有 mermaid 區塊。",
        "%d node · %d cạnh · ⚠ %@": "%d 個節點 · %d 條邊 · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid 圖：加入元素…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid 圖：連接選取的兩個元素",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid 圖：修改選取元素的標籤…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid 圖：刪除選取的元素",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid 圖：把訊息上移",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid 圖：把訊息下移",
        "Thêm phần tử": "加入元素",
        "Thêm participant": "加入參與者",
        "Thêm mục": "加入項目",
        "Thêm mục sơ đồ": "在圖中加入項目",
        "Sửa mục sơ đồ": "修改圖中的項目",
        "Xoá mục sơ đồ": "刪除圖中的項目",
        "Xoá phần tử": "刪除元素",
        "Sửa nhãn": "修改標籤",
        "Đổi thứ tự message": "重新排列訊息",
        "Tên mục": "項目名稱",
        "Mục mới": "新項目",
        "Tên mục hiện trên sơ đồ.": "項目名稱會顯示在圖上。",
        "Bảng thuộc tính sơ đồ": "圖的屬性表",
        "Tài liệu này không có khối mermaid nào": "此文件沒有 mermaid 區塊",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "圖原始碼中的識別碼 — 不含空格。標籤之後可按兩下修改。",
        "Để trống thì hiện chính định danh.": "留空則顯示識別碼本身。",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "只更動顯示的標籤；元素的識別碼維持不變。",
        "Không rõ «%@» là phần tử nào": "不清楚「%@」是哪個元素",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "請恰好選取兩個元素，然後再試一次",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "請把游標放在恰好一個元素上，然後再試一次",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "請選擇一個要刪除的元素，或兩個由邊連接的元素",
        "Xoá «%@» và %d cạnh chạm nó?": "要刪除「%1$@」以及與它相連的 %2$d 條邊嗎？",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "那些邊另一端的節點會保留 — 如果邊的敘述是它們唯一的宣告，會連同標籤一起重新宣告。",
        "Sơ đồ «%@» chỉ soạn text — %@": "圖「%1$@」只能以文字方式編輯 — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@：在兩個元素之間拖移即可連接，按兩下可修改標籤",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@：在兩個參與者之間拖移可加入訊息；可透過「工具」選單重新排列",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@：請在下方的屬性表中編輯",
        "Soạn trực quan đã bật": "已啟用視覺化編輯",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d 個項目 — 可直接在表中編輯，每個儲存格算一次還原",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "圓餅圖是一個數字；甘特圖則是冒號之後的內容。",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid 圖：把區塊擷取到 .mmd 檔案…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid 圖：把參照的檔案重新嵌入",
        "Tách khối sơ đồ": "擷取圖區塊",
        "Nhúng khối sơ đồ": "嵌入圖區塊",
        "Tách khối sơ đồ ra tệp riêng": "把圖區塊擷取到獨立檔案",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "檔案會放在文件旁邊；區塊中保留一行參照，這樣只需在一個地方編輯。",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "文件尚未儲存 — 圖檔案需要一個相鄰的位置",
        "Đã có tệp «%@» — chọn tên khác": "檔案「%@」已存在 — 請換一個名稱",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "已擷取到「%@」— 區塊中保留了一行參照",
        "Mở tệp": "打開檔案",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "已重新嵌入「%@」；檔案仍在磁碟上",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "此區塊包含真正的圖，而不是參照",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "此區塊參照「%@」— 請打開那個檔案進行編輯",
        "Không đọc được tệp sơ đồ %@": "無法讀取圖檔案 %@",
        "Soạn trực quan": "視覺化編輯",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "從一個節點拖移到另一個節點即可加入邊；按兩下可修改標籤。每次操作算一次還原。",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "視覺化編輯：在兩個節點之間拖移可加入邊，按兩下可修改標籤",
        "Soạn trực quan đã tắt": "已關閉視覺化編輯",
        "Thêm node…": "加入節點…",
        "Thêm cạnh giữa hai node đang chọn…": "在選取的兩個節點之間加入邊…",
        "Sửa nhãn node đang chọn…": "修改選取節點的標籤…",
        "Xoá node/cạnh đang chọn": "刪除選取的節點/邊",
        "Thêm node": "加入節點",
        "Thêm cạnh": "加入邊",
        "Sửa nhãn node": "修改節點標籤",
        "Xoá node": "刪除節點",
        "Xoá cạnh": "刪除邊",
        "Cmd-Z hoàn tác": "Cmd-Z 還原",
        "Tài liệu đang ở chế độ chỉ đọc": "此文件為唯讀",
        "Nhãn của «%@»": "「%@」的標籤",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "只更動顯示的標籤；節點的識別碼維持不變。",
        "Không rõ «%@» là node nào": "不清楚「%@」是哪個節點",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "DOT 檔案中的節點識別碼。標籤之後可在圖上按兩下修改。",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "請恰好選取兩個節點，然後再試一次",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "請選擇一個要刪除的節點，或兩個由邊連接的節點",
        "Xoá node «%@» và %d cạnh chạm nó?": "要刪除節點「%1$@」以及與它相連的 %2$d 條邊嗎？",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "如果留下懸空的邊，DOT 會依此重新產生節點 — 被刪除的節點會在下次繪製時再度出現。",
        "Phòng thí nghiệm truy hồi BM25": "BM25 檢索實驗室",
        "Câu hỏi — Enter để tìm": "問題 — 按 Enter 搜尋",
        "Đánh giá…": "評估…",
        "Đang dựng chỉ mục": "正在建立索引",
        "Không chunk nào khớp": "沒有相符的分塊",
        "kết quả trên": "個最佳結果",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0：每個詞只計一次，不論出現多少次",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 較低：重複某個詞幾乎不會增加分數",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 在預設值 1.2 附近：重複會增加分數，但增幅遞減",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 較高：重複某個詞很多次的分塊會得到很高的獎勵",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0：忽略長度，長分塊不受懲罰",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b 較低：長分塊只受到輕微懲罰",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b 在預設值 0.75 附近：長分塊受到中等懲罰",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1：依長度施加最大懲罰，短分塊較受青睞",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL：檢索實驗室…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "文件尚未儲存 — BM25 索引位於語料庫檔案旁邊，因此需要一個路徑",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "此檔案不是 JSONL — Retrieval Lab 執行於分塊語料庫之上",
        "Không dựng được chỉ mục BM25 cho tệp này": "無法為此檔案建立 BM25 索引",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "文件尚未儲存 — 產生報告需要一個語料庫路徑",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "選擇評估集（CSV 或 JSONL：問題 + 期望的分塊編號）",
        "Đánh giá truy hồi": "檢索評估",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "修改上方的 k1、b 或 k 後重新查看，即可比較兩種設定；加入一個「compare」區塊可在同一個評估集上平行執行兩組參數。",
        "Lỗi": "錯誤",
        "   (%d…%d, trung bình %.0f)": "   （%d…%d，平均 %.0f）",
        "Chế độ JSONL": "JSONL 模式",
        "Bản ghi": "記錄",
        "Chi tiết": "詳細資料",
        "Bản ghi ở dòng": "行中的記錄",
        "không phải JSON hợp lệ": "不是有效的 JSON",
        "bản ghi": "筆記錄",
        "dòng trắng": "空行",
        "không phải đối tượng": "不是物件",
        "bảng hiện": "顯示的表格",
        "ĐÃ HUỶ giữa chừng": "中途已取消",
        "Không lọc": "不篩選",
        "bản ghi khớp bộ lọc": "筆記錄符合篩選條件",
        "Đưa con nháy tới một dòng để xem bản ghi": "把游標移到某一行即可查看記錄",
        "Không có bản ghi nào hỏng": "沒有損毀的記錄",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "尚未檢視。驗證完成後請重新執行「JSONL：檢視分塊」。",
        "trường văn bản": "文字欄位",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "綱要（推測 — 可透過選擇其他欄位更動）",
        "văn bản": "文字",
        "định danh": "識別碼",
        "metadata lồng": "巢狀中繼資料",
        "TRƯỜNG": "欄位",
        "phủ": "涵蓋率",
        "nhiều kiểu": "多種型別",
        "ĐỘ DÀI — ký tự": "長度 — 字元",
        "ĐỘ DÀI — từ": "長度 — 詞",
        "ĐỘ DÀI — token ước lượng": "長度 — 估計詞元",
        "RỖNG VÀ TRÙNG": "空值與重複",
        "chunk rỗng": "個空分塊",
        "dòng": "行",
        "nhóm trùng chính xác": "組完全重複",
        "dòng không đọc được, không vào thống kê": "行無法讀取，不計入統計",
        "PHƯƠNG PHÁP": "方法",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "「字元」依 Unicode 字元（純量）計數，而不是依顯示的字形群",
        "«từ» tách theo khoảng trắng ASCII": "「詞」依 ASCII 空格切分",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "「詞元」以音節切分器計數 — 不是模型的切分器",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "「重複」指完全重複；近似重複在 ```quality 區塊中",
        "chunk": "個分塊",
        "JSONL: kiểm và soi chunk…": "JSONL：驗證並檢視分塊…",
        "Ảnh": "影像",
        "PDF": "PDF",
        "Tài liệu Word": "Word 文件",
        "Bảng tính Excel": "Excel 試算表",
        "Bản trình chiếu PowerPoint": "PowerPoint 簡報",
        "File nén": "壓縮檔",
        "Vừa khung": "符合視窗",
        "Chép ảnh": "拷貝影像",
        "Xoay": "旋轉",
        "Không đọc được ảnh «%@»": "無法讀取影像「%@」",
        "Đã chép ảnh vào clipboard": "已把影像拷貝到剪貼板",
        "Bôi vàng": "標為黃色",
        "Gạch chân": "底線",
        "Ghi chú…": "備註…",
        "Bỏ chú thích": "移除註解",
        "Lấy chữ ra tab mới": "把文字擷取到新的標籤頁",
        "Lưu bản có chú thích…": "儲存帶註解的版本…",
        "Tìm trong PDF": "在 PDF 中搜尋",
        "Thêm": "加入",
        "Trang %d/%d": "第 %d/%d 頁",
        "Trang %d": "第 %d 頁",
        "Kết quả %d/%d": "第 %d/%d 個結果",
        "0 kết quả": "0 個結果",
        "Không đọc được PDF «%@»": "無法讀取 PDF「%@」",
        "PDF này có mật khẩu — chưa mở được nội dung": "此 PDF 有密碼保護 — 無法存取內容",
        "Không thấy «%@» trong tài liệu": "在文件中找不到「%@」",
        "Đã bôi vàng": "已標示",
        "Đã gạch chân": "已加底線",
        "Hãy bôi đen một đoạn chữ trước": "請先選取一段文字",
        "Đã thêm ghi chú": "已加入備註",
        "Trang này chưa có chú thích nào": "此頁沒有任何註解",
        "Đã bỏ %d chú thích trên trang này": "已從此頁移除 %d 個註解",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "此 PDF 沒有文字層 — 很可能是掃描檔",
        "Không ghi được tệp": "無法寫入檔案",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "寫出的檔案無法正確重新打開 — 請不要使用這個版本",
        "Đã lưu %@ · %d trang": "已儲存 %@ · %d 頁",
        "Tên": "名稱",
        "Kích thước": "大小",
        "Đã nén": "壓縮後",
        "Tỉ lệ": "比例",
        "Sửa lúc": "修改於",
        "Mở mục đang chọn": "打開選取的項目",
        "Bung ra thư mục…": "解壓縮到檔案夾…",
        "Bung vào đây": "解壓縮到此處",
        "%d mục": "%d 個項目",
        "giải nén ra %@": "已解壓縮到 %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— Office 檔案的內部就是一個壓縮檔，這些是它的組成部分",
        "Đã bung %d mục": "已解壓縮 %d 個項目",
        "%d mục hỏng": "%d 個項目損毀",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d 個項目被拒絕，因為它們的路徑超出了目標檔案夾",
        "Không mở được mục này": "無法打開此項目",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "暫時無法直接寫回 %@ — 請使用「另存為…」",
        "Không có gì đổi": "沒有任何更動",
        "Đã ghi %d ô vào %@": "已把 %1$d 個儲存格寫入 %2$@",
        "Đã ghi %d đoạn vào %@": "已把 %1$d 個段落寫入 %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "無法寫入檔案 — 原始檔案完整無缺",
        "dựng bài": "準備測試案例",
        "Không ghi được settings.json": "無法寫入 settings.json",
        "Xoay trái": "向左旋轉",
        "Xoay phải": "向右旋轉",
        "Trang lên": "頁面上移",
        "Trang xuống": "頁面下移",
        "Xoá trang…": "刪除頁面…",
        "Xoá trang": "刪除頁面",
        "Trích trang…": "擷取頁面…",
        "Trích trang ra tệp mới": "擷取頁面至新檔案",
        "Gộp tệp PDF…": "合併 PDF 檔案…",
        "Tách tệp…": "分割檔案…",
        "Tách tệp PDF": "分割 PDF 檔案",
        "Xuất ảnh…": "匯出圖片…",
        "Xuất trang ra ảnh PNG": "將頁面匯出為 PNG 圖片",
        "Hoàn tác trang": "還原頁面操作",
        "Lưu bản đã sửa…": "儲存已編輯的副本…",
        "Phát": "播放",
        "Tạm dừng": "暫停",
        "Xem bình thường": "一般檢視",
        "Chọn sheet": "選擇工作表",
        "Mở sheet": "打開工作表",
        "Bỏ và đổi sheet": "捨棄並切換工作表",
        "Bảng tính có %d sheet.": "活頁簿有 %d 個工作表。",
        "Bảng tính này chỉ có một sheet: «%@»": "此活頁簿只有一個工作表：「%@」",
        "Bỏ phần chưa lưu của sheet này?": "捨棄此工作表中未儲存的更動？",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "切換工作表會取代整個標籤頁。未用 ⌘S 儲存的內容將遺失。",
        "Chọn tệp PDF cần gộp vào": "選擇要合併的 PDF 檔案",
        "Chọn thư mục ghi ảnh": "選擇存放圖片的檔案夾",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "選擇儲存位置。第二個檔案會寫在它旁邊。",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "文件有 %d 頁。輸入要刪除的頁面，例如 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "文件有 %d 頁。輸入要擷取的頁面，例如 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "文件有 %d 頁。輸入要匯出的頁面，例如 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "文件有 %d 頁。輸入要分割出的部分，例如 1-5；其餘成為第二個檔案。",
        "Đã xoay trang %d": "已旋轉第 %d 頁",
        "Đã xoá trang %@ · còn %d trang": "已刪除第 %@ 頁 · 剩餘 %d 頁",
        "Đã gộp %d trang từ «%@»": "已從「%2$@」合併 %1$d 頁",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "已分割為 %@（%d 頁）和 %@（%d 頁）",
        "Đã ghi %@ — %@ · %d trang": "已寫入 %@ — %@ · %d 頁",
        "Đã xuất %d ảnh vào %@": "已匯出 %d 張圖片到 %@",
        "Chỉ xuất được %d/%d ảnh": "只匯出了 %d/%d 張圖片",
        "Đã hoàn tác một thao tác trang": "已還原一次頁面操作",
        "Không còn thao tác trang nào để hoàn tác": "沒有可還原的頁面操作了",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "無法刪除全部頁面——PDF 至少要保留一頁",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "該範圍就是整份文件——沒有可分割的部分",
        "«%@» có mật khẩu — chưa gộp được": "「%@」有密碼保護——無法合併",
        "«%@» không có trang nào": "「%@」沒有任何頁面",
        "Đã ở trang đầu": "已在第一頁",
        "Đã ở trang cuối": "已在最後一頁",
        "· đã sửa, chưa lưu": "· 已編輯，未儲存",
        "Ảnh động · %d khung": "動態圖片 · %d 幀",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "文件未儲存——磁碟上沒有可用於二進位檢視的檔案",
        "Lệnh này chỉ dùng cho bảng tính Excel": "此指令僅適用於 Excel 活頁簿",
        "Không đọc được danh sách sheet": "無法讀取工作表列表",
        "Không có sheet «%@»": "沒有名為「%@」的工作表",
        "Không đọc được sheet «%@»": "無法讀取工作表「%@」",
        "Sheet «%@» · %d hàng": "工作表「%@」· %d 列",
        "phần còn lại": "其餘部分",
        "Lưu ý": "注意",
        "Cẩn thận": "小心",
        "Xem thêm": "另請參閱",
        "Chép": "拷貝",
        "Đã chép": "已拷貝",
        "Chép đoạn mã mẫu": "拷貝範例程式碼",
        "Tìm trong trợ giúp": "搜尋輔助說明",
        "Lùi": "返回",
        "Bắt đầu dùng": "開始使用",
        "Không mở cửa sổ này khi khởi động nữa": "啟動時不再顯示此視窗",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "輔助說明尚未翻譯成此語言——顯示越南文文字。",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "跳至偏移量（例如 1F400 或 0x1F400）",
        "Chép dòng đã chọn": "拷貝所選列",
        "Đã chép %d dòng": "已拷貝 %d 列",
        "Không đọc được «%@»": "無法讀取「%@」",
        "Tệp rỗng": "空檔案",
        "Không đọc được offset «%@»": "無法讀取偏移量「%@」",
        "Offset 0x%@ vượt quá cỡ tệp": "偏移量 0x%@ 超出檔案大小",
        "Mở bằng ứng dụng khác…": "用其他 App 打開…",
        "%d kênh": "%d 聲道",
        "Không phát được «%@»": "無法播放「%@」",
        "Không phát được — %@": "無法播放 — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS 沒有內建 %@ 格式的解碼器——這是系統限制，不是檔案損壞。",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "你仍可在二進位檢視中查看位元組，或用自帶解碼器的 App 打開。",
        "Ký…": "簽名…",
        "Sửa chữ…": "編輯文字…",
        "Sửa chữ": "編輯文字",
        "Vẽ đè": "覆蓋繪製",
        "Ô chưa điền": "下一個空白欄",
        "Xoá nội dung đã điền": "清除已填內容",
        "Tệp này không có ô biểu mẫu nào": "此檔案沒有表單欄位",
        "Đã xoá nội dung của %d ô biểu mẫu": "已清除 %d 個表單欄位",
        "Mọi ô biểu mẫu đều đã có nội dung": "所有表單欄位都已填寫",
        "Còn %d ô chưa điền": "還有 %d 個欄位未填",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "可填寫表單：%d 個欄位。直接輸入，然後「儲存已編輯的副本…」",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "選擇簽名圖片（透明背景效果最好）",
        "Không dựng được trang có chữ ký": "無法產生已簽名的頁面",
        "Đã chèn chữ ký vào trang %d": "已在第 %d 頁插入簽名",
        "Hãy bôi chọn phần chữ cần sửa trước": "請先選取要修改的文字",
        "Vùng chọn quá nhỏ": "所選區域太小",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "新文字用系統字體覆蓋繪製在所選區域上。舊文字只是被遮住，並未刪除——仍可被擷取，所以這不是塗黑。",
        "Không dựng được trang đã sửa": "無法產生已編輯的頁面",
        "Đã vẽ đè chữ mới lên trang %d": "已在第 %d 頁覆蓋繪製新文字",
        "Đổi chế độ View / Code": "切換檢視 / 原始碼",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "JSON · XML · YAML 尚無樹狀檢視",
        "Chưa có chế độ View dạng sơ đồ trong tab": "標籤頁內尚無圖表檢視",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "PowerPoint 尚無大綱檢視",
        "Tệp này chỉ có một chế độ hiển thị": "此檔案只有一種顯示模式",
        "%d nút": "%d 個節點",
        "Không dựng được cây: %@": "無法建立樹狀結構：%@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "文件太大，無法建立樹狀結構——請使用原始碼模式",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "無法為此檔案產生頁面 \u{2014} 請使用 Code 模式。",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.": "投影片由文字產生；原始圖片與版面尚未重繪。",
        "Vừa ngang": "適合寬度",
        "Thu nhỏ trang": "縮小頁面",
        "Phóng to trang": "放大頁面",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "在本文件中找不到「%@」",
        "Chỗ khớp %d/%d": "第 %d 處，共 %d 處",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "頁面上沒有選取文字。",
        "%d ký tự": "%d 個字元",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có": "有 View 的檔案直接以 View 模式開啟",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· 中途已取消 — 表格不完整",
        "Chế độ hiển thị": "顯示模式",
        "Đổi giữa View và Code (⌥⌘V)": "在 View 與 Code 之間切換（⌥⌘V）",
        "Trang tài liệu": "文件頁面",
        "Chữ đã dựng": "排版文字",
        "Trang bảng tính": "試算表頁面",
        "Sơ đồ": "圖表",
        "Cây khoá–giá trị": "鍵–值樹",
        "Bộ phát": "播放器",
        "Danh sách mục": "項目清單",
        "Báo cáo đã dựng": "已產生的報告",
        "Tô theo mức": "依層級著色",
        "Trang slide": "投影片頁面",
        "Dàn ý": "大綱",
        "Lưu rồi dựng lại": "儲存並重新排版",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "顯示的是磁碟上的副本 — 未儲存的修改不在其中。",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "系統無法建立文件檢視 — 請使用 Code 模式。",
        "Lưu tệp trước khi xem trang.": "檢視頁面前請先儲存檔案。",
        "Đang ở chế độ Code": "目前為 Code 模式",
        "Đang ở chế độ View": "目前為 View 模式",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "正在檢視原始碼 — 點按切換到 View 模式（⌥⌘V）",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "View 模式 — 點按返回原始碼（⌥⌘V）",
        "Tín hiệu: %@": "訊號：%@",
        "Lý do: %@": "原因：%@",
        "Chi tiết: %@": "詳情：%@",
        "Mở báo cáo": "開啟報告",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor 於 %@ 意外結束 — 開啟報告即可閱讀；不會傳送任何內容。",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "連字 — 關閉後每個字元各佔一格",
        "Chế độ CSV": "CSV 模式",
        "Dấu phân tách": "分隔符號",
        "Tự nhận diện": "自動辨識",
        "Dấu phân tách: %@": "分隔符號：%@",
        "Theo đuôi tệp": "依副檔名",
        "%d dấu cách": "%d 個空格",
        "Tài liệu đang sửa được": "這份文件可以編輯",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "唯讀：正在追蹤該檔案 — 停止追蹤後才能編輯",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "唯讀：磁碟上的檔案無法寫入",
        "Đã mở khoá — tài liệu sửa được": "已解鎖 — 文件可以再次編輯",
        "Nhân bản tệp": "複製檔案",
        "Đổi tên tệp…": "重新命名檔案…",
        "Chuyển tệp tới…": "移動檔案到…",
        "XML: đánh giá XPath…": "XML：求值 XPath…",
        "Đánh giá XPath": "求值 XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "例如：//order/item[2]/@code · //*[@kind='A'] · count(//item)",
        "Đánh giá": "求值",
        "XPath không đọc được: %@": "無法讀取這個 XPath：%@",
        "XPath «%@» không khớp node nào": "XPath「%@」沒有符合任何節點",
        "XPath «%@» — %d node": "XPath「%@」— %d 個節點",
        "XPath «%@»: %d node": "XPath「%@」：%d 個節點",
        "Lưu tệp trước khi nhân bản.": "複製前請先儲存檔案。",
        "Không nhân bản được": "無法複製",
        "Đã nhân bản thành %@": "已複製為 %@",
        "Lưu tệp trước khi đổi tên.": "重新命名前請先儲存檔案。",
        "Đổi tên tệp": "重新命名檔案",
        "Tên hiện tại: %@": "目前名稱：%@",
        "Đổi tên": "重新命名",
        "Tên tệp không hợp lệ": "這個檔名無效",
        "Đã có tệp tên %@ ở đó": "那裡已有名為 %@ 的檔案",
        "Lưu tệp trước khi chuyển.": "移動前請先儲存檔案。",
        "Chuyển tới": "移動到這裡",
        "Thư mục đích đã có tệp tên %@": "目標資料夾已有名為 %@ 的檔案",
        "Không chuyển được tệp": "無法移動檔案",
        "Đã chuyển tới %@": "已移動到 %@",
        "Bảng mã:": "字元編碼：",
        "Xuống dòng:": "換行字元：",
        "Riêng cho %@": "僅用於 %@",
        "    %d — dùng TAB": "    %d — 使用定位字元",
        "    %d — dùng dấu cách": "    %d — 使用空格",
        "    Bỏ khai riêng, dùng cài đặt chung": "    移除個別設定，改用全域設定",
        "%@: thụt lề %d %@": "%@：縮排 %d %@",
        "TAB": "定位字元",
        "dấu cách": "空格",
        "Xuất": "匯出",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "將結果以文字標籤頁開啟 — 用 ⌘S 儲存",
        "Lượt tìm trước đó": "先前的搜尋",
        "«%@» — %d kết quả": "「%@」— %d 筆結果",
        "Kết quả tìm «%@»": "「%@」的搜尋結果",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "篩選檔名 — 例如 *.csv;*.log（留空：所有文字檔）",
        "Thư mục %@ không có file văn bản nào": "資料夾 %@ 中沒有文字檔",
        "Không tệp nào trong %@ khớp «%@»": "%@ 中沒有檔案符合「%@」",
        "%d byte · %d dòng": "%d 位元組 · %d 行",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d 位元組 · %d 行 — 太大，無法統計字元與字數",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d 位元組 · %d 個字元 · %d 個字 · %d 行",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "本文件共 %d 行、%d 位元組。請輸入行號、「行,欄」或「@位元組」。",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "無法讀取「%@」— 請輸入行號、「行,欄」或「@位元組」",
    ]
}
