import Foundation

/// Bảng dịch tiếng Bồ Đào Nha. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let pt: [String: String] = [
        "Bản đã lưu…": "Versões guardadas…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Este documento nunca foi guardado — sem histórico",
        "Chưa có bản đã lưu nào trước đó": "Não há versões guardadas anteriores",
        "Không đọc được bản ấy": "Não é possível ler essa versão",
        "Khôi phục bản đã lưu": "Restaurar a versão guardada",
        "XML: kiểm theo DTD/XSD…": "XML: validar com DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Este Mac não tem libxml2, por isso a validação XSD não está disponível.",
        "Chọn lược đồ XSD để kiểm": "Escolher um esquema XSD para validar",
        "Hợp lệ theo": "Válido segundo",
        "Plugin chạy xong, không đổi gì": "A extensão terminou sem alterar nada",
        "Chưa cài plugin native nào": "Nenhuma extensão nativa instalada",
        "Gỡ plugin này": "Remover esta extensão",
        "Gỡ plugin này?": "Remover esta extensão?",
        "Gỡ": "Remover",
        "Cài plugin native…": "Instalar uma extensão nativa…",
        "Mở thư mục plugin": "Abrir a pasta de extensões",
        "Chọn file .dylib của plugin native": "Escolher o ficheiro .dylib da extensão",
        "Đã cài:": "Instalado:",
        "Đã gỡ:": "Removido:",
        "Plugin native…": "Extensões nativas…",
        "Chỉ nhận file .dylib.": "Só são aceites ficheiros .dylib.",
        "Đã có một plugin trùng tên:": "Já existe uma extensão com o mesmo nome:",
        "Không chép được plugin:": "Não é possível copiar a extensão:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "As extensões nativas só existem na transferência direta, não na versão da App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Processo auxiliar de extensões não encontrado.",
        "Không khởi động được tiến trình phụ:": "Não é possível iniciar o processo auxiliar:",
        "Tiến trình plugin đã dừng giữa chừng.": "O processo da extensão parou a meio.",
        "Plugin không trả lời kịp — đã dừng nó.": "A extensão não respondeu a tempo — foi interrompida.",
        "Plugin trả lời sai giao thức:": "A extensão respondeu com uma mensagem malformada:",
        "Plugin báo lỗi:": "A extensão reportou um erro:",
        "Về GEditor": "Acerca do GEditor",
        "Cài đặt…": "Definições…",
        "Thoát GEditor": "Sair do GEditor",
        "File": "Ficheiro",
        "Tab mới": "Novo separador",
        "Đóng tab": "Fechar separador",
        "Tab kế": "Separador seguinte",
        "Tab trước": "Separador anterior",
        "Tài liệu mới": "Novo documento",
        "Mở…": "Abrir…",
        "Mở thư mục làm Workspace…": "Abrir uma pasta como área de trabalho…",
        "Mở gần đây": "Abrir recente",
        "Lưu": "Guardar",
        "Lưu thành…": "Guardar como…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Remover espaços no fim da linha ao guardar",
        "Theo dõi file (tail -f)": "Seguir o ficheiro (tail -f)",
        "In…": "Imprimir…",
        "Mở lại tab vừa đóng": "Reabrir o separador fechado",
        "Chưa có file nào": "Não há ficheiros",
        "Xoá danh sách": "Limpar a lista",
        "Edit": "Editar",
        "Hoàn tác": "Anular",
        "Làm lại": "Refazer",
        "Cắt": "Cortar",
        "Sao chép": "Copiar",
        "Dán": "Colar",
        "Lịch sử clipboard…": "Histórico da área de transferência…",
        "Column Editor…": "Editor de colunas…",
        "Chọn lần kế tiếp": "Selecionar a ocorrência seguinte",
        "Chọn tất cả": "Selecionar tudo",
        "Nhân đôi dòng": "Duplicar a linha",
        "Xóa dòng": "Eliminar a linha",
        "Comment dòng": "Comentar a linha",
        "Chưa chép gì trong phiên này": "Nada foi copiado nesta sessão",
        "Xoá lịch sử": "Limpar o histórico",
        "Search": "Pesquisar",
        "Tìm…": "Procurar…",
        "Tìm và thay…": "Procurar e substituir…",
        "Tìm trong thư mục…": "Procurar numa pasta…",
        "Thay trong thư mục…": "Substituir numa pasta…",
        "Kết quả kế": "Resultado seguinte",
        "Kết quả trước": "Resultado anterior",
        "Đi tới dòng…": "Ir para a linha…",
        "Nhảy tới ngoặc khớp": "Ir para o parêntesis correspondente",
        "Đánh dấu mọi dòng khớp…": "Marcar todas as linhas correspondentes…",
        "Đảo dấu": "Inverter as marcas",
        "Bỏ mọi dấu": "Remover todas as marcas",
        "Chép dòng đã đánh dấu": "Copiar as linhas marcadas",
        "Xóa dòng đã đánh dấu": "Eliminar as linhas marcadas",
        "Chỉ giữ dòng đã đánh dấu": "Manter apenas as linhas marcadas",
        "Lines": "Linhas",
        "Sắp xếp A→Z": "Ordenar A→Z",
        "Sắp xếp Z→A": "Ordenar Z→A",
        "Sắp xếp tự nhiên": "Ordenação natural",
        "Khử trùng lặp": "Remover duplicados",
        "Đảo thứ tự dòng": "Inverter a ordem das linhas",
        "Dời dòng lên": "Subir a linha",
        "Dời dòng xuống": "Descer a linha",
        "Ghép dòng": "Juntar linhas",
        "Tách dòng theo độ dài…": "Dividir linhas por comprimento…",
        "Tách dòng theo ký tự…": "Dividir linhas por caráter…",
        "Xóa dòng rỗng": "Eliminar linhas vazias",
        "Nén dòng trống liên tiếp": "Reduzir linhas vazias consecutivas",
        "Cắt khoảng trắng cuối dòng": "Remover espaços no fim da linha",
        "Tab → Space": "Tab → Espaço",
        "Space → Tab": "Espaço → Tab",
        "HOA": "MAIÚSCULAS",
        "thường": "minúsculas",
        "Chữ Hoa Đầu Từ": "Maiúscula Em Cada Palavra",
        "Chữ hoa đầu câu": "Maiúscula no início da frase",
        "Đảo hoa/thường": "iNVERTER mAIÚSCULAS",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: escolher folha…",
        "Xem dạng bảng / văn bản": "Alternar vista de tabela / texto",
        "Xóa cột…": "Eliminar coluna…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Validar os dados (número de colunas · tipos)",
        "Bàn làm sạch dữ liệu…": "Bancada de limpeza de dados…",
        "Chạy công thức làm sạch…": "Executar uma receita de limpeza…",
        "Chuyển đổi…": "Converter…",
        "Đổi dấu phân tách…": "Mudar o separador…",
        "Xuất sang JSON…": "Exportar para JSON…",
        "Format": "Formato",
        "Bảng mã…": "Codificação…",
        "Xuống dòng…": "Fim de linha…",
        "Chuẩn hóa Unicode…": "Normalizar Unicode…",
        "JSON: định dạng lại": "JSON: formatar",
        "JSON: thu gọn một dòng": "JSON: compactar numa linha",
        "JSON: sắp xếp khóa": "JSON: ordenar chaves",
        "JSON: truy vấn JSONPath…": "JSON: consulta JSONPath…",
        "CSV: truy vấn SQL…": "CSV: consulta SQL…",
        "Truy vấn SQL": "Consulta SQL",
        "Đang chạy…": "A executar…",
        "Xuất ra tab mới": "Exportar para um separador novo",
        "Tài liệu rỗng — không có bảng để truy vấn": "Documento vazio — não há tabela para consultar",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Não é uma tabela CSV — a primeira linha só tem uma coluna",
        "Không đọc được câu truy vấn": "Não é possível ler a consulta",
        "Không kiểm được câu truy vấn": "Não é possível verificar a consulta",
        "Vàng (mặc định)": "Amarelo (predefinido)",
        "Xanh dương": "Azul",
        "Xanh lá": "Verde",
        "Vàng đất": "Ocre",
        "Tím": "Roxo",
        "Hồng": "Rosa",
        "Xanh ngọc": "Turquesa",
        "Cam": "Laranja",
        "Xám lam": "Ardósia",
        "Văn bản": "Texto",
        "Dãy số": "Série numérica",
        "Dãy ngày": "Série de datas",
        "Chữ HOA (hex)": "MAIÚSCULAS (hexadecimal)",
        "Bắt đầu": "Início",
        "Bước": "Passo",
        "Đệm 0 tới": "Preencher com zeros até",
        "Hệ": "Base",
        "Ngày đầu": "Primeira data",
        "Định dạng": "Formato",
        "Chèn": "Inserir",
        "Huỷ": "Cancelar",
        "Chuyển đổi định dạng": "Converter o formato",
        "Xem trước 5 hàng đầu": "Pré-visualizar as 5 primeiras linhas",
        "Tạo tab mới": "Abrir num separador novo",
        "Lưu ra file…": "Guardar num ficheiro…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "O resultado abre num separador novo por guardar. O documento original fica intacto.",
        "Chạy trên tài liệu này": "Executar neste documento",
        "Chạy trên thư mục…": "Executar numa pasta…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "A receita inteira é UM passo de anulação. O ficheiro no disco fica intacto até guardares.",
        "tắt": "desligado",
        "không thấy cột": "coluna não encontrada",
        "sẵn sàng": "pronto",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "continua a ocupar um núcleo do CPU até a aplicação fechar.",
        "Script không trả về gì": "O script não devolveu nada",
        "Không dựng được máy JavaScript": "Não foi possível criar o motor de JavaScript",
        "Lỗi JavaScript không rõ": "Erro de JavaScript desconhecido",
        "Bảng": "Tabela",
        "Áp sắp xếp vào file": "Aplicar a ordenação ao ficheiro",
        "Chuyển đổi ▾": "Converter ▾",
        "Xuất dòng khớp": "Exportar as linhas correspondentes",
        "Ẩn cột này": "Ocultar esta coluna",
        "Đổi tên tiêu đề…": "Mudar o nome do cabeçalho…",
        "Chèn cột trống bên trái": "Inserir uma coluna vazia à esquerda",
        "Chèn cột trống bên phải": "Inserir uma coluna vazia à direita",
        "Xóa cột này khỏi file…": "Eliminar esta coluna do ficheiro…",
        "Phải còn ít nhất một cột đang hiện": "Tem de ficar pelo menos uma coluna visível",
        "Đang sắp xếp…": "A ordenar…",
        "Trở về thứ tự trong file": "Voltar à ordem do ficheiro",
        "trăm hàng đầu": "primeiras cem linhas",
        "chọn cột": "escolher colunas",
        "đặt tên cột kết quả": "nomear uma coluna do resultado",
        "lọc theo chữ": "filtrar por texto",
        "ô rỗng": "células vazias",
        "ghép điều kiện": "combinar condições",
        "đếm hàng": "contar linhas",
        "gộp nhóm": "agrupar e agregar",
        "nhỏ nhất, lớn nhất": "mínimo, máximo",
        "sắp xếp và cắt": "ordenar e limitar",
        "tên cột có dấu cách": "nome de coluna com espaços",
        "Truy vấn bị dừng giữa chừng": "A consulta foi interrompida",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Não suportado: JOIN · subconsulta · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funções de janela",
        "XML: định dạng lại": "XML: formatar",
        "XML: thu gọn một dòng": "XML: compactar numa linha",
        "XML: kiểm cú pháp": "XML: verificar a sintaxe",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: verificar chaves duplicadas e indentação",
        "View": "Ver",
        "Ẩn/hiện sidebar (Function List)": "Mostrar/ocultar a barra lateral (lista de funções)",
        "Ẩn/hiện bản đồ tài liệu": "Mostrar/ocultar o mapa do documento",
        "Gấp / mở khối tại con nháy": "Dobrar / desdobrar o bloco no cursor",
        "Gấp tất cả": "Dobrar tudo",
        "Bỏ gấp tất cả": "Desdobrar tudo",
        "Gấp theo cấp": "Dobrar por nível",
        "Cấp %d": "Nível %d",
        "Đã gấp %d khối ở cấp %d": "%d {one=bloco dobrado|other=blocos dobrados} no nível %d",
        "Tài liệu này chỉ sâu %d cấp": "Este documento só tem %d {one=nível|other=níveis} de profundidade",
        "mermaid: không đọc được bản kê": "mermaid: manifesto ilegível",
        "Kiểm tra bản cập nhật…": "Procurar atualizações…",
        "Kiểm tra bản cập nhật": "Procurar atualizações",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "As versões da App Store atualizam-se pela Mac App Store, não pelo GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Esta versão não tem chave de assinatura de atualizações, por isso não as pode procurar.",
        "Phóng to chữ": "Aumentar o texto",
        "Thu nhỏ chữ": "Reduzir o texto",
        "Cỡ chữ gốc": "Tamanho real",
        "Chia đôi theo chiều dọc": "Dividir verticalmente",
        "Chia đôi theo chiều ngang": "Dividir horizontalmente",
        "Bỏ chia đôi": "Fechar a divisão",
        "Mở tab này ở nửa kia": "Abrir este separador no outro painel",
        "Nhảy sang nửa kia": "Ir para o outro painel",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Moldar linha (desligado / janela / coluna)",
        "Ngắt dòng tại cột…": "Moldar na coluna…",
        "Đánh dấu dòng này": "Marcar esta linha",
        "Dấu kế tiếp": "Marca seguinte",
        "Dấu trước đó": "Marca anterior",
        "Màu đánh dấu…": "Cor das marcas…",
        "Hiện tất cả ký tự ẩn": "Mostrar todos os carateres invisíveis",
        "  Khoảng trắng": "  Espaços",
        "  Tab": "  Tabulações",
        "  Xuống dòng": "  Fins de linha",
        "  NBSP · zero-width · điều khiển": "  NBSP · largura zero · controlo",
        "Xem nhị phân": "Vista binária",
        "Chế độ CSV (tô màu theo cột)": "Modo CSV (colunas a cores)",
        "Macro": "Macro",
        "Bắt đầu / dừng ghi": "Iniciar / parar a gravação",
        "Phát lại": "Reproduzir",
        "Phát nhiều lần…": "Reproduzir várias vezes…",
        "Phát đến cuối tài liệu": "Reproduzir até ao fim do documento",
        "Chạy trên mọi tab": "Executar em todos os separadores",
        "Hủy macro đang chạy": "Cancelar a macro em curso",
        "Lưu macro…": "Guardar a macro…",
        "Macro đã lưu…": "Macros guardadas…",
        "Help": "Ajuda",
        "Trợ giúp GEditor": "Ajuda do GEditor",
        "Giới thiệu tính năng": "Conheça os recursos",
        "Di cư từ Notepad++": "Migrar do Notepad++",
        "Tìm": "Procurar",
        "Thay bằng": "Substituir por",
        "Kế": "Seguinte",
        "Trước": "Anterior",
        "Đếm": "Contar",
        "Đóng": "Fechar",
        "Kiểm theo JSON Schema…": "Validar com um esquema JSON…",
        "Chọn tệp JSON Schema": "Escolher um ficheiro de esquema JSON",
        "Không thấy lỗi nào theo schema này.": "Não foram encontrados problemas segundo este esquema.",
        "JSON Schema": "Esquema JSON",
        "Kiểm cú pháp đồ thị": "Verificar a sintaxe do grafo",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Formato de grafo não reconhecido — é preciso uma extensão .dot, .gv, .cypher, .ttl ou .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Não foram encontrados erros de sintaxe %@ (a verificação não é exaustiva).",
        "Cú pháp %@": "Sintaxe %@",
        "không phải một đối tượng JSON": "não é um objeto JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Mineração de texto (n-gramas, TF-IDF)",
        "Tài liệu rỗng.": "O documento está vazio.",
        "Không rút được từ khoá nào.": "Não foi possível extrair nenhuma palavra-chave.",
        "Từ khoá": "Palavras-chave",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=palavra-chave|other=palavras-chave} · %d {one=token|other=tokens} · %d {one=documento|other=documentos}",
        "Tô lên tài liệu": "Marcar no documento",
        "Đánh dấu entity từ danh sách…": "Marcar entidades a partir de uma lista…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Escolher uma lista de entidades (CSV ou JSON)",
        "Không đọc được danh sách entity.": "Não é possível ler a lista de entidades.",
        "Danh sách entity rỗng.": "A lista de entidades está vazia.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Não foram encontradas entidades no documento (%d carregadas).",
        "%d lần xuất hiện · %@": "%d {one=ocorrência|other=ocorrências} · %@",
        "Chuyển đổi tri thức…": "Converter conhecimento…",
        "Chuyển đổi: %@ → %@": "Conversão: %@ → %@",
        "Không chuyển đổi được.": "Não foi possível converter.",
        "Xem trước cắt chunk…": "Pré-visualização do fatiamento…",
        "Cỡ cố định 800B, chồng 100B": "Tamanho fixo 800 B, sobreposição 100 B",
        "Theo câu (≤ 800B)": "Por frase (≤ 800 B)",
        "Theo heading Markdown": "Por título Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Documento vazio — sem fragmentos.",
        "%d chunk · trung bình %d B · %@": "%d {one=fragmento|other=fragmentos} · %d B em média · %@",
        "Xuất JSONL": "Exportar JSONL",
        "Chunk JSONL": "Fragmentos JSONL",
        "Mở triple/edge dạng bảng": "Abrir triplos/arestas como tabela",
        "Bảng triple": "Tabela de triplos",
        "Tài liệu này không có dòng triple nào.": "Este documento não tem nenhuma linha de triplo.",
        "Không đọc được triple nào — dòng %d: %@": "Não foi possível ler nenhum triplo — linha %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%d {one=triplo lido|other=triplos lidos} · %d {one=linha malformada ignorada|other=linhas malformadas ignoradas} (a primeira: linha %d)",
        "Trùng lặp mờ theo cột…": "Duplicados aproximados por coluna…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Duplicados aproximados — coluna «%@»: %d {one=grupo candidato|other=grupos candidatos}",
        "Gộp": "Fundir",
        "Giống": "Correspondência",
        "Các giá trị trong cụm": "Valores do grupo",
        "Gộp về": "Fundir em",
        "Gộp các cụm đã chọn": "Fundir os grupos selecionados",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Nenhum grupo selecionado — carregar em Fundir NÃO muda nada. A aplicação nunca funde sozinha.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=grupo selecionado|other=grupos selecionados} · %d {one=linha vai mudar|other=linhas vão mudar} · UM passo de anulação",
        "Không quét được cột này.": "Não foi possível analisar esta coluna.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "A coluna «%@» não tem grupos de duplicados aproximados.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Nenhum grupo foi fundido — o documento fica igual.",
        "Khử trùng lặp mờ · cột %@": "Desduplicação aproximada · coluna %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=grupo fundido|other=grupos fundidos} · %d {one=célula alterada|other=células alteradas}",
        "Báo cáo làm sạch": "Relatório de limpeza",
        "# Báo cáo làm sạch — %@\n\n": "# Relatório de limpeza — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Aplicado (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Nenhum passo aplicado._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Perfil dos dados\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%d {one=coluna|other=colunas} · %d {one=linha|other=linhas} · analisado em %.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Coluna | Tipo | Nulos | Distintos | Mín | Máx | Média |\n",
        "\n### Giá trị bất thường\n\n": "\n### Valores atípicos\n\n",
        "hàng %d: %@": "linha %d: %@",
        "- cột «%@» — %d ô: %@\n": "- coluna «%@» — %d {one=célula|other=células}: %@\n",
        "\n## Còn lại (%d)\n\n": "\n## Restante (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Não restam observações._\n",
        "- cột «%@»: %@\n": "- coluna «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Remover espaços ao guardar",
        "Chuẩn hóa xuống dòng": "Normalizar os fins de linha",
        "trước đó": "anterior",
        "Không mở lại được thư mục «%@» của phiên trước": "Não foi possível reabrir a pasta «%@» da sessão anterior",
        " (và %d file khác)": " (e mais %d {one=ficheiro|other=ficheiros})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "Não foi possível reabrir %d {one=separador|other=separadores}: %@%@ — os ficheiros já não estão no mesmo sítio.",
        "Không đọc được nội dung từ ống dẫn": "Não foi possível ler a entrada do canal",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Os espaços no fim da linha serão removidos em cada gravação",
        "Không cắt khoảng trắng khi lưu nữa": "Os espaços já não são removidos ao guardar",
        "Chưa đặt tên.txt": "Sem título.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Converter a codificação vai perder carateres",
        "Vẫn lưu": "Guardar mesmo assim",
        "Tài liệu có thay đổi chưa lưu": "O documento tem alterações por guardar",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Fechar sem guardar vai descartá-las.",
        "Bỏ thay đổi": "Descartar as alterações",
        "Đi tới dòng": "Ir para a linha",
        "Tài liệu có %d dòng.": "O documento tem %d {one=linha|other=linhas}.",
        "Số dòng": "Número da linha",
        "Đi tới": "Ir",
        "Diễn giải lại theo…": "Reinterpretar como…",
        "Chuyển đổi sang…": "Converter para…",
        "Không diễn giải lại được": "Não foi possível reinterpretar",
        "Bảng mã %@ không chứa hết ký tự": "%@ não consegue representar todos os carateres",
        "Vẫn chọn": "Escolher mesmo assim",
        "Cột %d": "Coluna %d",
        "Cột %d: %@": "Coluna %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Colunas ocultas: %@ (%d) — repõe-nas pelo menu de contexto da linha de cabeçalho",
        "Hiện lại: %@": "Mostrar de novo: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Coluna %@ ocultada — continua intacta no ficheiro",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Ordenado por %@ %@ · apenas visualização",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Ordenado: %@ %@ (apenas visualização)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ linhas correspondem — ainda a procurar…",
        "%d / %d dòng khớp": "%d / %d {one=linha corresponde|other=linhas correspondem}",
        "Không tìm thấy lỗi trong %d hàng": "Não foram encontrados problemas em %d {one=linha|other=linhas}",
        "%d hàng lệch số cột": "%d {one=linha|other=linhas} com número de colunas errado",
        "%d ô sai kiểu dữ liệu": "%d {one=célula|other=células} com o tipo de dados errado",
        " (đã dừng ở %d lỗi đầu)": " (parou nos primeiros %d {one=problema|other=problemas})",
        "   —   kiểu nhận ra: ": "   —   tipos detetados: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Linha %d, coluna %@: «%@» não é %@",
        "Column Editor — %d dòng": "Editor de colunas — %d {one=linha|other=linhas}",
        "Phát hiện": "Observações",
        "Hồ sơ dữ liệu": "Perfil dos dados",
        "Hồ sơ dữ liệu — đang quét…": "Perfil dos dados — a analisar…",
        "Lưu công thức…": "Guardar a receita…",
        "Xuất báo cáo": "Exportar o relatório",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Nenhum grupo aplicado · cada grupo é um passo de anulação",
        "quá nhiều giá trị": "demasiados valores",
        "hay gặp: ": "mais frequentes: ",
        "Giá trị điền vào ô thiếu": "Valor para preencher as células vazias",
        "Áp dụng": "Aplicar",
        "Không dựng được bản xem trước": "Não foi possível construir uma pré-visualização",
        "· giữ nguyên, không đọc được ·": "· mantido tal como está, ilegível ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Converter a coluna para ISO 8601 (AAAA-MM-DD)",
        "Quy ước số cho cả cột": "Convenção numérica para toda a coluna",
        "Làm gì với ô thiếu": "O que fazer com as células vazias",
        "Chuẩn hóa về ISO 8601": "Normalizar para ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Ler as células ambíguas com o DIA primeiro (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Ler as células ambíguas com o MÊS primeiro (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Ignorar as células ambíguas, corrigir só as certas",
        "Về Việt/Âu (1.234,56)": "Para vietnamita/europeu (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Para anglo-americano (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Para anglo-americano, sem separador de milhares (1234.56)",
        "Điền một giá trị mặc định…": "Preencher com um valor predefinido…",
        "Điền xuôi — lấy giá trị phía trên": "Preencher para baixo — usar o valor de cima",
        "Điền ngược — lấy giá trị phía dưới": "Preencher para cima — usar o valor de baixo",
        "Xóa hàng có ô thiếu ở cột này": "Eliminar as linhas com célula vazia nesta coluna",
        "Cắt khoảng trắng hai đầu": "Remover espaços nas duas pontas",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Remover nas duas pontas e reduzir os espaços interiores",
        "Pivot…": "Tabela dinâmica…",
        "Nguồn…": "Fontes…",
        "Pivot — gộp theo cột": "Tabela dinâmica — agrupar por coluna",
        "Hàng (gộp nhóm)": "Linhas (agrupamento)",
        "Giá trị": "Valores",
        "+ Hàng": "+ Linha",
        "+ Giá trị": "+ Valor",
        "Xoá hết": "Limpar tudo",
        "Đưa vào ô truy vấn": "Colocar na consulta",
        "Chọn cột để dựng câu truy vấn.": "Escolhe colunas para construir a consulta.",
        "Không đọc được tên cột của bảng này.": "Não foi possível ler os nomes das colunas desta tabela.",
        "Nguồn dữ liệu của truy vấn": "Fontes de dados da consulta",
        "«%@» — tài liệu đang mở": "«%@» — o documento aberto",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ o ficheiro mudou desde que foi registado",
        "Thêm file…": "Adicionar ficheiro…",
        "Bỏ hết": "Remover tudo",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Não foi possível deduzir um nome de tabela de «%@» — muda o nome do ficheiro.",
        "Tổng": "Soma",
        "Trung bình": "Média",
        "Nhỏ nhất": "Mín",
        "Lớn nhất": "Máx",
        "Đếm khác nhau": "Contagem distinta",
        "Biểu đồ": "Gráfico",
        "Xuất PNG": "Exportar PNG",
        "Xuất SVG": "Exportar SVG",
        "Bảng này không có cột số nào để vẽ.": "Esta tabela não tem nenhuma coluna numérica para representar.",
        "Không dựng được ảnh PNG.": "Não foi possível construir a imagem PNG.",
        "Kết quả truy vấn": "Resultado da consulta",
        "Đã lưu %@": "%@ guardado",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Gráfico %@ de «%@» — %d {one=ponto|other=pontos}, valores de %@ a %@",
        "Cột": "Barras",
        "Đường": "Linha",
        "Phân bố": "Histograma",
        "Phân tán": "Dispersão",
        "Hộp": "Caixa",
        "CSV: chất lượng dữ liệu…": "CSV: qualidade dos dados…",
        "Chất lượng dữ liệu": "Qualidade dos dados",
        "Xuất vi phạm ra tab mới": "Exportar as infrações para um separador novo",
        "Mức": "Nível",
        "Luật": "Regra",
        "Vi phạm": "Infrações",
        "Tỷ lệ": "Taxa",
        "đạt": "aprovado",
        "lỗi": "erro",
        "cảnh báo": "aviso",
        "hỏng": "danificado",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=linha em infração marcada|other=linhas em infração marcadas}",
        "Xu hướng": "Tendência",
        "Lúc chấm": "Avaliado em",
        "Số hàng": "Linhas",
        "Lệch": "Diferença",
        "Luật trượt": "Regras falhadas",
        "Điểm chất lượng": "Pontuação de qualidade",
        "Điểm theo thời gian": "Pontuação ao longo do tempo",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Ainda não há histórico — cada avaliação acrescenta ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "uma linha ao ficheiro «.history.jsonl» ao lado das regras.",
        "%d mốc trong lịch sử": "%d {one=ponto|other=pontos} no histórico",
        " · %d dòng KHÔNG đọc được": " · %d {one=linha ILEGÍVEL|other=linhas ILEGÍVEIS}",
        " · chọn hai dòng để so": " · seleciona duas linhas para comparar",
        "điểm %+.1f": "pontuação %+.1f",
        "không chiều nào tụt": "nenhuma dimensão desceu",
        "tụt: ": "desceram: ",
        "%d luật mới trượt: %@": "%d {one=regra que passou a falhar|other=regras que passaram a falhar}: %@",
        "số hàng %+d": "linhas %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (e mais %d {one=aviso|other=avisos} no separador Tendência)",
        "Không sửa tự động được: ": "Sem correção automática: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Abre a ferramenta correspondente na Bancada de limpeza e avalia logo de novo.",
        "Xử lý giá trị thiếu…": "Tratar os valores em falta…",
        "Chuẩn hóa ngày…": "Normalizar as datas…",
        "Khử trùng lặp…": "Remover duplicados…",
        "Thay thế…": "Substituir…",
        "Xem các dòng sai": "Mostrar as linhas erradas",
        "Không tìm thấy cột «%@» trong bảng này.": "A coluna «%@» não está nesta tabela.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplicados removidos — «%@» já é único. Pontuação: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplicados removidos, mas «%@» ainda tem %d {one=linha repetida|other=linhas repetidas} (antes: %d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "essas linhas partilham a CHAVE mas não a linha inteira, por isso é preciso olhar e escolher ",
        "giữ hàng nào.": "qual manter.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Não foi possível ler nenhum valor que infrinja esta regra.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%d {one=valor errado|other=valores errados} na coluna «%@» — preenche Substituir e carrega em Pré-visualizar",
        "Đã chấm lại: %.0f/100": "Avaliado de novo: %.0f/100",
        "Xem trước báo cáo": "Pré-visualização do relatório",
        "Tham số…": "Parâmetros…",
        "Xuất HTML…": "Exportar HTML…",
        "In / PDF…": "Imprimir / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=bloco executado|other=blocos executados} · %d {one=bloco FALHADO|other=blocos FALHADOS}",
        "%d khối chạy được": "%d {one=bloco executado|other=blocos executados}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · DADOS DESATUALIZADOS — o ficheiro de origem mudou; reconstrói",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "A pré-visualização do relatório precisa de um documento .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Nenhuma fonte de dados encontrada — declara «source: ficheiro.csv» no frontmatter.",
        "Không dựng được báo cáo.": "Não foi possível construir o relatório.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Este relatório não declara nenhum parâmetro no frontmatter.",
        "Tham số báo cáo": "Parâmetros do relatório",
        "Dựng lại": "Reconstruir",
        "Đã xuất %@": "%@ exportado",
        "Báo cáo: xem trước": "Relatório: pré-visualização",
        "Báo cáo: sinh loạt…": "Relatório: geração em lote…",
        "không phải tài liệu .greport.md": "não é um documento .greport.md",
        "không phân tích được báo cáo": "não foi possível analisar o relatório",
        "không tìm được dữ liệu nguồn": "não foi possível encontrar os dados de origem",
        "không đọc được danh sách tham số": "não foi possível ler a lista de parâmetros",
        "Sinh loạt cần tài liệu đuôi .%@": "A geração em lote precisa de um documento .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Escolher uma lista de parâmetros (CSV ou JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Escolher uma pasta para %d {one=relatório|other=relatórios}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "faltam parâmetros ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "aponta para o próprio ficheiro de origem — a substituição é recusada",
        "%d khối HỎNG": "%d {one=bloco FALHADO|other=blocos FALHADOS}",
        "Sinh loạt xong: %d tệp · %d hỏng": "Lote concluído: %d {one=ficheiro|other=ficheiros} · %d falhados",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=conjunto de parâmetros não pôde ser construído|other=conjuntos de parâmetros não puderam ser construídos} — vê o resumo",
        "Sơ đồ Mermaid: xem trước": "Diagrama Mermaid: pré-visualização",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagrama Mermaid: inserir modelo…",
        "Sơ đồ Mermaid: định dạng lại": "Diagrama Mermaid: reformatar",
        "Nền trong suốt": "Fundo transparente",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Este Mac não consegue converter o diagrama em PNG — é preciso macOS 13. A exportação SVG continua a funcionar.",
        "Lưu PNG %@…": "Guardar PNG %@…",
        "Lưu SVG…": "Guardar SVG…",
        "Chép ảnh vào clipboard": "Copiar a imagem para a área de transferência",
        "Màu thương hiệu…": "Cores da marca…",
        "Màu thương hiệu cho sơ đồ": "Cores da marca para os diagramas",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Cada campo é uma cor #rrggbb. Guardado em «themes/mermaid-brand.json» — pode copiar-se para outro Mac.",
        "Màu chính": "Cor principal",
        "Chữ trên nút": "Texto dos nós",
        "Viền": "Contorno",
        "Đường nối": "Ligações",
        "Nền khi xuất ảnh": "Fundo ao exportar",
        "Lưu và chèn %%{init}%% vào tài liệu": "Guardar e inserir %%{init}%% no documento",
        "Đã lưu màu thương hiệu": "Cores da marca guardadas",
        "Đã chép ảnh sơ đồ vào clipboard": "Imagem do diagrama copiada para a área de transferência",
        "Đã lưu %@ — %@": "%@ guardado — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Este diagrama já tem uma diretiva %%{init}%% — a tua fica intacta.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% inserido — o diagrama passa a levar as suas próprias cores",
        "Chèn màu thương hiệu vào sơ đồ": "Inserir as cores da marca no diagrama",
        "Định dạng sơ đồ Mermaid": "Reformatar o diagrama Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "O código do diagrama já está arrumado — nada a mudar",
        "Đã định dạng lại sơ đồ": "Diagrama reformatado",
        "Đã định dạng lại %d sơ đồ": "%d {one=diagrama reformatado|other=diagramas reformatados}",
        "Thư viện mẫu sơ đồ": "Biblioteca de modelos de diagramas",
        "Mẫu sơ đồ đầy đủ": "Modelos de diagrama completos",
        "Mẩu cú pháp": "Excertos de sintaxe",
        "Đang soạn: %@": "A editar: %@",
        "Đã chèn mẫu «%@»": "Modelo «%@» inserido",
        "Tài liệu đang ở chế độ chỉ đọc.": "Este documento é só de leitura.",
        "Sơ đồ Mermaid": "Diagrama Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Este documento não tem nenhum bloco mermaid.",
        "Thương hiệu": "Marca",
        "Xuất…": "Exportar…",
        "Chưa có sơ đồ nào": "Ainda não há diagramas",
        "%d sơ đồ · %@": "%d {one=diagrama|other=diagramas} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%d/%d {one=diagrama FALHADO|other=diagramas FALHADOS} — diagrama %d%@",
        ", dòng %d": ", linha %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Este documento não tem nenhum bloco ```mermaid e também não é um ficheiro .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Nenhum diagrama acabou de ser desenhado.",
        "Không tìm thấy «%@» trong mã sơ đồ": "Não foi encontrado «%@» no código do diagrama",
        "không dựng được hàng rào chặn mạng cho WKWebView": "não foi possível construir a barreira de rede para o WKWebView",
        "Luật kết hợp": "Regras de associação",
        "Mỗi dòng một giỏ": "Um cabaz por linha",
        "Hai cột: mã · item": "Duas colunas: id · artigo",
        "Dạng dữ liệu giao dịch": "Forma dos dados transacionais",
        "Cột giỏ hàng hoặc mã giao dịch": "Coluna de cabaz ou de id de transação",
        "Cột item": "Coluna de artigo",
        "Ký tự phân tách item": "Caráter separador de artigos",
        "Support tối thiểu, phần trăm": "Suporte mínimo, percentagem",
        "Confidence tối thiểu, phần trăm": "Confiança mínima, percentagem",
        "Tách bởi:": "Separado por:",
        "Support \u{2265}": "Suporte ≥",
        "% · Confidence \u{2265}": "% · Confiança ≥",
        "Bảng luật kết hợp": "Tabela de regras de associação",
        "Support": "Suporte",
        "Confidence": "Confiança",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Atenção",
        "%d giao dịch · %d item · %d luật": "%d {one=transação|other=transações} · %d {one=artigo|other=artigos} · %d {one=regra|other=regras}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — nenhuma regra atingiu os limiares; baixa o suporte ou a confiança",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — PAROU CEDO, a tabela está INCOMPLETA",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transação contém|other=transações contêm} os dois lados",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "A forma de duas colunas precisa de duas colunas DIFERENTES.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%d {one=linha marcada|other=linhas marcadas} em %d {one=transação que contém|other=transações que contêm} «%@»",
        "CSV: luật kết hợp…": "CSV: regras de associação…",
        "Khai phá theo nhóm": "Mineração por grupos",
        "Cột nhóm": "Coluna de grupo",
        "Cột giá trị": "Coluna de valores",
        "Cột thứ hai cho tương quan": "Segunda coluna para a correlação",
        "Cách xếp hạng": "Critério de ordenação",
        "Nhóm theo:": "Agrupar por:",
        "Giá trị:": "Valor:",
        "Xếp theo:": "Ordenar por:",
        "Bảng xếp hạng nhóm": "Tabela de classificação dos grupos",
        "Nhóm": "Grupo",
        "Hàng": "Linhas",
        "Hàng rào riêng": "Limiar próprio",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "Diferença r",
        "Ghi chú": "Nota",
        "không đo được": "não mensurável",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=grupo|other=grupos} · correlação global de referência %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GRUPO DESCARTADO|other=GRUPOS DESCARTADOS}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Esta tabela não tem nenhuma coluna de texto por onde agrupar.",
        "Bảng này không có cột số nào để khai phá.": "Esta tabela não tem nenhuma coluna numérica para explorar.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%d {one=linha do grupo|other=linhas do grupo} «%@» {one=marcada|other=marcadas}",
        "CSV: khai phá theo nhóm…": "CSV: mineração por grupos…",
        "\u{2194}": "↔",
        "Dự báo": "Previsão",
        "Cột giá trị theo thời gian": "Coluna de valores ao longo do tempo",
        "Mô hình dự báo": "Modelo de previsão",
        "Số kỳ dự báo": "Número de períodos a prever",
        "Kết luận so với baseline": "Veredito face às linhas de base",
        "Mô hình:": "Modelo:",
        "Số kỳ:": "Períodos:",
        "Chu kỳ:": "Estação:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Período sazonal; deixa vazio para deteção automática",
        "Bảng giá trị dự báo": "Tabela de valores previstos",
        "Kỳ": "Período",
        "Dải 80%": "Banda de 80 %",
        "Dải 95%": "Banda de 95 %",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "não calculável",
        "Bảng này không có cột số nào để dự báo.": "Esta tabela não tem nenhuma coluna numérica para prever.",
        "Không dựng được dự báo cho cột này.": "Não foi possível construir uma previsão para esta coluna.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "A coluna «%@» só tem %d {one=valor numérico|other=valores numéricos} — {one=é preciso|other=são precisos} pelo menos 4 para prever.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# A série é lida pela ordem das linhas do ficheiro — sem reordenar, sem deduzir coluna temporal.\n",
        "Sai số huấn luyện": "Erro de treino",
        "CSV: dự báo chuỗi thời gian…": "CSV: previsão de séries temporais…",
        "Holt-Winters cộng": "Holt-Winters aditivo",
        "Holt-Winters nhân": "Holt-Winters multiplicativo",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Colunas usadas no agrupamento",
        "Đường cong WCSS": "Curva WCSS",
        "Phân cụm": "Agrupamento",
        "Chuẩn hoá:": "Escalonamento:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Seleciona pelo menos uma coluna.",
        "Không đủ dữ liệu để dựng đường cong.": "Não há dados suficientes para construir a curva.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "O cotovelo sugere k = %d. O WCSS desce SEMPRE quando k cresce, por isso é um truque de leitura do gráfico e não um critério estatístico — olha para a curva e avalia se a quebra é nítida.",
        "WCSS theo k": "WCSS por k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "A k-distância sugere eps = %@ (minPts é por omissão 2 × número de colunas = %d). %@",
        "Khoảng cách tới hàng xóm thứ k": "Distância ao k-ésimo vizinho",
        "Cần ít nhất 2 cột số để phân cụm.": "São precisas pelo menos 2 colunas numéricas para o agrupamento.",
        "Cụm theo %@ và %@": "Grupos por %@ e %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — grupos encontrados em %d {one=dimensão|other=dimensões}; o gráfico só mostra as 2 primeiras",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# ruído (cluster_id = -1): %d {one=linha|other=linhas}\n",
        "CSV: phân cụm…": "CSV: agrupamento…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Centros dos grupos (unidades originais) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Matriz de correlação",
        "Phương pháp tương quan": "Método de correlação",
        "Tương quan không hàm ý nhân quả.": "Correlação não implica causalidade.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Par mais forte: %@ ↔ %@ = %@ (n = %d). Clica numa célula para ver o gráfico de dispersão.",
        "Không cặp nào đo được.": "Nenhum par é mensurável.",
        "%@ ↔ %@: %@ trên %d hàng": "%@ ↔ %@: %@ em %d {one=linha|other=linhas}",
        "Cần ít nhất 2 cột số để tính tương quan.": "São precisas pelo menos 2 colunas numéricas para a correlação.",
        "Không đọc được cột «%@».": "Não foi possível ler a coluna «%@».",
        "CSV: ma trận tương quan…": "CSV: matriz de correlação…",
        "Bất thường": "Anomalias",
        "Danh sách bất thường": "Lista de anomalias",
        "Cột:": "Coluna:",
        "Cột số cần xét": "Coluna numérica a examinar",
        "Cách:": "Método:",
        "Phương pháp phát hiện": "Método de deteção",
        "Phương pháp đã dùng": "Método utilizado",
        "Ngưỡng": "Limiar",
        "Đánh dấu": "Marcar",
        "Xuất tab mới": "Exportar para um separador novo",
        "Dòng": "Linha",
        "Điểm": "Pontuação",
        "Vì sao": "Porquê",
        "nhẹ": "leve",
        "vừa": "moderada",
        "nặng": "grave",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=linha|other=linhas} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Esta tabela não tem nenhuma coluna numérica onde procurar anomalias.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=linha anómala marcada|other=linhas anómalas marcadas}",
        "CSV: tìm bất thường…": "CSV: detetar anomalias…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%d {one=regra, APROVADA|other=regras, todas APROVADAS} · %d {one=linha|other=linhas} · %.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%d {one=erro|other=erros} · %d {one=aviso|other=avisos} em %d {one=regra|other=regras} · %d {one=linha|other=linhas} · %.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Guarda primeiro o documento — as regras de qualidade ficam ao lado do ficheiro de dados.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Ainda não há conjunto de regras. Cria o ficheiro %@ e volta a abrir.",
        "Lịch sử": "Histórico",
        "Câu đã lưu": "Consultas guardadas",
        "Lưu câu này…": "Guardar esta consulta…",
        "Lưu câu truy vấn": "Guardar a consulta",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Dá-lhe um nome para a encontrares depois. Um nome repetido substitui.",
        "Ví dụ: Doanh thu theo tỉnh": "Por exemplo: Receita por província",
        "Chưa nhập giá trị cho tham số: %@": "Não foi introduzido valor para o parâmetro: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "A extensão mudou desde que a aprovaste — o GEditor recusa-se a executá-la",
        "Chạy plugin chưa duyệt?": "Executar uma extensão não aprovada?",
        "Tôi tin file này — chạy": "Confio neste ficheiro — executar",
        "KHÔNG có chữ ký": "SEM assinatura",
        "Chữ ký: %@": "Assinatura: %@",
        "Đường dẫn: %@": "Caminho: %@",
        "Thay": "Substituir",
        "Thay tất cả": "Substituir tudo",
        "Chuỗi thuần": "Texto simples",
        "Extended (\\n \\t \\xNN)": "Estendido (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Expressão regular",
        "Phân biệt hoa thường": "Distinguir maiúsculas",
        "Cả từ": "Palavra inteira",
        "Không có kết quả": "Sem resultados",
        "Thử biểu thức chính quy…": "Testar uma expressão regular…",
        "Chế độ Log (tô theo mức)": "Modo registo (cor por nível)",
        "Lọc log theo mức…": "Filtrar o registo por nível…",
        "Chạy trên cả thư mục…": "Executar em toda a pasta…",
        "Lọc qua lệnh ngoài…": "Filtrar por um comando externo…",
        "Script…": "Scripts…",
        "Gói mở rộng…": "Pacotes de extensão…",
        "Cửa sổ mới": "Nova janela",
        "Tách tab ra cửa sổ mới": "Separar o separador numa janela nova",
        "Chưa mở thư mục nào": "Nenhuma pasta aberta",
        "Tìm file trong thư mục": "Procurar um ficheiro na pasta",
        "Lọc theo tên": "Filtrar por nome",
        "File mới…": "Novo ficheiro…",
        "Thư mục mới…": "Nova pasta…",
        "Đổi tên…": "Mudar o nome…",
        "Chuyển vào Thùng rác": "Mover para o Lixo",
        "Hiện trong Finder": "Mostrar no Finder",
        "Đang đọc cấu trúc tài liệu…": "A ler a estrutura do documento…",
        "file này không có hàm nào": "este ficheiro não tem funções",
        "Không có gì khớp": "Sem correspondências",
        "Văn bản thuần": "Texto simples",
        "🔒 Chỉ đọc": "🔒 Só de leitura",
        "Đang theo dõi": "A seguir",
        "ngắt tại cột": "moldar na coluna",
        "Cú pháp": "Sintaxe",
        "Bấm để chèn vào ô truy vấn": "Clica para inserir na consulta",
        "truy vấn không hợp lệ": "consulta inválida",
        "khóa `ten` ở gốc": "chave «nome» na raiz",
        "khóa có dấu cách": "chave com espaços",
        "phần tử đầu": "primeiro elemento",
        "mọi phần tử": "todos os elementos",
        "lát cắt": "fatia",
        "hợp nhiều chỉ số": "união de índices",
        "mọi khóa `gia` ở mọi tầng": "todas as chaves «preco» em todos os níveis",
        "mọi nút": "todos os nós",
        "lọc theo số": "filtrar por número",
        "lọc theo có mặt": "filtrar por presença",
        "Tới lỗi đầu tiên": "Ir para o primeiro erro",
        "Cột doanh_thu là số": "A coluna receita é numérica",
        "lọc…": "filtrar…",
        "Hủy": "Cancelar",
        "Thực hiện thay": "Efetuar a substituição",
        "xem trước": "pré-visualizar",
        "tương tác": "interativo",
        "Soạn thảo": "Edição",
        "Giao diện": "Interface",
        "Phím tắt": "Atalhos de teclado",
        "Cỡ chữ": "Tamanho do texto",
        "Bề rộng TAB": "Largura da tabulação",
        "Thụt lề bằng TAB": "Indentar com tabulações",
        "Tự động thụt lề khi xuống dòng": "Indentar automaticamente ao mudar de linha",
        "Tô mọi kết quả tìm kiếm": "Realçar todos os resultados da procura",
        "Chuẩn hóa về NFC khi lưu": "Normalizar para NFC ao guardar",
        "Ngôn ngữ": "Idioma",
        "Nền": "Aspeto",
        "Theo hệ thống": "Do sistema",
        "Sáng": "Claro",
        "Tối": "Escuro",
        "Theme": "Tema",
        "Dùng preset Notepad++": "Usar a predefinição do Notepad++",
        "Về phím mặc định": "Voltar às teclas predefinidas",
        "Mở file cấu hình": "Abrir o ficheiro de configuração",
        "Xuất theme hiện tại": "Exportar o tema atual",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "A mudança de idioma aplica-se totalmente no próximo arranque.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "As teclas predefinidas voltam no próximo arranque.",
        "Xem trước Markdown": "Pré-visualização Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "A pré-visualização usa o motor Markdown do sistema: ainda sem tabelas nem coloração de blocos de código.",
        "Thử biểu thức chính quy": "Testar uma expressão regular",
        "Biểu thức": "Expressão",
        "Văn bản thử": "Texto de teste",
        "Kết quả": "Resultado",
        "Kết quả khớp": "Correspondências",
        "Biểu thức này làm gì": "O que faz esta expressão",
        "Giải thích biểu thức": "Explicar a expressão",
        "Chế độ tìm kiếm": "Modo de procura",
        "Kết quả tìm kiếm": "Resultados da procura",
        "Không khớp chỗ nào": "Sem correspondências",
        " (đã cắt bớt)": " (truncado)",
        "Bản đồ tài liệu": "Mapa do documento",
        "Thanh tab": "Barra de separadores",
        "Hàng tiêu đề cột": "Linha de cabeçalho das colunas",
        "Không có cột nào": "Sem colunas",
        "Cây thư mục workspace": "Árvore da área de trabalho",
        "Danh sách hàm và lớp": "Lista de funções e classes",
        "Kết quả tìm trong thư mục": "Resultados da procura na pasta",
        "Bảng dữ liệu CSV": "Tabela de dados CSV",
        "Bàn làm sạch dữ liệu": "Bancada de limpeza de dados",
        "Truy vấn JSONPath": "Consulta JSONPath",
        "Danh sách lỗi dữ liệu": "Lista de erros de dados",
        "Bộ đánh giá golden set…": "Avaliador de golden set…",
        "So với điểm ngoài (JSONL)…": "Comparar com pontuações externas (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Escolher um ficheiro de pontuações externas (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Mudar o nome do nó selecionado",
        "Gộp các node đang chọn": "Fundir os nós selecionados",
        "Tách node đang chọn": "Dividir o nó selecionado",
        "Trích subgraph đang chọn ra tab mới": "Extrair o subgrafo selecionado para um separador novo",
        "Không có gì để đổi": "Nada a mudar",
        "%@ — áp %d thay đổi?": "%@ — aplicar %d {one=alteração|other=alterações}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%@: %d {one=alteração|other=alterações} · Cmd-Z anula o lote inteiro",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Põe o cursor sobre EXATAMENTE UM nó e tenta de novo",
        "Đổi tên «%@»": "Mudar o nome de «%@»",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Todas as arestas e etiquetas que referenciam este nó mudam com ele.",
        "Đổi tên node": "Mudar o nome do nó",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Seleciona PELO MENOS DOIS nós e tenta de novo",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Forma canónica «%@» — a mais frequente, a mais longa, acentuada",
        "Gộp node": "Fundir nós",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Seleciona as LINHAS DE ARESTA a mover e tenta de novo",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Todas as linhas selecionadas têm de tocar EXATAMENTE UM nó — seleciona mais linhas de aresta",
        "Tách «%@» — chuyển %d cạnh": "Dividir «%@» — mover %d {one=aresta|other=arestas}",
        "Cạnh tới: %@": "Arestas para: %@",
        "Tách node": "Dividir o nó",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Documento por guardar — o ficheiro extraído precisa de um sítio ao lado",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Seleciona a parte do grafo a extrair e tenta de novo",
        "Gom biến thể entity → bảng duyệt": "Agrupar variantes de entidade → tabela de revisão",
        "Áp bảng duyệt đã sửa": "Aplicar a tabela de revisão alterada",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Documento por guardar — a tabela de revisão tem de ficar ao lado do ficheiro do grafo",
        "Không tìm thấy biến thể nào để gom": "Não foi encontrada nenhuma variante para agrupar",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=grupo de variantes|other=grupos de variantes} — corrige a coluna «canonical» e executa «Aplicar a tabela de revisão»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Não há tabela de revisão «%@» — executa primeiro «Agrupar variantes de entidade»",
        "Bảng duyệt không đọc được: %@": "Tabela de revisão ilegível: %@",
        "Bảng duyệt không có dòng nào cần đổi": "A tabela de revisão não tem nenhuma linha para mudar",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Nenhum ponto do grafo corresponde à tabela de revisão",
        "Gom biến thể entity": "Agrupar variantes de entidade",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=alteração aplicada|other=alterações aplicadas} · tabela de alias e lista de marcadores escritas ao lado do ficheiro",
        "Áp %d thay đổi lên đồ thị?": "Aplicar %d {one=alteração|other=alterações} ao grafo?",
        "%d alias → dạng chuẩn.": "%d {one=alias|other=alias} → forma canónica.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "FUNDIR nós (não se anula voltando a escrever):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias não está no grafo e é ignorado|other=alias não estão no grafo e são ignorados}.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Análise de cobertura Fragmento ↔ Entidade",
        "Xuất gói ngữ cảnh (JSONL)": "Exportar o pacote de contexto (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Cobertura Fragmento ↔ Entidade ↔ Grafo",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %d {one=entidade|other=entidades} · %d {one=fragmento|other=fragmentos} · %.0f %% de entidades mencionadas · %.0f %% de fragmentos com entidade",
        "Entity không chunk nào nhắc tới": "Entidades que nenhum fragmento menciona",
        "Chunk mồ côi (không chứa entity nào)": "Fragmentos órfãos (sem qualquer entidade)",
        "Node đồ thị không có entity đối ứng": "Nós do grafo sem entidade correspondente",
        "không có": "nenhum",
        "Phương pháp": "Método",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Não foi possível construir a correspondência Fragmento ↔ Entidade",
        "Chấm sức khoẻ đồ thị": "Avaliar a saúde do grafo",
        "sức khoẻ đồ thị": "saúde do grafo",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Saúde %@/100 · %d {one=erro|other=erros} · %d {one=inversão|other=inversões} · %d órfãos",
        "Lai với đồ thị": "Híbrido com o grafo",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: o sinal do grafo é totalmente ignorado, o resultado é igual a BM25 puro",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α alto: o grafo só ajusta ligeiramente a ordenação do BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α perto do valor por omissão 0,7: manda o BM25, o grafo ajusta",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α baixo: manda o grafo, o BM25 só desempata",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: apenas o sinal do grafo; os fragmentos sem entidade ficam empatados",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Documento por guardar — o híbrido precisa de um ficheiro de grafo ao lado do corpus",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Ficheiro de grafo «%@» não encontrado — o híbrido precisa dele para o seu sinal",
        "lai %.1f ms · %@": "híbrido %.1f ms · %@",
        "Thuật toán…": "Algoritmos…",
        "PageRank (độ dày viền)": "PageRank (espessura do contorno)",
        "Cộng đồng (màu nền)": "Comunidades (cor de fundo)",
        "Thành phần liên thông": "Componentes ligados",
        "Xuất bảng node ra tab mới": "Exportar a tabela de nós para um separador novo",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%d {one=componente|other=componentes} · o maior com %d {one=nó|other=nós} · %d nós órfãos",
        "Tài liệu này không phải đồ thị DOT": "Este documento não é um grafo DOT",
        "Không dựng được bảng node/cạnh: %@": "Não foi possível construir a tabela de nós/arestas: %@",
        "%d hàng · %@": "%d {one=linha|other=linhas} · %@",
        "Gán nhãn": "Etiquetar",
        "Ghi chú (tuỳ chọn)": "Nota (opcional)",
        "Lưu record": "Guardar o registo",
        "Xuất CSV": "Exportar CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Documento por guardar — o avaliador tem de ficar ao lado do ficheiro de corpus",
        "Không nạp được bộ đánh giá: %@": "Não foi possível carregar o avaliador: %@",
        "Không lưu được: %@": "Não foi possível guardar: %@",
        "Bộ đánh giá chưa có record nào": "O avaliador ainda não tem nenhum registo",
        "Không ghi được: %@": "Não foi possível escrever: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Este documento não é um ficheiro .mmd, não é DOT e não tem nenhum bloco mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=nó|other=nós} · %d {one=aresta|other=arestas} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagrama Mermaid: adicionar um elemento…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagrama Mermaid: ligar os dois elementos selecionados",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagrama Mermaid: editar a etiqueta do elemento selecionado…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagrama Mermaid: eliminar o elemento selecionado",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagrama Mermaid: subir a mensagem",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagrama Mermaid: descer a mensagem",
        "Thêm phần tử": "Adicionar um elemento",
        "Thêm participant": "Adicionar um participante",
        "Thêm mục": "Adicionar uma entrada",
        "Thêm mục sơ đồ": "Adicionar uma entrada ao diagrama",
        "Sửa mục sơ đồ": "Editar uma entrada do diagrama",
        "Xoá mục sơ đồ": "Eliminar uma entrada do diagrama",
        "Xoá phần tử": "Eliminar o elemento",
        "Sửa nhãn": "Editar a etiqueta",
        "Đổi thứ tự message": "Reordenar as mensagens",
        "Tên mục": "Nome da entrada",
        "Mục mới": "Nova entrada",
        "Tên mục hiện trên sơ đồ.": "O nome da entrada aparece no diagrama.",
        "Bảng thuộc tính sơ đồ": "Tabela de propriedades do diagrama",
        "Tài liệu này không có khối mermaid nào": "Este documento não tem nenhum bloco mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identificador no código do diagrama — sem espaços. A etiqueta edita-se depois com duplo clique.",
        "Để trống thì hiện chính định danh.": "Se ficar vazio, é mostrado o próprio identificador.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Só muda a ETIQUETA visível; o identificador do elemento mantém-se.",
        "Không rõ «%@» là phần tử nào": "Não é claro qual é o elemento «%@»",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Seleciona EXATAMENTE DOIS elementos e tenta de novo",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Põe o cursor sobre EXATAMENTE UM elemento e tenta de novo",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Escolhe UM elemento para eliminar, ou dois elementos ligados por uma aresta",
        "Xoá «%@» và %d cạnh chạm nó?": "Eliminar «%@» e as %d {one=aresta que lhe toca|other=arestas que lhe tocam}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Os nós da outra ponta dessas arestas são mantidos — são redeclarados com a etiqueta se a instrução de aresta era a única declaração deles.",
        "Sơ đồ «%@» chỉ soạn text — %@": "O diagrama «%@» só se edita como texto — %@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: arrasta entre dois elementos para ligar, duplo clique para editar a etiqueta",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: arrasta entre dois participantes para adicionar uma mensagem; reordena pelo menu Ferramentas",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: edita na tabela de propriedades abaixo",
        "Soạn trực quan đã bật": "Edição visual ativada",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%@ · %d {one=entrada|other=entradas} — edita diretamente na tabela, cada célula é um passo de anulação",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Num gráfico circular, um número; num gantt, o que vem depois dos dois pontos.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagrama Mermaid: extrair o bloco para um ficheiro .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagrama Mermaid: reintegrar o ficheiro referenciado",
        "Tách khối sơ đồ": "Extrair o bloco do diagrama",
        "Nhúng khối sơ đồ": "Reintegrar o bloco do diagrama",
        "Tách khối sơ đồ ra tệp riêng": "Extrair o bloco do diagrama para um ficheiro separado",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "O ficheiro fica AO LADO do documento; o bloco mantém uma linha de referência para se editar num só sítio.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Documento por guardar — o ficheiro do diagrama precisa de um sítio ao lado",
        "Đã có tệp «%@» — chọn tên khác": "Já existe o ficheiro «%@» — escolhe outro nome",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Extraído para «%@» — o bloco mantém uma linha de referência",
        "Mở tệp": "Abrir o ficheiro",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» reintegrado; o ficheiro continua no disco",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Este bloco contém um diagrama verdadeiro, não uma referência",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Este bloco referencia «%@» — abre esse ficheiro para o editar",
        "Không đọc được tệp sơ đồ %@": "Não foi possível ler o ficheiro de diagrama %@",
        "Soạn trực quan": "Edição visual",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Arrasta de um nó para outro para adicionar uma aresta; duplo clique para editar a etiqueta. Cada ação é um passo de anulação.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Edição visual: arrasta entre dois nós para adicionar uma aresta, duplo clique para editar a etiqueta",
        "Soạn trực quan đã tắt": "Edição visual desativada",
        "Thêm node…": "Adicionar um nó…",
        "Thêm cạnh giữa hai node đang chọn…": "Adicionar uma aresta entre os dois nós selecionados…",
        "Sửa nhãn node đang chọn…": "Editar a etiqueta do nó selecionado…",
        "Xoá node/cạnh đang chọn": "Eliminar o nó/aresta selecionado",
        "Thêm node": "Adicionar um nó",
        "Thêm cạnh": "Adicionar uma aresta",
        "Sửa nhãn node": "Editar a etiqueta do nó",
        "Xoá node": "Eliminar o nó",
        "Xoá cạnh": "Eliminar a aresta",
        "Cmd-Z hoàn tác": "Cmd-Z anula",
        "Tài liệu đang ở chế độ chỉ đọc": "Este documento é só de leitura",
        "Nhãn của «%@»": "Etiqueta de «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Só muda a ETIQUETA visível; o identificador do nó mantém-se.",
        "Không rõ «%@» là node nào": "Não é claro qual é o nó «%@»",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identificador do nó no ficheiro DOT. A etiqueta edita-se depois com duplo clique no gráfico.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Seleciona EXATAMENTE DOIS nós e tenta de novo",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Escolhe UM nó para eliminar, ou dois nós ligados por uma aresta",
        "Xoá node «%@» và %d cạnh chạm nó?": "Eliminar o nó «%@» e as %d {one=aresta que lhe toca|other=arestas que lhe tocam}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Se ficarem arestas órfãs, o DOT recria os nós a partir delas — o nó eliminado volta a aparecer no desenho seguinte.",
        "Phòng thí nghiệm truy hồi BM25": "Laboratório de recuperação BM25",
        "Câu hỏi — Enter để tìm": "Pergunta — Enter para procurar",
        "Đánh giá…": "Avaliar…",
        "Đang dựng chỉ mục": "A construir o índice",
        "Không chunk nào khớp": "Nenhum fragmento corresponde",
        "kết quả trên": "melhores resultados",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: cada palavra conta SÓ uma vez, independentemente de quantas vezes apareça",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 baixo: repetir uma palavra quase não acrescenta pontuação",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 perto do valor por omissão 1,2: repetir acrescenta pontuação, mas cada vez menos",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 alto: um fragmento que repete uma palavra é fortemente premiado",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: o comprimento é ignorado, os fragmentos longos não são penalizados",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b baixo: os fragmentos longos são penalizados só um pouco",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b perto do valor por omissão 0,75: os fragmentos longos são moderadamente penalizados",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: penalização máxima por comprimento, os fragmentos curtos são favorecidos",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: laboratório de recuperação…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Documento por guardar — o índice BM25 fica ao lado do ficheiro de corpus e precisa de um caminho",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Este ficheiro não é JSONL — o Retrieval Lab trabalha sobre um corpus de fragmentos",
        "Không dựng được chỉ mục BM25 cho tệp này": "Não foi possível construir um índice BM25 para este ficheiro",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Documento por guardar — é preciso um caminho de corpus para gerar o relatório",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Escolher um conjunto de avaliação (CSV ou JSONL: pergunta + id de fragmento esperado)",
        "Đánh giá truy hồi": "Avaliação da recuperação",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Muda k1, b ou k acima e volta a rever para comparar duas configurações; acrescenta um bloco «compare» para correr dois conjuntos de parâmetros em paralelo sobre o mesmo conjunto de avaliação.",
        "Lỗi": "Erro",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, média %.0f)",
        "Chế độ JSONL": "Modo JSONL",
        "Bản ghi": "Registo",
        "Chi tiết": "Detalhe",
        "Bản ghi ở dòng": "Registo na linha",
        "không phải JSON hợp lệ": "não é JSON válido",
        "bản ghi": "registos",
        "dòng trắng": "linhas em branco",
        "không phải đối tượng": "não é um objeto",
        "bảng hiện": "tabela mostrada",
        "ĐÃ HUỶ giữa chừng": "CANCELADO a meio",
        "Không lọc": "Sem filtro",
        "bản ghi khớp bộ lọc": "registos que correspondem ao filtro",
        "Đưa con nháy tới một dòng để xem bản ghi": "Põe o cursor numa linha para ver o registo",
        "Không có bản ghi nào hỏng": "Não há registos danificados",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Ainda não inspecionado. Volta a executar «JSONL: inspecionar fragmentos» depois da verificação.",
        "trường văn bản": "campo de texto",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "ESQUEMA (adivinhado — muda-se escolhendo outro campo)",
        "văn bản": "texto",
        "định danh": "identificador",
        "metadata lồng": "metadados aninhados",
        "TRƯỜNG": "CAMPO",
        "phủ": "cobertura",
        "nhiều kiểu": "vários tipos",
        "ĐỘ DÀI — ký tự": "COMPRIMENTO — carateres",
        "ĐỘ DÀI — từ": "COMPRIMENTO — palavras",
        "ĐỘ DÀI — token ước lượng": "COMPRIMENTO — tokens estimados",
        "RỖNG VÀ TRÙNG": "VAZIOS E DUPLICADOS",
        "chunk rỗng": "fragmentos vazios",
        "dòng": "linhas",
        "nhóm trùng chính xác": "grupos de duplicados exatos",
        "dòng không đọc được, không vào thống kê": "linhas ilegíveis, fora das estatísticas",
        "PHƯƠNG PHÁP": "MÉTODO",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«carateres» conta carateres Unicode (escalares), não grupos visíveis",
        "«từ» tách theo khoảng trắng ASCII": "«palavras» separa por espaços ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«tokens» conta com um separador de sílabas — NÃO é o do modelo",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«duplicado» significa duplicado EXATO; os quase-duplicados estão no bloco ```quality",
        "chunk": "fragmentos",
        "JSONL: kiểm và soi chunk…": "JSONL: verificar e inspecionar fragmentos…",
        "Ảnh": "Imagem",
        "PDF": "PDF",
        "Tài liệu Word": "Documento Word",
        "Bảng tính Excel": "Folha de cálculo Excel",
        "Bản trình chiếu PowerPoint": "Apresentação PowerPoint",
        "File nén": "Arquivo comprimido",
        "Vừa khung": "Ajustar à janela",
        "Chép ảnh": "Copiar a imagem",
        "Xoay": "Rodar",
        "Không đọc được ảnh «%@»": "Não é possível ler a imagem «%@»",
        "Đã chép ảnh vào clipboard": "Imagem copiada para a área de transferência",
        "Bôi vàng": "Realçar a amarelo",
        "Gạch chân": "Sublinhar",
        "Ghi chú…": "Nota…",
        "Bỏ chú thích": "Remover as anotações",
        "Lấy chữ ra tab mới": "Extrair o texto para um separador novo",
        "Lưu bản có chú thích…": "Guardar a versão anotada…",
        "Tìm trong PDF": "Procurar no PDF",
        "Thêm": "Adicionar",
        "Trang %d/%d": "Página %d/%d",
        "Trang %d": "Página %d",
        "Kết quả %d/%d": "Resultado %d/%d",
        "0 kết quả": "0 resultados",
        "Không đọc được PDF «%@»": "Não é possível ler o PDF «%@»",
        "PDF này có mật khẩu — chưa mở được nội dung": "Este PDF tem palavra-passe — o conteúdo não está acessível",
        "Không thấy «%@» trong tài liệu": "«%@» não foi encontrado no documento",
        "Đã bôi vàng": "Realçado",
        "Đã gạch chân": "Sublinhado",
        "Hãy bôi đen một đoạn chữ trước": "Seleciona primeiro um trecho de texto",
        "Đã thêm ghi chú": "Nota adicionada",
        "Trang này chưa có chú thích nào": "Esta página não tem nenhuma anotação",
        "Đã bỏ %d chú thích trên trang này": "%d {one=anotação removida|other=anotações removidas} desta página",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Este PDF não tem camada de texto — provavelmente é uma digitalização",
        "Không ghi được tệp": "Não foi possível escrever o ficheiro",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "O ficheiro escrito NÃO volta a abrir corretamente — não uses esta versão",
        "Đã lưu %@ · %d trang": "%@ guardado · %d {one=página|other=páginas}",
        "Tên": "Nome",
        "Kích thước": "Tamanho",
        "Đã nén": "Comprimido",
        "Tỉ lệ": "Rácio",
        "Sửa lúc": "Modificado em",
        "Mở mục đang chọn": "Abrir o elemento selecionado",
        "Bung ra thư mục…": "Extrair para uma pasta…",
        "Bung vào đây": "Extrair aqui",
        "%d mục": "%d {one=elemento|other=elementos}",
        "giải nén ra %@": "extraído para %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— o interior de um ficheiro Office é um arquivo comprimido; estas são as suas partes",
        "Đã bung %d mục": "%d {one=elemento extraído|other=elementos extraídos}",
        "%d mục hỏng": "%d {one=elemento danificado|other=elementos danificados}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=elemento RECUSADO|other=elementos RECUSADOS} porque os caminhos saem da pasta de destino",
        "Không mở được mục này": "Não é possível abrir este elemento",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Ainda não é possível escrever diretamente num %@ — usa «Guardar como…»",
        "Không có gì đổi": "Nada mudou",
        "Đã ghi %d ô vào %@": "%d {one=célula escrita|other=células escritas} em %@",
        "Đã ghi %d đoạn vào %@": "%d {one=parágrafo escrito|other=parágrafos escritos} em %@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Não foi possível escrever no ficheiro — o original fica intacto",
        "dựng bài": "preparar o caso de teste",
        "Không ghi được settings.json": "Não foi possível gravar settings.json",
        "Xoay trái": "Girar à esquerda",
        "Xoay phải": "Girar à direita",
        "Trang lên": "Mover página acima",
        "Trang xuống": "Mover página abaixo",
        "Xoá trang…": "Excluir páginas…",
        "Xoá trang": "Excluir páginas",
        "Trích trang…": "Extrair páginas…",
        "Trích trang ra tệp mới": "Extrair páginas para um novo ficheiro",
        "Gộp tệp PDF…": "Juntar ficheiro PDF…",
        "Tách tệp…": "Dividir ficheiro…",
        "Tách tệp PDF": "Dividir ficheiro PDF",
        "Xuất ảnh…": "Exportar imagens…",
        "Xuất trang ra ảnh PNG": "Exportar páginas como imagens PNG",
        "Hoàn tác trang": "Desfazer edição de página",
        "Lưu bản đã sửa…": "Guardar cópia editada…",
        "Phát": "Reproduzir",
        "Tạm dừng": "Pausa",
        "Xem bình thường": "Vista normal",
        "Chọn sheet": "Escolher folha",
        "Mở sheet": "Abrir folha",
        "Bỏ và đổi sheet": "Descartar e mudar de folha",
        "Bảng tính có %d sheet.": "A pasta de trabalho tem %d folhas.",
        "Bảng tính này chỉ có một sheet: «%@»": "Esta pasta de trabalho só tem uma folha: «%@»",
        "Bỏ phần chưa lưu của sheet này?": "Descartar as alterações não guardadas desta folha?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Mudar de folha substitui todo o separador. O que não foi guardado com ⌘S perde-se.",
        "Chọn tệp PDF cần gộp vào": "Escolher o PDF a juntar",
        "Chọn thư mục ghi ảnh": "Escolher a pasta para as imagens",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Escolha onde guardar. O segundo ficheiro é escrito ao lado deste.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "O documento tem %d páginas. Indique as páginas a excluir, ex. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "O documento tem %d páginas. Indique as páginas a extrair, ex. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "O documento tem %d páginas. Indique as páginas a exportar, ex. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "O documento tem %d páginas. Indique a parte a separar, ex. 1-5; o resto torna-se um segundo ficheiro.",
        "Đã xoay trang %d": "Página %d girada",
        "Đã xoá trang %@ · còn %d trang": "Páginas %@ excluídas · restam %d páginas",
        "Đã gộp %d trang từ «%@»": "%d páginas juntadas de «%@»",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Dividido em %@ (%d páginas) e %@ (%d páginas)",
        "Đã ghi %@ — %@ · %d trang": "Escrito %@ — %@ · %d páginas",
        "Đã xuất %d ảnh vào %@": "%d imagens exportadas para %@",
        "Chỉ xuất được %d/%d ảnh": "Só %d de %d imagens foram exportadas",
        "Đã hoàn tác một thao tác trang": "Desfeita uma operação de página",
        "Không còn thao tác trang nào để hoàn tác": "Não há mais operações de página para desfazer",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Não é possível excluir TODAS as páginas — um PDF tem de manter pelo menos uma",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Esse intervalo é o documento inteiro — nada para separar",
        "«%@» có mật khẩu — chưa gộp được": "«%@» está protegido por palavra-passe — não é possível juntar",
        "«%@» không có trang nào": "«%@» não tem páginas",
        "Đã ở trang đầu": "Já na primeira página",
        "Đã ở trang cuối": "Já na última página",
        "· đã sửa, chưa lưu": "· editado, não guardado",
        "Ảnh động · %d khung": "Imagem animada · %d fotogramas",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Documento não guardado — não há ficheiro no disco para ver em binário",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Este comando só funciona com pastas de trabalho do Excel",
        "Không đọc được danh sách sheet": "Não foi possível ler a lista de folhas",
        "Không có sheet «%@»": "Não existe nenhuma folha «%@»",
        "Không đọc được sheet «%@»": "Não foi possível ler a folha «%@»",
        "Sheet «%@» · %d hàng": "Folha «%@» · %d linhas",
        "phần còn lại": "o restante",
        "Lưu ý": "Nota",
        "Cẩn thận": "Atenção",
        "Xem thêm": "Ver também",
        "Chép": "Copiar",
        "Đã chép": "Copiado",
        "Chép đoạn mã mẫu": "Copiar o código de exemplo",
        "Tìm trong trợ giúp": "Pesquisar na ajuda",
        "Lùi": "Voltar",
        "Bắt đầu dùng": "Começar",
        "Không mở cửa sổ này khi khởi động nữa": "Não mostrar esta janela ao iniciar",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "A ajuda ainda não está traduzida para este idioma — a mostrar em vietnamita.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Ir para o deslocamento (ex. 1F400 ou 0x1F400)",
        "Chép dòng đã chọn": "Copiar as linhas selecionadas",
        "Đã chép %d dòng": "%d linhas copiadas",
        "Không đọc được «%@»": "Não foi possível ler «%@»",
        "Tệp rỗng": "Ficheiro vazio",
        "Không đọc được offset «%@»": "Não foi possível ler o deslocamento «%@»",
        "Offset 0x%@ vượt quá cỡ tệp": "O deslocamento 0x%@ ultrapassa o tamanho do ficheiro",
        "Mở bằng ứng dụng khác…": "Abrir com outra app…",
        "%d kênh": "%d canais",
        "Không phát được «%@»": "Não é possível reproduzir «%@»",
        "Không phát được — %@": "Não é possível reproduzir — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "O macOS não tem descodificador para o formato %@ — é um limite do sistema, não um ficheiro danificado.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Ainda pode ver os bytes em modo binário, ou abrir com uma app que tenha o seu próprio descodificador.",
        "Ký…": "Assinar…",
        "Sửa chữ…": "Editar texto…",
        "Sửa chữ": "Editar texto",
        "Vẽ đè": "Desenhar por cima",
        "Ô chưa điền": "Próximo campo vazio",
        "Xoá nội dung đã điền": "Limpar o preenchido",
        "Tệp này không có ô biểu mẫu nào": "Este ficheiro não tem campos de formulário",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d campos de formulário limpos",
        "Mọi ô biểu mẫu đều đã có nội dung": "Todos os campos de formulário já estão preenchidos",
        "Còn %d ô chưa điền": "Ainda %d campos vazios",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Formulário preenchível: %d campos. Escreva diretamente e depois «Guardar cópia editada…»",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Escolher uma imagem de assinatura (fundo transparente fica melhor)",
        "Không dựng được trang có chữ ký": "Não foi possível criar a página assinada",
        "Đã chèn chữ ký vào trang %d": "Assinatura inserida na página %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Selecione primeiro o texto que quer alterar",
        "Vùng chọn quá nhỏ": "A seleção é demasiado pequena",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "O novo texto é DESENHADO POR CIMA da seleção com o tipo de letra do sistema. O texto antigo fica tapado, não removido — ainda pode ser extraído, logo isto não é uma censura.",
        "Không dựng được trang đã sửa": "Não foi possível criar a página editada",
        "Đã vẽ đè chữ mới lên trang %d": "O novo texto foi desenhado na página %d",
        "Đổi chế độ View / Code": "Alternar Vista / Código",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Ainda não há vista em árvore para JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Ainda não há vista de diagrama no separador",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Ainda não há vista de tópicos para o PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Este ficheiro só tem um modo de visualização",
        "%d nút": "%d nós",
        "Không dựng được cây: %@": "Não foi possível construir a árvore: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "O documento é demasiado grande para a árvore — use o modo Código",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Não foi possível construir as páginas deste ficheiro \u{2014} use o modo Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Os slides são construídos a partir do texto; imagens e layout originais ainda não são desenhados.",
        "Vừa ngang": "Ajustar à largura",
        "Thu nhỏ trang": "Reduzir página",
        "Phóng to trang": "Ampliar página",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu":
            "Não foi encontrado \u{201C}%@\u{201D} no documento",
        "Chỗ khớp %d/%d": "Correspondência %d de %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Nenhum texto selecionado na página.",
        "%d ký tự": "%d {one=caractere|other=caracteres}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Abrir ficheiros diretamente no modo View quando existir",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· CANCELADO no meio — tabela incompleta",
        "Chế độ hiển thị": "Modo de exibição",
        "Đổi giữa View và Code (⌥⌘V)": "Alternar entre View e Code (⌥⌘V)",
        "Trang tài liệu": "Páginas do documento",
        "Chữ đã dựng": "Texto composto",
        "Trang bảng tính": "Páginas da planilha",
        "Sơ đồ": "Diagrama",
        "Cây khoá–giá trị": "Árvore chave–valor",
        "Bộ phát": "Reprodutor",
        "Danh sách mục": "Lista de entradas",
        "Báo cáo đã dựng": "Relatório composto",
        "Tô theo mức": "Colorido por nível",
        "Trang slide": "Páginas de slides",
        "Dàn ý": "Estrutura de tópicos",
        "Lưu rồi dựng lại": "Salvar e recompor",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Mostrando a cópia NO DISCO — as alterações não salvas não estão aqui.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "O sistema não conseguiu montar o visualizador — use o modo Code.",
        "Lưu tệp trước khi xem trang.": "Salve o arquivo antes de ver as páginas.",
        "Đang ở chế độ Code": "No modo Code",
        "Đang ở chế độ View": "No modo View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Vendo o código-fonte — clique para ir ao modo View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "No modo View — clique para voltar ao código-fonte (⌥⌘V)",
        "Tín hiệu: %@": "Sinal: %@",
        "Lý do: %@": "Motivo: %@",
        "Chi tiết: %@": "Detalhe: %@",
        "Mở báo cáo": "Abrir relatório",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "O GEditor encerrou inesperadamente às %@ — abra o relatório para ler; nada é enviado.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligaduras — desligadas, cada caractere fica na própria célula",
        "Chế độ CSV": "Modo CSV",
        "Dấu phân tách": "Separador",
        "Tự nhận diện": "Detectar automaticamente",
        "Dấu phân tách: %@": "Separador: %@",
        "Theo đuôi tệp": "Pela extensão do arquivo",
        "%d dấu cách": "%d {one=espaço|other=espaços}",
        "Tài liệu đang sửa được": "Este documento pode ser editado",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Somente leitura porque o arquivo está sendo acompanhado — pare o acompanhamento para editar",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Somente leitura porque o arquivo no disco não permite gravação",
        "Đã mở khoá — tài liệu sửa được": "Desbloqueado — o documento voltou a ser editável",
        "Nhân bản tệp": "Duplicar arquivo",
        "Đổi tên tệp…": "Renomear arquivo…",
        "Chuyển tệp tới…": "Mover arquivo para…",
        "XML: đánh giá XPath…": "XML: avaliar XPath…",
        "Đánh giá XPath": "Avaliar XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Por exemplo: //pedido/item[2]/@codigo · //*[@tipo='A'] · count(//item)",
        "Đánh giá": "Avaliar",
        "XPath không đọc được: %@": "Não foi possível ler esse XPath: %@",
        "XPath «%@» không khớp node nào": "O XPath «%@» não encontrou nenhum nó",
        "XPath «%@» — %d node": "XPath «%@» — %d {one=nó|other=nós}",
        "XPath «%@»: %d node": "XPath «%@»: %d {one=nó|other=nós}",
        "Lưu tệp trước khi nhân bản.": "Salve o arquivo antes de duplicá-lo.",
        "Không nhân bản được": "Não foi possível duplicar",
        "Đã nhân bản thành %@": "Duplicado como %@",
        "Lưu tệp trước khi đổi tên.": "Salve o arquivo antes de renomeá-lo.",
        "Đổi tên tệp": "Renomear arquivo",
        "Tên hiện tại: %@": "Nome atual: %@",
        "Đổi tên": "Renomear",
        "Tên tệp không hợp lệ": "Esse nome de arquivo não é válido",
        "Đã có tệp tên %@ ở đó": "Já existe um arquivo chamado %@ ali",
        "Lưu tệp trước khi chuyển.": "Salve o arquivo antes de movê-lo.",
        "Chuyển tới": "Mover para cá",
        "Thư mục đích đã có tệp tên %@": "A pasta de destino já tem um arquivo chamado %@",
        "Không chuyển được tệp": "Não foi possível mover o arquivo",
        "Đã chuyển tới %@": "Movido para %@",
        "Bảng mã:": "Codificação:",
        "Xuống dòng:": "Fim de linha:",
        "Riêng cho %@": "Apenas para %@",
        "    %d — dùng TAB": "    %d — tabulações",
        "    %d — dùng dấu cách": "    %d — espaços",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Remover a regra própria e usar o ajuste global",
        "%@: thụt lề %d %@": "%@: recuo %d %@",
        "TAB": "tabulações",
        "dấu cách": "espaços",
        "Xuất": "Exportar",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Abrir os resultados em uma aba de texto — salve com ⌘S",
        "Lượt tìm trước đó": "Buscas anteriores",
        "«%@» — %d kết quả": "«%@» — %d {one=resultado|other=resultados}",
        "Kết quả tìm «%@»": "Resultados da busca por «%@»",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtrar nomes — ex.: *.csv;*.log (vazio: todo arquivo de texto)",
        "Thư mục %@ không có file văn bản nào": "A pasta %@ não tem arquivos de texto",
        "Không tệp nào trong %@ khớp «%@»": "Nenhum arquivo em %@ corresponde a «%@»",
        "%d byte · %d dòng": "%d bytes · %d {one=linha|other=linhas}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d bytes · %d {one=linha|other=linhas} — grande demais para contar caracteres e palavras",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d bytes · %d {one=caractere|other=caracteres} · %d {one=palavra|other=palavras} · %d {one=linha|other=linhas}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Este documento tem %d {one=linha|other=linhas}, %d bytes. Digite um número de linha, «linha,coluna» ou «@byte».",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "Não foi possível ler «%@» — digite um número de linha, «linha,coluna» ou «@byte»",
    ]
}
