import Foundation

/// Bảng dịch tiếng Đức. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let de: [String: String] = [
        "Bản đã lưu…": "Gespeicherte Versionen…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Dieses Dokument wurde nie gespeichert — kein Verlauf",
        "Chưa có bản đã lưu nào trước đó": "Keine früheren gespeicherten Versionen",
        "Không đọc được bản ấy": "Diese Version kann nicht gelesen werden",
        "Khôi phục bản đã lưu": "Gespeicherte Version wiederherstellen",
        "XML: kiểm theo DTD/XSD…": "XML: gegen DTD/XSD prüfen…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Auf diesem Mac fehlt libxml2, daher ist die XSD-Prüfung nicht verfügbar.",
        "Chọn lược đồ XSD để kiểm": "XSD-Schema zur Prüfung wählen",
        "Hợp lệ theo": "Gültig gemäß",
        "Plugin chạy xong, không đổi gì": "Das Plug-in wurde beendet, ohne etwas zu ändern",
        "Chưa cài plugin native nào": "Keine nativen Plug-ins installiert",
        "Gỡ plugin này": "Dieses Plug-in entfernen",
        "Gỡ plugin này?": "Dieses Plug-in entfernen?",
        "Gỡ": "Entfernen",
        "Cài plugin native…": "Natives Plug-in installieren…",
        "Mở thư mục plugin": "Plug-in-Ordner öffnen",
        "Chọn file .dylib của plugin native": "Die .dylib-Datei des Plug-ins wählen",
        "Đã cài:": "Installiert:",
        "Đã gỡ:": "Entfernt:",
        "Plugin native…": "Native Plug-ins…",
        "Chỉ nhận file .dylib.": "Es werden nur .dylib-Dateien akzeptiert.",
        "Đã có một plugin trùng tên:": "Ein Plug-in mit gleichem Namen ist bereits installiert:",
        "Không chép được plugin:": "Das Plug-in kann nicht kopiert werden:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Native Plug-ins gibt es nur im Direkt-Download, nicht in der App-Store-Version.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Der Hilfsprozess für Plug-ins wurde nicht gefunden.",
        "Không khởi động được tiến trình phụ:": "Der Hilfsprozess kann nicht gestartet werden:",
        "Tiến trình plugin đã dừng giữa chừng.": "Der Plug-in-Prozess wurde vorzeitig beendet.",
        "Plugin không trả lời kịp — đã dừng nó.": "Das Plug-in hat nicht rechtzeitig geantwortet — es wurde gestoppt.",
        "Plugin trả lời sai giao thức:": "Das Plug-in hat eine fehlerhafte Nachricht gesendet:",
        "Plugin báo lỗi:": "Das Plug-in meldet einen Fehler:",
        "Về GEditor": "Über GEditor",
        "Cài đặt…": "Einstellungen…",
        "Thoát GEditor": "GEditor beenden",
        "File": "Datei",
        "Tab mới": "Neuer Tab",
        "Đóng tab": "Tab schließen",
        "Tab kế": "Nächster Tab",
        "Tab trước": "Vorheriger Tab",
        "Tài liệu mới": "Neues Dokument",
        "Mở…": "Öffnen…",
        "Mở thư mục làm Workspace…": "Ordner als Arbeitsbereich öffnen…",
        "Mở gần đây": "Zuletzt benutzt",
        "Lưu": "Sichern",
        "Lưu thành…": "Sichern unter…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Leerzeichen am Zeilenende beim Sichern entfernen",
        "Theo dõi file (tail -f)": "Datei verfolgen (tail -f)",
        "In…": "Drucken…",
        "Mở lại tab vừa đóng": "Geschlossenen Tab wieder öffnen",
        "Chưa có file nào": "Keine Dateien",
        "Xoá danh sách": "Liste leeren",
        "Edit": "Bearbeiten",
        "Hoàn tác": "Widerrufen",
        "Làm lại": "Wiederholen",
        "Cắt": "Ausschneiden",
        "Sao chép": "Kopieren",
        "Dán": "Einsetzen",
        "Lịch sử clipboard…": "Zwischenablage-Verlauf…",
        "Column Editor…": "Spalteneditor…",
        "Chọn lần kế tiếp": "Nächstes Vorkommen auswählen",
        "Chọn tất cả": "Alles auswählen",
        "Nhân đôi dòng": "Zeile duplizieren",
        "Xóa dòng": "Zeile löschen",
        "Comment dòng": "Zeile auskommentieren",
        "Chưa chép gì trong phiên này": "In dieser Sitzung wurde nichts kopiert",
        "Xoá lịch sử": "Verlauf löschen",
        "Search": "Suchen",
        "Tìm…": "Suchen…",
        "Tìm và thay…": "Suchen und ersetzen…",
        "Tìm trong thư mục…": "In Ordner suchen…",
        "Thay trong thư mục…": "In Ordner ersetzen…",
        "Kết quả kế": "Nächstes Ergebnis",
        "Kết quả trước": "Vorheriges Ergebnis",
        "Đi tới dòng…": "Gehe zu Zeile…",
        "Nhảy tới ngoặc khớp": "Zur passenden Klammer springen",
        "Đánh dấu mọi dòng khớp…": "Alle passenden Zeilen markieren…",
        "Đảo dấu": "Markierungen umkehren",
        "Bỏ mọi dấu": "Alle Markierungen entfernen",
        "Chép dòng đã đánh dấu": "Markierte Zeilen kopieren",
        "Xóa dòng đã đánh dấu": "Markierte Zeilen löschen",
        "Chỉ giữ dòng đã đánh dấu": "Nur markierte Zeilen behalten",
        "Lines": "Zeilen",
        "Sắp xếp A→Z": "Sortieren A→Z",
        "Sắp xếp Z→A": "Sortieren Z→A",
        "Sắp xếp tự nhiên": "Natürliche Sortierung",
        "Khử trùng lặp": "Duplikate entfernen",
        "Đảo thứ tự dòng": "Zeilenreihenfolge umkehren",
        "Dời dòng lên": "Zeile nach oben",
        "Dời dòng xuống": "Zeile nach unten",
        "Ghép dòng": "Zeilen verbinden",
        "Tách dòng theo độ dài…": "Zeilen nach Länge teilen…",
        "Tách dòng theo ký tự…": "Zeilen nach Zeichen teilen…",
        "Xóa dòng rỗng": "Leere Zeilen entfernen",
        "Nén dòng trống liên tiếp": "Aufeinanderfolgende Leerzeilen zusammenfassen",
        "Cắt khoảng trắng cuối dòng": "Leerzeichen am Zeilenende entfernen",
        "Tab → Space": "Tab → Leerzeichen",
        "Space → Tab": "Leerzeichen → Tab",
        "HOA": "GROSSBUCHSTABEN",
        "thường": "kleinbuchstaben",
        "Chữ Hoa Đầu Từ": "Erster Buchstabe Jedes Wortes",
        "Chữ hoa đầu câu": "Erster Buchstabe des Satzes",
        "Đảo hoa/thường": "gROSS/kLEIN uMKEHREN",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: Blatt wählen…",
        "Xem dạng bảng / văn bản": "Tabellen-/Textansicht umschalten",
        "Xóa cột…": "Spalte löschen…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Daten prüfen (Spaltenzahl · Typen)",
        "Bàn làm sạch dữ liệu…": "Datenbereinigungs-Werkbank…",
        "Chạy công thức làm sạch…": "Bereinigungsrezept ausführen…",
        "Chuyển đổi…": "Umwandeln…",
        "Đổi dấu phân tách…": "Trennzeichen ändern…",
        "Xuất sang JSON…": "Als JSON exportieren…",
        "Format": "Format",
        "Bảng mã…": "Zeichenkodierung…",
        "Xuống dòng…": "Zeilenenden…",
        "Chuẩn hóa Unicode…": "Unicode normalisieren…",
        "JSON: định dạng lại": "JSON: formatieren",
        "JSON: thu gọn một dòng": "JSON: auf eine Zeile verdichten",
        "JSON: sắp xếp khóa": "JSON: Schlüssel sortieren",
        "JSON: truy vấn JSONPath…": "JSON: JSONPath-Abfrage…",
        "CSV: truy vấn SQL…": "CSV: SQL-Abfrage…",
        "Truy vấn SQL": "SQL-Abfrage",
        "Đang chạy…": "Läuft…",
        "Xuất ra tab mới": "In neuen Tab exportieren",
        "Tài liệu rỗng — không có bảng để truy vấn": "Leeres Dokument — keine Tabelle zum Abfragen",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Keine CSV-Tabelle — die erste Zeile hat nur eine Spalte",
        "Không đọc được câu truy vấn": "Die Abfrage kann nicht gelesen werden",
        "Không kiểm được câu truy vấn": "Die Abfrage kann nicht geprüft werden",
        "Vàng (mặc định)": "Gelb (Standard)",
        "Xanh dương": "Blau",
        "Xanh lá": "Grün",
        "Vàng đất": "Ocker",
        "Tím": "Violett",
        "Hồng": "Rosa",
        "Xanh ngọc": "Türkis",
        "Cam": "Orange",
        "Xám lam": "Schiefer",
        "Văn bản": "Text",
        "Dãy số": "Zahlenreihe",
        "Dãy ngày": "Datumsreihe",
        "Chữ HOA (hex)": "GROSSBUCHSTABEN (hexadezimal)",
        "Bắt đầu": "Beginn",
        "Bước": "Schrittweite",
        "Đệm 0 tới": "Mit Nullen auffüllen bis",
        "Hệ": "Basis",
        "Ngày đầu": "Erstes Datum",
        "Định dạng": "Format",
        "Chèn": "Einfügen",
        "Huỷ": "Abbrechen",
        "Chuyển đổi định dạng": "Format umwandeln",
        "Xem trước 5 hàng đầu": "Vorschau der ersten 5 Zeilen",
        "Tạo tab mới": "In neuem Tab öffnen",
        "Lưu ra file…": "In Datei sichern…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Das Ergebnis öffnet sich in einem neuen, ungesicherten Tab. Das Originaldokument bleibt unberührt.",
        "Chạy trên tài liệu này": "Auf dieses Dokument anwenden",
        "Chạy trên thư mục…": "Auf einen Ordner anwenden…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Das ganze Rezept ist EIN Widerrufsschritt. Die Datei auf der Festplatte bleibt unberührt, bis du sicherst.",
        "tắt": "aus",
        "không thấy cột": "Spalte nicht gefunden",
        "sẵn sàng": "bereit",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "es belegt weiterhin einen CPU-Kern, bis die App beendet wird.",
        "Script không trả về gì": "Das Skript hat nichts zurückgegeben",
        "Không dựng được máy JavaScript": "Die JavaScript-Engine konnte nicht erstellt werden",
        "Lỗi JavaScript không rõ": "Unbekannter JavaScript-Fehler",
        "Bảng": "Tabelle",
        "Áp sắp xếp vào file": "Sortierung auf die Datei anwenden",
        "Chuyển đổi ▾": "Umwandeln ▾",
        "Xuất dòng khớp": "Passende Zeilen exportieren",
        "Ẩn cột này": "Diese Spalte ausblenden",
        "Đổi tên tiêu đề…": "Überschrift umbenennen…",
        "Chèn cột trống bên trái": "Leere Spalte links einfügen",
        "Chèn cột trống bên phải": "Leere Spalte rechts einfügen",
        "Xóa cột này khỏi file…": "Diese Spalte aus der Datei löschen…",
        "Phải còn ít nhất một cột đang hiện": "Mindestens eine Spalte muss sichtbar bleiben",
        "Đang sắp xếp…": "Sortiere…",
        "Trở về thứ tự trong file": "Zurück zur Dateireihenfolge",
        "trăm hàng đầu": "erste hundert Zeilen",
        "chọn cột": "Spalten auswählen",
        "đặt tên cột kết quả": "Ergebnisspalte benennen",
        "lọc theo chữ": "nach Text filtern",
        "ô rỗng": "leere Zellen",
        "ghép điều kiện": "Bedingungen verknüpfen",
        "đếm hàng": "Zeilen zählen",
        "gộp nhóm": "gruppieren und aggregieren",
        "nhỏ nhất, lớn nhất": "Minimum, Maximum",
        "sắp xếp và cắt": "sortieren und begrenzen",
        "tên cột có dấu cách": "Spaltenname mit Leerzeichen",
        "Truy vấn bị dừng giữa chừng": "Die Abfrage wurde unterbrochen",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Nicht unterstützt: JOIN · Unterabfrage · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · Fensterfunktionen",
        "XML: định dạng lại": "XML: formatieren",
        "XML: thu gọn một dòng": "XML: auf eine Zeile verdichten",
        "XML: kiểm cú pháp": "XML: Syntax prüfen",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: doppelte Schlüssel und Einrückung prüfen",
        "View": "Darstellung",
        "Ẩn/hiện sidebar (Function List)": "Seitenleiste ein-/ausblenden (Funktionsliste)",
        "Ẩn/hiện bản đồ tài liệu": "Dokumentkarte ein-/ausblenden",
        "Gấp / mở khối tại con nháy": "Block an der Einfügemarke falten / entfalten",
        "Gấp tất cả": "Alles falten",
        "Bỏ gấp tất cả": "Alles entfalten",
        "Gấp theo cấp": "Nach Ebene falten",
        "Cấp %d": "Ebene %d",
        "Đã gấp %d khối ở cấp %d": "%d {one=Block|other=Blöcke} auf Ebene %d gefaltet",
        "Tài liệu này chỉ sâu %d cấp": "Dieses Dokument ist nur %d {one=Ebene|other=Ebenen} tief",
        "mermaid: không đọc được bản kê": "mermaid: Manifest nicht lesbar",
        "Kiểm tra bản cập nhật…": "Nach Updates suchen…",
        "Kiểm tra bản cập nhật": "Nach Updates suchen",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App-Store-Versionen aktualisieren sich über den Mac App Store, nicht über GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Dieser Build hat keinen Update-Signaturschlüssel und kann daher nicht nach Updates suchen.",
        "Phóng to chữ": "Text vergrößern",
        "Thu nhỏ chữ": "Text verkleinern",
        "Cỡ chữ gốc": "Originalgröße",
        "Chia đôi theo chiều dọc": "Vertikal teilen",
        "Chia đôi theo chiều ngang": "Horizontal teilen",
        "Bỏ chia đôi": "Teilung schließen",
        "Mở tab này ở nửa kia": "Diesen Tab im anderen Bereich öffnen",
        "Nhảy sang nửa kia": "Zum anderen Bereich wechseln",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Zeilenumbruch (aus / Fenster / Spalte)",
        "Ngắt dòng tại cột…": "Umbruch bei Spalte…",
        "Đánh dấu dòng này": "Diese Zeile markieren",
        "Dấu kế tiếp": "Nächste Markierung",
        "Dấu trước đó": "Vorherige Markierung",
        "Màu đánh dấu…": "Markierungsfarbe…",
        "Hiện tất cả ký tự ẩn": "Alle unsichtbaren Zeichen anzeigen",
        "  Khoảng trắng": "  Leerzeichen",
        "  Tab": "  Tabulatoren",
        "  Xuống dòng": "  Zeilenenden",
        "  NBSP · zero-width · điều khiển": "  NBSP · Nullbreite · Steuerzeichen",
        "Xem nhị phân": "Binäransicht",
        "Chế độ CSV (tô màu theo cột)": "CSV-Modus (Spalten in Farbe)",
        "Macro": "Makro",
        "Bắt đầu / dừng ghi": "Aufnahme starten / stoppen",
        "Phát lại": "Abspielen",
        "Phát nhiều lần…": "Mehrfach abspielen…",
        "Phát đến cuối tài liệu": "Bis zum Dokumentende abspielen",
        "Chạy trên mọi tab": "Auf alle Tabs anwenden",
        "Hủy macro đang chạy": "Laufendes Makro abbrechen",
        "Lưu macro…": "Makro sichern…",
        "Macro đã lưu…": "Gesicherte Makros…",
        "Help": "Hilfe",
        "Trợ giúp GEditor": "GEditor-Hilfe",
        "Giới thiệu tính năng": "Funktionsüberblick",
        "Di cư từ Notepad++": "Umstieg von Notepad++",
        "Tìm": "Suchen",
        "Thay bằng": "Ersetzen durch",
        "Kế": "Weiter",
        "Trước": "Zurück",
        "Đếm": "Zählen",
        "Đóng": "Schließen",
        "Kiểm theo JSON Schema…": "Gegen ein JSON-Schema prüfen…",
        "Chọn tệp JSON Schema": "JSON-Schema-Datei wählen",
        "Không thấy lỗi nào theo schema này.": "Keine Probleme gemäß diesem Schema gefunden.",
        "JSON Schema": "JSON-Schema",
        "Kiểm cú pháp đồ thị": "Graph-Syntax prüfen",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Graphformat nicht erkannt — es wird eine Endung .dot, .gv, .cypher, .ttl oder .graphml benötigt.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Keine %@-Syntaxfehler gefunden (die Prüfung ist nicht vollständig).",
        "Cú pháp %@": "%@-Syntax",
        "không phải một đối tượng JSON": "ist kein JSON-Objekt",
        "Khai phá văn bản (n-gram, TF-IDF)": "Text-Mining (n-Gramme, TF-IDF)",
        "Tài liệu rỗng.": "Das Dokument ist leer.",
        "Không rút được từ khoá nào.": "Es konnten keine Schlüsselwörter extrahiert werden.",
        "Từ khoá": "Schlüsselwörter",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=Schlüsselwort|other=Schlüsselwörter} · %d Token · %d {one=Dokument|other=Dokumente}",
        "Tô lên tài liệu": "Im Dokument markieren",
        "Đánh dấu entity từ danh sách…": "Entitäten aus einer Liste markieren…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Entitätenliste wählen (CSV oder JSON)",
        "Không đọc được danh sách entity.": "Die Entitätenliste kann nicht gelesen werden.",
        "Danh sách entity rỗng.": "Die Entitätenliste ist leer.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Keine Entitäten im Dokument gefunden (%d geladen).",
        "%d lần xuất hiện · %@": "%d {one=Vorkommen|other=Vorkommen} · %@",
        "Chuyển đổi tri thức…": "Wissen umwandeln…",
        "Chuyển đổi: %@ → %@": "Umwandlung: %@ → %@",
        "Không chuyển đổi được.": "Umwandlung nicht möglich.",
        "Xem trước cắt chunk…": "Chunking-Vorschau…",
        "Cỡ cố định 800B, chồng 100B": "Feste Größe 800 B, 100 B Überlappung",
        "Theo câu (≤ 800B)": "Nach Satz (≤ 800 B)",
        "Theo heading Markdown": "Nach Markdown-Überschrift",
        "Tài liệu rỗng — không có chunk nào.": "Leeres Dokument — keine Chunks.",
        "%d chunk · trung bình %d B · %@": "%d {one=Chunk|other=Chunks} · %d B im Mittel · %@",
        "Xuất JSONL": "JSONL exportieren",
        "Chunk JSONL": "Chunk-JSONL",
        "Mở triple/edge dạng bảng": "Tripel/Kanten als Tabelle öffnen",
        "Bảng triple": "Tripeltabelle",
        "Tài liệu này không có dòng triple nào.": "Dieses Dokument enthält keine Tripelzeile.",
        "Không đọc được triple nào — dòng %d: %@": "Es konnte kein Tripel gelesen werden — Zeile %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%d {one=Tripel|other=Tripel} gelesen · %d {one=fehlerhafte Zeile|other=fehlerhafte Zeilen} übersprungen (erste: Zeile %d)",
        "Trùng lặp mờ theo cột…": "Unscharfe Duplikate nach Spalte…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Unscharfe Duplikate — Spalte «%@»: %d {one=Kandidatengruppe|other=Kandidatengruppen}",
        "Gộp": "Zusammenführen",
        "Giống": "Übereinstimmung",
        "Các giá trị trong cụm": "Werte in der Gruppe",
        "Gộp về": "Zusammenführen zu",
        "Gộp các cụm đã chọn": "Ausgewählte Gruppen zusammenführen",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Keine Gruppe ausgewählt — Zusammenführen ändert NICHTS. Die App führt niemals von selbst zusammen.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=Gruppe|other=Gruppen} ausgewählt · %d {one=Zeile wird|other=Zeilen werden} geändert · EIN Widerrufsschritt",
        "Không quét được cột này.": "Diese Spalte konnte nicht durchsucht werden.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Die Spalte «%@» hat keine unscharfen Duplikatgruppen.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Keine Gruppe zusammengeführt — das Dokument bleibt unverändert.",
        "Khử trùng lặp mờ · cột %@": "Unscharfe Deduplizierung · Spalte %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=Gruppe|other=Gruppen} zusammengeführt · %d {one=Zelle|other=Zellen} geändert",
        "Báo cáo làm sạch": "Bereinigungsbericht",
        "# Báo cáo làm sạch — %@\n\n": "# Bereinigungsbericht — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Angewendet (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Es wurde kein Schritt angewendet._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Datenprofil\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%d {one=Spalte|other=Spalten} · %d {one=Zeile|other=Zeilen} · in %.1f s durchsucht_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Spalte | Typ | Null | Distinkt | Min | Max | Mittelwert |\n",
        "\n### Giá trị bất thường\n\n": "\n### Ausreißer\n\n",
        "hàng %d: %@": "Zeile %d: %@",
        "- cột «%@» — %d ô: %@\n": "- Spalte «%@» — %d {one=Zelle|other=Zellen}: %@\n",
        "\n## Còn lại (%d)\n\n": "\n## Verbleibend (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Keine Befunde mehr._\n",
        "- cột «%@»: %@\n": "- Spalte «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Leerzeichen beim Sichern entfernen",
        "Chuẩn hóa xuống dòng": "Zeilenenden normalisieren",
        "trước đó": "vorher",
        "Không mở lại được thư mục «%@» của phiên trước": "Der Ordner «%@» der vorherigen Sitzung konnte nicht wieder geöffnet werden",
        " (và %d file khác)": " (und %d {one=weitere Datei|other=weitere Dateien})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%d {one=Tab konnte|other=Tabs konnten} nicht wieder geöffnet werden: %@%@ — die Dateien liegen nicht mehr am selben Ort.",
        "Không đọc được nội dung từ ống dẫn": "Die Eingabe aus der Pipe konnte nicht gelesen werden",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Leerzeichen am Zeilenende werden bei jedem Sichern entfernt",
        "Không cắt khoảng trắng khi lưu nữa": "Leerzeichen werden beim Sichern nicht mehr entfernt",
        "Chưa đặt tên.txt": "Ohne Titel.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Beim Umwandeln der Kodierung gehen Zeichen verloren",
        "Vẫn lưu": "Trotzdem sichern",
        "Tài liệu có thay đổi chưa lưu": "Das Dokument hat ungesicherte Änderungen",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Beim Schließen ohne Sichern gehen sie verloren.",
        "Bỏ thay đổi": "Änderungen verwerfen",
        "Đi tới dòng": "Gehe zu Zeile",
        "Tài liệu có %d dòng.": "Das Dokument hat %d {one=Zeile|other=Zeilen}.",
        "Số dòng": "Zeilennummer",
        "Đi tới": "Los",
        "Diễn giải lại theo…": "Neu interpretieren als…",
        "Chuyển đổi sang…": "Umwandeln in…",
        "Không diễn giải lại được": "Neuinterpretation nicht möglich",
        "Bảng mã %@ không chứa hết ký tự": "%@ kann nicht alle Zeichen darstellen",
        "Vẫn chọn": "Trotzdem wählen",
        "Cột %d": "Spalte %d",
        "Cột %d: %@": "Spalte %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Ausgeblendete Spalten: %@ (%d) — über das Kontextmenü der Kopfzeile wiederherstellen",
        "Hiện lại: %@": "Wieder anzeigen: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Spalte %@ ausgeblendet — sie bleibt in der Datei unverändert",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Sortiert nach %@ %@ · nur Anzeige",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Sortiert: %@ %@ (nur Anzeige)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ Zeilen passen — Suche läuft…",
        "%d / %d dòng khớp": "%d / %d {one=Zeile passt|other=Zeilen passen}",
        "Không tìm thấy lỗi trong %d hàng": "Keine Probleme in %d {one=Zeile|other=Zeilen} gefunden",
        "%d hàng lệch số cột": "%d {one=Zeile|other=Zeilen} mit falscher Spaltenzahl",
        "%d ô sai kiểu dữ liệu": "%d {one=Zelle|other=Zellen} mit falschem Datentyp",
        " (đã dừng ở %d lỗi đầu)": " (bei den ersten %d {one=Problem|other=Problemen} gestoppt)",
        "   —   kiểu nhận ra: ": "   —   erkannte Typen: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Zeile %d, Spalte %@: «%@» ist kein %@",
        "Column Editor — %d dòng": "Spalteneditor — %d {one=Zeile|other=Zeilen}",
        "Phát hiện": "Befunde",
        "Hồ sơ dữ liệu": "Datenprofil",
        "Hồ sơ dữ liệu — đang quét…": "Datenprofil — wird durchsucht…",
        "Lưu công thức…": "Rezept sichern…",
        "Xuất báo cáo": "Bericht exportieren",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Keine Gruppe angewendet · jede Gruppe ist ein Widerrufsschritt",
        "quá nhiều giá trị": "zu viele Werte",
        "hay gặp: ": "am häufigsten: ",
        "Giá trị điền vào ô thiếu": "Wert zum Füllen leerer Zellen",
        "Áp dụng": "Anwenden",
        "Không dựng được bản xem trước": "Es konnte keine Vorschau erstellt werden",
        "· giữ nguyên, không đọc được ·": "· unverändert übernommen, nicht lesbar ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Spalte in ISO 8601 umwandeln (JJJJ-MM-TT)",
        "Quy ước số cho cả cột": "Zahlenkonvention für die ganze Spalte",
        "Làm gì với ô thiếu": "Was mit leeren Zellen geschehen soll",
        "Chuẩn hóa về ISO 8601": "Auf ISO 8601 normalisieren",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Mehrdeutige Zellen als TAG zuerst lesen (31.12.)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Mehrdeutige Zellen als MONAT zuerst lesen (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Mehrdeutige Zellen überspringen, nur die eindeutigen korrigieren",
        "Về Việt/Âu (1.234,56)": "Nach vietnamesisch/europäisch (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Nach angloamerikanisch (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Nach angloamerikanisch, ohne Tausendertrennzeichen (1234.56)",
        "Điền một giá trị mặc định…": "Mit einem Standardwert füllen…",
        "Điền xuôi — lấy giá trị phía trên": "Nach unten füllen — Wert von oben übernehmen",
        "Điền ngược — lấy giá trị phía dưới": "Nach oben füllen — Wert von unten übernehmen",
        "Xóa hàng có ô thiếu ở cột này": "Zeilen mit leerer Zelle in dieser Spalte löschen",
        "Cắt khoảng trắng hai đầu": "Leerzeichen an beiden Enden entfernen",
        "Cắt hai đầu và nén khoảng trắng bên trong": "An beiden Enden entfernen und innere Leerzeichen zusammenfassen",
        "Pivot…": "Pivot…",
        "Nguồn…": "Quellen…",
        "Pivot — gộp theo cột": "Pivot — nach Spalte gruppieren",
        "Hàng (gộp nhóm)": "Zeilen (Gruppierung)",
        "Giá trị": "Werte",
        "+ Hàng": "+ Zeile",
        "+ Giá trị": "+ Wert",
        "Xoá hết": "Alles löschen",
        "Đưa vào ô truy vấn": "In das Abfragefeld übernehmen",
        "Chọn cột để dựng câu truy vấn.": "Wähle Spalten, um die Abfrage aufzubauen.",
        "Không đọc được tên cột của bảng này.": "Die Spaltennamen dieser Tabelle konnten nicht gelesen werden.",
        "Nguồn dữ liệu của truy vấn": "Datenquellen der Abfrage",
        "«%@» — tài liệu đang mở": "«%@» — das geöffnete Dokument",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ die Datei hat sich seit der Registrierung geändert",
        "Thêm file…": "Datei hinzufügen…",
        "Bỏ hết": "Alle entfernen",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Aus «%@» ließ sich kein Tabellenname ableiten — benenne die Datei um.",
        "Tổng": "Summe",
        "Trung bình": "Mittelwert",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Max",
        "Đếm khác nhau": "Distinkte Anzahl",
        "Biểu đồ": "Diagramm",
        "Xuất PNG": "PNG exportieren",
        "Xuất SVG": "SVG exportieren",
        "Bảng này không có cột số nào để vẽ.": "Diese Tabelle hat keine numerische Spalte zum Darstellen.",
        "Không dựng được ảnh PNG.": "Das PNG-Bild konnte nicht erstellt werden.",
        "Kết quả truy vấn": "Abfrageergebnis",
        "Đã lưu %@": "%@ gesichert",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "%@-Diagramm von «%@» — %d {one=Punkt|other=Punkte}, Werte von %@ bis %@",
        "Cột": "Balken",
        "Đường": "Linie",
        "Phân bố": "Histogramm",
        "Phân tán": "Streuung",
        "Hộp": "Box",
        "CSV: chất lượng dữ liệu…": "CSV: Datenqualität…",
        "Chất lượng dữ liệu": "Datenqualität",
        "Xuất vi phạm ra tab mới": "Verstöße in neuen Tab exportieren",
        "Mức": "Stufe",
        "Luật": "Regel",
        "Vi phạm": "Verstöße",
        "Tỷ lệ": "Rate",
        "đạt": "bestanden",
        "lỗi": "Fehler",
        "cảnh báo": "Warnung",
        "hỏng": "defekt",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=verstoßende Zeile|other=verstoßende Zeilen} markiert",
        "Xu hướng": "Verlaufstrend",
        "Lúc chấm": "Bewertet am",
        "Số hàng": "Zeilen",
        "Lệch": "Differenz",
        "Luật trượt": "Fehlgeschlagene Regeln",
        "Điểm chất lượng": "Qualitätswert",
        "Điểm theo thời gian": "Wert im Zeitverlauf",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Noch kein Verlauf — jede Bewertung hängt ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "eine Zeile an die Datei «.history.jsonl» neben den Regeln an.",
        "%d mốc trong lịch sử": "%d {one=Punkt|other=Punkte} im Verlauf",
        " · %d dòng KHÔNG đọc được": " · %d NICHT lesbare {one=Zeile|other=Zeilen}",
        " · chọn hai dòng để so": " · zwei Zeilen zum Vergleichen auswählen",
        "điểm %+.1f": "Wert %+.1f",
        "không chiều nào tụt": "keine Dimension gefallen",
        "tụt: ": "gefallen: ",
        "%d luật mới trượt: %@": "%d neu fehlschlagende {one=Regel|other=Regeln}: %@",
        "số hàng %+d": "Zeilen %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (und %d {one=weitere Warnung|other=weitere Warnungen} im Tab Verlaufstrend)",
        "Không sửa tự động được: ": "Keine automatische Korrektur: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Öffnet das passende Werkzeug in der Bereinigungs-Werkbank und bewertet danach sofort neu.",
        "Xử lý giá trị thiếu…": "Fehlende Werte behandeln…",
        "Chuẩn hóa ngày…": "Datumsangaben normalisieren…",
        "Khử trùng lặp…": "Duplikate entfernen…",
        "Thay thế…": "Ersetzen…",
        "Xem các dòng sai": "Die fehlerhaften Zeilen anzeigen",
        "Không tìm thấy cột «%@» trong bảng này.": "Die Spalte «%@» ist in dieser Tabelle nicht vorhanden.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplikate entfernt — «%@» ist jetzt eindeutig. Wert: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplikate entfernt, aber «%@» hat noch %d {one=doppelte Zeile|other=doppelte Zeilen} (vorher: %d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "diese Zeilen teilen den SCHLÜSSEL, aber nicht die ganze Zeile; du musst also hinsehen und wählen, ",
        "giữ hàng nào.": "welche du behältst.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Es konnte kein Wert gelesen werden, der gegen diese Regel verstößt.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%d {one=falscher Wert|other=falsche Werte} in Spalte «%@» — fülle Ersetzen aus und klicke auf Vorschau",
        "Đã chấm lại: %.0f/100": "Neu bewertet: %.0f/100",
        "Xem trước báo cáo": "Berichtsvorschau",
        "Tham số…": "Parameter…",
        "Xuất HTML…": "Als HTML exportieren…",
        "In / PDF…": "Drucken / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=Block|other=Blöcke} ausgeführt · %d {one=Block|other=Blöcke} FEHLGESCHLAGEN",
        "%d khối chạy được": "%d {one=Block|other=Blöcke} ausgeführt",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · VERALTETE DATEN — die Quelldatei hat sich geändert; neu erstellen",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Die Berichtsvorschau benötigt ein .%@-Dokument",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Keine Datenquelle gefunden — deklariere «source: datei.csv» im Frontmatter.",
        "Không dựng được báo cáo.": "Der Bericht konnte nicht erstellt werden.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Dieser Bericht deklariert keine Parameter im Frontmatter.",
        "Tham số báo cáo": "Berichtsparameter",
        "Dựng lại": "Neu erstellen",
        "Đã xuất %@": "%@ exportiert",
        "Báo cáo: xem trước": "Bericht: Vorschau",
        "Báo cáo: sinh loạt…": "Bericht: Stapelweise erzeugen…",
        "không phải tài liệu .greport.md": "ist kein .greport.md-Dokument",
        "không phân tích được báo cáo": "der Bericht konnte nicht analysiert werden",
        "không tìm được dữ liệu nguồn": "die Quelldaten wurden nicht gefunden",
        "không đọc được danh sách tham số": "die Parameterliste konnte nicht gelesen werden",
        "Sinh loạt cần tài liệu đuôi .%@": "Die Stapelerzeugung benötigt ein .%@-Dokument",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Parameterliste wählen (CSV oder JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Ordner für %d {one=Bericht|other=Berichte} wählen",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "fehlende Parameter ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "zeigt auf die Quelldatei selbst — Überschreiben wird verweigert",
        "%d khối HỎNG": "%d {one=Block|other=Blöcke} FEHLGESCHLAGEN",
        "Sinh loạt xong: %d tệp · %d hỏng": "Stapel fertig: %d {one=Datei|other=Dateien} · %d fehlgeschlagen",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=Parametersatz konnte|other=Parametersätze konnten} nicht erstellt werden — siehe Zusammenfassung",
        "Sơ đồ Mermaid: xem trước": "Mermaid-Diagramm: Vorschau",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid-Diagramm: Vorlage einfügen…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid-Diagramm: neu formatieren",
        "Nền trong suốt": "Transparenter Hintergrund",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Dieser Mac kann das Diagramm nicht in PNG rastern — macOS 13 ist erforderlich. Der SVG-Export funktioniert weiterhin.",
        "Lưu PNG %@…": "PNG %@ sichern…",
        "Lưu SVG…": "SVG sichern…",
        "Chép ảnh vào clipboard": "Bild in die Zwischenablage kopieren",
        "Màu thương hiệu…": "Markenfarben…",
        "Màu thương hiệu cho sơ đồ": "Markenfarben für Diagramme",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Jedes Feld ist eine Farbe #rrggbb. Gesichert in «themes/mermaid-brand.json» — auf einen anderen Mac kopierbar.",
        "Màu chính": "Hauptfarbe",
        "Chữ trên nút": "Text auf Knoten",
        "Viền": "Rahmen",
        "Đường nối": "Verbindungen",
        "Nền khi xuất ảnh": "Hintergrund beim Export",
        "Lưu và chèn %%{init}%% vào tài liệu": "Sichern und %%{init}%% ins Dokument einfügen",
        "Đã lưu màu thương hiệu": "Markenfarben gesichert",
        "Đã chép ảnh sơ đồ vào clipboard": "Diagrammbild in die Zwischenablage kopiert",
        "Đã lưu %@ — %@": "%@ gesichert — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Dieses Diagramm hat bereits eine %%{init}%%-Anweisung — deine bleibt unberührt.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% eingefügt — das Diagramm trägt jetzt seine eigenen Farben",
        "Chèn màu thương hiệu vào sơ đồ": "Markenfarben ins Diagramm einfügen",
        "Định dạng sơ đồ Mermaid": "Mermaid-Diagramm neu formatieren",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Der Diagrammquelltext ist bereits sauber — nichts zu ändern",
        "Đã định dạng lại sơ đồ": "Diagramm neu formatiert",
        "Đã định dạng lại %d sơ đồ": "%d {one=Diagramm|other=Diagramme} neu formatiert",
        "Thư viện mẫu sơ đồ": "Bibliothek der Diagrammvorlagen",
        "Mẫu sơ đồ đầy đủ": "Vollständige Diagrammvorlagen",
        "Mẩu cú pháp": "Syntaxbausteine",
        "Đang soạn: %@": "In Bearbeitung: %@",
        "Đã chèn mẫu «%@»": "Vorlage «%@» eingefügt",
        "Tài liệu đang ở chế độ chỉ đọc.": "Dieses Dokument ist schreibgeschützt.",
        "Sơ đồ Mermaid": "Mermaid-Diagramm",
        "Tài liệu chưa có khối mermaid nào.": "Dieses Dokument hat keinen Mermaid-Block.",
        "Thương hiệu": "Marke",
        "Xuất…": "Exportieren…",
        "Chưa có sơ đồ nào": "Noch keine Diagramme",
        "%d sơ đồ · %@": "%d {one=Diagramm|other=Diagramme} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%d/%d {one=Diagramm|other=Diagramme} FEHLGESCHLAGEN — Diagramm %d%@",
        ", dòng %d": ", Zeile %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Dieses Dokument hat keinen ```mermaid-Block und ist auch keine .mmd-Datei.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Noch ist kein Diagramm fertig gezeichnet.",
        "Không tìm thấy «%@» trong mã sơ đồ": "«%@» wurde im Diagrammquelltext nicht gefunden",
        "không dựng được hàng rào chặn mạng cho WKWebView": "die Netzwerksperre für WKWebView konnte nicht erstellt werden",
        "Luật kết hợp": "Assoziationsregeln",
        "Mỗi dòng một giỏ": "Ein Warenkorb pro Zeile",
        "Hai cột: mã · item": "Zwei Spalten: ID · Artikel",
        "Dạng dữ liệu giao dịch": "Form der Transaktionsdaten",
        "Cột giỏ hàng hoặc mã giao dịch": "Warenkorb- oder Transaktions-ID-Spalte",
        "Cột item": "Artikelspalte",
        "Ký tự phân tách item": "Trennzeichen für Artikel",
        "Support tối thiểu, phần trăm": "Mindest-Support, Prozent",
        "Confidence tối thiểu, phần trăm": "Mindest-Confidence, Prozent",
        "Tách bởi:": "Getrennt durch:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "Tabelle der Assoziationsregeln",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Achtung",
        "%d giao dịch · %d item · %d luật": "%d {one=Transaktion|other=Transaktionen} · %d {one=Artikel|other=Artikel} · %d {one=Regel|other=Regeln}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — keine Regel hat die Schwellen erreicht; senke Support oder Confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — VORZEITIG GESTOPPT, die Tabelle ist UNVOLLSTÄNDIG",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=Transaktion enthält|other=Transaktionen enthalten} beide Seiten",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Die Zwei-Spalten-Form benötigt zwei VERSCHIEDENE Spalten.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%d {one=Zeile|other=Zeilen} in %d {one=Transaktion|other=Transaktionen} markiert, die «%@» enthalten",
        "CSV: luật kết hợp…": "CSV: Assoziationsregeln…",
        "Khai phá theo nhóm": "Gruppen-Mining",
        "Cột nhóm": "Gruppenspalte",
        "Cột giá trị": "Wertespalte",
        "Cột thứ hai cho tương quan": "Zweite Spalte für die Korrelation",
        "Cách xếp hạng": "Rangfolge",
        "Nhóm theo:": "Gruppieren nach:",
        "Giá trị:": "Wert:",
        "Xếp theo:": "Sortieren nach:",
        "Bảng xếp hạng nhóm": "Tabelle der Gruppenrangfolge",
        "Nhóm": "Gruppe",
        "Hàng": "Zeilen",
        "Hàng rào riêng": "Eigene Schranke",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r-Differenz",
        "Ghi chú": "Notiz",
        "không đo được": "nicht messbar",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=Gruppe|other=Gruppen} · gepoolte Referenzkorrelation %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GRUPPE|other=GRUPPEN} VERWORFEN",
        "Bảng này không có cột chữ nào để gom nhóm.": "Diese Tabelle hat keine Textspalte zum Gruppieren.",
        "Bảng này không có cột số nào để khai phá.": "Diese Tabelle hat keine numerische Spalte zum Auswerten.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%d {one=Zeile|other=Zeilen} der Gruppe «%@» markiert",
        "CSV: khai phá theo nhóm…": "CSV: Gruppen-Mining…",
        "\u{2194}": "↔",
        "Dự báo": "Prognose",
        "Cột giá trị theo thời gian": "Wertespalte über die Zeit",
        "Mô hình dự báo": "Prognosemodell",
        "Số kỳ dự báo": "Anzahl der zu prognostizierenden Perioden",
        "Kết luận so với baseline": "Urteil gegenüber den Referenzmodellen",
        "Mô hình:": "Modell:",
        "Số kỳ:": "Perioden:",
        "Chu kỳ:": "Saison:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Saisonperiode; leer lassen für automatische Erkennung",
        "Bảng giá trị dự báo": "Tabelle der prognostizierten Werte",
        "Kỳ": "Periode",
        "Dải 80%": "80-%-Band",
        "Dải 95%": "95-%-Band",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "nicht berechenbar",
        "Bảng này không có cột số nào để dự báo.": "Diese Tabelle hat keine numerische Spalte zum Prognostizieren.",
        "Không dựng được dự báo cho cột này.": "Für diese Spalte konnte keine Prognose erstellt werden.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Die Spalte «%@» hat nur %d {one=numerischen Wert|other=numerische Werte} — für eine Prognose sind mindestens 4 nötig.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Die Reihe wird in der Zeilenreihenfolge der Datei gelesen — ohne Neusortierung, ohne abgeleitete Zeitspalte.\n",
        "Sai số huấn luyện": "Trainingsfehler",
        "CSV: dự báo chuỗi thời gian…": "CSV: Zeitreihenprognose…",
        "Holt-Winters cộng": "Holt-Winters additiv",
        "Holt-Winters nhân": "Holt-Winters multiplikativ",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Spalten für das Clustering",
        "Đường cong WCSS": "WCSS-Kurve",
        "Phân cụm": "Cluster",
        "Chuẩn hoá:": "Skalierung:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Wähle mindestens eine Spalte.",
        "Không đủ dữ liệu để dựng đường cong.": "Nicht genug Daten, um die Kurve zu erstellen.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Der Ellbogen legt k = %d nahe. WCSS fällt IMMER, wenn k wächst; das ist also eine Lesehilfe für das Diagramm und kein statistisches Kriterium — sieh dir die Kurve an und beurteile, ob der Knick deutlich ist.",
        "WCSS theo k": "WCSS nach k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "Die k-Distanz legt eps = %@ nahe (minPts ist standardmäßig 2 × Spaltenzahl = %d). %@",
        "Khoảng cách tới hàng xóm thứ k": "Abstand zum k-ten Nachbarn",
        "Cần ít nhất 2 cột số để phân cụm.": "Für das Clustering sind mindestens 2 numerische Spalten nötig.",
        "Cụm theo %@ và %@": "Cluster nach %@ und %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — Cluster in %d {one=Dimension|other=Dimensionen} gefunden; die Grafik zeigt nur die ersten 2",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# Rauschen (cluster_id = -1): %d {one=Zeile|other=Zeilen}\n",
        "CSV: phân cụm…": "CSV: Clustering…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Clusterzentren (Originaleinheiten) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Korrelationsmatrix",
        "Phương pháp tương quan": "Korrelationsmethode",
        "Tương quan không hàm ý nhân quả.": "Korrelation bedeutet nicht Kausalität.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Stärkstes Paar: %@ ↔ %@ = %@ (n = %d). Klicke auf eine Zelle für ein Streudiagramm.",
        "Không cặp nào đo được.": "Kein Paar ist messbar.",
        "%@ ↔ %@: %@ trên %d hàng": "%@ ↔ %@: %@ über %d {one=Zeile|other=Zeilen}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Für die Korrelation sind mindestens 2 numerische Spalten nötig.",
        "Không đọc được cột «%@».": "Die Spalte «%@» konnte nicht gelesen werden.",
        "CSV: ma trận tương quan…": "CSV: Korrelationsmatrix…",
        "Bất thường": "Anomalien",
        "Danh sách bất thường": "Anomalienliste",
        "Cột:": "Spalte:",
        "Cột số cần xét": "Zu untersuchende numerische Spalte",
        "Cách:": "Methode:",
        "Phương pháp phát hiện": "Erkennungsmethode",
        "Phương pháp đã dùng": "Verwendete Methode",
        "Ngưỡng": "Schwelle",
        "Đánh dấu": "Markieren",
        "Xuất tab mới": "In neuen Tab exportieren",
        "Dòng": "Zeile",
        "Điểm": "Wert",
        "Vì sao": "Warum",
        "nhẹ": "leicht",
        "vừa": "mäßig",
        "nặng": "schwer",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=Zeile|other=Zeilen} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Diese Tabelle hat keine numerische Spalte, in der nach Anomalien gesucht werden könnte.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=anomale Zeile|other=anomale Zeilen} markiert",
        "CSV: tìm bất thường…": "CSV: Anomalien finden…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%d {one=Regel|other=Regeln}, alle BESTANDEN · %d {one=Zeile|other=Zeilen} · %.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%d {one=Fehler|other=Fehler} · %d {one=Warnung|other=Warnungen} über %d {one=Regel|other=Regeln} · %d {one=Zeile|other=Zeilen} · %.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Sichere zuerst das Dokument — die Qualitätsregeln liegen neben der Datendatei.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Noch kein Regelsatz. Lege die Datei %@ an und öffne erneut.",
        "Lịch sử": "Verlauf",
        "Câu đã lưu": "Gesicherte Abfragen",
        "Lưu câu này…": "Diese Abfrage sichern…",
        "Lưu câu truy vấn": "Abfrage sichern",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Gib ihr einen Namen, um sie später wiederzufinden. Gleicher Name überschreibt.",
        "Ví dụ: Doanh thu theo tỉnh": "Zum Beispiel: Umsatz nach Provinz",
        "Chưa nhập giá trị cho tham số: %@": "Für den Parameter wurde kein Wert eingegeben: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Das Plug-in hat sich seit deiner Freigabe geändert — GEditor führt es nicht aus",
        "Chạy plugin chưa duyệt?": "Nicht freigegebenes Plug-in ausführen?",
        "Tôi tin file này — chạy": "Ich vertraue dieser Datei — ausführen",
        "KHÔNG có chữ ký": "NICHT signiert",
        "Chữ ký: %@": "Signatur: %@",
        "Đường dẫn: %@": "Pfad: %@",
        "Thay": "Ersetzen",
        "Thay tất cả": "Alle ersetzen",
        "Chuỗi thuần": "Reiner Text",
        "Extended (\\n \\t \\xNN)": "Erweitert (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Regulärer Ausdruck",
        "Phân biệt hoa thường": "Groß-/Kleinschreibung beachten",
        "Cả từ": "Ganzes Wort",
        "Không có kết quả": "Keine Ergebnisse",
        "Thử biểu thức chính quy…": "Regulären Ausdruck testen…",
        "Chế độ Log (tô theo mức)": "Log-Modus (Farbe nach Stufe)",
        "Lọc log theo mức…": "Log nach Stufe filtern…",
        "Chạy trên cả thư mục…": "Auf den ganzen Ordner anwenden…",
        "Lọc qua lệnh ngoài…": "Durch externen Befehl filtern…",
        "Script…": "Skripte…",
        "Gói mở rộng…": "Erweiterungspakete…",
        "Cửa sổ mới": "Neues Fenster",
        "Tách tab ra cửa sổ mới": "Tab in ein neues Fenster lösen",
        "Chưa mở thư mục nào": "Kein Ordner geöffnet",
        "Tìm file trong thư mục": "Datei im Ordner suchen",
        "Lọc theo tên": "Nach Name filtern",
        "File mới…": "Neue Datei…",
        "Thư mục mới…": "Neuer Ordner…",
        "Đổi tên…": "Umbenennen…",
        "Chuyển vào Thùng rác": "In den Papierkorb legen",
        "Hiện trong Finder": "Im Finder zeigen",
        "Đang đọc cấu trúc tài liệu…": "Dokumentstruktur wird gelesen…",
        "file này không có hàm nào": "diese Datei hat keine Funktionen",
        "Không có gì khớp": "Keine Treffer",
        "Văn bản thuần": "Reiner Text",
        "🔒 Chỉ đọc": "🔒 Schreibgeschützt",
        "Đang theo dõi": "Wird verfolgt",
        "ngắt tại cột": "Umbruch bei Spalte",
        "Cú pháp": "Syntax",
        "Bấm để chèn vào ô truy vấn": "Klicken, um in die Abfrage einzufügen",
        "truy vấn không hợp lệ": "ungültige Abfrage",
        "khóa `ten` ở gốc": "Schlüssel «name» in der Wurzel",
        "khóa có dấu cách": "Schlüssel mit Leerzeichen",
        "phần tử đầu": "erstes Element",
        "mọi phần tử": "alle Elemente",
        "lát cắt": "Ausschnitt",
        "hợp nhiều chỉ số": "Vereinigung von Indizes",
        "mọi khóa `gia` ở mọi tầng": "alle Schlüssel «preis» auf allen Ebenen",
        "mọi nút": "alle Knoten",
        "lọc theo số": "nach Zahl filtern",
        "lọc theo có mặt": "nach Vorhandensein filtern",
        "Tới lỗi đầu tiên": "Zum ersten Fehler springen",
        "Cột doanh_thu là số": "Die Spalte umsatz ist numerisch",
        "lọc…": "filtern…",
        "Hủy": "Abbrechen",
        "Thực hiện thay": "Ersetzen ausführen",
        "xem trước": "Vorschau",
        "tương tác": "interaktiv",
        "Soạn thảo": "Bearbeiten",
        "Giao diện": "Oberfläche",
        "Phím tắt": "Tastaturkurzbefehle",
        "Cỡ chữ": "Schriftgröße",
        "Bề rộng TAB": "Tabulatorbreite",
        "Thụt lề bằng TAB": "Mit Tabulatoren einrücken",
        "Tự động thụt lề khi xuống dòng": "Beim Zeilenumbruch automatisch einrücken",
        "Tô mọi kết quả tìm kiếm": "Alle Suchergebnisse hervorheben",
        "Chuẩn hóa về NFC khi lưu": "Beim Sichern auf NFC normalisieren",
        "Ngôn ngữ": "Sprache",
        "Nền": "Erscheinungsbild",
        "Theo hệ thống": "Systemeinstellung",
        "Sáng": "Hell",
        "Tối": "Dunkel",
        "Theme": "Thema",
        "Dùng preset Notepad++": "Notepad++-Voreinstellung verwenden",
        "Về phím mặc định": "Zurück zu den Standardtasten",
        "Mở file cấu hình": "Konfigurationsdatei öffnen",
        "Xuất theme hiện tại": "Aktuelles Thema exportieren",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Der Sprachwechsel wird beim nächsten Start vollständig wirksam.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Die Standardtasten gelten wieder beim nächsten Start.",
        "Xem trước Markdown": "Markdown-Vorschau",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Die Vorschau nutzt die Markdown-Engine des Systems: noch keine Tabellen und keine Farbgebung für Codeblöcke.",
        "Thử biểu thức chính quy": "Regulären Ausdruck testen",
        "Biểu thức": "Ausdruck",
        "Văn bản thử": "Testtext",
        "Kết quả": "Ergebnis",
        "Kết quả khớp": "Treffer",
        "Biểu thức này làm gì": "Was dieser Ausdruck tut",
        "Giải thích biểu thức": "Ausdruck erklären",
        "Chế độ tìm kiếm": "Suchmodus",
        "Kết quả tìm kiếm": "Suchergebnisse",
        "Không khớp chỗ nào": "Keine Treffer",
        " (đã cắt bớt)": " (gekürzt)",
        "Bản đồ tài liệu": "Dokumentkarte",
        "Thanh tab": "Tableiste",
        "Hàng tiêu đề cột": "Kopfzeile der Spalten",
        "Không có cột nào": "Keine Spalten",
        "Cây thư mục workspace": "Baum des Arbeitsbereichs",
        "Danh sách hàm và lớp": "Liste der Funktionen und Klassen",
        "Kết quả tìm trong thư mục": "Suchergebnisse im Ordner",
        "Bảng dữ liệu CSV": "CSV-Datentabelle",
        "Bàn làm sạch dữ liệu": "Datenbereinigungs-Werkbank",
        "Truy vấn JSONPath": "JSONPath-Abfrage",
        "Danh sách lỗi dữ liệu": "Liste der Datenfehler",
        "Bộ đánh giá golden set…": "Golden-Set-Bewerter…",
        "So với điểm ngoài (JSONL)…": "Mit externen Werten vergleichen (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Datei mit externen Werten wählen (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Ausgewählten Knoten umbenennen",
        "Gộp các node đang chọn": "Ausgewählte Knoten zusammenführen",
        "Tách node đang chọn": "Ausgewählten Knoten aufteilen",
        "Trích subgraph đang chọn ra tab mới": "Ausgewählten Teilgraphen in einen neuen Tab extrahieren",
        "Không có gì để đổi": "Nichts zu ändern",
        "%@ — áp %d thay đổi?": "%@ — %d {one=Änderung|other=Änderungen} anwenden?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%@: %d {one=Änderung|other=Änderungen} · Cmd-Z widerruft den ganzen Stapel",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Setze die Einfügemarke auf GENAU EINEN Knoten und versuche es erneut",
        "Đổi tên «%@»": "«%@» umbenennen",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Alle Kanten und Beschriftungen, die auf diesen Knoten verweisen, ändern sich mit.",
        "Đổi tên node": "Knoten umbenennen",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Wähle MINDESTENS ZWEI Knoten und versuche es erneut",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Kanonische Form «%@» — am häufigsten, am längsten, mit Akzenten",
        "Gộp node": "Knoten zusammenführen",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Wähle die zu verschiebenden KANTENZEILEN und versuche es erneut",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Alle ausgewählten Zeilen müssen GENAU EINEN Knoten berühren — wähle weitere Kantenzeilen",
        "Tách «%@» — chuyển %d cạnh": "«%@» aufteilen — %d {one=Kante|other=Kanten} verschieben",
        "Cạnh tới: %@": "Kanten zu: %@",
        "Tách node": "Knoten aufteilen",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Dokument nicht gesichert — die extrahierte Datei braucht einen Platz daneben",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Wähle den zu extrahierenden Teil des Graphen und versuche es erneut",
        "Gom biến thể entity → bảng duyệt": "Entitätsvarianten zusammenfassen → Prüftabelle",
        "Áp bảng duyệt đã sửa": "Geänderte Prüftabelle anwenden",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Dokument nicht gesichert — die Prüftabelle muss neben der Graphdatei liegen",
        "Không tìm thấy biến thể nào để gom": "Keine Varianten zum Zusammenfassen gefunden",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=Variantengruppe|other=Variantengruppen} — korrigiere die Spalte «canonical» und führe «Prüftabelle anwenden» aus",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Keine Prüftabelle «%@» — führe zuerst «Entitätsvarianten zusammenfassen» aus",
        "Bảng duyệt không đọc được: %@": "Prüftabelle nicht lesbar: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Die Prüftabelle hat keine Zeile, die geändert werden müsste",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Keine Stelle im Graphen passt zur Prüftabelle",
        "Gom biến thể entity": "Entitätsvarianten zusammenfassen",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=Änderung|other=Änderungen} angewendet · Alias-Tabelle und Markerliste neben der Datei geschrieben",
        "Áp %d thay đổi lên đồ thị?": "%d {one=Änderung|other=Änderungen} auf den Graphen anwenden?",
        "%d alias → dạng chuẩn.": "%d {one=Alias|other=Aliase} → kanonische Form.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "Knoten ZUSAMMENFÜHREN (nicht durch erneutes Tippen rückgängig zu machen):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=Alias ist|other=Aliase sind} nicht im Graphen und {one=wird|other=werden} übersprungen.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Abdeckungsanalyse Chunk ↔ Entität",
        "Xuất gói ngữ cảnh (JSONL)": "Kontextpaket exportieren (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Abdeckung Chunk ↔ Entität ↔ Graph",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %d {one=Entität|other=Entitäten} · %d {one=Chunk|other=Chunks} · %.0f %% der Entitäten erwähnt · %.0f %% der Chunks mit Entität",
        "Entity không chunk nào nhắc tới": "Entitäten, die kein Chunk erwähnt",
        "Chunk mồ côi (không chứa entity nào)": "Verwaiste Chunks (ohne jede Entität)",
        "Node đồ thị không có entity đối ứng": "Graphknoten ohne zugehörige Entität",
        "không có": "keine",
        "Phương pháp": "Methode",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Die Zuordnung Chunk ↔ Entität konnte nicht erstellt werden",
        "Chấm sức khoẻ đồ thị": "Graphgesundheit bewerten",
        "sức khoẻ đồ thị": "Graphgesundheit",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Gesundheit %@/100 · %d {one=Fehler|other=Fehler} · %d {one=Umkehrung|other=Umkehrungen} · %d Verwaiste",
        "Lai với đồ thị": "Hybrid mit dem Graphen",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: das Graphsignal wird ganz ignoriert, das Ergebnis entspricht reinem BM25",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α hoch: der Graph passt die BM25-Rangfolge nur leicht an",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α um den Standardwert 0,7: BM25 führt, der Graph passt an",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α niedrig: der Graph führt, BM25 entscheidet nur Gleichstände",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: nur das Graphsignal; Chunks ohne Entität stehen gleichauf",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Dokument nicht gesichert — der Hybrid braucht eine Graphdatei neben dem Korpus",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Graphdatei «%@» nicht gefunden — der Hybrid braucht sie für sein Signal",
        "lai %.1f ms · %@": "Hybrid %.1f ms · %@",
        "Thuật toán…": "Algorithmen…",
        "PageRank (độ dày viền)": "PageRank (Randstärke)",
        "Cộng đồng (màu nền)": "Gemeinschaften (Hintergrundfarbe)",
        "Thành phần liên thông": "Zusammenhangskomponenten",
        "Xuất bảng node ra tab mới": "Knotentabelle in neuen Tab exportieren",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%d {one=Komponente|other=Komponenten} · größte %d {one=Knoten|other=Knoten} · %d verwaiste Knoten",
        "Tài liệu này không phải đồ thị DOT": "Dieses Dokument ist kein DOT-Graph",
        "Không dựng được bảng node/cạnh: %@": "Die Knoten-/Kantentabelle konnte nicht erstellt werden: %@",
        "%d hàng · %@": "%d {one=Zeile|other=Zeilen} · %@",
        "Gán nhãn": "Etikettieren",
        "Ghi chú (tuỳ chọn)": "Notiz (optional)",
        "Lưu record": "Datensatz sichern",
        "Xuất CSV": "CSV exportieren",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Dokument nicht gesichert — der Bewerter muss neben der Korpusdatei liegen",
        "Không nạp được bộ đánh giá: %@": "Der Bewerter konnte nicht geladen werden: %@",
        "Không lưu được: %@": "Sichern nicht möglich: %@",
        "Bộ đánh giá chưa có record nào": "Der Bewerter hat noch keinen Datensatz",
        "Không ghi được: %@": "Schreiben nicht möglich: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Dieses Dokument ist weder eine .mmd-Datei noch DOT und hat keinen Mermaid-Block.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=Knoten|other=Knoten} · %d {one=Kante|other=Kanten} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid-Diagramm: Element hinzufügen…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid-Diagramm: die beiden ausgewählten Elemente verbinden",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid-Diagramm: Beschriftung des ausgewählten Elements ändern…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid-Diagramm: ausgewähltes Element löschen",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid-Diagramm: Nachricht nach oben",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid-Diagramm: Nachricht nach unten",
        "Thêm phần tử": "Element hinzufügen",
        "Thêm participant": "Teilnehmer hinzufügen",
        "Thêm mục": "Eintrag hinzufügen",
        "Thêm mục sơ đồ": "Diagrammeintrag hinzufügen",
        "Sửa mục sơ đồ": "Diagrammeintrag ändern",
        "Xoá mục sơ đồ": "Diagrammeintrag löschen",
        "Xoá phần tử": "Element löschen",
        "Sửa nhãn": "Beschriftung ändern",
        "Đổi thứ tự message": "Nachrichten neu ordnen",
        "Tên mục": "Name des Eintrags",
        "Mục mới": "Neuer Eintrag",
        "Tên mục hiện trên sơ đồ.": "Der Name des Eintrags erscheint im Diagramm.",
        "Bảng thuộc tính sơ đồ": "Eigenschaftstabelle des Diagramms",
        "Tài liệu này không có khối mermaid nào": "Dieses Dokument hat keinen Mermaid-Block",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Bezeichner im Diagrammquelltext — ohne Leerzeichen. Die Beschriftung wird danach per Doppelklick geändert.",
        "Để trống thì hiện chính định danh.": "Wenn leer, wird der Bezeichner selbst angezeigt.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Nur die sichtbare BESCHRIFTUNG ändert sich; der Bezeichner des Elements bleibt gleich.",
        "Không rõ «%@» là phần tử nào": "Unklar, welches Element «%@» ist",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Wähle GENAU ZWEI Elemente und versuche es erneut",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Setze die Einfügemarke auf GENAU EIN Element und versuche es erneut",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Wähle EIN Element zum Löschen, oder zwei durch eine Kante verbundene Elemente",
        "Xoá «%@» và %d cạnh chạm nó?": "«%@» und die %d {one=Kante, die es berührt|other=Kanten, die es berühren}, löschen?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Die Knoten am anderen Ende dieser Kanten bleiben erhalten — sie werden mit ihrer Beschriftung neu deklariert, falls die Kantenanweisung ihre einzige Deklaration war.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Das Diagramm «%@» lässt sich nur als Text bearbeiten — %@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: zwischen zwei Elementen ziehen, um zu verbinden; Doppelklick, um die Beschriftung zu ändern",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: zwischen zwei Teilnehmern ziehen, um eine Nachricht hinzuzufügen; Reihenfolge über das Menü Werkzeuge ändern",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: in der Eigenschaftstabelle unten bearbeiten",
        "Soạn trực quan đã bật": "Visuelles Bearbeiten aktiviert",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%@ · %d {one=Eintrag|other=Einträge} — direkt in der Tabelle bearbeiten, jede Zelle ist ein Widerrufsschritt",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Bei einem Kreisdiagramm eine Zahl; bei einem Gantt das, was nach dem Doppelpunkt steht.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid-Diagramm: Block in eine .mmd-Datei auslagern…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid-Diagramm: referenzierte Datei wieder einbetten",
        "Tách khối sơ đồ": "Diagrammblock auslagern",
        "Nhúng khối sơ đồ": "Diagrammblock einbetten",
        "Tách khối sơ đồ ra tệp riêng": "Diagrammblock in eine eigene Datei auslagern",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Die Datei liegt NEBEN dem Dokument; der Block behält eine Referenzzeile, damit nur an einer Stelle bearbeitet wird.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Dokument nicht gesichert — die Diagrammdatei braucht einen Platz daneben",
        "Đã có tệp «%@» — chọn tên khác": "Die Datei «%@» gibt es schon — wähle einen anderen Namen",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Nach «%@» ausgelagert — der Block behält eine Referenzzeile",
        "Mở tệp": "Datei öffnen",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» wieder eingebettet; die Datei bleibt auf der Festplatte",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Dieser Block enthält ein echtes Diagramm, keine Referenz",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Dieser Block referenziert «%@» — öffne diese Datei, um sie zu bearbeiten",
        "Không đọc được tệp sơ đồ %@": "Die Diagrammdatei %@ konnte nicht gelesen werden",
        "Soạn trực quan": "Visuelles Bearbeiten",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Von einem Knoten zum anderen ziehen, um eine Kante hinzuzufügen; Doppelklick, um die Beschriftung zu ändern. Jede Aktion ist ein Widerrufsschritt.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Visuelles Bearbeiten: zwischen zwei Knoten ziehen, um eine Kante hinzuzufügen; Doppelklick, um die Beschriftung zu ändern",
        "Soạn trực quan đã tắt": "Visuelles Bearbeiten deaktiviert",
        "Thêm node…": "Knoten hinzufügen…",
        "Thêm cạnh giữa hai node đang chọn…": "Kante zwischen den beiden ausgewählten Knoten hinzufügen…",
        "Sửa nhãn node đang chọn…": "Beschriftung des ausgewählten Knotens ändern…",
        "Xoá node/cạnh đang chọn": "Ausgewählten Knoten/ausgewählte Kante löschen",
        "Thêm node": "Knoten hinzufügen",
        "Thêm cạnh": "Kante hinzufügen",
        "Sửa nhãn node": "Knotenbeschriftung ändern",
        "Xoá node": "Knoten löschen",
        "Xoá cạnh": "Kante löschen",
        "Cmd-Z hoàn tác": "Cmd-Z widerruft",
        "Tài liệu đang ở chế độ chỉ đọc": "Dieses Dokument ist schreibgeschützt",
        "Nhãn của «%@»": "Beschriftung von «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Nur die sichtbare BESCHRIFTUNG ändert sich; der Bezeichner des Knotens bleibt gleich.",
        "Không rõ «%@» là node nào": "Unklar, welcher Knoten «%@» ist",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Knotenbezeichner in der DOT-Datei. Die Beschriftung wird danach per Doppelklick in der Grafik geändert.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Wähle GENAU ZWEI Knoten und versuche es erneut",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Wähle EINEN Knoten zum Löschen, oder zwei durch eine Kante verbundene Knoten",
        "Xoá node «%@» và %d cạnh chạm nó?": "Knoten «%@» und die %d {one=Kante, die ihn berührt|other=Kanten, die ihn berühren}, löschen?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Bleiben verwaiste Kanten stehen, erzeugt DOT die Knoten daraus neu — der gelöschte Knoten taucht beim nächsten Zeichnen wieder auf.",
        "Phòng thí nghiệm truy hồi BM25": "BM25-Retrieval-Labor",
        "Câu hỏi — Enter để tìm": "Frage — Eingabetaste zum Suchen",
        "Đánh giá…": "Bewerten…",
        "Đang dựng chỉ mục": "Index wird erstellt",
        "Không chunk nào khớp": "Kein Chunk passt",
        "kết quả trên": "beste Ergebnisse",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: jedes Wort zählt NUR einmal, egal wie oft es vorkommt",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 niedrig: Wiederholung eines Wortes bringt fast keine zusätzliche Punktzahl",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 um den Standardwert 1,2: Wiederholung bringt Punkte, aber abnehmend",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 hoch: ein Chunk, der ein Wort oft wiederholt, wird stark belohnt",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: die Länge wird ignoriert, lange Chunks werden nicht bestraft",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b niedrig: lange Chunks werden nur leicht bestraft",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b um den Standardwert 0,75: lange Chunks werden mäßig bestraft",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: maximale Längenstrafe, kurze Chunks werden bevorzugt",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: Retrieval-Labor…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Dokument nicht gesichert — der BM25-Index liegt neben der Korpusdatei und braucht daher einen Pfad",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Diese Datei ist kein JSONL — das Retrieval Lab arbeitet auf einem Chunk-Korpus",
        "Không dựng được chỉ mục BM25 cho tệp này": "Für diese Datei konnte kein BM25-Index erstellt werden",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Dokument nicht gesichert — für den Bericht wird ein Korpuspfad benötigt",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Bewertungssatz wählen (CSV oder JSONL: Frage + erwartete Chunk-ID)",
        "Đánh giá truy hồi": "Retrieval-Bewertung",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Ändere k1, b oder k oben und sieh erneut nach, um zwei Konfigurationen zu vergleichen; füge einen «compare»-Block hinzu, um zwei Parametersätze parallel auf demselben Bewertungssatz laufen zu lassen.",
        "Lỗi": "Fehler",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, Mittel %.0f)",
        "Chế độ JSONL": "JSONL-Modus",
        "Bản ghi": "Datensatz",
        "Chi tiết": "Detail",
        "Bản ghi ở dòng": "Datensatz in Zeile",
        "không phải JSON hợp lệ": "ist kein gültiges JSON",
        "bản ghi": "Datensätze",
        "dòng trắng": "Leerzeilen",
        "không phải đối tượng": "ist kein Objekt",
        "bảng hiện": "angezeigte Tabelle",
        "ĐÃ HUỶ giữa chừng": "MITTENDRIN ABGEBROCHEN",
        "Không lọc": "Kein Filter",
        "bản ghi khớp bộ lọc": "Datensätze, die dem Filter entsprechen",
        "Đưa con nháy tới một dòng để xem bản ghi": "Setze die Einfügemarke auf eine Zeile, um den Datensatz zu sehen",
        "Không có bản ghi nào hỏng": "Keine defekten Datensätze",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Noch nicht untersucht. Führe «JSONL: Chunks untersuchen» nach der Prüfung erneut aus.",
        "trường văn bản": "Textfeld",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHEMA (geraten — durch Wahl eines anderen Feldes änderbar)",
        "văn bản": "Text",
        "định danh": "Bezeichner",
        "metadata lồng": "verschachtelte Metadaten",
        "TRƯỜNG": "FELD",
        "phủ": "Abdeckung",
        "nhiều kiểu": "mehrere Typen",
        "ĐỘ DÀI — ký tự": "LÄNGE — Zeichen",
        "ĐỘ DÀI — từ": "LÄNGE — Wörter",
        "ĐỘ DÀI — token ước lượng": "LÄNGE — geschätzte Token",
        "RỖNG VÀ TRÙNG": "LEER UND DOPPELT",
        "chunk rỗng": "leere Chunks",
        "dòng": "Zeilen",
        "nhóm trùng chính xác": "Gruppen exakter Duplikate",
        "dòng không đọc được, không vào thống kê": "nicht lesbare Zeilen, nicht in der Statistik",
        "PHƯƠNG PHÁP": "METHODE",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«Zeichen» zählt Unicode-Zeichen (Skalare), nicht sichtbare Gruppen",
        "«từ» tách theo khoảng trắng ASCII": "«Wörter» trennt an ASCII-Leerzeichen",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«Token» zählt mit einem Silbentrenner — NICHT dem des Modells",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«Duplikat» bedeutet EXAKTES Duplikat; Beinahe-Duplikate stehen im Block ```quality",
        "chunk": "Chunks",
        "JSONL: kiểm và soi chunk…": "JSONL: Chunks prüfen und untersuchen…",
        "Ảnh": "Bild",
        "PDF": "PDF",
        "Tài liệu Word": "Word-Dokument",
        "Bảng tính Excel": "Excel-Tabelle",
        "Bản trình chiếu PowerPoint": "PowerPoint-Präsentation",
        "File nén": "Archiv",
        "Vừa khung": "An das Fenster anpassen",
        "Chép ảnh": "Bild kopieren",
        "Xoay": "Drehen",
        "Không đọc được ảnh «%@»": "Das Bild «%@» kann nicht gelesen werden",
        "Đã chép ảnh vào clipboard": "Bild in die Zwischenablage kopiert",
        "Bôi vàng": "Gelb hervorheben",
        "Gạch chân": "Unterstreichen",
        "Ghi chú…": "Notiz…",
        "Bỏ chú thích": "Anmerkungen entfernen",
        "Lấy chữ ra tab mới": "Text in einen neuen Tab extrahieren",
        "Lưu bản có chú thích…": "Kommentierte Fassung sichern…",
        "Tìm trong PDF": "Im PDF suchen",
        "Thêm": "Hinzufügen",
        "Trang %d/%d": "Seite %d/%d",
        "Trang %d": "Seite %d",
        "Kết quả %d/%d": "Ergebnis %d/%d",
        "0 kết quả": "0 Ergebnisse",
        "Không đọc được PDF «%@»": "Das PDF «%@» kann nicht gelesen werden",
        "PDF này có mật khẩu — chưa mở được nội dung": "Dieses PDF ist passwortgeschützt — der Inhalt ist nicht zugänglich",
        "Không thấy «%@» trong tài liệu": "«%@» wurde im Dokument nicht gefunden",
        "Đã bôi vàng": "Hervorgehoben",
        "Đã gạch chân": "Unterstrichen",
        "Hãy bôi đen một đoạn chữ trước": "Wähle zuerst einen Textabschnitt aus",
        "Đã thêm ghi chú": "Notiz hinzugefügt",
        "Trang này chưa có chú thích nào": "Diese Seite hat keine Anmerkungen",
        "Đã bỏ %d chú thích trên trang này": "%d {one=Anmerkung|other=Anmerkungen} auf dieser Seite entfernt",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Dieses PDF hat keine Textebene — es ist wahrscheinlich ein Scan",
        "Không ghi được tệp": "Die Datei konnte nicht geschrieben werden",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Die geschriebene Datei lässt sich NICHT korrekt wieder öffnen — verwende diese Fassung nicht",
        "Đã lưu %@ · %d trang": "%@ gesichert · %d {one=Seite|other=Seiten}",
        "Tên": "Name",
        "Kích thước": "Größe",
        "Đã nén": "Komprimiert",
        "Tỉ lệ": "Verhältnis",
        "Sửa lúc": "Geändert am",
        "Mở mục đang chọn": "Ausgewähltes Element öffnen",
        "Bung ra thư mục…": "In einen Ordner entpacken…",
        "Bung vào đây": "Hierher entpacken",
        "%d mục": "%d {one=Element|other=Elemente}",
        "giải nén ra %@": "entpackt nach %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— das Innere einer Office-Datei ist ein Archiv; dies sind die Bestandteile",
        "Đã bung %d mục": "%d {one=Element|other=Elemente} entpackt",
        "%d mục hỏng": "%d {one=defektes Element|other=defekte Elemente}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=Element|other=Elemente} ABGELEHNT, weil ihre Pfade aus dem Zielordner herausführen",
        "Không mở được mục này": "Dieses Element kann nicht geöffnet werden",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "In eine %@ kann noch nicht direkt zurückgeschrieben werden — nutze «Sichern unter…»",
        "Không có gì đổi": "Nichts hat sich geändert",
        "Đã ghi %d ô vào %@": "%d {one=Zelle|other=Zellen} in %@ geschrieben",
        "Đã ghi %d đoạn vào %@": "%d {one=Absatz|other=Absätze} in %@ geschrieben",
        "Không ghi được vào tệp — bản gốc còn nguyên": "In die Datei konnte nicht geschrieben werden — das Original ist unberührt",
        "dựng bài": "Testfall vorbereiten",
        "Không ghi được settings.json": "settings.json kann nicht geschrieben werden",
        "Xoay trái": "Links drehen",
        "Xoay phải": "Rechts drehen",
        "Trang lên": "Seite nach oben",
        "Trang xuống": "Seite nach unten",
        "Xoá trang…": "Seiten löschen…",
        "Xoá trang": "Seiten löschen",
        "Trích trang…": "Seiten extrahieren…",
        "Trích trang ra tệp mới": "Seiten in neue Datei extrahieren",
        "Gộp tệp PDF…": "PDF-Datei zusammenführen…",
        "Tách tệp…": "Datei teilen…",
        "Tách tệp PDF": "PDF-Datei teilen",
        "Xuất ảnh…": "Bilder exportieren…",
        "Xuất trang ra ảnh PNG": "Seiten als PNG-Bilder exportieren",
        "Hoàn tác trang": "Seitenbearbeitung widerrufen",
        "Lưu bản đã sửa…": "Bearbeitete Kopie sichern…",
        "Phát": "Abspielen",
        "Tạm dừng": "Pause",
        "Xem bình thường": "Normale Ansicht",
        "Chọn sheet": "Blatt wählen",
        "Mở sheet": "Blatt öffnen",
        "Bỏ và đổi sheet": "Verwerfen und Blatt wechseln",
        "Bảng tính có %d sheet.": "Die Arbeitsmappe hat %d Blätter.",
        "Bảng tính này chỉ có một sheet: «%@»": "Diese Arbeitsmappe hat nur ein Blatt: „%@“",
        "Bỏ phần chưa lưu của sheet này?": "Nicht gesicherte Änderungen dieses Blatts verwerfen?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Ein Blattwechsel ersetzt den gesamten Tab. Nicht mit ⌘S gesichertes geht verloren.",
        "Chọn tệp PDF cần gộp vào": "PDF-Datei zum Zusammenführen wählen",
        "Chọn thư mục ghi ảnh": "Ordner für die Bilder wählen",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Speicherort wählen. Die zweite Datei wird daneben abgelegt.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Das Dokument hat %d Seiten. Zu löschende Seiten eingeben, z. B. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Das Dokument hat %d Seiten. Zu extrahierende Seiten eingeben, z. B. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Das Dokument hat %d Seiten. Zu exportierende Seiten eingeben, z. B. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Das Dokument hat %d Seiten. Abzutrennenden Teil eingeben, z. B. 1-5; der Rest wird eine zweite Datei.",
        "Đã xoay trang %d": "Seite %d gedreht",
        "Đã xoá trang %@ · còn %d trang": "Seiten %@ gelöscht · %d Seiten übrig",
        "Đã gộp %d trang từ «%@»": "%d Seiten aus „%@“ zusammengeführt",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Geteilt in %@ (%d Seiten) und %@ (%d Seiten)",
        "Đã ghi %@ — %@ · %d trang": "%@ geschrieben — %@ · %d Seiten",
        "Đã xuất %d ảnh vào %@": "%d Bilder nach %@ exportiert",
        "Chỉ xuất được %d/%d ảnh": "Nur %d von %d Bildern wurden exportiert",
        "Đã hoàn tác một thao tác trang": "Eine Seitenaktion wurde widerrufen",
        "Không còn thao tác trang nào để hoàn tác": "Keine Seitenaktion mehr zum Widerrufen",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "ALLE Seiten können nicht gelöscht werden — ein PDF braucht mindestens eine Seite",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Dieser Bereich ist das ganze Dokument — nichts zum Abtrennen",
        "«%@» có mật khẩu — chưa gộp được": "„%@“ ist passwortgeschützt — Zusammenführen nicht möglich",
        "«%@» không có trang nào": "„%@“ hat keine Seiten",
        "Đã ở trang đầu": "Bereits auf der ersten Seite",
        "Đã ở trang cuối": "Bereits auf der letzten Seite",
        "· đã sửa, chưa lưu": "· bearbeitet, nicht gesichert",
        "Ảnh động · %d khung": "Animiertes Bild · %d Einzelbilder",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Nicht gesichertes Dokument — keine Datei auf dem Volume für die Binäransicht",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Dieser Befehl gilt nur für Excel-Arbeitsmappen",
        "Không đọc được danh sách sheet": "Die Blattliste konnte nicht gelesen werden",
        "Không có sheet «%@»": "Es gibt kein Blatt „%@“",
        "Không đọc được sheet «%@»": "Blatt „%@“ konnte nicht gelesen werden",
        "Sheet «%@» · %d hàng": "Blatt „%@“ · %d Zeilen",
        "phần còn lại": "der Rest",
        "Lưu ý": "Hinweis",
        "Cẩn thận": "Achtung",
        "Xem thêm": "Siehe auch",
        "Chép": "Kopieren",
        "Đã chép": "Kopiert",
        "Chép đoạn mã mẫu": "Beispielcode kopieren",
        "Tìm trong trợ giúp": "Hilfe durchsuchen",
        "Lùi": "Zurück",
        "Bắt đầu dùng": "Loslegen",
        "Không mở cửa sổ này khi khởi động nữa": "Dieses Fenster beim Start nicht mehr zeigen",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Die Hilfe ist noch nicht in dieser Sprache verfügbar — es wird Vietnamesisch gezeigt.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Zu Offset springen (z. B. 1F400 oder 0x1F400)",
        "Chép dòng đã chọn": "Ausgewählte Zeilen kopieren",
        "Đã chép %d dòng": "%d Zeilen kopiert",
        "Không đọc được «%@»": "„%@“ konnte nicht gelesen werden",
        "Tệp rỗng": "Leere Datei",
        "Không đọc được offset «%@»": "Offset „%@“ konnte nicht gelesen werden",
        "Offset 0x%@ vượt quá cỡ tệp": "Offset 0x%@ liegt hinter dem Dateiende",
        "Mở bằng ứng dụng khác…": "Mit anderer App öffnen…",
        "%d kênh": "%d Kanäle",
        "Không phát được «%@»": "„%@“ kann nicht abgespielt werden",
        "Không phát được — %@": "Abspielen nicht möglich — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS hat keinen eingebauten Decoder für das Format %@ — das ist eine Systemgrenze, keine defekte Datei.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Die Bytes lassen sich weiterhin in der Binäransicht ansehen, oder mit einer App mit eigenem Decoder öffnen.",
        "Ký…": "Signieren…",
        "Sửa chữ…": "Text bearbeiten…",
        "Sửa chữ": "Text bearbeiten",
        "Vẽ đè": "Darüber zeichnen",
        "Ô chưa điền": "Nächstes leeres Feld",
        "Xoá nội dung đã điền": "Ausgefüllte Werte löschen",
        "Tệp này không có ô biểu mẫu nào": "Diese Datei hat keine Formularfelder",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d Formularfelder geleert",
        "Mọi ô biểu mẫu đều đã có nội dung": "Alle Formularfelder sind bereits ausgefüllt",
        "Còn %d ô chưa điền": "Noch %d Felder leer",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Ausfüllbares Formular: %d Felder. Direkt hineinschreiben, dann „Bearbeitete Kopie sichern…“",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Signaturbild wählen (transparenter Hintergrund sieht am besten aus)",
        "Không dựng được trang có chữ ký": "Signierte Seite konnte nicht erstellt werden",
        "Đã chèn chữ ký vào trang %d": "Signatur auf Seite %d eingefügt",
        "Hãy bôi chọn phần chữ cần sửa trước": "Markieren Sie zuerst den zu ändernden Text",
        "Vùng chọn quá nhỏ": "Die Auswahl ist zu klein",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Der neue Text wird mit der Systemschrift ÜBER die Auswahl gezeichnet. Der alte Text wird verdeckt, nicht entfernt — er lässt sich weiterhin extrahieren, das ist also keine Schwärzung.",
        "Không dựng được trang đã sửa": "Bearbeitete Seite konnte nicht erstellt werden",
        "Đã vẽ đè chữ mới lên trang %d": "Neuen Text auf Seite %d gezeichnet",
        "Đổi chế độ View / Code": "Ansicht / Code umschalten",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Noch keine Baumansicht für JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Noch keine Diagrammansicht im Tab",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Noch keine Gliederungsansicht für PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Diese Datei hat nur einen Anzeigemodus",
        "%d nút": "%d Knoten",
        "Không dựng được cây: %@": "Baum konnte nicht erstellt werden: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Das Dokument ist zu groß für einen Baum — den Code-Modus verwenden",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Seiten dieser Datei konnten nicht aufgebaut werden \u{2014} Code-Modus verwenden.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Folien werden aus Text aufgebaut; Originalbilder und Layout werden noch nicht gezeichnet.",
        "Vừa ngang": "Breite anpassen",
        "Thu nhỏ trang": "Seite verkleinern",
        "Phóng to trang": "Seite vergrößern",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu":
            "\u{201E}%@\u{201C} wurde im Dokument nicht gefunden",
        "Chỗ khớp %d/%d": "Treffer %d von %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Auf der Seite ist kein Text ausgewählt.",
        "%d ký tự": "%d {one=Zeichen|other=Zeichen}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Dateien direkt im View-Modus öffnen, sofern vorhanden",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· MITTENDRIN ABGEBROCHEN — Tabelle unvollständig",
        "Chế độ hiển thị": "Anzeigemodus",
        "Đổi giữa View và Code (⌥⌘V)": "Zwischen View und Code wechseln (⌥⌘V)",
        "Trang tài liệu": "Dokumentseiten",
        "Chữ đã dựng": "Gesetzter Text",
        "Trang bảng tính": "Tabellenseiten",
        "Sơ đồ": "Diagramm",
        "Cây khoá–giá trị": "Schlüssel-Wert-Baum",
        "Bộ phát": "Player",
        "Danh sách mục": "Eintragsliste",
        "Báo cáo đã dựng": "Fertiger Bericht",
        "Tô theo mức": "Nach Stufe eingefärbt",
        "Trang slide": "Folienseiten",
        "Dàn ý": "Gliederung",
        "Lưu rồi dựng lại": "Sichern und neu aufbauen",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Zeigt die Fassung AUF DER FESTPLATTE — ungesicherte Änderungen fehlen hier.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Das System konnte die Dokumentansicht nicht aufbauen — nutzen Sie den Code-Modus.",
        "Lưu tệp trước khi xem trang.": "Sichern Sie die Datei, bevor Sie ihre Seiten ansehen.",
        "Đang ở chế độ Code": "Derzeit im Code-Modus",
        "Đang ở chế độ View": "Derzeit im View-Modus",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Quelltext sichtbar — klicken für den View-Modus (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "Im View-Modus — klicken, um zum Quelltext zurückzukehren (⌥⌘V)",
        "Tín hiệu: %@": "Signal: %@",
        "Lý do: %@": "Grund: %@",
        "Chi tiết: %@": "Detail: %@",
        "Mở báo cáo": "Bericht öffnen",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor wurde um %@ unerwartet beendet — öffnen Sie den Bericht; nichts wird versendet.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligaturen — aus, dann bleibt jedes Zeichen in seiner Zelle",
        "Chế độ CSV": "CSV-Modus",
        "Dấu phân tách": "Trennzeichen",
        "Tự nhận diện": "Automatisch erkennen",
        "Dấu phân tách: %@": "Trennzeichen: %@",
        "Theo đuôi tệp": "Nach Dateiendung",
        "%d dấu cách": "%d {one=Leerzeichen|other=Leerzeichen}",
        "Tài liệu đang sửa được": "Dieses Dokument ist bearbeitbar",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Schreibgeschützt, weil die Datei verfolgt wird — Verfolgung beenden, um zu bearbeiten",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Schreibgeschützt, weil die Datei auf der Festplatte nicht beschreibbar ist",
        "Đã mở khoá — tài liệu sửa được": "Entsperrt — das Dokument ist wieder bearbeitbar",
        "Nhân bản tệp": "Datei duplizieren",
        "Đổi tên tệp…": "Datei umbenennen…",
        "Chuyển tệp tới…": "Datei bewegen nach…",
        "XML: đánh giá XPath…": "XML: XPath auswerten…",
        "Đánh giá XPath": "XPath auswerten",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Zum Beispiel: //bestellung/posten[2]/@nr · //*[@art='A'] · count(//posten)",
        "Đánh giá": "Auswerten",
        "XPath không đọc được: %@": "Dieser XPath ist nicht lesbar: %@",
        "XPath «%@» không khớp node nào": "XPath „%@“ traf auf keinen Knoten",
        "XPath «%@» — %d node": "XPath „%@“ — %d {one=Knoten|other=Knoten}",
        "XPath «%@»: %d node": "XPath „%@“: %d {one=Knoten|other=Knoten}",
        "Lưu tệp trước khi nhân bản.": "Sichern Sie die Datei, bevor Sie sie duplizieren.",
        "Không nhân bản được": "Duplizieren nicht möglich",
        "Đã nhân bản thành %@": "Dupliziert als %@",
        "Lưu tệp trước khi đổi tên.": "Sichern Sie die Datei, bevor Sie sie umbenennen.",
        "Đổi tên tệp": "Datei umbenennen",
        "Tên hiện tại: %@": "Aktueller Name: %@",
        "Đổi tên": "Umbenennen",
        "Tên tệp không hợp lệ": "Dieser Dateiname ist ungültig",
        "Đã có tệp tên %@ ở đó": "Dort gibt es bereits eine Datei namens %@",
        "Lưu tệp trước khi chuyển.": "Sichern Sie die Datei, bevor Sie sie bewegen.",
        "Chuyển tới": "Hierher bewegen",
        "Thư mục đích đã có tệp tên %@": "Der Zielordner enthält bereits eine Datei namens %@",
        "Không chuyển được tệp": "Die Datei konnte nicht bewegt werden",
        "Đã chuyển tới %@": "Bewegt nach %@",
        "Bảng mã:": "Zeichensatz:",
        "Xuống dòng:": "Zeilenenden:",
        "Riêng cho %@": "Nur für %@",
        "    %d — dùng TAB": "    %d — Tabulatoren",
        "    %d — dùng dấu cách": "    %d — Leerzeichen",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Eigene Regel entfernen, globale Einstellung nutzen",
        "%@: thụt lề %d %@": "%@: Einrückung %d %@",
        "TAB": "Tabulatoren",
        "dấu cách": "Leerzeichen",
        "Xuất": "Exportieren",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Ergebnisse als Text-Tab öffnen — mit ⌘S sichern",
        "Lượt tìm trước đó": "Frühere Suchen",
        "«%@» — %d kết quả": "„%@“ — %d {one=Treffer|other=Treffer}",
        "Kết quả tìm «%@»": "Suchergebnisse für „%@“",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Dateinamen filtern — z. B. *.csv;*.log (leer: jede Textdatei)",
        "Thư mục %@ không có file văn bản nào": "Der Ordner %@ enthält keine Textdateien",
        "Không tệp nào trong %@ khớp «%@»": "Keine Datei in %@ passt auf „%@“",
        "%d byte · %d dòng": "%d Bytes · %d {one=Zeile|other=Zeilen}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d Bytes · %d {one=Zeile|other=Zeilen} — zu groß, um Zeichen und Wörter zu zählen",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d Bytes · %d {one=Zeichen|other=Zeichen} · %d {one=Wort|other=Wörter} · %d {one=Zeile|other=Zeilen}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Dieses Dokument hat %d {one=Zeile|other=Zeilen}, %d Bytes. Geben Sie eine Zeilennummer, „Zeile,Spalte“ oder „@Byte“ ein.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "„%@“ ist nicht lesbar — geben Sie eine Zeilennummer, „Zeile,Spalte“ oder „@Byte“ ein",
    ]
}
