import Foundation

/// Bảng dịch tiếng Thuỵ Điển. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let sv: [String: String] = [
        "Bản đã lưu…": "Sparade versioner…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Det här dokumentet har aldrig sparats — ingen historik",
        "Chưa có bản đã lưu nào trước đó": "Inga tidigare sparade versioner",
        "Không đọc được bản ấy": "Det går inte att läsa den versionen",
        "Khôi phục bản đã lưu": "Återställ den sparade versionen",
        "XML: kiểm theo DTD/XSD…": "XML: validera mot DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Den här Mac-datorn saknar libxml2, så XSD-validering är inte tillgänglig.",
        "Chọn lược đồ XSD để kiểm": "Välj ett XSD-schema att validera mot",
        "Hợp lệ theo": "Giltig enligt",
        "Plugin chạy xong, không đổi gì": "Tillägget avslutades utan att ändra något",
        "Chưa cài plugin native nào": "Inga inbyggda tillägg är installerade",
        "Gỡ plugin này": "Ta bort det här tillägget",
        "Gỡ plugin này?": "Ta bort det här tillägget?",
        "Gỡ": "Ta bort",
        "Cài plugin native…": "Installera ett inbyggt tillägg…",
        "Mở thư mục plugin": "Öppna tilläggsmappen",
        "Chọn file .dylib của plugin native": "Välj tilläggets .dylib-fil",
        "Đã cài:": "Installerat:",
        "Đã gỡ:": "Borttaget:",
        "Plugin native…": "Inbyggda tillägg…",
        "Chỉ nhận file .dylib.": "Endast .dylib-filer godtas.",
        "Đã có một plugin trùng tên:": "Ett tillägg med samma namn är redan installerat:",
        "Không chép được plugin:": "Det går inte att kopiera tillägget:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Inbyggda tillägg finns bara i den direkta hämtningen, inte i App Store-versionen.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Hjälpprocessen för tillägg hittades inte.",
        "Không khởi động được tiến trình phụ:": "Det går inte att starta hjälpprocessen:",
        "Tiến trình plugin đã dừng giữa chừng.": "Tilläggets process stannade halvvägs.",
        "Plugin không trả lời kịp — đã dừng nó.": "Tillägget svarade inte i tid — det stoppades.",
        "Plugin trả lời sai giao thức:": "Tillägget svarade med ett felformat meddelande:",
        "Plugin báo lỗi:": "Tillägget rapporterade ett fel:",
        "Về GEditor": "Om GEditor",
        "Cài đặt…": "Inställningar…",
        "Thoát GEditor": "Avsluta GEditor",
        "File": "Arkiv",
        "Tab mới": "Ny flik",
        "Đóng tab": "Stäng fliken",
        "Tab kế": "Nästa flik",
        "Tab trước": "Föregående flik",
        "Tài liệu mới": "Nytt dokument",
        "Mở…": "Öppna…",
        "Mở thư mục làm Workspace…": "Öppna en mapp som arbetsyta…",
        "Mở gần đây": "Öppna senaste",
        "Lưu": "Spara",
        "Lưu thành…": "Spara som…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Ta bort blanksteg i radslut vid sparande",
        "Theo dõi file (tail -f)": "Följ filen (tail -f)",
        "In…": "Skriv ut…",
        "Mở lại tab vừa đóng": "Öppna den stängda fliken igen",
        "Chưa có file nào": "Inga filer",
        "Xoá danh sách": "Töm listan",
        "Edit": "Redigera",
        "Hoàn tác": "Ångra",
        "Làm lại": "Gör om",
        "Cắt": "Klipp ut",
        "Sao chép": "Kopiera",
        "Dán": "Klistra in",
        "Lịch sử clipboard…": "Urklippshistorik…",
        "Column Editor…": "Kolumnredigerare…",
        "Chọn lần kế tiếp": "Markera nästa träff",
        "Chọn tất cả": "Markera allt",
        "Nhân đôi dòng": "Duplicera raden",
        "Xóa dòng": "Radera raden",
        "Comment dòng": "Kommentera bort raden",
        "Chưa chép gì trong phiên này": "Inget har kopierats i den här sessionen",
        "Xoá lịch sử": "Rensa historiken",
        "Search": "Sök",
        "Tìm…": "Sök…",
        "Tìm và thay…": "Sök och ersätt…",
        "Tìm trong thư mục…": "Sök i en mapp…",
        "Thay trong thư mục…": "Ersätt i en mapp…",
        "Kết quả kế": "Nästa träff",
        "Kết quả trước": "Föregående träff",
        "Đi tới dòng…": "Gå till rad…",
        "Nhảy tới ngoặc khớp": "Gå till matchande parentes",
        "Đánh dấu mọi dòng khớp…": "Markera alla matchande rader…",
        "Đảo dấu": "Invertera markeringarna",
        "Bỏ mọi dấu": "Ta bort alla markeringar",
        "Chép dòng đã đánh dấu": "Kopiera markerade rader",
        "Xóa dòng đã đánh dấu": "Radera markerade rader",
        "Chỉ giữ dòng đã đánh dấu": "Behåll bara markerade rader",
        "Lines": "Rader",
        "Sắp xếp A→Z": "Sortera A→Ö",
        "Sắp xếp Z→A": "Sortera Ö→A",
        "Sắp xếp tự nhiên": "Naturlig sortering",
        "Khử trùng lặp": "Ta bort dubbletter",
        "Đảo thứ tự dòng": "Vänd radordningen",
        "Dời dòng lên": "Flytta raden uppåt",
        "Dời dòng xuống": "Flytta raden nedåt",
        "Ghép dòng": "Slå ihop rader",
        "Tách dòng theo độ dài…": "Dela rader efter längd…",
        "Tách dòng theo ký tự…": "Dela rader efter tecken…",
        "Xóa dòng rỗng": "Radera tomma rader",
        "Nén dòng trống liên tiếp": "Slå ihop rader av tomma rader",
        "Cắt khoảng trắng cuối dòng": "Ta bort blanksteg i radslut",
        "Tab → Space": "Tabb → mellanslag",
        "Space → Tab": "Mellanslag → tabb",
        "HOA": "VERSALER",
        "thường": "gemener",
        "Chữ Hoa Đầu Từ": "Stor Bokstav I Varje Ord",
        "Chữ hoa đầu câu": "Stor bokstav i meningens början",
        "Đảo hoa/thường": "vÄND gEMENER/vERSALER",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: välj blad…",
        "Xem dạng bảng / văn bản": "Växla mellan tabell- och textvy",
        "Xóa cột…": "Radera kolumn…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Validera data (antal kolumner · typer)",
        "Bàn làm sạch dữ liệu…": "Arbetsbänk för datarensning…",
        "Chạy công thức làm sạch…": "Kör ett rensningsrecept…",
        "Chuyển đổi…": "Konvertera…",
        "Đổi dấu phân tách…": "Byt avgränsare…",
        "Xuất sang JSON…": "Exportera till JSON…",
        "Format": "Format",
        "Bảng mã…": "Teckenkodning…",
        "Xuống dòng…": "Radslut…",
        "Chuẩn hóa Unicode…": "Normalisera Unicode…",
        "JSON: định dạng lại": "JSON: formatera",
        "JSON: thu gọn một dòng": "JSON: pressa ihop till en rad",
        "JSON: sắp xếp khóa": "JSON: sortera nycklar",
        "JSON: truy vấn JSONPath…": "JSON: JSONPath-fråga…",
        "CSV: truy vấn SQL…": "CSV: SQL-fråga…",
        "Truy vấn SQL": "SQL-fråga",
        "Đang chạy…": "Kör…",
        "Xuất ra tab mới": "Exportera till en ny flik",
        "Tài liệu rỗng — không có bảng để truy vấn": "Tomt dokument — ingen tabell att fråga",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Ingen CSV-tabell — första raden har bara en kolumn",
        "Không đọc được câu truy vấn": "Det går inte att läsa frågan",
        "Không kiểm được câu truy vấn": "Det går inte att kontrollera frågan",
        "Vàng (mặc định)": "Gul (standard)",
        "Xanh dương": "Blå",
        "Xanh lá": "Grön",
        "Vàng đất": "Ockra",
        "Tím": "Lila",
        "Hồng": "Rosa",
        "Xanh ngọc": "Turkos",
        "Cam": "Orange",
        "Xám lam": "Skiffer",
        "Văn bản": "Text",
        "Dãy số": "Talserie",
        "Dãy ngày": "Datumserie",
        "Chữ HOA (hex)": "VERSALER (hexadecimalt)",
        "Bắt đầu": "Början",
        "Bước": "Steg",
        "Đệm 0 tới": "Fyll ut med nollor till",
        "Hệ": "Bas",
        "Ngày đầu": "Första datum",
        "Định dạng": "Format",
        "Chèn": "Infoga",
        "Huỷ": "Avbryt",
        "Chuyển đổi định dạng": "Konvertera formatet",
        "Xem trước 5 hàng đầu": "Förhandsvisa de 5 första raderna",
        "Tạo tab mới": "Öppna i en ny flik",
        "Lưu ra file…": "Spara till en fil…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Resultatet öppnas i en ny, osparad flik. Ursprungsdokumentet lämnas orört.",
        "Chạy trên tài liệu này": "Kör på det här dokumentet",
        "Chạy trên thư mục…": "Kör på en mapp…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Hela receptet är ETT ångra-steg. Filen på hårddisken lämnas orörd tills du sparar.",
        "tắt": "av",
        "không thấy cột": "kolumnen hittades inte",
        "sẵn sàng": "klar",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "den fortsätter att uppta en processorkärna tills appen avslutas.",
        "Script không trả về gì": "Skriptet returnerade ingenting",
        "Không dựng được máy JavaScript": "Det går inte att skapa JavaScript-motorn",
        "Lỗi JavaScript không rõ": "Okänt JavaScript-fel",
        "Bảng": "Tabell",
        "Áp sắp xếp vào file": "Tillämpa sorteringen på filen",
        "Chuyển đổi ▾": "Konvertera ▾",
        "Xuất dòng khớp": "Exportera matchande rader",
        "Ẩn cột này": "Dölj den här kolumnen",
        "Đổi tên tiêu đề…": "Byt namn på rubriken…",
        "Chèn cột trống bên trái": "Infoga en tom kolumn till vänster",
        "Chèn cột trống bên phải": "Infoga en tom kolumn till höger",
        "Xóa cột này khỏi file…": "Radera den här kolumnen ur filen…",
        "Phải còn ít nhất một cột đang hiện": "Minst en kolumn måste förbli synlig",
        "Đang sắp xếp…": "Sorterar…",
        "Trở về thứ tự trong file": "Tillbaka till ordningen i filen",
        "trăm hàng đầu": "de första hundra raderna",
        "chọn cột": "välja kolumner",
        "đặt tên cột kết quả": "namnge en resultatkolumn",
        "lọc theo chữ": "filtrera på text",
        "ô rỗng": "tomma celler",
        "ghép điều kiện": "kombinera villkor",
        "đếm hàng": "räkna rader",
        "gộp nhóm": "gruppera och sammanfatta",
        "nhỏ nhất, lớn nhất": "minimum, maximum",
        "sắp xếp và cắt": "sortera och begränsa",
        "tên cột có dấu cách": "kolumnnamn med mellanslag",
        "Truy vấn bị dừng giữa chừng": "Frågan avbröts",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Stöds inte: JOIN · underfråga · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · fönsterfunktioner",
        "XML: định dạng lại": "XML: formatera",
        "XML: thu gọn một dòng": "XML: pressa ihop till en rad",
        "XML: kiểm cú pháp": "XML: kontrollera syntaxen",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: kontrollera dubblerade nycklar och indrag",
        "View": "Visa",
        "Ẩn/hiện sidebar (Function List)": "Visa/dölj sidofältet (funktionslistan)",
        "Ẩn/hiện bản đồ tài liệu": "Visa/dölj dokumentkartan",
        "Gấp / mở khối tại con nháy": "Fäll ihop / fäll ut blocket vid markören",
        "Gấp tất cả": "Fäll ihop allt",
        "Bỏ gấp tất cả": "Fäll ut allt",
        "Gấp theo cấp": "Fäll ihop efter nivå",
        "Cấp %d": "Nivå %d",
        "Đã gấp %d khối ở cấp %d": "%1$d {one=block ihopfällt|other=block ihopfällda} på nivå %2$d",
        "Tài liệu này chỉ sâu %d cấp": "Det här dokumentet är bara %d {one=nivå|other=nivåer} djupt",
        "mermaid: không đọc được bản kê": "mermaid: manifestet går inte att läsa",
        "Kiểm tra bản cập nhật…": "Sök efter uppdateringar…",
        "Kiểm tra bản cập nhật": "Sök efter uppdateringar",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store-versioner uppdateras via Mac App Store, inte via GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Det här bygget saknar signeringsnyckel för uppdateringar och kan därför inte söka efter dem.",
        "Phóng to chữ": "Förstora texten",
        "Thu nhỏ chữ": "Förminska texten",
        "Cỡ chữ gốc": "Verklig storlek",
        "Chia đôi theo chiều dọc": "Dela lodrätt",
        "Chia đôi theo chiều ngang": "Dela vågrätt",
        "Bỏ chia đôi": "Stäng delningen",
        "Mở tab này ở nửa kia": "Öppna den här fliken i den andra rutan",
        "Nhảy sang nửa kia": "Gå till den andra rutan",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Radbrytning (av / fönster / kolumn)",
        "Ngắt dòng tại cột…": "Bryt vid kolumn…",
        "Đánh dấu dòng này": "Markera den här raden",
        "Dấu kế tiếp": "Nästa markering",
        "Dấu trước đó": "Föregående markering",
        "Màu đánh dấu…": "Färg på markeringar…",
        "Hiện tất cả ký tự ẩn": "Visa alla osynliga tecken",
        "  Khoảng trắng": "  Mellanslag",
        "  Tab": "  Tabbar",
        "  Xuống dòng": "  Radslut",
        "  NBSP · zero-width · điều khiển": "  NBSP · nollbredd · styrtecken",
        "Xem nhị phân": "Binärvy",
        "Chế độ CSV (tô màu theo cột)": "CSV-läge (kolumner i färg)",
        "Macro": "Makro",
        "Bắt đầu / dừng ghi": "Starta / stoppa inspelningen",
        "Phát lại": "Spela upp",
        "Phát nhiều lần…": "Spela upp flera gånger…",
        "Phát đến cuối tài liệu": "Spela upp till dokumentets slut",
        "Chạy trên mọi tab": "Kör på alla flikar",
        "Hủy macro đang chạy": "Avbryt makrot som körs",
        "Lưu macro…": "Spara makrot…",
        "Macro đã lưu…": "Sparade makron…",
        "Help": "Hjälp",
        "Trợ giúp GEditor": "GEditor Hjälp",
        "Giới thiệu tính năng": "Funktionsöversikt",
        "Di cư từ Notepad++": "Byta från Notepad++",
        "Tìm": "Sök",
        "Thay bằng": "Ersätt med",
        "Kế": "Nästa",
        "Trước": "Föregående",
        "Đếm": "Räkna",
        "Đóng": "Stäng",
        "Kiểm theo JSON Schema…": "Validera mot ett JSON-schema…",
        "Chọn tệp JSON Schema": "Välj en JSON-schemafil",
        "Không thấy lỗi nào theo schema này.": "Inga problem hittades enligt det här schemat.",
        "JSON Schema": "JSON-schema",
        "Kiểm cú pháp đồ thị": "Kontrollera grafens syntax",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Grafformatet kändes inte igen — det krävs ändelsen .dot, .gv, .cypher, .ttl eller .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Inga %@-syntaxfel hittades (kontrollen är inte uttömmande).",
        "Cú pháp %@": "%@-syntax",
        "không phải một đối tượng JSON": "är inte ett JSON-objekt",
        "Khai phá văn bản (n-gram, TF-IDF)": "Textutvinning (n-gram, TF-IDF)",
        "Tài liệu rỗng.": "Dokumentet är tomt.",
        "Không rút được từ khoá nào.": "Inget nyckelord kunde utvinnas.",
        "Từ khoá": "Nyckelord",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=nyckelord|other=nyckelord} · %d {one=token|other=tokens} · %d {one=dokument|other=dokument}",
        "Tô lên tài liệu": "Markera i dokumentet",
        "Đánh dấu entity từ danh sách…": "Markera entiteter från en lista…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Välj en entitetslista (CSV eller JSON)",
        "Không đọc được danh sách entity.": "Det går inte att läsa entitetslistan.",
        "Danh sách entity rỗng.": "Entitetslistan är tom.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Inga entiteter hittades i dokumentet (%d inlästa).",
        "%d lần xuất hiện · %@": "%d {one=förekomst|other=förekomster} · %@",
        "Chuyển đổi tri thức…": "Konvertera kunskap…",
        "Chuyển đổi: %@ → %@": "Konvertering: %@ → %@",
        "Không chuyển đổi được.": "Det gick inte att konvertera.",
        "Xem trước cắt chunk…": "Förhandsvisning av styckningen…",
        "Cỡ cố định 800B, chồng 100B": "Fast storlek 800 B, överlapp 100 B",
        "Theo câu (≤ 800B)": "Per mening (≤ 800 B)",
        "Theo heading Markdown": "Per Markdown-rubrik",
        "Tài liệu rỗng — không có chunk nào.": "Tomt dokument — inga stycken.",
        "%d chunk · trung bình %d B · %@": "%d {one=stycke|other=stycken} · i snitt %d B · %@",
        "Xuất JSONL": "Exportera JSONL",
        "Chunk JSONL": "Styckenas JSONL",
        "Mở triple/edge dạng bảng": "Öppna tripplar/kanter som tabell",
        "Bảng triple": "Trippeltabell",
        "Tài liệu này không có dòng triple nào.": "Det här dokumentet har ingen trippelrad.",
        "Không đọc được triple nào — dòng %d: %@": "Ingen trippel kunde läsas — rad %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%1$d {one=trippel lästes|other=tripplar lästes} · %2$d {one=felaktig rad|other=felaktiga rader} hoppades över (den första: rad %3$d)",
        "Trùng lặp mờ theo cột…": "Luddiga dubbletter per kolumn…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Luddiga dubbletter — kolumnen «%1$@»: %2$d {one=kandidatgrupp|other=kandidatgrupper}",
        "Gộp": "Slå samman",
        "Giống": "Träff",
        "Các giá trị trong cụm": "Värden i gruppen",
        "Gộp về": "Slå samman till",
        "Gộp các cụm đã chọn": "Slå samman de valda grupperna",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Ingen grupp är vald — att trycka på «Slå samman» ändrar INGENTING. Appen slår aldrig samman av sig själv.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=grupp vald|other=grupper valda} · %d {one=rad kommer|other=rader kommer} att ändras · ETT ångra-steg",
        "Không quét được cột này.": "Det gick inte att söka igenom den här kolumnen.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Kolumnen «%@» har inga grupper med luddiga dubbletter.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Ingen grupp slogs samman — dokumentet är oförändrat.",
        "Khử trùng lặp mờ · cột %@": "Luddig dubblettrensning · kolumnen %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=grupp sammanslagen|other=grupper sammanslagna} · %d {one=cell ändrad|other=celler ändrade}",
        "Báo cáo làm sạch": "Rensningsrapport",
        "# Báo cáo làm sạch — %@\n\n": "# Rensningsrapport — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Tillämpat (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Inget steg har tillämpats._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Dataprofil\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d {one=kolumn|other=kolumner} · %2$d {one=rad|other=rader} · genomsökt på %3$.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Kolumn | Typ | Tomma | Unika | Min | Max | Medel |\n",
        "\n### Giá trị bất thường\n\n": "\n### Avvikande värden\n\n",
        "hàng %d: %@": "rad %d: %@",
        "- cột «%@» — %d ô: %@\n": "- kolumnen «%1$@» — %2$d {one=cell|other=celler}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Återstår (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Inga observationer kvar._\n",
        "- cột «%@»: %@\n": "- kolumnen «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Ta bort blanksteg vid sparande",
        "Chuẩn hóa xuống dòng": "Normalisera radsluten",
        "trước đó": "föregående",
        "Không mở lại được thư mục «%@» của phiên trước": "Det gick inte att öppna mappen «%@» från den förra sessionen igen",
        " (và %d file khác)": " (och %d {one=fil|other=filer} till)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "Det gick inte att öppna %d {one=flik|other=flikar} igen: %@%@ — filerna finns inte kvar på sin gamla plats.",
        "Không đọc được nội dung từ ống dẫn": "Det gick inte att läsa indata från röret",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Blanksteg i radslut tas bort vid varje sparande",
        "Không cắt khoảng trắng khi lưu nữa": "Blanksteg tas inte längre bort vid sparande",
        "Chưa đặt tên.txt": "Namnlös.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Att konvertera teckenkodningen gör att tecken går förlorade",
        "Vẫn lưu": "Spara ändå",
        "Tài liệu có thay đổi chưa lưu": "Dokumentet har osparade ändringar",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Att stänga utan att spara kastar bort dem.",
        "Bỏ thay đổi": "Kasta ändringarna",
        "Đi tới dòng": "Gå till rad",
        "Tài liệu có %d dòng.": "Dokumentet har %d {one=rad|other=rader}.",
        "Số dòng": "Radnummer",
        "Đi tới": "Gå",
        "Diễn giải lại theo…": "Tolka om som…",
        "Chuyển đổi sang…": "Konvertera till…",
        "Không diễn giải lại được": "Det gick inte att tolka om",
        "Bảng mã %@ không chứa hết ký tự": "%@ kan inte återge alla tecken",
        "Vẫn chọn": "Välj ändå",
        "Cột %d": "Kolumn %d",
        "Cột %d: %@": "Kolumn %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Dolda kolumner: %@ (%d) — återställ dem från kontextmenyn på rubrikraden",
        "Hiện lại: %@": "Visa igen: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Kolumnen %@ dolde — den ligger kvar orörd i filen",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Sorterad efter %@ %@ · endast visning",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Sorterad: %@ %@ (endast visning)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ rader matchar — söker vidare…",
        "%d / %d dòng khớp": "%d / %d {one=rad matchar|other=rader matchar}",
        "Không tìm thấy lỗi trong %d hàng": "Inga problem hittades i %d {one=rad|other=rader}",
        "%d hàng lệch số cột": "%d {one=rad|other=rader} med fel antal kolumner",
        "%d ô sai kiểu dữ liệu": "%d {one=cell|other=celler} med fel datatyp",
        " (đã dừng ở %d lỗi đầu)": " (stannade vid de %d {one=första problemet|other=första problemen})",
        "   —   kiểu nhận ra: ": "   —   igenkända typer: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Rad %1$d, kolumnen %2$@: «%3$@» är inte %4$@",
        "Column Editor — %d dòng": "Kolumnredigerare — %d {one=rad|other=rader}",
        "Phát hiện": "Observationer",
        "Hồ sơ dữ liệu": "Dataprofil",
        "Hồ sơ dữ liệu — đang quét…": "Dataprofil — söker igenom…",
        "Lưu công thức…": "Spara receptet…",
        "Xuất báo cáo": "Exportera rapporten",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Ingen grupp har tillämpats · varje grupp är ett ångra-steg",
        "quá nhiều giá trị": "för många värden",
        "hay gặp: ": "vanligast: ",
        "Giá trị điền vào ô thiếu": "Värde att fylla tomma celler med",
        "Áp dụng": "Tillämpa",
        "Không dựng được bản xem trước": "Det gick inte att bygga en förhandsvisning",
        "· giữ nguyên, không đọc được ·": "· lämnat som det är, går inte att tyda ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Konvertera kolumnen till ISO 8601 (ÅÅÅÅ-MM-DD)",
        "Quy ước số cho cả cột": "Talkonvention för hela kolumnen",
        "Làm gì với ô thiếu": "Vad som ska göras med tomma celler",
        "Chuẩn hóa về ISO 8601": "Normalisera till ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Läs tvetydiga celler med DAGEN först (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Läs tvetydiga celler med MÅNADEN först (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Hoppa över tvetydiga celler, rätta bara de säkra",
        "Về Việt/Âu (1.234,56)": "Till vietnamesiskt/europeiskt (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Till angloamerikanskt (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Till angloamerikanskt, utan tusentalsavgränsare (1234.56)",
        "Điền một giá trị mặc định…": "Fyll med ett standardvärde…",
        "Điền xuôi — lấy giá trị phía trên": "Fyll nedåt — ta värdet ovanför",
        "Điền ngược — lấy giá trị phía dưới": "Fyll uppåt — ta värdet nedanför",
        "Xóa hàng có ô thiếu ở cột này": "Radera rader med tom cell i den här kolumnen",
        "Cắt khoảng trắng hai đầu": "Ta bort blanksteg i båda ändarna",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Ta bort i båda ändarna och pressa ihop blanksteg inuti",
        "Pivot…": "Pivottabell…",
        "Nguồn…": "Källor…",
        "Pivot — gộp theo cột": "Pivottabell — gruppera efter kolumn",
        "Hàng (gộp nhóm)": "Rader (gruppering)",
        "Giá trị": "Värden",
        "+ Hàng": "+ Rad",
        "+ Giá trị": "+ Värde",
        "Xoá hết": "Rensa allt",
        "Đưa vào ô truy vấn": "Lägg i frågefältet",
        "Chọn cột để dựng câu truy vấn.": "Välj kolumner för att bygga frågan.",
        "Không đọc được tên cột của bảng này.": "Det gick inte att läsa kolumnnamnen i den här tabellen.",
        "Nguồn dữ liệu của truy vấn": "Frågans datakällor",
        "«%@» — tài liệu đang mở": "«%@» — det öppna dokumentet",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ filen har ändrats sedan den registrerades",
        "Thêm file…": "Lägg till fil…",
        "Bỏ hết": "Ta bort alla",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Det gick inte att härleda ett tabellnamn ur «%@» — byt namn på filen.",
        "Tổng": "Summa",
        "Trung bình": "Medelvärde",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Max",
        "Đếm khác nhau": "Antal unika",
        "Biểu đồ": "Diagram",
        "Xuất PNG": "Exportera PNG",
        "Xuất SVG": "Exportera SVG",
        "Bảng này không có cột số nào để vẽ.": "Den här tabellen har ingen numerisk kolumn att rita.",
        "Không dựng được ảnh PNG.": "Det gick inte att bygga PNG-bilden.",
        "Kết quả truy vấn": "Frågeresultat",
        "Đã lưu %@": "%@ sparad",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "%1$@-diagram för «%2$@» — %3$d {one=punkt|other=punkter}, värden från %4$@ till %5$@",
        "Cột": "Stapel",
        "Đường": "Linje",
        "Phân bố": "Histogram",
        "Phân tán": "Punkt",
        "Hộp": "Låda",
        "CSV: chất lượng dữ liệu…": "CSV: datakvalitet…",
        "Chất lượng dữ liệu": "Datakvalitet",
        "Xuất vi phạm ra tab mới": "Exportera överträdelserna till en ny flik",
        "Mức": "Nivå",
        "Luật": "Regel",
        "Vi phạm": "Överträdelser",
        "Tỷ lệ": "Andel",
        "đạt": "godkänd",
        "lỗi": "fel",
        "cảnh báo": "varning",
        "hỏng": "trasig",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=överträdande rad markerad|other=överträdande rader markerade}",
        "Xu hướng": "Utveckling",
        "Lúc chấm": "Bedömd",
        "Số hàng": "Rader",
        "Lệch": "Skillnad",
        "Luật trượt": "Underkända regler",
        "Điểm chất lượng": "Kvalitetspoäng",
        "Điểm theo thời gian": "Poäng över tid",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Ingen historik ännu — varje bedömning lägger till ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "en rad i filen «.history.jsonl» bredvid reglerna.",
        "%d mốc trong lịch sử": "%d {one=punkt|other=punkter} i historiken",
        " · %d dòng KHÔNG đọc được": " · %d {one=rad GÅR INTE ATT LÄSA|other=rader GÅR INTE ATT LÄSA}",
        " · chọn hai dòng để so": " · välj två rader att jämföra",
        "điểm %+.1f": "poäng %+.1f",
        "không chiều nào tụt": "ingen dimension sjönk",
        "tụt: ": "sjönk: ",
        "%d luật mới trượt: %@": "%d {one=nyligen underkänd regel|other=nyligen underkända regler}: %@",
        "số hàng %+d": "rader %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (och %d {one=varning|other=varningar} till på fliken Utveckling)",
        "Không sửa tự động được: ": "Ingen automatisk rättning: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Öppnar rätt verktyg i rensningsbänken och bedömer sedan om direkt.",
        "Xử lý giá trị thiếu…": "Hantera saknade värden…",
        "Chuẩn hóa ngày…": "Normalisera datum…",
        "Khử trùng lặp…": "Ta bort dubbletter…",
        "Thay thế…": "Ersätt…",
        "Xem các dòng sai": "Visa de felaktiga raderna",
        "Không tìm thấy cột «%@» trong bảng này.": "Kolumnen «%@» finns inte i den här tabellen.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Dubbletterna borttagna — «%@» är nu unik. Poäng: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Dubbletterna borttagna, men «%1$@» har fortfarande %2$d {one=upprepad rad|other=upprepade rader} (tidigare: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "de raderna delar NYCKEL men inte hela raden, så du måste titta och välja ",
        "giữ hàng nào.": "vilken du behåller.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Det gick inte att läsa något värde som bryter mot den här regeln.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {one=felaktigt värde|other=felaktiga värden} i kolumnen «%2$@» — fyll i Ersätt och tryck på Förhandsvisa",
        "Đã chấm lại: %.0f/100": "Bedömd på nytt: %.0f/100",
        "Xem trước báo cáo": "Förhandsvisning av rapporten",
        "Tham số…": "Parametrar…",
        "Xuất HTML…": "Exportera HTML…",
        "In / PDF…": "Skriv ut / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=block kördes|other=block kördes} · %d {one=block MISSLYCKADES|other=block MISSLYCKADES}",
        "%d khối chạy được": "%d block kördes",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · FÖRÅLDRADE DATA — källfilen har ändrats; bygg om",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Rapportförhandsvisning kräver ett .%@-dokument",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Ingen datakälla hittades — deklarera «source: fil.csv» i frontmattern.",
        "Không dựng được báo cáo.": "Det gick inte att bygga rapporten.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Den här rapporten deklarerar ingen parameter i frontmattern.",
        "Tham số báo cáo": "Rapportparametrar",
        "Dựng lại": "Bygg om",
        "Đã xuất %@": "%@ exporterad",
        "Báo cáo: xem trước": "Rapport: förhandsvisning",
        "Báo cáo: sinh loạt…": "Rapport: satsvis generering…",
        "không phải tài liệu .greport.md": "är inget .greport.md-dokument",
        "không phân tích được báo cáo": "det gick inte att tolka rapporten",
        "không tìm được dữ liệu nguồn": "det gick inte att hitta källdata",
        "không đọc được danh sách tham số": "det gick inte att läsa parameterlistan",
        "Sinh loạt cần tài liệu đuôi .%@": "Satsvis generering kräver ett .%@-dokument",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Välj en parameterlista (CSV eller JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Välj en mapp för %d {one=rapport|other=rapporter}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "saknade parametrar ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "pekar på själva källfilen — vägrar skriva över",
        "%d khối HỎNG": "%d block MISSLYCKADES",
        "Sinh loạt xong: %d tệp · %d hỏng": "Satsen klar: %d {one=fil|other=filer} · %d misslyckade",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=parameteruppsättning kunde|other=parameteruppsättningar kunde} inte byggas — se sammanfattningen",
        "Sơ đồ Mermaid: xem trước": "Mermaid-diagram: förhandsvisning",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid-diagram: infoga mall…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid-diagram: formatera om",
        "Nền trong suốt": "Genomskinlig bakgrund",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Den här Mac-datorn kan inte omvandla diagrammet till PNG — macOS 13 krävs. SVG-export fungerar fortfarande.",
        "Lưu PNG %@…": "Spara PNG %@…",
        "Lưu SVG…": "Spara SVG…",
        "Chép ảnh vào clipboard": "Kopiera bilden till urklipp",
        "Màu thương hiệu…": "Varumärkesfärger…",
        "Màu thương hiệu cho sơ đồ": "Varumärkesfärger för diagram",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Varje fält är en färg av typen #rrggbb. Sparas i «themes/mermaid-brand.json» — går att kopiera till en annan Mac.",
        "Màu chính": "Huvudfärg",
        "Chữ trên nút": "Text på noder",
        "Viền": "Ram",
        "Đường nối": "Länkar",
        "Nền khi xuất ảnh": "Bakgrund vid export",
        "Lưu và chèn %%{init}%% vào tài liệu": "Spara och infoga %%{init}%% i dokumentet",
        "Đã lưu màu thương hiệu": "Varumärkesfärgerna sparade",
        "Đã chép ảnh sơ đồ vào clipboard": "Diagrambilden kopierad till urklipp",
        "Đã lưu %@ — %@": "%@ sparad — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Det här diagrammet har redan ett %%{init}%%-direktiv — ditt lämnas orört.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% infogat — diagrammet bär nu sina egna färger",
        "Chèn màu thương hiệu vào sơ đồ": "Infoga varumärkesfärgerna i diagrammet",
        "Định dạng sơ đồ Mermaid": "Formatera om Mermaid-diagrammet",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Diagramkällan är redan städad — inget att ändra",
        "Đã định dạng lại sơ đồ": "Diagrammet omformaterat",
        "Đã định dạng lại %d sơ đồ": "%d {one=diagram omformaterat|other=diagram omformaterade}",
        "Thư viện mẫu sơ đồ": "Bibliotek med diagrammallar",
        "Mẫu sơ đồ đầy đủ": "Fullständiga diagrammallar",
        "Mẩu cú pháp": "Syntaxfragment",
        "Đang soạn: %@": "Redigeras: %@",
        "Đã chèn mẫu «%@»": "Mallen «%@» infogad",
        "Tài liệu đang ở chế độ chỉ đọc.": "Det här dokumentet är skrivskyddat.",
        "Sơ đồ Mermaid": "Mermaid-diagram",
        "Tài liệu chưa có khối mermaid nào.": "Det här dokumentet har inget mermaid-block.",
        "Thương hiệu": "Varumärke",
        "Xuất…": "Exportera…",
        "Chưa có sơ đồ nào": "Inga diagram ännu",
        "%d sơ đồ · %@": "%d diagram · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d diagram MISSLYCKADES — diagram %3$d%4$@",
        ", dòng %d": ", rad %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Det här dokumentet har inget ```mermaid-block och är inte heller en .mmd-fil.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Inget diagram har ritats färdigt ännu.",
        "Không tìm thấy «%@» trong mã sơ đồ": "«%@» hittades inte i diagramkällan",
        "không dựng được hàng rào chặn mạng cho WKWebView": "det gick inte att bygga nätverksspärren för WKWebView",
        "Luật kết hợp": "Associationsregler",
        "Mỗi dòng một giỏ": "En korg per rad",
        "Hai cột: mã · item": "Två kolumner: id · artikel",
        "Dạng dữ liệu giao dịch": "Transaktionsdatats form",
        "Cột giỏ hàng hoặc mã giao dịch": "Korgkolumn eller kolumn med transaktions-id",
        "Cột item": "Artikelkolumn",
        "Ký tự phân tách item": "Avgränsartecken för artiklar",
        "Support tối thiểu, phần trăm": "Minsta support, procent",
        "Confidence tối thiểu, phần trăm": "Minsta confidence, procent",
        "Tách bởi:": "Avgränsat av:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "Tabell över associationsregler",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Obs",
        "%d giao dịch · %d item · %d luật": "%d {one=transaktion|other=transaktioner} · %d {one=artikel|other=artiklar} · %d {one=regel|other=regler}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — ingen regel nådde trösklarna; sänk support eller confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — STOPPADES I FÖRTID, tabellen är OFULLSTÄNDIG",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transaktion innehåller|other=transaktioner innehåller} båda sidorna",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Tvåkolumnsformen kräver två OLIKA kolumner.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%1$d {one=rad markerad|other=rader markerade} i %2$d {one=transaktion|other=transaktioner} som innehåller «%3$@»",
        "CSV: luật kết hợp…": "CSV: associationsregler…",
        "Khai phá theo nhóm": "Gruppvis utvinning",
        "Cột nhóm": "Grupperingskolumn",
        "Cột giá trị": "Värdekolumn",
        "Cột thứ hai cho tương quan": "Andra kolumnen för korrelationen",
        "Cách xếp hạng": "Rangordningssätt",
        "Nhóm theo:": "Gruppera efter:",
        "Giá trị:": "Värde:",
        "Xếp theo:": "Rangordna efter:",
        "Bảng xếp hạng nhóm": "Tabell över gruppernas rangordning",
        "Nhóm": "Grupp",
        "Hàng": "Rader",
        "Hàng rào riêng": "Egen tröskel",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r-skillnad",
        "Ghi chú": "Anteckning",
        "không đo được": "går inte att mäta",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=grupp|other=grupper} · samlad referenskorrelation %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GRUPP BORTVALD|other=GRUPPER BORTVALDA}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Den här tabellen har ingen textkolumn att gruppera efter.",
        "Bảng này không có cột số nào để khai phá.": "Den här tabellen har ingen numerisk kolumn att utvinna ur.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%1$d {one=rad|other=rader} i gruppen «%2$@» {one=markerad|other=markerade}",
        "CSV: khai phá theo nhóm…": "CSV: gruppvis utvinning…",
        "\u{2194}": "↔",
        "Dự báo": "Prognos",
        "Cột giá trị theo thời gian": "Värdekolumn över tid",
        "Mô hình dự báo": "Prognosmodell",
        "Số kỳ dự báo": "Antal perioder att prognosticera",
        "Kết luận so với baseline": "Utlåtande mot referensmodellerna",
        "Mô hình:": "Modell:",
        "Số kỳ:": "Perioder:",
        "Chu kỳ:": "Säsong:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Säsongsperiod; lämna tomt för att upptäcka automatiskt",
        "Bảng giá trị dự báo": "Tabell över prognosticerade värden",
        "Kỳ": "Period",
        "Dải 80%": "80 %-band",
        "Dải 95%": "95 %-band",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "går inte att beräkna",
        "Bảng này không có cột số nào để dự báo.": "Den här tabellen har ingen numerisk kolumn att prognosticera.",
        "Không dựng được dự báo cho cột này.": "Det gick inte att bygga en prognos för den här kolumnen.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Kolumnen «%1$@» har bara %2$d {one=numeriskt värde|other=numeriska värden} — minst 4 krävs för en prognos.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Serien läses i filens radordning — utan omsortering och utan att härleda någon tidskolumn.\n",
        "Sai số huấn luyện": "Träningsfel",
        "CSV: dự báo chuỗi thời gian…": "CSV: tidsserieprognos…",
        "Holt-Winters cộng": "Holt-Winters additiv",
        "Holt-Winters nhân": "Holt-Winters multiplikativ",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Kolumner som går in i klustringen",
        "Đường cong WCSS": "WCSS-kurva",
        "Phân cụm": "Kluster",
        "Chuẩn hoá:": "Skalning:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Välj minst en kolumn.",
        "Không đủ dữ liệu để dựng đường cong.": "För lite data för att bygga kurvan.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Armbågen antyder k = %d. WCSS sjunker ALLTID när k växer, så det här är ett sätt att läsa diagrammet och inte ett statistiskt kriterium — titta på kurvan och bedöm om knäcken är tydlig.",
        "WCSS theo k": "WCSS efter k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k-avståndet antyder eps = %1$@ (minPts är som standard 2 × antalet kolumner = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Avstånd till den k:te grannen",
        "Cần ít nhất 2 cột số để phân cụm.": "Klustring kräver minst 2 numeriska kolumner.",
        "Cụm theo %@ và %@": "Kluster efter %@ och %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — klustren hittades i %d {one=dimension|other=dimensioner}; diagrammet visar bara de 2 första",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# brus (cluster_id = -1): %d {one=rad|other=rader}\n",
        "CSV: phân cụm…": "CSV: klustring…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Klustercentra (ursprungliga enheter) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Korrelationsmatris",
        "Phương pháp tương quan": "Korrelationsmetod",
        "Tương quan không hàm ý nhân quả.": "Korrelation innebär inte orsakssamband.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Starkaste paret: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klicka på en cell för att se ett punktdiagram.",
        "Không cặp nào đo được.": "Inget par går att mäta.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ över %4$d {one=rad|other=rader}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Korrelation kräver minst 2 numeriska kolumner.",
        "Không đọc được cột «%@».": "Det går inte att läsa kolumnen «%@».",
        "CSV: ma trận tương quan…": "CSV: korrelationsmatris…",
        "Bất thường": "Avvikelser",
        "Danh sách bất thường": "Lista över avvikelser",
        "Cột:": "Kolumn:",
        "Cột số cần xét": "Numerisk kolumn att undersöka",
        "Cách:": "Metod:",
        "Phương pháp phát hiện": "Upptäcktsmetod",
        "Phương pháp đã dùng": "Använd metod",
        "Ngưỡng": "Tröskel",
        "Đánh dấu": "Markera",
        "Xuất tab mới": "Exportera till en ny flik",
        "Dòng": "Rad",
        "Điểm": "Poäng",
        "Vì sao": "Varför",
        "nhẹ": "lindrig",
        "vừa": "måttlig",
        "nặng": "allvarlig",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=rad|other=rader} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Den här tabellen har ingen numerisk kolumn att leta avvikelser i.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=avvikande rad markerad|other=avvikande rader markerade}",
        "CSV: tìm bất thường…": "CSV: leta avvikelser…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d {one=regel, GODKÄND|other=regler, alla GODKÄNDA} · %2$d {one=rad|other=rader} · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d {one=fel|other=fel} · %2$d {one=varning|other=varningar} över %3$d {one=regel|other=regler} · %4$d {one=rad|other=rader} · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Spara dokumentet först — kvalitetsreglerna ligger bredvid datafilen.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Ingen regeluppsättning ännu. Skapa filen %@ och öppna igen.",
        "Lịch sử": "Historik",
        "Câu đã lưu": "Sparade frågor",
        "Lưu câu này…": "Spara den här frågan…",
        "Lưu câu truy vấn": "Spara frågan",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Ge den ett namn så du hittar den senare. Samma namn skriver över.",
        "Ví dụ: Doanh thu theo tỉnh": "Till exempel: Intäkter per län",
        "Chưa nhập giá trị cho tham số: %@": "Inget värde angavs för parametern: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Tillägget har ändrats sedan du godkände det — GEditor vägrar köra det",
        "Chạy plugin chưa duyệt?": "Köra ett icke godkänt tillägg?",
        "Tôi tin file này — chạy": "Jag litar på den här filen — kör",
        "KHÔNG có chữ ký": "OSIGNERAT",
        "Chữ ký: %@": "Signatur: %@",
        "Đường dẫn: %@": "Sökväg: %@",
        "Thay": "Ersätt",
        "Thay tất cả": "Ersätt alla",
        "Chuỗi thuần": "Ren text",
        "Extended (\\n \\t \\xNN)": "Utökad (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Reguljärt uttryck",
        "Phân biệt hoa thường": "Skilj på versaler och gemener",
        "Cả từ": "Helt ord",
        "Không có kết quả": "Inga resultat",
        "Thử biểu thức chính quy…": "Pröva ett reguljärt uttryck…",
        "Chế độ Log (tô theo mức)": "Loggläge (färg efter nivå)",
        "Lọc log theo mức…": "Filtrera loggen efter nivå…",
        "Chạy trên cả thư mục…": "Kör på hela mappen…",
        "Lọc qua lệnh ngoài…": "Filtrera genom ett externt kommando…",
        "Script…": "Skript…",
        "Gói mở rộng…": "Tilläggspaket…",
        "Cửa sổ mới": "Nytt fönster",
        "Tách tab ra cửa sổ mới": "Lossa fliken till ett nytt fönster",
        "Chưa mở thư mục nào": "Ingen mapp är öppnad",
        "Tìm file trong thư mục": "Sök efter en fil i mappen",
        "Lọc theo tên": "Filtrera på namn",
        "File mới…": "Ny fil…",
        "Thư mục mới…": "Ny mapp…",
        "Đổi tên…": "Byt namn…",
        "Chuyển vào Thùng rác": "Flytta till papperskorgen",
        "Hiện trong Finder": "Visa i Finder",
        "Đang đọc cấu trúc tài liệu…": "Läser dokumentets struktur…",
        "file này không có hàm nào": "den här filen har inga funktioner",
        "Không có gì khớp": "Inga träffar",
        "Văn bản thuần": "Ren text",
        "🔒 Chỉ đọc": "🔒 Skrivskyddad",
        "Đang theo dõi": "Följs",
        "ngắt tại cột": "brytning vid kolumn",
        "Cú pháp": "Syntax",
        "Bấm để chèn vào ô truy vấn": "Klicka för att infoga i frågan",
        "truy vấn không hợp lệ": "ogiltig fråga",
        "khóa `ten` ở gốc": "nyckeln «namn» i roten",
        "khóa có dấu cách": "nyckel med mellanslag",
        "phần tử đầu": "första elementet",
        "mọi phần tử": "alla element",
        "lát cắt": "utsnitt",
        "hợp nhiều chỉ số": "union av index",
        "mọi khóa `gia` ở mọi tầng": "alla nycklar «pris» på alla nivåer",
        "mọi nút": "alla noder",
        "lọc theo số": "filtrera på tal",
        "lọc theo có mặt": "filtrera på förekomst",
        "Tới lỗi đầu tiên": "Till första felet",
        "Cột doanh_thu là số": "Kolumnen intäkt är numerisk",
        "lọc…": "filtrera…",
        "Hủy": "Avbryt",
        "Thực hiện thay": "Utför ersättningen",
        "xem trước": "förhandsvisning",
        "tương tác": "interaktivt",
        "Soạn thảo": "Redigera",
        "Giao diện": "Gränssnitt",
        "Phím tắt": "Tangentbordsgenvägar",
        "Cỡ chữ": "Textstorlek",
        "Bề rộng TAB": "Tabbredd",
        "Thụt lề bằng TAB": "Indrag med tabbar",
        "Tự động thụt lề khi xuống dòng": "Dra in automatiskt vid ny rad",
        "Tô mọi kết quả tìm kiếm": "Framhäv alla sökträffar",
        "Chuẩn hóa về NFC khi lưu": "Normalisera till NFC vid sparande",
        "Ngôn ngữ": "Språk",
        "Nền": "Utseende",
        "Theo hệ thống": "Som systemet",
        "Sáng": "Ljust",
        "Tối": "Mörkt",
        "Theme": "Tema",
        "Dùng preset Notepad++": "Använd Notepad++-uppsättningen",
        "Về phím mặc định": "Tillbaka till standardtangenterna",
        "Mở file cấu hình": "Öppna konfigurationsfilen",
        "Xuất theme hiện tại": "Exportera det aktuella temat",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Språkbytet slår igenom helt vid nästa start.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Standardtangenterna kommer tillbaka vid nästa start.",
        "Xem trước Markdown": "Markdown-förhandsvisning",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Förhandsvisningen använder systemets Markdown-motor: ännu inga tabeller och ingen färgläggning av kodblock.",
        "Thử biểu thức chính quy": "Pröva ett reguljärt uttryck",
        "Biểu thức": "Uttryck",
        "Văn bản thử": "Testtext",
        "Kết quả": "Resultat",
        "Kết quả khớp": "Träffar",
        "Biểu thức này làm gì": "Vad det här uttrycket gör",
        "Giải thích biểu thức": "Förklara uttrycket",
        "Chế độ tìm kiếm": "Sökläge",
        "Kết quả tìm kiếm": "Sökresultat",
        "Không khớp chỗ nào": "Inga träffar",
        " (đã cắt bớt)": " (avkortat)",
        "Bản đồ tài liệu": "Dokumentkarta",
        "Thanh tab": "Flikfält",
        "Hàng tiêu đề cột": "Rubrikrad för kolumnerna",
        "Không có cột nào": "Inga kolumner",
        "Cây thư mục workspace": "Arbetsytans träd",
        "Danh sách hàm và lớp": "Lista över funktioner och klasser",
        "Kết quả tìm trong thư mục": "Sökresultat i mappen",
        "Bảng dữ liệu CSV": "CSV-datatabell",
        "Bàn làm sạch dữ liệu": "Arbetsbänk för datarensning",
        "Truy vấn JSONPath": "JSONPath-fråga",
        "Danh sách lỗi dữ liệu": "Lista över datafel",
        "Bộ đánh giá golden set…": "Bedömare för guldmängden…",
        "So với điểm ngoài (JSONL)…": "Jämför med externa poäng (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Välj en fil med externa poäng (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Byt namn på den valda noden",
        "Gộp các node đang chọn": "Slå samman de valda noderna",
        "Tách node đang chọn": "Dela den valda noden",
        "Trích subgraph đang chọn ra tab mới": "Plocka ut den valda delgrafen till en ny flik",
        "Không có gì để đổi": "Inget att ändra",
        "%@ — áp %d thay đổi?": "%1$@ — tillämpa %2$d {one=ändring|other=ändringar}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d {one=ändring|other=ändringar} · Cmd-Z ångrar hela omgången",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Sätt markören på EXAKT EN nod och försök igen",
        "Đổi tên «%@»": "Byt namn på «%@»",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Alla kanter och etiketter som pekar på den här noden ändras med den.",
        "Đổi tên node": "Byt namn på noden",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Välj MINST TVÅ noder och försök igen",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Kanonisk form «%@» — vanligast, längst, med diakritiska tecken",
        "Gộp node": "Slå samman noder",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Välj de KANTRADER som ska flyttas och försök igen",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Alla valda rader måste röra EXAKT EN nod — välj fler kantrader",
        "Tách «%@» — chuyển %d cạnh": "Dela «%1$@» — flytta %2$d {one=kant|other=kanter}",
        "Cạnh tới: %@": "Kanter till: %@",
        "Tách node": "Dela noden",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Dokumentet är osparat — den uttagna filen behöver en plats bredvid",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Välj den del av grafen som ska plockas ut och försök igen",
        "Gom biến thể entity → bảng duyệt": "Samla entitetsvarianter → granskningstabell",
        "Áp bảng duyệt đã sửa": "Tillämpa den ändrade granskningstabellen",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Dokumentet är osparat — granskningstabellen måste ligga bredvid graffilen",
        "Không tìm thấy biến thể nào để gom": "Inga varianter att samla hittades",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=variantgrupp|other=variantgrupper} — rätta kolumnen «canonical» och kör «Tillämpa granskningstabellen»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Ingen granskningstabell «%@» — kör «Samla entitetsvarianter» först",
        "Bảng duyệt không đọc được: %@": "Granskningstabellen går inte att läsa: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Granskningstabellen har ingen rad som behöver ändras",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Ingen plats i grafen stämmer med granskningstabellen",
        "Gom biến thể entity": "Samla entitetsvarianter",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=ändring tillämpad|other=ändringar tillämpade} · alias-tabellen och markörlistan skrevs bredvid filen",
        "Áp %d thay đổi lên đồ thị?": "Tillämpa %d {one=ändring|other=ändringar} på grafen?",
        "%d alias → dạng chuẩn.": "%d alias → kanonisk form.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "SLÅ SAMMAN noder (går inte att ångra genom att skriva om):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias finns|other=alias finns} inte i grafen och hoppades över.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Täckningsanalys stycke ↔ entitet",
        "Xuất gói ngữ cảnh (JSONL)": "Exportera kontextpaketet (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Täckning stycke ↔ entitet ↔ graf",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=entitet|other=entiteter} · %2$d {one=stycke|other=stycken} · %3$.0f %% av entiteterna nämnda · %4$.0f %% av styckena med entitet",
        "Entity không chunk nào nhắc tới": "Entiteter som inget stycke nämner",
        "Chunk mồ côi (không chứa entity nào)": "Föräldralösa stycken (utan någon entitet)",
        "Node đồ thị không có entity đối ứng": "Grafnoder utan motsvarande entitet",
        "không có": "inga",
        "Phương pháp": "Metod",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Det gick inte att bygga kopplingen stycke ↔ entitet",
        "Chấm sức khoẻ đồ thị": "Bedöm grafens hälsa",
        "sức khoẻ đồ thị": "grafens hälsa",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Hälsa %1$@/100 · %2$d {one=fel|other=fel} · %3$d {one=omkastning|other=omkastningar} · %4$d föräldralösa",
        "Lai với đồ thị": "Hybrid med grafen",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: grafens signal ignoreras helt, resultatet blir samma som ren BM25",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α högt: grafen justerar bara BM25-rangordningen lätt",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α kring standardvärdet 0,7: BM25 leder, grafen justerar",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α lågt: grafen leder, BM25 bryter bara lika",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: bara grafens signal; stycken utan entiteter hamnar på samma nivå",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Dokumentet är osparat — hybriden behöver en graffil bredvid korpusen",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Graffilen «%@» hittades inte — hybriden behöver den för sin signal",
        "lai %.1f ms · %@": "hybrid %.1f ms · %@",
        "Thuật toán…": "Algoritmer…",
        "PageRank (độ dày viền)": "PageRank (kantens tjocklek)",
        "Cộng đồng (màu nền)": "Gemenskaper (bakgrundsfärg)",
        "Thành phần liên thông": "Sammanhängande komponenter",
        "Xuất bảng node ra tab mới": "Exportera nodtabellen till en ny flik",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d {one=komponent|other=komponenter} · den största %2$d {one=nod|other=noder} · %3$d föräldralösa noder",
        "Tài liệu này không phải đồ thị DOT": "Det här dokumentet är ingen DOT-graf",
        "Không dựng được bảng node/cạnh: %@": "Det gick inte att bygga nod-/kanttabellen: %@",
        "%d hàng · %@": "%d {one=rad|other=rader} · %@",
        "Gán nhãn": "Etikettera",
        "Ghi chú (tuỳ chọn)": "Anteckning (frivillig)",
        "Lưu record": "Spara posten",
        "Xuất CSV": "Exportera CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Dokumentet är osparat — bedömaren måste ligga bredvid korpusfilen",
        "Không nạp được bộ đánh giá: %@": "Det gick inte att läsa in bedömaren: %@",
        "Không lưu được: %@": "Det gick inte att spara: %@",
        "Bộ đánh giá chưa có record nào": "Bedömaren har ännu ingen post",
        "Không ghi được: %@": "Det gick inte att skriva: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Det här dokumentet är varken en .mmd-fil eller DOT och har inget mermaid-block.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=nod|other=noder} · %d {one=kant|other=kanter} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid-diagram: lägg till element…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid-diagram: koppla ihop de två valda elementen",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid-diagram: ändra etiketten på det valda elementet…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid-diagram: radera det valda elementet",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid-diagram: flytta meddelandet uppåt",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid-diagram: flytta meddelandet nedåt",
        "Thêm phần tử": "Lägg till element",
        "Thêm participant": "Lägg till deltagare",
        "Thêm mục": "Lägg till post",
        "Thêm mục sơ đồ": "Lägg till en post i diagrammet",
        "Sửa mục sơ đồ": "Ändra en post i diagrammet",
        "Xoá mục sơ đồ": "Radera en post ur diagrammet",
        "Xoá phần tử": "Radera elementet",
        "Sửa nhãn": "Ändra etiketten",
        "Đổi thứ tự message": "Ändra ordningen på meddelandena",
        "Tên mục": "Postens namn",
        "Mục mới": "Ny post",
        "Tên mục hiện trên sơ đồ.": "Postens namn visas på diagrammet.",
        "Bảng thuộc tính sơ đồ": "Diagrammets egenskapstabell",
        "Tài liệu này không có khối mermaid nào": "Det här dokumentet har inget mermaid-block",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identifierare i diagramkällan — utan mellanslag. Etiketten ändras sedan med dubbelklick.",
        "Để trống thì hiện chính định danh.": "Lämnas det tomt visas identifieraren själv.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Bara den synliga ETIKETTEN ändras; elementets identifierare förblir densamma.",
        "Không rõ «%@» là phần tử nào": "Oklart vilket element «%@» är",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Välj EXAKT TVÅ element och försök igen",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Sätt markören på EXAKT ETT element och försök igen",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Välj ETT element att radera, eller två element som en kant förbinder",
        "Xoá «%@» và %d cạnh chạm nó?": "Radera «%1$@» och den %2$d {one=kant som rör det|other=kanter som rör det}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Noderna i andra änden av de kanterna behålls — de deklareras om med sin etikett om kantsatsen var deras enda deklaration.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Diagrammet «%1$@» redigeras bara som text — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: dra mellan två element för att koppla ihop dem, dubbelklicka för att ändra etiketten",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: dra mellan två deltagare för att lägga till ett meddelande; ordningen ändras via menyn Verktyg",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: redigera i egenskapstabellen nedanför",
        "Soạn trực quan đã bật": "Visuell redigering påslagen",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d {one=post|other=poster} — redigera direkt i tabellen, varje cell är ett ångra-steg",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "För ett cirkeldiagram är det ett tal; för ett gantt det som följer efter kolon.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid-diagram: plocka ut blocket till en .mmd-fil…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid-diagram: bädda in den refererade filen igen",
        "Tách khối sơ đồ": "Plocka ut diagramblocket",
        "Nhúng khối sơ đồ": "Bädda in diagramblocket",
        "Tách khối sơ đồ ra tệp riêng": "Plocka ut diagramblocket till en egen fil",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Filen läggs BREDVID dokumentet; blocket behåller en referensrad så att redigering sker på ett enda ställe.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Dokumentet är osparat — diagramfilen behöver en plats bredvid",
        "Đã có tệp «%@» — chọn tên khác": "Filen «%@» finns redan — välj ett annat namn",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Utplockat till «%@» — blocket behöll en referensrad",
        "Mở tệp": "Öppna filen",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» inbäddat igen; filen ligger kvar på hårddisken",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Det här blocket innehåller ett riktigt diagram, inte en referens",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Det här blocket refererar till «%@» — öppna den filen för att redigera",
        "Không đọc được tệp sơ đồ %@": "Det gick inte att läsa diagramfilen %@",
        "Soạn trực quan": "Visuell redigering",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Dra från en nod till en annan för att lägga till en kant; dubbelklicka för att ändra etiketten. Varje handling är ett ångra-steg.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Visuell redigering: dra mellan två noder för att lägga till en kant, dubbelklicka för att ändra etiketten",
        "Soạn trực quan đã tắt": "Visuell redigering avstängd",
        "Thêm node…": "Lägg till nod…",
        "Thêm cạnh giữa hai node đang chọn…": "Lägg till en kant mellan de två valda noderna…",
        "Sửa nhãn node đang chọn…": "Ändra etiketten på den valda noden…",
        "Xoá node/cạnh đang chọn": "Radera den valda noden/kanten",
        "Thêm node": "Lägg till nod",
        "Thêm cạnh": "Lägg till kant",
        "Sửa nhãn node": "Ändra nodens etikett",
        "Xoá node": "Radera noden",
        "Xoá cạnh": "Radera kanten",
        "Cmd-Z hoàn tác": "Cmd-Z ångrar",
        "Tài liệu đang ở chế độ chỉ đọc": "Det här dokumentet är skrivskyddat",
        "Nhãn của «%@»": "Etiketten för «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Bara den synliga ETIKETTEN ändras; nodens identifierare förblir densamma.",
        "Không rõ «%@» là node nào": "Oklart vilken nod «%@» är",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Nodens identifierare i DOT-filen. Etiketten ändras sedan med dubbelklick på bilden.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Välj EXAKT TVÅ noder och försök igen",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Välj EN nod att radera, eller två noder som en kant förbinder",
        "Xoá node «%@» và %d cạnh chạm nó?": "Radera noden «%1$@» och de %2$d {one=kant som rör den|other=kanter som rör den}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Om hängande kanter blir kvar återskapar DOT noderna ur dem — den raderade noden dyker upp igen vid nästa ritning.",
        "Phòng thí nghiệm truy hồi BM25": "BM25-sökningslabb",
        "Câu hỏi — Enter để tìm": "Fråga — Enter för att söka",
        "Đánh giá…": "Bedöm…",
        "Đang dựng chỉ mục": "Bygger indexet",
        "Không chunk nào khớp": "Inget stycke matchar",
        "kết quả trên": "bästa träffarna",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: varje ord räknas BARA en gång, hur många gånger det än förekommer",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 lågt: att upprepa ett ord ger nästan ingen extra poäng",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 kring standardvärdet 1,2: upprepning ger poäng, men allt mindre",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 högt: ett stycke som upprepar ett ord många gånger belönas kraftigt",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: längden ignoreras, långa stycken straffas inte",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b lågt: långa stycken straffas bara lätt",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b kring standardvärdet 0,75: långa stycken straffas måttligt",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: största straffet för längd, korta stycken gynnas",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: sökningslabb…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Dokumentet är osparat — BM25-indexet ligger bredvid korpusfilen och behöver därför en sökväg",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Den här filen är inte JSONL — Retrieval Lab arbetar på en korpus av stycken",
        "Không dựng được chỉ mục BM25 cho tệp này": "Det gick inte att bygga ett BM25-index för den här filen",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Dokumentet är osparat — en korpussökväg krävs för att skapa rapporten",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Välj en bedömningsmängd (CSV eller JSONL: fråga + väntat stycke-id)",
        "Đánh giá truy hồi": "Bedömning av sökningen",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Ändra k1, b eller k ovanför och titta igen för att jämföra två inställningar; lägg till ett «compare»-block för att köra två parameteruppsättningar parallellt på samma bedömningsmängd.",
        "Lỗi": "Fel",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, i snitt %.0f)",
        "Chế độ JSONL": "JSONL-läge",
        "Bản ghi": "Post",
        "Chi tiết": "Detaljer",
        "Bản ghi ở dòng": "Posten på raden",
        "không phải JSON hợp lệ": "är inte giltig JSON",
        "bản ghi": "poster",
        "dòng trắng": "tomma rader",
        "không phải đối tượng": "är inget objekt",
        "bảng hiện": "visad tabell",
        "ĐÃ HUỶ giữa chừng": "AVBRUTET PÅ HALVA VÄGEN",
        "Không lọc": "Inget filter",
        "bản ghi khớp bộ lọc": "poster som matchar filtret",
        "Đưa con nháy tới một dòng để xem bản ghi": "Sätt markören på en rad för att se posten",
        "Không có bản ghi nào hỏng": "Inga trasiga poster",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Ännu inte undersökt. Kör «JSONL: undersök stycken» igen efter kontrollen.",
        "trường văn bản": "textfält",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHEMA (gissat — ändras genom att välja ett annat fält)",
        "văn bản": "text",
        "định danh": "identifierare",
        "metadata lồng": "nästlade metadata",
        "TRƯỜNG": "FÄLT",
        "phủ": "täckning",
        "nhiều kiểu": "flera typer",
        "ĐỘ DÀI — ký tự": "LÄNGD — tecken",
        "ĐỘ DÀI — từ": "LÄNGD — ord",
        "ĐỘ DÀI — token ước lượng": "LÄNGD — uppskattade tokens",
        "RỖNG VÀ TRÙNG": "TOMMA OCH DUBBLETTER",
        "chunk rỗng": "tomma stycken",
        "dòng": "rader",
        "nhóm trùng chính xác": "grupper av exakta dubbletter",
        "dòng không đọc được, không vào thống kê": "rader går inte att läsa, utanför statistiken",
        "PHƯƠNG PHÁP": "METOD",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«tecken» räknas som Unicode-tecken (skalärer), inte som synliga grupper",
        "«từ» tách theo khoảng trắng ASCII": "«ord» delas på ASCII-mellanslag",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«tokens» räknas med en stavelsedelare — INTE modellens",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«dubblett» betyder EXAKT dubblett; nästan-dubbletter finns i blocket ```quality",
        "chunk": "stycken",
        "JSONL: kiểm và soi chunk…": "JSONL: kontrollera och undersök stycken…",
        "Ảnh": "Bild",
        "PDF": "PDF",
        "Tài liệu Word": "Word-dokument",
        "Bảng tính Excel": "Excel-kalkylblad",
        "Bản trình chiếu PowerPoint": "PowerPoint-presentation",
        "File nén": "Arkiv",
        "Vừa khung": "Anpassa till fönstret",
        "Chép ảnh": "Kopiera bilden",
        "Xoay": "Rotera",
        "Không đọc được ảnh «%@»": "Det går inte att läsa bilden «%@»",
        "Đã chép ảnh vào clipboard": "Bilden kopierad till urklipp",
        "Bôi vàng": "Framhäv i gult",
        "Gạch chân": "Stryk under",
        "Ghi chú…": "Anteckning…",
        "Bỏ chú thích": "Ta bort anteckningarna",
        "Lấy chữ ra tab mới": "Plocka ut texten till en ny flik",
        "Lưu bản có chú thích…": "Spara versionen med anteckningar…",
        "Tìm trong PDF": "Sök i PDF-filen",
        "Thêm": "Lägg till",
        "Trang %d/%d": "Sida %d/%d",
        "Trang %d": "Sida %d",
        "Kết quả %d/%d": "Träff %d/%d",
        "0 kết quả": "0 träffar",
        "Không đọc được PDF «%@»": "Det går inte att läsa PDF-filen «%@»",
        "PDF này có mật khẩu — chưa mở được nội dung": "Den här PDF-filen är lösenordsskyddad — innehållet går inte att komma åt",
        "Không thấy «%@» trong tài liệu": "«%@» hittades inte i dokumentet",
        "Đã bôi vàng": "Framhävt",
        "Đã gạch chân": "Understruket",
        "Hãy bôi đen một đoạn chữ trước": "Markera ett textstycke först",
        "Đã thêm ghi chú": "Anteckning tillagd",
        "Trang này chưa có chú thích nào": "Den här sidan har inga anteckningar",
        "Đã bỏ %d chú thích trên trang này": "%d {one=anteckning borttagen|other=anteckningar borttagna} från den här sidan",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Den här PDF-filen har inget textlager — troligen är det en inskanning",
        "Không ghi được tệp": "Det gick inte att skriva filen",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Den skrivna filen öppnas INTE korrekt igen — använd inte den här versionen",
        "Đã lưu %@ · %d trang": "%@ sparad · %d {one=sida|other=sidor}",
        "Tên": "Namn",
        "Kích thước": "Storlek",
        "Đã nén": "Komprimerad",
        "Tỉ lệ": "Förhållande",
        "Sửa lúc": "Ändrad",
        "Mở mục đang chọn": "Öppna det valda objektet",
        "Bung ra thư mục…": "Packa upp till en mapp…",
        "Bung vào đây": "Packa upp här",
        "%d mục": "%d {one=objekt|other=objekt}",
        "giải nén ra %@": "uppackat till %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— insidan av en Office-fil är ett arkiv; det här är dess delar",
        "Đã bung %d mục": "%d {one=objekt uppackat|other=objekt uppackade}",
        "%d mục hỏng": "%d {one=objekt trasigt|other=objekt trasiga}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=objekt NEKADES|other=objekt NEKADES} eftersom deras sökvägar går utanför målmappen",
        "Không mở được mục này": "Det går inte att öppna det här objektet",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Det går ännu inte att skriva direkt till en %@ — använd «Spara som…»",
        "Không có gì đổi": "Ingenting har ändrats",
        "Đã ghi %d ô vào %@": "%1$d {one=cell skriven|other=celler skrivna} till %2$@",
        "Đã ghi %d đoạn vào %@": "%1$d {one=stycke skrivet|other=stycken skrivna} till %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Det gick inte att skriva till filen — originalet är orört",
        "dựng bài": "förbereda testfallet",
        "Không ghi được settings.json": "Det går inte att skriva settings.json",
        "Xoay trái": "Rotera vänster",
        "Xoay phải": "Rotera höger",
        "Trang lên": "Flytta sidan upp",
        "Trang xuống": "Flytta sidan ned",
        "Xoá trang…": "Radera sidor…",
        "Xoá trang": "Radera sidor",
        "Trích trang…": "Extrahera sidor…",
        "Trích trang ra tệp mới": "Extrahera sidor till ny fil",
        "Gộp tệp PDF…": "Slå ihop PDF-fil…",
        "Tách tệp…": "Dela fil…",
        "Tách tệp PDF": "Dela PDF-fil",
        "Xuất ảnh…": "Exportera bilder…",
        "Xuất trang ra ảnh PNG": "Exportera sidor som PNG-bilder",
        "Hoàn tác trang": "Ångra sidändring",
        "Lưu bản đã sửa…": "Spara ändrad kopia…",
        "Phát": "Spela",
        "Tạm dừng": "Paus",
        "Xem bình thường": "Normal vy",
        "Chọn sheet": "Välj blad",
        "Mở sheet": "Öppna blad",
        "Bỏ và đổi sheet": "Kasta och byt blad",
        "Bảng tính có %d sheet.": "Arbetsboken har %d blad.",
        "Bảng tính này chỉ có một sheet: «%@»": "Arbetsboken har bara ett blad: ”%@”",
        "Bỏ phần chưa lưu của sheet này?": "Kasta osparade ändringar i det här bladet?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Att byta blad ersätter hela fliken. Det som inte sparats med ⌘S går förlorat.",
        "Chọn tệp PDF cần gộp vào": "Välj PDF-fil att slå ihop",
        "Chọn thư mục ghi ảnh": "Välj mapp för bilderna",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Välj var filen ska sparas. Den andra filen skrivs bredvid.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Dokumentet har %d sidor. Ange sidorna som ska raderas, t.ex. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Dokumentet har %d sidor. Ange sidorna som ska extraheras, t.ex. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Dokumentet har %d sidor. Ange sidorna som ska exporteras, t.ex. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Dokumentet har %d sidor. Ange delen som ska skiljas ut, t.ex. 1-5; resten blir en andra fil.",
        "Đã xoay trang %d": "Sida %d roterad",
        "Đã xoá trang %@ · còn %d trang": "Sidorna %@ raderade · %d sidor kvar",
        "Đã gộp %d trang từ «%@»": "%d sidor sammanslagna från ”%@”",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Delad i %@ (%d sidor) och %@ (%d sidor)",
        "Đã ghi %@ — %@ · %d trang": "Skrev %@ — %@ · %d sidor",
        "Đã xuất %d ảnh vào %@": "%d bilder exporterade till %@",
        "Chỉ xuất được %d/%d ảnh": "Endast %d av %d bilder exporterades",
        "Đã hoàn tác một thao tác trang": "En sidåtgärd ångrades",
        "Không còn thao tác trang nào để hoàn tác": "Inga sidåtgärder kvar att ångra",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Kan inte radera ALLA sidor — en PDF måste ha minst en sida",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Det intervallet är hela dokumentet — inget att dela av",
        "«%@» có mật khẩu — chưa gộp được": "”%@” är lösenordsskyddad — går inte att slå ihop",
        "«%@» không có trang nào": "”%@” har inga sidor",
        "Đã ở trang đầu": "Redan på första sidan",
        "Đã ở trang cuối": "Redan på sista sidan",
        "· đã sửa, chưa lưu": "· ändrad, ej sparad",
        "Ảnh động · %d khung": "Animerad bild · %d bildrutor",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Osparat dokument — ingen fil på disken att visa binärt",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Det här kommandot fungerar bara med Excel-arbetsböcker",
        "Không đọc được danh sách sheet": "Det gick inte att läsa listan över blad",
        "Không có sheet «%@»": "Det finns inget blad som heter ”%@”",
        "Không đọc được sheet «%@»": "Det gick inte att läsa bladet ”%@”",
        "Sheet «%@» · %d hàng": "Bladet ”%@” · %d rader",
        "phần còn lại": "resten",
        "Lưu ý": "Obs",
        "Cẩn thận": "Varning",
        "Xem thêm": "Se även",
        "Chép": "Kopiera",
        "Đã chép": "Kopierat",
        "Chép đoạn mã mẫu": "Kopiera exempelkoden",
        "Tìm trong trợ giúp": "Sök i hjälpen",
        "Lùi": "Tillbaka",
        "Bắt đầu dùng": "Kom igång",
        "Không mở cửa sổ này khi khởi động nữa": "Visa inte det här fönstret vid start",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Hjälpen är ännu inte översatt till det här språket — visar den vietnamesiska texten.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Gå till offset (t.ex. 1F400 eller 0x1F400)",
        "Chép dòng đã chọn": "Kopiera markerade rader",
        "Đã chép %d dòng": "%d rader kopierade",
        "Không đọc được «%@»": "Det gick inte att läsa ”%@”",
        "Tệp rỗng": "Tom fil",
        "Không đọc được offset «%@»": "Det gick inte att läsa offseten ”%@”",
        "Offset 0x%@ vượt quá cỡ tệp": "Offseten 0x%@ ligger bortom filens slut",
        "Mở bằng ứng dụng khác…": "Öppna med annat program…",
        "%d kênh": "%d kanaler",
        "Không phát được «%@»": "Kan inte spela ”%@”",
        "Không phát được — %@": "Kan inte spela — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS saknar inbyggd avkodare för formatet %@ — det är en systembegränsning, inte en trasig fil.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Du kan ändå se byten i binärläge, eller öppna filen i ett program med egen avkodare.",
        "Ký…": "Signera…",
        "Sửa chữ…": "Redigera text…",
        "Sửa chữ": "Redigera text",
        "Vẽ đè": "Rita över",
        "Ô chưa điền": "Nästa tomma fält",
        "Xoá nội dung đã điền": "Rensa ifyllda värden",
        "Tệp này không có ô biểu mẫu nào": "Den här filen har inga formulärfält",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d formulärfält rensade",
        "Mọi ô biểu mẫu đều đã có nội dung": "Alla formulärfält är redan ifyllda",
        "Còn %d ô chưa điền": "%d fält är fortfarande tomma",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Ifyllbart formulär: %d fält. Skriv direkt i dem och välj sedan ”Spara ändrad kopia…”",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Välj en signaturbild (transparent bakgrund ser bäst ut)",
        "Không dựng được trang có chữ ký": "Det gick inte att skapa den signerade sidan",
        "Đã chèn chữ ký vào trang %d": "Signaturen infogad på sida %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Markera först texten du vill ändra",
        "Vùng chọn quá nhỏ": "Markeringen är för liten",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Den nya texten RITAS ÖVER markeringen med systemtypsnittet. Den gamla texten täcks, den tas inte bort — den går fortfarande att extrahera, så detta är ingen maskering.",
        "Không dựng được trang đã sửa": "Det gick inte att skapa den ändrade sidan",
        "Đã vẽ đè chữ mới lên trang %d": "Ny text ritades över sida %d",
        "Đổi chế độ View / Code": "Växla Vy / Kod",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Ingen trädvy ännu för JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Ingen diagramvy i fliken ännu",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Ingen dispositionsvy ännu för PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Den här filen har bara ett visningsläge",
        "%d nút": "%d noder",
        "Không dựng được cây: %@": "Det gick inte att bygga trädet: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Dokumentet är för stort för ett träd — använd Kod-läget",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Kunde inte bygga sidor för den här filen \u{2014} använd Code-läget.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Bilder byggs från text; originalbilder och layout ritas inte än.",
        "Vừa ngang": "Anpassa bredd",
        "Thu nhỏ trang": "Zooma ut sida",
        "Phóng to trang": "Zooma in sida",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "Hittade inte ”%@” i dokumentet",
        "Chỗ khớp %d/%d": "Träff %d av %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Ingen text är markerad på sidan.",
        "%d ký tự": "%d {one=tecken|other=tecken}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Öppna filer direkt i View-läget när det finns",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· AVBRUTEN halvvägs — tabellen är ofullständig",
        "Chế độ hiển thị": "Visningsläge",
        "Đổi giữa View và Code (⌥⌘V)": "Växla mellan View och Code (⌥⌘V)",
        "Trang tài liệu": "Dokumentsidor",
        "Chữ đã dựng": "Satt text",
        "Trang bảng tính": "Kalkylbladssidor",
        "Sơ đồ": "Diagram",
        "Cây khoá–giá trị": "Nyckel–värde-träd",
        "Bộ phát": "Spelare",
        "Danh sách mục": "Postlista",
        "Báo cáo đã dựng": "Färdig rapport",
        "Tô theo mức": "Färgad efter nivå",
        "Trang slide": "Bildsidor",
        "Dàn ý": "Disposition",
        "Lưu rồi dựng lại": "Spara och bygg om",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Visar kopian PÅ DISKEN — osparade ändringar finns inte här.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Systemet kunde inte bygga dokumentvyn — använd Code-läget.",
        "Lưu tệp trước khi xem trang.": "Spara filen innan du visar dess sidor.",
        "Đang ở chế độ Code": "Just nu i Code-läge",
        "Đang ở chế độ View": "Just nu i View-läge",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Du ser källtexten — klicka för View-läget (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "I View-läge — klicka för att gå tillbaka till källtexten (⌥⌘V)",
        "Tín hiệu: %@": "Signal: %@",
        "Lý do: %@": "Orsak: %@",
        "Chi tiết: %@": "Detalj: %@",
        "Mở báo cáo": "Öppna rapporten",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor avslutades oväntat %@ — öppna rapporten för att läsa den; inget skickas iväg.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligaturer — av håller varje tecken i sin egen ruta",
        "Chế độ CSV": "CSV-läge",
        "Dấu phân tách": "Avgränsare",
        "Tự nhận diện": "Upptäck automatiskt",
        "Dấu phân tách: %@": "Avgränsare: %@",
        "Theo đuôi tệp": "Efter filändelse",
        "%d dấu cách": "%d {one=blanksteg|other=blanksteg}",
        "Tài liệu đang sửa được": "Det här dokumentet går att redigera",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Skrivskyddad eftersom filen följs — sluta följa för att redigera",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Skrivskyddad eftersom filen på disken inte går att skriva till",
        "Đã mở khoá — tài liệu sửa được": "Upplåst — dokumentet går att redigera igen",
        "Nhân bản tệp": "Duplicera fil",
        "Đổi tên tệp…": "Byt namn på fil…",
        "Chuyển tệp tới…": "Flytta fil till…",
        "XML: đánh giá XPath…": "XML: utvärdera XPath…",
        "Đánh giá XPath": "Utvärdera XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Till exempel: //order/rad[2]/@kod · //*[@typ='A'] · count(//rad)",
        "Đánh giá": "Utvärdera",
        "XPath không đọc được: %@": "Går inte att läsa den XPath-uttrycket: %@",
        "XPath «%@» không khớp node nào": "XPath ”%@” träffade ingen nod",
        "XPath «%@» — %d node": "XPath ”%@” — %d {one=nod|other=noder}",
        "XPath «%@»: %d node": "XPath ”%@”: %d {one=nod|other=noder}",
        "Lưu tệp trước khi nhân bản.": "Spara filen innan du duplicerar den.",
        "Không nhân bản được": "Kunde inte duplicera",
        "Đã nhân bản thành %@": "Duplicerad som %@",
        "Lưu tệp trước khi đổi tên.": "Spara filen innan du byter namn på den.",
        "Đổi tên tệp": "Byt namn på fil",
        "Tên hiện tại: %@": "Nuvarande namn: %@",
        "Đổi tên": "Byt namn",
        "Tên tệp không hợp lệ": "Det filnamnet är inte giltigt",
        "Đã có tệp tên %@ ở đó": "Det finns redan en fil som heter %@ där",
        "Lưu tệp trước khi chuyển.": "Spara filen innan du flyttar den.",
        "Chuyển tới": "Flytta hit",
        "Thư mục đích đã có tệp tên %@": "Målmappen har redan en fil som heter %@",
        "Không chuyển được tệp": "Kunde inte flytta filen",
        "Đã chuyển tới %@": "Flyttad till %@",
        "Bảng mã:": "Teckenkodning:",
        "Xuống dòng:": "Radslut:",
        "Riêng cho %@": "Bara för %@",
        "    %d — dùng TAB": "    %d — tabbar",
        "    %d — dùng dấu cách": "    %d — blanksteg",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Ta bort egen regel, använd den globala inställningen",
        "%@: thụt lề %d %@": "%@: indrag %d %@",
        "TAB": "tabbar",
        "dấu cách": "blanksteg",
        "Xuất": "Exportera",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Öppna resultaten som en textflik — spara med ⌘S",
        "Lượt tìm trước đó": "Tidigare sökningar",
        "«%@» — %d kết quả": "”%@” — %d {one=träff|other=träffar}",
        "Kết quả tìm «%@»": "Sökresultat för ”%@”",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtrera filnamn — t.ex. *.csv;*.log (tomt: varje textfil)",
        "Thư mục %@ không có file văn bản nào": "Mappen %@ har inga textfiler",
        "Không tệp nào trong %@ khớp «%@»": "Ingen fil i %@ matchar ”%@”",
        "%d byte · %d dòng": "%d byte · %d {one=rad|other=rader}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d byte · %d {one=rad|other=rader} — för stor för att räkna tecken och ord",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d byte · %d {one=tecken|other=tecken} · %d {one=ord|other=ord} · %d {one=rad|other=rader}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Det här dokumentet har %d {one=rad|other=rader}, %d byte. Skriv ett radnummer, ”rad,kolumn” eller ”@byte”.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "Går inte att läsa ”%@” — skriv ett radnummer, ”rad,kolumn” eller ”@byte”",
    ]
}
