import Foundation

/// Bảng dịch tiếng Ý. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let it: [String: String] = [
        "Bản đã lưu…": "Versioni salvate…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Questo documento non è mai stato salvato — nessuna cronologia",
        "Chưa có bản đã lưu nào trước đó": "Non ci sono versioni salvate precedenti",
        "Không đọc được bản ấy": "Impossibile leggere quella versione",
        "Khôi phục bản đã lưu": "Ripristina la versione salvata",
        "XML: kiểm theo DTD/XSD…": "XML: valida con DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Questo Mac non ha libxml2, quindi la validazione XSD non è disponibile.",
        "Chọn lược đồ XSD để kiểm": "Scegli uno schema XSD per la validazione",
        "Hợp lệ theo": "Valido secondo",
        "Plugin chạy xong, không đổi gì": "L’estensione ha terminato senza modificare nulla",
        "Chưa cài plugin native nào": "Nessuna estensione nativa installata",
        "Gỡ plugin này": "Rimuovi questa estensione",
        "Gỡ plugin này?": "Rimuovere questa estensione?",
        "Gỡ": "Rimuovi",
        "Cài plugin native…": "Installa un’estensione nativa…",
        "Mở thư mục plugin": "Apri la cartella delle estensioni",
        "Chọn file .dylib của plugin native": "Scegli il file .dylib dell’estensione",
        "Đã cài:": "Installato:",
        "Đã gỡ:": "Rimosso:",
        "Plugin native…": "Estensioni native…",
        "Chỉ nhận file .dylib.": "Sono accettati solo file .dylib.",
        "Đã có một plugin trùng tên:": "Esiste già un’estensione con lo stesso nome:",
        "Không chép được plugin:": "Impossibile copiare l’estensione:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Le estensioni native ci sono solo nel download diretto, non nella versione App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Processo ausiliario delle estensioni non trovato.",
        "Không khởi động được tiến trình phụ:": "Impossibile avviare il processo ausiliario:",
        "Tiến trình plugin đã dừng giữa chừng.": "Il processo dell’estensione si è interrotto a metà.",
        "Plugin không trả lời kịp — đã dừng nó.": "L’estensione non ha risposto in tempo — è stata fermata.",
        "Plugin trả lời sai giao thức:": "L’estensione ha risposto con un messaggio malformato:",
        "Plugin báo lỗi:": "L’estensione ha segnalato un errore:",
        "Về GEditor": "Informazioni su GEditor",
        "Cài đặt…": "Impostazioni…",
        "Thoát GEditor": "Esci da GEditor",
        "File": "File",
        "Tab mới": "Nuova scheda",
        "Đóng tab": "Chiudi scheda",
        "Tab kế": "Scheda successiva",
        "Tab trước": "Scheda precedente",
        "Tài liệu mới": "Nuovo documento",
        "Mở…": "Apri…",
        "Mở thư mục làm Workspace…": "Apri una cartella come area di lavoro…",
        "Mở gần đây": "Apri recenti",
        "Lưu": "Salva",
        "Lưu thành…": "Salva come…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Rimuovi gli spazi a fine riga al salvataggio",
        "Theo dõi file (tail -f)": "Segui il file (tail -f)",
        "In…": "Stampa…",
        "Mở lại tab vừa đóng": "Riapri la scheda chiusa",
        "Chưa có file nào": "Nessun file",
        "Xoá danh sách": "Svuota l’elenco",
        "Edit": "Modifica",
        "Hoàn tác": "Annulla",
        "Làm lại": "Ripristina",
        "Cắt": "Taglia",
        "Sao chép": "Copia",
        "Dán": "Incolla",
        "Lịch sử clipboard…": "Cronologia degli appunti…",
        "Column Editor…": "Editor di colonne…",
        "Chọn lần kế tiếp": "Seleziona l’occorrenza successiva",
        "Chọn tất cả": "Seleziona tutto",
        "Nhân đôi dòng": "Duplica la riga",
        "Xóa dòng": "Elimina la riga",
        "Comment dòng": "Commenta la riga",
        "Chưa chép gì trong phiên này": "Non è stato copiato nulla in questa sessione",
        "Xoá lịch sử": "Cancella la cronologia",
        "Search": "Cerca",
        "Tìm…": "Trova…",
        "Tìm và thay…": "Trova e sostituisci…",
        "Tìm trong thư mục…": "Cerca in una cartella…",
        "Thay trong thư mục…": "Sostituisci in una cartella…",
        "Kết quả kế": "Risultato successivo",
        "Kết quả trước": "Risultato precedente",
        "Đi tới dòng…": "Vai alla riga…",
        "Nhảy tới ngoặc khớp": "Vai alla parentesi corrispondente",
        "Đánh dấu mọi dòng khớp…": "Segna tutte le righe corrispondenti…",
        "Đảo dấu": "Inverti i segnalibri",
        "Bỏ mọi dấu": "Rimuovi tutti i segnalibri",
        "Chép dòng đã đánh dấu": "Copia le righe segnate",
        "Xóa dòng đã đánh dấu": "Elimina le righe segnate",
        "Chỉ giữ dòng đã đánh dấu": "Tieni solo le righe segnate",
        "Lines": "Righe",
        "Sắp xếp A→Z": "Ordina A→Z",
        "Sắp xếp Z→A": "Ordina Z→A",
        "Sắp xếp tự nhiên": "Ordinamento naturale",
        "Khử trùng lặp": "Rimuovi i duplicati",
        "Đảo thứ tự dòng": "Inverti l’ordine delle righe",
        "Dời dòng lên": "Sposta la riga in su",
        "Dời dòng xuống": "Sposta la riga in giù",
        "Ghép dòng": "Unisci le righe",
        "Tách dòng theo độ dài…": "Dividi le righe per lunghezza…",
        "Tách dòng theo ký tự…": "Dividi le righe per carattere…",
        "Xóa dòng rỗng": "Elimina le righe vuote",
        "Nén dòng trống liên tiếp": "Comprimi le righe vuote consecutive",
        "Cắt khoảng trắng cuối dòng": "Rimuovi gli spazi a fine riga",
        "Tab → Space": "Tab → Spazio",
        "Space → Tab": "Spazio → Tab",
        "HOA": "MAIUSCOLO",
        "thường": "minuscolo",
        "Chữ Hoa Đầu Từ": "Maiuscola A Ogni Parola",
        "Chữ hoa đầu câu": "Maiuscola a inizio frase",
        "Đảo hoa/thường": "iNVERTI mAIUSCOLE",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: scegli foglio…",
        "Xem dạng bảng / văn bản": "Alterna vista tabella / testo",
        "Xóa cột…": "Elimina colonna…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Valida i dati (numero di colonne · tipi)",
        "Bàn làm sạch dữ liệu…": "Banco di pulizia dei dati…",
        "Chạy công thức làm sạch…": "Esegui una ricetta di pulizia…",
        "Chuyển đổi…": "Converti…",
        "Đổi dấu phân tách…": "Cambia il separatore…",
        "Xuất sang JSON…": "Esporta in JSON…",
        "Format": "Formato",
        "Bảng mã…": "Codifica…",
        "Xuống dòng…": "Fine riga…",
        "Chuẩn hóa Unicode…": "Normalizza Unicode…",
        "JSON: định dạng lại": "JSON: formatta",
        "JSON: thu gọn một dòng": "JSON: compatta su una riga",
        "JSON: sắp xếp khóa": "JSON: ordina le chiavi",
        "JSON: truy vấn JSONPath…": "JSON: query JSONPath…",
        "CSV: truy vấn SQL…": "CSV: query SQL…",
        "Truy vấn SQL": "Query SQL",
        "Đang chạy…": "In esecuzione…",
        "Xuất ra tab mới": "Esporta in una nuova scheda",
        "Tài liệu rỗng — không có bảng để truy vấn": "Documento vuoto — nessuna tabella da interrogare",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Non è una tabella CSV — la prima riga ha una sola colonna",
        "Không đọc được câu truy vấn": "Impossibile leggere la query",
        "Không kiểm được câu truy vấn": "Impossibile verificare la query",
        "Vàng (mặc định)": "Giallo (predefinito)",
        "Xanh dương": "Blu",
        "Xanh lá": "Verde",
        "Vàng đất": "Ocra",
        "Tím": "Viola",
        "Hồng": "Rosa",
        "Xanh ngọc": "Turchese",
        "Cam": "Arancione",
        "Xám lam": "Ardesia",
        "Văn bản": "Testo",
        "Dãy số": "Serie numerica",
        "Dãy ngày": "Serie di date",
        "Chữ HOA (hex)": "MAIUSCOLO (esadecimale)",
        "Bắt đầu": "Inizio",
        "Bước": "Passo",
        "Đệm 0 tới": "Riempi di zeri fino a",
        "Hệ": "Base",
        "Ngày đầu": "Prima data",
        "Định dạng": "Formato",
        "Chèn": "Inserisci",
        "Huỷ": "Annulla",
        "Chuyển đổi định dạng": "Converti il formato",
        "Xem trước 5 hàng đầu": "Anteprima delle prime 5 righe",
        "Tạo tab mới": "Apri in una nuova scheda",
        "Lưu ra file…": "Salva su file…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Il risultato si apre in una nuova scheda non salvata. Il documento originale resta intatto.",
        "Chạy trên tài liệu này": "Esegui su questo documento",
        "Chạy trên thư mục…": "Esegui su una cartella…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "L’intera ricetta è UN solo passo di annullamento. Il file su disco resta intatto finché non salvi.",
        "tắt": "disattivato",
        "không thấy cột": "colonna non trovata",
        "sẵn sàng": "pronto",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "continua a occupare un core della CPU finché l’app non viene chiusa.",
        "Script không trả về gì": "Lo script non ha restituito nulla",
        "Không dựng được máy JavaScript": "Impossibile creare il motore JavaScript",
        "Lỗi JavaScript không rõ": "Errore JavaScript sconosciuto",
        "Bảng": "Tabella",
        "Áp sắp xếp vào file": "Applica l’ordinamento al file",
        "Chuyển đổi ▾": "Converti ▾",
        "Xuất dòng khớp": "Esporta le righe corrispondenti",
        "Ẩn cột này": "Nascondi questa colonna",
        "Đổi tên tiêu đề…": "Rinomina l’intestazione…",
        "Chèn cột trống bên trái": "Inserisci una colonna vuota a sinistra",
        "Chèn cột trống bên phải": "Inserisci una colonna vuota a destra",
        "Xóa cột này khỏi file…": "Elimina questa colonna dal file…",
        "Phải còn ít nhất một cột đang hiện": "Deve restare visibile almeno una colonna",
        "Đang sắp xếp…": "Ordinamento in corso…",
        "Trở về thứ tự trong file": "Torna all’ordine del file",
        "trăm hàng đầu": "prime cento righe",
        "chọn cột": "scegliere le colonne",
        "đặt tên cột kết quả": "dare un nome a una colonna del risultato",
        "lọc theo chữ": "filtrare per testo",
        "ô rỗng": "celle vuote",
        "ghép điều kiện": "combinare condizioni",
        "đếm hàng": "contare le righe",
        "gộp nhóm": "raggruppare e aggregare",
        "nhỏ nhất, lớn nhất": "minimo, massimo",
        "sắp xếp và cắt": "ordinare e limitare",
        "tên cột có dấu cách": "nome di colonna con spazi",
        "Truy vấn bị dừng giữa chừng": "La query è stata interrotta",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Non supportato: JOIN · sottoquery · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funzioni finestra",
        "XML: định dạng lại": "XML: formatta",
        "XML: thu gọn một dòng": "XML: compatta su una riga",
        "XML: kiểm cú pháp": "XML: verifica la sintassi",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: verifica chiavi duplicate e indentazione",
        "View": "Vista",
        "Ẩn/hiện sidebar (Function List)": "Mostra/nascondi la barra laterale (elenco funzioni)",
        "Ẩn/hiện bản đồ tài liệu": "Mostra/nascondi la mappa del documento",
        "Gấp / mở khối tại con nháy": "Comprimi / espandi il blocco al cursore",
        "Gấp tất cả": "Comprimi tutto",
        "Bỏ gấp tất cả": "Espandi tutto",
        "Gấp theo cấp": "Comprimi per livello",
        "Cấp %d": "Livello %d",
        "Đã gấp %d khối ở cấp %d": "%d {one=blocco compresso|other=blocchi compressi} al livello %d",
        "Tài liệu này chỉ sâu %d cấp": "Questo documento è profondo solo %d {one=livello|other=livelli}",
        "mermaid: không đọc được bản kê": "mermaid: manifest illeggibile",
        "Kiểm tra bản cập nhật…": "Cerca aggiornamenti…",
        "Kiểm tra bản cập nhật": "Cerca aggiornamenti",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Le versioni App Store si aggiornano tramite il Mac App Store, non tramite GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Questa build non ha una chiave di firma per gli aggiornamenti, quindi non può cercarli.",
        "Phóng to chữ": "Ingrandisci il testo",
        "Thu nhỏ chữ": "Riduci il testo",
        "Cỡ chữ gốc": "Dimensione reale",
        "Chia đôi theo chiều dọc": "Dividi verticalmente",
        "Chia đôi theo chiều ngang": "Dividi orizzontalmente",
        "Bỏ chia đôi": "Chiudi la divisione",
        "Mở tab này ở nửa kia": "Apri questa scheda nell’altro riquadro",
        "Nhảy sang nửa kia": "Vai all’altro riquadro",
        "Ngắt dòng (tắt / cửa sổ / cột)": "A capo automatico (disattivato / finestra / colonna)",
        "Ngắt dòng tại cột…": "A capo alla colonna…",
        "Đánh dấu dòng này": "Segna questa riga",
        "Dấu kế tiếp": "Segnalibro successivo",
        "Dấu trước đó": "Segnalibro precedente",
        "Màu đánh dấu…": "Colore dei segnalibri…",
        "Hiện tất cả ký tự ẩn": "Mostra tutti i caratteri invisibili",
        "  Khoảng trắng": "  Spazi",
        "  Tab": "  Tabulazioni",
        "  Xuống dòng": "  Fine riga",
        "  NBSP · zero-width · điều khiển": "  NBSP · larghezza zero · controllo",
        "Xem nhị phân": "Vista binaria",
        "Chế độ CSV (tô màu theo cột)": "Modalità CSV (colonne colorate)",
        "Macro": "Macro",
        "Bắt đầu / dừng ghi": "Avvia / ferma la registrazione",
        "Phát lại": "Riproduci",
        "Phát nhiều lần…": "Riproduci più volte…",
        "Phát đến cuối tài liệu": "Riproduci fino alla fine del documento",
        "Chạy trên mọi tab": "Esegui su tutte le schede",
        "Hủy macro đang chạy": "Annulla la macro in corso",
        "Lưu macro…": "Salva la macro…",
        "Macro đã lưu…": "Macro salvate…",
        "Help": "Aiuto",
        "Trợ giúp GEditor": "Aiuto di GEditor",
        "Giới thiệu tính năng": "Panoramica delle funzioni",
        "Di cư từ Notepad++": "Migrare da Notepad++",
        "Tìm": "Trova",
        "Thay bằng": "Sostituisci con",
        "Kế": "Successivo",
        "Trước": "Precedente",
        "Đếm": "Conta",
        "Đóng": "Chiudi",
        "Kiểm theo JSON Schema…": "Valida con uno schema JSON…",
        "Chọn tệp JSON Schema": "Scegli un file di schema JSON",
        "Không thấy lỗi nào theo schema này.": "Nessun problema trovato secondo questo schema.",
        "JSON Schema": "Schema JSON",
        "Kiểm cú pháp đồ thị": "Verifica la sintassi del grafo",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Formato del grafo non riconosciuto — serve un’estensione .dot, .gv, .cypher, .ttl o .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Nessun errore di sintassi %@ trovato (la verifica non è esaustiva).",
        "Cú pháp %@": "Sintassi %@",
        "không phải một đối tượng JSON": "non è un oggetto JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Text mining (n-grammi, TF-IDF)",
        "Tài liệu rỗng.": "Il documento è vuoto.",
        "Không rút được từ khoá nào.": "Non è stato possibile estrarre alcuna parola chiave.",
        "Từ khoá": "Parole chiave",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=parola chiave|other=parole chiave} · %d token · %d {one=documento|other=documenti}",
        "Tô lên tài liệu": "Segna nel documento",
        "Đánh dấu entity từ danh sách…": "Segna entità da un elenco…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Scegli un elenco di entità (CSV o JSON)",
        "Không đọc được danh sách entity.": "Impossibile leggere l’elenco di entità.",
        "Danh sách entity rỗng.": "L’elenco di entità è vuoto.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Nessuna entità trovata nel documento (%d caricate).",
        "%d lần xuất hiện · %@": "%d {one=occorrenza|other=occorrenze} · %@",
        "Chuyển đổi tri thức…": "Converti conoscenza…",
        "Chuyển đổi: %@ → %@": "Conversione: %@ → %@",
        "Không chuyển đổi được.": "Conversione non riuscita.",
        "Xem trước cắt chunk…": "Anteprima della suddivisione…",
        "Cỡ cố định 800B, chồng 100B": "Dimensione fissa 800 B, sovrapposizione 100 B",
        "Theo câu (≤ 800B)": "Per frase (≤ 800 B)",
        "Theo heading Markdown": "Per titolo Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Documento vuoto — nessun frammento.",
        "%d chunk · trung bình %d B · %@": "%d {one=frammento|other=frammenti} · %d B in media · %@",
        "Xuất JSONL": "Esporta JSONL",
        "Chunk JSONL": "Frammenti JSONL",
        "Mở triple/edge dạng bảng": "Apri triple/archi come tabella",
        "Bảng triple": "Tabella di triple",
        "Tài liệu này không có dòng triple nào.": "Questo documento non ha alcuna riga di tripla.",
        "Không đọc được triple nào — dòng %d: %@": "Non è stato possibile leggere alcuna tripla — riga %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%d {one=tripla letta|other=triple lette} · %d {one=riga malformata saltata|other=righe malformate saltate} (la prima: riga %d)",
        "Trùng lặp mờ theo cột…": "Duplicati approssimati per colonna…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Duplicati approssimati — colonna «%@»: %d {one=gruppo candidato|other=gruppi candidati}",
        "Gộp": "Unisci",
        "Giống": "Corrispondenza",
        "Các giá trị trong cụm": "Valori del gruppo",
        "Gộp về": "Unisci in",
        "Gộp các cụm đã chọn": "Unisci i gruppi selezionati",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Nessun gruppo selezionato — premere Unisci NON cambierà nulla. L’app non unisce mai da sola.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=gruppo selezionato|other=gruppi selezionati} · %d {one=riga cambierà|other=righe cambieranno} · UN solo passo di annullamento",
        "Không quét được cột này.": "Impossibile analizzare questa colonna.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "La colonna «%@» non ha gruppi di duplicati approssimati.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Nessun gruppo unito — il documento resta invariato.",
        "Khử trùng lặp mờ · cột %@": "Deduplicazione approssimata · colonna %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=gruppo unito|other=gruppi uniti} · %d {one=cella modificata|other=celle modificate}",
        "Báo cáo làm sạch": "Rapporto di pulizia",
        "# Báo cáo làm sạch — %@\n\n": "# Rapporto di pulizia — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Applicato (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Nessun passo applicato._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Profilo dei dati\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%d {one=colonna|other=colonne} · %d {one=riga|other=righe} · analizzato in %.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Colonna | Tipo | Null | Distinti | Min | Max | Media |\n",
        "\n### Giá trị bất thường\n\n": "\n### Valori anomali\n\n",
        "hàng %d: %@": "riga %d: %@",
        "- cột «%@» — %d ô: %@\n": "- colonna «%@» — %d {one=cella|other=celle}: %@\n",
        "\n## Còn lại (%d)\n\n": "\n## Rimanente (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Non restano rilevazioni._\n",
        "- cột «%@»: %@\n": "- colonna «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Rimuovi gli spazi al salvataggio",
        "Chuẩn hóa xuống dòng": "Normalizza i fine riga",
        "trước đó": "precedente",
        "Không mở lại được thư mục «%@» của phiên trước": "Impossibile riaprire la cartella «%@» della sessione precedente",
        " (và %d file khác)": " (e %d {one=altro file|other=altri file})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "Impossibile riaprire %d {one=scheda|other=schede}: %@%@ — i file non sono più dov’erano.",
        "Không đọc được nội dung từ ống dẫn": "Impossibile leggere l’input dalla pipe",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Gli spazi a fine riga verranno rimossi a ogni salvataggio",
        "Không cắt khoảng trắng khi lưu nữa": "Gli spazi non vengono più rimossi al salvataggio",
        "Chưa đặt tên.txt": "Senza titolo.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Convertire la codifica farà perdere caratteri",
        "Vẫn lưu": "Salva comunque",
        "Tài liệu có thay đổi chưa lưu": "Il documento ha modifiche non salvate",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Chiudere senza salvare le scarterà.",
        "Bỏ thay đổi": "Scarta le modifiche",
        "Đi tới dòng": "Vai alla riga",
        "Tài liệu có %d dòng.": "Il documento ha %d {one=riga|other=righe}.",
        "Số dòng": "Numero di riga",
        "Đi tới": "Vai",
        "Diễn giải lại theo…": "Reinterpreta come…",
        "Chuyển đổi sang…": "Converti in…",
        "Không diễn giải lại được": "Reinterpretazione non riuscita",
        "Bảng mã %@ không chứa hết ký tự": "%@ non può rappresentare tutti i caratteri",
        "Vẫn chọn": "Scegli comunque",
        "Cột %d": "Colonna %d",
        "Cột %d: %@": "Colonna %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Colonne nascoste: %@ (%d) — ripristinale dal menu contestuale della riga di intestazione",
        "Hiện lại: %@": "Mostra di nuovo: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Colonna %@ nascosta — resta intatta nel file",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Ordinato per %@ %@ · solo visualizzazione",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Ordinato: %@ %@ (solo visualizzazione)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ righe corrispondono — ricerca in corso…",
        "%d / %d dòng khớp": "%d / %d {one=riga corrisponde|other=righe corrispondono}",
        "Không tìm thấy lỗi trong %d hàng": "Nessun problema trovato in %d {one=riga|other=righe}",
        "%d hàng lệch số cột": "%d {one=riga|other=righe} con un numero di colonne errato",
        "%d ô sai kiểu dữ liệu": "%d {one=cella|other=celle} con il tipo di dato errato",
        " (đã dừng ở %d lỗi đầu)": " (fermato ai primi %d {one=problema|other=problemi})",
        "   —   kiểu nhận ra: ": "   —   tipi rilevati: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Riga %d, colonna %@: «%@» non è %@",
        "Column Editor — %d dòng": "Editor di colonne — %d {one=riga|other=righe}",
        "Phát hiện": "Rilevazioni",
        "Hồ sơ dữ liệu": "Profilo dei dati",
        "Hồ sơ dữ liệu — đang quét…": "Profilo dei dati — analisi in corso…",
        "Lưu công thức…": "Salva la ricetta…",
        "Xuất báo cáo": "Esporta il rapporto",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Nessun gruppo applicato · ogni gruppo è un passo di annullamento",
        "quá nhiều giá trị": "troppi valori",
        "hay gặp: ": "più frequenti: ",
        "Giá trị điền vào ô thiếu": "Valore con cui riempire le celle vuote",
        "Áp dụng": "Applica",
        "Không dựng được bản xem trước": "Impossibile costruire un’anteprima",
        "· giữ nguyên, không đọc được ·": "· lasciato com’è, illeggibile ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Converti la colonna in ISO 8601 (AAAA-MM-GG)",
        "Quy ước số cho cả cột": "Convenzione numerica per tutta la colonna",
        "Làm gì với ô thiếu": "Cosa fare con le celle vuote",
        "Chuẩn hóa về ISO 8601": "Normalizza in ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Leggi le celle ambigue con il GIORNO prima (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Leggi le celle ambigue con il MESE prima (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Salta le celle ambigue, correggi solo quelle certe",
        "Về Việt/Âu (1.234,56)": "In vietnamita/europeo (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "In angloamericano (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "In angloamericano, senza separatore delle migliaia (1234.56)",
        "Điền một giá trị mặc định…": "Riempi con un valore predefinito…",
        "Điền xuôi — lấy giá trị phía trên": "Riempi verso il basso — prendi il valore sopra",
        "Điền ngược — lấy giá trị phía dưới": "Riempi verso l’alto — prendi il valore sotto",
        "Xóa hàng có ô thiếu ở cột này": "Elimina le righe con cella vuota in questa colonna",
        "Cắt khoảng trắng hai đầu": "Rimuovi gli spazi a entrambe le estremità",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Rimuovi alle estremità e comprimi gli spazi interni",
        "Pivot…": "Tabella pivot…",
        "Nguồn…": "Sorgenti…",
        "Pivot — gộp theo cột": "Tabella pivot — raggruppa per colonna",
        "Hàng (gộp nhóm)": "Righe (raggruppamento)",
        "Giá trị": "Valori",
        "+ Hàng": "+ Riga",
        "+ Giá trị": "+ Valore",
        "Xoá hết": "Cancella tutto",
        "Đưa vào ô truy vấn": "Metti nella query",
        "Chọn cột để dựng câu truy vấn.": "Scegli le colonne per costruire la query.",
        "Không đọc được tên cột của bảng này.": "Impossibile leggere i nomi di colonna di questa tabella.",
        "Nguồn dữ liệu của truy vấn": "Sorgenti dati della query",
        "«%@» — tài liệu đang mở": "«%@» — il documento aperto",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ il file è cambiato da quando è stato registrato",
        "Thêm file…": "Aggiungi file…",
        "Bỏ hết": "Rimuovi tutto",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Impossibile dedurre un nome di tabella da «%@» — rinomina il file.",
        "Tổng": "Somma",
        "Trung bình": "Media",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Max",
        "Đếm khác nhau": "Conteggio distinto",
        "Biểu đồ": "Grafico",
        "Xuất PNG": "Esporta PNG",
        "Xuất SVG": "Esporta SVG",
        "Bảng này không có cột số nào để vẽ.": "Questa tabella non ha alcuna colonna numerica da rappresentare.",
        "Không dựng được ảnh PNG.": "Impossibile costruire l’immagine PNG.",
        "Kết quả truy vấn": "Risultato della query",
        "Đã lưu %@": "%@ salvato",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Grafico %@ di «%@» — %d {one=punto|other=punti}, valori da %@ a %@",
        "Cột": "Barre",
        "Đường": "Linea",
        "Phân bố": "Istogramma",
        "Phân tán": "Dispersione",
        "Hộp": "Box",
        "CSV: chất lượng dữ liệu…": "CSV: qualità dei dati…",
        "Chất lượng dữ liệu": "Qualità dei dati",
        "Xuất vi phạm ra tab mới": "Esporta le violazioni in una nuova scheda",
        "Mức": "Livello",
        "Luật": "Regola",
        "Vi phạm": "Violazioni",
        "Tỷ lệ": "Tasso",
        "đạt": "superato",
        "lỗi": "errore",
        "cảnh báo": "avviso",
        "hỏng": "rotto",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=riga in violazione segnata|other=righe in violazione segnate}",
        "Xu hướng": "Andamento",
        "Lúc chấm": "Valutato il",
        "Số hàng": "Righe",
        "Lệch": "Scarto",
        "Luật trượt": "Regole fallite",
        "Điểm chất lượng": "Punteggio di qualità",
        "Điểm theo thời gian": "Punteggio nel tempo",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Ancora nessuna cronologia — ogni valutazione aggiunge ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "una riga al file «.history.jsonl» accanto alle regole.",
        "%d mốc trong lịch sử": "%d {one=punto|other=punti} nella cronologia",
        " · %d dòng KHÔNG đọc được": " · %d {one=riga ILLEGGIBILE|other=righe ILLEGGIBILI}",
        " · chọn hai dòng để so": " · seleziona due righe per confrontare",
        "điểm %+.1f": "punteggio %+.1f",
        "không chiều nào tụt": "nessuna dimensione è scesa",
        "tụt: ": "scese: ",
        "%d luật mới trượt: %@": "%d {one=regola che ora fallisce|other=regole che ora falliscono}: %@",
        "số hàng %+d": "righe %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (e %d {one=altro avviso|other=altri avvisi} nella scheda Andamento)",
        "Không sửa tự động được: ": "Nessuna correzione automatica: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Apre lo strumento corrispondente nel Banco di pulizia, poi rivaluta subito.",
        "Xử lý giá trị thiếu…": "Gestisci i valori mancanti…",
        "Chuẩn hóa ngày…": "Normalizza le date…",
        "Khử trùng lặp…": "Rimuovi i duplicati…",
        "Thay thế…": "Sostituisci…",
        "Xem các dòng sai": "Mostra le righe errate",
        "Không tìm thấy cột «%@» trong bảng này.": "La colonna «%@» non è in questa tabella.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplicati rimossi — «%@» ora è univoca. Punteggio: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplicati rimossi, ma «%@» ha ancora %d {one=riga ripetuta|other=righe ripetute} (prima: %d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "quelle righe condividono la CHIAVE ma non l’intera riga, quindi devi guardarle e scegliere ",
        "giữ hàng nào.": "quale tenere.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Impossibile leggere un valore che violi questa regola.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%d {one=valore errato|other=valori errati} nella colonna «%@» — compila Sostituisci e premi Anteprima",
        "Đã chấm lại: %.0f/100": "Rivalutato: %.0f/100",
        "Xem trước báo cáo": "Anteprima del rapporto",
        "Tham số…": "Parametri…",
        "Xuất HTML…": "Esporta HTML…",
        "In / PDF…": "Stampa / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=blocco eseguito|other=blocchi eseguiti} · %d {one=blocco FALLITO|other=blocchi FALLITI}",
        "%d khối chạy được": "%d {one=blocco eseguito|other=blocchi eseguiti}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · DATI OBSOLETI — il file sorgente è cambiato; ricostruisci",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "L’anteprima del rapporto richiede un documento .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Nessuna sorgente dati trovata — dichiara «source: file.csv» nel frontmatter.",
        "Không dựng được báo cáo.": "Impossibile costruire il rapporto.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Questo rapporto non dichiara alcun parametro nel frontmatter.",
        "Tham số báo cáo": "Parametri del rapporto",
        "Dựng lại": "Ricostruisci",
        "Đã xuất %@": "%@ esportato",
        "Báo cáo: xem trước": "Rapporto: anteprima",
        "Báo cáo: sinh loạt…": "Rapporto: generazione in blocco…",
        "không phải tài liệu .greport.md": "non è un documento .greport.md",
        "không phân tích được báo cáo": "impossibile analizzare il rapporto",
        "không tìm được dữ liệu nguồn": "impossibile trovare i dati sorgente",
        "không đọc được danh sách tham số": "impossibile leggere l’elenco dei parametri",
        "Sinh loạt cần tài liệu đuôi .%@": "La generazione in blocco richiede un documento .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Scegli un elenco di parametri (CSV o JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Scegli una cartella per %d {one=rapporto|other=rapporti}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "parametri mancanti ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "punta al file sorgente stesso — sovrascrittura rifiutata",
        "%d khối HỎNG": "%d {one=blocco FALLITO|other=blocchi FALLITI}",
        "Sinh loạt xong: %d tệp · %d hỏng": "Blocco completato: %d {one=file|other=file} · %d falliti",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=set di parametri non è stato costruito|other=set di parametri non sono stati costruiti} — vedi il riepilogo",
        "Sơ đồ Mermaid: xem trước": "Diagramma Mermaid: anteprima",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagramma Mermaid: inserisci un modello…",
        "Sơ đồ Mermaid: định dạng lại": "Diagramma Mermaid: riformatta",
        "Nền trong suốt": "Sfondo trasparente",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Questo Mac non può convertire il diagramma in PNG — serve macOS 13. L’esportazione SVG funziona comunque.",
        "Lưu PNG %@…": "Salva PNG %@…",
        "Lưu SVG…": "Salva SVG…",
        "Chép ảnh vào clipboard": "Copia l’immagine negli appunti",
        "Màu thương hiệu…": "Colori del marchio…",
        "Màu thương hiệu cho sơ đồ": "Colori del marchio per i diagrammi",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Ogni campo è un colore #rrggbb. Salvato in «themes/mermaid-brand.json» — copiabile su un altro Mac.",
        "Màu chính": "Colore principale",
        "Chữ trên nút": "Testo sui nodi",
        "Viền": "Bordo",
        "Đường nối": "Collegamenti",
        "Nền khi xuất ảnh": "Sfondo all’esportazione",
        "Lưu và chèn %%{init}%% vào tài liệu": "Salva e inserisci %%{init}%% nel documento",
        "Đã lưu màu thương hiệu": "Colori del marchio salvati",
        "Đã chép ảnh sơ đồ vào clipboard": "Immagine del diagramma copiata negli appunti",
        "Đã lưu %@ — %@": "%@ salvato — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Questo diagramma ha già una direttiva %%{init}%% — la tua resta intatta.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% inserito — il diagramma porta ora i propri colori",
        "Chèn màu thương hiệu vào sơ đồ": "Inserisci i colori del marchio nel diagramma",
        "Định dạng sơ đồ Mermaid": "Riformatta il diagramma Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Il codice del diagramma è già in ordine — nulla da cambiare",
        "Đã định dạng lại sơ đồ": "Diagramma riformattato",
        "Đã định dạng lại %d sơ đồ": "%d {one=diagramma riformattato|other=diagrammi riformattati}",
        "Thư viện mẫu sơ đồ": "Libreria di modelli di diagramma",
        "Mẫu sơ đồ đầy đủ": "Modelli di diagramma completi",
        "Mẩu cú pháp": "Frammenti di sintassi",
        "Đang soạn: %@": "In modifica: %@",
        "Đã chèn mẫu «%@»": "Modello «%@» inserito",
        "Tài liệu đang ở chế độ chỉ đọc.": "Questo documento è di sola lettura.",
        "Sơ đồ Mermaid": "Diagramma Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Questo documento non ha alcun blocco mermaid.",
        "Thương hiệu": "Marchio",
        "Xuất…": "Esporta…",
        "Chưa có sơ đồ nào": "Ancora nessun diagramma",
        "%d sơ đồ · %@": "%d {one=diagramma|other=diagrammi} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%d/%d {one=diagramma FALLITO|other=diagrammi FALLITI} — diagramma %d%@",
        ", dòng %d": ", riga %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Questo documento non ha alcun blocco ```mermaid e non è nemmeno un file .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Nessun diagramma ha finito di essere disegnato.",
        "Không tìm thấy «%@» trong mã sơ đồ": "«%@» non è stato trovato nel codice del diagramma",
        "không dựng được hàng rào chặn mạng cho WKWebView": "impossibile costruire la barriera di rete per WKWebView",
        "Luật kết hợp": "Regole di associazione",
        "Mỗi dòng một giỏ": "Un carrello per riga",
        "Hai cột: mã · item": "Due colonne: id · articolo",
        "Dạng dữ liệu giao dịch": "Forma dei dati transazionali",
        "Cột giỏ hàng hoặc mã giao dịch": "Colonna carrello o id transazione",
        "Cột item": "Colonna articolo",
        "Ký tự phân tách item": "Carattere separatore degli articoli",
        "Support tối thiểu, phần trăm": "Supporto minimo, percentuale",
        "Confidence tối thiểu, phần trăm": "Confidenza minima, percentuale",
        "Tách bởi:": "Separato da:",
        "Support \u{2265}": "Supporto ≥",
        "% · Confidence \u{2265}": "% · Confidenza ≥",
        "Bảng luật kết hợp": "Tabella delle regole di associazione",
        "Support": "Supporto",
        "Confidence": "Confidenza",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Attenzione",
        "%d giao dịch · %d item · %d luật": "%d {one=transazione|other=transazioni} · %d {one=articolo|other=articoli} · %d {one=regola|other=regole}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — nessuna regola ha raggiunto le soglie; abbassa supporto o confidenza",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — FERMATO IN ANTICIPO, la tabella è INCOMPLETA",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transazione contiene|other=transazioni contengono} entrambi i lati",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "La forma a due colonne richiede due colonne DIVERSE.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%d {one=riga segnata|other=righe segnate} in %d {one=transazione che contiene|other=transazioni che contengono} «%@»",
        "CSV: luật kết hợp…": "CSV: regole di associazione…",
        "Khai phá theo nhóm": "Mining per gruppi",
        "Cột nhóm": "Colonna di gruppo",
        "Cột giá trị": "Colonna dei valori",
        "Cột thứ hai cho tương quan": "Seconda colonna per la correlazione",
        "Cách xếp hạng": "Criterio di classifica",
        "Nhóm theo:": "Raggruppa per:",
        "Giá trị:": "Valore:",
        "Xếp theo:": "Ordina per:",
        "Bảng xếp hạng nhóm": "Tabella di classifica dei gruppi",
        "Nhóm": "Gruppo",
        "Hàng": "Righe",
        "Hàng rào riêng": "Soglia propria",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "Scarto r",
        "Ghi chú": "Nota",
        "không đo được": "non misurabile",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=gruppo|other=gruppi} · correlazione globale di riferimento %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GRUPPO SCARTATO|other=GRUPPI SCARTATI}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Questa tabella non ha alcuna colonna di testo per raggruppare.",
        "Bảng này không có cột số nào để khai phá.": "Questa tabella non ha alcuna colonna numerica da esplorare.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%d {one=riga del gruppo|other=righe del gruppo} «%@» {one=segnata|other=segnate}",
        "CSV: khai phá theo nhóm…": "CSV: mining per gruppi…",
        "\u{2194}": "↔",
        "Dự báo": "Previsione",
        "Cột giá trị theo thời gian": "Colonna dei valori nel tempo",
        "Mô hình dự báo": "Modello di previsione",
        "Số kỳ dự báo": "Numero di periodi da prevedere",
        "Kết luận so với baseline": "Verdetto rispetto ai modelli di riferimento",
        "Mô hình:": "Modello:",
        "Số kỳ:": "Periodi:",
        "Chu kỳ:": "Stagione:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Periodo stagionale; lascia vuoto per il rilevamento automatico",
        "Bảng giá trị dự báo": "Tabella dei valori previsti",
        "Kỳ": "Periodo",
        "Dải 80%": "Banda all’80 %",
        "Dải 95%": "Banda al 95 %",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "non calcolabile",
        "Bảng này không có cột số nào để dự báo.": "Questa tabella non ha alcuna colonna numerica da prevedere.",
        "Không dựng được dự báo cho cột này.": "Impossibile costruire una previsione per questa colonna.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "La colonna «%@» ha solo %d {one=valore numerico|other=valori numerici} — ne servono almeno 4 per prevedere.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# La serie viene letta nell’ordine delle righe del file — senza riordinare, senza dedurre una colonna temporale.\n",
        "Sai số huấn luyện": "Errore di addestramento",
        "CSV: dự báo chuỗi thời gian…": "CSV: previsione di serie temporali…",
        "Holt-Winters cộng": "Holt-Winters additivo",
        "Holt-Winters nhân": "Holt-Winters moltiplicativo",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Colonne usate per il clustering",
        "Đường cong WCSS": "Curva WCSS",
        "Phân cụm": "Cluster",
        "Chuẩn hoá:": "Scalatura:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Seleziona almeno una colonna.",
        "Không đủ dữ liệu để dựng đường cong.": "Dati insufficienti per costruire la curva.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Il gomito suggerisce k = %d. Il WCSS scende SEMPRE al crescere di k, quindi è un accorgimento di lettura del grafico e non un criterio statistico — guarda la curva e giudica se la piega è netta.",
        "WCSS theo k": "WCSS per k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "La k-distanza suggerisce eps = %@ (minPts vale per default 2 × numero di colonne = %d). %@",
        "Khoảng cách tới hàng xóm thứ k": "Distanza dal k-esimo vicino",
        "Cần ít nhất 2 cột số để phân cụm.": "Per il clustering servono almeno 2 colonne numeriche.",
        "Cụm theo %@ và %@": "Cluster per %@ e %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — cluster trovati in %d {one=dimensione|other=dimensioni}; il grafico mostra solo le prime 2",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# rumore (cluster_id = -1): %d {one=riga|other=righe}\n",
        "CSV: phân cụm…": "CSV: clustering…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Centri dei cluster (unità originali) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Matrice di correlazione",
        "Phương pháp tương quan": "Metodo di correlazione",
        "Tương quan không hàm ý nhân quả.": "Correlazione non implica causalità.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Coppia più forte: %@ ↔ %@ = %@ (n = %d). Fai clic su una cella per il grafico a dispersione.",
        "Không cặp nào đo được.": "Nessuna coppia è misurabile.",
        "%@ ↔ %@: %@ trên %d hàng": "%@ ↔ %@: %@ su %d {one=riga|other=righe}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Per la correlazione servono almeno 2 colonne numeriche.",
        "Không đọc được cột «%@».": "Impossibile leggere la colonna «%@».",
        "CSV: ma trận tương quan…": "CSV: matrice di correlazione…",
        "Bất thường": "Anomalie",
        "Danh sách bất thường": "Elenco delle anomalie",
        "Cột:": "Colonna:",
        "Cột số cần xét": "Colonna numerica da esaminare",
        "Cách:": "Metodo:",
        "Phương pháp phát hiện": "Metodo di rilevamento",
        "Phương pháp đã dùng": "Metodo usato",
        "Ngưỡng": "Soglia",
        "Đánh dấu": "Segna",
        "Xuất tab mới": "Esporta in una nuova scheda",
        "Dòng": "Riga",
        "Điểm": "Punteggio",
        "Vì sao": "Perché",
        "nhẹ": "lieve",
        "vừa": "moderata",
        "nặng": "grave",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=riga|other=righe} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Questa tabella non ha alcuna colonna numerica in cui cercare anomalie.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=riga anomala segnata|other=righe anomale segnate}",
        "CSV: tìm bất thường…": "CSV: trova anomalie…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%d {one=regola, SUPERATA|other=regole, tutte SUPERATE} · %d {one=riga|other=righe} · %.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%d {one=errore|other=errori} · %d {one=avviso|other=avvisi} su %d {one=regola|other=regole} · %d {one=riga|other=righe} · %.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Salva prima il documento — le regole di qualità stanno accanto al file di dati.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Nessun set di regole. Crea il file %@ e riapri.",
        "Lịch sử": "Cronologia",
        "Câu đã lưu": "Query salvate",
        "Lưu câu này…": "Salva questa query…",
        "Lưu câu truy vấn": "Salva la query",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Dalle un nome per ritrovarla dopo. Lo stesso nome sovrascrive.",
        "Ví dụ: Doanh thu theo tỉnh": "Per esempio: Ricavi per provincia",
        "Chưa nhập giá trị cho tham số: %@": "Nessun valore inserito per il parametro: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "L’estensione è cambiata da quando l’hai approvata — GEditor si rifiuta di eseguirla",
        "Chạy plugin chưa duyệt?": "Eseguire un’estensione non approvata?",
        "Tôi tin file này — chạy": "Mi fido di questo file — esegui",
        "KHÔNG có chữ ký": "NON firmata",
        "Chữ ký: %@": "Firma: %@",
        "Đường dẫn: %@": "Percorso: %@",
        "Thay": "Sostituisci",
        "Thay tất cả": "Sostituisci tutto",
        "Chuỗi thuần": "Testo semplice",
        "Extended (\\n \\t \\xNN)": "Esteso (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Espressione regolare",
        "Phân biệt hoa thường": "Distingui maiuscole",
        "Cả từ": "Parola intera",
        "Không có kết quả": "Nessun risultato",
        "Thử biểu thức chính quy…": "Prova un’espressione regolare…",
        "Chế độ Log (tô theo mức)": "Modalità log (colore per livello)",
        "Lọc log theo mức…": "Filtra il log per livello…",
        "Chạy trên cả thư mục…": "Esegui sull’intera cartella…",
        "Lọc qua lệnh ngoài…": "Filtra con un comando esterno…",
        "Script…": "Script…",
        "Gói mở rộng…": "Pacchetti di estensione…",
        "Cửa sổ mới": "Nuova finestra",
        "Tách tab ra cửa sổ mới": "Stacca la scheda in una nuova finestra",
        "Chưa mở thư mục nào": "Nessuna cartella aperta",
        "Tìm file trong thư mục": "Cerca un file nella cartella",
        "Lọc theo tên": "Filtra per nome",
        "File mới…": "Nuovo file…",
        "Thư mục mới…": "Nuova cartella…",
        "Đổi tên…": "Rinomina…",
        "Chuyển vào Thùng rác": "Sposta nel Cestino",
        "Hiện trong Finder": "Mostra nel Finder",
        "Đang đọc cấu trúc tài liệu…": "Lettura della struttura del documento…",
        "file này không có hàm nào": "questo file non ha funzioni",
        "Không có gì khớp": "Nessuna corrispondenza",
        "Văn bản thuần": "Testo semplice",
        "🔒 Chỉ đọc": "🔒 Sola lettura",
        "Đang theo dõi": "In ascolto",
        "ngắt tại cột": "a capo alla colonna",
        "Cú pháp": "Sintassi",
        "Bấm để chèn vào ô truy vấn": "Fai clic per inserire nella query",
        "truy vấn không hợp lệ": "query non valida",
        "khóa `ten` ở gốc": "chiave «nome» alla radice",
        "khóa có dấu cách": "chiave con spazi",
        "phần tử đầu": "primo elemento",
        "mọi phần tử": "tutti gli elementi",
        "lát cắt": "porzione",
        "hợp nhiều chỉ số": "unione di indici",
        "mọi khóa `gia` ở mọi tầng": "tutte le chiavi «prezzo» a ogni livello",
        "mọi nút": "tutti i nodi",
        "lọc theo số": "filtra per numero",
        "lọc theo có mặt": "filtra per presenza",
        "Tới lỗi đầu tiên": "Vai al primo errore",
        "Cột doanh_thu là số": "La colonna ricavi è numerica",
        "lọc…": "filtra…",
        "Hủy": "Annulla",
        "Thực hiện thay": "Esegui la sostituzione",
        "xem trước": "anteprima",
        "tương tác": "interattivo",
        "Soạn thảo": "Modifica",
        "Giao diện": "Interfaccia",
        "Phím tắt": "Scorciatoie da tastiera",
        "Cỡ chữ": "Dimensione del testo",
        "Bề rộng TAB": "Larghezza della tabulazione",
        "Thụt lề bằng TAB": "Indenta con tabulazioni",
        "Tự động thụt lề khi xuống dòng": "Indenta automaticamente andando a capo",
        "Tô mọi kết quả tìm kiếm": "Evidenzia tutti i risultati della ricerca",
        "Chuẩn hóa về NFC khi lưu": "Normalizza in NFC al salvataggio",
        "Ngôn ngữ": "Lingua",
        "Nền": "Aspetto",
        "Theo hệ thống": "Di sistema",
        "Sáng": "Chiaro",
        "Tối": "Scuro",
        "Theme": "Tema",
        "Dùng preset Notepad++": "Usa il preset di Notepad++",
        "Về phím mặc định": "Torna ai tasti predefiniti",
        "Mở file cấu hình": "Apri il file di configurazione",
        "Xuất theme hiện tại": "Esporta il tema attuale",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Il cambio di lingua si applica del tutto al prossimo avvio.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "I tasti predefiniti tornano al prossimo avvio.",
        "Xem trước Markdown": "Anteprima Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "L’anteprima usa il motore Markdown di sistema: ancora senza tabelle né colorazione dei blocchi di codice.",
        "Thử biểu thức chính quy": "Prova un’espressione regolare",
        "Biểu thức": "Espressione",
        "Văn bản thử": "Testo di prova",
        "Kết quả": "Risultato",
        "Kết quả khớp": "Corrispondenze",
        "Biểu thức này làm gì": "Cosa fa questa espressione",
        "Giải thích biểu thức": "Spiega l’espressione",
        "Chế độ tìm kiếm": "Modalità di ricerca",
        "Kết quả tìm kiếm": "Risultati della ricerca",
        "Không khớp chỗ nào": "Nessuna corrispondenza",
        " (đã cắt bớt)": " (troncato)",
        "Bản đồ tài liệu": "Mappa del documento",
        "Thanh tab": "Barra delle schede",
        "Hàng tiêu đề cột": "Riga di intestazione delle colonne",
        "Không có cột nào": "Nessuna colonna",
        "Cây thư mục workspace": "Albero dell’area di lavoro",
        "Danh sách hàm và lớp": "Elenco di funzioni e classi",
        "Kết quả tìm trong thư mục": "Risultati della ricerca nella cartella",
        "Bảng dữ liệu CSV": "Tabella dati CSV",
        "Bàn làm sạch dữ liệu": "Banco di pulizia dei dati",
        "Truy vấn JSONPath": "Query JSONPath",
        "Danh sách lỗi dữ liệu": "Elenco degli errori nei dati",
        "Bộ đánh giá golden set…": "Valutatore del golden set…",
        "So với điểm ngoài (JSONL)…": "Confronta con punteggi esterni (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Scegli un file di punteggi esterni (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Rinomina il nodo selezionato",
        "Gộp các node đang chọn": "Unisci i nodi selezionati",
        "Tách node đang chọn": "Dividi il nodo selezionato",
        "Trích subgraph đang chọn ra tab mới": "Estrai il sottografo selezionato in una nuova scheda",
        "Không có gì để đổi": "Nulla da cambiare",
        "%@ — áp %d thay đổi?": "%@ — applicare %d {one=modifica|other=modifiche}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%@: %d {one=modifica|other=modifiche} · Cmd-Z annulla l’intero blocco",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Metti il cursore su ESATTAMENTE UN nodo e riprova",
        "Đổi tên «%@»": "Rinomina «%@»",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Tutti gli archi e le etichette che fanno riferimento a questo nodo cambieranno con esso.",
        "Đổi tên node": "Rinomina il nodo",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Seleziona ALMENO DUE nodi e riprova",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Forma canonica «%@» — la più frequente, la più lunga, accentata",
        "Gộp node": "Unisci i nodi",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Seleziona le RIGHE DI ARCO da spostare e riprova",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Tutte le righe selezionate devono toccare ESATTAMENTE UN nodo — seleziona altre righe di arco",
        "Tách «%@» — chuyển %d cạnh": "Dividi «%@» — sposta %d {one=arco|other=archi}",
        "Cạnh tới: %@": "Archi verso: %@",
        "Tách node": "Dividi il nodo",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Documento non salvato — il file estratto ha bisogno di un posto accanto",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Seleziona la parte del grafo da estrarre e riprova",
        "Gom biến thể entity → bảng duyệt": "Raggruppa le varianti di entità → tabella di revisione",
        "Áp bảng duyệt đã sửa": "Applica la tabella di revisione modificata",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Documento non salvato — la tabella di revisione deve stare accanto al file del grafo",
        "Không tìm thấy biến thể nào để gom": "Nessuna variante da raggruppare",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=gruppo di varianti|other=gruppi di varianti} — correggi la colonna «canonical» ed esegui «Applica la tabella di revisione»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Nessuna tabella di revisione «%@» — esegui prima «Raggruppa le varianti di entità»",
        "Bảng duyệt không đọc được: %@": "Tabella di revisione illeggibile: %@",
        "Bảng duyệt không có dòng nào cần đổi": "La tabella di revisione non ha righe da cambiare",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Nessun punto del grafo corrisponde alla tabella di revisione",
        "Gom biến thể entity": "Raggruppa le varianti di entità",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=modifica applicata|other=modifiche applicate} · tabella di alias ed elenco di marcatori scritti accanto al file",
        "Áp %d thay đổi lên đồ thị?": "Applicare %d {one=modifica|other=modifiche} al grafo?",
        "%d alias → dạng chuẩn.": "%d {one=alias|other=alias} → forma canonica.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "UNIRE i nodi (non si annulla riscrivendo):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias non è nel grafo e viene saltato|other=alias non sono nel grafo e vengono saltati}.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Analisi di copertura Frammento ↔ Entità",
        "Xuất gói ngữ cảnh (JSONL)": "Esporta il pacchetto di contesto (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Copertura Frammento ↔ Entità ↔ Grafo",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %d {one=entità|other=entità} · %d {one=frammento|other=frammenti} · %.0f %% di entità citate · %.0f %% di frammenti con entità",
        "Entity không chunk nào nhắc tới": "Entità che nessun frammento cita",
        "Chunk mồ côi (không chứa entity nào)": "Frammenti orfani (senza alcuna entità)",
        "Node đồ thị không có entity đối ứng": "Nodi del grafo senza entità corrispondente",
        "không có": "nessuno",
        "Phương pháp": "Metodo",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Impossibile costruire la corrispondenza Frammento ↔ Entità",
        "Chấm sức khoẻ đồ thị": "Valuta la salute del grafo",
        "sức khoẻ đồ thị": "salute del grafo",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Salute %@/100 · %d {one=errore|other=errori} · %d {one=inversione|other=inversioni} · %d orfani",
        "Lai với đồ thị": "Ibrido con il grafo",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: il segnale del grafo è del tutto ignorato, il risultato coincide con BM25 puro",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α alto: il grafo regola solo leggermente la classifica di BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α intorno al valore predefinito 0,7: comanda BM25, il grafo regola",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α basso: comanda il grafo, BM25 rompe solo la parità",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: solo il segnale del grafo; i frammenti senza entità restano a pari merito",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Documento non salvato — l’ibrido ha bisogno di un file di grafo accanto al corpus",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "File di grafo «%@» non trovato — l’ibrido ne ha bisogno per il suo segnale",
        "lai %.1f ms · %@": "ibrido %.1f ms · %@",
        "Thuật toán…": "Algoritmi…",
        "PageRank (độ dày viền)": "PageRank (spessore del bordo)",
        "Cộng đồng (màu nền)": "Comunità (colore di sfondo)",
        "Thành phần liên thông": "Componenti connesse",
        "Xuất bảng node ra tab mới": "Esporta la tabella dei nodi in una nuova scheda",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%d {one=componente|other=componenti} · la più grande %d {one=nodo|other=nodi} · %d nodi orfani",
        "Tài liệu này không phải đồ thị DOT": "Questo documento non è un grafo DOT",
        "Không dựng được bảng node/cạnh: %@": "Impossibile costruire la tabella di nodi/archi: %@",
        "%d hàng · %@": "%d {one=riga|other=righe} · %@",
        "Gán nhãn": "Etichetta",
        "Ghi chú (tuỳ chọn)": "Nota (facoltativa)",
        "Lưu record": "Salva il record",
        "Xuất CSV": "Esporta CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Documento non salvato — il valutatore deve stare accanto al file di corpus",
        "Không nạp được bộ đánh giá: %@": "Impossibile caricare il valutatore: %@",
        "Không lưu được: %@": "Impossibile salvare: %@",
        "Bộ đánh giá chưa có record nào": "Il valutatore non ha ancora alcun record",
        "Không ghi được: %@": "Impossibile scrivere: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Questo documento non è un file .mmd, non è DOT e non ha alcun blocco mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=nodo|other=nodi} · %d {one=arco|other=archi} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagramma Mermaid: aggiungi un elemento…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagramma Mermaid: collega i due elementi selezionati",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagramma Mermaid: modifica l’etichetta dell’elemento selezionato…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagramma Mermaid: elimina l’elemento selezionato",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagramma Mermaid: sposta il messaggio in su",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagramma Mermaid: sposta il messaggio in giù",
        "Thêm phần tử": "Aggiungi un elemento",
        "Thêm participant": "Aggiungi un partecipante",
        "Thêm mục": "Aggiungi una voce",
        "Thêm mục sơ đồ": "Aggiungi una voce al diagramma",
        "Sửa mục sơ đồ": "Modifica una voce del diagramma",
        "Xoá mục sơ đồ": "Elimina una voce del diagramma",
        "Xoá phần tử": "Elimina l’elemento",
        "Sửa nhãn": "Modifica l’etichetta",
        "Đổi thứ tự message": "Riordina i messaggi",
        "Tên mục": "Nome della voce",
        "Mục mới": "Nuova voce",
        "Tên mục hiện trên sơ đồ.": "Il nome della voce appare sul diagramma.",
        "Bảng thuộc tính sơ đồ": "Tabella delle proprietà del diagramma",
        "Tài liệu này không có khối mermaid nào": "Questo documento non ha alcun blocco mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identificatore nel codice del diagramma — senza spazi. L’etichetta si modifica poi con un doppio clic.",
        "Để trống thì hiện chính định danh.": "Se lasciato vuoto, viene mostrato l’identificatore stesso.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Cambia solo l’ETICHETTA visibile; l’identificatore dell’elemento resta lo stesso.",
        "Không rõ «%@» là phần tử nào": "Non è chiaro quale elemento sia «%@»",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Seleziona ESATTAMENTE DUE elementi e riprova",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Metti il cursore su ESATTAMENTE UN elemento e riprova",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Scegli UN elemento da eliminare, o due elementi collegati da un arco",
        "Xoá «%@» và %d cạnh chạm nó?": "Eliminare «%@» e %d {one=arco che lo tocca|other=archi che lo toccano}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "I nodi all’altro capo di quegli archi vengono conservati — sono ridichiarati con la loro etichetta se l’istruzione di arco era la loro unica dichiarazione.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Il diagramma «%@» si modifica solo come testo — %@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: trascina tra due elementi per collegarli, doppio clic per modificare l’etichetta",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: trascina tra due partecipanti per aggiungere un messaggio; riordina dal menu Strumenti",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: modifica nella tabella delle proprietà qui sotto",
        "Soạn trực quan đã bật": "Modifica visuale attivata",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%@ · %d {one=voce|other=voci} — modifica direttamente nella tabella, ogni cella è un passo di annullamento",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Per un grafico a torta un numero; per un gantt, ciò che segue i due punti.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagramma Mermaid: estrai il blocco in un file .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagramma Mermaid: reincorpora il file referenziato",
        "Tách khối sơ đồ": "Estrai il blocco del diagramma",
        "Nhúng khối sơ đồ": "Reincorpora il blocco del diagramma",
        "Tách khối sơ đồ ra tệp riêng": "Estrai il blocco del diagramma in un file separato",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Il file viene messo ACCANTO al documento; il blocco conserva una riga di riferimento per modificare in un solo posto.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Documento non salvato — il file del diagramma ha bisogno di un posto accanto",
        "Đã có tệp «%@» — chọn tên khác": "Il file «%@» esiste già — scegli un altro nome",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Estratto in «%@» — il blocco conserva una riga di riferimento",
        "Mở tệp": "Apri il file",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» reincorporato; il file resta sul disco",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Questo blocco contiene un diagramma vero, non un riferimento",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Questo blocco fa riferimento a «%@» — apri quel file per modificarlo",
        "Không đọc được tệp sơ đồ %@": "Impossibile leggere il file di diagramma %@",
        "Soạn trực quan": "Modifica visuale",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Trascina da un nodo all’altro per aggiungere un arco; doppio clic per modificare l’etichetta. Ogni azione è un passo di annullamento.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Modifica visuale: trascina tra due nodi per aggiungere un arco, doppio clic per modificare l’etichetta",
        "Soạn trực quan đã tắt": "Modifica visuale disattivata",
        "Thêm node…": "Aggiungi un nodo…",
        "Thêm cạnh giữa hai node đang chọn…": "Aggiungi un arco tra i due nodi selezionati…",
        "Sửa nhãn node đang chọn…": "Modifica l’etichetta del nodo selezionato…",
        "Xoá node/cạnh đang chọn": "Elimina il nodo/arco selezionato",
        "Thêm node": "Aggiungi un nodo",
        "Thêm cạnh": "Aggiungi un arco",
        "Sửa nhãn node": "Modifica l’etichetta del nodo",
        "Xoá node": "Elimina il nodo",
        "Xoá cạnh": "Elimina l’arco",
        "Cmd-Z hoàn tác": "Cmd-Z annulla",
        "Tài liệu đang ở chế độ chỉ đọc": "Questo documento è di sola lettura",
        "Nhãn của «%@»": "Etichetta di «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Cambia solo l’ETICHETTA visibile; l’identificatore del nodo resta lo stesso.",
        "Không rõ «%@» là node nào": "Non è chiaro quale nodo sia «%@»",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identificatore del nodo nel file DOT. L’etichetta si modifica poi con un doppio clic sul grafico.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Seleziona ESATTAMENTE DUE nodi e riprova",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Scegli UN nodo da eliminare, o due nodi collegati da un arco",
        "Xoá node «%@» và %d cạnh chạm nó?": "Eliminare il nodo «%@» e %d {one=arco che lo tocca|other=archi che lo toccano}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Se restano archi orfani, DOT ricrea i nodi da essi — il nodo eliminato ricomparirà al disegno successivo.",
        "Phòng thí nghiệm truy hồi BM25": "Laboratorio di retrieval BM25",
        "Câu hỏi — Enter để tìm": "Domanda — Invio per cercare",
        "Đánh giá…": "Valuta…",
        "Đang dựng chỉ mục": "Costruzione dell’indice",
        "Không chunk nào khớp": "Nessun frammento corrisponde",
        "kết quả trên": "risultati migliori",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: ogni parola conta SOLO una volta, per quante volte compaia",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 basso: ripetere una parola non aggiunge quasi punteggio",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 intorno al valore predefinito 1,2: ripetere aggiunge punteggio, ma sempre meno",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 alto: un frammento che ripete una parola viene premiato molto",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: la lunghezza è ignorata, i frammenti lunghi non sono penalizzati",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b basso: i frammenti lunghi sono penalizzati solo un poco",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b intorno al valore predefinito 0,75: i frammenti lunghi sono penalizzati moderatamente",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: penalità massima per la lunghezza, i frammenti corti sono favoriti",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: laboratorio di retrieval…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Documento non salvato — l’indice BM25 sta accanto al file di corpus e ha quindi bisogno di un percorso",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Questo file non è JSONL — il Retrieval Lab lavora su un corpus di frammenti",
        "Không dựng được chỉ mục BM25 cho tệp này": "Impossibile costruire un indice BM25 per questo file",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Documento non salvato — serve un percorso di corpus per generare il rapporto",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Scegli un set di valutazione (CSV o JSONL: domanda + id del frammento atteso)",
        "Đánh giá truy hồi": "Valutazione del retrieval",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Cambia k1, b o k qui sopra e riesamina per confrontare due configurazioni; aggiungi un blocco «compare» per eseguire due set di parametri in parallelo sullo stesso set di valutazione.",
        "Lỗi": "Errore",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, media %.0f)",
        "Chế độ JSONL": "Modalità JSONL",
        "Bản ghi": "Record",
        "Chi tiết": "Dettaglio",
        "Bản ghi ở dòng": "Record alla riga",
        "không phải JSON hợp lệ": "non è JSON valido",
        "bản ghi": "record",
        "dòng trắng": "righe vuote",
        "không phải đối tượng": "non è un oggetto",
        "bảng hiện": "tabella mostrata",
        "ĐÃ HUỶ giữa chừng": "ANNULLATO a metà",
        "Không lọc": "Nessun filtro",
        "bản ghi khớp bộ lọc": "record che corrispondono al filtro",
        "Đưa con nháy tới một dòng để xem bản ghi": "Metti il cursore su una riga per vedere il record",
        "Không có bản ghi nào hỏng": "Nessun record difettoso",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Non ancora ispezionato. Riesegui «JSONL: ispeziona i frammenti» dopo la verifica.",
        "trường văn bản": "campo di testo",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHEMA (indovinato — si cambia scegliendo un altro campo)",
        "văn bản": "testo",
        "định danh": "identificatore",
        "metadata lồng": "metadati annidati",
        "TRƯỜNG": "CAMPO",
        "phủ": "copertura",
        "nhiều kiểu": "più tipi",
        "ĐỘ DÀI — ký tự": "LUNGHEZZA — caratteri",
        "ĐỘ DÀI — từ": "LUNGHEZZA — parole",
        "ĐỘ DÀI — token ước lượng": "LUNGHEZZA — token stimati",
        "RỖNG VÀ TRÙNG": "VUOTI E DUPLICATI",
        "chunk rỗng": "frammenti vuoti",
        "dòng": "righe",
        "nhóm trùng chính xác": "gruppi di duplicati esatti",
        "dòng không đọc được, không vào thống kê": "righe illeggibili, fuori dalle statistiche",
        "PHƯƠNG PHÁP": "METODO",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«caratteri» conta i caratteri Unicode (scalari), non i gruppi visibili",
        "«từ» tách theo khoảng trắng ASCII": "«parole» divide sugli spazi ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«token» conta con un divisore di sillabe — NON è quello del modello",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«duplicato» significa duplicato ESATTO; i quasi-duplicati stanno nel blocco ```quality",
        "chunk": "frammenti",
        "JSONL: kiểm và soi chunk…": "JSONL: verifica e ispeziona i frammenti…",
        "Ảnh": "Immagine",
        "PDF": "PDF",
        "Tài liệu Word": "Documento Word",
        "Bảng tính Excel": "Foglio di calcolo Excel",
        "Bản trình chiếu PowerPoint": "Presentazione PowerPoint",
        "File nén": "Archivio",
        "Vừa khung": "Adatta alla finestra",
        "Chép ảnh": "Copia l’immagine",
        "Xoay": "Ruota",
        "Không đọc được ảnh «%@»": "Impossibile leggere l’immagine «%@»",
        "Đã chép ảnh vào clipboard": "Immagine copiata negli appunti",
        "Bôi vàng": "Evidenzia in giallo",
        "Gạch chân": "Sottolinea",
        "Ghi chú…": "Nota…",
        "Bỏ chú thích": "Rimuovi le annotazioni",
        "Lấy chữ ra tab mới": "Estrai il testo in una nuova scheda",
        "Lưu bản có chú thích…": "Salva la versione annotata…",
        "Tìm trong PDF": "Cerca nel PDF",
        "Thêm": "Aggiungi",
        "Trang %d/%d": "Pagina %d/%d",
        "Trang %d": "Pagina %d",
        "Kết quả %d/%d": "Risultato %d/%d",
        "0 kết quả": "0 risultati",
        "Không đọc được PDF «%@»": "Impossibile leggere il PDF «%@»",
        "PDF này có mật khẩu — chưa mở được nội dung": "Questo PDF è protetto da password — il contenuto non è accessibile",
        "Không thấy «%@» trong tài liệu": "«%@» non è stato trovato nel documento",
        "Đã bôi vàng": "Evidenziato",
        "Đã gạch chân": "Sottolineato",
        "Hãy bôi đen một đoạn chữ trước": "Seleziona prima un brano di testo",
        "Đã thêm ghi chú": "Nota aggiunta",
        "Trang này chưa có chú thích nào": "Questa pagina non ha annotazioni",
        "Đã bỏ %d chú thích trên trang này": "%d {one=annotazione rimossa|other=annotazioni rimosse} da questa pagina",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Questo PDF non ha un livello di testo — è probabilmente una scansione",
        "Không ghi được tệp": "Impossibile scrivere il file",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Il file scritto NON si riapre correttamente — non usare questa versione",
        "Đã lưu %@ · %d trang": "%@ salvato · %d {one=pagina|other=pagine}",
        "Tên": "Nome",
        "Kích thước": "Dimensione",
        "Đã nén": "Compresso",
        "Tỉ lệ": "Rapporto",
        "Sửa lúc": "Modificato il",
        "Mở mục đang chọn": "Apri l’elemento selezionato",
        "Bung ra thư mục…": "Estrai in una cartella…",
        "Bung vào đây": "Estrai qui",
        "%d mục": "%d {one=elemento|other=elementi}",
        "giải nén ra %@": "estratto in %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— l’interno di un file Office è un archivio; queste sono le sue parti",
        "Đã bung %d mục": "%d {one=elemento estratto|other=elementi estratti}",
        "%d mục hỏng": "%d {one=elemento difettoso|other=elementi difettosi}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=elemento RIFIUTATO|other=elementi RIFIUTATI} perché i loro percorsi escono dalla cartella di destinazione",
        "Không mở được mục này": "Impossibile aprire questo elemento",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Non è ancora possibile scrivere direttamente in un %@ — usa «Salva come…»",
        "Không có gì đổi": "Non è cambiato nulla",
        "Đã ghi %d ô vào %@": "%d {one=cella scritta|other=celle scritte} in %@",
        "Đã ghi %d đoạn vào %@": "%d {one=paragrafo scritto|other=paragrafi scritti} in %@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Impossibile scrivere nel file — l’originale resta intatto",
        "dựng bài": "preparare il caso di prova",
        "Không ghi được settings.json": "Impossibile scrivere settings.json",
        "Xoay trái": "Ruota a sinistra",
        "Xoay phải": "Ruota a destra",
        "Trang lên": "Sposta pagina su",
        "Trang xuống": "Sposta pagina giù",
        "Xoá trang…": "Elimina pagine…",
        "Xoá trang": "Elimina pagine",
        "Trích trang…": "Estrai pagine…",
        "Trích trang ra tệp mới": "Estrai pagine in un nuovo file",
        "Gộp tệp PDF…": "Unisci file PDF…",
        "Tách tệp…": "Dividi file…",
        "Tách tệp PDF": "Dividi file PDF",
        "Xuất ảnh…": "Esporta immagini…",
        "Xuất trang ra ảnh PNG": "Esporta pagine come immagini PNG",
        "Hoàn tác trang": "Annulla modifica pagina",
        "Lưu bản đã sửa…": "Salva copia modificata…",
        "Phát": "Riproduci",
        "Tạm dừng": "Pausa",
        "Xem bình thường": "Vista normale",
        "Chọn sheet": "Scegli foglio",
        "Mở sheet": "Apri foglio",
        "Bỏ và đổi sheet": "Scarta e cambia foglio",
        "Bảng tính có %d sheet.": "La cartella ha %d fogli.",
        "Bảng tính này chỉ có một sheet: «%@»": "Questa cartella ha un solo foglio: «%@»",
        "Bỏ phần chưa lưu của sheet này?": "Scartare le modifiche non salvate di questo foglio?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Cambiare foglio sostituisce l'intera scheda. Le modifiche non salvate con ⌘S vanno perse.",
        "Chọn tệp PDF cần gộp vào": "Scegli il PDF da unire",
        "Chọn thư mục ghi ảnh": "Scegli la cartella per le immagini",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Scegli dove salvare. Il secondo file viene scritto accanto a questo.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Il documento ha %d pagine. Inserisci le pagine da eliminare, es. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Il documento ha %d pagine. Inserisci le pagine da estrarre, es. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Il documento ha %d pagine. Inserisci le pagine da esportare, es. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Il documento ha %d pagine. Inserisci la parte da separare, es. 1-5; il resto diventa un secondo file.",
        "Đã xoay trang %d": "Pagina %d ruotata",
        "Đã xoá trang %@ · còn %d trang": "Pagine %@ eliminate · restano %d pagine",
        "Đã gộp %d trang từ «%@»": "%d pagine unite da «%@»",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Diviso in %@ (%d pagine) e %@ (%d pagine)",
        "Đã ghi %@ — %@ · %d trang": "Scritto %@ — %@ · %d pagine",
        "Đã xuất %d ảnh vào %@": "%d immagini esportate in %@",
        "Chỉ xuất được %d/%d ảnh": "Sono state esportate solo %d immagini su %d",
        "Đã hoàn tác một thao tác trang": "Annullata un'operazione sulla pagina",
        "Không còn thao tác trang nào để hoàn tác": "Nessuna operazione sulla pagina da annullare",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Impossibile eliminare TUTTE le pagine: un PDF deve averne almeno una",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Quell'intervallo è l'intero documento: non c'è nulla da separare",
        "«%@» có mật khẩu — chưa gộp được": "«%@» è protetto da password: impossibile unirlo",
        "«%@» không có trang nào": "«%@» non ha pagine",
        "Đã ở trang đầu": "Già alla prima pagina",
        "Đã ở trang cuối": "Già all'ultima pagina",
        "· đã sửa, chưa lưu": "· modificato, non salvato",
        "Ảnh động · %d khung": "Immagine animata · %d fotogrammi",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Documento non salvato: nessun file su disco da vedere in binario",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Questo comando vale solo per le cartelle di lavoro Excel",
        "Không đọc được danh sách sheet": "Impossibile leggere l'elenco dei fogli",
        "Không có sheet «%@»": "Non esiste alcun foglio «%@»",
        "Không đọc được sheet «%@»": "Impossibile leggere il foglio «%@»",
        "Sheet «%@» · %d hàng": "Foglio «%@» · %d righe",
        "phần còn lại": "il resto",
        "Lưu ý": "Nota",
        "Cẩn thận": "Attenzione",
        "Xem thêm": "Vedi anche",
        "Chép": "Copia",
        "Đã chép": "Copiato",
        "Chép đoạn mã mẫu": "Copia il codice di esempio",
        "Tìm trong trợ giúp": "Cerca nell'aiuto",
        "Lùi": "Indietro",
        "Bắt đầu dùng": "Inizia",
        "Không mở cửa sổ này khi khởi động nữa": "Non mostrare questa finestra all'avvio",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "L'aiuto non è ancora tradotto in questa lingua: viene mostrato in vietnamita.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Vai all'offset (es. 1F400 o 0x1F400)",
        "Chép dòng đã chọn": "Copia le righe selezionate",
        "Đã chép %d dòng": "%d righe copiate",
        "Không đọc được «%@»": "Impossibile leggere «%@»",
        "Tệp rỗng": "File vuoto",
        "Không đọc được offset «%@»": "Impossibile leggere l'offset «%@»",
        "Offset 0x%@ vượt quá cỡ tệp": "L'offset 0x%@ supera la dimensione del file",
        "Mở bằng ứng dụng khác…": "Apri con un'altra app…",
        "%d kênh": "%d canali",
        "Không phát được «%@»": "Impossibile riprodurre «%@»",
        "Không phát được — %@": "Riproduzione impossibile — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS non ha un decoder integrato per il formato %@: è un limite del sistema, non un file danneggiato.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Puoi comunque vedere i byte in modalità binaria o aprirlo con un'app dotata di decoder proprio.",
        "Ký…": "Firma…",
        "Sửa chữ…": "Modifica testo…",
        "Sửa chữ": "Modifica testo",
        "Vẽ đè": "Disegna sopra",
        "Ô chưa điền": "Prossimo campo vuoto",
        "Xoá nội dung đã điền": "Cancella i valori inseriti",
        "Tệp này không có ô biểu mẫu nào": "Questo file non ha campi modulo",
        "Đã xoá nội dung của %d ô biểu mẫu": "Svuotati %d campi modulo",
        "Mọi ô biểu mẫu đều đã có nội dung": "Tutti i campi modulo sono già compilati",
        "Còn %d ô chưa điền": "Restano %d campi vuoti",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Modulo compilabile: %d campi. Scrivi direttamente, poi «Salva copia modificata…»",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Scegli un'immagine di firma (sfondo trasparente è meglio)",
        "Không dựng được trang có chữ ký": "Impossibile creare la pagina firmata",
        "Đã chèn chữ ký vào trang %d": "Firma inserita a pagina %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Seleziona prima il testo da modificare",
        "Vùng chọn quá nhỏ": "La selezione è troppo piccola",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Il nuovo testo viene DISEGNATO SOPRA la selezione con il font di sistema. Il testo vecchio è coperto, non rimosso: può ancora essere estratto, quindi non è un oscuramento.",
        "Không dựng được trang đã sửa": "Impossibile creare la pagina modificata",
        "Đã vẽ đè chữ mới lên trang %d": "Nuovo testo disegnato sulla pagina %d",
        "Đổi chế độ View / Code": "Alterna Vista / Codice",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Non c'è ancora una vista ad albero per JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Non c'è ancora una vista diagramma nella scheda",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Non c'è ancora una vista struttura per PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Questo file ha una sola modalità di visualizzazione",
        "%d nút": "%d nodi",
        "Không dựng được cây: %@": "Impossibile costruire l'albero: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Il documento è troppo grande per l'albero: usa la modalità Codice",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Impossibile costruire le pagine di questo file \u{2014} usa la modalità Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Le diapositive sono costruite dal testo; immagini e impaginazione originali non sono ancora disegnate.",
        "Vừa ngang": "Adatta larghezza",
        "Thu nhỏ trang": "Riduci pagina",
        "Phóng to trang": "Ingrandisci pagina",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "\u{201C}%@\u{201D} non trovato nel documento",
        "Chỗ khớp %d/%d": "Corrispondenza %d di %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Nessun testo selezionato nella pagina.",
        "%d ký tự": "%d {one=carattere|other=caratteri}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Apri i file direttamente in modalità View quando disponibile",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· ANNULLATO a metà — tabella incompleta",
        "Chế độ hiển thị": "Modo di visualizzazione",
        "Đổi giữa View và Code (⌥⌘V)": "Passa tra View e Code (⌥⌘V)",
        "Trang tài liệu": "Pagine del documento",
        "Chữ đã dựng": "Testo composto",
        "Trang bảng tính": "Pagine del foglio",
        "Sơ đồ": "Diagramma",
        "Cây khoá–giá trị": "Albero chiave–valore",
        "Bộ phát": "Lettore",
        "Danh sách mục": "Elenco voci",
        "Báo cáo đã dựng": "Rapporto composto",
        "Tô theo mức": "Colorato per livello",
        "Trang slide": "Pagine delle diapositive",
        "Dàn ý": "Struttura",
        "Lưu rồi dựng lại": "Salva e ricomponi",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Mostra la copia SU DISCO — le modifiche non salvate non ci sono.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Il sistema non è riuscito a costruire il visualizzatore — usa il modo Code.",
        "Lưu tệp trước khi xem trang.": "Salva il file prima di vederne le pagine.",
        "Đang ở chế độ Code": "Ora in modo Code",
        "Đang ở chế độ View": "Ora in modo View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Stai vedendo il sorgente — fai clic per passare al modo View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "In modo View — fai clic per tornare al sorgente (⌥⌘V)",
        "Tín hiệu: %@": "Segnale: %@",
        "Lý do: %@": "Motivo: %@",
        "Chi tiết: %@": "Dettaglio: %@",
        "Mở báo cáo": "Apri il rapporto",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor si è chiuso all'improvviso alle %@ — apri il rapporto per leggerlo; non viene inviato nulla.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Legature — disattivate, ogni carattere resta nella sua cella",
        "Chế độ CSV": "Modo CSV",
        "Dấu phân tách": "Separatore",
        "Tự nhận diện": "Rileva automaticamente",
        "Dấu phân tách: %@": "Separatore: %@",
        "Theo đuôi tệp": "Dall'estensione del file",
        "%d dấu cách": "%d {one=spazio|other=spazi}",
        "Tài liệu đang sửa được": "Questo documento è modificabile",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Sola lettura: il file è sotto osservazione — interrompi l'osservazione per modificarlo",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Sola lettura: il file su disco non è scrivibile",
        "Đã mở khoá — tài liệu sửa được": "Sbloccato — il documento è di nuovo modificabile",
        "Nhân bản tệp": "Duplica file",
        "Đổi tên tệp…": "Rinomina file…",
        "Chuyển tệp tới…": "Sposta file in…",
        "XML: đánh giá XPath…": "XML: valuta XPath…",
        "Đánh giá XPath": "Valuta XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Per esempio: //ordine/riga[2]/@codice · //*[@tipo='A'] · count(//riga)",
        "Đánh giá": "Valuta",
        "XPath không đọc được: %@": "Impossibile leggere questo XPath: %@",
        "XPath «%@» không khớp node nào": "XPath «%@» non ha trovato alcun nodo",
        "XPath «%@» — %d node": "XPath «%@» — %d {one=nodo|other=nodi}",
        "XPath «%@»: %d node": "XPath «%@»: %d {one=nodo|other=nodi}",
        "Lưu tệp trước khi nhân bản.": "Salva il file prima di duplicarlo.",
        "Không nhân bản được": "Impossibile duplicare",
        "Đã nhân bản thành %@": "Duplicato come %@",
        "Lưu tệp trước khi đổi tên.": "Salva il file prima di rinominarlo.",
        "Đổi tên tệp": "Rinomina file",
        "Tên hiện tại: %@": "Nome attuale: %@",
        "Đổi tên": "Rinomina",
        "Tên tệp không hợp lệ": "Questo nome di file non è valido",
        "Đã có tệp tên %@ ở đó": "C'è già un file di nome %@ lì",
        "Lưu tệp trước khi chuyển.": "Salva il file prima di spostarlo.",
        "Chuyển tới": "Sposta qui",
        "Thư mục đích đã có tệp tên %@": "La cartella di destinazione ha già un file di nome %@",
        "Không chuyển được tệp": "Impossibile spostare il file",
        "Đã chuyển tới %@": "Spostato in %@",
        "Bảng mã:": "Codifica:",
        "Xuống dòng:": "Fine riga:",
        "Riêng cho %@": "Solo per %@",
        "    %d — dùng TAB": "    %d — tabulazioni",
        "    %d — dùng dấu cách": "    %d — spazi",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Togli la regola propria e usa l'impostazione globale",
        "%@: thụt lề %d %@": "%@: rientro %d %@",
        "TAB": "tabulazioni",
        "dấu cách": "spazi",
        "Xuất": "Esporta",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Apri i risultati in un pannello di testo — salvalo con ⌘S",
        "Lượt tìm trước đó": "Ricerche precedenti",
        "«%@» — %d kết quả": "«%@» — %d {one=risultato|other=risultati}",
        "Kết quả tìm «%@»": "Risultati della ricerca di «%@»",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtra i nomi — es. *.csv;*.log (vuoto: ogni file di testo)",
        "Thư mục %@ không có file văn bản nào": "La cartella %@ non contiene file di testo",
        "Không tệp nào trong %@ khớp «%@»": "Nessun file in %@ corrisponde a «%@»",
        "%d byte · %d dòng": "%d byte · %d {one=riga|other=righe}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d byte · %d {one=riga|other=righe} — troppo grande per contare caratteri e parole",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d byte · %d {one=carattere|other=caratteri} · %d {one=parola|other=parole} · %d {one=riga|other=righe}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Questo documento ha %d {one=riga|other=righe}, %d byte. Scrivi un numero di riga, «riga,colonna» oppure «@byte».",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "Impossibile leggere «%@» — scrivi un numero di riga, «riga,colonna» oppure «@byte»",
    ]
}
