import Foundation

/// Bảng dịch tiếng Indonesia. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let id: [String: String] = [
        "Bản đã lưu…": "Versi tersimpan…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Dokumen ini belum pernah disimpan — belum ada riwayat",
        "Chưa có bản đã lưu nào trước đó": "Tidak ada versi tersimpan sebelumnya",
        "Không đọc được bản ấy": "Versi itu tidak dapat dibaca",
        "Khôi phục bản đã lưu": "Pulihkan versi tersimpan",
        "XML: kiểm theo DTD/XSD…": "XML: validasi terhadap DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Mac ini tidak punya libxml2, jadi validasi XSD tidak tersedia.",
        "Chọn lược đồ XSD để kiểm": "Pilih skema XSD untuk validasi",
        "Hợp lệ theo": "Valid terhadap",
        "Plugin chạy xong, không đổi gì": "Pengaya selesai tanpa mengubah apa pun",
        "Chưa cài plugin native nào": "Belum ada pengaya native yang terpasang",
        "Gỡ plugin này": "Hapus pengaya ini",
        "Gỡ plugin này?": "Hapus pengaya ini?",
        "Gỡ": "Hapus",
        "Cài plugin native…": "Pasang pengaya native…",
        "Mở thư mục plugin": "Buka folder pengaya",
        "Chọn file .dylib của plugin native": "Pilih berkas .dylib pengaya",
        "Đã cài:": "Terpasang:",
        "Đã gỡ:": "Dihapus:",
        "Plugin native…": "Pengaya native…",
        "Chỉ nhận file .dylib.": "Hanya berkas .dylib yang diterima.",
        "Đã có một plugin trùng tên:": "Pengaya dengan nama yang sama sudah terpasang:",
        "Không chép được plugin:": "Pengaya tidak dapat disalin:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Pengaya native hanya tersedia pada unduhan langsung, bukan pada versi App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Proses pembantu pengaya tidak ditemukan.",
        "Không khởi động được tiến trình phụ:": "Proses pembantu pengaya tidak dapat dijalankan:",
        "Tiến trình plugin đã dừng giữa chừng.": "Proses pengaya berhenti tanpa diduga.",
        "Plugin không trả lời kịp — đã dừng nó.": "Pengaya tidak menjawab tepat waktu — proses dihentikan.",
        "Plugin trả lời sai giao thức:": "Pengaya membalas dengan pesan yang rusak:",
        "Plugin báo lỗi:": "Pengaya melaporkan galat:",
        "Về GEditor": "Tentang GEditor",
        "Cài đặt…": "Pengaturan…",
        "Thoát GEditor": "Keluar dari GEditor",
        "File": "Berkas",
        "Tab mới": "Tab Baru",
        "Đóng tab": "Tutup Tab",
        "Tab kế": "Tab Berikutnya",
        "Tab trước": "Tab Sebelumnya",
        "Tài liệu mới": "Dokumen Baru",
        "Mở…": "Buka…",
        "Mở thư mục làm Workspace…": "Buka Folder sebagai Ruang Kerja…",
        "Mở gần đây": "Baru Saja Dibuka",
        "Lưu": "Simpan",
        "Lưu thành…": "Simpan Sebagai…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Pangkas Spasi Akhir Baris saat Menyimpan",
        "Theo dõi file (tail -f)": "Ikuti Berkas (tail -f)",
        "In…": "Cetak…",
        "Mở lại tab vừa đóng": "Buka Kembali Tab yang Terakhir Ditutup",
        "Chưa có file nào": "Tidak ada berkas terkini",
        "Xoá danh sách": "Kosongkan Menu",
        "Edit": "Sunting",
        "Hoàn tác": "Urungkan",
        "Làm lại": "Ulangi",
        "Cắt": "Potong",
        "Sao chép": "Salin",
        "Dán": "Tempel",
        "Lịch sử clipboard…": "Riwayat Papan Klip…",
        "Column Editor…": "Penyunting Kolom…",
        "Chọn lần kế tiếp": "Pilih Kemunculan Berikutnya",
        "Chọn tất cả": "Pilih Semua",
        "Nhân đôi dòng": "Gandakan Baris",
        "Xóa dòng": "Hapus Baris",
        "Comment dòng": "Jadikan Komentar / Batalkan",
        "Chưa chép gì trong phiên này": "Belum ada yang disalin",
        "Xoá lịch sử": "Kosongkan Riwayat",
        "Search": "Cari",
        "Tìm…": "Cari…",
        "Tìm và thay…": "Cari dan Ganti…",
        "Tìm trong thư mục…": "Cari di Folder…",
        "Thay trong thư mục…": "Ganti di Folder…",
        "Kết quả kế": "Hasil Berikutnya",
        "Kết quả trước": "Hasil Sebelumnya",
        "Đi tới dòng…": "Ke Baris…",
        "Nhảy tới ngoặc khớp": "Lompat ke Kurung Pasangan",
        "Đánh dấu mọi dòng khớp…": "Tandai Semua Baris yang Cocok…",
        "Đảo dấu": "Balik Tanda",
        "Bỏ mọi dấu": "Hapus Semua Tanda",
        "Chép dòng đã đánh dấu": "Salin Baris Bertanda",
        "Xóa dòng đã đánh dấu": "Hapus Baris Bertanda",
        "Chỉ giữ dòng đã đánh dấu": "Sisakan Hanya Baris Bertanda",
        "Lines": "Baris",
        "Sắp xếp A→Z": "Urutkan A→Z",
        "Sắp xếp Z→A": "Urutkan Z→A",
        "Sắp xếp tự nhiên": "Urutan Alami",
        "Khử trùng lặp": "Hapus Duplikat",
        "Đảo thứ tự dòng": "Balik Urutan Baris",
        "Dời dòng lên": "Naikkan Baris",
        "Dời dòng xuống": "Turunkan Baris",
        "Ghép dòng": "Gabungkan Baris",
        "Tách dòng theo độ dài…": "Potong Baris Menurut Panjang…",
        "Tách dòng theo ký tự…": "Potong Baris Menurut Karakter…",
        "Xóa dòng rỗng": "Hapus Baris Kosong",
        "Nén dòng trống liên tiếp": "Rapatkan Baris Kosong",
        "Cắt khoảng trắng cuối dòng": "Pangkas Spasi Akhir Baris",
        "Tab → Space": "Tab → Spasi",
        "Space → Tab": "Spasi → Tab",
        "HOA": "HURUF BESAR",
        "thường": "huruf kecil",
        "Chữ Hoa Đầu Từ": "Huruf Besar Tiap Kata",
        "Chữ hoa đầu câu": "Huruf besar di awal kalimat",
        "Đảo hoa/thường": "bALIK bESAR kECIL",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: pilih lembar…",
        "Xem dạng bảng / văn bản": "Alihkan Tampilan Tabel / Teks",
        "Xóa cột…": "Hapus Kolom…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Periksa Data (kolom · tipe)",
        "Bàn làm sạch dữ liệu…": "Meja Pembersihan Data…",
        "Chạy công thức làm sạch…": "Jalankan Resep Pembersihan…",
        "Chuyển đổi…": "Konversi…",
        "Đổi dấu phân tách…": "Ubah Pemisah…",
        "Xuất sang JSON…": "Ekspor ke JSON…",
        "Format": "Format",
        "Bảng mã…": "Pengodean…",
        "Xuống dòng…": "Akhir Baris…",
        "Chuẩn hóa Unicode…": "Normalkan Unicode…",
        "JSON: định dạng lại": "JSON: Rapikan",
        "JSON: thu gọn một dòng": "JSON: Padatkan",
        "JSON: sắp xếp khóa": "JSON: Urutkan Kunci",
        "JSON: truy vấn JSONPath…": "JSON: Kueri JSONPath…",
        "CSV: truy vấn SQL…": "CSV: Kueri SQL…",
        "Truy vấn SQL": "Kueri SQL",
        "Đang chạy…": "Sedang berjalan…",
        "Xuất ra tab mới": "Ekspor ke Tab Baru",
        "Tài liệu rỗng — không có bảng để truy vấn": "Dokumen kosong — tidak ada tabel untuk dikueri",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Bukan tabel CSV — baris pertama hanya punya satu kolom",
        "Không đọc được câu truy vấn": "Kueri tidak dapat dibaca",
        "Không kiểm được câu truy vấn": "Kueri tidak dapat diperiksa",
        "Vàng (mặc định)": "Kuning (bawaan)",
        "Xanh dương": "Biru",
        "Xanh lá": "Hijau",
        "Vàng đất": "Oker",
        "Tím": "Ungu",
        "Hồng": "Merah muda",
        "Xanh ngọc": "Tosca",
        "Cam": "Jingga",
        "Xám lam": "Kelabu batu",
        "Văn bản": "Teks",
        "Dãy số": "Deret angka",
        "Dãy ngày": "Deret tanggal",
        "Chữ HOA (hex)": "Huruf besar (heksa)",
        "Bắt đầu": "Mulai",
        "Bước": "Langkah",
        "Đệm 0 tới": "Isi nol sampai",
        "Hệ": "Basis",
        "Ngày đầu": "Tanggal pertama",
        "Định dạng": "Format",
        "Chèn": "Sisipkan",
        "Huỷ": "Batal",
        "Chuyển đổi định dạng": "Konversi format",
        "Xem trước 5 hàng đầu": "Pratinjau 5 baris pertama",
        "Tạo tab mới": "Buka di tab baru",
        "Lưu ra file…": "Simpan ke berkas…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Hasilnya terbuka di tab baru yang belum disimpan. Dokumen asli tidak tersentuh.",
        "Chạy trên tài liệu này": "Jalankan pada dokumen ini",
        "Chạy trên thư mục…": "Jalankan pada satu folder…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Seluruh resep adalah SATU langkah urung. Berkas di cakram tidak tersentuh sampai Anda menyimpan.",
        "tắt": "mati",
        "không thấy cột": "kolom tidak ditemukan",
        "sẵn sàng": "siap",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "ia terus memakai satu inti prosesor sampai aplikasi ditutup.",
        "Script không trả về gì": "Skrip tidak mengembalikan apa pun",
        "Không dựng được máy JavaScript": "Mesin JavaScript tidak dapat dibuat",
        "Lỗi JavaScript không rõ": "Galat JavaScript yang tidak dikenal",
        "Bảng": "Tabel",
        "Áp sắp xếp vào file": "Terapkan pengurutan ke berkas",
        "Chuyển đổi ▾": "Konversi ▾",
        "Xuất dòng khớp": "Ekspor baris yang cocok",
        "Ẩn cột này": "Sembunyikan kolom ini",
        "Đổi tên tiêu đề…": "Ganti nama tajuk…",
        "Chèn cột trống bên trái": "Sisipkan kolom kosong di kiri",
        "Chèn cột trống bên phải": "Sisipkan kolom kosong di kanan",
        "Xóa cột này khỏi file…": "Hapus kolom ini dari berkas…",
        "Phải còn ít nhất một cột đang hiện": "Setidaknya satu kolom harus tetap terlihat",
        "Đang sắp xếp…": "Sedang mengurutkan…",
        "Trở về thứ tự trong file": "Kembali ke urutan berkas",
        "trăm hàng đầu": "seratus baris pertama",
        "chọn cột": "memilih kolom",
        "đặt tên cột kết quả": "menamai kolom hasil",
        "lọc theo chữ": "menyaring menurut teks",
        "ô rỗng": "sel kosong",
        "ghép điều kiện": "menggabungkan syarat",
        "đếm hàng": "menghitung baris",
        "gộp nhóm": "mengelompokkan dan meringkas",
        "nhỏ nhất, lớn nhất": "minimum, maksimum",
        "sắp xếp và cắt": "mengurutkan dan membatasi",
        "tên cột có dấu cách": "nama kolom berspasi",
        "Truy vấn bị dừng giữa chừng": "Kueri dihentikan di tengah jalan",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Tidak didukung: JOIN · subkueri · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · fungsi jendela",
        "XML: định dạng lại": "XML: Rapikan",
        "XML: thu gọn một dòng": "XML: Padatkan",
        "XML: kiểm cú pháp": "XML: Periksa Sintaks",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: Periksa Kunci dan Indentasi",
        "View": "Tampilan",
        "Ẩn/hiện sidebar (Function List)": "Alihkan Bilah Samping (Daftar Fungsi)",
        "Ẩn/hiện bản đồ tài liệu": "Alihkan Peta Dokumen",
        "Gấp / mở khối tại con nháy": "Lipat / Buka di Kursor",
        "Gấp tất cả": "Lipat Semua",
        "Bỏ gấp tất cả": "Buka Semua Lipatan",
        "Gấp theo cấp": "Lipat sampai Tingkat",
        "Cấp %d": "Tingkat %d",
        "Đã gấp %d khối ở cấp %d": "Melipat %1$d blok pada tingkat %2$d",
        "Tài liệu này chỉ sâu %d cấp": "Dokumen ini hanya sedalam %d tingkat",
        "mermaid: không đọc được bản kê": "mermaid: manifes tidak terbaca",
        "Kiểm tra bản cập nhật…": "Periksa Pembaruan…",
        "Kiểm tra bản cập nhật": "Periksa Pembaruan",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Versi App Store diperbarui lewat Mac App Store, bukan lewat GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Versi ini tidak punya kunci tanda tangan pembaruan, jadi ia tidak bisa memeriksa pembaruan.",
        "Phóng to chữ": "Perbesar",
        "Thu nhỏ chữ": "Perkecil",
        "Cỡ chữ gốc": "Ukuran Asli",
        "Chia đôi theo chiều dọc": "Belah Tegak",
        "Chia đôi theo chiều ngang": "Belah Mendatar",
        "Bỏ chia đôi": "Tutup Belahan",
        "Mở tab này ở nửa kia": "Buka Tab di Panel Sebelah",
        "Nhảy sang nửa kia": "Pindah ke Panel Sebelah",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Bungkus Baris (mati / ke jendela / ke kolom)",
        "Ngắt dòng tại cột…": "Bungkus pada Kolom…",
        "Đánh dấu dòng này": "Alihkan Penanda",
        "Dấu kế tiếp": "Penanda Berikutnya",
        "Dấu trước đó": "Penanda Sebelumnya",
        "Màu đánh dấu…": "Warna Penanda…",
        "Hiện tất cả ký tự ẩn": "Tampilkan Semua Karakter Tak Terlihat",
        "  Khoảng trắng": "  Spasi",
        "  Tab": "  Tab",
        "  Xuống dòng": "  Akhir baris",
        "  NBSP · zero-width · điều khiển": "  NBSP · lebar nol · kendali",
        "Xem nhị phân": "Tampilan biner",
        "Chế độ CSV (tô màu theo cột)": "Mode CSV (kolom pelangi)",
        "Macro": "Makro",
        "Bắt đầu / dừng ghi": "Mulai / Hentikan Perekaman",
        "Phát lại": "Mainkan",
        "Phát nhiều lần…": "Mainkan Beberapa Kali…",
        "Phát đến cuối tài liệu": "Mainkan sampai Akhir Dokumen",
        "Chạy trên mọi tab": "Jalankan pada Semua Tab",
        "Hủy macro đang chạy": "Hentikan Makro yang Berjalan",
        "Lưu macro…": "Simpan Makro…",
        "Macro đã lưu…": "Makro Tersimpan…",
        "Help": "Bantuan",
        "Trợ giúp GEditor": "Bantuan GEditor",
        "Giới thiệu tính năng": "Pengenalan Fitur",
        "Di cư từ Notepad++": "Pindah dari Notepad++",
        "Tìm": "Cari",
        "Thay bằng": "Ganti dengan",
        "Kế": "Berikutnya",
        "Trước": "Sebelumnya",
        "Đếm": "Hitung",
        "Đóng": "Tutup",
        "Kiểm theo JSON Schema…": "Validasi terhadap Skema JSON…",
        "Chọn tệp JSON Schema": "Pilih berkas Skema JSON",
        "Không thấy lỗi nào theo schema này.": "Tidak ada masalah terhadap skema ini.",
        "JSON Schema": "Skema JSON",
        "Kiểm cú pháp đồ thị": "Periksa sintaks graf",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Format graf tidak dikenali — perlu ekstensi .dot, .gv, .cypher, .ttl atau .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Tidak ditemukan galat sintaks %@ (pemeriksaan ini tidak menyeluruh).",
        "Cú pháp %@": "sintaks %@",
        "không phải một đối tượng JSON": "bukan objek JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Penambangan teks (n-gram, TF-IDF)",
        "Tài liệu rỗng.": "Dokumen kosong.",
        "Không rút được từ khoá nào.": "Tidak ada kata kunci yang bisa diambil.",
        "Từ khoá": "Kata kunci",
        "%d từ khoá · %d token · %d tài liệu": "%d kata kunci · %d token · %d dokumen",
        "Tô lên tài liệu": "Tandai di dokumen",
        "Đánh dấu entity từ danh sách…": "Tandai entitas dari sebuah daftar…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Pilih daftar entitas (CSV atau JSON)",
        "Không đọc được danh sách entity.": "Daftar entitas tidak dapat dibaca.",
        "Danh sách entity rỗng.": "Daftar entitas kosong.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Tidak ada entitas yang ditemukan di dokumen (%d dimuat).",
        "%d lần xuất hiện · %@": "%d kemunculan · %@",
        "Chuyển đổi tri thức…": "Konversi pengetahuan…",
        "Chuyển đổi: %@ → %@": "Konversi: %@ → %@",
        "Không chuyển đổi được.": "Konversi gagal.",
        "Xem trước cắt chunk…": "Pratinjau pemenggalan…",
        "Cỡ cố định 800B, chồng 100B": "Tetap 800 B, tumpang tindih 100 B",
        "Theo câu (≤ 800B)": "Per kalimat (≤ 800 B)",
        "Theo heading Markdown": "Per judul Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Dokumen kosong — tidak ada penggalan.",
        "%d chunk · trung bình %d B · %@": "%d penggalan · rata-rata %d B · %@",
        "Xuất JSONL": "Ekspor JSONL",
        "Chunk JSONL": "JSONL penggalan",
        "Mở triple/edge dạng bảng": "Buka triple/sisi sebagai tabel",
        "Bảng triple": "Tabel triple",
        "Tài liệu này không có dòng triple nào.": "Dokumen ini tidak punya baris triple.",
        "Không đọc được triple nào — dòng %d: %@": "Tidak ada triple yang terbaca — baris %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "Terbaca %1$d triple · dilewati %2$d baris rusak (pertama: baris %3$d)",
        "Trùng lặp mờ theo cột…": "Duplikat mirip menurut kolom…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Duplikat mirip — kolom «%1$@»: %2$d kelompok calon",
        "Gộp": "Gabungkan",
        "Giống": "Kemiripan",
        "Các giá trị trong cụm": "Nilai dalam kelompok",
        "Gộp về": "Gabungkan menjadi",
        "Gộp các cụm đã chọn": "Gabungkan kelompok terpilih",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Tidak ada kelompok terpilih — Gabungkan tidak akan mengubah apa pun. Aplikasi tidak pernah menggabungkan sendiri.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%1$d kelompok terpilih · %2$d baris akan berubah · SATU langkah urung",
        "Không quét được cột này.": "Kolom ini tidak dapat dipindai.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Kolom «%@» tidak punya kelompok duplikat mirip.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Tidak ada kelompok yang digabungkan — dokumen tidak berubah.",
        "Khử trùng lặp mờ · cột %@": "Dedup mirip · kolom %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "Digabungkan %1$d kelompok · %2$d sel berubah",
        "Báo cáo làm sạch": "Laporan pembersihan",
        "# Báo cáo làm sạch — %@\n\n": "# Laporan pembersihan — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Diterapkan (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Belum ada langkah yang diterapkan._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Profil data\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d kolom · %2$d baris · dipindai dalam %3$.1f d_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Kolom | Tipe | Kosong | Berbeda | Min | Maks | Rerata |\n",
        "\n### Giá trị bất thường\n\n": "\n### Pencilan\n\n",
        "hàng %d: %@": "baris %d: %@",
        "- cột «%@» — %d ô: %@\n": "- kolom «%1$@» — %2$d sel: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Tersisa (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Tidak ada temuan yang tersisa._\n",
        "- cột «%@»: %@\n": "- kolom «%1$@»: %2$@\n",
        "Cắt khoảng trắng khi lưu": "Pangkas spasi saat menyimpan",
        "Chuẩn hóa xuống dòng": "Seragamkan akhir baris",
        "trước đó": "sebelumnya",
        "Không mở lại được thư mục «%@» của phiên trước": "Folder «%@» dari sesi sebelumnya tidak dapat dibuka kembali",
        " (và %d file khác)": " (dan %d berkas lagi)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%1$d tab tidak dapat dibuka kembali: %2$@%3$@ — berkasnya sudah tidak ada di tempatnya.",
        "Không đọc được nội dung từ ống dẫn": "Masukan dari pipa tidak dapat dibaca",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Spasi di akhir baris akan dipangkas setiap kali menyimpan",
        "Không cắt khoảng trắng khi lưu nữa": "Spasi tidak lagi dipangkas saat menyimpan",
        "Chưa đặt tên.txt": "TanpaJudul.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Konversi pengodean akan menghilangkan sebagian karakter",
        "Vẫn lưu": "Simpan saja",
        "Tài liệu có thay đổi chưa lưu": "Dokumen punya perubahan yang belum disimpan",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Menutup tanpa menyimpan akan membuangnya.",
        "Bỏ thay đổi": "Buang perubahan",
        "Đi tới dòng": "Ke baris",
        "Tài liệu có %d dòng.": "Dokumen punya %d baris.",
        "Số dòng": "Nomor baris",
        "Đi tới": "Pergi",
        "Diễn giải lại theo…": "Tafsirkan ulang sebagai…",
        "Chuyển đổi sang…": "Konversi ke…",
        "Không diễn giải lại được": "Penafsiran ulang gagal",
        "Bảng mã %@ không chứa hết ký tự": "%@ tidak dapat mewakili semua karakter",
        "Vẫn chọn": "Tetap pilih",
        "Cột %d": "Kolom %d",
        "Cột %d: %@": "Kolom %1$d: %2$@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Kolom tersembunyi: %1$@ (%2$d) — kembalikan dari menu konteks baris tajuk",
        "Hiện lại: %@": "Tampilkan lagi: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Kolom %@ disembunyikan — kolomnya masih utuh di dalam berkas",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Diurutkan menurut %@ %@ · hanya tampilan",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Terurut: %@ %@ (hanya tampilan)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ baris cocok — pencarian masih berjalan…",
        "%d / %d dòng khớp": "%1$d / %2$d baris cocok",
        "Không tìm thấy lỗi trong %d hàng": "Tidak ada masalah pada %d baris",
        "%d hàng lệch số cột": "%d baris dengan jumlah kolom yang salah",
        "%d ô sai kiểu dữ liệu": "%d sel dengan tipe data yang salah",
        " (đã dừng ở %d lỗi đầu)": " (berhenti pada %d masalah pertama)",
        "   —   kiểu nhận ra: ": "   —   tipe yang terdeteksi: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Baris %1$d, kolom %2$@: «%3$@» bukan %4$@",
        "Column Editor — %d dòng": "Penyunting Kolom — %d baris",
        "Phát hiện": "Temuan",
        "Hồ sơ dữ liệu": "Profil data",
        "Hồ sơ dữ liệu — đang quét…": "Profil data — sedang memindai…",
        "Lưu công thức…": "Simpan resep…",
        "Xuất báo cáo": "Ekspor laporan",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Belum ada kelompok yang diterapkan · setiap kelompok adalah satu langkah urung",
        "quá nhiều giá trị": "terlalu banyak nilai",
        "hay gặp: ": "paling sering: ",
        "Giá trị điền vào ô thiếu": "Nilai pengisi untuk sel kosong",
        "Áp dụng": "Terapkan",
        "Không dựng được bản xem trước": "Pratinjau tidak dapat dibuat",
        "· giữ nguyên, không đọc được ·": "· dibiarkan apa adanya, tak terbaca ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Konversi kolom ke ISO 8601 (TTTT-BB-HH)",
        "Quy ước số cho cả cột": "Kelaziman angka untuk seluruh kolom",
        "Làm gì với ô thiếu": "Apa yang dilakukan pada sel kosong",
        "Chuẩn hóa về ISO 8601": "Seragamkan ke ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Baca sel ambigu dengan HARI di depan (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Baca sel ambigu dengan BULAN di depan (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Lewati sel ambigu, perbaiki yang pasti saja",
        "Về Việt/Âu (1.234,56)": "Ke gaya Vietnam/Eropa (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Ke gaya Anglo-Amerika (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Ke gaya Anglo-Amerika, tanpa pemisah ribuan (1234.56)",
        "Điền một giá trị mặc định…": "Isi dengan nilai bawaan…",
        "Điền xuôi — lấy giá trị phía trên": "Isi ke bawah — ambil nilai di atasnya",
        "Điền ngược — lấy giá trị phía dưới": "Isi ke atas — ambil nilai di bawahnya",
        "Xóa hàng có ô thiếu ở cột này": "Hapus baris yang kosong pada kolom ini",
        "Cắt khoảng trắng hai đầu": "Pangkas spasi di kedua ujung",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Pangkas kedua ujung dan rapatkan spasi di dalam",
        "Pivot…": "Tabel pivot…",
        "Nguồn…": "Sumber…",
        "Pivot — gộp theo cột": "Pivot — kelompokkan menurut kolom",
        "Hàng (gộp nhóm)": "Baris (kelompokkan menurut)",
        "Giá trị": "Nilai",
        "+ Hàng": "+ Baris",
        "+ Giá trị": "+ Nilai",
        "Xoá hết": "Kosongkan semua",
        "Đưa vào ô truy vấn": "Masukkan ke kotak kueri",
        "Chọn cột để dựng câu truy vấn.": "Pilih kolom untuk menyusun kueri.",
        "Không đọc được tên cột của bảng này.": "Nama kolom tabel ini tidak dapat dibaca.",
        "Nguồn dữ liệu của truy vấn": "Sumber data kueri",
        "«%@» — tài liệu đang mở": "“%@” — dokumen yang terbuka",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ berkas berubah sejak didaftarkan",
        "Thêm file…": "Tambah berkas…",
        "Bỏ hết": "Hapus semua",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Nama tabel tidak dapat diturunkan dari “%@” — ganti nama berkasnya.",
        "Tổng": "Jumlah",
        "Trung bình": "Rerata",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Maks",
        "Đếm khác nhau": "Cacah nilai berbeda",
        "Biểu đồ": "Grafik",
        "Xuất PNG": "Ekspor PNG",
        "Xuất SVG": "Ekspor SVG",
        "Bảng này không có cột số nào để vẽ.": "Tabel ini tidak punya kolom angka untuk digambar.",
        "Không dựng được ảnh PNG.": "Gambar PNG tidak dapat dibuat.",
        "Kết quả truy vấn": "Hasil kueri",
        "Đã lưu %@": "Tersimpan %@",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Grafik %1$@ dari “%2$@” — %3$d titik, nilai dari %4$@ sampai %5$@",
        "Cột": "Batang",
        "Đường": "Garis",
        "Phân bố": "Histogram",
        "Phân tán": "Sebar",
        "Hộp": "Kotak",
        "CSV: chất lượng dữ liệu…": "CSV: Mutu data…",
        "Chất lượng dữ liệu": "Mutu data",
        "Xuất vi phạm ra tab mới": "Ekspor pelanggaran ke tab baru",
        "Mức": "Tingkat",
        "Luật": "Aturan",
        "Vi phạm": "Pelanggaran",
        "Tỷ lệ": "Rasio",
        "đạt": "lolos",
        "lỗi": "galat",
        "cảnh báo": "peringatan",
        "hỏng": "rusak",
        "Đã đánh dấu %d dòng vi phạm": "Ditandai %d baris yang melanggar",
        "Xu hướng": "Tren",
        "Lúc chấm": "Dinilai pada",
        "Số hàng": "Baris",
        "Lệch": "Selisih",
        "Luật trượt": "Aturan yang gagal",
        "Điểm chất lượng": "Nilai mutu",
        "Điểm theo thời gian": "Nilai sepanjang waktu",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Belum ada riwayat — setiap penilaian menambahkan ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "satu baris ke berkas “.history.jsonl” di sebelah berkas aturan.",
        "%d mốc trong lịch sử": "%d titik dalam riwayat",
        " · %d dòng KHÔNG đọc được": " · %d baris tak terbaca",
        " · chọn hai dòng để so": " · pilih dua baris untuk dibandingkan",
        "điểm %+.1f": "nilai %+.1f",
        "không chiều nào tụt": "tidak ada dimensi yang turun",
        "tụt: ": "turun: ",
        "%d luật mới trượt: %@": "%1$d aturan yang baru gagal: %2$@",
        "số hàng %+d": "baris %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (dan %d peringatan lagi di tab Tren)",
        "Không sửa tự động được: ": "Tidak ada perbaikan otomatis: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Membuka alat Meja Pembersihan yang sesuai, lalu langsung menilai ulang.",
        "Xử lý giá trị thiếu…": "Tangani nilai yang hilang…",
        "Chuẩn hóa ngày…": "Seragamkan tanggal…",
        "Khử trùng lặp…": "Hapus duplikat…",
        "Thay thế…": "Ganti…",
        "Xem các dòng sai": "Tampilkan baris yang bermasalah",
        "Không tìm thấy cột «%@» trong bảng này.": "Kolom “%@” tidak ada di tabel ini.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplikat sudah dihapus — “%1$@” kini unik. Nilai: %2$.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplikat sudah dihapus, tetapi “%1$@” masih punya %2$d baris kembar (tadinya %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "baris-baris itu sama pada KUNCI-nya, tetapi tidak pada seluruh barisnya, jadi Anda harus melihat dan memilih ",
        "giữ hàng nào.": "mana yang dipertahankan.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Tidak ada nilai pelanggar aturan ini yang dapat dibaca.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d nilai keliru di kolom “%2$@” — isi kolom Ganti, lalu lihat pratinjau",
        "Đã chấm lại: %.0f/100": "Dinilai ulang: %.0f/100",
        "Xem trước báo cáo": "Pratinjau laporan",
        "Tham số…": "Parameter…",
        "Xuất HTML…": "Ekspor HTML…",
        "In / PDF…": "Cetak / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%1$d blok berjalan · %2$d blok GAGAL",
        "%d khối chạy được": "%d blok berjalan",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · DATA USANG — berkas sumber berubah; bangun ulang",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Pratinjau laporan memerlukan dokumen .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Sumber data tidak ditemukan — nyatakan “source: file.csv” di frontmatter.",
        "Không dựng được báo cáo.": "Laporan tidak dapat dibangun.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Laporan ini tidak menyatakan parameter apa pun di frontmatter-nya.",
        "Tham số báo cáo": "Parameter laporan",
        "Dựng lại": "Bangun ulang",
        "Đã xuất %@": "Diekspor %@",
        "Báo cáo: xem trước": "Laporan: Pratinjau",
        "Báo cáo: sinh loạt…": "Laporan: Buat sekaligus…",
        "không phải tài liệu .greport.md": "bukan dokumen .greport.md",
        "không phân tích được báo cáo": "laporan tidak dapat diurai",
        "không tìm được dữ liệu nguồn": "data sumber tidak ditemukan",
        "không đọc được danh sách tham số": "daftar parameter tidak dapat dibaca",
        "Sinh loạt cần tài liệu đuôi .%@": "Pembuatan sekaligus memerlukan dokumen .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Pilih daftar parameter (CSV atau JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Pilih folder untuk %d laporan",
        "[%d/%d] %@": "[%1$d/%2$d] %3$@",
        "thiếu tham số ": "parameter yang hilang ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "menunjuk ke berkas sumber itu sendiri — menolak menimpanya",
        "%d khối HỎNG": "%d blok GAGAL",
        "Sinh loạt xong: %d tệp · %d hỏng": "Selesai sekaligus: %1$d berkas · %2$d gagal",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d set parameter tidak dapat disusun — lihat ringkasannya",
        "Sơ đồ Mermaid: xem trước": "Diagram Mermaid: Pratinjau",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagram Mermaid: Sisipkan templat…",
        "Sơ đồ Mermaid: định dạng lại": "Diagram Mermaid: Rapikan ulang",
        "Nền trong suốt": "Latar tembus pandang",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Mac ini tidak dapat meraster diagram menjadi PNG — perlu macOS 13. Ekspor SVG tetap berjalan.",
        "Lưu PNG %@…": "Simpan PNG %@…",
        "Lưu SVG…": "Simpan SVG…",
        "Chép ảnh vào clipboard": "Salin gambar ke papan klip",
        "Màu thương hiệu…": "Warna merek…",
        "Màu thương hiệu cho sơ đồ": "Warna merek untuk diagram",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Setiap ruas adalah warna #rrggbb. Disimpan ke “themes/mermaid-brand.json” — salin berkas itu ke Mac lain.",
        "Màu chính": "Warna utama",
        "Chữ trên nút": "Teks pada simpul",
        "Viền": "Bingkai",
        "Đường nối": "Tautan",
        "Nền khi xuất ảnh": "Latar saat mengekspor",
        "Lưu và chèn %%{init}%% vào tài liệu": "Simpan dan sisipkan %%{init}%% ke dokumen",
        "Đã lưu màu thương hiệu": "Warna merek tersimpan",
        "Đã chép ảnh sơ đồ vào clipboard": "Gambar diagram disalin ke papan klip",
        "Đã lưu %@ — %@": "Tersimpan %1$@ — %2$@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Diagram ini sudah punya arahan %%{init}%% — milik Anda dibiarkan apa adanya.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% disisipkan — diagram kini membawa warnanya sendiri",
        "Chèn màu thương hiệu vào sơ đồ": "Sisipkan warna merek ke dalam diagram",
        "Định dạng sơ đồ Mermaid": "Rapikan ulang diagram Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Sumber diagram sudah rapi — tidak ada yang perlu diubah",
        "Đã định dạng lại sơ đồ": "Diagram sudah dirapikan ulang",
        "Đã định dạng lại %d sơ đồ": "Dirapikan ulang %d diagram",
        "Thư viện mẫu sơ đồ": "Pustaka templat diagram",
        "Mẫu sơ đồ đầy đủ": "Templat diagram utuh",
        "Mẩu cú pháp": "Potongan sintaks",
        "Đang soạn: %@": "Sedang menyunting: %@",
        "Đã chèn mẫu «%@»": "Templat “%@” disisipkan",
        "Tài liệu đang ở chế độ chỉ đọc.": "Dokumen ini hanya-baca.",
        "Sơ đồ Mermaid": "Diagram Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Dokumen ini tidak punya blok mermaid.",
        "Thương hiệu": "Merek",
        "Xuất…": "Ekspor…",
        "Chưa có sơ đồ nào": "Belum ada diagram",
        "%d sơ đồ · %@": "%d diagram · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d diagram GAGAL — diagram %3$d%4$@",
        ", dòng %d": ", baris %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Dokumen ini tidak punya blok ```mermaid dan bukan berkas .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Belum ada diagram yang selesai digambar.",
        "Không tìm thấy «%@» trong mã sơ đồ": "“%@” tidak ditemukan di sumber diagram",
        "không dựng được hàng rào chặn mạng cho WKWebView": "pemblokir jaringan untuk WKWebView tidak dapat dibuat",
        "Luật kết hợp": "Aturan asosiasi",
        "Mỗi dòng một giỏ": "Satu keranjang per baris",
        "Hai cột: mã · item": "Dua kolom: id · barang",
        "Dạng dữ liệu giao dịch": "Bentuk data transaksi",
        "Cột giỏ hàng hoặc mã giao dịch": "Kolom keranjang atau kolom id transaksi",
        "Cột item": "Kolom barang",
        "Ký tự phân tách item": "Karakter pemisah barang",
        "Support tối thiểu, phần trăm": "Dukungan minimum, persen",
        "Confidence tối thiểu, phần trăm": "Keyakinan minimum, persen",
        "Tách bởi:": "Pisahkan dengan:",
        "Support \u{2265}": "Dukungan ≥",
        "% · Confidence \u{2265}": "% · Keyakinan ≥",
        "Bảng luật kết hợp": "Tabel aturan asosiasi",
        "Support": "Dukungan",
        "Confidence": "Keyakinan",
        "Lift": "Angkat",
        "Leverage": "Ungkitan",
        "Cảnh báo": "Awas",
        "%d giao dịch · %d item · %d luật": "%d transaksi · %d barang · %d aturan",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — tidak ada aturan yang mencapai ambang; turunkan dukungan atau keyakinan",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — BERHENTI LEBIH AWAL, tabel ini BELUM LENGKAP",
        "%d / %d giao dịch chứa cả hai vế": "%1$d / %2$d transaksi memuat kedua sisinya",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Bentuk dua kolom memerlukan dua kolom yang BERBEDA.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "Ditandai %1$d baris di %2$d transaksi yang memuat “%3$@”",
        "CSV: luật kết hợp…": "CSV: Aturan Asosiasi…",
        "Khai phá theo nhóm": "Penambangan kelompok",
        "Cột nhóm": "Kolom pengelompokan",
        "Cột giá trị": "Kolom nilai",
        "Cột thứ hai cho tương quan": "Kolom kedua untuk korelasi",
        "Cách xếp hạng": "Peringkat",
        "Nhóm theo:": "Kelompokkan menurut:",
        "Giá trị:": "Nilai:",
        "Xếp theo:": "Peringkatkan menurut:",
        "Bảng xếp hạng nhóm": "Tabel peringkat kelompok",
        "Nhóm": "Kelompok",
        "Hàng": "Baris",
        "Hàng rào riêng": "Ambang sendiri",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "beda r",
        "Ghi chú": "Catatan",
        "không đo được": "tak terukur",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d kelompok · korelasi gabungan %@",
        " · ĐÃ CẮT %d nhóm": " · %d KELOMPOK DIBUANG",
        "Bảng này không có cột chữ nào để gom nhóm.": "Tabel ini tidak punya kolom teks untuk dikelompokkan.",
        "Bảng này không có cột số nào để khai phá.": "Tabel ini tidak punya kolom angka untuk ditambang.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "Ditandai %1$d baris kelompok “%2$@”",
        "CSV: khai phá theo nhóm…": "CSV: Penambangan Kelompok…",
        "\u{2194}": "↔",
        "Dự báo": "Ramalan",
        "Cột giá trị theo thời gian": "Kolom nilai sepanjang waktu",
        "Mô hình dự báo": "Model ramalan",
        "Số kỳ dự báo": "Banyaknya periode yang diramalkan",
        "Kết luận so với baseline": "Putusan terhadap model acuan",
        "Mô hình:": "Model:",
        "Số kỳ:": "Periode:",
        "Chu kỳ:": "Musim:",
        "tự": "otomatis",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Panjang musim; biarkan kosong agar dideteksi otomatis",
        "Bảng giá trị dự báo": "Tabel nilai ramalan",
        "Kỳ": "Periode",
        "Dải 80%": "Pita 80 persen",
        "Dải 95%": "Pita 95 persen",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "tak terhitung",
        "Bảng này không có cột số nào để dự báo.": "Tabel ini tidak punya kolom angka untuk diramalkan.",
        "Không dựng được dự báo cho cột này.": "Ramalan untuk kolom ini tidak dapat dibangun.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Kolom “%1$@” hanya punya %2$d nilai angka — meramalkan perlu setidaknya 4.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Deret dibaca menurut urutan baris di berkas — tanpa diurutkan ulang dan tanpa menebak kolom waktu.\n",
        "Sai số huấn luyện": "Galat pelatihan",
        "CSV: dự báo chuỗi thời gian…": "CSV: Ramalkan Deret Waktu…",
        "Holt-Winters cộng": "Holt-Winters aditif",
        "Holt-Winters nhân": "Holt-Winters multiplikatif",
        "seasonal-naive": "naif musiman",
        "naive": "naif",
        "Cột đưa vào phân cụm": "Kolom yang masuk ke pengelompokan",
        "Đường cong WCSS": "Kurva WCSS",
        "Phân cụm": "Gugus",
        "Chuẩn hoá:": "Penskalaan:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Pilih setidaknya satu kolom.",
        "Không đủ dữ liệu để dựng đường cong.": "Data tidak cukup untuk membangun kurva.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Sikunya menyarankan k = %d. WCSS SELALU turun saat k membesar, jadi ini cara membaca grafik, bukan kriteria statistik — lihat kurvanya dan nilai sendiri apakah tekukannya jelas.",
        "WCSS theo k": "WCSS menurut k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "Jarak-k menyarankan eps = %1$@ (minPts bawaannya 2 × jumlah kolom = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Jarak ke tetangga ke-k",
        "Cần ít nhất 2 cột số để phân cụm.": "Pengelompokan memerlukan setidaknya 2 kolom angka.",
        "Cụm theo %@ và %@": "Gugus menurut %@ dan %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — gugus ditemukan dalam %d dimensi; grafik hanya menampilkan 2 yang pertama",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# derau (cluster_id = -1): %d baris\n",
        "CSV: phân cụm…": "CSV: Gugus…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Pusat gugus (satuan asli) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Matriks korelasi",
        "Phương pháp tương quan": "Metode korelasi",
        "Tương quan không hàm ý nhân quả.": "Korelasi bukan berarti sebab-akibat.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Pasangan terkuat: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klik satu sel untuk grafik sebar.",
        "Không cặp nào đo được.": "Tidak ada pasangan yang dapat diukur.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ pada %4$d baris",
        "Cần ít nhất 2 cột số để tính tương quan.": "Korelasi memerlukan setidaknya 2 kolom angka.",
        "Không đọc được cột «%@».": "Kolom “%@” tidak dapat dibaca.",
        "CSV: ma trận tương quan…": "CSV: Matriks Korelasi…",
        "Bất thường": "Keanehan",
        "Danh sách bất thường": "Daftar keanehan",
        "Cột:": "Kolom:",
        "Cột số cần xét": "Kolom angka yang diperiksa",
        "Cách:": "Metode:",
        "Phương pháp phát hiện": "Metode pendeteksian",
        "Phương pháp đã dùng": "Metode yang dipakai",
        "Ngưỡng": "Ambang",
        "Đánh dấu": "Tandai",
        "Xuất tab mới": "Ekspor ke tab baru",
        "Dòng": "Baris",
        "Điểm": "Skor",
        "Vì sao": "Alasan",
        "nhẹ": "ringan",
        "vừa": "sedang",
        "nặng": "berat",
        "z-score": "skor-z",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%1$d / %2$d baris (%3$.2f%%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Tabel ini tidak punya kolom angka untuk dipindai keanehannya.",
        "Đã đánh dấu %d dòng bất thường": "Ditandai %d baris yang aneh",
        "CSV: tìm bất thường…": "CSV: Cari Keanehan…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d aturan, semua LOLOS · %2$d baris · %3$.0f md",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d galat · %2$d peringatan pada %3$d aturan · %4$d baris · %5$.0f md",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Simpan dokumennya dulu — aturan mutu tinggal di sebelah berkas data.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Belum ada berkas aturan. Buat %@ lalu buka kembali.",
        "Lịch sử": "Riwayat",
        "Câu đã lưu": "Kueri tersimpan",
        "Lưu câu này…": "Simpan kueri ini…",
        "Lưu câu truy vấn": "Simpan kueri",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Beri nama agar mudah ditemukan nanti. Nama yang sama akan menimpa.",
        "Ví dụ: Doanh thu theo tỉnh": "Misalnya: Pendapatan per provinsi",
        "Chưa nhập giá trị cho tham số: %@": "Belum ada nilai untuk parameter: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Pengaya berubah sejak Anda menyetujuinya — GEditor menolak menjalankannya",
        "Chạy plugin chưa duyệt?": "Jalankan pengaya yang belum disetujui?",
        "Tôi tin file này — chạy": "Saya percaya berkas ini — jalankan",
        "KHÔNG có chữ ký": "TANPA tanda tangan",
        "Chữ ký: %@": "Tanda tangan: %@",
        "Đường dẫn: %@": "Jalur: %@",
        "Thay": "Ganti",
        "Thay tất cả": "Ganti Semua",
        "Chuỗi thuần": "Teks biasa",
        "Extended (\\n \\t \\xNN)": "Diperluas (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Ekspresi reguler",
        "Phân biệt hoa thường": "Bedakan huruf besar-kecil",
        "Cả từ": "Kata utuh",
        "Không có kết quả": "Tidak ada hasil",
        "Thử biểu thức chính quy…": "Uji Ekspresi Reguler…",
        "Chế độ Log (tô theo mức)": "Mode Log (warna menurut tingkat)",
        "Lọc log theo mức…": "Saring Log menurut Tingkat…",
        "Chạy trên cả thư mục…": "Jalankan pada Seluruh Folder…",
        "Lọc qua lệnh ngoài…": "Saring lewat Perintah…",
        "Script…": "Skrip…",
        "Gói mở rộng…": "Paket Perluasan…",
        "Cửa sổ mới": "Jendela Baru",
        "Tách tab ra cửa sổ mới": "Pindahkan Tab ke Jendela Baru",
        "Chưa mở thư mục nào": "Tidak ada folder yang terbuka",
        "Tìm file trong thư mục": "Cari berkas di folder",
        "Lọc theo tên": "Saring menurut nama",
        "File mới…": "Berkas Baru…",
        "Thư mục mới…": "Folder Baru…",
        "Đổi tên…": "Ganti Nama…",
        "Chuyển vào Thùng rác": "Pindahkan ke Tong Sampah",
        "Hiện trong Finder": "Tampilkan di Finder",
        "Đang đọc cấu trúc tài liệu…": "Membaca struktur dokumen…",
        "file này không có hàm nào": "tidak ada fungsi di berkas ini",
        "Không có gì khớp": "Tidak ada yang cocok",
        "Văn bản thuần": "Teks biasa",
        "🔒 Chỉ đọc": "🔒 Hanya-baca",
        "Đang theo dõi": "Sedang diikuti",
        "ngắt tại cột": "bungkus pada kolom",
        "Cú pháp": "Sintaks",
        "Bấm để chèn vào ô truy vấn": "Klik untuk menyisipkan ke kotak kueri",
        "truy vấn không hợp lệ": "kueri tidak sah",
        "khóa `ten` ở gốc": "kunci `ten` di akar",
        "khóa có dấu cách": "kunci yang mengandung spasi",
        "phần tử đầu": "elemen pertama",
        "mọi phần tử": "semua elemen",
        "lát cắt": "irisan",
        "hợp nhiều chỉ số": "gabungan indeks",
        "mọi khóa `gia` ở mọi tầng": "semua kunci `gia` pada kedalaman mana pun",
        "mọi nút": "semua simpul",
        "lọc theo số": "saring menurut angka",
        "lọc theo có mặt": "saring menurut keberadaan",
        "Tới lỗi đầu tiên": "Ke masalah pertama",
        "Cột doanh_thu là số": "Kolom doanh_thu berupa angka",
        "lọc…": "saring…",
        "Hủy": "Batal",
        "Thực hiện thay": "Ganti",
        "xem trước": "pratinjau",
        "tương tác": "interaktif",
        "Soạn thảo": "Penyuntingan",
        "Giao diện": "Tampilan",
        "Phím tắt": "Pintasan Papan Ketik",
        "Cỡ chữ": "Ukuran huruf",
        "Bề rộng TAB": "Lebar tab",
        "Thụt lề bằng TAB": "Indentasi dengan tab",
        "Tự động thụt lề khi xuống dòng": "Indentasi otomatis di baris baru",
        "Tô mọi kết quả tìm kiếm": "Sorot semua hasil pencarian",
        "Chuẩn hóa về NFC khi lưu": "Normalkan ke NFC saat menyimpan",
        "Ngôn ngữ": "Bahasa",
        "Nền": "Latar",
        "Theo hệ thống": "Ikut sistem",
        "Sáng": "Terang",
        "Tối": "Gelap",
        "Theme": "Tema",
        "Dùng preset Notepad++": "Pakai prasetel Notepad++",
        "Về phím mặc định": "Kembalikan tombol bawaan",
        "Mở file cấu hình": "Buka berkas konfigurasi",
        "Xuất theme hiện tại": "Ekspor tema saat ini",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Pergantian bahasa berlaku sepenuhnya saat aplikasi dibuka berikutnya.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Tombol bawaan kembali saat aplikasi dibuka berikutnya.",
        "Xem trước Markdown": "Pratinjau Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Digambar dengan mesin Markdown bawaan sistem: tabel dan pewarnaan blok kode belum didukung.",
        "Thử biểu thức chính quy": "Penguji Ekspresi Reguler",
        "Biểu thức": "Ekspresi",
        "Văn bản thử": "Teks contoh",
        "Kết quả": "Hasil",
        "Kết quả khớp": "Hasil kecocokan",
        "Biểu thức này làm gì": "Apa yang dilakukan ekspresi ini",
        "Giải thích biểu thức": "Penjelasan ekspresi",
        "Chế độ tìm kiếm": "Mode pencarian",
        "Kết quả tìm kiếm": "Hasil pencarian",
        "Không khớp chỗ nào": "Tidak ada yang cocok",
        " (đã cắt bớt)": " (dipotong)",
        "Bản đồ tài liệu": "Peta dokumen",
        "Thanh tab": "Bilah tab",
        "Hàng tiêu đề cột": "Baris tajuk kolom",
        "Không có cột nào": "Tidak ada kolom",
        "Cây thư mục workspace": "Pohon berkas ruang kerja",
        "Danh sách hàm và lớp": "Daftar fungsi dan kelas",
        "Kết quả tìm trong thư mục": "Hasil pencarian di folder",
        "Bảng dữ liệu CSV": "Tabel data CSV",
        "Bàn làm sạch dữ liệu": "Meja pembersihan data",
        "Truy vấn JSONPath": "Kueri JSONPath",
        "Danh sách lỗi dữ liệu": "Daftar masalah data",
        "Bộ đánh giá golden set…": "Set emas…",
        "So với điểm ngoài (JSONL)…": "Bandingkan dengan skor dari luar (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Pilih berkas skor dari luar (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Ganti nama simpul terpilih",
        "Gộp các node đang chọn": "Gabungkan simpul terpilih",
        "Tách node đang chọn": "Pecah simpul terpilih",
        "Trích subgraph đang chọn ra tab mới": "Keluarkan subgraf terpilih ke tab baru",
        "Không có gì để đổi": "Tidak ada yang perlu diubah",
        "%@ — áp %d thay đổi?": "%1$@ — terapkan %2$d perubahan?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d perubahan · Cmd-Z mengurungkan seluruh rangkaian",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Letakkan kursor tepat pada SATU simpul, lalu jalankan lagi",
        "Đổi tên «%@»": "Ganti nama “%@”",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Semua sisi dan label yang menunjuk simpul ini ikut berubah.",
        "Đổi tên node": "Ganti nama simpul",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Pilih DUA simpul atau lebih, lalu jalankan lagi",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Bentuk baku “%@” — paling sering, paling panjang, memakai tanda diakritik",
        "Gộp node": "Gabungkan simpul",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Pilih BARIS-BARIS SISI yang dipindahkan, lalu jalankan lagi",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Setiap baris terpilih harus menyentuh tepat SATU simpul yang sama — pilih lebih banyak baris sisi",
        "Tách «%@» — chuyển %d cạnh": "Pecah “%1$@” — pindahkan %2$d sisi",
        "Cạnh tới: %@": "Sisi ke: %@",
        "Tách node": "Pecah simpul",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Dokumen belum disimpan — berkas hasil perlu tempat untuk berdampingan",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Pilih bagian graf yang dikeluarkan, lalu jalankan lagi",
        "Gom biến thể entity → bảng duyệt": "Kelompokkan ragam entitas → tabel tinjauan",
        "Áp bảng duyệt đã sửa": "Terapkan tabel tinjauan yang sudah disunting",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Dokumen belum disimpan — tabel tinjauan harus berada di sebelah berkas graf",
        "Không tìm thấy biến thể nào để gom": "Tidak ada ragam yang bisa dikelompokkan",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d kelompok ragam — sunting kolom “canonical”, lalu jalankan “Terapkan”",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Belum ada tabel tinjauan “%@” — jalankan “Kelompokkan ragam entitas” dulu",
        "Bảng duyệt không đọc được: %@": "Tabel tinjauan tidak dapat dibaca: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Tabel tinjauan tidak punya baris yang perlu diubah",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Tidak ada bagian graf yang cocok dengan tabel tinjauan",
        "Gom biến thể entity": "Kelompokkan ragam entitas",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "Diterapkan %d perubahan · tabel alias dan daftar penanda ditulis di sebelah berkas",
        "Áp %d thay đổi lên đồ thị?": "Terapkan %d perubahan pada graf?",
        "%d alias → dạng chuẩn.": "%d alias → bentuk baku.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "MENGGABUNGKAN simpul (tidak bisa dibatalkan dengan mengetik ulang):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d alias tidak ada di graf dan dilewati.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Cakupan penggalan ↔ entitas",
        "Xuất gói ngữ cảnh (JSONL)": "Ekspor paket konteks (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Cakupan penggalan ↔ entitas ↔ graf",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d entitas · %2$d penggalan · %3$.0f%% entitas disebut · %4$.0f%% penggalan memuat entitas",
        "Entity không chunk nào nhắc tới": "Entitas yang tidak disebut penggalan mana pun",
        "Chunk mồ côi (không chứa entity nào)": "Penggalan yatim (tanpa entitas di dalamnya)",
        "Node đồ thị không có entity đối ứng": "Simpul graf tanpa entitas yang cocok",
        "không có": "tidak ada",
        "Phương pháp": "Metode",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Pemetaan penggalan ↔ entitas tidak dapat dibangun",
        "Chấm sức khoẻ đồ thị": "Nilai kesehatan graf",
        "sức khoẻ đồ thị": "kesehatan graf",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Kesehatan %1$@/100 · %2$d masalah · %3$d pulau · %4$d menyendiri",
        "Lai với đồ thị": "Hibrida dengan graf",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: sinyal graf mati sama sekali, hasilnya sama dengan BM25 polos",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α tinggi: graf hanya menggeser sedikit peringkat BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α di sekitar bawaan 0,7: BM25 memimpin, graf menyesuaikan",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α rendah: graf memimpin, BM25 hanya memutus seri",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: hanya sinyal graf; penggalan tanpa entitas semuanya seri",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Dokumen belum disimpan — hibrida perlu berkas graf di sebelah korpus",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Tidak ada berkas graf “%@” — hibrida memerlukannya agar punya sinyal",
        "lai %.1f ms · %@": "hibrida %.1f md · %@",
        "Thuật toán…": "Algoritme…",
        "PageRank (độ dày viền)": "PageRank (tebal garis tepi)",
        "Cộng đồng (màu nền)": "Komunitas (warna isi)",
        "Thành phần liên thông": "Komponen terhubung",
        "Xuất bảng node ra tab mới": "Ekspor tabel simpul ke tab baru",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d komponen · terbesar %2$d simpul · %3$d menyendiri",
        "Tài liệu này không phải đồ thị DOT": "Dokumen ini bukan graf DOT",
        "Không dựng được bảng node/cạnh: %@": "Tabel simpul/sisi tidak dapat dibangun: %@",
        "%d hàng · %@": "%d baris · %@",
        "Gán nhãn": "Label",
        "Ghi chú (tuỳ chọn)": "Catatan (boleh dikosongkan)",
        "Lưu record": "Simpan catatan",
        "Xuất CSV": "Ekspor CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Dokumen belum disimpan — set penilaian harus berada di sebelah berkas korpus",
        "Không nạp được bộ đánh giá: %@": "Set penilaian tidak dapat dimuat: %@",
        "Không lưu được: %@": "Tidak dapat disimpan: %@",
        "Bộ đánh giá chưa có record nào": "Set penilaian belum punya satu pun catatan",
        "Không ghi được: %@": "Tidak dapat ditulis: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Dokumen ini bukan berkas .mmd, bukan DOT, dan tidak punya blok mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d simpul · %d sisi · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagram Mermaid: tambah elemen…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagram Mermaid: hubungkan dua elemen terpilih",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagram Mermaid: ubah label elemen terpilih…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagram Mermaid: hapus elemen terpilih",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagram Mermaid: naikkan pesan",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagram Mermaid: turunkan pesan",
        "Thêm phần tử": "Tambah elemen",
        "Thêm participant": "Tambah peserta",
        "Thêm mục": "Tambah butir",
        "Thêm mục sơ đồ": "Tambah butir diagram",
        "Sửa mục sơ đồ": "Ubah butir diagram",
        "Xoá mục sơ đồ": "Hapus butir diagram",
        "Xoá phần tử": "Hapus elemen",
        "Sửa nhãn": "Ubah label",
        "Đổi thứ tự message": "Susun ulang pesan",
        "Tên mục": "Nama butir",
        "Mục mới": "Butir baru",
        "Tên mục hiện trên sơ đồ.": "Nama butir yang tampil pada diagram.",
        "Bảng thuộc tính sơ đồ": "Tabel properti diagram",
        "Tài liệu này không có khối mermaid nào": "Dokumen ini tidak punya blok mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Pengenal di sumber diagram — tanpa spasi. Labelnya diubah nanti dengan klik ganda.",
        "Để trống thì hiện chính định danh.": "Kosongkan agar pengenalnya sendiri yang tampil.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Yang berubah hanya LABEL yang tampil; pengenal elemen tetap sama.",
        "Không rõ «%@» là phần tử nào": "Tidak jelas elemen yang mana “%@” itu",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Pilih tepat DUA elemen, lalu jalankan lagi",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Letakkan kursor tepat pada SATU elemen, lalu jalankan lagi",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Pilih SATU elemen untuk dihapus, atau dua elemen yang terhubung sisi",
        "Xoá «%@» và %d cạnh chạm nó?": "Hapus “%1$@” dan %2$d sisi yang menyentuhnya?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Simpul di ujung seberang sisi-sisi itu dipertahankan — ia dinyatakan ulang beserta labelnya jika perintah sisi tadi satu-satunya tempat ia dinyatakan.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Diagram “%1$@” hanya bisa disunting sebagai teks — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: seret di antara dua elemen untuk menghubungkannya, klik ganda untuk mengubah label",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: seret di antara dua peserta untuk menambah pesan; urutannya diubah dari menu Alat",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: sunting di tabel properti di bawah",
        "Soạn trực quan đã bật": "Penyuntingan visual menyala",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d butir — sunting langsung di tempat; setiap sel satu langkah urung",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Untuk pie berupa angka; untuk gantt, semua yang mengikuti titik dua.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagram Mermaid: keluarkan blok ke berkas .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagram Mermaid: benamkan kembali berkas yang dirujuk",
        "Tách khối sơ đồ": "Keluarkan blok diagram",
        "Nhúng khối sơ đồ": "Benamkan blok diagram",
        "Tách khối sơ đồ ra tệp riêng": "Keluarkan blok diagram ke berkasnya sendiri",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Berkasnya berdampingan DENGAN dokumen; bloknya menyisakan satu baris rujukan agar penyuntingan terjadi di satu tempat saja.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Dokumen belum disimpan — berkas diagram perlu tempat untuk berdampingan",
        "Đã có tệp «%@» — chọn tên khác": "Berkas “%@” sudah ada — pilih nama lain",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Dikeluarkan ke “%@” — bloknya menyisakan satu baris rujukan",
        "Mở tệp": "Buka berkas",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "“%@” sudah dibenamkan kembali; berkasnya masih ada di cakram",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Blok ini memuat diagram sungguhan, bukan rujukan",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Blok ini merujuk ke “%@” — buka berkas itu untuk menyuntingnya",
        "Không đọc được tệp sơ đồ %@": "Berkas diagram tidak dapat dibaca: %@",
        "Soạn trực quan": "Penyuntingan visual",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Seret dari satu simpul ke simpul lain untuk menambah sisi; klik ganda untuk mengubah label. Setiap tindakan adalah satu langkah urung.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Penyuntingan visual: seret di antara dua simpul untuk menambah sisi, klik ganda untuk mengubah label",
        "Soạn trực quan đã tắt": "Penyuntingan visual mati",
        "Thêm node…": "Tambah simpul…",
        "Thêm cạnh giữa hai node đang chọn…": "Tambah sisi di antara dua simpul terpilih…",
        "Sửa nhãn node đang chọn…": "Ubah label simpul terpilih…",
        "Xoá node/cạnh đang chọn": "Hapus simpul atau sisi terpilih",
        "Thêm node": "Tambah simpul",
        "Thêm cạnh": "Tambah sisi",
        "Sửa nhãn node": "Ubah label simpul",
        "Xoá node": "Hapus simpul",
        "Xoá cạnh": "Hapus sisi",
        "Cmd-Z hoàn tác": "Cmd-Z untuk mengurungkan",
        "Tài liệu đang ở chế độ chỉ đọc": "Dokumen ini hanya-baca",
        "Nhãn của «%@»": "Label “%@”",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Yang berubah hanya LABEL yang tampil; pengenal simpul tetap sama.",
        "Không rõ «%@» là node nào": "Tidak jelas simpul yang mana “%@” itu",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Pengenal simpul di berkas DOT. Labelnya diubah nanti dengan klik ganda pada diagram.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Pilih tepat DUA simpul, lalu jalankan lagi",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Pilih SATU simpul untuk menghapus simpul, atau dua simpul yang terhubung sisi",
        "Xoá node «%@» và %d cạnh chạm nó?": "Hapus simpul “%1$@” dan %2$d sisi yang menyentuhnya?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Kalau sisinya dibiarkan menggantung, DOT membuat ulang simpulnya justru dari sisi-sisi itu — simpul yang baru dihapus akan muncul lagi pada penggambaran berikutnya.",
        "Phòng thí nghiệm truy hồi BM25": "Lab pencarian BM25",
        "Câu hỏi — Enter để tìm": "Pertanyaan — tekan Return untuk mencari",
        "Đánh giá…": "Nilai…",
        "Đang dựng chỉ mục": "Sedang membangun indeks",
        "Không chunk nào khớp": "Tidak ada penggalan yang cocok",
        "kết quả trên": "hasil dari",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: setiap kata dihitung SEKALI saja, sesering apa pun ia muncul",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 rendah: mengulang satu kata hampir tidak menambah apa-apa",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 di sekitar bawaan 1,2: pengulangan menambah skor, tetapi makin lama makin sedikit",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 tinggi: penggalan yang mengulang satu kata diganjar besar",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: panjang diabaikan, penggalan panjang tidak dihukum",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b rendah: penggalan panjang hanya dihukum sedikit",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b di sekitar bawaan 0,75: penggalan panjang dihukum sedang-sedang",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: hukuman panjang paling besar, penggalan pendek diuntungkan",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: lab pencarian…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Dokumen belum disimpan — indeks BM25 tinggal di sebelah berkas korpus, jadi ia perlu jalur",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Berkas ini bukan JSONL — Lab Pencarian bekerja pada korpus penggalan",
        "Không dựng được chỉ mục BM25 cho tệp này": "Indeks BM25 untuk berkas ini tidak dapat dibangun",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Dokumen belum disimpan — perlu jalur korpus untuk membuat laporannya",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Pilih set penilaian (CSV atau JSONL: pertanyaan + id penggalan yang diharapkan)",
        "Đánh giá truy hồi": "Penilaian pencarian",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Ubah k1, b atau k di atas lalu gambar ulang untuk membandingkan dua konfigurasi; tambahkan blok “compare” agar dua set parameter berjalan berdampingan pada set penilaian yang sama.",
        "Lỗi": "Galat",
        "   (%d…%d, trung bình %.0f)": "   (%1$d…%2$d, rerata %3$.0f)",
        "Chế độ JSONL": "Mode JSONL",
        "Bản ghi": "Catatan",
        "Chi tiết": "Rincian",
        "Bản ghi ở dòng": "Catatan di baris",
        "không phải JSON hợp lệ": "bukan JSON yang sah",
        "bản ghi": "catatan",
        "dòng trắng": "baris kosong",
        "không phải đối tượng": "bukan objek",
        "bảng hiện": "tabel menampilkan",
        "ĐÃ HUỶ giữa chừng": "DIBATALKAN DI TENGAH JALAN",
        "Không lọc": "Tanpa saringan",
        "bản ghi khớp bộ lọc": "catatan cocok dengan saringan",
        "Đưa con nháy tới một dòng để xem bản ghi": "Pindahkan kursor ke satu baris untuk melihat catatannya",
        "Không có bản ghi nào hỏng": "Tidak ada catatan yang rusak",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Belum diperiksa. Jalankan “JSONL: periksa penggalan” setelah pemeriksaan selesai.",
        "trường văn bản": "ruas teks",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SKEMA (tebakan — pilih ruas lain untuk mengubahnya)",
        "văn bản": "teks",
        "định danh": "pengenal",
        "metadata lồng": "metadata bersarang",
        "TRƯỜNG": "RUAS",
        "phủ": "ada pada",
        "nhiều kiểu": "tipe campur",
        "ĐỘ DÀI — ký tự": "PANJANG — karakter",
        "ĐỘ DÀI — từ": "PANJANG — kata",
        "ĐỘ DÀI — token ước lượng": "PANJANG — perkiraan token",
        "RỖNG VÀ TRÙNG": "KOSONG DAN KEMBAR",
        "chunk rỗng": "penggalan kosong",
        "dòng": "baris",
        "nhóm trùng chính xác": "kelompok kembar persis",
        "dòng không đọc được, không vào thống kê": "baris tak terbaca, tidak dihitung dalam statistik",
        "PHƯƠNG PHÁP": "METODE",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "“karakter” menghitung skalar Unicode, bukan kelompok tampilan",
        "«từ» tách theo khoảng trắng ASCII": "“kata” dipisah pada spasi ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "“token” memakai pemenggal suku kata — BUKAN milik modelnya",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "“kembar” berarti PERSIS sama; yang HAMPIR sama ada di blok ```quality",
        "chunk": "penggalan",
        "JSONL: kiểm và soi chunk…": "JSONL: periksa dan telaah penggalan…",
        "Ảnh": "Gambar",
        "PDF": "PDF",
        "Tài liệu Word": "Dokumen Word",
        "Bảng tính Excel": "Lembar kerja Excel",
        "Bản trình chiếu PowerPoint": "Presentasi PowerPoint",
        "File nén": "Arsip",
        "Vừa khung": "Paskan",
        "Chép ảnh": "Salin gambar",
        "Xoay": "Putar",
        "Không đọc được ảnh «%@»": "Gambar “%@” tidak dapat dibaca",
        "Đã chép ảnh vào clipboard": "Gambar disalin ke papan klip",
        "Bôi vàng": "Sorot",
        "Gạch chân": "Garis bawah",
        "Ghi chú…": "Catatan…",
        "Bỏ chú thích": "Hapus anotasi",
        "Lấy chữ ra tab mới": "Keluarkan teksnya ke tab baru",
        "Lưu bản có chú thích…": "Simpan salinan beranotasi…",
        "Tìm trong PDF": "Cari di PDF",
        "Thêm": "Tambah",
        "Trang %d/%d": "Halaman %d dari %d",
        "Trang %d": "Halaman %d",
        "Kết quả %d/%d": "Kecocokan %d dari %d",
        "0 kết quả": "Tidak ada yang cocok",
        "Không đọc được PDF «%@»": "PDF “%@” tidak dapat dibaca",
        "PDF này có mật khẩu — chưa mở được nội dung": "PDF ini dilindungi kata sandi — isinya tidak dapat dibuka",
        "Không thấy «%@» trong tài liệu": "“%@” tidak ada di dokumen ini",
        "Đã bôi vàng": "Sudah disorot",
        "Đã gạch chân": "Sudah digarisbawahi",
        "Hãy bôi đen một đoạn chữ trước": "Pilih sepotong teks dulu",
        "Đã thêm ghi chú": "Catatan ditambahkan",
        "Trang này chưa có chú thích nào": "Halaman ini tidak punya anotasi",
        "Đã bỏ %d chú thích trên trang này": "Dihapus %d anotasi dari halaman ini",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "PDF ini tidak punya lapisan teks — kemungkinan besar hasil pindaian",
        "Không ghi được tệp": "Berkasnya tidak dapat ditulis",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Berkas yang baru ditulis TIDAK terbuka dengan benar — jangan pakai salinan ini",
        "Đã lưu %@ · %d trang": "Tersimpan %1$@ · %2$d halaman",
        "Tên": "Nama",
        "Kích thước": "Ukuran",
        "Đã nén": "Termampat",
        "Tỉ lệ": "Nisbah",
        "Sửa lúc": "Diubah",
        "Mở mục đang chọn": "Buka butir terpilih",
        "Bung ra thư mục…": "Bongkar ke folder…",
        "Bung vào đây": "Bongkar di sini",
        "%d mục": "%d butir",
        "giải nén ra %@": "membesar menjadi %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— isi sebuah berkas Office adalah arsip; inilah bagian-bagian di dalamnya",
        "Đã bung %d mục": "Dibongkar %d butir",
        "%d mục hỏng": "%d butir gagal",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d butir DITOLAK — jalurnya keluar dari folder tujuan",
        "Không mở được mục này": "Butir ini tidak dapat dibuka",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Belum bisa menulis balik ke %@ — pakai “Simpan Sebagai…”",
        "Không có gì đổi": "Tidak ada yang berubah",
        "Đã ghi %d ô vào %@": "Ditulis %1$d sel ke %2$@",
        "Đã ghi %d đoạn vào %@": "Ditulis %1$d paragraf ke %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Tidak dapat menulis ke berkas — yang asli tidak tersentuh",
        "dựng bài": "menyiapkan kasus uji",
        "Không ghi được settings.json": "settings.json tidak dapat ditulis",
        "Xoay trái": "Putar kiri",
        "Xoay phải": "Putar kanan",
        "Trang lên": "Pindahkan halaman ke atas",
        "Trang xuống": "Pindahkan halaman ke bawah",
        "Xoá trang…": "Hapus halaman…",
        "Xoá trang": "Hapus halaman",
        "Trích trang…": "Ekstrak halaman…",
        "Trích trang ra tệp mới": "Ekstrak halaman ke berkas baru",
        "Gộp tệp PDF…": "Gabungkan berkas PDF…",
        "Tách tệp…": "Pisahkan berkas…",
        "Tách tệp PDF": "Pisahkan berkas PDF",
        "Xuất ảnh…": "Ekspor gambar…",
        "Xuất trang ra ảnh PNG": "Ekspor halaman sebagai gambar PNG",
        "Hoàn tác trang": "Urungkan penyuntingan halaman",
        "Lưu bản đã sửa…": "Simpan salinan hasil edit…",
        "Phát": "Putar",
        "Tạm dừng": "Jeda",
        "Xem bình thường": "Tampilan normal",
        "Chọn sheet": "Pilih lembar",
        "Mở sheet": "Buka lembar",
        "Bỏ và đổi sheet": "Buang dan ganti lembar",
        "Bảng tính có %d sheet.": "Buku kerja memiliki %d lembar.",
        "Bảng tính này chỉ có một sheet: «%@»": "Buku kerja ini hanya memiliki satu lembar: «%@»",
        "Bỏ phần chưa lưu của sheet này?": "Buang perubahan yang belum disimpan di lembar ini?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Berganti lembar mengganti seluruh tab. Yang belum disimpan dengan ⌘S akan hilang.",
        "Chọn tệp PDF cần gộp vào": "Pilih berkas PDF untuk digabungkan",
        "Chọn thư mục ghi ảnh": "Pilih folder untuk gambar",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Pilih lokasi simpan. Berkas kedua ditulis di sebelahnya.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Dokumen memiliki %d halaman. Masukkan halaman yang dihapus, mis. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Dokumen memiliki %d halaman. Masukkan halaman yang diekstrak, mis. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Dokumen memiliki %d halaman. Masukkan halaman yang diekspor, mis. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Dokumen memiliki %d halaman. Masukkan bagian yang dipisah, mis. 1-5; sisanya jadi berkas kedua.",
        "Đã xoay trang %d": "Halaman %d diputar",
        "Đã xoá trang %@ · còn %d trang": "Halaman %@ dihapus · sisa %d halaman",
        "Đã gộp %d trang từ «%@»": "%d halaman digabungkan dari «%@»",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Dipisahkan menjadi %@ (%d halaman) dan %@ (%d halaman)",
        "Đã ghi %@ — %@ · %d trang": "Menulis %@ — %@ · %d halaman",
        "Đã xuất %d ảnh vào %@": "%d gambar diekspor ke %@",
        "Chỉ xuất được %d/%d ảnh": "Hanya %d/%d gambar yang diekspor",
        "Đã hoàn tác một thao tác trang": "Satu operasi halaman diurungkan",
        "Không còn thao tác trang nào để hoàn tác": "Tidak ada operasi halaman untuk diurungkan",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Tidak bisa menghapus SEMUA halaman — PDF harus punya minimal satu halaman",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Rentang itu adalah seluruh dokumen — tidak ada yang dipisah",
        "«%@» có mật khẩu — chưa gộp được": "«%@» dilindungi kata sandi — tidak bisa digabungkan",
        "«%@» không có trang nào": "«%@» tidak memiliki halaman",
        "Đã ở trang đầu": "Sudah di halaman pertama",
        "Đã ở trang cuối": "Sudah di halaman terakhir",
        "· đã sửa, chưa lưu": "· disunting, belum disimpan",
        "Ảnh động · %d khung": "Gambar animasi · %d bingkai",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Dokumen belum disimpan — tidak ada berkas di disk untuk tampilan biner",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Perintah ini hanya untuk buku kerja Excel",
        "Không đọc được danh sách sheet": "Tidak dapat membaca daftar lembar",
        "Không có sheet «%@»": "Tidak ada lembar bernama «%@»",
        "Không đọc được sheet «%@»": "Tidak dapat membaca lembar «%@»",
        "Sheet «%@» · %d hàng": "Lembar «%@» · %d baris",
        "phần còn lại": "sisanya",
        "Lưu ý": "Catatan",
        "Cẩn thận": "Perhatian",
        "Xem thêm": "Lihat juga",
        "Chép": "Salin",
        "Đã chép": "Tersalin",
        "Chép đoạn mã mẫu": "Salin kode contoh",
        "Tìm trong trợ giúp": "Cari di bantuan",
        "Lùi": "Kembali",
        "Bắt đầu dùng": "Mulai",
        "Không mở cửa sổ này khi khởi động nữa": "Jangan tampilkan jendela ini saat memulai",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Bantuan belum diterjemahkan ke bahasa ini — menampilkan teks bahasa Vietnam.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Ke offset (mis. 1F400 atau 0x1F400)",
        "Chép dòng đã chọn": "Salin baris terpilih",
        "Đã chép %d dòng": "%d baris disalin",
        "Không đọc được «%@»": "Tidak dapat membaca «%@»",
        "Tệp rỗng": "Berkas kosong",
        "Không đọc được offset «%@»": "Tidak dapat membaca offset «%@»",
        "Offset 0x%@ vượt quá cỡ tệp": "Offset 0x%@ melewati ukuran berkas",
        "Mở bằng ứng dụng khác…": "Buka dengan aplikasi lain…",
        "%d kênh": "%d kanal",
        "Không phát được «%@»": "Tidak bisa memutar «%@»",
        "Không phát được — %@": "Tidak bisa diputar — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS tidak punya dekoder bawaan untuk format %@ — ini batas sistem, bukan berkas rusak.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Anda tetap bisa melihat byte dalam mode biner, atau membukanya dengan aplikasi yang punya dekoder sendiri.",
        "Ký…": "Tanda tangan…",
        "Sửa chữ…": "Sunting teks…",
        "Sửa chữ": "Sunting teks",
        "Vẽ đè": "Gambar di atasnya",
        "Ô chưa điền": "Bidang kosong berikutnya",
        "Xoá nội dung đã điền": "Hapus isian",
        "Tệp này không có ô biểu mẫu nào": "Berkas ini tidak punya bidang formulir",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d bidang formulir dikosongkan",
        "Mọi ô biểu mẫu đều đã có nội dung": "Semua bidang formulir sudah terisi",
        "Còn %d ô chưa điền": "Masih %d bidang kosong",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Formulir isian: %d bidang. Ketik langsung, lalu «Simpan salinan hasil edit…»",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Pilih gambar tanda tangan (latar transparan paling bagus)",
        "Không dựng được trang có chữ ký": "Tidak bisa membuat halaman bertanda tangan",
        "Đã chèn chữ ký vào trang %d": "Tanda tangan disisipkan di halaman %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Pilih dulu teks yang ingin diubah",
        "Vùng chọn quá nhỏ": "Pilihan terlalu kecil",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Teks baru DIGAMBAR DI ATAS pilihan dengan fon sistem. Teks lama tertutup, bukan terhapus — masih bisa diekstrak, jadi ini bukan penyensoran.",
        "Không dựng được trang đã sửa": "Tidak bisa membuat halaman hasil edit",
        "Đã vẽ đè chữ mới lên trang %d": "Teks baru digambar di halaman %d",
        "Đổi chế độ View / Code": "Alihkan Tampilan / Kode",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Belum ada tampilan pohon untuk JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Belum ada tampilan diagram di dalam tab",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Belum ada tampilan kerangka untuk PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Berkas ini hanya punya satu mode tampilan",
        "%d nút": "%d simpul",
        "Không dựng được cây: %@": "Tidak bisa membangun pohon: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Dokumen terlalu besar untuk pohon — gunakan mode Kode",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Tidak dapat membangun halaman berkas ini \u{2014} gunakan mode Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Salindia dibangun dari teks; gambar dan tata letak asli belum digambar.",
        "Vừa ngang": "Pas Lebar",
        "Thu nhỏ trang": "Perkecil Halaman",
        "Phóng to trang": "Perbesar Halaman",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu":
            "Tidak menemukan \u{201C}%@\u{201D} dalam dokumen ini",
        "Chỗ khớp %d/%d": "Kecocokan %d dari %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Tidak ada teks yang dipilih di halaman.",
        "%d ký tự": "%d karakter",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Buka berkas langsung dalam mode View bila tersedia",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· DIBATALKAN di tengah jalan — tabel belum lengkap",
        "Chế độ hiển thị": "Mode tampilan",
        "Đổi giữa View và Code (⌥⌘V)": "Beralih antara View dan Code (⌥⌘V)",
        "Trang tài liệu": "Halaman dokumen",
        "Chữ đã dựng": "Teks tersusun",
        "Trang bảng tính": "Halaman lembar sebar",
        "Sơ đồ": "Diagram",
        "Cây khoá–giá trị": "Pohon kunci–nilai",
        "Bộ phát": "Pemutar",
        "Danh sách mục": "Daftar entri",
        "Báo cáo đã dựng": "Laporan tersusun",
        "Tô theo mức": "Diwarnai menurut tingkat",
        "Trang slide": "Halaman salindia",
        "Dàn ý": "Kerangka",
        "Lưu rồi dựng lại": "Simpan lalu susun ulang",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Menampilkan salinan DI DISK — perubahan yang belum disimpan tidak ada di sini.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Sistem tidak dapat membangun penampil dokumen — gunakan mode Code.",
        "Lưu tệp trước khi xem trang.": "Simpan berkas sebelum melihat halamannya.",
        "Đang ở chế độ Code": "Sedang dalam mode Code",
        "Đang ở chế độ View": "Sedang dalam mode View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Anda melihat sumbernya — klik untuk ke mode View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "Mode View — klik untuk kembali ke sumber (⌥⌘V)",
        "Tín hiệu: %@": "Sinyal: %@",
        "Lý do: %@": "Alasan: %@",
        "Chi tiết: %@": "Rincian: %@",
        "Mở báo cáo": "Buka laporan",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor berhenti mendadak pada %@ — buka laporannya untuk membaca; tidak ada yang dikirim.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligatur — dimatikan, tiap karakter tetap di selnya sendiri",
        "Chế độ CSV": "Mode CSV",
        "Dấu phân tách": "Pemisah",
        "Tự nhận diện": "Kenali otomatis",
        "Dấu phân tách: %@": "Pemisah: %@",
        "Theo đuôi tệp": "Menurut ekstensi berkas",
        "%d dấu cách": "%d spasi",
        "Tài liệu đang sửa được": "Dokumen ini bisa disunting",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Hanya-baca karena berkas sedang diikuti — hentikan pengikutan untuk menyunting",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Hanya-baca karena berkas di disk tidak bisa ditulisi",
        "Đã mở khoá — tài liệu sửa được": "Terbuka — dokumen bisa disunting lagi",
        "Nhân bản tệp": "Gandakan berkas",
        "Đổi tên tệp…": "Ganti nama berkas…",
        "Chuyển tệp tới…": "Pindahkan berkas ke…",
        "XML: đánh giá XPath…": "XML: evaluasi XPath…",
        "Đánh giá XPath": "Evaluasi XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Misalnya: //pesanan/baris[2]/@kode · //*[@jenis='A'] · count(//baris)",
        "Đánh giá": "Evaluasi",
        "XPath không đọc được: %@": "XPath itu tidak terbaca: %@",
        "XPath «%@» không khớp node nào": "XPath «%@» tidak cocok dengan simpul mana pun",
        "XPath «%@» — %d node": "XPath «%@» — %d simpul",
        "XPath «%@»: %d node": "XPath «%@»: %d simpul",
        "Lưu tệp trước khi nhân bản.": "Simpan berkas sebelum menggandakannya.",
        "Không nhân bản được": "Tidak bisa menggandakan",
        "Đã nhân bản thành %@": "Digandakan sebagai %@",
        "Lưu tệp trước khi đổi tên.": "Simpan berkas sebelum mengganti namanya.",
        "Đổi tên tệp": "Ganti nama berkas",
        "Tên hiện tại: %@": "Nama sekarang: %@",
        "Đổi tên": "Ganti nama",
        "Tên tệp không hợp lệ": "Nama berkas itu tidak sah",
        "Đã có tệp tên %@ ở đó": "Di sana sudah ada berkas bernama %@",
        "Lưu tệp trước khi chuyển.": "Simpan berkas sebelum memindahkannya.",
        "Chuyển tới": "Pindahkan ke sini",
        "Thư mục đích đã có tệp tên %@": "Folder tujuan sudah punya berkas bernama %@",
        "Không chuyển được tệp": "Berkas tidak bisa dipindahkan",
        "Đã chuyển tới %@": "Dipindahkan ke %@",
        "Bảng mã:": "Pengodean:",
        "Xuống dòng:": "Akhir baris:",
        "Riêng cho %@": "Khusus untuk %@",
        "    %d — dùng TAB": "    %d — pakai tab",
        "    %d — dùng dấu cách": "    %d — pakai spasi",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Hapus aturan khusus, pakai setelan umum",
        "%@: thụt lề %d %@": "%@: indentasi %d %@",
        "TAB": "tab",
        "dấu cách": "spasi",
        "Xuất": "Ekspor",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Buka hasilnya sebagai tab teks — simpan dengan ⌘S",
        "Lượt tìm trước đó": "Pencarian sebelumnya",
        "«%@» — %d kết quả": "«%@» — %d hasil",
        "Kết quả tìm «%@»": "Hasil pencarian «%@»",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Saring nama berkas — mis. *.csv;*.log (kosong: semua berkas teks)",
        "Thư mục %@ không có file văn bản nào": "Folder %@ tidak punya berkas teks",
        "Không tệp nào trong %@ khớp «%@»": "Tidak ada berkas di %@ yang cocok dengan «%@»",
        "%d byte · %d dòng": "%d bita · %d baris",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d bita · %d baris — terlalu besar untuk menghitung karakter dan kata",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d bita · %d karakter · %d kata · %d baris",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Dokumen ini punya %d baris, %d bita. Ketik nomor baris, «baris,kolom», atau «@bita».",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "«%@» tidak terbaca — ketik nomor baris, «baris,kolom», atau «@bita»",
    ]
}
