import Foundation

/// Bảng dịch tiếng Tây Ban Nha. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let es: [String: String] = [
        "Bản đã lưu…": "Versiones guardadas…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Este documento nunca se ha guardado — no hay historial",
        "Chưa có bản đã lưu nào trước đó": "No hay versiones guardadas anteriores",
        "Không đọc được bản ấy": "No se puede leer esa versión",
        "Khôi phục bản đã lưu": "Restaurar la versión guardada",
        "XML: kiểm theo DTD/XSD…": "XML: validar con DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Este Mac no tiene libxml2, así que la validación XSD no está disponible.",
        "Chọn lược đồ XSD để kiểm": "Elegir un esquema XSD para validar",
        "Hợp lệ theo": "Válido según",
        "Plugin chạy xong, không đổi gì": "El complemento terminó sin cambiar nada",
        "Chưa cài plugin native nào": "No hay complementos nativos instalados",
        "Gỡ plugin này": "Quitar este complemento",
        "Gỡ plugin này?": "¿Quitar este complemento?",
        "Gỡ": "Quitar",
        "Cài plugin native…": "Instalar un complemento nativo…",
        "Mở thư mục plugin": "Abrir la carpeta de complementos",
        "Chọn file .dylib của plugin native": "Elegir el archivo .dylib del complemento",
        "Đã cài:": "Instalado:",
        "Đã gỡ:": "Quitado:",
        "Plugin native…": "Complementos nativos…",
        "Chỉ nhận file .dylib.": "Solo se aceptan archivos .dylib.",
        "Đã có một plugin trùng tên:": "Ya hay un complemento con el mismo nombre:",
        "Không chép được plugin:": "No se puede copiar el complemento:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Los complementos nativos solo están en la descarga directa, no en la versión de la App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "No se encuentra el proceso auxiliar de complementos.",
        "Không khởi động được tiến trình phụ:": "No se puede iniciar el proceso auxiliar:",
        "Tiến trình plugin đã dừng giữa chừng.": "El proceso del complemento se detuvo a medias.",
        "Plugin không trả lời kịp — đã dừng nó.": "El complemento no respondió a tiempo — se detuvo.",
        "Plugin trả lời sai giao thức:": "El complemento respondió con un mensaje mal formado:",
        "Plugin báo lỗi:": "El complemento informó de un error:",
        "Về GEditor": "Acerca de GEditor",
        "Cài đặt…": "Ajustes…",
        "Thoát GEditor": "Salir de GEditor",
        "File": "Archivo",
        "Tab mới": "Pestaña nueva",
        "Đóng tab": "Cerrar pestaña",
        "Tab kế": "Pestaña siguiente",
        "Tab trước": "Pestaña anterior",
        "Tài liệu mới": "Documento nuevo",
        "Mở…": "Abrir…",
        "Mở thư mục làm Workspace…": "Abrir una carpeta como espacio de trabajo…",
        "Mở gần đây": "Abrir reciente",
        "Lưu": "Guardar",
        "Lưu thành…": "Guardar como…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Quitar espacios al final de línea al guardar",
        "Theo dõi file (tail -f)": "Seguir el archivo (tail -f)",
        "In…": "Imprimir…",
        "Mở lại tab vừa đóng": "Reabrir la pestaña cerrada",
        "Chưa có file nào": "No hay archivos",
        "Xoá danh sách": "Vaciar la lista",
        "Edit": "Edición",
        "Hoàn tác": "Deshacer",
        "Làm lại": "Rehacer",
        "Cắt": "Cortar",
        "Sao chép": "Copiar",
        "Dán": "Pegar",
        "Lịch sử clipboard…": "Historial del portapapeles…",
        "Column Editor…": "Editor de columnas…",
        "Chọn lần kế tiếp": "Seleccionar la siguiente coincidencia",
        "Chọn tất cả": "Seleccionar todo",
        "Nhân đôi dòng": "Duplicar la línea",
        "Xóa dòng": "Eliminar la línea",
        "Comment dòng": "Comentar la línea",
        "Chưa chép gì trong phiên này": "No se ha copiado nada en esta sesión",
        "Xoá lịch sử": "Borrar el historial",
        "Search": "Buscar",
        "Tìm…": "Buscar…",
        "Tìm và thay…": "Buscar y reemplazar…",
        "Tìm trong thư mục…": "Buscar en una carpeta…",
        "Thay trong thư mục…": "Reemplazar en una carpeta…",
        "Kết quả kế": "Resultado siguiente",
        "Kết quả trước": "Resultado anterior",
        "Đi tới dòng…": "Ir a la línea…",
        "Nhảy tới ngoặc khớp": "Ir al paréntesis correspondiente",
        "Đánh dấu mọi dòng khớp…": "Marcar todas las líneas coincidentes…",
        "Đảo dấu": "Invertir las marcas",
        "Bỏ mọi dấu": "Quitar todas las marcas",
        "Chép dòng đã đánh dấu": "Copiar las líneas marcadas",
        "Xóa dòng đã đánh dấu": "Eliminar las líneas marcadas",
        "Chỉ giữ dòng đã đánh dấu": "Conservar solo las líneas marcadas",
        "Lines": "Líneas",
        "Sắp xếp A→Z": "Ordenar A→Z",
        "Sắp xếp Z→A": "Ordenar Z→A",
        "Sắp xếp tự nhiên": "Orden natural",
        "Khử trùng lặp": "Quitar duplicados",
        "Đảo thứ tự dòng": "Invertir el orden de las líneas",
        "Dời dòng lên": "Subir la línea",
        "Dời dòng xuống": "Bajar la línea",
        "Ghép dòng": "Unir líneas",
        "Tách dòng theo độ dài…": "Dividir líneas por longitud…",
        "Tách dòng theo ký tự…": "Dividir líneas por carácter…",
        "Xóa dòng rỗng": "Eliminar líneas vacías",
        "Nén dòng trống liên tiếp": "Reducir líneas vacías consecutivas",
        "Cắt khoảng trắng cuối dòng": "Quitar espacios al final de línea",
        "Tab → Space": "Tab → Espacio",
        "Space → Tab": "Espacio → Tab",
        "HOA": "MAYÚSCULAS",
        "thường": "minúsculas",
        "Chữ Hoa Đầu Từ": "Mayúscula En Cada Palabra",
        "Chữ hoa đầu câu": "Mayúscula al inicio de la frase",
        "Đảo hoa/thường": "iNVERTIR mAYÚSCULAS",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: elegir hoja…",
        "Xem dạng bảng / văn bản": "Alternar vista de tabla / texto",
        "Xóa cột…": "Eliminar columna…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Validar los datos (número de columnas · tipos)",
        "Bàn làm sạch dữ liệu…": "Mesa de limpieza de datos…",
        "Chạy công thức làm sạch…": "Ejecutar una receta de limpieza…",
        "Chuyển đổi…": "Convertir…",
        "Đổi dấu phân tách…": "Cambiar el separador…",
        "Xuất sang JSON…": "Exportar a JSON…",
        "Format": "Formato",
        "Bảng mã…": "Codificación…",
        "Xuống dòng…": "Fin de línea…",
        "Chuẩn hóa Unicode…": "Normalizar Unicode…",
        "JSON: định dạng lại": "JSON: formatear",
        "JSON: thu gọn một dòng": "JSON: compactar en una línea",
        "JSON: sắp xếp khóa": "JSON: ordenar claves",
        "JSON: truy vấn JSONPath…": "JSON: consulta JSONPath…",
        "CSV: truy vấn SQL…": "CSV: consulta SQL…",
        "Truy vấn SQL": "Consulta SQL",
        "Đang chạy…": "Ejecutando…",
        "Xuất ra tab mới": "Exportar a una pestaña nueva",
        "Tài liệu rỗng — không có bảng để truy vấn": "Documento vacío — no hay tabla que consultar",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "No es una tabla CSV — la primera fila solo tiene una columna",
        "Không đọc được câu truy vấn": "No se puede leer la consulta",
        "Không kiểm được câu truy vấn": "No se puede comprobar la consulta",
        "Vàng (mặc định)": "Amarillo (por defecto)",
        "Xanh dương": "Azul",
        "Xanh lá": "Verde",
        "Vàng đất": "Ocre",
        "Tím": "Morado",
        "Hồng": "Rosa",
        "Xanh ngọc": "Turquesa",
        "Cam": "Naranja",
        "Xám lam": "Pizarra",
        "Văn bản": "Texto",
        "Dãy số": "Serie numérica",
        "Dãy ngày": "Serie de fechas",
        "Chữ HOA (hex)": "MAYÚSCULAS (hexadecimal)",
        "Bắt đầu": "Inicio",
        "Bước": "Paso",
        "Đệm 0 tới": "Rellenar con ceros hasta",
        "Hệ": "Base",
        "Ngày đầu": "Primera fecha",
        "Định dạng": "Formato",
        "Chèn": "Insertar",
        "Huỷ": "Cancelar",
        "Chuyển đổi định dạng": "Convertir el formato",
        "Xem trước 5 hàng đầu": "Vista previa de las 5 primeras filas",
        "Tạo tab mới": "Abrir en una pestaña nueva",
        "Lưu ra file…": "Guardar en un archivo…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "El resultado se abre en una pestaña nueva sin guardar. El documento original queda intacto.",
        "Chạy trên tài liệu này": "Ejecutar en este documento",
        "Chạy trên thư mục…": "Ejecutar en una carpeta…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Toda la receta es UN solo paso de deshacer. El archivo del disco queda intacto hasta que guardes.",
        "tắt": "desactivado",
        "không thấy cột": "columna no encontrada",
        "sẵn sàng": "listo",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "sigue ocupando un núcleo de CPU hasta que se cierre la aplicación.",
        "Script không trả về gì": "El script no devolvió nada",
        "Không dựng được máy JavaScript": "No se pudo crear el motor de JavaScript",
        "Lỗi JavaScript không rõ": "Error de JavaScript desconocido",
        "Bảng": "Tabla",
        "Áp sắp xếp vào file": "Aplicar el orden al archivo",
        "Chuyển đổi ▾": "Convertir ▾",
        "Xuất dòng khớp": "Exportar las filas coincidentes",
        "Ẩn cột này": "Ocultar esta columna",
        "Đổi tên tiêu đề…": "Renombrar el encabezado…",
        "Chèn cột trống bên trái": "Insertar una columna vacía a la izquierda",
        "Chèn cột trống bên phải": "Insertar una columna vacía a la derecha",
        "Xóa cột này khỏi file…": "Eliminar esta columna del archivo…",
        "Phải còn ít nhất một cột đang hiện": "Debe quedar al menos una columna visible",
        "Đang sắp xếp…": "Ordenando…",
        "Trở về thứ tự trong file": "Volver al orden del archivo",
        "trăm hàng đầu": "primeras cien filas",
        "chọn cột": "elegir columnas",
        "đặt tên cột kết quả": "nombrar una columna del resultado",
        "lọc theo chữ": "filtrar por texto",
        "ô rỗng": "celdas vacías",
        "ghép điều kiện": "combinar condiciones",
        "đếm hàng": "contar filas",
        "gộp nhóm": "agrupar y agregar",
        "nhỏ nhất, lớn nhất": "mínimo, máximo",
        "sắp xếp và cắt": "ordenar y limitar",
        "tên cột có dấu cách": "nombre de columna con espacios",
        "Truy vấn bị dừng giữa chừng": "La consulta se interrumpió",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "No admitido: JOIN · subconsulta · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · funciones de ventana",
        "XML: định dạng lại": "XML: formatear",
        "XML: thu gọn một dòng": "XML: compactar en una línea",
        "XML: kiểm cú pháp": "XML: comprobar la sintaxis",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: revisar claves duplicadas e indentación",
        "View": "Ver",
        "Ẩn/hiện sidebar (Function List)": "Mostrar/ocultar la barra lateral (lista de funciones)",
        "Ẩn/hiện bản đồ tài liệu": "Mostrar/ocultar el mapa del documento",
        "Gấp / mở khối tại con nháy": "Plegar / desplegar el bloque del cursor",
        "Gấp tất cả": "Plegar todo",
        "Bỏ gấp tất cả": "Desplegar todo",
        "Gấp theo cấp": "Plegar por nivel",
        "Cấp %d": "Nivel %d",
        "Đã gấp %d khối ở cấp %d": "%d {one=bloque plegado|other=bloques plegados} en el nivel %d",
        "Tài liệu này chỉ sâu %d cấp": "Este documento solo tiene %d {one=nivel|other=niveles} de profundidad",
        "mermaid: không đọc được bản kê": "mermaid: no se puede leer el manifiesto",
        "Kiểm tra bản cập nhật…": "Buscar actualizaciones…",
        "Kiểm tra bản cập nhật": "Buscar actualizaciones",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Las versiones de la App Store se actualizan por la Mac App Store, no por GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Esta versión no tiene clave de firma de actualizaciones, así que no puede buscarlas.",
        "Phóng to chữ": "Aumentar el texto",
        "Thu nhỏ chữ": "Reducir el texto",
        "Cỡ chữ gốc": "Tamaño real",
        "Chia đôi theo chiều dọc": "Dividir verticalmente",
        "Chia đôi theo chiều ngang": "Dividir horizontalmente",
        "Bỏ chia đôi": "Cerrar la división",
        "Mở tab này ở nửa kia": "Abrir esta pestaña en el otro panel",
        "Nhảy sang nửa kia": "Ir al otro panel",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Ajuste de línea (desactivado / ventana / columna)",
        "Ngắt dòng tại cột…": "Ajustar línea en la columna…",
        "Đánh dấu dòng này": "Marcar esta línea",
        "Dấu kế tiếp": "Marca siguiente",
        "Dấu trước đó": "Marca anterior",
        "Màu đánh dấu…": "Color de las marcas…",
        "Hiện tất cả ký tự ẩn": "Mostrar todos los caracteres invisibles",
        "  Khoảng trắng": "  Espacios",
        "  Tab": "  Tabulaciones",
        "  Xuống dòng": "  Fin de línea",
        "  NBSP · zero-width · điều khiển": "  NBSP · ancho cero · control",
        "Xem nhị phân": "Vista binaria",
        "Chế độ CSV (tô màu theo cột)": "Modo CSV (columnas en colores)",
        "Macro": "Macro",
        "Bắt đầu / dừng ghi": "Iniciar / detener la grabación",
        "Phát lại": "Reproducir",
        "Phát nhiều lần…": "Reproducir varias veces…",
        "Phát đến cuối tài liệu": "Reproducir hasta el final del documento",
        "Chạy trên mọi tab": "Ejecutar en todas las pestañas",
        "Hủy macro đang chạy": "Cancelar la macro en curso",
        "Lưu macro…": "Guardar la macro…",
        "Macro đã lưu…": "Macros guardadas…",
        "Help": "Ayuda",
        "Trợ giúp GEditor": "Ayuda de GEditor",
        "Giới thiệu tính năng": "Descubre las funciones",
        "Di cư từ Notepad++": "Migrar desde Notepad++",
        "Tìm": "Buscar",
        "Thay bằng": "Reemplazar por",
        "Kế": "Siguiente",
        "Trước": "Anterior",
        "Đếm": "Contar",
        "Đóng": "Cerrar",
        "Kiểm theo JSON Schema…": "Validar con un esquema JSON…",
        "Chọn tệp JSON Schema": "Elegir un archivo de esquema JSON",
        "Không thấy lỗi nào theo schema này.": "No se encontraron problemas según este esquema.",
        "JSON Schema": "Esquema JSON",
        "Kiểm cú pháp đồ thị": "Comprobar la sintaxis del grafo",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Formato de grafo no reconocido — se necesita una extensión .dot, .gv, .cypher, .ttl o .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "No se encontraron errores de sintaxis %@ (la comprobación no es exhaustiva).",
        "Cú pháp %@": "Sintaxis %@",
        "không phải một đối tượng JSON": "no es un objeto JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Minería de texto (n-gramas, TF-IDF)",
        "Tài liệu rỗng.": "El documento está vacío.",
        "Không rút được từ khoá nào.": "No se pudo extraer ninguna palabra clave.",
        "Từ khoá": "Palabras clave",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=palabra clave|other=palabras clave} · %d {one=token|other=tokens} · %d {one=documento|other=documentos}",
        "Tô lên tài liệu": "Marcar en el documento",
        "Đánh dấu entity từ danh sách…": "Marcar entidades desde una lista…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Elegir una lista de entidades (CSV o JSON)",
        "Không đọc được danh sách entity.": "No se puede leer la lista de entidades.",
        "Danh sách entity rỗng.": "La lista de entidades está vacía.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "No se encontraron entidades en el documento (%d cargadas).",
        "%d lần xuất hiện · %@": "%d {one=aparición|other=apariciones} · %@",
        "Chuyển đổi tri thức…": "Convertir conocimiento…",
        "Chuyển đổi: %@ → %@": "Conversión: %@ → %@",
        "Không chuyển đổi được.": "No se pudo convertir.",
        "Xem trước cắt chunk…": "Vista previa del troceado…",
        "Cỡ cố định 800B, chồng 100B": "Tamaño fijo 800 B, solape 100 B",
        "Theo câu (≤ 800B)": "Por frase (≤ 800 B)",
        "Theo heading Markdown": "Por encabezado Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Documento vacío — no hay fragmentos.",
        "%d chunk · trung bình %d B · %@": "%d {one=fragmento|other=fragmentos} · %d B de media · %@",
        "Xuất JSONL": "Exportar JSONL",
        "Chunk JSONL": "Fragmentos JSONL",
        "Mở triple/edge dạng bảng": "Abrir triples/aristas como tabla",
        "Bảng triple": "Tabla de triples",
        "Tài liệu này không có dòng triple nào.": "Este documento no tiene ninguna línea de triple.",
        "Không đọc được triple nào — dòng %d: %@": "No se pudo leer ningún triple — línea %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%d {one=triple leído|other=triples leídos} · %d {one=línea mal formada omitida|other=líneas mal formadas omitidas} (la primera: línea %d)",
        "Trùng lặp mờ theo cột…": "Duplicados aproximados por columna…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Duplicados aproximados — columna «%@»: %d {one=grupo candidato|other=grupos candidatos}",
        "Gộp": "Fusionar",
        "Giống": "Coincidencia",
        "Các giá trị trong cụm": "Valores del grupo",
        "Gộp về": "Fusionar en",
        "Gộp các cụm đã chọn": "Fusionar los grupos seleccionados",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "No hay ningún grupo seleccionado — pulsar Fusionar NO cambiará nada. La aplicación nunca fusiona por su cuenta.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=grupo seleccionado|other=grupos seleccionados} · %d {one=fila cambiará|other=filas cambiarán} · UN solo paso de deshacer",
        "Không quét được cột này.": "No se pudo analizar esta columna.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "La columna «%@» no tiene grupos de duplicados aproximados.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "No se fusionó ningún grupo — el documento queda igual.",
        "Khử trùng lặp mờ · cột %@": "Deduplicación aproximada · columna %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=grupo fusionado|other=grupos fusionados} · %d {one=celda modificada|other=celdas modificadas}",
        "Báo cáo làm sạch": "Informe de limpieza",
        "# Báo cáo làm sạch — %@\n\n": "# Informe de limpieza — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Aplicado (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_No se aplicó ningún paso._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Perfil de los datos\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%d {one=columna|other=columnas} · %d {one=fila|other=filas} · analizado en %.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Columna | Tipo | Nulos | Distintos | Mín | Máx | Media |\n",
        "\n### Giá trị bất thường\n\n": "\n### Valores atípicos\n\n",
        "hàng %d: %@": "fila %d: %@",
        "- cột «%@» — %d ô: %@\n": "- columna «%@» — %d {one=celda|other=celdas}: %@\n",
        "\n## Còn lại (%d)\n\n": "\n## Restante (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_No quedan hallazgos._\n",
        "- cột «%@»: %@\n": "- columna «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Quitar espacios al guardar",
        "Chuẩn hóa xuống dòng": "Normalizar los fines de línea",
        "trước đó": "anterior",
        "Không mở lại được thư mục «%@» của phiên trước": "No se pudo reabrir la carpeta «%@» de la sesión anterior",
        " (và %d file khác)": " (y %d {one=archivo|other=archivos} más)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%d {one=pestaña no se pudo reabrir|other=pestañas no se pudieron reabrir}: %@%@ — los archivos ya no están donde estaban.",
        "Không đọc được nội dung từ ống dẫn": "No se pudo leer la entrada desde la tubería",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Se quitarán los espacios al final de línea en cada guardado",
        "Không cắt khoảng trắng khi lưu nữa": "Ya no se quitan los espacios al guardar",
        "Chưa đặt tên.txt": "Sin título.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Convertir la codificación perderá caracteres",
        "Vẫn lưu": "Guardar de todos modos",
        "Tài liệu có thay đổi chưa lưu": "El documento tiene cambios sin guardar",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Cerrar sin guardar los descartará.",
        "Bỏ thay đổi": "Descartar los cambios",
        "Đi tới dòng": "Ir a la línea",
        "Tài liệu có %d dòng.": "El documento tiene %d {one=línea|other=líneas}.",
        "Số dòng": "Número de línea",
        "Đi tới": "Ir",
        "Diễn giải lại theo…": "Reinterpretar como…",
        "Chuyển đổi sang…": "Convertir a…",
        "Không diễn giải lại được": "No se pudo reinterpretar",
        "Bảng mã %@ không chứa hết ký tự": "%@ no puede representar todos los caracteres",
        "Vẫn chọn": "Elegir de todos modos",
        "Cột %d": "Columna %d",
        "Cột %d: %@": "Columna %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Columnas ocultas: %@ (%d) — restáuralas desde el menú contextual de la fila de encabezado",
        "Hiện lại: %@": "Mostrar de nuevo: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Columna %@ oculta — sigue intacta en el archivo",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Ordenado por %@ %@ · solo visualización",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Ordenado: %@ %@ (solo visualización)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ filas coinciden — seguimos buscando…",
        "%d / %d dòng khớp": "%d / %d {one=fila coincide|other=filas coinciden}",
        "Không tìm thấy lỗi trong %d hàng": "No se encontraron problemas en %d {one=fila|other=filas}",
        "%d hàng lệch số cột": "%d {one=fila|other=filas} con un número de columnas incorrecto",
        "%d ô sai kiểu dữ liệu": "%d {one=celda|other=celdas} con el tipo de dato incorrecto",
        " (đã dừng ở %d lỗi đầu)": " (detenido en los primeros %d {one=problema|other=problemas})",
        "   —   kiểu nhận ra: ": "   —   tipos detectados: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Fila %d, columna %@: «%@» no es %@",
        "Column Editor — %d dòng": "Editor de columnas — %d {one=línea|other=líneas}",
        "Phát hiện": "Hallazgos",
        "Hồ sơ dữ liệu": "Perfil de los datos",
        "Hồ sơ dữ liệu — đang quét…": "Perfil de los datos — analizando…",
        "Lưu công thức…": "Guardar la receta…",
        "Xuất báo cáo": "Exportar el informe",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "No se aplicó ningún grupo · cada grupo es un paso de deshacer",
        "quá nhiều giá trị": "demasiados valores",
        "hay gặp: ": "más frecuentes: ",
        "Giá trị điền vào ô thiếu": "Valor con el que rellenar las celdas vacías",
        "Áp dụng": "Aplicar",
        "Không dựng được bản xem trước": "No se pudo construir una vista previa",
        "· giữ nguyên, không đọc được ·": "· conservado tal cual, ilegible ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Convertir la columna a ISO 8601 (AAAA-MM-DD)",
        "Quy ước số cho cả cột": "Convención numérica para toda la columna",
        "Làm gì với ô thiếu": "Qué hacer con las celdas vacías",
        "Chuẩn hóa về ISO 8601": "Normalizar a ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Leer las celdas ambiguas con el DÍA primero (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Leer las celdas ambiguas con el MES primero (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Omitir las celdas ambiguas, corregir solo las seguras",
        "Về Việt/Âu (1.234,56)": "A vietnamita/europeo (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "A angloamericano (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "A angloamericano, sin separador de miles (1234.56)",
        "Điền một giá trị mặc định…": "Rellenar con un valor por defecto…",
        "Điền xuôi — lấy giá trị phía trên": "Rellenar hacia abajo — tomar el valor de arriba",
        "Điền ngược — lấy giá trị phía dưới": "Rellenar hacia arriba — tomar el valor de abajo",
        "Xóa hàng có ô thiếu ở cột này": "Eliminar las filas con celda vacía en esta columna",
        "Cắt khoảng trắng hai đầu": "Quitar espacios en ambos extremos",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Quitar en ambos extremos y reducir los espacios internos",
        "Pivot…": "Tabla dinámica…",
        "Nguồn…": "Fuentes…",
        "Pivot — gộp theo cột": "Tabla dinámica — agrupar por columna",
        "Hàng (gộp nhóm)": "Filas (agrupación)",
        "Giá trị": "Valores",
        "+ Hàng": "+ Fila",
        "+ Giá trị": "+ Valor",
        "Xoá hết": "Borrar todo",
        "Đưa vào ô truy vấn": "Poner en la consulta",
        "Chọn cột để dựng câu truy vấn.": "Elige columnas para construir la consulta.",
        "Không đọc được tên cột của bảng này.": "No se pudieron leer los nombres de columna de esta tabla.",
        "Nguồn dữ liệu của truy vấn": "Fuentes de datos de la consulta",
        "«%@» — tài liệu đang mở": "«%@» — el documento abierto",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ el archivo ha cambiado desde que se registró",
        "Thêm file…": "Añadir archivo…",
        "Bỏ hết": "Quitar todo",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "No se pudo deducir un nombre de tabla de «%@» — renombra el archivo.",
        "Tổng": "Suma",
        "Trung bình": "Media",
        "Nhỏ nhất": "Mín",
        "Lớn nhất": "Máx",
        "Đếm khác nhau": "Recuento distinto",
        "Biểu đồ": "Gráfico",
        "Xuất PNG": "Exportar PNG",
        "Xuất SVG": "Exportar SVG",
        "Bảng này không có cột số nào để vẽ.": "Esta tabla no tiene ninguna columna numérica que representar.",
        "Không dựng được ảnh PNG.": "No se pudo construir la imagen PNG.",
        "Kết quả truy vấn": "Resultado de la consulta",
        "Đã lưu %@": "%@ guardado",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Gráfico %@ de «%@» — %d {one=punto|other=puntos}, valores de %@ a %@",
        "Cột": "Barras",
        "Đường": "Líneas",
        "Phân bố": "Histograma",
        "Phân tán": "Dispersión",
        "Hộp": "Caja",
        "CSV: chất lượng dữ liệu…": "CSV: calidad de los datos…",
        "Chất lượng dữ liệu": "Calidad de los datos",
        "Xuất vi phạm ra tab mới": "Exportar las infracciones a una pestaña nueva",
        "Mức": "Nivel",
        "Luật": "Regla",
        "Vi phạm": "Infracciones",
        "Tỷ lệ": "Tasa",
        "đạt": "correcto",
        "lỗi": "error",
        "cảnh báo": "aviso",
        "hỏng": "roto",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=línea infractora marcada|other=líneas infractoras marcadas}",
        "Xu hướng": "Tendencia",
        "Lúc chấm": "Evaluado el",
        "Số hàng": "Filas",
        "Lệch": "Diferencia",
        "Luật trượt": "Reglas fallidas",
        "Điểm chất lượng": "Puntuación de calidad",
        "Điểm theo thời gian": "Puntuación en el tiempo",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Aún no hay historial — cada evaluación añade ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "una línea al archivo «.history.jsonl» junto a las reglas.",
        "%d mốc trong lịch sử": "%d {one=punto|other=puntos} en el historial",
        " · %d dòng KHÔNG đọc được": " · %d {one=línea ILEGIBLE|other=líneas ILEGIBLES}",
        " · chọn hai dòng để so": " · selecciona dos filas para comparar",
        "điểm %+.1f": "puntuación %+.1f",
        "không chiều nào tụt": "ninguna dimensión bajó",
        "tụt: ": "bajaron: ",
        "%d luật mới trượt: %@": "%d {one=regla que ahora falla|other=reglas que ahora fallan}: %@",
        "số hàng %+d": "filas %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (y %d {one=aviso|other=avisos} más en la pestaña Tendencia)",
        "Không sửa tự động được: ": "Sin corrección automática: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Abre la herramienta correspondiente en la Mesa de limpieza y vuelve a evaluar enseguida.",
        "Xử lý giá trị thiếu…": "Tratar los valores faltantes…",
        "Chuẩn hóa ngày…": "Normalizar las fechas…",
        "Khử trùng lặp…": "Quitar duplicados…",
        "Thay thế…": "Reemplazar…",
        "Xem các dòng sai": "Mostrar las filas incorrectas",
        "Không tìm thấy cột «%@» trong bảng này.": "La columna «%@» no está en esta tabla.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplicados eliminados — «%@» ya es único. Puntuación: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplicados eliminados, pero «%@» aún tiene %d {one=fila repetida|other=filas repetidas} (antes: %d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "esas filas comparten la CLAVE pero no la línea entera, así que hay que mirarlas y elegir ",
        "giữ hàng nào.": "cuál conservar.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "No se pudo leer ningún valor que infrinja esta regla.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%d {one=valor incorrecto|other=valores incorrectos} en la columna «%@» — rellena Reemplazar y pulsa Vista previa",
        "Đã chấm lại: %.0f/100": "Evaluado de nuevo: %.0f/100",
        "Xem trước báo cáo": "Vista previa del informe",
        "Tham số…": "Parámetros…",
        "Xuất HTML…": "Exportar HTML…",
        "In / PDF…": "Imprimir / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=bloque ejecutado|other=bloques ejecutados} · %d {one=bloque FALLIDO|other=bloques FALLIDOS}",
        "%d khối chạy được": "%d {one=bloque ejecutado|other=bloques ejecutados}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · DATOS OBSOLETOS — el archivo de origen cambió; reconstruye",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "La vista previa del informe necesita un documento .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "No se encontró origen de datos — declara «source: archivo.csv» en el frontmatter.",
        "Không dựng được báo cáo.": "No se pudo construir el informe.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Este informe no declara ningún parámetro en su frontmatter.",
        "Tham số báo cáo": "Parámetros del informe",
        "Dựng lại": "Reconstruir",
        "Đã xuất %@": "%@ exportado",
        "Báo cáo: xem trước": "Informe: vista previa",
        "Báo cáo: sinh loạt…": "Informe: generación por lotes…",
        "không phải tài liệu .greport.md": "no es un documento .greport.md",
        "không phân tích được báo cáo": "no se pudo analizar el informe",
        "không tìm được dữ liệu nguồn": "no se encontró el origen de datos",
        "không đọc được danh sách tham số": "no se pudo leer la lista de parámetros",
        "Sinh loạt cần tài liệu đuôi .%@": "La generación por lotes necesita un documento .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Elegir una lista de parámetros (CSV o JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Elegir una carpeta para %d {one=informe|other=informes}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "faltan parámetros ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "apunta al propio archivo de origen — se rechaza sobrescribir",
        "%d khối HỎNG": "%d {one=bloque FALLIDO|other=bloques FALLIDOS}",
        "Sinh loạt xong: %d tệp · %d hỏng": "Lote terminado: %d {one=archivo|other=archivos} · %d fallidos",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=juego de parámetros no se pudo construir|other=juegos de parámetros no se pudieron construir} — mira el resumen",
        "Sơ đồ Mermaid: xem trước": "Diagrama Mermaid: vista previa",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagrama Mermaid: insertar plantilla…",
        "Sơ đồ Mermaid: định dạng lại": "Diagrama Mermaid: volver a formatear",
        "Nền trong suốt": "Fondo transparente",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Este Mac no puede rasterizar el diagrama a PNG — se necesita macOS 13. La exportación SVG sigue funcionando.",
        "Lưu PNG %@…": "Guardar PNG %@…",
        "Lưu SVG…": "Guardar SVG…",
        "Chép ảnh vào clipboard": "Copiar la imagen al portapapeles",
        "Màu thương hiệu…": "Colores de marca…",
        "Màu thương hiệu cho sơ đồ": "Colores de marca para los diagramas",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Cada campo es un color #rrggbb. Se guarda en «themes/mermaid-brand.json» — se puede copiar a otro Mac.",
        "Màu chính": "Color principal",
        "Chữ trên nút": "Texto de los nodos",
        "Viền": "Borde",
        "Đường nối": "Enlaces",
        "Nền khi xuất ảnh": "Fondo al exportar",
        "Lưu và chèn %%{init}%% vào tài liệu": "Guardar e insertar %%{init}%% en el documento",
        "Đã lưu màu thương hiệu": "Colores de marca guardados",
        "Đã chép ảnh sơ đồ vào clipboard": "Imagen del diagrama copiada al portapapeles",
        "Đã lưu %@ — %@": "%@ guardado — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Este diagrama ya tiene una directiva %%{init}%% — la tuya se deja intacta.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% insertado — el diagrama ya lleva sus propios colores",
        "Chèn màu thương hiệu vào sơ đồ": "Insertar los colores de marca en el diagrama",
        "Định dạng sơ đồ Mermaid": "Volver a formatear el diagrama Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "El código del diagrama ya está ordenado — no hay nada que cambiar",
        "Đã định dạng lại sơ đồ": "Diagrama reformateado",
        "Đã định dạng lại %d sơ đồ": "%d {one=diagrama reformateado|other=diagramas reformateados}",
        "Thư viện mẫu sơ đồ": "Biblioteca de plantillas de diagramas",
        "Mẫu sơ đồ đầy đủ": "Plantillas de diagrama completas",
        "Mẩu cú pháp": "Fragmentos de sintaxis",
        "Đang soạn: %@": "Editando: %@",
        "Đã chèn mẫu «%@»": "Plantilla «%@» insertada",
        "Tài liệu đang ở chế độ chỉ đọc.": "Este documento es de solo lectura.",
        "Sơ đồ Mermaid": "Diagrama Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Este documento no tiene ningún bloque mermaid.",
        "Thương hiệu": "Marca",
        "Xuất…": "Exportar…",
        "Chưa có sơ đồ nào": "Todavía no hay diagramas",
        "%d sơ đồ · %@": "%d {one=diagrama|other=diagramas} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%d/%d {one=diagrama FALLIDO|other=diagramas FALLIDOS} — diagrama %d%@",
        ", dòng %d": ", línea %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Este documento no tiene ningún bloque ```mermaid y tampoco es un archivo .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Ningún diagrama ha terminado de dibujarse.",
        "Không tìm thấy «%@» trong mã sơ đồ": "No se encontró «%@» en el código del diagrama",
        "không dựng được hàng rào chặn mạng cho WKWebView": "no se pudo construir el cortafuegos de red para WKWebView",
        "Luật kết hợp": "Reglas de asociación",
        "Mỗi dòng một giỏ": "Una cesta por fila",
        "Hai cột: mã · item": "Dos columnas: id · artículo",
        "Dạng dữ liệu giao dịch": "Forma de los datos transaccionales",
        "Cột giỏ hàng hoặc mã giao dịch": "Columna de cesta o de id de transacción",
        "Cột item": "Columna de artículo",
        "Ký tự phân tách item": "Carácter separador de artículos",
        "Support tối thiểu, phần trăm": "Soporte mínimo, porcentaje",
        "Confidence tối thiểu, phần trăm": "Confianza mínima, porcentaje",
        "Tách bởi:": "Separado por:",
        "Support \u{2265}": "Soporte ≥",
        "% · Confidence \u{2265}": "% · Confianza ≥",
        "Bảng luật kết hợp": "Tabla de reglas de asociación",
        "Support": "Soporte",
        "Confidence": "Confianza",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Atención",
        "%d giao dịch · %d item · %d luật": "%d {one=transacción|other=transacciones} · %d {one=artículo|other=artículos} · %d {one=regla|other=reglas}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — ninguna regla alcanzó los umbrales; baja el soporte o la confianza",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — SE DETUVO ANTES, la tabla está INCOMPLETA",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transacción contiene|other=transacciones contienen} ambos lados",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "La forma de dos columnas necesita dos columnas DISTINTAS.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%d {one=fila marcada|other=filas marcadas} en %d {one=transacción que contiene|other=transacciones que contienen} «%@»",
        "CSV: luật kết hợp…": "CSV: reglas de asociación…",
        "Khai phá theo nhóm": "Minería por grupos",
        "Cột nhóm": "Columna de grupo",
        "Cột giá trị": "Columna de valores",
        "Cột thứ hai cho tương quan": "Segunda columna para la correlación",
        "Cách xếp hạng": "Criterio de clasificación",
        "Nhóm theo:": "Agrupar por:",
        "Giá trị:": "Valor:",
        "Xếp theo:": "Clasificar por:",
        "Bảng xếp hạng nhóm": "Tabla de clasificación de grupos",
        "Nhóm": "Grupo",
        "Hàng": "Filas",
        "Hàng rào riêng": "Umbral propio",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "Diferencia r",
        "Ghi chú": "Nota",
        "không đo được": "no medible",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=grupo|other=grupos} · correlación global de referencia %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GRUPO DESCARTADO|other=GRUPOS DESCARTADOS}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Esta tabla no tiene ninguna columna de texto por la que agrupar.",
        "Bảng này không có cột số nào để khai phá.": "Esta tabla no tiene ninguna columna numérica que explorar.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%d {one=fila del grupo|other=filas del grupo} «%@» {one=marcada|other=marcadas}",
        "CSV: khai phá theo nhóm…": "CSV: minería por grupos…",
        "\u{2194}": "↔",
        "Dự báo": "Pronóstico",
        "Cột giá trị theo thời gian": "Columna de valores en el tiempo",
        "Mô hình dự báo": "Modelo de pronóstico",
        "Số kỳ dự báo": "Número de periodos a pronosticar",
        "Kết luận so với baseline": "Veredicto frente a las líneas base",
        "Mô hình:": "Modelo:",
        "Số kỳ:": "Periodos:",
        "Chu kỳ:": "Estación:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Periodo estacional; déjalo vacío para detectarlo automáticamente",
        "Bảng giá trị dự báo": "Tabla de valores pronosticados",
        "Kỳ": "Periodo",
        "Dải 80%": "Banda del 80 %",
        "Dải 95%": "Banda del 95 %",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "no calculable",
        "Bảng này không có cột số nào để dự báo.": "Esta tabla no tiene ninguna columna numérica que pronosticar.",
        "Không dựng được dự báo cho cột này.": "No se pudo construir un pronóstico para esta columna.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "La columna «%@» solo tiene %d {one=valor numérico|other=valores numéricos} — se necesitan al menos 4 para pronosticar.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# La serie se lee en el orden de filas del archivo — sin reordenar, sin deducir columna temporal.\n",
        "Sai số huấn luyện": "Error de entrenamiento",
        "CSV: dự báo chuỗi thời gian…": "CSV: pronóstico de series temporales…",
        "Holt-Winters cộng": "Holt-Winters aditivo",
        "Holt-Winters nhân": "Holt-Winters multiplicativo",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Columnas usadas para el agrupamiento",
        "Đường cong WCSS": "Curva WCSS",
        "Phân cụm": "Clúster",
        "Chuẩn hoá:": "Escalado:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Selecciona al menos una columna.",
        "Không đủ dữ liệu để dựng đường cong.": "No hay datos suficientes para construir la curva.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "El codo sugiere k = %d. El WCSS SIEMPRE baja al crecer k, así que es un truco de lectura del gráfico y no un criterio estadístico — mira la curva y juzga si el quiebre es claro.",
        "WCSS theo k": "WCSS según k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "La k-distancia sugiere eps = %@ (minPts vale por defecto 2 × número de columnas = %d). %@",
        "Khoảng cách tới hàng xóm thứ k": "Distancia al k-ésimo vecino",
        "Cần ít nhất 2 cột số để phân cụm.": "Se necesitan al menos 2 columnas numéricas para el agrupamiento.",
        "Cụm theo %@ và %@": "Clústeres según %@ y %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — clústeres hallados en %d {one=dimensión|other=dimensiones}; el gráfico solo muestra las 2 primeras",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# ruido (cluster_id = -1): %d {one=fila|other=filas}\n",
        "CSV: phân cụm…": "CSV: agrupamiento…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Centros de los clústeres (unidades originales) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Matriz de correlación",
        "Phương pháp tương quan": "Método de correlación",
        "Tương quan không hàm ý nhân quả.": "La correlación no implica causalidad.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Par más fuerte: %@ ↔ %@ = %@ (n = %d). Pulsa una celda para ver el diagrama de dispersión.",
        "Không cặp nào đo được.": "Ningún par es medible.",
        "%@ ↔ %@: %@ trên %d hàng": "%@ ↔ %@: %@ sobre %d {one=fila|other=filas}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Se necesitan al menos 2 columnas numéricas para la correlación.",
        "Không đọc được cột «%@».": "No se pudo leer la columna «%@».",
        "CSV: ma trận tương quan…": "CSV: matriz de correlación…",
        "Bất thường": "Anomalías",
        "Danh sách bất thường": "Lista de anomalías",
        "Cột:": "Columna:",
        "Cột số cần xét": "Columna numérica a examinar",
        "Cách:": "Método:",
        "Phương pháp phát hiện": "Método de detección",
        "Phương pháp đã dùng": "Método utilizado",
        "Ngưỡng": "Umbral",
        "Đánh dấu": "Marcar",
        "Xuất tab mới": "Exportar a una pestaña nueva",
        "Dòng": "Línea",
        "Điểm": "Puntuación",
        "Vì sao": "Por qué",
        "nhẹ": "leve",
        "vừa": "moderada",
        "nặng": "grave",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=fila|other=filas} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Esta tabla no tiene ninguna columna numérica donde buscar anomalías.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=línea anómala marcada|other=líneas anómalas marcadas}",
        "CSV: tìm bất thường…": "CSV: detectar anomalías…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%d {one=regla, CORRECTA|other=reglas, todas CORRECTAS} · %d {one=fila|other=filas} · %.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%d {one=error|other=errores} · %d {one=aviso|other=avisos} en %d {one=regla|other=reglas} · %d {one=fila|other=filas} · %.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Guarda primero el documento — las reglas de calidad viven junto al archivo de datos.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Aún no hay conjunto de reglas. Crea el archivo %@ y vuelve a abrir.",
        "Lịch sử": "Historial",
        "Câu đã lưu": "Consultas guardadas",
        "Lưu câu này…": "Guardar esta consulta…",
        "Lưu câu truy vấn": "Guardar la consulta",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Ponle un nombre para encontrarla luego. Un nombre repetido sobrescribe.",
        "Ví dụ: Doanh thu theo tỉnh": "Por ejemplo: Ingresos por provincia",
        "Chưa nhập giá trị cho tham số: %@": "No se ha introducido valor para el parámetro: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "El complemento cambió desde que lo aprobaste — GEditor se niega a ejecutarlo",
        "Chạy plugin chưa duyệt?": "¿Ejecutar un complemento no aprobado?",
        "Tôi tin file này — chạy": "Confío en este archivo — ejecutar",
        "KHÔNG có chữ ký": "SIN firma",
        "Chữ ký: %@": "Firma: %@",
        "Đường dẫn: %@": "Ruta: %@",
        "Thay": "Reemplazar",
        "Thay tất cả": "Reemplazar todo",
        "Chuỗi thuần": "Texto plano",
        "Extended (\\n \\t \\xNN)": "Extendido (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Expresión regular",
        "Phân biệt hoa thường": "Distinguir mayúsculas",
        "Cả từ": "Palabra completa",
        "Không có kết quả": "Sin resultados",
        "Thử biểu thức chính quy…": "Probar una expresión regular…",
        "Chế độ Log (tô theo mức)": "Modo registro (color por nivel)",
        "Lọc log theo mức…": "Filtrar el registro por nivel…",
        "Chạy trên cả thư mục…": "Ejecutar en toda la carpeta…",
        "Lọc qua lệnh ngoài…": "Filtrar con un comando externo…",
        "Script…": "Scripts…",
        "Gói mở rộng…": "Paquetes de extensión…",
        "Cửa sổ mới": "Ventana nueva",
        "Tách tab ra cửa sổ mới": "Separar la pestaña en una ventana nueva",
        "Chưa mở thư mục nào": "No hay ninguna carpeta abierta",
        "Tìm file trong thư mục": "Buscar un archivo en la carpeta",
        "Lọc theo tên": "Filtrar por nombre",
        "File mới…": "Archivo nuevo…",
        "Thư mục mới…": "Carpeta nueva…",
        "Đổi tên…": "Renombrar…",
        "Chuyển vào Thùng rác": "Mover a la papelera",
        "Hiện trong Finder": "Mostrar en el Finder",
        "Đang đọc cấu trúc tài liệu…": "Leyendo la estructura del documento…",
        "file này không có hàm nào": "este archivo no tiene funciones",
        "Không có gì khớp": "Sin coincidencias",
        "Văn bản thuần": "Texto plano",
        "🔒 Chỉ đọc": "🔒 Solo lectura",
        "Đang theo dõi": "Siguiendo",
        "ngắt tại cột": "ajuste en la columna",
        "Cú pháp": "Sintaxis",
        "Bấm để chèn vào ô truy vấn": "Pulsa para insertar en la consulta",
        "truy vấn không hợp lệ": "consulta no válida",
        "khóa `ten` ở gốc": "clave «nombre» en la raíz",
        "khóa có dấu cách": "clave con espacios",
        "phần tử đầu": "primer elemento",
        "mọi phần tử": "todos los elementos",
        "lát cắt": "porción",
        "hợp nhiều chỉ số": "unión de índices",
        "mọi khóa `gia` ở mọi tầng": "todas las claves «precio» en todos los niveles",
        "mọi nút": "todos los nodos",
        "lọc theo số": "filtrar por número",
        "lọc theo có mặt": "filtrar por presencia",
        "Tới lỗi đầu tiên": "Ir al primer error",
        "Cột doanh_thu là số": "La columna ingresos es numérica",
        "lọc…": "filtrar…",
        "Hủy": "Cancelar",
        "Thực hiện thay": "Realizar el reemplazo",
        "xem trước": "vista previa",
        "tương tác": "interactivo",
        "Soạn thảo": "Edición",
        "Giao diện": "Interfaz",
        "Phím tắt": "Atajos de teclado",
        "Cỡ chữ": "Tamaño del texto",
        "Bề rộng TAB": "Ancho de tabulación",
        "Thụt lề bằng TAB": "Indentar con tabulaciones",
        "Tự động thụt lề khi xuống dòng": "Indentar automáticamente al saltar de línea",
        "Tô mọi kết quả tìm kiếm": "Resaltar todos los resultados de la búsqueda",
        "Chuẩn hóa về NFC khi lưu": "Normalizar a NFC al guardar",
        "Ngôn ngữ": "Idioma",
        "Nền": "Apariencia",
        "Theo hệ thống": "Del sistema",
        "Sáng": "Claro",
        "Tối": "Oscuro",
        "Theme": "Tema",
        "Dùng preset Notepad++": "Usar el preajuste de Notepad++",
        "Về phím mặc định": "Volver a las teclas por defecto",
        "Mở file cấu hình": "Abrir el archivo de configuración",
        "Xuất theme hiện tại": "Exportar el tema actual",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "El cambio de idioma se aplica del todo en el próximo arranque.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Las teclas por defecto vuelven en el próximo arranque.",
        "Xem trước Markdown": "Vista previa de Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "La vista previa usa el motor Markdown del sistema: todavía sin tablas ni coloreado de bloques de código.",
        "Thử biểu thức chính quy": "Probar una expresión regular",
        "Biểu thức": "Expresión",
        "Văn bản thử": "Texto de prueba",
        "Kết quả": "Resultado",
        "Kết quả khớp": "Coincidencias",
        "Biểu thức này làm gì": "Qué hace esta expresión",
        "Giải thích biểu thức": "Explicar la expresión",
        "Chế độ tìm kiếm": "Modo de búsqueda",
        "Kết quả tìm kiếm": "Resultados de la búsqueda",
        "Không khớp chỗ nào": "Sin coincidencias",
        " (đã cắt bớt)": " (recortado)",
        "Bản đồ tài liệu": "Mapa del documento",
        "Thanh tab": "Barra de pestañas",
        "Hàng tiêu đề cột": "Fila de encabezado de columnas",
        "Không có cột nào": "No hay columnas",
        "Cây thư mục workspace": "Árbol del espacio de trabajo",
        "Danh sách hàm và lớp": "Lista de funciones y clases",
        "Kết quả tìm trong thư mục": "Resultados de la búsqueda en la carpeta",
        "Bảng dữ liệu CSV": "Tabla de datos CSV",
        "Bàn làm sạch dữ liệu": "Mesa de limpieza de datos",
        "Truy vấn JSONPath": "Consulta JSONPath",
        "Danh sách lỗi dữ liệu": "Lista de errores de datos",
        "Bộ đánh giá golden set…": "Evaluador de golden set…",
        "So với điểm ngoài (JSONL)…": "Comparar con puntuaciones externas (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Elegir un archivo de puntuaciones externas (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Renombrar el nodo seleccionado",
        "Gộp các node đang chọn": "Fusionar los nodos seleccionados",
        "Tách node đang chọn": "Dividir el nodo seleccionado",
        "Trích subgraph đang chọn ra tab mới": "Extraer el subgrafo seleccionado a una pestaña nueva",
        "Không có gì để đổi": "No hay nada que cambiar",
        "%@ — áp %d thay đổi?": "%@ — ¿aplicar %d {one=cambio|other=cambios}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%@: %d {one=cambio|other=cambios} · Cmd-Z deshace todo el lote",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Pon el cursor sobre EXACTAMENTE UN nodo y vuelve a intentarlo",
        "Đổi tên «%@»": "Renombrar «%@»",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Todas las aristas y etiquetas que referencian este nodo cambiarán con él.",
        "Đổi tên node": "Renombrar el nodo",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Selecciona AL MENOS DOS nodos y vuelve a intentarlo",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Forma canónica «%@» — la más frecuente, la más larga, con tildes",
        "Gộp node": "Fusionar nodos",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Selecciona las LÍNEAS DE ARISTA que quieras mover y vuelve a intentarlo",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Todas las líneas seleccionadas deben tocar EXACTAMENTE UN nodo — selecciona más líneas de arista",
        "Tách «%@» — chuyển %d cạnh": "Dividir «%@» — mover %d {one=arista|other=aristas}",
        "Cạnh tới: %@": "Aristas hacia: %@",
        "Tách node": "Dividir el nodo",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Documento sin guardar — el archivo extraído necesita un sitio al lado",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Selecciona la parte del grafo que quieras extraer y vuelve a intentarlo",
        "Gom biến thể entity → bảng duyệt": "Agrupar variantes de entidad → tabla de revisión",
        "Áp bảng duyệt đã sửa": "Aplicar la tabla de revisión modificada",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Documento sin guardar — la tabla de revisión debe estar junto al archivo del grafo",
        "Không tìm thấy biến thể nào để gom": "No se encontró ninguna variante que agrupar",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=grupo de variantes|other=grupos de variantes} — corrige la columna «canonical» y ejecuta «Aplicar la tabla de revisión»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "No hay tabla de revisión «%@» — ejecuta antes «Agrupar variantes de entidad»",
        "Bảng duyệt không đọc được: %@": "Tabla de revisión ilegible: %@",
        "Bảng duyệt không có dòng nào cần đổi": "La tabla de revisión no tiene ninguna fila que cambiar",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Ningún punto del grafo coincide con la tabla de revisión",
        "Gom biến thể entity": "Agrupar variantes de entidad",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=cambio aplicado|other=cambios aplicados} · tabla de alias y lista de marcadores escritas junto al archivo",
        "Áp %d thay đổi lên đồ thị?": "¿Aplicar %d {one=cambio|other=cambios} al grafo?",
        "%d alias → dạng chuẩn.": "%d {one=alias|other=alias} → forma canónica.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "FUSIONAR nodos (no se deshace volviendo a escribir):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias no está en el grafo y se omite|other=alias no están en el grafo y se omiten}.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Análisis de cobertura Fragmento ↔ Entidad",
        "Xuất gói ngữ cảnh (JSONL)": "Exportar el paquete de contexto (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Cobertura Fragmento ↔ Entidad ↔ Grafo",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %d {one=entidad|other=entidades} · %d {one=fragmento|other=fragmentos} · %.0f %% de entidades mencionadas · %.0f %% de fragmentos con entidad",
        "Entity không chunk nào nhắc tới": "Entidades que ningún fragmento menciona",
        "Chunk mồ côi (không chứa entity nào)": "Fragmentos huérfanos (sin ninguna entidad)",
        "Node đồ thị không có entity đối ứng": "Nodos del grafo sin entidad correspondiente",
        "không có": "ninguno",
        "Phương pháp": "Método",
        "Không dựng được ánh xạ Chunk ↔ Entity": "No se pudo construir la correspondencia Fragmento ↔ Entidad",
        "Chấm sức khoẻ đồ thị": "Evaluar la salud del grafo",
        "sức khoẻ đồ thị": "salud del grafo",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Salud %@/100 · %d {one=error|other=errores} · %d {one=inversión|other=inversiones} · %d huérfanos",
        "Lai với đồ thị": "Híbrido con el grafo",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: se ignora del todo la señal del grafo, el resultado es igual a BM25 puro",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α alto: el grafo solo ajusta ligeramente el ranking de BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α cerca del valor por defecto 0,7: manda BM25, el grafo ajusta",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α bajo: manda el grafo, BM25 solo desempata",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: solo la señal del grafo; los fragmentos sin entidad quedan empatados",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Documento sin guardar — el híbrido necesita un archivo de grafo junto al corpus",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "No se encuentra el archivo de grafo «%@» — el híbrido lo necesita para su señal",
        "lai %.1f ms · %@": "híbrido %.1f ms · %@",
        "Thuật toán…": "Algoritmos…",
        "PageRank (độ dày viền)": "PageRank (grosor del borde)",
        "Cộng đồng (màu nền)": "Comunidades (color de fondo)",
        "Thành phần liên thông": "Componentes conexas",
        "Xuất bảng node ra tab mới": "Exportar la tabla de nodos a una pestaña nueva",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%d {one=componente|other=componentes} · la mayor con %d {one=nodo|other=nodos} · %d nodos huérfanos",
        "Tài liệu này không phải đồ thị DOT": "Este documento no es un grafo DOT",
        "Không dựng được bảng node/cạnh: %@": "No se pudo construir la tabla de nodos/aristas: %@",
        "%d hàng · %@": "%d {one=fila|other=filas} · %@",
        "Gán nhãn": "Etiquetar",
        "Ghi chú (tuỳ chọn)": "Nota (opcional)",
        "Lưu record": "Guardar el registro",
        "Xuất CSV": "Exportar CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Documento sin guardar — el evaluador debe estar junto al archivo de corpus",
        "Không nạp được bộ đánh giá: %@": "No se pudo cargar el evaluador: %@",
        "Không lưu được: %@": "No se pudo guardar: %@",
        "Bộ đánh giá chưa có record nào": "El evaluador aún no tiene ningún registro",
        "Không ghi được: %@": "No se pudo escribir: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Este documento no es un archivo .mmd, no es DOT y no tiene ningún bloque mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=nodo|other=nodos} · %d {one=arista|other=aristas} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagrama Mermaid: añadir un elemento…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagrama Mermaid: conectar los dos elementos seleccionados",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagrama Mermaid: editar la etiqueta del elemento seleccionado…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagrama Mermaid: eliminar el elemento seleccionado",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagrama Mermaid: subir el mensaje",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagrama Mermaid: bajar el mensaje",
        "Thêm phần tử": "Añadir un elemento",
        "Thêm participant": "Añadir un participante",
        "Thêm mục": "Añadir una entrada",
        "Thêm mục sơ đồ": "Añadir una entrada al diagrama",
        "Sửa mục sơ đồ": "Editar una entrada del diagrama",
        "Xoá mục sơ đồ": "Eliminar una entrada del diagrama",
        "Xoá phần tử": "Eliminar el elemento",
        "Sửa nhãn": "Editar la etiqueta",
        "Đổi thứ tự message": "Reordenar los mensajes",
        "Tên mục": "Nombre de la entrada",
        "Mục mới": "Entrada nueva",
        "Tên mục hiện trên sơ đồ.": "El nombre de la entrada aparece en el diagrama.",
        "Bảng thuộc tính sơ đồ": "Tabla de propiedades del diagrama",
        "Tài liệu này không có khối mermaid nào": "Este documento no tiene ningún bloque mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identificador en el código del diagrama — sin espacios. La etiqueta se edita después con doble clic.",
        "Để trống thì hiện chính định danh.": "Si se deja vacío, se muestra el propio identificador.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Solo cambia la ETIQUETA visible; el identificador del elemento se mantiene.",
        "Không rõ «%@» là phần tử nào": "No está claro qué elemento es «%@»",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Selecciona EXACTAMENTE DOS elementos y vuelve a intentarlo",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Pon el cursor sobre EXACTAMENTE UN elemento y vuelve a intentarlo",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Elige UN elemento para eliminar, o dos elementos unidos por una arista",
        "Xoá «%@» và %d cạnh chạm nó?": "¿Eliminar «%@» y las %d {one=arista que lo toca|other=aristas que lo tocan}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Los nodos del otro extremo de esas aristas se conservan — se vuelven a declarar con su etiqueta si la instrucción de arista era su única declaración.",
        "Sơ đồ «%@» chỉ soạn text — %@": "El diagrama «%@» solo se edita como texto — %@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: arrastra entre dos elementos para conectarlos, doble clic para editar la etiqueta",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: arrastra entre dos participantes para añadir un mensaje; reordena desde el menú Herramientas",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: edita en la tabla de propiedades de abajo",
        "Soạn trực quan đã bật": "Edición visual activada",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%@ · %d {one=entrada|other=entradas} — edita directamente en la tabla, cada celda es un paso de deshacer",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Para un gráfico circular, un número; para un gantt, lo que sigue a los dos puntos.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagrama Mermaid: extraer el bloque a un archivo .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagrama Mermaid: reincorporar el archivo referenciado",
        "Tách khối sơ đồ": "Extraer el bloque del diagrama",
        "Nhúng khối sơ đồ": "Reincorporar el bloque del diagrama",
        "Tách khối sơ đồ ra tệp riêng": "Extraer el bloque del diagrama a un archivo aparte",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "El archivo se coloca JUNTO al documento; el bloque conserva una línea de referencia para editar en un solo sitio.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Documento sin guardar — el archivo del diagrama necesita un sitio al lado",
        "Đã có tệp «%@» — chọn tên khác": "Ya existe el archivo «%@» — elige otro nombre",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Extraído a «%@» — el bloque conserva una línea de referencia",
        "Mở tệp": "Abrir el archivo",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» reincorporado; el archivo sigue en el disco",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Este bloque contiene un diagrama real, no una referencia",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Este bloque referencia «%@» — abre ese archivo para editarlo",
        "Không đọc được tệp sơ đồ %@": "No se pudo leer el archivo de diagrama %@",
        "Soạn trực quan": "Edición visual",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Arrastra de un nodo a otro para añadir una arista; doble clic para editar la etiqueta. Cada acción es un paso de deshacer.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Edición visual: arrastra entre dos nodos para añadir una arista, doble clic para editar la etiqueta",
        "Soạn trực quan đã tắt": "Edición visual desactivada",
        "Thêm node…": "Añadir un nodo…",
        "Thêm cạnh giữa hai node đang chọn…": "Añadir una arista entre los dos nodos seleccionados…",
        "Sửa nhãn node đang chọn…": "Editar la etiqueta del nodo seleccionado…",
        "Xoá node/cạnh đang chọn": "Eliminar el nodo/arista seleccionado",
        "Thêm node": "Añadir un nodo",
        "Thêm cạnh": "Añadir una arista",
        "Sửa nhãn node": "Editar la etiqueta del nodo",
        "Xoá node": "Eliminar el nodo",
        "Xoá cạnh": "Eliminar la arista",
        "Cmd-Z hoàn tác": "Cmd-Z para deshacer",
        "Tài liệu đang ở chế độ chỉ đọc": "Este documento es de solo lectura",
        "Nhãn của «%@»": "Etiqueta de «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Solo cambia la ETIQUETA visible; el identificador del nodo se mantiene.",
        "Không rõ «%@» là node nào": "No está claro qué nodo es «%@»",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identificador del nodo en el archivo DOT. La etiqueta se edita después con doble clic en el gráfico.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Selecciona EXACTAMENTE DOS nodos y vuelve a intentarlo",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Elige UN nodo para eliminarlo, o dos nodos unidos por una arista",
        "Xoá node «%@» và %d cạnh chạm nó?": "¿Eliminar el nodo «%@» y las %d {one=arista que lo toca|other=aristas que lo tocan}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Si quedan aristas huérfanas, DOT recrea los nodos a partir de ellas — el nodo eliminado reaparecerá en el siguiente dibujo.",
        "Phòng thí nghiệm truy hồi BM25": "Laboratorio de recuperación BM25",
        "Câu hỏi — Enter để tìm": "Pregunta — Intro para buscar",
        "Đánh giá…": "Evaluar…",
        "Đang dựng chỉ mục": "Construyendo el índice",
        "Không chunk nào khớp": "Ningún fragmento coincide",
        "kết quả trên": "mejores resultados",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: cada palabra cuenta SOLO una vez, sin importar cuántas veces aparezca",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 bajo: repetir una palabra casi no añade puntuación",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 cerca del valor por defecto 1,2: repetir añade puntuación, pero cada vez menos",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 alto: un fragmento que repite una palabra se premia con fuerza",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: se ignora la longitud, los fragmentos largos no se penalizan",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b bajo: los fragmentos largos se penalizan solo un poco",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b cerca del valor por defecto 0,75: los fragmentos largos se penalizan moderadamente",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: penalización máxima por longitud, se favorecen los fragmentos cortos",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: laboratorio de recuperación…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Documento sin guardar — el índice BM25 vive junto al archivo de corpus y necesita una ruta",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Este archivo no es JSONL — el Retrieval Lab funciona sobre un corpus de fragmentos",
        "Không dựng được chỉ mục BM25 cho tệp này": "No se pudo construir un índice BM25 para este archivo",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Documento sin guardar — hace falta una ruta de corpus para generar el informe",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Elegir un conjunto de evaluación (CSV o JSONL: pregunta + id de fragmento esperado)",
        "Đánh giá truy hồi": "Evaluación de la recuperación",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Cambia k1, b o k arriba y vuelve a revisar para comparar dos configuraciones; añade un bloque «compare» para ejecutar dos juegos de parámetros en paralelo sobre el mismo conjunto.",
        "Lỗi": "Error",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, media %.0f)",
        "Chế độ JSONL": "Modo JSONL",
        "Bản ghi": "Registro",
        "Chi tiết": "Detalle",
        "Bản ghi ở dòng": "Registro en la línea",
        "không phải JSON hợp lệ": "no es JSON válido",
        "bản ghi": "registros",
        "dòng trắng": "líneas en blanco",
        "không phải đối tượng": "no es un objeto",
        "bảng hiện": "tabla mostrada",
        "ĐÃ HUỶ giữa chừng": "CANCELADO a medias",
        "Không lọc": "Sin filtro",
        "bản ghi khớp bộ lọc": "registros que coinciden con el filtro",
        "Đưa con nháy tới một dòng để xem bản ghi": "Pon el cursor en una línea para ver el registro",
        "Không có bản ghi nào hỏng": "No hay registros defectuosos",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Todavía sin inspeccionar. Vuelve a ejecutar «JSONL: inspeccionar fragmentos» tras la comprobación.",
        "trường văn bản": "campo de texto",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "ESQUEMA (deducido — se cambia eligiendo otro campo)",
        "văn bản": "texto",
        "định danh": "identificador",
        "metadata lồng": "metadatos anidados",
        "TRƯỜNG": "CAMPO",
        "phủ": "cobertura",
        "nhiều kiểu": "varios tipos",
        "ĐỘ DÀI — ký tự": "LONGITUD — caracteres",
        "ĐỘ DÀI — từ": "LONGITUD — palabras",
        "ĐỘ DÀI — token ước lượng": "LONGITUD — tokens estimados",
        "RỖNG VÀ TRÙNG": "VACÍOS Y DUPLICADOS",
        "chunk rỗng": "fragmentos vacíos",
        "dòng": "líneas",
        "nhóm trùng chính xác": "grupos de duplicados exactos",
        "dòng không đọc được, không vào thống kê": "líneas ilegibles, fuera de las estadísticas",
        "PHƯƠNG PHÁP": "MÉTODO",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«caracteres» cuenta caracteres Unicode (escalares), no grupos visibles",
        "«từ» tách theo khoảng trắng ASCII": "«palabras» separa por espacios ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«tokens» cuenta con un separador de sílabas — NO es el del modelo",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«duplicado» significa duplicado EXACTO; los casi duplicados están en el bloque ```quality",
        "chunk": "fragmentos",
        "JSONL: kiểm và soi chunk…": "JSONL: comprobar e inspeccionar fragmentos…",
        "Ảnh": "Imagen",
        "PDF": "PDF",
        "Tài liệu Word": "Documento de Word",
        "Bảng tính Excel": "Hoja de cálculo de Excel",
        "Bản trình chiếu PowerPoint": "Presentación de PowerPoint",
        "File nén": "Archivo comprimido",
        "Vừa khung": "Ajustar a la ventana",
        "Chép ảnh": "Copiar la imagen",
        "Xoay": "Rotar",
        "Không đọc được ảnh «%@»": "No se puede leer la imagen «%@»",
        "Đã chép ảnh vào clipboard": "Imagen copiada al portapapeles",
        "Bôi vàng": "Resaltar en amarillo",
        "Gạch chân": "Subrayar",
        "Ghi chú…": "Nota…",
        "Bỏ chú thích": "Quitar las anotaciones",
        "Lấy chữ ra tab mới": "Extraer el texto a una pestaña nueva",
        "Lưu bản có chú thích…": "Guardar la versión anotada…",
        "Tìm trong PDF": "Buscar en el PDF",
        "Thêm": "Añadir",
        "Trang %d/%d": "Página %d/%d",
        "Trang %d": "Página %d",
        "Kết quả %d/%d": "Resultado %d/%d",
        "0 kết quả": "0 resultados",
        "Không đọc được PDF «%@»": "No se puede leer el PDF «%@»",
        "PDF này có mật khẩu — chưa mở được nội dung": "Este PDF tiene contraseña — no se puede acceder al contenido",
        "Không thấy «%@» trong tài liệu": "No se encuentra «%@» en el documento",
        "Đã bôi vàng": "Resaltado",
        "Đã gạch chân": "Subrayado",
        "Hãy bôi đen một đoạn chữ trước": "Selecciona antes un fragmento de texto",
        "Đã thêm ghi chú": "Nota añadida",
        "Trang này chưa có chú thích nào": "Esta página no tiene ninguna anotación",
        "Đã bỏ %d chú thích trên trang này": "%d {one=anotación quitada|other=anotaciones quitadas} de esta página",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Este PDF no tiene capa de texto — probablemente sea un escaneo",
        "Không ghi được tệp": "No se pudo escribir el archivo",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "El archivo escrito NO se vuelve a abrir bien — no uses esta versión",
        "Đã lưu %@ · %d trang": "%@ guardado · %d {one=página|other=páginas}",
        "Tên": "Nombre",
        "Kích thước": "Tamaño",
        "Đã nén": "Comprimido",
        "Tỉ lệ": "Proporción",
        "Sửa lúc": "Modificado el",
        "Mở mục đang chọn": "Abrir el elemento seleccionado",
        "Bung ra thư mục…": "Extraer a una carpeta…",
        "Bung vào đây": "Extraer aquí",
        "%d mục": "%d {one=elemento|other=elementos}",
        "giải nén ra %@": "extraído a %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— el interior de un archivo de Office es un comprimido; estas son sus partes",
        "Đã bung %d mục": "%d {one=elemento extraído|other=elementos extraídos}",
        "%d mục hỏng": "%d {one=elemento defectuoso|other=elementos defectuosos}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=elemento RECHAZADO|other=elementos RECHAZADOS} porque sus rutas salen de la carpeta de destino",
        "Không mở được mục này": "No se puede abrir este elemento",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Todavía no se puede escribir directamente en un %@ — usa «Guardar como…»",
        "Không có gì đổi": "No ha cambiado nada",
        "Đã ghi %d ô vào %@": "%d {one=celda escrita|other=celdas escritas} en %@",
        "Đã ghi %d đoạn vào %@": "%d {one=párrafo escrito|other=párrafos escritos} en %@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "No se pudo escribir en el archivo — el original queda intacto",
        "dựng bài": "preparar el caso de prueba",
        "Không ghi được settings.json": "No se puede escribir settings.json",
        "Xoay trái": "Girar a la izquierda",
        "Xoay phải": "Girar a la derecha",
        "Trang lên": "Subir página",
        "Trang xuống": "Bajar página",
        "Xoá trang…": "Eliminar páginas…",
        "Xoá trang": "Eliminar páginas",
        "Trích trang…": "Extraer páginas…",
        "Trích trang ra tệp mới": "Extraer páginas a un archivo nuevo",
        "Gộp tệp PDF…": "Combinar archivo PDF…",
        "Tách tệp…": "Dividir archivo…",
        "Tách tệp PDF": "Dividir archivo PDF",
        "Xuất ảnh…": "Exportar imágenes…",
        "Xuất trang ra ảnh PNG": "Exportar páginas como imágenes PNG",
        "Hoàn tác trang": "Deshacer edición de página",
        "Lưu bản đã sửa…": "Guardar copia editada…",
        "Phát": "Reproducir",
        "Tạm dừng": "Pausa",
        "Xem bình thường": "Vista normal",
        "Chọn sheet": "Elegir hoja",
        "Mở sheet": "Abrir hoja",
        "Bỏ và đổi sheet": "Descartar y cambiar de hoja",
        "Bảng tính có %d sheet.": "El libro tiene %d hojas.",
        "Bảng tính này chỉ có một sheet: «%@»": "Este libro solo tiene una hoja: «%@»",
        "Bỏ phần chưa lưu của sheet này?": "¿Descartar los cambios sin guardar de esta hoja?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Cambiar de hoja reemplaza toda la pestaña. Lo editado sin guardar con ⌘S se perderá.",
        "Chọn tệp PDF cần gộp vào": "Elige el PDF que se combinará",
        "Chọn thư mục ghi ảnh": "Elige la carpeta para las imágenes",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Elige dónde guardar. El segundo archivo se escribe junto a este.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "El documento tiene %d páginas. Escribe las páginas a eliminar, p. ej. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "El documento tiene %d páginas. Escribe las páginas a extraer, p. ej. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "El documento tiene %d páginas. Escribe las páginas a exportar, p. ej. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "El documento tiene %d páginas. Escribe la parte a separar, p. ej. 1-5; el resto será un segundo archivo.",
        "Đã xoay trang %d": "Página %d girada",
        "Đã xoá trang %@ · còn %d trang": "Páginas %@ eliminadas · quedan %d páginas",
        "Đã gộp %d trang từ «%@»": "%d páginas combinadas de «%@»",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Dividido en %@ (%d páginas) y %@ (%d páginas)",
        "Đã ghi %@ — %@ · %d trang": "Se escribió %@ — %@ · %d páginas",
        "Đã xuất %d ảnh vào %@": "%d imágenes exportadas a %@",
        "Chỉ xuất được %d/%d ảnh": "Solo se exportaron %d de %d imágenes",
        "Đã hoàn tác một thao tác trang": "Se deshizo una operación de página",
        "Không còn thao tác trang nào để hoàn tác": "No quedan operaciones de página que deshacer",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "No se pueden eliminar TODAS las páginas: un PDF debe conservar al menos una",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Ese intervalo es todo el documento: no hay nada que separar",
        "«%@» có mật khẩu — chưa gộp được": "«%@» está protegido con contraseña: no se puede combinar",
        "«%@» không có trang nào": "«%@» no tiene páginas",
        "Đã ở trang đầu": "Ya en la primera página",
        "Đã ở trang cuối": "Ya en la última página",
        "· đã sửa, chưa lưu": "· editado, sin guardar",
        "Ảnh động · %d khung": "Imagen animada · %d fotogramas",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Documento sin guardar: no hay archivo en el disco para ver en binario",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Este comando solo funciona con libros de Excel",
        "Không đọc được danh sách sheet": "No se pudo leer la lista de hojas",
        "Không có sheet «%@»": "No hay ninguna hoja llamada «%@»",
        "Không đọc được sheet «%@»": "No se pudo leer la hoja «%@»",
        "Sheet «%@» · %d hàng": "Hoja «%@» · %d filas",
        "phần còn lại": "el resto",
        "Lưu ý": "Nota",
        "Cẩn thận": "Precaución",
        "Xem thêm": "Véase también",
        "Chép": "Copiar",
        "Đã chép": "Copiado",
        "Chép đoạn mã mẫu": "Copiar el código de ejemplo",
        "Tìm trong trợ giúp": "Buscar en la ayuda",
        "Lùi": "Atrás",
        "Bắt đầu dùng": "Empezar",
        "Không mở cửa sổ này khi khởi động nữa": "No mostrar esta ventana al iniciar",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "La ayuda aún no está traducida a este idioma; se muestra en vietnamita.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Ir al desplazamiento (p. ej. 1F400 o 0x1F400)",
        "Chép dòng đã chọn": "Copiar las filas seleccionadas",
        "Đã chép %d dòng": "%d filas copiadas",
        "Không đọc được «%@»": "No se pudo leer «%@»",
        "Tệp rỗng": "Archivo vacío",
        "Không đọc được offset «%@»": "No se pudo leer el desplazamiento «%@»",
        "Offset 0x%@ vượt quá cỡ tệp": "El desplazamiento 0x%@ supera el tamaño del archivo",
        "Mở bằng ứng dụng khác…": "Abrir con otra app…",
        "%d kênh": "%d canales",
        "Không phát được «%@»": "No se puede reproducir «%@»",
        "Không phát được — %@": "No se puede reproducir — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS no incluye un decodificador para el formato %@: es un límite del sistema, no un archivo dañado.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Aún puedes ver los bytes en modo binario o abrirlo con una app que tenga su propio decodificador.",
        "Ký…": "Firmar…",
        "Sửa chữ…": "Editar texto…",
        "Sửa chữ": "Editar texto",
        "Vẽ đè": "Dibujar encima",
        "Ô chưa điền": "Siguiente campo vacío",
        "Xoá nội dung đã điền": "Borrar lo rellenado",
        "Tệp này không có ô biểu mẫu nào": "Este archivo no tiene campos de formulario",
        "Đã xoá nội dung của %d ô biểu mẫu": "Se borraron %d campos de formulario",
        "Mọi ô biểu mẫu đều đã có nội dung": "Todos los campos de formulario ya tienen valor",
        "Còn %d ô chưa điền": "Quedan %d campos vacíos",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Formulario rellenable: %d campos. Escribe directamente y luego «Guardar copia editada…»",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Elige una imagen de firma (con fondo transparente queda mejor)",
        "Không dựng được trang có chữ ký": "No se pudo crear la página firmada",
        "Đã chèn chữ ký vào trang %d": "Firma insertada en la página %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Primero selecciona el texto que quieres cambiar",
        "Vùng chọn quá nhỏ": "La selección es demasiado pequeña",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "El texto nuevo se DIBUJA ENCIMA de la selección con la tipografía del sistema. El texto antiguo queda tapado, no eliminado: aún se puede extraer, así que esto no es una censura.",
        "Không dựng được trang đã sửa": "No se pudo crear la página editada",
        "Đã vẽ đè chữ mới lên trang %d": "Se dibujó el texto nuevo en la página %d",
        "Đổi chế độ View / Code": "Cambiar Vista / Código",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Todavía no hay vista de árbol para JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Todavía no hay vista de diagrama en la pestaña",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Todavía no hay vista de esquema para PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Este archivo solo tiene un modo de visualización",
        "%d nút": "%d nodos",
        "Không dựng được cây: %@": "No se pudo construir el árbol: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "El documento es demasiado grande para el árbol: usa el modo Código",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "No se pudieron construir las páginas de este archivo \u{2014} usa el modo Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Las diapositivas se construyen a partir del texto; las imágenes y el diseño originales aún no se dibujan.",
        "Vừa ngang": "Ajustar al ancho",
        "Thu nhỏ trang": "Reducir página",
        "Phóng to trang": "Ampliar página",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu":
            "No se encontró \u{201C}%@\u{201D} en el documento",
        "Chỗ khớp %d/%d": "Coincidencia %d de %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "No hay texto seleccionado en la página.",
        "%d ký tự": "%d {one=carácter|other=caracteres}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Abrir los archivos directamente en modo View cuando lo tengan",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· CANCELADO a medias — la tabla está incompleta",
        "Chế độ hiển thị": "Modo de visualización",
        "Đổi giữa View và Code (⌥⌘V)": "Cambiar entre View y Code (⌥⌘V)",
        "Trang tài liệu": "Páginas del documento",
        "Chữ đã dựng": "Texto compuesto",
        "Trang bảng tính": "Páginas de la hoja",
        "Sơ đồ": "Diagrama",
        "Cây khoá–giá trị": "Árbol clave–valor",
        "Bộ phát": "Reproductor",
        "Danh sách mục": "Lista de entradas",
        "Báo cáo đã dựng": "Informe compuesto",
        "Tô theo mức": "Coloreado por nivel",
        "Trang slide": "Páginas de diapositivas",
        "Dàn ý": "Esquema",
        "Lưu rồi dựng lại": "Guardar y volver a componer",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Se muestra la copia EN DISCO: los cambios sin guardar no están aquí.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "El sistema no pudo construir el visor del documento: use el modo Code.",
        "Lưu tệp trước khi xem trang.": "Guarde el archivo antes de ver sus páginas.",
        "Đang ở chế độ Code": "Ahora en modo Code",
        "Đang ở chế độ View": "Ahora en modo View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Viendo el código fuente: pulse para pasar al modo View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "En modo View: pulse para volver al código fuente (⌥⌘V)",
        "Tín hiệu: %@": "Señal: %@",
        "Lý do: %@": "Motivo: %@",
        "Chi tiết: %@": "Detalle: %@",
        "Mở báo cáo": "Abrir informe",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor se cerró de forma inesperada a las %@: abra el informe para leerlo; no se envía nada.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligaduras: desactivadas, cada carácter ocupa una celda",
        "Chế độ CSV": "Modo CSV",
        "Dấu phân tách": "Separador",
        "Tự nhận diện": "Detectar automáticamente",
        "Dấu phân tách: %@": "Separador: %@",
        "Theo đuôi tệp": "Según la extensión",
        "%d dấu cách": "%d {one=espacio|other=espacios}",
        "Tài liệu đang sửa được": "Este documento se puede editar",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Solo lectura: se está siguiendo el archivo; detenga el seguimiento para editar",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Solo lectura: el archivo del disco no admite escritura",
        "Đã mở khoá — tài liệu sửa được": "Desbloqueado: el documento vuelve a ser editable",
        "Nhân bản tệp": "Duplicar archivo",
        "Đổi tên tệp…": "Cambiar nombre…",
        "Chuyển tệp tới…": "Mover archivo a…",
        "XML: đánh giá XPath…": "XML: evaluar XPath…",
        "Đánh giá XPath": "Evaluar XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Por ejemplo: //pedido/articulo[2]/@codigo · //*[@tipo='A'] · count(//articulo)",
        "Đánh giá": "Evaluar",
        "XPath không đọc được: %@": "No se puede leer ese XPath: %@",
        "XPath «%@» không khớp node nào": "XPath «%@» no coincidió con ningún nodo",
        "XPath «%@» — %d node": "XPath «%@» — %d {one=nodo|other=nodos}",
        "XPath «%@»: %d node": "XPath «%@»: %d {one=nodo|other=nodos}",
        "Lưu tệp trước khi nhân bản.": "Guarde el archivo antes de duplicarlo.",
        "Không nhân bản được": "No se pudo duplicar",
        "Đã nhân bản thành %@": "Duplicado como %@",
        "Lưu tệp trước khi đổi tên.": "Guarde el archivo antes de cambiarle el nombre.",
        "Đổi tên tệp": "Cambiar nombre del archivo",
        "Tên hiện tại: %@": "Nombre actual: %@",
        "Đổi tên": "Cambiar nombre",
        "Tên tệp không hợp lệ": "Ese nombre de archivo no es válido",
        "Đã có tệp tên %@ ở đó": "Ya hay un archivo llamado %@ ahí",
        "Lưu tệp trước khi chuyển.": "Guarde el archivo antes de moverlo.",
        "Chuyển tới": "Mover aquí",
        "Thư mục đích đã có tệp tên %@": "La carpeta de destino ya tiene un archivo llamado %@",
        "Không chuyển được tệp": "No se pudo mover el archivo",
        "Đã chuyển tới %@": "Movido a %@",
        "Bảng mã:": "Codificación:",
        "Xuống dòng:": "Fin de línea:",
        "Riêng cho %@": "Solo para %@",
        "    %d — dùng TAB": "    %d — tabulaciones",
        "    %d — dùng dấu cách": "    %d — espacios",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Quitar la regla propia y usar el ajuste global",
        "%@: thụt lề %d %@": "%@: sangría %d %@",
        "TAB": "tabulaciones",
        "dấu cách": "espacios",
        "Xuất": "Exportar",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Abrir los resultados en una pestaña de texto: guárdela con ⌘S",
        "Lượt tìm trước đó": "Búsquedas anteriores",
        "«%@» — %d kết quả": "«%@» — %d {one=resultado|other=resultados}",
        "Kết quả tìm «%@»": "Resultados de búsqueda de «%@»",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtrar nombres — p. ej. *.csv;*.log (vacío: todo archivo de texto)",
        "Thư mục %@ không có file văn bản nào": "La carpeta %@ no tiene archivos de texto",
        "Không tệp nào trong %@ khớp «%@»": "Ningún archivo de %@ coincide con «%@»",
        "%d byte · %d dòng": "%d bytes · %d {one=línea|other=líneas}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d bytes · %d {one=línea|other=líneas} — demasiado grande para contar caracteres y palabras",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d bytes · %d {one=carácter|other=caracteres} · %d {one=palabra|other=palabras} · %d {one=línea|other=líneas}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Este documento tiene %d {one=línea|other=líneas}, %d bytes. Escriba un número de línea, «línea,columna» o «@byte».",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "No se puede leer «%@»: escriba un número de línea, «línea,columna» o «@byte»",
    ]
}
