import Foundation

/// Bảng dịch tiếng Séc. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let cs: [String: String] = [
        "Bản đã lưu…": "Uložené verze…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Tento dokument nebyl nikdy uložen — žádná historie",
        "Chưa có bản đã lưu nào trước đó": "Žádné dřívější uložené verze",
        "Không đọc được bản ấy": "Tuto verzi nelze přečíst",
        "Khôi phục bản đã lưu": "Obnovit uloženou verzi",
        "XML: kiểm theo DTD/XSD…": "XML: ověřit podle DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Tento Mac nemá libxml2, takže ověření XSD není dostupné.",
        "Chọn lược đồ XSD để kiểm": "Vyberte schéma XSD pro ověření",
        "Hợp lệ theo": "Platné podle",
        "Plugin chạy xong, không đổi gì": "Zásuvný modul skončil, aniž by cokoli změnil",
        "Chưa cài plugin native nào": "Nejsou nainstalovány žádné nativní zásuvné moduly",
        "Gỡ plugin này": "Odebrat tento zásuvný modul",
        "Gỡ plugin này?": "Odebrat tento zásuvný modul?",
        "Gỡ": "Odebrat",
        "Cài plugin native…": "Nainstalovat nativní zásuvný modul…",
        "Mở thư mục plugin": "Otevřít složku zásuvných modulů",
        "Chọn file .dylib của plugin native": "Vyberte soubor .dylib zásuvného modulu",
        "Đã cài:": "Nainstalováno:",
        "Đã gỡ:": "Odebráno:",
        "Plugin native…": "Nativní zásuvné moduly…",
        "Chỉ nhận file .dylib.": "Přijímány jsou pouze soubory .dylib.",
        "Đã có một plugin trùng tên:": "Zásuvný modul se stejným názvem je již nainstalován:",
        "Không chép được plugin:": "Zásuvný modul nelze zkopírovat:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Nativní zásuvné moduly jsou jen ve verzi ke stažení, ne ve verzi z App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Pomocný proces zásuvných modulů nebyl nalezen.",
        "Không khởi động được tiến trình phụ:": "Pomocný proces nelze spustit:",
        "Tiến trình plugin đã dừng giữa chừng.": "Proces zásuvného modulu se zastavil v půli.",
        "Plugin không trả lời kịp — đã dừng nó.": "Zásuvný modul neodpověděl včas — byl zastaven.",
        "Plugin trả lời sai giao thức:": "Zásuvný modul odeslal chybně utvořenou zprávu:",
        "Plugin báo lỗi:": "Zásuvný modul ohlásil chybu:",
        "Về GEditor": "O aplikaci GEditor",
        "Cài đặt…": "Nastavení…",
        "Thoát GEditor": "Ukončit GEditor",
        "File": "Soubor",
        "Tab mới": "Nový panel",
        "Đóng tab": "Zavřít panel",
        "Tab kế": "Další panel",
        "Tab trước": "Předchozí panel",
        "Tài liệu mới": "Nový dokument",
        "Mở…": "Otevřít…",
        "Mở thư mục làm Workspace…": "Otevřít složku jako pracovní prostor…",
        "Mở gần đây": "Otevřít nedávné",
        "Lưu": "Uložit",
        "Lưu thành…": "Uložit jako…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Při ukládání odstraňovat mezery na konci řádku",
        "Theo dõi file (tail -f)": "Sledovat soubor (tail -f)",
        "In…": "Tisknout…",
        "Mở lại tab vừa đóng": "Znovu otevřít zavřený panel",
        "Chưa có file nào": "Žádné soubory",
        "Xoá danh sách": "Vyprázdnit seznam",
        "Edit": "Úpravy",
        "Hoàn tác": "Zpět",
        "Làm lại": "Znovu",
        "Cắt": "Vyjmout",
        "Sao chép": "Kopírovat",
        "Dán": "Vložit",
        "Lịch sử clipboard…": "Historie schránky…",
        "Column Editor…": "Editor sloupců…",
        "Chọn lần kế tiếp": "Vybrat další shodu",
        "Chọn tất cả": "Vybrat vše",
        "Nhân đôi dòng": "Zdvojit řádek",
        "Xóa dòng": "Smazat řádek",
        "Comment dòng": "Zakomentovat řádek",
        "Chưa chép gì trong phiên này": "V této relaci se nic nekopírovalo",
        "Xoá lịch sử": "Vymazat historii",
        "Search": "Hledat",
        "Tìm…": "Najít…",
        "Tìm và thay…": "Najít a nahradit…",
        "Tìm trong thư mục…": "Hledat ve složce…",
        "Thay trong thư mục…": "Nahradit ve složce…",
        "Kết quả kế": "Další výsledek",
        "Kết quả trước": "Předchozí výsledek",
        "Đi tới dòng…": "Přejít na řádek…",
        "Nhảy tới ngoặc khớp": "Přejít na odpovídající závorku",
        "Đánh dấu mọi dòng khớp…": "Označit všechny odpovídající řádky…",
        "Đảo dấu": "Obrátit označení",
        "Bỏ mọi dấu": "Zrušit všechna označení",
        "Chép dòng đã đánh dấu": "Kopírovat označené řádky",
        "Xóa dòng đã đánh dấu": "Smazat označené řádky",
        "Chỉ giữ dòng đã đánh dấu": "Ponechat jen označené řádky",
        "Lines": "Řádky",
        "Sắp xếp A→Z": "Seřadit A→Z",
        "Sắp xếp Z→A": "Seřadit Z→A",
        "Sắp xếp tự nhiên": "Přirozené řazení",
        "Khử trùng lặp": "Odstranit duplicity",
        "Đảo thứ tự dòng": "Obrátit pořadí řádků",
        "Dời dòng lên": "Posunout řádek nahoru",
        "Dời dòng xuống": "Posunout řádek dolů",
        "Ghép dòng": "Spojit řádky",
        "Tách dòng theo độ dài…": "Rozdělit řádky podle délky…",
        "Tách dòng theo ký tự…": "Rozdělit řádky podle znaku…",
        "Xóa dòng rỗng": "Smazat prázdné řádky",
        "Nén dòng trống liên tiếp": "Sloučit po sobě jdoucí prázdné řádky",
        "Cắt khoảng trắng cuối dòng": "Odstranit mezery na konci řádku",
        "Tab → Space": "Tab → mezera",
        "Space → Tab": "Mezera → Tab",
        "HOA": "VELKÁ PÍSMENA",
        "thường": "malá písmena",
        "Chữ Hoa Đầu Từ": "První Písmeno Každého Slova",
        "Chữ hoa đầu câu": "První písmeno věty",
        "Đảo hoa/thường": "oBRÁTIT vELIKOST pÍSMEN",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: vybrat list…",
        "Xem dạng bảng / văn bản": "Přepnout zobrazení tabulky / textu",
        "Xóa cột…": "Smazat sloupec…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Ověřit data (počet sloupců · typy)",
        "Bàn làm sạch dữ liệu…": "Dílna čištění dat…",
        "Chạy công thức làm sạch…": "Spustit recept čištění…",
        "Chuyển đổi…": "Převést…",
        "Đổi dấu phân tách…": "Změnit oddělovač…",
        "Xuất sang JSON…": "Exportovat do JSON…",
        "Format": "Formát",
        "Bảng mã…": "Kódování…",
        "Xuống dòng…": "Konce řádků…",
        "Chuẩn hóa Unicode…": "Normalizovat Unicode…",
        "JSON: định dạng lại": "JSON: naformátovat",
        "JSON: thu gọn một dòng": "JSON: zhustit do jednoho řádku",
        "JSON: sắp xếp khóa": "JSON: seřadit klíče",
        "JSON: truy vấn JSONPath…": "JSON: dotaz JSONPath…",
        "CSV: truy vấn SQL…": "CSV: dotaz SQL…",
        "Truy vấn SQL": "Dotaz SQL",
        "Đang chạy…": "Probíhá…",
        "Xuất ra tab mới": "Exportovat do nového panelu",
        "Tài liệu rỗng — không có bảng để truy vấn": "Prázdný dokument — není co dotazovat",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Není to tabulka CSV — první řádek má jen jeden sloupec",
        "Không đọc được câu truy vấn": "Dotaz nelze přečíst",
        "Không kiểm được câu truy vấn": "Dotaz nelze zkontrolovat",
        "Vàng (mặc định)": "Žlutá (výchozí)",
        "Xanh dương": "Modrá",
        "Xanh lá": "Zelená",
        "Vàng đất": "Okrová",
        "Tím": "Fialová",
        "Hồng": "Růžová",
        "Xanh ngọc": "Tyrkysová",
        "Cam": "Oranžová",
        "Xám lam": "Břidlicová",
        "Văn bản": "Text",
        "Dãy số": "Číselná řada",
        "Dãy ngày": "Řada dat",
        "Chữ HOA (hex)": "VELKÁ PÍSMENA (šestnáctkově)",
        "Bắt đầu": "Začátek",
        "Bước": "Krok",
        "Đệm 0 tới": "Doplnit nulami do",
        "Hệ": "Základ",
        "Ngày đầu": "První datum",
        "Định dạng": "Formát",
        "Chèn": "Vložit",
        "Huỷ": "Zrušit",
        "Chuyển đổi định dạng": "Převést formát",
        "Xem trước 5 hàng đầu": "Náhled prvních 5 řádků",
        "Tạo tab mới": "Otevřít v novém panelu",
        "Lưu ra file…": "Uložit do souboru…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Výsledek se otevře v novém, neuloženém panelu. Původní dokument zůstává nedotčen.",
        "Chạy trên tài liệu này": "Spustit na tomto dokumentu",
        "Chạy trên thư mục…": "Spustit na složce…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Celý recept je JEDEN krok zpět. Soubor na disku zůstává nedotčen, dokud neuložíte.",
        "tắt": "vypnuto",
        "không thấy cột": "sloupec nenalezen",
        "sẵn sàng": "připraveno",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "zabírá jádro procesoru, dokud se aplikace neukončí.",
        "Script không trả về gì": "Skript nic nevrátil",
        "Không dựng được máy JavaScript": "Nelze vytvořit stroj JavaScriptu",
        "Lỗi JavaScript không rõ": "Neznámá chyba JavaScriptu",
        "Bảng": "Tabulka",
        "Áp sắp xếp vào file": "Použít řazení na soubor",
        "Chuyển đổi ▾": "Převést ▾",
        "Xuất dòng khớp": "Exportovat odpovídající řádky",
        "Ẩn cột này": "Skrýt tento sloupec",
        "Đổi tên tiêu đề…": "Přejmenovat záhlaví…",
        "Chèn cột trống bên trái": "Vložit prázdný sloupec vlevo",
        "Chèn cột trống bên phải": "Vložit prázdný sloupec vpravo",
        "Xóa cột này khỏi file…": "Smazat tento sloupec ze souboru…",
        "Phải còn ít nhất một cột đang hiện": "Alespoň jeden sloupec musí zůstat viditelný",
        "Đang sắp xếp…": "Probíhá řazení…",
        "Trở về thứ tự trong file": "Zpět na pořadí ze souboru",
        "trăm hàng đầu": "prvních sto řádků",
        "chọn cột": "výběr sloupců",
        "đặt tên cột kết quả": "pojmenování sloupce výsledku",
        "lọc theo chữ": "filtrování podle textu",
        "ô rỗng": "prázdné buňky",
        "ghép điều kiện": "spojení podmínek",
        "đếm hàng": "počítání řádků",
        "gộp nhóm": "seskupení a souhrn",
        "nhỏ nhất, lớn nhất": "minimum, maximum",
        "sắp xếp và cắt": "řazení a omezení",
        "tên cột có dấu cách": "název sloupce s mezerami",
        "Truy vấn bị dừng giữa chừng": "Dotaz byl přerušen",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Nepodporováno: JOIN · poddotaz · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · okenní funkce",
        "XML: định dạng lại": "XML: naformátovat",
        "XML: thu gọn một dòng": "XML: zhustit do jednoho řádku",
        "XML: kiểm cú pháp": "XML: zkontrolovat syntaxi",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: zkontrolovat opakované klíče a odsazení",
        "View": "Zobrazení",
        "Ẩn/hiện sidebar (Function List)": "Zobrazit/skrýt postranní panel (seznam funkcí)",
        "Ẩn/hiện bản đồ tài liệu": "Zobrazit/skrýt mapu dokumentu",
        "Gấp / mở khối tại con nháy": "Sbalit / rozbalit blok u kurzoru",
        "Gấp tất cả": "Sbalit vše",
        "Bỏ gấp tất cả": "Rozbalit vše",
        "Gấp theo cấp": "Sbalit podle úrovně",
        "Cấp %d": "Úroveň %d",
        "Đã gấp %d khối ở cấp %d": "Sbaleno %1$d {one=blok|few=bloky|other=bloků} na úrovni %2$d",
        "Tài liệu này chỉ sâu %d cấp": "Tento dokument má hloubku jen %d {one=úroveň|few=úrovně|other=úrovní}",
        "mermaid: không đọc được bản kê": "mermaid: manifest nelze přečíst",
        "Kiểm tra bản cập nhật…": "Zkontrolovat aktualizace…",
        "Kiểm tra bản cập nhật": "Zkontrolovat aktualizace",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Verze z App Store se aktualizují přes Mac App Store, ne přes GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Toto sestavení nemá podpisový klíč aktualizací, takže je nemůže hledat.",
        "Phóng to chữ": "Zvětšit text",
        "Thu nhỏ chữ": "Zmenšit text",
        "Cỡ chữ gốc": "Skutečná velikost",
        "Chia đôi theo chiều dọc": "Rozdělit svisle",
        "Chia đôi theo chiều ngang": "Rozdělit vodorovně",
        "Bỏ chia đôi": "Zavřít rozdělení",
        "Mở tab này ở nửa kia": "Otevřít tento panel ve druhé polovině",
        "Nhảy sang nửa kia": "Přejít do druhé poloviny",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Zalamování řádků (vypnuto / okno / sloupec)",
        "Ngắt dòng tại cột…": "Zalamovat na sloupci…",
        "Đánh dấu dòng này": "Označit tento řádek",
        "Dấu kế tiếp": "Další značka",
        "Dấu trước đó": "Předchozí značka",
        "Màu đánh dấu…": "Barva značek…",
        "Hiện tất cả ký tự ẩn": "Zobrazit všechny neviditelné znaky",
        "  Khoảng trắng": "  Mezery",
        "  Tab": "  Tabulátory",
        "  Xuống dòng": "  Konce řádků",
        "  NBSP · zero-width · điều khiển": "  NBSP · nulová šířka · řídicí",
        "Xem nhị phân": "Binární zobrazení",
        "Chế độ CSV (tô màu theo cột)": "Režim CSV (sloupce barevně)",
        "Macro": "Makro",
        "Bắt đầu / dừng ghi": "Spustit / zastavit záznam",
        "Phát lại": "Přehrát",
        "Phát nhiều lần…": "Přehrát vícekrát…",
        "Phát đến cuối tài liệu": "Přehrávat do konce dokumentu",
        "Chạy trên mọi tab": "Spustit na všech panelech",
        "Hủy macro đang chạy": "Zrušit běžící makro",
        "Lưu macro…": "Uložit makro…",
        "Macro đã lưu…": "Uložená makra…",
        "Help": "Nápověda",
        "Trợ giúp GEditor": "Nápověda GEditor",
        "Giới thiệu tính năng": "Přehled funkcí",
        "Di cư từ Notepad++": "Přechod z Notepad++",
        "Tìm": "Najít",
        "Thay bằng": "Nahradit za",
        "Kế": "Další",
        "Trước": "Předchozí",
        "Đếm": "Spočítat",
        "Đóng": "Zavřít",
        "Kiểm theo JSON Schema…": "Ověřit podle schématu JSON…",
        "Chọn tệp JSON Schema": "Vyberte soubor schématu JSON",
        "Không thấy lỗi nào theo schema này.": "Podle tohoto schématu nebyly nalezeny žádné problémy.",
        "JSON Schema": "Schéma JSON",
        "Kiểm cú pháp đồ thị": "Zkontrolovat syntaxi grafu",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Formát grafu nebyl rozpoznán — je potřeba přípona .dot, .gv, .cypher, .ttl nebo .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Nebyly nalezeny žádné syntaktické chyby %@ (kontrola není vyčerpávající).",
        "Cú pháp %@": "Syntaxe %@",
        "không phải một đối tượng JSON": "není objekt JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Dolování textu (n-gramy, TF-IDF)",
        "Tài liệu rỗng.": "Dokument je prázdný.",
        "Không rút được từ khoá nào.": "Nepodařilo se získat žádné klíčové slovo.",
        "Từ khoá": "Klíčová slova",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=klíčové slovo|few=klíčová slova|other=klíčových slov} · %d {one=token|few=tokeny|other=tokenů} · %d {one=dokument|few=dokumenty|other=dokumentů}",
        "Tô lên tài liệu": "Označit v dokumentu",
        "Đánh dấu entity từ danh sách…": "Označit entity ze seznamu…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Vyberte seznam entit (CSV nebo JSON)",
        "Không đọc được danh sách entity.": "Seznam entit nelze přečíst.",
        "Danh sách entity rỗng.": "Seznam entit je prázdný.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "V dokumentu nebyly nalezeny žádné entity (načteno %d).",
        "%d lần xuất hiện · %@": "%d {one=výskyt|few=výskyty|other=výskytů} · %@",
        "Chuyển đổi tri thức…": "Převést znalosti…",
        "Chuyển đổi: %@ → %@": "Převod: %@ → %@",
        "Không chuyển đổi được.": "Nepodařilo se převést.",
        "Xem trước cắt chunk…": "Náhled dělení na části…",
        "Cỡ cố định 800B, chồng 100B": "Pevná velikost 800 B, překryv 100 B",
        "Theo câu (≤ 800B)": "Podle věty (≤ 800 B)",
        "Theo heading Markdown": "Podle nadpisu Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Prázdný dokument — žádné části.",
        "%d chunk · trung bình %d B · %@": "%d {one=část|few=části|other=částí} · v průměru %d B · %@",
        "Xuất JSONL": "Exportovat JSONL",
        "Chunk JSONL": "JSONL částí",
        "Mở triple/edge dạng bảng": "Otevřít trojice/hrany jako tabulku",
        "Bảng triple": "Tabulka trojic",
        "Tài liệu này không có dòng triple nào.": "Tento dokument nemá žádný řádek s trojicí.",
        "Không đọc được triple nào — dòng %d: %@": "Nepodařilo se přečíst žádnou trojici — řádek %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "Přečteno %1$d {one=trojici|few=trojice|other=trojic} · přeskočeno %2$d {one=chybný řádek|few=chybné řádky|other=chybných řádků} (první: řádek %3$d)",
        "Trùng lặp mờ theo cột…": "Neostré duplicity podle sloupce…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Neostré duplicity — sloupec «%1$@»: %2$d {one=skupina kandidátů|few=skupiny kandidátů|other=skupin kandidátů}",
        "Gộp": "Sloučit",
        "Giống": "Shoda",
        "Các giá trị trong cụm": "Hodnoty ve skupině",
        "Gộp về": "Sloučit do",
        "Gộp các cụm đã chọn": "Sloučit vybrané skupiny",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Není vybrána žádná skupina — stisknutí «Sloučit» NIC nezmění. Aplikace nikdy neslučuje sama od sebe.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "Vybrána %d {one=skupina|few=skupiny|other=skupin} · změní se %d {one=řádek|few=řádky|other=řádků} · JEDEN krok zpět",
        "Không quét được cột này.": "Tento sloupec nelze prohledat.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Sloupec «%@» nemá žádné skupiny neostrých duplicit.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Nebyla sloučena žádná skupina — dokument zůstává beze změny.",
        "Khử trùng lặp mờ · cột %@": "Odstranění neostrých duplicit · sloupec %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "Sloučena %d {one=skupina|few=skupiny|other=skupin} · změněno %d {one=buňka|few=buňky|other=buněk}",
        "Báo cáo làm sạch": "Zpráva o čištění",
        "# Báo cáo làm sạch — %@\n\n": "# Zpráva o čištění — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Použito (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Nebyl použit žádný krok._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Profil dat\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d {one=sloupec|few=sloupce|other=sloupců} · %2$d {one=řádek|few=řádky|other=řádků} · prohledáno za %3$.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Sloupec | Typ | Prázdné | Různé | Min | Max | Průměr |\n",
        "\n### Giá trị bất thường\n\n": "\n### Odlehlé hodnoty\n\n",
        "hàng %d: %@": "řádek %d: %@",
        "- cột «%@» — %d ô: %@\n": "- sloupec «%1$@» — %2$d {one=buňka|few=buňky|other=buněk}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Zbývá (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Žádná další zjištění._\n",
        "- cột «%@»: %@\n": "- sloupec «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Odstraňovat mezery při ukládání",
        "Chuẩn hóa xuống dòng": "Normalizovat konce řádků",
        "trước đó": "předchozí",
        "Không mở lại được thư mục «%@» của phiên trước": "Složku «%@» z předchozí relace nelze znovu otevřít",
        " (và %d file khác)": " (a další %d {one=soubor|few=soubory|other=souborů})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "Nepodařilo se znovu otevřít %d {one=panel|few=panely|other=panelů}: %@%@ — soubory už nejsou na původním místě.",
        "Không đọc được nội dung từ ống dẫn": "Vstup z roury nelze přečíst",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Mezery na konci řádku se budou odstraňovat při každém uložení",
        "Không cắt khoảng trắng khi lưu nữa": "Mezery se při ukládání už neodstraňují",
        "Chưa đặt tên.txt": "Bez názvu.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Převod kódování způsobí ztrátu znaků",
        "Vẫn lưu": "Přesto uložit",
        "Tài liệu có thay đổi chưa lưu": "Dokument má neuložené změny",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Zavření bez uložení je zahodí.",
        "Bỏ thay đổi": "Zahodit změny",
        "Đi tới dòng": "Přejít na řádek",
        "Tài liệu có %d dòng.": "Dokument má %d {one=řádek|few=řádky|other=řádků}.",
        "Số dòng": "Číslo řádku",
        "Đi tới": "Přejít",
        "Diễn giải lại theo…": "Znovu interpretovat jako…",
        "Chuyển đổi sang…": "Převést na…",
        "Không diễn giải lại được": "Nepodařilo se znovu interpretovat",
        "Bảng mã %@ không chứa hết ký tự": "%@ neumí zobrazit všechny znaky",
        "Vẫn chọn": "Přesto vybrat",
        "Cột %d": "Sloupec %d",
        "Cột %d: %@": "Sloupec %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Skryté sloupce: %@ (%d) — vraťte je z kontextové nabídky řádku záhlaví",
        "Hiện lại: %@": "Znovu zobrazit: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Sloupec %@ skryt — v souboru zůstává nedotčen",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Seřazeno podle %@ %@ · pouze zobrazení",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Seřazeno: %@ %@ (pouze zobrazení)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ řádků odpovídá — hledání pokračuje…",
        "%d / %d dòng khớp": "%d / %d {one=řádek odpovídá|few=řádky odpovídají|other=řádků odpovídá}",
        "Không tìm thấy lỗi trong %d hàng": "V %d {one=řádku|few=řádcích|other=řádcích} nebyly nalezeny žádné problémy",
        "%d hàng lệch số cột": "%d {one=řádek|few=řádky|other=řádků} s nesprávným počtem sloupců",
        "%d ô sai kiểu dữ liệu": "%d {one=buňka|few=buňky|other=buněk} s nesprávným datovým typem",
        " (đã dừng ở %d lỗi đầu)": " (zastaveno u prvních %d {one=problému|few=problémů|other=problémů})",
        "   —   kiểu nhận ra: ": "   —   rozpoznané typy: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Řádek %1$d, sloupec %2$@: «%3$@» není %4$@",
        "Column Editor — %d dòng": "Editor sloupců — %d {one=řádek|few=řádky|other=řádků}",
        "Phát hiện": "Zjištění",
        "Hồ sơ dữ liệu": "Profil dat",
        "Hồ sơ dữ liệu — đang quét…": "Profil dat — probíhá prohledávání…",
        "Lưu công thức…": "Uložit recept…",
        "Xuất báo cáo": "Exportovat zprávu",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Nebyla použita žádná skupina · každá skupina je jeden krok zpět",
        "quá nhiều giá trị": "příliš mnoho hodnot",
        "hay gặp: ": "nejčastější: ",
        "Giá trị điền vào ô thiếu": "Hodnota pro vyplnění prázdných buněk",
        "Áp dụng": "Použít",
        "Không dựng được bản xem trước": "Nepodařilo se sestavit náhled",
        "· giữ nguyên, không đọc được ·": "· ponecháno beze změny, nelze přečíst ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Převést sloupec na ISO 8601 (RRRR-MM-DD)",
        "Quy ước số cho cả cột": "Číselná konvence pro celý sloupec",
        "Làm gì với ô thiếu": "Co dělat s prázdnými buňkami",
        "Chuẩn hóa về ISO 8601": "Normalizovat na ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Číst nejednoznačné buňky s DNEM napřed (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Číst nejednoznačné buňky s MĚSÍCEM napřed (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Přeskočit nejednoznačné buňky, opravit jen jisté",
        "Về Việt/Âu (1.234,56)": "Na vietnamský/evropský (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Na angloamerický (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Na angloamerický, bez oddělovače tisíců (1234.56)",
        "Điền một giá trị mặc định…": "Vyplnit výchozí hodnotou…",
        "Điền xuôi — lấy giá trị phía trên": "Vyplnit dolů — vzít hodnotu shora",
        "Điền ngược — lấy giá trị phía dưới": "Vyplnit nahoru — vzít hodnotu zdola",
        "Xóa hàng có ô thiếu ở cột này": "Smazat řádky s prázdnou buňkou v tomto sloupci",
        "Cắt khoảng trắng hai đầu": "Odstranit mezery z obou konců",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Odstranit z obou konců a sloučit mezery uvnitř",
        "Pivot…": "Kontingenční tabulka…",
        "Nguồn…": "Zdroje…",
        "Pivot — gộp theo cột": "Kontingenční tabulka — seskupit podle sloupce",
        "Hàng (gộp nhóm)": "Řádky (seskupení)",
        "Giá trị": "Hodnoty",
        "+ Hàng": "+ Řádek",
        "+ Giá trị": "+ Hodnota",
        "Xoá hết": "Vymazat vše",
        "Đưa vào ô truy vấn": "Vložit do pole dotazu",
        "Chọn cột để dựng câu truy vấn.": "Vyberte sloupce pro sestavení dotazu.",
        "Không đọc được tên cột của bảng này.": "Názvy sloupců této tabulky nelze přečíst.",
        "Nguồn dữ liệu của truy vấn": "Zdroje dat dotazu",
        "«%@» — tài liệu đang mở": "«%@» — otevřený dokument",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ soubor se od zaregistrování změnil",
        "Thêm file…": "Přidat soubor…",
        "Bỏ hết": "Odebrat vše",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Z «%@» nelze odvodit název tabulky — přejmenujte soubor.",
        "Tổng": "Součet",
        "Trung bình": "Průměr",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Max",
        "Đếm khác nhau": "Počet různých",
        "Biểu đồ": "Graf",
        "Xuất PNG": "Exportovat PNG",
        "Xuất SVG": "Exportovat SVG",
        "Bảng này không có cột số nào để vẽ.": "Tato tabulka nemá číselný sloupec ke zobrazení.",
        "Không dựng được ảnh PNG.": "Nepodařilo se sestavit obrázek PNG.",
        "Kết quả truy vấn": "Výsledek dotazu",
        "Đã lưu %@": "Uloženo %@",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Graf %1$@ pro «%2$@» — %3$d {one=bod|few=body|other=bodů}, hodnoty od %4$@ do %5$@",
        "Cột": "Sloupcový",
        "Đường": "Spojnicový",
        "Phân bố": "Histogram",
        "Phân tán": "Bodový",
        "Hộp": "Krabicový",
        "CSV: chất lượng dữ liệu…": "CSV: kvalita dat…",
        "Chất lượng dữ liệu": "Kvalita dat",
        "Xuất vi phạm ra tab mới": "Exportovat porušení do nového panelu",
        "Mức": "Úroveň",
        "Luật": "Pravidlo",
        "Vi phạm": "Porušení",
        "Tỷ lệ": "Podíl",
        "đạt": "prošlo",
        "lỗi": "chyba",
        "cảnh báo": "varování",
        "hỏng": "poškozeno",
        "Đã đánh dấu %d dòng vi phạm": "Označen %d {one=porušující řádek|few=porušující řádky|other=porušujících řádků}",
        "Xu hướng": "Vývoj",
        "Lúc chấm": "Hodnoceno",
        "Số hàng": "Řádků",
        "Lệch": "Rozdíl",
        "Luật trượt": "Neprošlá pravidla",
        "Điểm chất lượng": "Skóre kvality",
        "Điểm theo thời gian": "Skóre v čase",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Historie zatím není — každé hodnocení připíše ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "jeden řádek do souboru «.history.jsonl» vedle pravidel.",
        "%d mốc trong lịch sử": "%d {one=bod|few=body|other=bodů} v historii",
        " · %d dòng KHÔNG đọc được": " · %d {one=řádek NELZE PŘEČÍST|few=řádky NELZE PŘEČÍST|other=řádků NELZE PŘEČÍST}",
        " · chọn hai dòng để so": " · vyberte dva řádky k porovnání",
        "điểm %+.1f": "skóre %+.1f",
        "không chiều nào tụt": "žádný rozměr neklesl",
        "tụt: ": "kleslo: ",
        "%d luật mới trượt: %@": "%d {one=nově neprošlé pravidlo|few=nově neprošlá pravidla|other=nově neprošlých pravidel}: %@",
        "số hàng %+d": "řádků %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (a další %d {one=varování|few=varování|other=varování} na panelu Vývoj)",
        "Không sửa tự động được: ": "Žádná automatická oprava: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Otevře odpovídající nástroj v dílně čištění a hned poté znovu ohodnotí.",
        "Xử lý giá trị thiếu…": "Zpracovat chybějící hodnoty…",
        "Chuẩn hóa ngày…": "Normalizovat data…",
        "Khử trùng lặp…": "Odstranit duplicity…",
        "Thay thế…": "Nahradit…",
        "Xem các dòng sai": "Zobrazit chybné řádky",
        "Không tìm thấy cột «%@» trong bảng này.": "Sloupec «%@» v této tabulce není.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Duplicity odstraněny — «%@» je nyní jedinečný. Skóre: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Duplicity odstraněny, ale «%1$@» má stále %2$d {one=opakovaný řádek|few=opakované řádky|other=opakovaných řádků} (dříve: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "ty řádky sdílejí KLÍČ, ale ne celý řádek, takže je nutné se podívat a vybrat ",
        "giữ hàng nào.": "který ponechat.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Nepodařilo se přečíst žádnou hodnotu porušující toto pravidlo.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {one=chybná hodnota|few=chybné hodnoty|other=chybných hodnot} ve sloupci «%2$@» — vyplňte pole Nahradit a stiskněte Náhled",
        "Đã chấm lại: %.0f/100": "Znovu ohodnoceno: %.0f/100",
        "Xem trước báo cáo": "Náhled zprávy",
        "Tham số…": "Parametry…",
        "Xuất HTML…": "Exportovat HTML…",
        "In / PDF…": "Tisk / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=blok proběhl|few=bloky proběhly|other=bloků proběhlo} · %d {one=blok SELHAL|few=bloky SELHALY|other=bloků SELHALO}",
        "%d khối chạy được": "%d {one=blok proběhl|few=bloky proběhly|other=bloků proběhlo}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · ZASTARALÁ DATA — zdrojový soubor se změnil; sestavte znovu",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Náhled zprávy vyžaduje dokument .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Nebyl nalezen zdroj dat — deklarujte «source: soubor.csv» ve frontmatteru.",
        "Không dựng được báo cáo.": "Nepodařilo se sestavit zprávu.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Tato zpráva nedeklaruje ve frontmatteru žádný parametr.",
        "Tham số báo cáo": "Parametry zprávy",
        "Dựng lại": "Sestavit znovu",
        "Đã xuất %@": "Exportováno %@",
        "Báo cáo: xem trước": "Zpráva: náhled",
        "Báo cáo: sinh loạt…": "Zpráva: dávkové vytvoření…",
        "không phải tài liệu .greport.md": "není dokument .greport.md",
        "không phân tích được báo cáo": "zprávu se nepodařilo rozebrat",
        "không tìm được dữ liệu nguồn": "nepodařilo se najít zdrojová data",
        "không đọc được danh sách tham số": "nepodařilo se přečíst seznam parametrů",
        "Sinh loạt cần tài liệu đuôi .%@": "Dávkové vytvoření vyžaduje dokument .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Vyberte seznam parametrů (CSV nebo JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Vyberte složku pro %d {one=zprávu|few=zprávy|other=zpráv}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "chybějící parametry ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "ukazuje na samotný zdrojový soubor — přepsání odmítnuto",
        "%d khối HỎNG": "%d {one=blok SELHAL|few=bloky SELHALY|other=bloků SELHALO}",
        "Sinh loạt xong: %d tệp · %d hỏng": "Dávka dokončena: %d {one=soubor|few=soubory|other=souborů} · %d selhalo",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=sadu parametrů|few=sady parametrů|other=sad parametrů} se nepodařilo sestavit — viz souhrn",
        "Sơ đồ Mermaid: xem trước": "Diagram Mermaid: náhled",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagram Mermaid: vložit šablonu…",
        "Sơ đồ Mermaid: định dạng lại": "Diagram Mermaid: znovu naformátovat",
        "Nền trong suốt": "Průhledné pozadí",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Tento Mac neumí převést diagram na PNG — je potřeba macOS 13. Export do SVG stále funguje.",
        "Lưu PNG %@…": "Uložit PNG %@…",
        "Lưu SVG…": "Uložit SVG…",
        "Chép ảnh vào clipboard": "Zkopírovat obrázek do schránky",
        "Màu thương hiệu…": "Barvy značky…",
        "Màu thương hiệu cho sơ đồ": "Barvy značky pro diagramy",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Každé pole je barva ve tvaru #rrggbb. Ukládá se do «themes/mermaid-brand.json» — lze zkopírovat na jiný Mac.",
        "Màu chính": "Hlavní barva",
        "Chữ trên nút": "Text na uzlech",
        "Viền": "Rámeček",
        "Đường nối": "Spoje",
        "Nền khi xuất ảnh": "Pozadí při exportu",
        "Lưu và chèn %%{init}%% vào tài liệu": "Uložit a vložit %%{init}%% do dokumentu",
        "Đã lưu màu thương hiệu": "Barvy značky uloženy",
        "Đã chép ảnh sơ đồ vào clipboard": "Obrázek diagramu zkopírován do schránky",
        "Đã lưu %@ — %@": "Uloženo %@ — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Tento diagram už má direktivu %%{init}%% — vaše zůstává nedotčena.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "Vloženo %%{init}%% — diagram si nyní nese vlastní barvy",
        "Chèn màu thương hiệu vào sơ đồ": "Vložit barvy značky do diagramu",
        "Định dạng sơ đồ Mermaid": "Znovu naformátovat diagram Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Zdroj diagramu je už uklizený — není co měnit",
        "Đã định dạng lại sơ đồ": "Diagram znovu naformátován",
        "Đã định dạng lại %d sơ đồ": "Znovu naformátován %d {one=diagram|few=diagramy|other=diagramů}",
        "Thư viện mẫu sơ đồ": "Knihovna šablon diagramů",
        "Mẫu sơ đồ đầy đủ": "Úplné šablony diagramů",
        "Mẩu cú pháp": "Úryvky syntaxe",
        "Đang soạn: %@": "Upravuje se: %@",
        "Đã chèn mẫu «%@»": "Vložena šablona «%@»",
        "Tài liệu đang ở chế độ chỉ đọc.": "Tento dokument je jen pro čtení.",
        "Sơ đồ Mermaid": "Diagram Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Tento dokument nemá žádný blok mermaid.",
        "Thương hiệu": "Značka",
        "Xuất…": "Exportovat…",
        "Chưa có sơ đồ nào": "Zatím žádné diagramy",
        "%d sơ đồ · %@": "%d {one=diagram|few=diagramy|other=diagramů} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d {one=diagram SELHAL|few=diagramy SELHALY|other=diagramů SELHALO} — diagram %3$d%4$@",
        ", dòng %d": ", řádek %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Tento dokument nemá blok ```mermaid a není ani souborem .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Zatím se nedokreslil žádný diagram.",
        "Không tìm thấy «%@» trong mã sơ đồ": "«%@» nebylo ve zdroji diagramu nalezeno",
        "không dựng được hàng rào chặn mạng cho WKWebView": "nepodařilo se sestavit síťovou zábranu pro WKWebView",
        "Luật kết hợp": "Asociační pravidla",
        "Mỗi dòng một giỏ": "Jeden košík na řádek",
        "Hai cột: mã · item": "Dva sloupce: identifikátor · položka",
        "Dạng dữ liệu giao dịch": "Tvar transakčních dat",
        "Cột giỏ hàng hoặc mã giao dịch": "Sloupec košíku nebo identifikátoru transakce",
        "Cột item": "Sloupec položky",
        "Ký tự phân tách item": "Znak oddělující položky",
        "Support tối thiểu, phần trăm": "Minimální support, procenta",
        "Confidence tối thiểu, phần trăm": "Minimální confidence, procenta",
        "Tách bởi:": "Odděleno:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "Tabulka asociačních pravidel",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Pozor",
        "%d giao dịch · %d item · %d luật": "%d {one=transakce|few=transakce|other=transakcí} · %d {one=položka|few=položky|other=položek} · %d {one=pravidlo|few=pravidla|other=pravidel}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — žádné pravidlo nedosáhlo prahů; snižte support nebo confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — ZASTAVENO PŘEDČASNĚ, tabulka je NEÚPLNÁ",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transakce obsahuje|few=transakce obsahují|other=transakcí obsahuje} obě strany",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Dvousloupcový tvar vyžaduje dva RŮZNÉ sloupce.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "Označeno %1$d {one=řádek|few=řádky|other=řádků} v %2$d {one=transakci|few=transakcích|other=transakcích} obsahujících «%3$@»",
        "CSV: luật kết hợp…": "CSV: asociační pravidla…",
        "Khai phá theo nhóm": "Skupinové dolování",
        "Cột nhóm": "Sloupec seskupení",
        "Cột giá trị": "Sloupec hodnot",
        "Cột thứ hai cho tương quan": "Druhý sloupec pro korelaci",
        "Cách xếp hạng": "Způsob řazení",
        "Nhóm theo:": "Seskupit podle:",
        "Giá trị:": "Hodnota:",
        "Xếp theo:": "Řadit podle:",
        "Bảng xếp hạng nhóm": "Tabulka pořadí skupin",
        "Nhóm": "Skupina",
        "Hàng": "Řádků",
        "Hàng rào riêng": "Vlastní práh",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "Rozdíl r",
        "Ghi chú": "Poznámka",
        "không đo được": "nelze změřit",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=skupina|few=skupiny|other=skupin} · celková referenční korelace %@",
        " · ĐÃ CẮT %d nhóm": " · VYŘAZENA %d {one=SKUPINA|few=SKUPINY|other=SKUPIN}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Tato tabulka nemá textový sloupec pro seskupení.",
        "Bảng này không có cột số nào để khai phá.": "Tato tabulka nemá číselný sloupec k prozkoumání.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "Označeno %1$d {one=řádek|few=řádky|other=řádků} skupiny «%2$@»",
        "CSV: khai phá theo nhóm…": "CSV: skupinové dolování…",
        "\u{2194}": "↔",
        "Dự báo": "Předpověď",
        "Cột giá trị theo thời gian": "Sloupec hodnot v čase",
        "Mô hình dự báo": "Model předpovědi",
        "Số kỳ dự báo": "Počet předpovídaných období",
        "Kết luận so với baseline": "Závěr vůči referenčním modelům",
        "Mô hình:": "Model:",
        "Số kỳ:": "Období:",
        "Chu kỳ:": "Sezóna:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Sezónní perioda; nechte prázdné pro automatické zjištění",
        "Bảng giá trị dự báo": "Tabulka předpovězených hodnot",
        "Kỳ": "Období",
        "Dải 80%": "Pásmo 80 %",
        "Dải 95%": "Pásmo 95 %",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "nelze spočítat",
        "Bảng này không có cột số nào để dự báo.": "Tato tabulka nemá číselný sloupec k předpovědi.",
        "Không dựng được dự báo cho cột này.": "Pro tento sloupec se nepodařilo sestavit předpověď.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Sloupec «%1$@» má jen %2$d {one=číselnou hodnotu|few=číselné hodnoty|other=číselných hodnot} — pro předpověď jsou potřeba alespoň 4.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Řada se čte přesně v pořadí řádků souboru — bez přeřazení a bez odvozování časového sloupce.\n",
        "Sai số huấn luyện": "Chyba učení",
        "CSV: dự báo chuỗi thời gian…": "CSV: předpověď časové řady…",
        "Holt-Winters cộng": "Holt-Winters aditivní",
        "Holt-Winters nhân": "Holt-Winters multiplikativní",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Sloupce vstupující do shlukování",
        "Đường cong WCSS": "Křivka WCSS",
        "Phân cụm": "Shluk",
        "Chuẩn hoá:": "Škálování:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Vyberte alespoň jeden sloupec.",
        "Không đủ dữ liệu để dựng đường cong.": "Na sestavení křivky není dost dat.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Loket naznačuje k = %d. WCSS VŽDY klesá s růstem k, takže jde o způsob čtení grafu, ne o statistické kritérium — podívejte se na křivku a posuďte, zda je zlom zřetelný.",
        "WCSS theo k": "WCSS podle k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k-vzdálenost naznačuje eps = %1$@ (minPts je ve výchozím stavu 2 × počet sloupců = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Vzdálenost ke k-tému sousedovi",
        "Cần ít nhất 2 cột số để phân cụm.": "Ke shlukování jsou potřeba alespoň 2 číselné sloupce.",
        "Cụm theo %@ và %@": "Shluky podle %@ a %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — shluky byly nalezeny v %d {one=rozměru|few=rozměrech|other=rozměrech}; graf ukazuje jen první 2",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# šum (cluster_id = -1): %d {one=řádek|few=řádky|other=řádků}\n",
        "CSV: phân cụm…": "CSV: shlukování…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Středy shluků (původní jednotky) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Korelační matice",
        "Phương pháp tương quan": "Metoda korelace",
        "Tương quan không hàm ý nhân quả.": "Korelace neznamená příčinnost.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Nejsilnější dvojice: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Klepnutím na buňku zobrazíte bodový graf.",
        "Không cặp nào đo được.": "Žádnou dvojici nelze změřit.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ na %4$d {one=řádku|few=řádcích|other=řádcích}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Ke korelaci jsou potřeba alespoň 2 číselné sloupce.",
        "Không đọc được cột «%@».": "Sloupec «%@» nelze přečíst.",
        "CSV: ma trận tương quan…": "CSV: korelační matice…",
        "Bất thường": "Anomálie",
        "Danh sách bất thường": "Seznam anomálií",
        "Cột:": "Sloupec:",
        "Cột số cần xét": "Číselný sloupec ke zkoumání",
        "Cách:": "Metoda:",
        "Phương pháp phát hiện": "Metoda zjišťování",
        "Phương pháp đã dùng": "Použitá metoda",
        "Ngưỡng": "Práh",
        "Đánh dấu": "Označit",
        "Xuất tab mới": "Exportovat do nového panelu",
        "Dòng": "Řádek",
        "Điểm": "Skóre",
        "Vì sao": "Proč",
        "nhẹ": "mírná",
        "vừa": "střední",
        "nặng": "vážná",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=řádek|few=řádky|other=řádků} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Tato tabulka nemá číselný sloupec, v němž by šlo hledat anomálie.",
        "Đã đánh dấu %d dòng bất thường": "Označen %d {one=anomální řádek|few=anomální řádky|other=anomálních řádků}",
        "CSV: tìm bất thường…": "CSV: najít anomálie…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d {one=pravidlo|few=pravidla|other=pravidel}, všechna PROŠLA · %2$d {one=řádek|few=řádky|other=řádků} · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d {one=chyba|few=chyby|other=chyb} · %2$d {one=varování|few=varování|other=varování} napříč %3$d {one=pravidlem|few=pravidly|other=pravidly} · %4$d {one=řádek|few=řádky|other=řádků} · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Nejprve uložte dokument — pravidla kvality leží vedle datového souboru.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Sada pravidel zatím neexistuje. Vytvořte soubor %@ a otevřete znovu.",
        "Lịch sử": "Historie",
        "Câu đã lưu": "Uložené dotazy",
        "Lưu câu này…": "Uložit tento dotaz…",
        "Lưu câu truy vấn": "Uložit dotaz",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Dejte mu název, ať jej později najdete. Stejný název přepisuje.",
        "Ví dụ: Doanh thu theo tỉnh": "Například: Tržby podle krajů",
        "Chưa nhập giá trị cho tham số: %@": "Pro parametr nebyla zadána hodnota: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Zásuvný modul se od vašeho schválení změnil — GEditor jej odmítá spustit",
        "Chạy plugin chưa duyệt?": "Spustit neschválený zásuvný modul?",
        "Tôi tin file này — chạy": "Tomuto souboru důvěřuji — spustit",
        "KHÔNG có chữ ký": "NEPODEPSÁNO",
        "Chữ ký: %@": "Podpis: %@",
        "Đường dẫn: %@": "Cesta: %@",
        "Thay": "Nahradit",
        "Thay tất cả": "Nahradit vše",
        "Chuỗi thuần": "Prostý text",
        "Extended (\\n \\t \\xNN)": "Rozšířený (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Regulární výraz",
        "Phân biệt hoa thường": "Rozlišovat velikost písmen",
        "Cả từ": "Celé slovo",
        "Không có kết quả": "Žádné výsledky",
        "Thử biểu thức chính quy…": "Vyzkoušet regulární výraz…",
        "Chế độ Log (tô theo mức)": "Režim protokolu (barva podle úrovně)",
        "Lọc log theo mức…": "Filtrovat protokol podle úrovně…",
        "Chạy trên cả thư mục…": "Spustit na celé složce…",
        "Lọc qua lệnh ngoài…": "Filtrovat vnějším příkazem…",
        "Script…": "Skripty…",
        "Gói mở rộng…": "Rozšiřující balíčky…",
        "Cửa sổ mới": "Nové okno",
        "Tách tab ra cửa sổ mới": "Oddělit panel do nového okna",
        "Chưa mở thư mục nào": "Není otevřena žádná složka",
        "Tìm file trong thư mục": "Najít soubor ve složce",
        "Lọc theo tên": "Filtrovat podle názvu",
        "File mới…": "Nový soubor…",
        "Thư mục mới…": "Nová složka…",
        "Đổi tên…": "Přejmenovat…",
        "Chuyển vào Thùng rác": "Přesunout do koše",
        "Hiện trong Finder": "Zobrazit ve Finderu",
        "Đang đọc cấu trúc tài liệu…": "Čte se struktura dokumentu…",
        "file này không có hàm nào": "tento soubor nemá žádné funkce",
        "Không có gì khớp": "Žádné shody",
        "Văn bản thuần": "Prostý text",
        "🔒 Chỉ đọc": "🔒 Jen pro čtení",
        "Đang theo dõi": "Sledováno",
        "ngắt tại cột": "zalomení na sloupci",
        "Cú pháp": "Syntaxe",
        "Bấm để chèn vào ô truy vấn": "Klepnutím vložíte do dotazu",
        "truy vấn không hợp lệ": "neplatný dotaz",
        "khóa `ten` ở gốc": "klíč «název» v kořeni",
        "khóa có dấu cách": "klíč s mezerami",
        "phần tử đầu": "první prvek",
        "mọi phần tử": "všechny prvky",
        "lát cắt": "výřez",
        "hợp nhiều chỉ số": "sjednocení indexů",
        "mọi khóa `gia` ở mọi tầng": "všechny klíče «cena» na všech úrovních",
        "mọi nút": "všechny uzly",
        "lọc theo số": "filtrovat podle čísla",
        "lọc theo có mặt": "filtrovat podle přítomnosti",
        "Tới lỗi đầu tiên": "Na první chybu",
        "Cột doanh_thu là số": "Sloupec tržby je číselný",
        "lọc…": "filtrovat…",
        "Hủy": "Zrušit",
        "Thực hiện thay": "Provést nahrazení",
        "xem trước": "náhled",
        "tương tác": "interaktivně",
        "Soạn thảo": "Úpravy",
        "Giao diện": "Rozhraní",
        "Phím tắt": "Klávesové zkratky",
        "Cỡ chữ": "Velikost textu",
        "Bề rộng TAB": "Šířka tabulátoru",
        "Thụt lề bằng TAB": "Odsazovat tabulátory",
        "Tự động thụt lề khi xuống dòng": "Odsazovat automaticky při novém řádku",
        "Tô mọi kết quả tìm kiếm": "Zvýrazňovat všechny výsledky hledání",
        "Chuẩn hóa về NFC khi lưu": "Normalizovat na NFC při ukládání",
        "Ngôn ngữ": "Jazyk",
        "Nền": "Vzhled",
        "Theo hệ thống": "Podle systému",
        "Sáng": "Světlý",
        "Tối": "Tmavý",
        "Theme": "Motiv",
        "Dùng preset Notepad++": "Použít předvolbu Notepad++",
        "Về phím mặc định": "Zpět na výchozí klávesy",
        "Mở file cấu hình": "Otevřít soubor nastavení",
        "Xuất theme hiện tại": "Exportovat aktuální motiv",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Změna jazyka se plně projeví při dalším spuštění.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Výchozí klávesy se vrátí při dalším spuštění.",
        "Xem trước Markdown": "Náhled Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Náhled používá systémový stroj Markdown: zatím bez tabulek a bez obarvení bloků kódu.",
        "Thử biểu thức chính quy": "Vyzkoušet regulární výraz",
        "Biểu thức": "Výraz",
        "Văn bản thử": "Zkušební text",
        "Kết quả": "Výsledek",
        "Kết quả khớp": "Shody",
        "Biểu thức này làm gì": "Co tento výraz dělá",
        "Giải thích biểu thức": "Vysvětlit výraz",
        "Chế độ tìm kiếm": "Režim hledání",
        "Kết quả tìm kiếm": "Výsledky hledání",
        "Không khớp chỗ nào": "Žádné shody",
        " (đã cắt bớt)": " (zkráceno)",
        "Bản đồ tài liệu": "Mapa dokumentu",
        "Thanh tab": "Panelová lišta",
        "Hàng tiêu đề cột": "Řádek záhlaví sloupců",
        "Không có cột nào": "Žádné sloupce",
        "Cây thư mục workspace": "Strom pracovního prostoru",
        "Danh sách hàm và lớp": "Seznam funkcí a tříd",
        "Kết quả tìm trong thư mục": "Výsledky hledání ve složce",
        "Bảng dữ liệu CSV": "Datová tabulka CSV",
        "Bàn làm sạch dữ liệu": "Dílna čištění dat",
        "Truy vấn JSONPath": "Dotaz JSONPath",
        "Danh sách lỗi dữ liệu": "Seznam chyb v datech",
        "Bộ đánh giá golden set…": "Hodnotitel zlaté sady…",
        "So với điểm ngoài (JSONL)…": "Porovnat s vnějšími skóre (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Vyberte soubor vnějších skóre (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Přejmenovat vybraný uzel",
        "Gộp các node đang chọn": "Sloučit vybrané uzly",
        "Tách node đang chọn": "Rozdělit vybraný uzel",
        "Trích subgraph đang chọn ra tab mới": "Vytáhnout vybraný podgraf do nového panelu",
        "Không có gì để đổi": "Není co měnit",
        "%@ — áp %d thay đổi?": "%1$@ — použít %2$d {one=změnu|few=změny|other=změn}?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d {one=změna|few=změny|other=změn} · Cmd-Z vrátí celou dávku",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Umístěte kurzor PŘESNĚ NA JEDEN uzel a zkuste to znovu",
        "Đổi tên «%@»": "Přejmenovat «%@»",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Všechny hrany a popisky odkazující na tento uzel se změní s ním.",
        "Đổi tên node": "Přejmenovat uzel",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Vyberte ALESPOŇ DVA uzly a zkuste to znovu",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Kanonický tvar «%@» — nejčastější, nejdelší, s diakritikou",
        "Gộp node": "Sloučit uzly",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Vyberte ŘÁDKY HRAN, které chcete přesunout, a zkuste to znovu",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Všechny vybrané řádky se musí dotýkat PŘESNĚ JEDNOHO uzlu — vyberte další řádky hran",
        "Tách «%@» — chuyển %d cạnh": "Rozdělit «%1$@» — přesunout %2$d {one=hranu|few=hrany|other=hran}",
        "Cạnh tới: %@": "Hrany k: %@",
        "Tách node": "Rozdělit uzel",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Dokument není uložen — vytažený soubor potřebuje místo vedle",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Vyberte část grafu k vytažení a zkuste to znovu",
        "Gom biến thể entity → bảng duyệt": "Sloučit varianty entit → kontrolní tabulka",
        "Áp bảng duyệt đã sửa": "Použít upravenou kontrolní tabulku",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Dokument není uložen — kontrolní tabulka musí ležet vedle souboru grafu",
        "Không tìm thấy biến thể nào để gom": "Nebyly nalezeny žádné varianty ke sloučení",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=skupina variant|few=skupiny variant|other=skupin variant} — opravte sloupec «canonical» a spusťte «Použít kontrolní tabulku»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Kontrolní tabulka «%@» neexistuje — spusťte nejprve «Sloučit varianty entit»",
        "Bảng duyệt không đọc được: %@": "Kontrolní tabulku nelze přečíst: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Kontrolní tabulka nemá žádný řádek ke změně",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Žádné místo v grafu neodpovídá kontrolní tabulce",
        "Gom biến thể entity": "Sloučit varianty entit",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "Použito %d {one=změna|few=změny|other=změn} · tabulka aliasů a seznam značek zapsány vedle souboru",
        "Áp %d thay đổi lên đồ thị?": "Použít na graf %d {one=změnu|few=změny|other=změn}?",
        "%d alias → dạng chuẩn.": "%d {one=alias|few=aliasy|other=aliasů} → kanonický tvar.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "SLOUČIT uzly (nelze vrátit opětovným napsáním):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias v grafu není a byl přeskočen|few=aliasy v grafu nejsou a byly přeskočeny|other=aliasů v grafu není a byly přeskočeny}.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Analýza pokrytí část ↔ entita",
        "Xuất gói ngữ cảnh (JSONL)": "Exportovat balík kontextu (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Pokrytí část ↔ entita ↔ graf",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=entita|few=entity|other=entit} · %2$d {one=část|few=části|other=částí} · %3$.0f %% entit zmíněno · %4$.0f %% částí s entitou",
        "Entity không chunk nào nhắc tới": "Entity, které nezmiňuje žádná část",
        "Chunk mồ côi (không chứa entity nào)": "Osiřelé části (bez jediné entity)",
        "Node đồ thị không có entity đối ứng": "Uzly grafu bez odpovídající entity",
        "không có": "žádné",
        "Phương pháp": "Metoda",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Nepodařilo se sestavit přiřazení část ↔ entita",
        "Chấm sức khoẻ đồ thị": "Ohodnotit zdraví grafu",
        "sức khoẻ đồ thị": "zdraví grafu",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Zdraví %1$@/100 · %2$d {one=chyba|few=chyby|other=chyb} · %3$d {one=obrácení|few=obrácení|other=obrácení} · %4$d osiřelých",
        "Lai với đồ thị": "Hybrid s grafem",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: signál grafu se zcela ignoruje, výsledek se shoduje s čistým BM25",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α vysoké: graf jen mírně upravuje pořadí od BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α kolem výchozí 0,7: vede BM25, graf upravuje",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α nízké: vede graf, BM25 jen rozhoduje o shodných případech",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: jen signál grafu; části bez entit jsou si rovny",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Dokument není uložen — hybrid potřebuje soubor grafu vedle korpusu",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Soubor grafu «%@» nebyl nalezen — hybrid jej potřebuje pro svůj signál",
        "lai %.1f ms · %@": "hybrid %.1f ms · %@",
        "Thuật toán…": "Algoritmy…",
        "PageRank (độ dày viền)": "PageRank (tloušťka obrysu)",
        "Cộng đồng (màu nền)": "Komunity (barva pozadí)",
        "Thành phần liên thông": "Komponenty souvislosti",
        "Xuất bảng node ra tab mới": "Exportovat tabulku uzlů do nového panelu",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d {one=komponenta|few=komponenty|other=komponent} · největší %2$d {one=uzel|few=uzly|other=uzlů} · %3$d osiřelých uzlů",
        "Tài liệu này không phải đồ thị DOT": "Tento dokument není graf DOT",
        "Không dựng được bảng node/cạnh: %@": "Nepodařilo se sestavit tabulku uzlů/hran: %@",
        "%d hàng · %@": "%d {one=řádek|few=řádky|other=řádků} · %@",
        "Gán nhãn": "Označit štítkem",
        "Ghi chú (tuỳ chọn)": "Poznámka (nepovinná)",
        "Lưu record": "Uložit záznam",
        "Xuất CSV": "Exportovat CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Dokument není uložen — hodnotitel musí ležet vedle souboru korpusu",
        "Không nạp được bộ đánh giá: %@": "Nepodařilo se načíst hodnotitele: %@",
        "Không lưu được: %@": "Nepodařilo se uložit: %@",
        "Bộ đánh giá chưa có record nào": "Hodnotitel zatím nemá žádný záznam",
        "Không ghi được: %@": "Nepodařilo se zapsat: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Tento dokument není soubor .mmd, není DOT a nemá blok mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=uzel|few=uzly|other=uzlů} · %d {one=hrana|few=hrany|other=hran} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagram Mermaid: přidat prvek…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagram Mermaid: spojit dva vybrané prvky",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagram Mermaid: změnit popisek vybraného prvku…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagram Mermaid: smazat vybraný prvek",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagram Mermaid: posunout zprávu nahoru",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagram Mermaid: posunout zprávu dolů",
        "Thêm phần tử": "Přidat prvek",
        "Thêm participant": "Přidat účastníka",
        "Thêm mục": "Přidat položku",
        "Thêm mục sơ đồ": "Přidat položku do diagramu",
        "Sửa mục sơ đồ": "Změnit položku diagramu",
        "Xoá mục sơ đồ": "Smazat položku diagramu",
        "Xoá phần tử": "Smazat prvek",
        "Sửa nhãn": "Změnit popisek",
        "Đổi thứ tự message": "Změnit pořadí zpráv",
        "Tên mục": "Název položky",
        "Mục mới": "Nová položka",
        "Tên mục hiện trên sơ đồ.": "Název položky se objeví na diagramu.",
        "Bảng thuộc tính sơ đồ": "Tabulka vlastností diagramu",
        "Tài liệu này không có khối mermaid nào": "Tento dokument nemá blok mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identifikátor ve zdroji diagramu — bez mezer. Popisek se mění později dvojitým klepnutím.",
        "Để trống thì hiện chính định danh.": "Necháte-li prázdné, zobrazí se samotný identifikátor.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Mění se jen viditelný POPISEK; identifikátor prvku zůstává stejný.",
        "Không rõ «%@» là phần tử nào": "Není jasné, který prvek je «%@»",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Vyberte PŘESNĚ DVA prvky a zkuste to znovu",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Umístěte kurzor PŘESNĚ NA JEDEN prvek a zkuste to znovu",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Vyberte JEDEN prvek ke smazání nebo dva prvky spojené hranou",
        "Xoá «%@» và %d cạnh chạm nó?": "Smazat «%1$@» a %2$d {one=hranu, která se ho dotýká|few=hrany, které se ho dotýkají|other=hran, které se ho dotýkají}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Uzly na druhém konci těchto hran zůstávají — jsou znovu deklarovány i s popiskem, pokud byl příkaz hrany jejich jedinou deklarací.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Diagram «%1$@» se upravuje pouze jako text — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: tažením mezi dvěma prvky je spojíte, dvojitým klepnutím změníte popisek",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: tažením mezi dvěma účastníky přidáte zprávu; pořadí změníte v nabídce Nástroje",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: upravujte v tabulce vlastností níže",
        "Soạn trực quan đã bật": "Vizuální úpravy zapnuty",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d {one=položka|few=položky|other=položek} — upravujte přímo v tabulce, každá buňka je jeden krok zpět",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "U koláčového grafu je to číslo; u gantta to, co následuje po dvojtečce.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagram Mermaid: vytáhnout blok do souboru .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagram Mermaid: vložit odkazovaný soubor zpět",
        "Tách khối sơ đồ": "Vytáhnout blok diagramu",
        "Nhúng khối sơ đồ": "Vložit blok diagramu",
        "Tách khối sơ đồ ra tệp riêng": "Vytáhnout blok diagramu do samostatného souboru",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Soubor se umístí VEDLE dokumentu; v bloku zůstane jeden řádek odkazu, takže upravujete jen na jednom místě.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Dokument není uložen — soubor diagramu potřebuje místo vedle",
        "Đã có tệp «%@» — chọn tên khác": "Soubor «%@» už existuje — zvolte jiný název",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Vytaženo do «%@» — v bloku zůstal řádek odkazu",
        "Mở tệp": "Otevřít soubor",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» vloženo zpět; soubor zůstává na disku",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Tento blok obsahuje skutečný diagram, ne odkaz",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Tento blok odkazuje na «%@» — otevřete ten soubor a upravte jej",
        "Không đọc được tệp sơ đồ %@": "Nepodařilo se přečíst soubor diagramu %@",
        "Soạn trực quan": "Vizuální úpravy",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Tažením od jednoho uzlu k druhému přidáte hranu; dvojitým klepnutím změníte popisek. Každý úkon je jeden krok zpět.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Vizuální úpravy: tažením mezi dvěma uzly přidáte hranu, dvojitým klepnutím změníte popisek",
        "Soạn trực quan đã tắt": "Vizuální úpravy vypnuty",
        "Thêm node…": "Přidat uzel…",
        "Thêm cạnh giữa hai node đang chọn…": "Přidat hranu mezi dva vybrané uzly…",
        "Sửa nhãn node đang chọn…": "Změnit popisek vybraného uzlu…",
        "Xoá node/cạnh đang chọn": "Smazat vybraný uzel/hranu",
        "Thêm node": "Přidat uzel",
        "Thêm cạnh": "Přidat hranu",
        "Sửa nhãn node": "Změnit popisek uzlu",
        "Xoá node": "Smazat uzel",
        "Xoá cạnh": "Smazat hranu",
        "Cmd-Z hoàn tác": "Cmd-Z vrátí zpět",
        "Tài liệu đang ở chế độ chỉ đọc": "Tento dokument je jen pro čtení",
        "Nhãn của «%@»": "Popisek «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Mění se jen viditelný POPISEK; identifikátor uzlu zůstává stejný.",
        "Không rõ «%@» là node nào": "Není jasné, který uzel je «%@»",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identifikátor uzlu v souboru DOT. Popisek se mění později dvojitým klepnutím na obrázku.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Vyberte PŘESNĚ DVA uzly a zkuste to znovu",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Vyberte JEDEN uzel ke smazání nebo dva uzly spojené hranou",
        "Xoá node «%@» và %d cạnh chạm nó?": "Smazat uzel «%1$@» a %2$d {one=hranu, která se ho dotýká|few=hrany, které se ho dotýkají|other=hran, které se ho dotýkají}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Zůstanou-li visící hrany, DOT z nich uzly vytvoří znovu — smazaný uzel se při dalším kreslení objeví zpět.",
        "Phòng thí nghiệm truy hồi BM25": "Laboratoř vyhledávání BM25",
        "Câu hỏi — Enter để tìm": "Otázka — Enter pro hledání",
        "Đánh giá…": "Ohodnotit…",
        "Đang dựng chỉ mục": "Sestavuje se index",
        "Không chunk nào khớp": "Žádná část neodpovídá",
        "kết quả trên": "nejlepších výsledků",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: každé slovo se počítá POUZE jednou, ať se vyskytne kolikrát chce",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 nízké: opakování slova skóre téměř nepřidá",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 kolem výchozí 1,2: opakování skóre přidává, ale stále méně",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 vysoké: část, která slovo mnohokrát opakuje, je silně odměněna",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: délka se ignoruje, dlouhé části nejsou penalizovány",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b nízké: dlouhé části jsou penalizovány jen mírně",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b kolem výchozí 0,75: dlouhé části jsou penalizovány středně",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: největší penalizace za délku, krátké části jsou zvýhodněny",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: laboratoř vyhledávání…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Dokument není uložen — index BM25 leží vedle souboru korpusu, takže je potřeba cesta",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Tento soubor není JSONL — Retrieval Lab pracuje nad korpusem částí",
        "Không dựng được chỉ mục BM25 cho tệp này": "Pro tento soubor se nepodařilo sestavit index BM25",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Dokument není uložen — k vytvoření zprávy je potřeba cesta ke korpusu",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Vyberte hodnoticí sadu (CSV nebo JSONL: otázka + očekávaný identifikátor části)",
        "Đánh giá truy hồi": "Hodnocení vyhledávání",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Změňte výše k1, b nebo k a podívejte se znovu, ať porovnáte dvě konfigurace; přidejte blok «compare», ať dvě sady parametrů běží souběžně nad toutéž hodnoticí sadou.",
        "Lỗi": "Chyba",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, průměr %.0f)",
        "Chế độ JSONL": "Režim JSONL",
        "Bản ghi": "Záznam",
        "Chi tiết": "Podrobnosti",
        "Bản ghi ở dòng": "Záznam na řádku",
        "không phải JSON hợp lệ": "není platný JSON",
        "bản ghi": "záznamů",
        "dòng trắng": "prázdných řádků",
        "không phải đối tượng": "není objekt",
        "bảng hiện": "zobrazená tabulka",
        "ĐÃ HUỶ giữa chừng": "ZRUŠENO V PŮLI",
        "Không lọc": "Bez filtru",
        "bản ghi khớp bộ lọc": "záznamů odpovídajících filtru",
        "Đưa con nháy tới một dòng để xem bản ghi": "Umístěte kurzor na řádek, ať uvidíte záznam",
        "Không có bản ghi nào hỏng": "Žádné poškozené záznamy",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Zatím neprozkoumáno. Po ověření spusťte znovu «JSONL: prozkoumat části».",
        "trường văn bản": "textové pole",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHÉMA (odhad — změní se výběrem jiného pole)",
        "văn bản": "text",
        "định danh": "identifikátor",
        "metadata lồng": "vnořená metadata",
        "TRƯỜNG": "POLE",
        "phủ": "pokrytí",
        "nhiều kiểu": "více typů",
        "ĐỘ DÀI — ký tự": "DÉLKA — znaky",
        "ĐỘ DÀI — từ": "DÉLKA — slova",
        "ĐỘ DÀI — token ước lượng": "DÉLKA — odhadované tokeny",
        "RỖNG VÀ TRÙNG": "PRÁZDNÉ A DUPLICITNÍ",
        "chunk rỗng": "prázdných částí",
        "dòng": "řádků",
        "nhóm trùng chính xác": "skupin přesných duplicit",
        "dòng không đọc được, không vào thống kê": "řádků nelze přečíst, mimo statistiku",
        "PHƯƠNG PHÁP": "METODA",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«znaky» se počítají jako znaky Unicode (skaláry), ne jako viditelné skupiny",
        "«từ» tách theo khoảng trắng ASCII": "«slova» se dělí mezerami ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«tokeny» se počítají slabikovým děličem — NE tím z modelu",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«duplicita» znamená PŘESNOU duplicitu; téměř-duplicity jsou v bloku ```quality",
        "chunk": "částí",
        "JSONL: kiểm và soi chunk…": "JSONL: ověřit a prozkoumat části…",
        "Ảnh": "Obrázek",
        "PDF": "PDF",
        "Tài liệu Word": "Dokument Word",
        "Bảng tính Excel": "Tabulka Excel",
        "Bản trình chiếu PowerPoint": "Prezentace PowerPoint",
        "File nén": "Archiv",
        "Vừa khung": "Přizpůsobit oknu",
        "Chép ảnh": "Kopírovat obrázek",
        "Xoay": "Otočit",
        "Không đọc được ảnh «%@»": "Obrázek «%@» nelze přečíst",
        "Đã chép ảnh vào clipboard": "Obrázek zkopírován do schránky",
        "Bôi vàng": "Zvýraznit žlutě",
        "Gạch chân": "Podtrhnout",
        "Ghi chú…": "Poznámka…",
        "Bỏ chú thích": "Odstranit poznámky",
        "Lấy chữ ra tab mới": "Vytáhnout text do nového panelu",
        "Lưu bản có chú thích…": "Uložit verzi s poznámkami…",
        "Tìm trong PDF": "Hledat v PDF",
        "Thêm": "Přidat",
        "Trang %d/%d": "Stránka %d/%d",
        "Trang %d": "Stránka %d",
        "Kết quả %d/%d": "Výsledek %d/%d",
        "0 kết quả": "0 výsledků",
        "Không đọc được PDF «%@»": "PDF «%@» nelze přečíst",
        "PDF này có mật khẩu — chưa mở được nội dung": "Toto PDF je chráněno heslem — k obsahu nelze přistoupit",
        "Không thấy «%@» trong tài liệu": "«%@» nebylo v dokumentu nalezeno",
        "Đã bôi vàng": "Zvýrazněno",
        "Đã gạch chân": "Podtrženo",
        "Hãy bôi đen một đoạn chữ trước": "Nejprve vyberte úsek textu",
        "Đã thêm ghi chú": "Poznámka přidána",
        "Trang này chưa có chú thích nào": "Tato stránka nemá žádné poznámky",
        "Đã bỏ %d chú thích trên trang này": "Z této stránky odstraněna %d {one=poznámka|few=poznámky|other=poznámek}",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Toto PDF nemá textovou vrstvu — nejspíš jde o sken",
        "Không ghi được tệp": "Soubor se nepodařilo zapsat",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Zapsaný soubor se NEOTEVŘE správně — tuto verzi nepoužívejte",
        "Đã lưu %@ · %d trang": "Uloženo %@ · %d {one=stránka|few=stránky|other=stránek}",
        "Tên": "Název",
        "Kích thước": "Velikost",
        "Đã nén": "Komprimováno",
        "Tỉ lệ": "Poměr",
        "Sửa lúc": "Změněno",
        "Mở mục đang chọn": "Otevřít vybranou položku",
        "Bung ra thư mục…": "Rozbalit do složky…",
        "Bung vào đây": "Rozbalit sem",
        "%d mục": "%d {one=položka|few=položky|other=položek}",
        "giải nén ra %@": "rozbaleno do %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— uvnitř souboru Office je archiv; toto jsou jeho části",
        "Đã bung %d mục": "Rozbalena %d {one=položka|few=položky|other=položek}",
        "%d mục hỏng": "%d {one=položka poškozena|few=položky poškozeny|other=položek poškozeno}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=položka ODMÍTNUTA|few=položky ODMÍTNUTY|other=položek ODMÍTNUTO}, protože jejich cesty vedou mimo cílovou složku",
        "Không mở được mục này": "Tuto položku nelze otevřít",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Do %@ zatím nelze zapisovat přímo — použijte «Uložit jako…»",
        "Không có gì đổi": "Nic se nezměnilo",
        "Đã ghi %d ô vào %@": "Zapsána %1$d {one=buňka|few=buňky|other=buněk} do %2$@",
        "Đã ghi %d đoạn vào %@": "Zapsán %1$d {one=odstavec|few=odstavce|other=odstavců} do %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Do souboru se nepodařilo zapsat — originál zůstává nedotčen",
        "dựng bài": "připravit testovací případ",
        "Không ghi được settings.json": "settings.json nelze zapsat",
        "Xoay trái": "Otočit doleva",
        "Xoay phải": "Otočit doprava",
        "Trang lên": "Posunout stránku nahoru",
        "Trang xuống": "Posunout stránku dolů",
        "Xoá trang…": "Smazat stránky…",
        "Xoá trang": "Smazat stránky",
        "Trích trang…": "Extrahovat stránky…",
        "Trích trang ra tệp mới": "Extrahovat stránky do nového souboru",
        "Gộp tệp PDF…": "Sloučit soubor PDF…",
        "Tách tệp…": "Rozdělit soubor…",
        "Tách tệp PDF": "Rozdělit soubor PDF",
        "Xuất ảnh…": "Exportovat obrázky…",
        "Xuất trang ra ảnh PNG": "Exportovat stránky jako obrázky PNG",
        "Hoàn tác trang": "Zpět úpravu stránky",
        "Lưu bản đã sửa…": "Uložit upravenou kopii…",
        "Phát": "Přehrát",
        "Tạm dừng": "Pozastavit",
        "Xem bình thường": "Normální zobrazení",
        "Chọn sheet": "Vybrat list",
        "Mở sheet": "Otevřít list",
        "Bỏ và đổi sheet": "Zahodit a přepnout list",
        "Bảng tính có %d sheet.": "Sešit má %d listů.",
        "Bảng tính này chỉ có một sheet: «%@»": "Tento sešit má jen jeden list: „%@“",
        "Bỏ phần chưa lưu của sheet này?": "Zahodit neuložené změny v tomto listu?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Přepnutí listu nahradí celou kartu. Co není uloženo pomocí ⌘S, bude ztraceno.",
        "Chọn tệp PDF cần gộp vào": "Vyberte soubor PDF ke sloučení",
        "Chọn thư mục ghi ảnh": "Vyberte složku pro obrázky",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Vyberte místo uložení. Druhý soubor se zapíše vedle tohoto.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Dokument má %d stránek. Zadejte stránky ke smazání, např. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Dokument má %d stránek. Zadejte stránky k extrahování, např. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Dokument má %d stránek. Zadejte stránky k exportu, např. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Dokument má %d stránek. Zadejte část k oddělení, např. 1-5; zbytek se uloží jako druhý soubor.",
        "Đã xoay trang %d": "Stránka %d otočena",
        "Đã xoá trang %@ · còn %d trang": "Stránky %@ smazány · zbývá %d stránek",
        "Đã gộp %d trang từ «%@»": "Sloučeno %d stránek z „%@“",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Rozděleno na %@ (%d stránek) a %@ (%d stránek)",
        "Đã ghi %@ — %@ · %d trang": "Zapsáno %@ — %@ · %d stránek",
        "Đã xuất %d ảnh vào %@": "Exportováno %d obrázků do %@",
        "Chỉ xuất được %d/%d ảnh": "Exportováno jen %d z %d obrázků",
        "Đã hoàn tác một thao tác trang": "Jedna operace se stránkou byla vrácena zpět",
        "Không còn thao tác trang nào để hoàn tác": "Žádná operace se stránkou ke vrácení",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Nelze smazat VŠECHNY stránky — PDF musí mít alespoň jednu",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Tento rozsah je celý dokument — není co oddělit",
        "«%@» có mật khẩu — chưa gộp được": "„%@“ je chráněn heslem — nelze sloučit",
        "«%@» không có trang nào": "„%@“ nemá žádné stránky",
        "Đã ở trang đầu": "Již na první stránce",
        "Đã ở trang cuối": "Již na poslední stránce",
        "· đã sửa, chưa lưu": "· upraveno, neuloženo",
        "Ảnh động · %d khung": "Animovaný obrázek · %d snímků",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Neuložený dokument — na disku není soubor pro binární zobrazení",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Tento příkaz funguje jen se sešity Excelu",
        "Không đọc được danh sách sheet": "Seznam listů se nepodařilo přečíst",
        "Không có sheet «%@»": "List „%@“ neexistuje",
        "Không đọc được sheet «%@»": "List „%@“ se nepodařilo přečíst",
        "Sheet «%@» · %d hàng": "List „%@“ · %d řádků",
        "phần còn lại": "zbytek",
        "Lưu ý": "Poznámka",
        "Cẩn thận": "Pozor",
        "Xem thêm": "Viz také",
        "Chép": "Kopírovat",
        "Đã chép": "Zkopírováno",
        "Chép đoạn mã mẫu": "Zkopírovat ukázkový kód",
        "Tìm trong trợ giúp": "Hledat v nápovědě",
        "Lùi": "Zpět",
        "Bắt đầu dùng": "Začít",
        "Không mở cửa sổ này khi khởi động nữa": "Nezobrazovat toto okno při spuštění",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Nápověda zatím není přeložena do tohoto jazyka — zobrazuje se vietnamsky.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Přejít na offset (např. 1F400 nebo 0x1F400)",
        "Chép dòng đã chọn": "Kopírovat vybrané řádky",
        "Đã chép %d dòng": "Zkopírováno %d řádků",
        "Không đọc được «%@»": "„%@“ se nepodařilo přečíst",
        "Tệp rỗng": "Prázdný soubor",
        "Không đọc được offset «%@»": "Offset „%@“ se nepodařilo přečíst",
        "Offset 0x%@ vượt quá cỡ tệp": "Offset 0x%@ přesahuje velikost souboru",
        "Mở bằng ứng dụng khác…": "Otevřít v jiné aplikaci…",
        "%d kênh": "%d kanálů",
        "Không phát được «%@»": "„%@“ nelze přehrát",
        "Không phát được — %@": "Nelze přehrát — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS nemá vestavěný dekodér pro formát %@ — jde o omezení systému, ne o poškozený soubor.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Bajty si stále můžete prohlédnout v binárním zobrazení nebo soubor otevřít v aplikaci s vlastním dekodérem.",
        "Ký…": "Podepsat…",
        "Sửa chữ…": "Upravit text…",
        "Sửa chữ": "Upravit text",
        "Vẽ đè": "Přemalovat",
        "Ô chưa điền": "Další prázdné pole",
        "Xoá nội dung đã điền": "Vymazat vyplněné hodnoty",
        "Tệp này không có ô biểu mẫu nào": "Tento soubor nemá formulářová pole",
        "Đã xoá nội dung của %d ô biểu mẫu": "Vymazáno %d formulářových polí",
        "Mọi ô biểu mẫu đều đã có nội dung": "Všechna formulářová pole jsou už vyplněná",
        "Còn %d ô chưa điền": "Zbývá %d prázdných polí",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Vyplnitelný formulář: %d polí. Pište přímo do nich a pak zvolte „Uložit upravenou kopii…“",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Vyberte obrázek podpisu (nejlépe s průhledným pozadím)",
        "Không dựng được trang có chữ ký": "Podepsanou stránku se nepodařilo vytvořit",
        "Đã chèn chữ ký vào trang %d": "Podpis vložen na stránku %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Nejprve vyberte text, který chcete změnit",
        "Vùng chọn quá nhỏ": "Výběr je příliš malý",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Nový text se KRESLÍ PŘES výběr systémovým písmem. Starý text je zakrytý, ne odstraněný — stále jde získat, takže nejde o začernění.",
        "Không dựng được trang đã sửa": "Upravenou stránku se nepodařilo vytvořit",
        "Đã vẽ đè chữ mới lên trang %d": "Nový text nakreslen přes stránku %d",
        "Đổi chế độ View / Code": "Přepnout Zobrazení / Kód",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Stromové zobrazení pro JSON · XML · YAML zatím není",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Zobrazení diagramu v kartě zatím není",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Zobrazení osnovy pro PowerPoint zatím není",
        "Tệp này chỉ có một chế độ hiển thị": "Tento soubor má jen jeden režim zobrazení",
        "%d nút": "%d uzlů",
        "Không dựng được cây: %@": "Strom se nepodařilo sestavit: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Dokument je příliš velký pro strom — použijte režim Kód",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Stránky tohoto souboru se nepodařilo sestavit \u{2014} použijte režim Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Snímky jsou sestaveny z textu; původní obrázky a rozvržení zatím nekreslíme.",
        "Vừa ngang": "Na šířku",
        "Thu nhỏ trang": "Zmenšit stránku",
        "Phóng to trang": "Zvětšit stránku",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "V dokumentu se nepodařilo najít „%@“",
        "Chỗ khớp %d/%d": "Shoda %d z %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Na stránce není vybrán žádný text.",
        "%d ký tự": "%d {one=znak|few=znaky|other=znaků}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Otevírat soubory rovnou v režimu View, pokud jej mají",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· ZRUŠENO v půli — tabulka je neúplná",
        "Chế độ hiển thị": "Režim zobrazení",
        "Đổi giữa View và Code (⌥⌘V)": "Přepnout mezi View a Code (⌥⌘V)",
        "Trang tài liệu": "Stránky dokumentu",
        "Chữ đã dựng": "Vysázený text",
        "Trang bảng tính": "Stránky sešitu",
        "Sơ đồ": "Diagram",
        "Cây khoá–giá trị": "Strom klíč–hodnota",
        "Bộ phát": "Přehrávač",
        "Danh sách mục": "Seznam položek",
        "Báo cáo đã dựng": "Hotová zpráva",
        "Tô theo mức": "Obarveno podle úrovně",
        "Trang slide": "Stránky snímků",
        "Dàn ý": "Osnova",
        "Lưu rồi dựng lại": "Uložit a znovu sestavit",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Ukazuje kopii NA DISKU — neuložené úpravy tu nejsou.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Systém nedokázal sestavit prohlížeč dokumentu — použijte režim Code.",
        "Lưu tệp trước khi xem trang.": "Uložte soubor, než se podíváte na jeho stránky.",
        "Đang ở chế độ Code": "Nyní v režimu Code",
        "Đang ở chế độ View": "Nyní v režimu View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Vidíte zdrojový text — klepnutím přejdete do režimu View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "Režim View — klepnutím se vrátíte ke zdrojovému textu (⌥⌘V)",
        "Tín hiệu: %@": "Signál: %@",
        "Lý do: %@": "Důvod: %@",
        "Chi tiết: %@": "Podrobnost: %@",
        "Mở báo cáo": "Otevřít zprávu",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor nečekaně skončil v %@ — zprávu si otevřete a přečtěte; nic se nikam neodesílá.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligatury — vypnuté, každý znak zůstane ve své buňce",
        "Chế độ CSV": "Režim CSV",
        "Dấu phân tách": "Oddělovač",
        "Tự nhận diện": "Rozpoznat automaticky",
        "Dấu phân tách: %@": "Oddělovač: %@",
        "Theo đuôi tệp": "Podle přípony souboru",
        "%d dấu cách": "%d {one=mezera|few=mezery|other=mezer}",
        "Tài liệu đang sửa được": "Tento dokument lze upravovat",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Jen pro čtení: soubor je sledován — sledování zastavte, abyste mohli upravovat",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Jen pro čtení: do souboru na disku nelze zapisovat",
        "Đã mở khoá — tài liệu sửa được": "Odemčeno — dokument lze zase upravovat",
        "Nhân bản tệp": "Duplikovat soubor",
        "Đổi tên tệp…": "Přejmenovat soubor…",
        "Chuyển tệp tới…": "Přesunout soubor do…",
        "XML: đánh giá XPath…": "XML: vyhodnotit XPath…",
        "Đánh giá XPath": "Vyhodnotit XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Například: //objednavka/radek[2]/@kod · //*[@druh='A'] · count(//radek)",
        "Đánh giá": "Vyhodnotit",
        "XPath không đọc được: %@": "Tento XPath nelze přečíst: %@",
        "XPath «%@» không khớp node nào": "XPath „%@“ nenašel žádný uzel",
        "XPath «%@» — %d node": "XPath „%@“ — %d {one=uzel|few=uzly|other=uzlů}",
        "XPath «%@»: %d node": "XPath „%@“: %d {one=uzel|few=uzly|other=uzlů}",
        "Lưu tệp trước khi nhân bản.": "Uložte soubor, než jej zduplikujete.",
        "Không nhân bản được": "Duplikace se nezdařila",
        "Đã nhân bản thành %@": "Zduplikováno jako %@",
        "Lưu tệp trước khi đổi tên.": "Uložte soubor, než jej přejmenujete.",
        "Đổi tên tệp": "Přejmenovat soubor",
        "Tên hiện tại: %@": "Současný název: %@",
        "Đổi tên": "Přejmenovat",
        "Tên tệp không hợp lệ": "Tento název souboru není platný",
        "Đã có tệp tên %@ ở đó": "Takový soubor s názvem %@ tam už je",
        "Lưu tệp trước khi chuyển.": "Uložte soubor, než jej přesunete.",
        "Chuyển tới": "Přesunout sem",
        "Thư mục đích đã có tệp tên %@": "Cílová složka už má soubor s názvem %@",
        "Không chuyển được tệp": "Soubor se nepodařilo přesunout",
        "Đã chuyển tới %@": "Přesunuto do %@",
        "Bảng mã:": "Kódování:",
        "Xuống dòng:": "Konce řádků:",
        "Riêng cho %@": "Jen pro %@",
        "    %d — dùng TAB": "    %d — tabulátory",
        "    %d — dùng dấu cách": "    %d — mezery",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Odebrat vlastní pravidlo, použít obecné nastavení",
        "%@: thụt lề %d %@": "%@: odsazení %d %@",
        "TAB": "tabulátory",
        "dấu cách": "mezery",
        "Xuất": "Exportovat",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Otevřít výsledky jako textový panel — uložte přes ⌘S",
        "Lượt tìm trước đó": "Dřívější hledání",
        "«%@» — %d kết quả": "„%@“ — %d {one=výsledek|few=výsledky|other=výsledků}",
        "Kết quả tìm «%@»": "Výsledky hledání „%@“",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtr názvů — např. *.csv;*.log (prázdné: každý textový soubor)",
        "Thư mục %@ không có file văn bản nào": "Složka %@ nemá textové soubory",
        "Không tệp nào trong %@ khớp «%@»": "Žádný soubor v %@ neodpovídá „%@“",
        "%d byte · %d dòng": "%d bajtů · %d {one=řádek|few=řádky|other=řádků}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d bajtů · %d {one=řádek|few=řádky|other=řádků} — příliš velký na počítání znaků a slov",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d bajtů · %d {one=znak|few=znaky|other=znaků} · %d {one=slovo|few=slova|other=slov} · %d {one=řádek|few=řádky|other=řádků}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Tento dokument má %d {one=řádek|few=řádky|other=řádků}, %d bajtů. Zadejte číslo řádku, „řádek,sloupec“ nebo „@bajt“.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "„%@“ nelze přečíst — zadejte číslo řádku, „řádek,sloupec“ nebo „@bajt“",
    ]
}
