import Foundation

/// Bảng dịch tiếng Nhật. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let ja: [String: String] = [
        "Bản đã lưu…": "保存済みのバージョン…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "この書類は一度も保存されていません — 履歴がありません",
        "Chưa có bản đã lưu nào trước đó": "以前の保存済みバージョンはありません",
        "Không đọc được bản ấy": "そのバージョンを読み込めません",
        "Khôi phục bản đã lưu": "保存済みバージョンを復元",
        "XML: kiểm theo DTD/XSD…": "XML：DTD/XSD で検証…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "この Mac には libxml2 がないため、XSD 検証は利用できません。",
        "Chọn lược đồ XSD để kiểm": "検証に使う XSD スキーマを選択",
        "Hợp lệ theo": "適合：",
        "Plugin chạy xong, không đổi gì": "プラグインは何も変更せずに終了しました",
        "Chưa cài plugin native nào": "ネイティブプラグインはインストールされていません",
        "Gỡ plugin này": "このプラグインを削除",
        "Gỡ plugin này?": "このプラグインを削除しますか？",
        "Gỡ": "削除",
        "Cài plugin native…": "ネイティブプラグインをインストール…",
        "Mở thư mục plugin": "プラグインフォルダを開く",
        "Chọn file .dylib của plugin native": "プラグインの .dylib ファイルを選択",
        "Đã cài:": "インストール済み：",
        "Đã gỡ:": "削除しました：",
        "Plugin native…": "ネイティブプラグイン…",
        "Chỉ nhận file .dylib.": ".dylib ファイルのみ受け付けます。",
        "Đã có một plugin trùng tên:": "同じ名前のプラグインがすでにあります：",
        "Không chép được plugin:": "プラグインをコピーできません：",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "ネイティブプラグインは直接ダウンロード版のみで、App Store 版にはありません。",
        "Không tìm thấy tiến trình phụ chạy plugin.": "プラグイン用の補助プロセスが見つかりません。",
        "Không khởi động được tiến trình phụ:": "補助プロセスを起動できません：",
        "Tiến trình plugin đã dừng giữa chừng.": "プラグインのプロセスが途中で停止しました。",
        "Plugin không trả lời kịp — đã dừng nó.": "プラグインが時間内に応答しなかったため停止しました。",
        "Plugin trả lời sai giao thức:": "プラグインが不正な形式のメッセージを返しました：",
        "Plugin báo lỗi:": "プラグインがエラーを報告しました：",
        "Về GEditor": "GEditor について",
        "Cài đặt…": "設定…",
        "Thoát GEditor": "GEditor を終了",
        "File": "ファイル",
        "Tab mới": "新規タブ",
        "Đóng tab": "タブを閉じる",
        "Tab kế": "次のタブ",
        "Tab trước": "前のタブ",
        "Tài liệu mới": "新規書類",
        "Mở…": "開く…",
        "Mở thư mục làm Workspace…": "フォルダをワークスペースとして開く…",
        "Mở gần đây": "最近使った項目を開く",
        "Lưu": "保存",
        "Lưu thành…": "別名で保存…",
        "Cắt khoảng trắng cuối dòng khi lưu": "保存時に行末の空白を削除",
        "Theo dõi file (tail -f)": "ファイルを追跡（tail -f）",
        "In…": "プリント…",
        "Mở lại tab vừa đóng": "閉じたタブを開き直す",
        "Chưa có file nào": "ファイルがありません",
        "Xoá danh sách": "リストを消去",
        "Edit": "編集",
        "Hoàn tác": "取り消す",
        "Làm lại": "やり直す",
        "Cắt": "カット",
        "Sao chép": "コピー",
        "Dán": "ペースト",
        "Lịch sử clipboard…": "クリップボードの履歴…",
        "Column Editor…": "カラムエディタ…",
        "Chọn lần kế tiếp": "次の一致を選択",
        "Chọn tất cả": "すべてを選択",
        "Nhân đôi dòng": "行を複製",
        "Xóa dòng": "行を削除",
        "Comment dòng": "行をコメントアウト",
        "Chưa chép gì trong phiên này": "このセッションでは何もコピーしていません",
        "Xoá lịch sử": "履歴を消去",
        "Search": "検索",
        "Tìm…": "検索…",
        "Tìm và thay…": "検索と置換…",
        "Tìm trong thư mục…": "フォルダ内を検索…",
        "Thay trong thư mục…": "フォルダ内で置換…",
        "Kết quả kế": "次の結果",
        "Kết quả trước": "前の結果",
        "Đi tới dòng…": "指定行へ移動…",
        "Nhảy tới ngoặc khớp": "対応する括弧へ移動",
        "Đánh dấu mọi dòng khớp…": "一致するすべての行にマークを付ける…",
        "Đảo dấu": "マークを反転",
        "Bỏ mọi dấu": "すべてのマークを解除",
        "Chép dòng đã đánh dấu": "マークした行をコピー",
        "Xóa dòng đã đánh dấu": "マークした行を削除",
        "Chỉ giữ dòng đã đánh dấu": "マークした行だけを残す",
        "Lines": "行",
        "Sắp xếp A→Z": "昇順に並べ替え",
        "Sắp xếp Z→A": "降順に並べ替え",
        "Sắp xếp tự nhiên": "自然順に並べ替え",
        "Khử trùng lặp": "重複を削除",
        "Đảo thứ tự dòng": "行の順序を反転",
        "Dời dòng lên": "行を上へ移動",
        "Dời dòng xuống": "行を下へ移動",
        "Ghép dòng": "行を連結",
        "Tách dòng theo độ dài…": "長さで行を分割…",
        "Tách dòng theo ký tự…": "文字で行を分割…",
        "Xóa dòng rỗng": "空行を削除",
        "Nén dòng trống liên tiếp": "連続する空行をまとめる",
        "Cắt khoảng trắng cuối dòng": "行末の空白を削除",
        "Tab → Space": "Tab → スペース",
        "Space → Tab": "スペース → Tab",
        "HOA": "大文字",
        "thường": "小文字",
        "Chữ Hoa Đầu Từ": "各単語の先頭を大文字",
        "Chữ hoa đầu câu": "文頭を大文字",
        "Đảo hoa/thường": "大文字と小文字を反転",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: シートを選択…",
        "Xem dạng bảng / văn bản": "表 / テキスト表示を切り替え",
        "Xóa cột…": "列を削除…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "データを検証（列数 · 型）",
        "Bàn làm sạch dữ liệu…": "データクリーニング作業台…",
        "Chạy công thức làm sạch…": "クリーニングレシピを実行…",
        "Chuyển đổi…": "変換…",
        "Đổi dấu phân tách…": "区切り文字を変更…",
        "Xuất sang JSON…": "JSON に書き出す…",
        "Format": "フォーマット",
        "Bảng mã…": "エンコーディング…",
        "Xuống dòng…": "改行コード…",
        "Chuẩn hóa Unicode…": "Unicode を正規化…",
        "JSON: định dạng lại": "JSON：整形",
        "JSON: thu gọn một dòng": "JSON：1 行に圧縮",
        "JSON: sắp xếp khóa": "JSON：キーを並べ替え",
        "JSON: truy vấn JSONPath…": "JSON：JSONPath クエリ…",
        "CSV: truy vấn SQL…": "CSV：SQL クエリ…",
        "Truy vấn SQL": "SQL クエリ",
        "Đang chạy…": "実行中…",
        "Xuất ra tab mới": "新規タブに書き出す",
        "Tài liệu rỗng — không có bảng để truy vấn": "書類が空です — クエリ対象の表がありません",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "CSV の表ではありません — 先頭行に列が 1 つしかありません",
        "Không đọc được câu truy vấn": "クエリを読み取れません",
        "Không kiểm được câu truy vấn": "クエリを検査できません",
        "Vàng (mặc định)": "黄（デフォルト）",
        "Xanh dương": "青",
        "Xanh lá": "緑",
        "Vàng đất": "黄土色",
        "Tím": "紫",
        "Hồng": "ピンク",
        "Xanh ngọc": "ターコイズ",
        "Cam": "オレンジ",
        "Xám lam": "スレート",
        "Văn bản": "テキスト",
        "Dãy số": "数値の連番",
        "Dãy ngày": "日付の連番",
        "Chữ HOA (hex)": "大文字（16 進）",
        "Bắt đầu": "開始",
        "Bước": "ステップ",
        "Đệm 0 tới": "ゼロ埋めの桁数",
        "Hệ": "基数",
        "Ngày đầu": "最初の日付",
        "Định dạng": "フォーマット",
        "Chèn": "挿入",
        "Huỷ": "キャンセル",
        "Chuyển đổi định dạng": "フォーマットを変換",
        "Xem trước 5 hàng đầu": "先頭 5 行をプレビュー",
        "Tạo tab mới": "新規タブで開く",
        "Lưu ra file…": "ファイルに保存…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "結果は未保存の新規タブで開きます。元の書類はそのままです。",
        "Chạy trên tài liệu này": "この書類に対して実行",
        "Chạy trên thư mục…": "フォルダに対して実行…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "レシピ全体で取り消し 1 回分です。保存するまでディスク上のファイルは変わりません。",
        "tắt": "オフ",
        "không thấy cột": "列が見つかりません",
        "sẵn sàng": "準備完了",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "アプリを終了するまで CPU コアを 1 つ占有し続けます。",
        "Script không trả về gì": "スクリプトは何も返しませんでした",
        "Không dựng được máy JavaScript": "JavaScript エンジンを作成できません",
        "Lỗi JavaScript không rõ": "不明な JavaScript エラー",
        "Bảng": "表",
        "Áp sắp xếp vào file": "並べ替えをファイルに適用",
        "Chuyển đổi ▾": "変換 ▾",
        "Xuất dòng khớp": "一致した行を書き出す",
        "Ẩn cột này": "この列を隠す",
        "Đổi tên tiêu đề…": "見出しの名前を変更…",
        "Chèn cột trống bên trái": "左に空の列を挿入",
        "Chèn cột trống bên phải": "右に空の列を挿入",
        "Xóa cột này khỏi file…": "この列をファイルから削除…",
        "Phải còn ít nhất một cột đang hiện": "少なくとも 1 列は表示したままにする必要があります",
        "Đang sắp xếp…": "並べ替え中…",
        "Trở về thứ tự trong file": "ファイル内の順序に戻す",
        "trăm hàng đầu": "先頭 100 行",
        "chọn cột": "列を選ぶ",
        "đặt tên cột kết quả": "結果の列に名前を付ける",
        "lọc theo chữ": "テキストで絞り込む",
        "ô rỗng": "空のセル",
        "ghép điều kiện": "条件を組み合わせる",
        "đếm hàng": "行数を数える",
        "gộp nhóm": "グループ化して集計する",
        "nhỏ nhất, lớn nhất": "最小値、最大値",
        "sắp xếp và cắt": "並べ替えて件数を絞る",
        "tên cột có dấu cách": "空白を含む列名",
        "Truy vấn bị dừng giữa chừng": "クエリが中断されました",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "未対応：JOIN · サブクエリ · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · ウインドウ関数",
        "XML: định dạng lại": "XML：整形",
        "XML: thu gọn một dòng": "XML：1 行に圧縮",
        "XML: kiểm cú pháp": "XML：構文を検査",
        "YAML: kiểm khóa trùng và thụt lề": "YAML：重複キーとインデントを検査",
        "View": "表示",
        "Ẩn/hiện sidebar (Function List)": "サイドバー（関数リスト）を表示/非表示",
        "Ẩn/hiện bản đồ tài liệu": "書類マップを表示/非表示",
        "Gấp / mở khối tại con nháy": "カーソル位置のブロックを折りたたむ / 展開する",
        "Gấp tất cả": "すべて折りたたむ",
        "Bỏ gấp tất cả": "すべて展開する",
        "Gấp theo cấp": "レベルで折りたたむ",
        "Cấp %d": "レベル %d",
        "Đã gấp %d khối ở cấp %d": "レベル %2$d で %1$d 個のブロックを折りたたみました",
        "Tài liệu này chỉ sâu %d cấp": "この書類の深さは %d レベルしかありません",
        "mermaid: không đọc được bản kê": "mermaid：マニフェストを読み取れません",
        "Kiểm tra bản cập nhật…": "アップデートを確認…",
        "Kiểm tra bản cập nhật": "アップデートを確認",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store 版は GEditor ではなく Mac App Store 経由で更新されます。",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "このビルドにはアップデート用の署名鍵がないため、確認できません。",
        "Phóng to chữ": "文字を大きく",
        "Thu nhỏ chữ": "文字を小さく",
        "Cỡ chữ gốc": "実際のサイズ",
        "Chia đôi theo chiều dọc": "上下に分割",
        "Chia đôi theo chiều ngang": "左右に分割",
        "Bỏ chia đôi": "分割を解除",
        "Mở tab này ở nửa kia": "このタブをもう一方のペインで開く",
        "Nhảy sang nửa kia": "もう一方のペインへ移動",
        "Ngắt dòng (tắt / cửa sổ / cột)": "行の折り返し（オフ / ウインドウ / 桁）",
        "Ngắt dòng tại cột…": "指定桁で折り返す…",
        "Đánh dấu dòng này": "この行にマークを付ける",
        "Dấu kế tiếp": "次のマーク",
        "Dấu trước đó": "前のマーク",
        "Màu đánh dấu…": "マークの色…",
        "Hiện tất cả ký tự ẩn": "不可視文字をすべて表示",
        "  Khoảng trắng": "  スペース",
        "  Tab": "  タブ",
        "  Xuống dòng": "  改行",
        "  NBSP · zero-width · điều khiển": "  NBSP · ゼロ幅 · 制御文字",
        "Xem nhị phân": "バイナリ表示",
        "Chế độ CSV (tô màu theo cột)": "CSV モード（列ごとに色分け）",
        "Macro": "マクロ",
        "Bắt đầu / dừng ghi": "記録を開始 / 停止",
        "Phát lại": "再生",
        "Phát nhiều lần…": "複数回再生…",
        "Phát đến cuối tài liệu": "書類の末尾まで再生",
        "Chạy trên mọi tab": "すべてのタブで実行",
        "Hủy macro đang chạy": "実行中のマクロを中止",
        "Lưu macro…": "マクロを保存…",
        "Macro đã lưu…": "保存したマクロ…",
        "Help": "ヘルプ",
        "Trợ giúp GEditor": "GEditor ヘルプ",
        "Giới thiệu tính năng": "機能の紹介",
        "Di cư từ Notepad++": "Notepad++ からの移行",
        "Tìm": "検索",
        "Thay bằng": "置換後",
        "Kế": "次へ",
        "Trước": "前へ",
        "Đếm": "カウント",
        "Đóng": "閉じる",
        "Kiểm theo JSON Schema…": "JSON スキーマで検証…",
        "Chọn tệp JSON Schema": "JSON スキーマファイルを選択",
        "Không thấy lỗi nào theo schema này.": "このスキーマに照らして問題は見つかりませんでした。",
        "JSON Schema": "JSON スキーマ",
        "Kiểm cú pháp đồ thị": "グラフの構文を検査",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "グラフの形式を認識できません — .dot、.gv、.cypher、.ttl、.graphml のいずれかの拡張子が必要です。",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "%@ の構文エラーは見つかりませんでした（この検査は網羅的ではありません）。",
        "Cú pháp %@": "%@ の構文",
        "không phải một đối tượng JSON": "JSON オブジェクトではありません",
        "Khai phá văn bản (n-gram, TF-IDF)": "テキストマイニング（n-gram、TF-IDF）",
        "Tài liệu rỗng.": "書類が空です。",
        "Không rút được từ khoá nào.": "キーワードを抽出できませんでした。",
        "Từ khoá": "キーワード",
        "%d từ khoá · %d token · %d tài liệu": "キーワード %d 個 · トークン %d 個 · 書類 %d 件",
        "Tô lên tài liệu": "書類上にマークする",
        "Đánh dấu entity từ danh sách…": "リストからエンティティをマーク…",
        "Chọn danh sách entity (CSV hoặc JSON)": "エンティティのリストを選択（CSV または JSON）",
        "Không đọc được danh sách entity.": "エンティティのリストを読み取れません。",
        "Danh sách entity rỗng.": "エンティティのリストが空です。",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "書類内にエンティティが見つかりません（%d 件読み込み済み）。",
        "%d lần xuất hiện · %@": "%d 件の出現 · %@",
        "Chuyển đổi tri thức…": "知識を変換…",
        "Chuyển đổi: %@ → %@": "変換：%@ → %@",
        "Không chuyển đổi được.": "変換できませんでした。",
        "Xem trước cắt chunk…": "チャンク分割のプレビュー…",
        "Cỡ cố định 800B, chồng 100B": "固定サイズ 800 B、重なり 100 B",
        "Theo câu (≤ 800B)": "文単位（≤ 800 B）",
        "Theo heading Markdown": "Markdown の見出し単位",
        "Tài liệu rỗng — không có chunk nào.": "書類が空です — チャンクがありません。",
        "%d chunk · trung bình %d B · %@": "チャンク %d 個 · 平均 %d B · %@",
        "Xuất JSONL": "JSONL を書き出す",
        "Chunk JSONL": "チャンク JSONL",
        "Mở triple/edge dạng bảng": "トリプル/エッジを表として開く",
        "Bảng triple": "トリプルの表",
        "Tài liệu này không có dòng triple nào.": "この書類にはトリプルの行がありません。",
        "Không đọc được triple nào — dòng %d: %@": "トリプルを 1 件も読み取れませんでした — %d 行目：%@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "トリプルを %1$d 件読み取り · 不正な %2$d 行をスキップ（最初：%3$d 行目）",
        "Trùng lặp mờ theo cột…": "列ごとのあいまい重複…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "あいまい重複 — 列「%1$@」：候補グループ %2$d 件",
        "Gộp": "統合",
        "Giống": "一致",
        "Các giá trị trong cụm": "グループ内の値",
        "Gộp về": "統合先",
        "Gộp các cụm đã chọn": "選択したグループを統合",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "グループが 1 つも選択されていません — 「統合」を押しても何も変わりません。アプリが勝手に統合することはありません。",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d 件のグループを選択 · %d 行が変更されます · 取り消し 1 回分",
        "Không quét được cột này.": "この列をスキャンできませんでした。",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "列「%@」にあいまい重複のグループはありません。",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "グループは 1 つも統合されませんでした — 書類は変わりません。",
        "Khử trùng lặp mờ · cột %@": "あいまい重複の除去 · 列 %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d 件のグループを統合 · %d 個のセルが変更されました",
        "Báo cáo làm sạch": "クリーニングレポート",
        "# Báo cáo làm sạch — %@\n\n": "# クリーニングレポート — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## 適用済み（%d）\n\n",
        "_Chưa áp dụng bước nào._\n": "_適用された手順はありません。_\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## データのプロファイル\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d 列 · %2$d 行 · %3$.1f 秒でスキャン_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| 列 | 型 | NULL | 一意 | 最小 | 最大 | 平均 |\n",
        "\n### Giá trị bất thường\n\n": "\n### 外れ値\n\n",
        "hàng %d: %@": "%d 行目：%@",
        "- cột «%@» — %d ô: %@\n": "- 列「%1$@」— %2$d 個のセル：%3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## 残り（%d）\n\n",
        "_Không còn phát hiện nào._\n": "_残っている指摘はありません。_\n",
        "- cột «%@»: %@\n": "- 列「%@」：%@\n",
        "Cắt khoảng trắng khi lưu": "保存時に空白を削除",
        "Chuẩn hóa xuống dòng": "改行コードを正規化",
        "trước đó": "以前",
        "Không mở lại được thư mục «%@» của phiên trước": "前回のセッションのフォルダ「%@」を開き直せませんでした",
        " (và %d file khác)": "（ほか %d 件のファイル）",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%d 個のタブを開き直せませんでした：%@%@ — ファイルが元の場所にありません。",
        "Không đọc được nội dung từ ống dẫn": "パイプから入力を読み取れませんでした",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "保存のたびに行末の空白を削除します",
        "Không cắt khoảng trắng khi lưu nữa": "保存時に空白を削除しなくなりました",
        "Chưa đặt tên.txt": "名称未設定.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "エンコーディングを変換すると文字が失われます",
        "Vẫn lưu": "それでも保存",
        "Tài liệu có thay đổi chưa lưu": "書類に未保存の変更があります",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "保存せずに閉じると変更は破棄されます。",
        "Bỏ thay đổi": "変更を破棄",
        "Đi tới dòng": "指定行へ移動",
        "Tài liệu có %d dòng.": "この書類は %d 行あります。",
        "Số dòng": "行番号",
        "Đi tới": "移動",
        "Diễn giải lại theo…": "別のエンコーディングとして解釈…",
        "Chuyển đổi sang…": "次に変換…",
        "Không diễn giải lại được": "解釈し直せませんでした",
        "Bảng mã %@ không chứa hết ký tự": "%@ ではすべての文字を表現できません",
        "Vẫn chọn": "それでも選ぶ",
        "Cột %d": "%d 列目",
        "Cột %d: %@": "%d 列目：%@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "隠している列：%@（%d）— 見出し行のコンテキストメニューから戻せます",
        "Hiện lại: %@": "再表示：%@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "列 %@ を隠しました — ファイル内にはそのまま残っています",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "%@ %@ で並べ替え済み · 表示のみ",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "並べ替え済み：%@ %@（表示のみ）",
        "%d+ dòng khớp — đang tìm tiếp…": "%d 行以上が一致 — 検索を続けています…",
        "%d / %d dòng khớp": "%d / %d 行が一致",
        "Không tìm thấy lỗi trong %d hàng": "%d 行に問題は見つかりませんでした",
        "%d hàng lệch số cột": "列数が正しくない行が %d 行",
        "%d ô sai kiểu dữ liệu": "データ型が正しくないセルが %d 個",
        " (đã dừng ở %d lỗi đầu)": "（最初の %d 件の問題で停止しました）",
        "   —   kiểu nhận ra: ": "   —   検出された型：",
        "Hàng %d, cột %@: «%@» không phải %@": "%1$d 行目、列 %2$@：「%3$@」は %4$@ ではありません",
        "Column Editor — %d dòng": "カラムエディタ — %d 行",
        "Phát hiện": "指摘",
        "Hồ sơ dữ liệu": "データのプロファイル",
        "Hồ sơ dữ liệu — đang quét…": "データのプロファイル — スキャン中…",
        "Lưu công thức…": "レシピを保存…",
        "Xuất báo cáo": "レポートを書き出す",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "適用したグループはありません · 各グループが取り消し 1 回分です",
        "quá nhiều giá trị": "値が多すぎます",
        "hay gặp: ": "頻出：",
        "Giá trị điền vào ô thiếu": "空のセルを埋める値",
        "Áp dụng": "適用",
        "Không dựng được bản xem trước": "プレビューを作成できませんでした",
        "· giữ nguyên, không đọc được ·": "· 解釈できないためそのまま ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "列を ISO 8601（YYYY-MM-DD）に変換",
        "Quy ước số cho cả cột": "列全体の数値表記",
        "Làm gì với ô thiếu": "空のセルの扱い",
        "Chuẩn hóa về ISO 8601": "ISO 8601 に正規化",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "あいまいなセルは日を先に読む（31/12）",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "あいまいなセルは月を先に読む（12/31）",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "あいまいなセルは飛ばし、確実なものだけ修正",
        "Về Việt/Âu (1.234,56)": "ベトナム/ヨーロッパ式へ（1.234,56）",
        "Về Anh-Mỹ (1,234.56)": "英米式へ（1,234.56）",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "英米式へ、桁区切りなし（1234.56）",
        "Điền một giá trị mặc định…": "デフォルト値で埋める…",
        "Điền xuôi — lấy giá trị phía trên": "下方向に埋める — 上の値を使う",
        "Điền ngược — lấy giá trị phía dưới": "上方向に埋める — 下の値を使う",
        "Xóa hàng có ô thiếu ở cột này": "この列が空の行を削除",
        "Cắt khoảng trắng hai đầu": "両端の空白を削除",
        "Cắt hai đầu và nén khoảng trắng bên trong": "両端を削除し内部の空白をまとめる",
        "Pivot…": "ピボット…",
        "Nguồn…": "ソース…",
        "Pivot — gộp theo cột": "ピボット — 列でグループ化",
        "Hàng (gộp nhóm)": "行（グループ化）",
        "Giá trị": "値",
        "+ Hàng": "+ 行",
        "+ Giá trị": "+ 値",
        "Xoá hết": "すべて消去",
        "Đưa vào ô truy vấn": "クエリ欄に入れる",
        "Chọn cột để dựng câu truy vấn.": "クエリを組み立てる列を選んでください。",
        "Không đọc được tên cột của bảng này.": "この表の列名を読み取れませんでした。",
        "Nguồn dữ liệu của truy vấn": "クエリのデータソース",
        "«%@» — tài liệu đang mở": "「%@」— 開いている書類",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ 登録後にファイルが変更されています",
        "Thêm file…": "ファイルを追加…",
        "Bỏ hết": "すべて外す",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "「%@」から表名を導き出せません — ファイル名を変更してください。",
        "Tổng": "合計",
        "Trung bình": "平均",
        "Nhỏ nhất": "最小",
        "Lớn nhất": "最大",
        "Đếm khác nhau": "一意な件数",
        "Biểu đồ": "グラフ",
        "Xuất PNG": "PNG を書き出す",
        "Xuất SVG": "SVG を書き出す",
        "Bảng này không có cột số nào để vẽ.": "この表にはグラフにできる数値列がありません。",
        "Không dựng được ảnh PNG.": "PNG 画像を作成できませんでした。",
        "Kết quả truy vấn": "クエリ結果",
        "Đã lưu %@": "%@ を保存しました",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "「%2$@」の %1$@ グラフ — %3$d 点、値は %4$@ から %5$@ まで",
        "Cột": "棒",
        "Đường": "折れ線",
        "Phân bố": "ヒストグラム",
        "Phân tán": "散布図",
        "Hộp": "箱ひげ図",
        "CSV: chất lượng dữ liệu…": "CSV：データ品質…",
        "Chất lượng dữ liệu": "データ品質",
        "Xuất vi phạm ra tab mới": "違反を新規タブに書き出す",
        "Mức": "レベル",
        "Luật": "ルール",
        "Vi phạm": "違反",
        "Tỷ lệ": "割合",
        "đạt": "合格",
        "lỗi": "エラー",
        "cảnh báo": "警告",
        "hỏng": "破損",
        "Đã đánh dấu %d dòng vi phạm": "違反している %d 行にマークを付けました",
        "Xu hướng": "推移",
        "Lúc chấm": "採点日時",
        "Số hàng": "行数",
        "Lệch": "差分",
        "Luật trượt": "不合格のルール",
        "Điểm chất lượng": "品質スコア",
        "Điểm theo thời gian": "スコアの推移",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "履歴はまだありません — 採点するたびに",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "ルールの隣の「.history.jsonl」ファイルに 1 行追加されます。",
        "%d mốc trong lịch sử": "履歴に %d 点",
        " · %d dòng KHÔNG đọc được": " · %d 行が読み取れません",
        " · chọn hai dòng để so": " · 比較する 2 行を選択してください",
        "điểm %+.1f": "スコア %+.1f",
        "không chiều nào tụt": "低下した観点はありません",
        "tụt: ": "低下：",
        "%d luật mới trượt: %@": "新たに不合格になったルールが %d 件：%@",
        "số hàng %+d": "行数 %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": "（「推移」タブにさらに %d 件の警告があります）",
        "Không sửa tự động được: ": "自動修正はできません：",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "クリーニング作業台の対応するツールを開き、その後すぐ採点し直します。",
        "Xử lý giá trị thiếu…": "欠損値を処理…",
        "Chuẩn hóa ngày…": "日付を正規化…",
        "Khử trùng lặp…": "重複を削除…",
        "Thay thế…": "置換…",
        "Xem các dòng sai": "問題のある行を表示",
        "Không tìm thấy cột «%@» trong bảng này.": "この表に列「%@」はありません。",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "重複を削除しました —「%@」は一意になりました。スコア：%.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "重複を削除しましたが、「%1$@」にはまだ %2$d 行の重複があります（以前：%3$d）— ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "それらの行はキーは同じでも行全体は同じではないため、見て選ぶ必要があります",
        "giữ hàng nào.": "どれを残すか。",
        "Không đọc được giá trị nào đang vi phạm luật này.": "このルールに違反している値を読み取れませんでした。",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "列「%2$@」に誤った値が %1$d 件 — 「置換」を入力してプレビューを押してください",
        "Đã chấm lại: %.0f/100": "採点し直しました：%.0f/100",
        "Xem trước báo cáo": "レポートのプレビュー",
        "Tham số…": "パラメータ…",
        "Xuất HTML…": "HTML を書き出す…",
        "In / PDF…": "プリント / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d ブロックを実行 · %d ブロックが失敗",
        "%d khối chạy được": "%d ブロックを実行",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · データが古い — 元ファイルが変更されています。作り直してください",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "レポートのプレビューには .%@ 書類が必要です",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "データソースが見つかりません — frontmatter に「source: ファイル.csv」を宣言してください。",
        "Không dựng được báo cáo.": "レポートを作成できませんでした。",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "このレポートの frontmatter にはパラメータが宣言されていません。",
        "Tham số báo cáo": "レポートのパラメータ",
        "Dựng lại": "作り直す",
        "Đã xuất %@": "%@ を書き出しました",
        "Báo cáo: xem trước": "レポート：プレビュー",
        "Báo cáo: sinh loạt…": "レポート：一括生成…",
        "không phải tài liệu .greport.md": ".greport.md 書類ではありません",
        "không phân tích được báo cáo": "レポートを解析できません",
        "không tìm được dữ liệu nguồn": "元データが見つかりません",
        "không đọc được danh sách tham số": "パラメータのリストを読み取れません",
        "Sinh loạt cần tài liệu đuôi .%@": "一括生成には .%@ 書類が必要です",
        "Chọn danh sách tham số (CSV hoặc JSON)": "パラメータのリストを選択（CSV または JSON）",
        "Chọn thư mục để ghi %d báo cáo": "%d 件のレポートを書き出すフォルダを選択",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "パラメータが不足：",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "元ファイル自身を指しています — 上書きを拒否しました",
        "%d khối HỎNG": "%d ブロックが失敗",
        "Sinh loạt xong: %d tệp · %d hỏng": "一括処理が完了：%d ファイル · %d 件失敗",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d 組のパラメータを作成できませんでした — まとめを確認してください",
        "Sơ đồ Mermaid: xem trước": "Mermaid 図：プレビュー",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid 図：テンプレートを挿入…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid 図：整形し直す",
        "Nền trong suốt": "背景を透明に",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "この Mac では図を PNG にラスタライズできません — macOS 13 が必要です。SVG の書き出しは利用できます。",
        "Lưu PNG %@…": "PNG %@ を保存…",
        "Lưu SVG…": "SVG を保存…",
        "Chép ảnh vào clipboard": "画像をクリップボードにコピー",
        "Màu thương hiệu…": "ブランドカラー…",
        "Màu thương hiệu cho sơ đồ": "図のブランドカラー",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "各項目は #rrggbb 形式の色です。「themes/mermaid-brand.json」に保存されます — 別の Mac にコピーできます。",
        "Màu chính": "メインカラー",
        "Chữ trên nút": "ノード上の文字",
        "Viền": "枠線",
        "Đường nối": "リンク",
        "Nền khi xuất ảnh": "書き出し時の背景",
        "Lưu và chèn %%{init}%% vào tài liệu": "保存して %%{init}%% を書類に挿入",
        "Đã lưu màu thương hiệu": "ブランドカラーを保存しました",
        "Đã chép ảnh sơ đồ vào clipboard": "図の画像をクリップボードにコピーしました",
        "Đã lưu %@ — %@": "%@ を保存しました — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "この図にはすでに %%{init}%% 指定があります — あなたのものはそのままです。",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% を挿入しました — 図が自前の配色を持つようになりました",
        "Chèn màu thương hiệu vào sơ đồ": "図にブランドカラーを挿入",
        "Định dạng sơ đồ Mermaid": "Mermaid 図を整形し直す",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "図のソースはすでに整っています — 変更するところはありません",
        "Đã định dạng lại sơ đồ": "図を整形し直しました",
        "Đã định dạng lại %d sơ đồ": "%d 個の図を整形し直しました",
        "Thư viện mẫu sơ đồ": "図テンプレートのライブラリ",
        "Mẫu sơ đồ đầy đủ": "完全な図テンプレート",
        "Mẩu cú pháp": "構文の断片",
        "Đang soạn: %@": "編集中：%@",
        "Đã chèn mẫu «%@»": "テンプレート「%@」を挿入しました",
        "Tài liệu đang ở chế độ chỉ đọc.": "この書類は読み出し専用です。",
        "Sơ đồ Mermaid": "Mermaid 図",
        "Tài liệu chưa có khối mermaid nào.": "この書類には mermaid ブロックがありません。",
        "Thương hiệu": "ブランド",
        "Xuất…": "書き出す…",
        "Chưa có sơ đồ nào": "図はまだありません",
        "%d sơ đồ · %@": "%d 個の図 · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d 個の図が失敗 — %3$d 番目の図%4$@",
        ", dòng %d": "、%d 行目",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "この書類には ```mermaid ブロックがなく、.mmd ファイルでもありません。",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "描画が完了した図はまだありません。",
        "Không tìm thấy «%@» trong mã sơ đồ": "図のソースに「%@」が見つかりません",
        "không dựng được hàng rào chặn mạng cho WKWebView": "WKWebView 用のネットワーク遮断を構成できませんでした",
        "Luật kết hợp": "アソシエーションルール",
        "Mỗi dòng một giỏ": "1 行につき 1 つのバスケット",
        "Hai cột: mã · item": "2 列：ID · アイテム",
        "Dạng dữ liệu giao dịch": "取引データの形",
        "Cột giỏ hàng hoặc mã giao dịch": "バスケット列または取引 ID 列",
        "Cột item": "アイテム列",
        "Ký tự phân tách item": "アイテムの区切り文字",
        "Support tối thiểu, phần trăm": "最小 support（パーセント）",
        "Confidence tối thiểu, phần trăm": "最小 confidence（パーセント）",
        "Tách bởi:": "区切り：",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "アソシエーションルールの表",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "注意",
        "%d giao dịch · %d item · %d luật": "取引 %d 件 · アイテム %d 個 · ルール %d 件",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — しきい値に達したルールがありません。support か confidence を下げてください",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — 途中で停止しました。表は不完全です",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d 件の取引が両側を含んでいます",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "2 列形式では異なる 2 つの列を選ぶ必要があります。",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "「%3$@」を含む %2$d 件の取引の %1$d 行にマークを付けました",
        "CSV: luật kết hợp…": "CSV：アソシエーションルール…",
        "Khai phá theo nhóm": "グループマイニング",
        "Cột nhóm": "グループ列",
        "Cột giá trị": "値の列",
        "Cột thứ hai cho tương quan": "相関に使う 2 番目の列",
        "Cách xếp hạng": "順位付けの方法",
        "Nhóm theo:": "グループ化：",
        "Giá trị:": "値：",
        "Xếp theo:": "並べ替え：",
        "Bảng xếp hạng nhóm": "グループ順位の表",
        "Nhóm": "グループ",
        "Hàng": "行数",
        "Hàng rào riêng": "個別のしきい値",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r の差",
        "Ghi chú": "メモ",
        "không đo được": "測定できません",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d グループ · 全体の基準相関 %@",
        " · ĐÃ CẮT %d nhóm": " · %d グループを除外",
        "Bảng này không có cột chữ nào để gom nhóm.": "この表にはグループ化に使えるテキスト列がありません。",
        "Bảng này không có cột số nào để khai phá.": "この表にはマイニングに使える数値列がありません。",
        "Đã đánh dấu %d dòng của nhóm «%@»": "グループ「%2$@」の %1$d 行にマークを付けました",
        "CSV: khai phá theo nhóm…": "CSV：グループマイニング…",
        "\u{2194}": "↔",
        "Dự báo": "予測",
        "Cột giá trị theo thời gian": "時系列の値の列",
        "Mô hình dự báo": "予測モデル",
        "Số kỳ dự báo": "予測する期間の数",
        "Kết luận so với baseline": "ベースラインとの比較結果",
        "Mô hình:": "モデル：",
        "Số kỳ:": "期間：",
        "Chu kỳ:": "季節：",
        "tự": "自動",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "季節周期。空欄にすると自動検出します",
        "Bảng giá trị dự báo": "予測値の表",
        "Kỳ": "期",
        "Dải 80%": "80% 区間",
        "Dải 95%": "95% 区間",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "計算できません",
        "Bảng này không có cột số nào để dự báo.": "この表には予測に使える数値列がありません。",
        "Không dựng được dự báo cho cột này.": "この列の予測を作成できませんでした。",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "列「%1$@」には数値が %2$d 個しかありません — 予測には少なくとも 4 個必要です。",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# 系列はファイルの行順どおりに読み取ります — 並べ替えも、時刻列の推定も行いません。\n",
        "Sai số huấn luyện": "学習時の誤差",
        "CSV: dự báo chuỗi thời gian…": "CSV：時系列予測…",
        "Holt-Winters cộng": "Holt-Winters 加法",
        "Holt-Winters nhân": "Holt-Winters 乗法",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "クラスタリングに使う列",
        "Đường cong WCSS": "WCSS 曲線",
        "Phân cụm": "クラスタ",
        "Chuẩn hoá:": "スケーリング：",
        "k:": "k：",
        "eps:": "eps：",
        "minPts:": "minPts：",
        "Chọn ít nhất một cột.": "少なくとも 1 列を選んでください。",
        "Không đủ dữ liệu để dựng đường cong.": "曲線を作るにはデータが足りません。",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "エルボー法は k = %d を示唆します。WCSS は k が増えると必ず下がるので、これは統計的な基準ではなくグラフの読み方のコツです — 曲線を見て、折れがはっきりしているか判断してください。",
        "WCSS theo k": "k ごとの WCSS",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k 距離は eps = %1$@ を示唆します（minPts の既定値は 2 × 列数 = %2$d）。%3$@",
        "Khoảng cách tới hàng xóm thứ k": "k 番目に近い点までの距離",
        "Cần ít nhất 2 cột số để phân cụm.": "クラスタリングには数値列が少なくとも 2 つ必要です。",
        "Cụm theo %@ và %@": "%@ と %@ によるクラスタ",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — クラスタは %d 次元で求めました。図は最初の 2 次元だけを表示しています",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# ノイズ（cluster_id = -1）：%d 行\n",
        "CSV: phân cụm…": "CSV：クラスタリング…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- クラスタ中心（元の単位）---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "相関行列",
        "Phương pháp tương quan": "相関の求め方",
        "Tương quan không hàm ý nhân quả.": "相関は因果を意味しません。",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "最も強い組み合わせ：%1$@ ↔ %2$@ = %3$@（n = %4$d）。セルをクリックすると散布図が見られます。",
        "Không cặp nào đo được.": "測定できる組み合わせがありません。",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@：%3$@（%4$d 行に基づく）",
        "Cần ít nhất 2 cột số để tính tương quan.": "相関を求めるには数値列が少なくとも 2 つ必要です。",
        "Không đọc được cột «%@».": "列「%@」を読み取れませんでした。",
        "CSV: ma trận tương quan…": "CSV：相関行列…",
        "Bất thường": "異常",
        "Danh sách bất thường": "異常の一覧",
        "Cột:": "列：",
        "Cột số cần xét": "調べる数値列",
        "Cách:": "方法：",
        "Phương pháp phát hiện": "検出方法",
        "Phương pháp đã dùng": "使用した方法",
        "Ngưỡng": "しきい値",
        "Đánh dấu": "マーク",
        "Xuất tab mới": "新規タブに書き出す",
        "Dòng": "行",
        "Điểm": "スコア",
        "Vì sao": "理由",
        "nhẹ": "軽度",
        "vừa": "中度",
        "nặng": "重度",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d 行（%.2f%%）",
        "Bảng này không có cột số nào để tìm bất thường.": "この表には異常を探せる数値列がありません。",
        "Đã đánh dấu %d dòng bất thường": "異常な %d 行にマークを付けました",
        "CSV: tìm bất thường…": "CSV：異常を探す…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d 件のルール、すべて合格 · %2$d 行 · %3$.0f ミリ秒",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d 件のエラー · %2$d 件の警告（%3$d 件のルール）· %4$d 行 · %5$.0f ミリ秒",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "先に書類を保存してください — 品質ルールはデータファイルの隣にあります。",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "ルールセットがまだありません。ファイル %@ を作成してから開き直してください。",
        "Lịch sử": "履歴",
        "Câu đã lưu": "保存したクエリ",
        "Lưu câu này…": "このクエリを保存…",
        "Lưu câu truy vấn": "クエリを保存",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "あとで見つけられるよう名前を付けてください。同じ名前は上書きされます。",
        "Ví dụ: Doanh thu theo tỉnh": "例：省ごとの売上",
        "Chưa nhập giá trị cho tham số: %@": "パラメータに値が入力されていません：%@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "承認後にプラグインが変更されています — GEditor は実行を拒否します",
        "Chạy plugin chưa duyệt?": "未承認のプラグインを実行しますか？",
        "Tôi tin file này — chạy": "このファイルを信頼する — 実行",
        "KHÔNG có chữ ký": "署名なし",
        "Chữ ký: %@": "署名：%@",
        "Đường dẫn: %@": "パス：%@",
        "Thay": "置換",
        "Thay tất cả": "すべて置換",
        "Chuỗi thuần": "プレーンテキスト",
        "Extended (\\n \\t \\xNN)": "拡張（\\n \\t \\xNN）",
        "Biểu thức chính quy": "正規表現",
        "Phân biệt hoa thường": "大文字と小文字を区別",
        "Cả từ": "単語単位",
        "Không có kết quả": "結果がありません",
        "Thử biểu thức chính quy…": "正規表現を試す…",
        "Chế độ Log (tô theo mức)": "ログモード（レベルで色分け）",
        "Lọc log theo mức…": "ログをレベルで絞り込む…",
        "Chạy trên cả thư mục…": "フォルダ全体に対して実行…",
        "Lọc qua lệnh ngoài…": "外部コマンドで絞り込む…",
        "Script…": "スクリプト…",
        "Gói mở rộng…": "拡張パッケージ…",
        "Cửa sổ mới": "新規ウインドウ",
        "Tách tab ra cửa sổ mới": "タブを新しいウインドウに分離",
        "Chưa mở thư mục nào": "フォルダが開かれていません",
        "Tìm file trong thư mục": "フォルダ内のファイルを検索",
        "Lọc theo tên": "名前で絞り込む",
        "File mới…": "新規ファイル…",
        "Thư mục mới…": "新規フォルダ…",
        "Đổi tên…": "名前を変更…",
        "Chuyển vào Thùng rác": "ゴミ箱に入れる",
        "Hiện trong Finder": "Finder で表示",
        "Đang đọc cấu trúc tài liệu…": "書類の構造を読み取り中…",
        "file này không có hàm nào": "このファイルには関数がありません",
        "Không có gì khớp": "一致するものがありません",
        "Văn bản thuần": "プレーンテキスト",
        "🔒 Chỉ đọc": "🔒 読み出し専用",
        "Đang theo dõi": "追跡中",
        "ngắt tại cột": "折り返し桁",
        "Cú pháp": "構文",
        "Bấm để chèn vào ô truy vấn": "クリックするとクエリに挿入されます",
        "truy vấn không hợp lệ": "無効なクエリ",
        "khóa `ten` ở gốc": "ルート直下の「名前」キー",
        "khóa có dấu cách": "空白を含むキー",
        "phần tử đầu": "最初の要素",
        "mọi phần tử": "すべての要素",
        "lát cắt": "スライス",
        "hợp nhiều chỉ số": "インデックスの和集合",
        "mọi khóa `gia` ở mọi tầng": "すべての階層の「価格」キー",
        "mọi nút": "すべてのノード",
        "lọc theo số": "数値で絞り込む",
        "lọc theo có mặt": "存在するかで絞り込む",
        "Tới lỗi đầu tiên": "最初のエラーへ移動",
        "Cột doanh_thu là số": "「売上」列は数値です",
        "lọc…": "絞り込み…",
        "Hủy": "キャンセル",
        "Thực hiện thay": "置換を実行",
        "xem trước": "プレビュー",
        "tương tác": "対話的",
        "Soạn thảo": "編集",
        "Giao diện": "インターフェース",
        "Phím tắt": "キーボードショートカット",
        "Cỡ chữ": "文字の大きさ",
        "Bề rộng TAB": "タブ幅",
        "Thụt lề bằng TAB": "タブでインデントする",
        "Tự động thụt lề khi xuống dòng": "改行時に自動でインデントする",
        "Tô mọi kết quả tìm kiếm": "検索結果をすべてハイライトする",
        "Chuẩn hóa về NFC khi lưu": "保存時に NFC へ正規化する",
        "Ngôn ngữ": "言語",
        "Nền": "外観",
        "Theo hệ thống": "システムに合わせる",
        "Sáng": "ライト",
        "Tối": "ダーク",
        "Theme": "テーマ",
        "Dùng preset Notepad++": "Notepad++ のプリセットを使う",
        "Về phím mặc định": "デフォルトのキーに戻す",
        "Mở file cấu hình": "設定ファイルを開く",
        "Xuất theme hiện tại": "現在のテーマを書き出す",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "言語の変更は次回の起動で完全に反映されます。",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "デフォルトのキーは次回の起動で戻ります。",
        "Xem trước Markdown": "Markdown プレビュー",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "プレビューはシステムの Markdown エンジンを使います：表にはまだ対応しておらず、コードブロックの色分けもありません。",
        "Thử biểu thức chính quy": "正規表現を試す",
        "Biểu thức": "式",
        "Văn bản thử": "テスト用テキスト",
        "Kết quả": "結果",
        "Kết quả khớp": "一致",
        "Biểu thức này làm gì": "この式が行うこと",
        "Giải thích biểu thức": "式を説明する",
        "Chế độ tìm kiếm": "検索モード",
        "Kết quả tìm kiếm": "検索結果",
        "Không khớp chỗ nào": "一致するものがありません",
        " (đã cắt bớt)": "（切り詰めました）",
        "Bản đồ tài liệu": "書類マップ",
        "Thanh tab": "タブバー",
        "Hàng tiêu đề cột": "列見出しの行",
        "Không có cột nào": "列がありません",
        "Cây thư mục workspace": "ワークスペースのツリー",
        "Danh sách hàm và lớp": "関数とクラスの一覧",
        "Kết quả tìm trong thư mục": "フォルダ内の検索結果",
        "Bảng dữ liệu CSV": "CSV データ表",
        "Bàn làm sạch dữ liệu": "データクリーニング作業台",
        "Truy vấn JSONPath": "JSONPath クエリ",
        "Danh sách lỗi dữ liệu": "データエラーの一覧",
        "Bộ đánh giá golden set…": "ゴールデンセット評価ツール…",
        "So với điểm ngoài (JSONL)…": "外部スコアと比較（JSONL）…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "外部スコアのファイルを選択（JSONL：query, chunk_id, score）",
        "Đổi tên node đang chọn": "選択中のノードの名前を変更",
        "Gộp các node đang chọn": "選択中のノードを統合",
        "Tách node đang chọn": "選択中のノードを分割",
        "Trích subgraph đang chọn ra tab mới": "選択中の部分グラフを新規タブに取り出す",
        "Không có gì để đổi": "変更するものがありません",
        "%@ — áp %d thay đổi?": "%1$@ — %2$d 件の変更を適用しますか？",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@：%2$d 件の変更 · Cmd-Z でまとめて取り消せます",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "カーソルをちょうど 1 つのノードに置いてからやり直してください",
        "Đổi tên «%@»": "「%@」の名前を変更",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "このノードを参照するすべてのエッジとラベルも一緒に変わります。",
        "Đổi tên node": "ノードの名前を変更",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "2 つ以上のノードを選択してからやり直してください",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "正規形「%@」— 最も多く、最も長く、記号付き",
        "Gộp node": "ノードを統合",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "移動したいエッジの行を選択してからやり直してください",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "選択したすべての行がちょうど 1 つのノードに接している必要があります — エッジの行をさらに選択してください",
        "Tách «%@» — chuyển %d cạnh": "「%1$@」を分割 — %2$d 本のエッジを移動",
        "Cạnh tới: %@": "%@ へのエッジ",
        "Tách node": "ノードを分割",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "書類が未保存です — 取り出したファイルを隣に置く場所が必要です",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "取り出したいグラフの部分を選択してからやり直してください",
        "Gom biến thể entity → bảng duyệt": "エンティティの表記ゆれをまとめる → 確認用の表",
        "Áp bảng duyệt đã sửa": "編集した確認用の表を適用",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "書類が未保存です — 確認用の表はグラフファイルの隣に置く必要があります",
        "Không tìm thấy biến thể nào để gom": "まとめられる表記ゆれが見つかりません",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d 組の表記ゆれ — 「canonical」列を直してから「確認用の表を適用」を実行してください",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "確認用の表「%@」がありません — 先に「エンティティの表記ゆれをまとめる」を実行してください",
        "Bảng duyệt không đọc được: %@": "確認用の表を読み取れません：%@",
        "Bảng duyệt không có dòng nào cần đổi": "確認用の表に変更が必要な行はありません",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "確認用の表に一致する箇所がグラフにありません",
        "Gom biến thể entity": "エンティティの表記ゆれをまとめる",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d 件の変更を適用 · 別名の表とマーカーの一覧をファイルの隣に書き出しました",
        "Áp %d thay đổi lên đồ thị?": "グラフに %d 件の変更を適用しますか？",
        "%d alias → dạng chuẩn.": "%d 件の別名 → 正規形。",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "ノードを統合します（打ち直しでは取り消せません）：",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d 件の別名はグラフに存在しないため、スキップしました。",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "チャンク ↔ エンティティのカバレッジ分析",
        "Xuất gói ngữ cảnh (JSONL)": "コンテキストパックを書き出す（JSONL）",
        "Phủ Chunk ↔ Entity ↔ Graph": "チャンク ↔ エンティティ ↔ グラフ のカバレッジ",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- エンティティ %1$d 件 · チャンク %2$d 件 · エンティティの %3$.0f%% が言及済み · チャンクの %4$.0f%% がエンティティを含む",
        "Entity không chunk nào nhắc tới": "どのチャンクからも言及されていないエンティティ",
        "Chunk mồ côi (không chứa entity nào)": "孤立したチャンク（エンティティを含まない）",
        "Node đồ thị không có entity đối ứng": "対応するエンティティがないグラフノード",
        "không có": "なし",
        "Phương pháp": "方法",
        "Không dựng được ánh xạ Chunk ↔ Entity": "チャンク ↔ エンティティ の対応付けを作成できませんでした",
        "Chấm sức khoẻ đồ thị": "グラフの健全性を評価",
        "sức khoẻ đồ thị": "グラフの健全性",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "健全性 %1$@/100 · エラー %2$d · 反転 %3$d · 孤立 %4$d",
        "Lai với đồ thị": "グラフとのハイブリッド",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1：グラフの信号を完全に無視します。結果は純粋な BM25 と同じです",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α が大きい：グラフは BM25 の順位をわずかに調整するだけです",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α が既定値 0.7 付近：BM25 が主導し、グラフが調整します",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α が小さい：グラフが主導し、BM25 は同点の解消だけに使われます",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0：グラフの信号のみ。エンティティを含まないチャンクは横並びになります",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "書類が未保存です — ハイブリッドにはコーパスの隣にグラフファイルが必要です",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "グラフファイル「%@」が見つかりません — ハイブリッドは信号を得るためにこれを必要とします",
        "lai %.1f ms · %@": "ハイブリッド %.1f ミリ秒 · %@",
        "Thuật toán…": "アルゴリズム…",
        "PageRank (độ dày viền)": "PageRank（枠線の太さ）",
        "Cộng đồng (màu nền)": "コミュニティ（背景色）",
        "Thành phần liên thông": "連結成分",
        "Xuất bảng node ra tab mới": "ノードの表を新規タブに書き出す",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d 個の成分 · 最大は %2$d ノード · 孤立ノード %3$d 個",
        "Tài liệu này không phải đồ thị DOT": "この書類は DOT グラフではありません",
        "Không dựng được bảng node/cạnh: %@": "ノード/エッジの表を作成できませんでした：%@",
        "%d hàng · %@": "%d 行 · %@",
        "Gán nhãn": "ラベル付け",
        "Ghi chú (tuỳ chọn)": "メモ（任意）",
        "Lưu record": "レコードを保存",
        "Xuất CSV": "CSV を書き出す",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "書類が未保存です — 評価ツールはコーパスファイルの隣に置く必要があります",
        "Không nạp được bộ đánh giá: %@": "評価ツールを読み込めませんでした：%@",
        "Không lưu được: %@": "保存できませんでした：%@",
        "Bộ đánh giá chưa có record nào": "評価ツールにはまだレコードがありません",
        "Không ghi được: %@": "書き込めませんでした：%@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "この書類は .mmd ファイルでも DOT でもなく、mermaid ブロックもありません。",
        "%d node · %d cạnh · ⚠ %@": "ノード %d 個 · エッジ %d 本 · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid 図：要素を追加…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid 図：選択した 2 つの要素をつなぐ",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid 図：選択した要素のラベルを変更…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid 図：選択した要素を削除",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid 図：メッセージを上へ",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid 図：メッセージを下へ",
        "Thêm phần tử": "要素を追加",
        "Thêm participant": "参加者を追加",
        "Thêm mục": "項目を追加",
        "Thêm mục sơ đồ": "図に項目を追加",
        "Sửa mục sơ đồ": "図の項目を変更",
        "Xoá mục sơ đồ": "図の項目を削除",
        "Xoá phần tử": "要素を削除",
        "Sửa nhãn": "ラベルを変更",
        "Đổi thứ tự message": "メッセージを並べ替える",
        "Tên mục": "項目の名前",
        "Mục mới": "新しい項目",
        "Tên mục hiện trên sơ đồ.": "項目の名前は図の上に表示されます。",
        "Bảng thuộc tính sơ đồ": "図のプロパティ表",
        "Tài liệu này không có khối mermaid nào": "この書類には mermaid ブロックがありません",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "図のソース内での識別子 — 空白は使えません。ラベルはあとからダブルクリックで変更できます。",
        "Để trống thì hiện chính định danh.": "空欄のままにすると識別子そのものが表示されます。",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "表示されるラベルだけが変わります。要素の識別子はそのままです。",
        "Không rõ «%@» là phần tử nào": "「%@」がどの要素か判別できません",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "ちょうど 2 つの要素を選択してからやり直してください",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "カーソルをちょうど 1 つの要素に置いてからやり直してください",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "削除する要素を 1 つ、またはエッジでつながった 2 つの要素を選んでください",
        "Xoá «%@» và %d cạnh chạm nó?": "「%1$@」と、それに接する %2$d 本のエッジを削除しますか？",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "それらのエッジの反対側にあるノードは残ります — エッジの記述が唯一の宣言だった場合は、ラベルとともに宣言し直されます。",
        "Sơ đồ «%@» chỉ soạn text — %@": "図「%1$@」はテキストとしてのみ編集できます — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@：2 つの要素の間をドラッグするとつながり、ダブルクリックでラベルを変更できます",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@：2 人の参加者の間をドラッグするとメッセージを追加できます。並べ替えは「ツール」メニューから",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@：下のプロパティ表で編集してください",
        "Soạn trực quan đã bật": "ビジュアル編集が有効になりました",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d 項目 — 表で直接編集できます。各セルが取り消し 1 回分です",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "円グラフなら数値、ガントならコロンの後ろの部分です。",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid 図：ブロックを .mmd ファイルに取り出す…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid 図：参照しているファイルを埋め込み直す",
        "Tách khối sơ đồ": "図のブロックを取り出す",
        "Nhúng khối sơ đồ": "図のブロックを埋め込む",
        "Tách khối sơ đồ ra tệp riêng": "図のブロックを別ファイルに取り出す",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "ファイルは書類の隣に置かれます。ブロックには参照の 1 行が残るので、編集は 1 か所で済みます。",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "書類が未保存です — 図のファイルを隣に置く場所が必要です",
        "Đã có tệp «%@» — chọn tên khác": "ファイル「%@」はすでにあります — 別の名前にしてください",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "「%@」に取り出しました — ブロックには参照の 1 行が残っています",
        "Mở tệp": "ファイルを開く",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "「%@」を埋め込み直しました。ファイルはディスク上に残っています",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "このブロックには参照ではなく実際の図が入っています",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "このブロックは「%@」を参照しています — 編集するにはそのファイルを開いてください",
        "Không đọc được tệp sơ đồ %@": "図のファイル %@ を読み取れませんでした",
        "Soạn trực quan": "ビジュアル編集",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "ノードから別のノードへドラッグするとエッジを追加できます。ダブルクリックでラベルを変更できます。操作 1 つが取り消し 1 回分です。",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "ビジュアル編集：2 つのノードの間をドラッグするとエッジを追加、ダブルクリックでラベルを変更",
        "Soạn trực quan đã tắt": "ビジュアル編集が無効になりました",
        "Thêm node…": "ノードを追加…",
        "Thêm cạnh giữa hai node đang chọn…": "選択した 2 つのノードの間にエッジを追加…",
        "Sửa nhãn node đang chọn…": "選択したノードのラベルを変更…",
        "Xoá node/cạnh đang chọn": "選択したノード/エッジを削除",
        "Thêm node": "ノードを追加",
        "Thêm cạnh": "エッジを追加",
        "Sửa nhãn node": "ノードのラベルを変更",
        "Xoá node": "ノードを削除",
        "Xoá cạnh": "エッジを削除",
        "Cmd-Z hoàn tác": "Cmd-Z で取り消し",
        "Tài liệu đang ở chế độ chỉ đọc": "この書類は読み出し専用です",
        "Nhãn của «%@»": "「%@」のラベル",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "表示されるラベルだけが変わります。ノードの識別子はそのままです。",
        "Không rõ «%@» là node nào": "「%@」がどのノードか判別できません",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "DOT ファイル内のノード識別子。ラベルはあとから図の上でダブルクリックして変更できます。",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "ちょうど 2 つのノードを選択してからやり直してください",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "削除するノードを 1 つ、またはエッジでつながった 2 つのノードを選んでください",
        "Xoá node «%@» và %d cạnh chạm nó?": "ノード「%1$@」と、それに接する %2$d 本のエッジを削除しますか？",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "宙に浮いたエッジが残ると、DOT はそこからノードを作り直します — 削除したノードは次の描画で再び現れます。",
        "Phòng thí nghiệm truy hồi BM25": "BM25 検索ラボ",
        "Câu hỏi — Enter để tìm": "質問 — Enter で検索",
        "Đánh giá…": "評価…",
        "Đang dựng chỉ mục": "インデックスを作成中",
        "Không chunk nào khớp": "一致するチャンクがありません",
        "kết quả trên": "件の上位結果",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0：各語は何回出現しても 1 回しか数えません",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 が小さい：語を繰り返してもスコアはほとんど増えません",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 が既定値 1.2 付近：繰り返しでスコアは増えますが、増え方は次第に小さくなります",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 が大きい：同じ語を何度も繰り返すチャンクが強く優遇されます",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0：長さを無視します。長いチャンクにペナルティはありません",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b が小さい：長いチャンクへのペナルティはわずかです",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b が既定値 0.75 付近：長いチャンクに中程度のペナルティがかかります",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1：長さによるペナルティが最大になり、短いチャンクが有利になります",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL：検索ラボ…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "書類が未保存です — BM25 インデックスはコーパスファイルの隣に置かれるためパスが必要です",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "このファイルは JSONL ではありません — Retrieval Lab はチャンクのコーパス上で動きます",
        "Không dựng được chỉ mục BM25 cho tệp này": "このファイルの BM25 インデックスを作成できませんでした",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "書類が未保存です — レポートの生成にはコーパスのパスが必要です",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "評価セットを選択（CSV または JSONL：質問 + 期待するチャンク ID）",
        "Đánh giá truy hồi": "検索の評価",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "上の k1、b、k を変えてから見直すと 2 つの設定を比較できます。「compare」ブロックを追加すると、同じ評価セットで 2 組のパラメータを並行して実行できます。",
        "Lỗi": "エラー",
        "   (%d…%d, trung bình %.0f)": "   （%d…%d、平均 %.0f）",
        "Chế độ JSONL": "JSONL モード",
        "Bản ghi": "レコード",
        "Chi tiết": "詳細",
        "Bản ghi ở dòng": "行のレコード",
        "không phải JSON hợp lệ": "有効な JSON ではありません",
        "bản ghi": "件のレコード",
        "dòng trắng": "空行",
        "không phải đối tượng": "オブジェクトではありません",
        "bảng hiện": "表示中の表",
        "ĐÃ HUỶ giữa chừng": "途中で中止しました",
        "Không lọc": "絞り込みなし",
        "bản ghi khớp bộ lọc": "件のレコードが条件に一致",
        "Đưa con nháy tới một dòng để xem bản ghi": "行にカーソルを置くとレコードが見られます",
        "Không có bản ghi nào hỏng": "壊れたレコードはありません",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "まだ調べていません。検証のあと「JSONL：チャンクを調べる」を実行し直してください。",
        "trường văn bản": "テキストのフィールド",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "スキーマ（推定 — 別のフィールドを選ぶと変わります）",
        "văn bản": "テキスト",
        "định danh": "識別子",
        "metadata lồng": "入れ子のメタデータ",
        "TRƯỜNG": "フィールド",
        "phủ": "カバレッジ",
        "nhiều kiểu": "複数の型",
        "ĐỘ DÀI — ký tự": "長さ — 文字",
        "ĐỘ DÀI — từ": "長さ — 単語",
        "ĐỘ DÀI — token ước lượng": "長さ — 推定トークン",
        "RỖNG VÀ TRÙNG": "空と重複",
        "chunk rỗng": "件の空チャンク",
        "dòng": "行",
        "nhóm trùng chính xác": "組の完全重複",
        "dòng không đọc được, không vào thống kê": "行は読み取れず、統計から除外",
        "PHƯƠNG PHÁP": "方法",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "「文字」は Unicode の文字（スカラー）で数えます。表示上のまとまりではありません",
        "«từ» tách theo khoảng trắng ASCII": "「単語」は ASCII の空白で区切ります",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "「トークン」は音節分割器で数えます — モデルの分割器ではありません",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "「重複」は完全一致の重複です。ほぼ重複は ```quality ブロックにあります",
        "chunk": "件のチャンク",
        "JSONL: kiểm và soi chunk…": "JSONL：チャンクを検証して調べる…",
        "Ảnh": "画像",
        "PDF": "PDF",
        "Tài liệu Word": "Word 書類",
        "Bảng tính Excel": "Excel スプレッドシート",
        "Bản trình chiếu PowerPoint": "PowerPoint プレゼンテーション",
        "File nén": "アーカイブ",
        "Vừa khung": "ウインドウに合わせる",
        "Chép ảnh": "画像をコピー",
        "Xoay": "回転",
        "Không đọc được ảnh «%@»": "画像「%@」を読み取れません",
        "Đã chép ảnh vào clipboard": "画像をクリップボードにコピーしました",
        "Bôi vàng": "黄色でハイライト",
        "Gạch chân": "下線",
        "Ghi chú…": "メモ…",
        "Bỏ chú thích": "注釈を削除",
        "Lấy chữ ra tab mới": "テキストを新規タブに取り出す",
        "Lưu bản có chú thích…": "注釈付きの版を保存…",
        "Tìm trong PDF": "PDF 内を検索",
        "Thêm": "追加",
        "Trang %d/%d": "%d/%d ページ",
        "Trang %d": "%d ページ",
        "Kết quả %d/%d": "%d/%d 件目",
        "0 kết quả": "0 件",
        "Không đọc được PDF «%@»": "PDF「%@」を読み取れません",
        "PDF này có mật khẩu — chưa mở được nội dung": "この PDF はパスワードで保護されています — 内容にアクセスできません",
        "Không thấy «%@» trong tài liệu": "書類内に「%@」が見つかりません",
        "Đã bôi vàng": "ハイライトしました",
        "Đã gạch chân": "下線を引きました",
        "Hãy bôi đen một đoạn chữ trước": "先にテキストを選択してください",
        "Đã thêm ghi chú": "メモを追加しました",
        "Trang này chưa có chú thích nào": "このページには注釈がありません",
        "Đã bỏ %d chú thích trên trang này": "このページから %d 件の注釈を削除しました",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "この PDF にはテキスト層がありません — おそらくスキャン画像です",
        "Không ghi được tệp": "ファイルに書き込めませんでした",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "書き出したファイルは正しく開き直せません — この版は使わないでください",
        "Đã lưu %@ · %d trang": "%@ を保存しました · %d ページ",
        "Tên": "名前",
        "Kích thước": "サイズ",
        "Đã nén": "圧縮後",
        "Tỉ lệ": "圧縮率",
        "Sửa lúc": "変更日時",
        "Mở mục đang chọn": "選択中の項目を開く",
        "Bung ra thư mục…": "フォルダに展開…",
        "Bung vào đây": "ここに展開",
        "%d mục": "%d 項目",
        "giải nén ra %@": "%@ に展開しました",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— Office ファイルの中身はアーカイブです。これがその構成要素です",
        "Đã bung %d mục": "%d 項目を展開しました",
        "%d mục hỏng": "%d 項目が壊れています",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d 項目は、パスが展開先フォルダの外へ出るため拒否しました",
        "Không mở được mục này": "この項目を開けません",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "%@ にはまだ直接書き戻せません — 「別名で保存…」を使ってください",
        "Không có gì đổi": "何も変わりませんでした",
        "Đã ghi %d ô vào %@": "%2$@ に %1$d 個のセルを書き込みました",
        "Đã ghi %d đoạn vào %@": "%2$@ に %1$d 個の段落を書き込みました",
        "Không ghi được vào tệp — bản gốc còn nguyên": "ファイルに書き込めませんでした — 元のファイルはそのままです",
        "dựng bài": "テストケースを用意",
        "Không ghi được settings.json": "settings.json に書き込めません",
        "Xoay trái": "左に回転",
        "Xoay phải": "右に回転",
        "Trang lên": "ページを上へ",
        "Trang xuống": "ページを下へ",
        "Xoá trang…": "ページを削除…",
        "Xoá trang": "ページを削除",
        "Trích trang…": "ページを抽出…",
        "Trích trang ra tệp mới": "ページを新規ファイルに抽出",
        "Gộp tệp PDF…": "PDF ファイルを結合…",
        "Tách tệp…": "ファイルを分割…",
        "Tách tệp PDF": "PDF ファイルを分割",
        "Xuất ảnh…": "画像を書き出し…",
        "Xuất trang ra ảnh PNG": "ページを PNG 画像として書き出し",
        "Hoàn tác trang": "ページ操作を取り消す",
        "Lưu bản đã sửa…": "編集したコピーを保存…",
        "Phát": "再生",
        "Tạm dừng": "一時停止",
        "Xem bình thường": "通常表示",
        "Chọn sheet": "シートを選択",
        "Mở sheet": "シートを開く",
        "Bỏ và đổi sheet": "破棄してシートを切り替え",
        "Bảng tính có %d sheet.": "ブックには %d 個のシートがあります。",
        "Bảng tính này chỉ có một sheet: «%@»": "このブックにはシートが 1 つだけです：「%@」",
        "Bỏ phần chưa lưu của sheet này?": "このシートの未保存の変更を破棄しますか？",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "シートを切り替えるとタブ全体が置き換わります。⌘S で保存していない内容は失われます。",
        "Chọn tệp PDF cần gộp vào": "結合する PDF ファイルを選択",
        "Chọn thư mục ghi ảnh": "画像の保存先フォルダを選択",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "保存場所を選択します。2 つめのファイルはこの隣に書き出されます。",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "この書類は %d ページです。削除するページを入力してください（例：2-4,7）",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "この書類は %d ページです。抽出するページを入力してください（例：1-3,8）",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "この書類は %d ページです。書き出すページを入力してください（例：1-3）",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "この書類は %d ページです。切り出す範囲を入力してください（例：1-5）。残りは 2 つめのファイルになります。",
        "Đã xoay trang %d": "%d ページを回転しました",
        "Đã xoá trang %@ · còn %d trang": "%@ ページを削除しました · 残り %d ページ",
        "Đã gộp %d trang từ «%@»": "「%2$@」から %1$d ページを結合しました",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "%@（%d ページ）と %@（%d ページ）に分割しました",
        "Đã ghi %@ — %@ · %d trang": "%@ を書き出しました — %@ · %d ページ",
        "Đã xuất %d ảnh vào %@": "%d 枚の画像を %@ に書き出しました",
        "Chỉ xuất được %d/%d ảnh": "%d/%d 枚の画像しか書き出せませんでした",
        "Đã hoàn tác một thao tác trang": "ページ操作を 1 つ取り消しました",
        "Không còn thao tác trang nào để hoàn tác": "取り消せるページ操作はもうありません",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "すべてのページは削除できません — PDF には最低 1 ページ必要です",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "その範囲は書類全体です — 切り出すものがありません",
        "«%@» có mật khẩu — chưa gộp được": "「%@」はパスワードで保護されています — 結合できません",
        "«%@» không có trang nào": "「%@」にはページがありません",
        "Đã ở trang đầu": "すでに最初のページです",
        "Đã ở trang cuối": "すでに最後のページです",
        "· đã sửa, chưa lưu": "· 編集済み・未保存",
        "Ảnh động · %d khung": "アニメーション画像 · %d フレーム",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "未保存の書類です — バイナリ表示できるファイルがディスク上にありません",
        "Lệnh này chỉ dùng cho bảng tính Excel": "このコマンドは Excel ブックでのみ使えます",
        "Không đọc được danh sách sheet": "シート一覧を読み込めませんでした",
        "Không có sheet «%@»": "「%@」というシートはありません",
        "Không đọc được sheet «%@»": "シート「%@」を読み込めませんでした",
        "Sheet «%@» · %d hàng": "シート「%@」· %d 行",
        "phần còn lại": "残りの部分",
        "Lưu ý": "メモ",
        "Cẩn thận": "注意",
        "Xem thêm": "関連項目",
        "Chép": "コピー",
        "Đã chép": "コピーしました",
        "Chép đoạn mã mẫu": "サンプルコードをコピー",
        "Tìm trong trợ giúp": "ヘルプを検索",
        "Lùi": "戻る",
        "Bắt đầu dùng": "使ってみる",
        "Không mở cửa sổ này khi khởi động nữa": "起動時にこのウインドウを表示しない",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "ヘルプはこの言語にまだ翻訳されていません — ベトナム語で表示しています。",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "オフセットへ移動（例：1F400 または 0x1F400）",
        "Chép dòng đã chọn": "選択した行をコピー",
        "Đã chép %d dòng": "%d 行をコピーしました",
        "Không đọc được «%@»": "「%@」を読み込めませんでした",
        "Tệp rỗng": "空のファイル",
        "Không đọc được offset «%@»": "オフセット「%@」を読み取れませんでした",
        "Offset 0x%@ vượt quá cỡ tệp": "オフセット 0x%@ はファイルサイズを超えています",
        "Mở bằng ứng dụng khác…": "別のアプリケーションで開く…",
        "%d kênh": "%d チャンネル",
        "Không phát được «%@»": "「%@」を再生できません",
        "Không phát được — %@": "再生できません — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS には %@ 形式のデコーダーが内蔵されていません — ファイルの破損ではなく OS の制限です。",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "バイナリ表示でバイト列を見ることはできます。独自のデコーダーを持つアプリで開くこともできます。",
        "Ký…": "署名…",
        "Sửa chữ…": "文字を編集…",
        "Sửa chữ": "文字を編集",
        "Vẽ đè": "上に描く",
        "Ô chưa điền": "次の空欄",
        "Xoá nội dung đã điền": "入力内容を消去",
        "Tệp này không có ô biểu mẫu nào": "このファイルにフォーム欄はありません",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d 個のフォーム欄を消去しました",
        "Mọi ô biểu mẫu đều đã có nội dung": "すべてのフォーム欄が入力済みです",
        "Còn %d ô chưa điền": "未入力の欄が %d 個あります",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "入力可能なフォーム：%d 欄。直接入力してから「編集したコピーを保存…」",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "署名画像を選択（背景が透明だときれいです）",
        "Không dựng được trang có chữ ký": "署名済みページを作成できませんでした",
        "Đã chèn chữ ký vào trang %d": "%d ページに署名を挿入しました",
        "Hãy bôi chọn phần chữ cần sửa trước": "先に変更したい文字を選択してください",
        "Vùng chọn quá nhỏ": "選択範囲が小さすぎます",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "新しい文字はシステムフォントで選択範囲の上に描かれます。古い文字は隠れるだけで削除されません — 抽出できるため、黒塗りにはなりません。",
        "Không dựng được trang đã sửa": "編集済みページを作成できませんでした",
        "Đã vẽ đè chữ mới lên trang %d": "%d ページに新しい文字を描きました",
        "Đổi chế độ View / Code": "ビュー / コードを切り替え",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "JSON · XML · YAML のツリービューはまだありません",
        "Chưa có chế độ View dạng sơ đồ trong tab": "タブ内の図ビューはまだありません",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "PowerPoint のアウトラインビューはまだありません",
        "Tệp này chỉ có một chế độ hiển thị": "このファイルには表示モードが 1 つしかありません",
        "%d nút": "%d ノード",
        "Không dựng được cây: %@": "ツリーを構築できませんでした：%@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "書類が大きすぎてツリーを作れません — コードモードを使ってください",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "このファイルのページを組み立てられませんでした \u{2014} コードモードを使ってください。",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "スライドは文字から組み立てています。元の画像とレイアウトはまだ描いていません。",
        "Vừa ngang": "幅に合わせる",
        "Thu nhỏ trang": "ページを縮小",
        "Phóng to trang": "ページを拡大",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "この書類に「%@」は見つかりません",
        "Chỗ khớp %d/%d": "%d 件目 / %d 件",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "ページで文字を選んでいません。",
        "%d ký tự": "%d 文字",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có": "View がある書類は最初から View で開く",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· 途中でキャンセル — 表は不完全です",
        "Chế độ hiển thị": "表示モード",
        "Đổi giữa View và Code (⌥⌘V)": "View と Code を切り替え（⌥⌘V）",
        "Trang tài liệu": "書類のページ",
        "Chữ đã dựng": "組版された文字",
        "Trang bảng tính": "表計算のページ",
        "Sơ đồ": "図",
        "Cây khoá–giá trị": "キーと値のツリー",
        "Bộ phát": "プレーヤー",
        "Danh sách mục": "項目一覧",
        "Báo cáo đã dựng": "組み上がったレポート",
        "Tô theo mức": "レベルで色分け",
        "Trang slide": "スライドのページ",
        "Dàn ý": "アウトライン",
        "Lưu rồi dựng lại": "保存して組み直す",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "ディスク上の内容を表示中 — 未保存の変更は含まれません。",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "システムが書類ビューを構築できませんでした — Code モードをお使いください。",
        "Lưu tệp trước khi xem trang.": "ページを見る前にファイルを保存してください。",
        "Đang ở chế độ Code": "現在 Code モード",
        "Đang ở chế độ View": "現在 View モード",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "ソースを表示中 — クリックで View モードへ（⌥⌘V）",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "View モード — クリックでソースへ戻る（⌥⌘V）",
        "Tín hiệu: %@": "シグナル: %@",
        "Lý do: %@": "理由: %@",
        "Chi tiết: %@": "詳細: %@",
        "Mở báo cáo": "レポートを開く",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor が %@ に予期せず終了しました — レポートを開いてお読みください。何も送信されません。",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "合字 — オフにすると各文字が 1 マスに収まります",
        "Chế độ CSV": "CSV モード",
        "Dấu phân tách": "区切り文字",
        "Tự nhận diện": "自動で判別",
        "Dấu phân tách: %@": "区切り文字: %@",
        "Theo đuôi tệp": "拡張子に従う",
        "%d dấu cách": "%d 個のスペース",
        "Tài liệu đang sửa được": "この書類は編集できます",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "ファイルを追跡中のため読み取り専用です — 編集するには追跡を停止してください",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "ディスク上のファイルが書き込み不可のため読み取り専用です",
        "Đã mở khoá — tài liệu sửa được": "ロック解除 — 書類を再び編集できます",
        "Nhân bản tệp": "ファイルを複製",
        "Đổi tên tệp…": "ファイル名を変更…",
        "Chuyển tệp tới…": "ファイルの移動先…",
        "XML: đánh giá XPath…": "XML: XPath を評価…",
        "Đánh giá XPath": "XPath を評価",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "例: //order/item[2]/@code · //*[@kind='A'] · count(//item)",
        "Đánh giá": "評価",
        "XPath không đọc được: %@": "この XPath は読み取れません: %@",
        "XPath «%@» không khớp node nào": "XPath「%@」に一致するノードはありません",
        "XPath «%@» — %d node": "XPath「%@」— %d 個のノード",
        "XPath «%@»: %d node": "XPath「%@」: %d 個のノード",
        "Lưu tệp trước khi nhân bản.": "複製する前にファイルを保存してください。",
        "Không nhân bản được": "複製できませんでした",
        "Đã nhân bản thành %@": "%@ として複製しました",
        "Lưu tệp trước khi đổi tên.": "名前を変更する前にファイルを保存してください。",
        "Đổi tên tệp": "ファイル名を変更",
        "Tên hiện tại: %@": "現在の名前: %@",
        "Đổi tên": "名前を変更",
        "Tên tệp không hợp lệ": "そのファイル名は使えません",
        "Đã có tệp tên %@ ở đó": "そこには既に %@ という名前のファイルがあります",
        "Lưu tệp trước khi chuyển.": "移動する前にファイルを保存してください。",
        "Chuyển tới": "ここへ移動",
        "Thư mục đích đã có tệp tên %@": "移動先のフォルダには既に %@ という名前のファイルがあります",
        "Không chuyển được tệp": "ファイルを移動できませんでした",
        "Đã chuyển tới %@": "%@ へ移動しました",
        "Bảng mã:": "文字コード:",
        "Xuống dòng:": "改行:",
        "Riêng cho %@": "%@ 専用",
        "    %d — dùng TAB": "    %d — タブを使う",
        "    %d — dùng dấu cách": "    %d — スペースを使う",
        "    Bỏ khai riêng, dùng cài đặt chung": "    個別設定を削除して全体設定を使う",
        "%@: thụt lề %d %@": "%@: インデント %d %@",
        "TAB": "タブ",
        "dấu cách": "スペース",
        "Xuất": "書き出す",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "結果をテキストのタブとして開く — ⌘S で保存",
        "Lượt tìm trước đó": "以前の検索",
        "«%@» — %d kết quả": "「%@」— %d 件",
        "Kết quả tìm «%@»": "「%@」の検索結果",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "ファイル名で絞り込み — 例 *.csv;*.log（空欄: すべてのテキストファイル）",
        "Thư mục %@ không có file văn bản nào": "フォルダ %@ にテキストファイルはありません",
        "Không tệp nào trong %@ khớp «%@»": "%@ の中に「%@」に一致するファイルはありません",
        "%d byte · %d dòng": "%d バイト · %d 行",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d バイト · %d 行 — 大きすぎて文字数と単語数を数えられません",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d バイト · %d 文字 · %d 単語 · %d 行",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "この書類は %d 行、%d バイトです。行番号、「行,列」、または「@バイト」を入力してください。",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "「%@」は読み取れません — 行番号、「行,列」、または「@バイト」を入力してください",
    ]
}
