import Foundation

/// Bảng dịch tiếng Phần Lan. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let fi: [String: String] = [
        "Bản đã lưu…": "Tallennetut versiot…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Tätä dokumenttia ei ole koskaan tallennettu — ei historiaa",
        "Chưa có bản đã lưu nào trước đó": "Ei aiempia tallennettuja versioita",
        "Không đọc được bản ấy": "Tuota versiota ei voi lukea",
        "Khôi phục bản đã lưu": "Palauta tallennettu versio",
        "XML: kiểm theo DTD/XSD…": "XML: tarkista DTD/XSD:tä vasten…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Tässä Macissa ei ole libxml2:ta, joten XSD-tarkistus ei ole käytettävissä.",
        "Chọn lược đồ XSD để kiểm": "Valitse XSD-skeema tarkistusta varten",
        "Hợp lệ theo": "Kelpaa seuraavan mukaan:",
        "Plugin chạy xong, không đổi gì": "Liitännäinen päättyi muuttamatta mitään",
        "Chưa cài plugin native nào": "Natiiveja liitännäisiä ei ole asennettu",
        "Gỡ plugin này": "Poista tämä liitännäinen",
        "Gỡ plugin này?": "Poistetaanko tämä liitännäinen?",
        "Gỡ": "Poista",
        "Cài plugin native…": "Asenna natiivi liitännäinen…",
        "Mở thư mục plugin": "Avaa liitännäisten kansio",
        "Chọn file .dylib của plugin native": "Valitse liitännäisen .dylib-tiedosto",
        "Đã cài:": "Asennettu:",
        "Đã gỡ:": "Poistettu:",
        "Plugin native…": "Natiivit liitännäiset…",
        "Chỉ nhận file .dylib.": "Vain .dylib-tiedostot kelpaavat.",
        "Đã có một plugin trùng tên:": "Samanniminen liitännäinen on jo asennettu:",
        "Không chép được plugin:": "Liitännäistä ei voi kopioida:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Natiivit liitännäiset ovat vain suoraan ladattavassa versiossa, eivät App Store -versiossa.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Liitännäisten apuprosessia ei löytynyt.",
        "Không khởi động được tiến trình phụ:": "Apuprosessia ei voi käynnistää:",
        "Tiến trình plugin đã dừng giữa chừng.": "Liitännäisen prosessi pysähtyi kesken.",
        "Plugin không trả lời kịp — đã dừng nó.": "Liitännäinen ei vastannut ajoissa — se pysäytettiin.",
        "Plugin trả lời sai giao thức:": "Liitännäinen lähetti virheellisen viestin:",
        "Plugin báo lỗi:": "Liitännäinen ilmoitti virheestä:",
        "Về GEditor": "Tietoja GEditorista",
        "Cài đặt…": "Asetukset…",
        "Thoát GEditor": "Lopeta GEditor",
        "File": "Arkisto",
        "Tab mới": "Uusi välilehti",
        "Đóng tab": "Sulje välilehti",
        "Tab kế": "Seuraava välilehti",
        "Tab trước": "Edellinen välilehti",
        "Tài liệu mới": "Uusi dokumentti",
        "Mở…": "Avaa…",
        "Mở thư mục làm Workspace…": "Avaa kansio työtilaksi…",
        "Mở gần đây": "Avaa viimeaikaiset",
        "Lưu": "Tallenna",
        "Lưu thành…": "Tallenna nimellä…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Poista rivin lopun välilyönnit tallennettaessa",
        "Theo dõi file (tail -f)": "Seuraa tiedostoa (tail -f)",
        "In…": "Tulosta…",
        "Mở lại tab vừa đóng": "Avaa suljettu välilehti uudelleen",
        "Chưa có file nào": "Ei tiedostoja",
        "Xoá danh sách": "Tyhjennä luettelo",
        "Edit": "Muokkaa",
        "Hoàn tác": "Kumoa",
        "Làm lại": "Tee uudelleen",
        "Cắt": "Leikkaa",
        "Sao chép": "Kopioi",
        "Dán": "Sijoita",
        "Lịch sử clipboard…": "Leikepöydän historia…",
        "Column Editor…": "Sarakemuokkain…",
        "Chọn lần kế tiếp": "Valitse seuraava osuma",
        "Chọn tất cả": "Valitse kaikki",
        "Nhân đôi dòng": "Kahdenna rivi",
        "Xóa dòng": "Poista rivi",
        "Comment dòng": "Kommentoi rivi pois",
        "Chưa chép gì trong phiên này": "Tässä istunnossa ei ole kopioitu mitään",
        "Xoá lịch sử": "Tyhjennä historia",
        "Search": "Etsi",
        "Tìm…": "Etsi…",
        "Tìm và thay…": "Etsi ja korvaa…",
        "Tìm trong thư mục…": "Etsi kansiosta…",
        "Thay trong thư mục…": "Korvaa kansiossa…",
        "Kết quả kế": "Seuraava tulos",
        "Kết quả trước": "Edellinen tulos",
        "Đi tới dòng…": "Siirry riville…",
        "Nhảy tới ngoặc khớp": "Siirry vastaavaan sulkuun",
        "Đánh dấu mọi dòng khớp…": "Merkitse kaikki osuvat rivit…",
        "Đảo dấu": "Käännä merkinnät",
        "Bỏ mọi dấu": "Poista kaikki merkinnät",
        "Chép dòng đã đánh dấu": "Kopioi merkityt rivit",
        "Xóa dòng đã đánh dấu": "Poista merkityt rivit",
        "Chỉ giữ dòng đã đánh dấu": "Säilytä vain merkityt rivit",
        "Lines": "Rivit",
        "Sắp xếp A→Z": "Lajittele A→Ö",
        "Sắp xếp Z→A": "Lajittele Ö→A",
        "Sắp xếp tự nhiên": "Luonnollinen lajittelu",
        "Khử trùng lặp": "Poista kaksoiskappaleet",
        "Đảo thứ tự dòng": "Käännä rivien järjestys",
        "Dời dòng lên": "Siirrä rivi ylös",
        "Dời dòng xuống": "Siirrä rivi alas",
        "Ghép dòng": "Yhdistä rivit",
        "Tách dòng theo độ dài…": "Jaa rivit pituuden mukaan…",
        "Tách dòng theo ký tự…": "Jaa rivit merkin mukaan…",
        "Xóa dòng rỗng": "Poista tyhjät rivit",
        "Nén dòng trống liên tiếp": "Tiivistä peräkkäiset tyhjät rivit",
        "Cắt khoảng trắng cuối dòng": "Poista rivin lopun välilyönnit",
        "Tab → Space": "Sarkain → välilyönti",
        "Space → Tab": "Välilyönti → sarkain",
        "HOA": "SUURAAKKOSET",
        "thường": "pienaakkoset",
        "Chữ Hoa Đầu Từ": "Iso Alkukirjain Joka Sanassa",
        "Chữ hoa đầu câu": "Iso alkukirjain virkkeessä",
        "Đảo hoa/thường": "kÄÄNNÄ kIRJAINKOKO",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: valitse taulukko…",
        "Xem dạng bảng / văn bản": "Vaihda taulukko- ja tekstinäkymän välillä",
        "Xóa cột…": "Poista sarake…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Tarkista data (sarakkeiden määrä · tyypit)",
        "Bàn làm sạch dữ liệu…": "Datan puhdistuspenkki…",
        "Chạy công thức làm sạch…": "Suorita puhdistusresepti…",
        "Chuyển đổi…": "Muunna…",
        "Đổi dấu phân tách…": "Vaihda erotinmerkki…",
        "Xuất sang JSON…": "Vie JSON-muotoon…",
        "Format": "Muoto",
        "Bảng mã…": "Merkistö…",
        "Xuống dòng…": "Rivinvaihdot…",
        "Chuẩn hóa Unicode…": "Normalisoi Unicode…",
        "JSON: định dạng lại": "JSON: muotoile",
        "JSON: thu gọn một dòng": "JSON: tiivistä yhdelle riville",
        "JSON: sắp xếp khóa": "JSON: lajittele avaimet",
        "JSON: truy vấn JSONPath…": "JSON: JSONPath-kysely…",
        "CSV: truy vấn SQL…": "CSV: SQL-kysely…",
        "Truy vấn SQL": "SQL-kysely",
        "Đang chạy…": "Suoritetaan…",
        "Xuất ra tab mới": "Vie uuteen välilehteen",
        "Tài liệu rỗng — không có bảng để truy vấn": "Tyhjä dokumentti — ei taulukkoa kyseltäväksi",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Ei ole CSV-taulukko — ensimmäisellä rivillä on vain yksi sarake",
        "Không đọc được câu truy vấn": "Kyselyä ei voi lukea",
        "Không kiểm được câu truy vấn": "Kyselyä ei voi tarkistaa",
        "Vàng (mặc định)": "Keltainen (oletus)",
        "Xanh dương": "Sininen",
        "Xanh lá": "Vihreä",
        "Vàng đất": "Okra",
        "Tím": "Violetti",
        "Hồng": "Vaaleanpunainen",
        "Xanh ngọc": "Turkoosi",
        "Cam": "Oranssi",
        "Xám lam": "Liuske",
        "Văn bản": "Teksti",
        "Dãy số": "Lukusarja",
        "Dãy ngày": "Päivämääräsarja",
        "Chữ HOA (hex)": "SUURAAKKOSET (heksadesimaali)",
        "Bắt đầu": "Alku",
        "Bước": "Askel",
        "Đệm 0 tới": "Täytä nollilla pituuteen",
        "Hệ": "Kantaluku",
        "Ngày đầu": "Ensimmäinen päivämäärä",
        "Định dạng": "Muoto",
        "Chèn": "Lisää",
        "Huỷ": "Kumoa",
        "Chuyển đổi định dạng": "Muunna muoto",
        "Xem trước 5 hàng đầu": "Esikatsele 5 ensimmäistä riviä",
        "Tạo tab mới": "Avaa uuteen välilehteen",
        "Lưu ra file…": "Tallenna tiedostoon…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Tulos avautuu uuteen, tallentamattomaan välilehteen. Alkuperäiseen dokumenttiin ei kosketa.",
        "Chạy trên tài liệu này": "Suorita tälle dokumentille",
        "Chạy trên thư mục…": "Suorita kansiolle…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Koko resepti on YKSI kumoamisaskel. Levyllä olevaan tiedostoon ei kosketa ennen kuin tallennat.",
        "tắt": "pois",
        "không thấy cột": "saraketta ei löytynyt",
        "sẵn sàng": "valmis",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "se varaa yhä yhden suoritinytimen, kunnes ohjelma lopetetaan.",
        "Script không trả về gì": "Skripti ei palauttanut mitään",
        "Không dựng được máy JavaScript": "JavaScript-moottoria ei voi luoda",
        "Lỗi JavaScript không rõ": "Tuntematon JavaScript-virhe",
        "Bảng": "Taulukko",
        "Áp sắp xếp vào file": "Käytä lajittelua tiedostoon",
        "Chuyển đổi ▾": "Muunna ▾",
        "Xuất dòng khớp": "Vie osuvat rivit",
        "Ẩn cột này": "Kätke tämä sarake",
        "Đổi tên tiêu đề…": "Nimeä otsikko uudelleen…",
        "Chèn cột trống bên trái": "Lisää tyhjä sarake vasemmalle",
        "Chèn cột trống bên phải": "Lisää tyhjä sarake oikealle",
        "Xóa cột này khỏi file…": "Poista tämä sarake tiedostosta…",
        "Phải còn ít nhất một cột đang hiện": "Vähintään yhden sarakkeen on jäätävä näkyviin",
        "Đang sắp xếp…": "Lajitellaan…",
        "Trở về thứ tự trong file": "Takaisin tiedoston järjestykseen",
        "trăm hàng đầu": "sata ensimmäistä riviä",
        "chọn cột": "sarakkeiden valinta",
        "đặt tên cột kết quả": "tulossarakkeen nimeäminen",
        "lọc theo chữ": "suodatus tekstin mukaan",
        "ô rỗng": "tyhjät solut",
        "ghép điều kiện": "ehtojen yhdistäminen",
        "đếm hàng": "rivien laskeminen",
        "gộp nhóm": "ryhmittely ja koonti",
        "nhỏ nhất, lớn nhất": "pienin, suurin",
        "sắp xếp và cắt": "lajittelu ja rajaus",
        "tên cột có dấu cách": "sarakkeen nimi välilyönnein",
        "Truy vấn bị dừng giữa chừng": "Kysely keskeytettiin",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Ei tueta: JOIN · alikysely · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · ikkunafunktiot",
        "XML: định dạng lại": "XML: muotoile",
        "XML: thu gọn một dòng": "XML: tiivistä yhdelle riville",
        "XML: kiểm cú pháp": "XML: tarkista syntaksi",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: tarkista toistuvat avaimet ja sisennys",
        "View": "Näytä",
        "Ẩn/hiện sidebar (Function List)": "Näytä/kätke sivupalkki (funktioluettelo)",
        "Ẩn/hiện bản đồ tài liệu": "Näytä/kätke dokumenttikartta",
        "Gấp / mở khối tại con nháy": "Laskosta / avaa lohko osoittimen kohdalla",
        "Gấp tất cả": "Laskosta kaikki",
        "Bỏ gấp tất cả": "Avaa kaikki",
        "Gấp theo cấp": "Laskosta tason mukaan",
        "Cấp %d": "Taso %d",
        "Đã gấp %d khối ở cấp %d": "%1$d {one=lohko|other=lohkoa} laskostettu tasolla %2$d",
        "Tài liệu này chỉ sâu %d cấp": "Tämä dokumentti on vain %d {one=taso|other=tasoa} syvä",
        "mermaid: không đọc được bản kê": "mermaid: manifestia ei voi lukea",
        "Kiểm tra bản cập nhật…": "Tarkista päivitykset…",
        "Kiểm tra bản cập nhật": "Tarkista päivitykset",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "App Store -versiot päivittyvät Mac App Storen kautta, eivät GEditorin kautta.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Tässä koosteessa ei ole päivitysten allekirjoitusavainta, joten se ei voi etsiä niitä.",
        "Phóng to chữ": "Suurenna tekstiä",
        "Thu nhỏ chữ": "Pienennä tekstiä",
        "Cỡ chữ gốc": "Todellinen koko",
        "Chia đôi theo chiều dọc": "Jaa pystysuunnassa",
        "Chia đôi theo chiều ngang": "Jaa vaakasuunnassa",
        "Bỏ chia đôi": "Sulje jako",
        "Mở tab này ở nửa kia": "Avaa tämä välilehti toisessa ruudussa",
        "Nhảy sang nửa kia": "Siirry toiseen ruutuun",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Rivitys (pois / ikkuna / sarake)",
        "Ngắt dòng tại cột…": "Rivitä sarakkeen kohdalla…",
        "Đánh dấu dòng này": "Merkitse tämä rivi",
        "Dấu kế tiếp": "Seuraava merkintä",
        "Dấu trước đó": "Edellinen merkintä",
        "Màu đánh dấu…": "Merkintöjen väri…",
        "Hiện tất cả ký tự ẩn": "Näytä kaikki näkymättömät merkit",
        "  Khoảng trắng": "  Välilyönnit",
        "  Tab": "  Sarkaimet",
        "  Xuống dòng": "  Rivinvaihdot",
        "  NBSP · zero-width · điều khiển": "  NBSP · nollalevyinen · ohjausmerkki",
        "Xem nhị phân": "Binäärinäkymä",
        "Chế độ CSV (tô màu theo cột)": "CSV-tila (sarakkeet väreillä)",
        "Macro": "Makro",
        "Bắt đầu / dừng ghi": "Aloita / lopeta tallennus",
        "Phát lại": "Toista",
        "Phát nhiều lần…": "Toista useita kertoja…",
        "Phát đến cuối tài liệu": "Toista dokumentin loppuun",
        "Chạy trên mọi tab": "Suorita kaikissa välilehdissä",
        "Hủy macro đang chạy": "Peru suoritettava makro",
        "Lưu macro…": "Tallenna makro…",
        "Macro đã lưu…": "Tallennetut makrot…",
        "Help": "Ohje",
        "Trợ giúp GEditor": "GEditorin ohje",
        "Giới thiệu tính năng": "Ominaisuuksien esittely",
        "Di cư từ Notepad++": "Siirtyminen Notepad++:sta",
        "Tìm": "Etsi",
        "Thay bằng": "Korvaa merkinnällä",
        "Kế": "Seuraava",
        "Trước": "Edellinen",
        "Đếm": "Laske",
        "Đóng": "Sulje",
        "Kiểm theo JSON Schema…": "Tarkista JSON-skeemaa vasten…",
        "Chọn tệp JSON Schema": "Valitse JSON-skeematiedosto",
        "Không thấy lỗi nào theo schema này.": "Tämän skeeman mukaan ei löytynyt ongelmia.",
        "JSON Schema": "JSON-skeema",
        "Kiểm cú pháp đồ thị": "Tarkista graafin syntaksi",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Graafin muotoa ei tunnistettu — tarvitaan pääte .dot, .gv, .cypher, .ttl tai .graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "%@-syntaksivirheitä ei löytynyt (tarkistus ei ole kattava).",
        "Cú pháp %@": "%@-syntaksi",
        "không phải một đối tượng JSON": "ei ole JSON-olio",
        "Khai phá văn bản (n-gram, TF-IDF)": "Tekstinlouhinta (n-grammit, TF-IDF)",
        "Tài liệu rỗng.": "Dokumentti on tyhjä.",
        "Không rút được từ khoá nào.": "Yhtään avainsanaa ei saatu poimittua.",
        "Từ khoá": "Avainsanat",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=avainsana|other=avainsanaa} · %d {one=merkkijakso|other=merkkijaksoa} · %d {one=dokumentti|other=dokumenttia}",
        "Tô lên tài liệu": "Merkitse dokumenttiin",
        "Đánh dấu entity từ danh sách…": "Merkitse entiteetit luettelosta…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Valitse entiteettiluettelo (CSV tai JSON)",
        "Không đọc được danh sách entity.": "Entiteettiluetteloa ei voi lukea.",
        "Danh sách entity rỗng.": "Entiteettiluettelo on tyhjä.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Dokumentista ei löytynyt entiteettejä (%d ladattu).",
        "%d lần xuất hiện · %@": "%d {one=esiintymä|other=esiintymää} · %@",
        "Chuyển đổi tri thức…": "Muunna tietämystä…",
        "Chuyển đổi: %@ → %@": "Muunnos: %@ → %@",
        "Không chuyển đổi được.": "Muuntaminen ei onnistunut.",
        "Xem trước cắt chunk…": "Paloittelun esikatselu…",
        "Cỡ cố định 800B, chồng 100B": "Kiinteä koko 800 tavua, limitys 100 tavua",
        "Theo câu (≤ 800B)": "Virkkeittäin (≤ 800 tavua)",
        "Theo heading Markdown": "Markdown-otsikoittain",
        "Tài liệu rỗng — không có chunk nào.": "Tyhjä dokumentti — ei paloja.",
        "%d chunk · trung bình %d B · %@": "%d {one=pala|other=palaa} · keskimäärin %d tavua · %@",
        "Xuất JSONL": "Vie JSONL",
        "Chunk JSONL": "Palojen JSONL",
        "Mở triple/edge dạng bảng": "Avaa kolmikot/kaaret taulukkona",
        "Bảng triple": "Kolmikkotaulukko",
        "Tài liệu này không có dòng triple nào.": "Tässä dokumentissa ei ole yhtään kolmikkoriviä.",
        "Không đọc được triple nào — dòng %d: %@": "Yhtään kolmikkoa ei saatu luettua — rivi %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%1$d {one=kolmikko|other=kolmikkoa} luettu · %2$d {one=virheellinen rivi|other=virheellistä riviä} ohitettu (ensimmäinen: rivi %3$d)",
        "Trùng lặp mờ theo cột…": "Sumeat kaksoiskappaleet sarakkeittain…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Sumeat kaksoiskappaleet — sarake «%1$@»: %2$d {one=ehdokasryhmä|other=ehdokasryhmää}",
        "Gộp": "Yhdistä",
        "Giống": "Osuma",
        "Các giá trị trong cụm": "Ryhmän arvot",
        "Gộp về": "Yhdistä arvoon",
        "Gộp các cụm đã chọn": "Yhdistä valitut ryhmät",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Yhtään ryhmää ei ole valittu — «Yhdistä» ei muuta MITÄÄN. Ohjelma ei koskaan yhdistä omin päin.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=ryhmä|other=ryhmää} valittu · %d {one=rivi|other=riviä} muuttuu · YKSI kumoamisaskel",
        "Không quét được cột này.": "Tätä saraketta ei voitu käydä läpi.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "Sarakkeessa «%@» ei ole sumeiden kaksoiskappaleiden ryhmiä.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Yhtään ryhmää ei yhdistetty — dokumentti on ennallaan.",
        "Khử trùng lặp mờ · cột %@": "Sumeiden kaksoiskappaleiden poisto · sarake %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=ryhmä|other=ryhmää} yhdistetty · %d {one=solu|other=solua} muuttui",
        "Báo cáo làm sạch": "Puhdistusraportti",
        "# Báo cáo làm sạch — %@\n\n": "# Puhdistusraportti — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Käytetty (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Yhtään askelta ei ole käytetty._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Datan profiili\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%1$d {one=sarake|other=saraketta} · %2$d {one=rivi|other=riviä} · käyty läpi %3$.1f sekunnissa_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Sarake | Tyyppi | Tyhjät | Eri arvoja | Pienin | Suurin | Keskiarvo |\n",
        "\n### Giá trị bất thường\n\n": "\n### Poikkeavat arvot\n\n",
        "hàng %d: %@": "rivi %d: %@",
        "- cột «%@» — %d ô: %@\n": "- sarake «%1$@» — %2$d {one=solu|other=solua}: %3$@\n",
        "\n## Còn lại (%d)\n\n": "\n## Jäljellä (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Havaintoja ei ole enää jäljellä._\n",
        "- cột «%@»: %@\n": "- sarake «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "Poista välilyönnit tallennettaessa",
        "Chuẩn hóa xuống dòng": "Normalisoi rivinvaihdot",
        "trước đó": "edellinen",
        "Không mở lại được thư mục «%@» của phiên trước": "Edellisen istunnon kansiota «%@» ei voitu avata uudelleen",
        " (và %d file khác)": " (ja %d {one=tiedosto|other=tiedostoa} lisää)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%d {one=välilehteä|other=välilehteä} ei voitu avata uudelleen: %@%@ — tiedostot eivät ole enää entisellä paikallaan.",
        "Không đọc được nội dung từ ống dẫn": "Syötettä putkesta ei voitu lukea",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Rivin lopun välilyönnit poistetaan jokaisella tallennuksella",
        "Không cắt khoảng trắng khi lưu nữa": "Välilyöntejä ei enää poisteta tallennettaessa",
        "Chưa đặt tên.txt": "Nimetön.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "Merkistön muuntaminen hävittää merkkejä",
        "Vẫn lưu": "Tallenna silti",
        "Tài liệu có thay đổi chưa lưu": "Dokumentissa on tallentamattomia muutoksia",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Sulkeminen tallentamatta hylkää ne.",
        "Bỏ thay đổi": "Hylkää muutokset",
        "Đi tới dòng": "Siirry riville",
        "Tài liệu có %d dòng.": "Dokumentissa on %d {one=rivi|other=riviä}.",
        "Số dòng": "Rivinumero",
        "Đi tới": "Siirry",
        "Diễn giải lại theo…": "Tulkitse uudelleen muodossa…",
        "Chuyển đổi sang…": "Muunna muotoon…",
        "Không diễn giải lại được": "Uudelleentulkinta ei onnistunut",
        "Bảng mã %@ không chứa hết ký tự": "%@ ei pysty esittämään kaikkia merkkejä",
        "Vẫn chọn": "Valitse silti",
        "Cột %d": "Sarake %d",
        "Cột %d: %@": "Sarake %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Kätketyt sarakkeet: %@ (%d) — palauta ne otsikkorivin kontekstivalikosta",
        "Hiện lại: %@": "Näytä uudelleen: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Sarake %@ kätketty — se on tiedostossa koskemattomana",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Lajiteltu: %@ %@ · vain näyttö",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Lajiteltu: %@ %@ (vain näyttö)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ riviä osuu — etsintä jatkuu…",
        "%d / %d dòng khớp": "%d / %d {one=rivi|other=riviä} osuu",
        "Không tìm thấy lỗi trong %d hàng": "%d rivillä ei löytynyt ongelmia",
        "%d hàng lệch số cột": "%d rivillä on väärä määrä sarakkeita",
        "%d ô sai kiểu dữ liệu": "%d solussa on väärä tietotyyppi",
        " (đã dừng ở %d lỗi đầu)": " (pysähtyi %d ensimmäiseen ongelmaan)",
        "   —   kiểu nhận ra: ": "   —   tunnistetut tyypit: ",
        "Hàng %d, cột %@: «%@» không phải %@": "Rivi %1$d, sarake %2$@: «%3$@» ei ole %4$@",
        "Column Editor — %d dòng": "Sarakemuokkain — %d {one=rivi|other=riviä}",
        "Phát hiện": "Havainnot",
        "Hồ sơ dữ liệu": "Datan profiili",
        "Hồ sơ dữ liệu — đang quét…": "Datan profiili — käydään läpi…",
        "Lưu công thức…": "Tallenna resepti…",
        "Xuất báo cáo": "Vie raportti",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Yhtään ryhmää ei ole käytetty · jokainen ryhmä on yksi kumoamisaskel",
        "quá nhiều giá trị": "liian monta arvoa",
        "hay gặp: ": "yleisimmät: ",
        "Giá trị điền vào ô thiếu": "Arvo, jolla tyhjät solut täytetään",
        "Áp dụng": "Käytä",
        "Không dựng được bản xem trước": "Esikatselua ei voitu rakentaa",
        "· giữ nguyên, không đọc được ·": "· jätetty ennalleen, ei tulkittavissa ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Muunna sarake muotoon ISO 8601 (VVVV-KK-PP)",
        "Quy ước số cho cả cột": "Lukujen esitystapa koko sarakkeelle",
        "Làm gì với ô thiếu": "Mitä tyhjille soluille tehdään",
        "Chuẩn hóa về ISO 8601": "Normalisoi muotoon ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Lue monitulkintaiset solut PÄIVÄ ensin (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Lue monitulkintaiset solut KUUKAUSI ensin (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Ohita monitulkintaiset solut, korjaa vain varmat",
        "Về Việt/Âu (1.234,56)": "Vietnamilaiseen/eurooppalaiseen (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Angloamerikkalaiseen (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Angloamerikkalaiseen ilman tuhaterotinta (1234.56)",
        "Điền một giá trị mặc định…": "Täytä oletusarvolla…",
        "Điền xuôi — lấy giá trị phía trên": "Täytä alaspäin — ota yläpuolinen arvo",
        "Điền ngược — lấy giá trị phía dưới": "Täytä ylöspäin — ota alapuolinen arvo",
        "Xóa hàng có ô thiếu ở cột này": "Poista rivit, joilla tämä sarake on tyhjä",
        "Cắt khoảng trắng hai đầu": "Poista välilyönnit molemmista päistä",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Poista molemmista päistä ja tiivistä sisäiset välilyönnit",
        "Pivot…": "Pivot-taulukko…",
        "Nguồn…": "Lähteet…",
        "Pivot — gộp theo cột": "Pivot-taulukko — ryhmittele sarakkeen mukaan",
        "Hàng (gộp nhóm)": "Rivit (ryhmittely)",
        "Giá trị": "Arvot",
        "+ Hàng": "+ Rivi",
        "+ Giá trị": "+ Arvo",
        "Xoá hết": "Tyhjennä kaikki",
        "Đưa vào ô truy vấn": "Sijoita kyselykenttään",
        "Chọn cột để dựng câu truy vấn.": "Valitse sarakkeet, joista kysely rakennetaan.",
        "Không đọc được tên cột của bảng này.": "Tämän taulukon sarakkeiden nimiä ei voitu lukea.",
        "Nguồn dữ liệu của truy vấn": "Kyselyn tietolähteet",
        "«%@» — tài liệu đang mở": "«%@» — avoinna oleva dokumentti",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ tiedosto on muuttunut rekisteröinnin jälkeen",
        "Thêm file…": "Lisää tiedosto…",
        "Bỏ hết": "Poista kaikki",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Taulukon nimeä ei voitu päätellä nimestä «%@» — nimeä tiedosto uudelleen.",
        "Tổng": "Summa",
        "Trung bình": "Keskiarvo",
        "Nhỏ nhất": "Pienin",
        "Lớn nhất": "Suurin",
        "Đếm khác nhau": "Eri arvojen määrä",
        "Biểu đồ": "Kaavio",
        "Xuất PNG": "Vie PNG",
        "Xuất SVG": "Vie SVG",
        "Bảng này không có cột số nào để vẽ.": "Tässä taulukossa ei ole numeerista saraketta piirrettäväksi.",
        "Không dựng được ảnh PNG.": "PNG-kuvaa ei voitu rakentaa.",
        "Kết quả truy vấn": "Kyselyn tulos",
        "Đã lưu %@": "%@ tallennettu",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "%1$@-kaavio kohteesta «%2$@» — %3$d {one=piste|other=pistettä}, arvot väliltä %4$@–%5$@",
        "Cột": "Pylväs",
        "Đường": "Viiva",
        "Phân bố": "Histogrammi",
        "Phân tán": "Hajonta",
        "Hộp": "Laatikko",
        "CSV: chất lượng dữ liệu…": "CSV: datan laatu…",
        "Chất lượng dữ liệu": "Datan laatu",
        "Xuất vi phạm ra tab mới": "Vie rikkomukset uuteen välilehteen",
        "Mức": "Taso",
        "Luật": "Sääntö",
        "Vi phạm": "Rikkomukset",
        "Tỷ lệ": "Osuus",
        "đạt": "läpäisi",
        "lỗi": "virhe",
        "cảnh báo": "varoitus",
        "hỏng": "rikki",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=rikkova rivi|other=rikkovaa riviä} merkitty",
        "Xu hướng": "Kehitys",
        "Lúc chấm": "Arvioitu",
        "Số hàng": "Rivejä",
        "Lệch": "Erotus",
        "Luật trượt": "Hylätyt säännöt",
        "Điểm chất lượng": "Laatupisteet",
        "Điểm theo thời gian": "Pisteet ajan mittaan",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Historiaa ei vielä ole — jokainen arviointi lisää ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "yhden rivin sääntöjen vieressä olevaan tiedostoon «.history.jsonl».",
        "%d mốc trong lịch sử": "%d {one=piste|other=pistettä} historiassa",
        " · %d dòng KHÔNG đọc được": " · %d {one=riviä|other=riviä} EI VOI LUKEA",
        " · chọn hai dòng để so": " · valitse kaksi riviä vertailtavaksi",
        "điểm %+.1f": "pisteet %+.1f",
        "không chiều nào tụt": "yksikään ulottuvuus ei laskenut",
        "tụt: ": "laskivat: ",
        "%d luật mới trượt: %@": "%d {one=vasta hylätty sääntö|other=vasta hylättyä sääntöä}: %@",
        "số hàng %+d": "rivejä %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (ja %d {one=varoitus|other=varoitusta} lisää Kehitys-välilehdellä)",
        "Không sửa tự động được: ": "Ei automaattista korjausta: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Avaa oikean työkalun puhdistuspenkissä ja arvioi sitten heti uudelleen.",
        "Xử lý giá trị thiếu…": "Käsittele puuttuvat arvot…",
        "Chuẩn hóa ngày…": "Normalisoi päivämäärät…",
        "Khử trùng lặp…": "Poista kaksoiskappaleet…",
        "Thay thế…": "Korvaa…",
        "Xem các dòng sai": "Näytä virheelliset rivit",
        "Không tìm thấy cột «%@» trong bảng này.": "Saraketta «%@» ei ole tässä taulukossa.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Kaksoiskappaleet poistettu — «%@» on nyt yksikäsitteinen. Pisteet: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Kaksoiskappaleet poistettu, mutta sarakkeessa «%1$@» on yhä %2$d {one=toistuva rivi|other=toistuvaa riviä} (aiemmin: %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "ne rivit jakavat AVAIMEN mutta eivät koko riviä, joten sinun on katsottava ja valittava ",
        "giữ hàng nào.": "kumman säilytät.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Yhtään tätä sääntöä rikkovaa arvoa ei voitu lukea.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {one=virheellinen arvo|other=virheellistä arvoa} sarakkeessa «%2$@» — täytä Korvaa-kenttä ja paina Esikatsele",
        "Đã chấm lại: %.0f/100": "Arvioitu uudelleen: %.0f/100",
        "Xem trước báo cáo": "Raportin esikatselu",
        "Tham số…": "Parametrit…",
        "Xuất HTML…": "Vie HTML…",
        "In / PDF…": "Tulosta / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=lohko|other=lohkoa} suoritettu · %d {one=lohko|other=lohkoa} EPÄONNISTUI",
        "%d khối chạy được": "%d {one=lohko|other=lohkoa} suoritettu",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · VANHENTUNUT DATA — lähdetiedosto on muuttunut; rakenna uudelleen",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "Raportin esikatselu vaatii .%@-dokumentin",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Tietolähdettä ei löytynyt — ilmoita «source: tiedosto.csv» frontmatterissa.",
        "Không dựng được báo cáo.": "Raporttia ei voitu rakentaa.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Tämä raportti ei ilmoita yhtään parametria frontmatterissa.",
        "Tham số báo cáo": "Raportin parametrit",
        "Dựng lại": "Rakenna uudelleen",
        "Đã xuất %@": "%@ viety",
        "Báo cáo: xem trước": "Raportti: esikatselu",
        "Báo cáo: sinh loạt…": "Raportti: erätuotanto…",
        "không phải tài liệu .greport.md": "ei ole .greport.md-dokumentti",
        "không phân tích được báo cáo": "raporttia ei voitu jäsentää",
        "không tìm được dữ liệu nguồn": "lähdedataa ei löytynyt",
        "không đọc được danh sách tham số": "parametriluetteloa ei voitu lukea",
        "Sinh loạt cần tài liệu đuôi .%@": "Erätuotanto vaatii .%@-dokumentin",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Valitse parametriluettelo (CSV tai JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Valitse kansio %d {one=raportille|other=raportille}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "puuttuvat parametrit ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "osoittaa itse lähdetiedostoon — päälle kirjoittaminen evättiin",
        "%d khối HỎNG": "%d {one=lohko|other=lohkoa} EPÄONNISTUI",
        "Sinh loạt xong: %d tệp · %d hỏng": "Erä valmis: %d {one=tiedosto|other=tiedostoa} · %d epäonnistui",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=parametrijoukkoa|other=parametrijoukkoa} ei voitu rakentaa — katso yhteenveto",
        "Sơ đồ Mermaid: xem trước": "Mermaid-kaavio: esikatselu",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid-kaavio: lisää malli…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid-kaavio: muotoile uudelleen",
        "Nền trong suốt": "Läpinäkyvä tausta",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Tämä Mac ei osaa muuntaa kaaviota PNG-muotoon — tarvitaan macOS 13. SVG-vienti toimii yhä.",
        "Lưu PNG %@…": "Tallenna PNG %@…",
        "Lưu SVG…": "Tallenna SVG…",
        "Chép ảnh vào clipboard": "Kopioi kuva leikepöydälle",
        "Màu thương hiệu…": "Brändin värit…",
        "Màu thương hiệu cho sơ đồ": "Kaavioiden brändivärit",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Jokainen kenttä on väri muodossa #rrggbb. Tallennetaan tiedostoon «themes/mermaid-brand.json» — voi kopioida toiseen Maciin.",
        "Màu chính": "Pääväri",
        "Chữ trên nút": "Solmujen teksti",
        "Viền": "Reunus",
        "Đường nối": "Yhteydet",
        "Nền khi xuất ảnh": "Tausta vietäessä",
        "Lưu và chèn %%{init}%% vào tài liệu": "Tallenna ja lisää %%{init}%% dokumenttiin",
        "Đã lưu màu thương hiệu": "Brändin värit tallennettu",
        "Đã chép ảnh sơ đồ vào clipboard": "Kaavion kuva kopioitu leikepöydälle",
        "Đã lưu %@ — %@": "%@ tallennettu — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Tässä kaaviossa on jo %%{init}%%-määre — omasi jätetään koskematta.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% lisätty — kaavio kantaa nyt omat värinsä",
        "Chèn màu thương hiệu vào sơ đồ": "Lisää brändin värit kaavioon",
        "Định dạng sơ đồ Mermaid": "Muotoile Mermaid-kaavio uudelleen",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "Kaavion lähde on jo siisti — mitään ei tarvitse muuttaa",
        "Đã định dạng lại sơ đồ": "Kaavio muotoiltu uudelleen",
        "Đã định dạng lại %d sơ đồ": "%d {one=kaavio|other=kaaviota} muotoiltu uudelleen",
        "Thư viện mẫu sơ đồ": "Kaaviomallien kirjasto",
        "Mẫu sơ đồ đầy đủ": "Täydelliset kaaviomallit",
        "Mẩu cú pháp": "Syntaksin palasia",
        "Đang soạn: %@": "Muokataan: %@",
        "Đã chèn mẫu «%@»": "Malli «%@» lisätty",
        "Tài liệu đang ở chế độ chỉ đọc.": "Tämä dokumentti on vain luettavissa.",
        "Sơ đồ Mermaid": "Mermaid-kaavio",
        "Tài liệu chưa có khối mermaid nào.": "Tässä dokumentissa ei ole yhtään mermaid-lohkoa.",
        "Thương hiệu": "Brändi",
        "Xuất…": "Vie…",
        "Chưa có sơ đồ nào": "Ei vielä kaavioita",
        "%d sơ đồ · %@": "%d {one=kaavio|other=kaaviota} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d {one=kaavio|other=kaaviota} EPÄONNISTUI — kaavio %3$d%4$@",
        ", dòng %d": ", rivi %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Tässä dokumentissa ei ole ```mermaid-lohkoa eikä se ole .mmd-tiedosto.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Yhtään kaaviota ei ole vielä piirretty valmiiksi.",
        "Không tìm thấy «%@» trong mã sơ đồ": "«%@» ei löytynyt kaavion lähteestä",
        "không dựng được hàng rào chặn mạng cho WKWebView": "verkkoestoa WKWebView:lle ei voitu rakentaa",
        "Luật kết hợp": "Assosiaatiosäännöt",
        "Mỗi dòng một giỏ": "Yksi kori riviä kohden",
        "Hai cột: mã · item": "Kaksi saraketta: tunnus · nimike",
        "Dạng dữ liệu giao dịch": "Tapahtumadatan muoto",
        "Cột giỏ hàng hoặc mã giao dịch": "Korisarake tai tapahtumatunnuksen sarake",
        "Cột item": "Nimikesarake",
        "Ký tự phân tách item": "Nimikkeitä erottava merkki",
        "Support tối thiểu, phần trăm": "Pienin support, prosenttia",
        "Confidence tối thiểu, phần trăm": "Pienin confidence, prosenttia",
        "Tách bởi:": "Erottimena:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "Assosiaatiosääntöjen taulukko",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Huomio",
        "%d giao dịch · %d item · %d luật": "%d {one=tapahtuma|other=tapahtumaa} · %d {one=nimike|other=nimikettä} · %d {one=sääntö|other=sääntöä}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — yksikään sääntö ei yltänyt kynnyksiin; laske support- tai confidence-arvoa",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — PYSÄHTYI ENNENAIKAISESTI, taulukko on VAJAA",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=tapahtuma|other=tapahtumaa} sisältää molemmat puolet",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "Kahden sarakkeen muoto vaatii kaksi ERI saraketta.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%1$d {one=rivi|other=riviä} merkitty %2$d tapahtumassa, jotka sisältävät «%3$@»",
        "CSV: luật kết hợp…": "CSV: assosiaatiosäännöt…",
        "Khai phá theo nhóm": "Ryhmittäinen louhinta",
        "Cột nhóm": "Ryhmittelysarake",
        "Cột giá trị": "Arvosarake",
        "Cột thứ hai cho tương quan": "Toinen sarake korrelaatiota varten",
        "Cách xếp hạng": "Järjestystapa",
        "Nhóm theo:": "Ryhmittele:",
        "Giá trị:": "Arvo:",
        "Xếp theo:": "Järjestä:",
        "Bảng xếp hạng nhóm": "Ryhmien järjestystaulukko",
        "Nhóm": "Ryhmä",
        "Hàng": "Rivejä",
        "Hàng rào riêng": "Oma kynnys",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r-ero",
        "Ghi chú": "Muistiinpano",
        "không đo được": "ei mitattavissa",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=ryhmä|other=ryhmää} · kokonaisviitekorrelaatio %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=RYHMÄ|other=RYHMÄÄ} JÄTETTY POIS",
        "Bảng này không có cột chữ nào để gom nhóm.": "Tässä taulukossa ei ole tekstisaraketta ryhmittelyyn.",
        "Bảng này không có cột số nào để khai phá.": "Tässä taulukossa ei ole numeerista saraketta louhittavaksi.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%1$d {one=rivi|other=riviä} ryhmästä «%2$@» merkitty",
        "CSV: khai phá theo nhóm…": "CSV: ryhmittäinen louhinta…",
        "\u{2194}": "↔",
        "Dự báo": "Ennuste",
        "Cột giá trị theo thời gian": "Arvosarake ajan mittaan",
        "Mô hình dự báo": "Ennustemalli",
        "Số kỳ dự báo": "Ennustettavien jaksojen määrä",
        "Kết luận so với baseline": "Tuomio vertailumalleihin nähden",
        "Mô hình:": "Malli:",
        "Số kỳ:": "Jaksoja:",
        "Chu kỳ:": "Kausi:",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Kausivaihtelun jakso; jätä tyhjäksi automaattista tunnistusta varten",
        "Bảng giá trị dự báo": "Ennustettujen arvojen taulukko",
        "Kỳ": "Jakso",
        "Dải 80%": "80 %:n väli",
        "Dải 95%": "95 %:n väli",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "ei laskettavissa",
        "Bảng này không có cột số nào để dự báo.": "Tässä taulukossa ei ole numeerista saraketta ennustettavaksi.",
        "Không dựng được dự báo cho cột này.": "Tälle sarakkeelle ei voitu rakentaa ennustetta.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "Sarakkeessa «%1$@» on vain %2$d {one=numeerinen arvo|other=numeerista arvoa} — ennusteeseen tarvitaan vähintään 4.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# Sarja luetaan täsmälleen tiedoston riviväljestyksessä — ilman uudelleenlajittelua ja ilman aikasarakkeen päättelyä.\n",
        "Sai số huấn luyện": "Opetusvirhe",
        "CSV: dự báo chuỗi thời gian…": "CSV: aikasarjaennuste…",
        "Holt-Winters cộng": "Holt-Winters additiivinen",
        "Holt-Winters nhân": "Holt-Winters multiplikatiivinen",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Klusterointiin menevät sarakkeet",
        "Đường cong WCSS": "WCSS-käyrä",
        "Phân cụm": "Klusteri",
        "Chuẩn hoá:": "Skaalaus:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Valitse vähintään yksi sarake.",
        "Không đủ dữ liệu để dựng đường cong.": "Käyrän rakentamiseen ei ole tarpeeksi dataa.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Kyynärpää ehdottaa k = %d. WCSS laskee AINA k:n kasvaessa, joten tämä on tapa lukea kuvaajaa eikä tilastollinen kriteeri — katso käyrää ja arvioi, onko taite selvä.",
        "WCSS theo k": "WCSS k:n mukaan",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "k-etäisyys ehdottaa eps = %1$@ (minPts on oletuksena 2 × sarakkeiden määrä = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Etäisyys k:nteen naapuriin",
        "Cần ít nhất 2 cột số để phân cụm.": "Klusterointiin tarvitaan vähintään 2 numeerista saraketta.",
        "Cụm theo %@ và %@": "Klusterit sarakkeiden %@ ja %@ mukaan",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — klusterit löytyivät %d {one=ulottuvuudesta|other=ulottuvuudesta}; kuvaaja näyttää vain 2 ensimmäistä",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# kohina (cluster_id = -1): %d {one=rivi|other=riviä}\n",
        "CSV: phân cụm…": "CSV: klusterointi…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Klustereiden keskipisteet (alkuperäiset yksiköt) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Korrelaatiomatriisi",
        "Phương pháp tương quan": "Korrelaatiomenetelmä",
        "Tương quan không hàm ý nhân quả.": "Korrelaatio ei tarkoita syy-yhteyttä.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Vahvin pari: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Napsauta solua nähdäksesi hajontakuvion.",
        "Không cặp nào đo được.": "Yhtään paria ei voi mitata.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ %4$d rivillä",
        "Cần ít nhất 2 cột số để tính tương quan.": "Korrelaatioon tarvitaan vähintään 2 numeerista saraketta.",
        "Không đọc được cột «%@».": "Saraketta «%@» ei voi lukea.",
        "CSV: ma trận tương quan…": "CSV: korrelaatiomatriisi…",
        "Bất thường": "Poikkeamat",
        "Danh sách bất thường": "Poikkeamien luettelo",
        "Cột:": "Sarake:",
        "Cột số cần xét": "Tutkittava numeerinen sarake",
        "Cách:": "Menetelmä:",
        "Phương pháp phát hiện": "Havaitsemismenetelmä",
        "Phương pháp đã dùng": "Käytetty menetelmä",
        "Ngưỡng": "Kynnys",
        "Đánh dấu": "Merkitse",
        "Xuất tab mới": "Vie uuteen välilehteen",
        "Dòng": "Rivi",
        "Điểm": "Pisteet",
        "Vì sao": "Miksi",
        "nhẹ": "lievä",
        "vừa": "kohtalainen",
        "nặng": "vakava",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=rivi|other=riviä} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Tässä taulukossa ei ole numeerista saraketta, josta etsiä poikkeamia.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=poikkeava rivi|other=poikkeavaa riviä} merkitty",
        "CSV: tìm bất thường…": "CSV: etsi poikkeamia…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d {one=sääntö, LÄPÄISI|other=sääntöä, kaikki LÄPÄISIVÄT} · %2$d {one=rivi|other=riviä} · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d {one=virhe|other=virhettä} · %2$d {one=varoitus|other=varoitusta} %3$d {one=säännössä|other=säännössä} · %4$d {one=rivi|other=riviä} · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Tallenna dokumentti ensin — laatusäännöt ovat datatiedoston vieressä.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Sääntöjoukkoa ei vielä ole. Luo tiedosto %@ ja avaa uudelleen.",
        "Lịch sử": "Historia",
        "Câu đã lưu": "Tallennetut kyselyt",
        "Lưu câu này…": "Tallenna tämä kysely…",
        "Lưu câu truy vấn": "Tallenna kysely",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Anna sille nimi, jotta löydät sen myöhemmin. Sama nimi korvaa aiemman.",
        "Ví dụ: Doanh thu theo tỉnh": "Esimerkiksi: Liikevaihto maakunnittain",
        "Chưa nhập giá trị cho tham số: %@": "Parametrille ei annettu arvoa: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "Liitännäinen on muuttunut hyväksymisesi jälkeen — GEditor kieltäytyy suorittamasta sitä",
        "Chạy plugin chưa duyệt?": "Suoritetaanko hyväksymätön liitännäinen?",
        "Tôi tin file này — chạy": "Luotan tähän tiedostoon — suorita",
        "KHÔNG có chữ ký": "EI allekirjoitettu",
        "Chữ ký: %@": "Allekirjoitus: %@",
        "Đường dẫn: %@": "Polku: %@",
        "Thay": "Korvaa",
        "Thay tất cả": "Korvaa kaikki",
        "Chuỗi thuần": "Pelkkä teksti",
        "Extended (\\n \\t \\xNN)": "Laajennettu (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Säännöllinen lauseke",
        "Phân biệt hoa thường": "Erota isot ja pienet kirjaimet",
        "Cả từ": "Koko sana",
        "Không có kết quả": "Ei tuloksia",
        "Thử biểu thức chính quy…": "Kokeile säännöllistä lauseketta…",
        "Chế độ Log (tô theo mức)": "Lokitila (väri tason mukaan)",
        "Lọc log theo mức…": "Suodata loki tason mukaan…",
        "Chạy trên cả thư mục…": "Suorita koko kansiolle…",
        "Lọc qua lệnh ngoài…": "Suodata ulkoisella komennolla…",
        "Script…": "Skriptit…",
        "Gói mở rộng…": "Laajennuspaketit…",
        "Cửa sổ mới": "Uusi ikkuna",
        "Tách tab ra cửa sổ mới": "Irrota välilehti uuteen ikkunaan",
        "Chưa mở thư mục nào": "Yhtään kansiota ei ole avattu",
        "Tìm file trong thư mục": "Etsi tiedostoa kansiosta",
        "Lọc theo tên": "Suodata nimen mukaan",
        "File mới…": "Uusi tiedosto…",
        "Thư mục mới…": "Uusi kansio…",
        "Đổi tên…": "Nimeä uudelleen…",
        "Chuyển vào Thùng rác": "Siirrä roskakoriin",
        "Hiện trong Finder": "Näytä Finderissa",
        "Đang đọc cấu trúc tài liệu…": "Luetaan dokumentin rakennetta…",
        "file này không có hàm nào": "tässä tiedostossa ei ole funktioita",
        "Không có gì khớp": "Ei osumia",
        "Văn bản thuần": "Pelkkä teksti",
        "🔒 Chỉ đọc": "🔒 Vain luku",
        "Đang theo dõi": "Seurataan",
        "ngắt tại cột": "rivitys sarakkeen kohdalla",
        "Cú pháp": "Syntaksi",
        "Bấm để chèn vào ô truy vấn": "Napsauta lisätäksesi kyselyyn",
        "truy vấn không hợp lệ": "kelvoton kysely",
        "khóa `ten` ở gốc": "avain «nimi» juuressa",
        "khóa có dấu cách": "avain, jossa on välilyöntejä",
        "phần tử đầu": "ensimmäinen alkio",
        "mọi phần tử": "kaikki alkiot",
        "lát cắt": "viipale",
        "hợp nhiều chỉ số": "indeksien unioni",
        "mọi khóa `gia` ở mọi tầng": "kaikki «hinta»-avaimet kaikilla tasoilla",
        "mọi nút": "kaikki solmut",
        "lọc theo số": "suodata luvun mukaan",
        "lọc theo có mặt": "suodata olemassaolon mukaan",
        "Tới lỗi đầu tiên": "Ensimmäiseen virheeseen",
        "Cột doanh_thu là số": "Sarake liikevaihto on numeerinen",
        "lọc…": "suodata…",
        "Hủy": "Kumoa",
        "Thực hiện thay": "Suorita korvaus",
        "xem trước": "esikatselu",
        "tương tác": "vuorovaikutteinen",
        "Soạn thảo": "Muokkaus",
        "Giao diện": "Käyttöliittymä",
        "Phím tắt": "Näppäinoikotiet",
        "Cỡ chữ": "Tekstin koko",
        "Bề rộng TAB": "Sarkaimen leveys",
        "Thụt lề bằng TAB": "Sisennä sarkaimin",
        "Tự động thụt lề khi xuống dòng": "Sisennä automaattisesti uudella rivillä",
        "Tô mọi kết quả tìm kiếm": "Korosta kaikki hakutulokset",
        "Chuẩn hóa về NFC khi lưu": "Normalisoi NFC-muotoon tallennettaessa",
        "Ngôn ngữ": "Kieli",
        "Nền": "Ulkoasu",
        "Theo hệ thống": "Järjestelmän mukaan",
        "Sáng": "Vaalea",
        "Tối": "Tumma",
        "Theme": "Teema",
        "Dùng preset Notepad++": "Käytä Notepad++-esiasetusta",
        "Về phím mặc định": "Takaisin oletusnäppäimiin",
        "Mở file cấu hình": "Avaa asetustiedosto",
        "Xuất theme hiện tại": "Vie nykyinen teema",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Kielen vaihto tulee kokonaan voimaan seuraavalla käynnistyksellä.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Oletusnäppäimet palaavat seuraavalla käynnistyksellä.",
        "Xem trước Markdown": "Markdown-esikatselu",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "Esikatselu käyttää järjestelmän Markdown-moottoria: ei vielä taulukoita eikä koodilohkojen väritystä.",
        "Thử biểu thức chính quy": "Kokeile säännöllistä lauseketta",
        "Biểu thức": "Lauseke",
        "Văn bản thử": "Koeteksti",
        "Kết quả": "Tulos",
        "Kết quả khớp": "Osumat",
        "Biểu thức này làm gì": "Mitä tämä lauseke tekee",
        "Giải thích biểu thức": "Selitä lauseke",
        "Chế độ tìm kiếm": "Hakutila",
        "Kết quả tìm kiếm": "Hakutulokset",
        "Không khớp chỗ nào": "Ei osumia",
        " (đã cắt bớt)": " (katkaistu)",
        "Bản đồ tài liệu": "Dokumenttikartta",
        "Thanh tab": "Välilehtipalkki",
        "Hàng tiêu đề cột": "Sarakkeiden otsikkorivi",
        "Không có cột nào": "Ei sarakkeita",
        "Cây thư mục workspace": "Työtilan puu",
        "Danh sách hàm và lớp": "Funktioiden ja luokkien luettelo",
        "Kết quả tìm trong thư mục": "Hakutulokset kansiosta",
        "Bảng dữ liệu CSV": "CSV-datataulukko",
        "Bàn làm sạch dữ liệu": "Datan puhdistuspenkki",
        "Truy vấn JSONPath": "JSONPath-kysely",
        "Danh sách lỗi dữ liệu": "Datavirheiden luettelo",
        "Bộ đánh giá golden set…": "Kultajoukon arvioija…",
        "So với điểm ngoài (JSONL)…": "Vertaa ulkoisiin pisteisiin (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Valitse ulkoisten pisteiden tiedosto (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "Nimeä valittu solmu uudelleen",
        "Gộp các node đang chọn": "Yhdistä valitut solmut",
        "Tách node đang chọn": "Jaa valittu solmu",
        "Trích subgraph đang chọn ra tab mới": "Poimi valittu aligraafi uuteen välilehteen",
        "Không có gì để đổi": "Ei mitään muutettavaa",
        "%@ — áp %d thay đổi?": "%1$@ — otetaanko %2$d {one=muutos|other=muutosta} käyttöön?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d {one=muutos|other=muutosta} · Cmd-Z kumoaa koko erän",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Aseta osoitin TÄSMÄLLEEN YHDEN solmun päälle ja yritä uudelleen",
        "Đổi tên «%@»": "Nimeä «%@» uudelleen",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Kaikki tähän solmuun viittaavat kaaret ja nimiöt muuttuvat sen mukana.",
        "Đổi tên node": "Nimeä solmu uudelleen",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Valitse VÄHINTÄÄN KAKSI solmua ja yritä uudelleen",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Kanoninen muoto «%@» — yleisin, pisin, tarkkeineen",
        "Gộp node": "Yhdistä solmut",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Valitse siirrettävät KAARIRIVIT ja yritä uudelleen",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Kaikkien valittujen rivien on kosketettava TÄSMÄLLEEN YHTÄ solmua — valitse lisää kaaririvejä",
        "Tách «%@» — chuyển %d cạnh": "Jaa «%1$@» — siirrä %2$d {one=kaari|other=kaarta}",
        "Cạnh tới: %@": "Kaaret kohteeseen: %@",
        "Tách node": "Jaa solmu",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Dokumenttia ei ole tallennettu — poimitulle tiedostolle tarvitaan paikka viereen",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Valitse poimittava graafin osa ja yritä uudelleen",
        "Gom biến thể entity → bảng duyệt": "Kokoa entiteettimuunnelmat → tarkistustaulukko",
        "Áp bảng duyệt đã sửa": "Ota muokattu tarkistustaulukko käyttöön",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Dokumenttia ei ole tallennettu — tarkistustaulukon on oltava graafitiedoston vieressä",
        "Không tìm thấy biến thể nào để gom": "Koottavia muunnelmia ei löytynyt",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=muunnelmaryhmä|other=muunnelmaryhmää} — korjaa sarake «canonical» ja suorita «Ota tarkistustaulukko käyttöön»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Tarkistustaulukkoa «%@» ei ole — suorita ensin «Kokoa entiteettimuunnelmat»",
        "Bảng duyệt không đọc được: %@": "Tarkistustaulukkoa ei voi lukea: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Tarkistustaulukossa ei ole yhtään muutettavaa riviä",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Yksikään graafin kohta ei vastaa tarkistustaulukkoa",
        "Gom biến thể entity": "Kokoa entiteettimuunnelmat",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=muutos|other=muutosta} otettu käyttöön · aliastaulukko ja merkintäluettelo kirjoitettu tiedoston viereen",
        "Áp %d thay đổi lên đồ thị?": "Otetaanko graafiin %d {one=muutos|other=muutosta} käyttöön?",
        "%d alias → dạng chuẩn.": "%d {one=alias|other=aliasta} → kanoninen muoto.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "YHDISTÄ solmut (ei kumottavissa kirjoittamalla uudelleen):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=aliasta|other=aliasta} ei ole graafissa ja ne ohitettiin.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Kattavuusanalyysi pala ↔ entiteetti",
        "Xuất gói ngữ cảnh (JSONL)": "Vie kontekstipaketti (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Kattavuus pala ↔ entiteetti ↔ graafi",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d {one=entiteetti|other=entiteettiä} · %2$d {one=pala|other=palaa} · %3$.0f %% entiteeteistä mainittu · %4$.0f %% paloista sisältää entiteetin",
        "Entity không chunk nào nhắc tới": "Entiteetit, joita yksikään pala ei mainitse",
        "Chunk mồ côi (không chứa entity nào)": "Orvot palat (ilman yhtään entiteettiä)",
        "Node đồ thị không có entity đối ứng": "Graafin solmut ilman vastaavaa entiteettiä",
        "không có": "ei mitään",
        "Phương pháp": "Menetelmä",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Vastaavuutta pala ↔ entiteetti ei voitu rakentaa",
        "Chấm sức khoẻ đồ thị": "Arvioi graafin kunto",
        "sức khoẻ đồ thị": "graafin kunto",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Kunto %1$@/100 · %2$d {one=virhe|other=virhettä} · %3$d {one=käännös|other=käännöstä} · %4$d orpoa",
        "Lai với đồ thị": "Hybridi graafin kanssa",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: graafin signaali sivuutetaan kokonaan, tulos on sama kuin puhtaalla BM25:llä",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α korkea: graafi säätää BM25:n järjestystä vain hieman",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α oletusarvon 0,7 tienoilla: BM25 johtaa, graafi säätää",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α matala: graafi johtaa, BM25 ratkaisee vain tasatilanteet",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: pelkkä graafin signaali; palat ilman entiteettejä ovat tasoissa",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Dokumenttia ei ole tallennettu — hybridi tarvitsee graafitiedoston korpuksen viereen",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Graafitiedostoa «%@» ei löytynyt — hybridi tarvitsee sen signaaliaan varten",
        "lai %.1f ms · %@": "hybridi %.1f ms · %@",
        "Thuật toán…": "Algoritmit…",
        "PageRank (độ dày viền)": "PageRank (reunuksen paksuus)",
        "Cộng đồng (màu nền)": "Yhteisöt (taustaväri)",
        "Thành phần liên thông": "Yhtenäiset komponentit",
        "Xuất bảng node ra tab mới": "Vie solmutaulukko uuteen välilehteen",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d {one=komponentti|other=komponenttia} · suurin %2$d {one=solmu|other=solmua} · %3$d orpoa solmua",
        "Tài liệu này không phải đồ thị DOT": "Tämä dokumentti ei ole DOT-graafi",
        "Không dựng được bảng node/cạnh: %@": "Solmu-/kaaritaulukkoa ei voitu rakentaa: %@",
        "%d hàng · %@": "%d {one=rivi|other=riviä} · %@",
        "Gán nhãn": "Nimiöi",
        "Ghi chú (tuỳ chọn)": "Muistiinpano (valinnainen)",
        "Lưu record": "Tallenna tietue",
        "Xuất CSV": "Vie CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Dokumenttia ei ole tallennettu — arvioijan on oltava korpustiedoston vieressä",
        "Không nạp được bộ đánh giá: %@": "Arvioijaa ei voitu ladata: %@",
        "Không lưu được: %@": "Tallennus ei onnistunut: %@",
        "Bộ đánh giá chưa có record nào": "Arvioijalla ei ole vielä yhtään tietuetta",
        "Không ghi được: %@": "Kirjoittaminen ei onnistunut: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Tämä dokumentti ei ole .mmd-tiedosto eikä DOT, eikä siinä ole mermaid-lohkoa.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=solmu|other=solmua} · %d {one=kaari|other=kaarta} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid-kaavio: lisää elementti…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid-kaavio: yhdistä kaksi valittua elementtiä",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid-kaavio: muuta valitun elementin nimiötä…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid-kaavio: poista valittu elementti",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid-kaavio: siirrä viesti ylös",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid-kaavio: siirrä viesti alas",
        "Thêm phần tử": "Lisää elementti",
        "Thêm participant": "Lisää osallistuja",
        "Thêm mục": "Lisää merkintä",
        "Thêm mục sơ đồ": "Lisää merkintä kaavioon",
        "Sửa mục sơ đồ": "Muuta kaavion merkintää",
        "Xoá mục sơ đồ": "Poista merkintä kaaviosta",
        "Xoá phần tử": "Poista elementti",
        "Sửa nhãn": "Muuta nimiötä",
        "Đổi thứ tự message": "Järjestä viestit uudelleen",
        "Tên mục": "Merkinnän nimi",
        "Mục mới": "Uusi merkintä",
        "Tên mục hiện trên sơ đồ.": "Merkinnän nimi näkyy kaaviossa.",
        "Bảng thuộc tính sơ đồ": "Kaavion ominaisuustaulukko",
        "Tài liệu này không có khối mermaid nào": "Tässä dokumentissa ei ole mermaid-lohkoa",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Tunniste kaavion lähteessä — ilman välilyöntejä. Nimiötä muutetaan jälkeenpäin kaksoisnapsautuksella.",
        "Để trống thì hiện chính định danh.": "Jos jätät tyhjäksi, näytetään itse tunniste.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Vain näkyvä NIMIÖ muuttuu; elementin tunniste pysyy samana.",
        "Không rõ «%@» là phần tử nào": "Ei ole selvää, mikä elementti «%@» on",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Valitse TÄSMÄLLEEN KAKSI elementtiä ja yritä uudelleen",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Aseta osoitin TÄSMÄLLEEN YHDEN elementin päälle ja yritä uudelleen",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Valitse YKSI poistettava elementti tai kaksi kaarella yhdistettyä elementtiä",
        "Xoá «%@» và %d cạnh chạm nó?": "Poistetaanko «%1$@» ja sitä koskettavat %2$d {one=kaari|other=kaarta}?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Näiden kaarien toisessa päässä olevat solmut säilytetään — ne esitellään uudelleen nimiöineen, jos kaarilause oli niiden ainoa esittely.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Kaaviota «%1$@» muokataan vain tekstinä — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: vedä kahden elementin välillä yhdistääksesi ne, kaksoisnapsauta muuttaaksesi nimiötä",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: vedä kahden osallistujan välillä lisätäksesi viestin; järjestystä muutetaan Työkalut-valikosta",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: muokkaa alla olevassa ominaisuustaulukossa",
        "Soạn trực quan đã bật": "Visuaalinen muokkaus käytössä",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d {one=merkintä|other=merkintää} — muokkaa suoraan taulukossa, jokainen solu on yksi kumoamisaskel",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Ympyräkaaviossa se on luku; gantt-kaaviossa se, mikä tulee kaksoispisteen jälkeen.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid-kaavio: poimi lohko .mmd-tiedostoon…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid-kaavio: upota viitattu tiedosto takaisin",
        "Tách khối sơ đồ": "Poimi kaaviolohko",
        "Nhúng khối sơ đồ": "Upota kaaviolohko",
        "Tách khối sơ đồ ra tệp riêng": "Poimi kaaviolohko omaksi tiedostokseen",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Tiedosto sijoitetaan dokumentin VIEREEN; lohkoon jää yksi viiterivi, jotta muokkaus tapahtuu vain yhdessä paikassa.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Dokumenttia ei ole tallennettu — kaaviotiedostolle tarvitaan paikka viereen",
        "Đã có tệp «%@» — chọn tên khác": "Tiedosto «%@» on jo olemassa — valitse toinen nimi",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Poimittu tiedostoon «%@» — lohkoon jäi viiterivi",
        "Mở tệp": "Avaa tiedosto",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "«%@» upotettu takaisin; tiedosto on yhä levyllä",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Tässä lohkossa on oikea kaavio, ei viite",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Tämä lohko viittaa tiedostoon «%@» — avaa se muokataksesi",
        "Không đọc được tệp sơ đồ %@": "Kaaviotiedostoa %@ ei voitu lukea",
        "Soạn trực quan": "Visuaalinen muokkaus",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Vedä solmusta toiseen lisätäksesi kaaren; kaksoisnapsauta muuttaaksesi nimiötä. Jokainen toimenpide on yksi kumoamisaskel.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Visuaalinen muokkaus: vedä kahden solmun välillä lisätäksesi kaaren, kaksoisnapsauta muuttaaksesi nimiötä",
        "Soạn trực quan đã tắt": "Visuaalinen muokkaus pois käytöstä",
        "Thêm node…": "Lisää solmu…",
        "Thêm cạnh giữa hai node đang chọn…": "Lisää kaari kahden valitun solmun välille…",
        "Sửa nhãn node đang chọn…": "Muuta valitun solmun nimiötä…",
        "Xoá node/cạnh đang chọn": "Poista valittu solmu/kaari",
        "Thêm node": "Lisää solmu",
        "Thêm cạnh": "Lisää kaari",
        "Sửa nhãn node": "Muuta solmun nimiötä",
        "Xoá node": "Poista solmu",
        "Xoá cạnh": "Poista kaari",
        "Cmd-Z hoàn tác": "Cmd-Z kumoaa",
        "Tài liệu đang ở chế độ chỉ đọc": "Tämä dokumentti on vain luettavissa",
        "Nhãn của «%@»": "Kohteen «%@» nimiö",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Vain näkyvä NIMIÖ muuttuu; solmun tunniste pysyy samana.",
        "Không rõ «%@» là node nào": "Ei ole selvää, mikä solmu «%@» on",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Solmun tunniste DOT-tiedostossa. Nimiötä muutetaan jälkeenpäin kaksoisnapsauttamalla kuvaa.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Valitse TÄSMÄLLEEN KAKSI solmua ja yritä uudelleen",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Valitse YKSI poistettava solmu tai kaksi kaarella yhdistettyä solmua",
        "Xoá node «%@» và %d cạnh chạm nó?": "Poistetaanko solmu «%1$@» ja sitä koskettavat %2$d {one=kaari|other=kaarta}?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Jos roikkuvia kaaria jää jäljelle, DOT luo solmut niistä uudelleen — poistettu solmu ilmestyy takaisin seuraavalla piirrolla.",
        "Phòng thí nghiệm truy hồi BM25": "BM25-hakulaboratorio",
        "Câu hỏi — Enter để tìm": "Kysymys — Enter hakee",
        "Đánh giá…": "Arvioi…",
        "Đang dựng chỉ mục": "Rakennetaan hakemistoa",
        "Không chunk nào khớp": "Yksikään pala ei osu",
        "kết quả trên": "parasta tulosta",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: jokainen sana lasketaan VAIN kerran, esiintyi se kuinka monta kertaa tahansa",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 matala: sanan toistaminen ei juuri lisää pisteitä",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 oletusarvon 1,2 tienoilla: toisto lisää pisteitä, mutta yhä vähemmän",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 korkea: pala, joka toistaa sanaa monta kertaa, palkitaan voimakkaasti",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: pituus sivuutetaan, pitkiä paloja ei rangaista",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b matala: pitkiä paloja rangaistaan vain kevyesti",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b oletusarvon 0,75 tienoilla: pitkiä paloja rangaistaan kohtalaisesti",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: suurin rangaistus pituudesta, lyhyet palat ovat etusijalla",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: hakulaboratorio…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Dokumenttia ei ole tallennettu — BM25-hakemisto on korpustiedoston vieressä ja tarvitsee siksi polun",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Tämä tiedosto ei ole JSONL — Retrieval Lab toimii palojen korpuksella",
        "Không dựng được chỉ mục BM25 cho tệp này": "Tälle tiedostolle ei voitu rakentaa BM25-hakemistoa",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Dokumenttia ei ole tallennettu — raportin luomiseen tarvitaan korpuspolku",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Valitse arviointijoukko (CSV tai JSONL: kysymys + odotettu palan tunnus)",
        "Đánh giá truy hồi": "Haun arviointi",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Muuta yllä k1-, b- tai k-arvoa ja katso uudelleen vertaillaksesi kahta kokoonpanoa; lisää «compare»-lohko ajaaksesi kaksi parametrijoukkoa rinnakkain samalla arviointijoukolla.",
        "Lỗi": "Virhe",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, keskimäärin %.0f)",
        "Chế độ JSONL": "JSONL-tila",
        "Bản ghi": "Tietue",
        "Chi tiết": "Yksityiskohdat",
        "Bản ghi ở dòng": "Rivin tietue",
        "không phải JSON hợp lệ": "ei ole kelvollista JSONia",
        "bản ghi": "tietuetta",
        "dòng trắng": "tyhjää riviä",
        "không phải đối tượng": "ei ole olio",
        "bảng hiện": "näytetty taulukko",
        "ĐÃ HUỶ giữa chừng": "PERUTTU KESKEN",
        "Không lọc": "Ei suodatusta",
        "bản ghi khớp bộ lọc": "suodattimeen osuvaa tietuetta",
        "Đưa con nháy tới một dòng để xem bản ghi": "Aseta osoitin riville nähdäksesi tietueen",
        "Không có bản ghi nào hỏng": "Ei rikkinäisiä tietueita",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Ei vielä tutkittu. Suorita «JSONL: tutki palat» uudelleen tarkistuksen jälkeen.",
        "trường văn bản": "tekstikenttä",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SKEEMA (arvattu — muuttuu valitsemalla toinen kenttä)",
        "văn bản": "teksti",
        "định danh": "tunniste",
        "metadata lồng": "sisäkkäiset metatiedot",
        "TRƯỜNG": "KENTTÄ",
        "phủ": "kattavuus",
        "nhiều kiểu": "useita tyyppejä",
        "ĐỘ DÀI — ký tự": "PITUUS — merkkejä",
        "ĐỘ DÀI — từ": "PITUUS — sanoja",
        "ĐỘ DÀI — token ước lượng": "PITUUS — arvioituja merkkijaksoja",
        "RỖNG VÀ TRÙNG": "TYHJÄT JA KAKSOISKAPPALEET",
        "chunk rỗng": "tyhjää palaa",
        "dòng": "riviä",
        "nhóm trùng chính xác": "täsmällisten kaksoiskappaleiden ryhmää",
        "dòng không đọc được, không vào thống kê": "riviä ei voi lukea, tilastojen ulkopuolella",
        "PHƯƠNG PHÁP": "MENETELMÄ",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«merkit» lasketaan Unicode-merkkeinä (skalaareina), ei näkyvinä ryhminä",
        "«từ» tách theo khoảng trắng ASCII": "«sanat» erotellaan ASCII-välilyönnein",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«merkkijaksot» lasketaan tavutuserottimella — EI mallin erottimella",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«kaksoiskappale» tarkoittaa TÄSMÄLLISTÄ kaksoiskappaletta; lähes samat ovat lohkossa ```quality",
        "chunk": "palaa",
        "JSONL: kiểm và soi chunk…": "JSONL: tarkista ja tutki palat…",
        "Ảnh": "Kuva",
        "PDF": "PDF",
        "Tài liệu Word": "Word-dokumentti",
        "Bảng tính Excel": "Excel-taulukko",
        "Bản trình chiếu PowerPoint": "PowerPoint-esitys",
        "File nén": "Arkisto",
        "Vừa khung": "Sovita ikkunaan",
        "Chép ảnh": "Kopioi kuva",
        "Xoay": "Käännä",
        "Không đọc được ảnh «%@»": "Kuvaa «%@» ei voi lukea",
        "Đã chép ảnh vào clipboard": "Kuva kopioitu leikepöydälle",
        "Bôi vàng": "Korosta keltaisella",
        "Gạch chân": "Alleviivaa",
        "Ghi chú…": "Muistiinpano…",
        "Bỏ chú thích": "Poista merkinnät",
        "Lấy chữ ra tab mới": "Poimi teksti uuteen välilehteen",
        "Lưu bản có chú thích…": "Tallenna merkinnöillä varustettu versio…",
        "Tìm trong PDF": "Etsi PDF:stä",
        "Thêm": "Lisää",
        "Trang %d/%d": "Sivu %d/%d",
        "Trang %d": "Sivu %d",
        "Kết quả %d/%d": "Tulos %d/%d",
        "0 kết quả": "0 tulosta",
        "Không đọc được PDF «%@»": "PDF-tiedostoa «%@» ei voi lukea",
        "PDF này có mật khẩu — chưa mở được nội dung": "Tämä PDF on suojattu salasanalla — sisältöön ei pääse käsiksi",
        "Không thấy «%@» trong tài liệu": "«%@» ei löytynyt dokumentista",
        "Đã bôi vàng": "Korostettu",
        "Đã gạch chân": "Alleviivattu",
        "Hãy bôi đen một đoạn chữ trước": "Valitse ensin tekstikohta",
        "Đã thêm ghi chú": "Muistiinpano lisätty",
        "Trang này chưa có chú thích nào": "Tällä sivulla ei ole merkintöjä",
        "Đã bỏ %d chú thích trên trang này": "%d {one=merkintä|other=merkintää} poistettu tältä sivulta",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Tässä PDF:ssä ei ole tekstikerrosta — se on todennäköisesti skannaus",
        "Không ghi được tệp": "Tiedostoa ei voitu kirjoittaa",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Kirjoitettu tiedosto EI avaudu oikein uudelleen — älä käytä tätä versiota",
        "Đã lưu %@ · %d trang": "%@ tallennettu · %d {one=sivu|other=sivua}",
        "Tên": "Nimi",
        "Kích thước": "Koko",
        "Đã nén": "Pakattu",
        "Tỉ lệ": "Suhde",
        "Sửa lúc": "Muutettu",
        "Mở mục đang chọn": "Avaa valittu kohde",
        "Bung ra thư mục…": "Pura kansioon…",
        "Bung vào đây": "Pura tähän",
        "%d mục": "%d {one=kohde|other=kohdetta}",
        "giải nén ra %@": "purettu kohteeseen %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— Office-tiedoston sisus on arkisto; nämä ovat sen osat",
        "Đã bung %d mục": "%d {one=kohde|other=kohdetta} purettu",
        "%d mục hỏng": "%d {one=kohde|other=kohdetta} rikki",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=kohde|other=kohdetta} HYLÄTTIIN, koska niiden polut menevät kohdekansion ulkopuolelle",
        "Không mở được mục này": "Tätä kohdetta ei voi avata",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Tiedostoon %@ ei voi vielä kirjoittaa suoraan — käytä «Tallenna nimellä…»",
        "Không có gì đổi": "Mikään ei muuttunut",
        "Đã ghi %d ô vào %@": "%1$d {one=solu|other=solua} kirjoitettu kohteeseen %2$@",
        "Đã ghi %d đoạn vào %@": "%1$d {one=kappale|other=kappaletta} kirjoitettu kohteeseen %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Tiedostoon ei voitu kirjoittaa — alkuperäinen on koskematon",
        "dựng bài": "valmistella testitapaus",
        "Không ghi được settings.json": "Tiedostoa settings.json ei voi kirjoittaa",
        "Xoay trái": "Käännä vasemmalle",
        "Xoay phải": "Käännä oikealle",
        "Trang lên": "Siirrä sivua ylös",
        "Trang xuống": "Siirrä sivua alas",
        "Xoá trang…": "Poista sivuja…",
        "Xoá trang": "Poista sivuja",
        "Trích trang…": "Pura sivut…",
        "Trích trang ra tệp mới": "Pura sivut uuteen tiedostoon",
        "Gộp tệp PDF…": "Yhdistä PDF-tiedosto…",
        "Tách tệp…": "Jaa tiedosto…",
        "Tách tệp PDF": "Jaa PDF-tiedosto",
        "Xuất ảnh…": "Vie kuvat…",
        "Xuất trang ra ảnh PNG": "Vie sivut PNG-kuvina",
        "Hoàn tác trang": "Kumoa sivumuokkaus",
        "Lưu bản đã sửa…": "Tallenna muokattu kopio…",
        "Phát": "Toista",
        "Tạm dừng": "Keskeytä",
        "Xem bình thường": "Tavallinen näkymä",
        "Chọn sheet": "Valitse taulukko",
        "Mở sheet": "Avaa taulukko",
        "Bỏ và đổi sheet": "Hylkää ja vaihda taulukkoa",
        "Bảng tính có %d sheet.": "Työkirjassa on %d taulukkoa.",
        "Bảng tính này chỉ có một sheet: «%@»": "Tässä työkirjassa on vain yksi taulukko: ”%@”",
        "Bỏ phần chưa lưu của sheet này?": "Hylätäänkö tämän taulukon tallentamattomat muutokset?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Taulukon vaihto korvaa koko välilehden. ⌘S:llä tallentamaton työ menetetään.",
        "Chọn tệp PDF cần gộp vào": "Valitse yhdistettävä PDF-tiedosto",
        "Chọn thư mục ghi ảnh": "Valitse kansio kuville",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Valitse tallennuspaikka. Toinen tiedosto kirjoitetaan tämän viereen.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Dokumentissa on %d sivua. Anna poistettavat sivut, esim. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Dokumentissa on %d sivua. Anna purettavat sivut, esim. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Dokumentissa on %d sivua. Anna vietävät sivut, esim. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Dokumentissa on %d sivua. Anna erotettava osa, esim. 1-5; loput tulevat toiseen tiedostoon.",
        "Đã xoay trang %d": "Sivu %d käännetty",
        "Đã xoá trang %@ · còn %d trang": "Sivut %@ poistettu · %d sivua jäljellä",
        "Đã gộp %d trang từ «%@»": "%d sivua yhdistetty tiedostosta ”%@”",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Jaettu osiin %@ (%d sivua) ja %@ (%d sivua)",
        "Đã ghi %@ — %@ · %d trang": "Kirjoitettiin %@ — %@ · %d sivua",
        "Đã xuất %d ảnh vào %@": "%d kuvaa viety kansioon %@",
        "Chỉ xuất được %d/%d ảnh": "Vain %d/%d kuvaa vietiin",
        "Đã hoàn tác một thao tác trang": "Yksi sivutoiminto kumottiin",
        "Không còn thao tác trang nào để hoàn tác": "Ei enää kumottavia sivutoimintoja",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "KAIKKIA sivuja ei voi poistaa — PDF:ssä on oltava vähintään yksi sivu",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Tuo alue on koko dokumentti — ei mitään erotettavaa",
        "«%@» có mật khẩu — chưa gộp được": "”%@” on salasanasuojattu — yhdistäminen ei onnistu",
        "«%@» không có trang nào": "”%@” ei sisällä sivuja",
        "Đã ở trang đầu": "Jo ensimmäisellä sivulla",
        "Đã ở trang cuối": "Jo viimeisellä sivulla",
        "· đã sửa, chưa lưu": "· muokattu, ei tallennettu",
        "Ảnh động · %d khung": "Animoitu kuva · %d ruutua",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Tallentamaton dokumentti — levyllä ei ole tiedostoa binäärinäkymään",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Tämä komento toimii vain Excel-työkirjoissa",
        "Không đọc được danh sách sheet": "Taulukkoluetteloa ei voitu lukea",
        "Không có sheet «%@»": "Taulukkoa ”%@” ei ole",
        "Không đọc được sheet «%@»": "Taulukkoa ”%@” ei voitu lukea",
        "Sheet «%@» · %d hàng": "Taulukko ”%@” · %d riviä",
        "phần còn lại": "loput",
        "Lưu ý": "Huomaa",
        "Cẩn thận": "Varoitus",
        "Xem thêm": "Katso myös",
        "Chép": "Kopioi",
        "Đã chép": "Kopioitu",
        "Chép đoạn mã mẫu": "Kopioi esimerkkikoodi",
        "Tìm trong trợ giúp": "Etsi ohjeesta",
        "Lùi": "Takaisin",
        "Bắt đầu dùng": "Aloita",
        "Không mở cửa sổ này khi khởi động nữa": "Älä näytä tätä ikkunaa käynnistyksessä",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "Ohjetta ei ole vielä käännetty tälle kielelle — näytetään vietnaminkielinen teksti.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Siirry siirtymään (esim. 1F400 tai 0x1F400)",
        "Chép dòng đã chọn": "Kopioi valitut rivit",
        "Đã chép %d dòng": "%d riviä kopioitu",
        "Không đọc được «%@»": "Kohdetta ”%@” ei voitu lukea",
        "Tệp rỗng": "Tyhjä tiedosto",
        "Không đọc được offset «%@»": "Siirtymää ”%@” ei voitu lukea",
        "Offset 0x%@ vượt quá cỡ tệp": "Siirtymä 0x%@ ylittää tiedoston koon",
        "Mở bằng ứng dụng khác…": "Avaa toisessa apissa…",
        "%d kênh": "%d kanavaa",
        "Không phát được «%@»": "Kohdetta ”%@” ei voi toistaa",
        "Không phát được — %@": "Ei voi toistaa — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS:ssä ei ole valmista dekooderia muodolle %@ — kyse on käyttöjärjestelmän rajoituksesta, ei rikkinäisestä tiedostosta.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Voit silti katsoa tavut binäärinäkymässä tai avata tiedoston apissa, jolla on oma dekooderi.",
        "Ký…": "Allekirjoita…",
        "Sửa chữ…": "Muokkaa tekstiä…",
        "Sửa chữ": "Muokkaa tekstiä",
        "Vẽ đè": "Piirrä päälle",
        "Ô chưa điền": "Seuraava tyhjä kenttä",
        "Xoá nội dung đã điền": "Tyhjennä täytetyt arvot",
        "Tệp này không có ô biểu mẫu nào": "Tässä tiedostossa ei ole lomakekenttiä",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d lomakekenttää tyhjennetty",
        "Mọi ô biểu mẫu đều đã có nội dung": "Kaikki lomakekentät on jo täytetty",
        "Còn %d ô chưa điền": "%d kenttää vielä tyhjänä",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Täytettävä lomake: %d kenttää. Kirjoita suoraan ja valitse sitten ”Tallenna muokattu kopio…”",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Valitse allekirjoituskuva (läpinäkyvä tausta näyttää parhaalta)",
        "Không dựng được trang có chữ ký": "Allekirjoitettua sivua ei voitu luoda",
        "Đã chèn chữ ký vào trang %d": "Allekirjoitus lisätty sivulle %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Valitse ensin muutettava teksti",
        "Vùng chọn quá nhỏ": "Valinta on liian pieni",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Uusi teksti PIIRRETÄÄN valinnan päälle järjestelmäfontilla. Vanha teksti peittyy, ei poistu — sen voi yhä purkaa, joten tämä ei ole peittosensuuri.",
        "Không dựng được trang đã sửa": "Muokattua sivua ei voitu luoda",
        "Đã vẽ đè chữ mới lên trang %d": "Uusi teksti piirrettiin sivun %d päälle",
        "Đổi chế độ View / Code": "Vaihda Näkymä / Koodi",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "JSON-, XML- ja YAML-tiedostoille ei ole vielä puunäkymää",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Välilehdellä ei ole vielä kaavionäkymää",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "PowerPointille ei ole vielä jäsennysnäkymää",
        "Tệp này chỉ có một chế độ hiển thị": "Tällä tiedostolla on vain yksi näyttötila",
        "%d nút": "%d solmua",
        "Không dựng được cây: %@": "Puuta ei voitu rakentaa: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Dokumentti on liian suuri puuksi — käytä Koodi-tilaa",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Tämän tiedoston sivuja ei voitu koostaa \u{2014} käytä Code-tilaa.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Diat koostetaan tekstistä; alkuperäisiä kuvia ja asettelua ei vielä piirretä.",
        "Vừa ngang": "Sovita leveyteen",
        "Thu nhỏ trang": "Loitonna sivua",
        "Phóng to trang": "Lähennä sivua",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "Tekstiä ”%@” ei löytynyt asiakirjasta",
        "Chỗ khớp %d/%d": "Osuma %d / %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Sivulla ei ole valittua tekstiä.",
        "%d ký tự": "%d {one=merkki|other=merkkiä}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Avaa tiedostot suoraan View-tilassa, jos sellainen on",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· PERUTTU kesken — taulukko on vaillinainen",
        "Chế độ hiển thị": "Näyttötila",
        "Đổi giữa View và Code (⌥⌘V)": "Vaihda View- ja Code-tilan välillä (⌥⌘V)",
        "Trang tài liệu": "Asiakirjan sivut",
        "Chữ đã dựng": "Taitettu teksti",
        "Trang bảng tính": "Taulukon sivut",
        "Sơ đồ": "Kaavio",
        "Cây khoá–giá trị": "Avain–arvo-puu",
        "Bộ phát": "Soitin",
        "Danh sách mục": "Merkintäluettelo",
        "Báo cáo đã dựng": "Valmis raportti",
        "Tô theo mức": "Väritetty tason mukaan",
        "Trang slide": "Diojen sivut",
        "Dàn ý": "Jäsennys",
        "Lưu rồi dựng lại": "Tallenna ja rakenna uudelleen",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Näyttää LEVYLLÄ olevan kopion — tallentamattomat muutokset eivät ole mukana.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Järjestelmä ei pystynyt rakentamaan asiakirjanäkymää — käytä Code-tilaa.",
        "Lưu tệp trước khi xem trang.": "Tallenna tiedosto ennen sivujen katselua.",
        "Đang ở chế độ Code": "Nyt Code-tilassa",
        "Đang ở chế độ View": "Nyt View-tilassa",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Näet lähdetekstin — napsauta siirtyäksesi View-tilaan (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "View-tilassa — napsauta palataksesi lähdetekstiin (⌥⌘V)",
        "Tín hiệu: %@": "Signaali: %@",
        "Lý do: %@": "Syy: %@",
        "Chi tiết: %@": "Yksityiskohta: %@",
        "Mở báo cáo": "Avaa raportti",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor sulkeutui yllättäen klo %@ — avaa raportti lukeaksesi sen; mitään ei lähetetä.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligatuurit — pois päältä jokainen merkki pysyy omassa ruudussaan",
        "Chế độ CSV": "CSV-tila",
        "Dấu phân tách": "Erotin",
        "Tự nhận diện": "Tunnista automaattisesti",
        "Dấu phân tách: %@": "Erotin: %@",
        "Theo đuôi tệp": "Tiedostopäätteen mukaan",
        "%d dấu cách": "%d {one=välilyönti|other=välilyöntiä}",
        "Tài liệu đang sửa được": "Tätä asiakirjaa voi muokata",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Vain luku, koska tiedostoa seurataan — lopeta seuranta muokataksesi",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Vain luku, koska levyllä olevaan tiedostoon ei voi kirjoittaa",
        "Đã mở khoá — tài liệu sửa được": "Lukitus avattu — asiakirjaa voi taas muokata",
        "Nhân bản tệp": "Monista tiedosto",
        "Đổi tên tệp…": "Nimeä tiedosto uudelleen…",
        "Chuyển tệp tới…": "Siirrä tiedosto…",
        "XML: đánh giá XPath…": "XML: laske XPath…",
        "Đánh giá XPath": "Laske XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Esimerkiksi: //tilaus/rivi[2]/@koodi · //*[@laji='A'] · count(//rivi)",
        "Đánh giá": "Laske",
        "XPath không đọc được: %@": "Tätä XPath-lauseketta ei voi lukea: %@",
        "XPath «%@» không khớp node nào": "XPath ”%@” ei osunut yhteenkään solmuun",
        "XPath «%@» — %d node": "XPath ”%@” — %d {one=solmu|other=solmua}",
        "XPath «%@»: %d node": "XPath ”%@”: %d {one=solmu|other=solmua}",
        "Lưu tệp trước khi nhân bản.": "Tallenna tiedosto ennen monistamista.",
        "Không nhân bản được": "Monistaminen ei onnistunut",
        "Đã nhân bản thành %@": "Monistettu nimellä %@",
        "Lưu tệp trước khi đổi tên.": "Tallenna tiedosto ennen uudelleennimeämistä.",
        "Đổi tên tệp": "Nimeä tiedosto uudelleen",
        "Tên hiện tại: %@": "Nykyinen nimi: %@",
        "Đổi tên": "Nimeä uudelleen",
        "Tên tệp không hợp lệ": "Tuo tiedostonimi ei kelpaa",
        "Đã có tệp tên %@ ở đó": "Siellä on jo tiedosto nimeltä %@",
        "Lưu tệp trước khi chuyển.": "Tallenna tiedosto ennen siirtämistä.",
        "Chuyển tới": "Siirrä tänne",
        "Thư mục đích đã có tệp tên %@": "Kohdekansiossa on jo tiedosto nimeltä %@",
        "Không chuyển được tệp": "Tiedoston siirtäminen ei onnistunut",
        "Đã chuyển tới %@": "Siirretty kohteeseen %@",
        "Bảng mã:": "Merkistö:",
        "Xuống dòng:": "Rivinvaihdot:",
        "Riêng cho %@": "Vain kielelle %@",
        "    %d — dùng TAB": "    %d — sarkaimia",
        "    %d — dùng dấu cách": "    %d — välilyöntejä",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Poista oma sääntö, käytä yleistä asetusta",
        "%@: thụt lề %d %@": "%@: sisennys %d %@",
        "TAB": "sarkainta",
        "dấu cách": "välilyöntiä",
        "Xuất": "Vie",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Avaa tulokset tekstivälilehtenä — tallenna ⌘S:llä",
        "Lượt tìm trước đó": "Aiemmat haut",
        "«%@» — %d kết quả": "”%@” — %d {one=osuma|other=osumaa}",
        "Kết quả tìm «%@»": "Hakutulokset haulle ”%@”",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Suodata tiedostonimiä — esim. *.csv;*.log (tyhjä: jokainen tekstitiedosto)",
        "Thư mục %@ không có file văn bản nào": "Kansiossa %@ ei ole tekstitiedostoja",
        "Không tệp nào trong %@ khớp «%@»": "Mikään tiedosto kansiossa %@ ei vastaa hakua ”%@”",
        "%d byte · %d dòng": "%d tavua · %d {one=rivi|other=riviä}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d tavua · %d {one=rivi|other=riviä} — liian suuri merkkien ja sanojen laskemiseen",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d tavua · %d {one=merkki|other=merkkiä} · %d {one=sana|other=sanaa} · %d {one=rivi|other=riviä}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Tässä asiakirjassa on %d {one=rivi|other=riviä}, %d tavua. Kirjoita rivinumero, ”rivi,sarake” tai ”@tavu”.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "”%@” ei ole luettavissa — kirjoita rivinumero, ”rivi,sarake” tai ”@tavu”",
    ]
}
