import Foundation

/// Bảng dịch tiếng Ả Rập. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let ar: [String: String] = [
        "Bản đã lưu…": "النسخ المحفوظة…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "لم يُحفَظ هذا المستند قط — لا يوجد سجل",
        "Chưa có bản đã lưu nào trước đó": "لا توجد نسخ محفوظة سابقة",
        "Không đọc được bản ấy": "تعذّرت قراءة تلك النسخة",
        "Khôi phục bản đã lưu": "استعادة النسخة المحفوظة",
        "XML: kiểm theo DTD/XSD…": "XML: التحقق عبر DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "لا يحتوي هذا الـ Mac على libxml2، لذا التحقق من XSD غير متاح.",
        "Chọn lược đồ XSD để kiểm": "اختر مخطط XSD للتحقق",
        "Hợp lệ theo": "صالح وفق",
        "Plugin chạy xong, không đổi gì": "انتهت الإضافة دون تغيير أي شيء",
        "Chưa cài plugin native nào": "لا توجد إضافات أصلية مثبّتة",
        "Gỡ plugin này": "إزالة هذه الإضافة",
        "Gỡ plugin này?": "إزالة هذه الإضافة؟",
        "Gỡ": "إزالة",
        "Cài plugin native…": "تثبيت إضافة أصلية…",
        "Mở thư mục plugin": "فتح مجلد الإضافات",
        "Chọn file .dylib của plugin native": "اختر ملف ‎.dylib الخاص بالإضافة",
        "Đã cài:": "مثبّت:",
        "Đã gỡ:": "أُزيل:",
        "Plugin native…": "الإضافات الأصلية…",
        "Chỉ nhận file .dylib.": "تُقبل ملفات ‎.dylib فقط.",
        "Đã có một plugin trùng tên:": "توجد إضافة بالاسم نفسه مثبّتة بالفعل:",
        "Không chép được plugin:": "تعذّر نسخ الإضافة:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "الإضافات الأصلية متاحة في التنزيل المباشر فقط، لا في نسخة App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "لم يُعثر على العملية المساعدة للإضافات.",
        "Không khởi động được tiến trình phụ:": "تعذّر تشغيل العملية المساعدة:",
        "Tiến trình plugin đã dừng giữa chừng.": "توقفت عملية الإضافة في منتصف الطريق.",
        "Plugin không trả lời kịp — đã dừng nó.": "لم تستجب الإضافة في الوقت المحدد — تم إيقافها.",
        "Plugin trả lời sai giao thức:": "ردّت الإضافة برسالة غير صحيحة:",
        "Plugin báo lỗi:": "أبلغت الإضافة عن خطأ:",
        "Về GEditor": "حول GEditor",
        "Cài đặt…": "الإعدادات…",
        "Thoát GEditor": "إنهاء GEditor",
        "File": "ملف",
        "Tab mới": "علامة تبويب جديدة",
        "Đóng tab": "إغلاق علامة التبويب",
        "Tab kế": "علامة التبويب التالية",
        "Tab trước": "علامة التبويب السابقة",
        "Tài liệu mới": "مستند جديد",
        "Mở…": "فتح…",
        "Mở thư mục làm Workspace…": "فتح مجلد كمساحة عمل…",
        "Mở gần đây": "فتح الأخيرة",
        "Lưu": "حفظ",
        "Lưu thành…": "حفظ باسم…",
        "Cắt khoảng trắng cuối dòng khi lưu": "إزالة المسافات في نهاية السطر عند الحفظ",
        "Theo dõi file (tail -f)": "متابعة الملف (tail -f)",
        "In…": "طباعة…",
        "Mở lại tab vừa đóng": "إعادة فتح علامة التبويب المغلقة",
        "Chưa có file nào": "لا توجد ملفات",
        "Xoá danh sách": "مسح القائمة",
        "Edit": "تحرير",
        "Hoàn tác": "تراجع",
        "Làm lại": "إعادة",
        "Cắt": "قص",
        "Sao chép": "نسخ",
        "Dán": "لصق",
        "Lịch sử clipboard…": "سجل الحافظة…",
        "Column Editor…": "محرر الأعمدة…",
        "Chọn lần kế tiếp": "تحديد التطابق التالي",
        "Chọn tất cả": "تحديد الكل",
        "Nhân đôi dòng": "تكرار السطر",
        "Xóa dòng": "حذف السطر",
        "Comment dòng": "تعليق السطر",
        "Chưa chép gì trong phiên này": "لم يُنسخ شيء في هذه الجلسة",
        "Xoá lịch sử": "مسح السجل",
        "Search": "بحث",
        "Tìm…": "بحث…",
        "Tìm và thay…": "بحث واستبدال…",
        "Tìm trong thư mục…": "البحث في مجلد…",
        "Thay trong thư mục…": "الاستبدال في مجلد…",
        "Kết quả kế": "النتيجة التالية",
        "Kết quả trước": "النتيجة السابقة",
        "Đi tới dòng…": "الانتقال إلى السطر…",
        "Nhảy tới ngoặc khớp": "الانتقال إلى القوس المطابق",
        "Đánh dấu mọi dòng khớp…": "تعليم كل الأسطر المطابقة…",
        "Đảo dấu": "عكس العلامات",
        "Bỏ mọi dấu": "إزالة كل العلامات",
        "Chép dòng đã đánh dấu": "نسخ الأسطر المعلَّمة",
        "Xóa dòng đã đánh dấu": "حذف الأسطر المعلَّمة",
        "Chỉ giữ dòng đã đánh dấu": "الإبقاء على الأسطر المعلَّمة فقط",
        "Lines": "الأسطر",
        "Sắp xếp A→Z": "ترتيب أ→ي",
        "Sắp xếp Z→A": "ترتيب ي→أ",
        "Sắp xếp tự nhiên": "ترتيب طبيعي",
        "Khử trùng lặp": "إزالة المكرر",
        "Đảo thứ tự dòng": "عكس ترتيب الأسطر",
        "Dời dòng lên": "تحريك السطر لأعلى",
        "Dời dòng xuống": "تحريك السطر لأسفل",
        "Ghép dòng": "دمج الأسطر",
        "Tách dòng theo độ dài…": "تقسيم الأسطر حسب الطول…",
        "Tách dòng theo ký tự…": "تقسيم الأسطر حسب حرف…",
        "Xóa dòng rỗng": "حذف الأسطر الفارغة",
        "Nén dòng trống liên tiếp": "ضغط الأسطر الفارغة المتتالية",
        "Cắt khoảng trắng cuối dòng": "إزالة المسافات في نهاية السطر",
        "Tab → Space": "Tab ← مسافة",
        "Space → Tab": "مسافة ← Tab",
        "HOA": "أحرف كبيرة",
        "thường": "أحرف صغيرة",
        "Chữ Hoa Đầu Từ": "أول حرف من كل كلمة كبير",
        "Chữ hoa đầu câu": "أول حرف من الجملة كبير",
        "Đảo hoa/thường": "عكس حالة الأحرف",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: اختيار الورقة…",
        "Xem dạng bảng / văn bản": "تبديل عرض الجدول / النص",
        "Xóa cột…": "حذف عمود…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "التحقق من البيانات (عدد الأعمدة · الأنواع)",
        "Bàn làm sạch dữ liệu…": "طاولة تنظيف البيانات…",
        "Chạy công thức làm sạch…": "تشغيل وصفة تنظيف…",
        "Chuyển đổi…": "تحويل…",
        "Đổi dấu phân tách…": "تغيير الفاصل…",
        "Xuất sang JSON…": "تصدير إلى JSON…",
        "Format": "تنسيق",
        "Bảng mã…": "الترميز…",
        "Xuống dòng…": "نهايات الأسطر…",
        "Chuẩn hóa Unicode…": "توحيد Unicode…",
        "JSON: định dạng lại": "JSON: تنسيق",
        "JSON: thu gọn một dòng": "JSON: ضغط في سطر واحد",
        "JSON: sắp xếp khóa": "JSON: ترتيب المفاتيح",
        "JSON: truy vấn JSONPath…": "JSON: استعلام JSONPath…",
        "CSV: truy vấn SQL…": "CSV: استعلام SQL…",
        "Truy vấn SQL": "استعلام SQL",
        "Đang chạy…": "قيد التشغيل…",
        "Xuất ra tab mới": "تصدير إلى علامة تبويب جديدة",
        "Tài liệu rỗng — không có bảng để truy vấn": "مستند فارغ — لا يوجد جدول للاستعلام",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "ليس جدول CSV — السطر الأول يحتوي على عمود واحد فقط",
        "Không đọc được câu truy vấn": "تعذّرت قراءة الاستعلام",
        "Không kiểm được câu truy vấn": "تعذّر التحقق من الاستعلام",
        "Vàng (mặc định)": "أصفر (افتراضي)",
        "Xanh dương": "أزرق",
        "Xanh lá": "أخضر",
        "Vàng đất": "مغرة",
        "Tím": "بنفسجي",
        "Hồng": "وردي",
        "Xanh ngọc": "فيروزي",
        "Cam": "برتقالي",
        "Xám lam": "رمادي أردوازي",
        "Văn bản": "نص",
        "Dãy số": "متتالية رقمية",
        "Dãy ngày": "متتالية تواريخ",
        "Chữ HOA (hex)": "أحرف كبيرة (ست عشري)",
        "Bắt đầu": "البداية",
        "Bước": "الخطوة",
        "Đệm 0 tới": "الحشو بالأصفار حتى",
        "Hệ": "الأساس",
        "Ngày đầu": "التاريخ الأول",
        "Định dạng": "التنسيق",
        "Chèn": "إدراج",
        "Huỷ": "إلغاء",
        "Chuyển đổi định dạng": "تحويل التنسيق",
        "Xem trước 5 hàng đầu": "معاينة أول ٥ صفوف",
        "Tạo tab mới": "فتح في علامة تبويب جديدة",
        "Lưu ra file…": "حفظ في ملف…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "تُفتح النتيجة في علامة تبويب جديدة غير محفوظة. يبقى المستند الأصلي دون تغيير.",
        "Chạy trên tài liệu này": "التشغيل على هذا المستند",
        "Chạy trên thư mục…": "التشغيل على مجلد…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "الوصفة كاملة خطوة تراجع واحدة. يبقى الملف على القرص دون تغيير حتى تحفظ.",
        "tắt": "متوقف",
        "không thấy cột": "لم يُعثر على العمود",
        "sẵn sàng": "جاهز",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "يظل يشغل نواة من المعالج حتى يُغلق التطبيق.",
        "Script không trả về gì": "لم يُرجع البرنامج النصي شيئًا",
        "Không dựng được máy JavaScript": "تعذّر إنشاء محرك JavaScript",
        "Lỗi JavaScript không rõ": "خطأ JavaScript غير معروف",
        "Bảng": "جدول",
        "Áp sắp xếp vào file": "تطبيق الترتيب على الملف",
        "Chuyển đổi ▾": "تحويل ▾",
        "Xuất dòng khớp": "تصدير الصفوف المطابقة",
        "Ẩn cột này": "إخفاء هذا العمود",
        "Đổi tên tiêu đề…": "إعادة تسمية العنوان…",
        "Chèn cột trống bên trái": "إدراج عمود فارغ على اليسار",
        "Chèn cột trống bên phải": "إدراج عمود فارغ على اليمين",
        "Xóa cột này khỏi file…": "حذف هذا العمود من الملف…",
        "Phải còn ít nhất một cột đang hiện": "يجب أن يبقى عمود واحد ظاهرًا على الأقل",
        "Đang sắp xếp…": "جارٍ الترتيب…",
        "Trở về thứ tự trong file": "العودة إلى ترتيب الملف",
        "trăm hàng đầu": "أول مئة صف",
        "chọn cột": "اختيار الأعمدة",
        "đặt tên cột kết quả": "تسمية عمود في النتيجة",
        "lọc theo chữ": "التصفية حسب النص",
        "ô rỗng": "الخلايا الفارغة",
        "ghép điều kiện": "دمج الشروط",
        "đếm hàng": "عدّ الصفوف",
        "gộp nhóm": "التجميع والتلخيص",
        "nhỏ nhất, lớn nhất": "الأصغر، الأكبر",
        "sắp xếp và cắt": "الترتيب والتحديد",
        "tên cột có dấu cách": "اسم عمود يحتوي مسافات",
        "Truy vấn bị dừng giữa chừng": "تم قطع الاستعلام",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "غير مدعوم: JOIN · استعلام فرعي · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · دوال النوافذ",
        "XML: định dạng lại": "XML: تنسيق",
        "XML: thu gọn một dòng": "XML: ضغط في سطر واحد",
        "XML: kiểm cú pháp": "XML: فحص البنية",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: فحص المفاتيح المكررة والإزاحة",
        "View": "عرض",
        "Ẩn/hiện sidebar (Function List)": "إظهار/إخفاء الشريط الجانبي (قائمة الدوال)",
        "Ẩn/hiện bản đồ tài liệu": "إظهار/إخفاء خريطة المستند",
        "Gấp / mở khối tại con nháy": "طي / بسط الكتلة عند المؤشر",
        "Gấp tất cả": "طي الكل",
        "Bỏ gấp tất cả": "بسط الكل",
        "Gấp theo cấp": "الطي حسب المستوى",
        "Cấp %d": "المستوى %d",
        "Đã gấp %d khối ở cấp %d": "طُويت %d {zero=كتلة|one=كتلة|two=كتلتان|few=كتل|many=كتلة|other=كتلة} عند المستوى %d",
        "Tài liệu này chỉ sâu %d cấp": "عمق هذا المستند %d {zero=مستوى|one=مستوى|two=مستويان|few=مستويات|many=مستوى|other=مستوى} فقط",
        "mermaid: không đọc được bản kê": "mermaid: تعذّرت قراءة البيان",
        "Kiểm tra bản cập nhật…": "التحقق من التحديثات…",
        "Kiểm tra bản cập nhật": "التحقق من التحديثات",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "تُحدَّث نسخ App Store عبر Mac App Store، لا عبر GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "لا يملك هذا الإصدار مفتاح توقيع للتحديثات، لذا لا يستطيع البحث عنها.",
        "Phóng to chữ": "تكبير النص",
        "Thu nhỏ chữ": "تصغير النص",
        "Cỡ chữ gốc": "الحجم الفعلي",
        "Chia đôi theo chiều dọc": "تقسيم رأسي",
        "Chia đôi theo chiều ngang": "تقسيم أفقي",
        "Bỏ chia đôi": "إغلاق التقسيم",
        "Mở tab này ở nửa kia": "فتح علامة التبويب هذه في اللوح الآخر",
        "Nhảy sang nửa kia": "الانتقال إلى اللوح الآخر",
        "Ngắt dòng (tắt / cửa sổ / cột)": "التفاف الأسطر (متوقف / النافذة / العمود)",
        "Ngắt dòng tại cột…": "الالتفاف عند العمود…",
        "Đánh dấu dòng này": "تعليم هذا السطر",
        "Dấu kế tiếp": "العلامة التالية",
        "Dấu trước đó": "العلامة السابقة",
        "Màu đánh dấu…": "لون العلامات…",
        "Hiện tất cả ký tự ẩn": "إظهار كل المحارف غير المرئية",
        "  Khoảng trắng": "  المسافات",
        "  Tab": "  علامات الجدولة",
        "  Xuống dòng": "  نهايات الأسطر",
        "  NBSP · zero-width · điều khiển": "  NBSP · عرض صفري · تحكّم",
        "Xem nhị phân": "عرض ثنائي",
        "Chế độ CSV (tô màu theo cột)": "وضع CSV (أعمدة ملوّنة)",
        "Macro": "ماكرو",
        "Bắt đầu / dừng ghi": "بدء / إيقاف التسجيل",
        "Phát lại": "تشغيل",
        "Phát nhiều lần…": "تشغيل عدة مرات…",
        "Phát đến cuối tài liệu": "التشغيل حتى نهاية المستند",
        "Chạy trên mọi tab": "التشغيل على كل علامات التبويب",
        "Hủy macro đang chạy": "إلغاء الماكرو الجاري",
        "Lưu macro…": "حفظ الماكرو…",
        "Macro đã lưu…": "وحدات الماكرو المحفوظة…",
        "Help": "مساعدة",
        "Trợ giúp GEditor": "مساعدة GEditor",
        "Giới thiệu tính năng": "جولة في الميزات",
        "Di cư từ Notepad++": "الانتقال من Notepad++",
        "Tìm": "بحث",
        "Thay bằng": "استبدال بـ",
        "Kế": "التالي",
        "Trước": "السابق",
        "Đếm": "عدّ",
        "Đóng": "إغلاق",
        "Kiểm theo JSON Schema…": "التحقق عبر مخطط JSON…",
        "Chọn tệp JSON Schema": "اختر ملف مخطط JSON",
        "Không thấy lỗi nào theo schema này.": "لم يُعثر على مشكلات وفق هذا المخطط.",
        "JSON Schema": "مخطط JSON",
        "Kiểm cú pháp đồ thị": "فحص بنية الرسم البياني",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "تعذّر التعرّف على صيغة الرسم البياني — يلزم امتداد ‎.dot أو ‎.gv أو ‎.cypher أو ‎.ttl أو ‎.graphml.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "لم يُعثر على أخطاء في بنية %@ (الفحص ليس شاملًا).",
        "Cú pháp %@": "بنية %@",
        "không phải một đối tượng JSON": "ليس كائن JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "تنقيب النصوص (n-gram، TF-IDF)",
        "Tài liệu rỗng.": "المستند فارغ.",
        "Không rút được từ khoá nào.": "تعذّر استخراج أي كلمة مفتاحية.",
        "Từ khoá": "الكلمات المفتاحية",
        "%d từ khoá · %d token · %d tài liệu": "%d {zero=كلمة مفتاحية|one=كلمة مفتاحية|two=كلمتان مفتاحيتان|few=كلمات مفتاحية|many=كلمة مفتاحية|other=كلمة مفتاحية} · %d {zero=رمز|one=رمز|two=رمزان|few=رموز|many=رمزًا|other=رمز} · %d {zero=مستند|one=مستند|two=مستندان|few=مستندات|many=مستندًا|other=مستند}",
        "Tô lên tài liệu": "التعليم في المستند",
        "Đánh dấu entity từ danh sách…": "تعليم الكيانات من قائمة…",
        "Chọn danh sách entity (CSV hoặc JSON)": "اختر قائمة كيانات (CSV أو JSON)",
        "Không đọc được danh sách entity.": "تعذّرت قراءة قائمة الكيانات.",
        "Danh sách entity rỗng.": "قائمة الكيانات فارغة.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "لم يُعثر على كيانات في المستند (%d محمّلة).",
        "%d lần xuất hiện · %@": "%d {zero=ظهور|one=ظهور|two=ظهوران|few=ظهورات|many=ظهورًا|other=ظهور} · %@",
        "Chuyển đổi tri thức…": "تحويل المعرفة…",
        "Chuyển đổi: %@ → %@": "التحويل: %@ ← %@",
        "Không chuyển đổi được.": "تعذّر التحويل.",
        "Xem trước cắt chunk…": "معاينة التقطيع…",
        "Cỡ cố định 800B, chồng 100B": "حجم ثابت ٨٠٠ بايت، تداخل ١٠٠ بايت",
        "Theo câu (≤ 800B)": "حسب الجملة (≤ ٨٠٠ بايت)",
        "Theo heading Markdown": "حسب عنوان Markdown",
        "Tài liệu rỗng — không có chunk nào.": "مستند فارغ — لا توجد مقاطع.",
        "%d chunk · trung bình %d B · %@": "%d {zero=مقطع|one=مقطع|two=مقطعان|few=مقاطع|many=مقطعًا|other=مقطع} · بمتوسط %d بايت · %@",
        "Xuất JSONL": "تصدير JSONL",
        "Chunk JSONL": "مقاطع JSONL",
        "Mở triple/edge dạng bảng": "فتح الثلاثيات/الحواف كجدول",
        "Bảng triple": "جدول الثلاثيات",
        "Tài liệu này không có dòng triple nào.": "لا يحتوي هذا المستند على أي سطر ثلاثي.",
        "Không đọc được triple nào — dòng %d: %@": "تعذّرت قراءة أي ثلاثي — السطر %d: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "قُرئت %d {zero=ثلاثية|one=ثلاثية|two=ثلاثيتان|few=ثلاثيات|many=ثلاثية|other=ثلاثية} · تُخطّي %d {zero=سطر تالف|one=سطر تالف|two=سطران تالفان|few=أسطر تالفة|many=سطرًا تالفًا|other=سطر تالف} (الأول: السطر %d)",
        "Trùng lặp mờ theo cột…": "المكرر التقريبي حسب العمود…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "المكرر التقريبي — العمود «%@»: %d {zero=مجموعة مرشّحة|one=مجموعة مرشّحة|two=مجموعتان مرشّحتان|few=مجموعات مرشّحة|many=مجموعة مرشّحة|other=مجموعة مرشّحة}",
        "Gộp": "دمج",
        "Giống": "تطابق",
        "Các giá trị trong cụm": "القيم في المجموعة",
        "Gộp về": "الدمج في",
        "Gộp các cụm đã chọn": "دمج المجموعات المحددة",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "لم تُحدَّد أي مجموعة — الضغط على «دمج» لن يغيّر شيئًا. لا يدمج التطبيق من تلقاء نفسه أبدًا.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "حُدِّدت %d {zero=مجموعة|one=مجموعة|two=مجموعتان|few=مجموعات|many=مجموعة|other=مجموعة} · ستتغير %d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} · خطوة تراجع واحدة",
        "Không quét được cột này.": "تعذّر فحص هذا العمود.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "لا يحتوي العمود «%@» على مجموعات مكرر تقريبي.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "لم تُدمج أي مجموعة — المستند دون تغيير.",
        "Khử trùng lặp mờ · cột %@": "إزالة التكرار التقريبي · العمود %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "دُمجت %d {zero=مجموعة|one=مجموعة|two=مجموعتان|few=مجموعات|many=مجموعة|other=مجموعة} · تغيّرت %d {zero=خلية|one=خلية|two=خليتان|few=خلايا|many=خلية|other=خلية}",
        "Báo cáo làm sạch": "تقرير التنظيف",
        "# Báo cáo làm sạch — %@\n\n": "# تقرير التنظيف — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## المطبَّق (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_لم تُطبَّق أي خطوة._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## ملف البيانات\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%d {zero=عمود|one=عمود|two=عمودان|few=أعمدة|many=عمودًا|other=عمود} · %d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} · فُحص في %.1f ث_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| العمود | النوع | فارغ | مميّز | الأصغر | الأكبر | المتوسط |\n",
        "\n### Giá trị bất thường\n\n": "\n### القيم الشاذة\n\n",
        "hàng %d: %@": "الصف %d: %@",
        "- cột «%@» — %d ô: %@\n": "- العمود «%@» — %d {zero=خلية|one=خلية|two=خليتان|few=خلايا|many=خلية|other=خلية}: %@\n",
        "\n## Còn lại (%d)\n\n": "\n## المتبقي (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_لم تعد هناك ملاحظات._\n",
        "- cột «%@»: %@\n": "- العمود «%@»: %@\n",
        "Cắt khoảng trắng khi lưu": "إزالة المسافات عند الحفظ",
        "Chuẩn hóa xuống dòng": "توحيد نهايات الأسطر",
        "trước đó": "السابق",
        "Không mở lại được thư mục «%@» của phiên trước": "تعذّرت إعادة فتح المجلد «%@» من الجلسة السابقة",
        " (và %d file khác)": " (و%d {zero=ملف|one=ملف|two=ملفان|few=ملفات|many=ملفًا|other=ملف} آخر)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "تعذّرت إعادة فتح %d {zero=علامة تبويب|one=علامة تبويب|two=علامتي تبويب|few=علامات تبويب|many=علامة تبويب|other=علامة تبويب}: %@%@ — لم تعد الملفات في مكانها السابق.",
        "Không đọc được nội dung từ ống dẫn": "تعذّرت قراءة المُدخل من الأنبوب",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "ستُزال المسافات في نهاية السطر عند كل حفظ",
        "Không cắt khoảng trắng khi lưu nữa": "لم تعد المسافات تُزال عند الحفظ",
        "Chưa đặt tên.txt": "بدون عنوان.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "سيؤدي تحويل الترميز إلى فقدان محارف",
        "Vẫn lưu": "الحفظ على أي حال",
        "Tài liệu có thay đổi chưa lưu": "يحتوي المستند على تغييرات غير محفوظة",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "الإغلاق دون حفظ سيتجاهلها.",
        "Bỏ thay đổi": "تجاهل التغييرات",
        "Đi tới dòng": "الانتقال إلى السطر",
        "Tài liệu có %d dòng.": "يحتوي المستند على %d {zero=سطر|one=سطر|two=سطرين|few=أسطر|many=سطرًا|other=سطر}.",
        "Số dòng": "رقم السطر",
        "Đi tới": "انتقال",
        "Diễn giải lại theo…": "إعادة التفسير كـ…",
        "Chuyển đổi sang…": "التحويل إلى…",
        "Không diễn giải lại được": "تعذّرت إعادة التفسير",
        "Bảng mã %@ không chứa hết ký tự": "لا يستطيع %@ تمثيل كل المحارف",
        "Vẫn chọn": "الاختيار على أي حال",
        "Cột %d": "العمود %d",
        "Cột %d: %@": "العمود %d: %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "الأعمدة المخفية: %@ (%d) — أعِدها من قائمة السياق في صف العناوين",
        "Hiện lại: %@": "إظهار مرة أخرى: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "أُخفي العمود %@ — ما زال سليمًا في الملف",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "مرتَّب حسب %@ %@ · للعرض فقط",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "مرتَّب: %@ %@ (للعرض فقط)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ صف مطابق — البحث مستمر…",
        "%d / %d dòng khớp": "%d / %d {zero=صف مطابق|one=صف مطابق|two=صفان مطابقان|few=صفوف مطابقة|many=صفًا مطابقًا|other=صف مطابق}",
        "Không tìm thấy lỗi trong %d hàng": "لم يُعثر على مشكلات في %d {zero=صف|one=صف|two=صفين|few=صفوف|many=صفًا|other=صف}",
        "%d hàng lệch số cột": "%d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} بعدد أعمدة خاطئ",
        "%d ô sai kiểu dữ liệu": "%d {zero=خلية|one=خلية|two=خليتان|few=خلايا|many=خلية|other=خلية} بنوع بيانات خاطئ",
        " (đã dừng ở %d lỗi đầu)": " (توقّف عند أول %d {zero=مشكلة|one=مشكلة|two=مشكلتين|few=مشكلات|many=مشكلة|other=مشكلة})",
        "   —   kiểu nhận ra: ": "   —   الأنواع المكتشفة: ",
        "Hàng %d, cột %@: «%@» không phải %@": "الصف %d، العمود %@: «%@» ليس %@",
        "Column Editor — %d dòng": "محرر الأعمدة — %d {zero=سطر|one=سطر|two=سطران|few=أسطر|many=سطرًا|other=سطر}",
        "Phát hiện": "الملاحظات",
        "Hồ sơ dữ liệu": "ملف البيانات",
        "Hồ sơ dữ liệu — đang quét…": "ملف البيانات — جارٍ الفحص…",
        "Lưu công thức…": "حفظ الوصفة…",
        "Xuất báo cáo": "تصدير التقرير",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "لم تُطبَّق أي مجموعة · كل مجموعة خطوة تراجع",
        "quá nhiều giá trị": "قيم كثيرة جدًا",
        "hay gặp: ": "الأكثر شيوعًا: ",
        "Giá trị điền vào ô thiếu": "القيمة التي تُملأ بها الخلايا الفارغة",
        "Áp dụng": "تطبيق",
        "Không dựng được bản xem trước": "تعذّر بناء معاينة",
        "· giữ nguyên, không đọc được ·": "· تُرك كما هو، غير قابل للقراءة ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "تحويل العمود إلى ISO 8601 ‏(YYYY-MM-DD)",
        "Quy ước số cho cả cột": "اصطلاح الأرقام للعمود كله",
        "Làm gì với ô thiếu": "ما العمل مع الخلايا الفارغة",
        "Chuẩn hóa về ISO 8601": "التوحيد إلى ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "قراءة الخلايا الملتبسة باليوم أولًا ‏(31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "قراءة الخلايا الملتبسة بالشهر أولًا ‏(12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "تخطّي الخلايا الملتبسة وتصحيح المؤكدة فقط",
        "Về Việt/Âu (1.234,56)": "إلى الفيتنامي/الأوروبي ‏(1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "إلى الأنجلو-أمريكي ‏(1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "إلى الأنجلو-أمريكي، دون فاصل الآلاف ‏(1234.56)",
        "Điền một giá trị mặc định…": "الملء بقيمة افتراضية…",
        "Điền xuôi — lấy giá trị phía trên": "الملء لأسفل — أخذ القيمة من الأعلى",
        "Điền ngược — lấy giá trị phía dưới": "الملء لأعلى — أخذ القيمة من الأسفل",
        "Xóa hàng có ô thiếu ở cột này": "حذف الصفوف ذات الخلية الفارغة في هذا العمود",
        "Cắt khoảng trắng hai đầu": "إزالة المسافات من الطرفين",
        "Cắt hai đầu và nén khoảng trắng bên trong": "الإزالة من الطرفين وضغط المسافات الداخلية",
        "Pivot…": "جدول محوري…",
        "Nguồn…": "المصادر…",
        "Pivot — gộp theo cột": "جدول محوري — التجميع حسب العمود",
        "Hàng (gộp nhóm)": "الصفوف (التجميع)",
        "Giá trị": "القيم",
        "+ Hàng": "+ صف",
        "+ Giá trị": "+ قيمة",
        "Xoá hết": "مسح الكل",
        "Đưa vào ô truy vấn": "الإدراج في مربع الاستعلام",
        "Chọn cột để dựng câu truy vấn.": "اختر أعمدة لبناء الاستعلام.",
        "Không đọc được tên cột của bảng này.": "تعذّرت قراءة أسماء أعمدة هذا الجدول.",
        "Nguồn dữ liệu của truy vấn": "مصادر بيانات الاستعلام",
        "«%@» — tài liệu đang mở": "«%@» — المستند المفتوح",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ تغيّر الملف منذ تسجيله",
        "Thêm file…": "إضافة ملف…",
        "Bỏ hết": "إزالة الكل",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "تعذّر استنتاج اسم جدول من «%@» — أعد تسمية الملف.",
        "Tổng": "المجموع",
        "Trung bình": "المتوسط",
        "Nhỏ nhất": "الأصغر",
        "Lớn nhất": "الأكبر",
        "Đếm khác nhau": "عدد القيم المميزة",
        "Biểu đồ": "رسم بياني",
        "Xuất PNG": "تصدير PNG",
        "Xuất SVG": "تصدير SVG",
        "Bảng này không có cột số nào để vẽ.": "لا يحتوي هذا الجدول على عمود رقمي للرسم.",
        "Không dựng được ảnh PNG.": "تعذّر بناء صورة PNG.",
        "Kết quả truy vấn": "نتيجة الاستعلام",
        "Đã lưu %@": "حُفظ %@",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "رسم %@ للعمود «%@» — %d {zero=نقطة|one=نقطة|two=نقطتان|few=نقاط|many=نقطة|other=نقطة}، القيم من %@ إلى %@",
        "Cột": "أعمدة",
        "Đường": "خط",
        "Phân bố": "مدرّج تكراري",
        "Phân tán": "مبعثر",
        "Hộp": "صندوقي",
        "CSV: chất lượng dữ liệu…": "CSV: جودة البيانات…",
        "Chất lượng dữ liệu": "جودة البيانات",
        "Xuất vi phạm ra tab mới": "تصدير المخالفات إلى علامة تبويب جديدة",
        "Mức": "المستوى",
        "Luật": "القاعدة",
        "Vi phạm": "المخالفات",
        "Tỷ lệ": "النسبة",
        "đạt": "ناجح",
        "lỗi": "خطأ",
        "cảnh báo": "تحذير",
        "hỏng": "معطوب",
        "Đã đánh dấu %d dòng vi phạm": "عُلِّم %d {zero=سطر مخالف|one=سطر مخالف|two=سطران مخالفان|few=أسطر مخالفة|many=سطرًا مخالفًا|other=سطر مخالف}",
        "Xu hướng": "الاتجاه",
        "Lúc chấm": "قُيِّم في",
        "Số hàng": "الصفوف",
        "Lệch": "الفارق",
        "Luật trượt": "القواعد الراسبة",
        "Điểm chất lượng": "درجة الجودة",
        "Điểm theo thời gian": "الدرجة عبر الزمن",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "لا يوجد سجل بعد — كل تقييم يضيف ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "سطرًا إلى ملف «‎.history.jsonl» بجوار القواعد.",
        "%d mốc trong lịch sử": "%d {zero=نقطة|one=نقطة|two=نقطتان|few=نقاط|many=نقطة|other=نقطة} في السجل",
        " · %d dòng KHÔNG đọc được": " · %d {zero=سطر غير قابل للقراءة|one=سطر غير قابل للقراءة|two=سطران غير قابلين للقراءة|few=أسطر غير قابلة للقراءة|many=سطرًا غير قابل للقراءة|other=سطر غير قابل للقراءة}",
        " · chọn hai dòng để so": " · اختر صفين للمقارنة",
        "điểm %+.1f": "الدرجة %+.1f",
        "không chiều nào tụt": "لم ينخفض أي بُعد",
        "tụt: ": "انخفض: ",
        "%d luật mới trượt: %@": "%d {zero=قاعدة رسبت حديثًا|one=قاعدة رسبت حديثًا|two=قاعدتان رسبتا حديثًا|few=قواعد رسبت حديثًا|many=قاعدة رسبت حديثًا|other=قاعدة رسبت حديثًا}: %@",
        "số hàng %+d": "الصفوف %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (و%d {zero=تحذير|one=تحذير|two=تحذيران|few=تحذيرات|many=تحذيرًا|other=تحذير} آخر في علامة تبويب الاتجاه)",
        "Không sửa tự động được: ": "لا يوجد إصلاح تلقائي: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "يفتح الأداة المناسبة في طاولة التنظيف، ثم يعيد التقييم فورًا.",
        "Xử lý giá trị thiếu…": "معالجة القيم المفقودة…",
        "Chuẩn hóa ngày…": "توحيد التواريخ…",
        "Khử trùng lặp…": "إزالة المكرر…",
        "Thay thế…": "استبدال…",
        "Xem các dòng sai": "عرض الصفوف الخاطئة",
        "Không tìm thấy cột «%@» trong bảng này.": "العمود «%@» غير موجود في هذا الجدول.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "أُزيل المكرر — «%@» صار فريدًا الآن. الدرجة: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "أُزيل المكرر، لكن «%@» ما زال فيه %d {zero=صف مكرر|one=صف مكرر|two=صفان مكرران|few=صفوف مكررة|many=صفًا مكررًا|other=صف مكرر} (كان: %d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "تشترك تلك الصفوف في المفتاح لا في السطر كله، لذا عليك النظر والاختيار ",
        "giữ hàng nào.": "أيّها تُبقي.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "تعذّرت قراءة أي قيمة تخالف هذه القاعدة.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%1$d {zero=قيمة خاطئة|one=قيمة خاطئة|two=قيمتان خاطئتان|few=قيم خاطئة|many=قيمة خاطئة|other=قيمة خاطئة} في العمود «%2$@» — املأ خانة الاستبدال ثم اضغط معاينة",
        "Đã chấm lại: %.0f/100": "أُعيد التقييم: %.0f/100",
        "Xem trước báo cáo": "معاينة التقرير",
        "Tham số…": "المعاملات…",
        "Xuất HTML…": "تصدير HTML…",
        "In / PDF…": "طباعة / PDF…",
        "%d khối chạy được · %d khối HỎNG": "نُفِّذت %d {zero=كتلة|one=كتلة|two=كتلتان|few=كتل|many=كتلة|other=كتلة} · فشلت %d {zero=كتلة|one=كتلة|two=كتلتان|few=كتل|many=كتلة|other=كتلة}",
        "%d khối chạy được": "نُفِّذت %d {zero=كتلة|one=كتلة|two=كتلتان|few=كتل|many=كتلة|other=كتلة}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · بيانات قديمة — تغيّر الملف المصدر؛ أعد البناء",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "تحتاج معاينة التقرير إلى مستند ‎.%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "لم يُعثر على مصدر بيانات — صرّح بـ «source: ملف.csv» في الـ frontmatter.",
        "Không dựng được báo cáo.": "تعذّر بناء التقرير.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "لا يصرّح هذا التقرير بأي معامل في الـ frontmatter.",
        "Tham số báo cáo": "معاملات التقرير",
        "Dựng lại": "إعادة البناء",
        "Đã xuất %@": "صُدِّر %@",
        "Báo cáo: xem trước": "التقرير: معاينة",
        "Báo cáo: sinh loạt…": "التقرير: توليد دفعي…",
        "không phải tài liệu .greport.md": "ليس مستند ‎.greport.md",
        "không phân tích được báo cáo": "تعذّر تحليل التقرير",
        "không tìm được dữ liệu nguồn": "تعذّر العثور على بيانات المصدر",
        "không đọc được danh sách tham số": "تعذّرت قراءة قائمة المعاملات",
        "Sinh loạt cần tài liệu đuôi .%@": "يحتاج التوليد الدفعي إلى مستند ‎.%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "اختر قائمة معاملات (CSV أو JSON)",
        "Chọn thư mục để ghi %d báo cáo": "اختر مجلدًا لـ %d {zero=تقرير|one=تقرير|two=تقريرين|few=تقارير|many=تقريرًا|other=تقرير}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "معاملات ناقصة ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "يشير إلى الملف المصدر نفسه — رُفضت الكتابة فوقه",
        "%d khối HỎNG": "فشلت %d {zero=كتلة|one=كتلة|two=كتلتان|few=كتل|many=كتلة|other=كتلة}",
        "Sinh loạt xong: %d tệp · %d hỏng": "انتهت الدفعة: %d {zero=ملف|one=ملف|two=ملفان|few=ملفات|many=ملفًا|other=ملف} · %d فاشل",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "تعذّر بناء %d {zero=مجموعة معاملات|one=مجموعة معاملات|two=مجموعتي معاملات|few=مجموعات معاملات|many=مجموعة معاملات|other=مجموعة معاملات} — انظر الملخص",
        "Sơ đồ Mermaid: xem trước": "مخطط Mermaid: معاينة",
        "Sơ đồ Mermaid: chèn mẫu…": "مخطط Mermaid: إدراج قالب…",
        "Sơ đồ Mermaid: định dạng lại": "مخطط Mermaid: إعادة التنسيق",
        "Nền trong suốt": "خلفية شفافة",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "لا يستطيع هذا الـ Mac تحويل المخطط إلى PNG — يلزم macOS 13. ما زال تصدير SVG يعمل.",
        "Lưu PNG %@…": "حفظ PNG ‏%@…",
        "Lưu SVG…": "حفظ SVG…",
        "Chép ảnh vào clipboard": "نسخ الصورة إلى الحافظة",
        "Màu thương hiệu…": "ألوان العلامة التجارية…",
        "Màu thương hiệu cho sơ đồ": "ألوان العلامة التجارية للمخططات",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "كل خانة لون بصيغة ‎#rrggbb. يُحفظ في «themes/mermaid-brand.json» — يمكن نسخه إلى Mac آخر.",
        "Màu chính": "اللون الأساسي",
        "Chữ trên nút": "نص العقد",
        "Viền": "الإطار",
        "Đường nối": "الروابط",
        "Nền khi xuất ảnh": "الخلفية عند التصدير",
        "Lưu và chèn %%{init}%% vào tài liệu": "الحفظ وإدراج %%{init}%% في المستند",
        "Đã lưu màu thương hiệu": "حُفظت ألوان العلامة التجارية",
        "Đã chép ảnh sơ đồ vào clipboard": "نُسخت صورة المخطط إلى الحافظة",
        "Đã lưu %@ — %@": "حُفظ %@ — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "يحتوي هذا المخطط على توجيه %%{init}%% مسبقًا — تُرك توجيهك كما هو.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "أُدرج %%{init}%% — صار المخطط يحمل ألوانه الخاصة",
        "Chèn màu thương hiệu vào sơ đồ": "إدراج ألوان العلامة التجارية في المخطط",
        "Định dạng sơ đồ Mermaid": "إعادة تنسيق مخطط Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "مصدر المخطط مرتّب بالفعل — لا شيء لتغييره",
        "Đã định dạng lại sơ đồ": "أُعيد تنسيق المخطط",
        "Đã định dạng lại %d sơ đồ": "أُعيد تنسيق %d {zero=مخطط|one=مخطط|two=مخططين|few=مخططات|many=مخططًا|other=مخطط}",
        "Thư viện mẫu sơ đồ": "مكتبة قوالب المخططات",
        "Mẫu sơ đồ đầy đủ": "قوالب مخططات كاملة",
        "Mẩu cú pháp": "مقتطفات بنية",
        "Đang soạn: %@": "قيد التحرير: %@",
        "Đã chèn mẫu «%@»": "أُدرج القالب «%@»",
        "Tài liệu đang ở chế độ chỉ đọc.": "هذا المستند للقراءة فقط.",
        "Sơ đồ Mermaid": "مخطط Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "لا يحتوي هذا المستند على أي كتلة mermaid.",
        "Thương hiệu": "العلامة التجارية",
        "Xuất…": "تصدير…",
        "Chưa có sơ đồ nào": "لا توجد مخططات بعد",
        "%d sơ đồ · %@": "%d {zero=مخطط|one=مخطط|two=مخططان|few=مخططات|many=مخططًا|other=مخطط} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "فشل %d/%d {zero=مخطط|one=مخطط|two=مخططان|few=مخططات|many=مخططًا|other=مخطط} — المخطط %d%@",
        ", dòng %d": "، السطر %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "لا يحتوي هذا المستند على كتلة ‎```mermaid وليس ملف ‎.mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "لم ينتهِ رسم أي مخطط بعد.",
        "Không tìm thấy «%@» trong mã sơ đồ": "لم يُعثر على «%@» في مصدر المخطط",
        "không dựng được hàng rào chặn mạng cho WKWebView": "تعذّر بناء حاجز الشبكة لـ WKWebView",
        "Luật kết hợp": "قواعد الاقتران",
        "Mỗi dòng một giỏ": "سلة واحدة لكل صف",
        "Hai cột: mã · item": "عمودان: المعرّف · العنصر",
        "Dạng dữ liệu giao dịch": "شكل بيانات المعاملات",
        "Cột giỏ hàng hoặc mã giao dịch": "عمود السلة أو معرّف المعاملة",
        "Cột item": "عمود العنصر",
        "Ký tự phân tách item": "محرف فصل العناصر",
        "Support tối thiểu, phần trăm": "أدنى support، نسبة مئوية",
        "Confidence tối thiểu, phần trăm": "أدنى confidence، نسبة مئوية",
        "Tách bởi:": "مفصول بـ:",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confidence ≥",
        "Bảng luật kết hợp": "جدول قواعد الاقتران",
        "Support": "Support",
        "Confidence": "Confidence",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "تنبيه",
        "%d giao dịch · %d item · %d luật": "%d {zero=معاملة|one=معاملة|two=معاملتان|few=معاملات|many=معاملة|other=معاملة} · %d {zero=عنصر|one=عنصر|two=عنصران|few=عناصر|many=عنصرًا|other=عنصر} · %d {zero=قاعدة|one=قاعدة|two=قاعدتان|few=قواعد|many=قاعدة|other=قاعدة}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — لم تبلغ أي قاعدة العتبات؛ اخفض support أو confidence",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — تَوقّف مبكرًا، الجدول غير مكتمل",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {zero=معاملة تحتوي|one=معاملة تحتوي|two=معاملتان تحتويان|few=معاملات تحتوي|many=معاملة تحتوي|other=معاملة تحتوي} الطرفين معًا",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "يحتاج شكل العمودين إلى عمودين مختلفين.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "عُلِّم %1$d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} في %2$d {zero=معاملة|one=معاملة|two=معاملتين|few=معاملات|many=معاملة|other=معاملة} تحتوي «%3$@»",
        "CSV: luật kết hợp…": "CSV: قواعد الاقتران…",
        "Khai phá theo nhóm": "التنقيب حسب المجموعة",
        "Cột nhóm": "عمود المجموعة",
        "Cột giá trị": "عمود القيم",
        "Cột thứ hai cho tương quan": "العمود الثاني للارتباط",
        "Cách xếp hạng": "طريقة الترتيب",
        "Nhóm theo:": "التجميع حسب:",
        "Giá trị:": "القيمة:",
        "Xếp theo:": "الترتيب حسب:",
        "Bảng xếp hạng nhóm": "جدول ترتيب المجموعات",
        "Nhóm": "المجموعة",
        "Hàng": "الصفوف",
        "Hàng rào riêng": "عتبة خاصة",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "فارق r",
        "Ghi chú": "ملاحظة",
        "không đo được": "غير قابل للقياس",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {zero=مجموعة|one=مجموعة|two=مجموعتان|few=مجموعات|many=مجموعة|other=مجموعة} · الارتباط المرجعي الكلي %@",
        " · ĐÃ CẮT %d nhóm": " · أُسقطت %d {zero=مجموعة|one=مجموعة|two=مجموعتان|few=مجموعات|many=مجموعة|other=مجموعة}",
        "Bảng này không có cột chữ nào để gom nhóm.": "لا يحتوي هذا الجدول على عمود نصي للتجميع.",
        "Bảng này không có cột số nào để khai phá.": "لا يحتوي هذا الجدول على عمود رقمي للتنقيب.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "عُلِّم %1$d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} من المجموعة «%2$@»",
        "CSV: khai phá theo nhóm…": "CSV: التنقيب حسب المجموعة…",
        "\u{2194}": "↔",
        "Dự báo": "التنبؤ",
        "Cột giá trị theo thời gian": "عمود القيم عبر الزمن",
        "Mô hình dự báo": "نموذج التنبؤ",
        "Số kỳ dự báo": "عدد الفترات المتنبأ بها",
        "Kết luận so với baseline": "الحكم مقارنةً بالنماذج المرجعية",
        "Mô hình:": "النموذج:",
        "Số kỳ:": "الفترات:",
        "Chu kỳ:": "الموسم:",
        "tự": "تلقائي",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "الدورة الموسمية؛ اتركها فارغة للاكتشاف التلقائي",
        "Bảng giá trị dự báo": "جدول القيم المتنبأ بها",
        "Kỳ": "الفترة",
        "Dải 80%": "نطاق ٨٠٪",
        "Dải 95%": "نطاق ٩٥٪",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "غير قابل للحساب",
        "Bảng này không có cột số nào để dự báo.": "لا يحتوي هذا الجدول على عمود رقمي للتنبؤ.",
        "Không dựng được dự báo cho cột này.": "تعذّر بناء تنبؤ لهذا العمود.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "يحتوي العمود «%@» على %d {zero=قيمة رقمية|one=قيمة رقمية|two=قيمتين رقميتين|few=قيم رقمية|many=قيمة رقمية|other=قيمة رقمية} فقط — يلزم ٤ على الأقل للتنبؤ.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# تُقرأ السلسلة بترتيب صفوف الملف تمامًا — دون إعادة ترتيب، ودون استنتاج عمود زمني.\n",
        "Sai số huấn luyện": "خطأ التدريب",
        "CSV: dự báo chuỗi thời gian…": "CSV: التنبؤ بالسلاسل الزمنية…",
        "Holt-Winters cộng": "Holt-Winters جمعي",
        "Holt-Winters nhân": "Holt-Winters ضربي",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "الأعمدة الداخلة في التجميع العنقودي",
        "Đường cong WCSS": "منحنى WCSS",
        "Phân cụm": "عنقود",
        "Chuẩn hoá:": "التحجيم:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "اختر عمودًا واحدًا على الأقل.",
        "Không đủ dữ liệu để dựng đường cong.": "لا توجد بيانات كافية لبناء المنحنى.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "يقترح الانحناء k = %d. ينخفض WCSS دائمًا مع زيادة k، فهذه حيلة لقراءة الرسم لا معيار إحصائي — انظر إلى المنحنى واحكم هل الانكسار واضح.",
        "WCSS theo k": "WCSS حسب k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "تقترح مسافة k القيمة eps = %@ ‏(minPts افتراضيًا ٢ × عدد الأعمدة = %d). %@",
        "Khoảng cách tới hàng xóm thứ k": "المسافة إلى الجار رقم k",
        "Cần ít nhất 2 cột số để phân cụm.": "يلزم عمودان رقميان على الأقل للتجميع العنقودي.",
        "Cụm theo %@ và %@": "عناقيد حسب %@ و%@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — وُجدت العناقيد في %d {zero=بُعد|one=بُعد|two=بُعدين|few=أبعاد|many=بُعدًا|other=بُعد}؛ يعرض الرسم أول بُعدين فقط",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# ضوضاء ‏(cluster_id = -1): %d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف}\n",
        "CSV: phân cụm…": "CSV: التجميع العنقودي…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- مراكز العناقيد (بالوحدات الأصلية) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "مصفوفة الارتباط",
        "Phương pháp tương quan": "طريقة الارتباط",
        "Tương quan không hàm ý nhân quả.": "الارتباط لا يعني السببية.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "أقوى زوج: %@ ↔ %@ = %@ ‏(n = %d). اضغط خلية لعرض مخطط الانتشار.",
        "Không cặp nào đo được.": "لا يمكن قياس أي زوج.",
        "%@ ↔ %@: %@ trên %d hàng": "%@ ↔ %@: %@ على %d {zero=صف|one=صف|two=صفين|few=صفوف|many=صفًا|other=صف}",
        "Cần ít nhất 2 cột số để tính tương quan.": "يلزم عمودان رقميان على الأقل لحساب الارتباط.",
        "Không đọc được cột «%@».": "تعذّرت قراءة العمود «%@».",
        "CSV: ma trận tương quan…": "CSV: مصفوفة الارتباط…",
        "Bất thường": "الشذوذات",
        "Danh sách bất thường": "قائمة الشذوذات",
        "Cột:": "العمود:",
        "Cột số cần xét": "العمود الرقمي المراد فحصه",
        "Cách:": "الطريقة:",
        "Phương pháp phát hiện": "طريقة الكشف",
        "Phương pháp đã dùng": "الطريقة المستخدمة",
        "Ngưỡng": "العتبة",
        "Đánh dấu": "تعليم",
        "Xuất tab mới": "تصدير إلى علامة تبويب جديدة",
        "Dòng": "السطر",
        "Điểm": "الدرجة",
        "Vì sao": "السبب",
        "nhẹ": "خفيف",
        "vừa": "متوسط",
        "nặng": "شديد",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} ‏(%.2f٪)",
        "Bảng này không có cột số nào để tìm bất thường.": "لا يحتوي هذا الجدول على عمود رقمي للبحث عن الشذوذات.",
        "Đã đánh dấu %d dòng bất thường": "عُلِّم %d {zero=سطر شاذ|one=سطر شاذ|two=سطران شاذان|few=أسطر شاذة|many=سطرًا شاذًا|other=سطر شاذ}",
        "CSV: tìm bất thường…": "CSV: البحث عن الشذوذات…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%d {zero=قاعدة، كلها ناجحة|one=قاعدة ناجحة|two=قاعدتان ناجحتان|few=قواعد، كلها ناجحة|many=قاعدة، كلها ناجحة|other=قاعدة، كلها ناجحة} · %d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} · %.0f مللي ثانية",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%d {zero=خطأ|one=خطأ|two=خطآن|few=أخطاء|many=خطأً|other=خطأ} · %d {zero=تحذير|one=تحذير|two=تحذيران|few=تحذيرات|many=تحذيرًا|other=تحذير} عبر %d {zero=قاعدة|one=قاعدة|two=قاعدتين|few=قواعد|many=قاعدة|other=قاعدة} · %d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} · %.0f مللي ثانية",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "احفظ المستند أولًا — تقع قواعد الجودة بجوار ملف البيانات.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "لا توجد مجموعة قواعد بعد. أنشئ الملف %@ ثم أعد الفتح.",
        "Lịch sử": "السجل",
        "Câu đã lưu": "الاستعلامات المحفوظة",
        "Lưu câu này…": "حفظ هذا الاستعلام…",
        "Lưu câu truy vấn": "حفظ الاستعلام",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "أعطه اسمًا لتجده لاحقًا. الاسم المكرر يستبدل السابق.",
        "Ví dụ: Doanh thu theo tỉnh": "مثال: الإيرادات حسب المحافظة",
        "Chưa nhập giá trị cho tham số: %@": "لم تُدخل قيمة للمعامل: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "تغيّرت الإضافة منذ موافقتك عليها — يرفض GEditor تشغيلها",
        "Chạy plugin chưa duyệt?": "تشغيل إضافة غير معتمدة؟",
        "Tôi tin file này — chạy": "أثق بهذا الملف — شغّله",
        "KHÔNG có chữ ký": "غير موقّعة",
        "Chữ ký: %@": "التوقيع: %@",
        "Đường dẫn: %@": "المسار: %@",
        "Thay": "استبدال",
        "Thay tất cả": "استبدال الكل",
        "Chuỗi thuần": "نص عادي",
        "Extended (\\n \\t \\xNN)": "موسّع ‏(\\n \\t \\xNN)",
        "Biểu thức chính quy": "تعبير نمطي",
        "Phân biệt hoa thường": "مطابقة حالة الأحرف",
        "Cả từ": "الكلمة كاملة",
        "Không có kết quả": "لا توجد نتائج",
        "Thử biểu thức chính quy…": "اختبار تعبير نمطي…",
        "Chế độ Log (tô theo mức)": "وضع السجلّات (لون حسب المستوى)",
        "Lọc log theo mức…": "تصفية السجلّات حسب المستوى…",
        "Chạy trên cả thư mục…": "التشغيل على المجلد كله…",
        "Lọc qua lệnh ngoài…": "التصفية عبر أمر خارجي…",
        "Script…": "البرامج النصية…",
        "Gói mở rộng…": "حزم التوسعة…",
        "Cửa sổ mới": "نافذة جديدة",
        "Tách tab ra cửa sổ mới": "فصل علامة التبويب في نافذة جديدة",
        "Chưa mở thư mục nào": "لا يوجد مجلد مفتوح",
        "Tìm file trong thư mục": "البحث عن ملف في المجلد",
        "Lọc theo tên": "التصفية حسب الاسم",
        "File mới…": "ملف جديد…",
        "Thư mục mới…": "مجلد جديد…",
        "Đổi tên…": "إعادة تسمية…",
        "Chuyển vào Thùng rác": "النقل إلى المهملات",
        "Hiện trong Finder": "الإظهار في Finder",
        "Đang đọc cấu trúc tài liệu…": "جارٍ قراءة بنية المستند…",
        "file này không có hàm nào": "لا يحتوي هذا الملف على دوال",
        "Không có gì khớp": "لا توجد مطابقات",
        "Văn bản thuần": "نص عادي",
        "🔒 Chỉ đọc": "🔒 للقراءة فقط",
        "Đang theo dõi": "قيد المتابعة",
        "ngắt tại cột": "الالتفاف عند العمود",
        "Cú pháp": "البنية",
        "Bấm để chèn vào ô truy vấn": "اضغط للإدراج في الاستعلام",
        "truy vấn không hợp lệ": "استعلام غير صالح",
        "khóa `ten` ở gốc": "المفتاح «الاسم» في الجذر",
        "khóa có dấu cách": "مفتاح يحتوي مسافات",
        "phần tử đầu": "العنصر الأول",
        "mọi phần tử": "كل العناصر",
        "lát cắt": "شريحة",
        "hợp nhiều chỉ số": "اتحاد فهارس",
        "mọi khóa `gia` ở mọi tầng": "كل مفاتيح «السعر» في كل المستويات",
        "mọi nút": "كل العقد",
        "lọc theo số": "التصفية حسب رقم",
        "lọc theo có mặt": "التصفية حسب الوجود",
        "Tới lỗi đầu tiên": "الانتقال إلى أول خطأ",
        "Cột doanh_thu là số": "عمود الإيرادات رقمي",
        "lọc…": "تصفية…",
        "Hủy": "إلغاء",
        "Thực hiện thay": "تنفيذ الاستبدال",
        "xem trước": "معاينة",
        "tương tác": "تفاعلي",
        "Soạn thảo": "التحرير",
        "Giao diện": "الواجهة",
        "Phím tắt": "اختصارات لوحة المفاتيح",
        "Cỡ chữ": "حجم النص",
        "Bề rộng TAB": "عرض علامة الجدولة",
        "Thụt lề bằng TAB": "الإزاحة بعلامات الجدولة",
        "Tự động thụt lề khi xuống dòng": "الإزاحة التلقائية عند سطر جديد",
        "Tô mọi kết quả tìm kiếm": "إبراز كل نتائج البحث",
        "Chuẩn hóa về NFC khi lưu": "التوحيد إلى NFC عند الحفظ",
        "Ngôn ngữ": "اللغة",
        "Nền": "المظهر",
        "Theo hệ thống": "حسب النظام",
        "Sáng": "فاتح",
        "Tối": "داكن",
        "Theme": "السمة",
        "Dùng preset Notepad++": "استخدام إعداد Notepad++ الجاهز",
        "Về phím mặc định": "العودة إلى المفاتيح الافتراضية",
        "Mở file cấu hình": "فتح ملف الإعدادات",
        "Xuất theme hiện tại": "تصدير السمة الحالية",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "يُطبَّق تغيير اللغة بالكامل عند التشغيل التالي.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "تعود المفاتيح الافتراضية عند التشغيل التالي.",
        "Xem trước Markdown": "معاينة Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "تستخدم المعاينة محرك Markdown الخاص بالنظام: لا جداول بعد ولا تلوين لكتل الشيفرة.",
        "Thử biểu thức chính quy": "اختبار تعبير نمطي",
        "Biểu thức": "التعبير",
        "Văn bản thử": "نص الاختبار",
        "Kết quả": "النتيجة",
        "Kết quả khớp": "المطابقات",
        "Biểu thức này làm gì": "ما الذي يفعله هذا التعبير",
        "Giải thích biểu thức": "شرح التعبير",
        "Chế độ tìm kiếm": "وضع البحث",
        "Kết quả tìm kiếm": "نتائج البحث",
        "Không khớp chỗ nào": "لا توجد مطابقات",
        " (đã cắt bớt)": " (مقتطع)",
        "Bản đồ tài liệu": "خريطة المستند",
        "Thanh tab": "شريط علامات التبويب",
        "Hàng tiêu đề cột": "صف عناوين الأعمدة",
        "Không có cột nào": "لا توجد أعمدة",
        "Cây thư mục workspace": "شجرة مساحة العمل",
        "Danh sách hàm và lớp": "قائمة الدوال والأصناف",
        "Kết quả tìm trong thư mục": "نتائج البحث في المجلد",
        "Bảng dữ liệu CSV": "جدول بيانات CSV",
        "Bàn làm sạch dữ liệu": "طاولة تنظيف البيانات",
        "Truy vấn JSONPath": "استعلام JSONPath",
        "Danh sách lỗi dữ liệu": "قائمة أخطاء البيانات",
        "Bộ đánh giá golden set…": "مُقيِّم المجموعة الذهبية…",
        "So với điểm ngoài (JSONL)…": "المقارنة بدرجات خارجية ‏(JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "اختر ملف درجات خارجية ‏(JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "إعادة تسمية العقدة المحددة",
        "Gộp các node đang chọn": "دمج العقد المحددة",
        "Tách node đang chọn": "تقسيم العقدة المحددة",
        "Trích subgraph đang chọn ra tab mới": "استخراج الرسم الفرعي المحدد إلى علامة تبويب جديدة",
        "Không có gì để đổi": "لا شيء لتغييره",
        "%@ — áp %d thay đổi?": "%@ — تطبيق %d {zero=تغيير|one=تغيير|two=تغييرين|few=تغييرات|many=تغييرًا|other=تغيير}؟",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%@: %d {zero=تغيير|one=تغيير|two=تغييران|few=تغييرات|many=تغييرًا|other=تغيير} · يتراجع Cmd-Z عن الدفعة كلها",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "ضع المؤشر على عقدة واحدة بالضبط ثم أعد المحاولة",
        "Đổi tên «%@»": "إعادة تسمية «%@»",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "ستتغير معها كل الحواف والتسميات التي تشير إلى هذه العقدة.",
        "Đổi tên node": "إعادة تسمية العقدة",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "حدّد عقدتين على الأقل ثم أعد المحاولة",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "الصيغة المعيارية «%@» — الأكثر تكرارًا، الأطول، بالتشكيل",
        "Gộp node": "دمج العقد",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "حدّد أسطر الحواف المراد نقلها ثم أعد المحاولة",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "يجب أن تلمس كل الأسطر المحددة عقدة واحدة بالضبط — حدّد أسطر حواف إضافية",
        "Tách «%@» — chuyển %d cạnh": "تقسيم «%@» — نقل %d {zero=حافة|one=حافة|two=حافتين|few=حواف|many=حافة|other=حافة}",
        "Cạnh tới: %@": "حواف إلى: %@",
        "Tách node": "تقسيم العقدة",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "المستند غير محفوظ — يحتاج الملف المستخرج إلى مكان بجواره",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "حدّد جزء الرسم المراد استخراجه ثم أعد المحاولة",
        "Gom biến thể entity → bảng duyệt": "تجميع صيغ الكيانات ← جدول المراجعة",
        "Áp bảng duyệt đã sửa": "تطبيق جدول المراجعة المعدّل",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "المستند غير محفوظ — يجب أن يقع جدول المراجعة بجوار ملف الرسم",
        "Không tìm thấy biến thể nào để gom": "لم يُعثر على صيغ للتجميع",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {zero=مجموعة صيغ|one=مجموعة صيغ|two=مجموعتا صيغ|few=مجموعات صيغ|many=مجموعة صيغ|other=مجموعة صيغ} — صحّح العمود «canonical» ثم شغّل «تطبيق جدول المراجعة»",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "لا يوجد جدول مراجعة «%@» — شغّل «تجميع صيغ الكيانات» أولًا",
        "Bảng duyệt không đọc được: %@": "جدول المراجعة غير قابل للقراءة: %@",
        "Bảng duyệt không có dòng nào cần đổi": "لا يحتوي جدول المراجعة على أي سطر يحتاج تغييرًا",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "لا يوجد موضع في الرسم يطابق جدول المراجعة",
        "Gom biến thể entity": "تجميع صيغ الكيانات",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "طُبِّق %d {zero=تغيير|one=تغيير|two=تغييران|few=تغييرات|many=تغييرًا|other=تغيير} · كُتب جدول الأسماء البديلة وقائمة العلامات بجوار الملف",
        "Áp %d thay đổi lên đồ thị?": "تطبيق %d {zero=تغيير|one=تغيير|two=تغييرين|few=تغييرات|many=تغييرًا|other=تغيير} على الرسم؟",
        "%d alias → dạng chuẩn.": "%d {zero=اسم بديل|one=اسم بديل|two=اسمان بديلان|few=أسماء بديلة|many=اسمًا بديلًا|other=اسم بديل} ← الصيغة المعيارية.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "دمج العقد (لا يمكن التراجع عنه بإعادة الكتابة):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {zero=اسم بديل غير موجود|one=اسم بديل غير موجود|two=اسمان بديلان غير موجودين|few=أسماء بديلة غير موجودة|many=اسمًا بديلًا غير موجود|other=اسم بديل غير موجود} في الرسم، وقد تُخطّي.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "تحليل التغطية: المقطع ↔ الكيان",
        "Xuất gói ngữ cảnh (JSONL)": "تصدير حزمة السياق ‏(JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "التغطية: المقطع ↔ الكيان ↔ الرسم",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %d {zero=كيان|one=كيان|two=كيانان|few=كيانات|many=كيانًا|other=كيان} · %d {zero=مقطع|one=مقطع|two=مقطعان|few=مقاطع|many=مقطعًا|other=مقطع} · %.0f٪ من الكيانات مذكورة · %.0f٪ من المقاطع تحتوي كيانًا",
        "Entity không chunk nào nhắc tới": "كيانات لا يذكرها أي مقطع",
        "Chunk mồ côi (không chứa entity nào)": "مقاطع يتيمة (بلا أي كيان)",
        "Node đồ thị không có entity đối ứng": "عقد رسم بلا كيان مقابل",
        "không có": "لا شيء",
        "Phương pháp": "الطريقة",
        "Không dựng được ánh xạ Chunk ↔ Entity": "تعذّر بناء التطابق: المقطع ↔ الكيان",
        "Chấm sức khoẻ đồ thị": "تقييم صحة الرسم",
        "sức khoẻ đồ thị": "صحة الرسم",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "الصحة %@/100 · %d {zero=خطأ|one=خطأ|two=خطآن|few=أخطاء|many=خطأً|other=خطأ} · %d {zero=انعكاس|one=انعكاس|two=انعكاسان|few=انعكاسات|many=انعكاسًا|other=انعكاس} · %d يتيم",
        "Lai với đồ thị": "هجين مع الرسم",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: تجاهل إشارة الرسم تمامًا، والنتيجة تطابق BM25 الصِرف",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α مرتفع: يعدّل الرسم ترتيب BM25 تعديلًا طفيفًا فقط",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α قرب القيمة الافتراضية ٠٫٧: يقود BM25 ويعدّل الرسم",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α منخفض: يقود الرسم ويفصل BM25 في التعادل فقط",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: إشارة الرسم وحدها؛ تتساوى المقاطع الخالية من الكيانات",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "المستند غير محفوظ — يحتاج الهجين إلى ملف رسم بجوار المدوّنة",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "لم يُعثر على ملف الرسم «%@» — يحتاجه الهجين للحصول على إشارته",
        "lai %.1f ms · %@": "هجين %.1f مللي ثانية · %@",
        "Thuật toán…": "الخوارزميات…",
        "PageRank (độ dày viền)": "PageRank ‏(سماكة الإطار)",
        "Cộng đồng (màu nền)": "المجتمعات (لون الخلفية)",
        "Thành phần liên thông": "المكوّنات المتصلة",
        "Xuất bảng node ra tab mới": "تصدير جدول العقد إلى علامة تبويب جديدة",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%d {zero=مكوّن|one=مكوّن|two=مكوّنان|few=مكوّنات|many=مكوّنًا|other=مكوّن} · الأكبر %d {zero=عقدة|one=عقدة|two=عقدتان|few=عقد|many=عقدة|other=عقدة} · %d عقدة يتيمة",
        "Tài liệu này không phải đồ thị DOT": "هذا المستند ليس رسم DOT",
        "Không dựng được bảng node/cạnh: %@": "تعذّر بناء جدول العقد/الحواف: %@",
        "%d hàng · %@": "%d {zero=صف|one=صف|two=صفان|few=صفوف|many=صفًا|other=صف} · %@",
        "Gán nhãn": "وسم",
        "Ghi chú (tuỳ chọn)": "ملاحظة (اختياري)",
        "Lưu record": "حفظ السجل",
        "Xuất CSV": "تصدير CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "المستند غير محفوظ — يجب أن يقع المُقيِّم بجوار ملف المدوّنة",
        "Không nạp được bộ đánh giá: %@": "تعذّر تحميل المُقيِّم: %@",
        "Không lưu được: %@": "تعذّر الحفظ: %@",
        "Bộ đánh giá chưa có record nào": "لا يحتوي المُقيِّم على أي سجل بعد",
        "Không ghi được: %@": "تعذّرت الكتابة: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "هذا المستند ليس ملف ‎.mmd، وليس DOT، ولا يحتوي كتلة mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {zero=عقدة|one=عقدة|two=عقدتان|few=عقد|many=عقدة|other=عقدة} · %d {zero=حافة|one=حافة|two=حافتان|few=حواف|many=حافة|other=حافة} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "مخطط Mermaid: إضافة عنصر…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "مخطط Mermaid: ربط العنصرين المحددين",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "مخطط Mermaid: تعديل تسمية العنصر المحدد…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "مخطط Mermaid: حذف العنصر المحدد",
        "Sơ đồ Mermaid: đưa message lên trên": "مخطط Mermaid: رفع الرسالة لأعلى",
        "Sơ đồ Mermaid: đưa message xuống dưới": "مخطط Mermaid: خفض الرسالة لأسفل",
        "Thêm phần tử": "إضافة عنصر",
        "Thêm participant": "إضافة مشارك",
        "Thêm mục": "إضافة إدخال",
        "Thêm mục sơ đồ": "إضافة إدخال إلى المخطط",
        "Sửa mục sơ đồ": "تعديل إدخال في المخطط",
        "Xoá mục sơ đồ": "حذف إدخال من المخطط",
        "Xoá phần tử": "حذف العنصر",
        "Sửa nhãn": "تعديل التسمية",
        "Đổi thứ tự message": "إعادة ترتيب الرسائل",
        "Tên mục": "اسم الإدخال",
        "Mục mới": "إدخال جديد",
        "Tên mục hiện trên sơ đồ.": "يظهر اسم الإدخال على المخطط.",
        "Bảng thuộc tính sơ đồ": "جدول خصائص المخطط",
        "Tài liệu này không có khối mermaid nào": "لا يحتوي هذا المستند على كتلة mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "المعرّف في مصدر المخطط — بلا مسافات. تُعدَّل التسمية لاحقًا بالنقر المزدوج.",
        "Để trống thì hiện chính định danh.": "إذا تُرك فارغًا، يُعرض المعرّف نفسه.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "تتغير التسمية الظاهرة فقط؛ يبقى معرّف العنصر كما هو.",
        "Không rõ «%@» là phần tử nào": "غير واضح أي عنصر هو «%@»",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "حدّد عنصرين بالضبط ثم أعد المحاولة",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "ضع المؤشر على عنصر واحد بالضبط ثم أعد المحاولة",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "اختر عنصرًا واحدًا للحذف، أو عنصرين تربطهما حافة",
        "Xoá «%@» và %d cạnh chạm nó?": "حذف «%@» و%d {zero=حافة تلامسه|one=حافة تلامسه|two=حافتين تلامسانه|few=حواف تلامسه|many=حافة تلامسه|other=حافة تلامسه}؟",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "تبقى العقد في الطرف الآخر من تلك الحواف — يُعاد التصريح بها مع تسميتها إذا كانت تعليمة الحافة تصريحها الوحيد.",
        "Sơ đồ «%@» chỉ soạn text — %@": "المخطط «%@» يُحرَّر نصًّا فقط — %@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: اسحب بين عنصرين للربط، وانقر نقرًا مزدوجًا لتعديل التسمية",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: اسحب بين مشاركَين لإضافة رسالة؛ أعد الترتيب من قائمة الأدوات",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: عدّل في جدول الخصائص أدناه",
        "Soạn trực quan đã bật": "التحرير المرئي مفعّل",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%@ · %d {zero=إدخال|one=إدخال|two=إدخالان|few=إدخالات|many=إدخالًا|other=إدخال} — عدّل مباشرة في الجدول، وكل خلية خطوة تراجع",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "للرسم الدائري رقم؛ ولـ gantt ما يأتي بعد النقطتين.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "مخطط Mermaid: استخراج الكتلة إلى ملف ‎.mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "مخطط Mermaid: إعادة تضمين الملف المُشار إليه",
        "Tách khối sơ đồ": "استخراج كتلة المخطط",
        "Nhúng khối sơ đồ": "تضمين كتلة المخطط",
        "Tách khối sơ đồ ra tệp riêng": "استخراج كتلة المخطط إلى ملف مستقل",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "يوضَع الملف بجوار المستند؛ وتحتفظ الكتلة بسطر إشارة ليكون التحرير في مكان واحد.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "المستند غير محفوظ — يحتاج ملف المخطط إلى مكان بجواره",
        "Đã có tệp «%@» — chọn tên khác": "الملف «%@» موجود بالفعل — اختر اسمًا آخر",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "استُخرج إلى «%@» — احتفظت الكتلة بسطر إشارة",
        "Mở tệp": "فتح الملف",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "أُعيد تضمين «%@»؛ ما زال الملف على القرص",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "تحتوي هذه الكتلة على مخطط حقيقي، لا إشارة",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "تشير هذه الكتلة إلى «%@» — افتح ذلك الملف للتحرير",
        "Không đọc được tệp sơ đồ %@": "تعذّرت قراءة ملف المخطط %@",
        "Soạn trực quan": "التحرير المرئي",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "اسحب من عقدة إلى أخرى لإضافة حافة؛ وانقر نقرًا مزدوجًا لتعديل التسمية. كل إجراء خطوة تراجع.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "التحرير المرئي: اسحب بين عقدتين لإضافة حافة، وانقر نقرًا مزدوجًا لتعديل التسمية",
        "Soạn trực quan đã tắt": "التحرير المرئي متوقف",
        "Thêm node…": "إضافة عقدة…",
        "Thêm cạnh giữa hai node đang chọn…": "إضافة حافة بين العقدتين المحددتين…",
        "Sửa nhãn node đang chọn…": "تعديل تسمية العقدة المحددة…",
        "Xoá node/cạnh đang chọn": "حذف العقدة/الحافة المحددة",
        "Thêm node": "إضافة عقدة",
        "Thêm cạnh": "إضافة حافة",
        "Sửa nhãn node": "تعديل تسمية العقدة",
        "Xoá node": "حذف العقدة",
        "Xoá cạnh": "حذف الحافة",
        "Cmd-Z hoàn tác": "‏Cmd-Z للتراجع",
        "Tài liệu đang ở chế độ chỉ đọc": "هذا المستند للقراءة فقط",
        "Nhãn của «%@»": "تسمية «%@»",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "تتغير التسمية الظاهرة فقط؛ يبقى معرّف العقدة كما هو.",
        "Không rõ «%@» là node nào": "غير واضح أي عقدة هي «%@»",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "معرّف العقدة في ملف DOT. تُعدَّل التسمية لاحقًا بالنقر المزدوج على الرسم.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "حدّد عقدتين بالضبط ثم أعد المحاولة",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "اختر عقدة واحدة للحذف، أو عقدتين تربطهما حافة",
        "Xoá node «%@» và %d cạnh chạm nó?": "حذف العقدة «%@» و%d {zero=حافة تلامسها|one=حافة تلامسها|two=حافتين تلامسانها|few=حواف تلامسها|many=حافة تلامسها|other=حافة تلامسها}؟",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "إذا بقيت حواف معلّقة، يعيد DOT إنشاء العقد منها — وستظهر العقدة المحذوفة مرة أخرى عند الرسم التالي.",
        "Phòng thí nghiệm truy hồi BM25": "مختبر الاسترجاع BM25",
        "Câu hỏi — Enter để tìm": "سؤال — اضغط Enter للبحث",
        "Đánh giá…": "تقييم…",
        "Đang dựng chỉ mục": "جارٍ بناء الفهرس",
        "Không chunk nào khớp": "لا يطابق أي مقطع",
        "kết quả trên": "أفضل النتائج",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: تُحسب كل كلمة مرة واحدة فقط مهما تكرر ظهورها",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 منخفض: تكرار الكلمة لا يضيف درجة تُذكر",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 قرب القيمة الافتراضية ١٫٢: يضيف التكرار درجة لكنها تتناقص",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 مرتفع: يُكافأ بقوة المقطع الذي يكرر كلمة كثيرًا",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: يُتجاهل الطول، ولا تُعاقب المقاطع الطويلة",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b منخفض: تُعاقب المقاطع الطويلة عقابًا خفيفًا",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b قرب القيمة الافتراضية ٠٫٧٥: تُعاقب المقاطع الطويلة عقابًا معتدلًا",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: أقصى عقوبة على الطول، وتُفضَّل المقاطع القصيرة",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: مختبر الاسترجاع…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "المستند غير محفوظ — يقع فهرس BM25 بجوار ملف المدوّنة، لذا يلزم مسار",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "هذا الملف ليس JSONL — يعمل Retrieval Lab على مدوّنة مقاطع",
        "Không dựng được chỉ mục BM25 cho tệp này": "تعذّر بناء فهرس BM25 لهذا الملف",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "المستند غير محفوظ — يلزم مسار مدوّنة لتوليد التقرير",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "اختر مجموعة تقييم ‏(CSV أو JSONL: السؤال + معرّف المقطع المتوقع)",
        "Đánh giá truy hồi": "تقييم الاسترجاع",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "غيّر k1 أو b أو k أعلاه ثم أعد النظر لمقارنة إعدادين؛ وأضف كتلة «compare» لتشغيل مجموعتَي معاملات بالتوازي على مجموعة التقييم نفسها.",
        "Lỗi": "خطأ",
        "   (%d…%d, trung bình %.0f)": "   ‏(%d…%d، المتوسط %.0f)",
        "Chế độ JSONL": "وضع JSONL",
        "Bản ghi": "سجل",
        "Chi tiết": "التفاصيل",
        "Bản ghi ở dòng": "السجل في السطر",
        "không phải JSON hợp lệ": "ليس JSON صالحًا",
        "bản ghi": "سجل",
        "dòng trắng": "أسطر فارغة",
        "không phải đối tượng": "ليس كائنًا",
        "bảng hiện": "الجدول المعروض",
        "ĐÃ HUỶ giữa chừng": "أُلغي في المنتصف",
        "Không lọc": "بلا تصفية",
        "bản ghi khớp bộ lọc": "سجلات تطابق المرشّح",
        "Đưa con nháy tới một dòng để xem bản ghi": "ضع المؤشر على سطر لرؤية السجل",
        "Không có bản ghi nào hỏng": "لا توجد سجلات تالفة",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "لم يُفحص بعد. أعد تشغيل «JSONL: فحص المقاطع» بعد التحقق.",
        "trường văn bản": "حقل نصي",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "المخطط (تخمين — يتغير باختيار حقل آخر)",
        "văn bản": "نص",
        "định danh": "معرّف",
        "metadata lồng": "بيانات وصفية متداخلة",
        "TRƯỜNG": "الحقل",
        "phủ": "التغطية",
        "nhiều kiểu": "أنواع متعددة",
        "ĐỘ DÀI — ký tự": "الطول — محارف",
        "ĐỘ DÀI — từ": "الطول — كلمات",
        "ĐỘ DÀI — token ước lượng": "الطول — رموز تقديرية",
        "RỖNG VÀ TRÙNG": "الفارغ والمكرر",
        "chunk rỗng": "مقاطع فارغة",
        "dòng": "أسطر",
        "nhóm trùng chính xác": "مجموعات مكرر تام",
        "dòng không đọc được, không vào thống kê": "أسطر غير قابلة للقراءة، خارج الإحصاء",
        "PHƯƠNG PHÁP": "الطريقة",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "«المحارف» تُحسب محارف Unicode (قيمًا مفردة) لا مجموعات معروضة",
        "«từ» tách theo khoảng trắng ASCII": "«الكلمات» تُفصل بمسافات ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "«الرموز» تُحسب بمقسّم مقاطع صوتية — وليس مقسّم النموذج",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "«المكرر» يعني المكرر التام؛ أما شبه المكرر ففي كتلة ‎```quality",
        "chunk": "مقاطع",
        "JSONL: kiểm và soi chunk…": "JSONL: التحقق من المقاطع وفحصها…",
        "Ảnh": "صورة",
        "PDF": "PDF",
        "Tài liệu Word": "مستند Word",
        "Bảng tính Excel": "جدول Excel",
        "Bản trình chiếu PowerPoint": "عرض PowerPoint",
        "File nén": "أرشيف",
        "Vừa khung": "الملاءمة للنافذة",
        "Chép ảnh": "نسخ الصورة",
        "Xoay": "تدوير",
        "Không đọc được ảnh «%@»": "تعذّرت قراءة الصورة «%@»",
        "Đã chép ảnh vào clipboard": "نُسخت الصورة إلى الحافظة",
        "Bôi vàng": "تظليل بالأصفر",
        "Gạch chân": "تسطير",
        "Ghi chú…": "ملاحظة…",
        "Bỏ chú thích": "إزالة التعليقات التوضيحية",
        "Lấy chữ ra tab mới": "استخراج النص إلى علامة تبويب جديدة",
        "Lưu bản có chú thích…": "حفظ النسخة المعلَّق عليها…",
        "Tìm trong PDF": "البحث في PDF",
        "Thêm": "إضافة",
        "Trang %d/%d": "الصفحة %d/%d",
        "Trang %d": "الصفحة %d",
        "Kết quả %d/%d": "النتيجة %d/%d",
        "0 kết quả": "٠ نتائج",
        "Không đọc được PDF «%@»": "تعذّرت قراءة ملف PDF «%@»",
        "PDF này có mật khẩu — chưa mở được nội dung": "ملف PDF هذا محمي بكلمة سر — المحتوى غير متاح",
        "Không thấy «%@» trong tài liệu": "لم يُعثر على «%@» في المستند",
        "Đã bôi vàng": "ظُلِّل",
        "Đã gạch chân": "سُطِّر",
        "Hãy bôi đen một đoạn chữ trước": "حدّد مقطعًا من النص أولًا",
        "Đã thêm ghi chú": "أُضيفت الملاحظة",
        "Trang này chưa có chú thích nào": "لا تحتوي هذه الصفحة على تعليقات توضيحية",
        "Đã bỏ %d chú thích trên trang này": "أُزيل %d {zero=تعليق توضيحي|one=تعليق توضيحي|two=تعليقان توضيحيان|few=تعليقات توضيحية|many=تعليقًا توضيحيًا|other=تعليق توضيحي} من هذه الصفحة",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "لا يحتوي ملف PDF هذا على طبقة نصية — على الأرجح أنه ممسوح ضوئيًا",
        "Không ghi được tệp": "تعذّرت كتابة الملف",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "الملف المكتوب لا يُفتح بشكل صحيح — لا تستخدم هذه النسخة",
        "Đã lưu %@ · %d trang": "حُفظ %@ · %d {zero=صفحة|one=صفحة|two=صفحتان|few=صفحات|many=صفحة|other=صفحة}",
        "Tên": "الاسم",
        "Kích thước": "الحجم",
        "Đã nén": "مضغوط",
        "Tỉ lệ": "النسبة",
        "Sửa lúc": "عُدّل في",
        "Mở mục đang chọn": "فتح العنصر المحدد",
        "Bung ra thư mục…": "الاستخراج إلى مجلد…",
        "Bung vào đây": "الاستخراج هنا",
        "%d mục": "%d {zero=عنصر|one=عنصر|two=عنصران|few=عناصر|many=عنصرًا|other=عنصر}",
        "giải nén ra %@": "استُخرج إلى %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— داخل ملف Office أرشيف، وهذه أجزاؤه",
        "Đã bung %d mục": "استُخرج %d {zero=عنصر|one=عنصر|two=عنصران|few=عناصر|many=عنصرًا|other=عنصر}",
        "%d mục hỏng": "%d {zero=عنصر تالف|one=عنصر تالف|two=عنصران تالفان|few=عناصر تالفة|many=عنصرًا تالفًا|other=عنصر تالف}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "رُفض %d {zero=عنصر|one=عنصر|two=عنصران|few=عناصر|many=عنصرًا|other=عنصر} لأن مساراتها تخرج من مجلد الوجهة",
        "Không mở được mục này": "تعذّر فتح هذا العنصر",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "لا يمكن بعد الكتابة مباشرة في %@ — استخدم «حفظ باسم…»",
        "Không có gì đổi": "لم يتغير شيء",
        "Đã ghi %d ô vào %@": "كُتبت %1$d {zero=خلية|one=خلية|two=خليتان|few=خلايا|many=خلية|other=خلية} في %2$@",
        "Đã ghi %d đoạn vào %@": "كُتبت %1$d {zero=فقرة|one=فقرة|two=فقرتان|few=فقرات|many=فقرة|other=فقرة} في %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "تعذّرت الكتابة في الملف — الأصل سليم",
        "dựng bài": "تجهيز حالة الاختبار",
        "Không ghi được settings.json": "تعذّرت الكتابة في settings.json",
        "Xoay trái": "تدوير لليسار",
        "Xoay phải": "تدوير لليمين",
        "Trang lên": "نقل الصفحة لأعلى",
        "Trang xuống": "نقل الصفحة لأسفل",
        "Xoá trang…": "حذف صفحات…",
        "Xoá trang": "حذف صفحات",
        "Trích trang…": "استخراج صفحات…",
        "Trích trang ra tệp mới": "استخراج الصفحات إلى ملف جديد",
        "Gộp tệp PDF…": "دمج ملف PDF…",
        "Tách tệp…": "تقسيم الملف…",
        "Tách tệp PDF": "تقسيم ملف PDF",
        "Xuất ảnh…": "تصدير صور…",
        "Xuất trang ra ảnh PNG": "تصدير الصفحات كصور PNG",
        "Hoàn tác trang": "تراجع عن تعديل الصفحة",
        "Lưu bản đã sửa…": "حفظ نسخة معدّلة…",
        "Phát": "تشغيل",
        "Tạm dừng": "إيقاف مؤقت",
        "Xem bình thường": "عرض عادي",
        "Chọn sheet": "اختيار الورقة",
        "Mở sheet": "فتح الورقة",
        "Bỏ và đổi sheet": "تجاهل وتبديل الورقة",
        "Bảng tính có %d sheet.": "يحتوي المصنّف على %d ورقة.",
        "Bảng tính này chỉ có một sheet: «%@»": "يحتوي هذا المصنّف على ورقة واحدة فقط: «%@»",
        "Bỏ phần chưa lưu của sheet này?": "هل تريد تجاهل التغييرات غير المحفوظة في هذه الورقة؟",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "تبديل الورقة يستبدل علامة التبويب بأكملها. ما لم يُحفظ بـ ⌘S سيُفقد.",
        "Chọn tệp PDF cần gộp vào": "اختر ملف PDF المراد دمجه",
        "Chọn thư mục ghi ảnh": "اختر مجلدًا للصور",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "اختر مكان الحفظ. يُكتب الملف الثاني بجانب هذا الملف.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "يحتوي المستند على %d صفحة. أدخل الصفحات المراد حذفها، مثل 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "يحتوي المستند على %d صفحة. أدخل الصفحات المراد استخراجها، مثل 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "يحتوي المستند على %d صفحة. أدخل الصفحات المراد تصديرها، مثل 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "يحتوي المستند على %d صفحة. أدخل الجزء المراد فصله، مثل 1-5؛ ويصبح الباقي ملفًا ثانيًا.",
        "Đã xoay trang %d": "تم تدوير الصفحة %d",
        "Đã xoá trang %@ · còn %d trang": "تم حذف الصفحات %@ · تبقّى %d صفحة",
        "Đã gộp %d trang từ «%@»": "تم دمج %d صفحة من «%@»",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "تم التقسيم إلى %@ (%d صفحة) و%@ (%d صفحة)",
        "Đã ghi %@ — %@ · %d trang": "تمت كتابة %@ — %@ · %d صفحة",
        "Đã xuất %d ảnh vào %@": "تم تصدير %d صورة إلى %@",
        "Chỉ xuất được %d/%d ảnh": "تم تصدير %d من %d صورة فقط",
        "Đã hoàn tác một thao tác trang": "تم التراجع عن عملية صفحة واحدة",
        "Không còn thao tác trang nào để hoàn tác": "لا توجد عمليات صفحات أخرى للتراجع عنها",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "لا يمكن حذف كل الصفحات — يجب أن تبقى صفحة واحدة على الأقل في ملف PDF",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "هذا النطاق هو المستند كاملًا — لا شيء لفصله",
        "«%@» có mật khẩu — chưa gộp được": "«%@» محمي بكلمة سر — تعذّر الدمج",
        "«%@» không có trang nào": "«%@» لا يحتوي على صفحات",
        "Đã ở trang đầu": "أنت في الصفحة الأولى بالفعل",
        "Đã ở trang cuối": "أنت في الصفحة الأخيرة بالفعل",
        "· đã sửa, chưa lưu": "· مُعدَّل، غير محفوظ",
        "Ảnh động · %d khung": "صورة متحركة · %d إطارًا",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "مستند غير محفوظ — لا يوجد ملف على القرص لعرضه ثنائيًا",
        "Lệnh này chỉ dùng cho bảng tính Excel": "هذا الأمر يعمل مع مصنّفات Excel فقط",
        "Không đọc được danh sách sheet": "تعذّرت قراءة قائمة الأوراق",
        "Không có sheet «%@»": "لا توجد ورقة باسم «%@»",
        "Không đọc được sheet «%@»": "تعذّرت قراءة الورقة «%@»",
        "Sheet «%@» · %d hàng": "الورقة «%@» · %d صف",
        "phần còn lại": "الباقي",
        "Lưu ý": "ملاحظة",
        "Cẩn thận": "تنبيه",
        "Xem thêm": "انظر أيضًا",
        "Chép": "نسخ",
        "Đã chép": "تم النسخ",
        "Chép đoạn mã mẫu": "نسخ نموذج الشيفرة",
        "Tìm trong trợ giúp": "البحث في المساعدة",
        "Lùi": "رجوع",
        "Bắt đầu dùng": "ابدأ",
        "Không mở cửa sổ này khi khởi động nữa": "لا تُظهر هذه النافذة عند بدء التشغيل",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "لم تُترجم المساعدة إلى هذه اللغة بعد — يُعرض النص الفيتنامي.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "الانتقال إلى الإزاحة (مثل 1F400 أو 0x1F400)",
        "Chép dòng đã chọn": "نسخ الصفوف المحددة",
        "Đã chép %d dòng": "تم نسخ %d صف",
        "Không đọc được «%@»": "تعذّرت قراءة «%@»",
        "Tệp rỗng": "ملف فارغ",
        "Không đọc được offset «%@»": "تعذّرت قراءة الإزاحة «%@»",
        "Offset 0x%@ vượt quá cỡ tệp": "الإزاحة 0x%@ تتجاوز حجم الملف",
        "Mở bằng ứng dụng khác…": "الفتح بتطبيق آخر…",
        "%d kênh": "%d قناة",
        "Không phát được «%@»": "تعذّر تشغيل «%@»",
        "Không phát được — %@": "تعذّر التشغيل — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "لا يتضمّن macOS مفكّك ترميز لصيغة %@ — هذا قيد في النظام وليس ملفًا تالفًا.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "لا يزال بإمكانك عرض البايتات في الوضع الثنائي، أو فتحه بتطبيق له مفكّك ترميز خاص.",
        "Ký…": "توقيع…",
        "Sửa chữ…": "تحرير النص…",
        "Sửa chữ": "تحرير النص",
        "Vẽ đè": "الرسم فوقه",
        "Ô chưa điền": "الحقل الفارغ التالي",
        "Xoá nội dung đã điền": "مسح القيم المُدخلة",
        "Tệp này không có ô biểu mẫu nào": "لا يحتوي هذا الملف على حقول نموذج",
        "Đã xoá nội dung của %d ô biểu mẫu": "تم مسح %d حقل نموذج",
        "Mọi ô biểu mẫu đều đã có nội dung": "جميع حقول النموذج مملوءة بالفعل",
        "Còn %d ô chưa điền": "لا يزال %d حقلًا فارغًا",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "نموذج قابل للتعبئة: %d حقل. اكتب فيها مباشرة، ثم «حفظ نسخة معدّلة…»",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "اختر صورة توقيع (الخلفية الشفافة تبدو أفضل)",
        "Không dựng được trang có chữ ký": "تعذّر إنشاء الصفحة الموقّعة",
        "Đã chèn chữ ký vào trang %d": "تم إدراج التوقيع في الصفحة %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "حدّد أولًا النص الذي تريد تغييره",
        "Vùng chọn quá nhỏ": "التحديد صغير جدًا",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "يُرسم النص الجديد فوق التحديد بخط النظام. النص القديم مغطّى وليس محذوفًا — لا يزال يمكن استخراجه، لذا هذه ليست طريقة حجب.",
        "Không dựng được trang đã sửa": "تعذّر إنشاء الصفحة المعدّلة",
        "Đã vẽ đè chữ mới lên trang %d": "تم رسم النص الجديد فوق الصفحة %d",
        "Đổi chế độ View / Code": "التبديل بين العرض والشيفرة",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "لا يوجد بعد عرض شجري لملفات JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "لا يوجد بعد عرض مخطط داخل علامة التبويب",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "لا يوجد بعد عرض مخطط تفصيلي لـ PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "لهذا الملف وضع عرض واحد فقط",
        "%d nút": "%d عقدة",
        "Không dựng được cây: %@": "تعذّر بناء الشجرة: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "المستند أكبر من أن يُبنى له شجرة — استخدم وضع الشيفرة",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "تعذّر إنشاء صفحات هذا الملف \u{2014} استخدم وضع Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "تُبنى الشرائح من النص؛ الصور والتخطيط الأصلي لم يُرسما بعد.",
        "Vừa ngang": "ملء العرض",
        "Thu nhỏ trang": "تصغير الصفحة",
        "Phóng to trang": "تكبير الصفحة",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "تعذّر العثور على «%@» في هذا المستند",
        "Chỗ khớp %d/%d": "المطابقة %d من %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "لم يُحدَّد أي نص في الصفحة.",
        "%d ký tự": "%d حرف",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "افتح الملفات مباشرة في وضع View إن توفّر",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· أُلغي في منتصف الطريق — الجدول غير مكتمل",
        "Chế độ hiển thị": "وضع العرض",
        "Đổi giữa View và Code (⌥⌘V)": "التبديل بين View وCode (⌥⌘V)",
        "Trang tài liệu": "صفحات المستند",
        "Chữ đã dựng": "نص مُنسَّق",
        "Trang bảng tính": "صفحات الجدول",
        "Sơ đồ": "مخطط",
        "Cây khoá–giá trị": "شجرة مفتاح–قيمة",
        "Bộ phát": "المشغّل",
        "Danh sách mục": "قائمة المدخلات",
        "Báo cáo đã dựng": "تقرير جاهز",
        "Tô theo mức": "ملوَّن حسب المستوى",
        "Trang slide": "صفحات الشرائح",
        "Dàn ý": "المخطط التفصيلي",
        "Lưu rồi dựng lại": "احفظ ثم أعد البناء",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "يعرض النسخة الموجودة على القرص — التعديلات غير المحفوظة ليست هنا.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "تعذّر على النظام بناء عارض المستند — استخدم وضع Code.",
        "Lưu tệp trước khi xem trang.": "احفظ الملف قبل عرض صفحاته.",
        "Đang ở chế độ Code": "في وضع Code الآن",
        "Đang ở chế độ View": "في وضع View الآن",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "تعرض الشيفرة المصدرية — انقر للانتقال إلى وضع View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "في وضع View — انقر للعودة إلى الشيفرة المصدرية (⌥⌘V)",
        "Tín hiệu: %@": "الإشارة: %@",
        "Lý do: %@": "السبب: %@",
        "Chi tiết: %@": "التفصيل: %@",
        "Mở báo cáo": "افتح التقرير",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "توقف GEditor فجأة في %@ — افتح التقرير لقراءته؛ لا يُرسل أي شيء.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "الحروف المتصلة — عند إيقافها يبقى كل حرف في خانته",
        "Chế độ CSV": "وضع CSV",
        "Dấu phân tách": "الفاصل",
        "Tự nhận diện": "التعرّف تلقائيًا",
        "Dấu phân tách: %@": "الفاصل: %@",
        "Theo đuôi tệp": "حسب امتداد الملف",
        "%d dấu cách": "%d مسافة",
        "Tài liệu đang sửa được": "هذا المستند قابل للتحرير",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "للقراءة فقط لأن الملف قيد المتابعة — أوقف المتابعة للتحرير",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "للقراءة فقط لأن الملف على القرص غير قابل للكتابة",
        "Đã mở khoá — tài liệu sửa được": "أُلغي القفل — صار المستند قابلًا للتحرير",
        "Nhân bản tệp": "تكرار الملف",
        "Đổi tên tệp…": "إعادة تسمية الملف…",
        "Chuyển tệp tới…": "نقل الملف إلى…",
        "XML: đánh giá XPath…": "XML: تقييم XPath…",
        "Đánh giá XPath": "تقييم XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "مثال: ‎//order/item[2]/@code · //*[@kind='A'] · count(//item)",
        "Đánh giá": "تقييم",
        "XPath không đọc được: %@": "تعذّرت قراءة تعبير XPath هذا: %@",
        "XPath «%@» không khớp node nào": "لم يطابق XPath «%@» أي عقدة",
        "XPath «%@» — %d node": "XPath «%@» — %d عقدة",
        "XPath «%@»: %d node": "XPath «%@»: %d عقدة",
        "Lưu tệp trước khi nhân bản.": "احفظ الملف قبل تكراره.",
        "Không nhân bản được": "تعذّر التكرار",
        "Đã nhân bản thành %@": "نُسخ باسم %@",
        "Lưu tệp trước khi đổi tên.": "احفظ الملف قبل إعادة تسميته.",
        "Đổi tên tệp": "إعادة تسمية الملف",
        "Tên hiện tại: %@": "الاسم الحالي: %@",
        "Đổi tên": "إعادة التسمية",
        "Tên tệp không hợp lệ": "اسم الملف هذا غير صالح",
        "Đã có tệp tên %@ ở đó": "يوجد هناك ملف باسم %@ بالفعل",
        "Lưu tệp trước khi chuyển.": "احفظ الملف قبل نقله.",
        "Chuyển tới": "انقل إلى هنا",
        "Thư mục đích đã có tệp tên %@": "المجلد الوجهة يحتوي بالفعل على ملف باسم %@",
        "Không chuyển được tệp": "تعذّر نقل الملف",
        "Đã chuyển tới %@": "نُقل إلى %@",
        "Bảng mã:": "الترميز:",
        "Xuống dòng:": "نهايات الأسطر:",
        "Riêng cho %@": "لـ %@ فقط",
        "    %d — dùng TAB": "    %d — استخدام الجدولة",
        "    %d — dùng dấu cách": "    %d — استخدام المسافات",
        "    Bỏ khai riêng, dùng cài đặt chung": "    أزل القاعدة الخاصة واستخدم الإعداد العام",
        "%@: thụt lề %d %@": "%@: إزاحة %d %@",
        "TAB": "جدولة",
        "dấu cách": "مسافات",
        "Xuất": "تصدير",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "افتح النتائج في لسان نصي — احفظه بـ ⌘S",
        "Lượt tìm trước đó": "عمليات بحث سابقة",
        "«%@» — %d kết quả": "«%@» — %d نتيجة",
        "Kết quả tìm «%@»": "نتائج البحث عن «%@»",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "رشِّح أسماء الملفات — مثل ‎*.csv;*.log (فارغ: كل ملف نصي)",
        "Thư mục %@ không có file văn bản nào": "المجلد %@ لا يحتوي على ملفات نصية",
        "Không tệp nào trong %@ khớp «%@»": "لا يطابق أي ملف في %@ التعبير «%@»",
        "%d byte · %d dòng": "%d بايت · %d سطر",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d بايت · %d سطر — أكبر من أن تُعدّ حروفه وكلماته",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d بايت · %d حرف · %d كلمة · %d سطر",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "يحتوي هذا المستند على %d سطر و%d بايت. اكتب رقم سطر أو «سطر,عمود» أو «@بايت».",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "تعذّرت قراءة «%@» — اكتب رقم سطر أو «سطر,عمود» أو «@بايت»",
    ]
}
