import Foundation

/// Bảng dịch tiếng Pháp. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let fr: [String: String] = [
        "Bản đã lưu…": "Versions enregistrées…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Ce document n’a jamais été enregistré — aucun historique",
        "Chưa có bản đã lưu nào trước đó": "Aucune version enregistrée antérieure",
        "Không đọc được bản ấy": "Impossible de lire cette version",
        "Khôi phục bản đã lưu": "Restaurer la version enregistrée",
        "XML: kiểm theo DTD/XSD…": "XML : valider avec une DTD/XSD…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Ce Mac n’a pas libxml2, la validation XSD est indisponible.",
        "Chọn lược đồ XSD để kiểm": "Choisir un schéma XSD pour la validation",
        "Hợp lệ theo": "Valide selon",
        "Plugin chạy xong, không đổi gì": "L’extension a terminé sans rien modifier",
        "Chưa cài plugin native nào": "Aucune extension native installée",
        "Gỡ plugin này": "Supprimer cette extension",
        "Gỡ plugin này?": "Supprimer cette extension ?",
        "Gỡ": "Supprimer",
        "Cài plugin native…": "Installer une extension native…",
        "Mở thư mục plugin": "Ouvrir le dossier des extensions",
        "Chọn file .dylib của plugin native": "Choisir le fichier .dylib de l’extension",
        "Đã cài:": "Installé :",
        "Đã gỡ:": "Supprimé :",
        "Plugin native…": "Extensions natives…",
        "Chỉ nhận file .dylib.": "Seuls les fichiers .dylib sont acceptés.",
        "Đã có một plugin trùng tên:": "Une extension du même nom est déjà installée :",
        "Không chép được plugin:": "Impossible de copier l’extension :",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "Les extensions natives ne sont disponibles que dans le téléchargement direct, pas dans la version App Store.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Processus auxiliaire des extensions introuvable.",
        "Không khởi động được tiến trình phụ:": "Impossible de démarrer le processus auxiliaire :",
        "Tiến trình plugin đã dừng giữa chừng.": "Le processus de l’extension s’est arrêté en cours de route.",
        "Plugin không trả lời kịp — đã dừng nó.": "L’extension n’a pas répondu à temps — elle a été arrêtée.",
        "Plugin trả lời sai giao thức:": "L’extension a répondu avec un message mal formé :",
        "Plugin báo lỗi:": "L’extension a signalé une erreur :",
        "Về GEditor": "À propos de GEditor",
        "Cài đặt…": "Réglages…",
        "Thoát GEditor": "Quitter GEditor",
        "File": "Fichier",
        "Tab mới": "Nouvel onglet",
        "Đóng tab": "Fermer l’onglet",
        "Tab kế": "Onglet suivant",
        "Tab trước": "Onglet précédent",
        "Tài liệu mới": "Nouveau document",
        "Mở…": "Ouvrir…",
        "Mở thư mục làm Workspace…": "Ouvrir un dossier comme espace de travail…",
        "Mở gần đây": "Ouvrir un élément récent",
        "Lưu": "Enregistrer",
        "Lưu thành…": "Enregistrer sous…",
        "Cắt khoảng trắng cuối dòng khi lưu": "Supprimer les espaces en fin de ligne à l’enregistrement",
        "Theo dõi file (tail -f)": "Suivre le fichier (tail -f)",
        "In…": "Imprimer…",
        "Mở lại tab vừa đóng": "Rouvrir l’onglet fermé",
        "Chưa có file nào": "Aucun fichier",
        "Xoá danh sách": "Vider la liste",
        "Edit": "Édition",
        "Hoàn tác": "Annuler",
        "Làm lại": "Rétablir",
        "Cắt": "Couper",
        "Sao chép": "Copier",
        "Dán": "Coller",
        "Lịch sử clipboard…": "Historique du presse-papiers…",
        "Column Editor…": "Éditeur de colonnes…",
        "Chọn lần kế tiếp": "Sélectionner l’occurrence suivante",
        "Chọn tất cả": "Tout sélectionner",
        "Nhân đôi dòng": "Dupliquer la ligne",
        "Xóa dòng": "Supprimer la ligne",
        "Comment dòng": "Commenter la ligne",
        "Chưa chép gì trong phiên này": "Rien n’a été copié durant cette session",
        "Xoá lịch sử": "Effacer l’historique",
        "Search": "Recherche",
        "Tìm…": "Rechercher…",
        "Tìm và thay…": "Rechercher et remplacer…",
        "Tìm trong thư mục…": "Rechercher dans un dossier…",
        "Thay trong thư mục…": "Remplacer dans un dossier…",
        "Kết quả kế": "Résultat suivant",
        "Kết quả trước": "Résultat précédent",
        "Đi tới dòng…": "Aller à la ligne…",
        "Nhảy tới ngoặc khớp": "Aller à la parenthèse correspondante",
        "Đánh dấu mọi dòng khớp…": "Marquer toutes les lignes correspondantes…",
        "Đảo dấu": "Inverser les marques",
        "Bỏ mọi dấu": "Supprimer toutes les marques",
        "Chép dòng đã đánh dấu": "Copier les lignes marquées",
        "Xóa dòng đã đánh dấu": "Supprimer les lignes marquées",
        "Chỉ giữ dòng đã đánh dấu": "Ne garder que les lignes marquées",
        "Lines": "Lignes",
        "Sắp xếp A→Z": "Trier A→Z",
        "Sắp xếp Z→A": "Trier Z→A",
        "Sắp xếp tự nhiên": "Tri naturel",
        "Khử trùng lặp": "Supprimer les doublons",
        "Đảo thứ tự dòng": "Inverser l’ordre des lignes",
        "Dời dòng lên": "Monter la ligne",
        "Dời dòng xuống": "Descendre la ligne",
        "Ghép dòng": "Joindre les lignes",
        "Tách dòng theo độ dài…": "Couper les lignes selon la longueur…",
        "Tách dòng theo ký tự…": "Couper les lignes selon un caractère…",
        "Xóa dòng rỗng": "Supprimer les lignes vides",
        "Nén dòng trống liên tiếp": "Réduire les lignes vides consécutives",
        "Cắt khoảng trắng cuối dòng": "Supprimer les espaces en fin de ligne",
        "Tab → Space": "Tab → Espace",
        "Space → Tab": "Espace → Tab",
        "HOA": "MAJUSCULES",
        "thường": "minuscules",
        "Chữ Hoa Đầu Từ": "Majuscule À Chaque Mot",
        "Chữ hoa đầu câu": "Majuscule en début de phrase",
        "Đảo hoa/thường": "iNVERSER lA cASSE",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV : choisir la feuille…",
        "Xem dạng bảng / văn bản": "Basculer vue tableau / texte",
        "Xóa cột…": "Supprimer une colonne…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Valider les données (nombre de colonnes · types)",
        "Bàn làm sạch dữ liệu…": "Atelier de nettoyage des données…",
        "Chạy công thức làm sạch…": "Exécuter une recette de nettoyage…",
        "Chuyển đổi…": "Convertir…",
        "Đổi dấu phân tách…": "Changer le séparateur…",
        "Xuất sang JSON…": "Exporter en JSON…",
        "Format": "Format",
        "Bảng mã…": "Encodage…",
        "Xuống dòng…": "Fins de ligne…",
        "Chuẩn hóa Unicode…": "Normaliser l’Unicode…",
        "JSON: định dạng lại": "JSON : mettre en forme",
        "JSON: thu gọn một dòng": "JSON : compacter sur une ligne",
        "JSON: sắp xếp khóa": "JSON : trier les clés",
        "JSON: truy vấn JSONPath…": "JSON : requête JSONPath…",
        "CSV: truy vấn SQL…": "CSV : requête SQL…",
        "Truy vấn SQL": "Requête SQL",
        "Đang chạy…": "Exécution…",
        "Xuất ra tab mới": "Exporter dans un nouvel onglet",
        "Tài liệu rỗng — không có bảng để truy vấn": "Document vide — aucune table à interroger",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Ce n’est pas une table CSV — la première ligne n’a qu’une colonne",
        "Không đọc được câu truy vấn": "Impossible de lire la requête",
        "Không kiểm được câu truy vấn": "Impossible de vérifier la requête",
        "Vàng (mặc định)": "Jaune (par défaut)",
        "Xanh dương": "Bleu",
        "Xanh lá": "Vert",
        "Vàng đất": "Ocre",
        "Tím": "Violet",
        "Hồng": "Rose",
        "Xanh ngọc": "Turquoise",
        "Cam": "Orange",
        "Xám lam": "Ardoise",
        "Văn bản": "Texte",
        "Dãy số": "Suite numérique",
        "Dãy ngày": "Suite de dates",
        "Chữ HOA (hex)": "MAJUSCULES (hexadécimal)",
        "Bắt đầu": "Début",
        "Bước": "Pas",
        "Đệm 0 tới": "Compléter par des zéros jusqu’à",
        "Hệ": "Base",
        "Ngày đầu": "Première date",
        "Định dạng": "Format",
        "Chèn": "Insérer",
        "Huỷ": "Annuler",
        "Chuyển đổi định dạng": "Convertir le format",
        "Xem trước 5 hàng đầu": "Aperçu des 5 premières lignes",
        "Tạo tab mới": "Ouvrir dans un nouvel onglet",
        "Lưu ra file…": "Enregistrer dans un fichier…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Le résultat s’ouvre dans un nouvel onglet non enregistré. Le document d’origine reste intact.",
        "Chạy trên tài liệu này": "Exécuter sur ce document",
        "Chạy trên thư mục…": "Exécuter sur un dossier…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Toute la recette est UNE seule annulation. Le fichier sur le disque reste intact jusqu’à l’enregistrement.",
        "tắt": "désactivé",
        "không thấy cột": "colonne introuvable",
        "sẵn sàng": "prêt",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "il continue d’occuper un cœur du processeur jusqu’à la fermeture de l’application.",
        "Script không trả về gì": "Le script n’a rien renvoyé",
        "Không dựng được máy JavaScript": "Impossible de créer le moteur JavaScript",
        "Lỗi JavaScript không rõ": "Erreur JavaScript inconnue",
        "Bảng": "Table",
        "Áp sắp xếp vào file": "Appliquer le tri au fichier",
        "Chuyển đổi ▾": "Convertir ▾",
        "Xuất dòng khớp": "Exporter les lignes correspondantes",
        "Ẩn cột này": "Masquer cette colonne",
        "Đổi tên tiêu đề…": "Renommer l’en-tête…",
        "Chèn cột trống bên trái": "Insérer une colonne vide à gauche",
        "Chèn cột trống bên phải": "Insérer une colonne vide à droite",
        "Xóa cột này khỏi file…": "Supprimer cette colonne du fichier…",
        "Phải còn ít nhất một cột đang hiện": "Au moins une colonne doit rester visible",
        "Đang sắp xếp…": "Tri en cours…",
        "Trở về thứ tự trong file": "Revenir à l’ordre du fichier",
        "trăm hàng đầu": "cent premières lignes",
        "chọn cột": "choisir des colonnes",
        "đặt tên cột kết quả": "nommer une colonne de résultat",
        "lọc theo chữ": "filtrer par texte",
        "ô rỗng": "cellules vides",
        "ghép điều kiện": "combiner des conditions",
        "đếm hàng": "compter les lignes",
        "gộp nhóm": "regrouper et agréger",
        "nhỏ nhất, lớn nhất": "minimum, maximum",
        "sắp xếp và cắt": "trier et limiter",
        "tên cột có dấu cách": "nom de colonne avec espaces",
        "Truy vấn bị dừng giữa chừng": "La requête a été interrompue",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Non pris en charge : JOIN · sous-requête · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · fonctions de fenêtrage",
        "XML: định dạng lại": "XML : mettre en forme",
        "XML: thu gọn một dòng": "XML : compacter sur une ligne",
        "XML: kiểm cú pháp": "XML : vérifier la syntaxe",
        "YAML: kiểm khóa trùng và thụt lề": "YAML : vérifier les clés en double et l’indentation",
        "View": "Affichage",
        "Ẩn/hiện sidebar (Function List)": "Afficher/masquer la barre latérale (liste des fonctions)",
        "Ẩn/hiện bản đồ tài liệu": "Afficher/masquer la carte du document",
        "Gấp / mở khối tại con nháy": "Plier / déplier le bloc au curseur",
        "Gấp tất cả": "Tout plier",
        "Bỏ gấp tất cả": "Tout déplier",
        "Gấp theo cấp": "Plier par niveau",
        "Cấp %d": "Niveau %d",
        "Đã gấp %d khối ở cấp %d": "%d {one=bloc plié|other=blocs pliés} au niveau %d",
        "Tài liệu này chỉ sâu %d cấp": "Ce document ne fait que %d {one=niveau|other=niveaux} de profondeur",
        "mermaid: không đọc được bản kê": "mermaid : manifeste illisible",
        "Kiểm tra bản cập nhật…": "Rechercher les mises à jour…",
        "Kiểm tra bản cập nhật": "Rechercher les mises à jour",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Les versions App Store se mettent à jour via le Mac App Store, pas via GEditor.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Cette version n’a pas de clé de signature de mise à jour, elle ne peut donc pas en rechercher.",
        "Phóng to chữ": "Agrandir le texte",
        "Thu nhỏ chữ": "Réduire le texte",
        "Cỡ chữ gốc": "Taille réelle",
        "Chia đôi theo chiều dọc": "Diviser verticalement",
        "Chia đôi theo chiều ngang": "Diviser horizontalement",
        "Bỏ chia đôi": "Fermer la division",
        "Mở tab này ở nửa kia": "Ouvrir cet onglet dans l’autre volet",
        "Nhảy sang nửa kia": "Aller à l’autre volet",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Retour à la ligne (désactivé / fenêtre / colonne)",
        "Ngắt dòng tại cột…": "Retour à la ligne à la colonne…",
        "Đánh dấu dòng này": "Marquer cette ligne",
        "Dấu kế tiếp": "Marque suivante",
        "Dấu trước đó": "Marque précédente",
        "Màu đánh dấu…": "Couleur des marques…",
        "Hiện tất cả ký tự ẩn": "Afficher tous les caractères invisibles",
        "  Khoảng trắng": "  Espaces",
        "  Tab": "  Tabulations",
        "  Xuống dòng": "  Fins de ligne",
        "  NBSP · zero-width · điều khiển": "  NBSP · largeur nulle · contrôle",
        "Xem nhị phân": "Vue binaire",
        "Chế độ CSV (tô màu theo cột)": "Mode CSV (colonnes en couleurs)",
        "Macro": "Macro",
        "Bắt đầu / dừng ghi": "Démarrer / arrêter l’enregistrement",
        "Phát lại": "Lire",
        "Phát nhiều lần…": "Lire plusieurs fois…",
        "Phát đến cuối tài liệu": "Lire jusqu’à la fin du document",
        "Chạy trên mọi tab": "Exécuter sur tous les onglets",
        "Hủy macro đang chạy": "Annuler la macro en cours",
        "Lưu macro…": "Enregistrer la macro…",
        "Macro đã lưu…": "Macros enregistrées…",
        "Help": "Aide",
        "Trợ giúp GEditor": "Aide de GEditor",
        "Giới thiệu tính năng": "Découverte des fonctionnalités",
        "Di cư từ Notepad++": "Migrer depuis Notepad++",
        "Tìm": "Rechercher",
        "Thay bằng": "Remplacer par",
        "Kế": "Suivant",
        "Trước": "Précédent",
        "Đếm": "Compter",
        "Đóng": "Fermer",
        "Kiểm theo JSON Schema…": "Valider avec un schéma JSON…",
        "Chọn tệp JSON Schema": "Choisir un fichier de schéma JSON",
        "Không thấy lỗi nào theo schema này.": "Aucun problème trouvé selon ce schéma.",
        "JSON Schema": "Schéma JSON",
        "Kiểm cú pháp đồ thị": "Vérifier la syntaxe du graphe",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Format de graphe non reconnu — une extension .dot, .gv, .cypher, .ttl ou .graphml est requise.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Aucune erreur de syntaxe %@ trouvée (la vérification n’est pas exhaustive).",
        "Cú pháp %@": "Syntaxe %@",
        "không phải một đối tượng JSON": "n’est pas un objet JSON",
        "Khai phá văn bản (n-gram, TF-IDF)": "Fouille de texte (n-grammes, TF-IDF)",
        "Tài liệu rỗng.": "Le document est vide.",
        "Không rút được từ khoá nào.": "Aucun mot-clé n’a pu être extrait.",
        "Từ khoá": "Mots-clés",
        "%d từ khoá · %d token · %d tài liệu": "%d {one=mot-clé|other=mots-clés} · %d {one=jeton|other=jetons} · %d {one=document|other=documents}",
        "Tô lên tài liệu": "Marquer dans le document",
        "Đánh dấu entity từ danh sách…": "Marquer des entités depuis une liste…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Choisir une liste d’entités (CSV ou JSON)",
        "Không đọc được danh sách entity.": "Impossible de lire la liste d’entités.",
        "Danh sách entity rỗng.": "La liste d’entités est vide.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "Aucune entité trouvée dans le document (%d chargées).",
        "%d lần xuất hiện · %@": "%d {one=occurrence|other=occurrences} · %@",
        "Chuyển đổi tri thức…": "Convertir des connaissances…",
        "Chuyển đổi: %@ → %@": "Conversion : %@ → %@",
        "Không chuyển đổi được.": "Conversion impossible.",
        "Xem trước cắt chunk…": "Aperçu du découpage…",
        "Cỡ cố định 800B, chồng 100B": "Taille fixe 800 o, chevauchement 100 o",
        "Theo câu (≤ 800B)": "Par phrase (≤ 800 o)",
        "Theo heading Markdown": "Par titre Markdown",
        "Tài liệu rỗng — không có chunk nào.": "Document vide — aucun segment.",
        "%d chunk · trung bình %d B · %@": "%d {one=segment|other=segments} · %d o en moyenne · %@",
        "Xuất JSONL": "Exporter en JSONL",
        "Chunk JSONL": "Segments JSONL",
        "Mở triple/edge dạng bảng": "Ouvrir les triplets/arêtes sous forme de table",
        "Bảng triple": "Table de triplets",
        "Tài liệu này không có dòng triple nào.": "Ce document ne contient aucune ligne de triplet.",
        "Không đọc được triple nào — dòng %d: %@": "Aucun triplet n’a pu être lu — ligne %d : %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%d {one=triplet lu|other=triplets lus} · %d {one=ligne mal formée ignorée|other=lignes mal formées ignorées} (première : ligne %d)",
        "Trùng lặp mờ theo cột…": "Doublons approximatifs par colonne…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Doublons approximatifs — colonne « %@ » : %d {one=groupe candidat|other=groupes candidats}",
        "Gộp": "Fusionner",
        "Giống": "Correspondance",
        "Các giá trị trong cụm": "Valeurs du groupe",
        "Gộp về": "Fusionner vers",
        "Gộp các cụm đã chọn": "Fusionner les groupes sélectionnés",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Aucun groupe sélectionné — Fusionner ne changera RIEN. L’application ne fusionne jamais d’elle-même.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d {one=groupe sélectionné|other=groupes sélectionnés} · %d {one=ligne changera|other=lignes changeront} · UNE seule annulation",
        "Không quét được cột này.": "Impossible d’analyser cette colonne.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "La colonne « %@ » n’a aucun groupe de doublons approximatifs.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Aucun groupe fusionné — le document est inchangé.",
        "Khử trùng lặp mờ · cột %@": "Déduplication approximative · colonne %@",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d {one=groupe fusionné|other=groupes fusionnés} · %d {one=cellule modifiée|other=cellules modifiées}",
        "Báo cáo làm sạch": "Rapport de nettoyage",
        "# Báo cáo làm sạch — %@\n\n": "# Rapport de nettoyage — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Appliqué (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Aucune étape appliquée._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Profil des données\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%d {one=colonne|other=colonnes} · %d {one=ligne|other=lignes} · analysé en %.1f s_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Colonne | Type | Null | Distinct | Min | Max | Moyenne |\n",
        "\n### Giá trị bất thường\n\n": "\n### Valeurs aberrantes\n\n",
        "hàng %d: %@": "ligne %d : %@",
        "- cột «%@» — %d ô: %@\n": "- colonne « %@ » — %d {one=cellule|other=cellules} : %@\n",
        "\n## Còn lại (%d)\n\n": "\n## Restant (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Aucune observation restante._\n",
        "- cột «%@»: %@\n": "- colonne « %@ » : %@\n",
        "Cắt khoảng trắng khi lưu": "Supprimer les espaces à l’enregistrement",
        "Chuẩn hóa xuống dòng": "Normaliser les fins de ligne",
        "trước đó": "précédent",
        "Không mở lại được thư mục «%@» của phiên trước": "Impossible de rouvrir le dossier « %@ » de la session précédente",
        " (và %d file khác)": " (et %d {one=autre fichier|other=autres fichiers})",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "Impossible de rouvrir %d {one=onglet|other=onglets} : %@%@ — les fichiers ne sont plus au même endroit.",
        "Không đọc được nội dung từ ống dẫn": "Impossible de lire l’entrée depuis le tube",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Les espaces en fin de ligne seront supprimés à chaque enregistrement",
        "Không cắt khoảng trắng khi lưu nữa": "Les espaces ne sont plus supprimés à l’enregistrement",
        "Chưa đặt tên.txt": "Sans titre.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "La conversion d’encodage perdra des caractères",
        "Vẫn lưu": "Enregistrer quand même",
        "Tài liệu có thay đổi chưa lưu": "Le document a des modifications non enregistrées",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Fermer sans enregistrer les abandonnera.",
        "Bỏ thay đổi": "Abandonner les modifications",
        "Đi tới dòng": "Aller à la ligne",
        "Tài liệu có %d dòng.": "Le document a %d {one=ligne|other=lignes}.",
        "Số dòng": "Numéro de ligne",
        "Đi tới": "Aller",
        "Diễn giải lại theo…": "Réinterpréter comme…",
        "Chuyển đổi sang…": "Convertir vers…",
        "Không diễn giải lại được": "Réinterprétation impossible",
        "Bảng mã %@ không chứa hết ký tự": "%@ ne peut pas représenter tous les caractères",
        "Vẫn chọn": "Choisir quand même",
        "Cột %d": "Colonne %d",
        "Cột %d: %@": "Colonne %d : %@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Colonnes masquées : %@ (%d) — restaurez-les depuis le menu contextuel de l’en-tête",
        "Hiện lại: %@": "Réafficher : %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "Colonne %@ masquée — elle reste intacte dans le fichier",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Trié par %@ %@ · affichage seulement",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Trié : %@ %@ (affichage seulement)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ lignes correspondent — recherche en cours…",
        "%d / %d dòng khớp": "%d / %d {one=ligne correspond|other=lignes correspondent}",
        "Không tìm thấy lỗi trong %d hàng": "Aucun problème trouvé dans %d {one=ligne|other=lignes}",
        "%d hàng lệch số cột": "%d {one=ligne|other=lignes} avec un nombre de colonnes incorrect",
        "%d ô sai kiểu dữ liệu": "%d {one=cellule|other=cellules} du mauvais type",
        " (đã dừng ở %d lỗi đầu)": " (arrêté aux %d {one=premier problème|other=premiers problèmes})",
        "   —   kiểu nhận ra: ": "   —   types détectés : ",
        "Hàng %d, cột %@: «%@» không phải %@": "Ligne %d, colonne %@ : « %@ » n’est pas %@",
        "Column Editor — %d dòng": "Éditeur de colonnes — %d {one=ligne|other=lignes}",
        "Phát hiện": "Observations",
        "Hồ sơ dữ liệu": "Profil des données",
        "Hồ sơ dữ liệu — đang quét…": "Profil des données — analyse…",
        "Lưu công thức…": "Enregistrer la recette…",
        "Xuất báo cáo": "Exporter le rapport",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Aucun groupe appliqué · chaque groupe est une annulation",
        "quá nhiều giá trị": "trop de valeurs",
        "hay gặp: ": "les plus fréquentes : ",
        "Giá trị điền vào ô thiếu": "Valeur de remplissage des cellules vides",
        "Áp dụng": "Appliquer",
        "Không dựng được bản xem trước": "Impossible de construire un aperçu",
        "· giữ nguyên, không đọc được ·": "· conservé tel quel, illisible ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Convertir la colonne en ISO 8601 (AAAA-MM-JJ)",
        "Quy ước số cho cả cột": "Convention numérique pour toute la colonne",
        "Làm gì với ô thiếu": "Que faire des cellules vides",
        "Chuẩn hóa về ISO 8601": "Normaliser en ISO 8601",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "Lire les cellules ambiguës JOUR d’abord (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "Lire les cellules ambiguës MOIS d’abord (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "Ignorer les cellules ambiguës, ne corriger que les certaines",
        "Về Việt/Âu (1.234,56)": "Vers le vietnamien/européen (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Vers l’anglo-américain (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Vers l’anglo-américain, sans séparateur (1234.56)",
        "Điền một giá trị mặc định…": "Remplir avec une valeur par défaut…",
        "Điền xuôi — lấy giá trị phía trên": "Remplir vers le bas — reprendre la valeur du dessus",
        "Điền ngược — lấy giá trị phía dưới": "Remplir vers le haut — reprendre la valeur du dessous",
        "Xóa hàng có ô thiếu ở cột này": "Supprimer les lignes vides dans cette colonne",
        "Cắt khoảng trắng hai đầu": "Supprimer les espaces aux deux extrémités",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Supprimer aux extrémités et réduire les espaces internes",
        "Pivot…": "Tableau croisé…",
        "Nguồn…": "Sources…",
        "Pivot — gộp theo cột": "Tableau croisé — regrouper par colonne",
        "Hàng (gộp nhóm)": "Lignes (regroupement)",
        "Giá trị": "Valeurs",
        "+ Hàng": "+ Ligne",
        "+ Giá trị": "+ Valeur",
        "Xoá hết": "Tout effacer",
        "Đưa vào ô truy vấn": "Insérer dans la requête",
        "Chọn cột để dựng câu truy vấn.": "Choisissez des colonnes pour construire la requête.",
        "Không đọc được tên cột của bảng này.": "Impossible de lire les noms de colonnes de cette table.",
        "Nguồn dữ liệu của truy vấn": "Sources de données de la requête",
        "«%@» — tài liệu đang mở": "« %@ » — le document ouvert",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ le fichier a changé depuis son enregistrement",
        "Thêm file…": "Ajouter un fichier…",
        "Bỏ hết": "Tout retirer",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "Impossible de déduire un nom de table depuis « %@ » — renommez le fichier.",
        "Tổng": "Somme",
        "Trung bình": "Moyenne",
        "Nhỏ nhất": "Min",
        "Lớn nhất": "Max",
        "Đếm khác nhau": "Nombre de valeurs distinctes",
        "Biểu đồ": "Graphique",
        "Xuất PNG": "Exporter en PNG",
        "Xuất SVG": "Exporter en SVG",
        "Bảng này không có cột số nào để vẽ.": "Cette table n’a aucune colonne numérique à représenter.",
        "Không dựng được ảnh PNG.": "Impossible de construire l’image PNG.",
        "Kết quả truy vấn": "Résultat de la requête",
        "Đã lưu %@": "%@ enregistré",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "Graphique %@ de « %@ » — %d {one=point|other=points}, valeurs de %@ à %@",
        "Cột": "Barres",
        "Đường": "Courbe",
        "Phân bố": "Histogramme",
        "Phân tán": "Nuage de points",
        "Hộp": "Boîte",
        "CSV: chất lượng dữ liệu…": "CSV : qualité des données…",
        "Chất lượng dữ liệu": "Qualité des données",
        "Xuất vi phạm ra tab mới": "Exporter les violations dans un nouvel onglet",
        "Mức": "Niveau",
        "Luật": "Règle",
        "Vi phạm": "Violations",
        "Tỷ lệ": "Taux",
        "đạt": "réussi",
        "lỗi": "erreur",
        "cảnh báo": "avertissement",
        "hỏng": "cassé",
        "Đã đánh dấu %d dòng vi phạm": "%d {one=ligne en violation marquée|other=lignes en violation marquées}",
        "Xu hướng": "Tendance",
        "Lúc chấm": "Évalué le",
        "Số hàng": "Lignes",
        "Lệch": "Écart",
        "Luật trượt": "Règles en échec",
        "Điểm chất lượng": "Score de qualité",
        "Điểm theo thời gian": "Score dans le temps",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Aucun historique — chaque évaluation ajoute ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "une ligne au fichier « .history.jsonl » à côté des règles.",
        "%d mốc trong lịch sử": "%d {one=point|other=points} dans l’historique",
        " · %d dòng KHÔNG đọc được": " · %d {one=ligne ILLISIBLE|other=lignes ILLISIBLES}",
        " · chọn hai dòng để so": " · sélectionnez deux lignes pour comparer",
        "điểm %+.1f": "score %+.1f",
        "không chiều nào tụt": "aucune dimension en baisse",
        "tụt: ": "en baisse : ",
        "%d luật mới trượt: %@": "%d {one=nouvelle règle en échec|other=nouvelles règles en échec} : %@",
        "số hàng %+d": "lignes %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (et %d {one=autre avertissement|other=autres avertissements} dans l’onglet Tendance)",
        "Không sửa tự động được: ": "Pas de correction automatique : ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Ouvre l’outil correspondant dans l’Atelier de nettoyage, puis réévalue aussitôt.",
        "Xử lý giá trị thiếu…": "Traiter les valeurs manquantes…",
        "Chuẩn hóa ngày…": "Normaliser les dates…",
        "Khử trùng lặp…": "Supprimer les doublons…",
        "Thay thế…": "Remplacer…",
        "Xem các dòng sai": "Afficher les lignes fautives",
        "Không tìm thấy cột «%@» trong bảng này.": "La colonne « %@ » n’est pas dans cette table.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Doublons supprimés — « %@ » est désormais unique. Score : %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Doublons supprimés, mais « %@ » a encore %d {one=ligne en double|other=lignes en double} (avant : %d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "ces lignes partagent la CLÉ mais pas la ligne entière, il faut donc regarder et choisir ",
        "giữ hàng nào.": "laquelle garder.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Impossible de lire une valeur en violation de cette règle.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%d {one=valeur incorrecte|other=valeurs incorrectes} dans la colonne « %@ » — remplissez Remplacer puis prévisualisez",
        "Đã chấm lại: %.0f/100": "Réévalué : %.0f/100",
        "Xem trước báo cáo": "Aperçu du rapport",
        "Tham số…": "Paramètres…",
        "Xuất HTML…": "Exporter en HTML…",
        "In / PDF…": "Imprimer / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%d {one=bloc exécuté|other=blocs exécutés} · %d {one=bloc EN ÉCHEC|other=blocs EN ÉCHEC}",
        "%d khối chạy được": "%d {one=bloc exécuté|other=blocs exécutés}",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · DONNÉES PÉRIMÉES — le fichier source a changé ; reconstruisez",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "L’aperçu de rapport nécessite un document .%@",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Aucune source de données trouvée — déclarez « source: fichier.csv » dans le frontmatter.",
        "Không dựng được báo cáo.": "Impossible de construire le rapport.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Ce rapport ne déclare aucun paramètre dans son frontmatter.",
        "Tham số báo cáo": "Paramètres du rapport",
        "Dựng lại": "Reconstruire",
        "Đã xuất %@": "%@ exporté",
        "Báo cáo: xem trước": "Rapport : aperçu",
        "Báo cáo: sinh loạt…": "Rapport : génération par lot…",
        "không phải tài liệu .greport.md": "n’est pas un document .greport.md",
        "không phân tích được báo cáo": "impossible d’analyser le rapport",
        "không tìm được dữ liệu nguồn": "source de données introuvable",
        "không đọc được danh sách tham số": "impossible de lire la liste des paramètres",
        "Sinh loạt cần tài liệu đuôi .%@": "La génération par lot nécessite un document .%@",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Choisir une liste de paramètres (CSV ou JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Choisir un dossier pour %d {one=rapport|other=rapports}",
        "[%d/%d] %@": "[%d/%d] %@",
        "thiếu tham số ": "paramètres manquants ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "pointe vers le fichier source lui-même — écrasement refusé",
        "%d khối HỎNG": "%d {one=bloc EN ÉCHEC|other=blocs EN ÉCHEC}",
        "Sinh loạt xong: %d tệp · %d hỏng": "Lot terminé : %d {one=fichier|other=fichiers} · %d en échec",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d {one=jeu de paramètres n’a pas pu être construit|other=jeux de paramètres n’ont pas pu être construits} — voir le récapitulatif",
        "Sơ đồ Mermaid: xem trước": "Diagramme Mermaid : aperçu",
        "Sơ đồ Mermaid: chèn mẫu…": "Diagramme Mermaid : insérer un modèle…",
        "Sơ đồ Mermaid: định dạng lại": "Diagramme Mermaid : remettre en forme",
        "Nền trong suốt": "Fond transparent",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Ce Mac ne peut pas convertir le diagramme en PNG — macOS 13 est requis. L’export SVG fonctionne toujours.",
        "Lưu PNG %@…": "Enregistrer le PNG %@…",
        "Lưu SVG…": "Enregistrer le SVG…",
        "Chép ảnh vào clipboard": "Copier l’image dans le presse-papiers",
        "Màu thương hiệu…": "Couleurs de marque…",
        "Màu thương hiệu cho sơ đồ": "Couleurs de marque pour les diagrammes",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Chaque champ est une couleur #rrggbb. Enregistré dans « themes/mermaid-brand.json » — copiable vers un autre Mac.",
        "Màu chính": "Couleur principale",
        "Chữ trên nút": "Texte des nœuds",
        "Viền": "Bordure",
        "Đường nối": "Liens",
        "Nền khi xuất ảnh": "Fond à l’export",
        "Lưu và chèn %%{init}%% vào tài liệu": "Enregistrer et insérer %%{init}%% dans le document",
        "Đã lưu màu thương hiệu": "Couleurs de marque enregistrées",
        "Đã chép ảnh sơ đồ vào clipboard": "Image du diagramme copiée dans le presse-papiers",
        "Đã lưu %@ — %@": "%@ enregistré — %@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Ce diagramme a déjà une directive %%{init}%% — la vôtre est conservée telle quelle.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% inséré — le diagramme porte désormais ses propres couleurs",
        "Chèn màu thương hiệu vào sơ đồ": "Insérer les couleurs de marque dans le diagramme",
        "Định dạng sơ đồ Mermaid": "Remettre en forme le diagramme Mermaid",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "La source du diagramme est déjà propre — rien à changer",
        "Đã định dạng lại sơ đồ": "Diagramme remis en forme",
        "Đã định dạng lại %d sơ đồ": "%d {one=diagramme remis|other=diagrammes remis} en forme",
        "Thư viện mẫu sơ đồ": "Bibliothèque de modèles de diagrammes",
        "Mẫu sơ đồ đầy đủ": "Modèles de diagrammes complets",
        "Mẩu cú pháp": "Fragments de syntaxe",
        "Đang soạn: %@": "Édition : %@",
        "Đã chèn mẫu «%@»": "Modèle « %@ » inséré",
        "Tài liệu đang ở chế độ chỉ đọc.": "Ce document est en lecture seule.",
        "Sơ đồ Mermaid": "Diagramme Mermaid",
        "Tài liệu chưa có khối mermaid nào.": "Ce document n’a aucun bloc mermaid.",
        "Thương hiệu": "Marque",
        "Xuất…": "Exporter…",
        "Chưa có sơ đồ nào": "Aucun diagramme",
        "%d sơ đồ · %@": "%d {one=diagramme|other=diagrammes} · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%d/%d {one=diagramme EN ÉCHEC|other=diagrammes EN ÉCHEC} — diagramme %d%@",
        ", dòng %d": ", ligne %d",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Ce document n’a aucun bloc ```mermaid et n’est pas un fichier .mmd.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Aucun diagramme n’a fini d’être rendu.",
        "Không tìm thấy «%@» trong mã sơ đồ": "Impossible de trouver « %@ » dans la source du diagramme",
        "không dựng được hàng rào chặn mạng cho WKWebView": "impossible de construire le pare-feu réseau pour WKWebView",
        "Luật kết hợp": "Règles d’association",
        "Mỗi dòng một giỏ": "Un panier par ligne",
        "Hai cột: mã · item": "Deux colonnes : identifiant · article",
        "Dạng dữ liệu giao dịch": "Forme des données transactionnelles",
        "Cột giỏ hàng hoặc mã giao dịch": "Colonne panier ou identifiant de transaction",
        "Cột item": "Colonne article",
        "Ký tự phân tách item": "Caractère séparateur d’articles",
        "Support tối thiểu, phần trăm": "Support minimum, pourcentage",
        "Confidence tối thiểu, phần trăm": "Confiance minimum, pourcentage",
        "Tách bởi:": "Séparé par :",
        "Support \u{2265}": "Support ≥",
        "% · Confidence \u{2265}": "% · Confiance ≥",
        "Bảng luật kết hợp": "Table des règles d’association",
        "Support": "Support",
        "Confidence": "Confiance",
        "Lift": "Lift",
        "Leverage": "Leverage",
        "Cảnh báo": "Attention",
        "%d giao dịch · %d item · %d luật": "%d {one=transaction|other=transactions} · %d {one=article|other=articles} · %d {one=règle|other=règles}",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — aucune règle n’a atteint les seuils ; baissez le support ou la confiance",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — ARRÊTÉ TÔT, la table est INCOMPLÈTE",
        "%d / %d giao dịch chứa cả hai vế": "%d / %d {one=transaction contient|other=transactions contiennent} les deux membres",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "La forme à deux colonnes nécessite deux colonnes DIFFÉRENTES.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%d {one=ligne marquée|other=lignes marquées} sur %d {one=transaction contenant|other=transactions contenant} « %@ »",
        "CSV: luật kết hợp…": "CSV : règles d’association…",
        "Khai phá theo nhóm": "Fouille par groupe",
        "Cột nhóm": "Colonne de groupe",
        "Cột giá trị": "Colonne de valeurs",
        "Cột thứ hai cho tương quan": "Deuxième colonne pour la corrélation",
        "Cách xếp hạng": "Classement",
        "Nhóm theo:": "Regrouper par :",
        "Giá trị:": "Valeur :",
        "Xếp theo:": "Classer par :",
        "Bảng xếp hạng nhóm": "Table de classement des groupes",
        "Nhóm": "Groupe",
        "Hàng": "Lignes",
        "Hàng rào riêng": "Seuil propre",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "Écart r",
        "Ghi chú": "Note",
        "không đo được": "non mesurable",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d {one=groupe|other=groupes} · corrélation globale de référence %@",
        " · ĐÃ CẮT %d nhóm": " · %d {one=GROUPE ÉCARTÉ|other=GROUPES ÉCARTÉS}",
        "Bảng này không có cột chữ nào để gom nhóm.": "Cette table n’a aucune colonne texte pour regrouper.",
        "Bảng này không có cột số nào để khai phá.": "Cette table n’a aucune colonne numérique à explorer.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "%d {one=ligne du groupe|other=lignes du groupe} « %@ » {one=marquée|other=marquées}",
        "CSV: khai phá theo nhóm…": "CSV : fouille par groupe…",
        "\u{2194}": "↔",
        "Dự báo": "Prévision",
        "Cột giá trị theo thời gian": "Colonne de valeurs dans le temps",
        "Mô hình dự báo": "Modèle de prévision",
        "Số kỳ dự báo": "Nombre de périodes à prévoir",
        "Kết luận so với baseline": "Verdict face aux modèles de référence",
        "Mô hình:": "Modèle :",
        "Số kỳ:": "Périodes :",
        "Chu kỳ:": "Saison :",
        "tự": "auto",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Période saisonnière ; laisser vide pour détection automatique",
        "Bảng giá trị dự báo": "Table des valeurs prévues",
        "Kỳ": "Période",
        "Dải 80%": "Bande 80 %",
        "Dải 95%": "Bande 95 %",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "non calculable",
        "Bảng này không có cột số nào để dự báo.": "Cette table n’a aucune colonne numérique à prévoir.",
        "Không dựng được dự báo cho cột này.": "Impossible de construire une prévision pour cette colonne.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "La colonne « %@ » n’a que %d {one=valeur numérique|other=valeurs numériques} — il en faut au moins 4 pour prévoir.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# La série est lue dans l’ordre des lignes du fichier — sans retri, sans colonne temporelle déduite.\n",
        "Sai số huấn luyện": "Erreur d’apprentissage",
        "CSV: dự báo chuỗi thời gian…": "CSV : prévision de série temporelle…",
        "Holt-Winters cộng": "Holt-Winters additif",
        "Holt-Winters nhân": "Holt-Winters multiplicatif",
        "seasonal-naive": "seasonal-naive",
        "naive": "naive",
        "Cột đưa vào phân cụm": "Colonnes utilisées pour le clustering",
        "Đường cong WCSS": "Courbe WCSS",
        "Phân cụm": "Cluster",
        "Chuẩn hoá:": "Mise à l’échelle :",
        "k:": "k :",
        "eps:": "eps :",
        "minPts:": "minPts :",
        "Chọn ít nhất một cột.": "Sélectionnez au moins une colonne.",
        "Không đủ dữ liệu để dựng đường cong.": "Pas assez de données pour construire la courbe.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "Le coude suggère k = %d. Le WCSS diminue TOUJOURS quand k augmente ; c’est donc une astuce de lecture graphique et non un critère statistique — regardez la courbe et jugez si la cassure est nette.",
        "WCSS theo k": "WCSS selon k",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "La k-distance suggère eps = %@ (minPts vaut par défaut 2 × nombre de colonnes = %d). %@",
        "Khoảng cách tới hàng xóm thứ k": "Distance au k-ième voisin",
        "Cần ít nhất 2 cột số để phân cụm.": "Au moins 2 colonnes numériques sont nécessaires pour le clustering.",
        "Cụm theo %@ và %@": "Clusters selon %@ et %@",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — clusters trouvés en %d {one=dimension|other=dimensions} ; le graphique n’en montre que les 2 premières",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# bruit (cluster_id = -1) : %d {one=ligne|other=lignes}\n",
        "CSV: phân cụm…": "CSV : clustering…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- Centres des clusters (unités d’origine) ---\n",
        "k-means": "k-means",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Matrice de corrélation",
        "Phương pháp tương quan": "Méthode de corrélation",
        "Tương quan không hàm ý nhân quả.": "Corrélation n’implique pas causalité.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "Paire la plus forte : %@ ↔ %@ = %@ (n = %d). Cliquez une cellule pour un nuage de points.",
        "Không cặp nào đo được.": "Aucune paire mesurable.",
        "%@ ↔ %@: %@ trên %d hàng": "%@ ↔ %@ : %@ sur %d {one=ligne|other=lignes}",
        "Cần ít nhất 2 cột số để tính tương quan.": "Au moins 2 colonnes numériques sont nécessaires pour la corrélation.",
        "Không đọc được cột «%@».": "Impossible de lire la colonne « %@ ».",
        "CSV: ma trận tương quan…": "CSV : matrice de corrélation…",
        "Bất thường": "Anomalies",
        "Danh sách bất thường": "Liste des anomalies",
        "Cột:": "Colonne :",
        "Cột số cần xét": "Colonne numérique à examiner",
        "Cách:": "Méthode :",
        "Phương pháp phát hiện": "Méthode de détection",
        "Phương pháp đã dùng": "Méthode utilisée",
        "Ngưỡng": "Seuil",
        "Đánh dấu": "Marquer",
        "Xuất tab mới": "Exporter dans un nouvel onglet",
        "Dòng": "Ligne",
        "Điểm": "Score",
        "Vì sao": "Pourquoi",
        "nhẹ": "léger",
        "vừa": "modéré",
        "nặng": "sévère",
        "z-score": "z-score",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d {one=ligne|other=lignes} (%.2f %%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Cette table n’a aucune colonne numérique où chercher des anomalies.",
        "Đã đánh dấu %d dòng bất thường": "%d {one=ligne anormale marquée|other=lignes anormales marquées}",
        "CSV: tìm bất thường…": "CSV : détecter les anomalies…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%d {one=règle, RÉUSSIE|other=règles, toutes RÉUSSIES} · %d {one=ligne|other=lignes} · %.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%d {one=erreur|other=erreurs} · %d {one=avertissement|other=avertissements} sur %d {one=règle|other=règles} · %d {one=ligne|other=lignes} · %.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Enregistrez d’abord le document — les règles de qualité vivent à côté du fichier de données.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Aucun jeu de règles. Créez le fichier %@ puis rouvrez.",
        "Lịch sử": "Historique",
        "Câu đã lưu": "Requêtes enregistrées",
        "Lưu câu này…": "Enregistrer cette requête…",
        "Lưu câu truy vấn": "Enregistrer la requête",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Donnez-lui un nom pour la retrouver plus tard. Un nom identique écrase.",
        "Ví dụ: Doanh thu theo tỉnh": "Par exemple : Chiffre d’affaires par province",
        "Chưa nhập giá trị cho tham số: %@": "Aucune valeur saisie pour le paramètre : %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "L’extension a changé depuis votre approbation — GEditor refuse de l’exécuter",
        "Chạy plugin chưa duyệt?": "Exécuter une extension non approuvée ?",
        "Tôi tin file này — chạy": "Je fais confiance à ce fichier — exécuter",
        "KHÔNG có chữ ký": "NON signé",
        "Chữ ký: %@": "Signature : %@",
        "Đường dẫn: %@": "Chemin : %@",
        "Thay": "Remplacer",
        "Thay tất cả": "Tout remplacer",
        "Chuỗi thuần": "Texte brut",
        "Extended (\\n \\t \\xNN)": "Étendu (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Expression régulière",
        "Phân biệt hoa thường": "Respecter la casse",
        "Cả từ": "Mot entier",
        "Không có kết quả": "Aucun résultat",
        "Thử biểu thức chính quy…": "Tester une expression régulière…",
        "Chế độ Log (tô theo mức)": "Mode journal (couleur par niveau)",
        "Lọc log theo mức…": "Filtrer le journal par niveau…",
        "Chạy trên cả thư mục…": "Exécuter sur tout le dossier…",
        "Lọc qua lệnh ngoài…": "Filtrer par une commande externe…",
        "Script…": "Scripts…",
        "Gói mở rộng…": "Paquets d’extension…",
        "Cửa sổ mới": "Nouvelle fenêtre",
        "Tách tab ra cửa sổ mới": "Détacher l’onglet dans une nouvelle fenêtre",
        "Chưa mở thư mục nào": "Aucun dossier ouvert",
        "Tìm file trong thư mục": "Rechercher un fichier dans le dossier",
        "Lọc theo tên": "Filtrer par nom",
        "File mới…": "Nouveau fichier…",
        "Thư mục mới…": "Nouveau dossier…",
        "Đổi tên…": "Renommer…",
        "Chuyển vào Thùng rác": "Placer dans la corbeille",
        "Hiện trong Finder": "Afficher dans le Finder",
        "Đang đọc cấu trúc tài liệu…": "Lecture de la structure du document…",
        "file này không có hàm nào": "ce fichier n’a aucune fonction",
        "Không có gì khớp": "Aucune correspondance",
        "Văn bản thuần": "Texte brut",
        "🔒 Chỉ đọc": "🔒 Lecture seule",
        "Đang theo dõi": "Suivi en cours",
        "ngắt tại cột": "retour à la colonne",
        "Cú pháp": "Syntaxe",
        "Bấm để chèn vào ô truy vấn": "Cliquez pour insérer dans la requête",
        "truy vấn không hợp lệ": "requête invalide",
        "khóa `ten` ở gốc": "clé « nom » à la racine",
        "khóa có dấu cách": "clé avec espaces",
        "phần tử đầu": "premier élément",
        "mọi phần tử": "tous les éléments",
        "lát cắt": "tranche",
        "hợp nhiều chỉ số": "union d’indices",
        "mọi khóa `gia` ở mọi tầng": "toutes les clés « prix » à tous les niveaux",
        "mọi nút": "tous les nœuds",
        "lọc theo số": "filtrer par nombre",
        "lọc theo có mặt": "filtrer par présence",
        "Tới lỗi đầu tiên": "Aller à la première erreur",
        "Cột doanh_thu là số": "La colonne chiffre_affaires est numérique",
        "lọc…": "filtrer…",
        "Hủy": "Annuler",
        "Thực hiện thay": "Effectuer le remplacement",
        "xem trước": "aperçu",
        "tương tác": "interactif",
        "Soạn thảo": "Édition",
        "Giao diện": "Interface",
        "Phím tắt": "Raccourcis clavier",
        "Cỡ chữ": "Taille du texte",
        "Bề rộng TAB": "Largeur de tabulation",
        "Thụt lề bằng TAB": "Indenter avec des tabulations",
        "Tự động thụt lề khi xuống dòng": "Indenter automatiquement à la ligne suivante",
        "Tô mọi kết quả tìm kiếm": "Surligner tous les résultats de recherche",
        "Chuẩn hóa về NFC khi lưu": "Normaliser en NFC à l’enregistrement",
        "Ngôn ngữ": "Langue",
        "Nền": "Apparence",
        "Theo hệ thống": "Système",
        "Sáng": "Clair",
        "Tối": "Sombre",
        "Theme": "Thème",
        "Dùng preset Notepad++": "Utiliser le préréglage Notepad++",
        "Về phím mặc định": "Revenir aux touches par défaut",
        "Mở file cấu hình": "Ouvrir le fichier de configuration",
        "Xuất theme hiện tại": "Exporter le thème actuel",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "Le changement de langue s’applique entièrement au prochain lancement.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Les touches par défaut reviennent au prochain lancement.",
        "Xem trước Markdown": "Aperçu Markdown",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "L’aperçu utilise le moteur Markdown du système : pas encore de tableaux ni de coloration des blocs de code.",
        "Thử biểu thức chính quy": "Tester une expression régulière",
        "Biểu thức": "Expression",
        "Văn bản thử": "Texte d’essai",
        "Kết quả": "Résultat",
        "Kết quả khớp": "Correspondances",
        "Biểu thức này làm gì": "Ce que fait cette expression",
        "Giải thích biểu thức": "Expliquer l’expression",
        "Chế độ tìm kiếm": "Mode de recherche",
        "Kết quả tìm kiếm": "Résultats de recherche",
        "Không khớp chỗ nào": "Aucune correspondance",
        " (đã cắt bớt)": " (tronqué)",
        "Bản đồ tài liệu": "Carte du document",
        "Thanh tab": "Barre d’onglets",
        "Hàng tiêu đề cột": "Ligne d’en-tête des colonnes",
        "Không có cột nào": "Aucune colonne",
        "Cây thư mục workspace": "Arborescence de l’espace de travail",
        "Danh sách hàm và lớp": "Liste des fonctions et classes",
        "Kết quả tìm trong thư mục": "Résultats de recherche dans le dossier",
        "Bảng dữ liệu CSV": "Table de données CSV",
        "Bàn làm sạch dữ liệu": "Atelier de nettoyage des données",
        "Truy vấn JSONPath": "Requête JSONPath",
        "Danh sách lỗi dữ liệu": "Liste des erreurs de données",
        "Bộ đánh giá golden set…": "Évaluateur de golden set…",
        "So với điểm ngoài (JSONL)…": "Comparer à des scores externes (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Choisir un fichier de scores externes (JSONL : query, chunk_id, score)",
        "Đổi tên node đang chọn": "Renommer le nœud sélectionné",
        "Gộp các node đang chọn": "Fusionner les nœuds sélectionnés",
        "Tách node đang chọn": "Scinder le nœud sélectionné",
        "Trích subgraph đang chọn ra tab mới": "Extraire le sous-graphe sélectionné dans un nouvel onglet",
        "Không có gì để đổi": "Rien à changer",
        "%@ — áp %d thay đổi?": "%@ — appliquer %d {one=modification|other=modifications} ?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%@ : %d {one=modification|other=modifications} · Cmd-Z annule tout le lot",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Placez le curseur sur EXACTEMENT UN nœud puis réessayez",
        "Đổi tên «%@»": "Renommer « %@ »",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Toutes les arêtes et étiquettes référençant ce nœud suivront.",
        "Đổi tên node": "Renommer le nœud",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Sélectionnez AU MOINS DEUX nœuds puis réessayez",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Forme canonique « %@ » — la plus fréquente, la plus longue, accentuée",
        "Gộp node": "Fusionner les nœuds",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Sélectionnez les LIGNES D’ARÊTES à déplacer puis réessayez",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Toutes les lignes sélectionnées doivent toucher EXACTEMENT UN nœud — sélectionnez d’autres lignes d’arêtes",
        "Tách «%@» — chuyển %d cạnh": "Scinder « %@ » — déplacer %d {one=arête|other=arêtes}",
        "Cạnh tới: %@": "Arêtes vers : %@",
        "Tách node": "Scinder le nœud",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "Document non enregistré — le fichier extrait a besoin d’un emplacement voisin",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Sélectionnez la partie du graphe à extraire puis réessayez",
        "Gom biến thể entity → bảng duyệt": "Regrouper les variantes d’entités → table de révision",
        "Áp bảng duyệt đã sửa": "Appliquer la table de révision modifiée",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "Document non enregistré — la table de révision doit être à côté du fichier de graphe",
        "Không tìm thấy biến thể nào để gom": "Aucune variante à regrouper",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d {one=groupe de variantes|other=groupes de variantes} — corrigez la colonne « canonical » puis lancez « Appliquer la table de révision »",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Pas de table de révision « %@ » — lancez d’abord « Regrouper les variantes d’entités »",
        "Bảng duyệt không đọc được: %@": "Table de révision illisible : %@",
        "Bảng duyệt không có dòng nào cần đổi": "La table de révision n’a aucune ligne à modifier",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "Aucun endroit du graphe ne correspond à la table de révision",
        "Gom biến thể entity": "Regrouper les variantes d’entités",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d {one=modification appliquée|other=modifications appliquées} · table d’alias et liste de marqueurs écrites à côté du fichier",
        "Áp %d thay đổi lên đồ thị?": "Appliquer %d {one=modification|other=modifications} au graphe ?",
        "%d alias → dạng chuẩn.": "%d {one=alias|other=alias} → forme canonique.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "FUSIONNER des nœuds (impossible à défaire en retapant) :",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d {one=alias absent du graphe, ignoré|other=alias absents du graphe, ignorés}.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Analyse de couverture Segment ↔ Entité",
        "Xuất gói ngữ cảnh (JSONL)": "Exporter le paquet de contexte (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Couverture Segment ↔ Entité ↔ Graphe",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %d {one=entité|other=entités} · %d {one=segment|other=segments} · %.0f %% d’entités mentionnées · %.0f %% de segments avec entité",
        "Entity không chunk nào nhắc tới": "Entités qu’aucun segment ne mentionne",
        "Chunk mồ côi (không chứa entity nào)": "Segments orphelins (sans aucune entité)",
        "Node đồ thị không có entity đối ứng": "Nœuds du graphe sans entité correspondante",
        "không có": "aucun",
        "Phương pháp": "Méthode",
        "Không dựng được ánh xạ Chunk ↔ Entity": "Impossible de construire la correspondance Segment ↔ Entité",
        "Chấm sức khoẻ đồ thị": "Évaluer la santé du graphe",
        "sức khoẻ đồ thị": "santé du graphe",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Santé %@/100 · %d {one=erreur|other=erreurs} · %d {one=inversion|other=inversions} · %d orphelins",
        "Lai với đồ thị": "Hybride avec le graphe",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1 : signal du graphe totalement ignoré, résultat identique à BM25 pur",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "α élevé : le graphe n’ajuste que légèrement le classement BM25",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α autour de la valeur par défaut 0,7 : BM25 mène, le graphe ajuste",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "α faible : le graphe mène, BM25 ne fait que départager",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0 : signal du graphe seul ; les segments sans entité sont à égalité",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "Document non enregistré — l’hybride a besoin d’un fichier de graphe à côté du corpus",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Fichier de graphe « %@ » introuvable — l’hybride en a besoin pour son signal",
        "lai %.1f ms · %@": "hybride %.1f ms · %@",
        "Thuật toán…": "Algorithmes…",
        "PageRank (độ dày viền)": "PageRank (épaisseur du contour)",
        "Cộng đồng (màu nền)": "Communautés (couleur de fond)",
        "Thành phần liên thông": "Composantes connexes",
        "Xuất bảng node ra tab mới": "Exporter la table des nœuds dans un nouvel onglet",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%d {one=composante|other=composantes} · la plus grande %d {one=nœud|other=nœuds} · %d nœuds orphelins",
        "Tài liệu này không phải đồ thị DOT": "Ce document n’est pas un graphe DOT",
        "Không dựng được bảng node/cạnh: %@": "Impossible de construire la table nœuds/arêtes : %@",
        "%d hàng · %@": "%d {one=ligne|other=lignes} · %@",
        "Gán nhãn": "Étiqueter",
        "Ghi chú (tuỳ chọn)": "Note (facultatif)",
        "Lưu record": "Enregistrer l’enregistrement",
        "Xuất CSV": "Exporter en CSV",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "Document non enregistré — l’évaluateur doit être à côté du fichier de corpus",
        "Không nạp được bộ đánh giá: %@": "Impossible de charger l’évaluateur : %@",
        "Không lưu được: %@": "Enregistrement impossible : %@",
        "Bộ đánh giá chưa có record nào": "L’évaluateur n’a encore aucun enregistrement",
        "Không ghi được: %@": "Écriture impossible : %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Ce document n’est ni un fichier .mmd, ni du DOT, et n’a aucun bloc mermaid.",
        "%d node · %d cạnh · ⚠ %@": "%d {one=nœud|other=nœuds} · %d {one=arête|other=arêtes} · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Diagramme Mermaid : ajouter un élément…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Diagramme Mermaid : relier les deux éléments sélectionnés",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Diagramme Mermaid : modifier l’étiquette de l’élément sélectionné…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Diagramme Mermaid : supprimer l’élément sélectionné",
        "Sơ đồ Mermaid: đưa message lên trên": "Diagramme Mermaid : remonter le message",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Diagramme Mermaid : descendre le message",
        "Thêm phần tử": "Ajouter un élément",
        "Thêm participant": "Ajouter un participant",
        "Thêm mục": "Ajouter une entrée",
        "Thêm mục sơ đồ": "Ajouter une entrée au diagramme",
        "Sửa mục sơ đồ": "Modifier une entrée du diagramme",
        "Xoá mục sơ đồ": "Supprimer une entrée du diagramme",
        "Xoá phần tử": "Supprimer l’élément",
        "Sửa nhãn": "Modifier l’étiquette",
        "Đổi thứ tự message": "Réordonner les messages",
        "Tên mục": "Nom de l’entrée",
        "Mục mới": "Nouvelle entrée",
        "Tên mục hiện trên sơ đồ.": "Le nom de l’entrée apparaît sur le diagramme.",
        "Bảng thuộc tính sơ đồ": "Table des propriétés du diagramme",
        "Tài liệu này không có khối mermaid nào": "Ce document n’a aucun bloc mermaid",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Identifiant dans la source du diagramme — sans espaces. L’étiquette se modifie ensuite par double-clic.",
        "Để trống thì hiện chính định danh.": "Si vide, l’identifiant lui-même est affiché.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Seule l’ÉTIQUETTE affichée change ; l’identifiant de l’élément reste le même.",
        "Không rõ «%@» là phần tử nào": "Impossible de savoir quel élément est « %@ »",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Sélectionnez EXACTEMENT DEUX éléments puis réessayez",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Placez le curseur sur EXACTEMENT UN élément puis réessayez",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Choisissez UN élément à supprimer, ou deux éléments reliés par une arête",
        "Xoá «%@» và %d cạnh chạm nó?": "Supprimer « %@ » et les %d {one=arête qui le touche|other=arêtes qui le touchent} ?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Les nœuds à l’autre bout de ces arêtes sont conservés — ils sont redéclarés avec leur étiquette si l’instruction d’arête était leur seule déclaration.",
        "Sơ đồ «%@» chỉ soạn text — %@": "Le diagramme « %@ » se modifie uniquement en texte — %@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@ : glissez entre deux éléments pour relier, double-cliquez pour modifier l’étiquette",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@ : glissez entre deux participants pour ajouter un message ; réordonnez via le menu Outils",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@ : modifiez dans la table des propriétés ci-dessous",
        "Soạn trực quan đã bật": "Édition visuelle activée",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%@ · %d {one=entrée|other=entrées} — modifiez directement dans la table, chaque cellule est une annulation",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Pour un camembert, un nombre ; pour un gantt, ce qui suit les deux-points.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Diagramme Mermaid : extraire le bloc dans un fichier .mmd…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Diagramme Mermaid : réintégrer le fichier référencé",
        "Tách khối sơ đồ": "Extraire le bloc du diagramme",
        "Nhúng khối sơ đồ": "Réintégrer le bloc du diagramme",
        "Tách khối sơ đồ ra tệp riêng": "Extraire le bloc du diagramme dans un fichier séparé",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "Le fichier est placé À CÔTÉ du document ; le bloc conserve une ligne de référence pour n’éditer qu’à un seul endroit.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "Document non enregistré — le fichier du diagramme a besoin d’un emplacement voisin",
        "Đã có tệp «%@» — chọn tên khác": "Le fichier « %@ » existe déjà — choisissez un autre nom",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Extrait dans « %@ » — le bloc conserve une ligne de référence",
        "Mở tệp": "Ouvrir le fichier",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "« %@ » réintégré ; le fichier reste sur le disque",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Ce bloc contient un vrai diagramme, pas une référence",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Ce bloc référence « %@ » — ouvrez ce fichier pour le modifier",
        "Không đọc được tệp sơ đồ %@": "Impossible de lire le fichier de diagramme %@",
        "Soạn trực quan": "Édition visuelle",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Glissez d’un nœud à un autre pour ajouter une arête ; double-cliquez pour modifier l’étiquette. Chaque action est une annulation.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Édition visuelle : glissez entre deux nœuds pour ajouter une arête, double-cliquez pour modifier l’étiquette",
        "Soạn trực quan đã tắt": "Édition visuelle désactivée",
        "Thêm node…": "Ajouter un nœud…",
        "Thêm cạnh giữa hai node đang chọn…": "Ajouter une arête entre les deux nœuds sélectionnés…",
        "Sửa nhãn node đang chọn…": "Modifier l’étiquette du nœud sélectionné…",
        "Xoá node/cạnh đang chọn": "Supprimer le nœud/l’arête sélectionné",
        "Thêm node": "Ajouter un nœud",
        "Thêm cạnh": "Ajouter une arête",
        "Sửa nhãn node": "Modifier l’étiquette du nœud",
        "Xoá node": "Supprimer le nœud",
        "Xoá cạnh": "Supprimer l’arête",
        "Cmd-Z hoàn tác": "Cmd-Z pour annuler",
        "Tài liệu đang ở chế độ chỉ đọc": "Ce document est en lecture seule",
        "Nhãn của «%@»": "Étiquette de « %@ »",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Seule l’ÉTIQUETTE affichée change ; l’identifiant du nœud reste le même.",
        "Không rõ «%@» là node nào": "Impossible de savoir quel nœud est « %@ »",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "Identifiant du nœud dans le fichier DOT. L’étiquette se modifie ensuite par double-clic sur le graphique.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Sélectionnez EXACTEMENT DEUX nœuds puis réessayez",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Choisissez UN nœud à supprimer, ou deux nœuds reliés par une arête",
        "Xoá node «%@» và %d cạnh chạm nó?": "Supprimer le nœud « %@ » et les %d {one=arête qui le touche|other=arêtes qui le touchent} ?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Si les arêtes orphelines restent, DOT recrée les nœuds à partir d’elles — le nœud supprimé réapparaîtra au tracé suivant.",
        "Phòng thí nghiệm truy hồi BM25": "Laboratoire de recherche BM25",
        "Câu hỏi — Enter để tìm": "Question — Entrée pour rechercher",
        "Đánh giá…": "Évaluer…",
        "Đang dựng chỉ mục": "Construction de l’index",
        "Không chunk nào khớp": "Aucun segment ne correspond",
        "kết quả trên": "meilleurs résultats",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0 : chaque mot ne compte QU’UNE fois, quel que soit le nombre d’occurrences",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "k1 faible : répéter un mot n’ajoute presque rien au score",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 autour de la valeur par défaut 1,2 : la répétition ajoute du score, de façon décroissante",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "k1 élevé : un segment répétant un mot est fortement récompensé",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0 : la longueur est ignorée, les segments longs ne sont pas pénalisés",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "b faible : les segments longs ne sont que légèrement pénalisés",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b autour de la valeur par défaut 0,75 : les segments longs sont modérément pénalisés",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1 : pénalité maximale selon la longueur, les segments courts sont favorisés",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL : laboratoire de recherche…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "Document non enregistré — l’index BM25 vit à côté du fichier de corpus et a donc besoin d’un chemin",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Ce fichier n’est pas du JSONL — le Retrieval Lab fonctionne sur un corpus de segments",
        "Không dựng được chỉ mục BM25 cho tệp này": "Impossible de construire un index BM25 pour ce fichier",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "Document non enregistré — un chemin de corpus est nécessaire pour générer le rapport",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Choisir un jeu d’évaluation (CSV ou JSONL : question + identifiant de segment attendu)",
        "Đánh giá truy hồi": "Évaluation de la recherche",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Modifiez k1, b ou k ci-dessus puis réexaminez pour comparer deux configurations ; ajoutez un bloc « compare » pour exécuter deux jeux de paramètres en parallèle sur le même jeu d’évaluation.",
        "Lỗi": "Erreur",
        "   (%d…%d, trung bình %.0f)": "   (%d…%d, moyenne %.0f)",
        "Chế độ JSONL": "Mode JSONL",
        "Bản ghi": "Enregistrement",
        "Chi tiết": "Détail",
        "Bản ghi ở dòng": "Enregistrement à la ligne",
        "không phải JSON hợp lệ": "n’est pas du JSON valide",
        "bản ghi": "enregistrements",
        "dòng trắng": "lignes vides",
        "không phải đối tượng": "n’est pas un objet",
        "bảng hiện": "table affichée",
        "ĐÃ HUỶ giữa chừng": "ANNULÉ en cours de route",
        "Không lọc": "Aucun filtre",
        "bản ghi khớp bộ lọc": "enregistrements correspondant au filtre",
        "Đưa con nháy tới một dòng để xem bản ghi": "Placez le curseur sur une ligne pour voir l’enregistrement",
        "Không có bản ghi nào hỏng": "Aucun enregistrement défectueux",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Pas encore inspecté. Relancez « JSONL : inspecter les segments » après la vérification.",
        "trường văn bản": "champ texte",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SCHÉMA (deviné — modifiable en choisissant un autre champ)",
        "văn bản": "texte",
        "định danh": "identifiant",
        "metadata lồng": "métadonnées imbriquées",
        "TRƯỜNG": "CHAMP",
        "phủ": "couverture",
        "nhiều kiểu": "types multiples",
        "ĐỘ DÀI — ký tự": "LONGUEUR — caractères",
        "ĐỘ DÀI — từ": "LONGUEUR — mots",
        "ĐỘ DÀI — token ước lượng": "LONGUEUR — jetons estimés",
        "RỖNG VÀ TRÙNG": "VIDES ET DOUBLONS",
        "chunk rỗng": "segments vides",
        "dòng": "lignes",
        "nhóm trùng chính xác": "groupes de doublons exacts",
        "dòng không đọc được, không vào thống kê": "lignes illisibles, hors statistiques",
        "PHƯƠNG PHÁP": "MÉTHODE",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "« caractères » compte les caractères Unicode (scalaires), pas les groupes affichés",
        "«từ» tách theo khoảng trắng ASCII": "« mots » découpe sur les espaces ASCII",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "« jetons » compte avec un découpeur de syllabes — CE N’EST PAS celui du modèle",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "« doublon » signifie doublon EXACT ; les quasi-doublons sont dans le bloc ```quality",
        "chunk": "segments",
        "JSONL: kiểm và soi chunk…": "JSONL : vérifier et inspecter les segments…",
        "Ảnh": "Image",
        "PDF": "PDF",
        "Tài liệu Word": "Document Word",
        "Bảng tính Excel": "Feuille de calcul Excel",
        "Bản trình chiếu PowerPoint": "Présentation PowerPoint",
        "File nén": "Archive",
        "Vừa khung": "Ajuster à la fenêtre",
        "Chép ảnh": "Copier l’image",
        "Xoay": "Pivoter",
        "Không đọc được ảnh «%@»": "Impossible de lire l’image « %@ »",
        "Đã chép ảnh vào clipboard": "Image copiée dans le presse-papiers",
        "Bôi vàng": "Surligner en jaune",
        "Gạch chân": "Souligner",
        "Ghi chú…": "Note…",
        "Bỏ chú thích": "Retirer les annotations",
        "Lấy chữ ra tab mới": "Extraire le texte dans un nouvel onglet",
        "Lưu bản có chú thích…": "Enregistrer la version annotée…",
        "Tìm trong PDF": "Rechercher dans le PDF",
        "Thêm": "Ajouter",
        "Trang %d/%d": "Page %d/%d",
        "Trang %d": "Page %d",
        "Kết quả %d/%d": "Résultat %d/%d",
        "0 kết quả": "0 résultat",
        "Không đọc được PDF «%@»": "Impossible de lire le PDF « %@ »",
        "PDF này có mật khẩu — chưa mở được nội dung": "Ce PDF est protégé par mot de passe — contenu inaccessible",
        "Không thấy «%@» trong tài liệu": "« %@ » introuvable dans le document",
        "Đã bôi vàng": "Surligné",
        "Đã gạch chân": "Souligné",
        "Hãy bôi đen một đoạn chữ trước": "Sélectionnez d’abord un passage de texte",
        "Đã thêm ghi chú": "Note ajoutée",
        "Trang này chưa có chú thích nào": "Cette page n’a aucune annotation",
        "Đã bỏ %d chú thích trên trang này": "%d {one=annotation retirée|other=annotations retirées} de cette page",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Ce PDF n’a pas de couche de texte — il s’agit probablement d’un scan",
        "Không ghi được tệp": "Impossible d’écrire le fichier",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Le fichier écrit ne se rouvre PAS correctement — n’utilisez pas cette version",
        "Đã lưu %@ · %d trang": "%@ enregistré · %d {one=page|other=pages}",
        "Tên": "Nom",
        "Kích thước": "Taille",
        "Đã nén": "Compressé",
        "Tỉ lệ": "Ratio",
        "Sửa lúc": "Modifié le",
        "Mở mục đang chọn": "Ouvrir l’élément sélectionné",
        "Bung ra thư mục…": "Extraire vers un dossier…",
        "Bung vào đây": "Extraire ici",
        "%d mục": "%d {one=élément|other=éléments}",
        "giải nén ra %@": "extrait vers %@",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— l’intérieur d’un fichier Office est une archive ; voici ses composants",
        "Đã bung %d mục": "%d {one=élément extrait|other=éléments extraits}",
        "%d mục hỏng": "%d {one=élément défectueux|other=éléments défectueux}",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d {one=élément REFUSÉ|other=éléments REFUSÉS} — leurs chemins sortent du dossier de destination",
        "Không mở được mục này": "Impossible d’ouvrir cet élément",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "Impossible d’écrire directement dans un %@ pour l’instant — utilisez « Enregistrer sous… »",
        "Không có gì đổi": "Rien n’a changé",
        "Đã ghi %d ô vào %@": "%d {one=cellule écrite|other=cellules écrites} dans %@",
        "Đã ghi %d đoạn vào %@": "%d {one=paragraphe écrit|other=paragraphes écrits} dans %@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "Impossible d’écrire dans le fichier — l’original est intact",
        "dựng bài": "préparer le cas de test",
        "Không ghi được settings.json": "Impossible d’écrire settings.json",
        "Xoay trái": "Pivoter à gauche",
        "Xoay phải": "Pivoter à droite",
        "Trang lên": "Monter la page",
        "Trang xuống": "Descendre la page",
        "Xoá trang…": "Supprimer des pages…",
        "Xoá trang": "Supprimer des pages",
        "Trích trang…": "Extraire des pages…",
        "Trích trang ra tệp mới": "Extraire les pages vers un nouveau fichier",
        "Gộp tệp PDF…": "Fusionner un PDF…",
        "Tách tệp…": "Diviser le fichier…",
        "Tách tệp PDF": "Diviser le fichier PDF",
        "Xuất ảnh…": "Exporter en images…",
        "Xuất trang ra ảnh PNG": "Exporter les pages en images PNG",
        "Hoàn tác trang": "Annuler l'action sur la page",
        "Lưu bản đã sửa…": "Enregistrer la copie modifiée…",
        "Phát": "Lire",
        "Tạm dừng": "Pause",
        "Xem bình thường": "Vue normale",
        "Chọn sheet": "Choisir la feuille",
        "Mở sheet": "Ouvrir la feuille",
        "Bỏ và đổi sheet": "Abandonner et changer de feuille",
        "Bảng tính có %d sheet.": "Le classeur contient %d feuilles.",
        "Bảng tính này chỉ có một sheet: «%@»": "Ce classeur ne contient qu'une feuille : « %@ »",
        "Bỏ phần chưa lưu của sheet này?": "Abandonner les modifications non enregistrées de cette feuille ?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "Changer de feuille remplace tout l'onglet. Ce qui n'a pas été enregistré avec ⌘S sera perdu.",
        "Chọn tệp PDF cần gộp vào": "Choisir le PDF à fusionner",
        "Chọn thư mục ghi ảnh": "Choisir le dossier des images",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Choisissez l'emplacement. Le second fichier sera écrit à côté de celui-ci.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "Le document a %d pages. Saisissez les pages à supprimer, ex. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "Le document a %d pages. Saisissez les pages à extraire, ex. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "Le document a %d pages. Saisissez les pages à exporter, ex. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "Le document a %d pages. Saisissez la partie à détacher, ex. 1-5 ; le reste devient un second fichier.",
        "Đã xoay trang %d": "Page %d pivotée",
        "Đã xoá trang %@ · còn %d trang": "Pages %@ supprimées · %d pages restantes",
        "Đã gộp %d trang từ «%@»": "%d pages fusionnées depuis « %@ »",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Divisé en %@ (%d pages) et %@ (%d pages)",
        "Đã ghi %@ — %@ · %d trang": "%@ écrit — %@ · %d pages",
        "Đã xuất %d ảnh vào %@": "%d images exportées vers %@",
        "Chỉ xuất được %d/%d ảnh": "Seules %d images sur %d ont été exportées",
        "Đã hoàn tác một thao tác trang": "Une action sur la page a été annulée",
        "Không còn thao tác trang nào để hoàn tác": "Plus aucune action sur la page à annuler",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Impossible de supprimer TOUTES les pages — un PDF doit en garder au moins une",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Cette plage correspond à tout le document — rien à détacher",
        "«%@» có mật khẩu — chưa gộp được": "« %@ » est protégé par mot de passe — fusion impossible",
        "«%@» không có trang nào": "« %@ » ne contient aucune page",
        "Đã ở trang đầu": "Déjà à la première page",
        "Đã ở trang cuối": "Déjà à la dernière page",
        "· đã sửa, chưa lưu": "· modifié, non enregistré",
        "Ảnh động · %d khung": "Image animée · %d images",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Document non enregistré — aucun fichier sur le disque à afficher en binaire",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Cette commande ne fonctionne qu'avec les classeurs Excel",
        "Không đọc được danh sách sheet": "Impossible de lire la liste des feuilles",
        "Không có sheet «%@»": "Aucune feuille nommée « %@ »",
        "Không đọc được sheet «%@»": "Impossible de lire la feuille « %@ »",
        "Sheet «%@» · %d hàng": "Feuille « %@ » · %d lignes",
        "phần còn lại": "le reste",
        "Lưu ý": "Remarque",
        "Cẩn thận": "Attention",
        "Xem thêm": "Voir aussi",
        "Chép": "Copier",
        "Đã chép": "Copié",
        "Chép đoạn mã mẫu": "Copier l'exemple de code",
        "Tìm trong trợ giúp": "Rechercher dans l'aide",
        "Lùi": "Retour",
        "Bắt đầu dùng": "Commencer",
        "Không mở cửa sổ này khi khởi động nữa": "Ne plus afficher cette fenêtre au démarrage",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "L'aide n'est pas encore traduite dans cette langue — affichage en vietnamien.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Aller à l'offset (ex. 1F400 ou 0x1F400)",
        "Chép dòng đã chọn": "Copier les lignes sélectionnées",
        "Đã chép %d dòng": "%d lignes copiées",
        "Không đọc được «%@»": "Impossible de lire « %@ »",
        "Tệp rỗng": "Fichier vide",
        "Không đọc được offset «%@»": "Offset « %@ » illisible",
        "Offset 0x%@ vượt quá cỡ tệp": "L'offset 0x%@ dépasse la taille du fichier",
        "Mở bằng ứng dụng khác…": "Ouvrir avec une autre app…",
        "%d kênh": "%d canaux",
        "Không phát được «%@»": "Impossible de lire « %@ »",
        "Không phát được — %@": "Lecture impossible — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "macOS n'a pas de décodeur intégré pour le format %@ — c'est une limite du système, pas un fichier corrompu.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "Vous pouvez toujours voir les octets en mode binaire, ou l'ouvrir avec une app disposant de son propre décodeur.",
        "Ký…": "Signer…",
        "Sửa chữ…": "Modifier le texte…",
        "Sửa chữ": "Modifier le texte",
        "Vẽ đè": "Dessiner par-dessus",
        "Ô chưa điền": "Champ vide suivant",
        "Xoá nội dung đã điền": "Effacer les champs remplis",
        "Tệp này không có ô biểu mẫu nào": "Ce fichier n'a aucun champ de formulaire",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d champs de formulaire effacés",
        "Mọi ô biểu mẫu đều đã có nội dung": "Tous les champs de formulaire sont remplis",
        "Còn %d ô chưa điền": "%d champs encore vides",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Formulaire à remplir : %d champs. Saisissez directement, puis « Enregistrer la copie modifiée… »",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Choisir une image de signature (fond transparent de préférence)",
        "Không dựng được trang có chữ ký": "Impossible de créer la page signée",
        "Đã chèn chữ ký vào trang %d": "Signature insérée à la page %d",
        "Hãy bôi chọn phần chữ cần sửa trước": "Sélectionnez d'abord le texte à modifier",
        "Vùng chọn quá nhỏ": "La sélection est trop petite",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Le nouveau texte est DESSINÉ PAR-DESSUS la sélection avec la police système. L'ancien texte est masqué, pas supprimé — il reste extractible, ce n'est donc pas un caviardage.",
        "Không dựng được trang đã sửa": "Impossible de créer la page modifiée",
        "Đã vẽ đè chữ mới lên trang %d": "Nouveau texte dessiné sur la page %d",
        "Đổi chế độ View / Code": "Basculer Vue / Code",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Pas encore de vue arborescente pour JSON · XML · YAML",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Pas encore de vue schéma dans l'onglet",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Pas encore de vue plan pour PowerPoint",
        "Tệp này chỉ có một chế độ hiển thị": "Ce fichier n'a qu'un seul mode d'affichage",
        "%d nút": "%d nœuds",
        "Không dựng được cây: %@": "Impossible de construire l'arbre : %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "Le document est trop grand pour un arbre — utilisez le mode Code",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Impossible de construire les pages de ce fichier \u{2014} utilisez le mode Code.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "Les diapositives sont construites à partir du texte ; les images et la mise en page d'origine ne sont pas encore dessinées.",
        "Vừa ngang": "Ajuster à la largeur",
        "Thu nhỏ trang": "Réduire la page",
        "Phóng to trang": "Agrandir la page",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu":
            "\u{201C}%@\u{201D} est introuvable dans le document",
        "Chỗ khớp %d/%d": "Correspondance %d sur %d",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Aucun texte n'est sélectionné sur la page.",
        "%d ký tự": "%d {one=caractère|other=caractères}",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "Ouvrir les fichiers directement en mode View lorsqu'il existe",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· ANNULÉ en cours de route — tableau incomplet",
        "Chế độ hiển thị": "Mode d'affichage",
        "Đổi giữa View và Code (⌥⌘V)": "Basculer entre View et Code (⌥⌘V)",
        "Trang tài liệu": "Pages du document",
        "Chữ đã dựng": "Texte rendu",
        "Trang bảng tính": "Pages du classeur",
        "Sơ đồ": "Diagramme",
        "Cây khoá–giá trị": "Arbre clé–valeur",
        "Bộ phát": "Lecteur",
        "Danh sách mục": "Liste des entrées",
        "Báo cáo đã dựng": "Rapport rendu",
        "Tô theo mức": "Coloré par niveau",
        "Trang slide": "Pages des diapositives",
        "Dàn ý": "Plan",
        "Lưu rồi dựng lại": "Enregistrer puis reconstruire",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "Affiche la copie SUR LE DISQUE — les modifications non enregistrées n'y sont pas.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "Le système n'a pas pu construire la visionneuse — utilisez le mode Code.",
        "Lưu tệp trước khi xem trang.": "Enregistrez le fichier avant d'afficher ses pages.",
        "Đang ở chế độ Code": "Actuellement en mode Code",
        "Đang ở chế độ View": "Actuellement en mode View",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "Vous voyez la source — cliquez pour passer en mode View (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "En mode View — cliquez pour revenir à la source (⌥⌘V)",
        "Tín hiệu: %@": "Signal : %@",
        "Lý do: %@": "Raison : %@",
        "Chi tiết: %@": "Détail : %@",
        "Mở báo cáo": "Ouvrir le rapport",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "GEditor s'est arrêté brutalement à %@ — ouvrez le rapport pour le lire ; rien n'est envoyé.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligatures — désactivées, chaque caractère garde sa case",
        "Chế độ CSV": "Mode CSV",
        "Dấu phân tách": "Séparateur",
        "Tự nhận diện": "Détecter automatiquement",
        "Dấu phân tách: %@": "Séparateur : %@",
        "Theo đuôi tệp": "D'après l'extension",
        "%d dấu cách": "%d {one=espace|other=espaces}",
        "Tài liệu đang sửa được": "Ce document est modifiable",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Lecture seule : le fichier est suivi — arrêtez le suivi pour modifier",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Lecture seule : le fichier sur le disque n'est pas inscriptible",
        "Đã mở khoá — tài liệu sửa được": "Déverrouillé — le document est de nouveau modifiable",
        "Nhân bản tệp": "Dupliquer le fichier",
        "Đổi tên tệp…": "Renommer le fichier…",
        "Chuyển tệp tới…": "Déplacer le fichier vers…",
        "XML: đánh giá XPath…": "XML : évaluer XPath…",
        "Đánh giá XPath": "Évaluer XPath",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Par exemple : //commande/article[2]/@code · //*[@type='A'] · count(//article)",
        "Đánh giá": "Évaluer",
        "XPath không đọc được: %@": "XPath illisible : %@",
        "XPath «%@» không khớp node nào": "XPath « %@ » n'a trouvé aucun nœud",
        "XPath «%@» — %d node": "XPath « %@ » — %d {one=nœud|other=nœuds}",
        "XPath «%@»: %d node": "XPath « %@ » : %d {one=nœud|other=nœuds}",
        "Lưu tệp trước khi nhân bản.": "Enregistrez le fichier avant de le dupliquer.",
        "Không nhân bản được": "Duplication impossible",
        "Đã nhân bản thành %@": "Dupliqué sous %@",
        "Lưu tệp trước khi đổi tên.": "Enregistrez le fichier avant de le renommer.",
        "Đổi tên tệp": "Renommer le fichier",
        "Tên hiện tại: %@": "Nom actuel : %@",
        "Đổi tên": "Renommer",
        "Tên tệp không hợp lệ": "Ce nom de fichier n'est pas valide",
        "Đã có tệp tên %@ ở đó": "Il y a déjà un fichier nommé %@ à cet endroit",
        "Lưu tệp trước khi chuyển.": "Enregistrez le fichier avant de le déplacer.",
        "Chuyển tới": "Déplacer ici",
        "Thư mục đích đã có tệp tên %@": "Le dossier de destination contient déjà un fichier nommé %@",
        "Không chuyển được tệp": "Impossible de déplacer le fichier",
        "Đã chuyển tới %@": "Déplacé vers %@",
        "Bảng mã:": "Encodage :",
        "Xuống dòng:": "Fins de ligne :",
        "Riêng cho %@": "Seulement pour %@",
        "    %d — dùng TAB": "    %d — tabulations",
        "    %d — dùng dấu cách": "    %d — espaces",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Supprimer la règle propre, utiliser le réglage global",
        "%@: thụt lề %d %@": "%@ : indentation %d %@",
        "TAB": "tabulations",
        "dấu cách": "espaces",
        "Xuất": "Exporter",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Ouvrir les résultats dans un onglet texte — enregistrez avec ⌘S",
        "Lượt tìm trước đó": "Recherches précédentes",
        "«%@» — %d kết quả": "« %@ » — %d {one=résultat|other=résultats}",
        "Kết quả tìm «%@»": "Résultats de recherche pour « %@ »",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Filtrer les noms — par ex. *.csv;*.log (vide : tous les fichiers texte)",
        "Thư mục %@ không có file văn bản nào": "Le dossier %@ ne contient aucun fichier texte",
        "Không tệp nào trong %@ khớp «%@»": "Aucun fichier de %@ ne correspond à « %@ »",
        "%d byte · %d dòng": "%d octets · %d {one=ligne|other=lignes}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d octets · %d {one=ligne|other=lignes} — trop volumineux pour compter caractères et mots",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d octets · %d {one=caractère|other=caractères} · %d {one=mot|other=mots} · %d {one=ligne|other=lignes}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Ce document a %d {one=ligne|other=lignes}, %d octets. Saisissez un numéro de ligne, « ligne,colonne » ou « @octet ».",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "Impossible de lire « %@ » — saisissez un numéro de ligne, « ligne,colonne » ou « @octet »",
    ]
}
