import Foundation

/// Bảng dịch tiếng Hungary. Sinh bằng `scripts/gen-language.py` — xem chú thích ở đó.
///
/// Khoá lấy NGUYÊN VĂN từ bảng tiếng Anh, nên không khoá nào lệch được. Chuỗi thiếu ở đây rơi
/// về tiếng Anh chứ không về tiếng Việt — xem `L10n.translate`.
extension L10n {

    static let hu: [String: String] = [
        "Bản đã lưu…": "Mentett változatok…",
        "Tài liệu chưa lưu lần nào — chưa có lịch sử": "Ezt a dokumentumot még soha nem mentették — nincs előzmény",
        "Chưa có bản đã lưu nào trước đó": "Nincs korábbi mentett változat",
        "Không đọc được bản ấy": "Ezt a változatot nem lehet elolvasni",
        "Khôi phục bản đã lưu": "Mentett változat visszaállítása",
        "XML: kiểm theo DTD/XSD…": "XML: ellenőrzés DTD/XSD szerint…",
        "Máy này không có libxml2 nên không kiểm được XSD.": "Ezen a Macen nincs libxml2, ezért az XSD-ellenőrzés nem érhető el.",
        "Chọn lược đồ XSD để kiểm": "Válasszon XSD-sémát az ellenőrzéshez",
        "Hợp lệ theo": "Megfelel ennek:",
        "Plugin chạy xong, không đổi gì": "A bővítmény úgy fejezte be, hogy semmit sem változtatott",
        "Chưa cài plugin native nào": "Nincs telepítve natív bővítmény",
        "Gỡ plugin này": "A bővítmény eltávolítása",
        "Gỡ plugin này?": "Eltávolítja ezt a bővítményt?",
        "Gỡ": "Eltávolítás",
        "Cài plugin native…": "Natív bővítmény telepítése…",
        "Mở thư mục plugin": "A bővítmények mappájának megnyitása",
        "Chọn file .dylib của plugin native": "Válassza ki a bővítmény .dylib fájlját",
        "Đã cài:": "Telepítve:",
        "Đã gỡ:": "Eltávolítva:",
        "Plugin native…": "Natív bővítmények…",
        "Chỉ nhận file .dylib.": "Csak .dylib fájlok fogadhatók el.",
        "Đã có một plugin trùng tên:": "Ilyen nevű bővítmény már telepítve van:",
        "Không chép được plugin:": "A bővítményt nem lehet átmásolni:",
        "Plugin native chỉ có ở bản tải trực tiếp, không có ở bản App Store.": "A natív bővítmények csak a közvetlen letöltésben érhetők el, az App Store-os változatban nem.",
        "Không tìm thấy tiến trình phụ chạy plugin.": "Nem található a bővítmények segédfolyamata.",
        "Không khởi động được tiến trình phụ:": "A bővítmények segédfolyamata nem indítható el:",
        "Tiến trình plugin đã dừng giữa chừng.": "A bővítményfolyamat váratlanul leállt.",
        "Plugin không trả lời kịp — đã dừng nó.": "A bővítmény nem válaszolt időben — leállítottuk.",
        "Plugin trả lời sai giao thức:": "A bővítmény hibás formátumú üzenettel válaszolt:",
        "Plugin báo lỗi:": "A bővítmény hibát jelzett:",
        "Về GEditor": "A GEditor névjegye",
        "Cài đặt…": "Beállítások…",
        "Thoát GEditor": "Kilépés a GEditorból",
        "File": "Fájl",
        "Tab mới": "Új lap",
        "Đóng tab": "A lap bezárása",
        "Tab kế": "Következő lap",
        "Tab trước": "Előző lap",
        "Tài liệu mới": "Új dokumentum",
        "Mở…": "Megnyitás…",
        "Mở thư mục làm Workspace…": "Mappa megnyitása munkaterületként…",
        "Mở gần đây": "Legutóbbiak",
        "Lưu": "Mentés",
        "Lưu thành…": "Mentés másként…",
        "Cắt khoảng trắng cuối dòng khi lưu": "A sorvégi szóközök levágása mentéskor",
        "Theo dõi file (tail -f)": "A fájl követése (tail -f)",
        "In…": "Nyomtatás…",
        "Mở lại tab vừa đóng": "Az utoljára bezárt lap újranyitása",
        "Chưa có file nào": "Nincs legutóbbi fájl",
        "Xoá danh sách": "A menü ürítése",
        "Edit": "Szerkesztés",
        "Hoàn tác": "Visszavonás",
        "Làm lại": "Újra",
        "Cắt": "Kivágás",
        "Sao chép": "Másolás",
        "Dán": "Beillesztés",
        "Lịch sử clipboard…": "A vágólap előzményei…",
        "Column Editor…": "Oszlopszerkesztő…",
        "Chọn lần kế tiếp": "A következő előfordulás kijelölése",
        "Chọn tất cả": "Az összes kijelölése",
        "Nhân đôi dòng": "A sor kettőzése",
        "Xóa dòng": "A sor törlése",
        "Comment dòng": "Megjegyzésbe / vissza",
        "Chưa chép gì trong phiên này": "Még nem másolt semmit",
        "Xoá lịch sử": "Az előzmények törlése",
        "Search": "Keresés",
        "Tìm…": "Keresés…",
        "Tìm và thay…": "Keresés és csere…",
        "Tìm trong thư mục…": "Keresés a mappában…",
        "Thay trong thư mục…": "Csere a mappában…",
        "Kết quả kế": "Következő találat",
        "Kết quả trước": "Előző találat",
        "Đi tới dòng…": "Ugrás a sorra…",
        "Nhảy tới ngoặc khớp": "Ugrás a párzárójelre",
        "Đánh dấu mọi dòng khớp…": "Az összes illeszkedő sor megjelölése…",
        "Đảo dấu": "A megjelölés megfordítása",
        "Bỏ mọi dấu": "Az összes jelölés törlése",
        "Chép dòng đã đánh dấu": "A megjelölt sorok másolása",
        "Xóa dòng đã đánh dấu": "A megjelölt sorok törlése",
        "Chỉ giữ dòng đã đánh dấu": "Csak a megjelölt sorok megtartása",
        "Lines": "Sorok",
        "Sắp xếp A→Z": "Rendezés A→Z",
        "Sắp xếp Z→A": "Rendezés Z→A",
        "Sắp xếp tự nhiên": "Természetes rendezés",
        "Khử trùng lặp": "Az ismétlődések eltávolítása",
        "Đảo thứ tự dòng": "A sorok megfordítása",
        "Dời dòng lên": "A sorok mozgatása felfelé",
        "Dời dòng xuống": "A sorok mozgatása lefelé",
        "Ghép dòng": "A sorok összefűzése",
        "Tách dòng theo độ dài…": "A sorok vágása hossz szerint…",
        "Tách dòng theo ký tự…": "A sorok vágása karakter szerint…",
        "Xóa dòng rỗng": "Az üres sorok eltávolítása",
        "Nén dòng trống liên tiếp": "Az üres sorok összevonása",
        "Cắt khoảng trắng cuối dòng": "A sorvégi szóközök levágása",
        "Tab → Space": "Tabulátor → szóköz",
        "Space → Tab": "Szóköz → tabulátor",
        "HOA": "NAGYBETŰS",
        "thường": "kisbetűs",
        "Chữ Hoa Đầu Từ": "Szókezdő Nagybetűs",
        "Chữ hoa đầu câu": "Mondatkezdő nagybetűs",
        "Đảo hoa/thường": "kIS- ÉS nAGYBETŰK cSERÉJE",
        "camelCase": "camelCase",
        "snake_case": "snake_case",
        "kebab-case": "kebab-case",
        "CSV": "CSV",
        "CSV: chọn sheet…": "CSV: munkalap választása…",
        "Xem dạng bảng / văn bản": "Váltás táblázat- és szövegnézet között",
        "Xóa cột…": "Az oszlop törlése…",
        "Kiểm tra dữ liệu (số cột · kiểu)": "Az adatok ellenőrzése (oszlopok · típusok)",
        "Bàn làm sạch dữ liệu…": "Adattisztító pult…",
        "Chạy công thức làm sạch…": "Tisztítási recept futtatása…",
        "Chuyển đổi…": "Átalakítás…",
        "Đổi dấu phân tách…": "Az elválasztó megváltoztatása…",
        "Xuất sang JSON…": "Exportálás JSON-be…",
        "Format": "Formátum",
        "Bảng mã…": "Kódolás…",
        "Xuống dòng…": "Sorvégek…",
        "Chuẩn hóa Unicode…": "Unicode-egységesítés…",
        "JSON: định dạng lại": "JSON: formázás",
        "JSON: thu gọn một dòng": "JSON: tömörítés",
        "JSON: sắp xếp khóa": "JSON: a kulcsok rendezése",
        "JSON: truy vấn JSONPath…": "JSON: JSONPath lekérdezés…",
        "CSV: truy vấn SQL…": "CSV: SQL lekérdezés…",
        "Truy vấn SQL": "SQL lekérdezés",
        "Đang chạy…": "Fut…",
        "Xuất ra tab mới": "Exportálás új lapra",
        "Tài liệu rỗng — không có bảng để truy vấn": "Üres dokumentum — nincs lekérdezhető táblázat",
        "Không nhận ra bảng CSV — dòng đầu chỉ có một cột": "Ez nem CSV-táblázat — az első sorban csak egy oszlop van",
        "Không đọc được câu truy vấn": "A lekérdezést nem sikerült elolvasni",
        "Không kiểm được câu truy vấn": "A lekérdezést nem sikerült ellenőrizni",
        "Vàng (mặc định)": "Sárga (alapértelmezett)",
        "Xanh dương": "Kék",
        "Xanh lá": "Zöld",
        "Vàng đất": "Okker",
        "Tím": "Lila",
        "Hồng": "Rózsaszín",
        "Xanh ngọc": "Türkiz",
        "Cam": "Narancs",
        "Xám lam": "Palaszürke",
        "Văn bản": "Szöveg",
        "Dãy số": "Számsorozat",
        "Dãy ngày": "Dátumsorozat",
        "Chữ HOA (hex)": "Nagybetűs (hexa)",
        "Bắt đầu": "Kezdet",
        "Bước": "Lépés",
        "Đệm 0 tới": "Nullákkal ennyi jegyre",
        "Hệ": "Számrendszer",
        "Ngày đầu": "Első dátum",
        "Định dạng": "Formátum",
        "Chèn": "Beszúrás",
        "Huỷ": "Mégse",
        "Chuyển đổi định dạng": "A formátum átalakítása",
        "Xem trước 5 hàng đầu": "Az első 5 sor előnézete",
        "Tạo tab mới": "Megnyitás új lapon",
        "Lưu ra file…": "Mentés fájlba…",
        "Kết quả mở thành tab mới, chưa lưu. Tài liệu gốc không đổi.": "Az eredmény új, nem mentett lapon nyílik meg. Az eredeti dokumentum érintetlen marad.",
        "Chạy trên tài liệu này": "Futtatás ezen a dokumentumon",
        "Chạy trên thư mục…": "Futtatás egy mappán…",
        "Cả công thức là MỘT bước undo. Tài liệu gốc trên đĩa không đổi cho tới khi anh lưu.": "Az egész recept EGY visszavonási lépés. A lemezen lévő fájl a mentésig érintetlen marad.",
        "tắt": "ki",
        "không thấy cột": "az oszlop nem található",
        "sẵn sàng": "kész",
        "nó vẫn chiếm một lõi CPU cho tới khi thoát ứng dụng.": "az alkalmazás kilépéséig lefoglalva tart egy processzormagot.",
        "Script không trả về gì": "A szkript nem adott vissza semmit",
        "Không dựng được máy JavaScript": "A JavaScript-motort nem sikerült létrehozni",
        "Lỗi JavaScript không rõ": "Ismeretlen JavaScript-hiba",
        "Bảng": "Táblázat",
        "Áp sắp xếp vào file": "A rendezés alkalmazása a fájlra",
        "Chuyển đổi ▾": "Átalakítás ▾",
        "Xuất dòng khớp": "Az illeszkedő sorok exportálása",
        "Ẩn cột này": "Ennek az oszlopnak az elrejtése",
        "Đổi tên tiêu đề…": "A fejléc átnevezése…",
        "Chèn cột trống bên trái": "Üres oszlop beszúrása balra",
        "Chèn cột trống bên phải": "Üres oszlop beszúrása jobbra",
        "Xóa cột này khỏi file…": "Ennek az oszlopnak a törlése a fájlból…",
        "Phải còn ít nhất một cột đang hiện": "Legalább egy oszlopnak láthatónak kell maradnia",
        "Đang sắp xếp…": "Rendezés…",
        "Trở về thứ tự trong file": "Vissza a fájl sorrendjéhez",
        "trăm hàng đầu": "az első száz sor",
        "chọn cột": "oszlopok választása",
        "đặt tên cột kết quả": "az eredményoszlop elnevezése",
        "lọc theo chữ": "szűrés szöveg szerint",
        "ô rỗng": "üres cellák",
        "ghép điều kiện": "feltételek összekapcsolása",
        "đếm hàng": "sorok számlálása",
        "gộp nhóm": "csoportosítás és összesítés",
        "nhỏ nhất, lớn nhất": "legkisebb, legnagyobb",
        "sắp xếp và cắt": "rendezés és korlátozás",
        "tên cột có dấu cách": "szóközt tartalmazó oszlopnév",
        "Truy vấn bị dừng giữa chừng": "A lekérdezés félbeszakadt",
        "Chưa làm: JOIN · truy vấn con · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · cửa sổ hàm": "Nem támogatott: JOIN · alkérdés · HAVING · DISTINCT · LIKE · IN · BETWEEN · UNION · ablakfüggvények",
        "XML: định dạng lại": "XML: formázás",
        "XML: thu gọn một dòng": "XML: tömörítés",
        "XML: kiểm cú pháp": "XML: szintaxis ellenőrzése",
        "YAML: kiểm khóa trùng và thụt lề": "YAML: kulcsok és behúzás ellenőrzése",
        "View": "Nézet",
        "Ẩn/hiện sidebar (Function List)": "Az oldalsáv be- és kikapcsolása (függvénylista)",
        "Ẩn/hiện bản đồ tài liệu": "A dokumentumtérkép be- és kikapcsolása",
        "Gấp / mở khối tại con nháy": "Összecsukás / kibontás a kurzornál",
        "Gấp tất cả": "Az összes összecsukása",
        "Bỏ gấp tất cả": "Az összes kibontása",
        "Gấp theo cấp": "Összecsukás szintig",
        "Cấp %d": "%d. szint",
        "Đã gấp %d khối ở cấp %d": "%2$d. szinten %1$d blokk összecsukva",
        "Tài liệu này chỉ sâu %d cấp": "Ez a dokumentum csak %d szint mély",
        "mermaid: không đọc được bản kê": "mermaid: a jegyzék nem olvasható",
        "Kiểm tra bản cập nhật…": "Frissítés keresése…",
        "Kiểm tra bản cập nhật": "Frissítés keresése",
        "Bản App Store cập nhật qua Mac App Store, không qua GEditor.": "Az App Store-os változat a Mac App Store-on keresztül frissül, nem a GEditoron át.",
        "Bản dựng này chưa có khoá ký cập nhật nên không kiểm tra được.": "Ebben a változatban nincs frissítést aláíró kulcs, ezért nem tud frissítést keresni.",
        "Phóng to chữ": "Nagyítás",
        "Thu nhỏ chữ": "Kicsinyítés",
        "Cỡ chữ gốc": "Eredeti méret",
        "Chia đôi theo chiều dọc": "Függőleges osztás",
        "Chia đôi theo chiều ngang": "Vízszintes osztás",
        "Bỏ chia đôi": "Az osztás megszüntetése",
        "Mở tab này ở nửa kia": "A lap megnyitása a másik panelen",
        "Nhảy sang nửa kia": "Ugrás a másik panelre",
        "Ngắt dòng (tắt / cửa sổ / cột)": "Sortörés (ki / ablakhoz / oszlophoz)",
        "Ngắt dòng tại cột…": "Törés ennél az oszlopnál…",
        "Đánh dấu dòng này": "Könyvjelző ki / be",
        "Dấu kế tiếp": "Következő könyvjelző",
        "Dấu trước đó": "Előző könyvjelző",
        "Màu đánh dấu…": "A könyvjelző színe…",
        "Hiện tất cả ký tự ẩn": "Az összes láthatatlan karakter",
        "  Khoảng trắng": "  Szóközök",
        "  Tab": "  Tabulátorok",
        "  Xuống dòng": "  Sorvégek",
        "  NBSP · zero-width · điều khiển": "  NBSP · nulla szélességű · vezérlő",
        "Xem nhị phân": "Bináris nézet",
        "Chế độ CSV (tô màu theo cột)": "CSV-mód (szivárványszínű oszlopok)",
        "Macro": "Makró",
        "Bắt đầu / dừng ghi": "A felvétel indítása / leállítása",
        "Phát lại": "Lejátszás",
        "Phát nhiều lần…": "Lejátszás többször…",
        "Phát đến cuối tài liệu": "Lejátszás a dokumentum végéig",
        "Chạy trên mọi tab": "Futtatás az összes lapon",
        "Hủy macro đang chạy": "A futó makró megszakítása",
        "Lưu macro…": "A makró mentése…",
        "Macro đã lưu…": "Mentett makrók…",
        "Help": "Súgó",
        "Trợ giúp GEditor": "GEditor súgó",
        "Giới thiệu tính năng": "Funkciók bemutatása",
        "Di cư từ Notepad++": "Átállás a Notepad++-ról",
        "Tìm": "Keresés",
        "Thay bằng": "Csere erre",
        "Kế": "Következő",
        "Trước": "Előző",
        "Đếm": "Számlálás",
        "Đóng": "Bezárás",
        "Kiểm theo JSON Schema…": "Ellenőrzés JSON-séma szerint…",
        "Chọn tệp JSON Schema": "Válasszon JSON-séma fájlt",
        "Không thấy lỗi nào theo schema này.": "Ehhez a sémához mérve nincs hiba.",
        "JSON Schema": "JSON-séma",
        "Kiểm cú pháp đồ thị": "A gráf szintaxisának ellenőrzése",
        "Chưa nhận ra định dạng đồ thị — cần đuôi .dot, .gv, .cypher, .ttl hoặc .graphml.": "Ismeretlen gráfformátum — .dot, .gv, .cypher, .ttl vagy .graphml kiterjesztés kell hozzá.",
        "Không thấy lỗi cú pháp %@ nào (phép kiểm không đầy đủ).": "Nem találtam %@ szintaktikai hibát (az ellenőrzés nem teljes körű).",
        "Cú pháp %@": "%@ szintaxis",
        "không phải một đối tượng JSON": "nem JSON-objektum",
        "Khai phá văn bản (n-gram, TF-IDF)": "Szövegbányászat (n-gramok, TF-IDF)",
        "Tài liệu rỗng.": "A dokumentum üres.",
        "Không rút được từ khoá nào.": "Nem sikerült kulcsszavakat kinyerni.",
        "Từ khoá": "Kulcsszavak",
        "%d từ khoá · %d token · %d tài liệu": "%d kulcsszó · %d token · %d dokumentum",
        "Tô lên tài liệu": "Megjelölés a dokumentumban",
        "Đánh dấu entity từ danh sách…": "Entitások megjelölése lista alapján…",
        "Chọn danh sách entity (CSV hoặc JSON)": "Válasszon entitáslistát (CSV vagy JSON)",
        "Không đọc được danh sách entity.": "Az entitáslistát nem sikerült elolvasni.",
        "Danh sách entity rỗng.": "Az entitáslista üres.",
        "Không thấy entity nào trong tài liệu (%d mục đã nạp).": "A dokumentumban egy entitás sem található (%d betöltve).",
        "%d lần xuất hiện · %@": "%d előfordulás · %@",
        "Chuyển đổi tri thức…": "Tudás átalakítása…",
        "Chuyển đổi: %@ → %@": "Átalakítás: %@ → %@",
        "Không chuyển đổi được.": "Az átalakítás nem sikerült.",
        "Xem trước cắt chunk…": "A szemcsézés előnézete…",
        "Cỡ cố định 800B, chồng 100B": "Rögzített 800 B, 100 B átfedéssel",
        "Theo câu (≤ 800B)": "Mondatonként (≤ 800 B)",
        "Theo heading Markdown": "Markdown-címsorok szerint",
        "Tài liệu rỗng — không có chunk nào.": "Üres dokumentum — nincsenek szemcsék.",
        "%d chunk · trung bình %d B · %@": "%d szemcse · átlagosan %d B · %@",
        "Xuất JSONL": "JSONL exportálása",
        "Chunk JSONL": "Szemcse-JSONL",
        "Mở triple/edge dạng bảng": "A hármasok/élek megnyitása táblázatként",
        "Bảng triple": "Hármasok táblázata",
        "Tài liệu này không có dòng triple nào.": "Ebben a dokumentumban nincs hármas sor.",
        "Không đọc được triple nào — dòng %d: %@": "Nem sikerült hármasokat olvasni — %d. sor: %@",
        "Đã đọc %d triple · %d dòng hỏng bị bỏ qua (dòng đầu: %d)": "%d hármas beolvasva · %d hibás sor kihagyva (első: %d. sor)",
        "Trùng lặp mờ theo cột…": "Közel azonos ismétlődések oszlop szerint…",
        "Trùng lặp mờ — cột «%@»: %d cụm ứng viên": "Közel azonos ismétlődések — „%@” oszlop: %d jelölt csoport",
        "Gộp": "Összevonás",
        "Giống": "Egyezés",
        "Các giá trị trong cụm": "A csoport értékei",
        "Gộp về": "Összevonás ebbe",
        "Gộp các cụm đã chọn": "A kijelölt csoportok összevonása",
        "Chưa chọn cụm nào — bấm Gộp thì KHÔNG có gì thay đổi. Máy không tự gộp bao giờ.": "Nincs kijelölt csoport — az Összevonás semmit sem változtat. Az alkalmazás magától soha nem von össze.",
        "Đã chọn %d cụm · %d hàng sẽ đổi giá trị · MỘT bước hoàn tác": "%d csoport kijelölve · %d sor változik · EGY visszavonási lépés",
        "Không quét được cột này.": "Ezt az oszlopot nem sikerült átvizsgálni.",
        "Cột «%@» không có cụm trùng lặp mờ nào.": "A(z) „%@” oszlopban nincs közel azonos ismétlődő csoport.",
        "Không cụm nào được gộp — tài liệu giữ nguyên.": "Egy csoportot sem vontunk össze — a dokumentum változatlan.",
        "Khử trùng lặp mờ · cột %@": "Közel azonos ismétlődések · %@ oszlop",
        "Đã gộp %d cụm · %d ô đổi giá trị": "%d csoport összevonva · %d cella változott",
        "Báo cáo làm sạch": "Tisztítási jelentés",
        "# Báo cáo làm sạch — %@\n\n": "# Tisztítási jelentés — %@\n\n",
        "## Đã áp dụng (%d)\n\n": "## Alkalmazva (%d)\n\n",
        "_Chưa áp dụng bước nào._\n": "_Még egy lépést sem alkalmaztunk._\n",
        "\n## Hồ sơ dữ liệu\n\n": "\n## Adatprofil\n\n",
        "_%d cột · %d hàng · quét %.1f s_\n\n": "_%d oszlop · %d sor · átvizsgálva %.1f s alatt_\n\n",
        "| Cột | Kiểu | Null | Distinct | Nhỏ nhất | Lớn nhất | Trung bình |\n": "| Oszlop | Típus | Üres | Egyedi | Legkisebb | Legnagyobb | Átlag |\n",
        "\n### Giá trị bất thường\n\n": "\n### Kiugró értékek\n\n",
        "hàng %d: %@": "%d. sor: %@",
        "- cột «%@» — %d ô: %@\n": "- „%@” oszlop — %d cella: %@\n",
        "\n## Còn lại (%d)\n\n": "\n## Hátralévő (%d)\n\n",
        "_Không còn phát hiện nào._\n": "_Nem maradt észrevétel._\n",
        "- cột «%@»: %@\n": "- „%@” oszlop: %@\n",
        "Cắt khoảng trắng khi lưu": "A szóközök levágása mentéskor",
        "Chuẩn hóa xuống dòng": "A sorvégek egységesítése",
        "trước đó": "előző",
        "Không mở lại được thư mục «%@» của phiên trước": "A(z) „%@” mappát nem sikerült újranyitni az előző munkamenetből",
        " (và %d file khác)": " (és még %d fájl)",
        "Không mở lại được %d tab: %@%@ — file không còn ở chỗ cũ.": "%d lapot nem sikerült újranyitni: %@%@ — a fájlok már nincsenek ott, ahol voltak.",
        "Không đọc được nội dung từ ống dẫn": "A csővezetékről nem sikerült bemenetet olvasni",
        "Sẽ cắt khoảng trắng cuối dòng mỗi lần lưu": "Minden mentéskor levágjuk a sorvégi szóközöket",
        "Không cắt khoảng trắng khi lưu nữa": "Mentéskor többé nem vágjuk le a szóközöket",
        "Chưa đặt tên.txt": "Névtelen.txt",
        "Chuyển đổi bảng mã sẽ làm mất ký tự": "A kódolás átalakítása karaktereket veszít el",
        "Vẫn lưu": "Mentés mindenképp",
        "Tài liệu có thay đổi chưa lưu": "A dokumentumban mentetlen módosítások vannak",
        "Đóng mà không lưu thì phần chưa lưu sẽ mất.": "Ha mentés nélkül zárja be, elvesznek.",
        "Bỏ thay đổi": "A módosítások eldobása",
        "Đi tới dòng": "Ugrás a sorra",
        "Tài liệu có %d dòng.": "A dokumentumnak %d sora van.",
        "Số dòng": "Sorszám",
        "Đi tới": "Ugrás",
        "Diễn giải lại theo…": "Újraértelmezés mint…",
        "Chuyển đổi sang…": "Átalakítás erre…",
        "Không diễn giải lại được": "Az újraértelmezés nem sikerült",
        "Bảng mã %@ không chứa hết ký tự": "A(z) %@ nem tud minden karaktert megjeleníteni",
        "Vẫn chọn": "Mégis ezt választom",
        "Cột %d": "%d. oszlop",
        "Cột %d: %@": "%1$d. oszlop: %2$@",
        "Cột ẩn: %@ (%d) — hiện lại từ menu ngữ cảnh trên hàng tiêu đề": "Rejtett oszlopok: %@ (%d) — a fejléc helyi menüjéből állíthatók vissza",
        "Hiện lại: %@": "Újra megjelenítve: %@",
        "Đã ẩn cột %@ — cột vẫn còn nguyên trong file": "A(z) %@ oszlop elrejtve — az oszlop a fájlban változatlanul megvan",
        "Sắp xếp theo %@ %@ · chỉ hiển thị": "Rendezve: %@ %@ · csak a megjelenítésben",
        "Sắp xếp: %@ %@ (chỉ hiển thị)": "Rendezve: %@ %@ (csak a megjelenítésben)",
        "%d+ dòng khớp — đang tìm tiếp…": "%d+ sor illeszkedik — a keresés még tart…",
        "%d / %d dòng khớp": "%1$d / %2$d sor illeszkedik",
        "Không tìm thấy lỗi trong %d hàng": "%d sorban nem találtam hibát",
        "%d hàng lệch số cột": "%d sorban rossz az oszlopok száma",
        "%d ô sai kiểu dữ liệu": "%d cellában rossz az adattípus",
        " (đã dừng ở %d lỗi đầu)": " (megálltunk az első %d hibánál)",
        "   —   kiểu nhận ra: ": "   —   felismert típusok: ",
        "Hàng %d, cột %@: «%@» không phải %@": "%1$d. sor, %2$@ oszlop: a(z) „%3$@” nem %4$@",
        "Column Editor — %d dòng": "Oszlopszerkesztő — %d sor",
        "Phát hiện": "Észrevételek",
        "Hồ sơ dữ liệu": "Adatprofil",
        "Hồ sơ dữ liệu — đang quét…": "Adatprofil — vizsgálat folyamatban…",
        "Lưu công thức…": "A recept mentése…",
        "Xuất báo cáo": "A jelentés exportálása",
        "Chưa áp dụng nhóm nào · mỗi nhóm là một bước undo": "Még egy csoportot sem alkalmaztunk · minden csoport egy visszavonási lépés",
        "quá nhiều giá trị": "túl sok érték",
        "hay gặp: ": "leggyakoribb: ",
        "Giá trị điền vào ô thiếu": "Az üres helyek kitöltő értéke",
        "Áp dụng": "Alkalmaz",
        "Không dựng được bản xem trước": "Nem sikerült előnézetet készíteni",
        "· giữ nguyên, không đọc được ·": "· értelmezhetetlen, változatlanul hagyva ·",
        "Đưa cột về ISO 8601 (YYYY-MM-DD)": "Az oszlop átalakítása ISO 8601-re (ÉÉÉÉ-HH-NN)",
        "Quy ước số cho cả cột": "Számformátum az egész oszlopra",
        "Làm gì với ô thiếu": "Mi legyen az üres cellákkal",
        "Chuẩn hóa về ISO 8601": "Egységesítés ISO 8601-re",
        "Ô mơ hồ đọc là NGÀY trước (31/12)": "A kétértelmű cellákban a NAP álljon elöl (31/12)",
        "Ô mơ hồ đọc là THÁNG trước (12/31)": "A kétértelmű cellákban a HÓNAP álljon elöl (12/31)",
        "Bỏ qua ô mơ hồ, chỉ sửa ô chắc chắn": "A kétértelmű cellák kihagyása, csak a biztosak javítása",
        "Về Việt/Âu (1.234,56)": "Vietnami/európai alakra (1.234,56)",
        "Về Anh-Mỹ (1,234.56)": "Angolszász alakra (1,234.56)",
        "Về Anh-Mỹ, bỏ dấu nhóm (1234.56)": "Angolszász alakra, csoportosítás nélkül (1234.56)",
        "Điền một giá trị mặc định…": "Kitöltés alapértelmezett értékkel…",
        "Điền xuôi — lấy giá trị phía trên": "Kitöltés lefelé — a fenti érték átvétele",
        "Điền ngược — lấy giá trị phía dưới": "Kitöltés felfelé — a lenti érték átvétele",
        "Xóa hàng có ô thiếu ở cột này": "Azoknak a soroknak a törlése, ahol ez az oszlop üres",
        "Cắt khoảng trắng hai đầu": "A szóközök levágása mindkét végén",
        "Cắt hai đầu và nén khoảng trắng bên trong": "Levágás mindkét végén és a belső szóközök összevonása",
        "Pivot…": "Kimutatás…",
        "Nguồn…": "Adatforrások…",
        "Pivot — gộp theo cột": "Kimutatás — csoportosítás oszlop szerint",
        "Hàng (gộp nhóm)": "Sorok (csoportosítás)",
        "Giá trị": "Értékek",
        "+ Hàng": "+ Sor",
        "+ Giá trị": "+ Érték",
        "Xoá hết": "Az összes törlése",
        "Đưa vào ô truy vấn": "Beírás a lekérdezés mezőbe",
        "Chọn cột để dựng câu truy vấn.": "Válasszon oszlopokat a lekérdezés összeállításához.",
        "Không đọc được tên cột của bảng này.": "Ennek a táblázatnak az oszlopneveit nem sikerült elolvasni.",
        "Nguồn dữ liệu của truy vấn": "A lekérdezés adatforrásai",
        "«%@» — tài liệu đang mở": "„%@” — a megnyitott dokumentum",
        "  ⚠️ file đã đổi kể từ khi đăng ký": "  ⚠️ a fájl a bejegyzés óta megváltozott",
        "Thêm file…": "Fájl hozzáadása…",
        "Bỏ hết": "Az összes eltávolítása",
        "Không suy được tên bảng từ «%@» — hãy đổi tên file.": "A(z) „%@” névből nem sikerült táblanevet képezni — nevezze át a fájlt.",
        "Tổng": "Összeg",
        "Trung bình": "Átlag",
        "Nhỏ nhất": "Legkisebb",
        "Lớn nhất": "Legnagyobb",
        "Đếm khác nhau": "Egyedi értékek száma",
        "Biểu đồ": "Diagram",
        "Xuất PNG": "PNG exportálása",
        "Xuất SVG": "SVG exportálása",
        "Bảng này không có cột số nào để vẽ.": "Ebben a táblázatban nincs számoszlop a diagramhoz.",
        "Không dựng được ảnh PNG.": "A PNG-képet nem sikerült elkészíteni.",
        "Kết quả truy vấn": "A lekérdezés eredménye",
        "Đã lưu %@": "Mentve: %@",
        "Biểu đồ %@ của «%@» — %d điểm, giá trị từ %@ đến %@": "„%2$@” %1$@ diagramja — %3$d pont, az értékek %4$@ és %5$@ között",
        "Cột": "Oszlop",
        "Đường": "Vonal",
        "Phân bố": "Hisztogram",
        "Phân tán": "Pont",
        "Hộp": "Doboz",
        "CSV: chất lượng dữ liệu…": "CSV: adatminőség…",
        "Chất lượng dữ liệu": "Adatminőség",
        "Xuất vi phạm ra tab mới": "A szabálysértések exportálása új lapra",
        "Mức": "Szint",
        "Luật": "Szabály",
        "Vi phạm": "Szabálysértések",
        "Tỷ lệ": "Arány",
        "đạt": "megfelelt",
        "lỗi": "hiba",
        "cảnh báo": "figyelmeztetés",
        "hỏng": "hibás",
        "Đã đánh dấu %d dòng vi phạm": "%d szabálysértő sor megjelölve",
        "Xu hướng": "Alakulás",
        "Lúc chấm": "Pontozva",
        "Số hàng": "Sorok",
        "Lệch": "Változás",
        "Luật trượt": "Bukott szabályok",
        "Điểm chất lượng": "Minőségi pontszám",
        "Điểm theo thời gian": "A pontszám az idő során",
        "Chưa có mốc nào trong lịch sử — mỗi lần chấm sẽ ghi thêm ": "Még nincs előzmény — minden pontozás hozzáfűz ",
        "một dòng vào tệp «.history.jsonl» cạnh bộ luật.": "egy sort a szabályok mellett lévő „.history.jsonl” fájlhoz.",
        "%d mốc trong lịch sử": "%d pont az előzményben",
        " · %d dòng KHÔNG đọc được": " · %d olvashatatlan sor",
        " · chọn hai dòng để so": " · jelöljön ki két sort az összehasonlításhoz",
        "điểm %+.1f": "pontszám %+.1f",
        "không chiều nào tụt": "egy dimenzió sem esett vissza",
        "tụt: ": "visszaesett: ",
        "%d luật mới trượt: %@": "%d újonnan bukott szabály: %@",
        "số hàng %+d": "sorok %+d",
        " (và %d cảnh báo nữa ở tab Xu hướng)": " (és még %d figyelmeztetés az Alakulás lapon)",
        "Không sửa tự động được: ": "Nincs automatikus javítás: ",
        "Mở đúng công cụ trong Bàn làm sạch, xong thì chấm lại ngay.": "Megnyitja a hozzá tartozó tisztítóeszközt, majd rögtön újra pontoz.",
        "Xử lý giá trị thiếu…": "A hiányzó értékek kezelése…",
        "Chuẩn hóa ngày…": "A dátumok egységesítése…",
        "Khử trùng lặp…": "Az ismétlődések eltávolítása…",
        "Thay thế…": "Csere…",
        "Xem các dòng sai": "A hibás sorok megmutatása",
        "Không tìm thấy cột «%@» trong bảng này.": "A(z) „%@” oszlop nincs ebben a táblázatban.",
        "Đã khử trùng lặp — «%@» nay không còn trùng. Điểm: %.0f/100": "Az ismétlődések eltávolítva — a(z) „%@” mostantól egyedi. Pontszám: %.0f/100",
        "Khử trùng lặp xong nhưng «%@» vẫn còn %d hàng trùng (trước: %d) — ": "Az ismétlődések eltávolítva, de a(z) „%1$@” oszlopban még mindig %2$d ismétlődő sor van (volt %3$d) — ",
        "những hàng ấy trùng KHOÁ chứ không trùng cả dòng, nên phải xem và chọn ": "azok a sorok a KULCSBAN egyeznek, de nem az egész sorban, ezért végig kell nézni és eldönteni, ",
        "giữ hàng nào.": "melyiket tartja meg.",
        "Không đọc được giá trị nào đang vi phạm luật này.": "Nem sikerült egyetlen ezt a szabályt sértő értéket sem beolvasni.",
        "%d giá trị sai ở cột «%@» — sửa ô Thay rồi bấm Xem trước": "%2$@ oszlopban %1$d hibás érték — töltse ki a Csere mezőt, majd kérjen előnézetet",
        "Đã chấm lại: %.0f/100": "Újrapontozva: %.0f/100",
        "Xem trước báo cáo": "A jelentés előnézete",
        "Tham số…": "Paraméterek…",
        "Xuất HTML…": "HTML exportálása…",
        "In / PDF…": "Nyomtatás / PDF…",
        "%d khối chạy được · %d khối HỎNG": "%1$d blokk lefutott · %2$d blokk MEGBUKOTT",
        "%d khối chạy được": "%d blokk lefutott",
        " · DỮ LIỆU CŨ — file nguồn đã đổi, bấm dựng lại": " · ELAVULT ADAT — a forrásfájl megváltozott; építse újra",
        "Xem trước báo cáo cần tài liệu đuôi .%@": "A jelentés előnézetéhez .%@ dokumentum kell",
        "Chưa tìm được dữ liệu — khai «source: tên-file.csv» ở frontmatter.": "Nem találtam adatforrást — adja meg a „source: file.csv” sort a fejlécben.",
        "Không dựng được báo cáo.": "A jelentést nem sikerült felépíteni.",
        "Báo cáo này chưa khai tham số nào ở frontmatter.": "Ez a jelentés nem ad meg paramétereket a fejlécében.",
        "Tham số báo cáo": "A jelentés paraméterei",
        "Dựng lại": "Újraépítés",
        "Đã xuất %@": "Exportálva: %@",
        "Báo cáo: xem trước": "Jelentés: előnézet",
        "Báo cáo: sinh loạt…": "Jelentés: kötegelt előállítás…",
        "không phải tài liệu .greport.md": "nem .greport.md dokumentum",
        "không phân tích được báo cáo": "a jelentést nem sikerült elemezni",
        "không tìm được dữ liệu nguồn": "a forrásadatokat nem sikerült megtalálni",
        "không đọc được danh sách tham số": "a paraméterlistát nem sikerült elolvasni",
        "Sinh loạt cần tài liệu đuôi .%@": "A kötegelt előállításhoz .%@ dokumentum kell",
        "Chọn danh sách tham số (CSV hoặc JSON)": "Válasszon paraméterlistát (CSV vagy JSON)",
        "Chọn thư mục để ghi %d báo cáo": "Válasszon mappát %d jelentésnek",
        "[%d/%d] %@": "[%1$d/%2$d] %3$@",
        "thiếu tham số ": "hiányzó paraméterek ",
        "trỏ vào chính tệp nguồn — từ chối ghi đè": "magára a forrásfájlra mutat — nem írjuk felül",
        "%d khối HỎNG": "%d blokk MEGBUKOTT",
        "Sinh loạt xong: %d tệp · %d hỏng": "A köteg kész: %1$d fájl · %2$d megbukott",
        "%d bộ tham số KHÔNG dựng được — xem bảng tổng kết": "%d paraméterkészletet nem sikerült összeállítani — lásd az összefoglalót",
        "Sơ đồ Mermaid: xem trước": "Mermaid diagram: előnézet",
        "Sơ đồ Mermaid: chèn mẫu…": "Mermaid diagram: sablon beszúrása…",
        "Sơ đồ Mermaid: định dạng lại": "Mermaid diagram: újraformázás",
        "Nền trong suốt": "Átlátszó háttér",
        "Máy này không dựng được ảnh PNG từ sơ đồ — cần macOS 13. Xuất SVG vẫn dùng được.": "Ez a Mac nem tudja PNG-vé alakítani a diagramot — macOS 13 kell hozzá. Az SVG-exportálás továbbra is működik.",
        "Lưu PNG %@…": "%@ PNG mentése…",
        "Lưu SVG…": "SVG mentése…",
        "Chép ảnh vào clipboard": "A kép másolása a vágólapra",
        "Màu thương hiệu…": "Márkaszínek…",
        "Màu thương hiệu cho sơ đồ": "A diagramok márkaszínei",
        "Mỗi ô là một mã màu dạng #rrggbb. Lưu vào «themes/mermaid-brand.json» — chép sang máy khác được.": "Minden mező egy #rrggbb szín. A „themes/mermaid-brand.json” fájlba mentjük — átmásolható másik Macre.",
        "Màu chính": "Fő szín",
        "Chữ trên nút": "A csomópontok szövege",
        "Viền": "Keret",
        "Đường nối": "Kapcsolatok",
        "Nền khi xuất ảnh": "Háttér exportáláskor",
        "Lưu và chèn %%{init}%% vào tài liệu": "Mentés és a %%{init}%% beszúrása a dokumentumba",
        "Đã lưu màu thương hiệu": "A márkaszínek elmentve",
        "Đã chép ảnh sơ đồ vào clipboard": "A diagram képe a vágólapra másolva",
        "Đã lưu %@ — %@": "Mentve: %1$@ — %2$@",
        "Sơ đồ này đã có sẵn một chỉ thị %%{init}%% — giữ nguyên bản của anh.": "Ebben a diagramban már van %%{init}%% direktíva — az önét nem bántottuk.",
        "Đã chèn %%{init}%% — sơ đồ nay tự mang màu của nó": "%%{init}%% beszúrva — a diagram mostantól a saját színeit hordozza",
        "Chèn màu thương hiệu vào sơ đồ": "Márkaszínek beszúrása a diagramba",
        "Định dạng sơ đồ Mermaid": "A Mermaid diagram újraformázása",
        "Mã sơ đồ đã đúng khuôn — không có gì để sửa": "A diagram forrása már rendezett — nincs mit változtatni",
        "Đã định dạng lại sơ đồ": "A diagram újraformázva",
        "Đã định dạng lại %d sơ đồ": "%d diagram újraformázva",
        "Thư viện mẫu sơ đồ": "Diagramsablonok könyvtára",
        "Mẫu sơ đồ đầy đủ": "Teljes diagramsablonok",
        "Mẩu cú pháp": "Szintaxisrészletek",
        "Đang soạn: %@": "Szerkesztés alatt: %@",
        "Đã chèn mẫu «%@»": "„%@” sablon beszúrva",
        "Tài liệu đang ở chế độ chỉ đọc.": "Ez a dokumentum csak olvasható.",
        "Sơ đồ Mermaid": "Mermaid diagram",
        "Tài liệu chưa có khối mermaid nào.": "Ebben a dokumentumban nincs mermaid blokk.",
        "Thương hiệu": "Márka",
        "Xuất…": "Exportálás…",
        "Chưa có sơ đồ nào": "Még nincs diagram",
        "%d sơ đồ · %@": "%d diagram · %@",
        "%d/%d sơ đồ HỎNG — sơ đồ thứ %d%@": "%1$d/%2$d diagram MEGBUKOTT — %3$d. diagram%4$@",
        ", dòng %d": ", %d. sor",
        "Tài liệu này chưa có khối ```mermaid nào, và cũng không phải tệp .mmd.": "Ebben a dokumentumban nincs ```mermaid blokk, és nem is .mmd fájl.",
        "Chưa có sơ đồ nào vẽ xong để xuất.": "Még egy diagram sem készült el.",
        "Không tìm thấy «%@» trong mã sơ đồ": "A(z) „%@” nem található a diagram forrásában",
        "không dựng được hàng rào chặn mạng cho WKWebView": "nem sikerült felépíteni a WKWebView hálózati blokkolóját",
        "Luật kết hợp": "Asszociációs szabályok",
        "Mỗi dòng một giỏ": "Soronként egy kosár",
        "Hai cột: mã · item": "Két oszlop: azonosító · tétel",
        "Dạng dữ liệu giao dịch": "A tranzakciós adatok alakja",
        "Cột giỏ hàng hoặc mã giao dịch": "Kosároszlop vagy tranzakcióazonosító-oszlop",
        "Cột item": "Tételoszlop",
        "Ký tự phân tách item": "A tételek elválasztó karaktere",
        "Support tối thiểu, phần trăm": "Minimális támogatottság, százalék",
        "Confidence tối thiểu, phần trăm": "Minimális megbízhatóság, százalék",
        "Tách bởi:": "Vágás ez szerint:",
        "Support \u{2265}": "Támogatottság ≥",
        "% · Confidence \u{2265}": "% · Megbízhatóság ≥",
        "Bảng luật kết hợp": "Asszociációs szabályok táblázata",
        "Support": "Támogatottság",
        "Confidence": "Megbízhatóság",
        "Lift": "Emelés",
        "Leverage": "Áttétel",
        "Cảnh báo": "Vigyázat",
        "%d giao dịch · %d item · %d luật": "%d tranzakció · %d tétel · %d szabály",
        " — không luật nào đạt ngưỡng; hạ support hoặc confidence xuống": " — egyetlen szabály sem érte el a küszöböt; csökkentse a támogatottságot vagy a megbízhatóságot",
        " — ĐÃ DỪNG SỚM, bảng KHÔNG đầy đủ": " — IDŐ ELŐTT LEÁLLT, a táblázat NEM TELJES",
        "%d / %d giao dịch chứa cả hai vế": "%1$d / %2$d tranzakcióban mindkét oldal szerepel",
        "Dạng hai cột cần chọn hai cột KHÁC nhau.": "A kétoszlopos alakhoz két KÜLÖNBÖZŐ oszlop kell.",
        "Đã đánh dấu %d dòng của %d giao dịch chứa «%@»": "%2$d tranzakcióban %1$d sor megjelölve, amely „%3$@” elemet tartalmaz",
        "CSV: luật kết hợp…": "CSV: asszociációs szabályok…",
        "Khai phá theo nhóm": "Csoportos bányászat",
        "Cột nhóm": "Csoportosító oszlop",
        "Cột giá trị": "Értékoszlop",
        "Cột thứ hai cho tương quan": "Második oszlop a korrelációhoz",
        "Cách xếp hạng": "Rangsorolás",
        "Nhóm theo:": "Csoportosítás:",
        "Giá trị:": "Érték:",
        "Xếp theo:": "Rangsor eszerint:",
        "Bảng xếp hạng nhóm": "A csoportok rangsortáblája",
        "Nhóm": "Csoport",
        "Hàng": "Sorok",
        "Hàng rào riêng": "Saját küszöb",
        "MAPE": "MAPE",
        "r": "r",
        "Lệch r": "r-eltérés",
        "Ghi chú": "Megjegyzés",
        "không đo được": "nem mérhető",
        "%d nhóm · mốc tương quan toàn bộ %@": "%d csoport · összevont korreláció %@",
        " · ĐÃ CẮT %d nhóm": " · %d CSOPORT KIESETT",
        "Bảng này không có cột chữ nào để gom nhóm.": "Ebben a táblázatban nincs szöveges oszlop a csoportosításhoz.",
        "Bảng này không có cột số nào để khai phá.": "Ebben a táblázatban nincs számoszlop a bányászathoz.",
        "Đã đánh dấu %d dòng của nhóm «%@»": "A(z) „%2$@” csoport %1$d sora megjelölve",
        "CSV: khai phá theo nhóm…": "CSV: csoportos bányászat…",
        "\u{2194}": "↔",
        "Dự báo": "Előrejelzés",
        "Cột giá trị theo thời gian": "Értékoszlop az idő mentén",
        "Mô hình dự báo": "Előrejelző modell",
        "Số kỳ dự báo": "Az előrejelzendő időszakok száma",
        "Kết luận so với baseline": "Ítélet az alapmodellekhez mérve",
        "Mô hình:": "Modell:",
        "Số kỳ:": "Időszakok:",
        "Chu kỳ:": "Szezon:",
        "tự": "automatikus",
        "Chu kỳ mùa vụ, để trống thì tự phát hiện": "Szezonhossz; hagyja üresen az automatikus felismeréshez",
        "Bảng giá trị dự báo": "Az előrejelzett értékek táblázata",
        "Kỳ": "Időszak",
        "Dải 80%": "80 százalékos sáv",
        "Dải 95%": "95 százalékos sáv",
        "MAE %@ · MAPE %@": "MAE %@ · MAPE %@",
        "không tính được": "nem számítható",
        "Bảng này không có cột số nào để dự báo.": "Ebben a táblázatban nincs számoszlop az előrejelzéshez.",
        "Không dựng được dự báo cho cột này.": "Ehhez az oszlophoz nem sikerült előrejelzést készíteni.",
        "Cột «%@» chỉ có %d giá trị số — cần ít nhất 4 để dự báo.": "A(z) „%1$@” oszlopban csak %2$d szám van — az előrejelzéshez legalább 4 kell.",
        "# Chuỗi đọc theo ĐÚNG thứ tự hàng trong file — không sắp lại, không suy ra cột thời gian.\n": "# A sorozatot a fájl sorrendjében olvassuk — nincs újrarendezés, és nem következtetünk időoszlopra.\n",
        "Sai số huấn luyện": "Tanulási hiba",
        "CSV: dự báo chuỗi thời gian…": "CSV: idősor előrejelzése…",
        "Holt-Winters cộng": "Holt-Winters additív",
        "Holt-Winters nhân": "Holt-Winters multiplikatív",
        "seasonal-naive": "szezonális naiv",
        "naive": "naiv",
        "Cột đưa vào phân cụm": "A klaszterezésbe bevont oszlopok",
        "Đường cong WCSS": "WCSS-görbe",
        "Phân cụm": "Klaszter",
        "Chuẩn hoá:": "Skálázás:",
        "k:": "k:",
        "eps:": "eps:",
        "minPts:": "minPts:",
        "Chọn ít nhất một cột.": "Válasszon legalább egy oszlopot.",
        "Không đủ dữ liệu để dựng đường cong.": "Nincs elég adat a görbe felépítéséhez.",
        "Elbow gợi ý k = %d. WCSS LUÔN giảm khi k tăng, nên đây là mẹo đọc đồ thị chứ không phải tiêu chí thống kê — nhìn đường cong xem chỗ gãy có rõ không.": "A könyök k = %d értéket sugall. A WCSS a k növekedésével MINDIG csökken, tehát ez a görbe olvasásának ökölszabálya, nem statisztikai kritérium — nézze meg a görbét, és döntse el, elég éles-e a törés.",
        "WCSS theo k": "WCSS a k függvényében",
        "k-distance gợi ý eps = %@ (minPts mặc định 2 × số cột = %d). %@": "A k-távolság eps = %1$@ értéket sugall (a minPts alapból 2 × oszlopszám = %2$d). %3$@",
        "Khoảng cách tới hàng xóm thứ k": "Távolság a k-adik szomszédig",
        "Cần ít nhất 2 cột số để phân cụm.": "A klaszterezéshez legalább 2 számoszlop kell.",
        "Cụm theo %@ và %@": "Klaszterek %@ és %@ szerint",
        " — cụm tìm trên %d chiều, hình chỉ vẽ 2 chiều đầu": " — a klasztereket %d dimenzióban találtuk; az ábra csak az első 2-t mutatja",
        "# nhiễu (cluster_id = -1): %d dòng\n": "# zaj (cluster_id = -1): %d sor\n",
        "CSV: phân cụm…": "CSV: klaszterezés…",
        "# --- Tâm cụm (thang gốc) ---\n": "# --- A klaszterek középpontjai (eredeti mértékegységben) ---\n",
        "k-means": "k-közép",
        "DBSCAN": "DBSCAN",
        "Ma trận tương quan": "Korrelációs mátrix",
        "Phương pháp tương quan": "Korrelációs módszer",
        "Tương quan không hàm ý nhân quả.": "A korreláció nem jelent okságot.",
        "Cặp mạnh nhất: %@ ↔ %@ = %@ (n = %d). Bấm một ô để xem biểu đồ phân tán.": "A legerősebb pár: %1$@ ↔ %2$@ = %3$@ (n = %4$d). Kattintson egy cellára a pontdiagramért.",
        "Không cặp nào đo được.": "Egyetlen párt sem sikerült megmérni.",
        "%@ ↔ %@: %@ trên %d hàng": "%1$@ ↔ %2$@: %3$@ · %4$d soron",
        "Cần ít nhất 2 cột số để tính tương quan.": "A korrelációhoz legalább 2 számoszlop kell.",
        "Không đọc được cột «%@».": "A(z) „%@” oszlopot nem sikerült elolvasni.",
        "CSV: ma trận tương quan…": "CSV: korrelációs mátrix…",
        "Bất thường": "Kiugró értékek",
        "Danh sách bất thường": "A kiugró értékek listája",
        "Cột:": "Oszlop:",
        "Cột số cần xét": "A vizsgálandó számoszlop",
        "Cách:": "Módszer:",
        "Phương pháp phát hiện": "Felismerési módszer",
        "Phương pháp đã dùng": "A használt módszer",
        "Ngưỡng": "Küszöb",
        "Đánh dấu": "Megjelölés",
        "Xuất tab mới": "Exportálás új lapra",
        "Dòng": "Sor",
        "Điểm": "Pontszám",
        "Vì sao": "Miért",
        "nhẹ": "enyhe",
        "vừa": "közepes",
        "nặng": "súlyos",
        "z-score": "z-érték",
        "IQR": "IQR",
        "MAD": "MAD",
        "%d / %d dòng (%.2f%%)": "%d / %d sor (%.2f%%)",
        "Bảng này không có cột số nào để tìm bất thường.": "Ebben a táblázatban nincs számoszlop a kiugró értékek kereséséhez.",
        "Đã đánh dấu %d dòng bất thường": "%d kiugró sor megjelölve",
        "CSV: tìm bất thường…": "CSV: kiugró értékek keresése…",
        "%d luật, tất cả ĐẠT · %d hàng · %.0f ms": "%1$d szabály, mind MEGFELELT · %2$d sor · %3$.0f ms",
        "%d lỗi · %d cảnh báo trên %d luật · %d hàng · %.0f ms": "%1$d hiba · %2$d figyelmeztetés %3$d szabályban · %4$d sor · %5$.0f ms",
        "Lưu tài liệu trước — bộ quy tắc chất lượng nằm cạnh file dữ liệu.": "Mentse el előbb a dokumentumot — a minőségi szabályok az adatfájl mellett laknak.",
        "Chưa có bộ quy tắc. Tạo tệp %@ rồi mở lại.": "Még nincs szabálykészlet. Hozza létre a(z) %@ fájlt, majd nyissa meg újra.",
        "Lịch sử": "Előzmények",
        "Câu đã lưu": "Mentett lekérdezések",
        "Lưu câu này…": "Ennek a lekérdezésnek a mentése…",
        "Lưu câu truy vấn": "A lekérdezés mentése",
        "Đặt tên để tìm lại sau. Trùng tên sẽ ghi đè.": "Adjon neki nevet, hogy később megtalálja. Az azonos név felülír.",
        "Ví dụ: Doanh thu theo tỉnh": "Például: Bevétel megyénként",
        "Chưa nhập giá trị cho tham số: %@": "Nem adott meg értéket ehhez a paraméterhez: %@",
        "Plugin đã đổi nội dung — GEditor từ chối chạy": "A bővítmény megváltozott, amióta jóváhagyta — a GEditor nem futtatja",
        "Chạy plugin chưa duyệt?": "Futtat egy jóvá nem hagyott bővítményt?",
        "Tôi tin file này — chạy": "Megbízom ebben a fájlban — futtatás",
        "KHÔNG có chữ ký": "NINCS aláírva",
        "Chữ ký: %@": "Aláírás: %@",
        "Đường dẫn: %@": "Útvonal: %@",
        "Thay": "Csere",
        "Thay tất cả": "Az összes cseréje",
        "Chuỗi thuần": "Sima szöveg",
        "Extended (\\n \\t \\xNN)": "Kiterjesztett (\\n \\t \\xNN)",
        "Biểu thức chính quy": "Reguláris kifejezés",
        "Phân biệt hoa thường": "Kis- és nagybetű számít",
        "Cả từ": "Egész szó",
        "Không có kết quả": "Nincs találat",
        "Thử biểu thức chính quy…": "Reguláris kifejezés kipróbálása…",
        "Chế độ Log (tô theo mức)": "Naplómód (színezés szint szerint)",
        "Lọc log theo mức…": "A napló szűrése szint szerint…",
        "Chạy trên cả thư mục…": "Futtatás az egész mappán…",
        "Lọc qua lệnh ngoài…": "Szűrés külső paranccsal…",
        "Script…": "Szkriptek…",
        "Gói mở rộng…": "Bővítménycsomagok…",
        "Cửa sổ mới": "Új ablak",
        "Tách tab ra cửa sổ mới": "A lap áthelyezése új ablakba",
        "Chưa mở thư mục nào": "Nincs megnyitott mappa",
        "Tìm file trong thư mục": "Fájl keresése a mappában",
        "Lọc theo tên": "Szűrés név szerint",
        "File mới…": "Új fájl…",
        "Thư mục mới…": "Új mappa…",
        "Đổi tên…": "Átnevezés…",
        "Chuyển vào Thùng rác": "Áthelyezés a Kukába",
        "Hiện trong Finder": "Megmutatás a Finderben",
        "Đang đọc cấu trúc tài liệu…": "A dokumentum szerkezetének beolvasása…",
        "file này không có hàm nào": "ebben a fájlban nincs függvény",
        "Không có gì khớp": "Nincs találat",
        "Văn bản thuần": "Sima szöveg",
        "🔒 Chỉ đọc": "🔒 Csak olvasható",
        "Đang theo dõi": "Követés",
        "ngắt tại cột": "törés ennél az oszlopnál",
        "Cú pháp": "Szintaxis",
        "Bấm để chèn vào ô truy vấn": "Kattintson a lekérdezés mezőbe illesztéshez",
        "truy vấn không hợp lệ": "érvénytelen lekérdezés",
        "khóa `ten` ở gốc": "a gyökér `ten` kulcsa",
        "khóa có dấu cách": "szóközt tartalmazó kulcs",
        "phần tử đầu": "első elem",
        "mọi phần tử": "minden elem",
        "lát cắt": "szelet",
        "hợp nhiều chỉ số": "indexek uniója",
        "mọi khóa `gia` ở mọi tầng": "minden `gia` kulcs bármilyen mélységben",
        "mọi nút": "minden csomópont",
        "lọc theo số": "szűrés szám szerint",
        "lọc theo có mặt": "szűrés meglét szerint",
        "Tới lỗi đầu tiên": "Ugrás az első hibához",
        "Cột doanh_thu là số": "A doanh_thu oszlop numerikus",
        "lọc…": "szűrés…",
        "Hủy": "Mégse",
        "Thực hiện thay": "Csere",
        "xem trước": "előnézet",
        "tương tác": "interaktív",
        "Soạn thảo": "Szerkesztés",
        "Giao diện": "Megjelenés",
        "Phím tắt": "Billentyűparancsok",
        "Cỡ chữ": "Betűméret",
        "Bề rộng TAB": "Tabulátorszélesség",
        "Thụt lề bằng TAB": "Behúzás tabulátorral",
        "Tự động thụt lề khi xuống dòng": "Automatikus behúzás új sorban",
        "Tô mọi kết quả tìm kiếm": "Az összes találat kiemelése",
        "Chuẩn hóa về NFC khi lưu": "NFC-re alakítás mentéskor",
        "Ngôn ngữ": "Nyelv",
        "Nền": "Háttér",
        "Theo hệ thống": "Mint a rendszer",
        "Sáng": "Világos",
        "Tối": "Sötét",
        "Theme": "Téma",
        "Dùng preset Notepad++": "A Notepad++ előbeállítása",
        "Về phím mặc định": "Vissza az alapértelmezett billentyűkhöz",
        "Mở file cấu hình": "A beállításfájl megnyitása",
        "Xuất theme hiện tại": "A jelenlegi téma exportálása",
        "Đổi ngôn ngữ áp dụng đầy đủ ở lần mở app kế tiếp.": "A nyelvváltás teljes egészében az alkalmazás következő indításakor lép életbe.",
        "Phím mặc định trở lại ở lần mở app kế tiếp.": "Az alapértelmezett billentyűk az alkalmazás következő indításakor térnek vissza.",
        "Xem trước Markdown": "Markdown-előnézet",
        "Xem trước dựng bằng bộ Markdown của hệ thống: chưa dựng bảng và chưa tô màu khối mã.": "A rendszer Markdown-motorjával jelenítjük meg: a táblázatok és a kódblokkok színezése még nem támogatott.",
        "Thử biểu thức chính quy": "Reguláris kifejezés kipróbálása",
        "Biểu thức": "Kifejezés",
        "Văn bản thử": "Mintaszöveg",
        "Kết quả": "Eredmények",
        "Kết quả khớp": "A találatok",
        "Biểu thức này làm gì": "Mit csinál ez a kifejezés",
        "Giải thích biểu thức": "A kifejezés magyarázata",
        "Chế độ tìm kiếm": "Keresési mód",
        "Kết quả tìm kiếm": "A keresés eredménye",
        "Không khớp chỗ nào": "Nincs találat",
        " (đã cắt bớt)": " (levágva)",
        "Bản đồ tài liệu": "Dokumentumtérkép",
        "Thanh tab": "Lapsáv",
        "Hàng tiêu đề cột": "Az oszlopok fejlécsora",
        "Không có cột nào": "Nincs oszlop",
        "Cây thư mục workspace": "A munkaterület fájlfája",
        "Danh sách hàm và lớp": "Függvények és osztályok listája",
        "Kết quả tìm trong thư mục": "A mappában keresés eredménye",
        "Bảng dữ liệu CSV": "CSV-adattáblázat",
        "Bàn làm sạch dữ liệu": "Adattisztító pult",
        "Truy vấn JSONPath": "JSONPath-lekérdezés",
        "Danh sách lỗi dữ liệu": "Adathibák listája",
        "Bộ đánh giá golden set…": "Aranykészlet…",
        "So với điểm ngoài (JSONL)…": "Összehasonlítás külső pontszámokkal (JSONL)…",
        "Chọn tệp điểm ngoài (JSONL: query, chunk_id, score)": "Válassza ki a külső pontszámfájlt (JSONL: query, chunk_id, score)",
        "Đổi tên node đang chọn": "A kijelölt csomópont átnevezése",
        "Gộp các node đang chọn": "A kijelölt csomópontok összevonása",
        "Tách node đang chọn": "A kijelölt csomópont szétvágása",
        "Trích subgraph đang chọn ra tab mới": "A kijelölt részgráf kiemelése új lapra",
        "Không có gì để đổi": "Nincs mit változtatni",
        "%@ — áp %d thay đổi?": "%1$@ — alkalmaz %2$d változtatást?",
        "%@: %d thay đổi · Cmd-Z hoàn tác cả cụm": "%1$@: %2$d változtatás · a Cmd-Z az egész köteget visszavonja",
        "Đặt con nháy lên ĐÚNG MỘT node rồi chạy lại": "Tegye a kurzort PONTOSAN EGY csomópontra, és futtassa újra",
        "Đổi tên «%@»": "A(z) „%@” átnevezése",
        "Mọi cạnh và nhãn tham chiếu node này sẽ đổi theo.": "Minden él és címke, amely erre a csomópontra hivatkozik, vele együtt változik.",
        "Đổi tên node": "A csomópont átnevezése",
        "Bôi đen từ HAI node trở lên rồi chạy lại": "Jelöljön ki KETTŐ VAGY TÖBB csomópontot, és futtassa újra",
        "Dạng chuẩn «%@» — hay gặp nhất, dài nhất, còn dấu": "Kanonikus alak: „%@” — a leggyakoribb, a leghosszabb, ékezetekkel",
        "Gộp node": "Csomópontok összevonása",
        "Bôi đen những DÒNG CẠNH muốn chuyển rồi chạy lại": "Jelölje ki az áthelyezendő ÉLSOROKAT, és futtassa újra",
        "Mọi dòng đã chọn phải cùng chạm ĐÚNG MỘT node — bôi đen thêm dòng cạnh": "Minden kijelölt sornak PONTOSAN EGY közös csomópontot kell érintenie — jelöljön ki több élsort",
        "Tách «%@» — chuyển %d cạnh": "A(z) „%1$@” szétvágása — %2$d él áthelyezése",
        "Cạnh tới: %@": "Élek ide: %@",
        "Tách node": "A csomópont szétvágása",
        "Tài liệu chưa lưu — tệp trích cần chỗ để nằm cạnh": "A dokumentum nincs mentve — a kiemelt fájlnak kell egy hely, ahová mellé kerülhet",
        "Bôi đen phần đồ thị muốn trích rồi chạy lại": "Jelölje ki a kiemelendő gráfrészt, és futtassa újra",
        "Gom biến thể entity → bảng duyệt": "Entitásváltozatok csoportosítása → ellenőrzőtáblázat",
        "Áp bảng duyệt đã sửa": "A szerkesztett ellenőrzőtáblázat alkalmazása",
        "Tài liệu chưa lưu — bảng duyệt cần nằm cạnh tệp đồ thị": "A dokumentum nincs mentve — az ellenőrzőtáblázatnak a gráffájl mellett kell lennie",
        "Không tìm thấy biến thể nào để gom": "Nem találtam csoportosítható változatot",
        "%d cụm biến thể — sửa cột «canonical» rồi chạy «Áp bảng duyệt»": "%d változatcsoport — szerkessze a „canonical” oszlopot, majd futtassa az „Alkalmazás” parancsot",
        "Chưa có bảng duyệt «%@» — chạy «Gom biến thể entity» trước": "Még nincs „%@” ellenőrzőtáblázat — előbb futtassa az „Entitásváltozatok csoportosítása” parancsot",
        "Bảng duyệt không đọc được: %@": "Az ellenőrzőtáblázatot nem sikerült elolvasni: %@",
        "Bảng duyệt không có dòng nào cần đổi": "Az ellenőrzőtáblázatban nincs megváltoztatandó sor",
        "Không có chỗ nào trên đồ thị khớp bảng duyệt": "A gráfban semmi sem felel meg az ellenőrzőtáblázatnak",
        "Gom biến thể entity": "Entitásváltozatok csoportosítása",
        "Đã áp %d thay đổi · bảng alias và danh sách marker ghi cạnh tệp": "%d változtatás alkalmazva · az álnévtáblázat és a jelöléslista a fájl mellé íródott",
        "Áp %d thay đổi lên đồ thị?": "Alkalmaz %d változtatást a gráfon?",
        "%d alias → dạng chuẩn.": "%d álnév → kanonikus alak.",
        "GỘP node (không hoàn tác được bằng cách gõ lại):": "ÖSSZEVONJA a csomópontokat (újragépeléssel nem vonható vissza):",
        "%d alias không có trên đồ thị, bị bỏ qua.": "%d álnév nincs a gráfban, ezeket kihagytuk.",
        "GraphRAG…": "GraphRAG…",
        "Phân tích phủ Chunk ↔ Entity": "Szemcse ↔ entitás lefedettség",
        "Xuất gói ngữ cảnh (JSONL)": "Kontextuscsomag exportálása (JSONL)",
        "Phủ Chunk ↔ Entity ↔ Graph": "Szemcse ↔ entitás ↔ gráf lefedettség",
        "- %d entity · %d chunk · %.0f%% entity được nhắc · %.0f%% chunk có entity": "- %1$d entitás · %2$d szemcse · az entitások %3$.0f%%-át említik · a szemcsék %4$.0f%%-a hordoz entitást",
        "Entity không chunk nào nhắc tới": "Entitások, amelyeket egyetlen szemcse sem említ",
        "Chunk mồ côi (không chứa entity nào)": "Árva szemcsék (nincs bennük entitás)",
        "Node đồ thị không có entity đối ứng": "Gráfcsomópontok, amelyeknek nincs megfelelő entitása",
        "không có": "nincs",
        "Phương pháp": "Módszer",
        "Không dựng được ánh xạ Chunk ↔ Entity": "A szemcse ↔ entitás megfeleltetést nem sikerült felépíteni",
        "Chấm sức khoẻ đồ thị": "A gráf egészségének pontozása",
        "sức khoẻ đồ thị": "a gráf egészsége",
        "Sức khoẻ %@/100 · %d lỗi · %d đảo · %d mồ côi": "Egészség %1$@/100 · %2$d hiba · %3$d sziget · %4$d magányos",
        "Lai với đồ thị": "Hibrid a gráffal",
        "α = 1: bỏ hẳn tín hiệu đồ thị, kết quả trùng BM25 thuần": "α = 1: a gráfjelzés teljesen ki van kapcsolva, az eredmény a tiszta BM25-tel egyezik",
        "α cao: đồ thị chỉ chỉnh nhẹ thứ hạng của BM25": "magas α: a gráf csak finoman igazít a BM25 rangsorán",
        "α quanh mặc định 0,7: BM25 dẫn, đồ thị chỉnh": "α a 0,7-es alapérték körül: a BM25 vezet, a gráf igazít",
        "α thấp: đồ thị dẫn, BM25 chỉ phá hoà": "alacsony α: a gráf vezet, a BM25 csak a holtversenyt dönti el",
        "α = 0: chỉ tín hiệu đồ thị; chunk không entity nào đều bằng điểm": "α = 0: csak a gráfjelzés; az entitás nélküli szemcsék mind holtversenyben állnak",
        "Tài liệu chưa lưu — phép lai cần một tệp đồ thị đặt cạnh corpus": "A dokumentum nincs mentve — a hibridhez gráffájl kell a korpusz mellett",
        "Không thấy tệp đồ thị «%@» — phép lai cần nó để có tín hiệu": "Nincs „%@” gráffájl — a hibridnek szüksége van rá, különben nincs jelzése",
        "lai %.1f ms · %@": "hibrid %.1f ms · %@",
        "Thuật toán…": "Algoritmus…",
        "PageRank (độ dày viền)": "PageRank (a keret vastagsága)",
        "Cộng đồng (màu nền)": "Közösségek (kitöltőszín)",
        "Thành phần liên thông": "Összefüggő komponensek",
        "Xuất bảng node ra tab mới": "A csomóponttáblázat exportálása új lapra",
        "%d thành phần · lớn nhất %d node · %d node mồ côi": "%1$d komponens · a legnagyobb %2$d csomópont · %3$d magányos",
        "Tài liệu này không phải đồ thị DOT": "Ez a dokumentum nem DOT-gráf",
        "Không dựng được bảng node/cạnh: %@": "A csomópont- és éltáblázatot nem sikerült felépíteni: %@",
        "%d hàng · %@": "%d sor · %@",
        "Gán nhãn": "Címke",
        "Ghi chú (tuỳ chọn)": "Megjegyzés (nem kötelező)",
        "Lưu record": "A bejegyzés mentése",
        "Xuất CSV": "CSV exportálása",
        "Tài liệu chưa lưu — bộ đánh giá cần nằm cạnh tệp corpus": "A dokumentum nincs mentve — a kiértékelő készletnek a korpuszfájl mellett kell lennie",
        "Không nạp được bộ đánh giá: %@": "A kiértékelő készletet nem sikerült betölteni: %@",
        "Không lưu được: %@": "Nem sikerült menteni: %@",
        "Bộ đánh giá chưa có record nào": "A kiértékelő készletben még nincs bejegyzés",
        "Không ghi được: %@": "Nem sikerült írni: %@",
        "Tài liệu này không phải tệp .mmd, không phải DOT, và chưa có khối mermaid.": "Ez a dokumentum nem .mmd fájl, nem DOT, és nincs benne mermaid blokk.",
        "%d node · %d cạnh · ⚠ %@": "%d csomópont · %d él · ⚠ %@",
        "Sơ đồ Mermaid: thêm phần tử…": "Mermaid diagram: elem hozzáadása…",
        "Sơ đồ Mermaid: nối hai phần tử đang chọn": "Mermaid diagram: a két kijelölt elem összekötése",
        "Sơ đồ Mermaid: sửa nhãn phần tử đang chọn…": "Mermaid diagram: a kijelölt elem címkéjének módosítása…",
        "Sơ đồ Mermaid: xoá phần tử đang chọn": "Mermaid diagram: a kijelölt elem törlése",
        "Sơ đồ Mermaid: đưa message lên trên": "Mermaid diagram: az üzenet mozgatása felfelé",
        "Sơ đồ Mermaid: đưa message xuống dưới": "Mermaid diagram: az üzenet mozgatása lefelé",
        "Thêm phần tử": "Elem hozzáadása",
        "Thêm participant": "Résztvevő hozzáadása",
        "Thêm mục": "Tétel hozzáadása",
        "Thêm mục sơ đồ": "Diagramtétel hozzáadása",
        "Sửa mục sơ đồ": "Diagramtétel módosítása",
        "Xoá mục sơ đồ": "Diagramtétel törlése",
        "Xoá phần tử": "Az elem törlése",
        "Sửa nhãn": "A címke módosítása",
        "Đổi thứ tự message": "Az üzenetek átrendezése",
        "Tên mục": "A tétel neve",
        "Mục mới": "Új tétel",
        "Tên mục hiện trên sơ đồ.": "A diagramon megjelenő tételnév.",
        "Bảng thuộc tính sơ đồ": "A diagram tulajdonságtáblája",
        "Tài liệu này không có khối mermaid nào": "Ebben a dokumentumban nincs mermaid blokk",
        "Định danh trong mã sơ đồ — không dấu cách. Nhãn sửa sau bằng double-click.": "Az azonosító a diagram forrásában — szóköz nélkül. A címkét később dupla kattintással módosíthatja.",
        "Để trống thì hiện chính định danh.": "Hagyja üresen, ha magát az azonosítót szeretné látni.",
        "Chỉ đổi NHÃN hiện trên hình; định danh phần tử giữ nguyên.": "Csak a diagramon látható CÍMKÉT változtatja meg; az elem azonosítója ugyanaz marad.",
        "Không rõ «%@» là phần tử nào": "Nem egyértelmű, melyik elem a(z) „%@”",
        "Bôi đen ĐÚNG HAI phần tử rồi chạy lại": "Jelöljön ki PONTOSAN KÉT elemet, és futtassa újra",
        "Đặt con nháy lên ĐÚNG MỘT phần tử rồi chạy lại": "Tegye a kurzort PONTOSAN EGY elemre, és futtassa újra",
        "Chọn MỘT phần tử để xoá, hoặc hai phần tử có cạnh nối": "Jelöljön ki EGY törlendő elemet, vagy két éllel összekötött elemet",
        "Xoá «%@» và %d cạnh chạm nó?": "Törli a(z) „%1$@” elemet és a hozzá tartozó %2$d élt?",
        "Node ở đầu kia của những cạnh ấy được giữ lại — chúng được khai lại kèm nhãn nếu câu lệnh cạnh là chỗ duy nhất khai chúng.": "Az élek túlsó végén lévő csomópontok megmaradnak — a címkéjükkel újra kiírjuk őket, ha csak az élparancs deklarálta őket.",
        "Sơ đồ «%@» chỉ soạn text — %@": "A(z) „%1$@” diagram csak szövegként szerkeszthető — %2$@",
        "%@: kéo giữa hai phần tử để nối, double-click để sửa nhãn": "%@: húzzon két elem között az összekötésükhöz, a címkét dupla kattintással módosíthatja",
        "%@: kéo giữa hai participant để thêm message; đổi thứ tự bằng menu Công cụ": "%@: húzzon két résztvevő között üzenet hozzáadásához; a sorrendet az Eszközök menüből rendezheti át",
        "%@: sửa trong bảng thuộc tính bên dưới": "%@: szerkessze az alábbi tulajdonságtáblában",
        "Soạn trực quan đã bật": "A vizuális szerkesztés bekapcsolva",
        "%@ · %d mục — sửa thẳng trong bảng, mỗi ô một bước hoàn tác": "%1$@ · %2$d tétel — szerkessze helyben; minden cella egy visszavonási lépés",
        "Với pie là một con số; với gantt là phần sau dấu hai chấm.": "Kördiagramnál egy szám; gantt-nál minden, ami a kettőspont után áll.",
        "Sơ đồ Mermaid: tách khối ra tệp .mmd…": "Mermaid diagram: a blokk kivágása .mmd fájlba…",
        "Sơ đồ Mermaid: nhúng tệp tham chiếu trở lại": "Mermaid diagram: a hivatkozott fájl visszaágyazása",
        "Tách khối sơ đồ": "A diagramblokk kivágása",
        "Nhúng khối sơ đồ": "A diagramblokk beágyazása",
        "Tách khối sơ đồ ra tệp riêng": "A diagramblokk kivágása saját fájlba",
        "Tệp đặt CẠNH tài liệu; khối trong tài liệu giữ một dòng tham chiếu để sửa một nơi.": "A fájl a dokumentum MELLÉ kerül; a blokk egy egysoros hivatkozást tart meg, így egy helyen szerkeszthető.",
        "Tài liệu chưa lưu — tệp sơ đồ cần chỗ để nằm cạnh": "A dokumentum nincs mentve — a diagramfájlnak kell egy hely, ahová mellé kerülhet",
        "Đã có tệp «%@» — chọn tên khác": "A(z) „%@” fájl már létezik — válasszon másik nevet",
        "Đã tách ra «%@» — khối giữ một dòng tham chiếu": "Kivágva ide: „%@” — a blokk egy egysoros hivatkozást tartott meg",
        "Mở tệp": "A fájl megnyitása",
        "Đã nhúng «%@» trở lại; tệp vẫn còn trên đĩa": "A(z) „%@” visszaágyazva; a fájl továbbra is a lemezen van",
        "Khối này chứa sơ đồ thật, không phải một tham chiếu": "Ez a blokk valódi diagramot tartalmaz, nem hivatkozást",
        "Khối này tham chiếu «%@» — mở tệp ấy để sửa": "Ez a blokk a(z) „%@” fájlra hivatkozik — nyissa meg azt a szerkesztéshez",
        "Không đọc được tệp sơ đồ %@": "A diagramfájlt nem sikerült elolvasni: %@",
        "Soạn trực quan": "Vizuális szerkesztés",
        "Kéo từ node này sang node kia để thêm cạnh; double-click để sửa nhãn. Mỗi thao tác một bước hoàn tác.": "Húzzon az egyik csomóponttól a másikig él hozzáadásához; a címkét dupla kattintással módosíthatja. Minden művelet egy visszavonási lépés.",
        "Soạn trực quan: kéo giữa hai node để thêm cạnh, double-click để sửa nhãn": "Vizuális szerkesztés: húzzon két csomópont között él hozzáadásához, a címkét dupla kattintással módosíthatja",
        "Soạn trực quan đã tắt": "A vizuális szerkesztés kikapcsolva",
        "Thêm node…": "Csomópont hozzáadása…",
        "Thêm cạnh giữa hai node đang chọn…": "Él hozzáadása a két kijelölt csomópont között…",
        "Sửa nhãn node đang chọn…": "A kijelölt csomópont címkéjének módosítása…",
        "Xoá node/cạnh đang chọn": "A kijelölt csomópont vagy él törlése",
        "Thêm node": "Csomópont hozzáadása",
        "Thêm cạnh": "Él hozzáadása",
        "Sửa nhãn node": "A csomópont címkéjének módosítása",
        "Xoá node": "A csomópont törlése",
        "Xoá cạnh": "Az él törlése",
        "Cmd-Z hoàn tác": "A Cmd-Z visszavonja",
        "Tài liệu đang ở chế độ chỉ đọc": "A dokumentum csak olvasható",
        "Nhãn của «%@»": "A(z) „%@” címkéje",
        "Chỉ đổi NHÃN hiện trên hình; định danh node giữ nguyên.": "Csak a diagramon látható CÍMKÉT változtatja meg; a csomópont azonosítója ugyanaz marad.",
        "Không rõ «%@» là node nào": "Nem egyértelmű, melyik csomópont a(z) „%@”",
        "Định danh node trong tệp DOT. Nhãn sửa sau bằng double-click trên hình.": "A csomópont azonosítója a DOT-fájlban. A címkét később a diagramon dupla kattintással módosíthatja.",
        "Bôi đen ĐÚNG HAI node rồi chạy lại": "Jelöljön ki PONTOSAN KÉT csomópontot, és futtassa újra",
        "Chọn MỘT node để xoá node, hoặc hai node có cạnh nối": "Jelöljön ki EGY csomópontot a törléséhez, vagy két éllel összekötött csomópontot",
        "Xoá node «%@» và %d cạnh chạm nó?": "Törli a(z) „%1$@” csomópontot és a hozzá tartozó %2$d élt?",
        "Giữ lại cạnh treo thì DOT tự sinh lại node từ chính những cạnh ấy — node vừa xoá sẽ hiện lại ở lần vẽ sau.": "Ha lógó élek maradnak, a DOT éppen azokból hozza létre újra a csomópontot — a most törölt csomópont a következő kirajzoláskor újra megjelenne.",
        "Phòng thí nghiệm truy hồi BM25": "BM25 kereső labor",
        "Câu hỏi — Enter để tìm": "Kérdés — Enterrel keres",
        "Đánh giá…": "Kiértékelés…",
        "Đang dựng chỉ mục": "Az index épül",
        "Không chunk nào khớp": "Egy szemcse sem illeszkedik",
        "kết quả trên": "találat ennyiből:",
        "k1 = 0: mỗi từ chỉ tính MỘT lần dù xuất hiện bao nhiêu lần": "k1 = 0: minden szó EGYSZER számít, akárhányszor is fordul elő",
        "k1 thấp: lặp từ nhiều lần gần như không cộng thêm điểm": "alacsony k1: egy szó ismétlése szinte semmit sem ad hozzá",
        "k1 quanh mặc định 1,2: lặp từ có cộng điểm nhưng giảm dần": "k1 az 1,2-es alapérték körül: az ismétlés növeli a pontszámot, de egyre kevésbé",
        "k1 cao: chunk lặp một từ nhiều lần được thưởng mạnh": "magas k1: a szót sokszor ismétlő szemcsék erős jutalmat kapnak",
        "b = 0: bỏ qua độ dài, chunk dài không bị phạt": "b = 0: a hosszt figyelmen kívül hagyjuk, a hosszú szemcséket nem büntetjük",
        "b thấp: chunk dài chỉ bị phạt nhẹ": "alacsony b: a hosszú szemcséket csak enyhén büntetjük",
        "b quanh mặc định 0,75: chunk dài bị phạt vừa phải": "b a 0,75-ös alapérték körül: a hosszú szemcséket mérsékelten büntetjük",
        "b = 1: phạt tối đa theo độ dài, chunk ngắn được ưu ái": "b = 1: maximális hosszbüntetés, a rövid szemcsék előnyben",
        "JSONL: phòng thí nghiệm truy hồi…": "JSONL: kereső labor…",
        "Tài liệu chưa lưu — chỉ mục BM25 nằm cạnh tệp corpus nên cần một đường dẫn": "A dokumentum nincs mentve — a BM25-index a korpuszfájl mellett lakik, ezért útvonal kell hozzá",
        "Tệp này không phải JSONL — Retrieval Lab chạy trên corpus chunk": "Ez a fájl nem JSONL — a Kereső labor szemcsekorpuszokon dolgozik",
        "Không dựng được chỉ mục BM25 cho tệp này": "Ehhez a fájlhoz nem sikerült BM25-indexet építeni",
        "Tài liệu chưa lưu — cần đường dẫn corpus để sinh báo cáo": "A dokumentum nincs mentve — a jelentéshez korpuszútvonal kell",
        "Chọn bộ đánh giá (CSV hoặc JSONL: câu hỏi + id chunk kỳ vọng)": "Válasszon kiértékelő készletet (CSV vagy JSONL: kérdés + várt szemcseazonosítók)",
        "Đánh giá truy hồi": "A keresés kiértékelése",
        "Sửa k1, b hoặc k ở trên rồi xem lại để so hai cấu hình; thêm khối «compare» để chạy song song hai bộ tham số trên cùng bộ đánh giá.": "Módosítsa fent a k1, b vagy k értékét, és jelenítse meg újra két beállítás összehasonlításához; adjon hozzá egy „compare” blokkot, hogy két paraméterkészlet egymás mellett fusson ugyanazon a kiértékelő készleten.",
        "Lỗi": "Hibák",
        "   (%d…%d, trung bình %.0f)": "   (%1$d…%2$d, átlag %3$.0f)",
        "Chế độ JSONL": "JSONL-mód",
        "Bản ghi": "Bejegyzés",
        "Chi tiết": "Részletek",
        "Bản ghi ở dòng": "A bejegyzés ebben a sorban",
        "không phải JSON hợp lệ": "nem érvényes JSON",
        "bản ghi": "bejegyzés",
        "dòng trắng": "üres sor",
        "không phải đối tượng": "nem objektum",
        "bảng hiện": "a táblázat mutatja",
        "ĐÃ HUỶ giữa chừng": "MENET KÖZBEN MEGSZAKÍTVA",
        "Không lọc": "Nincs szűrő",
        "bản ghi khớp bộ lọc": "bejegyzés illeszkedik a szűrőre",
        "Đưa con nháy tới một dòng để xem bản ghi": "Vigye a kurzort egy sorra a bejegyzés megtekintéséhez",
        "Không có bản ghi nào hỏng": "Nincs hibás bejegyzés",
        "Chưa soi. Chạy lại lệnh «JSONL: soi chunk» sau khi kiểm xong.": "Még nem vizsgáltuk meg. Az ellenőrzés végeztével futtassa a „JSONL: a szemcsék vizsgálata” parancsot.",
        "trường văn bản": "szövegmező",
        "SCHEMA (đoán — sửa được bằng cách chọn trường khác)": "SÉMA (találgatás — másik mező választásával változik)",
        "văn bản": "szöveg",
        "định danh": "azonosító",
        "metadata lồng": "beágyazott metaadat",
        "TRƯỜNG": "MEZŐK",
        "phủ": "megvan ennyiben:",
        "nhiều kiểu": "vegyes típusok",
        "ĐỘ DÀI — ký tự": "HOSSZ — karakterek",
        "ĐỘ DÀI — từ": "HOSSZ — szavak",
        "ĐỘ DÀI — token ước lượng": "HOSSZ — becsült tokenek",
        "RỖNG VÀ TRÙNG": "ÜRES ÉS ISMÉTLŐDŐ",
        "chunk rỗng": "üres szemcse",
        "dòng": "sor",
        "nhóm trùng chính xác": "pontosan egyező ismétlődő csoport",
        "dòng không đọc được, không vào thống kê": "olvashatatlan sor, a statisztikából kihagyva",
        "PHƯƠNG PHÁP": "MÓDSZER",
        "«ký tự» đếm theo ký tự Unicode (scalar), không theo cụm hiển thị": "a „karakter” Unicode-skalárokat számol, nem megjelenítési egységeket",
        "«từ» tách theo khoảng trắng ASCII": "a „szó” ASCII szóközök mentén válik szét",
        "«token» đếm bằng bộ tách âm tiết — KHÔNG phải bộ tách của model": "a „token” a szótagoló egységeit használja — NEM a modellét",
        "«trùng» là trùng CHÍNH XÁC; trùng GẦN nằm ở khối ```quality": "az „ismétlődő” PONTOS egyezést jelent; a KÖZEL azonosak a ```quality blokkban vannak",
        "chunk": "szemcse",
        "JSONL: kiểm và soi chunk…": "JSONL: a szemcsék ellenőrzése és vizsgálata…",
        "Ảnh": "Kép",
        "PDF": "PDF",
        "Tài liệu Word": "Word-dokumentum",
        "Bảng tính Excel": "Excel-munkafüzet",
        "Bản trình chiếu PowerPoint": "PowerPoint-bemutató",
        "File nén": "Archívum",
        "Vừa khung": "Ablakhoz igazítás",
        "Chép ảnh": "A kép másolása",
        "Xoay": "Forgatás",
        "Không đọc được ảnh «%@»": "A(z) „%@” kép nem olvasható",
        "Đã chép ảnh vào clipboard": "A kép a vágólapra másolva",
        "Bôi vàng": "Kiemelés",
        "Gạch chân": "Aláhúzás",
        "Ghi chú…": "Megjegyzés…",
        "Bỏ chú thích": "A jegyzetek törlése",
        "Lấy chữ ra tab mới": "A szöveg kiemelése új lapra",
        "Lưu bản có chú thích…": "A jegyzetelt másolat mentése…",
        "Tìm trong PDF": "Keresés a PDF-ben",
        "Thêm": "Hozzáadás",
        "Trang %d/%d": "%d. oldal, összesen %d",
        "Trang %d": "%d. oldal",
        "Kết quả %d/%d": "%d. találat, összesen %d",
        "0 kết quả": "Nincs találat",
        "Không đọc được PDF «%@»": "A(z) „%@” PDF nem olvasható",
        "PDF này có mật khẩu — chưa mở được nội dung": "Ez a PDF jelszóval védett — a tartalma nem nyitható meg",
        "Không thấy «%@» trong tài liệu": "A(z) „%@” nincs ebben a dokumentumban",
        "Đã bôi vàng": "Kiemelve",
        "Đã gạch chân": "Aláhúzva",
        "Hãy bôi đen một đoạn chữ trước": "Előbb jelöljön ki egy szövegrészt",
        "Đã thêm ghi chú": "A jegyzet hozzáadva",
        "Trang này chưa có chú thích nào": "Ezen az oldalon nincs jegyzet",
        "Đã bỏ %d chú thích trên trang này": "%d jegyzet eltávolítva erről az oldalról",
        "PDF này không có tầng chữ — nhiều khả năng là bản quét ảnh": "Ennek a PDF-nek nincs szövegrétege — nagy valószínűséggel beolvasott kép",
        "Không ghi được tệp": "A fájlt nem lehet megírni",
        "Tệp vừa ghi mở lại KHÔNG đúng — đừng dùng bản này": "Az imént megírt fájl NEM nyílik meg helyesen — ne használja ezt a másolatot",
        "Đã lưu %@ · %d trang": "Mentve: %1$@ · %2$d oldal",
        "Tên": "Név",
        "Kích thước": "Méret",
        "Đã nén": "Tömörítve",
        "Tỉ lệ": "Arány",
        "Sửa lúc": "Módosítva",
        "Mở mục đang chọn": "A kijelölt bejegyzés megnyitása",
        "Bung ra thư mục…": "Kibontás mappába…",
        "Bung vào đây": "Kibontás ide",
        "%d mục": "%d bejegyzés",
        "giải nén ra %@": "kibontva %@ méretre",
        "— ruột của tệp Office là file nén, đây là các phần bên trong": "— egy Office-fájl belseje archívum; ezek a benne lévő részek",
        "Đã bung %d mục": "%d bejegyzés kibontva",
        "%d mục hỏng": "%d bejegyzés hibás",
        "%d mục bị TỪ CHỐI vì đường dẫn thoát ra ngoài": "%d bejegyzést ELUTASÍTOTTUNK — az útvonaluk kivezet a célmappából",
        "Không mở được mục này": "Ezt a bejegyzést nem lehet megnyitni",
        "Chưa ghi ngược được vào tệp %@ — hãy dùng «Lưu thành…»": "%@ fájlba még nem lehet közvetlenül visszaírni — használja a „Mentés másként…” parancsot",
        "Không có gì đổi": "Semmi sem változott",
        "Đã ghi %d ô vào %@": "%1$d cella beírva ide: %2$@",
        "Đã ghi %d đoạn vào %@": "%1$d bekezdés beírva ide: %2$@",
        "Không ghi được vào tệp — bản gốc còn nguyên": "A fájlba nem sikerült írni — az eredeti érintetlen",
        "dựng bài": "teszteset előkészítése",
        "Không ghi được settings.json": "A settings.json nem írható",
        "Xoay trái": "Forgatás balra",
        "Xoay phải": "Forgatás jobbra",
        "Trang lên": "Oldal felfelé",
        "Trang xuống": "Oldal lefelé",
        "Xoá trang…": "Oldalak törlése…",
        "Xoá trang": "Oldalak törlése",
        "Trích trang…": "Oldalak kinyerése…",
        "Trích trang ra tệp mới": "Oldalak kinyerése új fájlba",
        "Gộp tệp PDF…": "PDF-fájl egyesítése…",
        "Tách tệp…": "Fájl szétvágása…",
        "Tách tệp PDF": "PDF-fájl szétvágása",
        "Xuất ảnh…": "Képek exportálása…",
        "Xuất trang ra ảnh PNG": "Oldalak exportálása PNG-képként",
        "Hoàn tác trang": "Oldalszerkesztés visszavonása",
        "Lưu bản đã sửa…": "Szerkesztett másolat mentése…",
        "Phát": "Lejátszás",
        "Tạm dừng": "Szünet",
        "Xem bình thường": "Normál nézet",
        "Chọn sheet": "Munkalap választása",
        "Mở sheet": "Munkalap megnyitása",
        "Bỏ và đổi sheet": "Elvetés és munkalapváltás",
        "Bảng tính có %d sheet.": "A munkafüzet %d munkalapot tartalmaz.",
        "Bảng tính này chỉ có một sheet: «%@»": "Ez a munkafüzet csak egy munkalapot tartalmaz: „%@”",
        "Bỏ phần chưa lưu của sheet này?": "Elveti a munkalap nem mentett módosításait?",
        "Đổi sheet sẽ thay toàn bộ nội dung tab. Phần vừa sửa mà chưa ⌘S sẽ mất.": "A munkalapváltás lecseréli az egész lapot. Ami nincs ⌘S-sel mentve, elvész.",
        "Chọn tệp PDF cần gộp vào": "Válassza ki az egyesítendő PDF-fájlt",
        "Chọn thư mục ghi ảnh": "Válasszon mappát a képeknek",
        "Chọn chỗ ghi. Tệp thứ hai ghi cạnh tệp này.": "Válassza ki a mentés helyét. A második fájl emellé kerül.",
        "Tài liệu có %d trang. Nhập trang cần xoá, ví dụ 2-4,7": "A dokumentum %d oldalas. Adja meg a törlendő oldalakat, pl. 2-4,7",
        "Tài liệu có %d trang. Nhập trang cần trích, ví dụ 1-3,8": "A dokumentum %d oldalas. Adja meg a kinyerendő oldalakat, pl. 1-3,8",
        "Tài liệu có %d trang. Nhập trang cần xuất, ví dụ 1-3": "A dokumentum %d oldalas. Adja meg az exportálandó oldalakat, pl. 1-3",
        "Tài liệu có %d trang. Nhập phần tách ra, ví dụ 1-5; phần còn lại ghi thành tệp thứ hai.": "A dokumentum %d oldalas. Adja meg a leválasztandó részt, pl. 1-5; a többi külön fájlba kerül.",
        "Đã xoay trang %d": "%d. oldal elforgatva",
        "Đã xoá trang %@ · còn %d trang": "%@ oldal törölve · %d oldal maradt",
        "Đã gộp %d trang từ «%@»": "%d oldal egyesítve innen: „%@”",
        "Đã tách thành %@ (%d trang) và %@ (%d trang)": "Szétvágva: %@ (%d oldal) és %@ (%d oldal)",
        "Đã ghi %@ — %@ · %d trang": "%@ kiírva — %@ · %d oldal",
        "Đã xuất %d ảnh vào %@": "%d kép exportálva ide: %@",
        "Chỉ xuất được %d/%d ảnh": "Csak %d kép exportálva a(z) %d közül",
        "Đã hoàn tác một thao tác trang": "Egy oldalművelet visszavonva",
        "Không còn thao tác trang nào để hoàn tác": "Nincs több visszavonható oldalművelet",
        "Không xoá được TẤT CẢ trang — một PDF phải còn ít nhất một trang": "Nem törölhető AZ ÖSSZES oldal — egy PDF-nek legalább egy oldala kell legyen",
        "Phần tách ra là toàn bộ tài liệu — không có gì để tách": "Ez a tartomány a teljes dokumentum — nincs mit leválasztani",
        "«%@» có mật khẩu — chưa gộp được": "A(z) „%@” jelszóval védett — nem egyesíthető",
        "«%@» không có trang nào": "A(z) „%@” nem tartalmaz oldalt",
        "Đã ở trang đầu": "Már az első oldalon",
        "Đã ở trang cuối": "Már az utolsó oldalon",
        "· đã sửa, chưa lưu": "· szerkesztve, nincs mentve",
        "Ảnh động · %d khung": "Animált kép · %d képkocka",
        "Tài liệu chưa lưu — không có tệp trên đĩa để xem nhị phân": "Nem mentett dokumentum — nincs fájl a lemezen a bináris nézethez",
        "Lệnh này chỉ dùng cho bảng tính Excel": "Ez a parancs csak Excel-munkafüzetekkel működik",
        "Không đọc được danh sách sheet": "A munkalapok listája nem olvasható",
        "Không có sheet «%@»": "Nincs „%@” nevű munkalap",
        "Không đọc được sheet «%@»": "A(z) „%@” munkalap nem olvasható",
        "Sheet «%@» · %d hàng": "„%@” munkalap · %d sor",
        "phần còn lại": "a maradék",
        "Lưu ý": "Megjegyzés",
        "Cẩn thận": "Vigyázat",
        "Xem thêm": "Lásd még",
        "Chép": "Másolás",
        "Đã chép": "Másolva",
        "Chép đoạn mã mẫu": "Példakód másolása",
        "Tìm trong trợ giúp": "Keresés a súgóban",
        "Lùi": "Vissza",
        "Bắt đầu dùng": "Kezdés",
        "Không mở cửa sổ này khi khởi động nữa": "Ne jelenjen meg ez az ablak induláskor",
        "Bản dịch trợ giúp cho ngôn ngữ này chưa có — đang hiện bản tiếng Việt.": "A súgó még nincs lefordítva erre a nyelvre — a vietnami szöveg látható.",
        "Tới offset (vd 1F400 hoặc 0x1F400)": "Ugrás eltoláshoz (pl. 1F400 vagy 0x1F400)",
        "Chép dòng đã chọn": "Kijelölt sorok másolása",
        "Đã chép %d dòng": "%d sor másolva",
        "Không đọc được «%@»": "A(z) „%@” nem olvasható",
        "Tệp rỗng": "Üres fájl",
        "Không đọc được offset «%@»": "A(z) „%@” eltolás nem olvasható",
        "Offset 0x%@ vượt quá cỡ tệp": "A 0x%@ eltolás túlmutat a fájl méretén",
        "Mở bằng ứng dụng khác…": "Megnyitás másik alkalmazással…",
        "%d kênh": "%d csatorna",
        "Không phát được «%@»": "A(z) „%@” nem játszható le",
        "Không phát được — %@": "Nem játszható le — %@",
        "macOS không có bộ giải mã sẵn cho định dạng %@ — đây là giới hạn của hệ điều hành, không phải tệp hỏng.": "A macOS nem tartalmaz dekódolót a(z) %@ formátumhoz — ez rendszerkorlát, nem sérült fájl.",
        "Nội dung tệp vẫn xem được ở chế độ nhị phân, hoặc mở bằng một ứng dụng có bộ giải mã riêng.": "A bájtokat továbbra is megnézheti bináris nézetben, vagy megnyithatja saját dekódolóval rendelkező alkalmazással.",
        "Ký…": "Aláírás…",
        "Sửa chữ…": "Szöveg szerkesztése…",
        "Sửa chữ": "Szöveg szerkesztése",
        "Vẽ đè": "Rárajzolás",
        "Ô chưa điền": "Következő üres mező",
        "Xoá nội dung đã điền": "Kitöltött értékek törlése",
        "Tệp này không có ô biểu mẫu nào": "Ebben a fájlban nincsenek űrlapmezők",
        "Đã xoá nội dung của %d ô biểu mẫu": "%d űrlapmező törölve",
        "Mọi ô biểu mẫu đều đã có nội dung": "Minden űrlapmező ki van töltve",
        "Còn %d ô chưa điền": "Még %d mező üres",
        "Biểu mẫu điền được: %d ô. Gõ thẳng vào ô, rồi «Lưu bản đã sửa…»": "Kitölthető űrlap: %d mező. Írjon közvetlenül beléjük, majd „Szerkesztett másolat mentése…”",
        "Chọn ảnh chữ ký (nền trong suốt thì đẹp nhất)": "Válasszon aláíráskképet (átlátszó háttérrel a legjobb)",
        "Không dựng được trang có chữ ký": "Az aláírt oldal nem hozható létre",
        "Đã chèn chữ ký vào trang %d": "Aláírás beszúrva a(z) %d. oldalra",
        "Hãy bôi chọn phần chữ cần sửa trước": "Először jelölje ki a módosítandó szöveget",
        "Vùng chọn quá nhỏ": "A kijelölés túl kicsi",
        "Chữ mới được VẼ ĐÈ lên vùng đã chọn bằng font hệ thống. Chữ cũ bị che chứ không bị xoá — nó vẫn trích ra được, nên đây không phải cách bôi đen.": "Az új szöveg a rendszerbetűtípussal a kijelölés FÖLÉ kerül. A régi szöveg eltakarva marad, nem törlődik — továbbra is kinyerhető, tehát ez nem kitakarás.",
        "Không dựng được trang đã sửa": "A szerkesztett oldal nem hozható létre",
        "Đã vẽ đè chữ mới lên trang %d": "Az új szöveg a(z) %d. oldalra rajzolva",
        "Đổi chế độ View / Code": "Váltás Nézet / Kód",
        "Chưa có chế độ View dạng cây cho JSON · XML · YAML": "Még nincs fanézet a JSON · XML · YAML fájlokhoz",
        "Chưa có chế độ View dạng sơ đồ trong tab": "Még nincs diagramnézet a lapon",
        "Chưa có chế độ View dạng dàn ý cho PowerPoint": "Még nincs vázlatnézet a PowerPointhoz",
        "Tệp này chỉ có một chế độ hiển thị": "Ennek a fájlnak csak egy megjelenítési módja van",
        "%d nút": "%d csomópont",
        "Không dựng được cây: %@": "A fa nem építhető fel: %@",
        "Tài liệu quá lớn để dựng cây — dùng chế độ Code": "A dokumentum túl nagy fához — használja a Kód módot",

        // --- Trang tài liệu tự dựng (04/09/2026) ---
        "Không dựng được trang của tệp này — dùng chế độ Code.":
            "Nem sikerült felépíteni a fájl oldalait \u{2014} használd a Code módot.",
        "Slide dựng từ chữ; hình và bố cục gốc chưa được vẽ lại.":
            "A diák szövegből épülnek; az eredeti képek és elrendezés még nincs kirajzolva.",
        "Vừa ngang": "Szélességhez",
        "Thu nhỏ trang": "Oldal kicsinyítése",
        "Phóng to trang": "Oldal nagyítása",

        // --- Tìm chữ trong trang đã dựng (04/09/2026) ---
        "Không tìm thấy «%@» trong tài liệu": "A „%@” nem található a dokumentumban",
        "Chỗ khớp %d/%d": "%d. találat %d közül",

        // --- Chọn và chép chữ trên trang (04/09/2026) ---
        "Chưa chọn chữ nào trên trang.": "Nincs kijelölt szöveg az oldalon.",
        "%d ký tự": "%d karakter",
        "Mở tệp là vào thẳng chế độ View nếu tệp ấy có":
            "A fájlok megnyitása rögtön View módban, ha van ilyen",
        " · ĐÃ HUỶ giữa chừng — bảng chưa đầy đủ": "· FÉLBEHAGYVA — a táblázat hiányos",
        "Chế độ hiển thị": "Megjelenítési mód",
        "Đổi giữa View và Code (⌥⌘V)": "Váltás View és Code között (⌥⌘V)",
        "Trang tài liệu": "Dokumentumoldalak",
        "Chữ đã dựng": "Tördelt szöveg",
        "Trang bảng tính": "Munkalapoldalak",
        "Sơ đồ": "Diagram",
        "Cây khoá–giá trị": "Kulcs–érték fa",
        "Bộ phát": "Lejátszó",
        "Danh sách mục": "Bejegyzéslista",
        "Báo cáo đã dựng": "Kész jelentés",
        "Tô theo mức": "Szint szerint színezve",
        "Trang slide": "Diaoldalak",
        "Dàn ý": "Vázlat",
        "Lưu rồi dựng lại": "Mentés és újraépítés",
        "Đang xem bản TRÊN ĐĨA — những sửa đổi chưa lưu không có ở đây.": "A LEMEZEN lévő példányt mutatja — a nem mentett módosítások nincsenek benne.",
        "Hệ thống không dựng được bộ xem tài liệu — dùng chế độ Code.": "A rendszer nem tudta felépíteni a dokumentumnézetet — használja a Code módot.",
        "Lưu tệp trước khi xem trang.": "Mentse a fájlt, mielőtt megnézi az oldalait.",
        "Đang ở chế độ Code": "Most Code módban",
        "Đang ở chế độ View": "Most View módban",
        "Đang xem mã nguồn — bấm để sang chế độ View (⌥⌘V)": "A forrást látja — kattintson a View módhoz (⌥⌘V)",
        "Đang ở chế độ View — bấm để quay về mã nguồn (⌥⌘V)": "View módban — kattintson, hogy visszatérjen a forráshoz (⌥⌘V)",
        "Tín hiệu: %@": "Jelzés: %@",
        "Lý do: %@": "Ok: %@",
        "Chi tiết: %@": "Részlet: %@",
        "Mở báo cáo": "Jelentés megnyitása",
        "GEditor đã đóng đột ngột lúc %@ — mở báo cáo để xem, không có gì được gửi đi.": "A GEditor váratlanul leállt ekkor: %@ — nyissa meg a jelentést; semmi sem kerül elküldésre.",
        "Chữ ghép (ligature) — tắt thì mỗi ký tự một ô": "Ligatúrák — kikapcsolva minden karakter a saját cellájában marad",
        "Chế độ CSV": "CSV mód",
        "Dấu phân tách": "Elválasztó",
        "Tự nhận diện": "Automatikus felismerés",
        "Dấu phân tách: %@": "Elválasztó: %@",
        "Theo đuôi tệp": "Fájlkiterjesztés szerint",
        "%d dấu cách": "%d {one=szóköz|other=szóköz}",
        "Tài liệu đang sửa được": "Ez a dokumentum szerkeszthető",
        "Chỉ đọc vì đang theo dõi file — tắt theo dõi để sửa lại": "Csak olvasható, mert a fájlt figyeljük — a szerkesztéshez állítsa le a figyelést",
        "Chỉ đọc vì tệp trên đĩa không cho ghi": "Csak olvasható, mert a lemezen lévő fájl nem írható",
        "Đã mở khoá — tài liệu sửa được": "Feloldva — a dokumentum újra szerkeszthető",
        "Nhân bản tệp": "Fájl megkettőzése",
        "Đổi tên tệp…": "Fájl átnevezése…",
        "Chuyển tệp tới…": "Fájl áthelyezése ide…",
        "XML: đánh giá XPath…": "XML: XPath kiértékelése…",
        "Đánh giá XPath": "XPath kiértékelése",
        "Ví dụ: //don_hang/hang[2]/@ma · //*[@loai='A'] · count(//hang)": "Például: //rendeles/tetel[2]/@kod · //*[@fajta='A'] · count(//tetel)",
        "Đánh giá": "Kiértékelés",
        "XPath không đọc được: %@": "Ez az XPath nem olvasható: %@",
        "XPath «%@» không khớp node nào": "A(z) „%@” XPath egyetlen csomópontot sem talált",
        "XPath «%@» — %d node": "XPath „%@” — %d {one=csomópont|other=csomópont}",
        "XPath «%@»: %d node": "XPath „%@”: %d {one=csomópont|other=csomópont}",
        "Lưu tệp trước khi nhân bản.": "Mentse a fájlt, mielőtt megkettőzi.",
        "Không nhân bản được": "Nem sikerült megkettőzni",
        "Đã nhân bản thành %@": "Megkettőzve %@ néven",
        "Lưu tệp trước khi đổi tên.": "Mentse a fájlt, mielőtt átnevezi.",
        "Đổi tên tệp": "Fájl átnevezése",
        "Tên hiện tại: %@": "Jelenlegi név: %@",
        "Đổi tên": "Átnevezés",
        "Tên tệp không hợp lệ": "Ez a fájlnév érvénytelen",
        "Đã có tệp tên %@ ở đó": "Ott már van %@ nevű fájl",
        "Lưu tệp trước khi chuyển.": "Mentse a fájlt, mielőtt áthelyezi.",
        "Chuyển tới": "Áthelyezés ide",
        "Thư mục đích đã có tệp tên %@": "A célmappában már van %@ nevű fájl",
        "Không chuyển được tệp": "A fájlt nem sikerült áthelyezni",
        "Đã chuyển tới %@": "Áthelyezve ide: %@",
        "Bảng mã:": "Kódolás:",
        "Xuống dòng:": "Sorvégek:",
        "Riêng cho %@": "Csak ehhez: %@",
        "    %d — dùng TAB": "    %d — tabulátor",
        "    %d — dùng dấu cách": "    %d — szóköz",
        "    Bỏ khai riêng, dùng cài đặt chung": "    Saját szabály eltávolítása, az általános beállítás használata",
        "%@: thụt lề %d %@": "%@: behúzás %d %@",
        "TAB": "tabulátor",
        "dấu cách": "szóköz",
        "Xuất": "Exportálás",
        "Mở kết quả thành một tab văn bản — lưu lại bằng ⌘S": "Az eredmények megnyitása szöveges lapként — mentse ⌘S-sel",
        "Lượt tìm trước đó": "Korábbi keresések",
        "«%@» — %d kết quả": "„%@” — %d {one=találat|other=találat}",
        "Kết quả tìm «%@»": "„%@” keresési eredményei",
        "Lọc tên tệp — ví dụ *.csv;*.log (để trống: mọi tệp văn bản)": "Fájlnevek szűrése — pl. *.csv;*.log (üresen: minden szövegfájl)",
        "Thư mục %@ không có file văn bản nào": "A(z) %@ mappában nincsenek szövegfájlok",
        "Không tệp nào trong %@ khớp «%@»": "A(z) %@ mappában egyik fájl sem illeszkedik erre: „%@”",
        "%d byte · %d dòng": "%d bájt · %d {one=sor|other=sor}",
        "%d byte · %d dòng — tệp quá lớn để đếm ký tự và từ": "%d bájt · %d {one=sor|other=sor} — túl nagy a karakterek és szavak megszámolásához",
        "%d byte · %d ký tự · %d từ · %d dòng": "%d bájt · %d {one=karakter|other=karakter} · %d {one=szó|other=szó} · %d {one=sor|other=sor}",
        "Tài liệu có %d dòng, %d byte. Gõ số dòng, «dòng,cột», hoặc «@vị trí byte».": "Ez a dokumentum %d {one=sor|other=sor}, %d bájt. Írjon sorszámot, „sor,oszlop” vagy „@bájt” alakban.",
        "12 · 12,5 · @1024": "12 · 12,5 · @1024",
        "Không hiểu «%@» — gõ số dòng, «dòng,cột», hoặc «@vị trí byte»": "„%@” nem olvasható — írjon sorszámot, „sor,oszlop” vagy „@bájt” alakban",
    ]
}
