# -*- coding: utf-8 -*-
"""CDS-12 dữ liệu chi tiết — phần A: project, memory, archive, search, extract, passport, kg, board.
Ký hiệu kiểu: str|int|num|bool|obj|arr<...>|enum:a|b ; hậu tố '!' = bắt buộc ; ' # ' = mô tả."""
D = {}
def d(id, inp, out, steps, err, undo, ex, tc): D[id] = dict(inp=inp, out=out, steps=steps, err=err, undo=undo, ex=ex, tc=tc)

# ---------- project ----------
d("project.create", {"text": "str! # câu lệnh gốc", "docs_path": "str", "chip": "str", "board": "str", "autonomy": "enum:A0|A1|A2|A3|A4", "name": "str", "dir": "str"},
  {"project_id": "str!", "path": "str!", "created": "bool!", "existing": "arr<obj> # dự án trùng/gần giống nếu có", "next": "arr<str> # năng lực nên gọi tiếp"},
  ["Suy tên (slug từ ý tưởng/tên nêu), thư mục (defaults.project_dir/<slug>), chip/board từ text hoặc mentions", "chat.ground: tra workspace khớp tên gần đúng (Levenshtein ≤ 2 hoặc trùng ≥ 2 từ khóa) → nếu trùng đúng tên: E2001 kèm phương án reuse|clone|new; gần giống: trả existing để Orchestrator hỏi (Z-02)", "Tạo .eide/ (store, session, index, docs/, diagrams/, PROGRESS.md, FEATURES.json, constraints.yaml, autonomy.yaml từ defaults, .gitignore)", "Nếu chip đã biết: project.set_target (ghim hộ chiếu); nếu docs_path: next=[archive.explore]; nếu ý tưởng: next=[search.reference_projects]", "Ghi ledger project.init; đăng ký undo delete_created_files"],
  ["E2001 ALREADY_EXISTS (trùng đúng tên)", "E1000 tên không hợp lệ", "E8000 thư mục ngoài workspace cho phép"], "delete_created_files",
  '{"text":"Tạo cho anh dự án robot hai bánh tự cân bằng","autonomy":"A3"}', "Tạo thư mục đúng cấu trúc; gọi lần 2 cùng tên → E2001; tên gần giống → existing[] không rỗng và created=false khi create_when_exists=ask")
d("project.open", {"project": "str! # id hoặc đường dẫn"}, {"summary": "obj! # dự án, board, hộ chiếu, feature failing đầu, mục chờ, undo còn hạn", "migrated": "bool", "stale_runs": "arr<str>"},
  ["Kiểm .eide/ tồn tại; PRAGMA user_version → nếu cũ: E6003 (Orchestrator gọi eide migrate)", "Kiểm hash store vs ledger.last_hash → lệch: E6000", "Tái dựng KG từ cache (hash khớp) hoặc từ store", "Mở SessionMemory mới; memory.summarize_session của phiên trước; đọc run có state running/asked", "Trả summary; ghi ledger session.open"],
  ["E6003 MIGRATION_REQUIRED", "E6000 STORE_INTEGRITY", "E2000 không tìm thấy"], "none", '{"project":"~/eide/robot-2-banh"}', "Store hợp lệ → summary có feature đầu; store bị ghi ngoài cổng → E6000")
d("project.list", {"workspace": "str"}, {"projects": "arr<obj>! # id, path, created, last_open, board, passing/total, autonomy"}, ["Quét thư mục workspace tìm .eide/; đọc FEATURES.json và constraints.yaml", "Sắp theo last_open giảm dần"], ["E2000 workspace không tồn tại"], "none", '{}', "Ba dự án mẫu → 3 mục đúng thứ tự")
d("project.clone", {"src": "str!", "new_name": "str!", "keep": "arr<enum:knowledge|code|docs|features> # mặc định knowledge"}, {"project_id": "str!", "path": "str!"}, ["Kiểm new_name chưa tồn tại (E2001)", "Sao chép store (fact, passport, constraints), tùy chọn mã/tài liệu; bỏ ledger, session, index, decision_log, run", "Ghi ledger project.clone với nguồn"], ["E2001", "E2000 src không có"], "delete_created_files", '{"src":"robot-ctrl","new_name":"robot-ctrl-v2","keep":["knowledge","code"]}', "Bản sao có cùng số fact, ledger rỗng")
d("project.archive", {"project": "str!"}, {"archived_path": "str!"}, ["Đóng phiên nếu mở; nén .eide/ và mã (không bao gồm cache/index) thành <name>-<date>.zip trong workspace/archive/", "Đánh dấu archived trong project.list"], ["E2000"], "restore_config", '{"project":"test-1"}', "Zip mở lại được; project.list gắn cờ archived")
d("project.set_target", {"chip": "str", "isa": "str", "board": "str", "pin_version": "str"}, {"pins": "obj! # hộ chiếu đã ghim {chip@ver, board@ver, isa}", "missing": "arr<str>"}, ["Suy ISA từ chip qua hộ chiếu/seed (bảng họ chip → ISA); board từ discovery nếu đang cắm", "Ghim phiên bản hộ chiếu vào constraints.yaml (registry.pull nếu chưa có trong store)", "Nếu không có hộ chiếu → missing + kg.request"], ["E2000 chip không rõ và không tìm được"], "restore_config", '{"chip":"STM32F411CE"}', "Ghim st.stm32f411ce@x; constraints.yaml cập nhật; chip lạ → missing")
d("project.rollback", {"tag": "str # mặc định known-good gần nhất"}, {"state": "obj! # commit, features"}, ["Xác định tag known-good; git checkout -B auto/rollback <tag>; build kiểm", "FEATURES.json khôi phục từ tag; ghi ledger"], ["E7001 xung đột working tree", "E2000 không có tag"], "restore_config", '{}', "Sau sửa hỏng → rollback → build đạt")
d("project.status", {}, {"report": "obj! # features, gates_open, undo_items, cost_today, autonomy, target"}, ["Tổng hợp từ FEATURES, queue, undo, ledger chi phí, session"], [], "none", '{}', "Số liệu khớp ledger")
d("project.preferences", {"key": "str", "value": "json # giá trị JSON bất kỳ (số, chuỗi, mảng, đối tượng)", "scope": "enum:user|project", "op": "enum:get|set|delete|list", "learned_from": "str # id decision/turn (D8)", "ttl_days": "int"}, {"prefs": "obj!"}, ["get/list: đọc dự án trước, người sau", "set: ghi Preference {value, learned_from, ttl_days, at} — value là giá trị JSON, learned_from và ttl_days là trường NGANG HÀNG đúng như thực thể DDD-14 §2, không lồng trong value; delete: xóa", "scope=project → bảng `preference` trong store dự án; scope=user → preferences.yaml ở thư mục cấu hình người dùng (DDD-14 §6)", "Không lưu dữ liệu nhạy cảm (kiểm regex khóa)"], ["E1000"], "restore_config", '{"op":"set","key":"probe","value":"stlink","scope":"user","learned_from":"UC-A03"}', "Ghi rồi đọc trả đúng; delete xóa; value là chuỗi vẫn hợp lệ (DEV-009)")

# ---------- memory (chi tiết ở MEM-11 §8, CXD-10) ----------
d("memory.compose", {"role": "str!", "task_ref": "str!"}, {"bundle": "obj! # ContextBundle"}, ["CXD-10 §4.1 compose; fit_to_budget; ledger context.bundle"], ["E5001 CONTEXT_OVERFLOW"], "none", '{"role":"coder","task_ref":"F-04/step-2"}', "TC-CX-01…08")
d("memory.compress", {"text": "str!", "target_tokens": "int!", "kind": "enum:history|facts|log|code"}, {"text": "str!", "compressions": "arr<str>!"}, ["Theo kind: summarize (mô hình intent), tabulate, window_log, function_only (CXD-10 §5)"], ["E5000"], "none", '{"kind":"log","target_tokens":900,"text":"…"}', "Kết quả ≤ target; mẫu lỗi giữ nguyên")
d("memory.retrieve", {"subjects": "arr<str>!", "k": "int", "hops": "int"}, {"facts": "arr<obj>!", "snippets": "arr<obj>!"}, ["Graph-RAG 2 bước (CXD §4.5) + RagIndex.retrieve theo IRI", "Trả kèm locator và điểm"], [], "none", '{"subjects":["part:bosch.bme280"],"k":8}', "TC-CX-02")
d("memory.progress", {"entry": "str"}, {"progress_md": "str!", "features": "obj!"}, ["Sinh PROGRESS.md và FEATURES.json từ M3 (MEM-11 §5); thêm entry người nếu có"], [], "none", '{}', "Nội dung khớp ledger; không viết tay")
d("memory.ledger", {"kind": "str!", "data": "obj!"}, {"hash": "str!"}, ["Che bí mật; canonical JSON; hash chuỗi; append JSONL ngày"], ["E1000 kind lạ"], "none", '{"kind":"tool.report","data":{}}', "Chuỗi hash liên tục; regex khóa bị che")
d("memory.error_ledger", {"role": "str", "kind": "enum:hallucination|refusal|tool_fail|human_reject|undo|policy_reject!", "task_ref": "str", "evidence": "str!", "chip": "str"}, {"id": "str!", "negative_prompt": "str"}, ["Ghi ErrorLedgerEntry", "Sinh negative_prompt ≤ 40 token bằng mô hình intent với schema; TTL 30 ngày"], [], "none", '{"kind":"human_reject","role":"coder","evidence":"đặt sai bit CTRL_MEAS","chip":"bosch.bme280"}', "negative_prompt xuất hiện trong C1 của coder lần sau")
d("memory.forget", {"scope": "enum:cache|session|preference|run!", "key": "str"}, {"removed": "int!"}, ["Theo scope (MEM-11 §4.3); không chạm M4; run đang chạy → E1000"], ["E1000"], "none", '{"scope":"cache"}', "TC-MM-07")
d("memory.summarize_session", {"session_id": "str"}, {"summary": "obj! # done[], waiting[], next[], undo_until"}, ["Đọc M2/M3 phiên; tóm tắt ≤ 200 token; ghi session.summary"], [], "none", '{}', "TC-MM-02")

# ---------- archive / ingest ----------
d("archive.list", {"path": "str!", "depth": "int"}, {"entries": "arr<obj>! # path, size, compressed, kind_guess, nested"}, ["Nhận dạng định dạng theo chữ ký (zip/7z/rar/tar/gz/xz); đọc bảng mục (7z/rar qua libarchive hoặc 7z CLI trong sandbox)", "Với entry là archive lồng: liệt kê đệ quy tới depth (≤ 5) mà không giải nén toàn bộ (đọc stream)", "Đoán loại theo tên/chữ ký 512 byte đầu"], ["E4001 thiếu 7z/unrar", "E8000 tỷ lệ nén bất thường"], "none", '{"path":"robot-kit.zip","depth":3}', "Zip lồng 3 cấp liệt kê đủ; rar cần công cụ → E4001 kèm gợi ý env.install")
d("archive.unpack", {"path": "str!", "members": "arr<str>", "limits": "obj"}, {"files": "arr<str>!", "skipped": "arr<obj>!"}, ["Sandbox; chuẩn hóa đường dẫn, từ chối ../, tuyệt đối, symlink ra ngoài", "Giới hạn tổng 2 GB, độ sâu 5, tỷ lệ 100:1", "Giải nén đệ quy các archive con; trả danh sách tệp đã cách ly trong cache/unpacked/<hash>/"], ["E8000 SANDBOX_VIOLATION", "E4004"], "delete_created_files", '{"path":"robot-kit.zip"}', "TC-11, TC-SE-02")
d("archive.extract_one", {"path": "str!", "member": "str! # đường dẫn hoặc glob"}, {"file": "str!"}, ["Stream một entry ra cache; kiểm giới hạn"], ["E2000 member không có"], "delete_created_files", '{"path":"sdk.zip","member":"**/stm32f411.svd"}', "Lấy đúng tệp không giải nén phần còn lại")
d("archive.query", {"path": "str!", "pattern": "str!", "mode": "enum:name|content|signature"}, {"matches": "arr<obj>!"}, ["name: glob trên bảng mục; signature: đọc 512 byte đầu từng entry; content: grep stream (giới hạn 200 MB)"], ["E4004"], "none", '{"path":"sdk.zip","pattern":"I2C_CR1","mode":"content"}', "Tìm thấy trong header nằm trong zip con")
d("ingest.classify", {"files": "arr<str>!"}, {"classification": "arr<obj>! # file, kind, tier, extractor, confidence"}, ["Chữ ký nội dung (magic, XML root, từ khóa) trước phần mở rộng", "Bảng kind → tier/extractor (svd/atdf/edc/binding/header: gold; pdf hãng: silver; ảnh: silver-vision; readme/md: context)", "PDF: phân biệt datasheet/reference manual/errata/schematic-pdf theo tiêu đề trang 1"], [], "none", '{"files":["a.svd","ds.pdf","board.jpg"]}', "TC-01 ≥ 95% đúng trên bộ 10 tệp")
d("ingest.hash_dedupe", {"files": "arr<str>!"}, {"new": "arr<str>!", "dup": "arr<obj>!"}, ["sha256 từng tệp; so với source.sha256"], [], "none", '{"files":["ds.pdf"]}', "Tệp đã có → dup kèm source_id")
d("ingest.index_text", {"files": "arr<str>!"}, {"indexed": "int!"}, ["Chỉ tài liệu ngữ cảnh (README, ghi chú): chunk + FTS5 (view.rag_index gọi bên trong)"], [], "none", '{"files":["README.md"]}', "Truy vấn từ khóa tìm thấy")

# ---------- search ----------
d("search.registry", {"query": "str!", "kind": "enum:passport|skill|template|any"}, {"candidates": "arr<obj>! # id@ver, kind, badges, score"}, ["Tra index.json registry (cache 1 h) theo id/mpn/từ khóa; xếp theo badge + khớp"], ["E4004 registry không tới được → trả rỗng + cảnh báo"], "none", '{"query":"stm32f411","kind":"passport"}', "Seed 640 chip → tìm thấy")
d("search.vendor", {"part": "str!"}, {"candidates": "arr<obj>! # uri, kind, domain, size_est, license_hint"}, ["Nhận diện hãng từ tiền tố mã (STM32→st.com/CMSIS pack; AT/PIC→microchip; nRF→nordic; ESP→espressif; GD32→gigadevice); áp mẫu URL trong TGT-19 §bảng nguồn", "HEAD để lấy kích thước; không tải"], [], "none", '{"part":"STM32F411CE"}', "Trả link CMSIS pack và datasheet st.com")
d("search.docs_mcp", {"query": "str!", "vendor": "enum:espressif|nordic"}, {"snippets": "arr<obj>! # text, url, date, sdk_version"}, ["MCP client tới docs server hãng; giới hạn 5 đoạn; lưu Source kind=docs_mcp"], ["E4004", "E8002 nếu sensitive và query chứa nội dung dự án"], "none", '{"query":"i2c_master_transmit timeout","vendor":"espressif"}', "TC-19")
d("search.web", {"query": "str!", "kinds": "arr<enum:datasheet|svd|repo|errata|forum|schematic>", "part": "str"}, {"candidates": "arr<obj>!"}, ["Truy vấn công cụ tìm kiếm (API cấu hình) với từ khóa + mã linh kiện + kind; tối đa 20 kết quả", "Gắn domain, kind đoán, tier dự kiến; loại trang không phải tài liệu; không tải"], ["E4004"], "none", '{"query":"A4988 datasheet","kinds":["datasheet"],"part":"A4988"}', "allegromicro.com xếp trên forum")
d("search.rank", {"candidates": "arr<obj>!", "part": "str"}, {"ranked": "arr<obj>!"}, ["Điểm = tier dự kiến (gold 3, silver 2, bronze 1) + domain tin cậy (+2) + hash/signature (+2) + license rõ (+1) + khớp mã linh kiện trong tiêu đề (+2) + mới hơn (+0,5)"], [], "none", '{"candidates":[]}', "Bộ 10 ứng viên xếp đúng thứ tự vàng")
d("search.fetch", {"candidate": "obj!"}, {"source_id": "str!", "sha256": "str!", "license": "str!", "size_bytes": "int!"}, ["policy.decide(G-SRC) với đặc trưng domain/size/license/kind/hash", "Tải qua core.net vào cache/ (giới hạn ngưỡng); sha256; so expected_hash", "Nhận diện license (SEC-25 §4); tạo Source; ledger"], ["E3000 pending", "E3001", "E8001", "E4004"], "delete_created_files", '{"candidate":{"uri":"https://www.st.com/…/rm0383.pdf","domain":"st.com","kind":"pdf_vendor","size_mb":12}}', "TC-07, S01…S07")
d("search.verify_match", {"source_id": "str!", "part": "str!", "version": "str"}, {"match_score": "num!", "reasons": "arr<str>!", "doc_version": "str"}, ["Trích 3 trang đầu (extract.pdf_layout); librarian so mã linh kiện, họ, phiên bản với yêu cầu; điểm 0–1"], [], "none", '{"source_id":"src_…","part":"BME280"}', "Datasheet BMP280 cho BME280 → < 0,7")
d("search.missing", {"task_ref": "str!"}, {"requests": "arr<obj>! # subject, kind, why"}, ["Từ Plan/STEP: liệt kê subject IRI cần (ngoại vi, chân, thanh ghi, timing); tra store; thiếu → request", "Gộp theo nguồn có thể đáp ứng; kg.request cho từng mục"], [], "none", '{"task_ref":"F-04"}', "Thiếu timing I2C → 1 request đúng IRI")
d("search.reference_projects", {"idea": "str!"}, {"templates": "arr<obj>! # id@ver, bom, verified, score"}, ["Registry kind=template theo từ khóa ý tưởng (đồng nghĩa Việt–Anh: cân bằng↔balancing); sau đó web repo (chỉ ứng viên)"], [], "none", '{"idea":"robot hai bánh tự cân bằng"}', "Z-01/Z-03 trả eide.ref.balancing-robot")

# ---------- extract ----------
d("extract.svd", {"file": "str!", "include_descriptions": "bool"}, {"batch_id": "str!", "n_facts": "int!", "part": "str!"}, ["Parser SVD (derivedFrom, dim, cluster, enum) như M0; *-Community → silver", "passport.import"], ["E6001"], "supersede_facts", '{"file":"STM32F411.svd"}', "TC-09")
d("extract.atdf", {"file": "str!"}, {"batch_id": "str!", "n_facts": "int!"}, ["Parser ATDF (M0)"], ["E6001"], "supersede_facts", '{"file":"ATmega328P.atdf"}', "TC-10")
d("extract.edc", {"file": "str!"}, {"batch_id": "str!", "n_facts": "int!"}, ["Parser EDC/.PIC (XML): SFR, bit, address; gold"], ["E6001"], "supersede_facts", '{"file":"PIC16F18855.PIC"}', "50 SFR khớp datasheet")
d("extract.header_c", {"file": "str!", "part": "str"}, {"batch_id": "str!", "n_facts": "int!", "conflicts": "int!"}, ["libclang/regex: #define <NAME>_BASE, bit mask, enum; ánh xạ tên → IRI theo quy ước hãng; tier gold nếu header chính hãng", "Đối chiếu SVD nếu có → conflicts"], [], "supersede_facts", '{"file":"stm32f411xe.h"}', "Lệch cố ý 1 địa chỉ → conflict 1")
d("extract.dt_binding", {"file": "str!"}, {"batch_id": "str!"}, ["YAML binding → thuộc tính bắt buộc/enum → fact predicate other"], [], "supersede_facts", '{"file":"bosch,bme280.yaml"}', "Thuộc tính required đúng")
d("extract.pdf_layout", {"file": "str!", "pages": "str"}, {"blocks": "arr<obj>! # page, bbox, type text|table|figure|heading, content", "toc": "arr<obj>!"}, ["Docling (fallback pdfplumber) → khối có bbox; phát hiện bảng; lưu ảnh cắt bảng vào cache", "Sinh mục lục từ heading"], ["E4001 thiếu docling", "E4004"], "delete_created_files", '{"file":"bme280-ds.pdf"}', "Bảng thanh ghi nhận dạng là table với bbox")
d("extract.pdf_register_map", {"file": "str!", "blocks": "arr<obj>", "part": "str!"}, {"batch_id": "str!", "n_facts": "int!", "low_confidence": "int!"}, ["Chọn bảng có tiêu đề/cột dạng thanh ghi (Register, Address, Bit, Reset…); librarian với schema RegisterTable chuyển bảng → fact (subject IRI part/periph/reg/field, offset, bit_range, reset_value, enum)", "Locator page+bbox+ảnh cắt; confidence = điểm bảng × khớp kiểu; silver", "passport.import (merge/conflict)"], ["E5002"], "supersede_facts", '{"file":"bme280-ds.pdf","part":"bosch.bme280"}', "TC-12 ≥ 90%")
d("extract.pdf_electrical", {"file": "str!", "part": "str!"}, {"batch_id": "str!"}, ["Bảng đặc tính điện/timing/nhiệt → fact voltage_range/timing với đơn vị chuẩn hóa (V, mA, ns, kHz); luôn silver, ask (G-FACT-03)"], ["E5002"], "supersede_facts", '{"file":"a4988.pdf","part":"allegro.a4988"}', "VDD range đúng; timing có min/typ/max")
d("extract.pdf_pinout", {"file": "str!", "part": "str!"}, {"batch_id": "str!"}, ["Bảng pinout (Pin, Name, Type) hoặc hình package (vision) → pin_function; package"], [], "supersede_facts", '{"file":"stm32f411-ds.pdf","part":"st.stm32f411ce"}', "PB6 có I2C1_SCL AF4")
d("extract.pdf_errata", {"file": "str!", "part": "str!"}, {"batch_id": "str!"}, ["Mỗi mục errata → fact predicate other với điều kiện (rev, silicon), overlay K2′; liên kết CONFLICTS_WITH nếu mâu thuẫn datasheet"], [], "supersede_facts", '{"file":"stm32f411-errata.pdf","part":"st.stm32f411ce"}', "Errata I2C → fact có rev")
d("extract.pdf_formula", {"file": "str!", "section": "str!", "part": "str!"}, {"skill_path": "str!"}, ["Trích công thức/thuật toán (bù nhiệt) → skill dự án (K5) có trích dẫn trang; không thành fact"], [], "delete_created_files", '{"file":"bme280-ds.pdf","section":"4.2.3","part":"bosch.bme280"}', "skill có mã C tham chiếu và trang")
d("extract.ocr", {"file": "str!", "lang": "str"}, {"text_blocks": "arr<obj>!"}, ["Tesseract/OCR đám mây (theo cấu hình) → khối văn bản có bbox; confidence −0,1; method vision_llm|parser"], ["E4001"], "delete_created_files", '{"file":"scan.pdf"}', "Ảnh chữ → text; fact sinh sau đó có confidence giảm")
d("extract.image_schematic", {"image": "str!", "part_hint": "str"}, {"proposal_id": "str!", "nets": "arr<obj>!", "unreadable": "arr<obj>!"}, ["cartographer (vision) với schema NetProposal; bbox làm bằng chứng; đối chiếu tên chân với hộ chiếu", "Ghi fact silver method vision_llm status normalized (luôn ASK)"], ["E5002"], "supersede_facts", '{"image":"sch.jpg","part_hint":"blackpill-f411"}', "TC-22")
d("extract.image_board", {"image": "str!"}, {"parts": "arr<obj>! # label, mpn_guess, bbox, ports[]"}, ["Vision đọc nhãn chip/linh kiện/cổng; passport.list khớp mpn"], ["E5002"], "none", '{"image":"board.jpg"}', "Z-04 nhận STM32F411CEU6")
d("extract.image_scope", {"image": "str!", "kind": "enum:oscilloscope|logic|multimeter"}, {"measurement": "obj!"}, ["Vision đọc thang, giá trị; tạo Measurement kind custom, confidence thấp; không thành fact"], [], "none", '{"image":"scope.png","kind":"oscilloscope"}', "Đọc tần số ±10%")
d("extract.kicad_netlist", {"file": "str!"}, {"board_passport_id": "str!", "nets": "int!", "parts": "int!"}, ["kicad-cli sch export netlist --format kicadxml (sandbox); parse nets/parts/pins", "Ánh xạ part → hộ chiếu theo MPN/value; board.build_passport"], ["E4001 thiếu kicad-cli"], "supersede_facts", '{"file":"robot.kicad_sch"}', "TC-20 ≥ 95%")
d("extract.bom", {"sources": "arr<str>!", "kind": "enum:schematic|csv|xlsx|image|readme"}, {"bom": "arr<obj>! # ref, mpn, value, qty, footprint, source_locator", "unmatched": "arr<str>!"}, ["schematic: từ netlist parts; csv/xlsx: nhận cột (ref/MPN/value/qty) theo tên gần đúng; image: cartographer; readme: librarian trích danh sách", "Chuẩn hóa MPN (bỏ hậu tố gói), gộp trùng, đếm qty", "Gắn locator từng dòng"], ["E5002"], "supersede_facts", '{"sources":["robot.kicad_sch"],"kind":"schematic"}', "BOM 12 linh kiện đúng ref/MPN")
d("extract.bom_enrich", {"bom": "arr<obj>!"}, {"bom": "arr<obj>!", "requests": "arr<str>!"}, ["Mỗi MPN: search.registry → search.vendor → (web); gắn passport/datasheet candidate; thiếu → kg.request"], [], "none", '{"bom":[{"mpn":"A4988"}]}', "A4988 gắn datasheet Allegro")
d("extract.office", {"file": "str!"}, {"blocks": "arr<obj>!"}, ["python-docx/openpyxl/html.parser/markdown → khối văn bản/bảng có vị trí (đoạn, ô)"], [], "none", '{"file":"notes.docx"}', "Bảng trong docx thành block table")
d("extract.readme_goal", {"text": "str!"}, {"goal": "str!", "features": "arr<obj>! # title, expectation, priority_guess", "bom_hints": "arr<str>!"}, ["librarian với schema Goal; đề xuất 5–10 Feature có kỳ vọng quan sát được"], ["E5002"], "none", '{"text":"# Balancing robot …"}', "Z-07 sinh F-01…F-08")
d("extract.code_constants", {"repo": "str!", "paths": "arr<str>"}, {"code_units": "int!", "unsourced": "arr<obj>! # file, line, literal"}, ["Quét C/C++/Rust: hằng số dạng địa chỉ/bit/enum; tìm chú thích eide:fact; khớp giá trị với store → CITES; không khớp → unsourced (đề xuất code.annotate)"], [], "none", '{"repo":"."}', "UC-A05: 100 hằng số → phân loại đúng")

# ---------- passport ----------
d("passport.import", {"batch": "obj! # FactBatch", "actor": "str!"}, {"written": "int!", "merged": "int!", "conflicts": "int!", "batch_id": "str!"}, ["Kiểm schema; merge theo tier; multi-valued predicate; conflict → status conflict + cạnh; ledger store.write (M0)"], ["E6001", "E6000"], "supersede_facts", '{"batch":{"facts":[]},"actor":"extract.svd"}', "TC-13, TC-16")
d("passport.query", {"part": "str", "peripheral": "str", "register": "str", "field": "str", "q": "str # câu hỏi NL", "include_history": "bool"}, {"facts": "arr<obj>!", "citations": "arr<obj>!", "tiers": "obj!", "latency_ms": "int!"}, ["Nếu q: intent nhỏ → part/periph/reg/field; store.query; < 200 ms"], [], "none", '{"part":"st.stm32f411ce","peripheral":"I2C1","register":"CR1"}', "TC-15")
d("passport.list", {"kind": "enum:chip|board|isa|part"}, {"passports": "arr<obj>!"}, ["store.passports"], [], "none", '{}', "≥ 640 sau seed")
d("passport.diff", {"a": "str!", "b": "str!"}, {"added": "arr<obj>!", "removed": "arr<obj>!", "changed": "arr<obj>!"}, ["So fact hiện hành hai phiên bản theo subject/predicate"], ["E2000"], "none", '{"a":"st.stm32f411ce@1.1","b":"st.stm32f411ce@1.2"}', "Đổi 1 offset → changed 1")
d("passport.upgrade", {"id": "str!", "version": "str!"}, {"impact": "obj! # stale_code_units, features_to_recheck"}, ["registry.pull nếu cần; passport.diff; kg.impact cho fact đổi; ghim mới; feature liên quan → failing (cần tái kiểm)"], ["E2000"], "restore_config", '{"id":"st.stm32f411ce","version":"1.2"}', "Feature dùng fact đổi → failing")
d("passport.verify_on_board", {"id": "str!", "target": "str!"}, {"badge": "obj!", "log_hash": "str!"}, ["Sinh firmware kiểm định (BEN-21 §2) đọc ID/GPIO/UART; policy G-OPS; target.flash; target.serial expect; so với fact → badge verified_on_board"], ["E3000", "E4003"], "reflash_known_good", '{"id":"st.stm32f411ce@1.2","target":"nucleo-f411"}', "TC-18")
d("passport.export", {"id": "str!", "format": "enum:yaml|json"}, {"file": "str!"}, ["Xuất fact + Source con trỏ (không PDF)"], [], "delete_created_files", '{"id":"st.stm32f411ce@1.2","format":"yaml"}', "Tệp nạp lại được")
d("passport.resolve_address", {"address": "str!", "part": "str"}, {"subject": "str", "facts": "arr<obj>!"}, ["Tra base_address/offset trong hộ chiếu ghim; trả periph/reg gần nhất"], [], "none", '{"address":"0x40005400"}', "TC-40")

# ---------- kg ----------
d("kg.build", {"part": "str", "force": "bool"}, {"nodes": "int!", "edges": "int!", "cached": "bool!"}, ["Cache hash store; NetworkX từ store (M0)"], [], "none", '{}', "Đổi store → rebuild")
d("kg.conflicts", {"project": "str"}, {"conflicts": "arr<obj>! # type fact|resource, nodes[], detail"}, ["Fact CONFLICTS_WITH + tài nguyên bị >1 module dùng (hw_map)"], [], "none", '{}', "TC-13, TC-21")
d("kg.impact", {"fact_id": "str!"}, {"stale_code_units": "arr<str>!", "features": "arr<str>!", "docs": "arr<str>!", "diagrams": "arr<str>!"}, ["CITES ngược từ fact → code_unit → feature; requirement.trace; doc_artifact.citations; diagram.source_ref"], ["E2000"], "none", '{"fact_id":"f_1a2b"}', "TC-17")
d("kg.neighborhood", {"node": "str!", "depth": "int"}, {"subgraph": "obj!"}, ["BFS ≤ 2 bước theo loại cạnh; giới hạn 500 nút"], [], "none", '{"node":"chip:st.stm32f411ce/periph:I2C1","depth":2}', "Có PB6/PB7 và BME280")
d("kg.review_facts", {"group": "str! # batch_id|subject prefix|status", "decision": "enum:accept|reject|policy", "actor": "str!"}, {"reviewed": "int!", "asked": "int!"}, ["decision=policy: với mỗi fact chạy policy.decide(G-FACT) → APPROVE: status reviewed, confirmed_by=policy; ASK: giữ normalized, mở gate; REJECT: rejected", "decision accept/reject bởi người: cập nhật; ledger"], ["E3000"], "supersede_facts", '{"group":"batch:b_12","decision":"policy","actor":"policy"}', "S09…S17")
d("kg.resolve_conflict", {"conflict_id": "str!", "choice": "enum:a|b|both_conditional!", "condition": "str", "actor": "str!"}, {"current": "str!"}, ["Người chọn; fact thua → superseded; both: giữ hai với điều kiện (errata rev)"], ["E3000 nếu actor=policy"], "supersede_facts", '{"conflict_id":"c_3","choice":"a","actor":"cong"}', "TC-13 nhánh")
d("kg.supersede", {"old": "str!", "new": "obj!", "reason": "str!", "actor": "str!"}, {"new_id": "str!"}, ["store.supersede (M0); kg.impact; ledger"], ["E2000"], "supersede_facts", '{"old":"f_1a2b","new":{},"reason":"SVD 1.2","actor":"agent"}', "TC-16")
d("kg.request", {"need": "str!", "subject": "str", "part": "str", "peripheral": "str"}, {"request_id": "str!"}, ["Tạo AcquisitionRequest REQUESTED; Orchestrator có thể nối search.*"], [], "none", '{"need":"timing I2C fast mode","subject":"part:bosch.bme280"}', "Request xuất hiện trong queue")
d("kg.evidence", {"id": "str! # feature|fact"}, {"evidence": "arr<obj>!"}, ["EVIDENCED_BY từ feature.evidence, measurement, tool_report, badge"], [], "none", '{"id":"F-03"}', "Feature passing có ≥ 1 evidence")

# ---------- board ----------
d("board.build_passport", {"sources": "arr<str>! # netlist|bom|image ids", "name": "str"}, {"board_passport_id": "str!", "nets": "int!", "warnings": "arr<str>!"}, ["Hợp nhất nets/parts từ extract.kicad_netlist / image_schematic / bom; suy bus (I2C: SCL/SDA net → địa chỉ từ hộ chiếu part), pull-up (R trên SCL/SDA), nguồn (VDD net)", "Tạo Passport kind=board, fact predicate net/address; tier theo nguồn thấp nhất"], [], "supersede_facts", '{"sources":["src_net1","src_bom1"],"name":"robot-main"}', "TC-20; BME280 gắn 0x76 từ SDO=GND")
d("board.check_pins", {"board": "str!", "plan": "obj"}, {"conflicts": "arr<obj>! # pin, kind, detail, severity"}, ["Quy tắc: một chân hai chức năng trái nhau (AF), reserved/boot/debug (SWD, BOOT0), trùng địa chỉ bus, thiếu pull-up I2C, dòng vượt fact; xét cả HwMap dự kiến trong plan"], [], "none", '{"board":"robot-main"}', "TC-21 phát hiện PB3 LED+MOSI, PA13")
d("board.constraints", {"board": "str!"}, {"constraints": "obj! # reserved_pins, bus_limits, voltage, current"}, ["Sinh constraints.yaml phần board từ fact điện và net"], [], "restore_config", '{"board":"robot-main"}', "I2C1 limit 400 kHz theo pull-up")
d("board.propose_fix", {"conflict": "obj!"}, {"options": "arr<obj>! # change, cost, touches_code"}, ["architect: remap AF, đổi chân, đổi địa chỉ (ADDR pin), thêm điện trở; xếp theo ít thay đổi nhất; đánh dấu chạm mã passing"], [], "none", '{"conflict":{"pin":"PB3"}}', "≥ 2 phương án; phương án chạm mã passing đánh dấu ASK")
d("board.mark_lab", {"board": "str!", "no_actuator": "bool!", "current_limited": "bool!", "by": "str!"}, {"lab": "bool!"}, ["Cả hai xác nhận true và by là người → autonomy.yaml boards.<id>.lab=true, ký (POL-17 §3)"], ["E3000 nếu by=policy", "E1000 thiếu xác nhận"], "restore_config", '{"board":"nucleo-f411","no_actuator":true,"current_limited":true,"by":"cong"}', "Z-10; board có động cơ → không lab")
