# -*- coding: utf-8 -*-
"""CDS-12 dữ liệu chi tiết — phần D: tool.* (self-tooling — năng lực gốc)."""
D = {}
def d(id, inp, out, steps, err, undo, ex, tc): D[id] = dict(inp=inp, out=out, steps=steps, err=err, undo=undo, ex=ex, tc=tc)

d("tool.need", {"gap": "str! # mô tả việc không có năng lực phù hợp", "context": "obj # intent, chain node, dữ liệu vào/ra mong muốn"},
  {"spec": "obj! # ToolSpec {name, purpose, input_schema, output_schema, effects[], deps[], acceptance[]}", "reuse": "arr<obj>! # công cụ/năng lực gần khớp"},
  ["Orchestrator gọi khi: (a) planner không tìm được năng lực cho một nút (điểm khớp C0 < 0,4), (b) năng lực trả E4001/E1000 lặp lại, (c) người nói 'viết cho anh công cụ …'", "tool.search + caps.list theo từ khóa → reuse[]; nếu có khớp ≥ 0,8 → không tạo mới", "planner viết ToolSpec: mục đích một câu, input/output schema mẫu số chung, **effects** khai báo tường minh trong {read_fs, write_project, network, hardware, system, llm}, deps (thư viện pip cho phép), acceptance (≥ 2 ví dụ vào/ra)"],
  ["E5002"], "none", '{"gap":"chuyển tệp .hex Intel sang .bin và tính CRC32","context":{"node":"n7"}}', "Sinh ToolSpec có effects=[read_fs, write_project], acceptance 2 ví dụ")
d("tool.search", {"spec": "obj!", "scope": "arr<enum:project|user|registry>"}, {"tools": "arr<obj>! # tool_id, score, uses, last_ok"}, ["Tra bảng tool (M5) theo tên/mục đích (BM25 + so schema vào/ra); registry kind=tool; xếp theo điểm × tỷ lệ thành công"], [], "none", '{"spec":{"purpose":"hex → bin + crc"}}', "Công cụ đã có → điểm ≥ 0,8")
d("tool.write", {"spec": "obj!"}, {"tool_id": "str!", "code_path": "str!", "test_path": "str!", "effects": "arr<str>!"},
  ["memory.compose(coder) với C5 = ToolSpec + mẫu tool (TEMPLATE_TOOL.py) + quy ước CON-28; coder sinh module Python: hàm `run(args: dict, ctx: ToolContext) -> dict`, `SPEC` (schema), docstring, kiểm tham số bằng jsonschema, lỗi kiểu EideError, **không** import mạng/subprocess/hardware nếu effects không khai báo (kiểm tĩnh AST: danh sách import cấm theo effects)", "Sinh test pytest từ acceptance", "Lưu vào .eide/tools/<tool_id>/{tool.py, test_tool.py, spec.json}; ledger; đăng ký undo"],
  ["E5002", "E5003 (import cấm)", "E8000"], "delete_created_files", '{"spec":{"name":"hex_to_bin_crc","effects":["read_fs","write_project"]}}', "AST không có import socket/subprocess khi effects không có network/system; test sinh chạy được")
d("tool.test", {"tool_id": "str!"}, {"report": "obj! # ToolReport", "observed_effects": "arr<str>!", "effects_ok": "bool!"},
  ["Sandbox không mạng, không thiết bị, thư mục tạm; chạy pytest; giám sát: tệp ghi (fs watcher), socket (LD_PRELOAD/strace hoặc audit hook sys.addaudithook), subprocess", "observed_effects ⊆ declared → effects_ok; ngược lại → thất bại + error_ledger", "Giới hạn 60 s CPU, 512 MB"],
  ["E8000", "E4000"], "none", '{"tool_id":"user.hex_to_bin_crc"}', "TC-TL-02 công cụ gọi socket ngầm → effects_ok=false")
d("tool.run", {"tool_id": "str!", "args": "obj!", "run_id": "str"}, {"result": "obj!", "report": "obj!"},
  ["Suy lớp rủi ro từ effects: {} hoặc read_fs → R0; network → R1; write_project → R2; hardware → R3; system (sudo, cài đặt, ngoài dự án) → R4", "policy.decide(gate=G-TOOL) với đặc trưng: tested, effects, risk, uses_ok, last_fail (POL-17 TOOL-01…04)", "Chạy trong sandbox cấu hình theo effects (mở mạng chỉ khi network; gắn thiết bị chỉ khi hardware và board lab); giám sát hiệu ứng như tool.test; vi phạm → dừng, E8000, deprecate tạm", "Kết quả kiểm output_schema; ToolReport; undo theo effects (write_project → delete_created_files/git_revert)"],
  ["E3000", "E3001", "E8000", "E4000", "E5002"], "delete_created_files", '{"tool_id":"user.hex_to_bin_crc","args":{"hex":"build/fw.hex"}}', "TC-TL-03: R0 chạy ngay; hardware → pending khi board không lab")
d("tool.register", {"tool_id": "str!"}, {"capability_code": "str! # USER-nn", "capability_id": "str! # user.<name>"},
  ["Yêu cầu tool.test đạt; sinh khai báo Capability 13 trường: id user.<name>, risk theo effects, tier T1 (R0/R1) | T1* (R2/R3) | T2 (R4), grounding [tool_tested], ask_when từ effects, undo theo effects, impl .eide/tools/<id>/tool.py:run, ui none (gọi qua chat/CLI)", "Registry nạp nóng; caps.list hiện; mô tả vào C0 cho các lượt sau; ledger"],
  ["E1000 chưa test"], "restore_config", '{"tool_id":"user.hex_to_bin_crc"}', "caps.describe user.hex_to_bin_crc trả đủ 13 trường; chuỗi sau gọi được")
d("tool.repair", {"tool_id": "str!", "report_id": "str!", "round": "int!"}, {"code_path": "str!", "give_up": "bool!"}, ["coder với C6 = lỗi; giữ SPEC/effects không đổi (đổi effects → về tool.need); tool.test lại; ≤ 3 vòng; error_ledger"], ["E5003"], "delete_created_files", '{"tool_id":"user.hex_to_bin_crc","report_id":"tr_7","round":1}', "Lỗi biên → sửa 1 vòng")
d("tool.promote", {"tool_id": "str!", "target_ns": "str!"}, {"proposal": "obj! # PR/pack, bench"},
  ["Điều kiện: uses ≥ 3 thành công, 0 vi phạm hiệu ứng, có test; bench.run mini (acceptance × 3 lần); sinh PR vào eide-packs/tools hoặc gói .hkp kind=tool; Pack owner duyệt (T2); sau duyệt: đổi id user.* → <ns>.*, cập nhật Danh mục (caps.py) và CDS"],
  ["E3000"], "none", '{"tool_id":"user.hex_to_bin_crc","target_ns":"code"}', "Đề xuất không tự áp dụng; sau duyệt registry có năng lực mới")
d("tool.compose", {"tool_ids": "arr<str>!", "wiring": "obj! # map output→input", "name": "str!"}, {"tool_id": "str!"},
  ["Kiểm schema khớp giữa các bước; effects = hợp; sinh tool.py gọi ctx.invoke từng bước (không nhúng mã); test từ acceptance của các thành phần"], ["E1000 schema không khớp"], "delete_created_files", '{"tool_ids":["user.hex_to_bin_crc","target.flash"],"wiring":{},"name":"build_and_flash_bin"}', "Effects gồm hardware → risk R3")
d("tool.deprecate", {"tool_id": "str!", "reason": "str!", "replaced_by": "str"}, {"ok": "bool!"}, ["Đánh dấu deprecated; registry ẩn khỏi C0; chuỗi cũ gọi → gợi ý replaced_by; giữ mã và lịch sử"], [], "restore_config", '{"tool_id":"user.old_tool","reason":"thay bằng code.size"}', "Không còn trong caps.list mặc định")
