# -*- coding: utf-8 -*-
"""CDS-12 dữ liệu chi tiết — phần C: req, arch, diagram, doc, view, discover."""
D = {}
def d(id, inp, out, steps, err, undo, ex, tc): D[id] = dict(inp=inp, out=out, steps=steps, err=err, undo=undo, ex=ex, tc=tc)

# ---------- req ----------
d("req.elicit", {"text": "str", "sources": "arr<str> # README, tài liệu, ảnh, chat ids", "feature": "str"}, {"raw": "arr<obj>! # text, source, locator, kind_guess", "gaps": "arr<obj>!"}, ["Gom câu yêu cầu từ lệnh, README (extract.readme_goal), tài liệu (extract.office/pdf_layout: mục 'Requirements', 'Specification'), ảnh (cartographer), chat (M2)", "architect với schema RawRequirements: tách mỗi câu một yêu cầu, giữ locator; nêu gaps (mơ hồ, thiếu số)", "gaps → chat.clarify một câu gộp (D3)"], ["E5002"], "none", '{"sources":["README.md"],"text":"robot cân bằng, pin 12 V, chạy 30 phút"}', "README robot → ≥ 15 yêu cầu thô có locator")
d("req.classify", {"raw": "arr<obj>!"}, {"reqset": "arr<obj>! # Requirement", "codes_assigned": "int!"}, ["architect: kind FR/NFR/HW/SAFETY/RT; câu đo được (đơn vị, ngưỡng); gán mã UR-<nhóm>-nn / FR-<nhóm>-nn theo bảng nhóm (SNS cảm biến, CTL điều khiển, COM giao tiếp, PWR nguồn, SAF an toàn, UI…)", "Ghi bảng requirement status generated"], ["E5002"], "restore_config", '{"raw":[]}', "Mỗi yêu cầu có mã duy nhất, kind đúng ≥ 90%")
d("req.ground_hw", {"reqset_ids": "arr<str>!", "passport": "str!"}, {"report": "arr<obj>! # req_id, ok, facts[], note, alternative"}, ["Với mỗi HW/RT: trích số liệu cần (tần số, RAM, Flash, số kênh ADC, tốc độ bus, dòng GPIO) → passport.query; so ngưỡng; ghi fact id; không có fact → 'chưa xác định' + kg.request", "Không khả thi → đề xuất thay thế (chip khác trong registry, giảm yêu cầu)"], [], "none", '{"reqset_ids":["FR-SNS-01"],"passport":"st.stm32f411ce@1.2"}', "TC-67 ADC 1 MSPS vs fact 2,4 MSPS → ok; yêu cầu 5 MSPS → không ok có fact id")
# [DEV-151] NGƯỜI trả lời một điểm cần làm rõ — vế còn lại của việc "người và tác tử cùng làm".
# Tác tử tìm ra điểm mờ và chỗ mâu thuẫn; tới đây chưa có đường nào cho người trả lời chúng, nên
# bảng ở tab "Làm rõ yêu cầu" là bảng chỉ đọc và cuộc cộng tác dừng một chiều.
# `undo: restore_answer` — lịch sử nằm ở `clarification_answer`, chỉ thêm, nên hoàn tác được
# TỪNG LẦN chứ không chỉ lần cuối.
d("req.answer_clarification", {"clar_id": "str!", "answer": "str!"}, {"clar_id": "str!", "status": "str!", "answer": "str!", "revision": "int!"}, ["Ghi một dòng vào clarification_answer (chỉ thêm); cập nhật clarification.answer/status/answered_by/answered_at", "actor human:<tên> — đây là việc của NGƯỜI, không phải của tác tử"], ["E2000"], "restore_answer", '{"clar_id":"CL-a1b2c3d4e5","answer":"file lớn nhất 8 MB"}', "Trả lời rồi hoàn tác thì câu trả lời TRƯỚC đó quay lại, không phải rỗng")
d("req.detect_conflict", {"reqset_ids": "arr<str>!"}, {"issues": "arr<obj>! # kind conflict|ambiguous|unmeasurable, req_ids[], text, suggestion"}, ["Quy tắc deterministic: cùng đại lượng ngưỡng trái nhau; thiếu đơn vị/số; từ mơ hồ (nhanh, đủ, tốt)", "architect đề xuất câu chữ đo được; mâu thuẫn không tự giải → chat.clarify"], [], "none", '{"reqset_ids":["FR-PWR-01","FR-PWR-02"]}', "TC-68")
d("req.prioritize", {"reqset_ids": "arr<str>!", "goal": "str"}, {"reqset": "arr<obj>!"}, ["MoSCoW theo: an toàn (M), mục tiêu dự án, phụ thuộc, rủi ro phần cứng; T1*: đổi M↔S → ASK"], ["E3000"], "restore_config", '{"reqset_ids":["FR-SNS-01"],"goal":"cân bằng"}', "SAFETY luôn M")
d("req.trace_matrix", {"format": "enum:xlsx|md"}, {"file": "str!", "gaps": "arr<obj>!"}, ["Nối requirement.trace ↔ module ↔ code_unit ↔ tc ↔ doc; phát hiện yêu cầu không có module/test; xuất"], [], "delete_created_files", '{"format":"xlsx"}', "TC-68 lỗ hổng liệt kê")
d("req.acceptance", {"reqset_ids": "arr<str>!"}, {"acceptance": "arr<obj>! # req_id, given, when, then, observable kind"}, ["architect: Given–When–Then với kỳ vọng máy quan sát được khi có thể (serial/probe/measure); ghi requirement.acceptance; nối plan.define_feature"], ["E5002"], "restore_config", '{"reqset_ids":["FR-SNS-01"]}', "Mỗi yêu cầu ≥ 1 AC; AC có kind quan sát")
d("req.change_impact", {"delta": "obj! # req_id, old, new | fact_id"}, {"impact": "obj! # modules[], code_units[], tests[], docs[], diagrams[], features[]"}, ["kg.impact + requirement.trace + doc/diagram source_ref; đánh dấu stale; > ngưỡng (≥ 3 module) → ASK"], [], "none", '{"delta":{"req_id":"FR-SNS-01","new":"…"}}', "Đổi yêu cầu → module/test/tài liệu liên quan stale")

# ---------- arch ----------
d("arch.style_select", {"reqset_ids": "arr<str>!", "passport": "str"}, {"decision": "obj! # style, reasons[], facts[], alternatives[]"}, ["Quy tắc tiền kiểm (deterministic): RAM < 4 KB → không RTOS; ≥ 3 tác vụ chu kỳ khác nhau + deadline < 10 ms → ưu tiên event_driven/rtos; ≥ 2 giao tiếp chặn → rtos; còn lại super_loop/layered", "architect viết lý do có fact; T1*: dự án đã có kiến trúc → ASK"], ["E3000", "E5002"], "restore_config", '{"reqset_ids":[],"passport":"st.stm32f411ce@1.2"}', "TC-69 robot → rtos hoặc event_driven có lý do")
d("arch.decompose", {"reqset_ids": "arr<str>!", "style": "str!"}, {"module_graph": "obj! # modules[], edges[]"}, ["architect: module theo lớp (hal → driver → service → control → app), trách nhiệm, giao diện, phụ thuộc không chu trình; mỗi FR ánh xạ ≥ 1 module (trace)"], ["E5002"], "restore_config", '{"reqset_ids":[],"style":"rtos"}', "Không chu trình; mọi FR có module")
d("arch.map_hw", {"module_ids": "arr<str>!", "passport": "str!", "board": "str"}, {"hw_map": "arr<obj>!", "conflicts": "arr<obj>!"}, ["Với module cần phần cứng: chọn ngoại vi/chân từ hộ chiếu + BoardPassport (net đã nối), ngắt, DMA, timer; board.check_pins với HwMap dự kiến; xung đột không tự giải → ASK kèm board.propose_fix"], ["E3000"], "restore_config", '{"module_ids":["mod_imu"],"passport":"st.stm32f411ce@1.2","board":"robot-main"}', "TC-69 xung đột = 0")
d("arch.memory_budget", {"module_ids": "arr<str>!", "passport": "str!"}, {"budget": "obj! # per module ram/flash/stack, total, limits, ok"}, ["Ước lượng theo bảng tham chiếu (driver I2C ~1–2 KB flash, 64 B ram; RTOS kernel theo fact/skill) + lịch sử code.size các dự án; so memory_size fact; vượt → cảnh báo/ASK"], [], "none", '{"module_ids":[],"passport":"st.stm32f411ce@1.2"}', "Tổng ≤ 85% Flash")
d("arch.timing_budget", {"module_ids": "arr<str>!"}, {"budget": "obj! # tasks[] {period, wcet_est, prio}, utilization, schedulable"}, ["Chu kỳ từ RT requirement; WCET ước lượng theo số lệnh × tần số fact (clock) + lịch sử đo (measure/probe timestamp); RMS: U ≤ n(2^(1/n)−1) → schedulable; ưu tiên ngắt theo deadline"], [], "none", '{"module_ids":["mod_pid","mod_imu"]}', "U tính đúng; không schedulable → cảnh báo")
d("arch.interface_spec", {"module_ids": "arr<str>!"}, {"interfaces": "arr<obj>! # module, functions[] {sig, errors[], timing}, messages[]"}, ["architect: chữ ký C, mã lỗi, ràng buộc gọi (ISR-safe?), message/queue cho RTOS; ghi module.interfaces"], ["E5002"], "restore_config", '{"module_ids":["mod_bme280"]}', "Chữ ký biên dịch được (kiểm bằng header stub)")
d("arch.state_machine", {"module_id": "str!"}, {"fsm": "obj! # states[], events[], transitions[], initial, invariants[]"}, ["architect sinh FSM; kiểm deterministic: mọi (state, event) có chuyển hoặc bỏ qua rõ ràng; không trạng thái không tới được; lưu module.fsm"], ["E5002"], "restore_config", '{"module_id":"mod_motor"}', "FSM đầy đủ; diagram.state vẽ được")
d("arch.adr", {"decision": "obj! # title, context, options[], choice, consequences"}, {"adr_id": "str!", "path": "str!"}, ["architect hoàn thiện theo mẫu (ADR §)); citations bắt buộc; ghi bảng adr + .eide/docs/adr/ADR-nn.md"], ["E5002"], "delete_created_files", '{"decision":{"title":"Dùng RTOS","options":[{"name":"super_loop"},{"name":"rtos"}],"choice":"rtos"}}', "ADR có ≥ 1 phương án bị loại và citations")
d("arch.review", {"module_ids": "arr<str>!"}, {"findings": "arr<obj>! # severity, module, rule, message"}, ["Checklist nhúng deterministic + architect: coupling (phụ thuộc chéo), ISR dài (hàm gọi từ ISR có vòng lặp/chờ), tài nguyên chia sẻ không khóa, watchdog, xử lý lỗi bus, khởi tạo thứ tự clock, stack ước lượng"], [], "none", '{"module_ids":[]}', "TC-70 ISR dài → finding")
d("arch.compare", {"options": "arr<obj>! # {name, module_graph|style}", "criteria": "arr<obj> # {name, weight}"}, {"comparison": "obj! # matrix, scores, recommendation"}, ["Tiêu chí mặc định: RAM, Flash, thời gian thực, độ phức tạp, khả năng mở rộng, rủi ro; điểm 1–5 có lý do; T1*: chọn phương án cuối → ASK"], ["E3000"], "none", '{"options":[{"name":"A"},{"name":"B"}]}', "TC-70 bảng có trọng số")
d("arch.to_plan", {"module_ids": "arr<str>!"}, {"features": "arr<str>!", "order": "arr<str>!"}, ["plan.decompose + plan.order từ ModuleGraph; mỗi module → Feature với AC từ req.acceptance"], [], "restore_config", '{"module_ids":[]}', "FEATURES.json có đủ module")

# ---------- diagram ----------
d("diagram.render", {"src": "str!", "lang": "enum:mermaid|plantuml|dot|d2|wavedrom|svg!", "fmt": "enum:svg|png"}, {"path": "str!", "lint": "arr<obj>!"}, ["diagram.lint trước; bộ render trong sandbox (mmdc, plantuml.jar, dot, d2, wavedrom-cli; svg: sao chép); GEditor render trực tiếp src khi mở panel"], ["E4001 thiếu renderer → env.install", "E4000 cú pháp"], "delete_created_files", '{"src":"graph TD; A-->B","lang":"mermaid","fmt":"svg"}', "TC-71 sáu ngôn ngữ")
d("diagram.block", {"board": "str!", "bom": "arr<obj>"}, {"diagram": "obj!"}, ["Nút = linh kiện chính (MCU, cảm biến, driver, nguồn) từ BOM/BoardPassport; cạnh = bus/net (I2C, SPI, PWM, nguồn) với nhãn địa chỉ/tốc độ từ fact; Mermaid flowchart LR (mặc định) hoặc DOT; node_ids = MPN/ref"], [], "delete_created_files", '{"board":"robot-main"}', "TC-72 nút/cạnh khớp BOM/net")
d("diagram.pinmap", {"board": "str", "module_ids": "arr<str>"}, {"diagram": "obj!", "table": "arr<obj>!"}, ["Từ HwMap + BoardPassport: bảng chân (MCU pin, AF, net, linh kiện, hướng); SVG chip outline (package từ fact) với nhãn chân; xung đột tô đỏ"], [], "delete_created_files", '{"board":"robot-main"}', "PB6→SCL BME280 đúng")
d("diagram.architecture", {"module_ids": "arr<str>", "level": "enum:context|container|component", "lang": "enum:mermaid|plantuml|d2"}, {"diagram": "obj!"}, ["C4 [36]: context (hệ thống/board/người), container (firmware lớp), component (module + phụ thuộc + luồng dữ liệu); node_ids = module id để sync"], [], "delete_created_files", '{"level":"component","lang":"mermaid"}', "TC-72")
d("diagram.sequence", {"scenario": "str! # UC id | feature | mô tả", "lang": "enum:mermaid|plantuml"}, {"diagram": "obj!"}, ["Từ Plan/FSM/kịch bản sim: participant = module/ISR/ngoại vi; thông điệp = gọi hàm/giao dịch bus (với địa chỉ fact); writer sinh; lint"], ["E5002"], "delete_created_files", '{"scenario":"F-04","lang":"mermaid"}', "Participant khớp module")
d("diagram.state", {"module_id": "str!", "lang": "enum:mermaid|plantuml"}, {"diagram": "obj!"}, ["Từ module.fsm → stateDiagram-v2/PlantUML; node_ids = state ids; nối diagram.sync với mã FSM"], [], "delete_created_files", '{"module_id":"mod_motor","lang":"mermaid"}', "TC-73")
d("diagram.flow", {"source": "str! # đường dẫn hàm C | mô tả", "lang": "enum:mermaid|dot"}, {"diagram": "obj!"}, ["Từ mã: CFG đơn giản (if/loop/return) bằng tree-sitter; từ mô tả: writer"], ["E5002"], "delete_created_files", '{"source":"src/control/pid.c:pid_step","lang":"mermaid"}', "Nhánh if/else đủ")
d("diagram.timing", {"source": "str! # fact ids timing | dataset_id"}, {"diagram": "obj! # WaveDrom JSON"}, ["Từ fact timing (tsu, th, tCLK) → WaveDrom signal + edge với nhãn giá trị; từ capture LA → chuyển mẫu"], [], "delete_created_files", '{"source":"ds_1"}', "WaveDrom hợp lệ")
d("diagram.memory_map", {"passport": "str!", "linker": "str"}, {"diagram": "obj! # svg"}, ["Bản đồ bộ nhớ từ fact memory_size/base_address; vùng linker (.text/.data/.bss) từ .map (code.size); SVG có tỷ lệ"], [], "delete_created_files", '{"passport":"st.stm32f411ce@1.2","linker":"build/fw.map"}', "Vùng đúng địa chỉ")
d("diagram.kg_view", {"query": "obj! # node, depth, filter"}, {"diagram": "obj! # DOT"}, ["kg.neighborhood → DOT với màu theo tier/status; giới hạn 300 nút"], [], "delete_created_files", '{"query":{"node":"part:bosch.bme280","depth":2}}', "Render được; màu đúng")
d("diagram.gantt", {"plan_id": "str"}, {"diagram": "obj!"}, ["Từ Plan/FEATURES + ước lượng → Mermaid gantt; cập nhật theo trạng thái"], [], "delete_created_files", '{}', "Feature passing đánh dấu done")
d("diagram.from_image", {"image": "str!", "target_lang": "enum:mermaid|dot"}, {"diagram": "obj!", "confidence": "num!"}, ["cartographer (vision) với schema Graph {nodes, edges}; sinh mã; confidence thấp → status chờ duyệt"], ["E5002"], "delete_created_files", '{"image":"whiteboard.jpg","target_lang":"mermaid"}', "TC-74")
d("diagram.lint", {"src": "str!", "lang": "str!", "model_ref": "str"}, {"issues": "arr<obj>! # severity, line, message"}, ["Cú pháp (parser nhẹ/renderer --check); nút mồ côi; tên nút không có trong mô hình tham chiếu (module/state/MPN); kích thước (> 300 nút)"], [], "none", '{"src":"…","lang":"mermaid","model_ref":"mod_graph"}', "Nút không có trong ModuleGraph → issue")
d("diagram.sync", {"diagram_id": "str!", "direction": "enum:to_code|from_code|check"}, {"diff": "obj!", "applied": "bool!"}, ["FSM: so states/transitions của lược đồ với bảng chuyển trong mã (macro/enum + switch) — tree-sitter; architecture: so với ModuleGraph; check → diff; to_code/from_code: sinh patch (qua code.modify / cập nhật src); lệch lớn (> 30%) → ASK"], ["E3000"], "git_revert", '{"diagram_id":"dg_1","direction":"check"}', "TC-73")

# ---------- doc ----------
d("doc.generate", {"type": "enum:URD|SRS|SAD|SDD|STP|BPD|bringup|test_report|custom!", "scope": "str", "lang": "enum:vi|en"}, {"doc_id": "str!", "path": "str!", "style_issues": "int!"}, ["Mục lục chuẩn theo type, đọc từ `doc/outlines.json` (rút từ chính bộ hồ sơ EAA/EIDE, DEV-070); mỗi mục có MỘT nguồn tri thức (ReqSet, ModuleGraph, HwMap, ADR, fact, ToolReport, CodeUnit): bảng số liệu kèm trích dẫn dựng bằng MÃ, writer chỉ viết văn xuôi quanh bảng và không được nhắc lại con số nào; mục không có dữ liệu thì ghi rõ là chưa có kèm năng lực cần chạy, KHÔNG gọi mô hình; mục bắt buộc thiếu → E3000 (ask_when)", "Sinh Markdown có bảng thuộc tính, lịch sử sửa đổi, hình đánh số (doc.embed_diagram) và mục Nguồn; doc.style_check; lưu DocArtifact. Chuyển sang docx/pdf là việc của report.export — dựng docx ở cả hai chỗ là hai bản dựng cùng một tài liệu (DEV-070)"], ["E5002", "E3000 thiếu fact bắt buộc"], "delete_created_files", '{"type":"SRS","lang":"vi"}', "TC-75")
d("doc.section", {"target": "str! # doc_id#heading | module | topic", "style": "str", "instructions": "str"}, {"markdown": "str!", "citations": "arr<str>!"}, ["writer với C5 = tri thức mục; style_check mục"], ["E5002"], "none", '{"target":"mod_bme280","style":"hướng dẫn cấu hình"}', "Có citations")
d("doc.api_ref", {"src": "arr<str>!"}, {"path": "str!"}, ["Bộ đọc chữ ký họ C viết trong doc.py là đường mặc định (Doxygen/tree-sitter khi có, cho ngôn ngữ khác — thiếu thì E4001) → chữ ký + chú thích; writer thêm ví dụ dùng theo hộ chiếu (fact id); md. Chuyển sang định dạng khác là việc của report.export (DEV-072)"], ["E4001"], "delete_created_files", '{"src":["src/drivers/bme280.h"]}', "Mọi hàm public có mục")
d("doc.datasheet_summary", {"part": "str!", "scope": "arr<str> # periph|electrical|timing|errata"}, {"path": "str!"}, ["Từ fact + locator: tóm tắt theo scope, mỗi câu có [src#page]; không nêu số không có fact"], ["E5002"], "delete_created_files", '{"part":"bosch.bme280","scope":["periph","timing"]}', "Mọi số liệu có trang")
d("doc.bringup_guide", {"board": "str!"}, {"path": "str!"}, ["Từ BoardPassport, target.yaml, discovery, ToolReport flash/serial đầu tiên: nguồn, kết nối probe, nạp, kiểm ID, UART, lỗi thường gặp (từ sổ lỗi)"], [], "delete_created_files", '{"board":"robot-main"}', "TC-77")
d("doc.test_report", {"results": "arr<str>! # tool_report/measurement ids", "format": "enum:md"}, {"path": "str!"}, ["Bảng TC ↔ kết quả ↔ bằng chứng (hash); tóm tắt; mục Nguồn; chuyển sang docx/pdf qua report.export — đó là chỗ DUY NHẤT dựng docx/pdf (DEV-070, DEV-073)"], [], "delete_created_files", '{"results":["tr_1","m_2"],"format":"md"}', "Mỗi kết quả có bằng chứng")
d("doc.embed_diagram", {"doc_id": "str!", "diagram_id": "str!", "caption": "str!", "after_heading": "str"}, {"figure_no": "int!"}, ["diagram.render svg/png; chèn với 'Hình n.', số thứ tự đọc từ CHÍNH tài liệu chứ không từ một bộ đếm trong store — \"đánh số liên tục\" là tính chất của tài liệu nên phải kiểm được trên tài liệu, và bộ đếm ngoài sẽ lệch ngay khi ai đó sửa tay hay sinh lại (DEV-071); thiếu bộ dựng → chèn mã lược đồ (CON-28 §6: lược đồ là văn bản, ảnh là sản phẩm phụ) chứ không bỏ hình; lược đồ stale → nhãn"], [], "restore_config", '{"doc_id":"doc_1","diagram_id":"dg_1","caption":"Kiến trúc firmware"}', "Đánh số liên tục")
d("doc.style_check", {"doc_id": "str!"}, {"issues": "arr<obj>! # kind lang|term|uncited|format|glossary, location, text"}, ["Quy tắc: tỷ lệ từ tiếng Anh ngoài định danh > 10%/đoạn → lang; thuật ngữ trong glossary CON-28 xuất hiện lần đầu không kèm giải nghĩa → term; câu có số liệu kỹ thuật không có [cite] → uncited; thiếu bảng thuộc tính/lịch sử/mục Nguồn/đánh số hình → format"], [], "none", '{"doc_id":"doc_1"}', "TC-76")
d("doc.translate", {"doc_id": "str!", "lang": "enum:vi|en!"}, {"path": "str!"}, ["writer dịch theo mục giữ bảng/hình/citations; glossary song ngữ; style_check bản đích"], ["E5002"], "delete_created_files", '{"doc_id":"doc_1","lang":"en"}', "Số hình/bảng bằng nhau")
d("doc.changelog", {"range": "str! # tag..tag | since date"}, {"markdown": "str!"}, ["git log + ledger (merge, supersede, badge) → nhóm feat/fix/knowledge; liên kết run_id"], [], "none", '{"range":"v0.1..HEAD"}', "TC-77")
d("doc.slides", {"scope": "str!", "n_slides": "int"}, {"path": "str!"}, ["Từ tài liệu + lược đồ: dàn ý → pptx (mẫu PTIT); mỗi slide có nguồn ở chú thích"], ["E4001"], "delete_created_files", '{"scope":"project","n_slides":15}', "pptx mở được")
d("doc.sync", {"delta": "obj! # fact_id|module_id|req_id"}, {"stale": "arr<obj>!", "updated": "arr<str>!"}, ["Tìm mục có citations/source_ref liên quan → stale; T1*: tự cập nhật mục nhỏ (số liệu) và ghi lịch sử; thay đổi lớn → ASK"], ["E3000"], "git_revert", '{"delta":{"fact_id":"f_9e0f"}}', "TC-77 mục liên quan stale")

# ---------- view ----------
d("view.kg_map", {"project": "str", "filter": "obj # tier[], status[], kinds[], layer[]"}, {"graph": "obj! # nodes[] {id, kind, label, tier, status, layer}, edges[]"}, ["kg.build; lọc; tô màu theo tier (vàng/bạc/đồng), status (conflict đỏ, superseded xám), layer; giới hạn 50.000 nút với gom cụm theo periph khi > 5.000"], [], "none", '{"filter":{"status":["conflict"]}}', "TC-78 < 3 s")
d("view.kg_focus", {"node": "str!", "depth": "int"}, {"graph": "obj!", "paths_to_sources": "arr<arr<str>>!"}, ["kg.neighborhood + đường CITES tới Source + USES tới code_unit"], [], "none", '{"node":"chip:st.stm32f411ce/periph:I2C1/reg:CR1","depth":2}', "Có đường tới SVD và bme280.c")
d("view.provenance", {"fact_id": "str!"}, {"chain": "arr<obj>! # source, locator, snippet, method, confirmed_by, supersedes chain"}, ["Đi CITES → Source; locator → mở PDF trang/bbox (ảnh cắt từ cache); lịch sử supersede"], ["E2000"], "none", '{"fact_id":"f_9e0f"}', "Nhấp → mở đúng trang")
d("view.conflict_board", {"project": "str"}, {"rows": "arr<obj>! # conflict_id, subject, a, b, tiers, sources, actions[]"}, ["kg.conflicts + queue ASK G-FACT; hành động gọi kg.resolve_conflict/review_facts"], [], "none", '{}', "Duyệt trên bảng cập nhật store")
d("view.coverage_map", {"passport": "str!"}, {"heatmap": "obj! # periph → {registers_total, with_facts, reviewed, requested}"}, ["Cấu trúc hộ chiếu (ngoại vi/thanh ghi/chân) vs fact hiện có vs AcquisitionRequest"], [], "none", '{"passport":"st.stm32f411ce@1.2"}', "TC-78 số khớp store")
d("view.impact_map", {"delta": "obj!"}, {"graph": "obj!"}, ["req.change_impact/kg.impact → đồ thị con tô màu stale"], [], "none", '{"delta":{"fact_id":"f_9e0f"}}', "Khớp kg.impact")
d("view.rag_ask", {"question": "str!", "scope": "arr<str> # source ids | kinds", "k": "int"}, {"answer": "str!", "citations": "arr<obj>! # source_id, locator, snippet", "trace_id": "str!", "not_found": "bool!"}, ["RagIndex.retrieve lai (từ khóa FTS5 + vector + lan tỏa KG 2 bước), k=8; writer trả lời chỉ từ chunk; mọi câu có [n]; không có chunk đủ điểm (< 0,35) → not_found và chat.decline"], ["E5002"], "none", '{"question":"BME280 địa chỉ I2C mặc định?"}', "TC-79 ≥ 90%, 100% citations")
# [DEV-215] VIEW-15 — đường trả lời cho câu hỏi mà kho dự án chưa có nguồn.
#
# KAD-07 N5 đã định sẵn chỗ này: "Điều mô hình nhớ là loại tri thức riêng (K9) ở tầng đồng,
# CHỈ DÙNG ĐỂ ĐỀ XUẤT, không bao giờ vào mã". Tức nguyên tắc cho phép từ đầu; thiếu là đường
# hiện thực. Tách khỏi `view.rag_ask` chứ không gộp: cái kia đòi 100% trích dẫn và chính ràng
# buộc ấy là lý do sản phẩm không bao giờ bịa — nhét một nhánh không nguồn vào đó là phá nó.
#
# `tu_choi` là trường QUAN TRỌNG NHẤT: năng lực này phải TỰ IM khi dự án đã có nguồn khớp câu
# hỏi. Không có nó thì K9 nói xen vào sau một câu "thứ này không có trong tài liệu" và người
# dùng nhận đúng thứ ảo giác mà câu kia vừa tránh được.
d("view.k9_ask", {"question": "str!", "context": "str # ngữ cảnh thêm, ví dụ đoạn log người dán"}, {"answer": "str!", "tier": "str! # luôn là `bronze` — K9 tầng đồng", "caveat": "str! # câu cảnh báo hiện cho người đọc", "declined": "bool! # true = dự án ĐÃ có nguồn, hãy dùng view.rag_ask"}, ["Tra chỉ mục RAG trước: có đoạn nào trên ngưỡng thì TỪ CHỐI trả lời (declined=true) và chỉ sang `view.rag_ask`", "Chưa có nguồn thì hỏi mô hình, gắn nhãn tầng đồng và câu cảnh báo 'chưa đối chiếu tài liệu của anh'", "KHÔNG ghi fact, KHÔNG trả trích dẫn giả — KAD-07 N5"], ["E5000"], "none", '{"question":"Pin 2000 mAh, tiêu thụ 8 mA, dùng được bao lâu?"}', "TC-K9 câu hỏi không có nguồn → trả lời có nhãn đồng; dự án có nguồn → declined")
d("view.rag_trace", {"trace_id": "str!"}, {"chunks": "arr<obj>!", "scores": "obj!", "graph_path": "arr<str>!"}, ["Trả chunk, điểm từng thành phần (bm25, vector, graph), đường lan tỏa"], ["E2000"], "none", '{"trace_id":"tr_a1"}', "Hiển thị đủ 3 điểm")
d("view.rag_index", {"sources": "arr<str>", "rebuild": "bool"}, {"chunks": "int!", "status": "obj!"}, ["Chunk ≤ 800 token theo bố cục (Docling block/OCR/mã theo hàm); embedding qua Gateway (embedding model trong models.yaml, batch 64); FTS5; gắn IRI xuất hiện; incremental theo source.sha256"], ["E5000"], "delete_created_files", '{"rebuild":false}', "TC-DD-05 tái dựng")
d("view.rag_compare", {"question": "str!"}, {"comparison": "arr<obj>! # tier/source → answer, citations; differences[]"}, ["Chạy rag_ask theo từng nhóm nguồn (datasheet, errata, cộng đồng); writer nêu khác biệt có trích dẫn"], [], "none", '{"question":"I2C fast mode tối đa?"}', "Chỉ ra errata khác datasheet")
d("view.doc_side_by_side", {"ref": "str! # fact_id | code_unit_id"}, {"left": "obj! # source, page, bbox", "right": "obj! # fact/code"}, ["Từ locator → trang PDF/ảnh với highlight; mã với dòng"], ["E2000"], "none", '{"ref":"f_9e0f"}', "Vùng bôi sáng đúng bbox")
d("view.timeline", {"range": "obj # from|to ISO, hoặc days:int", "filter": "obj # by policy|human, kinds", "limit": "int # số sự kiện MỚI NHẤT trả về"}, {"events": "arr<obj>!", "total": "int! # tổng trước khi cắt"}, ["Từ ledger/decision_log/capability_run/store.write; sắp theo thời gian; lọc", "`limit` cắt từ ĐUÔI (mới nhất) và `total` luôn là số trước khi cắt — bên gọi phải biết mình đang xem một phần"], [], "none", '{"range":{"days":7},"limit":120}', "Sự kiện khớp ledger")
d("view.export_map", {"view": "obj!", "format": "enum:dot|graphml|svg|png|mermaid!"}, {"file": "str!"}, ["Chuyển GraphView → định dạng; mermaid giới hạn 300 nút"], [], "delete_created_files", '{"view":{},"format":"mermaid"}', "Mermaid render được")
d("view.artifacts",
  {"kind": "enum:requirement|adr|plan|doc|diagram|module|board|feature|tool|clarification!", "filter": "obj # trường → giá trị, khớp bằng", "limit": "int"},
  {"items": "arr<obj>! # id + các trường chính của loại ấy, kèm at nếu có", "total": "int! # số trước khi cắt", "kind": "str!"},
  ["Đọc THẲNG bảng tương ứng trong store; không gọi mô hình, không ghi gì",
   "Mỗi loại trả các trường chính của nó, KHÔNG trả cả hàng: một bảng có cột nội dung dài (doc.body, diagram.src) sẽ kéo vài MB qua ống RPC cho một danh sách",
   "Sắp mới nhất trước; `limit` cắt từ ĐẦU danh sách đã sắp, `total` luôn là số trước khi cắt",
   "v1.3 — `kind: clarification` ([DEV-151]): các ĐIỂM CẦN LÀM RÕ mà `req.elicit` và `req.detect_conflict` tìm ra. Sắp theo `status` trước rồi thời gian — cái đang `open` phải nổi lên trên cái đã trả lời, vì tab S9 tồn tại để người thấy thứ CÒN PHẢI LÀM",
   "v1.3 — `kind: tool` (DEV-136): gộp `tool_report` theo `tool`, trả tên công cụ + số lượt ĐẠT/TỔNG + lần chạy gần nhất. `tool.search` (TOOL-02) KHÔNG dùng được cho việc này: nó là năng lực KHỚP chứ không phải LIỆT KÊ — gọi nó với một ToolSpec bịa ra để lấy danh sách là dùng sai hợp đồng, và điểm tương tự trả về sẽ vô nghĩa"],
  ["E1000 kind ngoài enum", "E2000 store chưa có"], "none",
  '{"kind":"adr"}',
  "Nhập 2 yêu cầu → kind=requirement trả 2 mục; kind lạ → E1000; dự án trống → items rỗng, total 0")

# ---------- discover ----------
d("discover.ports", {}, {"ports": "arr<obj>! # dev, vid, pid, product, serial, kind, driver_ok"}, ["pyserial list_ports + libusb (pyusb) → VID/PID; bảng VID/PID (TGT-19 §4) → kind; kiểm quyền mở (udev/driver) → driver_ok"], [], "none", '{}', "TC-80")
d("discover.probe", {}, {"probes": "arr<obj>! # kind, serial, fw, tool"}, ["probe-rs list, openocd -c 'adapter list' (sandbox), esptool --port … chip_id thăm dò, pymcuprog ping; hợp nhất theo serial; gợi ý cập nhật fw ST-Link cũ"], ["E4001"], "none", '{}', "ST-Link nhận đúng")
d("discover.chip_id", {"probe": "str!", "isa_hint": "str"}, {"identity": "obj! # method, raw, passport_match, confidence"}, ["Theo họ: Cortex-M đọc IDCODE (DP) + DBGMCU_IDCODE (STM32) qua probe-rs; AVR signature bytes qua avrdude -v; ESP esptool chip_id; PIC pymcuprog; RISC-V DTM idcode", "Đối chiếu bảng ID → part trong hộ chiếu/seed; không khớp → E4003 + leo thang"], ["E4002", "E4003"], "none", '{"probe":"stlink:0669FF…"}', "TC-80")
d("discover.board_match", {"evidence": "obj! # chip_id, bus_devices[], image?, bom?"}, {"candidates": "arr<obj>! # board_id, score, reasons[]"}, ["Điểm: chip khớp (5) + thiết bị I2C khớp BOM template (2/thiết bị) + ảnh (extract.image_board) (3) + tên board trong README (2); registry templates/boards; nhiều ứng viên điểm gần (Δ < 2) → ASK"], ["E3000"], "none", '{"evidence":{"chip_id":{"passport_match":"st.stm32f411ce"},"bus_devices":["0x68"]}}', "TC-82 BlackPill")
d("discover.bus_scan", {"bus": "enum:i2c|spi|onewire|can!", "target": "str!"}, {"devices": "arr<obj>! # addr|id, matched_part"}, ["Nạp firmware quét (BEN-21 firmware kiểm định có chế độ scan) hoặc probe RTT lệnh; đối chiếu địa chỉ với BOM/hộ chiếu part (address fact); R1 trên board lab"], ["E3000", "E4002"], "reflash_known_good", '{"bus":"i2c","target":"nucleo-f411"}', "0x68 → MPU6050")
d("discover.link_speed", {"kind": "enum:baud|swd|jtag|spi|i2c!", "target": "str!", "limit_fact": "str"}, {"chosen": "int!", "tried": "arr<arr<num>>!", "limit": "int!"}, ["baud: thử nấc [9600,19200,38400,57600,115200,230400,460800,921600] gửi/echo 1.000 khung (firmware kiểm định hoặc banner), đo tỷ lệ lỗi; chọn nấc cao nhất lỗi = 0; swd/jtag: probe-rs speed tăng dần 100 kHz→ giới hạn fact (mặc định 4 MHz) đọc IDCODE ×1.000; spi/i2c: đọc ID ngoại vi ×1.000; nấc vượt limit_fact → ASK", "Ghi target.yaml speeds; Discovery.link_speed"], ["E3000", "E4002"], "restore_config", '{"kind":"baud","target":"nucleo-f411"}', "TC-81")
d("discover.clock_measure", {"target": "str!"}, {"clocks": "obj! # sysclk, bus clocks measured vs configured"}, ["Firmware đo (toggle GPIO theo timer) + LA/probe timestamp → tần số; so fact clock/cấu hình RCC"], ["E4002"], "none", '{"target":"nucleo-f411"}', "Sai số < 1%")
d("discover.power", {"target": "str!"}, {"power": "obj! # vdd, idd, ok, warnings[]"}, ["Đọc từ probe hỗ trợ (ST-Link V3 VDD, PPK2, INA) hoặc firmware ADC VREFINT; so voltage_range fact → cảnh báo/chặn nạp"], ["E4002"], "none", '{"target":"nucleo-f411"}', "VDD 3,3 V ok; 5 V trên chip 3,3 → chặn")
d("discover.firmware_probe", {"port": "str!"}, {"firmware": "obj! # banner, version, bootloader, known_good_match"}, ["Mở serial (auto-baud), reset, đọc banner 2 s; so với chuỗi banner của artifact known-good (hash trong firmware); bootloader: DFU/UF2/esptool chế độ"], ["E4002"], "none", '{"port":"/dev/tty.usbmodem1"}', "Banner EIDE fw 0.3 nhận ra")
d("discover.network", {"subnet": "str", "services": "arr<str>"}, {"devices": "arr<obj>!"}, ["mDNS (_eide._tcp, _arduino._tcp, _http), quét OTA endpoint theo IP cấu hình; chỉ trong mạng lab (cấu hình) → ngoài → ASK"], ["E3000"], "none", '{}', "ESP32 mDNS hiện")
d("discover.env_hw", {}, {"report": "obj! # os, ports, drivers_missing[], permissions[], fixes[]"}, ["env.detect + kiểm udev/driver ký/quyền cổng; đề xuất lệnh sửa (sudo → ASK)"], [], "none", '{}', "Thiếu udev → fix gợi ý")
d("discover.auto_setup", {"discovery_id": "str!"}, {"target_config": "obj!", "path": "str!"}, ["Chip → ISA/adapter (TGT-19 bảng); probe → cfg openocd/probe-rs; cổng + baud từ link_speed; lab từ autonomy.yaml; ghi .eide/target.yaml (sao lưu cũ); ID không khớp → không ghi, E4003"], ["E4003"], "restore_config", '{"discovery_id":"dv_1"}', "TC-82 < 30 s")
